### ISSUE TITLE
Add GPIO Screen Support for Raspberry Pi

### ISSUE THREAD

**Issue by sachangregory** [hoobs-org/HOOBS#1]
Add Support for ADAFruit screens, Kuman 3.5 inch screens (what I have) and many other Raspberry Pi Screens.

https://www.amazon.com/Raspberry-Display-kuman-Interface-SC06/dp/B01CNJVG8K

**Comment by BobbySlope** [comment]
@mkellsy @askovi 
Will that be possible to give an video output to hdmi and gpio to show the ui?

**Comment by mkellsy** [comment]
The UI requires a browser. I could create an electron app with a UI that access the API. However I would like to save this for a later release.

**Comment by sachangregory** [comment]
That’s alright! I was just hoping it was possible

**Comment by mkellsy** [comment]
This will be part of a future project plan.
