### ISSUE TITLE
HOOBS 3.0.0 stuck on initialising page

### ISSUE THREAD

**Issue by grabson79** [hoobs-org/HOOBS#100]
I seem to be having the same issue as this one
[https://github.com/hoobs-org/HOOBS/issues/75](url) which remained unanswered as there was no response.

I logged via ssh I run the suggested commands, the results are below
[https://imgur.com/dp7z1h6](url)

Homebridge seems to be running fine in the background with all accessories available in HomeKit

**Comment by mkellsy** [comment]
@mkellsy
mkellsy 
commented 1 day ago
Can you post the results of these 2 commands; Assuming you are logged in ad the hoobs user.

ls -la ~/.hoobs/
hoobs

**Comment by mkellsy** [comment]
Run this command

```sh
sudo npm install -g --unsafe-perm --ignore-scripts @hoobs/hoobs
```

It will install an updated beta version.

**Comment by grabson79** [comment]
thanks mkellsy, this did not work and gave me the following error 
![IMG_0503](https://user-images.githubusercontent.com/54689833/64007068-6587fb00-cb0b-11e9-804f-3d80ac9da0b7.PNG)

but i run the command without "--ignore-scripts" and it worked, HOOBS updated and I can login now.

Cheers

**Comment by mkellsy** [comment]
I ment to remove "--ignore-scripts" typing on a phone.
