### ISSUE TITLE
System keep crashing / locking up

### ISSUE THREAD

**Issue by Litho1** [hoobs-org/HOOBS#1000]
**Description**

Please advise.  Just set up my system that I received as a Christmas gift.  1st Day out worked fine.  2nd day, it crashed.  Spent HOURS researching any sort of fix.   Took HOOBS apart and reloaded the software on the SD card.   Started working for 10 minutes and crashed again.  Will not allow me to login.

Please let me know how I can receive a replacement.  Loved it for the day it worked!!!

Error message I receive is: 

Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

**Version**
Please include the version of HOOBS you are using.
Don’t know... cant log in

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X ] No - New install

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Send an email to info@hoobs.org we can send you a replacement SD Card.
