### ISSUE TITLE
Removal of past accessories from cache

### ISSUE THREAD

**Issue by sfguyfor20** [hoobs-org/HOOBS#1003]
**Is your feature request related to a problem? Please describe.**
I have had the eufy-security plug-installed and have uninstalled it via the UI... however the doorbell is discovered is still coming up as an accessory... seems silly that there's no simple way to remove an accessory one doesn't use...

**Describe the solution you'd like**
I'd love to see accessories associated with a plug-in removed once the plug-in is removed

**Describe alternatives you've considered**

**Additional context**

**Comment by Sheldor81** [comment]
Ich habe genau das gleiche Problem.

Auf Homebridge mit dem plugin "config ui x" ist es ganz einfach möglich einzelne Geräte aus dem Cache zu löschen. Doch bei Hoobs habe ich leider immer noch keine Möglichkeit gefunden.

**Comment by LewisSpring** [comment]
Translation of @Sheldor81 for quick reference :)
> I have exactly the same problem.

> On Homebridge with the plugin "config ui x" it is very easy to delete individual devices from the cache. But unfortunately I still > haven't found an opportunity at Hoobs. .

I agree totally with a GUI or automated option, But even if the cache file was laid out line-by-line instead of one long line, that'd help a tonne.

Is it the plugin's responsibility to remove the cache entry?

**Comment by websnowtea** [comment]
moving to Homebridge! peace out HOOBS!!

**Comment by mkellsy** [comment]
HOOBS 4 has this ability
