### ISSUE TITLE
Unable to access Hoobs.local

### ISSUE THREAD

**Issue by OneManJ** [hoobs-org/HOOBS#1009]
After a couple of days I have not been able to access Hoobs. I have tried the suggestions of logging in as admin:

username: hoobs or hoobs.local or hoobsadmin
password: hoobsadmin

but to no avail. Any other ideas? I was able to confirm I can ping hoobs.local and get a reply.

Thanks

**Comment by EddieDSuza** [comment]
Were you able to resolve this issue ?
