### ISSUE TITLE
Terminal from System Tab to Config tab underneath Advanced Config

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#101]

**Comment by BobbySlope** [comment]
<img width="629" alt="Screenshot 2019-08-30 at 10 30 58" src="https://user-images.githubusercontent.com/50763727/64005801-573cdd80-cb11-11e9-8705-b7bc57ea28d5.png">
<img width="760" alt="Screenshot 2019-08-30 at 10 31 16" src="https://user-images.githubusercontent.com/50763727/64005802-573cdd80-cb11-11e9-8a00-f3840162437a.png">

**Comment by mkellsy** [comment]
It's part of the system. I will put it in the same place as UI-X. Terminal in the config is dangerous.

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.34
