### ISSUE TITLE
Unable to install homebridge-carwings

### ISSUE THREAD

**Issue by jsundgot** [hoobs-org/HOOBS#1012]
**Description**

Attempting to install homebridge-carwings plugin through search feature in HOOBS, but receiving the following error:

---

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/blandman/carwings.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-01-09T19_13_29_222Z-debug.log

Command failed. Please review log for details.

---

Following some reading (rarely use terminal and mostly unfamiliar with Linux), have unsuccessfully attempted to install both homebridge-carwings as well as homebridge-carwings-platform (latter not appearing in plugin search) using command npm install in dir usr/local/lib/node_modules. Receiving error message identical to above for both plugins.

Have located article https://www.reddit.com/r/HOOBS/comments/e64584/roborock_hoobs_certified_issues_installing/, which indicates that git is missing from HOOBS, and that installing git is inadvisable.

Article also appears to indicate that plugin homebridge-roborock was updated to remove git dependency, however uncertain whether such assistance is provided only for certified plugins and in this case must be carried out by plugin developer(s).

I would like to stay within the bounds established by HOOBS if possible rather than attempting to install git; any suggestions for how to proceed would be greatly appreciated.

**Plugin name**

homebridge-carwings, also homebridge-carwings-platform (latter not appearing in HOOBS Plugin search)

**Please report the issue to the plugin developer**

Preliminarily not reported to plugin developer as issue seems to be with HOOBS not supporting git.

**Version**

Running latest version of HOOBS at time of writing on Raspberry Pi 3 Model B. Homebridge version 1.2.5, Node.js version 14.15.4, NPM version 6.14.10.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**

- [ ] HOOBS Box
- [x] HOOBS SD Card, Raspberry Pi 3 Model B
- [ ] Custom Install

**Comment by EddieDSuza** [comment]
Use these commands to rebuild NPM 

`sudo npm uninstall -g @hoobs/hoobs`

`sudo npm install -g --unsafe-perm  @hoobs/hoobs`

`sudo reboot`

**Comment by jsundgot** [comment]
Hi Eddie,

Thank you for taking the time to reply, much appreciated. Attempted your instructions successfully without errors, but still receiving error message as follows when attempting to install homebridge-carwings from HOOBS Plugins UI:

---

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/blandman/carwings.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-01-22T09_58_45_912Z-debug.log

Command failed. Please review log for details.

---

Following the successful reinstallation of NPM, I was alerted that a .11 patch version was available (.10 was installed). When attempting to upgrade using npm install -g npm as instructed, I received the following error message:

---

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/hoobs/.npm/_cacache/index-v5/48/a3
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/home/hoobs/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-01-22T10_01_01_268Z-debug.log

---

Also attaching log files in case they may be relevant.

[2021-01-22T09_57_20_828Z-debug.log](https://github.com/hoobs-org/HOOBS/files/5855051/2021-01-22T09_57_20_828Z-debug.log)
[2021-01-22T09_58_45_912Z-debug.log](https://github.com/hoobs-org/HOOBS/files/5855052/2021-01-22T09_58_45_912Z-debug.log)
[2021-01-22T10_01_01_268Z-debug.log](https://github.com/hoobs-org/HOOBS/files/5855053/2021-01-22T10_01_01_268Z-debug.log)

**Comment by EddieDSuza** [comment]
Does the HOOBS instance return with no errors without the homebridge-carwings plugin ?

**Comment by jsundgot** [comment]
Not entirely sure if I understand what you mean by "return", but as far as I can tell from the logs there are no readily visible errors. HOOBS appears to run flawlessly both following a failed install of homebridge-carwings, following the NPM reinstall, and following a couple of manual reboots.

Incidentally, the homebridge-carwings plugin has not been installed previously. I have 5 other plugins (as well as Homebridge UI), 3 of which are HOOBS verified, and none of which are exhibiting any errors that I can tell.

**Comment by EddieDSuza** [comment]
The uninstall of the carvings plugin may have left some files in the cache and that's why you are seeing the error.

The only work around is - reflash the card and will fix the issue
