### ISSUE TITLE
Sonos ZP plugin error message

### ISSUE THREAD

**Issue by casperse** [hoobs-org/HOOBS#1013]
**Description**
I get the following error when loading the plugin

> 1/10/2021, 7:24:07 PM HOOBS listening on port 80.
> 1/10/2021, 7:24:09 PM Loaded plugin 'homebridge-camera-ffmpeg'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] The plugin "homebridge-zp" requires Node version of ^14.15.2 which does not satisfy the current Node version of v14.15.1. You may need to upgrade your installation of Node.
> 1/10/2021, 7:24:09 PM Loaded plugin 'homebridge-zp'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] Registering platform 'homebridge-zp.Lib'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] Registering platform 'homebridge-zp.ZP'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] Registering platform 'homebridge-zp.ZPS1'
> 1/10/2021, 7:24:09 PM Loading 2 platforms...
> 1/10/2021, 7:24:09 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...
> 1/10/2021, 7:24:09 PM [Sonos] Initializing ZP platform...
> 1/10/2021, 7:24:09 PM [Sonos] homebridge-zp v1.1.4, node v14.15.1, homebridge v1.1.7, homebridge-lib v4.8.4
> 1/10/2021, 7:24:09 PM [Sonos] warning: not using recommended node v14.15.2 LTS
> 1/10/2021, 7:24:09 PM [Sonos] warning: config.json: plugin_map: invalid key
> 1/10/2021, 7:24:09 PM [Camera FFmpeg] [Main Door] Configuring cached bridged accessory...
> 1/10/2021, 7:24:09 PM [Camera FFmpeg] [Driveway] Configuring cached bridged accessory...
> 1/10/2021, 7:24:09 PM Bridge is running on port 51826.
> 1/10/2021, 7:24:40 PM [Sonos] warning: no zone players found

**Expected behavoir**
Load and find my Sonos S2 system

**Plugin name**
HOOBS Certified: Zp
1.1.4 published 12/17/2020

**Version**
Latest one - wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts

Bridge Name | HOOBS
-- | --
HOOBS Version | 3.3.1
Node Version | 14.15.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No
Clean install

**Pervious version**
N/A
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install
Followed your excellent guide to install it on FEDORA and used your guide
Latest version of Fedora

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

```
> {
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISXXXXE4L",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "XX",
        "postal_code": "XXXX"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "XXX-XX-XXX",
        "username": "XX:XX:XX:XX:XX:XX"
    },
    "description": "Ultimative Bridge between all things in the Smart Home",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Main Door",
                    "videoConfig": {
                        "source": "-rtsp_transport http -i rtsp://192.168.0.1:7447/token",
                        "stillImageSource": "-i http://192.168.0.23/snap.jpeg",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 24,
                        "mapvideo": "0:1",
                        "mapaudio": "0:0",
                        "vcodec": "copy",
                        "acodec": "copy",
                        "packetSize": 188,
                        "encoderOptions": "-preset ultrafast",
                        "audio": false,
                        "debug": true
                    }
                },
                {
                    "name": "Driveway",
                    "manufacturer": "Ubiquiti",
                    "model": "UVC G4",
                    "motion": "true",
                    "doorbell": "true",
                    "videoConfig": {
                        "source": "-re -i rtsp://192.168.0.1:7447/token",
                        "stillImageSource": "-i http://192.168.0.20/snap.jpeg",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 24,
                        "vcodec": "libx264",
                        "mapvideo": "0:1",
                        "mapaudio": "0:0",
                        "audio": true,
                        "debug": true
                    }
                }
            ]
        },
        {
            "platform": "ZP",
            "plugin_map": {
                "plugin_name": "homebridge-zp"
            },
            "name": "Sonos",
            "service": "switch",
            "alarms": true,
            "excludeAirPlay": true,
            "forceS2": true,
            "brightness": true,
            "speakers": true
        }
    ]
}

```
**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

> 1/10/2021, 7:24:07 PM HOOBS listening on port 80.
> 1/10/2021, 7:24:09 PM Loaded plugin 'homebridge-camera-ffmpeg'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] The plugin "homebridge-zp" requires Node version of ^14.15.2 which does not satisfy the current Node version of v14.15.1. You may need to upgrade your installation of Node.
> 1/10/2021, 7:24:09 PM Loaded plugin 'homebridge-zp'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] Registering platform 'homebridge-zp.Lib'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] Registering platform 'homebridge-zp.ZP'
> 1/10/2021, 7:24:09 PM [1/10/2021, 7:24:09 PM] Registering platform 'homebridge-zp.ZPS1'
> 1/10/2021, 7:24:09 PM Loading 2 platforms...
> 1/10/2021, 7:24:09 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...
> 1/10/2021, 7:24:09 PM [Sonos] Initializing ZP platform...
> 1/10/2021, 7:24:09 PM [Sonos] homebridge-zp v1.1.4, node v14.15.1, homebridge v1.1.7, homebridge-lib v4.8.4
> 1/10/2021, 7:24:09 PM [Sonos] warning: not using recommended node v14.15.2 LTS
> 1/10/2021, 7:24:09 PM [Sonos] warning: config.json: plugin_map: invalid key
> 1/10/2021, 7:24:09 PM [Camera FFmpeg] [Main Door] Configuring cached bridged accessory...
> 1/10/2021, 7:24:09 PM [Camera FFmpeg] [Driveway] Configuring cached bridged accessory...
> 1/10/2021, 7:24:09 PM Bridge is running on port 51826.
> 1/10/2021, 7:24:40 PM [Sonos] warning: no zone players found
> 1/10/2021, 7:29:40 PM [Sonos] warning: no zone players found
> 1/10/2021, 7:34:40 PM [Sonos] warning: no zone players found
> 1/10/2021, 7:37:48 PM [Camera FFmpeg] [Main Door] Snapshot requested: 1280 x 720
> 1/10/2021, 7:37:48 PM [Camera FFmpeg] [Main Door] Sending snapshot: 1280 x 720
> 1/10/2021, 7:37:48 PM [Camera FFmpeg] [Main Door] Snapshot command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i http://192.168.0.23/snap.jpeg -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
> 1/10/2021, 7:37:48 PM [Camera FFmpeg] [Driveway] Snapshot requested: 1280 x 720
> 1/10/2021, 7:37:48 PM [Camera FFmpeg] [Driveway] Sending snapshot: 1280 x 720
> 1/10/2021, 7:37:48 PM [Camera FFmpeg] [Driveway] Snapshot command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -i http://192.168.0.20/snap.jpeg -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] Video stream requested: 1280 x 720, 30 fps, 299 kbps
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] Starting video stream: 640 x 360, 24 fps, 299 kbps
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] Stream command: /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg -re -i rtsp://192.168.0.1:7447/gg9vow5UljSE9p19 -map 0:1 -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -r 24 -f rawvideo -preset ultrafast -tune zerolatency -filter:v scale='min(640,iw)':'min(360,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -b:v 299k -payload_type 99 -ssrc 953368 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params vNsWlnwJYnNDOPQL+z1PTxMkC21zUOQZqk3GBUOq srtp://192.168.0.61:55339?rtcpport=55339&pkt_size=1316 -map 0:0 -codec:a libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -ac 1 -payload_type 110 -ssrc 1230134 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params jgwTC3Efg40Ka/hR76bPrkr+OjC/F3SlwRczjScJ srtp://192.168.0.61:58640?rtcpport=58640&pkt_size=188 -loglevel level+verbose
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info] ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   libavutil      56. 51.100 / 56. 51.100
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   libavcodec     58. 91.100 / 58. 91.100
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   libavformat    58. 45.100 / 58. 45.100
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   libavdevice    58. 10.100 / 58. 10.100
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   libavfilter     7. 85.100 /  7. 85.100
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   libswscale      5.  7.100 /  5.  7.100
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   libswresample   3.  7.100 /  3.  7.100
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [info]   libpostproc    55.  7.100 / 55.  7.100
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [tcp @ 0x55c5e80f4680] [verbose] Starting connection attempt to 192.168.0.1 port 7447
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [tcp @ 0x55c5e80f4680] [verbose] Successfully connected to 192.168.0.1 port 7447
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [rtsp @ 0x55c5e80f2300] [verbose] SDP:
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] v=0
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] o=- 1545 0 IN IP4 192.168.0.1
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] s=E063DAEF501B_2
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] u=www.evostream.com
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] e=contact@evostream.com
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] c=IN IP4 192.168.0.1
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] t=0 0
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=recvonly
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=control:*
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=range:npt=now-
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] m=audio 0 RTP/AVP 96
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=recvonly
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=rtpmap:96 mpeg4-generic/48000/1
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=control:trackID=1
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=fmtp:96 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1188; SizeLength=13; IndexLength=3; IndexDeltaLength=3;
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] m=video 0 RTP/AVP 97
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=recvonly
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=control:trackID=2
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=rtpmap:97 H264/90000
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] a=fmtp:97 profile-level-id=4d401e; packetization-mode=1; sprop-parameter-sets=Z01AHo2NQFAX/LgLcBAQFAAAD6AAAu4CdoIhGoA=,aO44gA==
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [rtsp @ 0x55c5e80f2300] [verbose] setting jitter buffer size to 500
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [rtsp @ 0x55c5e80f2300] 
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [verbose] 
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] setting jitter buffer size to 500
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] [h264 @ 0x55c5e80f9640] [verbose] Reinit context to 640x368, pix_fmt: yuvj420p
> 1/10/2021, 7:37:50 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info] Input #0, rtsp, from 'rtsp://192.168.0.1:7447/gg9vow5UljSE9p19':
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]   Metadata:
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]     title           : E063DAEF501B_2
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]   Duration: N/A, start: 0.000000, bitrate: N/A
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]     Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]     Stream #0:1: Video: h264 (Main), 1 reference frame, yuvj420p(pc, bt709, progressive, left), 640x360 (640x368) [SAR 1:1 DAR 16:9], 24 fps, 24.01 tbr, 90k tbn, 48 tbc
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info] Stream mapping:
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]   Stream #0:1 -> #0:0 (h264 (native) -> h264 (libx264))
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]   Stream #0:0 -> #1:0 (aac (native) -> aac (libfdk_aac))
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info] Press [q] to stop, [?] for help
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [graph_1_in_0_0 @ 0x55c5e8208780] [verbose] tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x4
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [format_out_1_0 @ 0x55c5e81d9080] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [verbose] auto-inserting filter 'auto_resampler_0' between the filter 'Parsed_anull_0' and the filter 'format_out_1_0'
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [auto_resampler_0 @ 0x55c5e820c4c0] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [verbose] ch:1 chl:mono fmt:fltp r:48000Hz -> ch:1 chl:mono fmt:s16 r:16000Hz
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info] Output #1, rtp, to 'srtp://192.168.0.61:58640?rtcpport=58640&pkt_size=188':
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]   Metadata:
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]     title           : E063DAEF501B_2
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]     encoder         : Lavf58.45.100
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]     Stream #1:0: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, delay 288, 24 kb/s
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]     Metadata:
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [info]       encoder         : Lavc58.91.100 libfdk_aac
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] [h264 @ 0x55c5e81a1100] [verbose] Reinit context to 640x368, pix_fmt: yuvj420p
> 1/10/2021, 7:37:51 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [libfdk_aac @ 0x55c5e8146fc0] [warning] Queue input is backward in time
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [Parsed_scale_0 @ 0x55c5e8176840] [verbose] w:min(640,iw) h:min(360,ih) flags:'bicubic' interl:0
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [Parsed_scale_1 @ 0x55c5e8212d80] [verbose] w:trunc(iw/2)*2 h:trunc(ih/2)*2 flags:'bicubic' interl:0
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [graph 0 input from stream 0:1 @ 0x55c5e83aa400] [verbose] w:640 h:360 pixfmt:yuvj420p tb:1/90000 fr:90000/3749 sar:1/1
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [Parsed_scale_0 @ 0x55c5e8176840] [verbose] w:640 h:360 fmt:yuvj420p sar:1/1 -> w:640 h:360 fmt:yuvj420p sar:1/1 flags:0x4
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [swscaler @ 0x55c5e8264c40] [warning] deprecated pixel format used, make sure you did set range correctly
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [Parsed_scale_1 @ 0x55c5e8212d80] [verbose] w:640 h:360 fmt:yuvj420p sar:1/1 -> w:640 h:360 fmt:yuv420p sar:1/1 flags:0x4
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [libx264 @ 0x55c5e816ff40] [info] using SAR=1/1
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [libx264 @ 0x55c5e816ff40] [info] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [libx264 @ 0x55c5e816ff40] [info] profile Constrained Baseline, level 3.0, 4:2:0, 8-bit
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] Output #0, rtp, to 'srtp://192.168.0.61:55339?rtcpport=55339&pkt_size=1316':
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info]   Metadata:
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info]     title           : E063DAEF501B_2
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info]     encoder         : Lavf58.45.100
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info]     Stream #0:0: Video: h264 (libx264), 1 reference frame, yuv420p(tv, left), 640x360 [SAR 1:1 DAR 16:9], q=-1--1, 299 kb/s, 24 fps, 90k tbn, 24 tbc
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info]     Metadata:
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info]       encoder         : Lavc58.91.100 libx264
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info]     Side data:
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info]       cpb: bitrate max/min/avg: 0/0/299000 buffer size: 0 vbv_delay: N/A
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [verbose] *** 2 dup!
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] 
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info] frame=    9 fps=0.0 q=29.0 size=      17kB time=00:00:00.50 bitrate= 284.6kbits/s dup=2 drop=0 speed=0.986x    
> 1/10/2021, 7:37:52 PM [Camera FFmpeg] [Driveway] [info] frame=   21 fps= 21 q=24.0 size=      29kB time=00:00:00.98 bitrate= 241.5kbits/s dup=2 drop=0 speed=0.966x    
> 1/10/2021, 7:37:53 PM [Camera FFmpeg] [Driveway] [info] frame=   28 fps= 18 q=23.0 size=      37kB time=00:00:01.49 bitrate= 203.1kbits/s dup=2 drop=0 speed=0.984x    
> 1/10/2021, 7:37:53 PM [Camera FFmpeg] [Driveway] [info] frame=   28 fps= 14 q=23.0 size=      37kB time=00:00:01.97 bitrate= 153.7kbits/s dup=2 drop=0 speed=0.978x    
> 1/10/2021, 7:37:54 PM [Camera FFmpeg] [Driveway] [info] frame=   28 fps= 11 q=23.0 size=      37kB time=00:00:02.48 bitrate= 122.1kbits/s dup=2 drop=0 speed=0.984x    
> 1/10/2021, 7:37:54 PM [Camera FFmpeg] [Driveway] [info] frame=   28 fps=9.3 q=23.0 size=      37kB time=00:00:02.99 bitrate= 101.2kbits/s dup=2 drop=0 speed=0.991x    
> 1/10/2021, 7:37:55 PM [Camera FFmpeg] [Driveway] [info] frame=   28 fps=7.9 q=23.0 size=      37kB time=00:00:03.51 bitrate=  86.5kbits/s dup=2 drop=0 speed=0.995x    
> 1/10/2021, 7:37:55 PM [Camera FFmpeg] [Driveway] [info] frame=   28 fps=7.0 q=23.0 size=      37kB time=00:00:03.99 bitrate=  76.1kbits/s dup=2 drop=0 speed=0.991x    
> 1/10/2021, 7:37:56 PM [Camera FFmpeg] [Driveway] [info] frame=   28 fps=6.2 q=23.0 size=      37kB time=00:00:04.50 bitrate=  67.4kbits/s dup=2 drop=0 speed=0.994x    
> 1/10/2021, 7:37:56 PM [Camera FFmpeg] [Driveway] [info] frame=   28 fps=5.6 q=23.0 size=      37kB time=00:00:04.98 bitrate=  60.9kbits/s dup=2 drop=0 speed=0.991x    
> 1/10/2021, 7:37:56 PM [Camera FFmpeg] [Driveway] Stopped video stream.
> 1/10/2021, 7:37:56 PM [Camera FFmpeg] [Driveway] FFmpeg exited with code: null and signal: SIGKILL (Expected)

**Additional context**

**Comment by bwp91** [comment]
> The plugin "homebridge-zp" requires Node version of ^14.15.2 which does not satisfy the current Node version of v14.15.1. You may need to upgrade your installation of Node.

This is just a warning about your node version. It is not an error and should not affect the functionality of the plugin at all.
