### ISSUE TITLE
Tplink Smarthome - Plugin has stopped working

### ISSUE THREAD

**Issue by bng22** [hoobs-org/HOOBS#1017]
**Description**
The Tplink Smarthome plug in worked perfectly until the last update in October 202, when it failed after update

**Expected behavoir**
The Plug in is hoobs certified and prior to update, automatically included TP Link Plugs (HS110) in Homekit, all worked excellently until the update and all icons disappeared from homekit.
**Plugin name**
Tplink Smarthome

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.
This Plug in is Hoobs certified, I find this a concern when it does not work.

**Version**
Please include the version of HOOBS you are using. 3.2.6

**Did you upgrade** - Plugin upgraded in October 2020
Please let us know if you upgraded from a previous version.
- [ ] Yes

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.

- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on. Raspberry Pi

- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
There is no config, the plug in automatically detects the TP Link items
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by bng22** [comment]
Has anyone from Hoobs got any form of answer, this update in December wiped out all my 4 TPLink plugs from Homekit, I would have hoped for a response

**Comment by jjdawgs84** [comment]
Having the same issue. I accidentally updated the plugin and it wiped my switches from HomeKit.
