### ISSUE TITLE
Upgraded to 3.3.2 Node still at 12.6.1

### ISSUE THREAD

**Issue by jackflem1** [hoobs-org/HOOBS#1019]
Just upgraded to V3.3.2 all is working fine. I noticed my Node Version is still at 12.6.1?

**Comment by bwp91** [comment]
I have just managed to update my version of node by running this command in the HOOBS terminal:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 14.15.4`

However I would only recommend this if you are confident with accessing your HOOBS instance via SSH as afterwards there might be a couple of commands you need to run to get things working again.

**Comment by jackflem1** [comment]
What would the additional commands I might need to run?

**Comment by mkellsy** [comment]
Node does not upgrade with HOOBS. You need to upgrade Node separately. This command will upgrade Node.
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node LTS
```

**Comment by Supermuls** [comment]
Great - Thanks…

Do I just paste this whole string into my terminal?

Please advise. 


Thanks again.. 

All the best,
-morty

**Comment by bwp91** [comment]
> What would the additional commands I might need to run?

Sometimes after node is updated the system needs rebuilding (via SSH as the web interface won't be available). The commands are (to be run separately)

```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by jackflem1** [comment]
Thanks bwp91,  I ran those two commands to rebuild and everything is back up with my Node at 14.15.4.

**Comment by mkellsy** [comment]
Run this in the terminal then reboot.
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```
It will do everything for you.

**Comment by Supermuls** [comment]
Thank you! 

I followed the instruction, and it made magic, however now I have a hard time re-install my ring plugin, as it didn’t function after the update?


Please advise. 



Best,

mp
