### ISSUE TITLE
UX: Plugin configuration as popup directly in plugins tab

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#102]
Users are confused about clicking on config plugin and landing in settings tab.
Can we use a popup to config the plugin related configuration directly in the plugins tab?

**Comment by BobbySlope** [comment]
<img width="1152" alt="Screenshot 2019-08-30 at 10 29 57" src="https://user-images.githubusercontent.com/50763727/64005691-28bf0280-cb11-11e9-81c6-d48a22530851.png">
<img width="659" alt="Screenshot 2019-08-30 at 10 29 41" src="https://user-images.githubusercontent.com/50763727/64005694-28bf0280-cb11-11e9-8f2b-d564c5082858.png">

**Comment by BobbySlope** [comment]
<img width="1192" alt="Screenshot 2019-08-30 at 10 32 07" src="https://user-images.githubusercontent.com/50763727/64005893-7dfb1400-cb11-11e9-8d49-9ac7f67e86d2.png">

**Comment by mkellsy** [comment]
This is a new UI. Some things change. They are just used to the old way. Give it a chance.

**Comment by BobbySlope** [comment]
is there a way to focus only on the plugin related parts?

**Comment by mkellsy** [comment]
That can be done. Microsoft blinks theirs.
