### ISSUE TITLE
Hoobs Log - Stop the auto scroll

### ISSUE THREAD

**Issue by palletodap** [hoobs-org/HOOBS#1022]
Hi Experts!

Im having a little frustration with the Hoobs live log and its auto scroll to the newest event.

Wouldn't it be possible to stop this from happening? Its almost impossible to use the log and see what's happening when i have a new line every half second :(

Hope someone has an solution for this.

- Palle

**Comment by EddieDSuza** [comment]
The Plugins do all the reporting of the logs - if theres a function in the plugin to disable the log reporting you can do it to stop it.

**Comment by palletodap** [comment]
> The Plugins do all the reporting of the logs - if theres a function in the plugin to disable the log reporting you can do it to stop it.

I want the logs, but the Hoobs log automatically scrolls to the newest line in the browser UI. That means that if you have a lot of plugins that is logging, you will not be able to see any of the logs, before there comes a new one.

**Comment by EddieDSuza** [comment]
The Logs are reported live by the plugins and the latest is always shown. Alternatively you can go to Help > backup > Logs - to scroll all the data
