### ISSUE TITLE
[Hue] config.json: warning: plugin_map: ignoring unknown key

### ISSUE THREAD

**Issue by benjamin7085** [hoobs-org/HOOBS#1023]
I'm having problems with my hue plugin and whatever I try I can't get it out. I hope someone can help me please.

I have a hue bridge 2.1 and a conbee stick 2.
I have followed this instruction: https://plugins.hoobs.org/plugin/homebridge-hue 

I have reinstalled hoobs several times as well as the hue plugin. The conbee stick is on my rasberry with the same address as my hoobs 192 ... 36: 1881 and 192 ... 36:80. The conbee stick works perfectly but doesn't get attached to hoobs.

With user I used both the key created by conbee and philips hue but with both it keeps showing the error message. Help what am I doing wrong...

This my log:

13-1-2021 15:27:34 HOOBS listening on port 80.
13-1-2021 15:27:40 Loaded plugin 'homebridge-hue'
13-1-2021 15:27:40 [1/13/2021, 7:27:40 AM] Registering platform 'homebridge-hue.Hue'
13-1-2021 15:27:40 Loading 1 platforms...
13-1-2021 15:27:40 [Hue] Initializing Hue platform...
13-1-2021 15:27:40 [Hue] config.json: warning: plugin_map: ignoring unknown key
13-1-2021 15:27:40 [Hue] homebridge-hue v0.12.11, node v14.15.4, homebridge v1.1.7
13-1-2021 15:27:40 [Hue] warning: not using recommended node version v14.15.1 LTS
13-1-2021 15:27:41 [Hue] warning: latest version: homebridge-hue v0.12.14
13-1-2021 15:27:41 [Hue] searching bridges and gateways
13-1-2021 15:27:46 [Hue] Bency-DECONZ: dresden elektronik deCONZ gateway v2.7.1, api v1.16.0
13-1-2021 15:27:46 [Hue] Bency-DECONZ: dresden elektronik deCONZ gateway v2.7.1, api v1.16.0
13-1-2021 15:27:46 [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1942135050, api v1.42.0
13-1-2021 15:27:46 [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.41.0
13-1-2021 15:27:46 [Hue] Bency-DECONZ: 1 accessories
13-1-2021 15:27:46 [Hue] Bency-DECONZ: 1 accessories
13-1-2021 15:27:46 [Hue] Philips hue: bridge request 1: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:27:46 [Hue] Philips hue: bridge request 1: error 101 link button not pressed
13-1-2021 15:27:46 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
13-1-2021 15:27:51 [Hue] request 1: GET /config
13-1-2021 15:27:51 [Hue] 172.30.33.1: timeout after 5 seconds
13-1-2021 15:27:51 [Hue] 172.***.***.1: 172.30.33.1: timeout after 5 seconds - retrying in 15s
13-1-2021 15:28:15 [Hue] Philips hue: bridge request 2: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:28:15 [Hue] Philips hue: bridge request 2: error 101 link button not pressed
13-1-2021 15:28:15 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
13-1-2021 15:28:25 [Hue] request 1: GET /config
13-1-2021 15:28:25 [Hue] 172.30.33.1: timeout after 5 seconds
13-1-2021 15:28:25 [Hue] 172.***.***.1: 172.30.33.1: timeout after 5 seconds - retrying in 15s
13-1-2021 15:28:30 [Hue] Philips hue: bridge request 3: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:28:30 [Hue] Philips hue: bridge request 3: error 101 link button not pressed
13-1-2021 15:28:30 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
13-1-2021 15:28:45 [Hue] request 1: GET /config
13-1-2021 15:28:45 [Hue] 172.30.33.1: timeout after 5 seconds
13-1-2021 15:28:45 [Hue] 172.***.***.1: 172.30.33.1: timeout after 5 seconds - retrying in 15s
13-1-2021 15:28:45 [Hue] Philips hue: bridge request 4: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:28:45 [Hue] Philips hue: bridge request 4: error 101 link button not pressed
13-1-2021 15:28:45 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
13-1-2021 15:29:00 [Hue] Philips hue: bridge request 5: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:29:00 [Hue] Philips hue: bridge request 5: error 101 link button not pressed
13-1-2021 15:29:00 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
13-1-2021 15:29:05 [Hue] request 1: GET /config
13-1-2021 15:29:05 [Hue] 172.30.33.1: timeout after 5 seconds
13-1-2021 15:29:05 [Hue] 172.***.***.1: 172.30.33.1: timeout after 5 seconds - retrying in 15s
13-1-2021 15:29:15 [Hue] Philips hue: bridge request 6: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:29:15 [Hue] Philips hue: bridge request 6: error 101 link button not pressed
13-1-2021 15:29:15 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
13-1-2021 15:29:25 [Hue] request 1: GET /config
13-1-2021 15:29:25 [Hue] 172.30.33.1: timeout after 5 seconds
13-1-2021 15:29:25 [Hue] 172.***.***.1: 172.30.33.1: timeout after 5 seconds - retrying in 15s
13-1-2021 15:29:30 [Hue] Philips hue: bridge request 7: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:29:30 [Hue] Philips hue: bridge request 7: error 101 link button not pressed
13-1-2021 15:29:30 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
13-1-2021 15:29:45 [Hue] request 1: GET /config
13-1-2021 15:29:45 [Hue] 172.30.33.1: timeout after 5 seconds
13-1-2021 15:29:45 [Hue] 172.***.***.1: 172.30.33.1: timeout after 5 seconds - retrying in 15s
13-1-2021 15:29:45 [Hue] Philips hue: bridge request 8: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:29:45 [Hue] Philips hue: bridge request 8: error 101 link button not pressed
13-1-2021 15:29:45 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
13-1-2021 15:30:00 [Hue] Philips hue: bridge request 9: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:30:00 [Hue] Philips hue: bridge request 9: error 101 link button not pressed
13-1-2021 15:30:00 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
13-1-2021 15:30:05 [Hue] request 1: GET /config
13-1-2021 15:30:05 [Hue] 172.30.33.1: timeout after 5 seconds
13-1-2021 15:30:05 [Hue] 172.***.***.1: 172.30.33.1: timeout after 5 seconds - retrying in 15s
13-1-2021 15:30:15 [Hue] Philips hue: bridge request 10: POST / {"devicetype":"homebridge-hue#hoobs"}
13-1-2021 15:30:15 [Hue] Philips hue: bridge request 10: error 101 link button not pressed
13-1-2021 15:30:15 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s

**Comment by mkellsy** [comment]
It doesn't hurt anything. We add that so we can map a config entry to a plugin without having to have Homebridge running.

This will go away in our next major release

**Comment by benjamin7085** [comment]
> It doesn't hurt anything. We add that so we can map a config entry to a plugin without having to have Homebridge running.
> 
> 
> 
> This will go away in our next major release

Thank you!

Can you indicate when? Otherwise I have to come up with something else.

**Comment by mkellsy** [comment]
We are aiming for a March release.
