### ISSUE TITLE
Unifi Protect plugin shows to many cameras?

### ISSUE THREAD

**Issue by casperse** [hoobs-org/HOOBS#1024]
**Description**
I had this working in Homebridge, same settings in HOOBS shows a string of cameras?

Homebridge:
![image](https://user-images.githubusercontent.com/2026859/104614802-ddb37a00-5688-11eb-824a-384a5f98bef5.png)

HOOBS:
![image](https://user-images.githubusercontent.com/2026859/104614939-020f5680-5689-11eb-9211-9e25102038a4.png)

**Expected behavoir**
Only show the two cameras

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.
![image](https://user-images.githubusercontent.com/2026859/104615075-279c6000-5689-11eb-90fb-5ccc186ea928.png)

**Version**

Bridge Name | HOOBS
-- | --
HOOBS Version | 3.3.2
Node Version | 14.15.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

Platform | linux
-- | --
Distro | Fedora
Release | 33
Codename | Server Edition
Kernel | 5.10.6-200.fc33.x86_64
Arch | x64

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

>         {
            "platform": "UniFi Protect",
            "plugin_map": {
                "plugin_name": "homebridge-unifi-protect"
            },
            "controllers": [
                {
                    "address": "192.168.X.X",
                    "username": "USERNAME",
                    "password": "PASSWORD"
                }
            ],
            "options": [
                "Disable.Stream.High"
            ],
            "verboseFfmpeg": false,
            "motionDuration": 10
        }

**Additional context**

**Comment by casperse** [comment]
I guess this is a HOOBS problem?

**Comment by askovi** [comment]
The unsupported cards you see are additional services of the camera that were discovered. These will be supported in the next major update - HOOBS 4.
