### ISSUE TITLE
Updated Node Cannot Login Hoobs.local

### ISSUE THREAD

**Issue by DaDD65** [hoobs-org/HOOBS#1025]
**Description**
Began having issues with the Ring plugin, devices were returning connection refused in the logs.  Was advised by plugin author to update to node 14 to solve the issue.  Updated within the interface via terminal.  It rebooted and hung a the orange screen for over half hour.  Closed and tried to open the interface, connection refused. 
Tried the following commands as suggested after a node update using ssh via putty.

udo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs

Install failed.  How do I fix that?
npm ERR! code EIO
npm ERR! syscall open
npm ERR! path /root/.npm/_cacache/index-v5/b8/d1/89dcac48f3dbb6abc2b159a4f9199a5f54e3cf5d155dc8b918d44d1efd74
npm ERR! errno -5
npm ERR! EIO: i/o error, open '/root/.npm/_cacache/index-v5/b8/d1/89dcac48f3dbb6abc2b159a4f9199a5f54e3cf5d155dc8b918d44d1efd74'

**Version**
Please include the version of HOOBS you are using.
3.3.2
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Ring
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by 6MH89F3j** [comment]
I'm having the exact same issue. Do you find a workaround yet?

**Comment by 6MH89F3j** [comment]
Ahh, I should have kept reading through the issues before posting. I ended up finding this and it worked for me. SSH in and run the following commands one after another:

sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs

**Comment by DaDD65** [comment]
> Ahh, I should have kept reading through the issues before posting. I ended up finding this and it worked for me. SSH in and run the following commands one after another:
> 
> sudo npm uninstall -g @hoobs/hoobs
> sudo npm install -g --unsafe-perm @hoobs/hoobs

Yep found that too.  Didn't work for me. I've tried everything I could and it's still dead in the water.

**Comment by DaDD65** [comment]
Got it back up.  Long process.  Removed the sd card, downloaded the image from hoobs.org, formatted and applied the image.  Box was not accessible, locally or ssh.  Tried a number of times.  Figured it was the card and asked Hoobs for a replacement.  Then I read somewhere to use the card formatter form sdcard.org.  Did that, applied the image with balenaEtcher, which it seems typically fails on validation.  Card back in and Hoobs was back up and accessible.  Still not sure it isn't the card.  One thing though the node showed as 14.15.1, so it was updated.  I'm unclear where data is stored?  Is everything on the card?  Anything on the board itself?  It was my update of the node that started this mess.  It appeared successful, but was not able to see the box after.
