### ISSUE TITLE
ISY accessories not showing up on HOOBS

### ISSUE THREAD

**Issue by stuhrd** [hoobs-org/HOOBS#1027]
I am using the homebridge-ISY plugin and it seems to find all my devices. However, under the accessories tab there are no devices. I have attached the config and logs. Thanks in advance.
[config.txt](https://github.com/hoobs-org/HOOBS/files/5816721/config.txt)
[logs.txt](https://github.com/hoobs-org/HOOBS/files/5816722/logs.txt)

**Comment by ksdennis** [comment]
I was having the same problem.  On a lark, I removed the check from the "Exclude" checkbox in the "Device List (Optional) section of the Homebridge ISY settings (I left the "Filter Type" field blank).  This solved my problem and I can see all the devices and scenes in the Accessories tab now.  This seems counterintuitive, especially as the checkbox is checked by default, but it seems to have excluded everything when checked.
