### ISSUE TITLE
Can't access Hoobs on the web, tried to reset over ssh, didn't work

### ISSUE THREAD

**Issue by ndpatel1280** [hoobs-org/HOOBS#1029]
**Description**
Hoobs stopped responding on my network, I tried to factory reset it in the web UI. It's now unaccessible on the web, I can ssh into the box at hoobs.local and tried to reset it, nothing seems to be working.

**Version**
3.3.1 I think

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
Whatever it shipped with - 3.something

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Ring, gsh, Nest

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
can't access logs, config, etc:(

```

**Additional context**
It was working fine for weeks with no issue, and then got wonky. I also reset the Eero and whitelisted npmjs.com but that has not helped any issues.

**Comment by EddieDSuza** [comment]
can you log in via ssh and paste the below line. 

`sudo hoobs service log`

Paste the output here

**Comment by hirsch85** [comment]
Started HOOBS.
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1284:19)
    at listenInCluster (net.js:1349:12)
    at Server.listen (net.js:1437:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 322.

**Comment by EddieDSuza** [comment]
that's a permission denied on port 80 issue. This command will fix it:

`sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`

**Comment by ndpatel1280** [comment]
sudo: hoobs: command not found

**Comment by EddieDSuza** [comment]
You'll need to reflash the SD card that's in the box to fix the issue - here is the [link](https://github.com/hoobs-org/hoobs-build/releases/download/v3.3.2/HOOBS-3.3.2-ARM7.zip)

**Comment by ndpatel1280** [comment]
I ended up opening the box and reflashing the card -- importantly, it didn't work until I did a full reformat of the card with the SD Card tool: https://www.sdcard.org/downloads/formatter/
