### ISSUE TITLE
Move System Update Check to Config Screen

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#103]
Users don't get the point to update there, they search it in settings tab

**Comment by BobbySlope** [comment]
<img width="1160" alt="Screenshot 2019-08-30 at 10 28 49" src="https://user-images.githubusercontent.com/50763727/64005594-00370880-cb11-11e9-81ff-6042acafc291.png">
<img width="804" alt="Screenshot 2019-08-30 at 10 28 41" src="https://user-images.githubusercontent.com/50763727/64005595-00370880-cb11-11e9-9c4f-2c229e63f4f8.png">

**Comment by mkellsy** [comment]
On you phone the system update is either under about phone or system.

**Comment by mkellsy** [comment]
I think having an update button in the config screen could lead to config file corruption.

1. User changes config
2. User doesn't Save config
3. User clicks Upgrade

If the config changes are to fix something before an upgrade, it could put the system is a state of flux. Updates and Configs do not belong together.
