### ISSUE TITLE
Can not Access HOOBs in a box

### ISSUE THREAD

**Issue by sgodfrey2000** [hoobs-org/HOOBS#1032]
**Description**
Getting error in browser, "Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

**Version**
Do not can not access

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
No
**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by sgodfrey2000** [comment]
Also notice when I use http://hoobs, the link gets changed to http://attlocal.net/xslt?PAGE=HURL00

**Comment by hbb88** [comment]
Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html

I keep losing connection to my HOOBS. Error message up appears when I try and access hoobs/local. Seems to resolve itself when I unplug my HOOBS and plug back in. Any info on this issue?

**Comment by EddieDSuza** [comment]
Login via ssh with user: hoobs and password: hoobsadmin
On MacOS use the Terminal app and type: ssh hoobs@hoobs.local
Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin
On Windows, use Putty with the same credentials as above.

Then run these commands in sequence:
`sudo npm uninstall -g @hoobs/hoobs`

`sudo npm install -g --unsafe-perm @hoobs/hoobs`

`sudo reboot`
