### ISSUE TITLE
Unable to login to Hoobs.local

### ISSUE THREAD

**Issue by Peltier36** [hoobs-org/HOOBS#1035]
**Description**
I'm unable to get into hoobs.local. I downloaded a plugin and the bridge stopped working. I hit "reboot device" in attempt to get the homekit bridge back up and running to no avail. The system now seems to be bricked as i've tried other sudo actions that i've seen here and those have not worked either. Please help as this is controlling all of my smart home. 

**Version**
unsure since i've only had the HOOBs device for a few weeks 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
"requireStack: [
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/settle.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/adapters/http.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/defaults.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/dispatchRequest.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/Axios.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/axios.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/index.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/server.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/user.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
  ]
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 91.
Stopped HOOBS.
Started HOOBS.
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module './createError'
Require stack:
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/settle.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/adapters/http.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/defaults.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/dispatchRequest.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/Axios.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/axios.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/server.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/user.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/api.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/settle.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/adapters/http.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/settle.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/adapters/http.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/defaults.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/dispatchRequest.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/core/Axios.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/lib/axios.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/axios/index.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/server.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/user.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
  ]
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.



**Additional context**
Add any other context about the problem here.

**Comment by DaDD65** [comment]
Not sure if this will help but I had a similar experience this week updating the node to 14 after the Ring plugin errored.  This was my way to get it back.  Only had the box a short time so not an issue to put the few plugin I had back.  Box is easy to open.
https://github.com/hoobs-org/HOOBS/issues/1025#issuecomment-761587072

**Comment by BobbySlope** [comment]
Please reach out to info@hoobs.org, so we can schedule an remote desktop session with you

Regards bobby@hoobs.org

**Comment by Peltier36** [comment]
I have and i have not heard back from that email group.

**Comment by Peltier36** [comment]
@DaDD65, i don't have a way to plug the sd card into my MAC...

**Comment by Peltier36** [comment]
@bobbySlope, I've reached out to info.hoobs.org and have not heard back.

**Comment by BobbySlope** [comment]
Please send again, cant find your email in the inbox

**Comment by DaDD65** [comment]
> @DaDD65, i don't have a way to plug the sd card into my MAC...
I got one of these.
https://www.amazon.ca/gp/product/B06ZYXR7DL/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

**Comment by Peltier36** [comment]
@bobbySlope I've resent the email again as of about 40 minutes ago with subject line "HOOBs less than one month old" from apost****k**3@gmail.com

**Comment by Peltier36** [comment]
@bobbySlope i still have yet to hear back. Do i need to send another email?

**Comment by Peltier36** [comment]
any idea how long i should continue to wait on a response from the HOOBs team?

**Comment by DaDD65** [comment]
I emailed them 5 days ago when my similar issue was happening, but got no response.  You are better off looking for solutions in the Hoobs facebook or reddit site.  I formatted and stated over.
