### ISSUE TITLE
Newly Purchases SD Card Not Functioning 

### ISSUE THREAD

**Issue by dpeterson329** [hoobs-org/HOOBS#1036]
I just recurved my new Hoobs SD card. It does not function when inserting into Rhaspberry Pi not does a PC detect it when plugging into my laptop. Completely non-functional.

**Comment by BobbySlope** [comment]
Please reach out via email to info@hoobs.org and provide the invoice, so we can send an replacement card. 

Regards Bobby@hoobs.org
