### ISSUE TITLE
Flash light and return to previous state?

### ISSUE THREAD

**Issue by Maykel1969** [hoobs-org/HOOBS#1038]
I’ve been searching for a solution in Hoobs and in plugins but I found nothing. And I think I’m not the only one looking for this option.
At the moment I’ve setup an automation where a group of light flash red 3 times when someone approaches my front door. After this the lights go back to a preselected scene.
But for every possible scene I need to setup fake switches to remember the active scene which makes it very complex to add a scene.
Isn’t there a way to store the previous color, intensity and state so after the flashing you can simply restore this situation?
The is an app called “ signal for homekit” that can do part of this trick but it’s way to complex.
Is there a plugin that can do this??

**Comment by mkellsy** [comment]
I am not aware of a plugin that does this. You may need to modify homebridge-dummy to store the current state.

**Comment by Maykel1969** [comment]
I use a dummy switch for every scene to remember the state before flashing.
But I would like to store the individual state of every light. This is much easier and even works if someone changed the brightness/color of a single bulb.
Unfortunately you can not store these values in automations...

**Comment by Maykel1969** [comment]
I found the app "Signals for Homekit" which can flash lights and go back to the original state.
Another app is not what I'm looking for and this is way more complicated than the simpel thing I want.
But for some reason they can do this trick, is there any Hoobs plugin that can do the same (simple setup)??

**Comment by mkellsy** [comment]
I don't want to leak too much info here.

The reason why (I think) there is no plugin that supports this use case is, storing a previous state of an accessory requires an on change event. Homebridge doesn't have this outside a plugin. So it is a tough problem to solve, ie: to track accessories from another accessory.

The good news is HOOBS has an on change event. It's how the accessories page updates. This is getting better in out next major release.

We also have a project in the descovery phase, that allows creating automatization flows within HOOBS. I will consider this use case when developing this feature.

**Comment by Maykel1969** [comment]
Thanks for the update.

My simpel usecase is: I want to flash some of the lights in my house red when motion is detected.
After this flash I want to go back to the light settings before the flash. Sounds simple but hard to achieve.
