### ISSUE TITLE
UX: move system info to ... header menu

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#104]
delete on main menu and add between about and help

**Comment by BobbySlope** [comment]
<img width="528" alt="Screenshot 2019-08-30 at 10 27 43" src="https://user-images.githubusercontent.com/50763727/64005504-da116880-cb10-11e9-932b-c9b34aae629c.png">
<img width="185" alt="Screenshot 2019-08-30 at 10 27 27" src="https://user-images.githubusercontent.com/50763727/64005505-da116880-cb10-11e9-92b0-e4fb518f4a9a.png">

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.34
