### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by awdpro** [hoobs-org/HOOBS#1040]
**DI have a HOOBs bridge that I’m trying to update from 3.3.1 to 3.3.2.  Doing this because for the past two weeks my box has been going offline and I have to remove power cable to reboot it.  After trying the update 4 times last night it keeps giving me an error.  After this I have to go and unplug the device to reboot.  Upon doing so the last time it is still stuck on version 3.3.1 but the dashboard screen is now blank.  I have my device directly connected to my router via ethernet.  Today I was able to update to 3.3.2 however my dashboard is still blank but all other Tabs work properly.  I did notice that I was getting the error message below in my logs.  Please let me know how to fix these issues.  Thanks in advance.

1/19/2021, 8:03:21 PM - (node:28094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpaired listeners added to [Bridge]. Use emitter.setMaxListeners() to increase limit
1/19/2021, 8:03:21 PM - (Use `node --trace-warnings ...` to show where the warning was created)

**Comment by EddieDSuza** [comment]
Can you reboot server and post the logs here
