### ISSUE TITLE
No control of Shelly RGBW2 via HOOBS Web-Interface

### ISSUE THREAD

**Issue by apartmedia** [hoobs-org/HOOBS#1042]
**Description**
It‘s not possible to control a Shelly RGBW2 from the HOOBS Web-Interface (outside HomeKit). With the Home App everything is working. Also controlling other Shelly devices does work (1, 1PM, 2.5, Dimmer2). But with RGBW2 trying to switch it on via Hoobs devices page does nothing.

**Expected behavoir**
I should be able to control the 4 channels of a RGBW2 device also from HOOBS web UI.

**Plugin name**
homebridge-shelly

**Please report the issue to the plugin developer**
https://github.com/alexryd/homebridge-shelly/issues/243

**Version**
3.3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes

**Pervious version**
3.3.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS SD Card

**Post your config**
```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "",
        "temp_units": "celsius",
        "country_code": "",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "",
        "username": ""
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-shelly",
        "homebridge-magichome-dynamic-platform",
        "homebridge-alexa"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Shelly",
            "plugin_map": {
                "plugin_name": "homebridge-shelly"
            },
            "name": "Shelly",
            "admin": {
                "enabled": false
            },
            "devices": [
                {
                    "id": "xxxxxx",
                    "name": "Wohnzimmer Spot Balkon"
                },
                {
                    "id": "xxxxxx",
                    "name": "Esszimmer Spot Fenster"
                }
            ],
            "password": "",
            "username": ""
        },
        {
            "platform": "homebridge-magichome-dynamic-platform",
            "plugin_map": {
                "plugin_name": "homebridge-magichome-dynamic-platform"
            },
            "pruning": {
                "pruneMissingCachedAccessories": false,
                "restartsBeforeMissingAccessoriesPruned": 3,
                "pruneAllAccessoriesNextRestart": false
            },
            "whiteEffects": {
                "simultaniousDevicesColorWhite": true,
                "colorWhiteThreshold": 10,
                "colorWhiteThresholdSimultaniousDevices": 50,
                "colorOffThresholdSimultaniousDevices": 5
            },
            "deviceManagement": {
                "blacklistOrWhitelist": "blacklist"
            },
            "advancedOptions": {
                "namesWithMacAddress": true
            }
        },
        {
            "platform": "Alexa",
            "plugin_map": {
                "plugin_name": "homebridge-alexa"
            },
            "name": "Alexa",
            "routines": false,
            "blind": true,
            "door": false,
            "debug": false,
            "deviceListHandling": "deny",
            "deviceList": [
                "Strip xxxxxx",
                "Strip xxxxxx"
            ],
            "username": "",
            "password": ""
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
```

**Comment by EddieDSuza** [comment]
Currently the HOOBS UI doesn't have this functionality. You will need to use the Home app.

**Comment by apartmedia** [comment]
What do you mean exactly?
Is your statement about this missing functionality referring only to Shelly RGBW2?
I ask because I can control other Shellies via the HOOBS UI (like Dimmer, 1PM, 2.5 etc) just not the RGBW2. Although I get an icon in HOOBS for controlling the RGBW2 and it offers a color wheel also. So it kinda recognizes it and knows about it’s different color features. But the UI control simply doesn‘t do anything. Is this exspected?

![2DD27110-EEAB-4377-A420-BA70EFF14737](https://user-images.githubusercontent.com/17024592/105619195-86cc4400-5df0-11eb-8846-bffbb2ae1d2a.jpeg)
![86A4829E-5606-478E-9535-94E1B0F4A6ED](https://user-images.githubusercontent.com/17024592/105619196-87fd7100-5df0-11eb-923b-51a1913bef7f.jpeg)
