### ISSUE TITLE
How to get HomematicIP running?

### ISSUE THREAD

**Issue by MathiasDiessner** [hoobs-org/HOOBS#1043]
Im a bit new to this: how do I start the service HomematicIP in hoobs after I installed it. I've put the ID of the accespoint in, but nothing happens. Is there a thing I need to do to start it manually? m8383@mail(dot)de

**Comment by EddieDSuza** [comment]
You will also need to add the API authentication token. Here is the guide to the [plugin](https://plugins.hoobs.org/plugin/homebridge-homematicip)

**Comment by MathiasDiessner** [comment]
It says I don't need it in the first place. It should say: press blue button etc... But it doesn't show up....

**Comment by MathiasDiessner** [comment]
{
  "accessories" : [

  ],
  "bridge" : {
    "name" : "HOOBS",
    "pin" : "031-45-154",
    "port" : 51826,
    "username" : "DE:27:38:08:FB:D6"
  },
  "client" : {
    "country_code" : "DE",
    "default_route" : "status",
    "inactive_logoff" : 30,
    "locale" : "de",
    "postal_code" : "23562",
    "temp_units" : "celsius",
    "theme" : "hoobs-light"
  },
  "description" : "",
  "platforms" : [
    {
      "platform" : "Ring",
      "plugin_map" : {
        "plugin_name" : "homebridge-ring"
      },
      "refreshToken" : "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTEyNjczOTAsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6Mzg5ODQ5MjYsInJuZCI6InVHbGJlU1RyNi04TzJRIiwic2Vzc2lvbl9pZCI6IjIzMmY4ZmQ3LWM2NzItNDVkNC05OTIwLTJlOTJlYjllYzA3MiIsInR5cGUiOiJyZWZyZXNoLXRva2VuIn0.aUjSo9nUlO6FWD7z3M2Nr6d7e4JvaVTJXlfd0dcJZLTcpjNiC6w-MRuhguMs_lIAyH_CzlxrYyYxcpQPXrtXtQ"
    },
    {
      "access_point" : "3014F711A00003DA4991D49B",
      "name" : "Mein Zuhause",
      "platform" : "HomematicIP",
      "plugin_map" : {
        "plugin_name" : "homebridge-homematicip"
      }
    }
  ],
  "ports" : {

  },
  "server" : {
    "autostart" : 0,
    "home_setup_id" : "X-HM://0023ISYWYJC9I",
    "origin" : "*",
    "polling_seconds" : 5,
    "port" : 80
  },
  "system" : "hoobs"
}

**Comment by MathiasDiessner** [comment]
{
  "access_point" : "3014F711A00003DA4991D49B",
  "name" : "Mein Zuhause",
  "platform" : "HomematicIP",
  "plugin_map" : {
    "plugin_name" : "homebridge-homematicip"
  }
}

**Comment by EddieDSuza** [comment]
Restart the Server and if the issue still persist with the plugin - please contact the developer.
