### ISSUE TITLE
HOOBS HELP cannot see UI

### ISSUE THREAD

**Issue by med813** [hoobs-org/HOOBS#1044]
I just purchased the HOOBS put of the box and after getting ready to setup and add plugins i must have changed the port number on my device and now cannot login to see the UI to make changes. Wifi cannot find the device nor can i see it via ethernet connection. 

Can I restore it to factory settings and if so...how?

**Comment by EddieDSuza** [comment]
Login via ssh with user: hoobs and password: hoobsadmin
On MacOS use the Terminal app and type: ssh hoobs@hoobs.local
Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin
On Windows, use Putty with the same credentials as above.

Then run this command to reset the HOOBS Box:
`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset`

**Comment by bmwmteknik** [comment]
comment
