### ISSUE TITLE
Hoobs.local error:  Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

### ISSUE THREAD

**Issue by mjudson64** [hoobs-org/HOOBS#1046]
I've got the subject error and I have no idea what to do.  I'm on Mac Big Sir and I did not upgrade from a previous hoops...have hoobs box

**Comment by EddieDSuza** [comment]
follow this [link](https://github.com/hoobs-org/HOOBS/issues/932#issuecomment-737012217) to fix the issue

**Comment by mjudson64** [comment]
I followed the link and my terminal said the following when I opened it up:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.

When I typed in ssh hoobs@hoobs.local <mailto:hoobs@hoobs.local>

But I didn’t get anything that I could answer yes to.  It just said "kex_exchange_identification: read: Connection reset by peer”

Then I thought I need to update the account to zsh, so I typed in chi -s /bin/zsh; it asked for a password, but wouldn’t let me type in anything.  

I’m at a loss.

**Comment by mjudson64** [comment]
I was told this is a stale issue; however, when I followed the suggested link in my Mac OS terminal app (ssh hoobs@hoobs.local), I got the following: 

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.

I typed in ssh hoobs@hoobs.local, but it didn't give me a certificate key to say yes to.  It just said "kex_exchange_identification: read: Connection reset by peer”

Then I thought I need to update the account to zsh, so I typed in chi -s /bin/zsh; it asked for a password, but wouldn’t let me type in anything.  

I’m at a loss.
