### ISSUE TITLE
Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data

### ISSUE THREAD

**Issue by Poppi1231** [hoobs-org/HOOBS#1047]
**Description**
Since yesterday (update hoobs and installation of the Hue-Deconz plugin), I can't start my service anymore.

**Version**
Version 3.3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
Dont, knoe

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Apple Home
Alexa
Dummy Switch
Hue
Meross
Shelly
Yeelight

**Post your config**
{
    "server": {
        "port": 80,
        "autostart": 0,
        "home_setup_id": "X-HM://002ISYWY295A",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "inactive_logoff": 30,
        "locale": "de",
        "postal_code": "",
        "theme": "hoobs-light",
        "country_code": "DE",
        "temp_units": "celsius",
        "default_route": "status"
    },
    "bridge": {
        "port": 51827,
        "pin": "****",
        "username": "***",
        "name": "HOOBS"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "yeelight",
            "plugin_map": {
                "plugin_name": "homebridge-yeelight-wifi"
            }
        },
        {
            "platform": "Shelly",
            "plugin_map": {
                "plugin_name": "homebridge-shelly"
            },
            "name": "Shelly",
            "admin": {
                "enabled": false
            },
            "username": "*****t",
            "password": "****",
            "staleTimeout": 30
        },
        {
            "platform": "Alexa",
            "plugin_map": {
                "plugin_name": "homebridge-alexa"
            },
            "name": "Alexa",
            "routines": true,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "username": "---",
            "password": "-----",
            "pin": "****"
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            }
        }
    ]
}

**Post your log**
23.1.2021, 09:18:42 Loaded plugin 'homebridge-alexa'
23.1.2021, 09:18:42 [1/23/2021, 1:18:42 AM] Registering platform 'homebridge-alexa.Alexa'
23.1.2021, 09:18:42 Loaded plugin 'homebridge-dummy'
23.1.2021, 09:18:42 [1/23/2021, 1:18:42 AM] Registering accessory 'homebridge-dummy.DummySwitch'
23.1.2021, 09:18:42 [1/23/2021, 1:18:42 AM] The plugin "homebridge-hue" requires Node version of ^14.15.4 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.
23.1.2021, 09:18:44 Loaded plugin 'homebridge-hue'
23.1.2021, 09:18:44 [1/23/2021, 1:18:44 AM] Registering platform 'homebridge-hue.Hue'
23.1.2021, 09:18:44 [1/23/2021, 1:18:44 AM] The plugin "homebridge-meross" requires Node version of >=14.15.1 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.
23.1.2021, 09:18:44 Loaded plugin 'homebridge-meross'
23.1.2021, 09:18:44 [1/23/2021, 1:18:44 AM] Registering accessory 'homebridge-meross.Meross'
23.1.2021, 09:18:44 Loaded plugin 'homebridge-shelly'
23.1.2021, 09:18:44 [1/23/2021, 1:18:44 AM] Registering platform 'homebridge-shelly.Shelly'
23.1.2021, 09:18:44 Loaded plugin 'homebridge-yeelight-wifi'
23.1.2021, 09:18:44 [1/23/2021, 1:18:44 AM] Registering platform 'homebridge-yeelight-wifi.yeelight'
23.1.2021, 09:18:44 Loading 4 platforms...
23.1.2021, 09:18:44 [yeelight] Initializing yeelight platform...
23.1.2021, 09:18:44 [Shelly] Initializing Shelly platform...
23.1.2021, 09:18:44 [Alexa] Initializing Alexa platform...
23.1.2021, 09:18:44 [Alexa] homebridge-alexa v0.5.23, node v12.16.3, homebridge v1.1.7
23.1.2021, 09:18:44 Initializing platform accessory 'Alexa'...
23.1.2021, 09:18:44 [Hue] Initializing Hue platform...
23.1.2021, 09:18:44 [Hue] config.json: warning: plugin_map: ignoring unknown key
23.1.2021, 09:18:44 [Hue] homebridge-hue v0.12.18, node v12.16.3, homebridge v1.1.7
23.1.2021, 09:18:44 [Hue] warning: not using recommended node version v14.15.4 LTS
23.1.2021, 09:18:44 [Hue] searching bridges and gateways
23.1.2021, 09:18:44 [yeelight] Loaded accessory color-5b6baa.
23.1.2021, 09:18:44 [yeelight] Searching for known devices...
23.1.2021, 09:18:44 [yeelight] Sending search request...
23.1.2021, 09:18:44 [Shelly] 3 accessories loaded from cache
23.1.2021, 09:18:44 Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
    at Socket.onListenError (dgram.js:525:22)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:322:22)
    at dgram.js:341:14
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
23.1.2021, 09:18:44 [Shelly] Device SHSW-L 84CCA8ACF821 is stale. Unregistering its accessories.
23.1.2021, 09:18:44 [Shelly] Device SHSW-1 A4CF12F45AF4 is stale. Unregistering its accessories.
23.1.2021, 09:18:44 [Shelly] Device SHSW-1 10521CF1C12D is stale. Unregistering its accessories.
23.1.2021, 09:18:44 Got SIGTERM, shutting down Bridge...
23.1.2021, 09:18:44 [Shelly] New device discovered: SHSW-L 84CCA8ACF821 at 192.168.2.120
23.1.2021, 09:18:44 [Shelly] New device discovered: SHSW-1 A4CF12F45AF4 at 192.168.2.122
23.1.2021, 09:18:44 [Shelly] New device discovered: SHSW-1 10521CF1C12D at 192.168.2.109
23.1.2021, 09:18:47 [Hue] goodbye

**Additional context**

**Comment by EddieDSuza** [comment]
Run this command to update node

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

**Comment by Poppi1231** [comment]
Thanks for you answer... 
I did, but now i habe no access to the Webinterface hoobs.local or http://192.168.2.123

**Comment by EddieDSuza** [comment]
Here are the instructions to reset your password:

Login to the HOOBS Box via SSH on your computer.
On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

After successfully logging in, type this - 

`sudo npm uninstall -g @hoobs/hoobs`

`sudo npm install -g --unsafe-perm  @hoobs/hoobs `

`sudo reboot`

**Comment by EddieDSuza** [comment]
Resolved via "Tech With Eddie Messenger"
