### ISSUE TITLE
Wait for router or retry until router boot after power outage.

### ISSUE THREAD

**Issue by MoTechnicalities** [hoobs-org/HOOBS#1048]
**Is your feature request related to a problem? Please describe.**
HOOBS Loads too fast for the router after a power outage and does not try to reestablish service once the router is back up and running.

**Describe the solution you'd like**
I would like to see HOOBS try to start the services after an IP connection is established.

**Describe alternatives you've considered**

**Additional context**
Currently I connect my HOOBS power transformer to an eWeLink switch so that if there is a power outage while I am not home, I can power the HOOBS Box up after the router is back up. Otherwise the service would remain down until i returned home to manually start the service. But even with this, I won't know the service is down unless I happen to check it!

**Comment by EddieDSuza** [comment]
Go to Configuration > Server Settings > Bridge Auto Start. Update the value to more than 0 to delay the service start in seconds.

**Comment by MoTechnicalities** [comment]
> 
> 
> Go to Configuration > Server Settings > Bridge Auto Start. Update the value to more than 0 to delay the service start in seconds.

That is one way.
But even my eWeLink switch auto connect after the router finally boots. Shouldn't we be able to have HOOBS have an option to simply keep trying until its got a connection?

**Comment by EddieDSuza** [comment]
Its the plugin that needs to do **the trying** to connect with the devices.

**Comment by MoTechnicalities** [comment]
> Its the plugin that needs to do **the trying** to connect with the devices. 

No. I'm talking about a power cycle after a power outage. ￼HOOBS won't start its services if the modem hasn't finished booting up. Xfinity router for example takes about 7 to 10 minutes to get going and if for any reason IP serve drops then HOOBS service just stops! Why not have HOOBS just keep trying to reconnect!￼
