### ISSUE TITLE
Can't create a cluster

### ISSUE THREAD

**Issue by Super-Harry** [hoobs-org/HOOBS#1049]
Hello I try to create a cluster on the raspberry pi.
I have an fresh installed the raspberry pi with Hoobs.
Node version 10.23.1
Hoobs version 3.3.2

Wenn I try to create a cluster via Terminal I got following issue.

hoobs@hoobs:~ $ sudo hoobs cluster client

✔ Choose your HOOBS cluster account name … EG
✔ Choose your HOOBS cluster username … admin
✔ Choose your HOOBS cluster password … *****
✔ Confirm your password … *****
(node:1155) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at Prompt.then (/usr/lib/node_modules/@hoobs/hoobs/scripts/client.js:88:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1155) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I saw found these issue:
Can't get HOOBS cluster working on new Raspberry Pi install #686 => this is closed
Also the 
Cluster Set UP #655 => this is closed

Do you have a solution for this topic?

**Comment by mkellsy** [comment]
We are working on easier instances in HOOBS 4.

Also your Node version is old. You should upgrade to the latest KTS version. Then try again.

I will look into this error in HOOBS 3 too.

**Comment by Super-Harry** [comment]
Hi,

Installed fresh pi with following versions. Now I get a other error

nodversion
v15.7.0

npm
6.14.11

When I try to create a cluster I get following error


hoobs@hoobs:~ $ hoobs cluster client
✔ Choose your HOOBS cluster account name … bridge
✔ Choose your HOOBS cluster username … Harald
✔ Choose your HOOBS cluster password … **********
✔ Confirm your password … **********
/usr/lib/node_modules/@hoobs/hoobs/scripts/client.js:88
        if (!error) {
        ^

ReferenceError: error is not defined
    at /usr/lib/node_modules/@hoobs/hoobs/scripts/client.js:88:9
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

> Am 26.01.2021 um 23:32 schrieb Michael Kellsy <notifications@github.com>:
> 
>  LTS ve
