### ISSUE TITLE
HOOBS web UI and SSH login stop working every couple of days…

### ISSUE THREAD

**Issue by digital-native** [hoobs-org/HOOBS#1050]
My only recourse is to power-cycle the box in order to get it back online. Please advise how I can resolve this issue, as I'm afraid it's only a matter of time before the file system corrupts and I have to do a complete restore. Thanks.

**Comment by EddieDSuza** [comment]
Go to Help > Backup > click on logs and post the file here to get an insight on the issue you are having

**Comment by digital-native** [comment]
Here's the log file. I also saw the 3.3.2 HOOBS update today too. Tried to install it, I see the bridge server stop and then start, but the web UI just churns and churns until I reload the page, and the version remains at 3.3.1. Thanks for the assist.

[logs.txt](https://github.com/hoobs-org/HOOBS/files/5877154/logs.txt)

**Comment by EddieDSuza** [comment]
Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: `ssh hoobs@hoobs.local`

Type yes to accept the certificate key then press enter. When prompted for password, type **hoobsadmin**
Once logged in you will see in green text hoobs@hoobs on the left side of the terminal.

Paste these commands - this will update Node & Your System 

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

**Comment by Hoobs-begginer** [comment]
@EddieDSuza 

Thanks Eddie! This command helped me a lot!!!
