### ISSUE TITLE
Can't get shelly 1's/bulbs to work reliably 

### ISSUE THREAD

**Issue by ari-ido-999** [hoobs-org/HOOBS#1051]
I have a few shelly 1's and bulbs and they don't seem to be turned off after after a short time of operating correctly. I read it might be a networking issue. I have TP Link Deco M5 which is setup as an access point. I tried to disable all the advanced settings in the TP linked App (beamfroming) but nothing helps.  Everything works perfect from the shelly App. also when I flash the shelly's with homekit firmware they also work flawlessly

**Comment by EddieDSuza** [comment]
Reset Network followed by HOOBS server.

**Comment by ari-ido-999** [comment]
Thanks, did it. Will update if it solved the issue

**Comment by ari-ido-999** [comment]
Didn't solve the issue 


Sent from Yahoo Mail for iPhone


On Tuesday, January 26, 2021, 12:13 PM, Tech With Eddie <notifications@github.com> wrote:




Reset Network followed by HOOBS server.

**Comment by EddieDSuza** [comment]
Just your subnet configuration so that all the devices as well as HOOBS are on the same subnet. These issues arise due to Network configurations.

**Comment by ari-ido-999** [comment]
I don't have any subnets, all devices are connected to the same network
