### ISSUE TITLE
ssh hoobs@hoobs.local not working in Terminal App

### ISSUE THREAD

**Issue by mjudson64** [hoobs-org/HOOBS#1052]
Trying to fix hoops.local error; said to type in ssh hoobs@hoobs.local.  First time I did it, I got the following:  

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.

So, I updated to zsh (I believe) and type in ssh hoobs@hoobs.local again and got the following:

"kex_exchange_identification: read: Connection reset by peer”

Not sure what to do now

**Comment by ghofmann1** [comment]
I believe o got something similar. Help!

**Comment by mkellsy** [comment]
HOOBS is not affected by the client shell. SSH is an application so it shouldn't be affected by the shell either. You can always switch back to BASH `chsh -s /bin/bash` if you believe zsh is the cause.

However it might be mDNS, try SSH hoobs@[ip address], you can get the ip from the router.

The other thing you can try, truncate the ~/.ssh/known_hosts file.

**Comment by mjudson64** [comment]
I tried as instructed above and still not working.  Here's the log:

Last login: Tue Feb  2 20:00:36 on console
michellejudson@Michelles-MBP-2 ~ % ssh hoobs@192.168.50.1
ssh: connect to host 192.168.50.1 port 22: Connection refused
michellejudson@Michelles-MBP-2 ~ % ~/.ssh/known_hosts file 
zsh: no such file or directory: /Users/michellejudson/.ssh/known_hosts
michellejudson@Michelles-MBP-2 ~ % chsh -s /bin/bash
Changing shell for michellejudson.
Password for michellejudson: 
chsh: Credentials could not be verified, username or password is invalid.  Credentials could not be verified, username or password is invalid.
michellejudson@Michelles-MBP-2 ~ % chsh -s /bin/bash
Changing shell for michellejudson.
Password for michellejudson: 
michellejudson@Michelles-MBP-2 ~ % hoobs@hoobs.local
zsh: command not found: hoobs@hoobs.local
michellejudson@Michelles-MBP-2 ~ % 

Any more suggestions?

**Comment by mkellsy** [comment]
Your Mac is the problem. The most I can tell you is try this command.
```
touch /Users/michellejudson/.ssh/known_hosts
```

If that doesn't work you may need to contact Apple support.
