### ISSUE TITLE
Error Adding to HomeKit

### ISSUE THREAD

**Issue by SynapseSmartHomes** [hoobs-org/HOOBS#1053]
**Description**
In the Apple Home App, QR code can be scanned, and a "hub" identified, but device is failed to be added to the clients Apple Home.

**Version**
3.3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Roomba stv

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
I've tried rebooting the Hoobs box several times, and each time I can get as far as adding the QR code, and the hub being recognized as a hub, but not fully being added to the Home app.

**Comment by askovi** [comment]
Make sure the HOOBS service is running correctly first (check the logs). Then make sure the HOOBS Box is plugged into the same network as the device used to scan the code. If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network.
