### ISSUE TITLE
Add confirmation before shutting down

### ISSUE THREAD

**Issue by LewisSpring** [hoobs-org/HOOBS#1054]
**Is your feature request related to a problem? Please describe.**
I pressed shutdown instead of restart and now I need to go up the loft.

**Describe the solution you'd like**
When I press Shutdown via the web interface, I'd like it if there was a confirmation box asking if i'd like to shutdown first.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mkellsy** [comment]
Done in HOOBS 4
