### ISSUE TITLE
Ring Cameras not responding in Homekit

### ISSUE THREAD

**Issue by GOTDNRV** [hoobs-org/HOOBS#1055]
This is a copy of error code
code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/27/2021, 6:49:39 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/27/2021, 6:49:39 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/27/2021, 6:49:39 AM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...

Update for Ring is 9.14.1 dated 1/11/21
Hoobs 3.3.2

Upgraded from the previous version

Running on
 HOOBS Box

Operating system Mac OS Big Sur
**List your plugins**

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
{
    "server": {
        "home_setup_id": "X-HM://0023ISYWY49H6",
        "origin": "*",
        "polling_seconds": 5,
        "autostart": 0,
        "port": 80
    },
    "client": {
        "postal_code": "94040",
        "locale": "en",
        "temp_units": "fahrenheit",
        "default_route": "status",
        "theme": "hoobs-light",
        "country_code": "US",
        "inactive_logoff": 30
    },
    "bridge": {
        "port": 51826,
        "pin": "031-45-154",
        "username": "48:F2:FE:E3:59:0F",
        "name": "HOOBS"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "persistAccessories": false,
            "plugin_map": {
                "plugin_name": "homebridge-simplisafe3"
            },
            "name": "Home Alarm",
            "resetSimpliSafeId": false,
            "cameras": true,
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "debug": false,
            "auth": {
                "username": 
                "password": 
                
                
            },
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "sensorRefresh": 15
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTE3NDc2NDgsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6NjgxNjQ3Miwicm5kIjoiQU5GdElOZFRna0JHaWciLCJzZXNzaW9uX2lkIjoiMTljMjFmOGItMDZhZS00MGJjLWE0NmUtMzY0OTQyOTJmOTk0IiwidHlwZSI6InJlZnJlc2gtdG9rZW4ifQ.4O5zMMAnPDTHh2Sg1RA_dSEVCPsgWAqgPM3DlgrjLepoQ0ubLS9dL7_MNTHA6We0fiQfzhF5v9pxshhWTw4GwQ",
            "hideDeviceIds": [],
            "locationIds": [],
            "onlyDeviceTypes": []
        }
    ]
}

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
Can you provide the Node version - If its Below Ver 12 - then 

Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: `ssh hoobs@hoobs.local`

Type yes to accept the certificate key then press enter. When prompted for password, type **hoobsadmin**
Once logged in you will see in green text hoobs@hoobs on the left side of the terminal.

Paste the below command

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`
