### ISSUE TITLE
HOOBS is not connecting to the internet

### ISSUE THREAD

**Issue by tai86hk** [hoobs-org/HOOBS#1057]
Hi, 
I tried to update one of my plugin this morning in the browser and as a result my hoobs is down since then. 

I tried ssh hoobs@hoobs.local, i tried on the browser. no luck!! 

Therefore, i check my router and it states that HOOBS isn't active since i tried to update the plugin 
![IMG_8F657FA8BEFE-1](https://user-images.githubusercontent.com/75288400/106048093-721ed300-60b2-11eb-99ea-ba9d09b91263.jpeg)

please advise.

**Comment by tai86hk** [comment]
i unboxed HOOBS and hooked it up to the monitor. it said it went in to the emergency mode. 

i used the following to reinstall it.

wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts

and i got the following error code 

please advise
![error code](https://user-images.githubusercontent.com/75288400/106062797-49540900-60c5-11eb-9348-4c0d60a2ca70.PNG)

**Comment by EddieDSuza** [comment]
Rebuild NPM - 
`sudo npm uninstall -g @hoobs/hoobs`
`sudo npm install -g --unsafe-perm  @hoobs/hoobs`

**Comment by tai86hk** [comment]
Thank you!!
