### ISSUE TITLE
UX: Change icon for Dashboard

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#106]
from
<img width="45" alt="Screenshot 2019-08-30 at 10 36 57" src="https://user-images.githubusercontent.com/50763727/64006247-3759e980-cb12-11e9-9534-ae0de5f8cad3.png">
to something like
https://www.flaticon.com/free-icon/dashboard_565489#term=dashboard&page=1&position=8

**Comment by mkellsy** [comment]
I will use the dashboard icon from material it's already there.

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.34
