### ISSUE TITLE
Bridge Service Not running

### ISSUE THREAD

**Issue by Bodreg** [hoobs-org/HOOBS#1060]
Hallo, 
I‘m new in Homebridge/Hoobs.

i installed Hoobs on a raspberry pi 4B.
Apple Home App successfully connected via QR-Code.

I‘m on hoobs.local on an iPad.
On the Hoobs-Dashboard i get the message:  „Bridge Service is not running“

Did I forget any plug-in or anything else?

Here is a screenshot of the log:
https://imgur.com/a/vdmCI5z

**Comment by EddieDSuza** [comment]
The Ikea plugin require configuration - youll need to add the hub information. Once that is configured. The bridge service will come back online
