### ISSUE TITLE
Hoobs keeps shutting down

### ISSUE THREAD

**Issue by chemicalsam** [hoobs-org/HOOBS#1061]
I’m running Hoobs (SD card) with a raspberry pi 4. It’s been working fine for months until today. It won’t start up. My pi lights are off   

After cycling power hoobs works for a few minutes and then shuts off again

**Comment by EddieDSuza** [comment]
Please attach the logs to assist you. For the logs - go to help > backup > click on logs. 

Or you can click the 3rd icon on the left in your Dashboard UI to check what the issues are.

**Comment by chemicalsam** [comment]
> Please attach the logs to assist you. For the logs - go to help > backup > click on logs.
> 
> Or you can click the 3rd icon on the left in your Dashboard UI to check what the issues are.

I just got the new card and everything worked fine for about a day. Now there’s yet another issue. 

provided empty image buffer!
3/7/2021, 9:18:09 PM [Ring] Front Door Detected Motion. Loading snapshot before sending event to HomeKit
3/7/2021, 9:18:09 PM [Front Door] Snapshot request handler provided empty image buffer!
3/7/2021, 9:18:09 PM [Front Door] Snapshot request handler provided empty image buffer!
3/7/2021, 9:40:03 PM Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
3/7/2021, 9:40:03 PM Got SIGTERM, shutting down Bridge...

**Comment by mkellsy** [comment]
The ENETUNREACH error is caused because the Pi can't reach 224.0.0.251:5353
This most likely is a camera. I would restart the camera, and check top see if there is a firmware update.
