### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by KlausStahl** [hoobs-org/HOOBS#1065]
Hi,

After working with some network modifications I came back to my original network system. Hoobs no longer can be reached by web interface, Mac Terminal, etc. There is no hardware reset I guess. Must I throw away the device?

Regards
Klaus

**Comment by EddieDSuza** [comment]
Check if the device is turned on (Red power light / Ethernet Green light Blinking / Orange Light )

Access your router and check the IP of the device. Open terminal and access the device by using SSH command 

for example `ssh hoobs@<IP address of the BOX>`

Once logged in - type `sudo hoobs service log`

Paste the information here.

**Comment by KlausStahl** [comment]
Hi,

thanks for your answer.

The device is turned on. Just the red light is shining, no other.

The LAN cable is connected directly to my Mac (the same when connected to the router): The IP of the Hoobs-box could not be found with the Mac-App LanScan.

Before it was no problem to find the IP and to connect to the interface of the Hoobs-box.

Regards
Klaus Stahl
