### ISSUE TITLE
Starting HOOBS as root

### ISSUE THREAD

**Issue by Mid99** [hoobs-org/HOOBS#1068]
Hi,

I am new to Hoobs and after spending long time looking for a solution to start HOOBS as root, only finding a discontinued solution, I hopefully can get some support here.
I want to use the Mi-flower app that requests root rights because of the Bluetooth connection.
Can anyone please help how to run HOOBS with root rights all the time? 
Thank you,
Mid

**Comment by EddieDSuza** [comment]
if you are referring to this plugin https://plugins.hoobs.org/plugin/homebridge-mi-flower-care then you will need to add the command `sudo` before the command link. If not included - it will request for root rights.
