### ISSUE TITLE
unable to access through UI or ssh

### ISSUE THREAD

**Issue by snarknesor** [hoobs-org/HOOBS#1070]
after updating to node 14, my hoobs was inaccessible. I've unplugged and replugged a number of times. tried to ssh into it but everytime i get asked for 'hoobs@hoobs.local's password', my keystrokes stop registering in the terminal. no clue how to move forward.

**Comment by askovi** [comment]
The password isn’t displayed in the terminal while you’re typing it. Just type it and press enter

**Comment by snarknesor** [comment]
Thanks!

________________________________
