### ISSUE TITLE
Unable to access through UI or SSH

### ISSUE THREAD

**Issue by Erkilaine** [hoobs-org/HOOBS#1071]
After rebooting the unit (HOOBS IN A BOX) it will not respond to any commands in SSH. LAN port is active but no IP adress. I've already tried to unplug network cable and disconnect USB power.

**Comment by EddieDSuza** [comment]
Is the green light at the ethernet port blinking. If yes - the device is connected with the device. Also make sure the HOOBS Box as well as the computer are on the same subnet

**Comment by Erkilaine** [comment]
> Is the green light at the ethernet port blinking. If yes - the device is connected with the device. Also make sure the HOOBS Box as well as the computer are on the same subnet

No, the Ethernet port worked yesterday but today it's dead.
