### ISSUE TITLE
Problem with eveatmo - black & white doesn't work

### ISSUE THREAD

**Issue by The-Paw** [hoobs-org/HOOBS#1074]
**Description**
eveatmo black & whitelist doesn't work .. all modules still in HomeKit 

**Expected behavoir**
netatmo weather station in HomeKit 

**Plugin name**
eveatmo

**Please report the issue to the plugin developer**
eveatmo black & whitelist doesn't work :-((

**Version**
Hoods 3.3.2 PlugIn 0.6.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [* ] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ *] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [* ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Post your config**

{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "****",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "***",
        "latitude": "***",
        "longitude": "****"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "****",
        "username": "*****"
    },

*PlugIn*
	    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "eveatmo",
            "plugin_map": {
                "plugin_name": "homebridge-eveatmo"
            },
            "name": "eveatmo",
            "ttl": 540,
            "extra_co2_sensor": false,
            "weatherstation": true,
            "airquality": false,
            "co2_alert_threshold": 1000,
            "auth": {
                "client_id": "**",
                "client_secret": "**",
                "username": "***",
                "password": "**",
                "whitelist": [
                    "70:ee:******",
                    "02:00:*****"
                ],
                "blacklist": [
                    "70:ee:***",
                    "03:00:0***",
                    "03:00:0***,
                    "03:00:00***",
                    "02:00:00:****",
                    "05:00:00:***",
                    "06:00:00:****"
                ]
            }
			},

**Post your log**

3.2.2021, 19:21:38 Got SIGINT, shutting down Bridge...
3.2.2021, 19:21:44 Loaded plugin 'homebridge-eveatmo'
3.2.2021, 19:21:44 [2/3/2021, 11:21:44 AM] Registering platform 'homebridge-eveatmo.eveatmo'
3.2.2021, 19:21:44 Loaded plugin 'homebridge-midea'
3.2.2021, 19:21:44 [2/3/2021, 11:21:44 AM] Registering platform 'homebridge-midea.midea'
3.2.2021, 19:21:45 Loaded plugin 'homebridge-philips-air'
3.2.2021, 19:21:45 [2/3/2021, 11:21:45 AM] Registering platform 'homebridge-philips-air.philipsAir'
3.2.2021, 19:21:45 Loading 3 platforms...
3.2.2021, 19:21:45 [eveatmo] Initializing eveatmo platform...
3.2.2021, 19:21:47 [eveatmo] Loading new data from API for: weatherstation
3.2.2021, 19:21:47 [Philips Air] Initializing philipsAir platform...
3.2.2021, 19:21:47 [midea] Initializing midea platform...
3.2.2021, 19:21:47 [Philips Air] [Keller] Initializing accessory...
3.2.2021, 19:21:49 HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
3.2.2021, 19:21:49 HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
3.2.2021, 19:21:49 HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
3.2.2021, 19:21:49 HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
3.2.2021, 19:21:49 HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
3.2.2021, 19:21:49 Initializing platform accessory 'Pollerweg (Küche) Küche'...
3.2.2021, 19:21:49 Initializing platform accessory 'Pollerweg (Küche) Aussen'...
3.2.2021, 19:21:49 Initializing platform accessory 'Pollerweg (Küche) Badezimmer'...
3.2.2021, 19:21:49 Initializing platform accessory 'Pollerweg (Küche) Esszimmer'...
3.2.2021, 19:21:49 Initializing platform accessory 'Pollerweg (Küche) Wohnzimmer'...
3.2.2021, 19:21:49 Initializing platform accessory 'Pollerweg (Küche) Regen'...
3.2.2021, 19:21:49 Initializing platform accessory 'Pollerweg (Küche) Wind'...
3.2.2021, 19:21:49 Initializing platform accessory 'Pollerweg (Bastelraum) Bastelraum'...
3.2.2021, 19:21:49 Initializing platform accessory 'Pollerweg (Bastelraum) Vorratsraum'...
3.2.2021, 19:21:49 Bridge is running on port 51826.
3.2.2021, 19:30:47 [eveatmo] Loading new data from API for: weatherstation

**Additional context**
What about HAP Warning ?? How can I fix the black & white issue?? It doesn't work. All modules signed in HomeKit.

**Comment by EddieDSuza** [comment]
Open an issue with the developer of the devices not working.

**Comment by The-Paw** [comment]
> Open an issue with the developer of the devices not working.

Still working, yet 👌🏼
