### ISSUE TITLE
I have removed a plug-in, however, in reviewing the logs, I'm showing "Failed to find plugin to handle accessory"

### ISSUE THREAD

**Issue by yefimovah** [hoobs-org/HOOBS#1075]
I have removed a plug-in, however, in reviewing the logs, I'm showing "Failed to find plugin to handle accessory"...

How do I get rid of the accessory from hoobs that's causing this?

**Comment by mkellsy** [comment]
How did you remove the plugin?
Remove the entries in your config.

**Comment by yefimovah** [comment]
so I used the uninstall button for the accessory... I'm guessing that you're referring to the configuration... the entries appear to be removed from the config... I clicked on "advanced" to review the whole config file...

**Comment by mkellsy** [comment]
Try purging the cache. It's in the help screen. You will need to re-pair with HomeKit.

**Comment by sfguyfor20** [comment]
Is that the reset option from the help menu?

**Comment by mkellsy** [comment]
No it's purge or reset connection

**Comment by sfguyfor20** [comment]
Thanks Mike... I ended up just blowing away the config and starting again, as I saved the config off,  and just pasted it back in after adding back the plugins... With the fresh start, ironically, the Eufy Security homebridge plugin and my Wiz Lan plugin are now both working... and associated accessories came up in HK... 

Would love to understand why a fresh canvas made a difference... Thanks for your help!

**Comment by mkellsy** [comment]
It's how the plugin caches accessories. The device was stuck in the cache. Resetting the connection would have fixed this.

Resetting the connection clears the accessory cache.
