### ISSUE TITLE
Wont connect to homekit

### ISSUE THREAD

**Issue by cdrwinston** [hoobs-org/HOOBS#1077]
I am new and have a raspberry pi4. I have downloaded Hoobs to my card. I can access Hoobs through the website 192.168.x it won’t connect through .local. But I cannot get it to connect to HomeKit. It keeps saying that accessory not found. I’m on eero mesh. I’ve unplugged the other nodes to ensure I’m on the same network. No luck. I’ve restarted, reset and generated a new code with no luck. What else should I try?

**Comment by EddieDSuza** [comment]
restart your Eero mesh router for the device to be found by Homekit and make sure you connect the Pi4 to the main node. When mDNS is not available then use the IP address of the box to access the UI.

**Comment by scottyb2210** [comment]
I am having the same issue but not using mesh routers.  My HOOBS is hard wired via a switch to my router.  I've tried using the homekit code as well as scanning the QR code but continue to get 'No Accessory Found'

**Comment by scottyb2210** [comment]
I am an idiot.  I've been testing the Unifi Dream Machine in my house on a different network and did not realize I wasn't on my main network. Switched to that and walla, device found.  <facepalm>

**Comment by cdrwinston** [comment]
Hahahaha. No you’re not. But I’m glad I could help.

**Comment by EddieDSuza** [comment]
Please close the issue :)
