### ISSUE TITLE
UI won't load, terminal wont accept password

### ISSUE THREAD

**Issue by ghofmann1** [hoobs-org/HOOBS#1079]
**Description**

UI wont load and gives error - Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

tried ssh in to reinstall and it wont accept any of the recommended passwords, nor my account password,

**Version**
Please include the version of HOOBS you are using.

hoobs 3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [X ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

ring
nest
roomba
tp link
kevo

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

cant access

* Remove any passwords from the config file. This is public.

cant access

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
cant access```

**Additional context**
Add any other context about the problem here.

**Comment by abbeycode** [comment]
I'm having this too. I found a post on Reddit suggesting I flash my SD card, but I'm nervous about doing so since I don't want to lose my configuration.

https://www.reddit.com/r/HOOBS/comments/klq03o/error_eio/

**Comment by abbeycode** [comment]
@mkellsy Hey, do you have any ideas? I've been totally offline for several days now.

**Comment by mkellsy** [comment]
We identified this as bad SD Cards and we have switched vendors.
This is corruption on the SD Card. You can SSH into the device and run these commands.
```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

This will remove the app files and re-download them. If this doesn't work you will need to re-flash the SD Card.

**Comment by abbeycode** [comment]
@mkellsy Thanks, but I am indeed unable to SSH in (I get the error `kex_exchange_identification: read: Connection reset by peer`). How would I re-flash the SD card? And once re-flashed, do I lose installations and configuration, or is that stored elsewhere?

**Comment by mkellsy** [comment]
You can download the image here.
https://github.com/hoobs-org/HOOBS/releases/tag/v3.3.2

Then use the balinaEtcher to flash it to an SD Card.
https://www.balena.io/etcher/

You can access the sd card slot by removing the feet and unscrewing the 4 screws. The sd card is located on the back side of the board.

I would also suggest replacing the SD card. I recommend this one.
https://www.amazon.com/Samsung-Class-Adapter-MB-MC32GA-AM/dp/B0749KG1JK

**Comment by abbeycode** [comment]
@mkellsy thanks for that. What is the warranty? I just received mine at the beginning of December, so I’m within 90 days. How do I go about having someone send a replacement card?

**Comment by mkellsy** [comment]
For warranty, you will need to send an email to info@hoobs.org with your order number. This can't be done in the public GitHub site :)
