### ISSUE TITLE
Update HOOBS From Dashboard

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#108]
<img width="523" alt="Screenshot 2019-08-30 at 10 47 19" src="https://user-images.githubusercontent.com/50763727/64006979-a421b380-cb13-11e9-8aee-0427d6511fbc.png">

**Comment by mkellsy** [comment]
Checking for the update on the status dashboard will cause unnecessary network traffic. I will add a Check for Updates, if the user has permission to do it.

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.37
