### ISSUE TITLE
Bridge Keeps Shutting Down

### ISSUE THREAD

**Issue by sprihar** [hoobs-org/HOOBS#1080]
Bridge is shutting down sporadically, and without reason. Below is a copy/paste of logs.

**Description**
2/6/2021, 7:04:34 PM HOOBS listening on port 80.
2/6/2021, 7:05:49 PM Loaded plugin 'homebridge-mylink'
2/6/2021, 7:05:50 PM [2/6/2021, 5:05:49 PM] Registering platform 'homebridge-mylink.Somfy myLink'
2/6/2021, 7:05:53 PM Loaded plugin 'homebridge-ring'
2/6/2021, 7:05:53 PM [2/6/2021, 5:05:53 PM] Registering platform 'homebridge-ring.Ring'
2/6/2021, 7:05:53 PM Loading 2 platforms...
2/6/2021, 7:05:53 PM [Somfy myLink] Initializing Somfy myLink platform...
2/6/2021, 7:05:53 PM Initializing platform accessory 'Somfy Living Room'...
2/6/2021, 7:05:53 PM Initializing platform accessory 'Somfy 2nd Floor'...
2/6/2021, 7:05:53 PM [Ring] Initializing Ring platform...
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory 41c5b1d1-2a1a-47ab-bb73-a57be64b7861 Ring Alarm
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory b3e52482-c78b-4002-9667-a975c75ca89c Front Door
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory 0ea2e671-4d94-49cd-9164-feffe56e6801 Patio Sliding Doors
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory 569251c1-b10a-436d-bb63-b4815fbf5501 Side Door
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory 4a353a89-2889-471d-92cc-e966eb5fb332 Garage Door
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory 7183582c-e613-4b84-9f68-d1a24aebf69c Second Floor Sliding Door
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory 8e209466-682d-47f0-8012-e47624fc138a Basement Window
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory 2a253c23-8b8f-4f25-b3a5-f7212b83d907 Kitchen 
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory d726cfe7-71bc-40c9-9025-256ca36f786b Smoke/CO Listener
2/6/2021, 7:05:53 PM [Ring] Configuring cached accessory 14310424-fc89-48ed-83eb-952632ae3f6f Hallway
2/6/2021, 7:05:53 PM Bridge is running on port 51826.
2/6/2021, 7:05:54 PM [Ring] Found the following locations:
2/6/2021, 7:05:54 PM [Ring]   locationId: 69387c91-f4ba-4a65-a964-4e3b7a38c7da - Home
2/6/2021, 7:05:54 PM [Ring] Creating location socket.io connection - Home
2/6/2021, 7:05:55 PM [Ring] Ring connected to socket.io server
2/6/2021, 7:05:55 PM [Ring] Configuring 0 cameras and 17 devices for location "Home" - locationId: 69387c91-f4ba-4a65-a964-4e3b7a38c7da
2/6/2021, 7:05:55 PM [Ring] Hidden accessory c459d254-9dce-4abf-96ea-fd5053963559 access-code.vault Code Vault
2/6/2021, 7:05:55 PM [Ring] Hidden accessory be334c3c-7d83-4c9d-81fb-1a893bee7ab5 adapter.zigbee ZigBee onboard adapter
2/6/2021, 7:05:55 PM [Ring] Hidden accessory 89912722-cbc5-41d7-9340-3523c509481c access-code Security Access Code
2/6/2021, 7:05:55 PM [Ring] Hidden accessory 28012dda-73dc-4c9a-a487-e0dd54ad8c3a hub.redsky Base Station
2/6/2021, 7:05:55 PM [Ring] Hidden accessory 8f38be3b-b136-4e3a-ae4a-f6668ddc2bf5 adapter.zwave Z-Wave Adapter
2/6/2021, 7:05:55 PM [Ring] Hidden accessory 629076dc-ee8d-4037-9a94-39d7508cdf7b security-keypad Kitchen Keypad
2/6/2021, 7:05:55 PM [Ring] Hidden accessory 8ce9c908-580a-4e00-a964-5fbddcc8e01f security-keypad Entryway Keypad
2/6/2021, 10:53:55 PM Got SIGINT, shutting down Bridge...
2/6/2021, 10:54:03 PM Loaded plugin 'homebridge-mylink'
2/6/2021, 10:54:03 PM [2/6/2021, 8:54:03 PM] Registering platform 'homebridge-mylink.Somfy myLink'
2/6/2021, 10:54:04 PM Loaded plugin 'homebridge-ring'
2/6/2021, 10:54:04 PM [2/6/2021, 8:54:04 PM] Registering platform 'homebridge-ring.Ring'
2/6/2021, 10:54:04 PM Loading 2 platforms...
2/6/2021, 10:54:04 PM [Somfy myLink] Initializing Somfy myLink platform...
2/6/2021, 10:54:05 PM Initializing platform accessory 'Somfy Living Room'...
2/6/2021, 10:54:05 PM Initializing platform accessory 'Somfy 2nd Floor'...
2/6/2021, 10:54:05 PM [Ring] Initializing Ring platform...
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory 41c5b1d1-2a1a-47ab-bb73-a57be64b7861 Ring Alarm
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory b3e52482-c78b-4002-9667-a975c75ca89c Front Door
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory 0ea2e671-4d94-49cd-9164-feffe56e6801 Patio Sliding Doors
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory 569251c1-b10a-436d-bb63-b4815fbf5501 Side Door
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory 4a353a89-2889-471d-92cc-e966eb5fb332 Garage Door
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory 7183582c-e613-4b84-9f68-d1a24aebf69c Second Floor Sliding Door
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory 8e209466-682d-47f0-8012-e47624fc138a Basement Window
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory 2a253c23-8b8f-4f25-b3a5-f7212b83d907 Kitchen 
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory d726cfe7-71bc-40c9-9025-256ca36f786b Smoke/CO Listener
2/6/2021, 10:54:05 PM [Ring] Configuring cached accessory 14310424-fc89-48ed-83eb-952632ae3f6f Hallway
2/6/2021, 10:54:05 PM Bridge is running on port 51826.
2/6/2021, 10:54:06 PM [Ring] Found the following locations:
2/6/2021, 10:54:06 PM [Ring]   locationId: 69387c91-f4ba-4a65-a964-4e3b7a38c7da - Home
2/6/2021, 10:54:06 PM [Ring] Creating location socket.io connection - Home
2/6/2021, 10:54:07 PM [Ring] Ring connected to socket.io server
2/6/2021, 10:54:07 PM [Ring] Configuring 0 cameras and 17 devices for location "Home" - locationId: 69387c91-f4ba-4a65-a964-4e3b7a38c7da
2/6/2021, 10:54:07 PM [Ring] Hidden accessory c459d254-9dce-4abf-96ea-fd5053963559 access-code.vault Code Vault
2/6/2021, 10:54:07 PM [Ring] Hidden accessory be334c3c-7d83-4c9d-81fb-1a893bee7ab5 adapter.zigbee ZigBee onboard adapter
2/6/2021, 10:54:07 PM [Ring] Hidden accessory 89912722-cbc5-41d7-9340-3523c509481c access-code Security Access Code
2/6/2021, 10:54:07 PM [Ring] Hidden accessory 28012dda-73dc-4c9a-a487-e0dd54ad8c3a hub.redsky Base Station
2/6/2021, 10:54:07 PM [Ring] Hidden accessory 8f38be3b-b136-4e3a-ae4a-f6668ddc2bf5 adapter.zwave Z-Wave Adapter
2/6/2021, 10:54:07 PM [Ring] Hidden accessory 629076dc-ee8d-4037-9a94-39d7508cdf7b security-keypad Kitchen Keypad
2/6/2021, 10:54:07 PM [Ring] Hidden accessory 8ce9c908-580a-4e00-a964-5fbddcc8e01f security-keypad Entryway Keypad
2/7/2021, 2:54:07 AM [Ring] Reconnecting location socket.io connection
2/7/2021, 2:54:08 AM [Ring] Creating location socket.io connection - Home
2/7/2021, 2:54:08 AM [Ring] Ring connected to socket.io server
2/7/2021, 6:54:08 AM [Ring] Reconnecting location socket.io connection
2/7/2021, 6:54:09 AM [Ring] Creating location socket.io connection - Home
2/7/2021, 6:54:10 AM [Ring] Ring connected to socket.io server
2/7/2021, 10:54:10 AM [Ring] Reconnecting location socket.io connection
2/7/2021, 10:54:11 AM [Ring] Creating location socket.io connection - Home
2/7/2021, 10:54:12 AM [Ring] Ring connected to socket.io server
2/7/2021, 11:24:27 AM [Somfy myLink] Setting position of target CC109957.2 (2nd Floor) from 0% to 100%.
2/7/2021, 11:24:28 AM [Somfy myLink] Setting position of target CC109957.1 (Living Room) from 0% to 100%.
2/7/2021, 2:54:12 PM [Ring] Reconnecting location socket.io connection
2/7/2021, 2:54:13 PM [Ring] Creating location socket.io connection - Home
2/7/2021, 2:54:13 PM [Ring] Ring connected to socket.io server
2/7/2021, 6:31:50 PM [Somfy myLink] Setting position of target CC109957.2 (2nd Floor) from 100% to 0%.
2/7/2021, 6:31:50 PM [Somfy myLink] Encountered an error setting target position of target CC109957.2 (2nd Floor): Unexpected token { in JSON at position 36
2/7/2021, 6:54:13 PM [Ring] Reconnecting location socket.io connection
2/7/2021, 6:54:14 PM [Ring] Creating location socket.io connection - Home
2/7/2021, 6:54:15 PM [Ring] Ring connected to socket.io server
2/7/2021, 7:42:14 PM [Somfy myLink] Setting position of target CC109957.1 (Living Room) from 100% to 0%.
2/7/2021, 9:43:25 PM [Somfy myLink] Setting position of target CC109957.2 (2nd Floor) from 100% to 0%.
2/7/2021, 10:54:15 PM [Ring] Reconnecting location socket.io connection
2/7/2021, 10:54:16 PM [Ring] Creating location socket.io connection - Home
2/7/2021, 10:54:17 PM [Ring] Ring connected to socket.io server
2/8/2021, 2:54:17 AM [Ring] Reconnecting location socket.io connection
2/8/2021, 2:54:18 AM [Ring] Creating location socket.io connection - Home
2/8/2021, 2:54:18 AM [Ring] Ring connected to socket.io server
2/8/2021, 6:54:18 AM [Ring] Reconnecting location socket.io connection
2/8/2021, 6:54:19 AM [Ring] Creating location socket.io connection - Home
2/8/2021, 6:54:20 AM [Ring] Ring connected to socket.io server
2/8/2021, 8:18:43 AM [Somfy myLink] Setting position of target CC109957.2 (2nd Floor) from 0% to 100%.
2/8/2021, 8:18:44 AM [Somfy myLink] Encountered an error setting target position of target CC109957.2 (2nd Floor): Unexpected token { in JSON at position 36
2/8/2021, 10:13:29 AM [Somfy myLink] Setting position of target CC109957.2 (2nd Floor) from 0% to 100%.
2/8/2021, 10:13:31 AM [Somfy myLink] Setting position of target CC109957.1 (Living Room) from 0% to 100%.
2/8/2021, 10:13:34 AM [Somfy myLink] Setting position of target CC109957.2 (2nd Floor) from 100% to 0%.
2/8/2021, 10:13:36 AM [Somfy myLink] Setting position of target CC109957.2 (2nd Floor) from 0% to 100%.
2/8/2021, 10:54:20 AM [Ring] Reconnecting location socket.io connection
2/8/2021, 10:54:21 AM [Ring] Creating location socket.io connection - Home
2/8/2021, 10:54:22 AM [Ring] Ring connected to socket.io server
2/8/2021, 10:57:39 AM [Somfy myLink] Setting position of target CC109957.2 (2nd Floor) from 100% to 0%.
2/8/2021, 10:57:55 AM [Somfy myLink] Setting position of target CC109957.2 (2nd Floor) from 0% to 100%.
2/8/2021, 10:59:38 AM [Somfy myLink] Setting position of target CC109957.1 (Living Room) from 100% to 0%.
2/8/2021, 10:59:59 AM [Somfy myLink] Setting position of target CC109957.1 (Living Room) from 0% to 100%.
2/8/2021, 2:07:16 PM [Somfy myLink] Setting position of target CC109957.1 (Living Room) from 100% to 0%.
2/8/2021, 2:09:16 PM Error: read ETIMEDOUT
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
2/8/2021, 2:09:16 PM Got SIGTERM, shutting down Bridge...
2/8/2021, 2:30:18 PM Loaded plugin 'homebridge-mylink'
2/8/2021, 2:30:18 PM [2/8/2021, 12:30:18 PM] Registering platform 'homebridge-mylink.Somfy myLink'
2/8/2021, 2:30:19 PM Loaded plugin 'homebridge-ring'
2/8/2021, 2:30:19 PM [2/8/2021, 12:30:19 PM] Registering platform 'homebridge-ring.Ring'
2/8/2021, 2:30:19 PM Loading 2 platforms...
2/8/2021, 2:30:19 PM [Somfy myLink] Initializing Somfy myLink platform...
2/8/2021, 2:30:19 PM Initializing platform accessory 'Somfy Living Room'...
2/8/2021, 2:30:19 PM Initializing platform accessory 'Somfy 2nd Floor'...
2/8/2021, 2:30:20 PM [Ring] Initializing Ring platform...
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory 41c5b1d1-2a1a-47ab-bb73-a57be64b7861 Ring Alarm
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory b3e52482-c78b-4002-9667-a975c75ca89c Front Door
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory 0ea2e671-4d94-49cd-9164-feffe56e6801 Patio Sliding Doors
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory 569251c1-b10a-436d-bb63-b4815fbf5501 Side Door
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory 4a353a89-2889-471d-92cc-e966eb5fb332 Garage Door
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory 7183582c-e613-4b84-9f68-d1a24aebf69c Second Floor Sliding Door
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory 8e209466-682d-47f0-8012-e47624fc138a Basement Window
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory 2a253c23-8b8f-4f25-b3a5-f7212b83d907 Kitchen 
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory d726cfe7-71bc-40c9-9025-256ca36f786b Smoke/CO Listener
2/8/2021, 2:30:20 PM [Ring] Configuring cached accessory 14310424-fc89-48ed-83eb-952632ae3f6f Hallway
2/8/2021, 2:30:20 PM Bridge is running on port 51826.
2/8/2021, 2:30:22 PM [Ring] Found the following locations:
2/8/2021, 2:30:22 PM [Ring]   locationId: 69387c91-f4ba-4a65-a964-4e3b7a38c7da - Home
2/8/2021, 2:30:22 PM [Ring] Creating location socket.io connection - Home
2/8/2021, 2:30:22 PM [Ring] Ring connected to socket.io server
2/8/2021, 2:30:22 PM [Ring] Configuring 0 cameras and 17 devices for location "Home" - locationId: 69387c91-f4ba-4a65-a964-4e3b7a38c7da
2/8/2021, 2:30:22 PM [Ring] Hidden accessory c459d254-9dce-4abf-96ea-fd5053963559 access-code.vault Code Vault
2/8/2021, 2:30:22 PM [Ring] Hidden accessory be334c3c-7d83-4c9d-81fb-1a893bee7ab5 adapter.zigbee ZigBee onboard adapter
2/8/2021, 2:30:23 PM [Ring] Hidden accessory 89912722-cbc5-41d7-9340-3523c509481c access-code Security Access Code
2/8/2021, 2:30:23 PM [Ring] Hidden accessory 28012dda-73dc-4c9a-a487-e0dd54ad8c3a hub.redsky Base Station
2/8/2021, 2:30:23 PM [Ring] Hidden accessory 8f38be3b-b136-4e3a-ae4a-f6668ddc2bf5 adapter.zwave Z-Wave Adapter
2/8/2021, 2:30:23 PM [Ring] Hidden accessory 629076dc-ee8d-4037-9a94-39d7508cdf7b security-keypad Kitchen Keypad
2/8/2021, 2:30:23 PM [Ring] Hidden accessory 8ce9c908-580a-4e00-a964-5fbddcc8e01f security-keypad Entryway Keypad
**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
ReAuthenticate the  refresh token.
