### ISSUE TITLE
HOOBS won't boot

### ISSUE THREAD

**Issue by rnewhart** [hoobs-org/HOOBS#1082]
**Description**
I unplug my HOOBS box and plug back in.  I cannot access hoobs.local.   Is there a way to reset the box?  Lights are on at ethernet port so there is power

**Comment by mkellsy** [comment]
You can try http://hoobs or http://hoobs.lan
If these don't work see if you can get the ip address from your router and access it with http://192.168.x.x

**Comment by rnewhart** [comment]
nope.  It also does not show up in my eero wifi.  The only hard wired device is my lutron device.  It's like the software is corrupt and it will not boot.  I was hoping there was a way to reset it.

**Comment by mkellsy** [comment]
Check your phone. Is it seeing a HOOBS WiFi signal?

**Comment by jefmedia1** [comment]
I think the issue I just posted about, are related to this same problem. Although my unit does show up on my router with an ip address I cannot get to it thru hoobs.local or hoobs.lan, now it refused to connect on the ip address also. I was able to get to it one time that way, but no longer.

**Comment by mkellsy** [comment]
Try plugging in a monitor and see if Linux is booting.

**Comment by rnewhart** [comment]
How do I plug in a monitor?  the hoobs device only has a power cord and an ethernet cable.

**Comment by mkellsy** [comment]
You will have to open the case. There is an HDMO port inside.

**Comment by askovi** [comment]
You don’t need to plug in a screen. Just connect via ssh and get the logs following the instructions below. If it doesn’t connect to ssh then your microSD card is corrupted and needs to be reflashed. 

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this command: sudo hoobs service log
