### ISSUE TITLE
Stuck in restore process on Raspi

### ISSUE THREAD

**Issue by Rustydw** [hoobs-org/HOOBS#1083]
Hi folks - wonder if you can help:

**Description**
I saved a backup file .hbfx at the end of Jan on my rasp4b
I installed an access point RaspAP.com  raspap-webgui
they share port 80 so i changed Hoobs to 8008 
Now I've reinstalled Hoobs uploaded the .hbfx file and clicked system restore - it stayed on the Hoobs logo screen for over 30 mins
![image](https://user-images.githubusercontent.com/73714211/107733342-192e7c00-6cfb-11eb-8b38-9db5d2cb2b21.png)

so then I restarted the pi, tried again to start hoobs, and i just get stuck on the same screen.

**Version**
Running 3.3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version - not sure but I regularly check for updates each week etc so it would have been the previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Raspbery pi

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
{
    "server": {
        "home_setup_id": "X-HM://0023ISYWYI8M0",
        "origin": "*",
        "port": 80,
        "autostart": 0,
        "polling_seconds": 5
    },
    "client": {
        "country_code": "ES",
        "postal_code": "08001",
        "inactive_logoff": 30,
        "locale": "en",
        "temp_units": "celsius",
        "theme": "tealzier",
        "default_route": "status"
    },
    "bridge": {
        "port": 51826,
        "name": "HOOBS",
        "pin": "031-45-154",
        "username": "7C:49:81:DE:AC:D4"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-dyson-pure-cool",
        "homebridge-blink-for-home",
        "homebridge-govee",
        "homebridge-alexa",
        "homebridge-samsung-tizen",
        "homebridge-zp",
        "homebridge-hue"
    ],
    "accessories": [],
    "platforms": [
        {
            "devices": [
                {
                    "ipAddress": "192.169.4.31",
                    "isJetFocusEnabled": true,
                    "serialNumber": "A1B-EU-NGA0702A",
                    "enableOscillationWhenActivating": false,
                    "isFullRangeHumidity": true,
                    "isSingleAccessoryModeEnabled": false,
                    "isHumiditySensorEnabled": true,
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": true,
                    "isAirQualitySensorEnabled": true,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isHeatingDisabled": false,
                    "credentials": "",
                    "isContinuousMonitoringEnabled": true,
                    "isTemperatureSensorEnabled": true
                }
            ],
            "password": "xxx",
            "name": "pure cool",
            "username": "rusty",
            "plugin_map": {
                "plugin_name": "homebridge-dyson-pure-cool"
            },
            "platform": "DysonPureCoolPlatform",
            "countryCode": "ES"
        },
        {
            "platform": "Blink",
            "avoid-thumbnail-battery-drain": false,
            "name": "Blink",
            "enable-verbose-logging": false,
            "username": "rusty",
            "enable-liveview": true,
            "plugin_map": {
                "plugin_name": "homebridge-blink-for-home"
            },
            "enable-startup-diagnostic": true,
            "hide-privacy-switch": false,
            "password": "",
            "pin": ,
            "enable-debug-logging": true,
            "camera-status-polling-seconds": 59
        },
        {
            "plugin_map": {
                "plugin_name": "homebridge-govee"
            },
            "refreshTime": 15,
            "name": "Govee",
            "apiKey": "32d3e56-83de-4f0f-84ff-53f5445d6482",
            "platform": "Govee"
        },
        {
            "door": false,
            "routines": false,
            "platform": "Alexa",
            "username": "",
            "name": "Alexa",
            "filter": "192.168.4.120:80",
            "password": "",
            "plugin_map": {
                "plugin_name": "homebridge-alexa"
            },
            "blind": false,
            "deviceListHandling": "allow",
            "pin": "031-45-154",
            "debug": false
        },
        {
            "devices": [
                {
                    "name": "Rusty-TV"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "name": "SamsungTizen",
            "platform": "SamsungTizen",
            "app_list": true
        },
        {
            "service": "speaker",
            "plugin_map": {
                "plugin_name": "homebridge-zp"
            },
            "name": "Sonos",
            "platform": "ZP"
        },
        {
            "hueMotionTemperatureHistory": false,
            "sensors": true,
            "resource": false,
            "scenesAsSwitch": false,
            "nativeHomeKitSensors": true,
            "group0": false,
            "forceHttp": false,
            "effects": false,
            "forceEveWeather": false,
            "wallSwitch": false,
            "anyOn": false,
            "users": {
                "ECB5FAFFFE02A018": "3mSIsFMRRXSOF2vhmDuMtS9qgUux13AUUyYoy2cE"
            },
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "rooms": false,
            "rules": false,
            "hueDimmerRepeat": false,
            "noResponse": true,
            "platform": "Hue",
            "schedules": false,
            "groups": false,
            "name": "Hue",
            "linkButton": false,
            "configuredName": false,
            "lights": true,
            "nativeHomeKitLights": true,
            "scenes": false
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}

**Post your log**
You can get the log from the intercafe. This is in the Log section.
Can't access the latest logs but the ones from before are below

```
POST LOG HERE
```

**Comment by EddieDSuza** [comment]
SSH into your HOOBS service and `type sudo hoobs service log`

then post the log here

**Comment by Rustydw** [comment]
[logforHoobs.txt](https://github.com/hoobs-org/HOOBS/files/6064959/logforHoobs.txt)

sorry for delay - here's the log

**Comment by askovi** [comment]
In your logs HOOBS is still configured to run on port 80. Make sure to edit the config file with `sudo nano /home/hoobs/.hoobs/etc/config.json` and change the server port from 80 to 8080 then save with ctrl + s then exit the file with ctrl + x. Then restart the service with `sudo hoobs service restart` and access it via http://hoobs.local:8080

**Comment by Rustydw** [comment]
thank you - it started working (the UI) for a bit, but the service never started. so I ran the hoobs -D to debug and it told me it was missing all the plugins.

I installed all the plugins, restarted and now get stuck at the login screen for rasp OS. I enter the password and it asks for it again.
So I switched to terminal and get the attached notes - telling me i've not got to change module 83 for 64.
So I ran over to the node website got the details and entered:
`sudo curl -k https://nodejs.org/dist/v10.22.1/node-v10.22.1-linux-armv7l.tar.gz | sudo tar -xz -C /usr/local --strip-components=1 --no-same-owner`
that fixed the first error of 'wrong module version' but now I need to change 64 to 72 - I tried to update/upgrade node and npm - but that didn't work - do I have to go thru and change each node one by one?
[logforHoobs3.txt](https://github.com/hoobs-org/HOOBS/files/6069946/logforHoobs3.txt)

**Comment by Rustydw** [comment]
So I took a little shimmy around the internet and found an article in a homebridge section (I can't remember where sorry and it doesn't seem to be showing up in my history now. 
Anyway - it said to revert the usr/local section in line 27 to what it was originally (and luckily gave that info.)
Then it said to go to line 52 ot something and add three IFs as they were missing?
So I copied what he said to do and i can now get thru to the OS desktop.
HOOBs won't run, I've done many restarts along with these changes:
`pinhole -r
sudo wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset 
sudo hoobs upgrade
sudo hoobs service start
sudo hoobs service enable
sudo raspi-config` (to make sure the time stamps are all correct!)

how can i get it to run now?
[log3.txt](https://github.com/hoobs-org/HOOBS/files/6075487/log3.txt)
thanks again guys!

**Comment by Rustydw** [comment]
hi guys, any suggestions?

**Comment by mkellsy** [comment]
It looks like when you restore, the plugins aren't being installed.

After you restore go to
```
cd ~/.hoobs
```

And then run this
```
npm install
```

See it that helps.

The other thing you can do is to restore manually. The .hbfx file is just a .zip file. If you rename the extension you can uncompress and extract the etc/config.json file.

You can then install the plugins on a fresh bridge. Then copy over the config.json file.
