### ISSUE TITLE
Unable to access HOOBS in a Box after initial setup

### ISSUE THREAD

**Issue by jefmedia1** [hoobs-org/HOOBS#1085]
I was never able to get to the HOOBS in a Box via hoobs.local or hoobs.lan. So finally got to it via ip address, was able to configure admin and install a plugin for Hubitat. From that point forward no way to get to the HinaB. Router sees the device, and I was able to assign a static ip address thru MAC reservation. When I go to the unit via ip address, it now gives me a connection refused. Downloaded Homemanager and it cannot find the server on the network. I have deleted the it from my Apple Home. Not sure what else to do. I cannot find a reset button on the unit. Also I don't see HOOBS WiFi signal on my iPhone.

**Comment by EddieDSuza** [comment]
Your router does not support mDNS - that's the reason you can only access the UI using the IP address. 

Power cycle the device making sure the Ethernet cable first.. Then - 

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this command: sudo hoobs service log
3. Post logs here
