### ISSUE TITLE
hoobs.local not working

### ISSUE THREAD

**Issue by dharmony44** [hoobs-org/HOOBS#1086]
**Description**
hoobs.local not working or loading.  Looking online this seems to be an ongoing issue.  I bought this because I am new and this was suppose to be fool proof.  But I am already wishing I didn't buy this.  Plus other users are saying it was working fine but all of a sudden stopped.  Is this what I have to look forward to?  

**Version**
Not sure just got it last night.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No
- [x ] Don't Know

**Pervious version**
If you upgraded, please let us know your previous version.
New out of the box

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
Please reach out to info@hoobs.org and we can offer a remote session to fix the issue.

**Comment by abbeycode** [comment]
the hoobs.local name won't load for me either, but I can browse to its IP address. Should I email info@hoobs.org to set up a remote session?
