### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory:

### ISSUE THREAD

**Issue by jamaalmck** [hoobs-org/HOOBS#1088]
Hi there, I'm having a hard time trying to figure this one out. I'm, pretty sure I might hav just overlooked something but for the life of me can't figure out what. I've used Homebridge UI installed directly on my desktop and it worked fine, but now that I'm using it on a HOOBS box, i'm getting this error. (I've completely uninstalled Homebridge UI via terminal before I set up the HOOBs Box)

Only Plugins are Vivint and SimpliSafe 

Log is attached. Any assistance here would be great, thanks.  

![Screen Shot 2021-02-14 at 9 51 37 PM](https://user-images.githubusercontent.com/79069283/107900373-d3e29800-6f0e-11eb-8fb6-9da16fb5da80.png)

**Comment by EddieDSuza** [comment]
Go to Configuration > Apple Home > Change the Service Name value.

Restart service
