### ISSUE TITLE
New HSLF-1 Box intermittent access

### ISSUE THREAD

**Issue by duderest** [hoobs-org/HOOBS#1089]
I received my new Hoobs in a Box yesterday, and it's been nothing but a source of frustration.  Out of the box I was unable to connect with it for several hours.  I let it run over night, and in the morning I was able to access it.  I set up a user account and updated the software, installed Homemanager on my phone and was able to access the server.  Now it's down again.  On the Homemanager app it simply reports "client errors".  When I try to access from my web browser(using IP address because hoobs.local does not resolve, it fails to open the page.  The lights on the box under the ethernet port are left solid red or orange (I'm color blind) and right flashing green.

When I arp-a from terminal I see this:
? (192.168.2.54) at (incomplete) on en0 ifscope [ethernet]

When I ran the same arp during the short window when it was working I got this:
(192.168.2.54) at b8:27:eb:fc:35:fc on en0 ifscope [ethernet]

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
What ever it shipped with when it was built last month.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box

**List your plugins**
Have been unable to access the box long enough to install a single plugin.

**Post your config**
Cannot access to post the config file

**Post your log**
Cannot access to post log file

**Additional context**
hoops.local does not resolve.  I access the box via the IP address.

**Comment by EddieDSuza** [comment]
f you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)
