### ISSUE TITLE
Bridge Service Stopping

### ISSUE THREAD

**Issue by aaronlikeshoobs** [hoobs-org/HOOBS#1091]
**Description**
Every few days and for no apparent reason my bridge service stops running. I can connect to the Hoobs and restart it without issue, but why is it stopping? 

**Version**
3.3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
Whatever the Hoobs in a box is currently shipping with. 

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Homebridge 

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Please check your logs when it stops. It will tell you the issue. It most likely is caused by a plugin.

**Comment by aaronlikeshoobs** [comment]
Can you tell me how to check the logs? I will do that the next time it stops.
And I am only running 1 plugin which is HomeBridge which is certified by Hoobs.

**Comment by askovi** [comment]
Click on the logs icon in the left menu

**Comment by aaronlikeshoobs** [comment]
Here is the portion of the logs that deals with the shutdown I experienced this morning:

/18/2021, 9:54:43 AM [Harmony] (Harmony)WARNING - socket closed
2/18/2021, 9:54:53 AM [Harmony] INFO - starting hub discovery
2/18/2021, 9:54:54 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2/18/2021, 9:54:54 AM Got SIGTERM, shutting down Bridge...
2/18/2021, 9:54:55 AM [Harmony] INFO - shutdown
2/18/2021, 9:54:55 AM [Harmony] INFO - shutdown
2/18/2021, 9:54:55 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2/18/2021, 9:54:56 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2/18/2021, 9:54:57 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2/18/2021, 9:58:06 AM Loaded plugin 'homebridge-harmony'
2/18/2021, 9:58:06 AM [2/18/2021, 10:58:06 AM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
2/18/2021, 9:58:06 AM Loading 1 platforms...
2/18/2021, 9:58:06 AM [Harmony] Initializing HarmonyHubWebSocket platform...
2/18/2021, 9:58:06 AM [Harmony] HarmonyPlatform Init
2/18/2021, 9:58:06 AM [Harmony] DidFinishLaunching
2/18/2021, 9:58:06 AM [Harmony] WARNING - Removing Accessories
2/18/2021, 9:58:06 AM [Harmony] (Harmony)INFO - Loading activities...
2/18/2021, 9:58:06 AM [Harmony] INFO - starting hub discovery
2/18/2021, 9:58:06 AM Bridge is running on port 51826.
2/18/2021, 9:58:12 AM [Harmony] INFO - stopping hub discovery, hubs found : 192.168.4.21|Harmony Hub|10517066
2/18/2021, 9:58:12 AM [Harmony] (Harmony)INFO - received discovered hubs  192.168.4.21|Harmony Hub|10517066
