### ISSUE TITLE
Default Room

### ISSUE THREAD

**Issue by aaronlikeshoobs** [hoobs-org/HOOBS#1092]
**Description**

when my device or bridge service reboots all switches revert back to a default room. How can I lock them to a room?

**Version**
Please include the version of HOOBS you are using.

3.3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
Does this happen to your Wifi or Zigbee devices

**Comment by aaronlikeshoobs** [comment]
It happens to the devices being controlled by my Harmony hub, which is primarily an audio receiver that is not on the network.

**Comment by EddieDSuza** [comment]
When that happens or any disconnection with your network... check the logs to fix the issue

**Comment by aaronlikeshoobs** [comment]
I am not aware of any network disconnection, but could hardwire the Hoobs box instead of wireless if you think it would help.
What am I looking for in the logs?

Thank you,
Aaron

**Comment by EddieDSuza** [comment]
Hardwire the HOOBS Box to your network, And if there are any devices that drop off the network - the plugin for the device will report it in the log.

**Comment by aaronlikeshoobs** [comment]
Okay, will do. I’ll report back if there are any further issues. Thank you.

**Comment by aaronlikeshoobs** [comment]
Hoobs is now hardwired. Can you tell me how to turn off the WiFi as it is now connected via both WiFi and wired.

Thank you,
Aaron

**Comment by EddieDSuza** [comment]
Once its hardwire - it will turn off the wifi

**Comment by aaronlikeshoobs** [comment]
After how long?

**Comment by EddieDSuza** [comment]
Its done automatically. Once connected Ethernet - it stops broadcasting its wifi signal

**Comment by aaronlikeshoobs** [comment]
Showing on my Eero that both connections are still active. How do I force disable the WiFi?

**Comment by aaronlikeshoobs** [comment]
Also are you able to help m with the other issue. Any time the Hoobs device, the Internet or the Harmony reboot, it resets all my accessories / switches in HomeKit to their default settings. How do I “lock” my personalized settings - such as room and device / switch name - into Hoobs?

Thank you!

**Comment by aaronlikeshoobs** [comment]
My bridge service keeps stopping on its own. Here’s my log. What’s causing this?

2/28/2021, 2:17:21 AM [Harmony] (Harmony)WARNING - socket closed
2/28/2021, 2:17:31 AM [Harmony] INFO - starting hub discovery
2/28/2021, 2:17:32 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2/28/2021, 2:17:32 AM Got SIGTERM, shutting down Bridge...
2/28/2021, 2:17:32 AM [Harmony] INFO - shutdown
2/28/2021, 2:17:32 AM [Harmony] INFO - shutdown
2/28/2021, 2:17:33 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2/28/2021, 2:17:34 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2/28/2021, 2:17:35 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
