### ISSUE TITLE
Homebridge service not running

### ISSUE THREAD

**Issue by vincentb007** [hoobs-org/HOOBS#1094]
**Description**
Homebridge service need to be restarted several times per day. Platform very unstable.

**Version**
Hoobs version 3.3.2

**Did you upgrade**

- [X ] Yes
- [ ] No

**Pervious version**
Initial version 3.3.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Ring (Certified)
Nest (Certified)
Deebotecovacs

**Post your config**
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY2FOG",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "fr",
        "temp_units": "celsius",
        "country_code": "BE",
        "postal_code": "5230"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "DF:F6:2A:EF:ED:3F"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "XXXXXXXXXXXXXXX"
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Thermostat",
            "googleAuth": {
                "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?XXXXXXXXXXXXXXXXXXXXX",
                "apiKey": "AIzaXXXXXXXXXXXXXXXXXX"
            }
        },
        {
            "platform": "DeebotEcovacs",
            "plugin_map": {
                "plugin_name": "homebridge-deebotecovacs"
            },
            "refreshTimer": 300,
            "publishBipSwitch": true,
            "publishSwitch": true,
            "publishFan": true,
            "publishMotionDetector": true,
            "publishAutoSwitch": true,
            "publishEdgeSwitch": true,
            "publishSpotSwitch": true,
            "email": "xxxxxx@xxxxx.com",
            "password": "xxxxxxxx",
            "countryCode": "BE"
        }
    ]
}

**Post your log**
You can get the log from the intercafe. This is in the Log section.

19/02/2021 à 16:22:34 HOOBS listening on port 80.
19/02/2021 à 16:22:39 Loaded plugin 'homebridge-deebotecovacs'
19/02/2021 à 16:22:39 [2/19/2021, 8:22:39 AM] Registering platform 'homebridge-deebotecovacs.DeebotEcovacs'
19/02/2021 à 16:22:40 Loaded plugin 'homebridge-nest'
19/02/2021 à 16:22:40 [2/19/2021, 8:22:40 AM] Registering platform 'homebridge-nest.Nest'
19/02/2021 à 16:22:42 Loaded plugin 'homebridge-ring'
19/02/2021 à 16:22:42 [2/19/2021, 8:22:42 AM] Registering platform 'homebridge-ring.Ring'
19/02/2021 à 16:22:42 Loading 3 platforms...
19/02/2021 à 16:22:42 [Ring] Initializing Ring platform...
19/02/2021 à 16:22:43 [Thermostat] Initializing Nest platform...
19/02/2021 à 16:22:43 [DeebotEcovacs] Initializing DeebotEcovacs platform...
19/02/2021 à 16:22:43 [DeebotEcovacs] INFO - API :EU/BE
19/02/2021 à 16:22:43 [Ring] Configuring cached accessory ea02e2ee-9b5c-4038-b2b9-d12106071dfa Porte d'entrée
19/02/2021 à 16:22:43 [Ring] Configuring cached accessory 5ad82937-68a1-4dca-90f8-8223575fdff0 Sombreffe Mode
19/02/2021 à 16:22:43 [Thermostat] Fetching Nest devices.
19/02/2021 à 16:22:43 [DeebotEcovacs] DidFinishLaunching
19/02/2021 à 16:22:43 Bridge is running on port 51826.
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - stopping deebots discovery, number of deebots found : 1
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - Discovered Deebot : Zyggy 
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - Edge Cleaning for Zyggy  : false
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - Spot Cleaning for Zyggy  : false
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - SpotArea Cleaning for Zyggy  : true
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - CustomArea Cleaning for Zyggy  : true
19/02/2021 à 16:22:46 [Ring] Found the following locations:
19/02/2021 à 16:22:46 [Ring]   locationId: f780a2ae-e17e-47a4-ada4-0144052b9546 - Sombreffe
19/02/2021 à 16:22:47 [Ring] Configuring 1 cameras and 2 devices for location "Sombreffe" - locationId: f780a2ae-e17e-47a4-ada4-0144052b9546
19/02/2021 à 16:22:49 [Thermostat] initing thermostat "Dining Room Thermostat": deviceId: 09AA01AC451901WB structureId: 65cd2532-1d04-11eb-b0fa-12fc5ba0e7ab
19/02/2021 à 16:22:49 [Thermostat] initing home_away_sensor "Home Occupied": deviceId: 65cd2532-1d04-11eb-b0fa-12fc5ba0e7ab structureId: 65cd2532-1d04-11eb-b0fa-12fc5ba0e7ab
```


**Additional context**
Add any other context about the problem here.

**Comment by bwp91** [comment]
Hey.
When you say HOOBS needs to be restarted, why does it need to be restarted?
Unfortunately nothing in your logs seems to give a clue as to any problems.
Ideally you’d need to post your logs when an issue occurs ie at the point of HOOBS needing to be restarted.

**Comment by vincentb007** [comment]
Hi Ben,

In the Hoobs dashboard, the frame related to the Homebridge is empty with the message: "Homebridge is not running."

You can see below the logs after the service became unavailable:

19/02/2021 à 16:22:34 HOOBS listening on port 80.
19/02/2021 à 16:22:39 Loaded plugin 'homebridge-deebotecovacs'
19/02/2021 à 16:22:39 [2/19/2021, 8:22:39 AM] Registering platform 'homebridge-deebotecovacs.DeebotEcovacs'
19/02/2021 à 16:22:40 Loaded plugin 'homebridge-nest'
19/02/2021 à 16:22:40 [2/19/2021, 8:22:40 AM] Registering platform 'homebridge-nest.Nest'
19/02/2021 à 16:22:42 Loaded plugin 'homebridge-ring'
19/02/2021 à 16:22:42 [2/19/2021, 8:22:42 AM] Registering platform 'homebridge-ring.Ring'
19/02/2021 à 16:22:42 Loading 3 platforms...
19/02/2021 à 16:22:42 [Ring] Initializing Ring platform...
19/02/2021 à 16:22:43 [Thermostat] Initializing Nest platform...
19/02/2021 à 16:22:43 [DeebotEcovacs] Initializing DeebotEcovacs platform...
19/02/2021 à 16:22:43 [DeebotEcovacs] INFO - API :EU/BE
19/02/2021 à 16:22:43 [Ring] Configuring cached accessory ea02e2ee-9b5c-4038-b2b9-d12106071dfa Porte d'entrée
19/02/2021 à 16:22:43 [Ring] Configuring cached accessory 5ad82937-68a1-4dca-90f8-8223575fdff0 Sombreffe Mode
19/02/2021 à 16:22:43 [Thermostat] Fetching Nest devices.
19/02/2021 à 16:22:43 [DeebotEcovacs] DidFinishLaunching
19/02/2021 à 16:22:43 Bridge is running on port 51826.
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - stopping deebots discovery, number of deebots found : 1
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - Discovered Deebot : Zyggy 
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - Edge Cleaning for Zyggy  : false
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - Spot Cleaning for Zyggy  : false
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - SpotArea Cleaning for Zyggy  : true
19/02/2021 à 16:22:46 [DeebotEcovacs] INFO - CustomArea Cleaning for Zyggy  : true
19/02/2021 à 16:22:46 [Ring] Found the following locations:
19/02/2021 à 16:22:46 [Ring]   locationId: f780a2ae-e17e-47a4-ada4-0144052b9546 - Sombreffe
19/02/2021 à 16:22:47 [Ring] Configuring 1 cameras and 2 devices for location "Sombreffe" - locationId: f780a2ae-e17e-47a4-ada4-0144052b9546
19/02/2021 à 16:22:49 [Thermostat] initing thermostat "Dining Room Thermostat": deviceId: 09AA01AC451901WB structureId: 65cd2532-1d04-11eb-b0fa-12fc5ba0e7ab
19/02/2021 à 16:22:49 [Thermostat] initing home_away_sensor "Home Occupied": deviceId: 65cd2532-1d04-11eb-b0fa-12fc5ba0e7ab structureId: 65cd2532-1d04-11eb-b0fa-12fc5ba0e7ab
19/02/2021 à 16:55:20 [Ring] Porte d'entrée Detected Motion
19/02/2021 à 17:34:34 [Ring] Porte d'entrée Detected Motion
19/02/2021 à 17:37:13 [Ring] Porte d'entrée Detected Motion
19/02/2021 à 17:54:41 [Ring] Porte d'entrée Detected Motion

**Comment by bwp91** [comment]
But again these are logs from **after** something has happened on a restart.
We need the logs of ideally what is going on from  **before** something goes wrong

**Comment by vincentb007** [comment]
No, I didn't yet restarted the service.
Can I provide logs from other logfiles ?

**Comment by MacFlagg** [comment]
This same issue is happening to me. 1-2 times a day, all my homebridge devices will become unresponsive. When I login to HOOBS, it says service is not running. I’ll restart the service and it’ll happen again in 8-12 hours.

this issue began about 2 weeks ago. It’s 03/06/2021 today.

any help would be greatly appreciated.
