### ISSUE TITLE
My Hoobs isn’t working

### ISSUE THREAD

**Issue by Superthugs** [hoobs-org/HOOBS#1095]
**Description**
I am not able to logon to Hoobs.local and my home kit does not recognize any of my accessories. 

**Version**
I am not sure.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Rhomba 
Ring

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
I am not sure

* Remove any passwords from the config file. This is public.

```
I am not sure.
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Add any other context about the problem here. Thank you.

**Comment by HolyHacker** [comment]
have the same issue after power was down

**Comment by Superthugs** [comment]
Are you using a PC or Mac? I don't know what to do!

**Comment by askovi** [comment]
If you don't see any network activity on your ethernet port on the HOOBS Box after a sudden power loss, it could have corrupted the microSD card and will require reflashing. 
This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

**Comment by Superthugs** [comment]
I need help accessing http://Hoobs.local

**Comment by askovi** [comment]
@Superthugs please check your router's admin page for the local ip address assigned to HOOBS and try to connect to it in your browser like this: http://192.168.x.x

If that doesn't work and you require remote assistance, please send an email to info@hoobs.org with your order number and reference this issue.

**Comment by Superthugs** [comment]
I was able to login and now when I search for plugins I get no results. The ring plugin Shiuld be there. Can you help?

**Comment by Superthugs** [comment]
OkY so now I can't update any of my plugins and I cannot uninstall the MyQ plugin. Please assist.
