### ISSUE TITLE
Node Update?

### ISSUE THREAD

**Issue by mikeB2210** [hoobs-org/HOOBS#1096]
Hi,
I tried to update "Node" with this command:

wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts

Now Hoobs shows the Nopde Version 14.15.1 but the latest LTS is 14.15.5

how can I update to 14.15.5?

**Comment by bwp91** [comment]
Hey use this in the HOOBS terminal:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 14.15.5`

At the very beginning it might say it's installing a different version of node, but once it's finished you'll see that 14.15.5 has been installed

**Comment by resgroupmsr** [comment]
> Hey use this in the HOOBS terminal:
> 
> `wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 14.15.5`
> 
> At the very beginning it might say it's installing a different version of node, but once it's finished you'll see that 14.15.5 has been installed

This seemed to work and saw that node 14.15.5 had been installed but then device rebooted and now I cannot get back onto HOOBS.  I see my RPi on the network.  Any ideas?

**Comment by resgroupmsr** [comment]
> > Hey use this in the HOOBS terminal:
> > `wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 14.15.5`
> > At the very beginning it might say it's installing a different version of node, but once it's finished you'll see that 14.15.5 has been installed
> 
> This seemed to work and saw that node 14.15.5 had been installed but then device rebooted and now I cannot get back onto HOOBS. I see my RPi on the network. Any ideas?

Ignore this.  Managed via SSH to get it back up and running.

**Comment by mkellsy** [comment]
I updated the install script so this will work.
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```
