### ISSUE TITLE
Update to Homebridge Version 1.3.0

### ISSUE THREAD

**Issue by MasterofKungfu9999** [hoobs-org/HOOBS#1097]
Hello guys,

I would like to ask if you plan to integrate Homebridge 1.3.0 in Hoobs because some newer Plugin versions do not work with the Old Homebridge.

**Comment by askovi** [comment]
This is coming in HOOBS 4 which is currently being tested internally. 
The official hb version is still 1.1.7. All plugins will work correctly on it. If you have a specific issue with a plugin please let us know.

**Comment by MasterofKungfu9999** [comment]
Ok, i habe issus with two plugins: openwebif TV and Blink for Home. These two plugins need in their new Version homebridge 1.3

**Comment by mkellsy** [comment]
We will update HOOBS 3 to 1.3 next week. HB was only released a few days ago, and needs a bit of testing on our end.
HB 1.3 will also be in HOOBS 4 which will hit beta next week too.

**Comment by sahotanick** [comment]
> This is coming in HOOBS 4 which is currently being tested internally.
> The official hb version is still 1.1.7. All plugins will work correctly on it. If you have a specific issue with a plugin please let us know.

Hi, I’m having issues with Tahoma plugin it’s asking for new version of homebridge. I am guessing version 3.3.5 has the latest version of homebridge?

**Comment by bwp91** [comment]
> Hi, I’m having issues with Tahoma plugin it’s asking for new version of homebridge. I am guessing version 3.3.5 has the latest version of homebridge?

HOOBS 3.3.5 has Homebridge 1.3.3

homebridge-tahoma (I assume this is the plugin in question) says it requires homebridge >=1.3.0 so HOOBS 3.3.5 does satisfy this

**Comment by sahotanick** [comment]
Thank you for your response 👍🏽
