### ISSUE TITLE
Cannot remove depreciated SmartThings V2

### ISSUE THREAD

**Issue by twennywonn** [hoobs-org/HOOBS#1098]
**Description**
A clear and concise description of what the plugin is doing.

Unable to remove the plugin.  The error I get is:

2/20/2021, 10:54:36 PM npm
2/20/2021, 10:54:36 PM  ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/snyk-resolve-deps/node_modules/.bin/semver
2/20/2021, 10:54:36 PM npm
2/20/2021, 10:54:36 PM ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/snyk-resolve-deps/node_modules/.bin/semver: is outside /home/hoobs/.hoobs/node_modules/snyk-resolve-deps/node_modules/semver and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/snyk-resolve-deps/node_modules/.bin/semver
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
2/20/2021, 10:54:37 PM 
2/20/2021, 10:54:37 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-02-21T04_54_36_521Z-debug.log

**Expected behavoir**
Please let us know what the plugin is supposed to do.

Im just looking to fully remove it so I can use the updated plugin

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.

SmartThings V2

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.

Hoobs 3.3.2

Node 14.15.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://c",
        "polling_seconds": 2,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "c"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "CC:22:3D:E3:CE:30",
        "port": c,
        "pin": "c-c-c"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [
        {
            "name": "Ring Alarm",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "accessory": "DummySwitch"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "name": "Door Auto Lock"
        }
    ],
    "platforms": [
        {
            "name": "Harmony Purifier",
            "hubIP": "192.168.1.58",
            "otherPlatforms": [
                {
                    "name": "Harmony Living Room",
                    "hubIP": "192.168.1.59"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        },
        {
            "platform": "SmartThings-v2",
            "name": "SmartThings-v2",
            "app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "a1529b34-3d60-c-a692-c",
            "access_token": "c-c-c-9cc2-c",
            "temperature_unit": "F",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": false,
                "hideTimestamp": false,
                "hideNamePrefix": false,
                "file": {
                    "enabled": true,
                    "level": "Good"
                }
            },
            "plugin_map": {
                "plugin_name": "homebridge-smartthings-v2"
            },
            "direct_port": 8000,
            "local_commands": true
        },
        {
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq"
            },
            "password": "ccc",
            "email": "ccc@gmail.com"
        }
    ]
}

**Additional context**

**Comment by askovi** [comment]
Looks like the plugin got stuck. Here's how you can remove it manually.

1. Open the HOOBS terminal from the top right menu
2. type: `sudo nano /home/hoobs/.hoobs/package.json`
3. Using the down arrow scroll down to the line with the plugin name and its version inside the dependencies object and delete it. It looks something like `"homebridge-smartthings-v2": "^x.x.x",` . Remove the entire line including the comma at the end. 
4. Press ctrl + S to save then ctrl + X to exit the editor. 
5. Click the top right menu and click restart service.
