### ISSUE TITLE
integrated plugins

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#11]
we need this preinstalled and seamless integrated in the ui

FFMPEG https://github.com/legotheboss/homebridge-camera-ffmpeg-omx
Homebridge-lib https://github.com/ebaauw/homebridge-lib
HAP-Alexa https://github.com/NorthernMan54/homebridge-alexa
Homebridge-Google-Smart-Home https://github.com/oznu/homebridge-gsh

**Comment by mkellsy** [comment]
Homebridge-lib doesn't get installed into the core. It is for the individual plugins. We don't need to include this. I am releasing this under @hoobs so we can adjust it for our needs.

**Comment by mkellsy** [comment]
With the certified plugins program, installing these plugins is even easier. I don't think we need to pre-install them.
