### ISSUE TITLE
Unable to Update Beta Build on 3.0.0 beta 28

### ISSUE THREAD

**Issue by sachangregory** [hoobs-org/HOOBS#110]

**Comment by BobbySlope** [comment]
please provide more information

**Comment by sachangregory** [comment]
Whenever I go to hoobs.local is says that is HOOBS is up to date but I'm on Beta 28 still

**Comment by mkellsy** [comment]
That's because the beta is not released. The update runs off of official releases. To upgrade the beta you need to run this

```sh
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by mkellsy** [comment]
I am moving this to use NPM versions instead of GitHub releases.

**Comment by sachangregory** [comment]
oh... have I been living under a rock or was this not announced

**Comment by mkellsy** [comment]
It's in beta. We were going to run this off of releases. A beta is not a release.

Anyway I am removing that restriction, so the update will work for beta versions too.

Done in 3.0.0-beta.37
