### ISSUE TITLE
can't install on Rasbian via command line

### ISSUE THREAD

**Issue by hermsdad** [hoobs-org/HOOBS#1102]
I tried to install hoobs on my mac mini which is now running Raspberry pi desktop as the OS. I ran 
wget -q -O - http://bit.ly/get-hoobs | sudo bash -

and got the following errors.

Thank You for choosing HOOBS
================================================================================
Node Version 
Updating Repositories
Hit:1 http://ftp.debian.org/debian buster InRelease
Hit:2 http://ftp.debian.org/debian buster-updates InRelease                    
Hit:3 http://security.debian.org buster/updates InRelease                      
Hit:4 http://packages.microsoft.com/repos/code stable InRelease                
Hit:5 http://archive.raspberrypi.org/debian buster InRelease                   
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u1).
git is already the newest version (1:2.20.1-2+deb10u3).
tar is already the newest version (1.30+dfsg-6).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
/usr/bin/env: ‘node’: No such file or directory
/usr/bin/env: ‘node’: No such file or directory
/usr/bin/env: ‘node’: No such file or directory
main: line 116: /usr/bin/node: No such file or directory

I checked the folders and "node" exists in /usr/bin/env
I'd paste the results of ls but it's rather lengthy. 

I just randomly tried this:
ln -s /usr/bin/env /usr/bin/node
ln: failed to create symbolic link '/usr/bin/node': File exists

Anybody have any ideas?

**Comment by askovi** [comment]
Try with this command, it will also take care of node:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

**Comment by hermsdad** [comment]
This may be the trick but I'm not sure. I started from scratch again with a new raspbian/debian image. I manually ran each section of the install script and had to force a specific version of node. I had to start at 10 and then move up to 12 with node. I was also banging my head because I didn't reboot after I got Hoobs to install.

**Comment by hermsdad** [comment]
That didn't work. Here's what worked for me so hopefully others can benefit from this. 
This is for a fresh install of Raspberry Pi on a mac mini. After the install of the OS from a USB go to root user so first set a root pwd:

sudo passwd root

go to root user 
su
cd ~

then upgrade Debian:

sudo apt-get update
sudo apt-get dist-upgrade

Install root user Hoobs:

adduser hoobs

then:

sudo /usr/sbin/usermod -a -G sudo hoobs

Add no passwd line to sudoers: 
sudo visudo

change this line:
%sudo ALL=(ALL:ALL) ALL
to:
%sudo ALL=(ALL:ALL) NOPASSWD:ALL

then set hostname to whatever you want:
nano /etc/hostname

reboot

then go back to root:
su
cd ~
then run:
apt-get install -y nodejs npmorsudo apt install nodejs npm

Node will be 10.24.0 which appears to be the only node that works with installing hoobs. You can upgrade to 12 later but don't do it just yet! Nodejs 12 appears to be necessary when you want to run zigbee2mqtt, which is what I am ultimately trying to do with a Conbee II stick. Still don't have this sorted out yet.

then run hoobs install:
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 10.24.0
when it's finished:
reboot

That should do it. I hope this helps someone trying to do the same. Would be nice to see this in the install instructions on hoobs FAQ's or install instructions.

**Comment by hermsdad** [comment]
Another update for others out there. For whatever reason I couldn't update node beyond 10.24.0 with the normal update methods. I started from scratch yet again and installed node 14.16.0 from source. 14.16.0 is required if you want to run zigbee2mqtt and a conbee ii. 
To install from source start with:
cd /usr/local/src
sudo mkdir node
cd node
sudo wget http://nodejs.org/dist/v14.16.0/node-v14.16.0.tar.gz
sudo tar -xzf node-v14.16.0.tar.gz

then:
cd node-v14.16.0/
sudo ./configure
sudo make -j4
sudo make install

then you can move on to installing hoobs, just make sure you change the node version in the install script.
Keep in mind I am starting with a fresh install of Debian/Raspberry Pi Desktop on a 2012 Mac Mini. I updated all OS software before starting to install node and npm, then hoobs, then mosquitto, then zigbee2mqtt. Once I got the node problem resolved installing hoobs, mosquitto, and zigbee2 with a conbee ii just worked while following the general installation instructions for those apps.

**Comment by mkellsy** [comment]
Building node on a pi is a nightmare. Will take too long.

If your using a newer Pi 3B 4B (armhf - armv7l)
```
cd ~/
wget https://nodejs.org/dist/v14.16.0/node-v14.16.0-linux-armv7l.tar.gz
tar -xzf ./node-v14.16.0-linux-armv7l.tar.gz -C /usr/local --strip-components=1 --no-same-owner
rm -rf ./node-v14.16.0-linux-armv7l.tar.gz
```

For older pis, Zero (armel - armv6l)
```
cd ~/
wget https://unofficial-builds.nodejs.org/download/release/v14.16.0/node-v14.16.0-linux-armv6l.tar.gz
tar -xzf ./node-v14.16.0-linux-armv7l.tar.gz -C /usr/local --strip-components=1 --no-same-owner
rm -rf ./node-v14.16.0-linux-armv7l.tar.gz
```

Note: Node dropped support for ARM6, and you must use an unofficial build.
