### ISSUE TITLE
Connected over LAN and Wireless 

### ISSUE THREAD

**Issue by marhindev** [hoobs-org/HOOBS#1105]
**Description**
I setup HOOBS via WLAN, and installed and tested successfully some plugins. It worked great so far!

I then followed the instructions for switching connection type and shut it down and connected it directly to the router via cable.

Now I can see that it has two IP and is connected via wireless and LAN.

How to disconnect it from wireless?

Thanks for help!
Martin

**Version**
Latest version 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

Raspberry OS

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

only HomeConnect so far

**Comment by askovi** [comment]
Ethernet takes precedence over wifi. It will always use your wired connection unless it disconnects. 
You can also turn off the wifi radio if you want with command:

`sudo iwconfig wlan0 txpower off`

**Comment by marhindev** [comment]
Great, thanks for your reply. I was just a bit confused, I interpreted the description in the documentation as "either - or".
Now everything is clear.
