### ISSUE TITLE
Ring Setup doesn't ask for 2 factor auth.  Freezes after password entry

### ISSUE THREAD

**Issue by lisadavies31** [hoobs-org/HOOBS#1106]
Trying to setup ring on my new Hoobs.  Terminal gets me to after I have entered password but then doesn't ask for 2 factor authentication (which is switched on in Ring account) just sits there not asking for any more info and not producing a Refresh Token.  Help please
<img width="1045" alt="Screenshot 2021-02-25 at 20 02 33" src="https://user-images.githubusercontent.com/79665528/109210582-f1342380-77a4-11eb-964e-7db51f1683c0.png">

nb have successfully setup nest plugin so doesn't seem to be an issue with my Hoobs account, Homekit etc

**Comment by fjose30** [comment]
I'm having the same issue with the last version of the Ring Plugin for HOOBS

**Comment by askovi** [comment]
Seems to run fine for me. Try running that command directly in your local terminal on your computer. It doesn't need to be ran on the HOOBS Box to work. Then you can copy the token into the plugin configuration once you have it.

**Comment by lisadavies31** [comment]
Forgive the noob question but type the command directly in terminal? Do I need to write any command lines before or open terminal and type straight in? There's no basic user support for hoobs so find myself on fithub asking basic questions 😅

> Seems to run fine for me. Try running that command directly in your local terminal on your computer. It doesn't need to be ran on the HOOBS Box to work. Then you can copy the token into the plugin configuration once you have it

**Comment by askovi** [comment]
Yes just paste the npx command directly in the Mac terminal.

**Comment by lisadavies31** [comment]
> Yes just paste the npx command directly in the Mac terminal.

didn't work got this
<img width="437" alt="Screenshot 2021-03-01 at 08 20 25" src="https://user-images.githubusercontent.com/79665528/109470308-2374a800-7a67-11eb-91d6-fd51d6fe6f71.png">

**Comment by lisadavies31** [comment]
> Yes just paste the npx command directly in the Mac terminal.

I figured it out need ssh hoobs@hoobls.local first
It worked - thanks for the pointer 🙏
