### ISSUE TITLE
Home bridge not running

### ISSUE THREAD

**Issue by GOTDNRV** [hoobs-org/HOOBS#1108]
**Description**. Bridge service stopped.   When restarting attempts starting and turns red reports stopped.

**Version** 3.3.2
Please include the version of HOOBS you are using.  

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version** 3.3.1
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Mac OS BigSur

**List your plugins**
Ring
SimpliSafe3
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```{
    "server": {
        "port": 80,
        "origin": "*",
        "home_setup_id": "X-HM://0023ISYWY90FE",
        "polling_seconds": 5,
        "autostart": 0
    },
    "client": {
        "country_code": "US",
        "default_route": "status",
        "locale": "en",
        "theme": "hoobs-light",
        "postal_code": "94040",
        "inactive_logoff": 30,
        "temp_units": "fahrenheit"
    },
    "bridge": {
        "port": 51826,
        "name": "HOOBS",
        "username": 
        "pin": "031-45-154"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "hideCameraMotionSensor": true,
            "refreshToken": "",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            }
        },
        {
            "debug": true,
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "plugin_map": {
                "plugin_name": "homebridge-simplisafe3"
            },
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "resetSimpliSafeId": false,
            "sensorRefresh": 15,
            "name": "Home Alarm",
            "persistAccessories": true,
            "cameras": true

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```2/26/2021, 4:28:01 AM HOOBS listening on port 80.
2/26/2021, 4:28:12 AM Loaded plugin 'homebridge-ring'
2/26/2021, 4:28:12 AM [2/26/2021, 2:28:12 AM] Registering platform 'homebridge-ring.Ring'
2/26/2021, 4:28:14 AM Loaded plugin 'homebridge-simplisafe3'
2/26/2021, 4:28:14 AM [2/26/2021, 2:28:14 AM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
2/26/2021, 4:28:14 AM Loading 2 platforms...
2/26/2021, 4:28:14 AM [Ring] Initializing Ring platform...
2/26/2021, 4:28:14 AM [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
2/26/2021, 4:28:14 AM TypeError: Cannot read property 'username' of undefined
    at new SS3Platform (/home/hoobs/.hoobs/node_modules/homebridge-simplisafe3/index.js:74:58)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:346:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Additional context**
Add any other context about the problem here.

**Comment by bwp91** [comment]
It looks like you haven't set your username and password for the simplisafe plugin.

Inside the simplisafe plugin config section you need to add the `auth` section

```
"debug": true,
"platform": "homebridge-simplisafe3.SimpliSafe 3",
"plugin_map": {
   "plugin_name": "homebridge-simplisafe3"
},
"auth": {
   "username": "YOUR_USERNAME",
   "password": "YOUR_PASSWORD"
},
"cameraOptions": {
   "enableHwaccelRpi": false
},
```

**Comment by GOTDNRV** [comment]
Thank you, I just figured it out.  Greatly appreciate you.

**Comment by GOTDNRV** [comment]
Inside the config it overlaps when entering npm.

**Comment by GOTDNRV** [comment]
I have tried to enter the npm in the terminal and it will not accept the last 9 letters.

**Comment by bwp91** [comment]
What are you trying to do? There’s no need to use the terminal to edit the configuration?

**Comment by GOTDNRV** [comment]
I am trying to enter this npm install -g --unsafe-perm homebridge-simplisafe3 into the terminal as directed however, it stops at simp

**Comment by GOTDNRV** [comment]
This is what allows me to see my devices in homekit.  I entered my username and password in the interface settings however, I can’t access my device in home kit as before.

**Comment by bwp91** [comment]
The command 

`npm install -g --unsafe-perm homebridge-simplisafe3`

is to install the plugin, but you already have it installed so you don't need to run the command

**Comment by GOTDNRV** [comment]
But I can’t see the device in homekit

**Comment by bwp91** [comment]
Is there anything in the logs to suggest why it might not be working?

**Comment by GOTDNRV** [comment]
Current nodejs version Iv12.16.3) nightp2_enhance your_calm error

**Comment by GOTDNRV** [comment]
Keeps repeating unable to copy to this thread

**Comment by askovi** [comment]
That error is coming from the Ring plugin. You can fix it by upgrading node with this command:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`
