### ISSUE TITLE
HOOBS not working even after reflash

### ISSUE THREAD

**Issue by lchd2392** [hoobs-org/HOOBS#1109]
**Description**
I lost power last week for an extended number of days. After power came back, HOOBS became unresponsive. I saw a lot of posts that mentioned reflashing. I tried that and now I can't even access hoobs.local

**Version**
Reflashed to 3.1.1 apparently

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Ring, Samsung TV, 

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
When you reflash you have to use the latest version from the website. Here are the instructions: 
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca


If you need additional help, please reach out to info@hoobs.org with your order number for remote assistance.
