### ISSUE TITLE
Unable to complete plugin process for Simplisafe3 

### ISSUE THREAD

**Issue by GOTDNRV** [hoobs-org/HOOBS#1111]
Unable to complete plug in

Hoops 3.3.2
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.2.1
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
MacOS BigSur
**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Ring
Simplisafe3
**Post your config**

This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```"server": {
        "port": 80,
        "origin": "*",
        "home_setup_id": "X-HM://0023ISYWY90FE",
        "polling_seconds": 5,
        "autostart": 0
    },
    "client": {
        "country_code": "US",
        "default_route": "status",
        "locale": "en",
        "theme": "hoobs-light",
        "postal_code": "27569",
        "inactive_logoff": 30,
        "temp_units": "fahrenheit",
        "latitude": "35.471480",
        "longitude": "-78.180710"
    },
    "bridge": {
        "port": 51826,
        "name": "HOOBS",
        "username": ,
        "pin": "031-45-154"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "hideCameraMotionSensor": true,
            "refreshToken": "_",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            }
        },
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "plugin_map": {
                "plugin_name": "homebridge-simplisafe3"
            },
            "name": "Home Alarm",

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```2/28/2021, 6:56:49 AM 
ffmpeg has been downloaded to /home/hoobs/.hoobs/node_modules/homebridge-simplisafe3/node_modules/ffmpeg-for-homebridge/ffmpeg
2/28/2021, 6:56:49 AM Thank you for using https://github.com/homebridge/ffmpeg-for-homebridge
2/28/2021, 6:56:49 AM 
> core-js@3.9.0 postinstall /home/hoobs/.hoobs/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
2/28/2021, 6:56:49 AM Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
2/28/2021, 6:56:51 AM + homebridge-simplisafe3@1.6.19
added 53 packages from 65 contributors in 25.811s
2/28/2021, 6:56:52 AM 
23 packages are looking for funding
  run `npm fund` for details
2/28/2021, 6:56:52 AM Plugin "homebridge-simplisafe3" installed.
2/28/2021, 6:56:52 AM Got SIGINT, shutting down Bridge...
2/28/2021, 6:57:03 AM Loaded plugin 'homebridge-ring'
2/28/2021, 6:57:03 AM [2/28/2021, 4:57:03 AM] Registering platform 'homebridge-ring.Ring'
2/28/2021, 6:57:04 AM Loaded plugin 'homebridge-simplisafe3'
2/28/2021, 6:57:04 AM [2/28/2021, 4:57:04 AM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
2/28/2021, 6:57:04 AM Loading 2 platforms...
2/28/2021, 6:57:04 AM [Ring] Initializing Ring platform...
2/28/2021, 6:57:04 AM [homebridge-simplisafe3.SimpliSafe 3] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
2/28/2021, 6:57:04 AM TypeError: Cannot read property 'username' of undefined
    at new SS3Platform (/home/hoobs/.hoobs/node_modules/homebridge-simplisafe3/index.js:74:58)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:346:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16

    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Additional context**
Add any other context about the problem here.
When attempting to put plug in, in this keeps happening 
![FDA9287F-577C-45C7-81DD-AFEA08CDFB42](https://user-images.githubusercontent.com/78084419/109418000-091dca00-7994-11eb-9903-9a09954fbb1c.jpeg)

**Comment by askovi** [comment]
The config you posted is incomplete. Please make sure the plugin is configured according to the plugin’s details page

**Comment by GOTDNRV** [comment]
[Screenshot 2021-02-28 at 7.06.32 AM.pdf](https://github.com/hoobs-org/HOOBS/files/6056783/Screenshot.2021-02-28.at.7.06.32.AM.pdf)
I just put a screen shit of what the plug in keeps doing.  Thank you

**Comment by GOTDNRV** [comment]
Ooops shot

**Comment by bwp91** [comment]
As i mentioned in your other issue, you don’t need to use npm to install the plugin - you already have it installed

**Comment by GOTDNRV** [comment]
I understand what you are saying however, I must be doing something wrong as my homekit is not recognizing Simplisafe3.  Sorry for the confusion.

**Comment by askovi** [comment]
Did you configure the plugin after installing it?

**Comment by GOTDNRV** [comment]
I posted a screenshot of what happens each time I have attempted to complete the configure. The best I can explain what happens is the plug in loops over itself causing it to be read incorrectly.

**Comment by bwp91** [comment]
The screenshot you posted shows you trying to run the npm command. you don’t need to do this.
you need to use the HOOBS interface to configure the plugin, adding this section to the similisafe section:

```
"auth": {
   "username": "",
   "password": ""
}
```

**Comment by GOTDNRV** [comment]
I apologize, I am trying my best to understand.  I have my username and password in however, I must be missing something as I am unable to access my device via HomeKit.

**Comment by bwp91** [comment]
What do your logs say when you restart hoobs?

**Comment by GOTDNRV** [comment]
States invalid password however, I have verified and it is correct.  I do know it requires a two factor authentication.  Could this be causing the error?
3/1/2021, 7:33:38 AM Bridge is running on port 51826.
3/1/2021, 7:33:39 AM [Home Alarm] SimpliSafe login failed with error: {
  error: 'invalid_grant',
  error_description: 'INVALID_CREDENTIALS_PASSWORD'
}
3/1/2021, 7:33:39 AM [Home Alarm] Initial accessories refresh failed with error: Error: Not logged into SimpliSafe. Check credentials in the plugin config.
    at /home/hoobs/.hoobs/node_modules/homebridge-simplisafe3/index.js:92:50
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by GOTDNRV** [comment]
Will check again

**Comment by GOTDNRV** [comment]
Thank you !! You were right.   I appreciate all of your patience.
