### ISSUE TITLE
HOOBS Server Intermittently Unresponsive

### ISSUE THREAD

**Issue by rajiviyengar** [hoobs-org/HOOBS#1114]
**Description**
Everything works as expected _most of the time_. Occasionally, all the devices that are associated with HOOBS will display as "not responding" in the home app. Additionally, any attempts to connect to the HOOBS server result in a timeout. However, when looking at my routers admin page, I can see the HOOBS device is still connected to wifi. A few minutes later, everything goes back to normal (I can view the hoops admin page, and all devices work as expected in the home app). 

**Version**
I am running the current version of HOOBS (3.3.2)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
I am running HOOBS on a Raspberry Pi Zero W, using the HOOBS for download from the website. 

**List your plugins**
- Bond (Hoobs certified)
- Nest (Hoobs certified)
- Pico (v 1.0.2)
- Tuya (v 1.4.0)
-  Bravia tvOS (v 4.1.8)

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYHPH4",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "BD:A8:64:DE:F1:B6"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest",
            "googleAuth": {
                "issueToken": "*",
                "cookies": "*",
                "apiKey": "*"
            },
            "fanDurationMinutes": 15,
            "options": [
                "HomeAway.Disable",
                "Thermostat.SeparateBuiltInHumiditySensor.Enable"
            ]
        },
        {
            "platform": "Bond",
            "plugin_map": {
                "plugin_name": "homebridge-bond"
            },
            "include_dimmer": true,
            "include_toggle_state": true,
            "fan_speed_values": false,
            "bonds": [
                {
                    "ip_address": "10.0.1.19",
                    "token": "*"
                }
            ]
        },
        {
            "platform": "Pico",
            "plugin_map": {
                "plugin_name": "homebridge-pico"
            },
            "buslog": "off",
            "longname": false,
            "servers": [
                {
                    "host": "10.0.1.22",
                    "port": 23,
                    "switches": [
                        {
                            "name": "Master Bedroom Pico",
                            "pico": [
                                3,
                                12
                            ],
                            "type": "favorite"
                        },
                        {
                            "name": "Bedroom Pico",
                            "pico": 5,
                            "type": "favorite"
                        },
                        {
                            "name": "Guest Bedroom Pico",
                            "pico": 13,
                            "type": "favorite"
                        },
                        {
                            "name": "Living Room Pico",
                            "pico": 10,
                            "type": "favorite"
                        }
                    ]
                }
            ]
        },
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Hot Water Valve",
                    "type": "waterValve",
                    "noTimer": true,
                    "dpPower": 1,
                    "manufacturer": "Tuya",
                    "model": "Smart Valve Controller",
                    "id": "*",
                    "key": "*"
                },
                {
                    "name": "Glow Light",
                    "type": "RGBTWLight",
                    "manufacturer": "TreatLife",
                    "model": "Glow Light",
                    "dpPower": 20,
                    "dpBrightness": 22,
                    "dpMode": 21,
                    "dpColorTemperature": 23,
                    "dpColor": 24,
                    "colorFunction": "HSB",
                    "id": "*",
                    "key": "*"
                },
                {
                    "name": "Bedroom Hall",
                    "type": "SimpleLight",
                    "manufacturer": "TreatLife",
                    "model": "WiFi Switch",
                    "id": "*",
                    "key": "*"
                },
                {
                    "name": "Center Patio",
                    "type": "SimpleLight",
                    "manufacturer": "TreatLife",
                    "model": "WiFi Switch",
                    "id": "*",
                    "key": "*"
                },
                {
                    "name": "Front Door Exterior",
                    "type": "SimpleLight",
                    "manufacturer": "TreatLife",
                    "model": "WiFi Switch",
                    "id": "*",
                    "key": "*"
                },
                {
                    "name": "Bathroom",
                    "type": "SimpleLight",
                    "manufacturer": "TreatLife",
                    "model": "WiFi Switch",
                    "id": "*",
                    "key": "*"
                },
                {
                    "name": "Back Patio",
                    "type": "SimpleLight",
                    "manufacturer": "TreatLife",
                    "model": "WiFi Switch",
                    "id": "*",
                    "key": "*"
                },
                {
                    "name": "Master Bedroom Hall",
                    "type": "SimpleLight",
                    "manufacturer": "TreatLife",
                    "model": "WiFi Switch",
                    "id": "*",
                    "key": "*"
                },
                {
                    "name": "Bedroom Night Light",
                    "type": "SimpleLight",
                    "manufacturer": "TreatLife",
                    "model": "WiFi Switch",
                    "id": "*",
                    "key": "*"
                },
                {
                    "name": "Cabinet",
                    "type": "SimpleLight",
                    "manufacturer": "TreatLife",
                    "model": "WiFi Switch",
                    "id": "**",
                    "key": "*"
                },
                {
                    "name": "Cabinet",
                    "type": "SimpleLight",
                    "manufacturer": "TreatLife",
                    "model": "WiFi Switch",
                    "id": "*",
                    "key": "*"
                }
            ]
        },
        {
            "platform": "BraviaOSPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-bravia-tvos"
            },
            "name": "BraviaTVOS",
            "tvs": [
                {
                    "name": "Sony TV",
                    "ip": "10.0.1.31",
                    "psk": "*************"
                }
            ]
        }
    ]
}

**Comment by askovi** [comment]
Sounds like a networking issue between the rpi0 and your router. Try connecting via SSH when it's unresponsive and see if you can ping anything.

**Comment by rajiviyengar** [comment]
I used to have homebridge installed on the same pi and experienced the exact same issue. The pi is also placed right next to my router, and no other devices experience dropped wifi. Would it be safe to assume it's a defect with my raspberry pi?

**Comment by askovi** [comment]
Could be an issue with the pi’s wifi chip if it just randomly drops connection and your other devices aren’t affected

**Comment by mkellsy** [comment]
Before you blame the board. Check to see if there are any remaining HB service files.

```
ls -la /etc/systemd/system/
```

See if there are any homebridge.service or config-ui-x.service files in there. It may just be a port conflict.
