### ISSUE TITLE
Unable to access HOOBS, only SSH through Terminal

### ISSUE THREAD

**Issue by kronic357** [hoobs-org/HOOBS#1118]
**Description**
Unable to access HOOBS through hoobs.local or ip address.  Tried to update Node for latest version and it stopped working.

**Version**
HOOBS 3.3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
-Nest
-Roku TV
-Sensibo AC
-IFTTT

**Post your config**
Unable

**Post your log**
You can get the log from the interface. This is in the Log section.

Linux hoobs 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l
Raspberry Pi 3 Model B Rev 1.2

*** HOOBS - Homebridge Out Of The Box System ***

To configure Homebridge browse to the one of the following addresses from 
another device on your network:

* http://hoobs.local
* http://192.168.86.27
* http://192.168.86.57
* http://[fd6a:a66d:e8b7:2:927f:7a08:58b2:7e93]
* http://[fd6a:a66d:e8b7:2:3d6c:7cc5:c364:bb59]

All Homebridge configuration can be completed via the Homebridge Web UI.

homebridge was created by nfarina and licensed under the Apache License 2.0.
homebridge-config-ui-x was created by oznu and licensed under the MIT License.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Mar  2 14:13:12 2021 from 192.168.XX.XX
Could not chdir to home directory /home/hoobs: No such file or directory
hoobs@hoobs:/$ 

**Additional context**

**Comment by mkellsy** [comment]
Since you can get to the terminal can you run this
```
sudo systemctl status hoobs
```

Then post the results. You may need to press `q` to exit this command.

**Comment by kronic357** [comment]
> Since you can get to the terminal can you run this
> 
> ```
> sudo hoobs service log
> ```
> 
> or
> 
> ```
> sudo systemctl status hoobs
> ```
> 
> Then post the results. You may need to press `q` to exit this command.

hoobs@192.168.86.57's password: 
Linux hoobs 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l
Raspberry Pi 3 Model B Rev 1.2


*** HOOBS - Homebridge Out Of The Box System ***

To configure Homebridge browse to the one of the following addresses from 
another device on your network:

* http://hoobs.local
* http://192.168.86.27
* http://192.168.86.57
* http://[fd6a:a66d:e8b7:2:927f:7a08:58b2:7e93]
* http://[fd6a:a66d:e8b7:2:3d6c:7cc5:c364:bb59]

All Homebridge configuration can be completed via the Homebridge Web UI.

homebridge was created by nfarina and licensed under the Apache License 2.0.
homebridge-config-ui-x was created by oznu and licensed under the MIT License.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Mar  2 14:27:49 2021 from 192.168.86.69
Could not chdir to home directory /home/hoobs: No such file or directory
hoobs@hoobs:/$ sudo hoobs service log
sudo: hoobs: command not found
hoobs@hoobs:/$ sudo systemctl status hoobs
● hoobs.service - HOOBS
   Loaded: loaded (/etc/systemd/system/hoobs.service; enabled; vendor preset: en
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-03-02 15
  Process: 2274 ExecStart=/usr/local/bin/hoobs (code=exited, status=203/EXEC)
 Main PID: 2274 (code=exited, status=203/EXEC)
lines 1-5/5 (END)

**Comment by mkellsy** [comment]
Wired. It's like the dist files aren't there.

Run this
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```

It will reinstall everything. If this fails, I think you may have a corrupt SD Card.

**Comment by kronic357** [comment]
> wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts

hoobs@hoobs:/$ wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts

Thank You for choosing HOOBS
================================================================================
Node Version 14.16.0
Updating Repositories
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u1).
git is already the newest version (1:2.20.1-2+deb10u3).
tar is already the newest version (1.30+dfsg-6).
0 upgraded, 0 newly installed, 0 to remove and 180 not upgraded.
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-02T20_47_58_623Z-debug.log
hoobs@hoobs:/$

**Comment by mkellsy** [comment]
Node is corrupt. You may have a corrupt SD Card. You can try NodeSource
```
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

Pay attention to the nodesource install script. It may tell you what the error is.

**Comment by kronic357** [comment]
> sudo npm install -g --unsafe-perm @hoobs/hoobs

hoobs@hoobs:/$ curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

## Installing the NodeSource Node.js 14.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/buster/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 14.x repo...

+ echo 'deb https://deb.nodesource.com/node_14.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_14.x buster main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:3 https://deb.nodesource.com/node_14.x buster InRelease [4,584 B]
Get:4 https://deb.nodesource.com/node_14.x buster/main armhf Packages [778 B]
Fetched 5,362 B in 3s (1,786 B/s)
Reading package lists... Done

## Run `sudo apt-get install -y nodejs` to install Node.js 14.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


hoobs@hoobs:/$ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 180 not upgraded.
Need to get 22.6 MB of archives.
After this operation, 113 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_14.x buster/main armhf nodejs armhf 14.16.0-1nodesource1 [22.6 MB]
Fetched 22.6 MB in 8s (2,972 kB/s)                                             
Selecting previously unselected package nodejs.
(Reading database ... 41090 files and directories currently installed.)
Preparing to unpack .../nodejs_14.16.0-1nodesource1_armhf.deb ...
Unpacking nodejs (14.16.0-1nodesource1) ...
Setting up nodejs (14.16.0-1nodesource1) ...
Processing triggers for man-db (2.8.5-2) ...
hoobs@hoobs:/$ sudo npm uninstall -g @hoobs/hoobs
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-02T22_21_43_700Z-debug.log
hoobs@hoobs:/$ sudo npm install -g --unsafe-perm @hoobs/hoobs
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-02T22_22_20_548Z-debug.log
hoobs@hoobs:/$ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (14.16.0-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 180 not upgraded.
hoobs@hoobs:/$

**Comment by kronic357** [comment]
hoobs@hoobs:/$ curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

## Installing the NodeSource Node.js 14.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/buster/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 14.x repo...

+ echo 'deb https://deb.nodesource.com/node_14.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_14.x buster main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:3 https://deb.nodesource.com/node_14.x buster InRelease [4,584 B]
Get:4 https://deb.nodesource.com/node_14.x buster/main armhf Packages [778 B]
Fetched 5,362 B in 3s (1,786 B/s)
Reading package lists... Done

## Run `sudo apt-get install -y nodejs` to install Node.js 14.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

**Comment by mkellsy** [comment]
I think you need to reflash the OS.
First things first. Backup this folder.
```
~/.hoobs
```

Then you can download a fresh image and flash the sd card using something like the balinaEtcher.

Once it's back up you can restore the ~/.hoobs folder and reboot the pi. It should come back up.

**Comment by kronic357** [comment]
> I think you need to reflash the OS.
> First things first. Backup this folder.
> 
> ```
> ~/.hoobs
> ```
> 
> Then you can download a fresh image and flash the sd card using something like the balinaEtcher.
> 
> Once it's back up you can restore the ~/.hoobs folder and reboot the pi. It should come back up.

Will try that. Thanks for your help!

**Comment by kronic357** [comment]
> I think you need to reflash the OS.
> First things first. Backup this folder.
> 
> ```
> ~/.hoobs
> ```
> 
> Then you can download a fresh image and flash the sd card using something like the balinaEtcher.
> 
> Once it's back up you can restore the ~/.hoobs folder and reboot the pi. It should come back up.

It worked! Thanks again
