### ISSUE TITLE
Interface reduced operation

### ISSUE THREAD

**Issue by vitorpt21** [hoobs-org/HOOBS#1119]
**Description**
After upgrade to 3.3.3 interface only works with dashboard and system.

**Version**
Please include the version of HOOBS you are using.
3.3.2 or 3.3.3

In the About I have 3.3.2 on dashboard 3.3.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.3.2

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Linux Hoobs

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
homebridge-ewelink

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
Nothing new in the log file. Tried a restart but not working
**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Clear your browse cache.

**Comment by vitorpt21** [comment]
Ok that was the problem. It's working.
