### ISSUE TITLE
Stuck on Startup Screen

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [hoobs-org/HOOBS#112]
Image removed

**Comment by mkellsy** [comment]
Can you let me know what device you are running.

**Comment by d0n4v4nb3ck3r** [comment]
Linux hoobs 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l
Raspberry Pi 3 Model B Rev 1.2


*** HOOBS - Homebridge Out Of The Box System ***

To configure Homebridge browse to the one of the following addresses from 
another device on your network:

* http://hoobs.local
* http://192.168.7.7
* http://[2001:48f8:402a:1adb:5cc5:cbe0:fcd4:9966]
* http://[fd36:6316:ac10:1:76b2:4453:6799:7f19]

All Homebridge configuration can be completed via the Homebridge Web UI.

homebridge was created by nfarina and licensed under the Apache License 2.0.
homebridge-config-ui-x was created by oznu and licensed under the MIT License.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Aug 30 17:30:24 2019 from 174.219.19.53
hoobs@hoobs:~ $ sudo systemctl status homebridge
● homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.s
   Active: active (running) since Fri 2019-08-30 17
 Main PID: 539 (hoobs-core)
    Tasks: 22 (limit: 2200)
   Memory: 276.9M
   CGroup: /system.slice/homebridge.service
           ├─ 539 hoobs-core
           └─1222 homebridge

Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
lines 1-20/20 (END)...skipping...● homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.s
   Active: active (running) since Fri 2019-08-30 17
 Main PID: 539 (hoobs-core)
    Tasks: 22 (limit: 2200)
   Memory: 276.9M
   CGroup: /system.slice/homebridge.service
           ├─ 539 hoobs-core
           └─1222 homebridge

Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-20/20 (END)


























● homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.s
   Active: active (running) since Fri 2019-08-30 17
 Main PID: 539 (hoobs-core)
    Tasks: 22 (limit: 2200)
   Memory: 276.9M
   CGroup: /system.slice/homebridge.service
           ├─ 539 hoobs-core
           └─1222 homebridge

Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
~
~
~
~
~
lines 1-20/20 (END)










































● homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.s
   Active: active (running) since Fri 2019-08-30 17
 Main PID: 539 (hoobs-core)
    Tasks: 22 (limit: 2200)
   Memory: 276.9M
   CGroup: /system.slice/homebridge.service
           ├─ 539 hoobs-core
           └─1222 homebridge

Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-20/20 (END)


























● homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.s
   Active: active (running) since Fri 2019-08-30 17
 Main PID: 539 (hoobs-core)
    Tasks: 22 (limit: 2200)
   Memory: 276.9M
   CGroup: /system.slice/homebridge.service
           ├─ 539 hoobs-core
           └─1222 homebridge

Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:25:28 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:30:42 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
Aug 30 17:41:13 hoobs homebridge[539]: [Homebridge]
~
~
~
~
~
lines 1-20/20 (END)

**Comment by d0n4v4nb3ck3r** [comment]
RaspberryPI 3

**Comment by mkellsy** [comment]
run this

```sh
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

Then reboot.

**Comment by d0n4v4nb3ck3r** [comment]
Working now! Didn’t work right away and then reinstalled again and again and now working

**Comment by d0n4v4nb3ck3r** [comment]
Happened again.

**Comment by d0n4v4nb3ck3r** [comment]
Linux hoobs 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l
Raspberry Pi 3 Model B Rev 1.2


*** HOOBS - Homebridge Out Of The Box System ***

To configure Homebridge browse to the one of the following addresses from 
another device on your network:

* http://hoobs.local
* http://192.168.7.7
* http://[2001:48f8:402a:1adb:5cc5:cbe0:fcd4:9966]
* http://[fd36:6316:ac10:1:76b2:4453:6799:7f19]

All Homebridge configuration can be completed via the Homebridge Web UI.

homebridge was created by nfarina and licensed under the Apache License 2.0.
homebridge-config-ui-x was created by oznu and licensed under the MIT License.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Aug 30 21:03:30 2019 from 64.31.243.180
hoobs@hoobs:~ $ sudo npm install -g --unsafe-perm @hoobs/hoobs
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
/usr/local/bin/hoobs-init -> /usr/local/lib/node_modules/@hoobs/hoobs/install.sh
+ @hoobs/hoobs@3.0.0-beta.38
updated 1 package in 28.11s
hoobs@hoobs:~ $ sudo systemctl status homebridge
● homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.s
   Active: active (running) since Fri 2019-08-30 21
 Main PID: 520 (hoobs-core)
    Tasks: 22 (limit: 2200)
   Memory: 107.9M
   CGroup: /system.slice/homebridge.service
           ├─520 hoobs-core
           └─676 homebridge

Aug 30 21:06:02 hoobs homebridge[520]: [Homebridge]
Aug 30 21:06:02 hoobs homebridge[520]: [Homebridge]
Aug 30 21:06:02 hoobs homebridge[520]: [Homebridge]
Aug 30 21:06:02 hoobs homebridge[520]: [Homebridge]
Aug 30 21:06:02 hoobs homebridge[520]: [Homebridge]
Aug 30 21:06:02 hoobs homebridge[520]: [Homebridge]
Aug 30 21:16:14 hoobs homebridge[520]: [Homebridge]
Aug 30 21:16:14 hoobs homebridge[520]: [Homebridge]
Aug 30 21:16:14 hoobs homebridge[520]: [Homebridge]
Aug 30 21:16:14 hoobs homebridge[520]: [Homebridge]
lines 1-20/20 (END)

**Comment by mkellsy** [comment]
I'm going to have to do some testing tomorrow. In the meantime can you post the config.json it is located at ~/.hoobs/etc/config.json

Also can you post the results of this
ls -la ~/.hoobs/

Also post this file
~/.hoobs/package.json

**Comment by d0n4v4nb3ck3r** [comment]
{
  "bridge" : {
    "username" : "CC:22:3D:E3:CE:30",
    "pin" : "031-45-154",
    "name" : "HOOBS",
    "port" : 51826
  },
  "description" : "This file is used for plugin configuration.",
  "accessories" : [

  ],
  "platforms" : [
 
        {
            "platform": "homebridge-honeywell-home.HoneywellHome",
            "name": "HoneywellHome",
            "credentials": {
                "consumerKey": "",
                "consumerSecret": "",
                "accessToken": "",
                "refreshToken": ""
            },
            "options": {
                "ttl": 600,
                "verboseP": false
            }
        },
    {
      "standalone" : true,
      "tempUnits" : "f",
      "accessoryControl" : {
        "instanceBlacklist" : [
          "(0E:E6:3CE9:E1:97)"
        ]
      },
      "restart" : "sudo -n systemctl restart homebridge homebridge-config-ui-x",
      "temp" : "/sys/class/thermal/thermal_zone0/temp",
      "theme" : "dark-mode",
      "log" : {
        "command" : "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x",
        "method" : "custom"
      },
      "auth" : "form",
      "platform" : "config",
      "sudo" : true,
      "name" : "Config",
      "port" : 8080
    },
    {
      "hideDoorbellSwitch" : true,
      "hideCameraSirenSwitch" : true,
      "hideLightGroups" : true,
      "platform" : "Ring",
      "cameraDingsPollingSeconds" : 1,
      "refreshToken" : "",
      "hideAlarmSirenSwitch" : true,
      "beamDurationSeconds" : 3600,
      "cameraStatusPollingSeconds" : 10,
      "hideCameraMotionSensor" : false
    }
  ]
}

**Comment by d0n4v4nb3ck3r** [comment]
total 176
drwxr-xr-x   6 hoobs hoobs   4096 Aug 30 17:51 .
drwxr-xr-x  10 hoobs hoobs   4096 Aug 30 17:49 ..
-rw-r--r--   1 hoobs hoobs    709 Aug 30 17:49 default.json
drwxr-xr-x   7 hoobs hoobs   4096 Aug 30 21:26 dist
drwxr-xr-x   4 hoobs hoobs   4096 Aug 30 23:53 etc
drwxr-xr-x   3 hoobs hoobs   4096 Aug 30 17:49 lib
drwxr-xr-x 359 hoobs hoobs  12288 Aug 30 17:51 node_modules
-rw-r--r--   1 hoobs hoobs   2219 Aug 30 17:51 package.json
-rw-r--r--   1 hoobs hoobs 135813 Aug 30 17:51 package-lock.json

**Comment by d0n4v4nb3ck3r** [comment]
{
    "_from": "@hoobs/hoobs",
    "_id": "@hoobs/hoobs@3.0.0-beta.38",
    "_inBundle": false,
    "_integrity": "sha512-61ArJMcggTCUfMaULArBAir4kC1D5s8CAt7BPBqnP5fzaQGuWjvtsTodJLyQK8TOSTBH8M7H9LNei/U9Wc6/qQ==",
    "_location": "/@hoobs/hoobs",
    "_phantomChildren": {},
    "_requested": {
        "type": "tag",
        "registry": true,
        "raw": "@hoobs/hoobs",
        "name": "@hoobs/hoobs",
        "escapedName": "@hoobs%2fhoobs",
        "scope": "@hoobs",
        "rawSpec": "",
        "saveSpec": null,
        "fetchSpec": "latest"
    },
    "_requiredBy": [
        "#USER",
        "/"
    ],
    "_resolved": "https://registry.npmjs.org/@hoobs/hoobs/-/hoobs-3.0.0-beta.38.tgz",
    "_shasum": "ebcfa8a769a8ce16fd7ba6ed412f0027d5b61481",
    "_spec": "@hoobs/hoobs",
    "_where": "/home/hoobs",
    "author": {
        "name": "Michael J Kellsy"
    },
    "browserslist": [
        "> 1%",
        "last 2 versions"
    ],
    "bugs": {
        "url": "https://github.com/hoobs-org/hoobs-core/issues"
    },
    "bundleDependencies": false,
    "dependencies": {
        "@hoobs/homebridge": "^3.0.3",
        "@hoobs/systeminfo": "^4.14.7",
        "axios": "^0.19.0",
        "commander": "^2.20.0",
        "cors": "^2.8.5",
        "express": "^4.17.1",
        "express-ws": "^4.0.0",
        "fs-extra": "^8.1.0",
        "homebridge-honeywell-home": "^1.2.0",
        "homebridge-ring": "^5.6.1",
        "lodash": "^4.17.15",
        "node-pty-prebuilt-multiarch": "^0.8.1",
        "ora": "^3.4.0",
        "request": "^2.88.0",
        "rimraf": "^2.7.1",
        "socket.io": "^2.2.0",
        "xterm": "^3.14.5"
    },
    "deprecated": false,
    "description": "Certified HOOBS stack",
    "engines": {
        "node": ">=10.16.3"
    },
    "homepage": "https://github.com/hoobs-org/hoobs-core#readme",
    "keywords": [
        "HOOBS",
        "homebridge"
    ],
    "license": "Apache-2.0",
    "main": "lib/cli.js",
    "name": "@hoobs/hoobs",
    "postcss": {
        "plugins": {
            "autoprefixer": {}
        }
    },
    "repository": {
        "type": "git",
        "url": "git://github.com/hoobs-org/hoobs-core.git"
    },
    "version": "3.0.0-beta.38"
}

**Comment by mkellsy** [comment]
Are you replacing the config.json with a backup? HOOBS has additional information now. You config is missing the server and client sections.

You can see the default.json file. It is here ~/.hoobs/default.json.

I am testing this.

To reset run this
rm -fR ~/.hoobs

Then this
hoobs

Look for errors.

If everything goes OK you can reboot.

**Comment by d0n4v4nb3ck3r** [comment]
hoobs@hoobs:~ $ sudo rm -fR ~/.hoobs
hoobs@hoobs:~ $ hoobs
Migrating config '/home/hoobs/.homebridge/config.json'.
[8/31/2019, 9:38:23 AM] Log server running on port 51828
[8/31/2019, 9:38:24 AM] Interface running on port 8080
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::51828
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at module.exports (/home/hoobs/.hoobs/lib/logger.js:49:10)
    at module.exports (/home/hoobs/.hoobs/lib/cli.js:100:38)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by mkellsy** [comment]
You need the ~
rm -fR ~/.hoobs

It looks like HB got stuck.
You will need to reboot

**Comment by d0n4v4nb3ck3r** [comment]
Same erros

**Comment by mkellsy** [comment]
Can you port foward port 22 to your Pi? And what's your public ip.

I will SSH into your Pi and see what's going on. I will remove sensitive info from the issue once I have it.

**Comment by d0n4v4nb3ck3r** [comment]
Can I send it on slack?

**Comment by mkellsy** [comment]
Hold on

**Comment by mkellsy** [comment]
go here
[https://m.me/HOOBSofficial](https://m.me/HOOBSofficial)

**Comment by mkellsy** [comment]
This moved to Slack

**Comment by mkellsy** [comment]
I think the issue is hoobs.local was in conflict. I changed the hostname to hoobs-two.

**Comment by TransRapid** [comment]
Running on OSX. I think this is my issue as well, trying this again now, did it yesterday and it didn’t work. Also going to try clearing cache.
