### ISSUE TITLE
3.3.3 - use ciao?

### ISSUE THREAD

**Issue by kbardai** [hoobs-org/HOOBS#1120]
Hey, thanks for the update to 3.3.3 and home bridge 1.3.1!

Is it possible in the settings to use ciao instead of bonjour-hap? (https://github.com/homebridge/homebridge/wiki/mDNS-Options)

Is it as simple as updating the "bridge" section under the advanced configuration in settings by adding the following:

"advertiser": "ciao"  // accepts "ciao" or "bonjour-hap"

Take Care

**Comment by mkellsy** [comment]
It's coming in our next major release.

**Comment by kbardai** [comment]
Thanks!
