### ISSUE TITLE
I can not connect to Hoobs anymore

### ISSUE THREAD

**Issue by svobod3** [hoobs-org/HOOBS#1121]
**Description**
Hoobs UI offered me update to new version. I clicked on it, but since then I can not access Hoobs anymore. When I try http://hoobs.local/, I get ERR_CONNECTION_REFUSED.

**Version**
I think original version was 3.3.2 and I tried to update to 3.3.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
I think original version was 3.3.2 and I tried to update to 3.3.3

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**list of plugins**
roomba2
harmony
tuya via web

**Post your config**
not able to get there

**Post your log**

I followed steps searched on other site - to login via SSH and get the HOOBS logs.
Result fllows:

Last login: Wed Mar  3 12:23:40 on ttys000
jirisvoboda@Jirkuv-iMac ~ % ssh hoobs@hoobs.local
hoobs@hoobs.local's password: 
Linux hoobs 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l
Raspberry Pi 3 Model B Rev 1.2

*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://192.168.1.34

HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Mar  3 04:24:39 2021 from fe80::18c8:277c:5fee:338c%wlan0
hoobs@hoobs:~ $ sudo hoobs service log
sudo: hoobs: command not found
hoobs@hoobs:~ $ 

**Additional context**
hoobs is connected via wifi

**Comment by mkellsy** [comment]
Since you can get to the terminal. Run this command.

```
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
```

The next minor version will do this automatically for you.

**Comment by svobod3** [comment]
I run command above, no message appeared after it. What should I do next?


Last login: Wed Mar  3 14:31:35 on ttys000
jirisvoboda@Jirkuv-iMac ~ % ssh hoobs@hoobs.local
hoobs@hoobs.local's password: 
Linux hoobs 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l
Raspberry Pi 3 Model B Rev 1.2


*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://192.168.1.34


HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Mar  3 06:49:56 2021 from fe80::18c8:277c:5fee:338c%eth0
hoobs@hoobs:~ $ sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
That command allows node to run on port 80. Just test if hoobs.local works. If not try a reboot.

If it still isn't coming up. Run this command
```
sudo hoobs log
```
And post the response.

**Comment by svobod3** [comment]
hoobs@hoobs:~ $ sudo hoobs log
sudo: hoobs: command not found
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
What does this say?
```
df -h
```

**Comment by svobod3** [comment]
hoobs@hoobs:~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        15G  2.0G   12G  15% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M   19M  446M   4% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   53M  200M  21% /boot
tmpfs            93M     0   93M   0% /run/user/1000
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
That looks good. I saw 2 sd card failures, where the available on /dev/root was 0%.

Since the HOOBS command isn't there. Maybe the install or upgrade got stuck. This command will try to install Node and will install the core package.

```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```

**Comment by svobod3** [comment]
I went through installation process and it looks good. I can access Hoobs via hoobs.local again and all settings should be ok.
BTW Is it possible to say what happened? Just to avoid it in the future when I will update to new version again.


Last login: Wed Mar  3 20:31:55 on console
jirisvoboda@Jirkuv-iMac ~ % ssh hoobs@hoobs.local
hoobs@hoobs.local's password: 
Linux hoobs 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l
Raspberry Pi 3 Model B Rev 1.2


*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://192.168.1.34


HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Mar  3 10:48:00 2021 from fe80::18c8:277c:5fee:338c%wlan0
hoobs@hoobs:~ $ wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts

Thank You for choosing HOOBS
============================================================================================================================================================================================================================================================================================================================================================================
Node Version 12.16.3
Updating Repositories
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.8 kB]             
Hit:2 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease           
Get:3 http://archive.raspberrypi.org/debian buster/main armhf Packages [364 kB]
Fetched 397 kB in 10s (41.1 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u1).
git is already the newest version (1:2.20.1-2+deb10u3).
tar is already the newest version (1.30+dfsg-6).
0 upgraded, 0 newly installed, 0 to remove and 91 not upgraded.
setsebool:  SELinux is disabled.

Installing Node
============================================================================================================================================================================================================================================================================================================================================================================
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:8.3.0-1+rpi2).
gcc is already the newest version (4:8.3.0-1+rpi2).
make is already the newest version (4.2.1-1.2).
python is already the newest version (2.7.16-1).
python set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 91 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.2M  100 30.2M    0     0  1157k      0  0:00:26  0:00:26 --:--:-- 1119k
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@7.6.0
added 56 packages from 23 contributors, removed 260 packages and updated 197 packages in 167.849s
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Node 14.16.0 Installed


added 227 packages, and audited 228 packages in 4m

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Initializing HOOBS
============================================================================================================================================================================================================================================================================================================================================================================
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u1).
gcc is already the newest version (4:8.3.0-1+rpi2).
libavahi-compat-libdnssd-dev is already the newest version (0.7-4+b1).
make is already the newest version (4.2.1-1.2).
perl is already the newest version (5.28.1-6).
python is already the newest version (2.7.16-1).
0 upgraded, 0 newly installed, 0 to remove and 91 not upgraded.
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
That should do more I will test it.

I'm the meantime can you run
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by svobod3** [comment]
I just wanted to execute commands above, but I can not get there via Mac OS Terminal - see below. Do you know why?
BTW hoobs.local works fine

jirisvoboda@Jirkuv-iMac ~ % ssh hoobs@hoobs.local
zsh: command not found: ssh hoobs@hoobs.local
jirisvoboda@Jirkuv-iMac ~ %

**Comment by mkellsy** [comment]
On your Mac type this
```
echo $PATH
```

It should include `/usr/bin`.
The ssh command lives on /usr/bin.

**Comment by svobod3** [comment]
jirisvoboda@Jirkuv-iMac ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
jirisvoboda@Jirkuv-iMac ~ % hoobs@hoobs.local
zsh: command not found: hoobs@hoobs.local
jirisvoboda@Jirkuv-iMac ~ %

**Comment by mkellsy** [comment]
Does running `/usr/bin/ssh` work?

**Comment by svobod3** [comment]
yes, I works, thanks a lot

BTW do you have any clue what originally happened that update was not successful and can it happen in the future with new updates again?

**Comment by mkellsy** [comment]
Sometimes NPM gets stuck. It happens.

**Comment by svobod3** [comment]
ok, thanks a lot for helping me to fix it
