### ISSUE TITLE
nginx config file missing.

### ISSUE THREAD

**Issue by rafaelfaria** [hoobs-org/HOOBS#1123]
Hi,

I manually installed my hoobs. everything is working except I don't have the nginx config file in `/etc/nginx/conf.d` to make "hoobs.local" work. I  have been using the IP.

Can someone share the steps to make this work? Is it only adding a config file? what the config file look like?

Thanks

**Comment by mkellsy** [comment]
Are you on Mac.

There isn't a config.d file. The instructions for Mac are here.
https://support.hoobs.org/docs/5e763f44e87d1e02b6c19d3a

If you aren't on Mac, you don't need Nginx.
https://support.hoobs.org/docs/5e763e76e87d1e02b6c19d35
