### ISSUE TITLE
Plugin FibaroHC3 error !

### ISSUE THREAD

**Issue by DJJL** [hoobs-org/HOOBS#1124]
Hello,

I have Hoobs3 box and,
I'm glad I found a plugin for the Fibaro HC3, but there is a big problem.
Impossible for this plugin to start because of the absence of the "ca.cer" file ???

Message : 

**[FibaroHC3] Put a valid ca.cer file in config.json folder.**

Full error message : 

**[FibaroHC3] Initializing FibaroHC3 platform...
04/03/2021 à 00:26:30 [FibaroHC3] Error reading ca.cer:  Error: ENOENT: no such file or directory, open '/home/hoobs/.homebridge/ca.cer'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at new FibaroClient (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/src/fibaro-api.ts:54:19)
    at new FibaroHC3 (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/src/index.ts:132:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:347:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:321:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:153:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/hoobs/.homebridge/ca.cer'
}
04/03/2021 à 00:26:30 [FibaroHC3] Put a valid ca.cer file in config.json folder.
04/03/2021 à 00:26:30 [FibaroHC3] Cannot connect to Fibaro Home Center Check credentials, url/host or ca.cer file**

Do you have any idea to solve this problem?

Thank you very much

JL

**Comment by mkellsy** [comment]
It looks legit or you need a `ca.cer` file.
Put this in this folder `~/.hoobs`.

**Comment by DJJL** [comment]
Thanks mkellsy,
ok, so this is possible through the terminal of the Hoobs box.
I will do this tonight when I get home.
Creation of the hidden hombridge folder and I will look for the famous "ca.cer" file.
I will say if it is ok after installation.
Thank you very much for the reply

**Comment by DJJL** [comment]
It's no ok :-(
Don't find the file "ca.cer"... why ?

**Comment by mkellsy** [comment]
Is the ca.cer in ~/.hoobs?
I think the plugin is looking for it using a hard coded path.

**Comment by DJJL** [comment]
No "ca.cer" in .hoobs

Yes, I asked the question to the developer, he said not to put anything in "URL" but only in "Host".
And now it works.
Why ? I don't know...

Now I need to create variables in HC3, but I am looking for how to assign these variables to devices ... like the portal command ...
An idea ?
