### ISSUE TITLE
HOOBS Nest plugin install

### ISSUE THREAD

**Issue by acorona78** [hoobs-org/HOOBS#1127]
Hello, 

I installed the HOOBS certified Nest plugin but when I run the "npm install -g homebridge" I get the message below,

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-03-05T17_26_02_811Z-debug.log

**Comment by askovi** [comment]
You don't need to run any of those commands. Install the plugin via the UI then configure it. Here's a video tutorial for getting the Nest account data: https://www.youtube.com/watch?v=nX5ztcGnRUQ

**Comment by acorona78** [comment]
Thank you, I will try that!
