### ISSUE TITLE
Can‘t access UI

### ISSUE THREAD

**Issue by heavyonwire** [hoobs-org/HOOBS#1128]
**Description**
Can‘t access UI after latest update via web interface, but software seems to running.
**Version**
Please include the version of HOOBS you are using.
latest, probably
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
yes
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
fritz
ewelink
magichome
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Try getting the local IP address from your router’s admin page and see if you can access it directly like this: http://192.168.x.x

**Comment by askovi** [comment]
Try getting the local IP address from your router’s admin page and see if you can access it directly like this: http://192.168.x.x
