### ISSUE TITLE
my hobbs box - no working 

### ISSUE THREAD

**Issue by GITHUBALE2001** [hoobs-org/HOOBS#1129]
my new hobbs box . no working 
My equipment worked for 36 hours, the service stopped responding for 24 hours, I cut the power and then it was not activated again (lights off) the cables work perfectly

**Comment by askovi** [comment]
Please send an email to info@hoobs.org with your order number and someone will assist you directly with troubleshooting.

**Comment by GITHUBALE2001** [comment]
thank you Eddi
