### ISSUE TITLE
Config File Not Imported after HOOBS Upgrade; Homebridge Won't Start

### ISSUE THREAD

**Issue by charlestephen** [hoobs-org/HOOBS#113]
I used the automated updater and my config file wasn't imported properly. While the file is at /home/hoobs/config/config.json, it doesn't seem to matter (I assume the file structure changed) and I now can't start Homebridge or load the config at all. I'm getting the following error message:

[8/30/2019, 8:13:06 PM] Log client connected
[List Accessories] Cannot read property 'forEach' of undefined
[List Accessories] Cannot read property 'forEach' of undefined
[Homebridge] /home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:206
[Homebridge] throw new Error(`Not a valid username: ${username}. Must be 6 pairs of colon- separated hexadecimal chars (A-F 0-9), like a MAC address.`);
[Homebridge] ^
[Homebridge] Error: Not a valid username: undefined. Must be 6 pairs of colon- separated hexadecimal chars (A-F 0-9), like a MAC address.
[Homebridge] at Server._loadConfig (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:206:15)
[Homebridge] at new Server (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:48:40)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:35:18)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by charlestephen** [comment]
Literally nothing imported correctly. Blurg.

**Comment by mkellsy** [comment]
I am currently looking into this. In the mean time can you post your current config.json (remove any sensitive data) and if it exists, the new config file. It is located at ~/.hoobs/etc/config.json.
