### ISSUE TITLE
Hoobs in a box not responsive.

### ISSUE THREAD

**Issue by utknox89** [hoobs-org/HOOBS#1137]
**Description**
I had a brief power failure. I attempted to connect to hoops by ssh from terminal, but there is no response. There is a red light on the front, but the ethernet net lights are not lit.

**Version**
Not sure of the version extension, but know it is version 3.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
macOS Big Sur Version 11.2.2

**List your plugins**
Deebott
Nest Protect (Hoobs Certified version)
Smartthings
MyQ
**Post your config**
Can not access config
* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Check your phone wifi. Is there an access point called HOOBS?

If WiFi works but hard line doesn't. It could be a couple of things.
1. The SD card got corrupt, you can check this by plugging in a monitor to the HDMI port. (You may have to open the case), see if Linux is starting.

2. There may be an issue with the cable, try a different cable.

3. There may be an issue with your router. Try changing ports.

4. An issue with the hardware, how long ago did you buy the box?

**Comment by utknox89** [comment]
I bought the box May 2020. It looks like it is stuck in a loop. Would it be easier just to download the Hoobs software and reinstall it on the hoobs box?

**Comment by utknox89** [comment]
It's definitely stuck in a loop. Thinking the card is corrupted.The display

**Comment by carloperez** [comment]
Having the exact same problem.  Made no changes, noticed my HOOBS devices were no longer online, tried resetting the box and the red light is on on the front but no network.  Purchased same timeframe as you.

Any luck in sorting this out?

**Comment by utknox89** [comment]
No, haven't been able to repair. I downloaded a coke of the hoobs system to another sd card, but it is still not working.

**Comment by utknox89** [comment]
Just added a new raspberry pi and plugged in the micro-sd card. It is now working. Looks like the hardware failed in my case. Had working red light, but no lights working on the Ethernet side.

**Comment by utknox89** [comment]
I bought a new blackberry pie from Amazon and installed the hoobs card that came with the Hoobs unit. Everything has been working for a while now.
