### ISSUE TITLE
Preinstall most used dependencies by plugins?

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#114]
- [ ] (sudo) apt-get install bluetooth bluez libbluetooth-dev libudev-dev
- [ ] (sudo) apt-get install git

**Comment by mkellsy** [comment]
Can't pre install. A plug-ins dependencies are a child of it. In fact if we pre install the plugins will not share deps.

**Comment by BobbySlope** [comment]
Some of the plugins dont install everything needed

**Comment by BobbySlope** [comment]
And users running into installation errors

**Comment by BobbySlope** [comment]
or can we solve this on certified plugins by integrating all dependencies plugin devs missed?

**Comment by mkellsy** [comment]
They should install on pre or post npm install scripts. This would be part of the certification.

A lot of these developers don't know you can do that.
