### ISSUE TITLE
HOOBS & HUE

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1146]
Since 0.13.0 of HUE Plugin the whole Hoobs crashes!
Cant even go back to 0.12.26. Still crashes!

Need help!

**Comment by Christian-CFP** [comment]
Hue release info. Needed HB 1.3.3

**Comment by Christian-CFP** [comment]
It seems only if I add the IPs (hosts) of the bridges. If added, it stops working even if I delete the IPs...

**Comment by mkellsy** [comment]
Duplicate of #1147

Update to version 3.3.4.
