### ISSUE TITLE
Please update Node & Homebridge

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1147]
Node and Homebridge Update please.

If possible tell me how to update myself.

**Comment by bwp91** [comment]
i can help with the node update, but not with the homebridge update. you'll likely need to wait for HOOBS to update their system with the latest version of homebridge.

i can help with downgrading your version of homebridge-hue as i noticed in your other issue?

**Comment by Christian-CFP** [comment]
homebridge-hue does not work if IPs (hosts) are entered.
Now I cant install hue because its now 0.13.1 and hoobs shows 0.13.0 and failed to update :(

How can I update nodes?

**Comment by Christian-CFP** [comment]
hue is now 0.13.1 in hoobs :)

**Comment by bwp91** [comment]
Node update isn't necessary for homebridge-hue, but if you want to try updating you can by ssh-ing into the hoobs box and run this command:

```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 14.16.0
```

**Comment by Christian-CFP** [comment]
Now I do not have http access to hoobs :(

**Comment by Christian-CFP** [comment]
ssh still works

**Comment by bwp91** [comment]
what is shown if you ssh this command:

```
sudo hoobs service log
```

**Comment by Christian-CFP** [comment]
command not found

**Comment by bwp91** [comment]
You can try rebuilding hoobs with these two commands (separately)

```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by Christian-CFP** [comment]
Does not work. tried.

hoobs@hoobs:~ $ sudo npm uninstall -g @hoobs/hoobs
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-14T17_10_16_729Z-debug.log
hoobs@hoobs:~ $ sudo npm uninstall -g @hoobs/hoobs
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-14T17_11_08_309Z-debug.log

**Comment by mkellsy** [comment]
Version 3.3.4 just released.

**Comment by Christian-CFP** [comment]
I know. But cant connect to hoobs via http. Hoobs not working :(

**Comment by mkellsy** [comment]
Looks like the NPM cache is root locked. Try this.
```
sudo rm -fR ~/.npm
sudo rm -fR /usr/local/lib/node_modules/@hoobs/hoobs
sudo npm install -g --unsafe-perm  @hoobs/hoobs
```

Note. In our next major release ~v4, we are ditching NPM and using APT because of these errors.

**Comment by Christian-CFP** [comment]
THX!!!!!!!

**Comment by Christian-CFP** [comment]
But still, I cant get hue to run.

**Comment by Christian-CFP** [comment]
Now everything is upside down. No accessoir will be saved. Everytime I restart hoobs service all accessoires will register again..... :(

**Comment by bwp91** [comment]
_All_ accessories? or just homebridge hue accessories?

**Comment by Christian-CFP** [comment]
I cant install hue!
Accessoires like Fritz! or Harmony Hub

**Comment by Christian-CFP** [comment]
Load a backup with hue 0.12.22 This works. Trying to update...

**Comment by Christian-CFP** [comment]
Hue is now back on 0.12.26
https://github.com/ebaauw/homebridge-hue/releases
