### ISSUE TITLE
Hoobs 4 beta

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1148]
Want to join hoobs 4 private beta :)

**Comment by askovi** [comment]
Will send you a link this upcoming week.

**Comment by mkellsy** [comment]
Christian send me an email, an I will send you a link.

I need beta testers.

Please note v4 is bleeding edit, and I mean bleeding. Don't use for your main setup yet. If you find any issues let me know.

**Comment by oliverchapple** [comment]
hi 

mikellsy

if you don't mind I would like to try the beta 4 

thanks Oliver

**Comment by mkellsy** [comment]
Oliverchapple

Send me an email
mkellsy@hoobs.org

I will send you some info.
