### ISSUE TITLE
HOOBS 3.3.4 update all rooms lost

### ISSUE THREAD

**Issue by apartmedia** [hoobs-org/HOOBS#1150]
After updating from 3.3.3 to 3.3.4 via web UI all rooms and accessory assignments got lost.
HomeKit is messed up. In Home App everything dumped into Living Room. Same for HOOBS dashboard and accessory page in the web UI.
Even after rearranging and assigning everything back, rebooted hoobs and everything went back again to Living Room and no accessories assigned in any automation.
Multiple users reporting this problem.
See this [posting](https://www.facebook.com/groups/HOOBSorg/permalink/2910931212523202/)
Any way you guys suggest to fix this? May be downgrading to 3.3.3 a possible way? How would a downgrade work?

**Comment by apartmedia** [comment]
Related to issue [#1149](https://github.com/hoobs-org/HOOBS/issues/1149#issue-831294455)

**Comment by LS73** [comment]
Same issue for me since 3.3.4 upgrade

**Comment by e1l52** [comment]
Same issue here.

**Comment by apartmedia** [comment]
Duplicate of #1149
