### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by cdaniels77** [hoobs-org/HOOBS#1151]
**Description**
Since upgrading to 3.3.3 hoobs is not responding, i unable to upgrade to 3.3.4. I cant reboot it nor can i reset the system seems dead

**Version**
3.3.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
3.3.2

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by apartmedia** [comment]
Did you update to latest node lts prior to updating hoobs to 3.3.3?
If not try this, as it was needed for me to get hoobs 3.3.3 running without problems.
Try to avoid updating to hoobs 3.3.4 for now, as there seems to be possible problems with loosing rooms and accessory assignments after rebooting on hoobs 3.3.4.
