### ISSUE TITLE
Upgraded to 3.3.4 from 3.3.3 and now HOOBS fails

### ISSUE THREAD

**Issue by arohl** [hoobs-org/HOOBS#1152]
I get the following log file

15/03/2021, 10:01:41 pm Initializing HAP-NodeJS v0.9.3...
15/03/2021, 10:01:42 pm Loaded plugin 'homebridge-advanced-http-temperature-humidity'
15/03/2021, 10:01:42 pm [3/15/2021, 10:01:42 PM] Registering accessory 'homebridge-advanced-http-temperature-humidity.AdvancedHttpTemperatureHumidity'
15/03/2021, 10:01:42 pm [3/15/2021, 10:01:42 PM] The plugin "homebridge-meross" requires Node.js version of >=14.16.0 which does not satisfy the current Node.js version of v12.16.3. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
15/03/2021, 10:01:43 pm Loaded plugin 'homebridge-meross'
15/03/2021, 10:01:43 pm [3/15/2021, 10:01:43 PM] Registering platform 'homebridge-meross.Meross'
15/03/2021, 10:01:43 pm Loaded plugin 'homebridge-pihole'
15/03/2021, 10:01:43 pm [3/15/2021, 10:01:43 PM] Registering accessory 'homebridge-pihole.Pihole'
15/03/2021, 10:01:43 pm [3/15/2021, 10:01:43 PM] The plugin "homebridge-platform-wemo" requires Node.js version of ^14.16.0 which does not satisfy the current Node.js version of v12.16.3. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
15/03/2021, 10:01:43 pm Loaded plugin 'homebridge-platform-wemo'
15/03/2021, 10:01:43 pm [3/15/2021, 10:01:43 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
15/03/2021, 10:01:43 pm Loading 1 platforms...
15/03/2021, 10:01:43 pm [Belkin WeMo] Initializing BelkinWeMo platform...
15/03/2021, 10:01:43 pm Loading 4 accessories...
15/03/2021, 10:01:43 pm Error loading accessory requested in your config.json at position 1
15/03/2021, 10:01:43 pm Got SIGTERM, shutting down Bridge...

The Node.js errors look fatal but they have been there for some time now and not prevented the bridge from running. Any ideas?

**Comment by apartmedia** [comment]
You should update your node to latest lts version 14.16.0 as your log states and the wemo plugin requires.
Updating node can be be done via SSH by issuing the following terminal command:
`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin —node lts`

Be careful though updating to HOOBS 3.3.4 as there seems to be a problem with loosing rooms and accessory assignment after reboot.
See [this issue](https://github.com/hoobs-org/HOOBS/issues/1149#issue-831294455)

hoobs 3.3.3 doesn‘t seem to have this issue so sticking to this version until there is a fix could be the better choice.

**Comment by bwp91** [comment]
the node version isn’t an issue here.
the issue is something in the config file. could you post your config file removing any sensitive info like passwords?

**Comment by arohl** [comment]
I haven't changed it for quite some time

{
    "server": {
        "home_setup_id": "X-HM://XXXXXXXXXXX",
        "autostart": 0,
        "polling_seconds": 5,
        "port": 80,
        "origin": "*"
    },
    "client": {
        "theme": "hoobs-light",
        "inactive_logoff": 30,
        "default_route": "status",
        "country_code": "AU",
        "temp_units": "celsius",
        "postal_code": "XXXX",
        "locale": "en"
    },
    "bridge": {
        "username": "4C:6A:19:71:AA:25",
        "name": "HOOBS",
        "port": 51826,
        "pin": "XXXXXXXXXXX"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "plugin_map": {
                "index": 0,
                "plugin_name": "homebridge-meross"
            },
            "sign": "XXXXXXXXXXXXXXXXXXXXXXXX",
            "deviceUrl": "192.168.178.139",
            "model": "MSS-310",
            "accessory": "Meross",
            "name": "Amplifier",
            "timestamp": 1587218340,
            "channel": 0,
            "messageId": "XXXXXXXXXXXXXXXXXXXXXXXX"
        },
        {
            "plugin_map": {
                "index": 0,
                "plugin_name": "homebridge-meross"
            },
            "sign": "XXXXXXXXXXXXXXXXXXXXXXXX",
            "deviceUrl": "192.168.178.140",
            "model": "MSS-310",
            "accessory": "Meross",
            "name": "Jotunheim",
            "timestamp": 1587218340,
            "channel": 0,
            "messageId": "XXXXXXXXXXXXXXXXXXXXXXXX"
        },
        {
            "plugin_map": {
                "index": 0,
                "plugin_name": "homebridge-pihole"
            },
            "logLevel": 1,
            "reversed": false,
            "time": 3600,
            "accessory": "Pihole",
            "name": "Pihole",
            "host": "192.168.178.59",
            "port": 80,
            "auth": "XXXXXXXXXXXXXXXXXXXXXXXX",
            "ssl": false,
            "baseDirectory": "/admin/"
        },
        {
            "accessory": "AdvancedHttpTemperatureHumidity",
            "name": "Temperature and Humidity",
            "url": "http://192.168.178.201:9000"
        }
    ],
    "platforms": [
        {
            "platform": "BelkinWeMo",
            "name": "Belkin WeMo",
            "plugin_map": {
                "plugin_name": "homebridge-platform-wemo"
            }
        }
    ]
}

**Comment by bwp91** [comment]
Have you updated meross to 5.0?

Check the change log

https://github.com/donavanbecker/homebridge-meross/blob/master/CHANGELOG.md

you’ll need to update your config

**Comment by arohl** [comment]
Duh! I didn't see that so thanks for pointing it out. Its late here in Oz, so I will try changing it tomorrow

**Comment by arohl** [comment]
Wasn't easy getting the JSON correct but all good now - thanks @bwp91
