### ISSUE TITLE
Please send me an invite for the version 4 beta

### ISSUE THREAD

**Issue by superfeldy** [hoobs-org/HOOBS#1153]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mkellsy** [comment]
Send me an email
mkellsy@hoobs.org
I will send you a link to download the image file.

Please note this is beta software. It will have bugs and issues. If you find them please let me know.

**Comment by superfeldy** [comment]
Thanks!

**Comment by AmeMeEternamen** [comment]
Stop

Thanks,
Franklin Downing-Seldon

Sent From My iPhone... Please Excuse All Typo And Errors!!!
