### ISSUE TITLE
HS103 Wall Outlet not showing up

### ISSUE THREAD

**Issue by DoubleA11** [hoobs-org/HOOBS#1156]
Description
Sorry guys first post total Noob here. I was hoping it was just plug n play but there must be some config file adjustments need to get the HS103 to work.

Expected behavoir
Add my TPLINK smart home outlet to Hoobs

Plugin name
TplinkSmartHome

Version
Hoobs version: 6.3.0

Did you upgrade
Please let us know if you upgraded from a previous version.

 Yes
[ X] No
Pervious version
If you upgraded, please let us know your previous version.

Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.

 Yes
[X ] No
What device are you using?
Please let us know the device you are running HOOBS on.

 HOOBS Box
[X ] HOOBS SD Card
 Custom Install
If this is a custom install, what's your operating system?
NO

**Comment by bwp91** [comment]
Please post your config file (from Configuration -> Advanced), removing any personal information, to check that you have the plugin configured properly.

Also, is the outlet connected to your wifi and would it be discoverable over your network by HOOBS?
