### ISSUE TITLE
Cannot update Hoobs to core 3.3.5

### ISSUE THREAD

**Issue by to16321** [hoobs-org/HOOBS#1157]
I cannot update my hoobs to 3.3.5, I get this:

npm
16.3.2021, 09:41:30 ERR! code ENOTEMPTY
16.3.2021, 09:41:30 npm ERR! syscall rename
16.3.2021, 09:41:30 npm ERR!
16.3.2021, 09:41:30 path /usr/local/lib/node_modules/@hoobs/hoobs
16.3.2021, 09:41:30 npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
16.3.2021, 09:41:30 npm ERR! errno -39
16.3.2021, 09:41:30 
16.3.2021, 09:41:30 npm
16.3.2021, 09:41:30 ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'
16.3.2021, 09:41:30 
16.3.2021, 09:41:30 
16.3.2021, 09:41:30 
16.3.2021, 09:41:30 npm ERR! A complete log of this run can be found in:
16.3.2021, 09:41:30 npm ERR!     /root/.npm/_logs/2021-03-16T08_41_30_850Z-debug.log

Anybody can help please?

Thanks.

**Comment by bwp91** [comment]
Stop the HOOBS service and run these commands from the terminal separately:

```
sudo rm -fR ~/.npm
sudo rm -fR /usr/local/lib/node_modules/@hoobs/hoobs
sudo npm install -g --unsafe-perm  @hoobs/hoobs
```

**Comment by to16321** [comment]
Worked perfect, thank you.

**Comment by bwp91** [comment]
Fab. Please remember to close this issue if everything is sorted!
