### ISSUE TITLE
Plugin speedtest-net Node Update

### ISSUE THREAD

**Issue by Stewart06** [hoobs-org/HOOBS#1158]
Bonjour,

Le plugin SpeedTest demande que Node soit mise à jour vers la version 12.16.

Y a t'il une solution pour le mettre à jour ?

The plugin "homebridge-speedtest-net" requires Node.js version of ^12.16.0 which does not satisfy the current Node.js version of v12.14.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
16/03/2021 à 10:19:31 Loaded plugin 'homebridge-speedtest-net'
16/03/2021 à 10:19:32 [3/16/2021, 10:19:32 AM] Registering accessory 'homebridge-speedtest-net.SpeedtestNet'
16/03/2021 à 10:19:32 Loaded plugin 'homebridge-wol'

**Comment by bwp91** [comment]
If you are confident with connecting via SSH to HOOBS, run this command to update node:

```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 14.16.0
```

Once it has finished (it might take a few minutes), then run these two commands separately:

```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

I would advise against using the HOOBS terminal as sometimes the UI can become unavailable between running the commands.

**Comment by Stewart06** [comment]
Ok merci !

Y a t'il un risque ?

**Comment by bwp91** [comment]
I personally do this every time there is a new version of node available, never had any issues so long as done via SSH.

**Comment by Stewart06** [comment]
Ok, mais que veux dire c'est deux lignes de commandes ?
ça supprime HOOBS ?

sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs

Pourquoi HOOBS ne l'intègre pas directement dans les mises à jours ?

**Comment by bwp91** [comment]
HOOBS needs to be rebuilt against the new version of node. These commands uninstall and reinstall HOOBS.

But this does not affect your plugins, configurations, etc. All this data is stored in a different place to the main HOOBS files that are reinstalled.
