### ISSUE TITLE
Not able to update to 3.3.5

### ISSUE THREAD

**Issue by svobod3** [hoobs-org/HOOBS#1159]
**Description**
I use web interface where update to new version 3.3.5 is available. When I click on it, I can see progress bar, but after a minute I get back to the same page (current installed version is 3.3.3 and 3.3.5 is available)
BTW I had the same problem with update to 3.3.4 (maybe fortunately:))
<img width="836" alt="3 3 5 available" src="https://user-images.githubusercontent.com/79516491/111288998-00d8b680-8645-11eb-9fe0-1c6d4a7d48e2.png">
<img width="840" alt="progress bar" src="https://user-images.githubusercontent.com/79516491/111289011-046c3d80-8645-11eb-9b6b-335e3b7a0380.png">

**Version**
3.3.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
3.3.3

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Roomba2
Tuya Web
Harmony

**Post your config**

{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "xxx",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "CZ",
        "postal_code": "xxx",
        "latitude": "xxx",
        "longitude": "xxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xxx",
        "username": "xxx"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Roomba2",
            "plugin_map": {
                "plugin_name": "homebridge-roomba2",
                "index": 0
            },
            "dockContactSensor": true,
            "name": "Cleaner",
            "model": "980",
            "blid": "xxx",
            "robotpwd": "xxx",
            "ipaddress": "192.168.1.15",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "runningContactSensor": true,
            "binContactSensor": true,
            "cacheTTL": 600
        }
    ],
    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "activitiesToPublishAsAccessoriesSwitch": [
                "TV",
                "Apple TV"
            ],
            "devicesToPublishAsAccessoriesSwitch": [
                "LG OLED TV|TV Channel Up;ChannelUp",
                "LG OLED TV|TV Channel Down;ChannelDown",
                "Marantz AV Receiver|TV Mute;Mute",
                "Marantz AV Receiver|TV Volume Up;VolumeUp;VolumeUp;VolumeUp;VolumeUp;VolumeUp;VolumeUp;VolumeUp;VolumeUp",
                "Marantz AV Receiver|TV Volume Down;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown"
            ],
            "sequencesToPublishAsAccessoriesSwitch": [
                "TV Channel 1",
                "TV Channel 4",
                "TV Channel 8"
            ],
            "name": "Harmony Hub",
            "hubIP": "192.168.1.25",
            "hubName": "HarmonyHub",
            "cleanCache": true,
            "publishAllTVAsExternalAccessory": true,
            "configureAccesscontrol": false,
            "switchAccessories": true,
            "publishGeneralMuteSwitch": false,
            "publishGeneralVolumeSlider": false,
            "publishGeneralVolumeSwitches": false,
            "linkVolumeControlToTV": true,
            "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "publishDevicesAsIndividualAccessories": true,
            "publishSequencesAsIndividualAccessories": true,
            "publishHomeControlsAsIndividualAccessories": true,
            "showCommandsAtStartup": true,
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "skippedIfSameStateActivities": [],
            "homeControlsToPublishAsAccessoriesSwitch": [],
            "otherPlatforms": []
        },
        {
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            },
            "name": "TuyaWebPlatform",
            "scenes": false,
            "options": {
                "platform": "tuya",
                "username": "xxx",
                "password": "xxx",
                "countryCode": "420",
                "pollingInterval": 600
            }
        }
    ]
}

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Looks like NPM is root locked.

Run 
```
rm -fR ~/.npm
```

And try again.

**Comment by svobod3** [comment]
I executed command above, but behaviour is still the same:( I click on update button, but after a minute of progress bar I am still on 3.3.3

**Comment by mkellsy** [comment]
Run this
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

If it fails post the output.

**Comment by svobod3** [comment]
Here is the result:

obsbs@hoobs:/home/hoobs/.hoobs/etc $ sudo npm install -g --unsafe-perm @hoobs/hoo
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-16T15_37_06_203Z-debug.log
hoobs@hoobs:/home/hoobs/.hoobs/etc $

**Comment by mkellsy** [comment]
Try uninstall first
```
sudo npm uninstall @hoobs/hoobs
sudo install -g --unsafe-perm @hoobs/hoobs
```

If that fails

```
sudo rm -fR /usr/local/lib/node_modules/@hoobs/hoobs
sudo install -g --unsafe-perm @hoobs/hoobs
```

NPM has been acting wired lately.

**Comment by svobod3** [comment]
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo npm uninstall @hoobs/hoobs

up to date, audited 163 packages in 20s

found 0 vulnerabilities
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo install -g --unsafe-perm @hoobs/hoobs
install: missing destination file operand after '@hoobs/hoobs'
Try 'install --help' for more information.
hoobs@hoobs:/home/hoobs/.hoobs/etc $ 


hoobs@hoobs:/home/hoobs/.hoobs/etc $ 
obs/hoobsbs:/home/hoobs/.hoobs/etc $ sudo rm -fR /usr/local/lib/node_modules/@hoo
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo install -g --unsafe-perm @hoobs/hoobs
install: missing destination file operand after '@hoobs/hoobs'
Try 'install --help' for more information.
hoobs@hoobs:/home/hoobs/.hoobs/etc $

**Comment by svobod3** [comment]
and now when I want to connect to hoobs via browser I get this:

Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs'
    at Object.realpathSync (fs.js:1728:7)
    at Function.get paths [as paths] (/usr/local/lib/node_modules/@hoobs/hoobs/server/server.js:80:40)
    at /usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:185:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:315:20)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:421:12)

**Comment by mkellsy** [comment]
Try this

```
sudo rm -fR /usr/local/lib/node_modules/@hoobs
sudo install -g --unsafe-perm @hoobs/hoobs
```

**Comment by svobod3** [comment]
when I want to connect via terminal on Mac, I get this

jirisvoboda@Jirkuv-iMac ~ % ssh hoobs@hoobs.local
zsh: command not found: ssh hoobs@hoobs.local
jirisvoboda@Jirkuv-iMac ~ %

**Comment by mkellsy** [comment]
Source https://stackoverflow.com/questions/18428374/commands-not-found-on-zsh

```
PATH=/bin:/usr/bin:/usr/local/bin:${PATH}
export PATH
```

Then

```
ssh hoobs@hoobs.local
```

**Comment by svobod3** [comment]
great, thanks, I am now connected to hoobs via terminal
this is the result of executing 2 commands you proposed:

hoobs@hoobs:~ $ sudo rm -fR /usr/local/lib/node_modules/@hoobs
hoobs@hoobs:~ $ sudo install -g --unsafe-perm @hoobs/hoobs
install: missing destination file operand after '@hoobs/hoobs'
Try 'install --help' for more information.
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
Try running this
```
npm cache clean
sudo npm cache clean
```

clear both user and root cache

**Comment by mkellsy** [comment]
If npm cache clear doesn't work. Manually remove the cache

```
rm -fR ~/.npm
```

```
sudo -i
rm -fR ~/.npm
exit
```

Then try to install again.
```
sudo install -g --unsafe-perm @hoobs/hoobs
```

The issue is, NPM and sudo don't get along. IN our next major release we are ditching NPM and moving to APT, because of errors like this.

**Comment by svobod3** [comment]
hoobs@hoobs:~ $ npm cache clean
npm notice 
npm notice New patch version of npm available! 7.6.0 -> 7.6.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.6.3
npm notice Run npm install -g npm@7.6.3 to update!
npm notice 
npm ERR! As of npm@5, the npm cache self-heals from corruption issues
npm ERR! by treating integrity mismatches as cache misses.  As a result,
npm ERR! data extracted from the cache is guaranteed to be valid.  If you
npm ERR! want to make sure everything is consistent, use `npm cache verify`
npm ERR! instead.  Deleting the cache can only make npm go slower, and is
npm ERR! not likely to correct any problems you may be encountering!
npm ERR! 
npm ERR! On the other hand, if you're debugging an issue with the installer,
npm ERR! or race conditions that depend on the timing of writing to an empty
npm ERR! cache, you can use `npm install --cache /tmp/empty-cache` to use a
npm ERR! temporary cache instead of nuking the actual one.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command
npm ERR! with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-03-16T16_14_53_285Z-debug.log
hoobs@hoobs:~ $ sudo npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues
npm ERR! by treating integrity mismatches as cache misses.  As a result,
npm ERR! data extracted from the cache is guaranteed to be valid.  If you
npm ERR! want to make sure everything is consistent, use `npm cache verify`
npm ERR! instead.  Deleting the cache can only make npm go slower, and is
npm ERR! not likely to correct any problems you may be encountering!
npm ERR! 
npm ERR! On the other hand, if you're debugging an issue with the installer,
npm ERR! or race conditions that depend on the timing of writing to an empty
npm ERR! cache, you can use `npm install --cache /tmp/empty-cache` to use a
npm ERR! temporary cache instead of nuking the actual one.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command
npm ERR! with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-16T16_15_12_952Z-debug.log
hoobs@hoobs:~ $ 
hoobs@hoobs:~ $ 
hoobs@hoobs:~ $ 
hoobs@hoobs:~ $ 
hoobs@hoobs:~ $ 
hoobs@hoobs:~ $ rm -fR ~/.npm
hoobs@hoobs:~ $ sudo -i
root@hoobs:~# rm -fR ~/.npm
root@hoobs:~# exit
logout
hoobs@hoobs:~ $ 
hoobs@hoobs:~ $ sudo install -g --unsafe-perm @hoobs/hoobs
install: missing destination file operand after '@hoobs/hoobs'
Try 'install --help' for more information.
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
I messed up on my posts

```
sudo **npm** install -g --unsafe-perm @hoobs/hoobs
```

missing the **npm**

**Comment by svobod3** [comment]
Great, it looks good. I can connect to hoobs via web again and it is updated to 3.3.5
Anything else I should do?

hoobs@hoobs:~ $ sudo npm install -g --unsafe-perm @hoobs/hoobs

added 227 packages, and audited 228 packages in 5m

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New patch version of npm available! 7.6.0 -> 7.6.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.6.3
npm notice Run npm install -g npm@7.6.3 to update!
npm notice 
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
NPM has a new version
```
sudo npm install -g npm
```

That's it if you want to.

**Comment by svobod3** [comment]
strange, I executed the command, but I got info about update again - see below

hoobs@hoobs:~ $ sudo npm install -g npm

changed 14 packages, and audited 254 packages in 23s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New patch version of npm available! 7.6.0 -> 7.6.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.6.3
npm notice Run npm install -g npm@7.6.3 to update!
npm notice 
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
It's telling you what to run, you just need to add sudo
```
sudo npm install -g npm@7.6.3
```

**Comment by svobod3** [comment]
thanks a lot for your support
