### ISSUE TITLE
terminal wierd behaviour on lower lines when returning command key up

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#116]
also strange flickering input stroke
<img width="856" alt="Screenshot 2019-08-31 at 13 53 55" src="https://user-images.githubusercontent.com/50763727/64063623-e243d380-cbf6-11e9-8603-07bf6f78a4e3.png">

**Comment by mkellsy** [comment]
This is xterm. If you have an issue with xterm please use their issue tracker. https://github.com/xtermjs/xterm.js/

**Comment by mkellsy** [comment]
i removed the blinking cursor. the xterm community said this causes all the problems.

Fixed in 3.0.0-beta.39
