### ISSUE TITLE
NodeJS version

### ISSUE THREAD

**Issue by nairnet** [hoobs-org/HOOBS#1161]
I'm seeing entries in my logs that NodeJS needs updating. I can't see any guides on HOOBS site on how to do this?

`16/03/2021, 11:11:26 [Ring] There is a known issue with your current NodeJS version (v12.16.3).  Please see https://github.com/dgreif/ring/wiki/NGHTTP2_ENHANCE_YOUR_CALM-Error for details
16/03/2021, 11:11:28 [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...`

Thanks

**Comment by bwp91** [comment]
Please see https://github.com/hoobs-org/HOOBS/issues/1158#issuecomment-800101363

**Comment by nairnet** [comment]
Thanks @bwp91 that worked a treat!
Why is there no update button for Node Version on the dashboard?
Doing this also automatically updated my HOOBS to v3.3.5 (was on 3.3.3 prior)

Logged into my HOOBS box via SSH from macOS using Terminal:

`ssh hoobs@hoobs.local`

Note: hoobsadmin is the default password for the hoobs account

Step 1:
`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 14.16.0`
Step 2:
`sudo npm uninstall -g @hoobs/hoobs`
Step 3:
`sudo npm install -g --unsafe-perm @hoobs/hoobs`

Done :)
