### ISSUE TITLE
Noobie question re updating my hoobs running pi

### ISSUE THREAD

**Issue by arohl** [hoobs-org/HOOBS#1162]
I like the idea of an easy to use system - I previously used homebridge and have been pleased with hoobs so far. I regularly update the hoobs system and assumed this this would update everything including the OS. However, given the comments I have just read it seems that the NodeJS version needs to be updated via ssh. Is there anything else I should be looking to update when I ssh in? I'm not even sure what os the pi is running!

Thanks for any advice

  Andrew

**Comment by askovi** [comment]
All you need to do is paste the command below in your terminal after logging in via SSH. It will upgrade node to the latest stable release:

wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts

**Comment by arohl** [comment]
@askovi That's how you update npm. What about updating the underlying system for e.g. kernel updates

**Comment by bwp91** [comment]
I don't know if this is recommended and this is certainly not 'endorsed' by hoobs (get the disclaimer in!) but...

To keep my hoobs box (and homebridge pi) up to date, I use

```
sudo apt update
sudo apt full-upgrade
```

to keep the packages up to date,

also keep node updated (with the above command for hoobs)

and also of course keep HOOBS and its plugins up to date.

**Comment by mkellsy** [comment]
@bwp91 that is correct. See in HOOBS 4 (next major release) we are moving to an APT repo. So those commands will upgrade the OS, Node and HOOBS.

**Comment by arohl** [comment]
thanks @mkellsy and @bwp91 for your advice. Have updated Raspain and rebooted and all seems well
