### ISSUE TITLE
Failed upgrade from 3.3.3 to 3.3.5

### ISSUE THREAD

**Issue by JohnBarger** [hoobs-org/HOOBS#1163]
**Description**
Every time I upgrade from 3.3.3 (or 3.2.9) to 3.3.5, the the system seems to be reset to new.  The web interface asks me to setup as a new user and there are no accessories/plug-ins configured.

Luckily I can easily restore my VM from a snapshot and get back to working order.

**Version**
Upgrading from 3.3.3 or 3.2.9 to 3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
I've tried both 3.3.3 and 3.2.9

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Fedora 32 running on ESXi 6.5

**List your plugins**
Ring
Roomba Stv
Http Advanced Accessory

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": [REDACTED],
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hunters-green",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "03079"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": [REDACTED],
        "username": [REDACTED]
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Roomba",
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            },
            "name": "R2-Dirt2",
            "model": "R960020",
            "blid": "69B8860C81239760",
            "robotpwd": [REDACTED],
            "ipaddress": "192.168.222.72",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true
        },
        {
            "accessory": "Roomba",
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            },
            "name": "Sweep-3PO",
            "model": "R98----",
            "blid": "3178840071028780",
            "robotpwd": [REDACTED],
            "ipaddress": "192.168.222.71",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": [REDACTED],
            "hideLightGroups": false,
            "hideDoorbellSwitch": false,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": false,
            "hideInHomeDoorbellSwitch": false,
            "hideAlarmSirenSwitch": false,
            "hideUnsupportedServices": true,
            "showPanicButtons": true
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
Logs were wiped out when restoring back to previous version.
```

**Additional context**

**Comment by mkellsy** [comment]
Try upgrading manually.

Run
```
sudo npm install -g --unsafe-perm @hoobs/hoobs

```

**Comment by JohnBarger** [comment]
Same result.

Sent from my iPhone

On Mar 16, 2021, at 11:19 AM, Michael Kellsy ***@***.***> wrote:

﻿

Try upgrading manually.

Run

sudo npm install -g --unsafe-perm @hoobs/hoobs

**Comment by mkellsy** [comment]
When you run
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

What does the output say?

**Comment by JohnBarger** [comment]
From CLI:

***@***.*** ~]# sudo npm install -g --unsafe-perm @hoobs/hoobs
/usr/local/bin/hoobs -> ***@***.***/hoobs/bin/hoobs

> @***@***.*** postinstall ***@***.***/hoobs
> bin/hoobs upgrade

+ @***@***.***
updated 4 packages in 9.701s
***@***.*** ~]# 
According to the Web interface, HOOBS was still on 3.3.3.  I rebooted from the CLI and then the HOOBS interface asked me to log in as a new user.

John Barger

**Comment by mkellsy** [comment]
Run this
```
ls -la ~/.hoobs/etc
```

Then post the results

**Comment by JohnBarger** [comment]
***@***.*** ~]# ls -la ~/.hoobs/etc
total 28
drwxr-xr-x. 4 root root  203 Mar 16 13:19 .
drwxr-xr-x. 5 root root   97 Mar 16 11:21 ..
-rw-r--r--. 1 root root  352 May  4  2020 access.json
drwxr-xr-x. 2 root root   31 May  4  2020 accessories
-rw-r--r--. 1 root root 1694 May  4  2020 config-1588611524091.json
-rw-r--r--. 1 root root 1694 May  4  2020 config-1588613026125.json
-rw-r--r--. 1 root root 2736 Mar 16 12:24 config.json
-rw-r--r--. 1 root root  686 Mar 16 13:19 dashboard.json
-rw-r--r--. 1 root root    2 May  4  2020 layout.json
drwxr-xr-x. 2 root root  166 May 17  2020 persist
-rw-r--r--. 1 root root   79 Mar 15 17:22 .ring.json
***@***.*** ~]# 

John Barger

**Comment by mkellsy** [comment]
Your setup is still there. Try rebooting.

**Comment by JohnBarger** [comment]
Done.

Still getting the “New Administrator” login on:


John Barger

**Comment by mkellsy** [comment]
backup the ~/.hoobs folder. (make two copies just in case)
```
cp -r ~/.hoobs ~/hoobs-backup
cp -r ~/.hoobs ~/hoobs-restore
```

Then in the UI setup a new user.
Then restore your backup

```
rm -fR ~/.hoobs
mv ~/hoobs-restore ~/.hoobs
```

And reboot.

**Comment by JohnBarger** [comment]
Didn’t seem to help:

3/16/2021, 2:01:33 PM HOOBS listening on port 80.
3/16/2021, 2:01:34 PM Initializing HAP-NodeJS v0.9.3...
3/16/2021, 2:01:34 PM No plugins installed.
3/16/2021, 2:01:34 PM Preparing Advertiser for 'HOOBS B3E5' using bonjour-hap backend!
3/16/2021, 2:01:34 PM Starting to advertise 'HOOBS B3E5' using bonjour-hap backend!
3/16/2021, 2:01:34 PM Bridge is running on port 51826.

Should I try this?

Revert back to 3.3.3 snapshot
Back up that config
Upgrade to 3.5
Create User
Restore config from 3.3.3?

John Barger

**Comment by mkellsy** [comment]
That should work.

**Comment by JohnBarger** [comment]
That didn’t work.  I got frustrated and just rebuilt from scratch.  I seem to be OK now.

John Barger

**Comment by mkellsy** [comment]
The problem has been pin pointed and we have addressed this in our next major release.

**Comment by Schattenkaiser** [comment]
I've the same issue. Upgrade from 3.3.3 -> 3.3.5 doesn't work.
I tried automatic upgrade - got an error
I tried manual upgrade using the suggested code: sudo npm install -g --unsafe-perm @hoobs/hoobs - got an error as displayed below

> npm ERR! code ENOTEMPTY
> npm ERR! syscall rename
> npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
> npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
> npm ERR! errno -39
> npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-03-21T19_11_28_499Z-debug.log

what else can I do?

**Comment by mkellsy** [comment]
Try running
```
sudo npm uninstall -g @hoobs/hoobs
sudo rm -fR /usr/local/lib/node_modules/@hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by Schattenkaiser** [comment]
Thanks - that worked, without any loss of my other settings
