### ISSUE TITLE
homebridge-somfy-hotwired

### ISSUE THREAD

**Issue by Johan8012** [hoobs-org/HOOBS#1166]
How do I configure the config file for this plugin?
When I try to edit it says invalid json.

**Description**
A clear and concise description of what the plugin is doing.

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by bwp91** [comment]
If you post your current config perhaps I can help with where you need to add the new plugin config (remove current sensitive info like passwords etc)

**Comment by Johan8012** [comment]
"description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": false,
            "effects": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": false,
            "users": {
                "XXXXX"
            },
            "sensors": true,
            "hueMotionTemperatureHistory": true,
            "scenesAsSwitch": false,
            "linkButton": false,
            "groups": false,
            "rules": false,
            "scenes": false,
            "rooms": false,
            "schedules": false
        },
        {
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            },
            "name": "TuyaWebPlatform",
            "scenes": false,
            "options": {
                "platform": "smart_life",
                "countryCode": "XXX",
                "username": "jXXXX",
                "password": "XXXX",
                "pollingInterval": 3600
            }
        },
        {
            "platform": "Nest-cam",
            "plugin_map": {
                "plugin_name": "homebridge-nest-cam"
            },
            "options": {
                "ffmpegCodec": "libx264",
                "streamQuality": "HIGH",
                "alertCheckRate": 10,
                "alertCooldownRate": 180,
                "importantOnly": true,
                "motionDetection": true,
                "streamingSwitch": true,
                "chimeSwitch": true,
                "announcementsSwitch": true,
                "doorbellAlerts": true,
                "doorbellSwitch": true,
                "audioSwitch": true,
                "fieldTest": false
            },
            "refreshToken": "X"
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest",
            "googleAuth": {
                "issueToken": "X",
                "cookies": "X",
                "apiKey": "X"
            }
        }
    ]
}

**Comment by Johan8012** [comment]
Thank you! Where and how should I edit? The example looks like this.

{
    "name": "Shutter",
    "pin_up": "3",
    "pin_down": "5",
    "pin_my_position": "7",
    "movement_duration": "11",
    "accessory": "Homebridge-somfy-hotwired",
    "default_position": "up"
}

**Comment by bwp91** [comment]
The whole example you posted needs to go inside the `"accessories": [],` square brackets

make sure you have the plugin installed first.

then from your config you posted:

```json
"ports": {},
"accessories": [{
   "name": "Shutter",
   "pin_up": "3",
   "pin_down": "5",
   "pin_my_position": "7",
   "movement_duration": "11",
   "accessory": "Homebridge-somfy-hotwired",
   "default_position": "up"
   }
],
"platforms": [
```
