### ISSUE TITLE
homebridge-mercedesme not supported

### ISSUE THREAD

**Issue by e1l52** [hoobs-org/HOOBS#1167]
**Description**
Looks like that this plugin is not running in HOOBS.
HomeBridge / Config UI X is needed.
Any chance to get it running under HOOBS ?

**Expected behavoir**

**Plugin name**
homebridge-mercedesme

**Please report the issue to the plugin developer**
Done.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
The plugin seems to run just fine. What issues have you encountered?

**Comment by e1l52** [comment]
The plugin needs an access token to work with the Mercedes servers. 
This token is generated during configuration with Config UI X.
I can't find a way without.

**Comment by askovi** [comment]
Please read the First steps (obtain Client ID and Client Secret) here: https://plugins.hoobs.org/plugin/homebridge-mercedesme

I will add this to the list of custom plugins to integrate into the HOOBS 4 UI. For now you must get the details manually and add them to the json box on the plugin config according to the plugin’s documentation.

**Comment by e1l52** [comment]
Thanks a lot for your answer. I already added Client ID and Client Secret, but in addition there is an access token needed, which i can't add manually - as fas as I understand util now. This is done by Config UI X.
I see the following log message :

`There is no access token configured for this car. This car will be skipped.`

**Comment by adriaan** [comment]
I'm having a similar issue with another plugin. The plugin uses a custom user interface for the plugin configuration (https://developers.homebridge.io/#/custom-plugin-ui). This works as expected when the plugin is installed in Homebridge, but the custom UI isn't presented in HOOBS. Instead HOOBS presents an auto generated form based on the config schema (which is not something a user of the plugin can readily fill in). Does HOOBS not support Homebridge custom UI?
