### ISSUE TITLE
Unable to update or uninstall plugins

### ISSUE THREAD

**Issue by Mike-Stark-Barnes** [hoobs-org/HOOBS#1168]
Hi, my Hoobs (version 3.3.5, Raspberry Pi 4) is showing updates available for both the Ring and TPLink plugins, however, even though the updates state that they've completed the update button still shows that there's an update available. If I try to uninstall the plugins (I don't need the TPLink one anymore) the uninstall fails.
Looking at the logs I see the following for the ring update:

18/03/2021, 07:43:54 npm
18/03/2021, 07:43:54  ERR! code EEXIST
18/03/2021, 07:43:54 npm
18/03/2021, 07:43:54 
18/03/2021, 07:43:54 ERR!
18/03/2021, 07:43:54 
18/03/2021, 07:43:54 path
18/03/2021, 07:43:54  /home/hoobs/.hoobs/node_modules/.bin/ring-auth-cli
18/03/2021, 07:43:54 npm ERR!
18/03/2021, 07:43:54  Refusing to delete /home/hoobs/.hoobs/node_modules/.bin/ring-auth-cli: is outside /home/hoobs/.hoobs/node_modules/homebridge-ring and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/.bin/ring-auth-cli
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

Any idea how I can resolve this otherwise it looks like I'm going to be stuck on the versions of the plugins that I'm currently on?

Thanks in advance.

**Comment by askovi** [comment]
Delete the lock file using the HOOBS Terminal with the following command (there won't be any output):

`sudo rm -fR /home/hoobs/.hoobs/node_modules/.bin/ring-auth-cli`

Then try updating the Ring plugin again.

**Comment by Mike-Stark-Barnes** [comment]
Thanks, but it still doesn't work. still shows that an update is available and the log shows this:

18/03/2021, 16:16:46 npm
18/03/2021, 16:16:46  ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/.bin/ring-device-data-cli
18/03/2021, 16:16:47 npm ERR!
18/03/2021, 16:16:47  Refusing to delete /home/hoobs/.hoobs/node_modules/.bin/ring-device-data-cli: is outside /home/hoobs/.hoobs/node_modules/homebridge-ring and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/.bin/ring-device-data-cli
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

**Comment by askovi** [comment]
looks like there is another file in there that's blocking

sudo rm -fR /home/hoobs/.hoobs/node_modules/.bin/ring-device-data-cli

**Comment by Mike-Stark-Barnes** [comment]
Still the same I'm afraid:
npm ERR! path /home/hoobs/.hoobs/node_modules/.bin/systeminformation
18/03/2021, 16:37:21 npm ERR!
18/03/2021, 16:37:21  Refusing to delete /home/hoobs/.hoobs/node_modules/.bin/systeminformation: is outside /home/hoobs/.hoobs/node_modules/systeminformation and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/.bin/systeminformation
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

**Comment by askovi** [comment]
Seems like it's complaining about every single file in that .bin folder so just delete the whole folder:

sudo rm -fR /home/hoobs/.hoobs/node_modules/.bin/

**Comment by Mike-Stark-Barnes** [comment]
You're a star. That's resolved it for the Ring plugin and I was hoping that was also what was stopping the TPLink plugin from uninstalling / updating too but unfortunately not:

8/03/2021, 16:51:28 npm
18/03/2021, 16:51:28  ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/homebridge-tplink-smarthome/node_modules/.bin/semver
18/03/2021, 16:51:28 npm
18/03/2021, 16:51:28 
18/03/2021, 16:51:28 ERR!
18/03/2021, 16:51:28  Refusing to delete /home/hoobs/.hoobs/node_modules/homebridge-tplink-smarthome/node_modules/.bin/semver: is outside /home/hoobs/.hoobs/node_modules/homebridge-tplink-smarthome/node_modules/semver and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/homebridge-tplink-smarthome/node_modules/.bin/semver
npm ERR! Remove the existing file and try again, or run npm
18/03/2021, 16:51:28 npm ERR! with --force to overwrite files recklessly.

**Comment by Mike-Stark-Barnes** [comment]
Sorted it looking at you previous code. Thanks again for your help.

**Comment by askovi** [comment]
You're welcome :)
