### ISSUE TITLE
Hoobs does not show up on Hoobs - new user

### ISSUE THREAD

**Issue by djfunkysara** [hoobs-org/HOOBS#1169]
I have tried resetting and restart new names and it does not work

**Comment by askovi** [comment]
Please provide more details about your issue.

**Comment by djfunkysara** [comment]
Currently the Home bridge - Hoob don’t show up on home app. So I read that
it’s there but so I wanted to add broadlink app via a plug-in but realise
that it does not work and need scripting . So I abit lost here . After
adding the broadlink plugin it does appear on home app as “learn “ and
“scan frequency” icon . Any one can help me on this or YouTube video for
broadlink and nest

**Comment by djfunkysara** [comment]
Hi

Adding on to it ... I assume that the new home app does not show hoob
bridge on as a icon ? Am I right ?
