### ISSUE TITLE
cannot install google home

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#117]
rpi4 1gb
still not working on beta 38
- don't display as installed plugin after installation
- don't show in settings

log
[Homebridge] [8/31/2019, 1:56:51 PM] Got SIGINT, shutting down service...
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826

**Comment by BobbySlope** [comment]
runs perfectly on macOS

**Comment by mkellsy** [comment]
This is an issue with the NGINX server.
Fixed in 3.0.0-beta.39

You need to run this though
sudo hoobs-init

Or start over. This is a beta. We are supporting 2.11- to 3.0.0 not within the beta.
