### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by mstahl79** [hoobs-org/HOOBS#1170]
I am continuously getting this message in the logs when the service restarts.  I can not find what is causing this

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

**Comment by askovi** [comment]
Please see here: https://github.com/hoobs-org/HOOBS/issues/1154#issuecomment-799800839
