### ISSUE TITLE
502 error / All the problems

### ISSUE THREAD

**Issue by RichDias** [hoobs-org/HOOBS#1171]
Been getting a lot of different errors after 502 error. 
Had a EADDRINUSE for port 80.  Change to port 8080, but it started happening for that port.  When I Can get the UI to run, most plugins fail to install.  The ones that do trigger a shutdown of the bridge.  
most recently had a “Got SIGNIT” and the whole instance shut down.  

Any idea where to begin?

**Comment by askovi** [comment]
Please check your logs from the left menu or upload your entire log file here from settings->backup->log

Also please provide more details about the system you’re running HOOBS on
