### ISSUE TITLE
Hoobs in a box not working

### ISSUE THREAD

**Issue by jakehobson** [hoobs-org/HOOBS#1172]
**Description**
_**I just received yesterday my HOOBS in A box.  I followed the instructions: I plugged it in.  I waited.  Nothing.  The hoobs.local page returns an error (I waited quite a while).  I tried via Wifi.  Nothing.  Can't log in to Hoobs network.**_

**Version**
Please include the version of HOOBS you are using: _**It says model HLSF-1**_

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
**_- [X ] No_**

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
_**- [ X] No**_

**What device are you using?**
Please let us know the device you are running HOOBS on.
**_- [X] HOOBS Box_**
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
**_Mac OS 11.2.3 Big Sur_**

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**_Didn't get that far._**

Thank you for your help.

**Comment by askovi** [comment]
Please make sure that the HOOBS box is connected to the network. Check the ethernet port lights if the amber light is solid and the green light is blinking (when connected by ethernet cable). 

If they are then check your router’s admin page or app for the devices on your network and see if HOOBS shows up. 

Grab the ip assigned to HOOBS by your router and connect to it like this: http://192.168.x.x 

If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)
