### ISSUE TITLE
Upgrades with this product a really bad

### ISSUE THREAD

**Issue by debratton** [hoobs-org/HOOBS#1174]
**Description**
It said there was an upgrade available, I believe from 3.3.3 to 3.3.5

**Version**
I believe 3.3.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
I believe 3.3.3

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
No this is out of the box from Hoobs.

**List your plugins**
Ring and MyQ

**Additional context**
I wasn't able to do anything.  Finally was able to login ssh via terminal after unplugging and plugging device back in.  I saw individuals posted to upgrade manually => sudo npm install -g --unsafe-perm @hoobs/hoobs but even after that I can now connect to web interface but it just has a HOOBS with logo and yellow line going back in fourth.
![2021-03-20 12 23 19](https://user-images.githubusercontent.com/13292664/111880047-1b799b00-8977-11eb-92d6-3d78ff3e10f7.png)

**Comment by askovi** [comment]
Please get the logs via ssh with command
`sudo hoobs service log`

**Comment by debratton** [comment]
I ran the cmd, not sure if you want me to open, but I have no idea where it is located.

![2021-03-20 13 28 19](https://user-images.githubusercontent.com/13292664/111881778-2684f900-8980-11eb-95d0-c002b7c6f0b4.png)

**Comment by apartmedia** [comment]
> I ran the cmd, not sure if you want me to open, but I have no idea where it is located.
This command displays the hoobs log on your terminal screen.
Copy them and post it here to see what goes wrong.

**Comment by apartmedia** [comment]
> I ran the cmd, not sure if you want me to open, but I have no idea where it is located.
> 

This command displays the hoobs log on your terminal screen.
Copy them and post it here to see what goes wrong.

**Comment by debratton** [comment]
After I initiate the cmd, nothing displays on terminal.

**Comment by jlg89** [comment]
You can always try a full hoobs reinstall. Backup your configuration first (just in case!), then run the following commands:

sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm  @hoobs/hoobs

I've had to use this on a couple of occasions post-upgrade.
