### ISSUE TITLE
Plugin configuration always blank, unable to list plugins or config details at all

### ISSUE THREAD

**Issue by txara** [hoobs-org/HOOBS#1176]
**Description**
Configuration page almost always blank, does not display information

**Version**
3.3.5 and all prior

**Did you upgrade**
- [x] Yes

**Pervious version**
all prior

**Did you originally (<-spelling) upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
Not sure, possibly?  

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS SD Card, on raspberry pi

**If this is a custom install, what's your operating system?**

**List your plugins**

 "homebridge-broadlink-rm-pro": "^4.4.1",
 "homebridge-camera-ffmpeg": "^3.1.2",
 "homebridge-ewelink": "^3.18.1",
 "homebridge-gpio-device-petaren": "^0.4.9",
 "homebridge-messenger": "0.0.8"
 
**Post your config**
i can't get to it

* Remove any passwords from the config file. This is public.

**Post your log**
You can get the log from the interface. This is in the Log section.

**Additional context**
seems like the web service (node) allows a plugin code to cause the page to fail.

**Comment by txara** [comment]
I can manually SSH and get to the configs, the the web admin doesn't work -- I'm amazed when it does once in a while, been that way since installing few months ago --- seems like that's how Hoobs just is.

**Comment by mkellsy** [comment]
Your network may have issues with .local addresses.
Try http://hoobs or http://hoobs.lan

If those act the same and since you can get to the terminal, run this.
```
ip address
```

Then try http://192.168.x.x

**Comment by txara** [comment]
Still having issues. It's specifically just the plug-in pages and related configuration, which either display the full content or doesn't display the configuration settings section (which is left blank). Given your feedback I'm still trying to see it's something about the network/router, but it's not obvious at the moment what that would be.  Sometimes the pages appears, just not right away, continues to be intermittent.

More details: I'm usually been able to navigate using http://hoobs.local', can log in, can always see the dashboard, side menu always appears. (name seems to resolve ok) -- but given the suggestion, i've also added an entry in the hosts file manually (client side) to make sure hoobs.local resolves coorectly.... When the issue happens (over the period of hours?), the plug-ins can be searched for and the names show up (but getting to the details is another matter).

Also noteable: getting the same behavior for different systems/OS/browsers/refresh/restart --all have the same issue, at the same time (when not working). 

Fortunately I'm still able to SSH login, get to config settings that way and make minor tweaks via terminal, just the web interface can be an issue.

Also note: I was getting the top and side menus, just not the plugin/configuration content. And that may also be different then a completely blank white-page (which also seems to come up, but recoverable via refresh alone)

**Comment by mkellsy** [comment]
Can you post your logs. There might be something in there.

**Comment by txara** [comment]
there's not much in the logs and the system is working (generally, when it does, it's great) -- also, after a reboot or reset, while the config pages are blank (top and size menu content only) by just leaving the page open and waiting, the page content (plugin details) will appear with [1] time, maybe 10-20 minutes, and [2] a refresh after waiting that period of time. At that point the content is prompt, updated and always readily present.

3/30/2021, 11:37:55 AM - HOOBS listening on port 80.
3/30/2021, 1:45:32 PM - Initializing HAP-NodeJS v0.9.3...
3/30/2021, 1:45:36 PM - Loaded plugin 'homebridge-camera-ffmpeg'
3/30/2021, 1:45:36 PM - [3/30/2021, 2:45:36 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
3/30/2021, 1:45:36 PM - Loaded plugin 'homebridge-ewelink'
3/30/2021, 1:45:36 PM - [3/30/2021, 2:45:36 PM] Registering platform 'homebridge-ewelink.eWeLink'
3/30/2021, 1:45:36 PM - Loaded plugin 'homebridge-gpio-device-petaren'
3/30/2021, 1:45:36 PM - homebridge-gpio-device API version: 2.7
3/30/2021, 1:45:36 PM - [3/30/2021, 2:45:36 PM] Registering accessory 'homebridge-gpio-device-petaren.GPIODevice'
3/30/2021, 1:45:37 PM - Loaded plugin 'homebridge-messenger'
3/30/2021, 1:45:37 PM - [3/30/2021, 2:45:37 PM] Registering accessory 'homebridge-messenger.HomebridgeMessenger'
3/30/2021, 1:45:37 PM - Loading 2 platforms...
3/30/2021, 1:45:37 PM - [eWeLink] Initializing eWeLink platform...
3/30/2021, 1:45:37 PM - [Camera FFmpeg] Initializing Camera-ffmpeg platform...
3/30/2021, 1:45:37 PM - Loading 2 accessories...
3/30/2021, 1:45:37 PM - [Doorbell] Initializing GPIODevice accessory...
3/30/2021, 1:45:37 PM - [Messenger] Initializing HomebridgeMessenger accessory...
3/30/2021, 1:45:37 PM - [Messenger] Added Main Switch : Messenger
3/30/2021, 1:45:37 PM - [Messenger] Main Switch status : true
3/30/2021, 1:45:37 PM - [Camera FFmpeg] [Cam-1] Configuring cached bridged accessory...
3/30/2021, 1:45:37 PM - [eWeLink] Plugin [v3.18.1] initialised. Syncing with eWeLink...
3/30/2021, 1:45:38 PM - Preparing Advertiser for 'HOOBS 7A9B' using bonjour-hap backend!
3/30/2021, 1:45:38 PM - Starting to advertise 'HOOBS 7A9B' using bonjour-hap backend!
3/30/2021, 1:45:38 PM - Bridge is running on port 51826.
3/30/2021, 1:45:45 PM - [eWeLink] [3] eWeLink devices loaded from the Homebridge cache.
3/30/2021, 1:45:45 PM - [eWeLink] [1] primary devices loaded from your eWeLink account.
3/30/2021, 1:45:58 PM - [eWeLink]  → [Buzzer] initialised and found locally with IP [10.10.1.102].
3/30/2021, 1:45:58 PM - [eWeLink] eWeLink sync complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!

I've never seen an error or suspect entry in the logs that might indicate why the page isn't rendering properly (completely) fully the first time. It seems like there is something on the page, that isn't getting a reply, is stuck waiting, times-out but eventually gets a socket and gets the content to display?  ~20 minutes is a long time tho.

**Comment by txara** [comment]
Note: I just noticed (few days ago) that consistent behavior, if I wait loooong enough, and then refresh, the config content does appear. Took long enough I always 'gave up' before, would come back, and later it would be 'working' again and figured the issue was resolved. only to resurface for sure, the next reset/reboot etc. More clues here?
