### ISSUE TITLE
Hoobs service (3.3.5) down after updating to latest Hue plugin

### ISSUE THREAD

**Issue by dibimuc** [hoobs-org/HOOBS#1177]
**Description**
I am running Hoobs in version 3.3.5 and updated to the latest hue plugin 0.13.4 from March 21st. The service does not start after updating Hue plugin

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
22.3.2021, 05:41:23 Initializing HAP-NodeJS v0.9.3...
22.3.2021, 05:41:25 Loaded plugin 'homebridge-dummy'
22.3.2021, 05:41:25 [3/21/2021, 10:41:25 PM] Registering accessory 'homebridge-dummy.DummySwitch'
22.3.2021, 05:41:25 Loaded plugin 'homebridge-harmony'
22.3.2021, 05:41:25 [3/21/2021, 10:41:25 PM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
22.3.2021, 05:41:25 [3/21/2021, 10:41:25 PM] The plugin "homebridge-hue" requires Node.js version of ^14.16.0 which does not satisfy the current Node.js version of v12.14.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
22.3.2021, 05:41:29 Loaded plugin 'homebridge-hue'
22.3.2021, 05:41:29 [3/21/2021, 10:41:29 PM] Registering platform 'homebridge-hue.Hue'
22.3.2021, 05:41:29 Loaded plugin 'homebridge-shelly'
22.3.2021, 05:41:30 [3/21/2021, 10:41:30 PM] Registering platform 'homebridge-shelly.Shelly'
22.3.2021, 05:41:30 Loaded plugin 'homebridge-tahoma'
22.3.2021, 05:41:30 [3/21/2021, 10:41:30 PM] Registering platform 'homebridge-tahoma.Tahoma'
22.3.2021, 05:41:31 Loaded plugin 'homebridge-weather-plus'
22.3.2021, 05:41:31 [3/21/2021, 10:41:31 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
22.3.2021, 05:41:31 Loading 5 platforms...
22.3.2021, 05:41:31 [Wohnzimmer] Initializing HarmonyHubWebSocket platform...
22.3.2021, 05:41:31 [Wohnzimmer] HarmonyPlatform Init
22.3.2021, 05:41:31 [WeatherPlus] Initializing WeatherPlus platform...
22.3.2021, 05:41:31 [WeatherPlus] Adding station with weather service Dark Sky named 'Now'
22.3.2021, 05:41:32 Initializing platform accessory 'Now'...
22.3.2021, 05:41:32 [My TaHoma Box] Initializing Tahoma platform...
22.3.2021, 05:41:32 Got SIGTERM, shutting down Bridge...
22.3.2021, 05:41:32 [Wohnzimmer] INFO - shutdown
22.3.2021, 05:41:32 [Wohnzimmer] INFO - shutdown
22.3.2021, 05:41:33 [HOOBS@Now@Now@Air Pressure] Characteristic not in required or optional characteristic section for service TemperatureSensor. Adding anyway.
```

**Additional context**

**Comment by mkellsy** [comment]
Hue requires the latest Node version 14.16.0 your Node version is 12.14.1.

Run this in the terminal to upgrade Node
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```

**Comment by dibimuc** [comment]
First of all, thanks a lot for your very quick answer. Appreciate this.
I run this command but service does not start. Die Log (see below) does not reveal a lot.

22.3.2021, 10:21:30 HOOBS listening on port 8080.
22.3.2021, 10:21:33 Initializing HAP-NodeJS v0.9.3...
22.3.2021, 10:21:35 Loaded plugin 'homebridge-dummy'
22.3.2021, 10:21:36 [3/22/2021, 3:21:35 AM] Registering accessory 'homebridge-dummy.DummySwitch'
22.3.2021, 10:21:37 Loaded plugin 'homebridge-harmony'
22.3.2021, 10:21:37 [3/22/2021, 3:21:37 AM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
22.3.2021, 10:21:57 Loaded plugin 'homebridge-hue'
22.3.2021, 10:21:57 [3/22/2021, 3:21:57 AM] Registering platform 'homebridge-hue.Hue'
22.3.2021, 10:21:57 Loaded plugin 'homebridge-shelly'
22.3.2021, 10:21:59 [3/22/2021, 3:21:59 AM] Registering platform 'homebridge-shelly.Shelly'
22.3.2021, 10:22:00 Loaded plugin 'homebridge-tahoma'
22.3.2021, 10:22:00 [3/22/2021, 3:22:00 AM] Registering platform 'homebridge-tahoma.Tahoma'
22.3.2021, 10:22:11 Loaded plugin 'homebridge-weather-plus'
22.3.2021, 10:22:11 [3/22/2021, 3:22:11 AM] Registering platform 'homebridge-weather-plus.WeatherPlus'
22.3.2021, 10:22:11 Loading 5 platforms...
22.3.2021, 10:22:11 [Wohnzimmer] Initializing HarmonyHubWebSocket platform...
22.3.2021, 10:22:11 [Wohnzimmer] HarmonyPlatform Init
22.3.2021, 10:22:11 [WeatherPlus] Initializing WeatherPlus platform...
22.3.2021, 10:22:11 [WeatherPlus] Adding station with weather service Dark Sky named 'Now'
22.3.2021, 10:22:11 Initializing platform accessory 'Now'...
22.3.2021, 10:22:11 [My TaHoma Box] Initializing Tahoma platform...
22.3.2021, 10:22:11 Got SIGTERM, shutting down Bridge...
22.3.2021, 10:22:11 [Wohnzimmer] INFO - shutdown
22.3.2021, 10:22:11 [Wohnzimmer] INFO - shutdown
22.3.2021, 10:22:13 [HOOBS@Now@Now@Air Pressure] Characteristic not in required or optional characteristic section for service TemperatureSensor. Adding anyway.

**Comment by mkellsy** [comment]
It's hard to tell what's happening from your logs.

Run node -v does it say v14.16.0?
Remember to back everything up.

Since the plugin isn't producing an error message, try removing plugins one by one to identify the culprit.

**Comment by dibimuc** [comment]
Yes, it‘s version 14.16.0
When I remove plug-ins (especially hue) that hurts since I have plenty of devices (and therefore rules in Home app). Is there a chance to prevent that all devices in the Home app are lost after removing and re-installing a plug-in in Hoobs?

**Comment by mkellsy** [comment]
Create a backup and save your config.
You can restore.

**Comment by dibimuc** [comment]
Okay, thanks for that. The latest Tahoma plug-in was the error. I‘ll wait for an update of that.
Thanks and this ticket can be closed then. Appreciate your help man!

**Comment by dibimuc** [comment]
One last question regarding this issue. I de-installed the Tahoma plugin successfully. But the accessories of this plugin are still shown in Hoobs and Home App. Even after rebooting of Hoobs. Does Hoobs caches this and is there a way to get rid of this accessories?

**Comment by mkellsy** [comment]
Try rebooting sounds like a stuck node process

**Comment by dibimuc** [comment]
I did several times. Even re-installing the plug-in. Rebooted Hoobs server and homebridge service. Nothing helps. Accessories are still there while plug-in has been deinstalled.

**Comment by mkellsy** [comment]
This is wired. Something has to be running.
How did you uninstall it? With a command or using the UI?

**Comment by dibimuc** [comment]
I uninstalled it with the UI

**Comment by mkellsy** [comment]
If you look at the config with this command.
```
cat ~/.hoobs/etc/config.json
```

Is the plugin listed in the "plugins": [ ...] section?

**Comment by dibimuc** [comment]
No, the plugin is not listed by looking with this command.
Restarted the server again - accessories still there. When I try to install the plug-in again, the following error occurs (attached). Don't know how to get the log-file.

[Hoobs log Tahoma install.txt](https://github.com/hoobs-org/HOOBS/files/6200390/Hoobs.log.Tahoma.install.txt)

**Comment by dubocr** [comment]
Hi Guys,

As @Ciarals84 encountered same issue with homebridge-tahoma plugin I discovered that Hoobs log are not showing some error not reported via homebridge logger.
As you can't knwo what is the error, please carefully check "service", "user" and "password" values in your homebridge-tahoma config with following info :

service | String | 'tahoma' | optional, service name ('tahoma', 'connexoon', 'connexoon_rts', 'cozytouch' or 'rexel')
-- | -- | -- | --
user | String | null | mandatory, your service account username
password | String | null | mandatory, your service account password

**Comment by dibimuc** [comment]
> Hi Guys,
> 
> As @Ciarals84 encountered same issue with homebridge-tahoma plugin I discovered that Hoobs log are not showing some error not reported via homebridge logger.
> As you can't knwo what is the error, please carefully check "service", "user" and "password" values in your homebridge-tahoma config with following info :
> 
> service	String	'tahoma'	optional, service name ('tahoma', 'connexoon', 'connexoon_rts', 'cozytouch' or 'rexel')
> user	String	null	mandatory, your service account username
> password	String	null	mandatory, your service account password

Hi, sure we did. The problem is, if you can see in my description: the plug-in has been de-installed but the accessories of this plug-in are still there and will not (cannot) be deleted.

**Comment by dubocr** [comment]
Yes but I think that if the plugin starts correctly it could clean devices. But for sure if you really want to uninstall it this "cache" issue will remain.
You could then try to remove any "homebridge-tahoma" device in the accessories/cachedAccessories file

**Comment by dibimuc** [comment]
Ok, I will try and if you like you can then close this issue. Because: if this does not work I am fine to re-setup Hoobs. What can you recommend to reset Hoobs? Can you recommend the factory reset in the GUI (help session) or do you recommend a terminal command?
