### ISSUE TITLE
Cannot access Hoobs.local after physically powering it off.

### ISSUE THREAD

**Issue by SteveAuhc16** [hoobs-org/HOOBS#1180]
Dear Hoobs Community,
  
  I have encounter the following issue 3 times and counting. And it has affected my usage of Hoobs, as Hoobs is totally unusable.

Issue:
After physically powering off Hoobs and powering it back on. Hoobs is unusable, portal is unable to load, Homekit devices stuck at “No Respond” status.  

Findings:
- I did a proper shut down by going to the portal and shutdown it, before physically powering Hoobs off.
- I tried LAN connection and Wi-fi connection, but unable to get Hoobs working.
- I have tried 2 times to replace the SD card with new ones, load in the firmware and put the new SD card back into Hoobs, and Hoobs will be back up and running. But it will be unusable again every time I physically power it off.
- I am unable to ssh into Hoobs via the following command `ssh hoobs@hoobs.local`

Kindly advise on the possible solutions.   Thank you lots!

**Comment by Niklas31** [comment]
I had the same issue

Fixed for me #996 
Basically, go to terminal on mac or windows

type:
`ssh hoobs@hoobs.local`
If asked, say `yes`
password: hoobsadmin

`sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`

Don't know what it does, but fixed for me :)

**Comment by thehotrod** [comment]
I'm having the same issue.  But this did not fix it for me.  Here is my log.  I would appreciate any help.  Please and thank you. 
<img width="860" alt="Screen Shot 2021-03-28 at 9 15 42 PM" src="https://user-images.githubusercontent.com/14954115/112779033-75c7cb00-900b-11eb-8310-47ff32e4c2e0.png">

**Comment by jcdelemos** [comment]
Same problem but is not fixed. Set up jobs but after reboot I can not access hoops.local
Installed a monitor and connected wifi
I can ping internal and external urls
Loved in to hoobs@hoobs
I see my local ip but still not able to log to the GUI from PC
I ha try multiple times with different sdcads and raspberry pi’s 4 and 3 B
New at this need help
