### ISSUE TITLE
Can't authenticate after logging in once

### ISSUE THREAD

**Issue by Kidokoro580** [hoobs-org/HOOBS#1182]
Hope you can help. I just received my HOOBS box today, set it up via ethernet connection, logged in once then clicked to update the version from 3.3.2 to 3.3.5.

I'm guessing it got stuck while trying to update the software because I let it try to update over 20 minutes.

I rebooted the device after connecting to it via ssh and get to the authentication screen, but my username and password aren't accepted. I feel I just wasted money on this device. Any ideas?

Thanks in advance!

**Comment by mkellsy** [comment]
You are going to have to SSH into the box
If you are on a mac open the terminal and run this.
```
ssh hoobs@hoobs.local
```
The password is: hoobsadmin

If on windows you will have to use Putty

Once you are SSHed into the box. Run this.
```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm
```

Then reboot. You should get the UI back.

**Comment by Kidokoro580** [comment]
Hi, I ran both and the first one was fine.
The second one gave me problems, but I guessed that the command should be:
sudo npm install -g npm --unsafe-perm

I ran that and rebooted.

now the GUI services don't seem to work but can ssh into the box. 
any further ideas? thanks!

**Comment by bwp91** [comment]
Try running this:

```
sudo npm install @hoobs/hoobs -g --unsafe-perm
```

**Comment by mkellsy** [comment]
Sorry, typo on the last command
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by Kidokoro580** [comment]
Many thanks guys. Problem solved. 
After running the last command, I went to reset the password and now I'm back in service.
I love this community!
