### ISSUE TITLE
Hoobs issues

### ISSUE THREAD

**Issue by damonII** [hoobs-org/HOOBS#1185]
After I did the update on the new hoobs I just got it’s no longer working. It won’t connect to the internet nor can I log into the hoobs.local. Need help please

**Comment by mkellsy** [comment]
First check if http://hoobs works.

Then see if you can SSH into the device.
If you are on Mac, open the terminal and type this.
```
ssh hoobs@hoobs.local
```
The password is: hoobsadmin
```

If on Windows you need to use Putty

Once you are SSH'ed in, type these commands.
```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

Then reboot the device
```
sudo shutdown -r now
```

**Comment by damonII** [comment]
Its not working for me

**Comment by damonII** [comment]
http://hoobs doesn’t work and when I try to ssh into the device this is
what I get (check the attachment) I don’t know what to do.

**Comment by damonII** [comment]
It should have showed up as a picture of the terminal on my computer, I
guess I showed up like that instead of an attachment. Did you see it and
what I’m talking about?

**Comment by mkellsy** [comment]
If you are attaching an image via email, it won't work.
You can post to this issue via GitHub and below this text field there is a message about attaching files.
If not email me the attachment mkellsy@hoobs.org

**Comment by damonII** [comment]
Is it possible to get a replacement because this one don’t work hasn’t
worked since the day I got it.

**Comment by mkellsy** [comment]
Send an email to info@hoobs.org with your order number describe what's happening.

Transactions like this can't be done via GitHub.

**Comment by damonII** [comment]
Thank you, I will do that.
