### ISSUE TITLE
Apple Home loses Hoobs

### ISSUE THREAD

**Issue by wills721** [hoobs-org/HOOBS#1188]
**Description**
[Every time I add/remove a Hoobs plug-in Hoobs UX the Apple Home App loses connectivity to the entire bridge.  The only way to restore Hoobs is to remove the bridge from Apple Home and re-add the Hoobs bridge and then all devices into rooms.  A serious pain -- I have over 50 devices coming over from Hoobs.  ]

**Version**
[3.3.5]

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [Yes ] Yes
- [ ] No

**Pervious version**
3.3.2
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
 No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ Raspberry Pi4] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by wills721** [comment]
Question:  Is it possible Apple Home would lose sight of Hoobs if one were to delete /home/hoobs/.hoobs/etc/persist/* ?

**Comment by mkellsy** [comment]
Yes if you delete persist the connection to HomeKit will be lost. If persist is deleted, you will have to generate a new username and the re-pair.

It's hard to tell what's happening, I don't know all the plugins you are running. It may take some time for HomeKit to catch up when you restart after installing a plugin.
