### ISSUE TITLE
hoobs.local 

### ISSUE THREAD

**Issue by treforparr** [hoobs-org/HOOBS#1192]
**Description**

Keep losing hoobs.local  Constant configuration problems since the latest upgrade Random shutdowns   other bug  
**Version**
Please include the version of HOOBS you are using.
3.3.5.
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.
27/03/2021, 13:33:36 HOOBS listening on port 80.
27/03/2021, 13:33:38 Initializing HAP-NodeJS v0.9.3...
27/03/2021, 13:33:40 Loaded plugin '@joshepw/homebridge-lgwebos-tv'
27/03/2021, 13:33:40 [3/27/2021, 7:33:40 AM] Registering platform 'joshepw/homebridge-lgwebos-tv.LgWebOsTv'
27/03/2021, 13:33:44 Loaded plugin 'homebridge-alexa'
27/03/2021, 13:33:44 [3/27/2021, 7:33:44 AM] Registering platform 'homebridge-alexa.Alexa'
27/03/2021, 13:33:44 Loaded plugin 'homebridge-gsh'
27/03/2021, 13:33:44 [3/27/2021, 7:33:44 AM] Registering platform 'homebridge-gsh.google-smarthome'
27/03/2021, 13:33:46 Loaded plugin 'homebridge-ring'
27/03/2021, 13:33:46 [3/27/2021, 7:33:46 AM] Registering platform 'homebridge-ring.Ring'
27/03/2021, 13:33:47 Loaded plugin 'homebridge-smartthings'
27/03/2021, 13:33:47 [3/27/2021, 7:33:47 AM] Registering platform 'homebridge-smartthings.SmartThings-v2'
27/03/2021, 13:33:47 Loading 5 platforms...
27/03/2021, 13:33:47 [SmartThings-v2] Initializing SmartThings-v2 platform...
27/03/2021, 13:33:48 INFO: Homebridge Version: 2.7
27/03/2021, 13:33:48 INFO: SmartThings-v2 Plugin Version: 2.3.8
27/03/2021, 13:33:48 INFO: Checking Package Version for Updates...
27/03/2021, 13:33:48 [Ring] Initializing Ring platform...
27/03/2021, 13:33:48 [google-smarthome] Initializing google-smarthome platform...
27/03/2021, 13:33:48 [Alexa] Initializing Alexa platform...
27/03/2021, 13:33:48 [Alexa] homebridge-alexa v0.5.34, node v14.16.0, homebridge v1.3.3
27/03/2021, 13:33:48 Initializing platform accessory 'Alexa'...
27/03/2021, 13:33:48 [LgWebOsTv] Initializing LgWebOsTv platform...
27/03/2021, 13:33:49 [dining room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:33:49 [dining room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:33:49 [living room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:33:49 [living room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:33:49 [Ring] Configuring cached accessory 4e29c4e1-3b19-4490-80b4-a5086afb49b1 Front Door
27/03/2021, 13:33:49 [Ring] Configuring cached accessory 4983bc71-8f16-4991-b91d-56781b3320de Back Door
27/03/2021, 13:33:49 [Ring] Configuring cached accessory feebe7a7-fa74-47a6-a2b0-9c445550de7b Kitchen
27/03/2021, 13:33:49 [Ring] Configuring cached accessory db68701f-1111-4ea4-99f7-1a3d042aaebe Living room
27/03/2021, 13:33:49 [Ring] Configuring cached accessory 7000accc-eef2-47ec-a9bc-446e3e14cfb6 Dining room
27/03/2021, 13:33:49 [Ring] Configuring cached accessory d3793402-3cf6-4de7-b157-bb1a9bdd6893 Newton-Le-Willows Mode
27/03/2021, 13:33:49 INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
27/03/2021, 13:33:49 GOOD: Refreshing All Device Data | Source: (First Launch)
27/03/2021, 13:33:49 [LgWebOsTv] Device: 192.168.0.2 LG TV, get current Power state successfull, state: OFF
27/03/2021, 13:33:49 A platform configured a external accessory under the plugin name 'homebridge-lgwebos-tv'. However no loaded plugin could be found for the name!
27/03/2021, 13:33:49 Preparing Advertiser for 'LG TV 47AA' using bonjour-hap backend!
27/03/2021, 13:33:49 Preparing Advertiser for 'HOOBS D1AE' using bonjour-hap backend!
27/03/2021, 13:33:49 Starting to advertise 'LG TV 47AA' using bonjour-hap backend!
27/03/2021, 13:33:49 LG TV 47AA is running on port 43283.
27/03/2021, 13:33:49 Please add [LG TV 47AA] manually in Home app. Setup Code: 031-45-154
27/03/2021, 13:33:49 Starting to advertise 'HOOBS D1AE' using bonjour-hap backend!
27/03/2021, 13:33:49 Bridge is running on port 51826.
27/03/2021, 13:33:50 [LgWebOsTv] Device: 192.168.0.2 LG TV, state: Online.
27/03/2021, 13:33:50 [LgWebOsTv] -------- LG TV --------
27/03/2021, 13:33:50 [LgWebOsTv] Manufacturer: LG Electronics
27/03/2021, 13:33:50 [LgWebOsTv] Model: Model Name
27/03/2021, 13:33:50 [LgWebOsTv] System: System
27/03/2021, 13:33:50 [LgWebOsTv] Serialnr: Serial Number
27/03/2021, 13:33:50 [LgWebOsTv] Firmware: Firmware Revision
27/03/2021, 13:33:50 [LgWebOsTv] ----------------------------------
27/03/2021, 13:33:50 [LgWebOsTv] Device: 192.168.0.2 LG TV, get current Power state successfull, state: OFF
27/03/2021, 13:33:50 [LG TV 47AA@LG TV@Active Identifier] characteristic value expected valid finite number and received "undefined" (undefined)
27/03/2021, 13:33:51 [HOOBS D1AE@dining room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:33:51 [HOOBS D1AE@living room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:33:51 NOTICE: Temperature Unit is Now: (F)
27/03/2021, 13:33:51 NOTICE: Updating Global Values | HubIP: 192.168.0.30 | UseLocal: false
27/03/2021, 13:33:51 WARN: Devices to Remove: (0) []
27/03/2021, 13:33:51 INFO: Devices to Update: (14)
27/03/2021, 13:33:51 GOOD: Devices to Create: (0) []
27/03/2021, 13:33:51 [HOOBS D1AE@dining room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:33:51 [HOOBS D1AE@living room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:33:51 ALERT: Total Initialization Time: (2 seconds)
27/03/2021, 13:33:51 NOTICE: Unknown Capabilities: ["Tone","Signal Strength","Occupancy Sensor","Holdable Button","Three Axis"]
27/03/2021, 13:33:51 INFO: SmartThings DeviceCache Size: (14)
27/03/2021, 13:33:51 INFO: WebServer Initiated...
27/03/2021, 13:33:51 INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
27/03/2021, 13:33:51 INFO: Direct Connect Active | Listening at 192.168.0.28:8000
27/03/2021, 13:33:52 INFO: SmartThings-v2 Hub Communication Established
27/03/2021, 13:33:53 INFO: INFO: Your plugin version is up-to-date
27/03/2021, 13:33:53 NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.8
27/03/2021, 13:33:53 [LgWebOsTv] Device: 192.168.0.2 LG TV, get current Power state successfull, state: OFF
27/03/2021, 13:33:54 [LG TV 47AA@LG TV@Active Identifier] characteristic value expected valid finite number and received "undefined" (undefined)
27/03/2021, 13:33:55 [Ring] Found the following locations:
27/03/2021, 13:33:55 [Ring]   locationId: 11495610-ba8f-4a58-b400-38a8330cce3e - Newton-Le-Willows
27/03/2021, 13:33:55 [Ring] Configuring 5 cameras and 6 devices for location "Newton-Le-Willows" - locationId: 11495610-ba8f-4a58-b400-38a8330cce3e
27/03/2021, 13:33:57 [HOOBS D1AE@dining room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:33:57 [HOOBS D1AE@living room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:34:08 [Ring] Dining room Detected Motion. Loading snapshot before sending event to HomeKit
27/03/2021, 13:34:09 [HOOBS D1AE@dining room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:34:09 [HOOBS D1AE@living room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:34:09 [LgWebOsTv] Device: 192.168.0.2 LG TV, get current Power state successfull, state: OFF
27/03/2021, 13:34:09 [LG TV 47AA@LG TV@Active Identifier] characteristic value expected valid finite number and received "undefined" (undefined)
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name diskwasher
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name diskwasher
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name fridge door
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name fridge door
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name Back Door
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name Back Door
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name Dining room
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name Front Door
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name Front Door
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name Kitchen
27/03/2021, 13:34:20 [Alexa] WARNING: Duplicate device name Living room
27/03/2021, 13:34:20 [Alexa] alexaDiscovery - returned 31 devices
27/03/2021, 13:34:25 INFO: [Device Event]: (diskwasher) [TEMPERATURE] is 68.6
27/03/2021, 13:34:46 [LgWebOsTv] Device: 192.168.0.2 LG TV, get current Power state successfull, state: OFF
27/03/2021, 13:34:46 [LG TV 47AA@LG TV@Active Identifier] characteristic value expected valid finite number and received "undefined" (undefined)
27/03/2021, 13:35:46 [LgWebOsTv] Device: 192.168.0.2 LG TV, get current Power state successfull, state: OFF
27/03/2021, 13:35:46 [LG TV 47AA@LG TV@Active Identifier] characteristic value expected valid finite number and received "undefined" (undefined)
27/03/2021, 13:36:06 [LgWebOsTv] Device: 192.168.0.2 LG TV, get current Power state successfull, state: OFF
27/03/2021, 13:36:06 [LG TV 47AA@LG TV@Active Identifier] characteristic value expected valid finite number and received "undefined" (undefined)
27/03/2021, 13:36:06 [HOOBS D1AE@dining room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:36:06 [HOOBS D1AE@living room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:36:46 [LgWebOsTv] Device: 192.168.0.2 LG TV, get current Power state successfull, state: OFF
27/03/2021, 13:36:46 [LG TV 47AA@LG TV@Active Identifier] characteristic value expected valid finite number and received "undefined" (undefined)
27/03/2021, 13:36:52 [HOOBS D1AE@dining room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:36:52 [HOOBS D1AE@living room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:37:27 [HOOBS D1AE@dining room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:37:27 [HOOBS D1AE@living room LED@@Hue] characteristic was supplied illegal value: number 0 exceeded minimum of 1
27/03/2021, 13:37:27 INFO: [Device Event]: (fridge door) [TEMPERATURE] is 43.2
27/03/2021, 13:37:46 [LgWebOsTv] Device: 192.168.0.2 LG TV, get current Power state successfull, state: OFF
27/03/2021, 13:37:46 [LG TV 47AA@LG TV@Active Identifier] characteristic value expected valid finite number and received "undefined" (undefined)
```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
If hoobs.local isn't working try
http://hoobs

**Comment by treforparr** [comment]
It does when I reboot it, it's been happening every morning since the latest update

**Comment by mkellsy** [comment]
The last update just upgraded Homebridge to 1.3.3.
I am wondering if one of your plugins is causing the bridge  to stop.
Check to see if all your plugins are updated.
