### ISSUE TITLE
hoobs service not running

### ISSUE THREAD

**Issue by svobod3** [hoobs-org/HOOBS#1195]
**Description**
Perhaps it is more feature request than bug, but - sometimes HomeKit says that it can not connect to hoobs accessory. Reason for this is that boobs service is not running. And 2 have 2 questions here:
- is it possible to find out the reason?
- is it possible to set it somewhere (or to use some script) that will periodically check service status and if it is stopped, it will automatically start it again?

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
tuya web
harmony
roomba2

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
You can see the historical log with this command.
```
sudo journalctl -o cat -n 500 -f -u hoobs.service
```

Change -n 500 to a larger number to see more messages.

From other reports, I think it might be the Harmony plugin that is crashing the bridge. Look for a socket hangup I'm the log.

**Comment by svobod3** [comment]
Ok, thanks.
When the servise stops again, I will check the logs.

**Comment by svobod3** [comment]
So hoobs service was stopped again, here are the logs:

Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Got SIGTERM, shutting down Bridge...
[Harmony Hub] INFO - shutdown
[Harmony Hub] INFO - shutdown

**Comment by svobod3** [comment]
Is it possible to say which plugin causes stopping of hoobs service?

**Comment by mkellsy** [comment]
It's hard from the logs to tell. Trial and error is really the only way.
1. Remove one plugin at a time.
2. If it still fails, add the plugin back before removing the next plugin.

Do this until the crash stops. Then you know which plugin it is.
