### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#12]
![dash1](https://user-images.githubusercontent.com/50763727/62468079-72782f80-b795-11e9-986f-e930739dca6b.png)

Changeable Background
Transparent Boxes 60% Oppacity
Locale edit by ZIP and Country, Sunrise Sunset, Wheaterforecast 1h/4h/8h/12h/24h
Favorite accessories, select from available accessories, reorder able
Status Name Switch (iPhone I/O Style) Status Green/Orange/Red | Online/Restrating/Offline
Support Box ......
About Box.....
Technical Contact Box ....... (If someone use this professional)
we can expand this more and more

**Comment by mkellsy** [comment]
Done in 3.0.0-alpha.17
