### ISSUE TITLE
changed config-port / no login possible (Beta)

### ISSUE THREAD

**Issue by IT-Lueg** [hoobs-org/HOOBS#120]
![Bildschirmfoto 2019-09-01 um 15 50 36](https://user-images.githubusercontent.com/4661044/64077376-5900cf80-ccd0-11e9-9472-f9e74bffa1c6.png)

I changed the config-port in the Config.json to "8090".
Now if I go to <raspi-ip>:8090 I cannot login.

**Comment by mkellsy** [comment]
Can you post the config.
~/.hoobs/etc/config.json

**Comment by IT-Lueg** [comment]
![Bildschirmfoto 2019-09-01 um 21 08 23](https://user-images.githubusercontent.com/4661044/64081098-a98e2200-ccfc-11e9-9a9e-c5bc9d5fa0a8.png)

**Comment by mkellsy** [comment]
You need to all occurrences of
http://hoobs.local/api -> http://192.168.1.13:51827 (2 places)
and
http://hoobs.local -> http://192.168.1.13:51828 (1 place)

**Comment by TransRapid** [comment]
Stuck on this as well, ports are setup right, cleared all settings and did a clean install. Nothing ever loads to create a username.

**Comment by mkellsy** [comment]
http://hoobs.local/api -> http://192.168.1.13:51827
needs top be
http://hoobs.local/api -> http://192.168.1.13:51827**/api**
