### ISSUE TITLE
JSON size limit? Crash and config wipe after reaching 1020 lines.

### ISSUE THREAD

**Issue by iznaf** [hoobs-org/HOOBS#1201]
Is there a limitation of json file size? 
I have a valid and working json config file, 1020 lines total, 128kb (many hex codes), and when i try to add another definition - no matter in which plugin, ffmpeg for example, and push "Save Changes", the HOOBS interface crashes. After the page is reloaded, json file is shrinking to about 20 lines, all definitions are wiped. I tried it few times, added valid data (jsonlint-validated), few different plugins, same result - crash and wipe.
No useful log can be accessed due to the system crash. The config can be restored after reboot.
Version 3.3.5, RPi 4, HOOBS SD

**Comment by iznaf** [comment]
So... same result both using HOOBS UI and editing using terminal 
ssh hoobs@192.168.68.141
cd ~/.hoobs/etc
ls
nano config-1617128612146.json

can't get over 1020 lines

**Comment by mkellsy** [comment]
There is no limitation on file size. If nano is not saving, check to see if there is space for it.
```
df -h
```
This shows the free space on the drives.
