### ISSUE TITLE
Tried to install Eufy Security Plugin and I’m not having access to Hoobs anymore.

### ISSUE THREAD

**Issue by charliezinno** [hoobs-org/HOOBS#1202]
**Description**
Tried to install the Eufy Security plugin from "hoobs.local", the installer never finished and now I’m not being able to access Hoobs anymore.

**Expected behavior**
See the Doorbell in HomeKit.

**Plugin name**
Eufy Security

**Please report the issue to the plugin developer**
https://github.com/birkir/homebridge-plugin-eufy-security#readme

**Version**
3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYKI2C",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94025"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "36:75:4A:85:A0:84"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-simplisafe3",
        "homebridge-tplink-smarthome"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "plugin_map": {
                "plugin_name": "homebridge-simplisafe3"
            },
            "name": "Alarm",
            "cameras": false,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "auth": {
                "username": "zinnoromano@gmail.com",
                "password": ""
            }
        },
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            },
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ]
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Can you post your logs. Could be a number of things.
