### ISSUE TITLE
Service not working after Upgrading to HOOBS 3.3.5  

### ISSUE THREAD

**Issue by CaldenMig21** [hoobs-org/HOOBS#1205]
Hoobs stoped working showing the following error in the log initiallizing the Broadlink Plugging.
I started to look in the hoobs platform finding out there is a new Hoobs Core Version (3.3.5). I was running 3.3.2.
I initiated the upgrade and everything stoped working. I can not even open the terminal o look at a new log anymore.

How can I reset and restablisk the Hoobs service?
Thanks...
[logs (7).txt](https://github.com/hoobs-org/HOOBS/files/6255023/logs.7.txt)

3/4/2021 0:53:04 - HOOBS listening on port 80.
3/4/2021 0:53:09 - Loaded plugin '@milo526/homebridge-tuya-web'
3/4/2021 0:53:09 - [4/2/2021, 11:53:09 PM] Registering platform 'milo526/homebridge-tuya-web.TuyaWebPlatform'
3/4/2021 0:53:10 - Loaded plugin 'homebridge-arlo'
3/4/2021 0:53:10 - [4/2/2021, 11:53:10 PM] Registering platform 'homebridge-arlo.Arlo'
3/4/2021 0:53:11 - Loaded plugin 'homebridge-broadlink-rm-pro'
3/4/2021 0:53:11 - [4/2/2021, 11:53:11 PM] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
3/4/2021 0:53:11 - Loaded plugin 'homebridge-delay-switch'
3/4/2021 0:53:11 - [4/2/2021, 11:53:11 PM] Registering accessory 'homebridge-delay-switch.DelaySwitch'
3/4/2021 0:53:11 - Loaded plugin 'homebridge-dummy'
3/4/2021 0:53:11 - [4/2/2021, 11:53:11 PM] Registering accessory 'homebridge-dummy.DummySwitch'
3/4/2021 0:53:12 - Loaded plugin 'homebridge-sensibo-ac'
3/4/2021 0:53:12 - [4/2/2021, 11:53:12 PM] Registering platform 'homebridge-sensibo-ac.SensiboAC'
3/4/2021 0:53:12 - Loading 4 platforms...
3/4/2021 0:53:12 - [SensiboAC] Initializing SensiboAC platform...
3/4/2021 0:53:12 - [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
3/4/2021 0:53:12 - [Arlo] Initializing Arlo platform...
3/4/2021 0:53:12 - [Broadlink RM] Initializing BroadlinkRM platform...
3/4/2021 0:53:12 - Error: [PARSE-ERROR] /home/hoobs/.hoobs/etc/plugin-persist/homebridge-broadlink-rm/ae7bf0ba9a925c33560943edc232942c does not look like a valid storage file!
    at LocalStorage.parseFileSync (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:666:19)
    at LocalStorage.parseStorageDirSync (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:615:26)
    at LocalStorage.initSync (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:142:14)
    at Object.nodePersist.initSync (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/node-persist.js:37:32)
    at Object.init (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/base/helpers/persistentState.js:9:15)
    at new HomebridgePlatform (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/base/platform.js:15:21)
    at new BroadlinkRMPlatform (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/platform.js:40:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:346:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by CaldenMig21** [comment]
The log that I sent in the previous message is the one before running the upgrade. 
Now the upgrade process seem to be in a loop, and the log is only showing the following:

4/4/2021 11:44:04 HOOBS listening on port 80.
4/4/2021 11:44:06 Initializing HAP-NodeJS v0.9.3...
4/4/2021 11:44:07 Loaded plugin '@milo526/homebridge-tuya-web'
4/4/2021 11:44:08 [4/4/2021, 10:44:07 AM] Registering platform 'milo526/homebridge-tuya-web.TuyaWebPlatform'
4/4/2021 11:44:09 Loaded plugin 'homebridge-arlo'
4/4/2021 11:44:09 [4/4/2021, 10:44:09 AM] Registering platform 'homebridge-arlo.Arlo'
4/4/2021 11:44:10 Loaded plugin 'homebridge-broadlink-rm-pro'
4/4/2021 11:44:10 [4/4/2021, 10:44:10 AM] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
4/4/2021 11:44:10 Loaded plugin 'homebridge-delay-switch'
4/4/2021 11:44:10 [4/4/2021, 10:44:10 AM] Registering accessory 'homebridge-delay-switch.DelaySwitch'
4/4/2021 11:44:10 Loaded plugin 'homebridge-dummy'
4/4/2021 11:44:10 [4/4/2021, 10:44:10 AM] Registering accessory 'homebridge-dummy.DummySwitch'
4/4/2021 11:44:10 Loaded plugin 'homebridge-sensibo-ac'
4/4/2021 11:44:10 [4/4/2021, 10:44:10 AM] Registering platform 'homebridge-sensibo-ac.SensiboAC'
4/4/2021 11:44:10 Loading 4 platforms...
4/4/2021 11:44:10 [SensiboAC] Initializing SensiboAC platform...
4/4/2021 11:44:10 [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
4/4/2021 11:44:10 [Arlo] Initializing Arlo platform...
4/4/2021 11:44:10 [Broadlink RM] Initializing BroadlinkRM platform...

It seem that the Brosdlink plugging is not initializing. The upgrades seems to keep working (for more than 1 hour) and I am not able to open the terminal, or restore a previous backup, because all those options are hidden in the Hoobs UI.

**Comment by CaldenMig21** [comment]
I logged out. And now I am not even able to log back in, in the UI.

**Comment by CaldenMig21** [comment]
For some reasoon the UI stoped working on the chrome environment. I was able to open the UI from an Ipad and restore a previous backup. Now everything it is working fine and it sais I am in Hoobs 3.3.5.
The only issue is that I can not use chrome to open the UI. I am using Edge from my Windows PC.

**Comment by askovi** [comment]
Try deleting your browser cache in chrome.
