### ISSUE TITLE
re can't update the ring Oliver 

### ISSUE THREAD

**Issue by oliverchapple** [hoobs-org/HOOBS#1207]
hi 

I can't update the ring plugin    if I chick update .

update just says there  and does not update the ring plug in.

is there a  command to update the plugin 

thanks Oliver

**Comment by mkellsy** [comment]
Can you post your logs. Could be a number of things

**Comment by oliverchapple** [comment]
I fixed it with npm install -g npm  I found with ring  on the end of it
