### ISSUE TITLE
No certified plugins show

### ISSUE THREAD

**Issue by maajaber** [hoobs-org/HOOBS#1209]
**Description**
Just received my HOOBS Box. Did the sign in and update to 3.3.5 but no certified plugins appear in the plugins window. Not sure if I'm doing something wrong but I did follow all step by step instructions.

**Version**
Please include the version of HOOBS you are using.
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.x.x can't really remember anything beside it being version 3.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```
4/5/2021, 4:54:25 PM HOOBS listening on port 80.
4/5/2021, 4:54:27 PM Initializing HAP-NodeJS v0.9.3...
4/5/2021, 4:54:28 PM No plugins installed.
4/5/2021, 4:54:28 PM Preparing Advertiser for 'HOOBS 9046' using bonjour-hap backend!
4/5/2021, 4:54:28 PM Starting to advertise 'HOOBS 9046' using bonjour-hap backend!
4/5/2021, 4:54:28 PM Bridge is running on port 51826.
4/5/2021, 5:04:23 PM Got SIGINT, shutting down Bridge...
4/5/2021, 5:04:30 PM Initializing HAP-NodeJS v0.9.3...
4/5/2021, 5:04:31 PM No plugins installed.
4/5/2021, 5:04:31 PM Preparing Advertiser for 'HOOBS 9046' using bonjour-hap backend!
4/5/2021, 5:04:31 PM Starting to advertise 'HOOBS 9046' using bonjour-hap backend!
4/5/2021, 5:04:31 PM Bridge is running on port 51826.
4/5/2021, 5:09:29 PM npm
4/5/2021, 5:09:29 PM  notice created a lockfile as package-lock.json. You should commit this file.
4/5/2021, 5:09:29 PM + homebridge-myhome-own@0.2.0
added 52 packages from 49 contributors in 37.339s
4/5/2021, 5:09:29 PM 
8 packages are looking for funding
  run `npm fund` for details
4/5/2021, 5:09:33 PM Plugin "homebridge-myhome-own" installed.
4/5/2021, 5:09:35 PM Got SIGINT, shutting down Bridge...
4/5/2021, 5:09:41 PM Initializing HAP-NodeJS v0.9.3...
4/5/2021, 5:09:42 PM Initializing HAP-NodeJS v0.9.3...
4/5/2021, 5:09:43 PM Loaded plugin 'homebridge-myhome-own'
4/5/2021, 5:09:43 PM Loaded plugin 'homebridge-myhome-own'
4/5/2021, 5:09:47 PM [4/5/2021, 7:09:46 AM] Registering platform 'homebridge-myhome-own.LegrandMyHome'
4/5/2021, 5:09:47 PM [4/5/2021, 7:09:46 AM] Registering platform 'homebridge-myhome-own.LegrandMyHome'
4/5/2021, 5:09:47 PM Loading 1 platforms...
4/5/2021, 5:09:47 PM Loading 1 platforms...
4/5/2021, 5:09:47 PM [LegrandMyHome] Initializing LegrandMyHome platform...
4/5/2021, 5:09:47 PM [LegrandMyHome] Initializing LegrandMyHome platform...
4/5/2021, 5:25:28 PM Initializing HAP-NodeJS v0.9.3...
4/5/2021, 5:25:29 PM Loaded plugin 'homebridge-myhome-own'
4/5/2021, 5:25:33 PM [4/5/2021, 7:25:32 AM] Registering platform 'homebridge-myhome-own.LegrandMyHome'
4/5/2021, 5:25:33 PM Loading 1 platforms...
4/5/2021, 5:25:33 PM [LegrandMyHome] Initializing LegrandMyHome platform...
4/5/2021, 5:35:26 PM 
> bufferutil@4.0.3 install /home/hoobs/.hoobs/node_modules/bufferutil
> node-gyp-build
4/5/2021, 5:35:26 PM 
> utf-8-validate@5.0.4 install /home/hoobs/.hoobs/node_modules/utf-8-validate
> node-gyp-build
4/5/2021, 5:35:27 PM added 3 packages from 2 contributors, removed 52 packages and audited 3 packages in 7.587s
4/5/2021, 5:35:27 PM found 0 vulnerabilities
4/5/2021, 5:35:27 PM Plugin "homebridge-myhome-own" removed.
4/5/2021, 5:35:29 PM Initializing HAP-NodeJS v0.9.3...
4/5/2021, 5:35:30 PM No plugins installed.
4/5/2021, 5:35:30 PM Preparing Advertiser for 'HOOBS 9046' using bonjour-hap backend!
4/5/2021, 5:35:30 PM Starting to advertise 'HOOBS 9046' using bonjour-hap backend!
4/5/2021, 5:35:30 PM Bridge is running on port 51826.
4/6/2021, 12:39:11 AM 
> sleep@3.0.1 install /home/hoobs/.hoobs/node_modules/sleep
> node-gyp rebuild
4/6/2021, 12:39:17 AM make: Entering directory '/home/hoobs/.hoobs/node_modules/sleep/build'
4/6/2021, 12:39:17 AM   CXX(target) Release/obj.target/node_sleep/sleep.o
4/6/2021, 12:39:22 AM ../sleep.cc:6:11: error: ‘v8::Handle’ has not been declared
 using v8::Handle;
           ^~~~~~
4/6/2021, 12:39:22 AM ../sleep.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Sleep(Nan::NAN_METHOD_ARGS_TYPE)’:
../sleep.cc:42:30: error: no matching function for call to ‘v8::Value::Uint32Value()’
   sleep(info[0]->Uint32Value());
                              ^
4/6/2021, 12:39:22 AM In file included from /home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:2866:41: note: candidate: ‘v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:2866:41: note:   candidate expects 1 argument, 0 provided
4/6/2021, 12:39:22 AM ../sleep.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE USleep(Nan::NAN_METHOD_ARGS_TYPE)’:
../sleep.cc:54:31: error: no matching function for call to ‘v8::Value::Uint32Value()’
   usleep(info[0]->Uint32Value());
                               ^
In file included from /home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:2866:41: note: candidate: ‘v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:2866:41: note:   candidate expects 1 argument, 0 provided
../sleep.cc: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../sleep.cc:62:52: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
     Nan::New<FunctionTemplate>(Sleep)->GetFunction());
                                                    ^
In file included from /home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:6482:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:6482:46: note:   candidate expects 1 argument, 0 provided
4/6/2021, 12:39:22 AM ../sleep.cc:64:53: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
     Nan::New<FunctionTemplate>(USleep)->GetFunction());
                                                     ^
In file included from /home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:6482:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:6482:46: note:   candidate expects 1 argument, 0 provided
In file included from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
../sleep.cc: At global scope:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../sleep.cc:68:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(node_sleep, init)
 ^~~~~~~~~~~
4/6/2021, 12:39:23 AM make: *** [node_sleep.target.mk:109: Release/obj.target/node_sleep/sleep.o] Error 1
4/6/2021, 12:39:23 AM make: Leaving directory '/home/hoobs/.hoobs/node_modules/sleep/build'
4/6/2021, 12:39:23 AM gyp ERR! build error
4/6/2021, 12:39:23 AM gyp
4/6/2021, 12:39:23 AM  ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
4/6/2021, 12:39:23 AM gyp ERR! System Linux 5.10.11-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hoobs/.hoobs/node_modules/sleep
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
4/6/2021, 12:39:23 AM npm
4/6/2021, 12:39:23 AM 
4/6/2021, 12:39:23 AM ERR!
4/6/2021, 12:39:23 AM code ELIFECYCLE
4/6/2021, 12:39:23 AM npm
4/6/2021, 12:39:23 AM  ERR! errno 1
4/6/2021, 12:39:23 AM npm
4/6/2021, 12:39:23 AM ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm
4/6/2021, 12:39:23 AM ERR! Failed at the sleep@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
4/6/2021, 12:39:23 AM 
4/6/2021, 12:39:23 AM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-04-05T20_39_23_406Z-debug.log
4/6/2021, 12:40:03 AM 
> sleep@3.0.1 install /home/hoobs/.hoobs/node_modules/sleep
> node-gyp rebuild
4/6/2021, 12:40:06 AM make: Entering directory '/home/hoobs/.hoobs/node_modules/sleep/build'
4/6/2021, 12:40:06 AM   CXX(target) Release/obj.target/node_sleep/sleep.o
4/6/2021, 12:40:09 AM ../sleep.cc:6:11: error: ‘v8::Handle’ has not been declared
 using v8::Handle;
           ^~~~~~
4/6/2021, 12:40:09 AM ../sleep.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Sleep(Nan::NAN_METHOD_ARGS_TYPE)’:
../sleep.cc:42:30: error: no matching function for call to ‘v8::Value::Uint32Value()’
   sleep(info[0]->Uint32Value());
                              ^
4/6/2021, 12:40:09 AM In file included from /home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:2866:41: note: candidate: ‘v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:2866:41: note:   candidate expects 1 argument, 0 provided
4/6/2021, 12:40:09 AM ../sleep.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE USleep(Nan::NAN_METHOD_ARGS_TYPE)’:
../sleep.cc:54:31: error: no matching function for call to ‘v8::Value::Uint32Value()’
   usleep(info[0]->Uint32Value());
                               ^
4/6/2021, 12:40:09 AM In file included from /home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:2866:41: note: candidate: ‘v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:2866:41: note:   candidate expects 1 argument, 0 provided
4/6/2021, 12:40:09 AM ../sleep.cc: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../sleep.cc:62:52: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
     Nan::New<FunctionTemplate>(Sleep)->GetFunction());
                                                    ^
4/6/2021, 12:40:09 AM In file included from /home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:6482:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:6482:46: note:   candidate expects 1 argument, 0 provided
4/6/2021, 12:40:09 AM ../sleep.cc:64:53: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
     Nan::New<FunctionTemplate>(USleep)->GetFunction());
                                                     ^
In file included from /home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:6482:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/hoobs/.cache/node-gyp/14.16.0/include/node/v8.h:6482:46: note:   candidate expects 1 argument, 0 provided
4/6/2021, 12:40:09 AM In file included from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
../sleep.cc: At global scope:
/home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/hoobs/.cache/node-gyp/14.16.0/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../sleep.cc:68:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(node_sleep, init)
 ^~~~~~~~~~~
4/6/2021, 12:40:09 AM make: *** [node_sleep.target.mk:109: Release/obj.target/node_sleep/sleep.o] Error 1
4/6/2021, 12:40:09 AM make: Leaving directory '/home/hoobs/.hoobs/node_modules/sleep/build'
4/6/2021, 12:40:09 AM gyp
4/6/2021, 12:40:09 AM  ERR! build error
4/6/2021, 12:40:09 AM gyp
4/6/2021, 12:40:09 AM ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
4/6/2021, 12:40:09 AM gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
4/6/2021, 12:40:09 AM gyp ERR! System Linux 5.10.11-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
4/6/2021, 12:40:09 AM gyp ERR! cwd /home/hoobs/.hoobs/node_modules/sleep
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v
4/6/2021, 12:40:09 AM  v5.1.0
gyp ERR! not ok
4/6/2021, 12:40:09 AM npm
4/6/2021, 12:40:09 AM  ERR! code ELIFECYCLE
npm ERR! errno
4/6/2021, 12:40:09 AM  1
4/6/2021, 12:40:09 AM npm
4/6/2021, 12:40:09 AM ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@3.0.1 install script.
npm
4/6/2021, 12:40:09 AM ERR! This is probably not a problem with npm. There is likely additional logging output above.
4/6/2021, 12:40:09 AM 
4/6/2021, 12:40:09 AM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-04-05T20_40_09_718Z-debug.log
**Additional context**

**Comment by askovi** [comment]
The plugins page on HOOBS 3 requires searching for plugins by name such as brand, accessory type, etc.

In HOOBS 4 this has been transformed into an app store style plugin page. HOOBS 4 is currently in closed beta, you’ll be able to upgrade to it once it’s released.

**Comment by maajaber** [comment]
Okay that's great to know. Anything to be done if my Smarthome devices plugins not available? Orvibo Hub and Bticino Panel?

**Comment by askovi** [comment]
There are a couple of community plugins available for each of those brands. They’re not certified so you will have to test if they work for you. Just search the brand name in the plugin search bar.
