### ISSUE TITLE
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826

### ISSUE THREAD

**Issue by thok21** [hoobs-org/HOOBS#121]
I have everything setup now... in the end all plugins have been running and all devices have be shown in the accessories view in the new hoobs ui. Suddenly after one reboot without having changed anything at the config the accessories cannot be accessed any longer (wether by the Hoobs UI nor by HomeKit). Restarting the service or rebooting will not fix the problem.

The log shows regularly 
'[List Rooms] connect ECONNREFUSED 127.0.0.1:51826'

What could this be? As mentioned everything was running just before...

EDIT: My syslog shows the following:
'
Sep  1 18:43:22 hoobs systemd[1]: Started SSDP Discovery Broadcast Service.
Sep  1 18:43:22 hoobs ssdpd[8030]: No /etc/lsb-release found on system, using built-in server string.
Sep  1 18:43:22 hoobs ssdpd[8030]: Failed binding to 239.255.255.250:1900: Address already in use
Sep  1 18:43:22 hoobs systemd[1]: ssdpd.service: Main process exited, code=exited, status=1/FAILURE
Sep  1 18:43:22 hoobs ssdpd[8030]: ssdpd: Failed creating multicast socket: Address already in use
Sep  1 18:43:22 hoobs systemd[1]: ssdpd.service: Failed with result 'exit-code'.
Sep  1 18:43:25 hoobs systemd[1]: ssdpd.service: Service RestartSec=3s expired, scheduling restart.
Sep  1 18:43:25 hoobs systemd[1]: ssdpd.service: Scheduled restart job, restart counter is at 195.
Sep  1 18:43:25 hoobs systemd[1]: Stopped SSDP Discovery Broadcast Service.
'

**Comment by mkellsy** [comment]
That's the HAP Node server denying the connection. I will look into this.

**Comment by thok21** [comment]
Thanks. One more hint which could help:
After three more reboots I reached to get the devices back. But something is still wrong. The 'loading bar' in the very top of the hoobs-ui is flashing instantly and in the hoobs menu in the top right corner (the three dots) the options start, stop, restart and reboot are greyed out. Curious...

**Comment by mkellsy** [comment]
I reviewed this deeply. And the problem is sometimes the HAP server refuses connections.
https://github.com/KhaosT/HAP-NodeJS

We previously hid this message, but If I don't display the message, Node will throw a different, more nasty, error about not handling errors on requests.

Unfortunately for now, this message will appear from time to time.
