### ISSUE TITLE
Hoobs in a box not working

### ISSUE THREAD

**Issue by stif33** [hoobs-org/HOOBS#1213]
So I have the box, my power went out a few days back and the device never came up. The Ethernet lights were not flashing so I formatted the SD card and flashed with "HOOBS-3.3.3-ARM7" using the balena etcher. I've done it twice already and nothing. The weird part is although my Ethernet lights are on (solid amber and flashing green) my router doesn't recognize the device so I can't even get the IP since is "not connected".

Please help.

**Comment by ramosfranciscoj** [comment]
Same here - I even flashed it to the Hoobs 4 Beta and it won't connect to it. I did not have a power outage but have noticed that it does not let me log into the portal. When it did I tried to update to the new version and it would not update and it would stop working. Need help too

**Comment by stif33** [comment]
> Same here - I even flashed it to the Hoobs 4 Beta and it won't connect to it. I did not have a power outage but have noticed that it does not let me log into the portal. When it did I tried to update to the new version and it would not update and it would stop working. Need help too

So After messing with it for a few hours.  I ended up buying a new Raspberry Pi.  I plugged the same sd card and voila all good to be setup.  I guess the sad part is that the hoobs box that I bought from them just died in one year.  Not worth is since you can get one for $40 in amazon.  

Sorry I don’t have a better answer than just buying a new one.  

Please let me know if you resolve it.
