### ISSUE TITLE
can't access hoobs.local 

### ISSUE THREAD

**Issue by AppleDude1** [hoobs-org/HOOBS#1217]
**Description**
Recently purchased hoobs, was going through the set up and stopped at hoobs.local when I could not access it.

**Version**
Latest version 

**Did you upgrade**
 No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
HOOBS Box

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

No plugins as I can not access it.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

Cant access it

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Does http://hoobs work?
