### ISSUE TITLE
Updated failed, now cannot access hoobs.local

### ISSUE THREAD

**Issue by karinatwork** [hoobs-org/HOOBS#1218]
**Description**
The update failed and nothing worked anymore. The screen was just frozen. I unplugged and plugged it back in, and now I cannot access hoobs.local anymore.
**Version**
I have no idea. I cannot see it anymore.
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
I have no idea.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Mac OS Catalina, 10.15.7

**List your plugins**
Ring, MyGarageDoor

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
Huh?
* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
SSH should be
hoobs@hoobs.local (or ip address)
Password is hoobsadmin

Once in run
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs

The reboot
sudo shutdown -r now

**Comment by karinatwork** [comment]
Thank you, but sadly, I don't understand any of what you just said.

**Comment by askovi** [comment]
Hi Karina,

Please send an email to info@hoobs.org with your order number and someone will assist you remotely.

**Comment by karinatwork** [comment]
I did, someone already contacted me. Thank you so much!!
