### ISSUE TITLE
HOOBS quit working after update 

### ISSUE THREAD

**Issue by drewgranttx** [hoobs-org/HOOBS#1219]
**Description**
After an update all devices quit working in the HomeKit app, I tried logging into the GUI using my IP address as usual, got server not found, when I SSH into the IP address and input the password hoobsadmin I get back "Permission denied, please try again." so I have no way to access the device, device logs, or settings. 

**Version**
Unsure as I can not access anything but I am positive the update was to the latest version that was released. 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
Unknown 

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Vivint 

**Post your config**
Can not access
* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Ssh should be
hoobs@hoobs.local (or ip address)
Password is hoobsadmin

Once in run
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs

The reboot
sudo shutdown -r now

**Comment by drewgranttx** [comment]
I was able to get in to SSH and followed the commands and still can not get it up and running again.

**Comment by mkellsy** [comment]
Run
sudo systemctl status hoobs

Does it say active?

**Comment by drewgranttx** [comment]
hoobs.service - HOOBS
   Loaded: loaded (/etc/systemd/system/hoobs.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-04-12 19:37:33 MDT; 1s ago
  Process: 7056 ExecStart=/usr/local/bin/hoobs (code=exited, status=1/FAILURE)
 Main PID: 7056 (code=exited, status=1/FAILURE)

**Comment by mkellsy** [comment]
Can you post the log
You can get the log with this command

sudo hoobs log

**Comment by drewgranttx** [comment]
hoobs@hoobs:~ $ sudo hoobs log
HOOBS listening on port 80.
Initializing HAP-NodeJS v0.9.3...
No plugins installed.
Preparing Advertiser for 'HOOBS 3578' using bonjour-hap backend!
Starting to advertise 'HOOBS 3578' using bonjour-hap backend!
Bridge is running on port 51826.

**Comment by mkellsy** [comment]
According to the log it should be up.
Try one of these
http://hoobs
http://hoobs.local

If those don't work run
ip address

And then try
http://ip.address

**Comment by drewgranttx** [comment]
Still unable to access hoobs using the local or IP address

**Comment by mkellsy** [comment]
Try running this
It will make sure node is installed and the service is there

```
sudo wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```
