### ISSUE TITLE
Run Pi-Hole and HOOBs on one Pi

### ISSUE THREAD

**Issue by sachangregory** [hoobs-org/HOOBS#122]
Both use port 80 so how do I use Pi-Hole

**Comment by BobbySlope** [comment]
Running v2.1.1 or v3 beta?

**Comment by sachangregory** [comment]
v3

**Comment by mkellsy** [comment]
Edit /etc/nginx/conf.d/hoobs.conf

Change
listen 80;
listen [::]:80;

to (90 in this example, you canuse any port you want as long as it isn't 8080, 51826, 51827, 51828)
listen 90;
listen [::]:90;

**Comment by sachangregory** [comment]
I can’t view the web UI for pihole

**Comment by mkellsy** [comment]
Does pihole use NGINX too? I will look this up. If you want to use both. Starting from scratch just run
sudo npm install -g --unsafe-perm @hoobs/hoobs

It will not automatically setup NGINX now. Further info can be found here https://github.com/hoobs-org/HOOBS/wiki/2.5.2-Debian-Installation.
