### ISSUE TITLE
Can't login into hoobs.local

### ISSUE THREAD

**Issue by Drogo-512** [hoobs-org/HOOBS#1220]
**Description**
A clear and concise description of what the bug is.I just downloaded HOOBS - Raspberry Pi 4B, 3B, and 3B+ on CanaKit -Raspberry Pi 4 PRO Kit, that I just bought to use it for HOOBS. After going for the process of the installation and getting everything set up, come to find out I can't login into HOOBS UI using hoops.local. So I tried everything including, trying to login using IP address, resetting my network, reinstall the HOOBS, using HOOBS - Raspberry Raspberry Pi 1B,2B, and Zero. I even took it a step further and reinstalled Raspberry Pi OS itself. And nothing seems to be workin. 

**Version**
Please include the version of HOOBS you are using.
HOOBS-3.3.3-ARM7

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version. N/A

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository. N/A

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Use the ARM7 version for Pi 4.
Then flash using something like the balinaEtcher.
Insert the sd card into the pi and power on.

Then using your phone. Wait for the HOOBS access point to show up.
Once it does, connect to it and then it will ask you which wifi to connect to. Enter in your password and click connect.
After a short wait the HOOBS access point will go away and then your phone should reconnect to your previous wifi.

Now you should be able to connect to one of these;
http://hoobs
http://hoobs.local
http://ip.address

**Comment by Drogo-512** [comment]
I used balinaEtcher to flash the MicroSD Card, and I did with ARM7. and I followed your instructions, but the HOOBS access point is not showing up.

**Comment by mkellsy** [comment]
Plugin a monitor and see what's happening.

**Comment by Drogo-512** [comment]
It is plugged into the monitor since the beginning. And I'll try this beta and see if it works

**Comment by Drogo-512** [comment]
Hello there. I was wondering if you have any further information about the issue that I have. 
thanks

**Comment by mkellsy** [comment]
I am not sure what's happening.
Try using the official Raspberry Pi OS to see if you can get your Pi to boot.
https://www.raspberrypi.org/software/operating-systems/

Once you get your Pi to boot, you can install HOOBS from APT
First run this command to setup the repos
```
wget -O - https://support.hoobs.org/setup | bash
```

Then install HOOBS
```
sudo apt install -y hoobs
```

**Comment by Drogo-512** [comment]
It worked, thank you so much!
now the new issue I'm having is when I add HOOBS to my homeKit app, it's adding but I can't see it in the room

**Comment by mkellsy** [comment]
HOOBS doesn't expose devices. You need to install plugins for the devices you have.

**Comment by Drogo-512** [comment]
I did install the plugins, and still nothing is showing up on my HomeKit app.

**Comment by mkellsy** [comment]
What plugin?
Did you scan the code on the bridge you created?

**Comment by Drogo-512** [comment]
1- "The Garage Opener With Door Sensor" plugin will not install on the (HOOBS Version: 3.3.5) but I tried it on the HOOBS beta 4.0.17 and it works.
2- the Nest plugin (HOOBS Certified) I'm fallowing the instructions the best I can, but I can't get it to work.
