### ISSUE TITLE
After Updating to 3.3.5 Bridge Service Not Working

### ISSUE THREAD

**Issue by cdaniels77** [hoobs-org/HOOBS#1222]
**Description**
I was having issue with 3.4 install i updated to 3.5 since doing so, the Bridge Service is not running

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
3.3.4

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
HUE
NEST
Platform Wemo
Ring
Roomba STv
Tplink Smarthome
WizLan
(harmony i removed today, thinking this was the issue)

**Post your config**
 "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY96FH",
        "polling_seconds": 1
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "48188",
        "latitude": "",
        "longitude": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "3F:F7:D4:70:95:49"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Roomba",
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            },
            "name": "Roomba",
            "blid": "31B8440C82118530",
            "robotpwd": ":1:1",
            "model": "981",
            "ipaddress": "192.168.86.248",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "cacheTTL": 30
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest"
        },
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            },
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "pollingInterval": 1,
            "transport": "tcp",
            "waitTimeUpdate": 1,
            "timeout": 2
        },
        {
            "platform": "BelkinWeMo",
            "plugin_map": {
                "plugin_name": "homebridge-platform-wemo"
            },
            "name": "Wemo"
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "users": {
                "001788FFFE24F66F": "nRAqtIjwX-nAq5Vk-ZG-SEeUbYnPOQdP-38HmgSI"
            },
            "groups": true,
            "lights": true,
            "linkButton": true,
            "group0": true,
            "scenes": true,
            "scenesAsSwitch": true,
            "rooms": true,
            "rules": false,
            "timeout": 1
        },
        {
            "platform": "WizSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-wiz-lan"
            }
        }
    ]
}
```
POST CONFIG HERE


```
POST LOG HERE
4/13/2021, 2:01:18 PM - HOOBS listening on port 80.
4/13/2021, 2:01:21 PM - Initializing HAP-NodeJS v0.9.3...
4/13/2021, 2:01:25 PM - Loaded plugin 'homebridge-harmony'
4/13/2021, 2:01:25 PM - [4/13/2021, 12:01:25 PM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
4/13/2021, 2:01:25 PM - [4/13/2021, 12:01:25 PM] The plugin "homebridge-hue" requires a Homebridge version of ^1.3.4 which does not satisfy the current Homebridge version of 1.3.3. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
4/13/2021, 2:01:30 PM - Loaded plugin 'homebridge-hue'
4/13/2021, 2:01:30 PM - [4/13/2021, 12:01:30 PM] Registering platform 'homebridge-hue.Hue'
4/13/2021, 2:01:31 PM - Loaded plugin 'homebridge-nest'
4/13/2021, 2:01:31 PM - [4/13/2021, 12:01:31 PM] Registering platform 'homebridge-nest.Nest'
4/13/2021, 2:01:31 PM - [4/13/2021, 12:01:31 PM] The plugin "homebridge-platform-wemo" requires Node.js version of ^14.16.1 which does not satisfy the current Node.js version of v14.16.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
4/13/2021, 2:01:31 PM - Loaded plugin 'homebridge-platform-wemo'
4/13/2021, 2:01:31 PM - [4/13/2021, 12:01:31 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
4/13/2021, 2:01:34 PM - Loaded plugin 'homebridge-ring'
4/13/2021, 2:01:34 PM - [4/13/2021, 12:01:34 PM] Registering platform 'homebridge-ring.Ring'
4/13/2021, 2:01:35 PM - Loaded plugin 'homebridge-roomba-stv'
4/13/2021, 2:01:35 PM - [4/13/2021, 12:01:35 PM] Registering accessory 'homebridge-roomba-stv.Roomba'
4/13/2021, 2:01:36 PM - Loaded plugin 'homebridge-tplink-smarthome'
4/13/2021, 2:01:36 PM - [4/13/2021, 12:01:36 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
4/13/2021, 2:01:36 PM - Loaded plugin 'homebridge-wiz-lan'
4/13/2021, 2:01:36 PM - Loading 8 platforms...
4/13/2021, 2:01:36 PM - [4/13/2021, 12:01:36 PM] Registering platform 'homebridge-wiz-lan.WizSmarthome'
4/13/2021, 2:01:36 PM - [Ring] Initializing Ring platform...
4/13/2021, 2:01:36 PM - [Nest] Initializing Nest platform...
4/13/2021, 2:01:36 PM - [Living Room TV] Initializing HarmonyHubWebSocket platform...
4/13/2021, 2:01:36 PM - [Living Room TV] HarmonyPlatform Init
4/13/2021, 2:01:36 PM - [4/13/2021, 12:01:36 PM] The dynamic platform HarmonyHubWebSocket from the plugin homebridge-harmony seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
4/13/2021, 2:01:36 PM - [ManCave TV] Initializing HarmonyHubWebSocket platform...
4/13/2021, 2:01:36 PM - [ManCave TV] HarmonyPlatform Init
4/13/2021, 2:01:36 PM - [TplinkSmarthome] Initializing TplinkSmarthome platform...
4/13/2021, 2:01:36 PM - [TplinkSmarthome] homebridge-tplink-smarthome v6.3.0, node v14.16.0, homebridge v1.3.3, api v2.7
4/13/2021, 2:01:36 PM - [Wemo] Initializing BelkinWeMo platform...
4/13/2021, 2:01:36 PM - [Hue] Initializing Hue platform...
4/13/2021, 2:01:36 PM - [Hue] homebridge-hue v0.13.5, node v14.16.0, homebridge v1.3.3
4/13/2021, 2:01:36 PM - [Hue] config.json: plugin_map: invalid key
4/13/2021, 2:01:36 PM - [Hue] config.json: nupnp: invalid key
4/13/2021, 2:01:36 PM - [Hue] searching bridges and gateways
4/13/2021, 2:01:36 PM - [WizSmarthome] Initializing WizSmarthome platform...
4/13/2021, 2:01:36 PM - Loading 1 accessories...
4/13/2021, 2:01:36 PM - [Roomba] Initializing Roomba accessory...
4/13/2021, 2:01:36 PM - [Roomba] Enabling keepAlive
4/13/2021, 2:01:37 PM - [Ring] Configuring cached accessory 3e2865b9-726c-4acc-bbc0-4f6da5e37e48 Front Door
4/13/2021, 2:01:37 PM - [Ring] Configuring cached accessory 3db72ee9-5bf0-4026-84e8-4ca08828a70a Canton Mode
4/13/2021, 2:01:37 PM - [TplinkSmarthome] Configuring cached accessory: [Plug1] UUID: 87cdb423-bf26-42d8-a3e0-adfa12547d83 deviceId: 8006AC27C74BAD10F7FB211F4E207CC91CE1A61700 
4/13/2021, 2:01:37 PM - [TplinkSmarthome] Configuring cached accessory: [Plug2] UUID: 2098c564-1da2-429b-a4ea-0a58c75244b5 deviceId: 8006AC27C74BAD10F7FB211F4E207CC91CE1A61701 
4/13/2021, 2:01:37 PM - [WizSmarthome] Loading accessory from cache: a8bb509e8e90
4/13/2021, 2:01:37 PM - [ManCave TV] WARNING - configureAccessory - The platform Living Room TV is not there anymore in your config (name property). It won't be loaded and will be removed from cache.
4/13/2021, 2:01:37 PM - [ManCave TV] WARNING - configureAccessory - The platform Living Room TV is not there anymore in your config (name property). It won't be loaded and will be removed from cache.
4/13/2021, 2:01:38 PM - Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f014b51c-e623-47b1-b1bf-5a395e40c951
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
4/13/2021, 2:01:38 PM - Got SIGTERM, shutting down Bridge...
4/13/2021, 2:01:38 PM - [Living Room TV] INFO - shutdown
4/13/2021, 2:01:38 PM - [ManCave TV] INFO - shutdown
4/13/2021, 2:01:38 PM - [Living Room TV] INFO - shutdown
4/13/2021, 2:01:38 PM - [ManCave TV] INFO - shutdown
4/13/2021, 2:01:41 PM - [Hue] Vision: Signify Netherlands B.V. BSB002 bridge v1943185030, api v1.43.0
4/13/2021, 2:01:42 PM - [Hue] Vision: 24 accessories
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Vision'...
4/13/2021, 2:01:42 PM - [Hue] Vision: 3 services
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Group 0'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Entertainment area 1'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Man Cave'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Living Room'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Front door'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Master'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'MC TV FRT LH'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'MC TV RR RH'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'MC TV  RR LH'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'MC TV FRT RH'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Nook RR'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Nook FRT'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Fish Tank RR'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'FRT Porch'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'LR TV'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'MB FRT LH'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'MB FRT RH'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'MB RR RH'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'MB RR LH'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Fish Tank FRT'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Man Cave TV'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'iMac'...
4/13/2021, 2:01:42 PM - Initializing platform accessory 'Bedroom TV Light'...
4/13/2021, 2:06:06 PM - npm
4/13/2021, 2:06:06 PM - 
4/13/2021, 2:06:06 PM - WARN
4/13/2021, 2:06:06 PM -  EBADENGINE Unsupported engine {
npm WARN EBADENGINE
4/13/2021, 2:06:06 PM -    package: 'homebridge-platform-wemo@3.0.2',
npm WARN EBADENGINE   required: { homebridge: '^1.3.3', node: '^14.16.1' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.3' }
npm WARN
4/13/2021, 2:06:06 PM - EBADENGINE }
4/13/2021, 2:06:14 PM - 
removed 7 packages, and audited 559 packages in 14s

39 packages are looking for funding
  run `npm fund` for details
4/13/2021, 2:06:14 PM - 
4 low severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
4/13/2021, 2:06:14 PM - Plugin "homebridge-harmony" removed.
4/13/2021, 2:06:17 PM - Initializing HAP-NodeJS v0.9.3...
4/13/2021, 2:06:21 PM - [4/13/2021, 12:06:20 PM] The plugin "homebridge-hue" requires a Homebridge version of ^1.3.4 which does not satisfy the current Homebridge version of 1.3.3. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
4/13/2021, 2:06:26 PM - Loaded plugin 'homebridge-hue'
4/13/2021, 2:06:26 PM - [4/13/2021, 12:06:26 PM] Registering platform 'homebridge-hue.Hue'
4/13/2021, 2:06:26 PM - Loaded plugin 'homebridge-nest'
4/13/2021, 2:06:26 PM - [4/13/2021, 12:06:26 PM] Registering platform 'homebridge-nest.Nest'
4/13/2021, 2:06:26 PM - [4/13/2021, 12:06:26 PM] The plugin "homebridge-platform-wemo" requires Node.js version of ^14.16.1 which does not satisfy the current Node.js version of v14.16.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
4/13/2021, 2:06:26 PM - Loaded plugin 'homebridge-platform-wemo'
4/13/2021, 2:06:26 PM - [4/13/2021, 12:06:26 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
4/13/2021, 2:06:30 PM - Loaded plugin 'homebridge-ring'
4/13/2021, 2:06:30 PM - [4/13/2021, 12:06:30 PM] Registering platform 'homebridge-ring.Ring'
4/13/2021, 2:06:30 PM - Initializing HAP-NodeJS v0.9.3...
4/13/2021, 2:06:31 PM - Loaded plugin 'homebridge-roomba-stv'
4/13/2021, 2:06:31 PM - [4/13/2021, 12:06:31 PM] Registering accessory 'homebridge-roomba-stv.Roomba'
4/13/2021, 2:06:32 PM - Loaded plugin 'homebridge-tplink-smarthome'
4/13/2021, 2:06:32 PM - [4/13/2021, 12:06:32 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
4/13/2021, 2:06:32 PM - Loaded plugin 'homebridge-wiz-lan'
4/13/2021, 2:06:32 PM - [4/13/2021, 12:06:32 PM] Registering platform 'homebridge-wiz-lan.WizSmarthome'
4/13/2021, 2:06:32 PM - Loading 6 platforms...
4/13/2021, 2:06:32 PM - [Ring] Initializing Ring platform...
4/13/2021, 2:06:32 PM - [Nest] Initializing Nest platform...
4/13/2021, 2:06:32 PM - [TplinkSmarthome] Initializing TplinkSmarthome platform...
4/13/2021, 2:06:32 PM - [TplinkSmarthome] homebridge-tplink-smarthome v6.3.0, node v14.16.0, homebridge v1.3.3, api v2.7
4/13/2021, 2:06:32 PM - [Wemo] Initializing BelkinWeMo platform...
4/13/2021, 2:06:32 PM - [Hue] Initializing Hue platform...
4/13/2021, 2:06:32 PM - [Hue] homebridge-hue v0.13.5, node v14.16.0, homebridge v1.3.3
4/13/2021, 2:06:32 PM - [Hue] config.json: plugin_map: invalid key
4/13/2021, 2:06:32 PM - [Hue] config.json: nupnp: invalid key
4/13/2021, 2:06:32 PM - [Hue] searching bridges and gateways
4/13/2021, 2:06:32 PM - [WizSmarthome] Initializing WizSmarthome platform...
4/13/2021, 2:06:33 PM - Loading 1 accessories...
4/13/2021, 2:06:33 PM - [Roomba] Initializing Roomba accessory...
4/13/2021, 2:06:33 PM - [Roomba] Enabling keepAlive
4/13/2021, 2:06:33 PM - [Ring] Configuring cached accessory 3e2865b9-726c-4acc-bbc0-4f6da5e37e48 Front Door
4/13/2021, 2:06:33 PM - [Ring] Configuring cached accessory 3db72ee9-5bf0-4026-84e8-4ca08828a70a Canton Mode
4/13/2021, 2:06:33 PM - [TplinkSmarthome] Configuring cached accessory: [Plug1] UUID: 87cdb423-bf26-42d8-a3e0-adfa12547d83 deviceId: 8006AC27C74BAD10F7FB211F4E207CC91CE1A61700 
4/13/2021, 2:06:33 PM - [TplinkSmarthome] Configuring cached accessory: [Plug2] UUID: 2098c564-1da2-429b-a4ea-0a58c75244b5 deviceId: 8006AC27C74BAD10F7FB211F4E207CC91CE1A61701 
4/13/2021, 2:06:33 PM - [WizSmarthome] Loading accessory from cache: a8bb509e8e90
4/13/2021, 2:06:33 PM - Failed to find plugin to handle accessory Living Room TV-TV
4/13/2021, 2:06:33 PM - Failed to find plugin to handle accessory Living Room TV-Watch Apple TV
4/13/2021, 2:06:33 PM - Failed to find plugin to handle accessory ManCave TV-TV
4/13/2021, 2:06:33 PM - Failed to find plugin to handle accessory ManCave TV-PS4
4/13/2021, 2:06:33 PM - Failed to find plugin to handle accessory ManCave TV-Switch
4/13/2021, 2:06:33 PM - Failed to find plugin to handle accessory ManCave TV-TV-Switch
4/13/2021, 2:06:34 PM - Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f014b51c-e623-47b1-b1bf-5a395e40c951
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
4/13/2021, 2:06:34 PM - Got SIGTERM, shutting down Bridge...
4/13/2021, 2:06:35 PM - [4/13/2021, 12:06:34 PM] The plugin "homebridge-hue" requires a Homebridge version of ^1.3.4 which does not satisfy the current Homebridge version of 1.3.3. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
4/13/2021, 2:06:37 PM - [Hue] Vision: Signify Netherlands B.V. BSB002 bridge v1943185030, api v1.43.0
4/13/2021, 2:06:38 PM - [Hue] Vision: 24 accessories
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Vision'...
4/13/2021, 2:06:38 PM - [Hue] Vision: 3 services
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Group 0'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Entertainment area 1'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Man Cave'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Living Room'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Front door'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Master'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'MC TV FRT LH'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'MC TV RR RH'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'MC TV  RR LH'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'MC TV FRT RH'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Nook RR'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Nook FRT'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Fish Tank RR'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'FRT Porch'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'LR TV'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'MB FRT LH'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'MB FRT RH'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'MB RR RH'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'MB RR LH'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Fish Tank FRT'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Man Cave TV'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'iMac'...
4/13/2021, 2:06:38 PM - Initializing platform accessory 'Bedroom TV Light'...
4/13/2021, 2:06:40 PM - Loaded plugin 'homebridge-hue'
4/13/2021, 2:06:40 PM - [4/13/2021, 12:06:40 PM] Registering platform 'homebridge-hue.Hue'
4/13/2021, 2:06:41 PM - Loaded plugin 'homebridge-nest'
4/13/2021, 2:06:41 PM - [4/13/2021, 12:06:41 PM] Registering platform 'homebridge-nest.Nest'
4/13/2021, 2:06:41 PM - [4/13/2021, 12:06:41 PM] The plugin "homebridge-platform-wemo" requires Node.js version of ^14.16.1 which does not satisfy the current Node.js version of v14.16.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
4/13/2021, 2:06:41 PM - Loaded plugin 'homebridge-platform-wemo'
4/13/2021, 2:06:41 PM - [4/13/2021, 12:06:41 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
4/13/2021, 2:06:44 PM - Loaded plugin 'homebridge-ring'
4/13/2021, 2:06:44 PM - [4/13/2021, 12:06:44 PM] Registering platform 'homebridge-ring.Ring'
4/13/2021, 2:06:45 PM - Loaded plugin 'homebridge-roomba-stv'
4/13/2021, 2:06:45 PM - [4/13/2021, 12:06:45 PM] Registering accessory 'homebridge-roomba-stv.Roomba'
4/13/2021, 2:06:46 PM - Loaded plugin 'homebridge-tplink-smarthome'
4/13/2021, 2:06:46 PM - [4/13/2021, 12:06:46 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
4/13/2021, 2:06:46 PM - Loaded plugin 'homebridge-wiz-lan'
4/13/2021, 2:06:46 PM - Loading 6 platforms...
4/13/2021, 2:06:46 PM - [4/13/2021, 12:06:46 PM] Registering platform 'homebridge-wiz-lan.WizSmarthome'
4/13/2021, 2:06:46 PM - [Ring] Initializing Ring platform...
4/13/2021, 2:06:46 PM - [Nest] Initializing Nest platform...
4/13/2021, 2:06:46 PM - [TplinkSmarthome] Initializing TplinkSmarthome platform...
4/13/2021, 2:06:46 PM - [TplinkSmarthome] homebridge-tplink-smarthome v6.3.0, node v14.16.0, homebridge v1.3.3, api v2.7
4/13/2021, 2:06:46 PM - [Wemo] Initializing BelkinWeMo platform...
4/13/2021, 2:06:46 PM - [Hue] Initializing Hue platform...
4/13/2021, 2:06:46 PM - [Hue] homebridge-hue v0.13.5, node v14.16.0, homebridge v1.3.3
4/13/2021, 2:06:46 PM - [Hue] config.json: plugin_map: invalid key
4/13/2021, 2:06:46 PM - [Hue] config.json: nupnp: invalid key
4/13/2021, 2:06:46 PM - [Hue] searching bridges and gateways
4/13/2021, 2:06:47 PM - [WizSmarthome] Initializing WizSmarthome platform...
4/13/2021, 2:06:47 PM - Loading 1 accessories...
4/13/2021, 2:06:47 PM - [Roomba] Initializing Roomba accessory...
4/13/2021, 2:06:47 PM - [Roomba] Enabling keepAlive
4/13/2021, 2:06:47 PM - [Ring] Configuring cached accessory 3e2865b9-726c-4acc-bbc0-4f6da5e37e48 Front Door
4/13/2021, 2:06:47 PM - [Ring] Configuring cached accessory 3db72ee9-5bf0-4026-84e8-4ca08828a70a Canton Mode
4/13/2021, 2:06:47 PM - [TplinkSmarthome] Configuring cached accessory: [Plug1] UUID: 87cdb423-bf26-42d8-a3e0-adfa12547d83 deviceId: 8006AC27C74BAD10F7FB211F4E207CC91CE1A61700 
4/13/2021, 2:06:47 PM - [TplinkSmarthome] Configuring cached accessory: [Plug2] UUID: 2098c564-1da2-429b-a4ea-0a58c75244b5 deviceId: 8006AC27C74BAD10F7FB211F4E207CC91CE1A61701 
4/13/2021, 2:06:47 PM - [WizSmarthome] Loading accessory from cache: a8bb509e8e90
4/13/2021, 2:06:47 PM - Failed to find plugin to handle accessory Living Room TV-TV
4/13/2021, 2:06:47 PM - Failed to find plugin to handle accessory Living Room TV-Watch Apple TV
4/13/2021, 2:06:47 PM - Failed to find plugin to handle accessory ManCave TV-TV
4/13/2021, 2:06:47 PM - Failed to find plugin to handle accessory ManCave TV-PS4
4/13/2021, 2:06:47 PM - Failed to find plugin to handle accessory ManCave TV-Switch
4/13/2021, 2:06:47 PM - Failed to find plugin to handle accessory ManCave TV-TV-Switch
4/13/2021, 2:06:48 PM - Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f014b51c-e623-47b1-b1bf-5a395e40c951
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
4/13/2021, 2:06:48 PM - Got SIGTERM, shutting down Bridge...
4/13/2021, 2:06:51 PM - [Hue] Vision: Signify Netherlands B.V. BSB002 bridge v1943185030, api v1.43.0
4/13/2021, 2:06:52 PM - [Hue] Vision: 24 accessories
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Vision'...
4/13/2021, 2:06:52 PM - [Hue] Vision: 3 services
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Group 0'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Entertainment area 1'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Man Cave'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Living Room'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Front door'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Master'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'MC TV FRT LH'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'MC TV RR RH'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'MC TV  RR LH'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'MC TV FRT RH'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Nook RR'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Nook FRT'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Fish Tank RR'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'FRT Porch'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'LR TV'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'MB FRT LH'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'MB FRT RH'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'MB RR RH'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'MB RR LH'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Fish Tank FRT'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Man Cave TV'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'iMac'...
4/13/2021, 2:06:52 PM - Initializing platform accessory 'Bedroom TV Light'...
4/13/2021, 2:12:31 PM - connect ECONNREFUSED 127.0.0.1:51826
**Additional context**

**Comment by EddieDSuza** [comment]
Go to Help > Common Issues > Reset Connection.

Then Reboot Server
