### ISSUE TITLE
Cannot log into hoobs: Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

### ISSUE THREAD

**Issue by chanman87** [hoobs-org/HOOBS#1223]
**Description**
HOOBS suddenly stoped working after i did a reboot on my router
i get an error trying to get into the UI, 
Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'
or it just doesn't allow me onto the site at all with a cannot connect to server page

is there a way to factory reset without going into the UI?

**Version**
Not sure what version im running anymore as I cannot get into the UI 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- X No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
Please email info@hoobs.org with your sales order no. They will replace the SD card. Please close the issue
