### ISSUE TITLE
bridge service stops

### ISSUE THREAD

**Issue by ewokkillah** [hoobs-org/HOOBS#1224]
after upgrading to 3.3.5 the bridge stopped. I've done a factory reset, but when I try to install any plugins bridge service stops and I have to do another reset.

**Comment by mkellsy** [comment]
Can you post logs.

**Comment by ewokkillah** [comment]
4/13/2021, 5:01:10 PM Plugin "homebridge-camera-ffmpeg" installed.
4/13/2021, 5:01:11 PM Got SIGINT, shutting down Bridge...
4/13/2021, 5:01:17 PM Initializing HAP-NodeJS v0.9.3...
4/13/2021, 5:01:18 PM Loaded plugin 'homebridge-camera-ffmpeg'
4/13/2021, 5:01:18 PM [4/13/2021, 6:01:18 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
4/13/2021, 5:01:18 PM Loading 1 platforms...
4/13/2021, 5:01:18 PM [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
4/13/2021, 5:01:18 PM Preparing Advertiser for 'HOOBS 4806' using bonjour-hap backend!
4/13/2021, 5:01:18 PM Starting to advertise 'HOOBS 4806' using bonjour-hap backend!
4/13/2021, 5:01:18 PM Bridge is running on port 51826.
4/13/2021, 5:04:12 PM Got SIGINT, shutting down Bridge...
4/13/2021, 5:04:17 PM Initializing HAP-NodeJS v0.9.3...
4/13/2021, 5:04:18 PM Loaded plugin 'homebridge-camera-ffmpeg'
4/13/2021, 5:04:18 PM [4/13/2021, 6:04:18 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
4/13/2021, 5:04:18 PM Loading 1 platforms...
4/13/2021, 5:04:18 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...
4/13/2021, 5:06:55 PM Initializing HAP-NodeJS v0.9.3...
4/13/2021, 5:06:56 PM Loaded plugin 'homebridge-camera-ffmpeg'
4/13/2021, 5:06:56 PM [4/13/2021, 6:06:56 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
4/13/2021, 5:06:56 PM Loading 1 platforms...
4/13/2021, 5:06:56 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...
4/13/2021, 5:07:11 PM Initializing HAP-NodeJS v0.9.3...
4/13/2021, 5:07:12 PM Loaded plugin 'homebridge-camera-ffmpeg'
4/13/2021, 5:07:12 PM [4/13/2021, 6:07:12 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
4/13/2021, 5:07:12 PM Loading 1 platforms...
4/13/2021, 5:07:12 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...
4/13/2021, 5:07:24 PM Initializing HAP-NodeJS v0.9.3...
4/13/2021, 5:07:24 PM Loaded plugin 'homebridge-camera-ffmpeg'
4/13/2021, 5:07:24 PM [4/13/2021, 6:07:24 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
4/13/2021, 5:07:24 PM Loading 1 platforms...
4/13/2021, 5:07:24 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...
4/13/2021, 5:09:01 PM Initializing HAP-NodeJS v0.9.3...
4/13/2021, 5:09:02 PM Loaded plugin 'homebridge-camera-ffmpeg'
4/13/2021, 5:09:02 PM [4/13/2021, 6:09:02 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
4/13/2021, 5:09:02 PM Loading 1 platforms...
4/13/2021, 5:09:02 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...
4/13/2021, 5:09:16 PM Initializing HAP-NodeJS v0.9.3...
4/13/2021, 5:09:17 PM Loaded plugin 'homebridge-camera-ffmpeg'
4/13/2021, 5:09:17 PM [4/13/2021, 6:09:17 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
4/13/2021, 5:09:17 PM Loading 1 platforms...
4/13/2021, 5:09:17 PM [Camera FFmpeg] Initializing Camera-ffmpeg platform...

> Can you post logs.

**Comment by mkellsy** [comment]
The only thing I can think is your NPM is giving you grief.

If you go to this folder and run npm install what's the output?
```
cd ~/.hoobs
npm install
```

**Comment by ewokkillah** [comment]
hoobs@hoobs:/home/hoobs/.hoobs/etc $ cd ~/.hoobs
hoobs@hoobs:/home/hoobs/.hoobs $ npm install
npm WARN checkPermissions Missing write access to /home/hoobs/.hoobs/node_modules/hap-nodejs
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/hoobs/.hoobs/node_modules/hap-nodejs
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR!  [Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/hap-nodejs'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-04-14T19_27_46_613Z-debug.log
hoobs@hoobs:/home/hoobs/.hoobs $

**Comment by mkellsy** [comment]
You need to stop HOOBS before running that.
```
sudo systemctl stop hoobs.service
```

Then start it back  up after running
```
sudo systemctl start hoobs.service
```

**Comment by ewokkillah** [comment]
after I stop HOOBS how do I terminal in?

**Comment by mkellsy** [comment]
You will need to use ssh.
From a mac, open the terminal and type this.
```
ssh hoobs@hoobs.local
```

Password is hoobsadmin

on Windows, you will need to use a tool like Putty.

**Comment by ewokkillah** [comment]
hoobs@hoobs:/ $ sudo systemctl stop hoobs.service
hoobs@hoobs:/ $ cd ~/.hoobs
hoobs@hoobs:~/.hoobs $ npm install
npm WARN checkPermissions Missing write access to /home/hoobs/.hoobs/node_modules/hap-nodejs
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/hoobs/.hoobs/node_modules/hap-nodejs
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR!  [Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/hap-nodejs'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-04-17T04_44_09_062Z-debug.log
hoobs@hoobs:~/.hoobs $

**Comment by CookiesBoomerang** [comment]
Same for me.

**Comment by mkellsy** [comment]
Steps
1. SSH into hoobs
From a Mac
```
ssh hoobs@hoobs.local
```
On Windows you will have to use Putty https://www.putty.org/
