### ISSUE TITLE
Plugin Securitysystem new version 4.2.0

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1225]
Hi,
the Plugin Securitysystem has a new version 4.2.0.
The latest Update was 4.2.0-beta-1 (yes it was an official release even with beta-1 in the name)
But now it will not update to the final 4.2.0

Can you make this happen?

**Comment by bwp91** [comment]
this is not an 'official' solution, but so long as you are updating rather than installing (ie you already have the plugin installed) you can:

1. stop hoobs service
2. run these commands in the terminal:
    ```
    cd ~/.hoobs/
    ```
    ```
    npm install homebridge-securitysystem@latest
    ```
3. start hoobs again

**Comment by Christian-CFP** [comment]
Thank you!
