### ISSUE TITLE
I can't log into the web client 

### ISSUE THREAD

**Issue by Con1977** [hoobs-org/HOOBS#1227]
I updated the hoobs in the box purchased from Hoobs and now I can't log into the web client. Need Help

**Comment by EddieDSuza** [comment]
Here are the instructions to retrieve the logs:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this command: sudo hoobs service log

Copy and pastiche output
