### ISSUE TITLE
Unable to backup system

### ISSUE THREAD

**Issue by freddair** [hoobs-org/HOOBS#1229]
**Description**
when I try to backup the system via settings - backup - system, it starts the "busy" animation but never saves a file. after a while, i have to log in again to hoops. Tried this many times after re-boots and even complete (manual) re-installs and config-restores...

**Version**
3.3.5, but had the same issue on earlier versions

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
3.3.3

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
Dummy Switch
Eveatmo
Fritz Platform
R Pi
Weather Plus
LG webOS
Xiaomifan
Xiaomi Roborock Vacuum

**Comment by mkellsy** [comment]
The number of plugins is probably slowing the backup down.

A backup is just a zip file of the ~/.hoobs folder. You can create a backup on the pi with this command.

```
cp -r ~/.hoobs ~/hoobs_backup
```

We have addressed this in our next major release which is currently in beta testing.

**Comment by Christian-CFP** [comment]
Just my 2 Cents without creating a new issue. In my case the config file that should be backuped, opens in an new window as plain text.

HOOB 3.3.5

**Comment by mkellsy** [comment]
Safari has issues with the method the UI creates the config download.
We have addressed this in HOOBS 4.
