### ISSUE TITLE
Unable to have homebridge-roku-config work on ROKU Plug-In

### ISSUE THREAD

**Issue by sachangregory** [hoobs-org/HOOBS#123]

**Comment by sachangregory** [comment]
It says command not found

**Comment by BobbySlope** [comment]
On v2.1.1 or beta v3?
Please show config and log

**Comment by sachangregory** [comment]
v3

**Comment by mkellsy** [comment]
HOOBS uses a slightly different config structure. This plugin attempts to modify the config, but it is in a different place.

I have taken note of this, and will look at what this plugin does. In this issue.
https://github.com/hoobs-org/HOOBS/issues/97

Currently don't support this plugin.
