### ISSUE TITLE
Turn on Bluetooth on raspi 4 via hoobs?

### ISSUE THREAD

**Issue by frhofer** [hoobs-org/HOOBS#1230]
Hi altogether,
As I am a total newbie I have a (for me unsolvable) question:

how can I turn on Bluetooth on my Raspi, on which I have installed hoobs? I often read to turn it on with a Sudo command. Can I simply include it into the hoobs configuration, and if yes, at wihich position would it be the best?

(you see I have no idea at all)

Greets,
frhofer

**Comment by EddieDSuza** [comment]
There is an additional package called `Noble you need to install`. This helps to enable the Pi`s bluetooth radio. 

All the plugins that need Bluetooth to be enabled - have the guides in them on how the can be done.

**Comment by frhofer** [comment]
Sorry for this probable stupid question: I didn’t find a plug-in called noble... 
can you help me further?
Thanks a lot!

**Comment by EddieDSuza** [comment]
hi there - which device are you trying to connect via Bluetooth.

**Comment by EddieDSuza** [comment]
Access the HOOBS UI and click on the 3 dots > terminal and run the below command to connect with your switchbot

`sudo apt install -y bluetooth bluez libbluetooth-dev libudev-dev libcap2-bin`

This will enable the bluetooth radio and also pair with your device

**Comment by frhofer** [comment]
I just got the same tip yesterday on reddit. Stupid question: how can I control if Bluetooth really works? 🤔

**Comment by EddieDSuza** [comment]
Install the plugin, add the device information and once you restart service then the plugin will connect with the device.
