### ISSUE TITLE
Please login via SSH and get the HOOBS logs.

### ISSUE THREAD

**Issue by abozaki32stlouis** [hoobs-org/HOOBS#1231]
Please login via SSH and get the HOOBS logs.

1. On MacOS use the Terminal app and type: `ssh hoobs@hoobs.local`

Type yes to accept the certificate key then press enter. When prompted for password, type `hoobsadmin`

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this: `sudo hoobs service log`

_Originally posted by @askovi in https://github.com/hoobs-org/HOOBS/issues/849#issuecomment-711109359_

**Comment by abozaki32stlouis** [comment]
I can't access hoops.local despite trying the above , I am desperate for help

**Comment by mkellsy** [comment]
Try
`ssh hoobs@hoobs`

I also hope this is not the case, I noticed you spelled hoobs with a p, check that you are using hoo**b**s.
