### ISSUE TITLE
I cannot access my hoobs.local

### ISSUE THREAD

**Issue by abozaki32stlouis** [hoobs-org/HOOBS#1232]
**Description**

I tried to upgrade my node version 12.16 to  a newer one, upgrade process was interrupted. and now I can't access my hoobs.local anymore. my already installed plugins are not working

**Version**
Please include the version of HOOBS you are using.
not sure now as I can't access my hoobs.local

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
Try accessing the Box via terminal and retrieve the logs 

Here are the instructions to retrieve the logs:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this command: sudo hoobs service log

Copy and paste the output

**Comment by abozaki32stlouis** [comment]
Thanks 

Here is what I get 

***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^
Error: The module ***@***.***/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 121.
Stopped HOOBS.
Started HOOBS.
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- ***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js
- ***@***.***/hoobs/node_modules/node-pty/lib/index.js
- ***@***.***/hoobs/server/api.js
- ***@***.***/hoobs/server/cli.js
- ***@***.***/hoobs/scripts/loader.js
- ***@***.***/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    ***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js',
    ***@***.***/hoobs/node_modules/node-pty/lib/index.js',
    ***@***.***/hoobs/server/api.js',
    ***@***.***/hoobs/server/cli.js',
    ***@***.***/hoobs/scripts/loader.js',
    ***@***.***/hoobs/bin/hoobs'
  ]
}
***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^
Error: The module ***@***.***/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
h

**Comment by EddieDSuza** [comment]
please SSH and run this 

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

**Comment by abozaki32stlouis** [comment]
Thanks Eddie, but this is what I got and still can not access my hoobs.local



Thank You for choosing HOOBS
================================================================================
Node Version 14.16.0
Updating Repositories
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u2).
git is already the newest version (1:2.20.1-2+deb10u3).
tar is already the newest version (1.30+dfsg-6).
0 upgraded, 0 newly installed, 0 to remove and 109 not upgraded.
setsebool:  SELinux is disabled.
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path ***@***.***/hoobs
npm ERR! dest ***@***.***/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename ***@***.***/hoobs' -> ***@***.***/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-19T00_07_23_550Z-debug.log
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path ***@***.***/hoobs
npm ERR! dest ***@***.***/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename ***@***.***/hoobs' -> ***@***.***/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-19T00_07_29_350Z-debug.log
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path ***@***.***/hoobs
npm ERR! dest ***@***.***/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename ***@***.***/hoobs' -> ***@***.***/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-19T00_07_58_219Z-debug.log

Restarting HOOBS
==============================================================================================================================================================================================================================================================
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- ***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js
- ***@***.***/hoobs/node_modules/node-pty/lib/index.js
- ***@***.***/hoobs/server/api.js
- ***@***.***/hoobs/server/cli.js
- ***@***.***/hoobs/scripts/loader.js
- ***@***.***/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    ***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js',
    ***@***.***/hoobs/node_modules/node-pty/lib/index.js',
    ***@***.***/hoobs/server/api.js',
    ***@***.***/hoobs/server/cli.js',
    ***@***.***/hoobs/scripts/loader.js',
    ***@***.***/hoobs/bin/hoobs'
  ]
}
***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: The module ***@***.***/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ***@***.***/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
***@***.***:~ $

**Comment by bwp91** [comment]
SSH back into your HOOBS box and run these separately:

```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by abozaki32stlouis** [comment]
Thanks , still no luck


***@***.***:~ $ sudo npm uninstall -g @hoobs/hoobs
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path ***@***.***/hoobs
npm ERR! dest ***@***.***/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename ***@***.***/hoobs' -> ***@***.***/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-19T11_10_54_100Z-debug.log
***@***.***:~ $ sudo npm install -g --unsafe-perm @hoobs/hoobs
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path ***@***.***/hoobs
npm ERR! dest ***@***.***/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename ***@***.***/hoobs' -> ***@***.***/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-19T11_11_54_084Z-debug.log
***@***.***:~ $

**Comment by bwp91** [comment]
Try these:

```
sudo rm -rf /usr/local/lib/node_modules/@hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by abozaki32stlouis** [comment]
That’s great. Now I can access hoobs.local but bridge is not on my homekit? Any advice on how to add it back?

**Comment by bwp91** [comment]
You could try this?
https://support.hoobs.org/docs/5e960c1b0ab68b0344e872e0

You may need to delete the old hoobs bridge from the home app (Home Settings) and then re add using the above link

**Comment by abozaki32stlouis** [comment]
Thanks Ben 

I removed bridge from home app, tried to reset but dashboard is still blank and can’t see barcode to add back hoobs

**Comment by abozaki32stlouis** [comment]
Good news, I was able to add back hoobs bridge , but now none of my plugins are added to HomeKit , tried rebooting and restating with no success  should I uninstall each one and add it back ?!

**Comment by bwp91** [comment]
Does the hoobs ui say the plugins are installed? Try restarting the hoobs service. do the accessories appear in the hoobs ui? if they are, then they should appear in the home app. maybe check your default homekit room as the accessories may have been added to that room

**Comment by abozaki32stlouis** [comment]
They do not actually

**Comment by abozaki32stlouis** [comment]
Thanks guys 

My hoobs is up and running again, I had to uninstall and reinstall all my plugins for it to work though .

But everything seems to be running smoothly now .

Again thank you all for the efforts and great support 😃
