### ISSUE TITLE
the Camera-ffmpeg addon seems to break Ring addon

### ISSUE THREAD

**Issue by tfraley** [hoobs-org/HOOBS#1234]
Good day guys, New user here. 
I Have set up Ring and that seems to be working well. 
However, I also have some Wyze cameras and wanted to set up "Camera-ffmpeg" but it seems to break the ring feeds when I set it up. Can not get it going. 
I also have a Canary camera I would also like to get up have not had any luck with that either. 
Not sure if all these camera apps are breaking each other.
Thoughts suggestions welcome.
Also a side note very nube question:

**Comment by EddieDSuza** [comment]
can you post your logs when you install the camera-ffmpeg plugin

**Comment by tfraley** [comment]
I just figured it out. 
Once I found the advanced table for the json I noticed it was duplicating code from camera-ffmpeg.
this was on me for being new to this. I was copying my version of the example code the whole thing. 
But seems the first few lines the addon includes so it was doubling up

Please ignore I was able to get both of them working

**Comment by EddieDSuza** [comment]
Awesome. Please close the issue
