### ISSUE TITLE
DiyHue plugin support (Virtual Philips Hue Bridge)

### ISSUE THREAD

**Issue by iANGELgr** [hoobs-org/HOOBS#1237]
**Description**
I install successfully the plugin DiyHUE from Hoobs Terminal with the following code
`curl -fsSL https://get.diyhue.org -o install.sh
sudo bash install.sh`
The installation was successful. After that the virtual bridge is discovered by the apps (Philips hue app & Hue Essentials) as virtual Philips hue bridge and must to Pairing diyHue with the Hue app.

To pair a new device to diyHue, first head to http://{IP_ADDRESS}/hue/linkbutton
When I go to this url, shows me the login page of Hoobs and NOT the DIYHUE interface and page there is blank!!!!!

So I CAN'T pair the virtual bridge

The developer of DIYHUE ask me to find the log to see how this try to pair. If it use the cloud based detection we have no options. :(
More here:
https://github.com/diyhue/diyHue/discussions/607

How to take the log from Hoobs???

**Expected behavoir**
I want to install Yeelight bulbs to work as Philips Hue bulbs (inside Philips hue app & Hue Essentials app) so DIYHUE creates virtual Hue bridge with the help of Hoobs.

**Plugin name**
DIYHUE is the name. Not at Hoobs ecosystem.
https://diyhue.org/
https://diyhue.readthedocs.io/en/latest/getting_started.html#host-install

**Please report the issue to the plugin developer**
The developer of DIYHUE ask me to find the log to see how this try to pair. If it use the cloud based detection we have no options. :(
More here:
https://github.com/diyhue/diyHue/discussions/607

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes

**Pervious version**
I think was 3.3.4

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
* Remove any passwords from the config file. This is public.

```
hoobs@hoobs:/home/hoobs/.hoobs/etc $ cat ~/.hoobs/etc/config.json
{
    "server": {
        "autostart": 0,
        "origin": "*",
        "polling_seconds": 5,
        "port": 80,
        "home_setup_id": "X-HM://XXXXXXXXXXXX"
    },
    "client": {
        "postal_code": "XXXXX",
        "inactive_logoff": 30,
        "temp_units": "celsius",
        "country_code": "GR",
        "locale": "en",
        "default_route": "status",
        "theme": "hoobs-light"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "XXXXXXXXXXXX",
        "pin": "XXXXXXXXXXX",
        "port": 51826
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": [],
    "package_manager": "npm",
    "system": "hoobs"
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Change the port of your diyHUE interface. HOOBS already uses port 80. You can find out how in their documentation: https://diyhue.readthedocs.io/en/latest/getting_started.html

**Comment by iANGELgr** [comment]
@askovi Hello and thank for the answer, I try to run some lines but I cant change the port :/ The hoobs dont recognise some commands
