### ISSUE TITLE
ERR_STRING_TOO_LONG

### ISSUE THREAD

**Issue by Splix123** [hoobs-org/HOOBS#1239]
**Description**
Tried to install a plugin this morning but Homebridge wouldn't do it. Searched in the log and got:
`Cannot create a string longer than 0xffffff0 characters`

Thought it was a Plugin Problem and tried other ones but failed as well.
After a bit of research that would be caused by a file larger than 256MB in the persist-folder, but checking that with ls -sh shows no file above 8KB.

**Version**
Version: 3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
I installed HOOBS on a Raspberry Pi therefore im on Raspbian/Linux

**List your plugins**
None, Since I did a factory reset

**Post your config**

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY5GNJ",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "76776"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "F3:EA:51:F7:D0:66"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}
```

**Post your log**

```
25.4.2021, 22:31:13 Got SIGINT, shutting down Bridge...
25.4.2021, 22:31:36 Initializing HAP-NodeJS v0.9.3...
25.4.2021, 22:31:42 No plugins installed.
25.4.2021, 22:31:43 Preparing Advertiser for 'HOOBS DE1F' using bonjour-hap backend!
25.4.2021, 22:31:43 Starting to advertise 'HOOBS DE1F' using bonjour-hap backend!
25.4.2021, 22:31:43 Bridge is running on port 51826.
25.4.2021, 22:33:54 Got SIGINT, shutting down Bridge...
25.4.2021, 22:34:05 Initializing HAP-NodeJS v0.9.3...
25.4.2021, 22:34:09 No plugins installed.
25.4.2021, 22:34:10 Preparing Advertiser for 'HOOBS DE1F' using bonjour-hap backend!
25.4.2021, 22:34:10 Starting to advertise 'HOOBS DE1F' using bonjour-hap backend!
25.4.2021, 22:34:10 Bridge is running on port 51826.
25.4.2021, 22:35:43 npm
25.4.2021, 22:35:43 
25.4.2021, 22:35:43 ERR! code ERR_STRING_TOO_LONG
25.4.2021, 22:35:44 npm
25.4.2021, 22:35:44  ERR! Cannot create a string longer than 0xffffff0 characters
25.4.2021, 22:35:45 
25.4.2021, 22:35:45 npm
25.4.2021, 22:35:45  ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-04-25T20_35_44_041Z-debug.log
```

**Comment by mkellsy** [comment]
A complete log of this run can be found in:
/home/hoobs/.npm/_logs/2021-04-25T20_35_44_041Z-debug.log

So run
```
cat /home/hoobs/.npm/_logs/2021-04-25T20_35_44_041Z-debug.log
```

How did you install Node? The problem is Node and NPM.

**Comment by Splix123** [comment]
Got the Log file: 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-dht'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose stack Error: Cannot create a string longer than 0xffffff0 characters
4 verbose stack     at Object.slice (buffer.js:604:37)
4 verbose stack     at Buffer.toString (buffer.js:801:14)
4 verbose stack     at Object.readFileSync (fs.js:408:41)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1034:22)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:879:32)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:903:19)
4 verbose stack     at require (internal/modules/cjs/helpers.js:74:18)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/mississippi/index.js:8:23)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:1015:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:879:32)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:903:19)
4 verbose stack     at require (internal/modules/cjs/helpers.js:74:18)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js:11:12)
5 verbose cwd /home/hoobs/.hoobs/etc
6 verbose Linux 5.4.72+
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-dht"
8 verbose node v12.19.0
9 verbose npm  v6.14.8
10 error code ERR_STRING_TOO_LONG
11 error Cannot create a string longer than 0xffffff0 characters
12 verbose exit [ 1, true ]
```

And I didn't really install Node on it's own, because the HOOBS install already had node on it, or am I wrong?

Thanks for your help really appreciate it :)

**Comment by mkellsy** [comment]
According to the NPM log your system is using node 12.19.0
When you run `node -v` what does it say.
If it is 12.19.0 run `command -v node` that will tell you the node path.

What I am concerned about is, was Node already installed on the system before you ran the install script. We may have to remove Node from 2 places and then run the install script again.

**Comment by Splix123** [comment]
Jup 12.19.0 is the right version and running `command -v node` gives me: `/usr/local/bin/node`.
I did a fresh install of HOOBS and had nothing on the sd-card before, so node should only be on the path above.

**Comment by mkellsy** [comment]
Node should be at version 14.16.1

Run this to to upgrade to the latest LTS version
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```

**Comment by Splix123** [comment]
so upgrading to the latest version did work, but now I get a different error which is:
```
npm ERR! code ENETUNREACH
npm ERR! syscall connect
npm ERR! errno ENETUNREACH
npm ERR! request to https://registry.npmjs.org/homebridge-dht failed, reason: connect ENETUNREACH 104.16.27.35:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-26T23_06_11_575Z-debug.log
```

and the debug file looks like this:
`0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   'homebridge-dht'
0 verbose cli ]
1 info using npm@7.11.1
2 info using node@v14.16.0
3 timing npm:load:whichnode Completed in 27ms
4 timing config:load:defaults Completed in 35ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 23ms
6 timing config:load:builtin Completed in 26ms
7 timing config:load:cli Completed in 58ms
8 timing config:load:env Completed in 5ms
9 timing config:load:file:/home/hoobs/.hoobs/.npmrc Completed in 3ms
10 timing config:load:project Completed in 17ms
11 timing config:load:file:/root/.npmrc Completed in 2ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 12ms
14 timing config:load:global Completed in 13ms
15 timing config:load:validate Completed in 6ms
16 timing config:load:credentials Completed in 24ms
17 timing config:load:setEnvs Completed in 20ms
18 timing config:load Completed in 210ms
19 timing npm:load:configload Completed in 213ms
20 timing npm:load:setTitle Completed in 3ms
21 timing npm:load:setupLog Completed in 34ms
22 timing npm:load:cleanupLog Completed in 47ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 5ms
25 timing npm:load Completed in 342ms
26 timing config:load:flatten Completed in 61ms
27 timing arborist:ctor Completed in 16ms
28 timing idealTree:init Completed in 182ms
29 timing idealTree:userRequests Completed in 46ms
30 silly idealTree buildDeps
31 silly fetch manifest homebridge-dht@*
32 silly placeDep ROOT homebridge-dht@ OK for:  want: *
33 timing idealTree:#root Completed in 1112ms
34 timing idealTree:node_modules/homebridge-dht Completed in 1ms
35 timing idealTree:buildDeps Completed in 1135ms
36 timing idealTree:fixDepFlags Completed in 18ms
37 timing idealTree Completed in 1404ms
38 timing command:install Completed in 1607ms
39 verbose type system
40 verbose stack FetchError: request to https://registry.npmjs.org/homebridge-dht failed, reason: connect ENETUNREACH 104.16.27.35:443
40 verbose stack     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:97:14)
40 verbose stack     at ClientRequest.emit (events.js:315:20)
40 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:469:9)
40 verbose stack     at TLSSocket.emit (events.js:327:22)
40 verbose stack     at emitErrorNT (internal/streams/destroy.js:106:8)
40 verbose stack     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
40 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
41 verbose cwd /home/hoobs/.hoobs/etc
42 verbose Linux 5.4.72+
43 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-dht"
44 verbose node v14.16.0
45 verbose npm  v7.11.1
46 error code ENETUNREACH
47 error syscall connect
48 error errno ENETUNREACH
49 error request to https://registry.npmjs.org/homebridge-dht failed, reason: connect ENETUNREACH 104.16.27.35:443
50 verbose exit 1`

**Comment by mkellsy** [comment]
NPM is complaining that it can't reach https://registry.npmjs.org/

Open this URL in your browser
```
https://registry.npmjs.org/homebridge-dht
```

Does it work? You might need to flush the DNS cache on your Pi
```
sudo systemd-resolve --flush-caches
sudo resolvectl flush-caches
```

You can verify that worked by running this. The **Current Cache Size** should be **0**.
```
sudo systemd-resolve --statistics
```

**Comment by Splix123** [comment]
Yes it works in my browser but flushing gets me:
`Failed to flush caches: Unit dbus-org.freedesktop.resolve1.service not found.`

**Comment by mkellsy** [comment]
According to the Raspberry Pi forums, a reboot should clear it. I would fully shutdown, sometimes a reboot doesn't completely clear memory. To hard reboot the pi do this.

1. Completely shutdown `sudo shutdown -h now`.
2. Wait about 10 seconds and unplug.
3. Plug back in.

**Comment by Splix123** [comment]
So I had a lot to do the past few days and I'm sorry to respond that late. I googled a bunch and tinkered around with npm.
Unfortunately I always ran into new errors which had to be resolved and strictly gave up and reinstalled HOOBS completely because my library wasn't really big nor important enough to justify the stress.

Either way I'm really thankful for the help @mkellsy and hope, that anybody with the same error can resolve it ;)
Much love
