### ISSUE TITLE
Hoobs Wifi connection impossible (first lunch for Pi Zero W)

### ISSUE THREAD

**Issue by Calexnice** [hoobs-org/HOOBS#1243]
Hello,
I installed version 3.3.3 (HOOBS-3.3.3-ARM6 for Pi Zero) on a micro SD card that I inserted in my Raspberry Pi Zero W following all the instructions in the online guide and I do not see the HOOBS WIFI on my Mac, so I cannot connect to hoobs.local

Has anyone ever had this problem? Can you help me ?

Thank you in advance.

**Comment by mkellsy** [comment]
On first boot after flashing the partition must resize. This can take some time for a pi zero. You can view this if you attach a monitor to the pi zero.

**Comment by Calexnice** [comment]
I waited 2 hours and nothing happened :(

**Comment by mkellsy** [comment]
Try a re-flash. And plug in a monitor to your Pi see if it is working

**Comment by Calexnice** [comment]
I can't plug monitor on micro-USB port of my Pi Zero W...
I reflashed many times (earlier versions also)... and the green led flashes for 2 minutes then stays on. And... nothing... no Hoobs Wifi.

**Comment by joemap40** [comment]
The RPi Zero W comes with a mini-HDMI port that you can use to connect (with an adapter) to an HDMI cable to a monitor.  Mine came with the adapter.
