### ISSUE TITLE
Hoobs box is not connecting to network 

### ISSUE THREAD

**Issue by rgj217** [hoobs-org/HOOBS#1247]
I have my hoobs box connected to my wireless router and it is not connecting to my network on my router it is not showing any light as if it is connected and it does have power.   Any one have an idea on why this might be happening. It started happening today where I couldn’t access hoobs.local.

**Comment by EddieDSuza** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)

**Comment by rgj217** [comment]
How can I factory reset the hoobs box?


Rudy Gracia
________________________________

**Comment by rgj217** [comment]
I have it connected to my router on an Ethernet port and it is not picking up the network signal.   I’ve tried it with multiple cables and same results. It had been working for a few days It stoped working today.



Rudy Gracia
________________________________

**Comment by EddieDSuza** [comment]
That error seems to indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

You can download the img file free or charge from here: https://download.hoobs.org/HOOBS-armv7.zip

**Comment by Calorion** [comment]
I seem to be in the same situation. Is there a way to access and back up the relevant files on the SD card before I reflash so I don't lose my entire setup?
