### ISSUE TITLE
Google home won’t link with homebridge

### ISSUE THREAD

**Issue by braydeni51** [hoobs-org/HOOBS#1248]
I’m trying to set up my HOOBS with my Google/Apple services, but for some reason when I try and link the service with my Google home app, it won’t let me… is there something I’m missing? I followed everything up to that point exactly like I should have

**Comment by EddieDSuza** [comment]
Check within the google home app - if the service is integrated. Try logging off the service and try again. Sometimes it does take a couple of tries for success

**Comment by braydeni51** [comment]
It’s not showing up as a linked service at all. It will say “homebridge is
linked” and right after that will say “something went wrong. Try again”
when I try and select it as a new service. I’ve tried logging out/in,
deleting the app, restarting/resetting my HOOBS device and it still doesn’t
work
