### ISSUE TITLE
Can't login to hoobs.local after power outtage

### ISSUE THREAD

**Issue by whsbb99** [hoobs-org/HOOBS#1249]
Hi fairly new to this.  I purchased the Hoobs box in December. In the past if i lose internet or power i just cycle the wifi to log back into HOOBS.  No i can no longer access hoobs.local with the following error code:

Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

I've google searched this with no luck.  Either responses that are too technical to follow or unrelated issues.  Hoping somebody can help.  Let me know what information is needed to dig deeper and i'll gladly provide.  I've been down for two weeks and my smart home is in shambles.

**Comment by whsbb99** [comment]
FYI i downloaded putty and typed "ssh hoobs@hoobs.local" under host name.  When i did that a window popped up and said "network error: software caused connection abort".

I have no training in any sort of programming other than self-teaching myself how to use basic Webcore programming for Smartthings.

**Comment by whsbb99** [comment]
to clarify further, i get this error code when i type in the ip address.  When i type in hoobs.local, chrome simply says the site can't be reached.

**Comment by EddieDSuza** [comment]
That error seems to indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

You can download the img file free or charge from here: https://download.hoobs.org/HOOBS-armv7.zip

**Comment by mkellsy** [comment]
Check to see it lost WiFi.
Use your phone and see if it is broadcasting the "HOOBS" Wifi.
If it is connect to it and enter your House WiFi info.

**Comment by whsbb99** [comment]
> That error seems to indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:
> 
> You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
> https://support.hoobs.org/docs/5e875c220ab68b0344e872ca
> 
> You can download the img file free or charge from here: https://download.hoobs.org/HOOBS-armv7.zip

Thank you but it looks like windows fixed my error.  When i plugged the SD card into the computer it fixed an error but it wiped my plugins.  I will report back if I have any further issues.  Thank you for the assistance and the instructions on how to flash the card.

**Comment by mkellsy** [comment]
Windows fixed the bad blocks, it didn't fix the lost data.

See Linux writes to a buffer, and then writes to the drive when the buffer fills.
On occasion when the power is lost, Linux doesn't get the chance to write the buffer to disk.
This can cause corruption over the entire drive, because the file allocation table points to data is supposed to be there.
Windows just fixed the link from one block to the next essentially skipping over an entire block.

There is no way to know what went wrong, a re-flash could help, but we don't know if the actual cells are bad in the SD Card.

Things like this is why battery backups exist :)
