### ISSUE TITLE
HOOBS range

### ISSUE THREAD

**Issue by simeonhoobs** [hoobs-org/HOOBS#1250]
I have accessories in the basement and also the 3rd floor. With the HOOBS bridge in the 3rd floor. How can I use HOOBS to control accessories in the basement?

**Comment by mkellsy** [comment]
HOOBS doesn't have any radios, unless you add them. It is a bridge that combines different ecosystems I to one. HOOBS doesn't have a range. If your accessories connect to SmartThings, the range would be your SmartThings hub. If your accessories are WiFi, the range is your WiFi range.
