### ISSUE TITLE
Shelly plugin

### ISSUE THREAD

**Issue by bikerboy-86** [hoobs-org/HOOBS#1251]
Hello everybody,

since I no longer need the Shelly plugin, I uninstalled it in Hoobs (raspberry pi). Unfortunately, the switches and sensors still show up in the Apple Home and Home + app. How can I delete this there?

**Comment by BobbySlope** [comment]
open hoobs.local:8181 (homebridge-shelly admin interface) and remove all shellys there and they will be deleted in Homekit

**Comment by bikerboy-86** [comment]
If I enter hoobs.local: 8181 in the browser it doesn't work.

Or am I doing something wrong?

**Comment by BobbySlope** [comment]
You probably need to reinstall the shelly plugin to access the shelly admin interface. 
Reinstall the plugin
Open hoobs.local:8181
Remove all your shelly devices
Uninstall the plugin

**Comment by bikerboy-86** [comment]
thank you very much it worked
