### ISSUE TITLE
Hoobs V4 beta

### ISSUE THREAD

**Issue by DavidBern69** [hoobs-org/HOOBS#1253]
I've installed the beta version of Hoobs to try out, only problem is when i want to access Terminal its now requesting a username and password.
I've tried with my Mozilla details and Hoobs, but can't get past that......any suggestions?

**Comment by askovi** [comment]
hoobs // hoobsadmin

The terminal now runs independently from HOOBS

**Comment by DavidBern69** [comment]
I figured it out......thank you!!!
