### ISSUE TITLE
Service is stopped

### ISSUE THREAD

**Issue by mikeB2210** [hoobs-org/HOOBS#1258]
Homebridge is not running and the service does not start. I've already tried a restart, but I always get the message that the service has stopped.

12.5.2021, 17:09:55 HOOBS listening on port 80.
12.5.2021, 17:09:56 Initializing HAP-NodeJS v0.9.3...
12.5.2021, 17:09:56 Loaded plugin 'homebridge-eveatmo'
12.5.2021, 17:09:56 [5/12/2021, 9:09:56 AM] Registering platform 'homebridge-eveatmo.eveatmo'
12.5.2021, 17:09:57 Loaded plugin 'homebridge-harmony'
12.5.2021, 17:09:57 [5/12/2021, 9:09:57 AM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
12.5.2021, 17:09:57 [5/12/2021, 9:09:57 AM] The plugin "homebridge-hue" requires a Homebridge version of ^1.3.4 which does not satisfy the current Homebridge version of 1.3.3. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
12.5.2021, 17:09:57 [5/12/2021, 9:09:57 AM] The plugin "homebridge-hue" requires Node.js version of ^14.16.1 which does not satisfy the current Node.js version of v14.16.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
12.5.2021, 17:09:58 Loaded plugin 'homebridge-hue'
12.5.2021, 17:09:58 [5/12/2021, 9:09:58 AM] Registering platform 'homebridge-hue.Hue'
12.5.2021, 17:09:58 Loaded plugin 'homebridge-wol'
12.5.2021, 17:09:58 [5/12/2021, 9:09:58 AM] Registering accessory 'homebridge-wol.NetworkDevice'
12.5.2021, 17:09:58 Loading 3 platforms...
12.5.2021, 17:09:58 [Hue] Initializing Hue platform...
12.5.2021, 17:09:58 [Hue] homebridge-hue v0.13.10, node v14.16.0, homebridge v1.3.3
12.5.2021, 17:09:58 [Hue] config.json: plugin_map: invalid key
12.5.2021, 17:09:58 [Hue] searching bridges and gateways
12.5.2021, 17:09:58 [Wohnzimmer] Initializing HarmonyHubWebSocket platform...
12.5.2021, 17:09:58 [Wohnzimmer] HarmonyPlatform Init
12.5.2021, 17:09:58 [eveatmo platform] Initializing eveatmo platform...
12.5.2021, 17:09:58 [eveatmo platform] Loading new data from API for: weatherstation
12.5.2021, 17:09:58 Loading 1 accessories...
12.5.2021, 17:09:58 [MediaNas] Initializing NetworkDevice accessory...
12.5.2021, 17:09:58 [Wohnzimmer] DidFinishLaunching
12.5.2021, 17:09:58 [Wohnzimmer] (Wohnzimmer)INFO - Loading activities...
12.5.2021, 17:09:59 [eveatmo platform] ERROR - Netatmo: Error: Authenticate error: too_many_connections
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Adding Accessory : Wohnzimmer-TV
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - configuring Main TV Service
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Creating TV Service
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - Light Manager
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - SHIELD TV
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - Spotify Musik
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - Apple TV4k
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - Fernsehen SAT
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)WARNING - No main Activity that match config file found, default to first one
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Configuring Main Activity Light Manager
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Creating TV Speaker Service
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : Light Manager
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : SHIELD TV
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : Spotify Musik
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : Apple TV4k
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : Fernsehen SAT
12.5.2021, 17:10:01 [Wohnzimmer] (Wohnzimmer)INFO - setupFoundAccessories - TV accessory added as external accessory
12.5.2021, 17:10:01 Preparing Advertiser for 'Wohnzimmer-TV D6B9' using bonjour-hap backend!
12.5.2021, 17:10:01 Starting to advertise 'Wohnzimmer-TV D6B9' using bonjour-hap backend!
12.5.2021, 17:10:01 Wohnzimmer-TV D6B9 is running on port 44479.
12.5.2021, 17:10:01 Please add [Wohnzimmer-TV D6B9] manually in Home app. Setup Code: 031-45-154
12.5.2021, 17:10:03 [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1944193080, api v1.44.0
12.5.2021, 17:10:04 [Hue] Philips hue: 4 accessories
12.5.2021, 17:10:04 Initializing platform accessory 'Philips hue'...
12.5.2021, 17:10:04 [Hue] Philips hue: 2 services
12.5.2021, 17:10:04 Initializing platform accessory 'CD LED'...
12.5.2021, 17:10:04 Initializing platform accessory 'LED Küchenfenster'...
12.5.2021, 17:10:04 Initializing platform accessory 'LED Kegel'...
12.5.2021, 17:10:26 Initializing HAP-NodeJS v0.9.3...
12.5.2021, 17:10:27 Loaded plugin 'homebridge-eveatmo'
12.5.2021, 17:10:27 [5/12/2021, 9:10:27 AM] Registering platform 'homebridge-eveatmo.eveatmo'
12.5.2021, 17:10:27 Loaded plugin 'homebridge-harmony'
12.5.2021, 17:10:27 [5/12/2021, 9:10:27 AM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
12.5.2021, 17:10:27 [5/12/2021, 9:10:27 AM] The plugin "homebridge-hue" requires a Homebridge version of ^1.3.4 which does not satisfy the current Homebridge version of 1.3.3. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
12.5.2021, 17:10:27 [5/12/2021, 9:10:27 AM] The plugin "homebridge-hue" requires Node.js version of ^14.16.1 which does not satisfy the current Node.js version of v14.16.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
12.5.2021, 17:10:28 Loaded plugin 'homebridge-hue'
12.5.2021, 17:10:28 [5/12/2021, 9:10:28 AM] Registering platform 'homebridge-hue.Hue'
12.5.2021, 17:10:28 Loaded plugin 'homebridge-wol'
12.5.2021, 17:10:28 [5/12/2021, 9:10:28 AM] Registering accessory 'homebridge-wol.NetworkDevice'
12.5.2021, 17:10:28 Loading 3 platforms...
12.5.2021, 17:10:28 [Hue] Initializing Hue platform...
12.5.2021, 17:10:28 [Hue] homebridge-hue v0.13.10, node v14.16.0, homebridge v1.3.3
12.5.2021, 17:10:28 [Hue] config.json: plugin_map: invalid key
12.5.2021, 17:10:28 [Hue] searching bridges and gateways
12.5.2021, 17:10:28 [Wohnzimmer] Initializing HarmonyHubWebSocket platform...
12.5.2021, 17:10:28 [Wohnzimmer] HarmonyPlatform Init
12.5.2021, 17:10:28 [eveatmo platform] Initializing eveatmo platform...
12.5.2021, 17:10:29 [eveatmo platform] Loading new data from API for: weatherstation
12.5.2021, 17:10:29 Loading 1 accessories...
12.5.2021, 17:10:29 [MediaNas] Initializing NetworkDevice accessory...
12.5.2021, 17:10:29 [Wohnzimmer] DidFinishLaunching
12.5.2021, 17:10:29 [Wohnzimmer] (Wohnzimmer)INFO - Loading activities...
12.5.2021, 17:10:30 [eveatmo platform] ERROR - Netatmo: Error: Authenticate error: invalid_grant
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Adding Accessory : Wohnzimmer-TV
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - configuring Main TV Service
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Creating TV Service
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - Light Manager
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - SHIELD TV
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - Spotify Musik
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - Apple TV4k
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Creating Input Service - Fernsehen SAT
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)WARNING - No main Activity that match config file found, default to first one
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Configuring Main Activity Light Manager
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Creating TV Speaker Service
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : Light Manager
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : SHIELD TV
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : Spotify Musik
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : Apple TV4k
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - Discovered Activity : Fernsehen SAT
12.5.2021, 17:10:31 [Wohnzimmer] (Wohnzimmer)INFO - setupFoundAccessories - TV accessory added as external accessory
12.5.2021, 17:10:31 Preparing Advertiser for 'Wohnzimmer-TV D6B9' using bonjour-hap backend!
12.5.2021, 17:10:31 Starting to advertise 'Wohnzimmer-TV D6B9' using bonjour-hap backend!
12.5.2021, 17:10:31 Wohnzimmer-TV D6B9 is running on port 37087.
12.5.2021, 17:10:31 Please add [Wohnzimmer-TV D6B9] manually in Home app. Setup Code: 031-45-154
12.5.2021, 17:10:31 Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:108:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
12.5.2021, 17:10:31 Got SIGTERM, shutting down Bridge...
12.5.2021, 17:10:31 [Wohnzimmer] INFO - shutdown
12.5.2021, 17:10:31 [Wohnzimmer] INFO - shutdown
12.5.2021, 17:10:33 [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1944193080, api v1.44.0
12.5.2021, 17:10:34 [Hue] Philips hue: 4 accessories
12.5.2021, 17:10:34 Initializing platform accessory 'Philips hue'...
12.5.2021, 17:10:34 [Hue] Philips hue: 2 services
12.5.2021, 17:10:34 Initializing platform accessory 'CD LED'...
12.5.2021, 17:10:34 Initializing platform accessory 'LED Küchenfenster'...
12.5.2021, 17:10:34 Initializing platform accessory 'LED Kegel'...
12.5.2021, 17:10:36 [Hue] goodbye

**Comment by EddieDSuza** [comment]
Go to help > Common Issues > Generate new username.

Click on Reboot

**Comment by tiableeker** [comment]
Also with me the bridge service stopped working after updating HOOBS to the latest version and a clean install of the latest HUE plugin. When you de-install the HUE plugin the bridge service starts again so it seems that the plugin causes the issue. I tried generating a new username without any effect.

**Comment by mikeB2210** [comment]
I also uninstalled all plugins and found that it is probably due to the Hue plugin.
I have now switched to "Homebridge" and everything is running again without any errors.

**Comment by EddieDSuza** [comment]
Please close the issue
