### ISSUE TITLE
Goons box bricked

### ISSUE THREAD

**Issue by awdpro** [hoobs-org/HOOBS#1260]
**Description**

I have been having issues with my hoobs box not working after I updated to 3.2. I have been temporarily fixing it by unplugging and plugging back in. I sat down to fix today and noticed my dashboard was blank and I couldn't type in the terminal. I did a reboot from the main screen & now I can't access the device at all even though it is showing on my Eero network. Is there a way to do a hard reset back to factory settings or any way to access it now?

**Version**
3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [y] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ y] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
To hard reset the box - you will need to reflash the card. Here are the instruction 

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

You can download the img file free or charge from here: https://download.hoobs.org/HOOBS-armv7.zip

**Comment by awdpro** [comment]
Ok.  I flashed it twice.  And now I can't even find on my network when I plug back in.  I'm starting to think it's a hardware issue.  This sucks as it is I just bought this in December!

**Comment by awdpro** [comment]
I plugged the unit into my monitor and I'm getting all these errors.
![image](https://user-images.githubusercontent.com/58316301/118215231-c9b13680-b436-11eb-9339-0341b68ca171.jpeg)

**Comment by askovi** [comment]
Please send an email to info@hoobs.org with your order number and reference this issue. You will receive a replacement microSD card.

**Comment by awdpro** [comment]
Errors start here
![image](https://user-images.githubusercontent.com/58316301/118216573-62e14c80-b439-11eb-8fe7-e79a09b371a4.jpeg)

**Comment by awdpro** [comment]
I tried another micro sd card and got a little further but now I'm getting an undervoltage warning and still can't connect to web interface.  I have unit plugged in using the power supply that came with device. ![image](https://user-images.githubusercontent.com/58316301/118221199-bf953500-b442-11eb-8888-d0a373b359af.jpeg)
