### ISSUE TITLE
Hoobs Mac App detecting Hoobs fail

### ISSUE THREAD

**Issue by joesarkis** [hoobs-org/HOOBS#1262]
**Description**
I recently received an email to test the new Mac OS Hoobs app. When I open the app and let it automatically scan, it does not find any Hoobs instances. When I manually add the IP address and the port, it says Invalid IP. I am putting the exact IP and port numbers that I use to access Hoobs using a browser.

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian GNU/Linux 10 (buster)

**List your plugins**
Nest 4.5.3 (Hoobs Certified)
Ring 9.18.1 (Hoobs Certified)
Camera FFMPEG 3.1.2 (Hoobs Certified)
Nest Cam 7.2.0 (Hoobs Certified)

**Comment by BobbySlope** [comment]
The new HOOBS Apps only detects HOOBS v4 beta devices. You wrote that you are on v 3.3.5

**Comment by joesarkis** [comment]
makes sense now. Thanks for the quick reply.
