### ISSUE TITLE
Weather Plus installation failure Hoobs 4.0 beta

### ISSUE THREAD

**Issue by tcoombs** [hoobs-org/HOOBS#1263]
I’m currently testing the 4.0 beta and all is working fine except I cannot install the Weather Plus plugin that works fine with Hoobs 3.. During the installation I get the following log messages:

Weather Plus Bridge starting
yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
warning homebridge-weather-plus > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning homebridge-weather-plus > dark-sky > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning homebridge-weather-plus > request > har-validator@5.1.5: this library is no longer supported
warning homebridge-weather-plus > geo-tz > geobuf > shapefile > text-encoding@0.6.4: no longer maintained
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...

After a few more errors saying there’s a problem with my network (believe me there’s no issue with my network) the installation fails.

Looking at the log messages it seems that there are some compatibility issues, which leads me to believe it’s a plugin issue. Does this make sense?

Please could you investigate this issue?

**Comment by tcoombs** [comment]
Mike, Thanks for re-opening the case. I tried to install again today on a different network (my neighbours) and again we were Ethernet attached. Yet again the installation failed with the "network error" message. When I installed on the same Raspberry Pi with Hoobs 3 it works fine. It only fails with Hoobs 4.0 beta. I've even tried a new installation of Hoobs 4.0 and it still fails. All other plugins work fine and there are no network issue log messages with these plugins.

Have you tried installing under the Hoobs 4.0 beta?

**Comment by EddieDSuza** [comment]
I ma using this plugin with HOOBS 4 with the below config. You do get connectivity errors when the internet is down and it does stop the bridge. Which service are you using to get the weather information and check the token values again 

```
{
            "platform": "WeatherPlus",
            "units": "ca",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "Weather",
                    "service": "openweathermap",
                    "key": "XXXXXXX",
                    "locationGeo": [
                        -XXXXXX,
                        -XXXXXX
                    ],
                    "language": "en",
                    "compatibility": "both",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": true,
                    "hidden": [
                        "Condition Category",
                        "Dew Point",
                        "Observation Station",
                        "Observation Time",
                        "Ozone",
                        "Rain Day",
                        "Rain Chance",
                        "Snow",
                        "Solar Radiation",
                        "Temperature Apparent",
                        "UV Index",
                        "Wind Speed Max"
                    ]
                }
            ]
        }
```

**Comment by tcoombs** [comment]
Eddie, thank but I'm not getting beyond the installation stage of the plugin.  The installation fails every time!  All other plugins install correctly without any error!

**Comment by mkellsy** [comment]
You can try getting this into the Yarn cache using the terminal.
Try this.

1. In the terminal navigate to your home directory
```
cd ~/
```

2. create a temp folder.
```
mkdir temp && cd temp
```

3. Using Yarn initialize a project
```
yarn init
```
> It will ask you questions, just put anything in, defaults are OK

4. Now install homebridge-weather-plus to the temp project.
```
yarn add homebridge-weather-plus
```

5. Now you can delete the temp project
```
cd ~/ && rm -fR temp
```

What this is doing is telling Yarn to install the plugin into a project, this is the same thing HOOBS 4 does. It will also cache the plugin if it installs. HOOBS 4 can use this cache too. So you either will get an error, maybe with some more information, or it will work. If it installs, try installing the plugin in HOOBS again.

**Comment by tcoombs** [comment]
I've tried your suggestion and this still fails. Here is an output from an SSH session to hoobs.local:

hoobs@hoobs:~ $ cd ~/
hoobs@hoobs:~ $ pwd
/home/hoobs
hoobs@hoobs:~ $ mkdir temp && cd temp
hoobs@hoobs:~/temp $ yarn init
yarn init v1.22.5
question name (temp): 
question version (1.0.0): 
question description: 
question entry point (index.js): 
question repository url: 
question author: 
question license (MIT): 
question private: 
success Saved package.json
Done in 7.56s.
hoobs@hoobs:~/temp $ yarn add homebridge-weather-plus
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
warning homebridge-weather-plus > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning homebridge-weather-plus > dark-sky > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning homebridge-weather-plus > request > har-validator@5.1.5: this library is no longer supported
warning homebridge-weather-plus > geo-tz > geobuf > shapefile > text-encoding@0.6.4: no longer maintained
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/googleapis/-/googleapis-73.0.0.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/hoobs/temp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
hoobs@hoobs:~/temp $ 

The interesting thing is that If I put the https url (https://registry.yarnpkg.com/googleapis/-/googleapis-73.0.0.tgz:) in the error above into my laptop browser the file downloads in just over 1 second!

I've also tried installing the SamsungTV plugin straight afterwards to see if this has any issues and it installed fine.

**Comment by mkellsy** [comment]
This might help. I made some changes to the image builder.
you can re-flash.

1. Create a backup Menu -> Hub Settings -> Backup
2. Reflash with this image https://repo.hoobs.org/image/hoobs-latest.zip
3. On setup click on Disable Logins
4. Restore Menu -> Hub Settings -> Restore -> Upload File (The restore will restore your logins)

Then try installing weather-plus again.

**Comment by tcoombs** [comment]
Sorry - Tried this and it didn't solve the problem. I've even tried installing the plugin straight after the new hoobs installation with no other plugins installed and this didn't work either.

All other plugins install perfectly.

**Comment by mkellsy** [comment]
I've sent an issue to Yarn on this. Seems like they have an issue.

**Comment by tcoombs** [comment]
Thanks Michael!

**Comment by BobbySlope** [comment]
@mkellsy This issue is still present. Can u check again?

**Comment by Willygoat1** [comment]
This fails for me as well on install.
