### ISSUE TITLE
HOOBS 3.3.5 Crashing with Homebridge-TPLink-Smarthome 6.4.0

### ISSUE THREAD

**Issue by mickelsn** [hoobs-org/HOOBS#1266]
**Description**
When activating homebridge-tplink-smarthome plugin v6.4.0, the HOOBS Bridge service will not start after the plugin attempts to initialize. This error did not occur with the previous stable version of the plugin.

**Expected behavoir**
Plugin installs and initiates successfully, HOOBS/homebridge service starts.

**Plugin name**
homebridge-tplink-smarthome

**Please report the issue to the plugin developer**
https://github.com/plasticrake/homebridge-tplink-smarthome/issues/200

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X ] Yes
- [ ] No

**Pervious version**
Believe the prior version of HOOBS installed was 3.3.3. Unclear if this problem occurred with 3.3.3 of HOOBS or not.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Using a home-etched install of a HOOBS SD image.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "[[[REMOVED]]]",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "XXXXX"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "[[[REMOVED]]]",
        "username": "[[[REMOVED]]]"
    },
    "description": "HOOBS bridge on Raspberry Pi 4.",
    "ports": {},
    "plugins": [
        "homebridge-magichome-dynamic-platform",
        "homebridge-tplink-smarthome"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "homebridge-magichome-dynamic-platform",
            "plugin_map": {
                "plugin_name": "homebridge-magichome-dynamic-platform"
            },
            "pruning": {
                "pruneMissingCachedAccessories": false,
                "restartsBeforeMissingAccessoriesPruned": 3,
                "pruneAllAccessoriesNextRestart": false
            },
            "whiteEffects": {
                "simultaniousDevicesColorWhite": true,
                "colorWhiteThreshold": 10,
                "colorWhiteThresholdSimultaniousDevices": 50,
                "colorOffThresholdSimultaniousDevices": 5
            },
            "deviceManagement": {
                "blacklistOrWhitelist": "blacklist"
            }
        },
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
5/22/2021, 11:13:24 PM Initializing HAP-NodeJS v0.9.3...
5/22/2021, 11:13:24 PM Loaded plugin 'homebridge-magichome-dynamic-platform'
5/22/2021, 11:13:24 PM [5/22/2021, 11:13:24 PM] Registering platform 'homebridge-magichome-dynamic-platform.homebridge-magichome-dynamic-platform'
5/22/2021, 11:13:25 PM Loaded plugin 'homebridge-tplink-smarthome'
5/22/2021, 11:13:25 PM [5/22/2021, 11:13:25 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
5/22/2021, 11:13:25 PM Loading 2 platforms...
5/22/2021, 11:13:25 PM [homebridge-magichome-dynamic-platform] Initializing homebridge-magichome-dynamic-platform platform...
5/22/2021, 11:13:25 PM [homebridge-magichome-dynamic-platform] Finished initializing homebridge-magichome-dynamic-platform '1.9.2'
5/22/2021, 11:13:25 PM [homebridge-magichome-dynamic-platform] If this plugin brings you joy, consider visiting GitHub and giving it a ⭐.
5/22/2021, 11:13:25 PM [TplinkSmarthome] Initializing TplinkSmarthome platform...
5/22/2021, 11:13:25 PM [TplinkSmarthome] homebridge-tplink-smarthome v6.4.0, node v12.19.0, homebridge v1.3.3, api v2.7
```

**Additional context**
It appears current version of the "HOOBS certified" TP-Link plugin requires Homebridge 1.3.3 per the log file...but since HOOBS 3.3.5 is built upon Homebridge 1.3.1, the plugin is crashing out.

When will HOOBS be updated to utilize Homebridge 1.3.3?

Also opening a feature request to add the capability to install a specific version of a Plugin because rolling back manually is impossible from the web interface, and I'm getting permission errors when attempting it from the command line per HOOBS wiki instructions despite being logged in as the `hoobs` user.

**Comment by jzuhone** [comment]
I'm having this problem too and it would be nice to get a timetable for when HOOBS will support homebridge 1.3.3.

**Comment by bwp91** [comment]
HOOBS 3.3.5 is built with Homebridge 1.3.3.

This line in your log:

```
5/22/2021, 11:13:25 PM [TplinkSmarthome] homebridge-tplink-smarthome v6.4.0, node v12.19.0, homebridge v1.3.3, api v2.7
```

is simply stating the versions you are running.

Most likely a different problem that is causing hoobs to crash?

**Comment by mickelsn** [comment]
Well, this is frankly a moot point for me personally - I transitioned over to stock Homebridge and my system has been rock-stable ever since.

And for what it's worth, the HOOBS interface is where I got the information that version 3.3.5 was based on Homebridge 1.3.1 instead of 1.3.3 - perhaps the problem lies there, somehow?

Best of luck.
