### ISSUE TITLE
Enable Web-Based Install of Specific Plugin Versions

### ISSUE THREAD

**Issue by mickelsn** [hoobs-org/HOOBS#1267]
**Is your feature request related to a problem? Please describe.**
I am experience problems with the latest version of a "HOOBS certified" plugin. As such, I want to roll back to a prior (working) version but I cannot do it from the web interface.

**Describe the solution you'd like**
I would like to be able to install an arbitrary version of any HOOBS plugin from the web interface. I suggest doing so under the Details pane of a plugin page in the web GUI.

**Describe alternatives you've considered**
I've tried installing a specific version of the non-working plugin via the command line, but I'm encountering permission errors.

**Additional context**
N/A

**Comment by mkellsy** [comment]
Done in HOOBS 4 (currently in beta)
