### ISSUE TITLE
Issue with Plugin Viessmann Control

### ISSUE THREAD

**Issue by sebastianertl** [hoobs-org/HOOBS#1268]
**Description**
I installed the Plugin Viessmann Control for my Vitoconnect, but connection with Homekit did not really work (what has to be entered at IP Address and Port etc.?).

Therefore i deinstalled the plugin.

After Deinstallation the Accessory is still visible in  Homekit and in hoobs, i am not able to delete it and it causes so issues with miy other plugins (Ring and MyQ)

**Expected behavoir**
Connect to Apple Homekit...

**Plugin name**
Viessmann Control

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.3.5.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
Failed to find plugin to handle accessory Vtoconnect Opto2

 [HOOBS 0C83@Vtoconnect Opto2@HK1@Target Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 15
```

**Additional context**

**Comment by mkellsy** [comment]
Can you post your config. Remove any username, passwords, or ip addresses.

I think you might have an issue with the config. What concerns me is the **Vtoconnect Opto2** prefix. I think it should be **Viessmann**.
