### ISSUE TITLE
Terminal not selectable

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#127]
@mkellsy Maybe you could make the terminal selectable, so you can copy text from it.

**Comment by mkellsy** [comment]
This is selectable. Here's an example.

   1 mkellsy  staff    319 Dec  2  2018 .ms_openjdk_config
drwxr-xr-x    5 mkellsy  staff    160 Aug 28 14:47 .node-gyp
-rw-------    1 mkellsy  staff     12 Aug 29 23:56 .node_repl_history
drwxr-xr-x    7 mkellsy  staff    224 Aug 28 15:55 .npm
-rw-------    1 mkellsy  staff    141 Aug 31 08:42 .npmrc
drwxr-xr-x    4 mkellsy  staff    128 Dec  4  2018 .nuget
drwxr-xr-x    2 mkellsy  staff     64 Dec  3  2018 .omnisharp
drwx------    5 mkellsy  staff    160 Aug  8 12:05 .ssh
drwxr-xr-x    6 mkellsy  staff    192 Dec  5  2018 .subversion
drwxr-xr-x    4 mkellsy  staff    128 Dec  3  2018 .templateengine
drwxr-xr-x   10 mkellsy  staff    320 Dec  2  2018 .vagrant.d
-rw-------    1 mkellsy  staff    965 Feb 28  2019 .viminfo
drwxr-xr-x    3 mkellsy  staff     96 Dec  1  2018 .vscode
drwxr-xr-x    4 mkellsy  staff    128 Jul 23 22:45 .vue-cli-ui
-rw-r--r--    1 mkellsy  staff     93 Aug 22 07:51 .vuerc
-rw-------    1 mkellsy  staff  16885 Aug 31 11:13 .zsh_history
drwxr-xr-x    4 mkellsy  staff    128 Jan 31  2019 AppData
drwx------@   6 mkellsy  staff    192 Apr  8 14:03 Applications
drwx------@   3 mkellsy  staff     96 Feb 21  2019 Applications (Parallels)
drwxrwxr-x@  34 mkellsy  staff   1088 Aug 25 19:39 Creative Cloud Files
drwx------@   6 mkellsy  staff    192 Aug 31 11:13 Desktop
drwx------@  14 mkellsy  staff    448 Aug 28 01:30 Documents
drwx------@  10 mkellsy  staff    320 Aug 30 15:43 Downloads
drwx------@  12 mkellsy  staff    384 Aug 26 10:37 Google Drive
drwxr-xr-x    2 mkellsy  staff     64 Dec  2  2018 Images
drwx------@  79 mkellsy  staff   2528 Aug 18 17:07 Library
drwx------+   6 mkellsy  staff    192 Jul  8 08:57 Movies
drwx------+   7 mkellsy  staff    224 Jul  8 08:57 Music
drwx------@   4 mkellsy  staff    128 Dec  1  2018 OneDrive
drwx------    8 mkellsy  staff    256 Aug 30 21:56 Parallels
drwx------+   8 mkellsy  staff    256 Jul  8 08:44 Pictures
drwxr-xr-x    3 mkellsy  staff     96 Jul 10 08:25 Postman
drwxr-xr-x   37 mkellsy  staff   1184 Aug 30 00:59 Projects
drwxr-xr-x+   4 mkellsy  staff    128 Dec 31  2017 Public
drwxr-xr-x    6 mkellsy  staff    192 Dec  7  2018 Sandbox
drwxr-xr-x   21 mkellsy  staff    672 Aug 15 08:41 hoobs-core
drwxr-xr-x@   6 mkellsy  staff    192 Jul 28 11:56 iCloud D

**Comment by rpolenthon** [comment]
@mkellsy On iOS it is not selectable.

**Comment by mkellsy** [comment]
I will open an issue with xterm.js. I am doing nothing special.

**Comment by rpolenthon** [comment]
I send you an video an video on slack @mkellsy
