### ISSUE TITLE
Python3.7 corrupt installation in Hoobs

### ISSUE THREAD

**Issue by github9984** [hoobs-org/HOOBS#1270]
Python3 appears to be broken within Hoobs environment. 

Possible ways to reinstall Python3?

When python3 is run in Terminal, the below errors are showing.

Fatal Python error: initfsencoding: unable to load the file system codec
ValueError: source code string cannot contain null bytes

Current thread 0x76f97ad0 (most recent call first):
Aborted

**Comment by wallacepost** [comment]
same here

**Comment by mkellsy** [comment]
The HOOBS image is based on Raspbian, you just need to run this run this;
```
sudo apt update
sudo apt install python3
```

**Comment by github9984** [comment]
Running the command results in the same error, as I believe apt get executes using python as well. So it's a viscious cycle

**Comment by wallacepost** [comment]
Any updates / solutions?

**Comment by wallacepost** [comment]
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo apt update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease
Reading package lists... Done                               
Building dependency tree       
Reading state information... Done
136 packages can be upgraded. Run 'apt list --upgradable' to see them.
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo apt install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 136 not upgraded.
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo apt install python3-picamera
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libblas3 libgfortran5 liblapack3 python3-numpy
Suggested packages:
  gfortran python-numpy-doc python3-pytest python3-numpy-dbg
  python-picamera-docs python3-rpi.gpio
The following NEW packages will be installed:
  libblas3 libgfortran5 liblapack3 python3-numpy python3-picamera
0 upgraded, 5 newly installed, 0 to remove and 136 not upgraded.
Need to get 3830 kB of archives.
After this operation, 18.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf python3-picamera armhf 1.13 [154 kB]
Get:2 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libgfortran5 armhf 8.3.0-6+rpi1 [206 kB]
Get:3 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libblas3 armhf 3.8.0-2 [103 kB]
Get:4 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf liblapack3 armhf 3.8.0-2 [1493 kB]
Get:5 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf python3-numpy armhf 1:1.16.2-1 [1873 kB]
Fetched 3830 kB in 6s (629 kB/s)                                               
Fatal Python error: initfsencoding: unable to load the file system codec
ValueError: source code string cannot contain null bytes

Current thread 0x76f54ad0 (most recent call first):
Aborted
E: Sub-process /usr/bin/apt-listchanges --apt || test $? -lt 10 returned an error code (1)
E: Failure running script /usr/bin/apt-listchanges --apt || test $? -lt 10
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo apt remove python3-picamera
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'python3-picamera' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 136 not upgraded.
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo apt purge python3-picamera
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'python3-picamera' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 136 not upgraded.
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo apt install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 136 not upgraded.
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo pip3 install unicornhat
Fatal Python error: initfsencoding: unable to load the file system codec
ValueError: source code string cannot contain null bytes

Current thread 0x76f32ad0 (most recent call first):
Aborted
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo pip3 uninstall
Fatal Python error: initfsencoding: unable to load the file system codec
ValueError: source code string cannot contain null bytes

Current thread 0x76fb3ad0 (most recent call first):
Aborted
hoobs@hoobs:/home/hoobs/.hoobs/etc $
