### ISSUE TITLE
WYZE Connected Home Op or Wyze Connected Home Plugin not showing Equipment  

### ISSUE THREAD

**Issue by bmcneil77** [hoobs-org/HOOBS#1271]
Up until recently I was able to see all of my Wyze Sense (version 1 sensors, contact, motion, plugs), however for the past week I have not seen them. I have removed everything, started from scratch.  rebooted everything.... and tried both plugin's (WCHO v0.5.3 and WCH v0.5.1) and I can not get them to show up. Is there something else anyone can think of?

**Comment by EddieDSuza** [comment]
There is an issue with the plugin with multiple reports of it not working. Heres the open [issue](https://github.com/misenhower/homebridge-wyze-connected-home/issues/37) with the developer of the plugin.
