### ISSUE TITLE
Stuck in loop

### ISSUE THREAD

**Issue by rdlink** [hoobs-org/HOOBS#1273]
Tried to join my hub to HomeKit.  Scanned the code, went through the setup, all the way up to adding it to a room.  As it was finalizing it crashed my Home app.  The Hoobs is not showing up anywhere in the Home App, but when I try to join it I am told it is already joined, and I need to reset it in order to join it again.  Help?

**Comment by askovi** [comment]
Since iOS 13 bridges show up in hubs & bridges under home settings. They no longer appear as a normal accessory. If it's already added then you should find it there. If you want to re-add it you will have to reset it from the HOOBS interface in the top right menu -> Help -> Reset Connection

**Comment by rdlink** [comment]
Thanks.  That was the issue.
