### ISSUE TITLE
Hoobs in a box errors

### ISSUE THREAD

**Issue by jeffsgithubuser** [hoobs-org/HOOBS#1277]
I am a newbie to Hoobs, linux, Rasperry Pi's etc. Have a HOOBS-in-a-box and started getting this error and don't know what it is or how to fix it? Any help?

Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

**Comment by EddieDSuza** [comment]
That error seems to indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

You can download the img file free or charge from here: https://download.hoobs.org/HOOBS-armv7.zip

**Comment by jeffsgithubuser** [comment]
Thank you. I don't have a microSD port, so will have to order one and start to learn a bit about Raspberry Pi-ing I guess. Thanks for the quick response.

**Comment by EddieDSuza** [comment]
Try reflashing the SD card prior to purchasing it and in most cases it the reflash fixes the issue.

**Comment by jeffsgithubuser** [comment]
Bought an SD card adapter, flashed the SD card (said it was flashed successfully), and now getting this: 

"This site can't be reached
Check to see if there is a typo in hoobs.local"

Next steps?

**Comment by jeffsgithubuser** [comment]
Can anyone offer any advice on next steps?

**Comment by EddieDSuza** [comment]
Did you load the .zip or .img file for reflashing. Please make sure you re-flashed the card by selecting the .zip file.

**Comment by jeffsgithubuser** [comment]
I loaded the Zip file. 
![image](https://user-images.githubusercontent.com/85425290/122274763-2c677900-cea0-11eb-8351-0aad5bf6c987.png)

BalenaEtcher then appeared to open it and said "HOOBS*3.3.3-ARM7.img"
Then flashed it and reported "Flash Complete!"

Still getting:

"This site can't be reached
Check to see if there is a typo in hoobs.local"

Any ideas?

**Comment by EddieDSuza** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)

**Comment by jeffsgithubuser** [comment]
Thanks Eddie, I very much appreciate you helping me troubleshoot this. 

 

I am not seeing it get an IP address on my network at all? 

(Not a mesh network, using a traditional Unifi WAP Network setup, but the HOOBS box has an ethernet cable plugged directly to the UDM-Pro [router/switch]).

 

I have a link light on both the HOOBS device and the Unifi UDM-Pro integrated switch. And the network controller says the port is connected, BUT the HOOBS is NOT getting an IP address or connecting to the network?

**Comment by jeffsgithubuser** [comment]
Thank you again for helping.

 

Blinking green / Steady Orange on both sides. Unifi network controller software is showing port activity. But no IP address.

 

 

I have reset the port to make sure there are no restriction (and tried it switch to other ports – same result).

 


“This site can’t be reached


Check if there is a typo in hoobs.local.

*	If spelling is correct, try running Windows Network Diagnostics <javascript:diagnoseErrors()> .

DNS_PROBE_FINISHED_NXDOMAIN

**Comment by EddieDSuza** [comment]
Jeff - can you test with another working SD card using the HOOBS image ?

**Comment by jeffsgithubuser** [comment]
I don’t have another SD card, but I guess I can buy one. What kind would I need? From: Tech With EddieSent: Friday, June 18, 2021 4:27 AMTo: hoobs-org/HOOBSCc: jeffsgithubuser; AuthorSubject: Re: [hoobs-org/HOOBS] Hoobs in a box errors (#1277) Jeff - can you test with another working SD card using the HOOBS image ?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by EddieDSuza** [comment]
together with your sales number - email info@hoobs.org and we will ship you a replacement SD card

**Comment by jeffsgithubuser** [comment]
Eddie, thank you for your help, the new card worked well, and am back on the network. Very appreciated. 

Now I have "old" /disconnected devices in my 'Home' iOS app. Can you help point me to how to reset the connection? 

Thanks again for your help! 

JS

**Comment by EddieDSuza** [comment]
Hello Jeff, 

Go to help > reset connection 

this will remove the cached accessories.

**Comment by jeffsgithubuser** [comment]
Thanks Eddie! From: Tech With EddieSent: Monday, July 5, 2021 3:34 PMTo: hoobs-org/HOOBSCc: jeffsgithubuser; AuthorSubject: Re: [hoobs-org/HOOBS] Hoobs in a box errors (#1277) Hello Jeff,Go to help > reset connectionthis will remove the cached accessories.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
