### ISSUE TITLE
Hoobs UI cannot access

### ISSUE THREAD

**Issue by dabimaster** [hoobs-org/HOOBS#1279]
Hi Hoobs Team just like to ask assistance for this issue im encoutering

Cannot access my Hoobs on the UI.
Btw im running mya hoobs on RASPB 4b
I tried restarting it nut still no success
I tried also accessomg it via terminal it seems fine and normal
Tried also to ping my hoobs ip and its pingble from a different pc in the same network but cannot access the gui interface
My hoobs os connected via LAN AND If intried to connect wirelessly cannot still access but again its ip is pingable.

Any ideas how can insolved this
See pics below![image](https://user-images.githubusercontent.com/75493111/121382510-432a3f00-c979-11eb-8c21-cb16641fcb61.jpeg)

![image](https://user-images.githubusercontent.com/75493111/121382586-563d0f00-c979-11eb-8876-f873f3a2ffed.jpeg)

![image](https://user-images.githubusercontent.com/75493111/121383294-ebd89e80-c979-11eb-8e6a-81fd2ae44141.jpeg)

**Comment by metalnodeug** [comment]
Same problem here, with Hoobs 4. I have tried sudo apt-get update & upgrade but same issues. I also have access with ssh but tried to type sudo hoobs service log said sudo:hoobs command not found.
