### ISSUE TITLE
Safari on iOS; First letter from Username login field is forced capitalized

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#128]
I tested it with Safari on iOS. The first character in the username field is every time capitalized, so I can’t login from my iPad. 

Safari on macOS is not affected.

**Comment by mkellsy** [comment]
I looked at this. This is a normal text field. There is nothing special about it. There is no restriction.

**Comment by mkellsy** [comment]
I just tested on Safari on my iPad. I am able to login without issue.

Apple does start the keyboard as shift on like it always does.

**Comment by rpolenthon** [comment]
Oh man. I used the Logitech smart folio keyboard. That’s the issue. It doesn’t allow me to stop shifting at the beginning. That’s so awful. Problem solved.

**Comment by IT-Lueg** [comment]
https://9to5mac.com/2018/11/08/customize-hardware-keyboard-settings-on-ipad/

**Comment by rpolenthon** [comment]
@IT-Lueg Thanks
