### ISSUE TITLE
Challenge installing manually a plugin

### ISSUE THREAD

**Issue by radtrentasei** [hoobs-org/HOOBS#1280]
Hey guys, sorry to bother you here.

I am struggling installing a developer version of a plugin: https://github.com/faune/homebridge-grohe-sense/tree/feature/release-1.5.1 

I am running hoobs 3.3.5

I am getting this error:

```
Error loading platform requested in your config.json at position 1
```

please check further -extended- troubleshooting done here: 
https://github.com/faune/homebridge-grohe-sense/issues/15 

Any help would be appreciated.

**Comment by bwp91** [comment]
If the dev of the plugin is willing to publish a version to npm with a beta tag then i could help you with the steps to do it this way.

**Comment by radtrentasei** [comment]
Hey, thanks you for help. I've suggested this to the dev. Are you aware on the process on how to publish this with the beta tag? Any pointer would be nice.

Coming back to the original 'problem', is there really not a way to install it manually?

**Comment by bwp91** [comment]
The most straightforward way would be to use the hoobs ui to initially install the 'current' version (hoobs will add everything it needs to to the config file) and then use a command to overwrite the plugin with the 'test' version.

I would start afresh... uninstall any plugin versions you have installed and remove entries from the hoobs config.

Then

1. use the hoobs ui to install the plugin
2. stop hoobs service
3. use these commands to update the plugin to test version (I assume the second command works?)
    ```
    cd ~/.hoobs/
    ```
    ```
    npm install https://github.com/faune/homebridge-grohe-sense.git#feature/release-1.5.1
    ```
4. start hoobs service again

**Comment by radtrentasei** [comment]
Thanks, we have managed to put it on the right track! The developer published a beta version on nmp, I've install id from the .hoobs directory with npm install XXX@beta

I am closing this

**Comment by jlg89** [comment]
What is this process under HOOBS 4, now that (for starters) the ~/.hoobs directory no longer exists?
