### ISSUE TITLE
Hoobs in a Box will not connect via Ethernet

### ISSUE THREAD

**Issue by rpbmbry** [hoobs-org/HOOBS#1281]
**Description**
Hoobs in a Box hardware will not connect to network via Ethernet; unable to access hoobs.local. Unplugged device, allowed to remain powered off for 15 minutes. Plugged in device, allowed to re-initialize for 10 minutes. Still unable to connect to Hoobs.local; Solid red light on Hoobs Box hardware.

**Version**
Please include the version of HOOBS you are using = UNKNOWN, unable to access Hoobs software UI.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
Connect the Ethernet cable first then power the device. Check visually to see a orange & blinking green light at the ethernet port.

If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)

**Comment by rpbmbry** [comment]
Thanks for the assistance. I connected the box to my main router node, ethernet first then power. Solid red light by the power port. No lights at all by the ethernet port.

**Comment by EddieDSuza** [comment]
That error seems to indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

You can download the img file free or charge from here: https://download.hoobs.org/HOOBS-armv7.zip
