### ISSUE TITLE
Hoobs in a Box will not connect via Ethernet

### ISSUE THREAD

**Issue by marcpalasciano** [hoobs-org/HOOBS#1282]
**Description**
My HOOBS in a box quit working, most likely due to a power outage corrupting SD card. I've downloaded the most current version and refreshed the SD card, I still cannot connect to HOOBS.

**Version**
HOOBS-3.3.3-ARM7

**Did you upgrade**
Please let us know if you upgraded from a previous version.
I can't remember what version I was prior to issue.

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
I'm not sure. 

**What device are you using?**
Please let us know the device you are running HOOBS on.
HOOBS Box

**If this is a custom install, what's your operating system?**
Nothing custom

**List your plugins**
Ring is my main one. But nothing works as of now, so I'm not using any plugins.

**Post your config**
I cannot connect through Terminal and SSH

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)

**Comment by marcpalasciano** [comment]
It used to work and stopped, I made no changes. I have an Ethernet hub plugged into the main mode of my mesh network.

On Jun 13, 2021, at 5:52 PM, Tech With Eddie ***@***.***> wrote:

﻿
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network.

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)

**Comment by EddieDSuza** [comment]
can you SSH into the box using the below commands

`ssh hoobs@hoobs.local `

password `hoobsadmin`

Once logged in type `sudo hoobs service log`

copy and paste the output here.
