### ISSUE TITLE
hoobs.local access gone after update

### ISSUE THREAD

**Issue by thebzknz** [hoobs-org/HOOBS#1283]
**Description**

After upgrade I can no longer access hoobs.local. I had just completed the sd card installation and had accessed hoobs.local. The first thing I did was run the update. I bought and received this card about 2 weeks ago - order #66224.

**Version**
Please include the version of HOOBS you are using. - ?

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes - YES
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version. - ?

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?** - ?
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card - New SD card order # 66224
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository. - no plug ins installed yet. 

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
hoobs@hoobs:~ $ sudo hoobs service log
Started HOOBS.
HOOBS listening on port 80.
Initializing HAP-NodeJS v0.9.2...
No plugins installed.
Preparing Advertiser for 'HOOBS 1FBB' using bonjour-hap backend!
Starting to advertise 'HOOBS 1FBB' using bonjour-hap backend!
Bridge is running on port 51826.
Got SIGINT, shutting down Bridge...
   hoobs : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/npm install -g --unsafe-perm @hoobs/hoobs
pam_unix(sudo:session): session opened for user root by (uid=0)
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
> utf-8-validate@5.0.5 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/utf-8-validate
> node-gyp-build
> @hoobs/hoobs@3.3.5 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade
    root : TTY=unknown ; PWD=/usr/local/lib/node_modules/@hoobs/hoobs ; USER=root ; COMMAND=/usr/sbin/setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
Stopping HOOBS...
[HOOBS] Stopping server.
hoobs.service: Succeeded.
Stopped HOOBS.
hoobs.service: Found left-over process 1301 (sudo) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 1302 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 1359 (sh) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 1360 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 1390 (sh) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 1391 (systemctl) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started HOOBS.
pam_unix(sudo:session): session closed for user root
HOOBS listening on port 80.
Initializing HAP-NodeJS v0.9.3...
No plugins installed.
Preparing Advertiser for 'HOOBS 1FBB' using bonjour-hap backend!
Starting to advertise 'HOOBS 1FBB' using bonjour-hap backend!
Bridge is running on port 51826.

```

**Additional context**

**Comment by EddieDSuza** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)
