### ISSUE TITLE
Can't connect to hoobs.local (ip, or any other permutations)

### ISSUE THREAD

**Issue by Isomalt1** [hoobs-org/HOOBS#1284]
Had a power outage while I was out of town and came back to hoobs no longer working. Tried a reboot and now a reflash/reinstall and still can't get anything. Hoobs.local and its assigned IP both hang and I can't connect via SSH. Up for trying anything, but I've tried everything I can find here and elsewhere and still having no luck.

I can't pull any logs because I can't get into the device. I'm on Mac OS 11.2.3 and can operate on a windows machine if needed.

**Comment by Isomalt1** [comment]
Some additional info:

- Running on hoobs in a box, newest possible version
- Reflashed using balena etcher with no errors
- Connected via ethernet (ethernet plugged in, then power via usb c)

**Comment by EddieDSuza** [comment]
When you flashed the device - did you load the .img or .zip file ?

If .img - please reflash the same SD card by loading the .zip file into the Balena Etcher app.

**Comment by Isomalt1** [comment]
Tried both and still nothing.

When I try to ssh in via terminal, it just hangs and does nothing.

**Comment by EddieDSuza** [comment]
please email info@hoobs.org with your sales number to get a replacement SD card
