### ISSUE TITLE
Hoobs stoped to be reachable - IP adress 0.0.0.0

### ISSUE THREAD

**Issue by Sobajdin** [hoobs-org/HOOBS#1285]
**Description**
Hoobs in the box stopped working. After checking support solutions tried to flash card, but unsuccessful see attachment. After buying new card and reader Hoobs is functional, but configuration is obviously lost. 

What is your warranty policy in this case, because card is dead.

**Version** newest possible version (up to date)

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box

![Flash](https://user-images.githubusercontent.com/78220488/122051678-282a5580-cde5-11eb-9070-82b4175452a0.png)

**Comment by EddieDSuza** [comment]
please reach out to info@hoobs.org together with your sales Number for warranty replacements.

**Comment by Sobajdin** [comment]
Dear all,

please find invoice in attachment regarding this topic. MicroSD card in
Hoobs in the box just died, after few months of usage, it cannot be
flashed, so it is HW problem.

Regards, Sasa Obajdin


uto, 15. lip 2021. u 14:27 Tech With Eddie ***@***.***>
napisao je:

**Comment by Sobajdin** [comment]
Hello Sasa,

Thanks for reaching out. A request has been made and we will ship you a replacement SD card.

You will receive a system, notification once the card is shipped.

Thanks,
Eddie @ hoobs.org
