### ISSUE TITLE
Can not open web interface

### ISSUE THREAD

**Issue by edwardlotz** [hoobs-org/HOOBS#1286]
when I try to access Hoobs I get the following

Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

I have tried restarting multiple times but still get this message..

**Version**
Please include the version of HOOBS you are using.

before this happened in was on the latest firmware cause it said up to date when checked\\\

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
MacOS 11.4 Big Sur. 

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Bond and Smartthings

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

when I use terminal for ssh I get no directory found

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
That error seems to indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

You can download the img file free or charge from here: https://download.hoobs.org/HOOBS-armv7.zip

**Comment by hwrite** [comment]
I have just to set up HOOBS.  I logged in and set up wifi logged into Hoobs.local,  set the bridge  up on Homekit, went to plugins, went to download ring and got endless cycling.  Now when I go to hoops.local I just get Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'.  I have only just set up so latest software.  No bridge on homesite.  I have iMac 202o with Big Sur 11.4.

**Comment by EddieDSuza** [comment]
Please email info@hoobs.org together with your sales number for a replacement SD card.

**Comment by hwrite** [comment]
Hi I’m sorry (new on Github) but probably posted in wrong thread I have HOOBS in a box starter kit sales order 52802 18  November 2020  (tried setting it up before, failed, left it and went renovating hence the time gap).

Thanks for your help

From: Tech With Eddie ***@***.***>
Reply to: hoobs-org/HOOBS ***@***.***>
Date: Thursday, 17 June 2021 at 10:11 pm
To: hoobs-org/HOOBS ***@***.***>
Cc: hwrite ***@***.***>, Comment ***@***.***>
Subject: Re: [hoobs-org/HOOBS] Can not open web interface (#1286)


Please email ***@***.******@***.***> together with your sales number for a replacement SD card.
