### ISSUE TITLE
Http;//hoobs.local

### ISSUE THREAD

**Issue by davidcentral** [hoobs-org/HOOBS#1287]
On step 4 of Hoobs in a box -Ethernet will not open . Open your browser and go to

**Comment by EddieDSuza** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)

**Comment by davidcentral** [comment]
Thanks for the response . I tried to plug into my main nod of my Google mesh network . Didn’t work I tried to plug directly into Fios router didn’t work . Can’t reach site on my Mac .hoobs local

**Comment by davidcentral** [comment]
I got it to work plugged it into a Sonos switch
