### ISSUE TITLE
Plug ins 

### ISSUE THREAD

**Issue by davidcentral** [hoobs-org/HOOBS#1288]
When I search for plug ins with common names and homebridge none are found. Wondering why? Using Hoobs Box

**Comment by EddieDSuza** [comment]
Please check the internet connection. The Box needs an active internet connection to connect with the database to download and update plugins.
if you are using a mesh network - please connect the Box to the main node.

**Comment by davidcentral** [comment]
I see the ethernet cable light is on the Hoobs Box. I would thi that would
mean it's connected. How should I check otherwise.

**Comment by EddieDSuza** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)

**Comment by davidcentral** [comment]
Looks like I had it set up correctly . When I signed back after coming hime from work the plug ins loads. Appreciated your thoughts

**Comment by EddieDSuza** [comment]
Hey David - thanks for your confirmation. You can please close the issue
