### ISSUE TITLE
install forked-Plugin

### ISSUE THREAD

**Issue by IT-Lueg** [hoobs-org/HOOBS#129]
is there a way to install forked Plugins from the UI ?

**Comment by mkellsy** [comment]
What plugin are you looking at?

**Comment by mkellsy** [comment]
Forked could mean many things.
1. In Node you can fork a process. Some plugins do this.
2. On GitHub you can fork a project.

I am assuming the latter. In this case, you need to rename the package in package.json. then publish to NPM to install from the UI.

**Comment by rpolenthon** [comment]
Michael, I think it wouldn’t be that bad if we add a option to install forked plugins from GitHub directly. This would be a good advanced feature. I think Bobby already opened an issue for a standard git integration, so it shouldn’t be a big thing to allow installations from git

**Comment by IT-Lueg** [comment]
> Forked could mean many things.
> 
> 1. In Node you can fork a process. Some plugins do this.
> 2. On GitHub you can fork a project.
> 
> I am assuming the latter. In this case, you need to rename the package in package.json. then publish to NPM to install from the UI.

Can you maybe explain to me a little more exactly how this works? 
Unfortunately I have no experience with it.

**Comment by IT-Lueg** [comment]
> option to install forked plugins from GitHub directly

this would be really nice 👌🏼

**Comment by IT-Lueg** [comment]
this one…
https://github.com/Cloudore/homebridge-broadlink-rm

But i need exactly this fork.

**Comment by IT-Lueg** [comment]
@mkellsy will there be a way to do this?
Or is this thread closed for you ?

**Comment by rpolenthon** [comment]
@IT-Lueg 

@mkellsy is on holiday until the end of this week. We will discuss it and give you an update.

**Comment by mkellsy** [comment]
There is a terminal in hoobs. You can install it this way and edit the config from the advanced config editor. I will need to write docs to do this.

**Comment by IT-Lueg** [comment]
Ohhh nice 👌🏼
I need to wait for the docs because I don‘t know how to do it with the Terminal. 

Thank you 🙏

**Comment by mkellsy** [comment]
Merged with issue https://github.com/hoobs-org/HOOBS/issues/142
