### ISSUE TITLE
Hubitat Maker Plugin Issue Persists

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/HOOBS#1291]
I'm not sure if you need to know this here or want this posted elsewhere but the Hubitat Maker api plugin has been throwing all sorts of errors lately.... I have it residing on its own bridge by itself.

6/18/2021, 1:53:27 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:53:27 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:53:34 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:53:34 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:54:38 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:54:38 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:54:51 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:54:51 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:54:54 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:54:54 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:55:02 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:55:02 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:55:14 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:55:14 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:55:20 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)6/18/2021, 1:55:20 PMHubitat Maker API BridgeError[Hubitat Maker API Bridge 132D@Alarm System

**Comment by mkellsy** [comment]
I can't tell much. There is a lack of info here.

1. What plugin is this? homebridge-hubitat? homebridge-hubitat-tonesto7? homebridge-hubitat-makerapi?
2. If this is homebridge-hubitat-makerapi, it doesn't have a config schema, do you have a config issue?

**Comment by themick4u** [comment]
Yea it’s the makerapi without the schema… this plugin has seemed to be the most responsive one I’ve used thus far. I’ll double check the config, I believe this to be a HSM issue (the alarm system arm/disarm status updates). I’d also be open to trying another plugin if you have any recommendation

**Comment by mkellsy** [comment]
homebridge-hubitat-tonesto7 seems to be the popular Hubitat plugin.
It is also certified.

**Comment by themick4u** [comment]
Ok thanks. I’ll give it a try!

**Comment by themick4u** [comment]
I gave the tonesto7 a try however am having issues with my schlage door lock and status updates, push/get via this plugin. The makerAPI worked flawless for my door lock. I am guessing I will need to bring this up on that plugin support page
