### ISSUE TITLE
Hello, I performed a node update. Unfortunately, the Hoobs web interface is no longer available. With ssh I come up with Hoobs. 

### ISSUE THREAD

**Issue by shellyman** [hoobs-org/HOOBS#1296]
**Description**

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

Error: The module '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 304.
Stopped HOOBS.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
You need to trigger a rebuild
Run this
```
sudo npm uninstall -g @hoobs/hoobs
```
Then run this
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by shellyman** [comment]
I've already tried: 
hoobs@hoobs:~ $ sudo npm uninstall -g @hoobs/hoobs
sudo: npm: command not found

**Comment by mkellsy** [comment]
Your Node install is hosed.
This might recover Node and NPM
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```

**Comment by shellyman** [comment]
hoobs@hoobs:~ $ wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
/dev/stdin: line 145: /usr/local/bin/npm: Permission denied
/dev/stdin: line 146: /usr/local/bin/npm: Permission denied

Thank You for choosing HOOBS
=============================================================================================================================================================================================================================================
Node Version 14.17.0
Updating Repositories
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u2).
git is already the newest version (1:2.20.1-2+deb10u3).
tar is already the newest version (1.30+dfsg-6).
0 upgraded, 0 newly installed, 0 to remove and 123 not upgraded.
setsebool:  SELinux is disabled.
/dev/stdin: line 145: /usr/local/bin/npm: Permission denied
/dev/stdin: line 146: /usr/local/bin/npm: Permission denied
/dev/stdin: line 456: /usr/local/bin/npm: Permission denied
/dev/stdin: line 459: /usr/local/bin/npm: Permission denied
/dev/stdin: line 464: /usr/local/bin/npm: Permission denied

Restarting HOOBS
=============================================================================================================================================================================================================================================
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/api.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
  ]
}
/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: The module '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)

**Comment by shellyman** [comment]
Unfortunately no success

**Comment by mkellsy** [comment]
Run
```
npm -v
```

See if NPM is fixed.

**Comment by shellyman** [comment]
hoobs@hoobs:~ $ npm -v
-bash: /usr/local/bin/npm: Permission denied

**Comment by shellyman** [comment]
I hope I don't have to completely reinstall hoobs

**Comment by mkellsy** [comment]
You will have to manually remove Node and NPM and reinstall.
I can give you the commands, but I need to now the architecture first.
Run
```
uname -a
```
Post the results

**Comment by shellyman** [comment]
Linux hoobs 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

**Comment by mkellsy** [comment]
First you need to remove the root locked files
```
sudo rm -fR /usr/local/bin/npm
sudo rm -fR /usr/local/bin/node
sudo rm -fR /usr/local/bin/npx
```

And just incase Node got installed in /usr/bin
```
sudo rm -fR /usr/bin/npm
sudo rm -fR /usr/bin/node
sudo rm -fR /usr/bin/npx
```

Then remove NPM
```
sudo rm -fR /usr/local/lib/node_modules/npm
```

Now download and install Node (NPM comes with Node)
```
curl -k -O https://nodejs.org/dist/v14.17.1/node-v14.17.1-linux-armv7l.tar.gz
sudo tar -xzf ./node-v14.17.1-linux-armv7l.tar.gz -C /usr/local --strip-components=1 --no-same-owner
```

Then ensure the prefix is set properly and the latest NPM is installed
```
sudo npm config set -g prefix /usr/local
sudo npm install -g npm@latest
```

Finally make sure Node an run services on ports lower then 3000
```
setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
```

Now you can reinstall HOOBS to trigger a GYP rebuild (thank Microsoft for this step :)
```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

This should get up back up. If it doesn't, you may have to re-flash. The good news is, we are really close to our 4.0 release. The new version has built-in Node management via the operating system's package manager. And we are able to upgrade Node along with our software from within the UI.

If this is the case, I can give you a link to download the 4.0 release candidate.

**Comment by shellyman** [comment]
Hi Michael,
it works, i'm glad.
Thank you for your great support.
Sunday is saved
Will version 4 come soon?

**Comment by mkellsy** [comment]
June 29th.

**Comment by shellyman** [comment]
It's my pleasure.
thank you again
