### ISSUE TITLE
HOOBS Bandwidth Usage

### ISSUE THREAD

**Issue by Emotive9** [hoobs-org/HOOBS#1299]
**Description**
HOOBS is constantly sending 10-14Mbps of traffic on ethernet. I don't have any cameras streaming.

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [] Custom Install

**List your plugins**
Big Ass Fans
Hubitat Tonesto7
myQ
Nest
Platform Wemo
Ring

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST LOG HERE

```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Installed on a Raspberry Pi 3B
![hoobs](https://user-images.githubusercontent.com/75334534/123560467-4b072300-d770-11eb-9d2a-703bb9da470e.JPG)

**Comment by mkellsy** [comment]
HOOBS it’s self doesn’t access the internet outside of viewing, installing and uninstalling plugins.

You can check your plugins to see if one of those plugins are polling the internet. An easy way is to stop the service and see if the usage goes down.

**Comment by Emotive9** [comment]
> HOOBS it’s self doesn’t access the internet outside of viewing, installing and uninstalling plugins.
> 
> You can check your plugins to see if one of those plugins are polling the internet. An easy way is to stop the service and see if the usage goes down.
> 
> I use myQ, SmartThings, Ring and FFMpeg plugins and I only see around 7 kbps. I think this if from the myQ plug-in, but I could be wrong.

I forgot to mention the screenshot I posted is from the switch port. My firewall only show about 90MB of traffic leaving the network a day which is all MyQ/Ring/Nest. Unfortunately I cannot see where the traffic is going to from HOOBS. I have also tried swapping the SD card into another Pi but it gives me the same result.

**Comment by mkellsy** [comment]
HOOBS does use websockets to communicate with browser. This is how live logs are sent to the browser app. Websockets are also used to push device updates to the accessories in the app too.

Your router may be logging this activity, as the websockets are always open if you have a browser window open to hoobs.local, even if it is not logged in.

**Comment by Emotive9** [comment]
> HOOBS does use websockets to communicate with browser. This is how live logs are sent to the browser app. Websockets are also used to push device updates to the accessories in the app.
> 
> Your router may be logging this activity, as the websockets are always open if you have a browser window open to hoobs.local, even if it is not logged in.

Makes sense, I do remember traffic being very light previously until I started messing around the web interface. Thanks!
