### ISSUE TITLE
Can't Login or Password Reset

### ISSUE THREAD

**Issue by Technojerryd** [hoobs-org/HOOBS#1302]
**Description**
Set up Hoobs Box end of last year (did not add any plugins, only connected to Homekit). Now trying to get back in to work on it really for the first time, but none of my known user/passwords work. I see the login via ssh, but my login or password reset process doesn't work either (hoobsadmin, "permission denied, please try again). I can connect with ssh 192.168.1.88, or with ssh hoops.local. I found the IP address with Homemanager iOS app.

**Expected behavior**
Can't even login and no reset password on Hoobs Server login screen. Now I am not sure why I bought the Hoobs Box because I think I will have to disassemble and flash the SD card. 

**Plugin name**
N/A

**Please report the issue to the plugin developer**
N/A

**Version**
Can't see it from the server login screen or terminal ssh.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No
- [X ] Not Sure if it did when I set it up in Dec 2020

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
Can't login to see anything

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
Below is trying to use the "hoobsadmin" or "admin" passwords
iMac-635:~ jerrytaylor$ ssh hoobs.local
jerrytaylor@hoobs.local's password: 
Permission denied, please try again.
jerrytaylor@hoobs.local's password: 
Permission denied, please try again.
jerrytaylor@hoobs.local's password: 
jerrytaylor@hoobs.local: Permission denied (publickey,password).

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
To use SSH you need to define a username
```
ssh hoobs@hoobs.local
```

Then the password is **hoobsadmin**.

**Comment by Technojerryd** [comment]
I had tried the "hoobsadmin" so many times I had lost track, b ut it worked the third time I tore logging in again via ssh. Thanks
