### ISSUE TITLE
HOOBS 3.3.5 Shutdown 

### ISSUE THREAD

**Issue by DaleNorris** [hoobs-org/HOOBS#1303]
**Description**
Hoobs keeps shutting down and bridge service not running

**Version**
Please include the version of HOOBS you are using.
3.35, 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes however it wasn't working prior to that and I was hoping an update would fix 
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Sensibo Sky 7modes
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "...",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "AU",
        "postal_code": "4120",
        "latitude": "-27.498350",
        "longitude": "153.046660"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "REDACTED",
        "username": "54:F1:FA:16:74:B0"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "SensiboSky",
            "name": "Sensibo",
            "apiKey": "REDACTED",
            "timeLapse": 5,
            "ai": false,
            "hideFan": false,
            "hideHumidity": true,
            "fixedState": "manual",
            "plugin_map": {
                "plugin_name": "homebridge-sensibo-sky-7modes"
            }
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
30/06/2021, 12:01:00 am HOOBS listening on port 8080.
30/06/2021, 12:01:03 am Initializing HAP-NodeJS v0.9.3...
30/06/2021, 12:01:05 am Loaded plugin 'homebridge-sensibo-sky-7modes'
30/06/2021, 12:01:05 am [6/29/2021, 8:01:05 AM] Registering platform 'homebridge-sensibo-sky-7modes.SensiboSky'
30/06/2021, 12:01:05 am Loading 1 platforms...
30/06/2021, 12:01:05 am [Sensibo] Initializing SensiboSky platform...
30/06/2021, 12:01:05 am [Sensibo] Fetching Sensibo devices...
30/06/2021, 12:01:07 am [Sensibo] Bedroom : AI State:  false , RefreshCycle:  5000 , fixedState, AI, hideFan : manual false false
30/06/2021, 12:01:07 am [Sensibo] KbqyfNmu Setting fan up
30/06/2021, 12:01:07 am [Sensibo] Device Added (Name: Bedroom, ID: KbqyfNmu, Group: pods)
30/06/2021, 12:01:07 am [Sensibo] Lounge : AI State:  false , RefreshCycle:  5500 , fixedState, AI, hideFan : manual false false
30/06/2021, 12:01:07 am [Sensibo] eswZBCeh Setting fan up
30/06/2021, 12:01:07 am [Sensibo] Device Added (Name: Lounge, ID: eswZBCeh, Group: pods)
30/06/2021, 12:01:07 am Initializing platform accessory 'Bedroom'...
30/06/2021, 12:01:07 am Initializing platform accessory 'Lounge'...
30/06/2021, 12:01:07 am Preparing Advertiser for 'HOOBS ABB4' using bonjour-hap backend!
30/06/2021, 12:01:07 am Starting to advertise 'HOOBS ABB4' using bonjour-hap backend!
30/06/2021, 12:01:07 am Bridge is running on port 51826.
30/06/2021, 12:01:25 am Got SIGTERM, shutting down Bridge...
30/06/2021, 10:51:18 am Initializing HAP-NodeJS v0.9.3...
30/06/2021, 10:51:20 am Loaded plugin 'homebridge-sensibo-sky-7modes'
30/06/2021, 10:51:20 am [6/29/2021, 6:51:20 PM] Registering platform 'homebridge-sensibo-sky-7modes.SensiboSky'
30/06/2021, 10:51:20 am Loading 1 platforms...
30/06/2021, 10:51:20 am [Sensibo] Initializing SensiboSky platform...
30/06/2021, 10:51:20 am [Sensibo] Fetching Sensibo devices...
30/06/2021, 10:51:21 am [Sensibo] Bedroom : AI State:  false , RefreshCycle:  5000 , fixedState, AI, hideFan : manual false false
30/06/2021, 10:51:21 am [Sensibo] KbqyfNmu Setting fan up
30/06/2021, 10:51:21 am [Sensibo] Device Added (Name: Bedroom, ID: KbqyfNmu, Group: pods)
30/06/2021, 10:51:21 am [Sensibo] Lounge : AI State:  false , RefreshCycle:  5500 , fixedState, AI, hideFan : manual false false
30/06/2021, 10:51:21 am [Sensibo] eswZBCeh Setting fan up
30/06/2021, 10:51:21 am [Sensibo] Device Added (Name: Lounge, ID: eswZBCeh, Group: pods)
30/06/2021, 10:51:21 am Initializing platform accessory 'Bedroom'...
30/06/2021, 10:51:21 am Initializing platform accessory 'Lounge'...
30/06/2021, 10:51:21 am Preparing Advertiser for 'HOOBS ABB4' using bonjour-hap backend!
30/06/2021, 10:51:22 am Starting to advertise 'HOOBS ABB4' using bonjour-hap backend!
30/06/2021, 10:51:22 am Bridge is running on port 51826.
30/06/2021, 10:51:27 am Got SIGTERM, shutting down Bridge...
30/06/2021, 10:53:01 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:53:01 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:53:01 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:53:01 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:53:03 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:53:03 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:53:03 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:53:03 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:56:09 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:56:09 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:56:09 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:56:09 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:56:12 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:56:12 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:56:12 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/06/2021, 10:56:12 am [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
```

**Additional context**

**Comment by EddieDSuza** [comment]
try rebooting the server. Click on the 3 dots > reboot

**Comment by DaleNorris** [comment]
Yeah tried that

**Comment by DaleNorris** [comment]
Still having this issue

**Comment by mkellsy** [comment]
Thanks, we released 4.0. Trying to keep this straight.

**Comment by mkellsy** [comment]
Have you upgraded to 3.3.7. It has HB 1.3.4, might help.

**Comment by DaleNorris** [comment]
Have updated, still experiencing issue

**Comment by mkellsy** [comment]
Try changing your "timeLapse" value to 30.

**Comment by DaleNorris** [comment]
Just Tried. 

nitializing HAP-NodeJS v0.9.4...
08/07/2021, 4:29:25 pm Loaded plugin 'homebridge-sensibo-sky-7modes'
08/07/2021, 4:29:25 pm [7/8/2021, 12:29:25 AM] Registering platform 'homebridge-sensibo-sky-7modes.SensiboSky'
08/07/2021, 4:29:25 pm Loading 1 platforms...
08/07/2021, 4:29:25 pm [Sensibo] Initializing SensiboSky platform...
08/07/2021, 4:29:25 pm [Sensibo] Fetching Sensibo devices...
08/07/2021, 4:29:26 pm [Sensibo] Bedroom : AI State:  false , RefreshCycle:  30000 , fixedState, AI, hideFan : manual false false
08/07/2021, 4:29:26 pm [Sensibo] KbqyfNmu Setting fan up
08/07/2021, 4:29:26 pm [Sensibo] Device Added (Name: Bedroom, ID: KbqyfNmu, Group: pods)
08/07/2021, 4:29:26 pm [Sensibo] Lounge : AI State:  false , RefreshCycle:  30500 , fixedState, AI, hideFan : manual false false
08/07/2021, 4:29:26 pm [Sensibo] eswZBCeh Setting fan up
08/07/2021, 4:29:26 pm [Sensibo] Device Added (Name: Lounge, ID: eswZBCeh, Group: pods)
08/07/2021, 4:29:26 pm Initializing platform accessory 'Bedroom'...
08/07/2021, 4:29:26 pm Initializing platform accessory 'Lounge'...
08/07/2021, 4:29:26 pm Preparing Advertiser for 'HOOBS ABB4' using bonjour-hap backend!
08/07/2021, 4:29:26 pm Starting to advertise 'HOOBS ABB4' using bonjour-hap backend!
08/07/2021, 4:29:27 pm Bridge is running on port 51826.
08/07/2021, 4:29:57 pm Got SIGTERM, shutting down Bridge...
08/07/2021, 4:31:24 pm Initializing HAP-NodeJS v0.9.4...
08/07/2021, 4:31:25 pm Loaded plugin 'homebridge-sensibo-sky-7modes'
08/07/2021, 4:31:25 pm [7/8/2021, 12:31:25 AM] Registering platform 'homebridge-sensibo-sky-7modes.SensiboSky'
08/07/2021, 4:31:25 pm Loading 1 platforms...
08/07/2021, 4:31:25 pm [Sensibo] Initializing SensiboSky platform...
08/07/2021, 4:31:25 pm [Sensibo] Fetching Sensibo devices...
08/07/2021, 4:31:27 pm [Sensibo] Bedroom : AI State:  false , RefreshCycle:  30000 , fixedState, AI, hideFan : manual false false
08/07/2021, 4:31:27 pm [Sensibo] KbqyfNmu Setting fan up
08/07/2021, 4:31:27 pm [Sensibo] Device Added (Name: Bedroom, ID: KbqyfNmu, Group: pods)
08/07/2021, 4:31:27 pm [Sensibo] Lounge : AI State:  false , RefreshCycle:  30500 , fixedState, AI, hideFan : manual false false
08/07/2021, 4:31:27 pm [Sensibo] eswZBCeh Setting fan up
08/07/2021, 4:31:27 pm [Sensibo] Device Added (Name: Lounge, ID: eswZBCeh, Group: pods)
08/07/2021, 4:31:27 pm Initializing platform accessory 'Bedroom'...
08/07/2021, 4:31:27 pm Initializing platform accessory 'Lounge'...
08/07/2021, 4:31:27 pm Preparing Advertiser for 'HOOBS ABB4' using bonjour-hap backend!
08/07/2021, 4:31:27 pm Starting to advertise 'HOOBS ABB4' using bonjour-hap backend!
08/07/2021, 4:31:27 pm Bridge is running on port 51826.
08/07/2021, 4:31:58 pm Got SIGTERM, shutting down Bridge...

**Comment by mkellsy** [comment]
I've been trying to research this, and I noticed that this plugin homebridge-sensibo-sky-7modes has had no updated since 2019. That's OK, but the issues have been disabled, so I can't report. I have tried to get the plugin dev to look at this, but there is no answer.

Something in this plugin is hard crashing, and I can't tell if anyone else is having issues. This is forked from this plugin, homebridge-sensibo-sky, which is even older and people are complaining that no one is maintaining it either. So this one is a no go.

We do have a Certified Sensibo plugin, and the dev maintains this, as well as supports both Homebridge and HOOBS.
https://plugins.hoobs.org/plugin/homebridge-sensibo-ac

You may want to consider changing to this plugin.

**Comment by DaleNorris** [comment]
Thanks I'll check it out. 
At the moment I just re-booted and when I go to hoobs.local Im getting the image as per screen shot. ? 
seems like its not wanting to make it to the login page as if the port or something had changed? 
[
![Screen Shot 2021-07-08 at 4 56 29 pm (2)](https://user-images.githubusercontent.com/86698200/124876576-8249bf80-e00d-11eb-92a4-688ceede6814.png)
](url)

**Comment by mkellsy** [comment]
Try accessing the terminal
https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

And run this command
```
sudo systemctl status hoobs
```
