### ISSUE TITLE
My phone can't find anything..!

### ISSUE THREAD

**Issue by Felbeeey** [hoobs-org/HOOBS#1304]
Hey guys! So in front of all my phone is in another vlan as de HOOBS Controller, but both vlans have full access to all other vlans.
To notice: phone (10.101.10.91) HOOBS Controller (10.101.0.230)

I've tried it several times but my "Home" app on my iphone won't find anything and when i scan the qr code on hoobs dashboard it also runs into a timeout.

Here's my config, maybe u'll see the problem... if it is due to the configuration!

`{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYY91T",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "83317"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "FA:58:6C:64:B8:68"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Zufahrt",
                    "videoConfig": {
                        "source": "-re -i rtsp://10.101.0.1:7447/5wuMCo0qincgrkD2",
                        "maxStreams": 2,
                        "maxWidth": 1024,
                        "maxHeight": 576,
                        "maxFPS": 30,
                        "mapvideo": "0:1",
                        "mapaudio": "0:0",
                        "vcodec": "h264_omx",
                        "audio": false,
                        "debug": true
                    }
                },
                {
                    "name": "Büro",
                    "videoConfig": {
                        "source": "-re -i rtsp://10.101.0.1:7447/xJ2VKOMWvD0ynuU5",
                        "maxStreams": 2,
                        "maxWidth": 1024,
                        "maxHeight": 576,
                        "maxFPS": 30,
                        "mapvideo": "0:1",
                        "mapaudio": "0:0",
                        "vcodec": "h264_omx",
                        "audio": false,
                        "debug": true
                    }
                }
            ]
        }
    ]
}`

And here's the log file, but this looks fine to me...

`30.6.2021, 17:45:06 HOOBS listening on port 80.
30.6.2021, 17:45:07 Initializing HAP-NodeJS v0.9.3...
30.6.2021, 17:45:08 Loaded plugin 'homebridge-camera-ffmpeg'
30.6.2021, 17:45:08 [6/30/2021, 9:45:08 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
30.6.2021, 17:45:08 Loading 1 platforms...
30.6.2021, 17:45:08 [Camera FFmpeg] Initializing Camera-ffmpeg platform...
30.6.2021, 17:45:08 [Camera FFmpeg] [Büro] Configuring cached bridged accessory...
30.6.2021, 17:45:08 [Camera FFmpeg] [Zufahrt] Configuring cached bridged accessory...
30.6.2021, 17:45:08 Preparing Advertiser for 'HOOBS EAEE' using bonjour-hap backend!
30.6.2021, 17:45:08 Starting to advertise 'HOOBS EAEE' using bonjour-hap backend!
30.6.2021, 17:45:08 Bridge is running on port 51826.
30.6.2021, 17:53:58 Got SIGINT, shutting down Bridge...
30.6.2021, 17:54:04 Initializing HAP-NodeJS v0.9.3...
30.6.2021, 17:54:05 Loaded plugin 'homebridge-camera-ffmpeg'
30.6.2021, 17:54:05 [6/30/2021, 9:54:05 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
30.6.2021, 17:54:05 Loading 1 platforms...
30.6.2021, 17:54:05 [Camera FFmpeg] Initializing Camera-ffmpeg platform...
30.6.2021, 17:54:05 [Camera FFmpeg] [Büro] Configuring cached bridged accessory...
30.6.2021, 17:54:05 [Camera FFmpeg] [Zufahrt] Configuring cached bridged accessory...
30.6.2021, 17:54:05 Preparing Advertiser for 'HOOBS EAEE' using bonjour-hap backend!
30.6.2021, 17:54:05 Starting to advertise 'HOOBS EAEE' using bonjour-hap backend!
30.6.2021, 17:54:05 Bridge is running on port 51826.`

**Comment by Felbeeey** [comment]
That was the error... So now i my cameras are successfully imported to HomeKit but i can't see the live view or the snapshots... Here's the log...

`30.6.2021, 19:07:51 [Camera FFmpeg] [Büro] [info]   libavutil      56. 51.100 / 56. 51.100
30.6.2021, 19:07:51 [Camera FFmpeg] [Büro] [info]   libavcodec     58. 91.100 / 58. 91.100
30.6.2021, 19:07:51 [Camera FFmpeg] [Büro] [info]   libavformat    58. 45.100 / 58. 45.100
30.6.2021, 19:07:51 [Camera FFmpeg] [Büro] [info]   libavdevice    58. 10.100 / 58. 10.100
30.6.2021, 19:07:51 [Camera FFmpeg] [Büro] [info]   libavfilter     7. 85.100 /  7. 85.100
30.6.2021, 19:07:51 [Camera FFmpeg] [Büro] [info]   libswscale      5.  7.100 /  5.  7.100
30.6.2021, 19:07:51 [Camera FFmpeg] [Büro] [info]   libswresample   3.  7.100 /  3.  7.100
30.6.2021, 19:07:51 [Camera FFmpeg] [Büro] [info]   libpostproc    55.  7.100 / 55.  7.100
30.6.2021, 19:07:51 [Camera FFmpeg] [Büro] [tcp @ 0x2e5eb80] [verbose] Starting connection attempt to 10.101.0.1 port 7447
30.6.2021, 19:08:21 [Camera FFmpeg] [Büro] Stopped video stream.
30.6.2021, 19:08:21 [Camera FFmpeg] [Büro] FFmpeg exited with code: null and signal: SIGKILL (Expected)
30.6.2021, 19:09:49 [Camera FFmpeg] [Zufahrt] Snapshot requested: 1280 x 720
30.6.2021, 19:09:54 [Zufahrt] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
30.6.2021, 19:09:54 [Camera FFmpeg] [Zufahrt] [Snapshot] [tcp @ 0x3bcf770] Connection to tcp://10.101.40.87:80 failed: Connection timed out
30.6.2021, 19:09:54 [Camera FFmpeg] [Zufahrt] [Snapshot] http://10.101.40.87/snap.jpeg: Connection timed out
30.6.2021, 19:09:54 [Camera FFmpeg] [Zufahrt] Fetching snapshot took 5.032 seconds. It is highly recommended you switch to unbridge mode.
30.6.2021, 19:09:54 [Camera FFmpeg] [Zufahrt] Failed to fetch snapshot.
30.6.2021, 19:09:54 [Camera FFmpeg] [Büro] Snapshot requested: 1280 x 720
30.6.2021, 19:09:59 [Büro] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
30.6.2021, 19:09:59 [Camera FFmpeg] [Büro] [Snapshot] [tcp @ 0x261e770] Connection to tcp://10.101.40.67:80 failed: Connection timed out
30.6.2021, 19:09:59 [Camera FFmpeg] [Büro] [Snapshot] http://10.101.40.67/snap.jpeg: Connection timed out
30.6.2021, 19:09:59 [Camera FFmpeg] [Büro] Fetching snapshot took 5.034 seconds. It is highly recommended you switch to unbridge mode.
30.6.2021, 19:09:59 [Camera FFmpeg] [Büro] Failed to fetch snapshot.
30.6.2021, 19:10:04 [Camera FFmpeg] [Zufahrt] Snapshot requested: 1280 x 720
30.6.2021, 19:10:09 [Zufahrt] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
30.6.2021, 19:10:09 [Camera FFmpeg] [Zufahrt] [Snapshot] [tcp @ 0x41a6770] Connection to tcp://10.101.40.87:80 failed: Connection timed out
30.6.2021, 19:10:09 [Camera FFmpeg] [Zufahrt] [Snapshot] http://10.101.40.87/snap.jpeg: Connection timed out
30.6.2021, 19:10:09 [Camera FFmpeg] [Zufahrt] Fetching snapshot took 5.044 seconds. It is highly recommended you switch to unbridge mode.
30.6.2021, 19:10:09 [Camera FFmpeg] [Zufahrt] Failed to fetch snapshot.
30.6.2021, 19:10:09 [Camera FFmpeg] [Büro] Snapshot requested: 1280 x 720`

**Comment by mkellsy** [comment]
You need to install ffmpeg.
