### ISSUE TITLE
Network interface select for QR-Code generation

### ISSUE THREAD

**Issue by albertovm** [hoobs-org/HOOBS#1306]
I use a Mac mini as Hoobs Server + Emoncms Server + Plex Server.
I have ethernet connected to a network A, and wifi connected to network B.
Computers in network A can see only others in network A, but computers in network B can see every computers in bot networks.

Every server works fine, except when I try to add Hoobs "Home Kit" QR-Code in to my Home Kit.
I understood that Hoobs is using only ethernet for QR-Code generation, because it is en0.
Wlan is en1, and it is not possible to modify this in OSX.

Than, the only option is to select the preferred interface/ip, like I have for Plex Server.

I found that Homebridge has the MDNS option, but it appears not to be accepted for Hoobs.
"mdns": { "interface": "192.168.1.110" }

Or an interface like Homebridge:
https://github.com/homebridge/homebridge/wiki/mDNS-Options

I believe it is missing also a place with server IP address used to generate QR-Code.

Thank you very much.

**Comment by mkellsy** [comment]
HomeKit communicates over Bonjour (mDNS). This doesn’t cross networks even if you can see the IP.

if you have an Apple TV or a HomePod you can set those up on the same network as the HOOBS or Homebridge, and it will act like a bridge using iCloud.
