### ISSUE TITLE
Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html

### ISSUE THREAD

**Issue by simonwilkes-sudo** [hoobs-org/HOOBS#1314]
**Description**
No unusual activity or changes. Then the following error was presented - Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html

I have rebooted with no success. It appears to not join my network anymore either. No way to SSH via Terminal on mac.

**Version**
Latest (assumed)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
RING

**Post your config**
Unavailable as unable to reach

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by simonwilkes-sudo** [comment]
To add, has been bullet-proof since purchase last year.

**Comment by mkellsy** [comment]
Try running
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by simonwilkes-sudo** [comment]
Thanks, mkellsy. Do I issue this command from my mac on the same network via terminal?

**Comment by mkellsy** [comment]
SSH into the device.
On a Mac, open the terminal and type this
```
ssh hoobs@hoobs.local
```
Password is: hoobsadmin

Then run that command.

**Comment by simonwilkes-sudo** [comment]
Thanks. Mkellsy. Unfortunately the Hoobs box doesn't appear to want to get onto my network to enable this command to be effective. No network lights flashing. Confirmed network cable working on another device. A red light is present on the Hoobs box each time I power cycle.

**Comment by mkellsy** [comment]
Red light is always there.

Can you get the IP address?
```
ssh hoobs@192.168.x.x
```

**Comment by simonwilkes-sudo** [comment]
Attempted via the previously known IP address which my router observed, there is no connection made. The router no longer reports the hoobs box on my network. The network up and down lights should be flashing on the hoobs box right?

**Comment by mkellsy** [comment]
Should be.
Power cycle it again.
if not see if it is broadcasting the HOOBS access point.
You can use your phone for that.

**Comment by simonwilkes-sudo** [comment]
Did the power cycle with no success. Unable to connect via SSH, not able to see on network. But good point on broadcast, I checked, but no broadcasting. I am take a hit on my current configuration and rebuild it. In this case, is there a way to reset the device to factory settings and start a fresh install? It appears we have exhausted all options?

**Comment by mkellsy** [comment]
You can open it. Pull out the SD Card and flash a new image
You can use a flash utility like the balinaEtcher https://balinaetcher.io
You can download a fresh image here

https://support.hoobs.org/downloads/image

**Comment by simonwilkes-sudo** [comment]
Ok, cheers for all your help today! :)

**Comment by simonwilkes-sudo** [comment]
As a follow up. The existing SD card appeared dead. I could not flash, it was no recognized. I had a spare SD card, flashed it and now Hoobs back online :)
