### ISSUE TITLE
Download Hoobs 4.x .zip? 

### ISSUE THREAD

**Issue by shellyman** [hoobs-org/HOOBS#1318]
Hello,
A few months ago I paid for the Hoobs version 3.6 via PayPal and downloaded it.
Now I wanted to completely reinstall my Hoobs with the new version 4.x. 
Can I download it again or do I have to buy it again?

**Comment by BobbySlope** [comment]
Here https://support.hoobs.org/downloads/image

**Comment by shellyman** [comment]
Many Thanks
