### ISSUE TITLE
HOOBS 4 Debug Mode for Homebridge

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1321]
How can I enable debug mode?
And not the bug icon that says debug log. That's not the debug mode.

**Comment by Christian-CFP** [comment]
Isn't it possible for the future update to consider a switch to enable debug mode right in HOOBS/Hub Settings?

**Comment by Christian-CFP** [comment]
> How can I enable debug mode?
> And not the bug icon that says debug log. That's not the debug mode.

Please someone? Need to take a look at the debug for the plugin LG ThinQ.

**Comment by mkellsy** [comment]
I have to modify the software to add this feature.

**Comment by mkellsy** [comment]
I added the "Enable Debugging" option to the Bridges screen.

You can now enable debugging per bridge from the UI.

![debugging](https://user-images.githubusercontent.com/9777975/124863408-3991f800-df74-11eb-92ef-8f03ca521f13.png)

**Comment by Christian-CFP** [comment]
Thank you so much thats awesome. And well implemented in the bridge itself.
Now the bug icon (debug log) makes more sense.
