### ISSUE TITLE
Unable to update to 3.3.7

### ISSUE THREAD

**Issue by tjridge** [hoobs-org/HOOBS#1322]
Ever time I attempt to update to 3.3.7 I get the following error:

7/2021, 9:11:41 AM Got SIGINT, shutting down Bridge...
7/7/2021, 9:12:19 AM npm
7/7/2021, 9:12:19 AM ERR! code ENOTEMPTY
7/7/2021, 9:12:19 AM npm ERR! syscall rename
7/7/2021, 9:12:19 AM npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
7/7/2021, 9:12:19 AM npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
7/7/2021, 9:12:19 AM npm ERR! errno -39
7/7/2021, 9:12:19 AM 
7/7/2021, 9:12:19 AM npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'
7/7/2021, 9:12:19 AM 
7/7/2021, 9:12:19 AM 
7/7/2021, 9:12:19 AM 
7/7/2021, 9:12:19 AM npm ERR! A complete log of this run can be found in:
7/7/2021, 9:12:19 AM npm ERR!     /root/.npm/_logs/2021-07-07T13_12_19_419Z-debug.log
7/7/2021, 9:12:19 AM

**Comment by bwp91** [comment]
Try running these two commands from the HOOBS or SSH terminal:

```
sudo rm -rf /usr/local/lib/node_modules/@hoobs
```

```
sudo npm install -g @hoobs/hoobs --unsafe-perm
```

**Comment by mkellsy** [comment]
This should help you out
https://support.hoobs.org/docs/60e62f336c19a6a5ca8f580f
