### ISSUE TITLE
No option to upgrade from 3.3.7 to 4

### ISSUE THREAD

**Issue by ColinScattergood** [hoobs-org/HOOBS#1323]
**Description**
I was able to update NPM and get from 3.3.6 to 3.3.7 yesterday, but nearly 24h later and I am still not getting an option to update to v4.

**Version**
3.3.7

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Previous version**
3.3.6->3.3.7

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No
- Maybe? If so it was a long time ago I honestly don't recall. I've been on HOOBS for a pretty long time.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian GNU/Linux v10

**List your plugins**
Canary v1.0.3
Camera FFMPEG v3.1.2
myQ v2.6.2
Weather Plus v3.2.6

**Post your config**

Config

{
    "server": {
        "polling_seconds": 5,
        "origin": "*",
        "home_setup_id": "X-HM://0023ISYWYA8CB",
        "port": 8080,
        "autostart": 0
    },
    "client": {
        "temp_units": "fahrenheit",
        "locale": "en",
        "theme": "hoobs-light",
        "inactive_logoff": 30,
        "default_route": "status",
        "country_code": "US",
        "postal_code": "08055",
        "latitude": "HOMELAT",
        "longitude": "HOMELONG"
    },
    "bridge": {
        "name": "HOOBS",
        "pin": "HOMEKITPIN",
        "port": 51826,
        "username": "USERNAME"
    },
    "description": "Homebridge server, managing garage doors and other light non-Homekit appliances.",
    "ports": {},
    "plugins": [
        "homebridge-camera-ffmpeg",
        "homebridge-canary",
        "homebridge-weather-plus",
        "homebridge-myq"
    ],
    "accessories": [
        {
            "name": "Canary",
            "serial": "C100K1615631",
            "password": "PASSWORD
            "model": "AllInOne",
            "username": "USERNAME",            "accessory": "Canary",
            "pollingInterval": 300
        }
    ],
    "platforms": [
        {
            "name": "Camera-FFmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "model": "WyzeCam v2",
                    "manufacturer": "Wyze",
                    "videoConfig": {
                        "maxBitrate": 299,
                        "maxFPS": 15,
                        "stillImageSource": "-i NETWORKADDRESS -vframes 1 -r 1",                        "motion": true,
                        "vcodec": "copy",
                        "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp",
                        "source": "-i NETWORKADDRESS",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "audio": true
                    },
                    "name": "Playroom"
                }
            ]
        },
        {
            "platform": "WeatherPlus",
            "plugin_map": {
                "plugin_name": "homebridge-weather-plus"
            },
            "units": "si",
            "interval": 4,
            "stations": [
                {
                    "displayName": "Medford L Jim akes",
                    "service": "openweathermap",
                    "key": "KEY",
                    "forecast": [
                        0
                    ],
                    "locationGeo": [
                        LAT,
                        LONG
                    ]
                }
            ]
        },
        {
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq"
            },
            "email": "EMAIL",
            "password": "PASSWORD",
            "name": "myQ"
        }
    ],
    "interfaces": [],
    "package_manager": "npm",
    "system": "hoobs"

**Post your log**
You can get the log from the interface. This is in the Log section.

```
No relevant log
```

**Additional context**

**Comment by mkellsy** [comment]
The migration only show if these criteria are met.
* Running on a Raspberry Pi 3B, 3B+ or 4B
* Currently running on port 80

According to your config, you are running on port 8080.

You can migrate but some things need to be checked first.
* Is NGINX installed

```
sudo systemctl status nginx
```

if it is, it must be disabled and your config needs to change to port 80.
Then you can migrate.

If you intentionally have HOOBS set to port 8080, you must migrate manually.

**Comment by ColinScattergood** [comment]
Ah man what a bonehead I am lol thank you. Literally saw the port 80 issue everywhere and in my head was like yep I'm in 80 I'm fine. Thank you!
