### ISSUE TITLE
4.0 Migration Failure on Docker Image

### ISSUE THREAD

**Issue by oliverchapple** [hoobs-org/HOOBS#1324]
got a log here trying to update to 4 v but this sudo npm install -g --unsafe-perm @hoobs/hoobs comes up with error

I did update to 3.3.7 thought.

thanks Oliver hope that helps.  here's the log.
[
[2021-07-07T12_32_06_518Z-debug.log](https://github.com/hoobs-org/HOOBS/files/6778214/2021-07-07T12_32_06_518Z-debug.log)
](url)

**Comment by oliverchapple** [comment]
tried to update it now can't access page

**Comment by mkellsy** [comment]
This should help you out
https://support.hoobs.org/docs/60e62f336c19a6a5ca8f580f

**Comment by oliverchapple** [comment]
thanks for the link I try that but keep getting changed 264 packages, and audited 265 packages in 45s

53 packages are looking for funding
  run `npm fund` for details this.

**Comment by oliverchapple** [comment]
I still getting the same error

**Comment by mkellsy** [comment]
This command installs 3.3.12 not 4.0
sudo npm install -g --unsafe-perm @hoobs/hoobs

Did you already try to migrate to 4.0?

Check to see if ~/.hoobs esists
```
ls ~/.hoobs
```

**Comment by oliverchapple** [comment]
I ran ls ~/.hoobs [
![Screenshot 2021-07-10 at 23 32 39](https://user-images.githubusercontent.com/42448591/125177868-46faec80-e1d7-11eb-86f8-3dc4ff7fbaff.png)
](url). and get that. 

but no webpage ui still

**Comment by mkellsy** [comment]
OK run this
```
sudo systemctl status hoobs
```

**Comment by oliverchapple** [comment]
Jul 10 00:05:12 oliver-desktop hoobs[1124]: Failed to find plugin to handle accessory Scenes
Jul 10 00:05:12 oliver-desktop hoobs[1124]: Failed to find plugin to handle accessory Scenes
Jul 10 00:05:12 oliver-desktop hoobs[1124]: Failed to find plugin to handle accessory Front Door
Jul 10 00:05:12 oliver-desktop hoobs[1124]: Failed to find plugin to handle accessory PlugB
Jul 10 00:05:12 oliver-desktop hoobs[1124]: Failed to find plugin to handle accessory PlugC
Jul 10 00:05:12 oliver-desktop hoobs[1124]: Failed to find plugin to handle accessory Pluga
Jul 10 00:05:12 oliver-desktop hoobs[1124]: Preparing Advertiser for 'HOOBS 22DA' using bonjour-hap b>
Jul 10 00:05:12 oliver-desktop hoobs[1124]: Starting to advertise 'HOOBS 22DA' using bonjour-hap back>
Jul 10 00:05:12 oliver-desktop hoobs[1124]: Bridge is running on port 51826.
lines 1-20/20 (END)

I got this .

**Comment by mkellsy** [comment]
Did you already try to migrate to 4.0?

**Comment by oliverchapple** [comment]
yep

**Comment by mkellsy** [comment]
OK run this
```
sudo systemctl status hoobsd
```
It's different then above.

**Comment by oliverchapple** [comment]
![Screenshot 2021-07-10 at 23 50 11](https://user-images.githubusercontent.com/42448591/125178124-a4903880-e1d9-11eb-988f-e4ea8d69b573.png) I get this

**Comment by mkellsy** [comment]
OK. Now lets check for NGINX
```
sudo systemctl status nginx
```

**Comment by oliverchapple** [comment]
![Screenshot 2021-07-10 at 23 52 09](https://user-images.githubusercontent.com/42448591/125178147-e91bd400-e1d9-11eb-9d73-abd97055f533.png). got this

**Comment by mkellsy** [comment]
I am trying to understand your setup. Please answer these questions.

1. It this a HOOBS Box, SD Card, or a Custom Setup, on a Raspberry Pi?
2. Can you post your config `cat ~/.hoobs/etc/config.json?
3. How many plugins do you have? It might be easier starting from scratch.
4. If you don have many plugins was your current config proper and working?

**Comment by oliverchapple** [comment]
my setup a Raspberry pi 4 with ubuntu with hoobs docker 
![Screenshot 2021-07-11 at 00 01 55](https://user-images.githubusercontent.com/42448591/125178281-46645500-e1db-11eb-8476-40acb6e1366b.png)  and here config file.

**Comment by oliverchapple** [comment]
also I did have plugins like tuna and Alexa before and I do make backup files of the System before

**Comment by mkellsy** [comment]
4.0 is not supported on Docker yet. Only 3.3.5.
Your best option is to re-pull the image from Docker Hub.
Docker containers are not meant to be changed, they are immutable.
Changing a container only leads to issues.

If you have your volumes setup properly you won't loose you current setup.

**Comment by mkellsy** [comment]
Anyway, you can still generate a 4.0 backup file with these commands
```
sudo npm install -g @hoobs/migration
```
Then run this
```
cd ~/ && sudo hbs-migrate -t
```
This will create the `~/migration.zip` file

You can transfer this file from you **Mac Terminal**
```
scp hoobs@hoobs.local:~/migration.zip ./~/Downloads
```

Then you can deploy your own Debian or Ubuntu VM or container and follow these instructions.
https://support.hoobs.org/docs/60e9f2ecdea381a881af7237

Once you have a fresh copy of 4.0 running, you can restore it with the migration.zip file in your Downloads folder.

**Comment by oliverchapple** [comment]
ok thanks  I will keep the 3.3.5 for now unit the docker can support 4.0 

and thanks for your help
