### ISSUE TITLE
DMG won't download

### ISSUE THREAD

**Issue by micosf** [hoobs-org/HOOBS#1325]
**Description**
Just purchased the image download and I get an "image" (html) file that is 8kb to download. I've tried Safari and Chrome. The actual .img file doesn't download.

<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="theme-color" content="#feb400"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="manifest" href="/manifest.json"><link rel="icon" href="/favicon.png"><title>HOOBS</title><link href="/css/cockpit-terminal.f16f469f.css" rel="prefetch"><link href="/css/cockpit.be0231c4.css" rel="prefetch"><link href="/css/cockpit~manage~manage-docs~manage-plugins.47c49fab.css" rel="prefetch"><link href="/css/docs.7ab5e219.css" rel="prefetch"><link href="/css/downloads.c5b7bdaa.css" rel="prefetch"><link href="/css/home.ab1c38bd.css" rel="prefetch"><link href="/css/manage-docs.0c6f93ee.css" rel="prefetch"><link href="/css/manage-plugins.438fddfb.css" rel="prefetch"><link href="/css/manage.b155dd2a.css" rel="prefetch"><link href="/js/cockpit-terminal.5cbc8410.js" rel="prefetch"><link href="/js/cockpit.09e2c46e.js" rel="prefetch"><link href="/js/cockpit~manage~manage-docs~manage-plugins.593fe918.js" rel="prefetch"><link href="/js/docs.0d741bed.js" rel="prefetch"><link href="/js/downloads.3a057834.js" rel="prefetch"><link href="/js/home.9f3feb16.js" rel="prefetch"><link href="/js/manage-docs.523a777e.js" rel="prefetch"><link href="/js/manage-plugins.e741d5d7.js" rel="prefetch"><link href="/js/manage.2d237c59.js" rel="prefetch"><link href="/js/mod.xterm-addon-attach.3781fc5c.js" rel="prefetch"><link href="/js/mod.xterm-addon-fit.bf280c14.js" rel="prefetch"><link href="/js/mod.xterm-addon-web-links.973481ea.js" rel="prefetch"><link href="/js/mod.xterm.37893035.js" rel="prefetch"><link href="/css/app.7788be16.css" rel="preload" as="style"><link href="/js/app.205d38da.js" rel="modulepreload" as="script"><link href="/js/mod.axios.4b64dd32.js" rel="modulepreload" as="script"><link href="/js/mod.barbe.0e8fcf7e.js" rel="modulepreload" as="script"><link href="/js/mod.emojer.c5b9c669.js" rel="modulepreload" as="script"><link href="/js/mod.github-api-emojis.66fb0723.js" rel="modulepreload" as="script"><link href="/js/mod.he.d4c0410a.js" rel="modulepreload" as="script"><link href="/js/mod.highlight.js.c2425832.js" rel="modulepreload" as="script"><link href="/js/mod.html-encoder-decoder.b7d4c902.js" rel="modulepreload" as="script"><link href="/js/mod.iterate-object.0db14ac9.js" rel="modulepreload" as="script"><link href="/js/mod.js-base64.ebdb98b9.js" rel="modulepreload" as="script"><link href="/js/mod.jwt-decode.426f7509.js" rel="modulepreload" as="script"><link href="/js/mod.match-all.ec2e1268.js" rel="modulepreload" as="script"><link href="/js/mod.materialize-css.10a9c094.js" rel="modulepreload" as="script"><link href="/js/mod.node-libs-browser.66148f2a.js" rel="modulepreload" as="script"><link href="/js/mod.oidc-client.581ad87d.js" rel="modulepreload" as="script"><link href="/js/mod.path-browserify.c978aa99.js" rel="modulepreload" as="script"><link href="/js/mod.querystring-es3.581b3301.js" rel="modulepreload" as="script"><link href="/js/mod.regex-emoji.85b2164b.js" rel="modulepreload" as="script"><link href="/js/mod.regex-escape.56b242dd.js" rel="modulepreload" as="script"><link href="/js/mod.showdown-highlight.b0f0fd13.js" rel="modulepreload" as="script"><link href="/js/mod.showdown.dd4220e0.js" rel="modulepreload" as="script"><link href="/js/mod.vue-loader.f66f8b99.js" rel="modulepreload" as="script"><link href="/js/mod.vue-router.04e92cac.js" rel="modulepreload" as="script"><link href="/js/mod.vue.6dc9316a.js" rel="modulepreload" as="script"><link href="/js/mod.webpack.c44bc378.js" rel="modulepreload" as="script"><link href="/js/runtime.65342c53.js" rel="modulepreload" as="script"><link href="/css/app.7788be16.css" rel="stylesheet"></head><body><div id="app"></div><script type="module" src="/js/runtime.65342c53.js"></script><script type="module" src="/js/mod.highlight.js.c2425832.js"></script><script type="module" src="/js/mod.axios.4b64dd32.js"></script><script type="module" src="/js/mod.jwt-decode.426f7509.js"></script><script type="module" src="/js/mod.querystring-es3.581b3301.js"></script><script type="module" src="/js/mod.webpack.c44bc378.js"></script><script type="module" src="/js/mod.barbe.0e8fcf7e.js"></script><script type="module" src="/js/mod.emojer.c5b9c669.js"></script><script type="module" src="/js/mod.github-api-emojis.66fb0723.js"></script><script type="module" src="/js/mod.he.d4c0410a.js"></script><script type="module" src="/js/mod.html-encoder-decoder.b7d4c902.js"></script><script type="module" src="/js/mod.iterate-object.0db14ac9.js"></script><script type="module" src="/js/mod.js-base64.ebdb98b9.js"></script><script type="module" src="/js/mod.match-all.ec2e1268.js"></script><script type="module" src="/js/mod.materialize-css.10a9c094.js"></script><script type="module" src="/js/mod.node-libs-browser.66148f2a.js"></script><script type="module" src="/js/mod.oidc-client.581ad87d.js"></script><script type="module" src="/js/mod.path-browserify.c978aa99.js"></script><script type="module" src="/js/mod.regex-emoji.85b2164b.js"></script><script type="module" src="/js/mod.regex-escape.56b242dd.js"></script><script type="module" src="/js/mod.showdown-highlight.b0f0fd13.js"></script><script type="module" src="/js/mod.showdown.dd4220e0.js"></script><script type="module" src="/js/mod.vue-loader.f66f8b99.js"></script><script type="module" src="/js/mod.vue-router.04e92cac.js"></script><script type="module" src="/js/mod.vue.6dc9316a.js"></script><script type="module" src="/js/app.205d38da.js"></script><script>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script><script src="/js/runtime-legacy.069283b8.js" nomodule></script><script src="/js/mod.highlight.js-legacy.c2425832.js" nomodule></script><script src="/js/mod.axios-legacy.4b64dd32.js" nomodule></script><script src="/js/mod.jwt-decode-legacy.426f7509.js" nomodule></script><script src="/js/mod.querystring-es3-legacy.581b3301.js" nomodule></script><script src="/js/mod.webpack-legacy.c44bc378.js" nomodule></script><script src="/js/mod.barbe-legacy.0e8fcf7e.js" nomodule></script><script src="/js/mod.emojer-legacy.c5b9c669.js" nomodule></script><script src="/js/mod.github-api-emojis-legacy.66fb0723.js" nomodule></script><script src="/js/mod.he-legacy.d4c0410a.js" nomodule></script><script src="/js/mod.html-encoder-decoder-legacy.b7d4c902.js" nomodule></script><script src="/js/mod.iterate-object-legacy.0db14ac9.js" nomodule></script><script src="/js/mod.js-base64-legacy.ebdb98b9.js" nomodule></script><script src="/js/mod.match-all-legacy.ec2e1268.js" nomodule></script><script src="/js/mod.materialize-css-legacy.10a9c094.js" nomodule></script><script src="/js/mod.node-libs-browser-legacy.66148f2a.js" nomodule></script><script src="/js/mod.oidc-client-legacy.581ad87d.js" nomodule></script><script src="/js/mod.path-browserify-legacy.c978aa99.js" nomodule></script><script src="/js/mod.regex-emoji-legacy.85b2164b.js" nomodule></script><script src="/js/mod.regex-escape-legacy.56b242dd.js" nomodule></script><script src="/js/mod.showdown-highlight-legacy.b0f0fd13.js" nomodule></script><script src="/js/mod.showdown-legacy.dd4220e0.js" nomodule></script><script src="/js/mod.vue-loader-legacy.f66f8b99.js" nomodule></script><script src="/js/mod.vue-router-legacy.04e92cac.js" nomodule></script><script src="/js/mod.vue-legacy.6dc9316a.js" nomodule></script><script src="/js/app-legacy.205d38da.js" nomodule></script></body></html>

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
I'm on a Mac trying to download the install image.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
Heres the download link:

https://support.hoobs.org/downloads/image

**Comment by micosf** [comment]
Thank you.


Cheers,
G.

Geoff Madeiros | +1.415.710.0478 | ***@***.***

**Comment by BobbySlope** [comment]
there is an issue with the download page we fixed temporarily
@mkellsy the link https://support.hoobs.org/downloads/image isnt working on woocommerce as download source.
needed to add the github release directly as download source. this was working the old way, can you make the image file for HOOBS Image downloads available the old way to the always the latest release?
