### ISSUE TITLE
Users the stuck in webui and app. Cant open config

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#1326]
**Description**
User get stuck with animated hoobs logo on webui and apps if they try to get to config screen

2screenshots attached from two different users
![image](https://user-images.githubusercontent.com/50763727/124806900-7c94a100-df5d-11eb-8f05-85583159b5dd.jpeg)
![image](https://user-images.githubusercontent.com/50763727/124806914-80282800-df5d-11eb-8d16-3b5ad5c9ab88.jpeg)

A factory reset helped one of the  to get access to the config.

**Comment by BobbySlope** [comment]
User with factory reset has now access to config screen but can not restore backup he had done before factory reset

**Comment by BobbySlope** [comment]
Thats the error he gets when he tries to restore backup 

7/7/2021, 19:59:44WARNINGunhandled rejection: Cancel

**Comment by mkellsy** [comment]
I got this fixed.
Check for Updates
