### ISSUE TITLE
Login for terminal in HOOBS 4 cycling so I can't use

### ISSUE THREAD

**Issue by jimmyfisher** [hoobs-org/HOOBS#1327]
**Description**
I just installed a fresh version of HOOBS on a new Raspberry Pi. Bought on the site and had a similar issue as another user where it downloaded an 8KB file called 'image'. I sourced HOOBS 3 from GitHub and then ran the update to migrate to HOOBS 4 (nothing was installed previously aside from my one admin user).

When I go into the Terminal tab, it gives me this prompt:

<img width="1062" alt="Screen Shot 2021-07-07 at 12 44 54 PM" src="https://user-images.githubusercontent.com/35467099/124806246-18082080-df22-11eb-8bc5-62b6f468a723.png">

I'm using the same login/password as my admin user here. The text keeps disappearing momentarily, then reappears re-prompting the login.

Can't figure out why it's not working and allowing me to get to the normal terminal command line. There's no other login I could think of using. Even tried changing my password, but same thing is happening.

**Version**
4.0.72

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.3.3 (this was the GitHub version I was able to download to do my initial boot of my Raspberry Pi 4)

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card (I created)
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
macOS Mojave 10.14.6

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
this interface path doesn't seem to exist in HOOBS 4
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
no log generated yet as i haven't done anything

```

**Additional context**

**Comment by BobbySlope** [comment]
You can login by using 
User: hoobs
Password: hoobsadmin

**Comment by jimmyfisher** [comment]
Ok great thanks. That worked. Is that permanent, or am I changing that to my own user/pass?

Also, FYI - in the desktop app at least, when I click on 'Check For Updates' next to the version number, it just sits on this indefinitely:

<img width="808" alt="Screen Shot 2021-07-07 at 1 07 15 PM" src="https://user-images.githubusercontent.com/35467099/124808211-4555ce00-df24-11eb-876f-d5459181a7c4.png">

**Comment by jimmyfisher** [comment]
Another similar issue - I can't access the Configuration page due to the same spinning loading gif going.

Installed the Ring plugin, which was fine. Clicked Configuration and it's just spinning

I should be making a new bridge per-plugin (like one for Ring, one for Magic Home, etc.) right?

**Comment by jimmyfisher** [comment]
Seems like a lot of parts of the UI end up just cycling indefinitely... not sure if this is an isolated issue or something lagging on HOOBS' side? I've rebooted as well as been able to uninstall and reinstall the Ring and Magic Home plugins on their own bridges. All that is fine. It's just getting to the config pages and various other places around the interface.

**Comment by jimmyfisher** [comment]
UPDATE #3: 

I've wiped the microSD and used the HOOBS 4 img from another recent thread (same issue I had w the link downloading the 8kb file) and things seem to be running smoothly.

I had a bridge called 'HOOBS' which I did not manually add. Must've been created from the migration from 3 to 4. 

Upon installing Ring, for instance, the configuration tab is now working and seems to be operating normally. All spinning icons are gone.

**Comment by mkellsy** [comment]
This should help you out
https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

**Comment by mkellsy** [comment]
There is an update that fixes the loading loop.
If you don't see the update go to Menu -> Hub Settings then click Clear Cache
Then Check for Updates

**Comment by jimmyfisher** [comment]
Thanks - I ended up wiping as I said since it was a new HOOBS setup (first time venturing into smart home stuff) and that seemed to fix.

But i'll check for the update nonetheless. Appreciate the info and links!
