### ISSUE TITLE
Unable to download Hoobs

### ISSUE THREAD

**Issue by cjchap** [hoobs-org/HOOBS#1329]
Hello, this is more of a storefront issue.  I cannot access my purchase history or download page to re-download a copy of my Hoobs image.  Thank you.

**Comment by askovi** [comment]
The site data is currently being migrated. Check the releases here on GitHub in this repository to download

**Comment by mkellsy** [comment]
You can download the image here
https://support.hoobs.org/downloads/image

**Comment by cjchap** [comment]
Thank you very much for the quick response!  I am downloading the new image now.
