### ISSUE TITLE
Trying to get an API token

### ISSUE THREAD

**Issue by MatsA** [hoobs-org/HOOBS#133]
Hi !

After reading the API doc I did a test with 

hoobs@hoobs:~ $ curl -X POST -d '{"username": "admin", "password": "admin"}' -H "Content-type: application/json" http://localhost/auth
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /auth</pre>
</body>
</html>

What am I doing/What is, wrong ?
V3 beta 39
/Mats

**Comment by rpolenthon** [comment]
You have to use http://hoobs.local/api/auth

**Comment by MatsA** [comment]
Thx, for quick response, it works, nice! Did test some different requests and got a "strange"  response on;

curl -X GET http://hoobs/api -H "Authorization: ey2QIn0=" 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>

No problem for me but just a heads up
/Mats

**Comment by mkellsy** [comment]
When running NGNIX the api is proxied. You will need to handle the redirect on the application. Curl doesn't by default handle redirects. You need to use -L.

curl -X GET http://hoobs/api -H -L "Authorization: ey2QIn0="

Another option is to use Postman.

**Comment by MatsA** [comment]
Thanks for the education!
