### ISSUE TITLE
HOOBS 4 not showing up as an update.

### ISSUE THREAD

**Issue by MacFlagg** [hoobs-org/HOOBS#1330]
I’m not getting the HOOBS 4 update. Yesterday, HOOBS 3.3.6 was available and I updated to that. But no HOOBS 4.

Am I missing something?

I have a HOOBS Hub box - Model | Raspberry Pi 3 Model B Rev 1.2

**Comment by magnificent3** [comment]
I'm having a similar issue. But mine is stuck on 3.3.7.
I can't even find that version on the releases.

**Comment by EddieDSuza** [comment]
try #1323 to fix the issue

**Comment by mkellsy** [comment]
The migration only shows if these criteria are met.
* Running on a Raspberry Pi 3B, 3B+ or 4B
* Currently running on port 80

According to your config, you are running on port 8080.

You can migrate but some things need to be checked first.
* Is NGINX installed

```
sudo systemctl status nginx
```

if it is, it must be disabled and your config needs to change to port 80.
Then you can migrate.

If you intentionally have HOOBS set to port 8080, you must migrate manually.

**Comment by cleanev** [comment]
I am in the same situation as @magnificent3. Stuck on 3.3.7
nginx is running - only using port 80 on RPi 3B+ 
Hoobs works perfectly with bond and ring plugins
What is the method to migrate manually as update page is not showing 4.x?

Thanks in advance

**Comment by mkellsy** [comment]
NGINX needs to be disabled.

```
sudo systemctl stop nginx
sudo systemctl disable nginx
```

After this HOOBS is most likely on port 8080
http://hoobs.local:8080

Change the server port to 80.
Then you will see the migration prompt.

**Comment by MacFlagg** [comment]
Thanks for the additional info. I was just about to ask how to disable NGINX.

**Comment by MacFlagg** [comment]
I just did the - sudo systemctl stop nginx - command in the terminal and my computer instantly lost the connection with my HOOBS hub and I now I get the message “Safari cannot open the page because it could not connect to the server.” I am locked out of my hub. 

What do I do now?

FYI I know nothing about the backend of computers eg coding, programming, terminals. I just know how to use consumer level software.

**Comment by mkellsy** [comment]
Option 1.
Go to http://hoobs.local:8080

Option 2.
SSH

If on a Mac open the Terminal and type this
```
ssh hoobs@hoobs.local
```

If on Windows download the [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab), and type this
```
ssh hoobs@hoobs
```

The password is: **hoobsadmin**

Then you can finish running the commands.

**Comment by MacFlagg** [comment]
I’ve got another issue now. 

I unplugged/plugged in the hub and was able to get back in. 

I changed the port to 80 and rebooted and now my HOOBS hub won’t boot up. 

When I go to HOOBS.local, I get a HOOBS page with progress bar and it never goes away. On my hub, the light turns red, then blinks green, then turns off. It does that over and over. It’s like it’s in a boot loop.

Going to http://hoobs.local:80/ just takes me to the HOOBS page with the progress bar.

**Comment by MacFlagg** [comment]
I can SSH in to HOOBS. But, I don’t know what to do now.

**Comment by magnificent3** [comment]
That did the trick! :) only thing is the "Wait" screen disappeared.
I figured out the migration was running and waited until the reboot, and everything woke up fine 👍

**Comment by mkellsy** [comment]
Yes the migration needs to run on boot, and needs to reboot twice. Takes about 10 - 15 minutes.

**Comment by MacFlagg** [comment]
This is all I get when I try to log into HOOBS
![16BF3130-37D2-470A-87F9-25A2DE5D2872](https://user-images.githubusercontent.com/10389407/124836880-c11a3f80-df51-11eb-9529-c8980ab8f120.png)

Here is what I’ve done.

I changed the port from 8080 to 80 and rebooted. That’s when I began getting that screen with the progress bar.

I was still able to SSH into my hub, so I ran 

sudo rm -rf /usr/local/lib/node_modules/@hoobs
sudo npm install -g @hoobs/hoobs --unsafe-perm

I then ran 

npm install -g npm

which seemed to fail. It said missing write access.

I still can’t get into my hub via safari.

any suggestions?

**Comment by mkellsy** [comment]
Run
```
sudo systemctl stop nginx
sudo systemctl disable nginx
sudo apt remove nginx
```

**Comment by MacFlagg** [comment]
That worked. Thank You!

**Comment by cleanev** [comment]
Thanks @mkellsy - your suggestion would work only on RPi’s that are totally dedicated to HOOBS. In my case I have openmediavault installed in addition to HOOBS so removing nginx would break OMV completely. I guess I will have to wait till I can get another dedicated RPi.
Appreciate your hard work in keeping this offering as current and assisting github community and others. 
Be safe in these trying times and GOD bless.
