### ISSUE TITLE
Plugins won't install on HOOBS 4

### ISSUE THREAD

**Issue by kahnartist81** [hoobs-org/HOOBS#1331]
Plugins will not install after upgrading to HOOBS 4. Even re-installs of existing plugins error out.
![Screen Shot 2021-07-07 at 3 04 48 PM](https://user-images.githubusercontent.com/33696994/124835837-d2a21e00-df36-11eb-9337-c41fdeba2675.png)
![Screen Shot 2021-07-07 at 3 04 36 PM](https://user-images.githubusercontent.com/33696994/124835845-d46be180-df36-11eb-9d6d-828c47e8b1e9.png)

**Comment by mkellsy** [comment]
Refresh the screen and try to uninstall and reinstall.

**Comment by kahnartist81** [comment]
That's not going to help, as you can see from the screenshots, hitting install actually created a new bridge and fresh install. But the plugin didn't install in the new bridge. Trying to "add a plugin" like the link on that page says, brings up the same errors.

**Comment by mkellsy** [comment]
Go to the bridges screen and remove the bridge it created and try to install again.

**Comment by kahnartist81** [comment]
Also this.
![Screen Shot 2021-07-07 at 3 41 41 PM](https://user-images.githubusercontent.com/33696994/124837555-e1d69b00-df39-11eb-9b74-6fecb32a40b3.png)

**Comment by mkellsy** [comment]
Go to the bridges screen and remove the bridge it created and try to install again.

**Comment by mkellsy** [comment]
You can reinstall plugins. Go to the Versions tab and click the download icon on the latest version. Then you can select the current bridge.

**Comment by kahnartist81** [comment]
Actually, like the screen grabs show I can't do anything with plugins. I've tried new plugins from scratch, downgrades, uninstalls. Nothing works. I'm not looking for other users to point out how to use hoobs, I'm looking for Dev help to fix it as recommended by Hoobs.

**Comment by mkellsy** [comment]
I am the dev. I tested installing the Nest plugin and it worked for me. I was thinking it was due to the npm registry having issues today. I noticed this with other modules. This is why I was having you reinstall, I was trying to rule out the network issue.

Can you post your logs so I can see what's going on. Go to the Log screen and click the Download Icon and upload to this task.

**Comment by kahnartist81** [comment]
Oh man, I'm really sorry. For some reason I thought that it would have said dev by your name. Now I just feel like an ass.

I definitely did try reinstalling the plugin, both from the GUI and terminal, but nothing was working. And then I tried a bunch of other plugins, and none of them would go.

Posting my logs here for you, don't mind the possible random extras of things i was trying.
[log.txt](https://github.com/hoobs-org/HOOBS/files/6781329/log.txt)

**Comment by kahnartist81** [comment]
I just checked again, and it looks like I was able to delete it and reinstall is from scratch. I have done that, but it's still not working. I'm uploading some screenshots and the latest log file that has nest reinstalled.
![Screen Shot 2021-07-07 at 8 58 06 PM](https://user-images.githubusercontent.com/33696994/124860627-cdf55e00-df66-11eb-9223-b66a80892745.png)
![Screen Shot 2021-07-07 at 9 00 10 PM](https://user-images.githubusercontent.com/33696994/124860631-cf268b00-df66-11eb-9c89-1eb8a5c568fc.png)
[log.txt](https://github.com/hoobs-org/HOOBS/files/6781350/log.txt)

**Comment by kahnartist81** [comment]
Also, tried installing an older version on a "fresh" bridge by itself, and that is not working either.
![Screen Shot 2021-07-07 at 9 08 15 PM](https://user-images.githubusercontent.com/33696994/124860999-8d4a1480-df67-11eb-946b-e3fe44ba71a8.png)

**Comment by mkellsy** [comment]
OK. It looks like NPM was ran inside the bridge files. 4.0 uses Yarn. Lets remove the lock files, and reinstall.

Open the terminal and run this.
```
ls -la /var/lib/hoobs/hoobs
```

I need to see which files are in this directory.

**Comment by kahnartist81** [comment]
![Screen Shot 2021-07-07 at 9 37 35 PM](https://user-images.githubusercontent.com/33696994/124863223-95a44e80-df6b-11eb-9a24-1331c570377a.png)

**Comment by mkellsy** [comment]
OK,

Run these commands.

```
cd /var/lib/hoobs/hoobs
rm -f package-lock.json
rm -f yarn-error.log
```

Then run

```
yarn install
```

After this completes, try to install the plugin again.

**Comment by kahnartist81** [comment]
![Screen Shot 2021-07-07 at 9 51 20 PM](https://user-images.githubusercontent.com/33696994/124864275-7c040680-df6d-11eb-95c6-f3911c332c4a.png)

**Comment by mkellsy** [comment]
Sorry you need root access.

Run these commands. (now with sudo)

```
cd /var/lib/hoobs/hoobs
sudo rm -f package-lock.json
sudo rm -f yarn-error.log
```

Then run

```
sudo yarn install
```

After this completes, try to install the plugin again.

**Comment by kahnartist81** [comment]
![Screen Shot 2021-07-07 at 9 53 02 PM](https://user-images.githubusercontent.com/33696994/124864433-bc638480-df6d-11eb-99e9-934edf81cbe6.png)

**Comment by mkellsy** [comment]
Can you open your browser and go to this URL https://registry.yarnpkg.com/

**Comment by kahnartist81** [comment]
{"db_name":"registry","engine":"couch_bt_engine","doc_count":2239266,"doc_del_count":334,"update_seq":6007149,"purge_seq":0,"compact_running":false,"sizes":{"active":40879178799,"external":129584903190,"file":41245835894},"disk_size":41245835894,"data_size":40879178799,"other":{"data_size":129584903190},"instance_start_time":"1625373022580150","disk_format_version":7,"committed_update_seq":6007148,"compacted_seq":6006661,"uuid":"964c127ddcbbd59982db296a0f9e8a56"}

**Comment by mkellsy** [comment]
I am stumped. The network connection in the terminal is troubling.

I'm going to have to think about this one.
NPM has had partial outages the past few days.
Yarn was affected by this too.

Our mirror at plugins.hoobs.org was affected too, but we recovered quickly.

One thing you can try is to install the problem module alone.

In that directory run this
```
cd /var/lib/hoobs/hoobs
sudo yarn install protobufjs
```

See if this completes. If not, I think you might have to wait and try again later.

If it does complete, try running yarn install again

```
cd /var/lib/hoobs/hoobs
sudo yarn install
```

**Comment by kahnartist81** [comment]
Yeah the network thing was weird for me too. I don't think it's my network, i'm on fiber 500/500. But installing just that module didn't work. I'll try these steps again in the morning.
![Screen Shot 2021-07-07 at 10 34 09 PM](https://user-images.githubusercontent.com/33696994/124867756-89bc8a80-df73-11eb-862f-160413b914e3.png)

**Comment by mkellsy** [comment]
You can try to run clear the yarn cache

```
yarn cache clean && sudo yarn cache clean
```

Then see if you can install the plugin again.

If it still doesn't install, I noticed that there was an issue with the protpbufjs module a few versions back. According to the Nest plugin version 6.10.2 is needed. So you can try to install that version before installing homebridge-nest.

```
cd /var/lib/hoobs/hoobs
sudo yarn remove homebridge-nest protobufjs
sudo yarn cache clear
sudo yarn add protobufjs@6.10.2
```

Then install homebridge-nest. You can do this from the CLI with this command.
```
sudo hbs plugin add homebridge-nest
```

This is the last trick up my sleeve. If this doesn't work, I will have to open an issue with protobufjs.

**Comment by kahnartist81** [comment]
It worked! I don't know which feature did it, either waiting some hours, or clearing the yarn cache but it is installed on it's own bridge. Now it won't let me uninstall it from the original all-in-one bridge i had, but hey, i'll take it! I cleared the settings from that one so I don't double up.

Thanks so much for your help, and sorry again for earlier!

**Comment by mkellsy** [comment]
For the all in one bridge. I think your best option is to start moving plugins off if it into their own bridge. This allows each plug-in to do its own thing. And if a plug-in crashes your entire setup isn’t down.

it does require pairing each bridge in HomeKit but the this trade off is worth it.

Yep nice you have all your plugins and configs moved you can simply delete the HOOBS bridge.

**Comment by kahnartist81** [comment]
I actually moved all my plugins to their own bridges after I posted there last message because something crashed my big bridge and reset my home app, so figured it was a good time. I think blows that everything is as it should be, it'll be smoother sailing. Thanks again!

**Comment by mkstretch** [comment]
Ok so I had this exact same problem and after I ran the clear yarn cache I was able to install the nest plugin no problem.
