### ISSUE TITLE
No Homekit QR Code

### ISSUE THREAD

**Issue by michaelromero2020** [hoobs-org/HOOBS#1332]
**Description**
Every YouTube explainer shows a QR code for Homekit on your dashboard after installation. I don't have that. 

**Version**
4.0.73 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [√ ] Yes

**Previous version**
Whatever came right out of the box. I received the kit today. 

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
No Idea

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [√ ] HOOBS Box

**Post your config**
I'm not sure if my version is just different but I can't find this either. 

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
With Version 4 - you have to create a new bridge and scan the QR code for it. 

to do that.- you can follow this guide https://support.hoobs.org/docs/60e0c685646faaa152f10dd8

**Comment by michaelromero2020** [comment]
Thanks Eddie! After that is that how I add accessories to HomeKit? Creates bridges for my devices (light switches, thermostats, etc?)

**Comment by EddieDSuza** [comment]
Yes create bridges for every plugin. So if any plugin fails (Bridge) your other bridges (plugins) are still responsive in HomeKit

**Comment by michaelromero2020** [comment]
Thanks again! So I'll create bridges and then add plugins to those corresponding bridges?

Sorry for the million questions. Just getting started.

**Comment by EddieDSuza** [comment]
Hey Michael - when you install a plugin - the system will prompt you I want to create a new bridge with or add the plugin to an existing one. 

Try adding a plugin and you'l that system prompt. Once the plugin is setup - go tot the 4th icon on the left and scan the QR of the bridge where the plug-in has been added to.

**Comment by michaelromero2020** [comment]
Okay -- I was able to add my garage. I'll keep trying the others and see if I can figure it out. Do you happen to know if Config UI X is still available? The Simplisafe plugin is asking for that to be installed but I can't find it in the plugin library.

**Comment by mkellsy** [comment]
You don’t need ui-x just go the the config screen in HOOBS (the gear icon on the bottom left)

**Comment by michaelromero2020** [comment]
@mkellsy I've filled out the login information, scanned the QR code, and added to homekit but nothing appears. Having this same issue with Kasa (TP-LINK) which also calls for Homebridge Config UI X. Apologies if I'm missing something super obvious.

**Comment by michaelromero2020** [comment]
@mkellsy I figured it out. For anyone reading this, make sure you check the logs every time you're running into an issue. That might seem obvious to some but it wasn't to me. The log was asking me to approve authentication and now it's up and running.
