### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by isinned** [hoobs-org/HOOBS#1333]
just got a new hoobs box came with 3x5 I think I updated to 337??? then saw 4.0 was available 337 was fine but 4.0 it never booted I ssh into the hoobs but not sure what I am doing... nothing is set up I am just trying to restore to a working hoobs I would of thought getting it in the mail today it would have the latest on it... my bad

not sure what I did but I tried to bring it back to 3.3.7

Hoobs

Last login: Wed Jul  7 20:32:18 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Denniss-MacBook-Pro:~ dpluym$ ssh hoobs@hoobs.local
The authenticity of host 'hoobs.local (192.168.7.184)' can't be established.
ECDSA key fingerprint is SHA256:OugA9hFUAI/TN/KMWxkfRYxQirVoTTWuN0RpcfqKW2Y.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'hoobs.local,192.168.7.184' (ECDSA) to the list of known hosts.
hoobs@hoobs.local's password: 
Linux hoobs 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l
Raspberry Pi 3 Model B Plus Rev 1.3

*** HOOBS - User Friendly Home Automation for Everyone ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs
* http://hoobs.local
* http://192.168.7.184

HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
hoobs@hoobs:~ $ sudo rm -fR /usr/local/lib/node_modules/@hoobs
hoobs@hoobs:~ $ sudo npm install -g --unsafe-perm @hoobs/hoobs
/usr/bin/hoobs -> /usr/lib/node_modules/@hoobs/hoobs/bin/hoobs

> bufferutil@4.0.3 install /usr/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil
> node-gyp-build

> node-pty@0.9.0 install /usr/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
> node scripts/install.js

make: Entering directory '/usr/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function ‘void pty_after_waitpid(uv_async_t*)’:
../src/unix/pty.cc:486:43: warning: ‘void* memset(void*, int, size_t)’ writing to an object of type ‘class Nan::Persistent<v8::Function>’ with no trivial copy-assignment [-Wclass-memaccess]
   memset(&baton->cb, -1, sizeof(baton->cb));
                                           ^
In file included from ../../nan/nan.h:405,
                 from ../src/unix/pty.cc:20:
../../nan/nan_persistent_12_inl.h:12:40: note: ‘class Nan::Persistent<v8::Function>’ declared here
 template<typename T, typename M> class Persistent :
                                        ^~~~~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
../src/unix/pty.cc: At global scope:
/root/.cache/node-gyp/14.17.2/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.cache/node-gyp/14.17.2/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/unix/pty.cc:708:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(pty, init)
 ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory '/usr/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'

> utf-8-validate@5.0.5 install /usr/lib/node_modules/@hoobs/hoobs/node_modules/utf-8-validate
> node-gyp-build

> node-pty@0.9.0 postinstall /usr/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
> node scripts/post-install.js

> @hoobs/hoobs@3.3.7 postinstall /usr/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

+ @hoobs/hoobs@3.3.7
added 261 packages from 221 contributors in 97.423s
hoobs@hoobs:~ $ sudo shutdown -r now
Connection to hoobs.local closed by remote host.
Connection to hoobs.local closed.
Denniss-MacBook-Pro:~ dpluym$

**Comment by mkellsy** [comment]
This should help you
https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

**Comment by isinned** [comment]
Actually I went through that but it does not seem to boot up I can ssh into the box but it doesn’t fully boot it appears the new 4.0 software is on there something is keeping it from running.  Also I seem to get a couple errors when I reset the node and since I didn’t understand it at all I just kept going like I said I just got the box yesterday and updated to the 37 and then the 40 the only thing I did was sign up for an admin account on it there are no other settings.  Curious do you guys have phone support for your hoobs boxes or remote support.

**Comment by EddieDSuza** [comment]
contact info@hoobs.org for remote support
