### ISSUE TITLE
My Hoobs is Broken...?

### ISSUE THREAD

**Issue by jamaalmck** [hoobs-org/HOOBS#1334]
**Description**

I upgraded from 3.24 I believe. Currently on 4.0.73. Upon install it crashed, initially. Figured I would just factory reset as I only use it for one plugin (Vivint). Upon the factory reset, all is well, set up admin + Password, etc. Log is nothing but 
" 7/8/2021, 1:18:28 AMWARNINGunhandled rejection: Cancel
7/8/2021, 1:18:28 AMWARNINGunhandled rejection: Cancel
7/8/2021, 1:18:28 AMWARNINGunhandled rejection: Cancel
7/8/2021, 1:18:28 AMWARNINGunhandled rejection: Cancel
7/8/2021, 1:18:28 AMWARNINGunhandled rejection: Cancel

Upon attempting to instal the vivint plugin there is nowhere to input config for sign in info, and json is basically empty. 
Not sure what to do here. 

**Version**
Please include the version of HOOBS you are using.

4.0.73

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

3.24

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

None currently but I only use it for VIVINT 

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
[log-4.txt](https://github.com/hoobs-org/HOOBS/files/6781752/log-4.txt)

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
![Screen Shot 2021-07-08 at 1 29 22 AM](https://user-images.githubusercontent.com/79069283/124867363-f80d4700-df8b-11eb-800c-41a9b2418db9.png)

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

On previous versions of HOOBS the config .json was more populated. Hoobs 4.xx seems to implement a few different things so if there's a way to downgrade back, that'd be great, too. 

Apologies for the NOOB questions. I'm extremely new to this.

**Comment by mkellsy** [comment]
This should help you
https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

**Comment by jamaalmck** [comment]
> This should help you
> https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

Thanks so much for your response : now my issue is that my HOOBS device has a blinking red light, every few seconds Eternet (Yellow and Green) are blinking in the back. I've tried to unplug for some time and restart, still nothing. I did the "sudo hbs system reset" and that got me to a solid red light. 

When I try to access Hoobs.local i'm greeted with this: 
![Screen Shot 2021-07-09 at 12 49 40 AM](https://user-images.githubusercontent.com/79069283/125024952-bf36a600-e04f-11eb-88ac-b6699a3bcff4.png)
Same when I attempt to get in with ip adrdress etc. 

Any insight would be greatly appreciated. *Sheesh*

**Comment by jamaalmck** [comment]
Also, trying to go through the tutorial when finding errors with 4.0 migration, when I attempt to stop the service via "sudo systemctl stop hoobs.service" i recieve "Failed to stop hoobs.service: Unit hoobs.service not loaded." 

I imagine the service being loaded would definitely help the situation.

**Comment by jamaalmck** [comment]
Ok - updating as I go. Somehow, I managed to regain access to Hoobs.local. So I'm back to the first post. 
After going through the full tutorial for migration failure, I'm still unable to configure this plugin. And I keep getting a statuscodeerroe 400 because I'm missing username and password but where am I to input that info? On the previous Hoobs 3xx  version there was a configuration option which I don't see on this version.

**Comment by BobbySlope** [comment]
Please reach out via email info@hoobs.org or via fb messenger. We can do a remote session to get you upgraded
