### ISSUE TITLE
Hoobs dashboard not fully visible on iOS with Hoobs 4.x

### ISSUE THREAD

**Issue by shellyman** [hoobs-org/HOOBS#1335]
Hello,
under the latest Hoobs version 4.x (unfortunately the dashboard is not correctly visible under iOS (iPad) (see picture).
![Hoobs](https://user-images.githubusercontent.com/69757639/124874703-52c49400-dfc8-11eb-9d32-8dddfa553faa.jpg)

**Comment by mkellsy** [comment]
You can resize the dashboard to fit better. Click the Lock Icon and you can drag and size the items as needed.

**Comment by shellyman** [comment]
Thank you, it worked
