### ISSUE TITLE
Cannot start HOOBS device after failed upgrade to v4

### ISSUE THREAD

**Issue by HomeCoops** [hoobs-org/HOOBS#1336]
Tried re-installing multiple times - but fails to start with this error

Initializing HAP-NodeJS v0.9.4...
Error: /usr/lib/hoobsd/node_modules/node-uname/build/Release/uname.node: file too short

**Comment by EddieDSuza** [comment]
Please try following this guide https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

**Comment by HomeCoops** [comment]
Get the following error when doing 'Reinstall Node and HOOBS' section, Now re-install HOOBS and HeIM

yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "/usr/local/share/.cache/yarn/v6/npm-cancel-token-0.1.1-c18197674bb1c84c1d6933ebf15d8d5a5ce79b4f-integrity/node_modules/cancel-token/.yarn-metadata.json: Unexpected end of JSON input".
info If you think this is a bug, please open a bug report with the information provided in "/usr/lib/hoobsd/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
dpkg: error processing package hoobsd (--configure):
 installed hoobsd package post-installation script subprocess returned error exit status 1
Setting up helm (1.2.5) ...
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 19.33s.
Setting up hoobs-cli (4.0.35) ...
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 17.40s.
dpkg: dependency problems prevent configuration of hoobs-gui:
 hoobs-gui depends on hoobsd (>= 4.0.0); however:
  Package hoobsd is not configured yet.

dpkg: error processing package hoobs-gui (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 hoobsd
 hoobs-gui
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mkellsy** [comment]
It looks like a network issue. Run through the tutorial again.

https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

I added a cache clear command that should help.
