### ISSUE TITLE
(node:16000) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by BiGassKanga** [hoobs-org/HOOBS#1339]
**Description**

I've upgraded to the latest version of Hoobs 4. I've got a raspberry Pi 4 (4gb) 
And i've noted the following issues on the log:
(node:16000) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit

and plugin
7/8/2021, 10:11:23 PMWARNINGplugin site unavailable

and myq issue 

All things seem to work. But would like to remove the warnings.

**Version**
Please include the version of HOOBS you are using.
Hoobs 4.0.74

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
Hoobs3 to Hoobs4

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Hue
MyQ
Bigassfans
Unifi

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
BigAssFansBridge
{
    "accessories": [],
    "platforms": [
        {
            "platform": "BigAssFans"
        }
    ]
}

Hue Bridge
{
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": false,
            "resource": true,
            "lights": true,
            "hueMotionTemperatureHistory": true,
            "brightnessAdjustment": 100,
            "heartrate": 5,
            "lowBattery": 25,
            "timeout": 5,
            "waitTimePut": 50,
            "waitTimePutGroup": 1000,
            "waitTimeResend": 300,
            "waitTimeUpdate": 20,
            "users": {
               [3 users in total]
            },
            "sensors": false
        }
    ]
}
UNifi protect bridge
{
    "accessories": [],
    "platforms": [
        {
            "platform": "UniFi Protect",
            "controllers": [
                {
                    "address": "xxx.xxx.xxx.xxx",
                    "username": "xyz@xxxxxxxxxx.xom",
                    "password": "password"
                }
            ]
        }
    ]
}
MyQ bridge
{
    "accessories": [],
    "platforms": [
        {
            "platform": "myQ",
            "email": "xyz@xxxxxxxxxx.xom",
            "password": "password",
            "name": "myQ"
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
7/8/2021, 10:10:48 PMWARNINGdevice reboot command received
7/8/2021, 10:10:49 PMHue Bridge stopping
7/8/2021, 10:10:49 PMBig Ass Fans Bridge stopping
7/8/2021, 10:10:49 PMUnifi Protect Bridge stopping
7/8/2021, 10:10:49 PMmyQ Bridge stopping
7/8/2021, 10:11:12 PMhub is running on port 80
7/8/2021, 10:11:13 PMHue Bridge starting
7/8/2021, 10:11:13 PMUnifi Protect Bridge starting
7/8/2021, 10:11:14 PMBig Ass Fans Bridge starting
7/8/2021, 10:11:14 PMmyQ Bridge starting
7/8/2021, 10:11:17 PMBig Ass Fans BridgeLoaded plugin 'homebridge-bigAssFans'
7/8/2021, 10:11:17 PMBig Ass Fans BridgeLoading 1 platforms...
7/8/2021, 10:11:17 PMBig Ass Fans BridgeBridge is running on port 53826.
7/8/2021, 10:11:19 PMUnifi Protect BridgeLoaded plugin 'homebridge-unifi-protect'
7/8/2021, 10:11:19 PMUnifi Protect BridgeLoading 1 platforms...
7/8/2021, 10:11:19 PMmyQ BridgeLoaded plugin 'homebridge-myq'
7/8/2021, 10:11:19 PMmyQ BridgeLoading 1 platforms...
7/8/2021, 10:11:19 PMUnifi Protect BridgeBridge is running on port 52826.
7/8/2021, 10:11:19 PMmyQ BridgeBridge is running on port 54826.
7/8/2021, 10:11:21 PMHue BridgeLoaded plugin 'homebridge-hue'
7/8/2021, 10:11:21 PMHue BridgeLoading 1 platforms...
7/8/2021, 10:11:23 PMWARNINGplugin site unavailable
7/8/2021, 10:11:27 PMHue BridgeBridge is running on port 51826.
7/8/2021, 10:12:18 PMHue BridgeERROR(node:798) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
7/8/2021, 10:12:18 PMHue BridgeERROR(Use `node --trace-warnings ...` to show where the warning was created)
7/8/2021, 10:12:39 PMmyQ BridgeERROR[myQ Bridge FA37@Garage Door@@Manufacturer] characteristic value expected string and received undefined
7/8/2021, 10:12:39 PMmyQ BridgeERROR[myQ Bridge FA37@Garage Door@@Model] characteristic value expected string and received undefined
```

**Additional context**

**Comment by mkellsy** [comment]
This is just a warning from Node. The plugins use a lot of listeners.

one thing you can do is separate your plugins into separate bridges. This increases the max listners.

**Comment by BiGassKanga** [comment]
Thanks mkellsy. All my plugins are on separate bridges as shown in the config. So it seems the issue still remains. Or Maybe I take your logic one step further and put one hue bridge (their zigbee hub) on a separate Hoobs bridge. I have three Philips hue bridges so I would have three Hoobs bridges…. Will try later today and report back.

**Comment by BobbySlope** [comment]
This was an issue with homebridge-lib loaded with hue plugin. It should be solved now: https://github.com/ebaauw/homebridge-lib/releases/tag/v5.1.9
