### ISSUE TITLE
Factory Reset

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#134]
What about adding a reset (factory settings) feature. 

So users can reset their system if they crashed it, or if they sell their HOOBS Box.

Maybe has to be discussed in team. @mkellsy

**Comment by mkellsy** [comment]
There is a default.json. Or you can delete the ~/.hoobs folder.

**Comment by rpolenthon** [comment]
Because it will be sold as a finished product, users should not have to write commands. There should be a factory setting button @BobbySlope @mkellsy

**Comment by mkellsy** [comment]
Yes. I am just adding notes to the issue for when I build the function.

**Comment by askovi** [comment]
Adding to this, it should be a 'Reset to factory defaults' button, at the very bottom of the Help page with a warning confirmation that will delete all plugins, restore default config, delete users, etc and bring you back to the registration page.

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.71

**Comment by ivanarro** [comment]
I have problems with my accessories after the upgrade. They are hidden, but de plugin is running. How can I restore the factory configuration?

**Comment by mkellsy** [comment]
Menu -> Help -> Factory Reset

**Comment by ivanarro** [comment]
> Menu -> Help -> Factory Reset

Thank You mkellsy,

Now I have another issue. I've reading that the problem could be on the ports configuration and I've changed one port in the config.json and now I cannot log in the hood interface. Do you know why?

Thank Youn in advance.

**Comment by ivanarro** [comment]
All time I see that, I've eresed my browser caché and reboot a lot of times the hood and router but nothing works.


<img width="1280" alt="Captura de Pantalla 2019-11-24 a les 13 29 09" src="https://user-images.githubusercontent.com/58119870/69494653-9aafa980-0ebe-11ea-9932-7bfaa3fda702.png">

**Comment by mkellsy** [comment]
you have to use the port you entered
http://hoobs.local:8080

Replace 8080 with the port you entered.
