### ISSUE TITLE
SmartThings not Updating Unavailable Devices

### ISSUE THREAD

**Issue by albertovm** [hoobs-org/HOOBS#1340]
When any bulb changes status to unavailable, the plugin keep the bulb ON. It could at least change it to off. If I turn any of these bulbs off, they turn back on.

Every bulb in the following screen shot are unavailable in Smartthings, but still ON in Hoobs and Home app:

![Screen Shot 2021-07-08 at 11 49 12](https://user-images.githubusercontent.com/4246424/124943054-890f0d00-dfe2-11eb-86f4-fd5f31f5d630.png)

**Comment by mkellsy** [comment]
Open the SmartApp in SmartThings and uncheck the bulbs you don’t want to show.

**Comment by albertovm** [comment]
I want and I need all them. And Homekit should not mirror Smartthings with this Hoobs plugin? Or this is just a bug that people has no idea how to solve?

**Comment by mkellsy** [comment]
I will have to look into it.
I actually use the SmartThings plugin too for a mix of around 85 devices.
Mine has always been instant.

Check to see if your Direct IP is set, if it isn't you might need to set it. This would be the IP address of HOOBS not SmartThings.

**Comment by albertovm** [comment]
Thanks… I use it there’s a long time, and this always happened. This is a “never solved” problem. I believe that this plugin is not able to change status without a direct command, and “turn unavailable” looks a “daemon” function. Maybe Smartthings is not giving this information to the plugin.
