### ISSUE TITLE
Broadlink RM Pro not Showing in HomeKit

### ISSUE THREAD

**Issue by orianlevy** [hoobs-org/HOOBS#1342]
Hi,
Since upgrading to Hoobs4, unable to add a tv accessory using Broadlink RM Pro plugin.
In the Home app usually i clicked add accessory and the TV appeared there, but now its not available there.
This is what i found in the log:
(i think the issue is this line:
HOOBS WARNING A platform configured a external accessory under the plugin name "[object Object]". However no loaded plugin could be found for the name.
)

08/07/2021, 8:29:18 pmHOOBSLoading 2 platforms...
08/07/2021, 8:29:18 pmHOOBSBroadlink RM[INFO] Automatically discovering Broadlink RM devices.
08/07/2021, 8:29:18 pmHOOBSBroadlink RM[INFO] Running Bridge Broadlink RM Plugin version 4.4.5
08/07/2021, 8:29:18 pmHOOBSBroadlink RMTV Accessory Ready
08/07/2021, 8:29:18 pmHOOBSBroadlink RMAC Accessory Ready
08/07/2021, 8:29:18 pmHOOBSWARNINGA platform configured a external accessory under the plugin name "[object Object]". However no loaded plugin could be found for the name.
08/07/2021, 8:29:18 pmHOOBSBroadlink RM**************************************************************************************************************
08/07/2021, 8:29:18 pmHOOBSBroadlink RMYou added TVs in your configuration!
08/07/2021, 8:29:18 pmHOOBSBroadlink RMDue to a HomeKit limitation you need to add any TVs to the Home app by using the Add Accessory function.
08/07/2021, 8:29:18 pmHOOBSBroadlink RMThere you'll find your TVs and you can use the same PIN as you using for this HomeBridge instance.
08/07/2021, 8:29:18 pmHOOBSBroadlink RM**************************************************************************************************************

**Comment by mkellsy** [comment]
The plugin doesn't have a visual config configured.

Go to the Advanced section in the Configuration screen, you can add configs there.

https://broadlink.kiwicam.nz/#installation

**Comment by BobbySlope** [comment]
User contacted via FB messenger.
He added the TV successfully to HOOBS4
the Plugin needs manual add accessory in homekit but the TV does  not appear in Homekit when trying to add accessory
See desciption in Log between the ******** Lines
![211199828_1134314887053305_4058150959283362988_n](https://user-images.githubusercontent.com/50763727/125155425-1035bf80-e160-11eb-8a6f-d3fe5a44077e.jpg)

to Do: 
add exposing separate Accessories to be able to add it in Homekit or
Implement to the Bridge itself to be added automatically

**Comment by mkellsy** [comment]
Can’t automatically add bridges in HomeKit.

**Comment by mkellsy** [comment]
I want to update everyone on this.

I have tried to trace this with no luck. So I headed over to Amazon and bought a BroadLink RM Mini3 Black Bean. It should be here in the next few days. This will allow me to set this up, find and test this plugin.

I thank everyone for their patience.

**Comment by orianlevy** [comment]
Thank you so much!
In order to reproduce you need to add tv accessory in the config file, and then try to add accessory in Home app

**Comment by orianlevy** [comment]
Hi, in the latest plugin update for broadlink - the issue is now resolved. 
thank you anyway!
