### ISSUE TITLE
Cannot Set location in 4.0

### ISSUE THREAD

**Issue by cjchap** [hoobs-org/HOOBS#1343]
**Description**
Unable to set location in Hoobs 4

**Version**
4.0.73

**Did you upgrade**
Clean installation.

**Pervious version**
Was able to leverage location features and setting and Hoobs 3

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] Custom Install
Raspberry Pi 4

```
{
    "accessories": [
        {
            "name": "Roomba",
            "model": "r671",
            "robotpwd": "",
            "ipaddress": "192.168.1.101",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "dockContactSensor": true,
            "runningContactSensor": true,
            "binContactSensor": true,
            "accessory": "",
            "blid": ""
        }
    ],
    "platforms": [
        {
            "platform": "Roomba"
        },
        {
            "platform": "myQ",
            "email": "",
            "password": "",
            "name": "myQ"
        },
        {
            "platform": "Nest",
            "name": "Nest",
            "access_token": "{\",
            "googleAuth": {
                "issueToken": ""
            }
        },
        {
            "platform": "BelkinWeMo",
            "name": "Wemo",
            "mode": "auto"
        },
        {
            "platform": "Arlo",
            "name": "Arlo",
            "email": "",
            "password": "",
            "include_cameras": true
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
2:29:48 PMWARNINGunhandled rejection: Cancel
```

**Additional context**
I have tried to add location via local cities and zipcode several times.  Each time I get the entry in the log 5 seconds later.

Thank you for the help.

**Comment by mkellsy** [comment]
Go to Menu -> Hub Settings
In the Weather section click Change in the Location field.

**Comment by cjchap** [comment]
This is the method used earlier.  I will not allow me to search for locations and only returns single log entry listed above.

**Comment by mkellsy** [comment]
What are you typing in the serch field?

**Comment by cjchap** [comment]
I have tried a couple formats,
local city, state
local city, ST
local city, US
Large City, state
Large City, US
Zipcode
Grid Coordinates from google maps.

Each time, 5 seconds after searching I get the following entry in my logs:
2:29:48 PMWARNINGunhandled rejection: Cancel

Any suggestions?

**Comment by mkellsy** [comment]
It uses Map Quest for a search.
If you go to this URL http://open.mapquestapi.com/geocoding/v1
It should say "The AppKey submitted with this request is invalid."

Then to see if your device can see the URL oprn the terminal and type in this
```
curl http://open.mapquestapi.com/geocoding/v1
```
You should see the same message.
