### ISSUE TITLE
Version 4 Upgrade

### ISSUE THREAD

**Issue by whitsunday68** [hoobs-org/HOOBS#1347]
My upgrade didn't work so I tried the Migration Failed Tutorial on the Support site but it came back with a 

hoobs@hoobs:~ $ cd ~/
hoobs@hoobs:~ $ sudo hbs system restore ~/migration.zip
 WARNING  this will remove all current settings and plugins and replace it with the backup
 WARNING  invalid restore file
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
Run
```
ls -la ~/
```
Is migration.zip in that directory?

**Comment by whitsunday68** [comment]
HI there I decided to go back to a clean install in the end.  So just going to add the plugs again.

I didn’t have that many.


Regards,


Roy Olsen
***@***.***

**Comment by mkellsy** [comment]
Sorry the migration didn't work for you. I just finished a ton of work on it. It will work much better in the future.

Anyway fresh 4.0 image has some improvements from Raspbian. Run much smoother.
You can download a 4.0 image here https://support.hoobs.org/downloads/image
