### ISSUE TITLE
Naming of Bridges

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1348]
Hi, if you create a Bridge e.g. "Bridge No. 1" and you decide to rename it you can do so in the Bridge section but:

The new name shows up correctly but there is internally a naming that keeps the "original" name. The creation name instead of the renaming. Because if you export the bridge (Bridge No. 1) and the new name is "AllNew" the export shows bridge-no-1 not allnew. 

And in addition in the log if you restart the new renamed bridge "AllNew" it shows Bridge No. 1 is stopping and starting.

HOOBS 4.0.79

**Comment by mkellsy** [comment]
Yes this is by design.
