### ISSUE TITLE
Somfy Protect Plugin Errors

### ISSUE THREAD

**Issue by just808b** [hoobs-org/HOOBS#1353]
Hi 

I have updated to v 4.0.79 (not sure from what verison) on the Hoobs box and now the plugin Somfy Protect is no longer responding in Homekit.  I removed everything and added as a brand new accessory.  I added successfully the bridge to homekit alongside my alarm.  While it appears on Homekit it stats 'no response'.  

The plugin should arm the security system 

I believe this is nothing to do with the developer. 

```
7/9/2021, 3:56:58 PMsomfyprotectbridge stopping
7/9/2021, 3:57:02 PMSomfy Protect Bridge starting
7/9/2021, 3:57:10 PMSomfy Protect BridgeLoaded plugin 'homebridge-somfy-protect'
7/9/2021, 3:57:10 PMSomfy Protect BridgeLoading 1 accessories...
7/9/2021, 3:57:10 PMSomfy Protect BridgeSecurity SystemGetting a new token
7/9/2021, 3:57:10 PMSomfy Protect BridgeSecurity SystemSecurity system finished initializing!
7/9/2021, 3:57:10 PMSomfy Protect BridgeBridge is running on port 52826.
7/9/2021, 3:57:11 PMSomfy Protect BridgeWARNINGunhandled rejection: Error: Request failed with status code 400
```

if I attempt to arm the device within Hoobs - Accessories I get the following logs

```
7/9/2021, 6:01:29 PMSomfy Protect BridgeSecurity SystemTarget state was set to: 2
7/9/2021, 6:01:29 PMSomfy Protect BridgeSecurity SystemstopPolling: Polling already stopped
7/9/2021, 6:01:29 PMSomfy Protect BridgeERROR[Somfy Protect Bridge BD8F@Security System@Security System@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
7/9/2021, 6:01:30 PMSomfy Protect BridgeERROR[Somfy Protect Bridge BD8F@Security System@Security System@Security System Target State] characteristic value 0 is not contained in valid values array
```

Same problem with the plugin Somfy Protect Multi app

**Comment by mkellsy** [comment]
Can you download your logs and post them. I need more logs.

You can download your logs from the logs screen and click the download icon on the top of the screen.

**Comment by just808b** [comment]
I wasnt too sure if the error was a WiFi communication error, so I have reset my Hoobs box to reset the WiFi ssid details.  However, I am having problems installing the plugin into Homekit.  The Bridge add to Home, but the accessory does not.  Attached  are the logs after the reset and then reboot

thanks

[add bridge but can not add accessory to homekit log.txt](https://github.com/hoobs-org/HOOBS/files/6795996/add.bridge.but.can.not.add.accessory.to.homekit.log.txt)

**Comment by just808b** [comment]
Still no joy with this plug-in since upgrading 

29/07/2021, 19:42:32Somfy Protect Bridge starting
29/07/2021, 19:42:32Deebot BridgeBridge change
29/07/2021, 19:42:33deebotbridge stopping
29/07/2021, 19:42:37Deebot Bridge starting
29/07/2021, 19:42:46Deebot BridgeLoaded plugin 'homebridge-deebot'
29/07/2021, 19:42:46Deebot BridgeLoading 1 platforms...
29/07/2021, 19:42:46Deebot BridgeDeebotInitialising plugin v3.3.1 | Node v14.17.2 | HB v1.3.4 | HOOBS v4...
29/07/2021, 19:42:46Deebot BridgeDeebotPlugin initialised. Setting up accessories....
29/07/2021, 19:42:46Deebot BridgeDeebotUsing ecovacs-deebot library v0.6.1-beta.3.
29/07/2021, 19:42:46Deebot BridgeBridge is running on port 51826.
29/07/2021, 19:42:49Somfy Protect BridgeConfiguration change
29/07/2021, 19:42:49somfyprotectbridge stopping
29/07/2021, 19:42:49Deebot BridgeDeebot[Jeeves] initialising with options: {"hideMotionSensor":false,"motionDuration":30,"lowBattThreshold":15,"showMotionLowBatt":false,"showBattHumidity":false,"overrideLogging":"default"}.
29/07/2021, 19:42:49Deebot BridgeDeebot[Jeeves] initialised with id 2ebf3b73-b8b5-4c97-be69-0620b341f0ea.
29/07/2021, 19:42:49Deebot BridgeDeebot✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
29/07/2021, 19:42:51Deebot BridgeDeebot[Jeeves] current battery [100%].
29/07/2021, 19:42:51Deebot BridgeDeebot[Jeeves] current charging state [charging].
29/07/2021, 19:42:51Deebot BridgeDeebot[Jeeves] current cleaning state [idle].
29/07/2021, 19:42:51Deebot BridgeDeebot[Jeeves] current cleaning speed [standard].
29/07/2021, 19:42:53Somfy Protect Bridge starting
29/07/2021, 19:42:54Deebot BridgeDeebot[Jeeves] has been reported [online].
29/07/2021, 19:43:01Somfy Protect BridgeWARNINGNo plugins installed.
29/07/2021, 19:43:01Somfy Protect BridgeBridge is running on port 52826.
29/07/2021, 19:44:30Somfy Protect BridgeConfiguration change
29/07/2021, 19:44:30somfyprotectbridge stopping
29/07/2021, 19:44:34Somfy Protect Bridge starting
29/07/2021, 19:44:41Somfy Protect BridgeWARNINGNo plugins installed.
29/07/2021, 19:44:41Somfy Protect BridgeLoading 1 accessories...
29/07/2021, 19:44:42Somfy Protect BridgeBridge is running on port 52826.

**Comment by just808b** [comment]
I have updated Hoobs to version 4.0.96 and now allows me to configure the plug-in which in turn the alarm adds to HomeKit.  However, it does not allow me to arm or disarm it, in HomeKit in says ‘no response’.  See errors below 

Log

29/07/2021, 20:22:35Somfy Protect BridgeConfiguration change
29/07/2021, 20:22:35somfyprotectbridge stopping
29/07/2021, 20:22:39Somfy Protect Bridge starting
29/07/2021, 20:22:43Somfy Protect BridgeLoaded plugin 'homebridge-somfy-protect-multi'
29/07/2021, 20:22:43Somfy Protect BridgeLoading 1 accessories...
29/07/2021, 20:22:43Somfy Protect BridgeBridge is running on port 52826.
29/07/2021, 20:22:44Somfy Protect BridgeWARNINGunhandled rejection: Error: Request failed with status code 400
29/07/2021, 20:24:35Somfy Protect BridgeERROR[Somfy Protect Bridge 85EA@Somfy Protect@Somfy Protect@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
29/07/2021, 20:25:26somfyprotectbridge stopping
29/07/2021, 20:25:30Somfy Protect Bridge starting
29/07/2021, 20:25:34Somfy Protect BridgeLoaded plugin 'homebridge-somfy-protect-multi'
29/07/2021, 20:25:34Somfy Protect BridgeLoading 1 accessories...
29/07/2021, 20:25:35Somfy Protect BridgeBridge is running on port 52826.
29/07/2021, 20:25:35Somfy Protect BridgeWARNINGunhandled rejection: Error: Request failed with status code 400
29/07/2021, 20:26:00Somfy Protect BridgeConfiguration change
29/07/2021, 20:26:00somfyprotectbridge stopping
29/07/2021, 20:26:04Somfy Protect Bridge starting
29/07/2021, 20:26:08Somfy Protect BridgeLoaded plugin 'homebridge-somfy-protect-multi'
29/07/2021, 20:26:08Somfy Protect BridgeLoading 1 accessories...
29/07/2021, 20:26:09Somfy Protect BridgeBridge is running on port 52826.
29/07/2021, 20:26:10Somfy Protect BridgeWARNINGunhandled rejection: Error: Request failed with status code 400

**Comment by just808b** [comment]
This is the error logs when trying to arm the alarm

29/07/2021, 20:33:35Somfy Protect BridgeProtectTarget state was set to: 1
29/07/2021, 20:33:35Somfy Protect BridgeProtectstopPolling: Polling already stopped
29/07/2021, 20:33:36Somfy Protect BridgeERROR[Somfy Protect Bridge 85EA@Protect@Protect@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response

**Comment by just808b** [comment]
All this was fine before upgrading to Hoobs 4.  Anyone got a clue?

**Comment by just808b** [comment]
Upgraded to version 4.0.98

Still doesn’t work although the error has changed to only the last line of code.  See attached for the logs printed after I am requesting to change the status of the security system I.e. turn on the security system.  
![5B8B9E6F-B1D8-4D4C-B007-CD2A8651775F](https://user-images.githubusercontent.com/84090729/128573262-b73ad5f8-768b-4f34-b20b-e8a8618be1b3.jpeg)

**Comment by just808b** [comment]
![4D60D033-2537-4F2F-BBDA-FB6147813D6D](https://user-images.githubusercontent.com/84090729/128879144-b5a072f7-65a1-4d82-90e6-2f9d3480b3d1.jpeg)

**Comment by just808b** [comment]
Updated to new version same error code.  Again this plug-in worked great before the upgrade to Hoobs 4 
![E4C0509A-DDCF-4E66-96BE-D712EA6AA01A](https://user-images.githubusercontent.com/84090729/129335640-497ae094-147e-489c-9134-0729558e77e8.jpeg)

**Comment by just808b** [comment]
> Can you download your logs and post them. I need more logs.
> 
> You can download your logs from the logs screen and click the download icon on the top of the screen.

Are these logs sufficient?

**Comment by just808b** [comment]
I have been informed that it’s a problem with Somfy Protect developer https://github.com/alxscms/homebridge-somfy-protect/issues
