### ISSUE TITLE
Hoobs won't load after upgrade to v4 attempt

### ISSUE THREAD

**Issue by TheLucidOne** [hoobs-org/HOOBS#1354]
I upgraded to v4 and now the device turns on but will not load (GUI or bridge).  If I restart it manually, and login in via ssh (hoobs@hoobs.local) at the right time, I can get in but I get an error like this any time I try to issue a (known) command:

This is just an example of me trying to install some disk check tools
hoobs@hoobs:~ $ /usr/bin/sudo apt-get install smartmontools
-bash: /usr/bin/sudo: Input/output error

This sounds/looks like some sort of disk issue but I cannot check the disk because I cannot run anything.  I previously was running 3.3.5 then went to 3.3.7 then 4.  I have no idea what to do from here.  Any help would be appreciated.

**Comment by mkellsy** [comment]
It looks like your SD Card has failed.
Please send email info@hoobs.org to see if we can RMA a new SD Card.
