### ISSUE TITLE
Field Labels/Titles missing for Samsung Tizen (Certified Plug-in)

### ISSUE THREAD

**Issue by scoutbeer** [hoobs-org/HOOBS#1355]
Fresh Image of v4 updated to latest (4.0.79).  The Samsung Tizen certified plugin is not showing any field labels on the configuration page.  The only way data will populate is if configured via Advanced and editing the JSON format and saving. 
 Then data populate the fields but still not not show field labels/titles. See screenshot attached.  

**Expected behavior**
Plugin should show labels/titles/descriptions for each entry field

**Plugin name**
http://hoobs.local/plugin/homebridge-samsung-tizen

**Please report the issue to the plugin developer**
https://github.com/tavicu/homebridge-samsung-tizen/issues/384

**Version**
4.0.79 (clean install from v4 image and then updated via UI

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
**_The above instructions are not valid for v4_**

```
{
    "accessories": [],
    "platforms": [
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Master Bedroom TV",
                    "ip": "x.x.x.x",
                    "mac": "54:AA:AA:AA:AA:AA",
                    "uuid": "A1",
                    "method": "frame"
                }
            ]
        }
    ]
}
```

![Tizen Plugin](https://user-images.githubusercontent.com/87205579/125125039-aaddc200-e0be-11eb-8283-0c070aa0788d.png)

**Comment by mkellsy** [comment]
Fixed.

You may have to clear the hub cache
Menu -> Hub Settings
Click on the Clear Cache button.
