### ISSUE TITLE
User list from API GET /users have different admin formats

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#136]
@mkellsy 

Steps to reproduce:
1. Use a clean old HOOBS Image 2.x
2. Do a HOOBS 3 update
3. Add a new user in the web interface
4. HTTP GET request for /users

The response will have two users. The "admin" parameter is one time formatted as string and the other time formatted as bool.

Please migrate it to one standard.

Example:

[
  {
    "id": 1,
    "name": "Administrator",
    "admin": true,
    "username": "admin"
  },
  {
    "id": 2,
    "name": "Ron",
    "admin": "true",
    "username": "Ron"
  }
]

**Comment by mkellsy** [comment]
This is from UI-X. The admin property should be a boolean.

**Comment by mkellsy** [comment]
There was a type error. Bools can come across as strings. Need to handle both cases of "true" and true and "false" and false. As well as catch bad strings and make the result false.

Fixed in 3.0.0-beta.40

**Comment by rpolenthon** [comment]
@mkellsy 

Yes already did that, I have finished almost all controllers on my side during weekend. I initialize a Boolean from the string description and if it fails the request fails with error bad response from server.
