### ISSUE TITLE
How to change SSID on Hoobs box

### ISSUE THREAD

**Issue by just808b** [hoobs-org/HOOBS#1361]
Is it possible to change the name of the SSID Ethernet network inside the hoobs box?  

For some strange reason, I have one name for my wifi wireless network and another for the Ethernet cable. This is causing problems with communication between the two networks.  I have changed the name of the SSID Ethernet network on my PC, which has solved the problem for the wireless devices and my PC.  

I believe this same communication error is causing problems between the Hoobs box and the wireless devices, but I am unsure how to change the name of the Ethernet SSID network.  Thus any advice would be grateful?

**Comment by mkellsy** [comment]
I’m not too sure what you are trying to accomplish here.

Are you trying to change the WiFi network your device is connected to?

or are you trying to change the setup ssid?

**Comment by just808b** [comment]
I would like to check the setup ssid? if its incorrect change it.  Otherwise change the wifi network

**Comment by mkellsy** [comment]
The setup SSID **HOOBS (NNNN)** is generated on startup. It adds a unique number **(NNNN)** to it so it doesn't conflict with other HOOBS devices.

You can find the script that runs on startup here
```
/usr/local/sbin/wifi-connect-startup
```

This script will start the setup SSID, if there is no network. If there is, it will not start.

This is all controlled from a one shot service here.
```
/etc/systemd/system/wifi-connect.service
```
