### ISSUE TITLE
Missing values for combined sensors

### ISSUE THREAD

**Issue by apartmedia** [hoobs-org/HOOBS#1364]
**Description**
Version 4.0.79 in conjunction with the Certified Plugin Shelly 0.18.0, only one sensor value is reported in the dashboard and accessory list for combined sensors such as the H&T or Flood.
The H&T sensor reports temperature and humidity, but HOOBS 4 only shows the temperature accessory.
The flood sensor reports leakage and temperature, HOOBS 4 only shows leakage accessory.
It looks like it's not related to the plugin, because that worked flawlessly with the same version in HOOBS 3.
Additionally both sensor values are still transmitted and displayed in the Home app and also via the Alexa plugin in the Alexa app. Basically, the values of both sensors are there, but only not available in the HOOBS UI.

**Version**
4.0.79

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
3.3.7

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install
- [x] HOOBS 3 Image

**List your plugins**
- Alexa
- homebridge-magichome-dynamic-platform
- Shelly

**Post your config**
[config.txt](https://github.com/hoobs-org/HOOBS/files/6795906/config.txt)

**Post your log**
[log.txt](https://github.com/hoobs-org/HOOBS/files/6795907/log.txt)

**Comment by mkellsy** [comment]
4.0 combines sensors with the same UUID into one. There is a display and then icons on the bottom showing the other sensors.

**Comment by apartmedia** [comment]
> 4.0 combines sensors with the same UUID into one. There is a display and then icons on the bottom showing the other sensors.

Can you guide me where exactly this display and icons for the other sensors are?
On the accessory card I only see the one sensor value and the gear icon for setting up name, icon and room (tested on iOS mobile Safari and Firefox).
May be I just do not get what you mean…

![A5C8325A-1936-4657-BCA1-02FDD180EC47](https://user-images.githubusercontent.com/17024592/125411460-3ce71280-e3be-11eb-8f5e-3cdba75ac2a1.jpeg)

**Comment by mkellsy** [comment]
There’s another issue for this.

**Comment by apartmedia** [comment]
What ID is it?
