### ISSUE TITLE
Govee Device ID (23 digit Govee Device ID) 

### ISSUE THREAD

**Issue by michaelromero2020** [hoobs-org/HOOBS#1366]
**Description**
When configuring this plugin Govee Device ID (23 digit Govee Device ID) is asked for when you add a lighting device. Does anyone know where I can find this?

**Version**
4.0

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ √] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [√ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**List your plugins**

Govee
Hue
Simplesafe 
TPLINK
Tuya Web 
My Q

**Comment by bwp91** [comment]
Should be in the logs when you start the plugin, something like:

```
[Device] initialised with id %%%.
```

It's normally in the format

AB:CD:EF:AB:CD:EF:AB:CD

**Comment by michaelromero2020** [comment]
Hmm. I'm just getting this in the log:

7/10/2021, 5:22:35 PMgoveebridge stopping
7/10/2021, 5:22:39 PMGovee Bridge starting
7/10/2021, 5:24:29 PMgoveebridge stopping
7/10/2021, 5:24:33 PMGovee Bridge starting
7/10/2021, 5:28:53 PMgoveebridge stopping
7/10/2021, 5:28:57 PMGovee Bridge starting

**Comment by michaelromero2020** [comment]
Also i'm using: Govee RGBIC WiFi LED Strip Lights H6163

**Comment by bwp91** [comment]
Can you turn on debug logging in the plugin settings (and then restart the bridge) to see if anything appears in the logs to explain why it's stopping and starting?

**Comment by michaelromero2020** [comment]
I feel like I might be missing something super obvious. When I click on the bridge there isn't even a restart option. At the top I see:

>Govee Bridge
>>Pairing
>>>Start Cache

Still, I turned on debug logging, hit "Start" under pairing and nothing changed in the log. I just got another series of Stopping and starting.

**Comment by bwp91** [comment]
It's actually in the plugin settings, go to:

Plugins -> (Govee Bridge) -> Click on Govee plugin -> Configuration ->

Then scroll down a bit you should see this -> Tick the `Debug Logging` box

<img width="820" alt="Screenshot 2021-07-11 at 00 33 37" src="https://user-images.githubusercontent.com/43026681/125178765-b379e980-e1df-11eb-8821-d9f13cbb6e0a.png">

Restart the bridge and check the logs

**Comment by michaelromero2020** [comment]
I'm sorry, I explained poorly. I proceeded with turning on Debug Logging. When I went back to the bridge to restart it, I noticed I don't have a restart option (like I do on my other bridges).

**Comment by michaelromero2020** [comment]
![Screen Shot 2021-07-10 at 6 53 21 PM](https://user-images.githubusercontent.com/87102150/125179036-1bb0d700-e1b0-11eb-8c28-a221d405026e.png)

**Comment by michaelromero2020** [comment]
7/10/2021, 6:54:45 PMgoveebridge stopping
7/10/2021, 6:54:50 PMGovee Bridge starting

**Comment by bwp91** [comment]
There is no restart option because the bridge isn't running already. Click on "Start" in your screenshot...

**Comment by michaelromero2020** [comment]
![Animated GIF-source](https://user-images.githubusercontent.com/87102150/125179563-e8bd1200-e1b4-11eb-8c54-fc60a5120fcf.gif)

Okay, I did that but unfortunately not seeing anything change.

**Comment by bwp91** [comment]
> Okay, I did that but unfortunately not seeing anything change. Would you recommend deleting the bridge and starting over?

Yes do try this, if this doesn’t work, can you post your govee config here (remove the api key) just so i can double check it’s in a correct format…

**Comment by michaelromero2020** [comment]
Issue solved by rebooting HOOBS.
