### ISSUE TITLE
Cannot upgrade to 4.x from 3.3.12

### ISSUE THREAD

**Issue by cleanev** [hoobs-org/HOOBS#1367]
**Description**
Cannot upgrade to 4.x. New install on RPi 3B+ with no nginx

**Version**
3.3.12

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi OS - latest updates installed 

**List your plugins**
none installed yet

**Post your config**
Nothing is there - just trying to get system to upgrade to 4.x before adding plugins

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

**Additional context**
Is there a command or requirement to upgrade to 4.x. WebGUI shows that update is available - upon clicking and going thru motions screen returns to same old 3.3.12 version after a period of about 10 minutes though it shows ‘Migrating…’ on the screen during the time. This is a new install using this command - wget -q -O - http://bit.ly/get-hoobs | sudo bash -
Node version is 14.17.0

**Comment by mkellsy** [comment]
This should help you out
https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a
