### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1372]
Is it possible, even in this early stage with minor fixes, to provide us release notes? So that we can see/read what kind of changes were made.

**Comment by scoutbeer** [comment]
+1 , this would be great.

**Comment by mkellsy** [comment]
Nodes are here
https://github.com/hoobs-org/hoobsd/releases

And here
https://github.com/hoobs-org/hoobsd/commits/main
https://github.com/hoobs-org/gui/commits/main

**Comment by Christian-CFP** [comment]
:( and you think "Big fixes" tells me the changes that have been made?

**Comment by mkellsy** [comment]
The commit logs tell you every commit made to the code.

We have tasks in the pipe line to make this autogenerate, but until I get the change to commit time to that project we have to rely on commit logs.
