### ISSUE TITLE
Can't connect via HOOBS.LOCAL, HomeManager, or IP address

### ISSUE THREAD

**Issue by hoobnoob** [hoobs-org/HOOBS#1376]
I noticed some of my Hoobs plugins were no longer working in HomeKit. I was unable to connect via HOOBS.local or the HomeManager app. When I pinged it in terminal, it returned

64 bytes from 23.221.222.250: icmp_seq=0 ttl=47 time=48.779 ms:

I still can not access HOOBS from the browser and the app still says "Connection Failed"

Would love some insight on how to reconnect.

**Comment by BobbySlope** [comment]
Try hoobs/ instead

**Comment by hoobnoob** [comment]
That did it. Thanks!
