### ISSUE TITLE
No configuration options homebridge-broadlink-rm in Hoobs 4

### ISSUE THREAD

**Issue by grabarz1986** [hoobs-org/HOOBS#1377]
**Description**
<img width="1233" alt="broadlink" src="https://user-images.githubusercontent.com/52297847/125474963-fd8fa62c-f969-4f73-9a06-c91466c8374b.png">

When installing plugin on fresh installation of Hoobs 4 and creating separate bridge there is no option to configure the plugin. Pasted configuration in Advanced section doesn't work.

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
homebridge-broadlink-rm

**Version**
4.0.8.0

**Did you upgrade**
Please let us know if you upgraded from a previous version.
fresh install

**Pervious version**

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ .] Custom Install

.

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
13.07.2021, 16:16:28Broadlink Rm Enhanced Bridge starting
13.07.2021, 16:17:05broadlinkrmenhancedbridge stopping
13.07.2021, 16:17:08ERRORUnable to determine plugin type for "homebridge-broadlink-rm"

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
homebridge-broadlink-rm doesn't have support for visual configs, you have to use the advanced editor.

Go to Config screen click Advanced then go to the Broadlink RM Bridge
