### ISSUE TITLE
API not fully functional after reboot without accessing the WEB-UI

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#138]
I experienced that after a reboot I have to access the WEB-UI a single time before some API functionality is available. I tested it with different controllers who need the admin permissions, but I think all functions checking for admin permissions are effected.

Steps to reproduce:
1. Reboot your server, make sure the browser tab is closed.
2. Do a POST /service/:action with an already known token.
3. You will get {"error":"unauthorized"}
4. Login to the WEB UI.
5. Do the request again and the request will succeed.

**Comment by mkellsy** [comment]
I noticed this in Postman too. I need to find out where this is happening.

**Comment by mkellsy** [comment]
This was because the main before request that validates the token needs to be async. I made the change and is fixed in 3.0.0-beta-40
