### ISSUE TITLE
HOOBS 4 cannot access terminal

### ISSUE THREAD

**Issue by wjkie** [hoobs-org/HOOBS#1380]
**Description**

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
We need more information to help you. 
Which version are you running. 
How do I our try to access the terminal. 
What exactly does not work.

**Comment by wjkie** [comment]
Hoobs 4 using the MacOS app I cannot access the terminal it presents  a login and password prompts and I respond with my HOOBS credentials then it pauses a few seconds then loops back to the login prompts.  Can't get past this.

**Comment by wjkie** [comment]
version 4.0.83 of HOOBS  
the MacOS software just downloaded today but can't find a version number on that
The Web interface has the same issue but it blinks a white screen for a half second before looping back to to the login prompt

I access the terminal through the Hoobs app and the Web interface using the menu  accessed from the 3 dots in the upper right of the screen

**Comment by wjkie** [comment]
what does not work:  it never actually completes the login to terminal.

I also tried to access using ssh hoobs@hoobs.local with MacOS Terminal and it just hangs and doesn't present a login prompt

**Comment by mkellsy** [comment]
The username is: **hoobs**
The password is: **hoobsadmin**

**Comment by wjkie** [comment]
thank you for your help.  It works fine now.
