### ISSUE TITLE
SimpliSafe Plugin Show Footage On Apple TV 

### ISSUE THREAD

**Issue by michaelromero2020** [hoobs-org/HOOBS#1381]
**Description**
Does anyone know if it's possible to have the footage from your Simplisafe Doorbell Camera to appear on your Apple TV (like other doorbell cameras) whenever someone approaches your door?
**Version**
Please include the version of HOOBS you are using.
4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [√ ] No

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [√ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [√ ] HOOBS Box

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Govee 
Simplisafe3
TpLink
Tuya Web 
myQ

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "accessories": [],
    "platforms": [
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "name": "Home Alarm",
            "sensorRefresh": 15,
            "auth": {
                "username": "",
                "password": ""
            },
            "cameras": true,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "debug": true
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
7/14/2021, 1:29:49 PMSimplisafe3 BridgeHome AlarmERRORSensor refresh received an error from the SimpliSafe API: {
  type: 'GatewayTimeout',
  message: 'The message timed out connecting to the base station.',
  code: '009',
  statusCode: 504,
  props: {}
```

**Additional context**

**Comment by mkellsy** [comment]
I don't have a SimpliSafe system to test with, however I would assume if the plugin supports cameras, it should show on your Apple TV.

Does the camera show in your Apple Home app? You can check this on your iPhone, iPad or a Mac.

Also the 504 error in your log leads me to believe you might have a config error. Check the any IP addresses in your config. You may have to make a static lease for your SimpliSafe hub on your router.

I hope this helps.

**Comment by michaelromero2020** [comment]
Thanks, @mkellsy I enabled FFMPEG, restarted HOOBS but it still isn't working. 

I don't think Google Fiber allows me to set static IPs for individual devices. All I saw as an option for port forwarding but it doesn't seem like that's the right solution.

**Comment by michaelromero2020** [comment]
In the config for the plugin do i need to have the ffmepg path filled out? 

![Screen Shot 2021-07-15 at 1 53 21 PM](https://user-images.githubusercontent.com/87102150/125841891-30facdc4-0bc2-4bd4-bbc3-9dbc794db2ba.png)

**Comment by michaelromero2020** [comment]
Update: since adding the ffmpeg in terminal I am unable to see video on the home app. 

Still no video from doorbell on Apple TV

**Comment by mkellsy** [comment]
You can try /usr/bin/ffmpeg or /usr/local/bin/ffmpeg for the path

**Comment by michaelromero2020** [comment]
No luck @mkellsy 

Is there a way to disable the ffmpeg? Before installing that I was able to view the cameras in the Home app.

**Comment by mkellsy** [comment]
```
sudo hbs extension rm ffmpeg
```
