### ISSUE TITLE
Hoobs 4 Migration Failed

### ISSUE THREAD

**Issue by DaDD65** [hoobs-org/HOOBS#1384]
**Description**

**Version**
3.3.12

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
cannot access
* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
There was an option to update/migrate to Ver 4.  I clicked on it and the it started migrating.  After about 10 minutes hoobs became inaccessible.  Tried multiple time to get to hoobs.local interface. Restarted box but still no access.  I can ssh in via putty.
Tried to follow steps here...
https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a
Fails here
hoobs@hoobs:~ $ sudo apt install -y hoobsd hoobs-cli hoobs-gui helm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package hoobsd
E: Unable to locate package hoobs-cli
E: Unable to locate package hoobs-gui
E: Unable to locate package helm

At a loss at this point?

**Comment by mkellsy** [comment]
If the migration failed, try rebooting. The migration will try again until it succeeds.

**Comment by DaDD65** [comment]
Tried a number of times but nothing.  Going to format flash with ver. 4 and start fresh.

**Comment by jlg89** [comment]
Yeah, it definitely takes awhile. If you can SSH into the box, "tail -f /var/log/syslog" and watch for updates from the "migrate" process. If nothing's happening, reboot.
