### ISSUE TITLE
Installed plugins unavailable after migrating to v4

### ISSUE THREAD

**Issue by jrwilson99** [hoobs-org/HOOBS#1386]
**Description**
I migrated to v4 yesterday. Eventually the upgrade/migration finished, I assume, because I couldn't see anything any more.  It took me a while to figure out how to get back in via the web (my bookmark gave me the login, but then a blank screen). I also got the MacOS app installed and logged in.  From what I could tell, everything was/is working. Homekit still sees the accessories.
However, when I go to Plugins -> HOOBS, all I see is the message "No plugins installed. Install Plugin".   I've done some reboots, but no difference.  I haven't tried adding a new plugin. 

**Version**
4.0.87

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Previous version**
3.3.13, I think.  It was latest version yesterday

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No
- ?   Maybe, but I don't remember, sorry. 

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install. ( HOOBS Image )

**If this is a custom install, what's your operating system?**
Raspberry Pi 4b

**List your plugins**
'homebridge-denon-quickselect'
'homebridge-dummy'
'homebridge-marantz-volume'
'homebridge-myq2'
'homebridge-roomba2'
'homebridge-zp'

**Post your config**

```
{
    "server": {
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY0YTO",
        "polling_seconds": 5,
        "origin": "*",
        "port": 80
    },
    "client": {
        "default_route": "status",
        "latitude": "34.1505",
        "temp_units": "fahrenheit",
        "locale": "en",
        "theme": "hazed-infused",
        "country_code": "US",
        "postal_code": "91737",
        "inactive_logoff": 30,
        "longitude": "-117.5843"
    },
    "bridge": {
        "pin": "031-45-154",
        "name": "HOOBS",
        "username": “xxxx”,
        "port": 51826
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-denon-quickselect",
        "homebridge-marantz-volume",
        "homebridge-zp",
        "homebridge-myq2",
        "homebridge-dummy",
        "homebridge-roomba2"
    ],
    "accessories": [
        {
            "zone": 1,
            "plugin_map": {
                "plugin_name": "homebridge-denon-quickselect",
                "index": 0
            },
            "accessory": "denon-quickselect",
            "name": "Denon AppleTV",
            "quickselect": 1,
            "host": "192.168.4.135"
        },
        {
            "zone": 1,
            "plugin_map": {
                "plugin_name": "homebridge-denon-quickselect",
                "index": 0
            },
            "accessory": "denon-quickselect",
            "name": "Denon Sonos",
            "quickselect": 2,
            "host": "192.168.4.135"
        },
        {
            "plugin_map": {
                "plugin_name": "homebridge-marantz-volume",
                "index": 0
            },
            "accessory": "marantz-volume",
            "maxVolume": 80,
            "name": "Denon Volume",
            "host": "192.168.4.135"
        },
        {
            "reverse": false,
            "accessory": "DummySwitch",
            "stateful": true,
            "name": "MotionLiteAllowed",
            "time": 1000,
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "resettable": false
        },
        {
            "accessory": "Roomba2",
            "plugin_map": {
                "plugin_name": "homebridge-roomba2",
                "index": 0
            },
            "dockContactSensor": true,
            "name": "Jeeves",
            "model": "i6+",
            "blid": “xxx”,
            "robotpwd": “xxx”,
            "ipaddress": "192.168.4.33",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "runningContactSensor": true,
            "binContactSensor": true,
            "cacheTTL": 30
        }
    ],
    "platforms": [
        {
            "resetTimeout": 500,
            "service": "fan",
            "name": "Sonos-Zp",
            "tv": false,
            "excludeAirPlay": true,
            "speakers": true,
            "leds": false,
            "platform": "ZP",
            "plugin_map": {
                "plugin_name": "homebridge-zp"
            },
            "maxFavourites": 96,
            "timeout": 15,
            "forceS2": false,
            "brightness": false,
            "nameScheme": "% Sonos",
            "subscriptionTimeout": 30,
            "alarms": false
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
7 (Return) (Live 10/13/1982)"
7/15/2021, 7:35:11 PMWARNINGdevice reboot command received
7/15/2021, 7:35:11 PMHOOBS stopping
7/15/2021, 7:35:12 PMHOOBSSonos-Zpclosed http://0.0.0.0:38515/notify
7/15/2021, 7:35:13 PMHOOBSSonos-Zpgoodbye
7/15/2021, 7:35:34 PMhub is running on port 80
7/15/2021, 7:35:36 PMHOOBS starting
7/15/2021, 7:35:39 PMHOOBSLoaded plugin 'homebridge-denon-quickselect'
7/15/2021, 7:35:39 PMHOOBSLoaded plugin 'homebridge-dummy'
7/15/2021, 7:35:39 PMHOOBSLoaded plugin 'homebridge-marantz-volume'
7/15/2021, 7:35:39 PMHOOBSLoaded plugin 'homebridge-myq2'
7/15/2021, 7:35:40 PMHOOBSLoaded plugin 'homebridge-roomba2'
7/15/2021, 7:35:40 PMHOOBSLoaded plugin 'homebridge-zp'
7/15/2021, 7:35:40 PMHOOBSLoading 1 platforms...
7/15/2021, 7:35:40 PMHOOBSSonos-Zphomebridge-zp v1.3.3, node v14.17.2, homebridge v1.3.4, homebridge-lib v5.1.9
7/15/2021, 7:35:40 PMHOOBSLoading 2 accessories...
7/15/2021, 7:35:40 PMHOOBSMotionLiteAllowedSetting switch to false
7/15/2021, 7:35:40 PMHOOBSJeevesEnabling keepAlive
7/15/2021, 7:35:40 PMHOOBSSonos-Zprestored 2 accessories from cache
7/15/2021, 7:35:40 PMHOOBSBridge is running on port 51826.
7/15/2021, 7:35:41 PMHOOBSSonos-Zplistening on http://0.0.0.0:37561/notify
7/15/2021, 7:35:41 PMHOOBSSonos-ZpRINCON_000E5830FD0801400 [Patio]: associated S1 zone player
7/15/2021, 7:35:41 PMHOOBSSonos-Zpfound 2 S1 zone players in 2 zones
7/15/2021, 7:35:41 PMHOOBSSonos-Zp├─ Garage
7/15/2021, 7:35:41 PMHOOBSSonos-Zp│  └─ RINCON_000E5830573E01400 [Garage]: Sonos Connect:Amp (ZP120) (master, audioIn)
7/15/2021, 7:35:41 PMHOOBSSonos-Zp└─ Patio
7/15/2021, 7:35:41 PMHOOBSSonos-Zp   └─ RINCON_000E5830FD0801400 [Patio]: Sonos Connect:Amp (ZP120) (master, audioIn)
7/15/2021, 7:35:42 PMHOOBSJeevesRunning status requested
7/15/2021, 7:35:42 PMHOOBSJeevesBattery status requested
7/15/2021, 7:35:42 PMHOOBSJeevesBattery level requested
7/15/2021, 7:35:42 PMHOOBSJeevesCharging status requested
7/15/2021, 7:35:42 PMHOOBSJeevesDocked status requested
7/15/2021, 7:35:42 PMHOOBSJeevesRunning status requested
7/15/2021, 7:35:42 PMHOOBSJeevesBin status requested
7/15/2021, 7:35:42 PMHOOBSSonos-ZpGarage Sonos: get Remaining Duration: return 0s
7/15/2021, 7:35:42 PMHOOBSSonos-ZpPatio Sonos: get Remaining Duration: return 0s
7/15/2021, 7:36:01 PMHOOBSSonos-ZpWARNINGwarning: heartbeat 9, drift 10495
7/15/2021, 7:36:01 PMHOOBSSonos-ZpWARNINGwarning: heartbeat 10, drift 9497
7/15/2021, 7:36:01 PMHOOBSSonos-ZpWARNINGwarning: heartbeat 11, drift 8498
```

**Additional context**

**Comment by mkellsy** [comment]
If the migration failed on plug-in installs, reboot it will try again until it succeeds

**Comment by jrwilson99** [comment]
The plug-ins are installed and working.  The problem is that they do not show on the Plug-in -> HOOBS screen.

-jack

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jrwilson99** [comment]
Here are some screenshots.
<img width="739" alt="HomeKit" src="https://user-images.githubusercontent.com/61249889/125991343-3f78d2b3-6fa4-4404-a5df-e71f4d15af2f.png">
<img width="1189" alt="Plugins" src="https://user-images.githubusercontent.com/61249889/125991348-ccc229d5-3881-4237-aecb-0b84613b5186.png">
<img width="1189" alt="Accessories" src="https://user-images.githubusercontent.com/61249889/125991353-8fafced2-0ad2-460f-b712-80cc4be70374.png">

**Comment by mkellsy** [comment]
Can you open the terminal and run this.

cat /var/lib/hoobs/hoobs/package.json

post the results.

**Comment by jrwilson99** [comment]
hoobs@hoobs:~ $ cat /var/lib/hoobs/hoobs/package.json 
{
    "name": "plugins",
    "description": "HOOBS Plugins",
    "private": true,
    "dependencies": {
        "hap-nodejs": "^0.9.4",
        "homebridge-denon-quickselect": "^0.3.0",
        "homebridge-dummy": "^0.5.0",
        "homebridge-marantz-volume": "^1.6.3",
        "homebridge-myq2": "^2.1.11",
        "homebridge-roomba2": "^1.2.0",
        "homebridge-zp": "^1.3.3"
    }
}
hoobs@hoobs:~ $

**Comment by adrianopery** [comment]
to use terminal is requesting user and password.
What I can use?

**Comment by mkellsy** [comment]
It looks like the plugins are there. The only other reason why the plugins wouldn't show up is, your device is not connected to the internet. We don't store plugin details on the device and use our plugins site for this. https://plugins.hoobs.org.

**Comment by jrwilson99** [comment]
Which device do you mean, the HOOBS host?  It shows current weather and forecast on your Dashboard, and the Plugins -> Library section works - I'm able to drill in to various plugins to get info on them.  I assume that this means the HOOBS device has access to the internet.

**Comment by jrwilson99** [comment]
Any ideas on getting the plugins screen working?
I have a couple suggestions I could try - if you don’t think it would make things worse:
I could try adding another plugin and then maybe the missing plugins might reappear, or I could just remove all the plugins and then re-add them. 
Let me know.

**Comment by jrwilson99** [comment]
FYI, I’ve updated the Mac app and HOOBS to the latest versions, as of today, and still no change.

From: Michael Kellsy ***@***.***>
Date: Sunday, July 18, 2021 at 08:36
To: hoobs-org/HOOBS ***@***.***>
Cc: jrwilson99 ***@***.***>, Author ***@***.***>
Subject: Re: [hoobs-org/HOOBS] Installed plugins unavailable after migrating to v4 (#1386)

It looks like the plugins are there. The only other reason why the plugins wouldn't show up is, your device is not connected to the internet. We don't store plugin details on the device and use our plugins site for this. https://plugins.hoobs.org<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplugins.hoobs.org%2F&data=04%7C01%7C%7C742fb226f389401f8cf908d94a01dd64%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637622194132540716%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OWQgwgbNgaPJmpuN%2BCGthV3eJNzC6tdW1Wuu6QMaeJ8%3D&reserved=0>.

**Comment by jrwilson99** [comment]
I ended just doing a factory reset and re-adding everything back in.

**Comment by mkellsy** [comment]
4.0.100 fixes the plugins not showing up issue.
