### ISSUE TITLE
Connexoon, odd bug since last release

### ISSUE THREAD

**Issue by Biggsylad** [hoobs-org/HOOBS#1388]
Hi Guys

I have been using the Connexoon plugin for RTS equipment pretty much since day 1, all has been fine until the last release. When I drop into the accessories page, it's defaulting to open which triggers the garage door to do just that. I stopped and restarted the bridge and rebooted the PI, but it's still doing the same thing. I would consider the plugin as the problem, but it hasn't changed in quite a long time, but I did get a couple of updates last night. Cleared the Acc cache as well on the bridge

Plugin Details - https://github.com/yenoiwesa/homebridge-connexoon#readme
http://hoobs.local/plugin/homebridge-connexoon

Hoobs V 4..0.87

**Comment by mkellsy** [comment]
See if 4.0.92 helps

**Comment by Mike-Stark-Barnes** [comment]
Same issue for me. Normally the logs would show the current and target states for my three blinds (so 6 instances) but now HOOBS is regularly sending the 'open' command to all blinds, overriding any change I make either via Apple's Home App, the Connexoon App or via the physical remote.

**Comment by Biggsylad** [comment]
That has stopped the issue, I am able to navigate to accessories with out the garage door opening, thanks. One issue, the icon shows as orange when closed which makes sense but control to move it up and down is on the wrong end. Door is closed, the dot should be at the bottom, door is open and the dot should be at the top but not showing orange. Ridiculous I know and not urgent but also cockle be right?

**Comment by Biggsylad** [comment]
> Same issue for me. Normally the logs would show the current and target states for my three blinds (so 6 instances) but now HOOBS is regularly sending the 'open' command to all blinds, overriding any change I make either via Apple's Home App, the Connexoon App or via the physical remote.
> Just to add a bit more context; I was on the HOOBS log page with all blinds open, I then closed one of my blinds via Apple's Home app and it stayed closed for several minutes. I then went to the HOOBS Dashboard page that incorrectly showed all three of my blinds as open and then suddenly the blind I'd previously closed started to open. There just doesn't seem to be a consistent link between the states shown in the HOOBS Dashboard and Apple Home etc, and once HOOBS realises that there's a difference it will set the blinds based on the Dashboard settings (which are potentially wrong) despite what you may have requested from Apple Home.

I think this is a limitation on RTS which somofy uses to control doors, it isn’t two way so it can’t tell Hoobs and HK whee it is. Which is odd as the plugin does show a 0 or 100 but this seems to be a problem with the plugin not hoobs

**Comment by Mike-Stark-Barnes** [comment]
Mmm….worked fine for me under V3, but hasn’t worked correctly under V4 so far. Initially I had the issue of the HOOBS dashboard showing the incorrect visual representation of the blinds position (like what you’ve mentioned re your garage door), however, opening and closing the blinds via the Apple Home app still worked worked fine, so only a superficial problem  (although it did break my use of IF statements with Flic buttons for controlling the blinds), but now it seems that the dashboard isn’t updating based on any actions made in Apple Home and is then causing problems for me when what it believes the position to be doesn’t align with what Apple Home shows. They could just be out of sync with each other but I can’t see how to get them both realigned as whichever one I use causes issues with the other.

**Comment by Biggsylad** [comment]
> Mmm….worked fine for me under V3, but hasn’t worked correctly under V4 so far. Initially I had the issue of the HOOBS dashboard showing the incorrect visual representation of the blinds position (like what you’ve mentioned re your garage door), however, opening and closing the blinds via the Apple Home app still worked worked fine, so only a superficial problem (although it did break my use of IF statements with Flic buttons for controlling the blinds), but now it seems that the dashboard isn’t updating based on any actions made in Apple Home and is then causing problems for me when what it believes the position to be doesn’t align with what Apple Home shows. They could just be out of sync with each other but I can’t see how to get them both realigned as whichever one I use causes issues with the other.

I have never seen that work, open the door via HK never reflected in hoobs but oddly the logs for the door position reports 0 for closed and 100 for open….. it’s not a huge issue and the initial issue has been fixed all be it with the icon the wrong way round :)

**Comment by mkellsy** [comment]
Can someone attach a screenshot. I think I know what's going on, but I need to see it.

**Comment by Mike-Stark-Barnes** [comment]
Specifically what do you need a screenshot of?
Just to add, I removed the blinds from my HOOBS dashboard earlier today and so far (touch wood) it hasn’t done it since; there aren’t any instances in the Connexoon app history but it might just be a coincidence. I’ll see what happens over the next day or so and will re comment if it starts happening again.

**Comment by Biggsylad** [comment]
I can give you scenarios and corresponding log entries and if HK and Hoobs reflect one another?
Will be tomorrow now but happy to put it together

**Comment by Mike-Stark-Barnes** [comment]
Just to update, everything seems fine for me today since removing the blinds from my dashboard. Just to illustrate what was happening yesterday please see the attached screen grab from HOOBS which shows the regular 'open' command being sent to the Connexoon Hub every few minutes. Today the log looks normal i.e. 3 blinds each with a get current position and get target position log and nothing else.
![IMG_0306](https://user-images.githubusercontent.com/61647804/126296260-cfcd26db-4746-4346-b7b8-76d2437a5957.jpg)
