### ISSUE TITLE
Docker V3.2 to Rpi V4.0

### ISSUE THREAD

**Issue by delucs** [hoobs-org/HOOBS#1389]
**Description**
I installed a fresh 3.3.5 on an RPi, then restored the docker back-up and did all updates, now 3.3.12 on RPi but no upgrade to V4 button in restored backup from Docker to RPi? RPi still says its a Docker in the about? how do I force upgrade from  V3.3.12 to V4.0 and remove the Docker in the "about"

**Version**
Please include the version of HOOBS youker tousing.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
We haven't released a Docker image yet.

You can setup your own image.
First you will need a 4.0 backup of your current setup.
You will need to access your current container with SSH
https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

Then generate a 4.0 backup file with these commands.
```
sudo npm install -g @hoobs/migration
```
Then run the migration in transfer mode
```
cd ~/ && sudo hbs-migrate -t
```
This will create a file in your home directory called `migration.zip`
You can transfer this file to your computer with SCP. The Mac Terminal or Windows PowerShell support SCP.
```
scp hoobs@hoobs.local:~/migration.zip ./
```

Then start with a Debian or Ubuntu Docker image. Then log into your new container with SSH.
Then follow these steps to install HOOBS on the container.
https://support.hoobs.org/docs/60e9f2ecdea381a881af7237

I am marking this closed because the Docker image is already in our pipeline.

**Comment by delucs** [comment]
I think you misunderstood. I do not want a Docker anymore (btw no ssh on docker), i want to go back to RPi but i am stuck... the restored and upgraded RPi says its still a Docker ar v3.3.12... it is working but i see no button to upgrade to V4.0

**Comment by mkellsy** [comment]
Remove the system variable in the config.json

**Comment by delucs** [comment]
Thanks @mkellsy , ""docker" has now dispappeared in the "about", but still no upgrade path/button to V4, how can I force upgrade?
![2021-07-20_09h12_42](https://user-images.githubusercontent.com/7610744/126277980-65671bc5-e185-42ac-9bb6-99f054080954.png)

**Comment by mkellsy** [comment]
4.0 has only been released for Raspberry Pi for now. The instructions above are the only way to migrate for non arm processors.

you can access the terminal from within HOOBS.

**Comment by delucs** [comment]
@mkellsy i am on a Rpi 3b, the screenshot is from it? But i can't get to v4. I don't need Docker anymore 😊

**Comment by delucs** [comment]
@mkellsy I made some more tests: on a new SD card I installed V.3.3 image, then upgraded o V3.3.12... I then see the button to upgrade to V4... but instead I then restore my backup , then the upgrade button disappears and the Rpi says its up to date (see above screenshot, except that I am now on node 14.17.1) How can I force upgrade to V4? (should be possible, no?)
