### ISSUE TITLE
Homebridge Roomba STV Not Easy on HOOBS

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#139]
tried to install roomba plugin

https://github.com/esteban-mallen/homebridge-roomba-stv

installation work but at 
https://github.com/esteban-mallen/homebridge-roomba-stv#2-find-robotpwd-and-blid

he gets following error:

> npm ERR! path /home/hoobs/package.json
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall open
> npm ERR! enoent ENOENT: no such file or directory, open '/home/hoobs/package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/hoobs/.npm/_logs/2019-09-08T19_04_33_760Z-debug.log

we tried to install git and load needed repo
 https://github.com/koalazak/dorita980

but also errors on npm install:

> npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
> npm WARN deprecated   npm i nyc
> npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
> npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3

**Comment by mkellsy** [comment]
How are you installing this plugin?
Are you using HOOBS 2.1.1?

If so, it looks like there docs are a bit wrong
1. sudo npm install -g **--unsafe-perm** homebridge-roomba-stv
2. **cd /usr/local/lib/node_modules/homebridge-roomba-stv** (Navigate to the plugin folder)
3. sudo npm run getrobotpwd `192.168.xx.xx` (Your romba's IP address)

The warnings you are getting are deprecated packages, not to worry, but they should update the plugin.

**Comment by mwhaley99** [comment]
I am running v3.0.0 beta 69

 

I was able to use the steps below, but after I added one of the Roomba’s to the Accessories section, Hoobs starts up and then shutsdown.

 

Mark

**Comment by mkellsy** [comment]
Moved to issue #97

**Comment by askovi** [comment]
> How are you installing this plugin?
> Are you using HOOBS 2.1.1?
> 
> If so, it looks like there docs are a bit wrong
> 
> 1. sudo npm install -g **--unsafe-perm** homebridge-roomba-stv
> 2. **cd /usr/local/lib/node_modules/homebridge-roomba-stv** (Navigate to the plugin folder)
> 3. **sudo** npm run getrobotpwd `192.168.xx.xx` (Your romba's IP address)
> 
> The warnings you are getting are deprecated packages, not to worry, but they should update the plugin.

I just applied this to a customer through remote support and it worked fine. However that command on step3 should theoretically be ran by the plugin itself when certified

**Comment by mkellsy** [comment]
Yes. The command and IP search should be done by the plugin.
