### ISSUE TITLE
Install deCONZ no longer available?

### ISSUE THREAD

**Issue by thbenedicto** [hoobs-org/HOOBS#1390]
Hi! Installing deCONZ on the same PI as Hoobs is no longer available?

I looked for all the documentation and I couldn't find more.

**Comment by EddieDSuza** [comment]
here is the command to install deCONZ

`wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/main/scripts/deconz-phoscon-hoobs.sh | sudo bash -`
