### ISSUE TITLE
Wrong german translation

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1392]
Hey there is a wrong german translation.
The word "clear" is translated to "klar" (wich not only means clear - in case of a clear window, it also means "of cause") and not to "löschen".

That could cause some miss-understanding in case of clear the cache or clear the notifications ;)

**Comment by BobbySlope** [comment]
Changed in Loco translation, @mkellsy 
Please update with next gui version

**Comment by mkellsy** [comment]
Fixed in next release
