### ISSUE TITLE
QR Code not appearing on dashboard 

### ISSUE THREAD

**Issue by Paulbehrhorst** [hoobs-org/HOOBS#1395]
**Description**
When I opened my dashboard for the first time (and every time since) the QR code does not appear and I cannot connect to my HomeKit. 

**Version**
4.0.87

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Comment by mkellsy** [comment]
Go the the Bridges screen and select the bridge you want to pair.
