### ISSUE TITLE
Hue Bridge Added But No Accessories 

### ISSUE THREAD

**Issue by DaDD65** [hoobs-org/HOOBS#1399]
**Description**
I added the Hue plugin.  Pressed the link button to get the bridge to start.  Not sure what to do on the config tab.  No Hue bulbs 
 in accessories appear

**Version**
4.0.87

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Ring
Hue
Govee
SmartLife
Wemo

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Go to the Config screen and then the Hue section. There is an option to **Expose Lights**.
Check this to show your lights in HOOBS.

**Comment by DaDD65** [comment]
Done. Thanks
