### ISSUE TITLE
The Ring plugin auto updates this. This is fixed in 4.0.92

### ISSUE THREAD

**Issue by yagowaf** [hoobs-org/HOOBS#1401]
The Ring plugin auto updates this. This is fixed in 4.0.92

In the config the refresh token is provided by Ring.
Click Link Account, enter in your Ring username and password.
Ring will send you a temp code. Enter that and then the refresh token will be added for you.

If you don't see the Link Account button. You may need to re-install the plugin.

_Originally posted by @mkellsy in https://github.com/hoobs-org/HOOBS/issues/1397#issuecomment-882135279_

**Comment by yagowaf** [comment]
After update still not able to get ring refresh token.  after email and password is entered splash screen just sit there with no action. #

**Comment by yagowaf** [comment]
> The Ring plugin auto updates this. This is fixed in 4.0.92
> 
> In the config the refresh token is provided by Ring.
> Click Link Account, enter in your Ring username and password.
> Ring will send you a temp code. Enter that and then the refresh token will be added for you.
> 
> If you don't see the Link Account button. You may need to re-install the plugin.
> 
> _Originally posted by @mkellsy in [#1397 (comment)](https://github.com/hoobs-org/HOOBS/issues/1397#issuecomment-882135279)_

**Comment by yagowaf** [comment]
Hi bobby,

After update still not able to get ring refresh token. after email and password is entered splash screen just sit there with no action.

**Comment by mkellsy** [comment]
Please use issue #1397
