### ISSUE TITLE
Where is the wiki?

### ISSUE THREAD

**Issue by Calorion** [hoobs-org/HOOBS#1404]
I was directed to the setup instructions at https://github.com/hoobs-org/HOOBS/wiki/2.5.0-macOS-Installation, but they (and the entire wiki) seem to be missing. Could we get them reactivated please? Thanks!

**Comment by BobbySlope** [comment]
We moved everything to support.hoobs.org/docs

**Comment by BobbySlope** [comment]
You can follow this:

https://support.hoobs.org/docs/60e9f2ecdea381a881af7237

**Comment by Calorion** [comment]
Have you removed Mac support, then?

**Comment by Calorion** [comment]
@BobbySlope Have you removed Mac support then?
