### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by cleanev** [hoobs-org/HOOBS#1407]
**Description**
High CPU usage and many hoobs services running
**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
3.3.5

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi OS  5.10.17-v7l+ #1421 SMP
**List your plugins**
Ring
Bond

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "autostart": 0,
        "home_setup_id": "X-HM://0023TFYTUS5M0",
        "polling_seconds": 5,
        "origin": "*",
        "docker": true
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "zipcode"
    },
    "bridge": {
        "name": "hubz",
        "port": 51826,
        "pin": "123-45-678",
        "username": "MAC Address"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-bond",
        "homebridge-ring"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Bond",
            "bonds": [
                {
                    "ip_address": "10.x.x.x",
                    "token": "redacted token"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-bond"
            },
            "include_dimmer": false,
            "fan_speed_values": true,
            "include_toggle_state": false
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "redacted token",
            "hideDoorbellSwitch": true,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "showPanicButtons": false,
            "hideCameraMotionSensor": true,
            "hideInHomeDoorbellSwitch": true
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Before upgrade Raspberry Pi 4B used to run under 10% usage, since upgrade CPU usage is consistently above 60%. Snapshot of htop attached. Guidance to bring this down will be appreciated.

![81B66229-7F0D-4E73-BBA5-5C3F5CC98DD5](https://user-images.githubusercontent.com/45519661/126411229-13724bc0-c9bc-4269-9ca2-3ad508acce7c.jpeg)

**Comment by BobbySlope** [comment]
Are you running the latest hoobs4 version?

**Comment by cleanev** [comment]
Hello @BobbySlope - yes I am running latest version 4.0.92 as shown in attached snapshot.

One additional item to note is while CPU% under line chart shows at the moment percentage down below in table CPU is shown as 0%.
![D531E14E-C50C-4603-BF02-9743C83241D7](https://user-images.githubusercontent.com/45519661/127047983-9a81157c-c42c-47da-aa23-4c9c0785747f.jpeg)

**Comment by cleanev** [comment]
Looks like the latest version ver 4.0.98 took care of high CPU usage. Now Pi is running at 1-2% and quite cool at 45-47C instead of constant 55C+. Additionally this version took care of CPU percentage showing 0% in System Info widget. Now CPU usage is reflected correctly.

Thanks for all the hard work.
![IMG_0665](https://user-images.githubusercontent.com/45519661/127756026-f73dc1ec-05c1-4c50-95c0-3d42659a9df1.jpeg)
![IMG_0666](https://user-images.githubusercontent.com/45519661/127756031-3824cfd2-d90d-43bc-ba2e-b93abca52155.jpeg)

**Comment by cleanev** [comment]
Short lived as something on the system got updated in last couple days getting CPU to run close to 60% again
![IMG_0675](https://user-images.githubusercontent.com/45519661/128560455-605113d1-feed-41fd-a952-29e7bbbfdbc8.jpeg)
