### ISSUE TITLE
Plug-and-play not working @my place :-(

### ISSUE THREAD

**Issue by KSWDK** [hoobs-org/HOOBS#1408]
Hi,

Just received my Hoobs in a box, plugged it into my Unify switch and powered up and next nothing, inside I can see red light flashing for a while and then nothing. It's not visible on my network so no IP.
I tried to set it up via WIFI, but no SSID is visible :-(

All input's are welcome!

**Comment by BobbySlope** [comment]
Pleas reach out to us via email info@hoobs.com and send a copy of your order (invoice) we either can fix it via remote support or we will replace the unit

**Comment by KSWDK** [comment]
No need to now :-) I found the power cord was not working properly it disconnected temporary, after replacing it everything work perfectly!

Best Regards Ken



Den 21. jul. 2021 kl. 15.32 skrev BobbySlope ***@***.***>:


Closed #1408 <https://github.com/hoobs-org/HOOBS/issues/1408>.
