### ISSUE TITLE
Homebridge firbaro hc2 no longer loading since upgrade

### ISSUE THREAD

**Issue by activ** [hoobs-org/HOOBS#1409]
**Description**
The plugin will not load, the log file gives me:
7/21/2021, 3:55:11 PMHOOBSErrorError loading plugin "homebridge-eveatmo"7/21/2021, 3:55:11 PMHOOBSErrorCannot find module '/var/lib/hoobs/hoobs/node_modules/async/dist/async.js'. Please verify that the package.json has a valid "main" entry7/21/2021, 3:55:12 PMHOOBSErrorError loading plugin "homebridge-fibaro-hc2"

Looks like there is a dependency missing or something? I did try to reinstall, but that did not help (for this plugin, it did for some others)

**Expected behavoir**
The plugin should load and work, use to work fine before. 

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.
homebridge-fibaro-hc2

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.
Is this needed? It is listed as officially supported by hoobs. Just let me know.

**Version**
Please include the version of HOOBS you are using.
Hoobs 4.0.92
Node 14.17.2
Homebridge 1.3.4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
Latest 3 version, do not remember what was after the 3.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "accessories": [],
    "platforms": [
        {
            "platform": "OTGW",
            "name": "OTGW",
            "host": "192.168.1.5:8081",
            "otgw": "192.168.1.5:8081"
        },
        {
            "platform": "Ring",
            "refreshToken": "token"
        },
        {
            "platform": "eveatmo",
            "name": "eveatmo platform",
            "ttl": 540,
            "co2_alert_threshold": 1000,
            "auth": {
                "client_id": "id",
                "client_secret": "secret",
                "username": "username",
                "password": "secret"
            },
            "weatherstation": true,
            "airquality": true
        },
        {
            "platform": "Hue",
            "name": "Hue",
            "anyOn": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "lights": true,
            "linkButton": false,
            "sensors": true,
            "wallSwitch": false,
            "schedules": false,
            "scenes": false,
            "rules": false,
            "rooms": false,
            "group0": false,
            "groups": false,
            "forceEveWeather": false,
            "forceHttp": false,
            "users": {
                "secret": "secret"
            },
            "effects": true,
            "brightnessAdjustment": 100,
            "heartrate": 5,
            "lowBattery": 25,
            "timeout": 5,
            "waitTimePut": 50,
            "waitTimePutGroup": 1000,
            "waitTimeResend": 300,
            "waitTimeUpdate": 20
        },
        {
            "platform": "FibaroHC2",
            "name": "FibaroHC2",
            "host": "192.168.1.4",
            "username": "homebridge",
            "password": "secret"
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
7/21/2021, 3:55:11 PMHOOBSErrorError loading plugin "homebridge-eveatmo"7/21/2021, 3:55:11 PMHOOBSErrorCannot find module '/var/lib/hoobs/hoobs/node_modules/async/dist/async.js'. Please verify that the package.json has a valid "main" entry7/21/2021, 3:55:12 PMHOOBSErrorError loading plugin "homebridge-fibaro-hc2"
```

**Additional context**

**Comment by BobbySlope** [comment]
Try to install the plugin and use a new bridge. I was able to install it, but i can not configure it as i dont own an fibaro hc2

**Comment by activ** [comment]
Don't know why, but now that I have installed in on a separate instance it works. Perhaps it was a weir upgrade thing, case closed and thanks for the help.
