### ISSUE TITLE
Plugin Custom Storage Paths (.node-persist)

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#141]
I got some requests about which path can be used for plugins with a storage file. Maybe it should be added to the path overview.

Examples: homebridge-http-webhooks, homebridge-people

The path used by default from the above plugins: ./.node-persist/storage

**Comment by mkellsy** [comment]
Using the configuration path is best. This is the same thing as the StoragePath variable in Homebridge.
