### ISSUE TITLE
Hoobs/hoobs docker image latest version is 3.3.5

### ISSUE THREAD

**Issue by enrogue** [hoobs-org/HOOBS#1410]
Hello,

I am using the hoobs/hoobs image in docker on my Synology NAS. Latest version of this image has been at 3.3.5 for a while now. I think the latest 3.x version is now at 3.3.12 however. (never mind 4.x for now!)

That image used to update quite frequently to the latest versions. Is that image no longer being updated? If so should I be switching to another one that will continually have the updates?

Thanks!

R

**Comment by mkellsy** [comment]
We have released 4.0 on the Pi only for now.
Docker is coming when we get this wave of upgrades done.

I am closing this because this is already in our pipeline along with a macOS package too.
