### ISSUE TITLE
relays plugin no access to gpio

### ISSUE THREAD

**Issue by Maikysupra** [hoobs-org/HOOBS#1411]
**Description**
Yesterday I upgraded my HOOBS from v3 to the latest v4 and I've been unable make my 'Relays' plugin work since than.

**Expected behavoir**
The plugin is meant to operate a 8 channel relay module

**Plugin name**
Homebridge Relays

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
4.0.92

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [  ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
"accessories": [
        {
            "accessory": "Relay 1",
            "name": "Relay 1",
            "pin": 26
        },
        {
            "accessory": "Relay 2",
            "name": "Relay 2",
            "pin": 19
        },
        {
            "accessory": "Relay 3y",
            "name": "Relay 3",
            "pin": 13
        },
        {
            "accessory": "Relay 4",
            "name": "Relay 4",
            "pin": 6
        },
        {
            "accessory": "Relay 5",
            "name": "Relay 5",
            "pin": 12
        },
        {
            "accessory": "Relay 6",
            "name": "Relay 6",
            "pin": 16
        },
        {
            "accessory": "Relay 7",
            "name": "Relay 7",
            "pin": 20
        },
        {
            "accessory": "Relay 8",
            "name": "Relay 8",
            "pin": 21
        }
    ],

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
22/07/2021, 14:07:50HOOBS BridgeLoaded plugin 'homebridge-camera-ffmpeg'
22/07/2021, 14:07:50HOOBS BridgeLoaded plugin 'homebridge-nest'
22/07/2021, 14:07:50HOOBS BridgeLoaded plugin 'homebridge-relays'
22/07/2021, 14:07:50HOOBS BridgeLoading 4 platforms...
22/07/2021, 14:07:50HOOBS BridgeLoading 8 accessories...
22/07/2021, 14:07:50HOOBS BridgeCamera FFmpeg[Chicken Coop Camera] Configuring cached bridged accessory...
22/07/2021, 14:07:50HOOBS BridgeNestFetching Nest devices.
22/07/2021, 14:07:50HOOBS BridgeBridge is running on port 51826.
```

**Additional context**

**Comment by Maikysupra** [comment]
Thanks @BobbySlope, I've run the command but it didn't solve the issue. One thing that I noticed is that the 'home bridge-relays' doesn't show in the 'advanced' menu alongside all the other installed plugins.

**Comment by Maikysupra** [comment]
<img width="1264" alt="Screenshot 2021-07-31 at 10 13 35" src="https://user-images.githubusercontent.com/87820029/127735174-88ff257f-44ef-49d4-969c-5f055c5b05de.png">

**Comment by mkellsy** [comment]
This plugin doesn't have a graphical schema file.
Go to the Advanced section and then select the bridge you have this plugin installed on.
I am assuming you have this installed on the **Relays Bridge**.

**Comment by Maikysupra** [comment]
<img width="1039" alt="Screenshot 2021-08-03 at 10 52 05" src="https://user-images.githubusercontent.com/87820029/127996109-dd9af79a-87a4-4317-a91c-e70627ee1188.png">

**Comment by Maikysupra** [comment]
Thank you for clarifying that @mkellsy. I wasn't sure whether that might have anything to do with the problem. I attached my advanced set-up code.

**Comment by Maikysupra** [comment]
Basically, despite installing the Plugin and setting up the code in the Advanced section (as above), I do not seem to have any control over the relays as I did before. If everything worked, I should see the appropriate 8 Relay buttons in the 'Accessories' section what would allow me to toggle those relays. However this is not the case right now as I cannot see anyway of controlling those relays (see the below screenshot of my 'Accessories' page)

**Comment by Maikysupra** [comment]
<img width="1933" alt="Screenshot 2021-08-03 at 10 58 14" src="https://user-images.githubusercontent.com/87820029/127997019-4cc576f3-9a16-41e5-9767-11aa7dbbd897.png">
