### ISSUE TITLE
electra-smart plugin terminal command fails

### ISSUE THREAD

**Issue by gba215** [hoobs-org/HOOBS#1412]
Hi,

I'm trying to run a command from hoobs **version 4** terminal (to obtain token & imei) and get unknown command message. 

I have to login first to terminal using hoobs/hoobsadmin user name & password and then after writing that command I get the error.

In version 3 it was OK. The command in OK and approved by the developer.

It seems like I'm writing the command in the wrong place. How do I run this command properly in the terminal?

Thanks.

**Comment by BobbySlope** [comment]
Please provide more info:
Plugin?
Command you like to run?
What error do you get?

**Comment by gba215** [comment]
Plugin: Electra Smart
Command: electra-extract

I get unknown command error

**Comment by gba215** [comment]
Any idea?

**Comment by BobbySlope** [comment]
Was able to reproduce the issue. 
The command is probably stored in anonther path. @mkellsy can u take a look at it? Maybe build a sidecar?

**Comment by mkellsy** [comment]
I am assuming the bridge you installed this plugin on is called **electrasmartbridge**. If you installed this on a different bridge replace this in the commands below with the id of the bridge.

You can view the bridges and their ids with this command
```
sudo hbs bridge ls
```

Then go to the bridge's /bin folder
```
cd /var/lib/hoobs/electrasmartbridge/node_modules/.bin
```

Then you can run the command
```
electra-extract
```

If you get permission errors try running it with sudo
```
sudo electra-extract
```

**Comment by gba215** [comment]
Thanks but I tried and yet get "Command not found" although  'electra-extract' is exist under .bin directory.

What could be the problem?

**Comment by mkellsy** [comment]
Try this

node electra-extract

**Comment by gba215** [comment]
Works great! Thank you.
