### ISSUE TITLE
Better responsive views

### ISSUE THREAD

**Issue by vvdheuvel** [hoobs-org/HOOBS#1413]
**Is your feature request related to a problem? Please describe.**
The responsive views in Hoobs on tablet portrait and mobile should be reimagined. I don’t know how to say this less elegant but they suck.

**Describe the solution you'd like**
Better responsive column layout on breakpoint for mobile devices

**Describe alternatives you've considered**
Create and inject my own CSS but that’s not a sustainable the solution 

**Additional context**
Please make this a high priority it’s not a bug but it’s really annoying.

**Comment by BobbySlope** [comment]
Please attach screenshots. 
If you already solved it via css please provide us the css file so we can adjust it the same way

**Comment by vvdheuvel** [comment]
Best, Vincent

**Comment by BobbySlope** [comment]
You need to upload via git attachments via email dont work.

**Comment by vvdheuvel** [comment]
![image](https://user-images.githubusercontent.com/32132496/126807263-829acddc-da2b-4171-adad-386a47679a05.png)
