### ISSUE TITLE
Auto Restart Bridge Instance

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1414]
Is it possible to add a Auto Restart feature to the bridge instances? In case a bridge shuts down for any reason, the bridge will restart automatically.

**Comment by BobbySlope** [comment]
This is an useful enhancement
@mkellsy please take a look at it

**Comment by Christian-CFP** [comment]
Here as well for all viewers. I totally forgot the weekend and therefore wanted to apologize.

**Comment by mkellsy** [comment]
Bridges auto restart if they crash. Granted they run for more then 2 seconds.
I do this to prevent a bridge from restarting if it crashes on startup.

**Comment by Christian-CFP** [comment]
Thats cool. Didnt know thats already implemented.
