### ISSUE TITLE
Update in Loop

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1415]
4.0.93 and gui 4.0.76 are in loop. 
So I made the update and it seems to do so but after restart the Version is still 4.0.92 and it shows the same update again.

**Comment by Christian-CFP** [comment]
I cleared the cache, now the update is gon and it still shows 4.0.92 as the latest version.

**Comment by Christian-CFP** [comment]
Was that a mistake? With the 4.0.93 and 4.0.76?

**Comment by Christian-CFP** [comment]
Wow, no answer at all.
Why cant you just say it was an miss-happen and close this...
My high opinion of you guys is just going down step by step.

**Comment by BobbySlope** [comment]
We will investigate that

**Comment by Christian-CFP** [comment]
Hey @BobbySlope I know you guys are really under load but do not forget about the reportings ;)
Not for days. Love your work and your devotion.

**Comment by BobbySlope** [comment]
You opened this issue 2days ago so on weekend right? We also need to breath sometimes. We take all issues seriously. no commant does not mean we dont take care of it.

**Comment by Christian-CFP** [comment]
Totally agree. Sorry. Forgot about weekend. This corona times su...s. Sorry for that.

**Comment by Christian-CFP** [comment]
Really I am so sorry. ...
