### ISSUE TITLE
Raspberry Pi Power LED no longer lit after upgrade to Hoobs 4

### ISSUE THREAD

**Issue by Tom5640** [hoobs-org/HOOBS#1417]
Hello.  As above, migration to Hoobs 4 worked well, however I notice that since this installation, the power (red) status LED on my Raspberry Pi is off, even though the unit is on.  The green HDD/activity light still illuminates during activity.  The red power LED also illuminates as expected when the R/pi boots up, but is extinguished when the Hoobs application boots.  I cannot see an option to toggle the power LED in the options anywhere.  Please advise.

**Comment by EddieDSuza** [comment]
With version 4.0.90 - this is how the LED lights will represent the status of your Device. 

- Solid or blinking green, hoobsd is running
- Solid red, hoobsd has stopped with an error.
- No LEDs on, hoobsd has stopped without error, or device is off.

**Comment by Tom5640** [comment]
Thanks @EddieDSuza . To clarify at the moment the Pi appears to blink a green light at random intervals - like a hard drive activity light. All is as expected then? Tom

**Comment by EddieDSuza** [comment]
Yes - it is as expected and HOOBs is running without any issues. You can close this issue
