### ISSUE TITLE
Can't access terminal from within Web GUI any longer

### ISSUE THREAD

**Issue by SlasherKG** [hoobs-org/HOOBS#1420]
**Description**
Can't access terminal from within Web GUI any longer. Latest HOOBS 4.0.92.  I used to be able to access the new built-in terminal without issue, but now it just times out.  I have tried rebooting the device several times, but the same issue.

**Version**
4.0.92

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install
Raspberry Pi 3B

**If this is a custom install, what's your operating system?**
Raspbian

**List your plugins**
Ring
myQ
Wol
Bravia

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
How did u installed HOOBS? Did u follow the manual installation guide?

**Comment by SlasherKG** [comment]
Yes I did. Everything was working before. Not sure if it broke after updating to 4.0.92 from a lower 4.0 version though. I know it was working about a week or so ago.

**Comment by mkellsy** [comment]
Can you access http://hoobs.local:9090

**Comment by SlasherKG** [comment]
> Can you access http://hoobs.local:9090

Actually, I can.
Is this only supposed to work locally on the LAN?

I was trying it remotely and only had port 80 forwarded but am home now.
If I forward 9090 will it work?

**Comment by mkellsy** [comment]
Yep. The terminal is actually a different app called HelM. I separated this so you can still access the terminal when HOOBS can't start.

I would recommend that you don't forward the terminal port, as it could be a security risk.
