### ISSUE TITLE
Accessories persist after plugin deletion

### ISSUE THREAD

**Issue by TeslaOwnerTips** [hoobs-org/HOOBS#1421]
**Description**
Accessories continue to show up after the plugin is deleted. For example the TeslaFi plugin.

**Version**
Please include the version of HOOBS you are using.
Latest
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Not relevant. Easy to reproduce.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
Not relevant. Easy to reproduce.

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
Not relevant. Easy to reproduce.
**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```
Not relevant. Easy to reproduce.
**Additional context**

**Comment by BobbySlope** [comment]
You can clear cached accessories 
In UI -> bridges -> cache

**Comment by TeslaOwnerTips** [comment]
Thanks. Will I need to setup the accessories again in the iOS Home App?

**Comment by BobbySlope** [comment]
You can delete single accessories from cache there

**Comment by jbrinley5** [comment]
Anything from xfinity  I saw some updates I really want it on HomeKit
