### ISSUE TITLE
after installing new V4 on a system that also runs pihole everything is messed up

### ISSUE THREAD

**Issue by melliemuff** [hoobs-org/HOOBS#1423]
I did an update via hoobs interface (search for updates) and upgraded to V4 
hoobs came back and seemed to be working
pihole which is running on the same system was working, but I couldn‘t access its console 
I restarted the system in hope that would clear it

Now I can access pihole console but not hoobs console anymore 
     -  when entering hoobs.local it brings up a page generated by pihole that the website blocked „**because its not found on any blacklist**“ NO TYPO! 
     - when I explicitly whitelisted hoobs.local it brings me to the same website blocked page but there is no reason given anymore for blockage
     -  when entering <ip addr> I get a pihole page that says „did you mean to go to the admin panel“ - when clicking on it it brings me to the console
     -  hoobs is running - I can get to terminal via <ip add>:9090 and logon on 

is there a known issue with running hoobs V4 and pihole on same system? 

before I go back to V3 and start from scratch I wanted to know if there is a simple answer to this …

Thanks 

**Version**
V4   hoobs
Pi-hole v5.3.1-0-g4736e03

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
V3  - sorry dont‘t have the exact - about 6 month old

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [] Custom Install

**If this is a custom install, what's your operating system?**
debian V10

**List your plugins**
none 

**Post your config**
I don‘t have a config yet … this is more or less an empty system which I wanted to bring to newest version before starting to bring in my data

```
POST CONFIG HERE
```

**Post your log**

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
you need to change the port pi-hole is running on.
HOOBS needs to run on port 80

**Comment by BobbySlope** [comment]
https://raspberrypi.stackexchange.com/questions/52090/how-do-i-change-pi-holes-url-path#:~:text=There%20are%20many%20ways%20that,port%20number%20such%20as%208080%20.

**Comment by melliemuff** [comment]
thanks for the quick answer …

Cheers/Gruß 

„Adam war nichts als ein Rohentwurf, die Schöpfung des Menschen ist Gott erst völlig gelungen, als er Eva geschaffen hat.“ Simone de Beauvoir
