### ISSUE TITLE
I really want xfinity home on HomeKit I saw some updates got more stuff. Let me how do it

### ISSUE THREAD

**Issue by jbrinley5** [hoobs-org/HOOBS#1424]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mkellsy** [comment]
Go to the plugins screen and search for xfinity. There are plugins out there for this.

**Comment by jbrinley5** [comment]
Do it work
