### ISSUE TITLE
Ring Error connecting to API

### ISSUE THREAD

**Issue by DaDD65** [hoobs-org/HOOBS#1426]
**Description**
Ring plugin has stopped working.  Cameras in accessories and homekit are showing no response.  Updated the Ring plugin to 9.1.85, no change
**Version**
Please include the version of HOOBS you are using.
4.0.96
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
7/27/2021, 8:36:47 PMRing BridgeRingERRORRequest to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 404. Response body: 
7/27/2021, 8:36:47 PMRing BridgeRingERRORHTTPError: Response code 404 (Not Found)
7/27/2021, 8:36:47 PMRing BridgeRingERRORError connecting to API
:
```

**Additional context**

**Comment by mkellsy** [comment]
Already reported to homebridge-ring and they fixed it in the next plug-in update.
