### ISSUE TITLE
Can't seem to remember login/password

### ISSUE THREAD

**Issue by vinceh04** [hoobs-org/HOOBS#1427]
**Description**
I have tried about 20 different login and password combinations to get into the app with no luck.  Can log into puTTy just fine

**Version**
Please include the version of HOOBS you are using.
4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
None yet

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://                                                 0023ISYWY8PK2",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status"                                                 ,
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit                                                 ",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "CF:F6:00:99:                                                 27:BD"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": [],
    "package_manager": "npm",
    "system": "hoobs"

```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
I just got the Hoobs in box and went through the initial start up.  went to log in today and the system wouldn't take my login or password.  Is there a way to reset?  or add a user?
Thanks

**Comment by mkellsy** [comment]
You have two options. For both you will need to access the terminal.

To access the terminal follow this doc
https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

Then once you are logged into the terminal.

**Disable the Auth**
This is helpful if you have a tough time remembering passwords

```
sudo hbs config
```

Select **Hub**  
Then set the `"disable_auth": false` to `"disable_auth": true`.  
Then ctrl+x then y then enter to save.

**Reset the Users**
You can delete the access file

```
sudo rm -f /var/lib/hoobs/access
```

Then reboot
```
sudo shutdown -r now
```
