### ISSUE TITLE
Trying to run HOOBS in a Proxmox VM

### ISSUE THREAD

**Issue by yorkshirelandscape** [hoobs-org/HOOBS#1429]
Hi folks,

It feels a little weird creating a github issue to ask a question, but it sounds like that's how you do things. I just purchased Hoobs and was hoping to run it in a VM on my Proxmox machine. I'm wondering if anyone has tried anything similar, as I'm not having much luck. I've successfully converted the .img file to the qemu native qcow2 format, imported it and set it as the hard disk image for the VM I created. However, the VM won't boot off the image. I know the image is meant to be loaded onto an SD card and used in a Raspberry Pi and I presume the Pi boots from that SD card, so it seems like this should work. Anyone have any thoughts?

Thanks in advance.

**Comment by yorkshirelandscape** [comment]
Never mind. I just installed it manually. Was easier than the internet had led me to believe. Keep the donation, though. I'm glad you're around to help others.

**Comment by mkellsy** [comment]
Looks like you found the information before I got to this.
https://support.hoobs.org/docs/60e9f2ecdea381a881af7237

If you have a Debian based Linux distro, this should work.
