### ISSUE TITLE
Architecture Unavailable for Node

### ISSUE THREAD

**Issue by thecemeterygates** [hoobs-org/HOOBS#1430]
**Description**
Can’t connect to any form of hoobs.local. I’m using a pi zero w and a Mac running Catalina 10.15.7 to access HOOBS

**Version**
v3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**Additional context**
HOOBS is successfully installed, connected to WiFi and shows up on my router

**Comment by mkellsy** [comment]
Your router might not be allowing the .local address

You can try any of these
http://hoobs.local
http://hoobs
http://[ip address] (replace [ip address] with the ip address of the Pi Zero.

**Comment by thecemeterygates** [comment]
I tried those as well

**Comment by mkellsy** [comment]
See if you can access the terminal You can use this document for this. Note 3.3 doesn't have HelM.
https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

Once you are in the terminal. Run this
```
sudo systemctl status hoobs.service
```

This will tell you if it is running and will show if there are any errors.

Also check to see if Note is working
```
node -v
```

If you need to reinstall HOOBS
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by thecemeterygates** [comment]
After the first command I get “Unit hoobs.service could not be found”

After sudo node -v “Illegal instruction”

After the install command “Illegal instruction”

**Comment by mkellsy** [comment]
Hold on. I am working on creating an Armel .deb package for Node.

The issue you are having is the Pi Zero is ARMv6. Node doesn't officially support that CPU. I am working on getting HOOBS 4.0 installable on that architecture.

**Comment by mkellsy** [comment]
This should get you up and running on the Pi Zero. Note that the Pi Zero has a very low power CPU, so things will be slower.

## Step 1
Download a blank operating system. We created the MixerOS with includes the WiFi connection utility.
https://github.com/hoobs-org/hoobs-mixer/releases/download/v1.0.1/HOOBS-Mixer-1.0.1.zip

Then flash this to an SD Card using the balinaEtcher
https://www.balena.io/etcher/

## Step 2
Setup the repositories. Run this command

```
wget -qO- https://raw.githubusercontent.com/hoobs-org/cli/main/bin/armel | sudo -E bash -
```

## Step 3
Install HOOBS. You have 2 options here. 

**HOOBS 4.0**
Simply run this command

```
sudo apt install -y hoobs
```

**HOOBS 3.3**
This is a bit more involved. First install Node.

```
sudo apt install -y nodejs
```

Then install HOOBS

```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

Then setup the system to run HOOBS as a service

```
sudo hoobs service install
```
