### ISSUE TITLE
Hoobs 4 docker

### ISSUE THREAD

**Issue by Gavin123-code** [hoobs-org/HOOBS#1440]
Yes

**Comment by rafasamp** [comment]
Any news on this?

**Comment by dehness** [comment]
Still nothing?

**Comment by Gavin123-code** [comment]
No but i found an alternative flash hoobs to the pi and install docker and all of your container

**Comment by Gavin123-code** [comment]
Synology users: yea sorry

**Comment by JulianKropp** [comment]
Have a look here: [#1774 ](https://github.com/hoobs-org/HOOBS/issues/1774#issuecomment-1126948067)
