### ISSUE TITLE
Can’t update from 3.3.5 to 3.3.12

### ISSUE THREAD

**Issue by georgereinoso** [hoobs-org/HOOBS#1441]
**Description**
I click update from webUI and it never updates from 3.3.5 to 3.3.12

**Version**
3.3.5 on a raspberry 4 - running rasbian 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes, but long time ago when the 3.3.5 went out
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian GNU/Linux

**List your plugins**
all Hoobs certified, Ring, Alexa, Sensibo Ac, Tplink smartphone, Samsung Tizen

**Post your config**
Sorry tried to attached the image but can’t find how (I’m using an iPad at this moment)
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Can you post your logs?
