### ISSUE TITLE
All of my plugins have disappeared!

### ISSUE THREAD

**Issue by arohl** [hoobs-org/HOOBS#1443]
I am running Hoobs 4.0.98 (I upgraded to 4 from 3). It has been working perfectly until a couple fo days ago when my plugins disappeared (the plugins page says No plugins installed. Install Plugin). However my plugins are still working as can be seen from the log

05/08/2021, 11:09:18 pmHOOBS starting
05/08/2021, 11:09:24 pmHOOBSLoaded plugin 'homebridge-advanced-http-temperature-humidity'
05/08/2021, 11:09:24 pmHOOBSLoaded plugin 'homebridge-harmony'
05/08/2021, 11:09:25 pmHOOBSLoaded plugin 'homebridge-meross'
05/08/2021, 11:09:25 pmHOOBSLoaded plugin 'homebridge-pihole'
05/08/2021, 11:09:26 pmHOOBSLoaded plugin 'homebridge-platform-wemo'
05/08/2021, 11:09:26 pmHOOBSLoading 3 platforms...
05/08/2021, 11:09:26 pmHOOBSLoading 1 accessories...
05/08/2021, 11:09:26 pmHOOBSBridge is running on port 51826.
05/08/2021, 11:09:28 pmHOOBSTV-TV 1632 is running on port 42397.

and the accessories are visible in the home app and work as expected.

Any ideas?

**Comment by mkellsy** [comment]
Network glitch. The plugin data is cached.
Go to Menu -> Hub Settings then click Clear Cache.

The installed plugins should show back up.

**Comment by arohl** [comment]
Done all of the above but still no plugins!

**Comment by mkellsy** [comment]
Open the terminal and type this
```
sudo hbs plugin ls
```

**Comment by arohl** [comment]
hoobs@hoobs:~ $ sudo hbs plugin ls

```
bridge | name                                          | version | path
--------------------------------------------------------------------------------------------------------------------------------------------------
hoobs  | homebridge-advanced-http-temperature-humidity | 1.0.3   | /var/lib/hoobs/hoobs/node_modules/homebridge-advanced-http-temperature-humidity
hoobs  | homebridge-harmony                            | 1.5.3   | /var/lib/hoobs/hoobs/node_modules/homebridge-harmony
hoobs  | homebridge-meross                             | 5.0.3   | /var/lib/hoobs/hoobs/node_modules/homebridge-meross
hoobs  | homebridge-pihole                             | 0.3.5   | /var/lib/hoobs/hoobs/node_modules/homebridge-pihole
hoobs  | homebridge-platform-wemo                      | 3.3.1   | /var/lib/hoobs/hoobs/node_modules/homebridge-platform-wemo
```

**Comment by mkellsy** [comment]
That tells me that the backend is working, it's a display issue.
I will look into this.

**Comment by arohl** [comment]
I just tried a different browser (was using Safari; tried Firefox) but no plugins in both

**Comment by mkellsy** [comment]
I found the issue. It's the "homebridge-platform-wemo" plugin that's causing this. It was unpublished and moved to "homebridge-wemo". This was causing an error in the code.

I have a fix for this in testing, which will allow you to see and uninstall this plugin. If all goes well, we will be able to release this update next Tuesday.

**Comment by arohl** [comment]
Great! Does that mean I will be able to remove and then add the homebridge-wemo plugin to retain the demo functionality

**Comment by mkellsy** [comment]
Yes you will be able to remove the deleted plugin. You will need to copy the config from the old plugin first. You can get this from the Advanced section in the config screen.

If you want to get this sooner, you can switch to the edge branch. I don’t recommend this because we release to this branch faster and sometimes the code can break things. That’s why we have it, to prevent bad things from happening. If you wish to run on this branch, run this command.

sudo hbs system edge

to switch back to the stable branch

sudo hbs system stable

**Comment by arohl** [comment]
OK - have updated and can now see all the plugins. However to remove a plugin I believe I have to click on it to open its configuration and then click on remove. When I click on the memo plugin it just hangs with the I'm doing something animated icon. Is there another ay to delete?

**Comment by arohl** [comment]
OK - I had to update plugin as well - all seems to be working well now

Many thanks!

  Andrew
