### ISSUE TITLE
Cant see the QR code at the top left corner of the hoobs.local page

### ISSUE THREAD

**Issue by ayanmohanta** [hoobs-org/HOOBS#1444]
![Screenshot 2021-08-05 at 9 06 20 PM](https://user-images.githubusercontent.com/26746689/128381859-f8225f8d-af20-44b3-982e-77635fc45369.png)

**Comment by askovi** [comment]
In HOOBS 4 each bridge has its own QR code. Click on bridges in the left menu and select a bridge to see it.
