### ISSUE TITLE
Hoobs in a box can't log on

### ISSUE THREAD

**Issue by craigton** [hoobs-org/HOOBS#1445]
Hi my hoobs in a box froze during an update today and I now can't login. I can access via terminal on my mac *** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://192.168.1.73

HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Aug  5 12:40:35 2021 from fe80::1c84:fc23:e973:9fc1%eth0

after I type "sudo hoobs service log" I get

internal/util.js:1
ecma262/#sec-object.prototype.tostring
        ^^^^

SyntaxError: Unexpected identifier
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:285:18)
    at nativeModuleRequire (internal/bootstrap/loaders.js:315:14)
    at internal/bootstrap/node.js:51:23 

Any Idea where I go from here?

Regards

Craig.

**Comment by mkellsy** [comment]
What version are you running?
What device?

Looks like you are trying to run an armhf version on Node on an armel CPU.

**Comment by craigton** [comment]
I was running version 4 when and it was working fine I logged on using a few day ago using  the new desktop app it said there was an update which I started after about 45min to a hour it looked like it had froze so reload the desktop app and now I can't connect using hoobs.local or the desktop app. I have no idea what you mean when you say "armhf" and "armel CPU" I know a bit about Macs and can follow instructions using the terminal but the reason I brought HOOBS in a box was to keep it simple.
![D7758F34-9469-4CB8-B37E-CC8EF32CCD99](https://user-images.githubusercontent.com/73250232/128596123-2d876cd9-975c-4c0a-911a-47a160c80571.jpeg)
![0067F39C-5894-4683-84FF-8DCC8148C4B3](https://user-images.githubusercontent.com/73250232/128596131-4d532af3-1433-46ad-b409-05420130a5c7.jpeg)

**Comment by mkellsy** [comment]
Sounds like an SD Card failure.

Access the terminal
https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

Run this to see if hoobsd is running.
sudo systemctl status hoobsd.service

if not, from above it think not. You can get a new SD Card. Send an email to info@hoobs.org with your order number and a link to this issue.

**Comment by craigton** [comment]
This is what I got from the terminal on my Mac

hoobs@hoobs:~ $ sudo systemctl status hoobsd.service
● hoobsd.service - HOOBSD
   Loaded: loaded (/etc/systemd/system/hoobsd.service; enabled; vendor preset: e
   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-08-07 10
  Process: 31018 ExecStart=/usr/bin/hoobsd hub (code=exited, status=6)
 Main PID: 31018 (code=exited, status=6)
lines 1-5/5 (END)...skipping...
● hoobsd.service - HOOBSD
   Loaded: loaded (/etc/systemd/system/hoobsd.service; enabled; vendor preset: e
   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-08-07 10
  Process: 31018 ExecStart=/usr/bin/hoobsd hub (code=exited, status=6)
 Main PID: 31018 (code=exited, status=6)
~

**Comment by mkellsy** [comment]
The issue is Node is corrupt. It shouldn’t be. This is definitely SD Card corruption. You can try opening the case and re-flashing the SD Card, but if the SD Card is corrupt it will happen again.

send an email to info@hoobs.org with your order number to start the RMA process. We can either send you a new SD Card or replace the entire device.
