### ISSUE TITLE
Static Box on Dashboard

### ISSUE THREAD

**Issue by cameronk96** [hoobs-org/HOOBS#1446]
**Description**
On the main dashboard of the GUI through a browser or HOOBS Desktop on a Mac, there is a static window where a widget would typically sit that I cannot remove. It's just a white box with no settings, toggle switches or anything. It can, however, be moved around the space allotted for widgets.
**Version**
Please include the version of HOOBS you are using.
4.0.98
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
ring
philips-hue
platform-wemo
Nest Plugin
Unifi Protect
myQ
SamsungTV
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
![Screen Shot 2021-08-01 at 3 43 55 PM](https://user-images.githubusercontent.com/78843008/128518450-eefa87d3-1af7-411a-8dd1-22bf808b3ad3.png)

**Comment by mkellsy** [comment]
Looks like a stuck widget. You can fix this using the CLI.
Open the terminal and enter this command.
```
sudo hbs config
```

The dashboard item config looks like this
```
"dashboard": {
    "items": [
        { 
            "x": 36,
            "y": 47,
            "w": 18,
            "h": 15,
            "component": "camera-widget",
            "bridge": "ringbridge",
            "id": "982c07b1-fb62-aee9-8be2-cbcf4df642a8",
            "i": "982c07b1-fb62-aee9-8be2-cbcf4df642a8" 
        }
    ],
    "backdrop": false
}
```

You can try to find the item and remove it. Or you can simply clear it so it looks like this.
```
"dashboard": {
    "items": [],
    "backdrop": false
}
```

"Ctrl+X" then "Y" then "Enter" to save.

Then you can fix your dashboard with the UI. Note you might need to reboot after making the changes in the config.
