### ISSUE TITLE
Hoobs Update from 3.3.5 to 3.3.12 does not work

### ISSUE THREAD

**Issue by dibimuc** [hoobs-org/HOOBS#1447]
**Description**
Updating from Hoobs core 3.3.5 to 3.3.12 does not work (see log-file)

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
Yes

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
MacOS 11.5.1

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
7.8.2021, 15:31:52 - Got SIGINT, shutting down Bridge...
7.8.2021, 15:31:52 - [Wohnzimmer] INFO - shutdown
7.8.2021, 15:31:52 - [Wohnzimmer] INFO - shutdown
7.8.2021, 15:31:57 - [Hue] goodbye
7.8.2021, 15:32:32 - npm
7.8.2021, 15:32:32 - notice
7.8.2021, 15:32:32 - npm notice New minor version of npm available! 7.6.3 -> 7.20.5
7.8.2021, 15:32:32 - npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.20.5>
7.8.2021, 15:32:32 - npm notice Run `npm install -g npm@7.20.5` to update!
7.8.2021, 15:32:32 - npm notice
7.8.2021, 15:32:32 - 
7.8.2021, 15:32:32 - npm
7.8.2021, 15:32:32 - ERR! code ENOTEMPTY
7.8.2021, 15:32:32 - npm ERR! syscall rename
7.8.2021, 15:32:32 - npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
7.8.2021, 15:32:32 - 
7.8.2021, 15:32:32 - npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
7.8.2021, 15:32:32 - npm ERR! errno -39
7.8.2021, 15:32:32 - 
7.8.2021, 15:32:32 - npm
7.8.2021, 15:32:32 - ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'
7.8.2021, 15:32:32 - 
7.8.2021, 15:32:33 - 
7.8.2021, 15:32:33 - 
7.8.2021, 15:32:33 - npm ERR! A complete log of this run can be found in:
7.8.2021, 15:32:33 - npm ERR!     /root/.npm/_logs/2021-08-07T13_32_32_915Z-debug.log
7.8.2021, 15:32:33 - 
```

**Additional context**

**Comment by mkellsy** [comment]
Symptoms
- ENOTEMPTY

Step 1
Look at the error and find a line that looks like this
```
npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
```
If that's there continue.

Step 2
Delete the problem files
```
sudo rm -fR /usr/local/lib/node_modules/@hoobs
```

Step 3
Reinstall HOOBS 3.3
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by dibimuc** [comment]
Two word: many thanks. Worked perfectly and ticket can be closed. Have a great day!
