### ISSUE TITLE
Hoobs Stopped Working

### ISSUE THREAD

**Issue by pedramghafoori** [hoobs-org/HOOBS#1448]
Hello, 

not sure if I'm even reaching out through the proper channel but I've purchased Hoobs out of the box and it was working fine for about a month and now none of my accessories can connect. I've done research tried to reformat the SD card and installed the img file from your website but hoobs is not connecting to my network (or at least it can't be found on the network). 

I'm not very knowledgable with coding. I'm wondering if its possible to be sent a replacement item so I can set it up from scratch? 

Hope to hear from you soon

**Comment by mkellsy** [comment]
A fresh image needs an internet connection. If you are using WiFi, use your phone to connect to the HOOBS WiFi, it will then ask you to connect to your home’s WiFi.

https://support.hoobs.org/docs/60e125e9646faaa152f10ddf
