### ISSUE TITLE
Plugins site unavailable

### ISSUE THREAD

**Issue by ymohiuddin** [hoobs-org/HOOBS#1449]
**Description**
I am getting an error message saying "Plugins site unavailable" and under installed plugins it says No plugins installed. I had the ring plugin, dummy switch, TPLINK, Aladdin genie garage, smart things plugins, LGWEBOS installed and working fine. I recently upgraded to HOOBS 4 but that was a few days ago and it was working fine.

![HOOBs log 8:7:21](https://user-images.githubusercontent.com/88597993/128614057-77c767a9-128f-4c07-bcba-5ae20e5e2e7c.png)

**Version**
4.098

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
?

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**

**Post your config**

```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
8/7/2021, 4:21:27 PMWARNINGplugin site unavailable
8/7/2021, 4:26:02 PMWARNINGplugin site unavailable
8/7/2021, 4:26:21 PMWARNINGplugin site unavailable
8/7/2021, 4:33:28 PMWARNINGplugin site unavailable
8/7/2021, 4:33:28 PMWARNINGplugin site unavailable
8/7/2021, 4:40:13 PMWARNINGplugin site unavailable
8/7/2021, 4:40:21 PMWARNINGplugin site unavailable

**Additional context**

**Comment by mkellsy** [comment]
I just checked the status of the plug-in site and it is up and running.

check your internet connection, reboot the device and try rebooting your router too.
