### ISSUE TITLE
Tried to update to vers. 4, box said "Migrating", now lost connection, "Hoobs in a box"

### ISSUE THREAD

**Issue by pklaursen** [hoobs-org/HOOBS#1455]
**Description**

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

Since I cannot connect to the box i cannot retrive a config file etc. 
Was trying to update from vers. 3.1 i think, to vers 4.
Box started updating, and the screen was saying "Migrating", after a while the browser went black, and i could not reconnect to the box.

Am using Windows.

The box was ordered from Hoobs last December, and is a model no. HSLF-1

**Comment by mkellsy** [comment]
We have a support doc for this
https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

**Comment by pklaursen** [comment]
HOOBS customer service help sort the issue. Was necessary to flash the SD card
