### ISSUE TITLE
no upgrade to Hoobs 4 available, wrong port ?!

### ISSUE THREAD

**Issue by tobihoby** [hoobs-org/HOOBS#1457]
**Description**
I want to migrate hobbs 3.3.12 to version 4. Unfortunately with no upgrade is offered. I had read that port 80 is required. Strangely, the port 8080 is deposited as standard with me. if I change the port from 8080 to 80 via the hobbs web gui and restart hoobs, the gui gets stuck and can no longer be used. Via putty I can then set the old port 8080 in the config.json again, after a reboot the gui can then be used normally again. does the change of the port still have to be made somewhere?

**Version**
3.3.12

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian GNU/Linux 10

**List your plugins**
too many

**Post your config**
gladly if really necessary

Thank you
Tobi

**Comment by mkellsy** [comment]
We have a support doc for this
https://support.hoobs.org/docs/60e62a926c19a6a5ca8f4f42
