### ISSUE TITLE
Connexoon plug-in doesn't work on HOOBS 4

### ISSUE THREAD

**Issue by pklaursen** [hoobs-org/HOOBS#1459]
After update to HOOBS vers. 4, the Connexoon plug-in doesn't work correctly.

The configuration tab is not available so no possibility to do customization rtc

**Comment by mkellsy** [comment]
Upgrade or use the Advanced config screen.

**Comment by pklaursen** [comment]
That wasn't available, but since an update again yesterday, it works, and the config tab is now present, so I am up and running again.
