### ISSUE TITLE
No response in HomeKit after latest HOOBS updates

### ISSUE THREAD

**Issue by jrwilson99** [hoobs-org/HOOBS#1460]
HomeKit and HOOBS has been working fine for a few weeks.  I regularly check for updates and apply them. Yesterday, after installing available updates, I'm started getting "accessory is not responding" errors in the Home app for all HOOBS bridges and accessories.   

The current version is 4.0.100, node version 14.17.5 and Homebridge version 1.3.4. The Mac app version is 4.0.56.  

HOOBS itself is working fine, I'm able to control the accessories from the HOOBS app.  It is just from HomeKit that is the issue.

I've restarted HOOBS and also the Homepod hubs, but the problem continues.

**Comment by mkellsy** [comment]
Is your iPhone connected to your WiFi? Do you have an Apple TV or a HomePod to relay the bridge?

**Comment by jrwilson99** [comment]
Yes, iPhone is on same network. Other HomeKit devices are working properly, it is just the HOOBS bridges that started having issues after the recent update.  I have Apple TV and some HomePods. This morning, I switched the controlling Home Hub to a different HomePod, but it didn't help.

**Comment by mkellsy** [comment]
It looks like there's an issue with the persisted connections in the cache.

OK, go to the Bridges screen and select the bridge you are having issues with. Then click the Cache button and then click Clear.
Then in the Home app, go to Settings -> Hubs & Bridges and remove the problematic bridge.
Then re-pair the bridge.

This is also a good time to separate your plugins to different bridges.

**Comment by jrwilson99** [comment]
I already have multiple bridges - one for each of the four plugins.  All four bridges, and associated accessories had the same issue.
I used your suggestion to Clear Cache and remove and re-add one of the bridges.
Note, I only did this with one bridge, but after doing that one, all the HOOBS bridges and their accessories started responding in HomeKit again.
