### ISSUE TITLE
After upgrade to HOOBS 4.0 not responding

### ISSUE THREAD

**Issue by rump1991** [hoobs-org/HOOBS#1461]
**Description**
During the upgrade it was an outage, now it's not responding. I have HOOBS in a box

**Version**
Had 3.something, was upgrading to 4.0

**Did you upgrade**
i don't know, the outage happened during the update

**Pervious version**
3.something

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box

**If this is a custom install, what's your operating system?**
Windows

**List your plugins**
Ring

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Try rebooting it will attempt to recover. If it failed upgrading Node you may need to re-flash the SD card.

**Comment by rump1991** [comment]
1. How to reboot it correctly?
2. How to re-flash the SD card?
Thanks!

**Comment by mkellsy** [comment]
In this case just unplug it count to 10 and plug it back in.

to reflash you need to open the case. Pull the add card and using a card reader connect it to a computer. The download the latest image https://support.hoobs.org/downloads/image and flash it using the balinaEtcher https://www.balena.io/etcher/

**Comment by rump1991** [comment]
did everything (reboot, re-flash), still have the same issue. Can't connect to the HOOBS box. Tried to connect it directly to the router, tried from Windows and Mac...still nothing.
The red light is on. the green one is blinking.

**Comment by mkellsy** [comment]
Can you access the terminal at http://hoobs.local:9090?

**Comment by rump1991** [comment]
> Can you access the terminal at http://hoobs.local:9090?

no, I can't. Also just noticed that it says on my router that hoobs is offline, but at the same time it's connected and all the lights are ON. I have a Nest WiFi router btw

**Comment by mkellsy** [comment]
Using  you phone, can you see the HOOBS WiFi?

**Comment by rump1991** [comment]
> Using you phone, can you see the HOOBS WiFi?

do you mean just to try to access  http://hoobs.local:9090 from the phone? if yes, nothing happens. It's not loading.

**Comment by mkellsy** [comment]
No. Open your phone's WiFi settings. Is there a network called HOOBS?

**Comment by rump1991** [comment]
> No. Open your phone's WiFi settings. Is there a network called HOOBS?

No, it's no hoobs network found

**Comment by mkellsy** [comment]
There's an HDMI port on it. What do you see when you plugin a monitor? You may have to take a picture and post it.

**Comment by rump1991** [comment]
> There's an HDMI port on it. What do you see when you plugin a monitor? You may have to take a picture and post it.

i don't have a regular monitor, I have just a laptop at home. But I also tried to connect it to my TV, it says "No Signal"

**Comment by mkellsy** [comment]
What device are you using?
- HOOBS Box
- Raspberry Pi 4B/3B/3B+
- Raspberry Pi Zero

**Comment by rump1991** [comment]
> I see you are using a HOOBS Box. Please email [info@hoobs.com](mailto:info@hoobs.com) with your order number. We can troubleshoot and replace components if needed.

Just did it. Thank you for your help! Hope we will solve this issue together.

**Comment by rump1991** [comment]
Received new SD card, everything works fine now. Thank you!
