### ISSUE TITLE
HOOBS on Pi 3B Cannot Interface with Eero Pro 6 Router

### ISSUE THREAD

**Issue by mrpk80** [hoobs-org/HOOBS#1464]
After updating my network with a new WiFi (mesh) router (Eero Pro 6), I don't see the captive portal ("Welcome to HOOBS") screen to select my new WiFi network as my Pi 3B cannot connect to my new router (HOOBS version 4.0.98 installed).  I can connect via an ethernet connection without a problem.  I have tired: disabling Eero Secure, Pausing 5 GHz band, entering into Legacy Mode which disables WiFi 6, and even hit Factory Reset on HOOBS and cannot get the captive portal to pop up as I don't get an IP address during the connection process.

**Comment by EddieDSuza** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)

**Comment by mrpk80** [comment]
I did connect manually to my main node.  HOOBS does connect and I can go to http://hoobs address; however what I never see is the "Welcome to HOOBS" captive portal screen that lets me select the WiFi network to configure HOOBS.

Also how does the Apple Bonjour Print Services for connecting printers help with connecting HOOBS with Windows??

**Comment by mkellsy** [comment]
The captive portal will not start if it is connected. You have to first disconnect the network cable and restart it. Then in a few the portal will start.

https://support.hoobs.org/docs/60e0b978646faaa152f10dcc

**Comment by mrpk80** [comment]
yes I can connect directly with an ethernet cable.  When I disconnect the cable and restart the Pi, the portal never comes up.

**Comment by mrpk80** [comment]
I only see "HOOBS"

**Comment by askovi** [comment]
Try connecting to the HOOBS network with another device like a laptop or phone. The portal should pop up automatically.

**Comment by mkellsy** [comment]
https://support.hoobs.org/docs/60e125e9646faaa152f10ddf

**Comment by mrpk80** [comment]
I have tried using other devices and the portal never pops up.  I read the very simple support document on day 1 when I started using HOOBS a long time ago.  Nothing addresses the situation of the portal NOT coming up to configure my WiFi setting on my Pi.  

I guess the takeaway is that HOOBS is not compatible with my network setup unlike my other 50+ devices.  No one has come up with anything useful to correct the setup (Reached out to several user groups too).  Sounds like I just need to move on without HOOBS.  Unfortunate...

**Comment by mkellsy** [comment]
I think there is some miss-communication here.
- You state the captive portal doesn’t show
- You also state you can see the HOOBS WiFi
- You also state that the device is incompatible with your network 

I am confused. Are you seeing the portal but not seeing your WiFi in the list? Or does your phone not connect to the HOOBS WiFi?

This is how this works.
1. An unconnected device detects that is has no network connection and starts the HOOBS wifi access point.
2. You use your phone to connect to the HOOBS wifi
3. A portal opens up asking you to select a wifi network to connect to
4. Then it connects to your wifi and shutdowns the HOOBS wifi access point
5. Your phone will reconnect to its previous wifi

If you want further information on this it can be found on Balina’s repo. https://github.com/balena-os/wifi-connect

**Comment by mrpk80** [comment]
The phone/tablet/PC (tried several different devices) can connect to the HOOBS WiFi access point, but after it connects, the captive portal asking me to select my home WiFi DOESN'T show.

**Comment by mkellsy** [comment]
I did some searches and you aren’t the only one. Here’s a huge topic about this on this. https://www.raspberrypi.org/forums/viewtopic.php?t=177629&start=25

Basically from what I am reading Amazon’s eero is not good for Raspberry Pi’s.

**Comment by mrpk80** [comment]
Thanks for the post as I have read other similar threads.  4.5 yrs ago though... you would think they would have a solution now.  As I said above, I updated 50+ devices to my Eero mesh system without a problem.  I wonder if it is a Raspberry Pi 3B issue and the 4 is more capable.

**Comment by mkellsy** [comment]
It’s worth a test. I use AmpliFi Alien and it’s flawless. It’s a WiFi 6 mesh system too, so it’s definitely Eeros.

**Comment by mrpk80** [comment]
Yeah likely not going to rush out and get a new Pi.  I found another workaround without using HOOBS.  I really like my Eeros system.
