### ISSUE TITLE
Hoobs terminal does not accept my Hoobs log-in credentials

### ISSUE THREAD

**Issue by NewOnHoobs** [hoobs-org/HOOBS#1465]
After opening the terminal for modifying an accessory, I'm greeted with "Login:" and after entering my user name prompted for the "Password:". I sure used the correct password for my Hoobs box, but the terminal keeps throwing me back to the "Login:" line. Seems I'm missing a magic trick...

**Comment by mkellsy** [comment]
The terminal uses system credentials.
The default username is **hoobs** and the default password is **hoobsadmin**.

This is documented here
https://support.hoobs.org/docs/60e09b9a646faaa152f10dc3
