### ISSUE TITLE
Changed the Hoobs port to 80 and cannot access loging page

### ISSUE THREAD

**Issue by dibimuc** [hoobs-org/HOOBS#1466]
![Hoobs Splash-Screen](https://user-images.githubusercontent.com/61652682/129681935-02b37a0b-28bc-4ed7-bc74-bbc0f8e38b3e.JPG)
**Description**
I changed the Hoobs port from 8080 to 80 and cannot access the login-page. I only see the splash screen

**Version**
3.3.12

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
I use an MacOS system

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
You need to disable NGINX
https://support.hoobs.org/docs/60e62a926c19a6a5ca8f4f42

Run

sudo systemctl stop nginx
sudo systemctl disable nginx

**Comment by dibimuc** [comment]
A brief question. Should I do all the steps mentioned in the support document or just connecting to the terminal and run

sudo systemctl stop nginx
sudo systemctl disable nginx

in order to disable NGINX?

Thanks.

**Comment by mkellsy** [comment]
The document is geared towards upgrading to 4.0. I assumed that’s what you are doing.

**Comment by dibimuc** [comment]
Again: GREAT THANKS. Worked perfectly. With every ticket I become a greater Hoobs fan.
