### ISSUE TITLE
cannot update to 4.0

### ISSUE THREAD

**Issue by mxb172** [hoobs-org/HOOBS#1467]
I cannot update to 4.0.  The GUI on hoops.local was timing out so I used the ssh commands in terminal but these are the outputs I'm getting.  
<img width="572" alt="Screen Shot 2021-08-17 at 9 11 26 PM" src="https://user-images.githubusercontent.com/89116247/129828071-3bacf1a2-62fe-4846-b9be-80df2657a79f.png">
<img width="563" alt="Screen Shot 2021-08-17 at 9 23 05 PM" src="https://user-images.githubusercontent.com/89116247/129828075-525d4be2-0fd6-4da6-91a8-5cfb2fc3e7f9.png">
<img width="567" alt="Screen Shot 2021-08-17 at 9 23 57 PM" src="https://user-images.githubusercontent.com/89116247/129828076-65ce15c9-b7b3-4aff-9974-4c99a3d48131.png">

**Comment by mkellsy** [comment]
Reboot and it will try the migration again.

**Comment by mxb172** [comment]
I have been rebooting and trying this for the last 3 days.

**Comment by mxb172** [comment]
I try to run sudo apt install hoobs but get an error that says I need to run sudo dpkg --configure -a which I do.  but then that process returns an error and I can't move beyond it

**Comment by mkellsy** [comment]
Dpkg is part of the base OS. That’s bad. Your SD Card sounds corrupt. You can try re-flashing with a fresh image.

https://support.hoobs.org/downloads/image

**Comment by mxb172** [comment]
I have a box without an SD. What is the process to reimage?

**Comment by mkellsy** [comment]
It does have an sd card. You will need to open it. If you are uncomfortable doing this you can send an email to info@hoobs.org with your order number to start the rma process.
