### ISSUE TITLE
noob here

### ISSUE THREAD

**Issue by Jaw769** [hoobs-org/HOOBS#1469]
**Description**
just got  hoobs in a box and tried installing and when I log into hoobs local or or the desktop app I keep getting login incorrect.  I can log into hoobs.com no problem.   do they use the same info?  

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Not the same. It’s the username and password you used on initial setup.

**Comment by Jaw769** [comment]
> Not the same. It’s the username and password you used on initial setup.

I don't remember doing the box id/password.  looks like they screwed me and sent a used one.  box was unsealed writing on papers and wires everywhere.   is there a way to flash it to clear any unwanted info ?

**Comment by askovi** [comment]
Did you purchase the unit directly on hoobs.com or other marketplaces such as Amazon? All units shipped by us are new and sealed. Please reach out to info@hoobs.com with your order number to have it sorted out. 

If you purchased it elsewhere such as Amazon please make sure you didn't purchase a used box.

**Comment by mkellsy** [comment]
Amazon is supposed to ship all returns to me. I then test each component to see what failed. Then if a component is good we will recycle it to cut down on ewaste.

Sometimes Amazon makes this decision for us, despite us telling them they can’t. A device can’t be re-sold without a reset.

Sorry this happened to you. As Ovi said please email us at info@hoobs.com.
