### ISSUE TITLE
No Plugins for IP Cameras

### ISSUE THREAD

**Issue by mrtargaryen** [hoobs-org/HOOBS#147]
Since I'm just starting out with HOOBS I was wondering if there is suppose to be plugins available for IP Cameras (Amcrest in my case) ... here's a screenshot of HOOBS Plugins for "Video & Monitoring" https://i.imgur.com/tVWLF8Z.png

**Comment by mrtargaryen** [comment]
Also, I noticed that I have to SSH into my iMac with Termius and start HOOBS ($ hoobs) and leave the SSH session open otherwise HOOBS shutsdown. Is that its normal behavior?

**Comment by mkellsy** [comment]
V3 is in beta, there is no Mac startup script yet. For now you need to set HOOBS to run as a service
https://github.com/hoobs-org/HOOBS/wiki/2.6-Running-HOOBS-on-Startup

HOOBS runs Homebridge under the hood. You can search for plugins from the plugin screen.

**Comment by mrtargaryen** [comment]
Done, thank you.
