### ISSUE TITLE
TP Link Smarthome Bridge is down and can't find the QR code for the TP link bridge

### ISSUE THREAD

**Issue by ama8220** [hoobs-org/HOOBS#1472]
**Description**
I just sat up HOOBS Box 4.0 and downloaded TP Link Smarthome Bridge. Now the dashboard is telling me the plugin is down> I'm new to this so I'm not sure what I'm supposed to do. 

<img width="1002" alt="Screen Shot 2021-08-21 at 5 42 35 PM" src="https://user-images.githubusercontent.com/89306449/130323692-bdd42e6c-b543-4cd1-89d7-72189ec8ac30.png">
<img width="588" alt="Screen Shot 2021-08-21 at 5 42 56 PM" src="https://user-images.githubusercontent.com/89306449/130323695-54c5b3d4-4d21-41b6-b4ba-5ae53470f0f9.png">

**Version**
HOOBS 4.0

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

*

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
The log is telling you that the plug-in is mid-configured. You need to fix this before the bridge will start. Once it starts you can pair it with HomeKit.
