### ISSUE TITLE
upgrade to hoobs 4

### ISSUE THREAD

**Issue by tivo65** [hoobs-org/HOOBS#1474]
I am running hoobs 3.3.12 on raspberrypi.  It is not a dedicated hoobs server, I have other software running on the server.

Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l

I ran the program to upgrade to hoobs 4, it ran for several minutes then lost connection to my server.  I could no longer login to hoobs, no response at my static ip address from the browser.

From a shell command: I ended up running the following to re-install, then restored from a backup. I am back running on ver 3.3.12

wget -q -O - http://bit.ly/get-hoobs | sudo bash -
 
how can I manually install hoobs 4 using a wget command?  Or what is the best way to upgrade to ver 4?

I tried the commands from this link – I got an error something to the effect that it was not the latest running version. 

https://support.hoobs.org/docs/60e9f2ecdea381a881af7237

 

suggestions?

**Comment by mkellsy** [comment]
https://support.hoobs.org/docs/60e9f2ecdea381a881af7237

**Comment by askovi** [comment]
see here for potential issues: https://support.hoobs.org/docs/60e62a926c19a6a5ca8f4f42

**Comment by tivo65** [comment]
how do I get past this error when running wget...... see text below

wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
+ rm -f /etc/apt/sources.list.d/hoobs.list
Installing the NodeSource Node.js 14.x repo...
+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Reading package lists... Done                              
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Error executing command, exiting

**Comment by mkellsy** [comment]
This is not HOOBS related. It has to do with the OS on your Pi.
This might help you. https://www.raspberrypi.org/forums/viewtopic.php?t=245073

I think you might need to run this command.
```
sudo apt update --allow-releaseinfo-change
```

**Comment by tivo65** [comment]
thanks, the above allow releaseinfo command did the trick and allowed me to manually upgrade to hoobs 4.
