### ISSUE TITLE
Hoobs not loading

### ISSUE THREAD

**Issue by breather74** [hoobs-org/HOOBS#1476]
**Description**

I was setting up my HOOBS in a box today. It is connected via ethernet and I used IP 192.168.1.95 to get to the online portal where the first thing I did was an attempt to upgrade to the new HOOBS 4. I'm not sure what version it was prior to the update but it then went to an orange screen which said "migrating" for around 10 minutes and then randomly started showing "this site can't be reached" messages. I tried accessing Hoobs through my mac terminal and it seems to be working there but I can't manage to open the online portal. I neither can find the device when I try to use the desktop app and scan on my network. In addition to this my HOOBS is displaying a red light.
![IMG_3850](https://user-images.githubusercontent.com/89380644/130411401-4bdd3402-b510-4c98-a064-6a97c0736c83.jpg)

<img width="941" alt="Screen Shot 2021-08-23 at 7 39 51 PM" src="https://user-images.githubusercontent.com/89380644/130410661-67619a2c-007a-4504-b526-6ea7b1beea62.png">

![Screen Shot 2021-08-23 at 7 40 51 PM](https://user-images.githubusercontent.com/89380644/130411496-260660e3-6c71-4193-a2fe-505fcb59fbc7.png)

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [Y ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
Not sure

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ Y] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
The 4.0 upgrade is going to take some time. Like an hour or more depending on your plugins.

**Comment by breather74** [comment]
This issue remained for more than 10 hours afterwards and is still going on… I tried restarting the phone box but still nothing. It was a completely fresh setup, I just took it out of the box had no plug-ins installed, just a simple attempt to upgrade to hoobs 4 and this happens :(
