### ISSUE TITLE
My Hoobs device is no longer responding

### ISSUE THREAD

**Issue by Wwilds01** [hoobs-org/HOOBS#1478]
**I went on vacation and when I returned my Hoobs device was no longer showing up on my network and is not responding*

**Version 3 unless it automatically tried to update to 4**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system
I am running Mac OS Big Sur version 11.5.2?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

* Ring video, bond bridge, myQ garage doors**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config I am unable to access that information because my Hoobs is not showing up on my network**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**I am not sure what happened, I have tried to reboot several times and there appears to be network traffic from the lights on my switch and there is a red light on the HOOBs itself but I cannot see it on the network. when I go to Hoobs.local which is how I usually access it I get an "Safari cannot open the page because the server cannot be found"**

**Comment by mkellsy** [comment]
Did you try rebooting?

**Comment by Wwilds01** [comment]
Yes I don’t know if there is a way to do a hard reset?



Warm regards,
William Wildstein

**Comment by mkellsy** [comment]
Is the red light on?
Can you access terminal at http://hoobs.local:9090?

**Comment by Wwilds01** [comment]
Yes there is a red light on



Warm regards,
William Wildstein

**Comment by Wwilds01** [comment]
I cannot access terminal at 
Hoobs.local:9090



Warm regards,
William Wildstein

**Comment by mkellsy** [comment]
Using  you phone, can you see the HOOBS WiFi?

**Comment by Wwilds01** [comment]
No



Warm regards,
William Wildstein

**Comment by mkellsy** [comment]
The next thing is to check the output. If you are comfortable, you can open the case. You will see an HDMI port, plugin a monitor and see that's going on.

**Comment by Wwilds01** [comment]
Just to clarify you want me to unscrew the box, open it up, inside there is an HDMI connection. Plug that into a monitor to see what is going on?



Warm regards,
William Wildstein

**Comment by mkellsy** [comment]
Yep. It's the only thing that's left before we have to RMA the device.

**Comment by Wwilds01** [comment]
I’ll give it a shot. How do I get the plastic protectors off of the screws?



Warm regards,
William Wildstein

**Comment by mkellsy** [comment]
Please send an email to info@hoobs.com to continue troubleshooting.

**Comment by Wwilds01** [comment]
I figured it out. I’m not getting anything on monitor




Warm regards,
William Wildstein

**Comment by mkellsy** [comment]
Please send an email with your order number to info@hoobs.com. I think your SD Card needs to be replaced.

**Comment by Wwilds01** [comment]
I sent the order number but haven’t heard back. Also how would an sd card replacement work?



Warm regards,
William Wildstein
