### ISSUE TITLE
I tried to upgrade to 4.0 and can no longer access HOOBS

### ISSUE THREAD

**Issue by gagz135** [hoobs-org/HOOBS#1479]
**Description**
I attempted to update my HOOBS to 4.0 a couple of days ago. Since then, the HOOBS is offline and cannot be reached at hoobs.local (or hoobs.local:8080, etc.).

**Version**
4.0 if the upgrade was successful.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
No idea

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No
- [X ] - Not sure

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
ca you try following this [guide](https://github.com/hoobs-org/HOOBS/issues/1480#issuecomment-904181356)
