### ISSUE TITLE
I have a pi already running buster...

### ISSUE THREAD

**Issue by lacedup** [hoobs-org/HOOBS#148]
Can and how do I just install hoobs? I already have ssh. Can hoobs be installed like a regular program or do I need the whole image? I’d be using windows 10 putty, to a raspberry pi 4

**Comment by mkellsy** [comment]
More info here
https://github.com/hoobs-org/HOOBS/wiki/2.5.2-Debian-Installation

It is the beta version. If you run hoobs-init it will take over port 80.
