### ISSUE TITLE
Hoobs won’t launch after update

### ISSUE THREAD

**Issue by k5nwz** [hoobs-org/HOOBS#1480]
Hoobs won’t run after update. I can see it on the network but cannot access Hoobs. I purchased the complete hoobs box. How can I fix this?

**Comment by EddieDSuza** [comment]
Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: `ssh hoobs@hoobs.local`

Type yes to accept the certificate key then press enter. When prompted for password, type `hoobsadmin`

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, execute the following commands:

`sudo apt update`

`sudo apt install hoobsd`

`sudo npm install -g @hoobs/migration`

**select HOOBS and Do not enable separate each plugin by bridge**

`cd ~/ && sudo hbs-migrate`

Follow the onscreen instructions, Select HOOBS and DO NOT setup as separate bridges or else you will need to redo your setup

Terminal will disconnect from the box and after 3 mins - SSH back into the Box and paste below command to see the progress of the migration

`sudo journalctl -o cat -n 500 -f -u migrate.service`

It will take 5 to 10 mins. Wait for the process to complete. Let me know if it worked for you

**Comment by k5nwz** [comment]
Thank you for that quick reply. I followed the instructions and it froze at this point. 


Have a great day
Shawn Bates281-923-6365 

    On Monday, August 23, 2021, 05:38:56 PM CDT, Tech With Eddie ***@***.***> wrote:  
 
 


Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh ***@***.***

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.
   
   - After successfully logging in, execute the following commands:

sudo apt update

sudo apt install hoobsd

sudo npm install -g @hoobs/migration

select HOOBS and Do not enable separate each plugin by bridge

cd ~/ && sudo hbs-migrate

Follow the onscreen instructions, Select HOOBS and DO NOT setup as separate bridges or else you will need to redo your setup

Terminal will disconnect from the box and after 3 mins - SSH back into the Box and paste below command to see the progress of the migration

sudo journalctl -o cat -n 500 -f -u migrate.service

It will take 5 to 10 mins. Wait for the process to complete. Let me know if it worked for you

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EddieDSuza** [comment]
can you add the error ?

**Comment by k5nwz** [comment]
NO
Have a great day
Shawn Bates281-923-6365 

    On Monday, August 23, 2021, 06:11:13 PM CDT, Tech With Eddie ***@***.***> wrote:  
 
 


can you add the error ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by k5nwz** [comment]
No I get this when I trie to get back in 
Have a great day
Shawn Bates281-923-6365 

    On Monday, August 23, 2021, 06:11:13 PM CDT, Tech With Eddie ***@***.***> wrote:  
 
 


can you add the error ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by k5nwz** [comment]
I disconnected the power and was able to log in again. Started the process over and now I get this. I would be happy to just get it back to the factory state. 
Have a great day
Shawn Bates281-923-6365 

    On Monday, August 23, 2021, 06:11:13 PM CDT, Tech With Eddie ***@***.***> wrote:  
 
 


can you add the error ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by k5nwz** [comment]
progress stopped and then It just froze up again. Waited about 10 minutes. Disconnected and reconnected. Not sure what to do now. Anyway to factory reset the entire thing? 
Have a great day
Shawn Bates281-923-6365 

    On Monday, August 23, 2021, 06:11:13 PM CDT, Tech With Eddie ***@***.***> wrote:  
 
 


can you add the error ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EddieDSuza** [comment]
You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
    1. Download the App BalenaEtcher - https://www.balena.io/etcher/
    2. Download the HOOBS Image - https://support.hoobs.org/downloads/image
    3. From the download folder - Load the .zip file in the BalenaEtcher. If you are using a Mac - the file is automatically decompressed and moved to the thrash bin. Restore the file to your download folder
    4. Click on flash

Once the process is over - insert the card back into the board. Close the box with the screws. Plug the ethernet cable and then power the device.

**Comment by kaceyb25** [comment]
Hi I followed the instruction above after I upgraded to 4 from 3 (something) and device could not be found and I cannot connect to terminal or Hoobs.local.

I get sudo command not found.

**Comment by kaceyb25** [comment]
`hoobs@hoobs:~ $ sudo apt update
sudo: apt: command not found
hoobs@hoobs:~ $ sudo apt install hoobsd
sudo: apt: command not found
hoobs@hoobs:~ $ sudo npm install -g @hoobs/migration
sudo: npm: command not found`
