### ISSUE TITLE
Device Not Initialized

### ISSUE THREAD

**Issue by caspianguirey** [hoobs-org/HOOBS#1481]
OK. The username is **hoobs** and the password is **hoobsadmin**.

Then run this command.
```
sudo systemctl status hoobsd
```

Also can you post your logs?
```
sudo hbs log -d
```

_Originally posted by @mkellsy in https://github.com/hoobs-org/HOOBS/issues/1477#issuecomment-904071616_

**Comment by caspianguirey** [comment]
please can you help me i am at my wits end

**Comment by caspianguirey** [comment]
i have run all the tasks as other user except i am getting this

**Comment by caspianguirey** [comment]
hoobs@hoobs:~ $ 
hoobs@hoobs:~ $ sudo systemctl status hoobsd
Unit hoobsd.service could not be found.
hoobs@hoobs:~ $ node -v
v14.17.5
hoobs@hoobs:~ $ ip adress
Object "adress" is unknown, try "ip help".
hoobs@hoobs:~ $ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:0f:3e:f1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.71/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 258652sec preferred_lft 258652sec
    inet6 2001:bb6:9208:be58:8751:e851:2951:757/64 scope global dynamic noprefixroute 
       valid_lft 7010sec preferred_lft 3410sec
    inet6 fe80::ed78:4ae8:2108:6089/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:5a:6b:a4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.65/24 brd 192.168.1.255 scope global dynamic noprefixroute wlan0
       valid_lft 258666sec preferred_lft 258666sec
    inet6 2001:bb6:9208:be58:35bd:7332:2b03:1fb8/64 scope global dynamic noprefixroute 
       valid_lft 7010sec preferred_lft 3410sec
    inet6 fe80::c037:9843:9b9d:3d5d/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
hoobs@hoobs:~ $ sudo hbs bridge 1s
 WARNING  system is not initilized, please initilize the system first.
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
Please explain the issue you are having. I can help, but I need to know what's going on.

Running commands from another issue for another persons device is not good.

Please explain your issue.

**Comment by caspianguirey** [comment]
got hoob to to today plug in got on to dash and did update not can't get on to hoob via hardwire on wirerless

**Comment by caspianguirey** [comment]
tried running what you gave other user 22 hours ago and this is how far i gothoobs@hoobs:~ $ 
hoobs@hoobs:~ $ sudo systemctl status hoobsd
Unit hoobsd.service could not be found.
hoobs@hoobs:~ $ node -v
v14.17.5
hoobs@hoobs:~ $ ip adress
Object "adress" is unknown, try "ip help".
hoobs@hoobs:~ $ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:0f:3e:f1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.71/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 258652sec preferred_lft 258652sec
    inet6 2001:bb6:9208:be58:8751:e851:2951:757/64 scope global dynamic noprefixroute 
       valid_lft 7010sec preferred_lft 3410sec
    inet6 fe80::ed78:4ae8:2108:6089/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:5a:6b:a4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.65/24 brd 192.168.1.255 scope global dynamic noprefixroute wlan0
       valid_lft 258666sec preferred_lft 258666sec
    inet6 2001:bb6:9208:be58:35bd:7332:2b03:1fb8/64 scope global dynamic noprefixroute 
       valid_lft 7010sec preferred_lft 3410sec
    inet6 fe80::c037:9843:9b9d:3d5d/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
hoobs@hoobs:~ $ sudo hbs bridge 1s
 WARNING  system is not initilized, please initilize the system first.
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
What version of HOOBS are you running?

For 4.0 this is the service
```
sudo systemctl status hoobsd
```

For 3.3 this is the service
```
sudo systemctl status hoobs
```

When you upgraded, was it a migration from 3.3?
What version are you trying to upgrade to?

**Comment by caspianguirey** [comment]
not sure i just did plug and play and followed instructions and saw on the dash to update

**Comment by mkellsy** [comment]
I see you got a "WARNING system is not initilized, please initilize the system first." message.
Did you purchase this from our site or Amazon? I ask because we are having a problem with Amazon selling returned devices.

**Comment by caspianguirey** [comment]
your site
and how do i inilize

**Comment by mkellsy** [comment]
It looks like the device was reset but not re-initilized. You can run this command and see if it starts.
```
sudo hbs install
```

It will ask you a series of questions, the defaults are fine, you can just enter through them.

**Comment by caspianguirey** [comment]
perfect just in a meeting for 10 mins can i contact you here in 10 please

**Comment by caspianguirey** [comment]
perfect all finished where do we start

**Comment by caspianguirey** [comment]
you still there

**Comment by mkellsy** [comment]
See if http://hoobs.local works.

**Comment by caspianguirey** [comment]
Hi there thanks forgetting back to me have been trying to get this working all day￼

**Comment by caspianguirey** [comment]
Have tried hoobs.local but says Safari can't connect to the server￼

**Comment by mkellsy** [comment]
If you ran sudo hbs install and http://hoobs.local or http://hoobs is not available, you have a defective device.

please send an email to info@hoobs.con with your order number so we can troubleshoot and replace components if needed.

**Comment by caspianguirey** [comment]
I have sent the email with the order on it about half an hour ago

**Comment by caspianguirey** [comment]
Can we FaceTime or communicate some other way because Some
 is on the forum son is via email I don’t even know if I’m doing this correctly Do you have a phone number where I can maybe speak to some customer care

**Comment by caspianguirey** [comment]
Okay where would you like me to run that command in terminal￼

**Comment by caspianguirey** [comment]
I am not sure what lights I am even supposed to see on the device￼

**Comment by caspianguirey** [comment]
You said reinitialise the device by running a command where would you like me to run the command￼

**Comment by caspianguirey** [comment]
![image](https://user-images.githubusercontent.com/89479884/130678640-987a5fe2-e84e-49ca-801e-bef4ea7a2f66.png)

**Comment by caspianguirey** [comment]
Just wondering are you still online in this chat￼

**Comment by mkellsy** [comment]
You run the command in the same place as the others I sent to you.

https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

However I think the SD Card is bad. Please continue with the RMA process. Please allow 24-48 hours for a response.

**Comment by caspianguirey** [comment]
Okay perfect I have got in it is asking for a log in can you help me with that please

**Comment by caspianguirey** [comment]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15

Login: 
This is where we are at right now. Is that of any help

**Comment by mkellsy** [comment]
Login: hoobs 
Password: hoobsadmin

https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

**Comment by caspianguirey** [comment]
***@***.***:~ $ 
***@***.***:~ $ 

Thanks Michael appreciate all your help have entered the username and password this is where we are at now. I am normally pretty good at this stuff but don't have any idea about coding in terminal. Looks like we might be getting somewhere.

**Comment by mkellsy** [comment]
sudo hbs install

**Comment by caspianguirey** [comment]
this is what is coming up

Error: Cannot find module 'source-map-support/register'
Require stack:
- /usr/lib/hoobsd/main.js
- /usr/bin/hoobsd
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/hoobsd/main.js:41:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/lib/hoobsd/main.js', '/usr/bin/hoobsd' ]
}
 ERROR  (node:2527) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: 
    at new SemVer (/usr/lib/hbs/node_modules/semver/classes/semver.js:38:13)
    at compare (/usr/lib/hbs/node_modules/semver/functions/compare.js:3:32)
    at Object.gt (/usr/lib/hbs/node_modules/semver/functions/gt.js:2:29)
    at Object.info (/usr/src/system/index.ts:400:103)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Command.<anonymous> (/usr/src/main.ts:58:50)
(Use `node --trace-warnings ...` to show where the warning was created)
 ERROR  (node:2527) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 ERROR  (node:2527) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
***@***.***:~ $

**Comment by mkellsy** [comment]
Again. Your device is defective. The SD Card needs to be replaced. If you haven’t already, please send an email to info@hoobs.com. Include your order number. Please allow 24-48 hours for a response.

**Comment by caspianguirey** [comment]
Does that mean we are logged onto the hoobs box or is it not on the network￼

**Comment by caspianguirey** [comment]
Okay thanks for your help I have sent the email in. I did manage to get onto the hub this morning when I first 20 again and then did the update that was there and then from then on I could not get onto the network or even find it wirelessly with this be normal
