### ISSUE TITLE
Can't update GUI to 4.0.88 (from 4.0.86)

### ISSUE THREAD

**Issue by ColinScattergood** [hoobs-org/HOOBS#1489]
I have the following update available for the GUI:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/943049/131139199-fbb2773b-b340-4737-a578-4e70a219f41e.png">

However, when I click update, HOOBS thinks that 4.0.86 IS the latest version, and I get:

**10:00:42 AMReading package lists...
10:00:47 AMReading package lists...
10:00:47 AMBuilding dependency tree...
10:00:48 AMReading state information...
10:00:49 AMhoobs-gui is already the newest version (4.0.86).
10:00:49 AMThe following package was automatically installed and is no longer required:
10:00:49 AMlibbrotli1
10:00:49 AMUse 'apt autoremove' to remove it.
10:00:56 AM0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
10:00:56 AMWARNINGservice restart command received
10:00:56 AMrestarting
10:00:56 AM**

**Comment by mkellsy** [comment]
I am not seeing our repo in the list. Try running this.
```
wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
```

It won't install anything, it just reconfigures the repo lists.

Then you can see which version is available by running this.
```
apt-cache show hoobs-gui | grep Version
```

You should see something like this *Version: 4.0.88*. If you do, try the update again.

**Comment by ColinScattergood** [comment]
This worked!! Thanks a ton!!
