### ISSUE TITLE
Can't update from 3.3.5 to 3.3.12

### ISSUE THREAD

**Issue by nickcarey86** [hoobs-org/HOOBS#1491]
**Description**
I'm ultimately trying to update to Hoobs 4 but it says the only update available is 3.3.12. When trying to update in the GUI interface it hangs and does nothing only stops the bridge service.

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
Not sure.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
SmartThings
2.3.8 published 8/19/2020
Samsung Tizen
5.0.1 published 4/13/2021
Ring
9.21.0 published 8/14/2021

**Post your config**
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYBML3",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": "ST4"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "29:A5:51:55:7F:6E"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "SamsungTizen",
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "Living Room TV",
                    "ip": "192.168.1.40",
                    "mac": "B8:BC:5B:25:F7:53"
                }
            ]
        },
        {
            "platform": "SmartThings-v2",
            "plugin_map": {
                "plugin_name": "homebridge-smartthings"
            },
            "name": "SmartThings-v2",
            "direct_port": 8000,
            "temperature_unit": "C",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "Good"
                }
            },
            "app_url": "https://graph-eu01-euwest1.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "58180363-bc58-47ed-83b5-8a759dd16c3b",
            "access_token": "36ae5f5b-7bd4-4693-b3c4-ce81fff43afe"
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MzAxNTkwNTgsImlzcyI6IlJpbmdPYXV0aFNlcnZpY2UtcHJvZDp1cy1lYXN0LTE6OTI2YmM1ZWYiLCJyZWZyZXNoX2NpZCI6InJpbmdfb2ZmaWNpYWxfYW5kcm9pZCIsInJlZnJlc2hfc2NvcGVzIjpbImNsaWVudCJdLCJyZWZyZXNoX3VzZXJfaWQiOjY2MDk0NjMsInJuZCI6IjZGUWt0aExxRkRXdmFnIiwic2Vzc2lvbl9pZCI6ImM5OTkzYzU3LTk2ZTItNDdhMy1iOTMzLTRhMWQ3ZmNhMmMyMSIsInR5cGUiOiJyZWZyZXNoLXRva2VuIn0.dOYGXZxagJpgF6CA4Xl-hfit2uBJMl16Okj-Y9AZXKwV3N2pChU0Oj9eNhUdTWEkiN8YoUT62B6ekgPsHjNzBw"
        }
    ]
}
**Post your log**
28/08/2021, 15:16:17 HOOBS listening on port 80.
28/08/2021, 15:16:19 Initializing HAP-NodeJS v0.9.3...
28/08/2021, 15:16:23 Loaded plugin 'homebridge-ring'
28/08/2021, 15:16:24 [8/28/2021, 8:16:23 AM] Registering platform 'homebridge-ring.Ring'
28/08/2021, 15:16:24 Loaded plugin 'homebridge-samsung-tizen'
28/08/2021, 15:16:24 [8/28/2021, 8:16:24 AM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
28/08/2021, 15:16:25 Loaded plugin 'homebridge-smartthings'
28/08/2021, 15:16:25 [8/28/2021, 8:16:25 AM] Registering platform 'homebridge-smartthings.SmartThings-v2'
28/08/2021, 15:16:25 Loading 3 platforms...
28/08/2021, 15:16:25 [SamsungTizen] Initializing SamsungTizen platform...
28/08/2021, 15:16:25 [SmartThings-v2] Initializing SmartThings-v2 platform...
28/08/2021, 15:16:26 INFO: Homebridge Version: 2.7
28/08/2021, 15:16:26 INFO: SmartThings-v2 Plugin Version: 2.3.8
28/08/2021, 15:16:26 INFO: Checking Package Version for Updates...
28/08/2021, 15:16:26 [Ring] Initializing Ring platform...
28/08/2021, 15:16:26 [Ring] Configuring cached accessory 817dc641-d736-4bee-a24b-693275fd5662 Front Door
28/08/2021, 15:16:26 [Ring] Configuring cached accessory 7f2fc87a-78fb-48a7-8383-bdf69896b14e Garden
28/08/2021, 15:16:26 Failed to find plugin to handle accessory Christmas Tree
28/08/2021, 15:16:26 INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
28/08/2021, 15:16:26 GOOD: Refreshing All Device Data | Source: (First Launch)
28/08/2021, 15:16:26 Preparing Advertiser for 'HOOBS 9995' using bonjour-hap backend!
28/08/2021, 15:16:26 Starting to advertise 'HOOBS 9995' using bonjour-hap backend!
28/08/2021, 15:16:26 Bridge is running on port 51826.
28/08/2021, 15:16:26 Preparing Advertiser for 'Living Room TV 7057' using bonjour-hap backend!
28/08/2021, 15:16:26 Starting to advertise 'Living Room TV 7057' using bonjour-hap backend!
28/08/2021, 15:16:26 Living Room TV 7057 is running on port 36259.
28/08/2021, 15:16:26 Please add [Living Room TV 7057] manually in Home app. Setup Code: 031-45-154
28/08/2021, 15:16:27 NOTICE: Temperature Unit is Now: (C)
28/08/2021, 15:16:27 NOTICE: Updating Global Values | HubIP: 192.168.1.41 | UseLocal: false
28/08/2021, 15:16:27 WARN: Devices to Remove: (0) []
28/08/2021, 15:16:27 INFO: Devices to Update: (2)
28/08/2021, 15:16:27 GOOD: Devices to Create: (0) []
28/08/2021, 15:16:27 ALERT: Total Initialization Time: (1 seconds)
28/08/2021, 15:16:27 NOTICE: Unknown Capabilities: []
28/08/2021, 15:16:27 INFO: SmartThings DeviceCache Size: (2)
28/08/2021, 15:16:27 INFO: WebServer Initiated...
28/08/2021, 15:16:27 INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
28/08/2021, 15:16:27 INFO: Direct Connect Active | Listening at 192.168.1.47:8000
28/08/2021, 15:16:27 INFO: SmartThings-v2 Hub Communication Established
28/08/2021, 15:16:28 [Ring] Found the following locations:
28/08/2021, 15:16:28 [Ring]   locationId: 33e3ef56-da9b-4345-5d85-28bbeaf885c4 - Stoke-on-Trent
28/08/2021, 15:16:29 [Ring] Configuring 2 cameras and 2 devices for location "Stoke-on-Trent" - locationId: 33e3ef56-da9b-4345-5d85-28bbeaf885c4
28/08/2021, 15:16:31 INFO: INFO: Your plugin version is up-to-date
28/08/2021, 15:16:31 NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.8
28/08/2021, 15:17:42 Got SIGINT, shutting down Bridge...
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:50 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:17:51 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
28/08/2021, 15:18:01 npm
28/08/2021, 15:18:01 ERR! code ENOTEMPTY
28/08/2021, 15:18:01 npm ERR! syscall rename
28/08/2021, 15:18:01 npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
28/08/2021, 15:18:01 npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
28/08/2021, 15:18:01 npm ERR! errno -39
28/08/2021, 15:18:01 
28/08/2021, 15:18:01 npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'
28/08/2021, 15:18:01 
28/08/2021, 15:18:01 
28/08/2021, 15:18:01 
28/08/2021, 15:18:01 npm ERR! A complete log of this run can be found in:
28/08/2021, 15:18:01 npm ERR!     /root/.npm/_logs/2021-08-28T14_18_01_787Z-debug.log
28/08/2021, 15:18:01 
28/08/2021, 15:19:48 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826

**Comment by mkellsy** [comment]
NPM is stuck. We have a doc for this.
https://support.hoobs.org/docs/60e62f336c19a6a5ca8f580f
