### ISSUE TITLE
Can't access hoobs

### ISSUE THREAD

**Issue by MalcolmChapel** [hoobs-org/HOOBS#1492]
I connected my hoobs after it having been disconnected for a while. Now I can't access it at all. When I use the IP address as shown by my router it states “invalid IP address”.

**Comment by wegi95** [comment]
I have the same problem since a few days (Raspberry Pi 4, 2GB, newest version of HOOBS (upgraded from v3.x, installed using the provided sd-card image)).

Can‘t even connect via ssh. HOOBS is still working fine (HomeKit) but the Raspberry is not reachable at all (also unable to connect to both Pi-Hole and Phoscon).
However, when I unplug the Raspberry and plug it in again, everything is reachable again.

**Comment by MalcolmChapel** [comment]
Nothing on mine is reachable. Waiting to see how responsive HOOBS is.

**Comment by mkellsy** [comment]
Try
http://hoobs
or
http://hoobs.local
or
http://192.168.xxx.xxx (replace 192.168.xxx.xxx with the up address of the device)

**Comment by MalcolmChapel** [comment]
Tried all of these. When I try to access through the mac OS app, it states that the IP address (shown in my router) is “invalid”.

**Comment by mkellsy** [comment]
The invalid up means that the IP is not active. Is your device on? Red led off? Did the IP change?

**Comment by MalcolmChapel** [comment]
Device is on: sold amber light, flickering green light. Eero is showing IP address: has not changed.

**Comment by MalcolmChapel** [comment]
I can see a flashing red light through the grill on the unit. Didn't see before because of angle.

**Comment by mkellsy** [comment]
The amber LED shouldn't be on. Try to access the terminal.
https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

Then try running these commands.
```
sudo systemctl status hoobsd
```

It should say active.

Also check to see if there is SD Card corruption.
```
node -v
```
It should return a version number.

**Comment by MalcolmChapel** [comment]
Says

sudo: systemctl: command not found

**Comment by mkellsy** [comment]
That’s bad. We see this when the SD Card is corrupt. You will need to re-flash your SD Card, which might not work. You may need to replace it.

This can happen when the device is unplugged. It’s like unplugging a desktop computer. There is a chance corruption.

**Comment by MalcolmChapel** [comment]
This is a homebridge in a box I bought from you.

**Comment by mkellsy** [comment]
Then send an email to info@hoobs.com with your order number. We can continue to troubleshoot and replace components as needed. Please allow for 24 to 48 hours for a response.
