### ISSUE TITLE
Login and password in Hoobs > Terminal

### ISSUE THREAD

**Issue by rump1991** [hoobs-org/HOOBS#1495]
I have the latest software on my HOOBS, when I enter the Terminal it asks me a login and password, when I try to enter a login and password from my account nothing happens. What do I do wrong, what the login and password should be?

**Comment by mkellsy** [comment]
https://support.hoobs.org/docs/60e09b9a646faaa152f10dc3

See the terminal section.

the default username is **hoobs** the default password is **hoobsadmin**
