### ISSUE TITLE
Edit shortcuts don't work on macOS app

### ISSUE THREAD

**Issue by oisinlavery** [hoobs-org/HOOBS#1499]
**Description**
cmd + c, cmd + v, etc. don't work on the macOS app

This can be fixed by adding the Edit menu to MainMenu in Xcode (it is added by default but I guess it was removed...)

**Version**
macOS app

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
macOS Big Sur (11.5.1)

**List your plugins**
n/a

**Post your config**
n/a

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
The terminal is not typical. Modern terminals have moved this functionality to the right click.

select any text in the terminal and right click. It will copy it.

when nothing is selected, right click and it will paste.

see in a terminal control keys mean different things. For example ctl+c is the end program key not paste. However the Apple command key is not mapped, so I will look into it.
