### ISSUE TITLE
How to keep Raspbian up to date?

### ISSUE THREAD

**Issue by VladimirSpidla** [hoobs-org/HOOBS#150]
Even after running _hoobs-update_ the os itself is not up to date.

Is a _apt-get update && apt-get upgrade_ save to do or how can be assured that the os is running with the latest updates?

**Comment by mkellsy** [comment]
HOOBS doesn't upgrade your OS. You can run apt-get update && apt-get upgrade on your own. If you started with 2.1.1 it is using Raspbian Buster.
