### ISSUE TITLE
Can’t connect to Hoobs

### ISSUE THREAD

**Issue by fleshparade** [hoobs-org/HOOBS#1503]
Started to update Hoobs 3 and was logged in to Hoobs until one of the updates killed my connection. How can I get back in?

**Comment by EddieDSuza** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)
