### ISSUE TITLE
User ID and password showing "INVALID" on Hoobs installed on RaspBerry PI 400. 

### ISSUE THREAD

**Issue by colonelshag** [hoobs-org/HOOBS#1504]
User ID and password showing "INVALID" on Hoobs installed on RaspBerry PI 400.   Have tried all the admin admin, admin hoobsadmin. and it is a new install so not setup.  tried to reset using the command line, but still get teh same message.  Any help is appreciated.

**Comment by mkellsy** [comment]
There is no default password. The first screen has you setup an account.

you may need to initialize. Run this

sudo hbs install
