### ISSUE TITLE
Vivint Devices stopped working

### ISSUE THREAD

**Issue by jcdelacruz23** [hoobs-org/HOOBS#1507]
My Vivint devices stopped working using HomeKit app after the Vivint technician installed airbridge and connected the main panel to airbridge rather than directly to my wireless SSID.

**Comment by EddieDSuza** [comment]
Have the technician to reconnect the vivant devices to your main network or have the HOOBS device on that network where the vivint devices reside 

Again, you will need to fix your network configurations and have also of your devices be on the same subnet / network as the same as HOOBS

**Comment by jcdelacruz23** [comment]
I did that part. Everything is directly connected to the main router. All vivant devices still not working.  I did uninstall the plugin and reinstall the plugin.  After reinstalling the plugins. There’s no vivint device showing on my HomeKit app. And it created it’s on homebridge instead of using the hoops hombridge.

9/6/2021, 4:39:01 PMVivint BridgeConfiguration change
9/6/2021, 4:39:01 PMvivintbridge stopping
9/6/2021, 4:39:07 PMVivint Bridge starting
9/6/2021, 4:39:26 PMVivint BridgeLoaded plugin ***@***.***/homebridge-vivint'
9/6/2021, 4:39:26 PMVivint BridgeLoading 1 platforms...
9/6/2021, 4:39:26 PMVivint BridgeBridge is running on port 51826.
9/6/2021, 4:39:52 PMVivint BridgeVivintERRORError occured during login, retrying... RequestError: Error: socket hang up
    at new RequestError (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/lib/hoobs/vivintbridge/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.emit (domain.js:470:12)
    at Request.onRequestError (/var/lib/hoobs/vivintbridge/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:470:12)
    at TLSSocket.socketOnEnd (_http_client.js:499:9)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  cause: Error: socket hang up
      at connResetException (internal/errors.js:628:14)
      at TLSSocket.socketOnEnd (_http_client.js:499:23)
      at TLSSocket.emit (events.js:412:35)
      at TLSSocket.emit (domain.js:470:12)
      at endReadableNT (internal/streams/readable.js:1317:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'ECONNRESET'
  },
  error: Error: socket hang up
      at connResetException (internal/errors.js:628:14)
      at TLSSocket.socketOnEnd (_http_client.js:499:23)
      at TLSSocket.emit (events.js:412:35)
      at TLSSocket.emit (domain.js:470:12)
      at endReadableNT (internal/streams/readable.js:1317:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'ECONNRESET'
  },
  options: {
    method: 'POST',
    url: 'https://vivintsky.com/api/login',
    body: '{}',
    resolveWithFullResponse: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    transform2xxOnly: false
  },
  response: undefined
}
9/6/2021, 4:39:53 PMVivint BridgeConfiguration change
9/6/2021, 4:39:53 PMvivintbridge stopping
9/6/2021, 4:39:58 PMVivint Bridge starting
9/6/2021, 4:40:05 PMVivint BridgeLoaded plugin ***@***.***/homebridge-vivint'
9/6/2021, 4:40:05 PMVivint BridgeLoading 1 platforms...
9/6/2021, 4:40:05 PMVivint BridgeBridge is running on port 51826.
9/6/2021, 4:42:28 PMVivint Bridge 2 starting
9/6/2021, 4:42:42 PMVivint Bridge 2WARNINGNo plugins installed.
9/6/2021, 4:42:43 PMVivint Bridge 2Bridge is running on port 51836.
9/6/2021, 4:43:09 PMVivint Bridge 2Configuration change
9/6/2021, 4:43:09 PMvivintbridge2 stopping
9/6/2021, 4:43:14 PMVivint Bridge 2 starting
9/6/2021, 4:43:25 PMvivintbridge2 stopping
9/6/2021, 4:43:31 PMVivint Bridge 2 starting
9/6/2021, 4:43:38 PMVivint Bridge 2Loaded plugin ***@***.***/homebridge-vivint'
9/6/2021, 4:43:38 PMVivint Bridge 2Loading 1 platforms...
9/6/2021, 4:43:38 PMVivint Bridge 2Bridge is running on port 51836.
9/6/2021, 4:44:49 PMvivintbridge stopping
9/6/2021, 4:44:54 PMVivint Bridge starting
9/6/2021, 4:45:01 PMVivint BridgeLoaded plugin ***@***.***/homebridge-vivint'
9/6/2021, 4:45:01 PMVivint BridgeLoading 1 platforms...
9/6/2021, 4:45:01 PMVivint BridgeBridge is running on port 51826.
9/6/2021, 4:47:13 PMvivintbridge2 stopping
9/6/2021, 4:48:21 PMVivint Bridge 2 starting
9/6/2021, 4:48:35 PMVivint Bridge 2WARNINGNo plugins installed.
9/6/2021, 4:48:35 PMVivint Bridge 2Bridge is running on port 51836.
9/6/2021, 4:48:56 PMVivint Bridge 2Configuration change
9/6/2021, 4:48:56 PMvivintbridge2 stopping
9/6/2021, 4:49:01 PMVivint Bridge 2 starting
9/6/2021, 4:49:21 PMVivint Bridge 2Loaded plugin 'homebridge-vivint'
9/6/2021, 4:49:21 PMVivint Bridge 2Loading 1 platforms...
9/6/2021, 4:49:21 PMVivint Bridge 2Bridge is running on port 51836.
9/6/2021, 4:49:21 PMVivint Bridge 2VivintError while bootstrapping accessories
9/6/2021, 4:49:21 PMVivint Bridge 2VivintStatusCodeError: 403 - "<!DOCTYPE html>\n\n\n\n <html class=\"no-js\" lang=\"en-US\"> \n<head>\n<title>Attention Required! | Cloudflare</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n\n\n\n<script>\n  if (!navigator.cookieEnabled) {\n    window.addEventListener('DOMContentLoaded', function () {\n      var cookieEl = document.getElementById('cookie-alert');\n      cookieEl.style.display = 'block';\n    })\n  }\n</script>\n\n\n\n</head>\n<body>\n  <div id=\"cf-wrapper\">\n    <div class=\"cf-alert cf-alert-error cf-cookie-error\" id=\"cookie-alert\" data-translate=\"enable_cookies\">Please enable cookies.</div>\n    <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n      <div class=\"cf-wrapper cf-header cf-error-overview\">\n        <h1 data-translate=\"block_headline\">Sorry, you have been blocked</h1>\n        <h2 class=\"cf-subheadline\"><span data-translate=\"unable_to_access\">You are unable to access</span> vivintsky.com</h2>\n      </div>\n\n      <div class=\"cf-section cf-highlight\">\n        <div class=\"cf-wrapper\">\n          <div class=\"cf-screenshot-container cf-screenshot-full\">\n            \n              <span class=\"cf-no-screenshot error\"></span>\n            \n          </div>\n        </div>\n      </div>\n\n      <div class=\"cf-section cf-wrapper\">\n        <div class=\"cf-columns two\">\n          <div class=\"cf-column\">\n            <h2 data-translate=\"blocked_why_headline\">Why have I been blocked?</h2>\n\n            <p data-translate=\"blocked_why_detail\">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>\n          </div>\n\n          <div class=\"cf-column\">\n            <h2 data-translate=\"blocked_resolve_headline\">What can I do to resolve this?</h2>\n\n            <p data-translate=\"blocked_resolve_detail\">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>\n          </div>\n        </div>\n      </div>\n\n      <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n  <p class=\"text-13\">\n    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">68aa9040286d58a6</strong></span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Your IP</span>: 108.31.176.83</span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n</div>\n\n\n    </div>\n  </div>\n\n  <script type=\"text/javascript\">\n  window._cf_translation = {};\n  \n  \n</script>\n\n</body>\n</html>\n"
TJ Jerome Dela Cruz
(408) 219-1667
***@***.***
***@***.***

**Comment by jcdelacruz23** [comment]
Additional information see attachment from my hoobs.local







Thank You,

TJ Jerome Dela Cruz
