### ISSUE TITLE
Can't paste into Terminal in iOS

### ISSUE THREAD

**Issue by Calorion** [hoobs-org/HOOBS#1509]
**Description**
When using the Terminal from within the HOOBS interface, it is impossible to paste text. This makes using secure passwords or executing long commands very difficult.

**Version**
4.0.100

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**

"Pervious"?

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Additional context**
Technically you *can* paste using the Paste button on the iOS keyboard, but it's useless as you can't then execute the command; Return does nothing.

**Comment by EddieDSuza** [comment]
Right click in the field and you will see the option to paste

**Comment by Calorion** [comment]
How do you right-click on iOS?

**Comment by mkellsy** [comment]
The terminal is not mobile friendly. To use a terminal on an iOS device please use an SSH app.
