### ISSUE TITLE
Add the Ability to Rename Accessories and Store Locally

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#151]
<img width="1012" alt="Screenshot 2019-09-17 at 13 46 24" src="https://user-images.githubusercontent.com/50763727/65039037-a11b2580-d951-11e9-8260-485563492926.png">
with these names nobody can use it, please add a feature to rename accessories to logical names. eg. Livingroom Lamp

**Comment by mkellsy** [comment]
Add the Ability to Rename Accessories and Store Locally

**Comment by mkellsy** [comment]
Same issue as reported to the core repo

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.48
