### ISSUE TITLE
Plugin store unavailable

### ISSUE THREAD

**Issue by cinaali** [hoobs-org/HOOBS#1510]
I keep getting an error that says "plugin store unavailable" whenever I tried to install a plugin.  Tried restarting.  Brand new hoobs system.  Version 4.0.100.  

All help appreciated.

**Comment by EddieDSuza** [comment]
Connect your box to the main node and also ensure no network rules are applied to ports or the IP address of the box.

That error indicates the box is unable to communicate with the outside world.

**Comment by mkellsy** [comment]
"plugin store unavailable" means the device is not connected to the internet. The site it's trying to reach is https://plugins.hoobs.org.

Check you router.
