### ISSUE TITLE
Can access hoobs.local but no login prompt

### ISSUE THREAD

**Issue by Daz1811** [hoobs-org/HOOBS#1512]
**Description**
After updating to Hoobs 4 I do not longer get the user ID prompt when accessing hoobs.local

**Version**
Hoobs 4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
Hoobs 3.3.12

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYKNLB",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "tealzier",
        "locale": "es",
        "temp_units": "celsius",
        "country_code": "ES",
        "postal_code": "xxxxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "x",
        "username": "x"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-samsung-tizen",
        "homebridge-platform-wemo",
        "homebridge-camera-ffmpeg"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "SamsungTizen",
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "name": "homebridge-samsung-tizen",
            "devices": [
                {
                    "name": "Tele",
                    "ip": "192.168.0.x",
                    "mac": "x",
                    "uuid": "A1",
                    "switches": [
                        {
                            "name": "Bajar volumen",
                            "command": "KEY_VOLDOWN"
                        },
                        {
                            "name": "Subir volumen",
                            "command": "KEY_VOLUP"
                        },
                        {
                            "name": "Subir canal",
                            "command": "KEY_CHUP"
                        },
                        {
                            "name": "Bajar canal",
                            "command": "KEY_CHDOWN"
                        }
                    ],
                    "inputs": [
                        {
                            "name": "Live TV",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "Netflix",
                            "type": "app",
                            "value": "11101200001"
                        },
                        {
                            "name": "YouTube",
                            "type": "app",
                            "value": "111299001912"
                        },
                        {
                            "name": "HBO España",
                            "type": "app",
                            "value": "111299002125"
                        },
                        {
                            "name": "Prime Video",
                            "type": "app",
                            "value": "3201512006785"
                        },
                        {
                            "name": "Disney +",
                            "type": "app",
                            "value": "3201901017640"
                        },
                        {
                            "name": "Apple TV",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT*4",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "Apple Music",
                            "type": "app",
                            "value": "3201908019041"
                        }
                    ]
                }
            ],
            "app_list": true
        },
        {
            "platform": "BelkinWeMo",
            "plugin_map": {
                "plugin_name": "homebridge-platform-wemo"
            },
            "name": "Wemo",
            "mode": "auto",
            "disableDeviceLogging": true
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "cameras": [
                {
                    "name": "Camara x 01",
                    "manufacturer": "TP-Link",
                    "model": "C100",
                    "videoConfig": {
                        "source": "-rtsp_transport http -re -i rtsp://xxxxx@192.168.0.x:554/stream1",
                        "stillImageSource": "-rtsp_transport tcp -re -i rtsp://xxxx@192.168.0.x:554/stream1",
                        "maxStreams": 2,
                        "maxWidth": 1024,
                        "maxHeight": 576,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "h264_omx",
                        "audio": true,
                        "debug": true
                    }
                }
            ],
            "tlsmqtt": true,
            "name": "Camera FFmpeg"
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

Tried running apt update
 
hoobs@hoobs:~ $ sudo apt update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 https://deb.nodesource.com/node_14.x buster InRelease                    
Hit:3 https://dl.yarnpkg.com/debian stable InRelease                           
Hit:4 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease       
Get:5 https://dl.hoobs.org/deb/stable buster InRelease [3,022 B]
Fetched 3,022 B in 4s (693 B/s)      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
120 packages can be upgraded. Run 'apt list --upgradable' to see them.
hoobs@hoobs:~ $ sudo apt install hoobsd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hoobsd is already the newest version (4.0.100).
The following package was automatically installed and is no longer required:
  libbrotli1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 120 not upgraded.
hoobs@hoobs:~ $ sudo npm install -g @hoobs/migration
/usr/bin/hbs-migrate -> /usr/lib/node_modules/@hoobs/migration/bin/hbs-migrate
+ @hoobs/migration@4.4.24
updated 1 package in 43.779s

![image](https://user-images.githubusercontent.com/90212949/132251098-af4a3109-6741-4238-9ebf-339b32c89ea8.png)

**Comment by EddieDSuza** [comment]
SSH into the box and run `sudo reboot`

**Comment by mkellsy** [comment]
If the migration fails, it will retry on nest start. Simply reboot and the migration will attempt again. If it continues to fail, you may have to do a manual migration.

https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

If it continues to fail, it might be worth starting with a fresh image.

**Comment by Daz1811** [comment]
Tried rebooting several times. Even installed image (4.0.31 image just downloaded from the hoobs website) again in a fresh SD card. First boot, everything works fine but as soon as anything is updated, same happens (no user ID prompt when accessing the hoobs server either via hoobs.local or IP).

At first I didn't notice any other problems. But then, accessories started to not work randomly, when up until this update to Hoobs 4 everything worked fine. Seems like a very unstable build!

**Comment by mkellsy** [comment]
4.0.31 is not the latest build.
https://github.com/hoobs-org/repo/releases/download/v4.0.33/hoobs-v4.0.33.zip

**Comment by Daz1811** [comment]
Yes, that is the case, but that was the build available when I downloaded the latest version from the Hoobs site. When I installed it as a fresh image, it immediately show there were updates available, so I went ahead. When it rebooted, the same ID prompt problem reappeared.

I'll try the manual migration with the original SD card to see if it works.

**Comment by mkellsy** [comment]
The UI actually runs in your browser. The 2 things I can think of that would stop the login dialog from showing is;

1. You browser can't connect to websockets
2. You browser has local storage disabled

What browser are you using? What version?

You can try to clear your browser cache and see if that helps.

The other option is use our desktop app https://support.hoobs.org/downloads/desktop
HOOBS Desktop doesn't use your browser and shouldn't have an issue.
