### ISSUE TITLE
What to do after fail migration?

### ISSUE THREAD

**Issue by kennethlf2** [hoobs-org/HOOBS#1514]
I was upgrading my HOOBS 3 to 4 and it is "suppose" to take 10-20 mins, however after letting it upgrade for over a night, it is still stuck on the migrating page. I refresehd the page and now I no longer can access hoobs.local page. I unplugged the HOOBS and plugging it back in it still does not fix the issue, what is there for me to do to "fix" this issue?

**Comment by mkellsy** [comment]
https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

**Comment by kennethlf2** [comment]
my hoobs doesn’t even seem to connect to wifi, so i don’t have access to their IP address

**Comment by mkellsy** [comment]
Check your phone. Is it broadcasting the HOOBS access point?

If not what device are you running? Is it a HOOBS Box, SD Card or a custom install?

**Comment by PBXLthrMan** [comment]
I'm having this issue as well, I tried SSH'ing into the box, which is still responding. Resetting to Factory Settings. The box has become completely unresponsive. It's not broadcasting the SSID/WiFi access point, and I've plugged it into the network and rebooted it and I'm still unable to access the box. Everything was fine before migrating from 3 to 4.

**Comment by mkellsy** [comment]
Send an email to info@hoobs.com with your order number. We can troubleshoot further and replace components if needed. Allow 24 - 48 hours for a response.

**Comment by PBXLthrMan** [comment]
> Send an email to [info@hoobs.com](mailto:info@hoobs.com) with your order number. We can troubleshoot further and replace components if needed. Allow 24 - 48 hours for a response.

Thank you. Sent.
