### ISSUE TITLE
Error when updating Hoobs

### ISSUE THREAD

**Issue by simplewilly** [hoobs-org/HOOBS#1515]
I cannot get an IP address assigned to Hoobs.local and cannot get into the web side of it.  I can SSH but get errors when re-installing it.  Please help.  Here is my logfile.

hoobs@hoobs:~ $ wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 https://dl.hoobs.org/deb/stable buster InRelease
Hit:3 https://deb.nodesource.com/node_14.x buster InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Hit:5 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
129 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ rm -f /etc/apt/sources.list.d/hoobs.list
Installing the NodeSource Node.js 14.x repo...
+ apt-get update
Hit:1 https://dl.yarnpkg.com/debian stable InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 https://deb.nodesource.com/node_14.x buster InRelease
Hit:4 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease
Reading package lists... Done
Confirming "buster" is supported...
+ wget -qO /dev/null -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/buster/Release'
Adding the NodeSource repository
+ wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK
+ echo 'deb https://deb.nodesource.com/node_14.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_14.x buster main' >> /etc/apt/sources.list.d/nodesource.list
Adding the Yarn repository
+ wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
OK
+ echo 'deb https://dl.yarnpkg.com/debian/ stable main' | tee /etc/apt/sources.list.d/yarn.list
deb https://dl.yarnpkg.com/debian/ stable main
Adding the HOOBS repository
+ wget -qO- https://dl.hoobs.org/deb/key.gpg | apt-key add -
OK
+ echo 'deb https://dl.hoobs.org/deb/stable/ buster main' | tee /etc/apt/sources.list.d/hoobs.list
deb https://dl.hoobs.org/deb/stable/ buster main
Updating packages
+ apt-get update
Get:1 https://dl.hoobs.org/deb/stable buster InRelease [3,022 B]
Hit:2 https://deb.nodesource.com/node_14.x buster InRelease
Hit:3 https://dl.yarnpkg.com/debian stable InRelease
Hit:4 http://archive.raspberrypi.org/debian buster InRelease
Hit:5 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease
Get:6 https://dl.hoobs.org/deb/stable buster/main armhf Packages [1,245 B]
Fetched 4,267 B in 3s (1,673 B/s)
Reading package lists... Done
Run "sudo apt install -y hoobs" to install HOOBS, node and yarn
hoobs@hoobs:~ $ sudo apt install hoobs
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
hoobs@hoobs:~ $ sudo apt install hoobs
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
hoobs@hoobs:~ $ sudo apt install -y hoobs
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
hoobs@hoobs:~ $ sudo hoobs --configure -a
sudo: hoobs: command not found
hoobs@hoobs:~ $ sudo hoobs --configure -a
sudo: hoobs: command not found
hoobs@hoobs:~ $
hoobs@hoobs:~ $ sudo dpkg --configure -a
Setting up hoobsd (4.0.100) ...
yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 60.74s.
Setting up libpam0g-dev:armhf (1.3.1-5+rpt2) ...
Setting up helm (1.2.5) ...
yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
[1/2] ⢀ @hoobs/pam
error /usr/lib/helm/node_modules/@hoobs/pam: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /usr/lib/helm/node_modules/@hoobs/pam
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.15.1 | linux | arm
gyp info find Python using Python version 3.7.3 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/helm/node_modules/@hoobs/pam/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/14.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/lib/helm/node_modules/@hoobs/pam',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/usr/lib/helm/node_modules/@hoobs/pam/build'
  CXX(target) Release/obj.target/authenticate_pam/authenticate_pam.o
make: *** [authenticate_pam.target.mk:109: Release/obj.target/authenticate_pam/authenticate_pam.o] Bus error
make: Leaving directory '/usr/lib/helm/node_modules/@hoobs/pam/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.72-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/helm/node_modules/@hoobs/pam
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

Failed to lookup unit file state: Input/output error
Failed to start helm.service: Unit helm.service not found.
dpkg: error processing package helm (--configure):
 installed helm package post-installation script subprocess returned error exit status 5
Setting up hoobs-cli (4.0.44) ...
dpkg: error processing package hoobs-cli (--configure):
 unable to open triggers ci file '/var/lib/dpkg/info/hoobs-cli.triggers': Input/output error
dpkg: error processing package man-db (--configure):
 unable to check existence of '/var/lib/dpkg/info/libgcc1:armhf.postinst': Input/output error
dpkg: error: unable to create new file '/var/lib/dpkg/status-new': Input/output error
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the proble

**Comment by simplewilly** [comment]
I did that, see above.   sudo dpkg --configure -a

**Comment by mkellsy** [comment]
Run this command, what does it say

uname -a

**Comment by simplewilly** [comment]
I forgot to tell you, this is a Hoobs box I bought, not a homemade one.  
When I run the command, I get this....

Linux hoobs 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux

**Comment by mkellsy** [comment]
For the HOOBS Box send an email to info@hoobs.com with your order number. We can troubleshoot it further and replace components if needed.
