### ISSUE TITLE
Hoobs restart

### ISSUE THREAD

**Issue by dgilman1** [hoobs-org/HOOBS#1516]
Just recovered from electrical outage. Hoobs in a box shows not connected on Eero pro router and am unable to get on line. There is a orange light on hoobs ethernet connection and a green light on switch Ethernet connection. Not sure is raspberry pi is on line or not  but am not connected to either the software or the browser (Hoobs.local). Any help/direction would be appreciated.

**Comment by mkellsy** [comment]
Power outages can cause drive corruption. Send an email to info@hoobs.com with your order number so we can troubleshoot this and replace components if needed.
