### ISSUE TITLE
HOOBS unresponsive

### ISSUE THREAD

**Issue by SharonT3095** [hoobs-org/HOOBS#1518]
Hi,
I received my HOOBS in a box a few weeks ago.  I did the initial connection and have since left it until I had time to start getting serious! 
Today I have tried to connect and it is unresponsive.
The red light comes on for a few minutes then goes off.
I have followed all instructions and tried connecting directly through router, wifi and through the IP address.
I am unable to see HOOBS via any connection type.
I have not had any changes to systems or connections since I first connected.

The device has not been dropped or damaged in any way and I am using original cables. 
I have tried finding a solution on all support forums and other methods and am unable to find a solution.

Is it possible the device is faulty?

**Comment by mkellsy** [comment]
1. Check to see if the HOOBS access point is on. User your phone.
2. If you can connect, a green LED should light up.

If the green light doesn't come on (it is dim you may need to turn off your lights to see it), send an email to info@hoobs.com with your order number. We can troubleshoot it further and replace components if needed. Please allow 24 - 48 hours for a response.
