### ISSUE TITLE
Vincular FIBARO Roller Shutter 3 con Hoobs

### ISSUE THREAD

**Issue by Fernan39** [hoobs-org/HOOBS#1519]
Hola. Tengo un Homecenter lite y FIBARO Roller Shutter 3 en las persianas. Cómo puedo vincularlo al Hoobs para utilizar con HomeKit? Muchas gracias

**Comment by mkellsy** [comment]
Install a plugin for Fibaro
https://plugins.hoobs.org/search/ZmliYXJv
