### ISSUE TITLE
No Access to HOOBS after attempted update to latest beta version 

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/HOOBS#152]
Tried to update from beta v3.0.0 39 to latest version using this command 
sudo npm install -g --unsafe-perm @hoobs/hoobs
Everything seemed to go well but then nothing ... waited 20-25 min then powered pi off and back on.
Still nothing, no ui and no ability to ssh

**Comment by mkellsy** [comment]
Without further information, I can't find out what happened. Can you post your img file.

https://thepihut.com/blogs/raspberry-pi-tutorials/17789160-backing-up-and-restoring-your-raspberry-pis-sd-card

**Comment by OfficialKaos** [comment]
It's a physical HOOBS box with pre installed sd card! Am I doomed!?

**Comment by mkellsy** [comment]
No. Ovi is trying to work with you to ret remoted in.

**Comment by mkellsy** [comment]
After investigation we found that this was a kernel panic.
