### ISSUE TITLE
Can't uninstall Hoobs from Mac OSX

### ISSUE THREAD

**Issue by thepiecesofme** [hoobs-org/HOOBS#1520]
Hi,

I need help uninstalling HOOBS. I was time to reach out to HOOBS support directly and they don't have any idea what to do and suggested I reach out to GitHub, which is why I'm here.

I installed HOOBS on my Mac mini about six months ago￼ (not using Docker, straight install). I used the instructions available at that time (these seem to have disappeared when V4 came out). I was told for two months that V V4 was available for my server but I couldn't get out upgrade. Support had me change tons is settlings to try to get it to work. Then I hear from another user that there is no v4 for HOOBS on Mac and won't be for the foreseeable future.

Now, I have a non working install and I'm trying to uninstall HOOBS from my Mac mini. But I can't. I've tried the command "sudo npm uninstall @hoobs/hoobs" but it doesn't work. My Mac is called server.local instead of HOOBS.local. Support has no idea to have to install with the server being a different name. I've tried sudo npm uninstall @server/hoobs and sudo npm uninstall @hoobs/server and neither one will work.

If I can't uninstall HOOBS directly, can I remove NPM and have that remove HOOBS when it gets deleted? Any other ideas? Ultimately, I'm trying to get Homebridge installed instead, since they are supporting Mac more moving forward and my current HOOBS install is totally borked. I'm trying to uninstall HOOBS so I can do a fresh install of Homebridge, seems like the only way to switch over.

Could anyone please, please help me get rid of this? I would so, so appreciate it! Thanks so much in advance!!!

**Comment by mkellsy** [comment]
First you need to disable the service and delete the launchctl file.
```
sudo launchctl unload /Library/LaunchDaemons/com.hoobs.core.plist
sudo rm -f /Library/LaunchDaemons/com.hoobs.core.plist
```

Then uninstall the Node module, don't forget the -g (global) flag
```
sudo npm uninstrall -g @hoobs/hoobs
```

If NPM is acting up, you can manually remove the files.
```
sudo rm -fR /usr/local/node_modules/@hoobs/hoobs
sudo rm -f /usr/local/bin/hoobs
```

If you plan on using Homebridge, it installs in the same way, and uses Node and NPM too. So it's best to keep Node and NPM around.

We haven't released HOOBS 4.0 for Mac, in part, for this reason. We want a smoother install and uninstall process and are working towards this.
