### ISSUE TITLE
How to export config.json?

### ISSUE THREAD

**Issue by Calorion** [hoobs-org/HOOBS#1521]
I have a plug-in developer asking me to post my config.json to troubleshoot some errors. However, I don’t see any way within the HOOBS interface to do this. How do you export your config.json file?

**Comment by askovi** [comment]
You can export the bridge that runs that plugin from the bridges page or you can go to the advanced config page and copy paste it from there

**Comment by mkellsy** [comment]
Config Screen -> Advanced Section -> Bridge Tab

This is the config for the bridge's plugins.
