### ISSUE TITLE
Can’t access HOOBS Box

### ISSUE THREAD

**Issue by WHVWHV** [hoobs-org/HOOBS#1524]
I received and installed yesterday successfully a brand new Hoobs in a Box (Model No. HSLF-1) through Ethernet getting proper access including setting up my account).
Today after switching from Ethernet to WiFi (as I had to relocate the Hoobs Box) following the related tutorial on the Hoobs support page I was not longer able to connect to the Hoobs system. Hoobs did (and still does not) not show up as WiFi acces point and unfortunately access through Ethernet was no longer possible.
Hoobs is still detected by network (IP adress defined, able to ping, able to connect through SSH) but Hoobs is not responding (also not through IP address). Also Windows Hoobs desktop software is not able to detect the Box as a Hoobs device, and the error message "IP address invalid" when entering the IP address.
What needs to be done to make this Hoobs in a box responding again ? Thanks.

**Comment by mkellsy** [comment]
From the SSH terminal type this

sudo systemctl start hoobsd.service

**Comment by WHVWHV** [comment]
thanks. done. no message/error reveived in SSH. next?

**Comment by WHVWHV** [comment]
see screenshot related to my above earlier comment

![Hoobs_shellscreen_1](https://user-images.githubusercontent.com/90855593/133860843-778d8bdb-2ac3-42f5-bdef-777de5c25876.jpg)

**Comment by WHVWHV** [comment]
Michael, 

Thanks. Pls see my reply and related screenshot in "github.com"

Regards.

**Comment by mkellsy** [comment]
Is this a HOOBS Bos?

Please send an email to info@hoobs.com. We can troubleshoot and replace components if needed. Please allow 24-48 hours for a response.
