### ISSUE TITLE
Can not log into hoobs.local

### ISSUE THREAD

**Issue by dharmony44** [hoobs-org/HOOBS#1527]
I am using a MacBook Pro.  I logged into local and downloaded the updates.  It then popped up a window saying Merge.  So I click ok.  It seemed to be doing fine. It advised not to turn off your computer.  Cool.  So 30 mins later I come back to Safari can't connect to the server.  I have not been able to login since.

**Comment by EddieDSuza** [comment]
Complete the migration manually [https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a](url)
