### ISSUE TITLE
Plugin Updates not showing up

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1528]
Hi, is there an issue with the plugin section?
There are new versions available but HOOBS does not show them at all.

Not since minutes, updates are available since days but not showing up.

**Comment by mkellsy** [comment]
CouchDB mirror failed. Restarted the follower.

**Comment by mkellsy** [comment]
What plugin?

**Comment by mkellsy** [comment]
The mirror is caught up now
