### ISSUE TITLE
HOOBS Box Causes Eero Malfunction and Network Drop

### ISSUE THREAD

**Issue by wrhayem** [hoobs-org/HOOBS#1529]
**Description**

my HOOBS Box is wired into a remote Eero (Wifi Pro 6) node (also wired to main node). once every few days that particular Eero node will drop from the network completely. this will often times propagate up to the main node and they will all go down. this causes the whole network to restart multiple times. takes about half an hour for things to come back up. i also notice that the Eero is constantly generating a WiFi signal. This has NOT happened since I completely disconnected the HOOBS Box.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

myQ
Ring
MyLink

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
HOOBS uses standard Linux network tools.
This includes Network Manager (from Gnome) and Avahi (mDNS).

Network Manager is used to connect to Wi-Fi
Avahi is used to broadcast a .local address

HOOBS is simply a program that installs on Linux.
The router dropping is solely an issue with Eeros, please contact their support. There isn't anything we can do :(
The only option you have is to connect it with a cable.
