### ISSUE TITLE
Update to 3.0.0 Beta 49 crashes HOOBS

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#153]
After Update ro new Beta HOOBS doesnt Start. This error is in Log.
[Homebridge] at API.accessory (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:45:19)
[Homebridge] at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:261:48)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:80:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:73:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[Homebridge] at startup (internal/bootstrap/node.js:283:19)
[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by mkellsy** [comment]
Yours is failing on this line of code

```
throw new Error(`The requested accessory '${name}' was not registered by any plugin.`);
```

This tells me that one of your plugins is causing this. Can you post your config.json?

`~/.hoobs/etc/config.json`

**Comment by Bladestar2105** [comment]
Okay. This is the error line: [Homebridge] [2019-9-18 3:39:13 PM] Error: The requested accessory 'HomePodRadio' was not registered by any plugin.
I had to reinstall this Plugin https://www.npmjs.com/package/homebridge-airtunes-radio
But why did it lost after updating HOOBS?
Now the service starts without problems.

**Comment by mkellsy** [comment]
Looking into it.

**Comment by Bladestar2105** [comment]
Again after updating to Beta 50 I had to reinstall this Plugin.
