### ISSUE TITLE
Hoobs app can no longer find any device

### ISSUE THREAD

**Issue by colmanllflee** [hoobs-org/HOOBS#1531]
**Description**
Hoob Box is connected to Router with LAN but app says "No Devices.  Make sure your device is plugged in and connected to the Network

The red light of the Hoob Box is on.

**Version**
Please include the version of HOOBS you are using.
Hoobs 4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
MACOS Big Sur

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Add any other context about the problem here
<img width="632" alt="Screenshot 2021-09-19 at 21 51 38" src="https://user-images.githubusercontent.com/91037692/133950766-ac8f480d-3677-45bd-8059-35661737fa6f.png">
.

**Comment by EddieDSuza** [comment]
Go to advanced and populate the IP address of the box
