### ISSUE TITLE
Unable to determine plugin type for "homebridge-broadlink-rm"

### ISSUE THREAD

**Issue by lokiinlove** [hoobs-org/HOOBS#1532]
Hi, i'm setting up Hoobs box after moving to new apartment, wiped Hoobs v3 and flashed with v4, wanted to start from scratch. Have one other plugin for bravia tv, which is running fine, but couldn't make broadlink plugin work for couple of evenings.

**Description**
homebridge-broadlink-rm plugin config is not being showed (blank). Tried fork homebridge-broadlink-rm-samsungtv - same issue. I've tried to write config manually based on examples found on github with no luck. Checking multiple issues on github makes me think problem may be on Hoobs side (seen similar issues for users upgrading from older to newer version). I'm using RM4C mini if that makes any difference.

**Expected behavoir**
Supposed to work i guess

**Plugin name**
homebridge-broadlink-rm
homebridge-broadlink-rm-samsungtv

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Hoobs 4.0.100
Node 14.17.6
Homebridge 1.3.4

**Did you upgrade**
No

**What device are you using?**
HOOBS Box

**Post your config**

```
{
    "platform": "homebridge-broadlink-rm"
}
```

**Post your log**

```
20.09.2021, 11:10:42Broadlink Rm Bridge starting
20.09.2021, 11:10:55Broadlink Rm BridgeWARNINGNo plugins installed.
20.09.2021, 11:10:56Broadlink Rm BridgeBridge is running on port 51836.
20.09.2021, 11:11:18ERRORUnable to determine plugin type for "homebridge-broadlink-rm"
20.09.2021, 11:11:18Broadlink Rm BridgeConfiguration change
20.09.2021, 11:11:18broadlinkrmbridge stopping
20.09.2021, 11:11:20ERRORUnable to determine plugin type for "homebridge-broadlink-rm"
20.09.2021, 11:11:23Broadlink Rm Bridge starting
20.09.2021, 11:11:27ERRORUnable to determine plugin type for "homebridge-broadlink-rm"
20.09.2021, 11:11:39Broadlink Rm BridgeLoaded plugin 'homebridge-broadlink-rm'
20.09.2021, 11:11:39Broadlink Rm BridgeBridge is running on port 51836.
20.09.2021, 11:12:11ERRORUnable to determine plugin type for "homebridge-broadlink-rm"
20.09.2021, 11:12:11ERRORUnable to determine plugin type for "homebridge-broadlink-rm"
```

**Comment by mkellsy** [comment]
I tested this and I was able to install both plugins.
Are you installing these on their own bridge?

Try uninstalling the plugin. Remove the the bridge if it is empty.
Then install the plugin its own bridge.

If that doesn't work, create the bridge first, then install the plugin to the newly created bridge.
