### ISSUE TITLE
Cannot complete install of version 4. 

### ISSUE THREAD

**Issue by BluTango** [hoobs-org/HOOBS#1534]
**Description**
Tried to updgrade first via the web interface, but both the ip and hoobs.local became unreacheable. 
Then I tried to follow the torubleshooting guides to remove 3.3 and install 4 but got stuck . 
When I try to run sudo apt install -y hoobsd hoobs-cli hoobs-gui helm
this is what I get. It seemns that the berckley network is unaccessible. 

hoobs@hoobs:~ $ sudo apt install -y hoobsd hoobs-cli hoobs-gui helm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpam0g-dev lsof
The following NEW packages will be installed:
  helm hoobs-cli hoobs-gui hoobsd libpam0g-dev lsof
0 upgraded, 6 newly installed, 0 to remove and 100 not upgraded.
Need to get 307 kB/14.1 MB of archives.
After this operation, 1038 kB of additional disk space will be used.
Err:1 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf lsof armhf 4.91+dfsg-1
  Could not connect to mirrors.ocf.berkeley.edu:80 (169.229.226.30). - connect (111: Connection refused) Cannot initiate the connection to mirrors.ocf.berkeley.edu:80 (2607:f140:8801::1:30). - connect (101: Network is unreachable)
E: Failed to fetch http://mirrors.ocf.berkeley.edu/raspbian/raspbian/pool/main/l/lsof/lsof_4.91+dfsg-1_armhf.deb  Could not connect to mirrors.ocf.berkeley.edu:80 (169.229.226.30). - connect (111: Connection refused) Cannot initiate the connection to mirrors.ocf.berkeley.edu:80 (2607:f140:8801::1:30). - connect (101: Network is unreachable)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

If I try apt-get update:

hoobs@hoobs:~ $ apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

**Version**
3.3? 
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
3.3
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Ring doorbell
Sonos

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
I have to dig up the instructions on changing the OS main repo.

how complicated is your setup? Re-flashing might be easier.

**Comment by BluTango** [comment]
Hi there and thanks for the reply. I ended up reflashing. So now it works
