### ISSUE TITLE
After upgrading to 4.0 the Envisalink plug-in isn't working and setup is behaving oddly

### ISSUE THREAD

**Issue by TDT1969** [hoobs-org/HOOBS#1535]
EDIT: Updated my RPi to a 4B.  Still having the issue.

**Description**
I have been successfully using HOOBS 3.2.6 with this Plug-in that brings my alarm system into the Home app.

After upgrading to 4.0.1, the Next and MyQ plugins worked great.  However, Envisalink did not.  After some attempts to trouble shoot, I thought I'd start fresh and removed the plugin and associated bridge.

I then added the Envisalink plug in, creating a unique bridge for it.  It all appeared to go well.  I then added to Home app -- and that setup flow appeared to be successful.  The bridge appeared in Home Settings but no accessories appeared in the room it was assigned to (or in any other room).  

When I return to Envisalink configuration to further troubleshoot, it no longer displays the GUI form-based interface but only the JSON file.  Edits to that JSON file cannot be saved.  (My other plugins still have the form-based UI.)

**Version**
4.0.100

**Did you upgrade**
Yes, I believe it was from the version I purchased: 3.2.6.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
No.

**What device are you using?**
Running on a Raspberry Pi 4B (EDIT).  I loaded your SW onto an SD card.

**List your plugins**
Nest
MyQ
Envisalink

**Post your config**
This is just the config for Envisalink. 
```
{
    "accessories": [],
    "platforms": [
        {
            "platform": "Envisalink",
            "password": "**********",
            "pin": "****",
            "host": "192.168.1.8",
            "deviceType": "DSC",
            "zones": [
                {
                    "name": "Front Door",
                    "partition": 1,
                    "type": "door"
                }
            ]
        }
    ]
}
```

**Post your log**
Note, the plugin is installed.
```
9/24/2021, 3:26:58 PM Envisalink Bridge starting
9/24/2021, 3:27:06 PM Envisalink Bridge WARNING No plugins installed.
9/24/2021, 3:27:06 PM Envisalink BridgeLoading 1 platforms...
9/24/2021, 3:27:06 PM Envisalink BridgeBridge is running on port 51826.
```

**Additional context**

**Comment by TDT1969** [comment]
After a reboot logs are slightly different...

9/24/2021, 4:00:49 PMenvisalinkbridge stopping
9/24/2021, 4:00:54 PMEnvisalink Bridge starting
9/24/2021, 4:01:02 PMEnvisalink BridgeERRORError loading plugin "homebridge-envisalink"
9/24/2021, 4:01:02 PMEnvisalink BridgeWARNINGNo plugins installed.
9/24/2021, 4:01:02 PMEnvisalink BridgeLoading 1 platforms...
9/24/2021, 4:01:02 PMEnvisalink BridgeBridge is running on port 51826.

**Comment by askovi** [comment]
I'm using the Envisalink plugin on HOOBS 4 and it works well for me(using it with a DSC panel). Running it on a separate bridge as well. No errors in the logs. I had some port issues with it before but a reboot fixed it. 

You config looks fine too. You mentioned you're running on a Pi 2B? Do you mean a 3B? HOOBS 4 doesn't run on an older than a 3B.

**Comment by TDT1969** [comment]
Apparently it does run on a 2B, but perhaps that's my problem? :)   The Nest and MyQ plug-ins are working just fine on it...

![IMG_88B1B1FFFE3A-1](https://user-images.githubusercontent.com/61669497/134751449-0b69a6b0-7852-4fd5-9867-a6c9b7607a82.jpeg)

**Comment by TDT1969** [comment]
Updated to a 4B and still having the issue.  Nest and MyQ work fine.  Just can’t get any Envisalink doors or windows to appear in Home app despite successful bridge/plug-in install and pairing to Home app.

**Comment by zaxx40** [comment]
Same Issue here. New install plugin does not seem to work with Hoobs4. Bridge is created but will not add any components to homekit
