### ISSUE TITLE
After trying to update my hoobs box to V4 manually its now only accessible using Terminal. Need factory reset instructions.

### ISSUE THREAD

**Issue by nrupal77** [hoobs-org/HOOBS#1538]
Trying so many command looks like its fully messed up. I need to reset the entire device to factory setting. How can i do that?

Need factory reset instructions.

Please if someone can help.

**Comment by mkellsy** [comment]
Please send an email to info@hoobs.com so we can troubleshoot and replace components if needed. Please allow 24-48 hours for a reply.
