### ISSUE TITLE
After trying to update my hoobs box is not accessible and cannot be found

### ISSUE THREAD

**Issue by Elifinela** [hoobs-org/HOOBS#1539]
**Description**
Hello, 
I logged in to my hoobs dashboard and clicked on the update; after clicking on the link, the system logged me out.
After a few minutes, I got an error EI0.
Since then, I cannot get hoobs ack. I tried unplugging it, I restarted my network, nothing. I unplugged it for over 30 min plug again, and nothing.

hoobs.local - nothing happens
using the ip address - nothing happens

Please help

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
I was trying to
- [ ] Yes
- [X ] No

**Previous version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [X] Yes but no sccess 
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
This is a HOOBS Box
Please send an email to info@hoobs.com so we can troubleshoot and replace components if needed. Please allow 24 - 48 hours for a response.
