### ISSUE TITLE
hoobs box not working. Only accessible via Terminal. No service and missing folders.

### ISSUE THREAD

**Issue by nrupal77** [hoobs-org/HOOBS#1540]
**Description**

**Version**
Please include the version of HOOBS you are using.
Raspberry Pi 3 Model B Rev 1.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Removed all plugins

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY917P",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "CA",
        "postal_code": "L6X 0M1",
        "latitude": "L6X 0M1",
        "longitude": "L6X 0M1"
    },
    "bridge": {
        "name": "Stealth HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "01:90:DD:F6:94:88"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": [],
    "package_manager": "npm",
    "system": "hoobs"


**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
From you config file I am assuming you are running HOOBS 3.3.
If you can access the terminal. Run this
```
sudo systemctl enable hoobs
sudo systemctl start hoobs
```

**Comment by Elifinela** [comment]
Hi, thank you for your help. that's what I get:  Sudo systemctl enable hoobs
Password:
Sorry, try again.
Password:
it doesn't let me type anything

**Comment by Elifinela** [comment]
Ok, git it to log in, but the dashboard is blank. nothing in it, just white page

**Comment by Elifinela** [comment]
Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/plugins'

**Comment by nrupal77** [comment]
hoobs@hoobs:~ $ sudo systemctl enable hoobs
Failed to enable unit: Unit file hoobs.service does not exist.

**Comment by nrupal77** [comment]
hoobs@hoobs:~ $ sudo systemctl enable hoobs
Failed to enable unit: Unit file hoobs.service does not exist.
hoobs@hoobs:~ $ sudo systemctl start hoobs
Failed to start hoobs.service: Unit hoobs.service not found.

**Comment by nrupal77** [comment]
> Hi, thank you for your help. that's what I get: Sudo systemctl enable hoobs
> Password:
> Sorry, try again.
> Password:
> it doesn't let me type anything

you wont see anythng but try pass : hoobsadmin

**Comment by nrupal77** [comment]
> From you config file I am assuming you are running HOOBS 3.3.
> If you can access the terminal. Run this
> 
> ```
> sudo systemctl enable hoobs
> sudo systemctl start hoobs
> ```

hoobs@hoobs:~ $ sudo systemctl enable hoobs
Failed to enable unit: Unit file hoobs.service does not exist.
hoobs@hoobs:~ $ sudo systemctl start hoobs
Failed to start hoobs.service: Unit hoobs.service not found.

**Comment by mkellsy** [comment]
This sounds like SD Card corruption.
Please send an email to info@hoobs.com with your order number. We can further troubleshoot and replace components if needed. Please allow 24-48 hours for a response.

**Comment by nrupal77** [comment]
> This sounds like SD Card corruption.
> Please send an email to [info@hoobs.com](mailto:info@hoobs.com) with your order number. We can further troubleshoot and replace components if needed. Please allow 24-48 hours for a response.

Thank you!
