### ISSUE TITLE
Hoobs No longer working

### ISSUE THREAD

**Issue by jcdelacruz23** [hoobs-org/HOOBS#1541]
Hoobs device is not working.  Current version 4.0.104.  The hoobs device is directly connected to the main router.

Issues:

- Hoobs bridge no longer on HomeKit app

- Did a factory reset and tried to add hoobs again on HomeKit with the provided HomeKit code from the back of the device, and it won't add.

- Added the most recent vivint plug-in which created a bridge from the hoobs.local, added the vivint bridge to the HomeKit app and vivint devices is still not visible on the HomeKit app.

**Comment by nrupal77** [comment]
> Hoobs device is not working. Current version 4.0.104. The hoobs device is directly connected to the main router.
> 
> Issues:
> 
> * Hoobs bridge no longer on HomeKit app
> * Did a factory reset and tried to add hoobs again on HomeKit with the provided HomeKit code from the back of the device, and it won't add.
> * Added the most recent vivint plug-in which created a bridge from the hoobs.local, added the vivint bridge to the HomeKit app and vivint devices is still not visible on the HomeKit app.

How did you do factory reset. Can i pls get instructions on how to.

**Comment by mkellsy** [comment]
Try renaming your bridges and re-generating the identifiers.

**Comment by jcdelacruz23** [comment]
Tried to do that still did work.


Thank You,

TJ Jerome Dela Cruz

**Comment by jcdelacruz23** [comment]
I clicked on hub settings then clicked Factory reset

Thank You,

TJ Jerome Dela Cruz

**Comment by jcdelacruz23** [comment]
I mean still didn’t worked.


TJ Jerome Dela Cruz

**Comment by jcdelacruz23** [comment]
Update:  I finally was able to add my vivint accessories thru the Terminal.  Base on Thread from GitHub.  Hoobs would need a sidecar created to support the custom UI components created for homehomebridge.
