### ISSUE TITLE
Two Node  JS Instances after update

### ISSUE THREAD

**Issue by Cojaeck** [hoobs-org/HOOBS#1542]
**Description**
Since updating hoobs to core 3.3.12 it is not starting correct anymore
**Version**
3.3.12

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
do not know. I just pressed update in the webconsole

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Raspian 10 (buster)

**List your plugins**
Shelly, HUE, http Webhooks, Alexa, Homeconnect

**Post your config**
{
    "server": {
        "home_setup_id": "X-HM://0023ISYWY7279",
        "origin": "*",
        "port": 8080,
        "polling_seconds": 5,
        "autostart": 0
    },
    "client": {
        "theme": "tealzier",
        "locale": "de",
        "inactive_logoff": 30,
        "default_route": "status",
        "postal_code": "96479",
        "temp_units": "celsius",
        "country_code": "DE"
    },
    "bridge": {
        "name": "HOOBSBlackPie",
        "port": 51826,
        "pin": "**PIN***",
        "username": "***USERNAME***"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "admin": {
                "enabled": true
            },
            "name": "Shelly",
            "platform": "Shelly",
            "plugin_map": {
                "plugin_name": "homebridge-shelly"
            },
            "staleTimeout": 0
        },
        {
            "plugin_map": {
                "plugin_name": "homebridge-http-webhooks"
            },
            "platform": "HttpWebHooks",
            "statelessswitches": [
                {
                    "id": "statelessswitch1",
                    "name": "Taster Bad",
                    "buttons": [
                        {
                            "name": "Button1",
                            "double_press": true
                        }
                    ]
                },
                {
                    "id": "statelessswitch2",
                    "name": "Taster Bruno",
                    "buttons": [
                        {
                            "name": "Button1",
                            "double_press": true
                        },
                        {
                            "name": "Button2",
                            "double_press": true
                        }
                    ]
                },
                {
                    "id": "statelessswitch3",
                    "name": "Taster Arthur",
                    "buttons": [
                        {
                            "name": "Button1",
                            "double_press": true
                        },
                        {
                            "name": "Button2",
                            "double_press": true
                        }
                    ]
                },
                {
                    "id": "statelessswitch4",
                    "name": "Taster Schlafzimmer",
                    "buttons": [
                        {
                            "name": "Button1",
                            "double_press": true
                        },
                        {
                            "name": "Button2",
                            "double_press": true
                        }
                    ]
                }
            ],
            "webhook_port": "51828"
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": false,
            "users": {
                "***USER***": "***PASSWORD***",
                "***USER***": "***PASSWORD***"
            },
            "hueMotionTemperatureHistory": true,
            "lights": true,
            "wallSwitch": true,
            "hueDimmerRepeat": true,
            "hosts": "IP-ADRESS:1881",
            "forceEveWeather": true,
            "sensors": true,
            "scenesAsSwitch": false,
            "scenes": false,
            "groups": false,
            "rooms": false,
            "effects": true
        },
        {
            "platform": "HomeConnect",
            "plugin_map": {
                "plugin_name": "homebridge-homeconnect"
            },
            "simulator": false,
            "language": {
                "api": "en-GB"
            },
            "clientid": "***string***"
        },
        {
            "platform": "Alexa",
            "plugin_map": {
                "plugin_name": "homebridge-alexa"
            },
            "name": "Alexa",
            "routines": false,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "username": "***Username***",
            "password": "***password***"
        }
    ]
}

**Post your log**
You can get the log from the interface. This is in the Log section.

27/09/2021, 10:25:11 Initializing HAP-NodeJS v0.9.5...
27/09/2021, 10:25:12 Initializing HAP-NodeJS v0.9.4...
27/09/2021, 10:25:15 Loaded plugin 'homebridge-alexa'
27/09/2021, 10:25:15 [9/27/2021, 10:25:15 AM] Registering platform 'homebridge-alexa.Alexa'
27/09/2021, 10:25:16 Loaded plugin 'homebridge-homeconnect'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering platform 'homebridge-homeconnect.HomeConnect'
27/09/2021, 10:25:16 Loaded plugin 'homebridge-http-webhooks'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering platform 'homebridge-http-webhooks.HttpWebHooks'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookSensor'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookSwitch'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookPushButton'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookLight'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookThermostat'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookOutlet'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookSecurity'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookGarageDoorOpener'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookStatelessSwitch'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookLockMechanism'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookWindowCovering'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookFanv2'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] Registering accessory 'homebridge-http-webhooks.HttpWebHookCarbonDioxideSensor'
27/09/2021, 10:25:16 [9/27/2021, 10:25:16 AM] The plugin "homebridge-hue" requires Node.js version of ^14.15.1 which does not satisfy the current Node.js version of v12.16.3. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
27/09/2021, 10:25:19 Loaded plugin 'homebridge-hue'
27/09/2021, 10:25:19 [9/27/2021, 10:25:19 AM] Registering platform 'homebridge-hue.Hue'
27/09/2021, 10:25:19 Loaded plugin 'homebridge-shelly'
27/09/2021, 10:25:20 [9/27/2021, 10:25:20 AM] Registering platform 'homebridge-shelly.Shelly'
27/09/2021, 10:25:20 Loading 5 platforms...
27/09/2021, 10:25:20 [Shelly] Initializing Shelly platform...
27/09/2021, 10:25:20 [HttpWebHooks] Initializing HttpWebHooks platform...
27/09/2021, 10:25:20 [HttpWebHooks] Started server for webhooks on port '51828' listening for host '0.0.0.0'.
27/09/2021, 10:25:20 Initializing platform accessory 'Taster Bad'...
27/09/2021, 10:25:20 [Hue] Initializing Hue platform...
27/09/2021, 10:25:20 [Hue] config.json: warning: plugin_map: ignoring unknown key
27/09/2021, 10:25:20 [Hue] homebridge-hue v0.12.11, node v12.16.3, homebridge v1.3.4
27/09/2021, 10:25:20 [HomeConnect] Initializing HomeConnect platform...
27/09/2021, 10:25:20 [HomeConnect] new HomeConnectPlatform
27/09/2021, 10:25:20 [Alexa] Initializing Alexa platform...
27/09/2021, 10:25:20 [Alexa] homebridge-alexa v0.5.19, node v12.16.3, homebridge v1.3.4
27/09/2021, 10:25:20 Initializing platform accessory 'Alexa'...
27/09/2021, 10:25:20 [Shelly] 15 accessories loaded from cache
27/09/2021, 10:25:20 [HomeConnect] Restored 2 cached accessories
27/09/2021, 10:25:21 [Shelly] Failed to launch the admin server: listen EADDRINUSE: address already in use :::8181
27/09/2021, 10:25:21 Got SIGTERM, shutting down Bridge...
27/09/2021, 10:25:21 [HomeConnect] Starting events stream for all appliances
27/09/2021, 10:25:21 [Hue] warning: latest version: homebridge-hue v0.13.23
27/09/2021, 10:25:21 [Hue] PhosconPIFour: dresden elektronik deCONZ gateway v2.5.81, api v1.16.0
27/09/2021, 10:25:21 [Hue] PhosconPIFour: warning: not using recommended deCONZ gateway version 2.7.1
27/09/2021, 10:25:21 [HomeConnect] [Backofen] Siemens Oven (E-Nr: HN878G4B6/82)
27/09/2021, 10:25:22 [HomeConnect] [Kochfeld] Siemens Hob (E-Nr: EX877LX67E/01)
27/09/2021, 10:25:22 [Hue] PhosconPIFour: /sensors/29: warning: unknown ZHACarbonMonoxide sensor {"config":{"battery":100,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"bdf8116e2dd803314e9bba32bb909d6a","lastseen":"2021-09-27T08:14Z","manufacturername":"Heiman","modelid":"COSensor-EF-3.0","name":"CO Sensor EG","state":{"carbonmonoxide":false,"lastupdated":"2021-09-24T15:30:40.313","lowbattery":false,"tampered":false},"swversion":"2019.9.5","type":"ZHACarbonMonoxide","uniqueid":"ec:1b:bd:ff:fe:ad:a7:c4-01-0500"}
27/09/2021, 10:25:22 [Hue] PhosconPIFour: /sensors/30: warning: unknown ZHACarbonMonoxide sensor {"config":{"battery":100,"on":true,"pending":[],"reachable":false},"ep":1,"etag":"c1b4ecb14ee54b721fc96602524f36a3","lastseen":null,"manufacturername":"Heiman","modelid":"COSensor-EF-3.0","name":"CO Sensor Flur OG","state":{"carbonmonoxide":false,"lastupdated":"2021-01-10T19:12:53.156","lowbattery":false,"tampered":false},"swversion":"2019.9.5","type":"ZHACarbonMonoxide","uniqueid":"bc:33:ac:ff:fe:03:f7:5a-01-0500"}
27/09/2021, 10:25:22 [Hue] PhosconPIFour: /sensors/32: warning: unknown ZHAFire sensor {"config":{"battery":100,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"107c6b22e5e38d13baf4ed23142519f2","lastseen":"2021-09-27T07:45Z","manufacturername":"Heiman","modelid":"SmokeSensor-EF-3.0","name":"Wohnzimmer","state":{"fire":false,"lastupdated":"2021-08-13T19:58:56.047","lowbattery":false,"tampered":false},"swversion":"2019.8.29","type":"ZHAFire","uniqueid":"84:2e:14:ff:fe:ef:58:af-01-0500"}
27/09/2021, 10:25:22 [Hue] PhosconPIFour: /sensors/33: warning: unknown ZHAFire sensor {"config":{"battery":100,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"96341dda4bd526626d9fb1a841d5afa9","lastseen":"2021-09-27T07:59Z","manufacturername":"Heiman","modelid":"SmokeSensor-EF-3.0","name":"Heizung","state":{"fire":false,"lastupdated":"2021-07-17T00:49:06.169","lowbattery":false,"tampered":false},"swversion":"2019.8.29","type":"ZHAFire","uniqueid":"84:2e:14:ff:fe:e5:4c:1a-01-0500"}
27/09/2021, 10:25:22 [Hue] PhosconPIFour: /sensors/36: warning: unknown ZHAFire sensor {"config":{"battery":100,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"da9e17d46a4163009ffa532ece9671d7","lastseen":"2021-09-27T08:23Z","manufacturername":"Heiman","modelid":"SmokeSensor-EF-3.0","name":"Musikzimmer","state":{"fire":false,"lastupdated":"2021-09-22T04:53:30.130","lowbattery":false,"tampered":false},"type":"ZHAFire","uniqueid":"84:2e:14:ff:fe:e3:5a:12-01-0500"}
27/09/2021, 10:25:22 [Hue] PhosconPIFour: /sensors/37: warning: unknown ZHAFire sensor {"config":{"battery":null,"on":true,"pending":[],"reachable":false},"ep":1,"etag":"c1b4ecb14ee54b721fc96602524f36a3","lastseen":null,"manufacturername":"Heiman","modelid":"SmokeSensor-EF-3.0","name":"Flur Kachelofen","state":{"fire":null,"lastupdated":"none","lowbattery":null,"tampered":null},"type":"ZHAFire","uniqueid":"84:2e:14:ff:fe:ef:58:ae-01-0500"}
27/09/2021, 10:25:22 [Hue] PhosconPIFour: /sensors/38: warning: unknown ZHACarbonMonoxide sensor {"config":{"battery":100,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"2374964541b0a7b1d3b6b08ff7f24e26","lastseen":"2021-09-27T08:22Z","manufacturername":"Heiman","modelid":"COSensor-EM","name":"CO Sensor Keller","state":{"carbonmonoxide":null,"lastupdated":"none","lowbattery":null,"tampered":null},"swversion":"1.1.1","type":"ZHACarbonMonoxide","uniqueid":"00:0d:6f:00:14:f6:a9:f7-01-0500"}
27/09/2021, 10:25:22 [Hue] PhosconPIFour: 72 accessories
27/09/2021, 10:25:23 [HomeConnect] [Backofen] Can be placed in standby
27/09/2021, 10:25:23 [HomeConnect] [Kochfeld] Can be switched off
27/09/2021, 10:25:23 [HomeConnect] [Backofen] Event Program Finished
27/09/2021, 10:25:23 [HomeConnect] [Backofen] Inactive (Finished)
27/09/2021, 10:25:23 Initializing platform accessory 'PhosconPIFour'...
27/09/2021, 10:25:23 [Hue] PhosconPIFour: 2 services
27/09/2021, 10:25:23 [Hue] homebridge: error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: undefined
27/09/2021, 10:25:23 [HomeConnect] [Backofen] Door closed
27/09/2021, 10:25:23 [HomeConnect] [Backofen] Inactive (Finished)
27/09/2021, 10:25:23 [HomeConnect] [Backofen] Remote operation enabled (remote control activated, remote start allowed)
27/09/2021, 10:25:23 [HomeConnect] [Kochfeld] Inactive (Inactive)
27/09/2021, 10:25:23 [HomeConnect] [Kochfeld] Remote operation NOT enabled (remote control not activated)
27/09/2021, 10:25:23 [HomeConnect] [Backofen] On
27/09/2021, 10:25:23 [HomeConnect] [Kochfeld] Off
27/09/2021, 10:25:23 [HomeConnect] [Kochfeld] Connected
27/09/2021, 10:25:23 [Hue] Dimmschalter Schlafzimmer: set homekit battery level from 61% to 63%
27/09/2021, 10:25:23 [Hue] Dimmschalter Schlafzimmer: set homekit battery level from 61% to 63%
27/09/2021, 10:25:23 [Hue] Dimmschalter Schlafzimmer: set homekit battery level from 61% to 63%
27/09/2021, 10:25:23 [Hue] Dimmschalter Schlafzimmer: set homekit battery level from 61% to 63%
27/09/2021, 10:25:23 [Hue] Dimmschalter Schlafzimmer: set homekit battery level from 61% to 63%
27/09/2021, 10:25:24 [HomeConnect] [Backofen] Connected
27/09/2021, 10:25:24 [HomeConnect] [Backofen] 13 of 13 programs are currently unavailable
27/09/2021, 10:25:24 [HomeConnect] [Backofen] Finished reading available program options
27/09/2021, 10:25:24 [HomeConnect] [Backofen] Adding services for 13 programs
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Hot air eco' (Cooking.Oven.Program.HeatingMode.HotAirEco)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Top  bottom heating eco' (Cooking.Oven.Program.HeatingMode.TopBottomHeatingEco)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Pizza setting' (Cooking.Oven.Program.HeatingMode.PizzaSetting)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Intensive heat' (Cooking.Oven.Program.HeatingMode.IntensiveHeat)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Slow cook' (Cooking.Oven.Program.HeatingMode.SlowCook)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     '4D Hot air' (Cooking.Oven.Program.HeatingMode.HotAir)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Topbottom heating' (Cooking.Oven.Program.HeatingMode.TopBottomHeating)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Hot air grilling' (Cooking.Oven.Program.HeatingMode.HotAirGrilling)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Bottom heating' (Cooking.Oven.Program.HeatingMode.BottomHeating)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Dry food' (Cooking.Oven.Program.HeatingMode.Desiccation)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Preheat ovenware' (Cooking.Oven.Program.HeatingMode.PreheatOvenware)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'CoolStart function' (Cooking.Oven.Program.HeatingMode.FrozenHeatupSpecial)
27/09/2021, 10:25:24 [HomeConnect] [Backofen]     'Keep warm' (Cooking.Oven.Program.HeatingMode.KeepWarm)
27/09/2021, 10:25:24 [HomeConnect] [Backofen] Removing services for 0 programs
27/09/2021, 10:25:24 [HomeConnect] [Backofen] Programs cannot be controlled without Control scope
27/09/2021, 10:25:25 [HomeConnect] [Backofen] Door open
27/09/2021, 10:25:25 [HomeConnect] [Backofen] Manual mode (remote control activated, remote start allowed, being operated locally)
27/09/2021, 10:25:26 [Hue] goodbye

**Additional context**

I tried to update the plugins before. It always said it was sucessfull, but the plugins did not show a higher number. The update button in the webconsole was still there. I tried to uninstall three of the plugins (http webhooks, alexa and homeconnect). This also was not sucessfull. 
Since pressing the update button for HOOBS itself it is not starting anymore (see log).

**Comment by Cojaeck** [comment]
Update:
After the "hue goodbye" I can see a lot of messages in the log. All my devices seem to communicate with hoobs. But Hoobs shows stopped....

**Comment by mkellsy** [comment]
Try rebooting

**Comment by Cojaeck** [comment]
:-)
I have not much knowledge about Linux but I am no total noob I hope.
Of course I restarted it an tried to install config and system restore.
But this was no help at all.
I would like to know how to uninstall this second node which you can see in
the log.
But I guess it will be best to install it from scratch.


Am Mo., 27. Sept. 2021 um 13:09 Uhr schrieb Michael Kellsy <
***@***.***>:

**Comment by mkellsy** [comment]
Run this from the terminal and post the results.
```
ls -la /etc/systemd/system/
```
