### ISSUE TITLE
Issues with Remootio (Certified)

### ISSUE THREAD

**Issue by mikeyis** [hoobs-org/HOOBS#1543]
**Description**
The plugin fails to install correctly, complaining that the NODE/NPM is out of date. Refuses to start. Is listed as a certified plugin to work with HOOBS

**Expected behavoir**
Should install correctly, and allow you to configure the inputs from the GUI. 

**Plugin name**
REMOOTIO - ronniepettersson/homebridge-remootio

**Please report the issue to the plugin developer**
Reported to the developer who identified that the issue was the NPM and the NODE versions. Suggested upgrading them. Upgraded, but still fails to load and won't start the bridge.

**Version**
V3 and V4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X ] HOOBS SD Card
- [ X ] Custom Install

**If this is a custom install, what's your operating system?**
Have tried on a Raspi 3b+ and on a docker container.

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
26/9/21, 7:17:51 pm TypeError: this.config.devices is not iterable at RemootioPlatform.discoverAndSyncAccessories (/hoobs/node_modules/homebridge-remootio/dist/platform.js:59:42) at API.<anonymous> (/hoobs/node_modules/homebridge-remootio/dist/platform.js:28:18) at API.emit (events.js:322:22) at Server.run (/usr/src/hoobs/bridge/server.js:104:18) at module.exports (/usr/src/hoobs/bridge/cli.js:84:12) at Object.<anonymous> (/usr/src/hoobs/bin/hoobs:63:81) at Module._compile (internal/modules/cjs/loader.js:1156:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10) at Module.load (internal/modules/cjs/loader.js:1000:32) at Function.Module._load (internal/modules/cjs/loader.js:899:14)

26/9/21, 7:17:40 pm WARN notsup Unsupported engine for homebridge-remootio@1.2.5: wanted: {"homebridge":"^1.1.0","node":">=12.18.3"} (current: {"node":"12.16.2","npm":"6.14.4"}) npm WARN notsup Not compatible with your version of node/npm: homebridge-remootio@1.2.5 26/9/21, 7:17:40 pm 26/9/21, 7:17:40 pm + homebridge-remootio@1.2.5 updated 1 package in 0.621s 26/9/21, 7:17:40 pm 2 packages are looking for funding run npm fund for details 26/9/21, 7:17:40 pm Plugin "homebridge-remootio" installed. 26/9/21, 7:17:40 pm Got SIGINT, shutting down Bridge...
```

**Comment by bwp91** [comment]
I think the plugin is restarting due to an incorrectly formatted config, not due to the version warnings.

Can you post your config for this plugin?

**Comment by mikeyis** [comment]
Doesn't even get that far to create one. Just get the brackets and nothing else.

**Comment by bwp91** [comment]
Can you show me a screenshot of the plugin settings screen? (not the advanced settings screen)

**Comment by mikeyis** [comment]
`27/9/21, 8:56:38 pmRemootio Bridge 2 starting
27/9/21, 8:56:54 pmRemootio Bridge 2WARNINGNo plugins installed.
27/9/21, 8:56:55 pmRemootio Bridge 2Bridge is running on port 51876.
27/9/21, 8:56:57 pmRemootio Bridge 2Configuration change
27/9/21, 8:56:57 pmremootiobridge2 stopping
27/9/21, 8:57:02 pmRemootio Bridge 2 starting`

**Comment by bwp91** [comment]
i think you misunderstood me, a screenshot of what the plugin settings screen looks like for you (not the log)
