### ISSUE TITLE
Hoobs v4 Docker/OCI image?

### ISSUE THREAD

**Issue by joshuawhite929** [hoobs-org/HOOBS#1545]
**Is your feature request related to a problem? Please describe.**
The Hoobs Docker/OCI images haven't been updated in 6 months.  See:  https://hub.docker.com/r/hoobs/hoobs/tags?page=1&ordering=last_updated

**Describe the solution you'd like**
Provide a v4 Hoobs OCI image

**Describe alternatives you've considered**
State that Docker/OCI images are no longer provided/supported

**Additional context**
As a Hoobs user, I'd like to install Hoobs as a Docker image on my Raspberry Pi

**Comment by askovi** [comment]
There is no docker support for HOOBS 4 at this time. If you're running on a Raspberry Pi then you should flash the HOOBS 4 img directly.

**Comment by JulianKropp** [comment]
Have a look here: [#1774 ](https://github.com/hoobs-org/HOOBS/issues/1774#issuecomment-1126948067)
