### ISSUE TITLE
Upgrade error - Error: listen EADDRINUSE-Failed to set capabilities on file /usr/local/bin/node (No such file or directorv)

### ISSUE THREAD

**Issue by databoy01** [hoobs-org/HOOBS#1546]
**Description**
An update is showing available and won’t actually upgrade, when doing a CLI upgrade it get this error

Initializing HAP-NodeJSv0.9.4.
Error: listen EADDRINUSE: address already in use :::80 at Server.setuplistenHandle [as listen21 (net.is:1318:16) at listenInCluster(net.js:1366:12) at Server.listen (net.js:1452:7) 
at Function.serverListen [as listen (/usr/local/lib/node modules/@hoobs/hoobs/node modules/express-ws/lib/in
dex.js:42:40)
at API.start (/usr/local/lib/node modules/Choobs/hoobs/server/api.js:192:17)
at module.exports (/sr/local/lib/node modules/Choobs/hoobs/server/cli.is:172:21/f
code: " EADDRINUSE errno: -98, syscall: 'listen address: port: 80
[HOBS] Stopping server
Failed to set capabilities on file /usr/local/bin/node (No such file or directorv)
The value of the capability argument is not permitted for a file. Or the file is not a reqular (non-symlink) file

**Version**

Version: 4.0.104

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

RING Plugin

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

```

"server"
port
80%*"
origin"
"autostart":
0
"home setup id":
"X-HM://0023ISYWYBNZ8"
polling seconds":
client"
"default route":
"status"
"inactive logoff":
"theme"
30,
"hoobs-light
"locale
"en
"temp units"
"fahrenheit"
"country code"
"US
"postal code":
"XXXXX"
"bridge
"name" :
"HOOBS"
port":
51826,
pin":
""
username" :
""
"description
ports": (
plugins
"homebridge-ring"
accessories
'platforms'
"platform":
"Ring"
'plugin map"
{
plugin name"
"homebridge-ring

"refreshToken"
system
hoobs

```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Run this and post the results.

ls -la /etc/systemd/system
