### ISSUE TITLE
Hoobs.local

### ISSUE THREAD

**Issue by GOTDNRV** [hoobs-org/HOOBS#1547]
**Description**
Can not connect to hoobs local
**Version**
Please include the version of HOOBS you are using.
Hoobs 4
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
MAC OS BIG SUR
**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Simiplesafe3
Ring
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Have you tried the desktop app?

**Comment by GOTDNRV** [comment]
No, where can I find this?

**Comment by GOTDNRV** [comment]
Thank you so very much, I found the download link all is well.
