### ISSUE TITLE
Ring plugin

### ISSUE THREAD

**Issue by Paddenhoek** [hoobs-org/HOOBS#1554]
**Description**
A clear and concise description of what the plugin is doing.

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by Paddenhoek** [comment]
Hi, after installing Ring plugin i am not able to fill in e-mail/password/refresh token...Tried reinstalling several times.
What i am doing wrong

**Comment by askovi** [comment]
Make sure the bridge is started then go to the configuration page for Ring and click the link account button at the top. The button takes a few seconds to appear after the bridge has been restarted

**Comment by Paddenhoek** [comment]
I did, 
Install, Install Ring, Uninstal-Instal-Configuration-
The page starts with Ring Bridge but no login..
![Screenshot 2021-09-29 at 20 55 10](https://user-images.githubusercontent.com/91569557/135331249-d80f1358-508f-4c17-9b8b-03db6d5d9e54.png)
![Screenshot 2021-09-29 at 20 55 10 2](https://user-images.githubusercontent.com/91569557/135331260-d8b398b4-57f1-45e6-b0d3-199971e2c9d7.png)
.

**Comment by Paddenhoek** [comment]
Ring Bridge starting


![Screenshot 2021-09-29 at 21 11 32](https://user-images.githubusercontent.com/91569557/135333676-fec06111-c4f9-41b5-9899-4368154a4e43.png)

**Comment by askovi** [comment]
Can you post a screenshot of your Ring Bridge page? Do you see the QR code? Is the bridge running?

**Comment by Paddenhoek** [comment]
![Screenshot 2021-09-29 at 22 21 48](https://user-images.githubusercontent.com/91569557/135342784-f6536097-b488-4e37-9d8c-29b100587ad8.png)

**Comment by askovi** [comment]
Not the config page. The bridge page like this:
![image](https://user-images.githubusercontent.com/3981552/135342909-56319251-5615-4a89-bfe1-582eeb8f5ac9.png)

**Comment by Paddenhoek** [comment]
Ah ok moment please

**Comment by Paddenhoek** [comment]
iam reinstalling the plugin

**Comment by Paddenhoek** [comment]
![Screenshot 2021-09-29 at 22 25 59](https://user-images.githubusercontent.com/91569557/135343301-88d6ebd8-83da-4723-984f-cf64b89f455d.png)

**Comment by askovi** [comment]
your bridge is not starting. Try rebooting your device from the top right menu -> hub settings -> reboot. See if it starts after that.

**Comment by Paddenhoek** [comment]
ok iam doing that right now

**Comment by Paddenhoek** [comment]
start- save.... same page...

**Comment by Paddenhoek** [comment]
![Screenshot 2021-09-29 at 22 58 19](https://user-images.githubusercontent.com/91569557/135347547-eadbcbec-6550-40c9-8142-0d0e7d329a41.png)

**Comment by askovi** [comment]
ok please send an email to info@hoobs.com with your order number and request a remote support session to troubleshoot

**Comment by Paddenhoek** [comment]
![Screenshot 2021-09-29 at 23 00 55](https://user-images.githubusercontent.com/91569557/135347880-9e31fd74-da06-49c4-8dbc-0214472cb19e.png)

**Comment by Paddenhoek** [comment]
Ok i will send Hoobs a request for support, thank you for helping me
Alain

**Comment by mkellsy** [comment]
The EPIPE is a bad error. It is part of Node.
There is one thing you can try.
1. Menu -> Hub Settings -> Clear Cache
2. Then from the Dashboard click Check for Updates

See if there are any updates available.

**Comment by tfraley** [comment]
Just saw this. 
FYI i've been seeing that EPIPE error since update as well. 
I've also did a fresh install and see it as well. 

I've been having rebooting issues with hoobs while trying to get webostv plugin working just started a separate bug report.

I have ring and works well I do see server connection issues at times the past two days while i've been trying to trouble shoot webos plugin.

Just and FYI

**Comment by mkellsy** [comment]
I'm working on it.

**Comment by mkellsy** [comment]
I found the issue and you can upgrade from the terminal. I don't think the upgrade from the UI will work.
Go to the terminal and run this
```
sudo apt update && sudo apt install -y hoobs-cli hoobsd
```

This will upgrade you to 4.0.109. This should fix the pipe error and the Ring plugin issue.

**Comment by Paddenhoek** [comment]
goodmorning, i ran the commands i rebooted Hoobs- reinstalled Ring plugin, start it but still no login...

**Comment by Paddenhoek** [comment]
![Screenshot 2021-09-30 at 10 11 47](https://user-images.githubusercontent.com/91569557/135413873-4c63c6ae-1793-41db-9ac2-df35459adce3.png)

**Comment by Paddenhoek** [comment]
installed Ewelink plugin and no issues all good..  running hoobs V 4.0.109 now- shall reinstall Ring plugin

**Comment by Paddenhoek** [comment]
installing previous version 9.13, shows update tap done that, Ring Bridge 9.21.2, hit configuration, nope ):

**Comment by Paddenhoek** [comment]
send a mail to "info@hoobs.com" with my order number and requested a remote support session to troubleshoot.
Thanks for the help

**Comment by Paddenhoek** [comment]
Finally- after reinstalling Ring plugin- config-hit the Ring Bridge word and orange login appears!
Hit the login and the Ring login screen is a fact!!! Doorbell ok Cams ok all good
@mkellsy and @askovi thanks for the support

**Comment by EddieDSuza** [comment]
> The EPIPE is a bad error. It is part of Node. There is one thing you can try.
> 
> 1. Menu -> Hub Settings -> Clear Cache
> 2. Then from the Dashboard click Check for Updates
> 
> See if there are any updates available.

The clearing of cache fixed the issue of the link button not appearing.
