### ISSUE TITLE
Cannot connect after latest update 09/28/21

### ISSUE THREAD

**Issue by paskalicky** [hoobs-org/HOOBS#1555]
Cannot connect to my Hoobs in a box after last update 09/28/21 
Running Hoobs4 
Hoobs.local unavailable. 
Hardware: solid yellow - green activity light blinking.
I would sent you the log but unable to access.
Thanx

**Comment by mkellsy** [comment]
Is the red light on?

**Comment by paskalicky** [comment]
Yes - On the inside of the device

Paul Skalicky

(206) 304-2071
***@***.***



On Sep 30, 2021, at 2:19 PM, Michael Kellsy ***@***.***> wrote:

﻿
Is the red light on?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mkellsy** [comment]
OK There is something wrong.

See if you can access the terminal.
http://hoobs.local:9090
If you can the username is **hoobs** and the password is **hoobsadmin**

Then run this. And post the results.
You can copy text from the terminal by selecting it and right clicking. It will automatically copy.
```
sudo systemctl status hoobsd
```

If it isn't running. Try starting it.
```
sudo systemctl start hoobsd
```

**Comment by paskalicky** [comment]
Thanx :0
Results:
***@***.***:~ $ sudo systemctl status hoobsd
● hoobsd.service - HOOBSD
   Loaded: loaded (/etc/systemd/system/hoobsd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) since Fri 2021-10-01 05:58:41 MST; 1s ago
  Process: 26062 ExecStart=/usr/bin/hoobsd hub (code=exited, status=0/SUCCESS)
 Main PID: 26062 (code=exited, status=0/SUCCESS)

**Comment by paskalicky** [comment]
Help ;) What now? 

Paul Skalicky

(206) 304-2071
***@***.***



On Oct 1, 2021, at 6:00 AM, Paul Skalicky ***@***.***> wrote:

﻿Thanx :0
Results:
***@***.***:~ $ sudo systemctl status hoobsd
● hoobsd.service - HOOBSD
   Loaded: loaded (/etc/systemd/system/hoobsd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) since Fri 2021-10-01 05:58:41 MST; 1s ago
  Process: 26062 ExecStart=/usr/bin/hoobsd hub (code=exited, status=0/SUCCESS)
 Main PID: 26062 (code=exited, status=0/SUCCESS)

**Comment by mkellsy** [comment]
According to your systemd command the service is running. (Process ID 26062)

See if NGINX is running, It shouldn't be there.
```
sudo systemctl status nginx
```

Also see if there is an old version of HOOBS 3.3 running.
```
sudo systemctl status nginx
```

**Comment by paskalicky** [comment]
Results
***@***.***:~ $ sudo systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-10-04 12:48:36 MST; 18h ago
     Docs: man:nginx(8)
  Process: 536 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 590 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 591 (nginx)
    Tasks: 5 (limit: 2200)
   Memory: 8.8M
   CGroup: /system.slice/nginx.service
           ├─591 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─592 nginx: worker process
           ├─593 nginx: worker process
           ├─594 nginx: worker process
           └─596 nginx: worker process

Oct 04 12:48:35 hoobs systemd[1]: Starting A high performance web server and a reverse proxy server...
Oct 04 12:48:36 hoobs systemd[1]: Started A high performance web server and a reverse proxy server.
***@***.***:~ $ 

Next steps please :) Need Hoobs back!
Thanx
Paul

**Comment by paskalicky** [comment]
Thx. Would have never guessed to look at migration tool unavailable :) easy fun Hoobs 👍🏼


Paul Skalicky
46067 W Guilder Ave
Maricopa AZ 85139

(206) 304-2071
***@***.***
