### ISSUE TITLE
using homebridge-hue-utils ph

### ISSUE THREAD

**Issue by oly13** [hoobs-org/HOOBS#156]
How can i use that command inside HOOBS Beta?

**Comment by mkellsy** [comment]
There is a terminal in HOOBS
Try running pH
If not try running ~/.hoobs/node_modules/homebridge-hue/cli/ph.hs

**Comment by oly13** [comment]
> If not try running ~/.hoobs/node_modules/homebridge-hue/cli/ph.hs

Thats work, thank you.
