### ISSUE TITLE
Treatlife Switches

### ISSUE THREAD

**Issue by mmccombs01** [hoobs-org/HOOBS#1563]
Does anyone know if Hoobs will support Treatlife wall switches?

I am decently moving along on my smart home journey and I am debating between getting a HOOBs or Home Assistant product. My programming skill set is substantially above average to the US population but I am not a pro. So working with pre-existing Java scripts or coding a a simple new script isn't an issue. 

My home devises right now are Sonoff, MyQ, Ring, TreatLife wall switches, Govee, Sengled, TP Link, Blink cameras, Ring. 

Here is the link to the wall swtiches:
https://www.amazon.com/dp/B07WWYQJFR?psc=1&ref=ppx_yo2_dt_b_product_details

**Comment by askovi** [comment]
Those seem to be just rebranded Tuya devices. If you can control them with the Tuya or Smart Life app then they will work just fine in HOOBS using one of these tuya plugins:

https://plugins.hoobs.org/plugin/@milo526/homebridge-tuya-web
https://plugins.hoobs.org/plugin/homebridge-tuya-lan
https://plugins.hoobs.org/plugin/homebridge-tuya

**Comment by mmccombs01** [comment]
Great. I am using the Smart Life app and they also show up in the Smartthings app as well. The other devices appear to have several plugins, so I think I am good with HOOBS. 

askovi- You using HOOBS and you like the product? Seem to have any issues for you?

**Comment by askovi** [comment]
If they show up in SmartThings they can also be integrated via the SmartThings plugin into HOOBS. 

Regarding using HOOBS, as a co-founder of the company, I'd probably be a little bit biased answering that 😄 
If you run into any issues the HOOBS team is here to help. You can either open an issue here on Github or reach out directly by email at info@hoobs.com if you require remote assistance with your setup.

**Comment by mmccombs01** [comment]
Thanks. I went ahead and bought the HOOBS V 4 just now. Thanks for the information. Will get it in a three day and try it out.
