### ISSUE TITLE
homebridge-hubitat-tonesto7

### ISSUE THREAD

**Issue by jackflem1** [hoobs-org/HOOBS#1564]
**Description**
Log shows a plugin update is available, but no option is presented to update it.

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
homebridge-hubitat-tonesto7

**Please report the issue to the plugin developer**
Developers response was -- I'm not sure what to tell you guys. HOOBS handles plug-ins different.
It's why I moved over to native Homebridge config-ui-x
It does everything hoobs does and more like splitting off plugins into child bridges which is awesome and prevents plug-ins from slowing down the main bridge

.

**Version**
Please include the version of HOOBS you are using.
4.0.104 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
10/4/2021, 12:27:34 PMHOOBS Hubitat-v2 WARNING---------------------------------------------------------------
10/4/2021, 12:27:34 PMHOOBS Hubitat-v2 WARNINGNOTICE: New version of homebridge-hubitat-tonesto7 available: 2.5.12
10/4/2021, 12:27:34 PMHOOBS Hubitat-v2 WARNING---------------------------------------------------------------
10/4/2021, 12:27:34 PMHOOBS Hubitat-v2 Sending Plugin Status to Hubitat | UpdateAvailable: true | newVersion: 2.5.12

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Meanwhile, go to the Plugins screen and open that plugin.
There should be an Upgrade button there.

**Comment by jackflem1** [comment]
There is no upgrade option when viewing the plug-in

Thanks.
Jack

**Comment by mkellsy** [comment]
Syncing the server. There was a mirror error. It will be ready later today.

**Comment by jackflem1** [comment]
I just Switched to native Homebridge config-ui-x, so my problem is solved.
