### ISSUE TITLE
Upgrade Failed No Access

### ISSUE THREAD

**Issue by jscurry1** [hoobs-org/HOOBS#1567]
**Description**
Hoobs Upgrade Failed.

**Version**
Unknown, trying to upgrade to newest version
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
Unknown
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
Ring
Harmony
MyQ

**Post your log**
hoobs@hoobs:~ $ sudo hbs log
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Module._compile (internal/modules/cjs/loader.js:1085:14)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Module.load (internal/modules/cjs/loader.js:950:32)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Module.require (internal/modules/cjs/loader.js:974:19)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at require (internal/modules/cjs/helpers.js:93:18)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Object.<anonymous> (/usr/src/hub/index.ts:26:1)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Module._compile (internal/modules/cjs/loader.js:1085:14)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Module.load (internal/modules/cjs/loader.js:950:32)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Module.require (internal/modules/cjs/loader.js:974:19)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at require (internal/modules/cjs/helpers.js:93:18)
10/4/2021, 3:11:21 PM HOOBS  ERROR  at Object.<anonymous> (/usr/src/main.ts:34:1)
10/4/2021, 3:11:28 PM HOOBS starting
10/4/2021, 3:11:35 PM  WARNING  unhandled rejection: TypeError: Invalid Version: 
10/4/2021, 3:11:35 PM HOOBS  ERROR  /usr/lib/hoobsd/node_modules/eiows/dist/eiows.js:30
10/4/2021, 3:11:35 PM HOOBS  ERROR  })();
10/4/2021, 3:11:35 PM HOOBS  ERROR  ^
10/4/2021, 3:11:35 PM HOOBS  ERROR  Error: Error: Cannot find module './eiows_linux_83'
10/4/2021, 3:11:35 PM HOOBS  ERROR  Require stack:
10/4/2021, 3:11:35 PM HOOBS  ERROR  - /usr/lib/hoobsd/node_modules/eiows/dist/eiows.js
10/4/2021, 3:11:35 PM HOOBS  ERROR  - /usr/lib/hoobsd/hub/index.js
10/4/2021, 3:11:35 PM HOOBS  ERROR  - /usr/lib/hoobsd/main.js
10/4/2021, 3:11:35 PM HOOBS  ERROR  - /usr/bin/hoobsd
10/4/2021, 3:11:35 PM HOOBS  ERROR  at /usr/lib/hoobsd/node_modules/eiows/dist/eiows.js:27:15
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Object.<anonymous> (/usr/lib/hoobsd/node_modules/eiows/dist/eiows.js:30:3)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Module._compile (internal/modules/cjs/loader.js:1085:14)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Module.load (internal/modules/cjs/loader.js:950:32)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Module.require (internal/modules/cjs/loader.js:974:19)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at require (internal/modules/cjs/helpers.js:93:18)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Object.<anonymous> (/usr/src/hub/index.ts:26:1)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Module._compile (internal/modules/cjs/loader.js:1085:14)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Module.load (internal/modules/cjs/loader.js:950:32)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Module.require (internal/modules/cjs/loader.js:974:19)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at require (internal/modules/cjs/helpers.js:93:18)
10/4/2021, 3:11:35 PM HOOBS  ERROR  at Object.<anonymous> (/usr/src/main.ts:34:1)
10/4/2021, 3:12:13 PM  WARNING  unhandled rejection: TypeError: Invalid Version: 
10/4/2021, 3:12:58 PM  WARNING  unhandled rejection: TypeError: Invalid Version: 
10/4/2021, 3:13:36 PM  WARNING  unhandled rejection: TypeError: Invalid Version: 
10/4/2021, 3:13:44 PM  WARNING  unhandled rejection: TypeError: Invalid Version: 
10/4/2021, 3:13:46 PM upgrading node
10/4/2021, 3:15:15 PM  WARNING  unhandled rejection: TypeError: Invalid Version: 
10/4/2021, 3:16:03 PM  WARNING  unhandled rejection: TypeError: Invalid Version: 
10/4/2021, 3:16:15 PM  WARNING  unhandled rejection: TypeError: Invalid Version: 
10/4/2021, 3:16:32 PM  WARNING  device reboot command received

**Additional context**
Hoobs told me there was a new version available, when I started the upgrade it seemed to get hung. After an hour I restarted but since can no longer access via the web browser.  I can SSH into the box, logs above.  Please help if possible with next steps to get back up and running

**Comment by mkellsy** [comment]
This looks like a bad SD card. Please send an email to info@hoobs.com. We can troubleshoot it further.
