### ISSUE TITLE
Add plugin's NPM and repo links

### ISSUE THREAD

**Issue by xdmate** [hoobs-org/HOOBS#157]
Hey guys. Just updated to the beta, I'm sure you might be aware, but plugins no longer have the links to npm & github. I found that super useful and a great feature. 

Thanks!

**Comment by mkellsy** [comment]
That's an overnight. We include the readme. I will add the links on the plug-in details screen.

Thanks for pointing this out.

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.51
