### ISSUE TITLE
Cannot remove plugins

### ISSUE THREAD

**Issue by jurekjure** [hoobs-org/HOOBS#1573]
I'm trying to clean out my hoobs setup and cannot remove two plugins
- HOOBS Certified Camera FFMPEG 3.0.3 published 8/25/2021
- HOOBS Certified Xiaomi Roborock Vacuum 0.16.1 published 8/2/2021

When trying to uninstall I get a response - Plugin remove failed

Is there any other way to remove these plugins?

<img width="752" alt="Screenshot 2021-10-07 at 22 34 08" src="https://user-images.githubusercontent.com/54580999/136458145-e6441858-d6ef-4e64-8767-8f717664d698.png">
<img width="838" alt="Screenshot 2021-10-07 at 22 34 14" src="https://user-images.githubusercontent.com/54580999/136458148-9337c8be-bbd0-4032-83dc-e047c96c8d50.png">

**Comment by mkellsy** [comment]
Are you trying to reset?
You can reset from the system screen.
