### ISSUE TITLE
error on voltage

### ISSUE THREAD

**Issue by routerdude** [hoobs-org/HOOBS#1574]
How do I see what the problem is with this? it is plugged into a UPS and it is continuing about every 25-30 seconds 
Oct  7 19:55:52 hoobs kernel: [983771.136059] Voltage normalised (0x00000000)
Oct  7 19:55:54 hoobs kernel: [983773.216035] Under-voltage detected! (0x00050005)
Oct  7 19:56:02 hoobs kernel: [983781.536041] Voltage normalised (0x00000000)
Oct  7 19:56:09 hoobs kernel: [983787.776051] Under-voltage detected! (0x00050005)
Oct  7 19:56:27 hoobs kernel: [983806.496084] Voltage normalised (0x00000000)
Oct  7 20:00:45 hoobs kernel: [984064.416842] rpi_firmware_get_throttled: 21 callbacks suppressed
Oct  7 20:00:45 hoobs kernel: [984064.416852] Under-voltage detected! (0x00050005)
Oct  7 20:00:54 hoobs kernel: [984072.736855] Under-voltage detected! (0x00050005)
Oct  7 20:01:04 hoobs kernel: [984083.136925] rpi_firmware_get_throttled: 22 callbacks suppressed

if it is a hardware failure id like to get an RMA depending on where this actually goes..

**Comment by mkellsy** [comment]
Send an email to info@hoobs.com with your order number.
