### ISSUE TITLE
Can't Login to Hoobs Box

### ISSUE THREAD

**Issue by BrevityLLC** [hoobs-org/HOOBS#1577]
Having issues with a new Hoobs Box. Someone started setting it up, and I believe he created an admin user. But he doesn't remember the password and so we can't login.

I logged into the box with SSH, and tried the "sudo rm -rf /home/hoobs/.hoobs/etc/access.json" command and rebooted, but it's just the same login screen, not a place to setup a new user.

**Comment by mkellsy** [comment]
HOOBS 4?

You can remove the accounts with this command
```
sudo rm -f /var/lib/hoobs/access
```
Then restart the service
```
sudo hoobsd service restart
```
