### ISSUE TITLE
Can Not Access Device

### ISSUE THREAD

**Issue by Oasamala** [hoobs-org/HOOBS#1581]
I've added Hoobs in my Homeapp since early May but I've really not added any devices to it but I now installed Eufy door lock and video doorbell and wanted to incorporate it to my home app. When I plugged back hoops into my router and power simply, it simply said "No Devices." after scanning it. I can't even get access to the dashboard. I can't even get access to Hoops.local. SOS

**Comment by mkellsy** [comment]
Send an email to info@hoobs.com so we can troubleshoot and replace components if needed. Please allow 24-48 hours for a response.
