### ISSUE TITLE
A/C plugin not working after hoobs update

### ISSUE THREAD

**Issue by ThisIzKrazy** [hoobs-org/HOOBS#1585]
I have an issue with my izone plugin after 4.0 update.
homekit doesn't recognise this plugin.
(ip is a stand in for real my ip)
hoobs.local can see it but HomeKit doesn't.
was working on previous hoobs software prior to 4.0

Izone Airconditioner
```json
{
    "accessories": [
        {
            "accessory": "iZone Air Conditioner",
            "name": "house A/C",
            "url": "http://000.000.00.000/",
            "reportSetpointAsCurrentTemperature": false,
            "plugin_map": {
                "plugin_name": "homebridge-izone-airconditioner"
            }
        }
    ]
}
```

**Comment by BobbySlope** [comment]
Did u installed it on a separate bridge for the plugin? if so please scan the qr code for this separate bridge to connect it to homekit
