### ISSUE TITLE
Shelly 1 Plus for Apple HomeKit integration

### ISSUE THREAD

**Issue by Sgoy86** [hoobs-org/HOOBS#1586]
I have just bought the brand new Shelly 1 Plus and it seems that they are currently not working with HomeKit .

can anyone assist in getting the new Shelly 1 plus integrated in HomeKit?

thx

**Comment by mkellsy** [comment]
Install the Shelly plugin
https://plugins.hoobs.org/plugin/homebridge-shelly

**Comment by Sgoy86** [comment]
Hi Michael, hi everyone,

I already have this plugin installed and it worked very well however Allterco Robotics has just recently released a new Shelly device, the Shelly Plus 1 which is not yet included in this plugin.

Here is a link to the new Shelly.

https://shop.shelly.cloud/shelly-plus-1-wifi-smart-home-automation

Please let me know If this can be included as well.

Thanks

Sebastian

Von meinem iPhone gesendet

**Comment by mkellsy** [comment]
Please create a feature request for the Shelly plugin dev.

https://github.com/alexryd/homebridge-shelly

**Comment by Sgoy86** [comment]
Hi Michael,

Sorry but I thought this is what I did already!? Am new to this platform. How do I do this?

Thanks

Sebastian

Von meinem iPhone gesendet

**Comment by mkellsy** [comment]
We are HOOBS, we write and maintain the code which allows the community to make plugins for everything.
The Shelly plugin is wrote and maintained by another developer.

I really want to help you, but I do not have access to this code. That's why I am directing you to alexryd.
https://github.com/alexryd/homebridge-shelly

**Comment by Sgoy86** [comment]
Okay got you! Thanks, will reach out to him directly

Von meinem iPhone gesendet
