### ISSUE TITLE
LG WebOS TV - remote access on the tv is required every 10 seconds

### ISSUE THREAD

**Issue by hruskat** [hoobs-org/HOOBS#1587]
**Description**
A clear and concise description of what the plugin is doing.
When plugin is running on the screen is looping message "do you like to connect the tv remote access and give a access?" for every 10 seconds. I select yes and after 10 sec is displayed again. Before the migration to Hoobs 4 works everything correctly. The connections seems to be OK.. also accessories are visible in the HomeKit.. but there are not corresponding  when after fifth asking about the verification I select no. 

**Expected behavoir**
Please let us know what the plugin is supposed to do.
Not display every 10 seconds the message. 
**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.
LgWebOS TV

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.
We discussed with on the GitHub - check the stream https://github.com/merdok/homebridge-webos-tv/issues/392 - the developer seems to think that the issue is on the hoobs side. Could you please check it? 

**Version**
Please include the version of HOOBS you are using.
4.0.109

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes

**Pervious version**
If you upgraded, please let us know your previous version.
Sadly I`m not sure which version of HOOBS 3 was it 

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.

- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.

- [ ] HOOBS SD Card

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
{
    "platform": "webostv",
    "devices": [
        {
            "name": "LG Hoobs",
            "ip": "192.168.x.xx“,
            "mac": "2x:xx:4x:xx:xx:8D“,
            "pollingInterval": 100,
            "inputs": [
                {
                    "appId": "com.webos.app.livetv",
                    "name": "Live TV"
                },
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Apple"
                },
                {
                    "appId": "com.webos.app.hdmi4",
                    "name": "Vodafone"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube",
                    "params": {
                        "contentTarget": "https://www.youtube.com/tv?v=Bey4XXJAqS8"
                    }
                }
            ],
            "showInputButtons": true,
            "volumeControl": true,
            "channelControl": true,
            "mediaControl": true,
            "channelButtons": [
                1,
                2,
                10,
                30
            ],
            "keyFile": "~/.hoobs/etc/lgtvKeyFile",
            "prefsDir": "~/.hoobs/etc/.webosTv",
            "volumeLimit": 100,
            "deepDebugLog": true
        }
    ]
}
**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```
12. 10. 2021 19:20:07WebOS Tv Bridge starting
12. 10. 2021 19:20:09WebOS Tv BridgeLoaded plugin 'homebridge-webos-tv'
12. 10. 2021 19:20:09WebOS Tv BridgeLoading 1 platforms...
12. 10. 2021 19:20:09WebOS Tv BridgewebostvInit - initializing devices
12. 10. 2021 19:20:09WebOS Tv Bridgewebostv[LG Hoobs] Init - got TV configuration, initializing device with name: LG Hoobs
12. 10. 2021 19:20:09WebOS Tv BridgeLG Hoobs C4BF is running on port 40747.
12. 10. 2021 19:20:09WebOS Tv BridgeBridge is running on port 51836.
12. 10. 2021 19:20:09WebOS Tv Bridgewebostv[LG Hoobs] Prompt for confirmation. Please accept the pairing request on the TV!
12. 10. 2021 19:20:12WebOS Tv Bridgewebostv[LG Hoobs] Connected to TV
12. 10. 2021 19:20:19WebOS Tv Bridge starting
12. 10. 2021 19:20:22WebOS Tv BridgeLoaded plugin 'homebridge-webos-tv'
12. 10. 2021 19:20:22WebOS Tv BridgeLoading 1 platforms...
12. 10. 2021 19:20:22WebOS Tv BridgewebostvInit - initializing devices
12. 10. 2021 19:20:22WebOS Tv Bridgewebostv[LG Hoobs] Init - got TV configuration, initializing device with name: LG Hoobs
12. 10. 2021 19:20:22WebOS Tv BridgeLG Hoobs C4BF is running on port 33363.
12. 10. 2021 19:20:22WebOS Tv BridgeBridge is running on port 51836.
12. 10. 2021 19:20:22WebOS Tv Bridgewebostv[LG Hoobs] Prompt for confirmation. Please accept the pairing request on the TV!
12. 10. 2021 19:20:24WebOS Tv Bridgewebostv[LG Hoobs] Connected to TV
12. 10. 2021 19:20:31WebOS Tv Bridge starting
12. 10. 2021 19:20:33WebOS Tv BridgeLoaded plugin 'homebridge-webos-tv'
12. 10. 2021 19:20:33WebOS Tv BridgeLoading 1 platforms...
12. 10. 2021 19:20:33WebOS Tv BridgewebostvInit - initializing devices
12. 10. 2021 19:20:33WebOS Tv Bridgewebostv[LG Hoobs] Init - got TV configuration, initializing device with name: LG Hoobs
12. 10. 2021 19:20:33WebOS Tv BridgeLG Hoobs C4BF is running on port 37303.
12. 10. 2021 19:20:33WebOS Tv BridgeBridge is running on port 51836.
12. 10. 2021 19:20:33WebOS Tv Bridgewebostv[LG Hoobs] Prompt for confirmation. Please accept the pairing request on the TV!
12. 10. 2021 19:20:35WebOS Tv Bridgewebostv[LG Hoobs] Connected to TV
12. 10. 2021 19:20:42WebOS Tv Bridge starting
12. 10. 2021 19:20:45WebOS Tv BridgeLoaded plugin 'homebridge-webos-tv'
12. 10. 2021 19:20:45WebOS Tv BridgeLoading 1 platforms...
12. 10. 2021 19:20:45WebOS Tv BridgewebostvInit - initializing devices
12. 10. 2021 19:20:45WebOS Tv Bridgewebostv[LG Hoobs] Init - got TV configuration, initializing device with name: LG Hoobs
12. 10. 2021 19:20:45WebOS Tv BridgeLG Hoobs C4BF is running on port 41269.
12. 10. 2021 19:20:45WebOS Tv BridgeBridge is running on port 51836.
12. 10. 2021 19:20:45WebOS Tv Bridgewebostv[LG Hoobs] Prompt for confirmation. Please accept the pairing request on the TV!
12. 10. 2021 19:20:46WebOS Tv Bridgewebostv[LG Hoobs] Connected to TV
**Additional context**

**Comment by OrigSorceror** [comment]
For some reason HOOBS ignores the recommended (locked) dependencies attached to the plugin and loads the latest version of the bufferutil package (4.0.4) which causes issues with the homebridge-webos-tv plugin. I have left instructions that should rectify the issue by downgrading the bufferutil package to 4.0.3 on https://github.com/merdok/homebridge-webos-tv/issues/392
Merdok is looking into why the 4.0.4 version of bufferutil breaks the package causing the homebridge to re-boot upon pairing, but for now the recommendation is to downgrade the bufferutil package to 4.0.3.

**Comment by mkellsy** [comment]
This is an issue with the plugin and is addressed in this task
https://github.com/merdok/homebridge-webos-tv/issues/392
