### ISSUE TITLE
Delete All not useable Shelly Plugins from Search

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#159]
<img width="1093" alt="Screenshot 2019-09-24 at 09 02 20" src="https://user-images.githubusercontent.com/50763727/65489031-98bf6f00-deaa-11e9-9b4e-9afb59d9f84d.png">

**Comment by mkellsy** [comment]
This info comes from NPM. Non admin users can only see certified plugins.

**Comment by mkellsy** [comment]
The Shelly plugin is slated to be certified. This is already mentioned in #97.
