### ISSUE TITLE
Not showing in Home

### ISSUE THREAD

**Issue by MalcolmChapel** [hoobs-org/HOOBS#1593]
I have two bridges - Nest and Dummy Switch - that show in Home Settings > Home Hubs and Bridges. Now, how do I get them to show up in Home? I've rebooted router, eero, and pretty much everything that can be rebooted. What's next? Any help would be appreciated.

**Comment by mkellsy** [comment]
eero has special requirements to work with HomeKit
https://support.eero.com/hc/en-us/articles/360036319531-How-to-use-HomeKit-with-your-eero-Network#h_95355f87-85a4-4b72-bce5-b9f8fa59aca8

**Comment by MalcolmChapel** [comment]
I haven't added eero to homekit.

**Comment by BobbySlope** [comment]
Try running hoobs and then reboot your eero router
