### ISSUE TITLE
Plugin Updates

### ISSUE THREAD

**Issue by wnaylor** [hoobs-org/HOOBS#1595]
**Description**
On my dashboard 'Check for Update' it says that I have updates. When I try to update the plugins Hoobs just keeps trying. However, if I go into each plugin it shows that I already have the updated plugin.

**Version**
Hoobs 4.0.104

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X] HOOBS SD Card (SSD Memory)
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Switchbot, tuya, bond, Dyson pure cool, Garagedoor Ryobi, Govee, Hydrawise, Leviton, Meross, Nest, Platform Insteon, Plugin Govee, Ring, Sensible Ac, Wemo

**Post your config**
```
Not needed in this context
```

**Post your log**
```
Not needed in this context
```

**Additional context**
<img width="2560" alt="Screen Shot 2021-10-15 at 9 31 57 AM" src="https://user-images.githubusercontent.com/4623959/137495465-5f0b5b24-2701-480e-8f00-f46212c3c698.png">

**Comment by mkellsy** [comment]
This happens when a plugin is out of place. This has been fixed. Run this command in the terminal to fix.
```
sudo rm -fR /var/lib/hoobs/hub/node_modules && sudo rm -f /var/lib/hoobs/hub/package.json && sudo hoobsd service restart
```
