### ISSUE TITLE
Issue login into my hoobs desktop app

### ISSUE THREAD

**Issue by blacksillk** [hoobs-org/HOOBS#1596]
**Description**

I'm unable to login to my hoobs desktop app for Mac.
I was able to do the initial setup, after a while I was logged out. 
No when trying to log back in with the password I create, I get an error "Ivalid username or password "

I try to use the same password I use on "https://hoobs.com". This password works, I even reset the password and confirm login. 

I'm also not able to access "https://accounts.hoobs.org" with the same password to and avail.

I also created a new account with the same email address. This just doesn't make any sense. 

**Version**
Please include the version of HOOBS you are using.
 I don't know

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Your device doesn't use the same password as the website.

You can recover this from the terminal.
Here's a doc about connecting to the terminal https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f

Then run this command
```
sudo rm -f /var/lib/hoobs/access && sudo hoobsd service restart
```

Then access the UI and you will be prompted with the setup screen. Your config and plugins are not affected.
