### ISSUE TITLE
Unable to Log-in/Configure any Plug-Ins (Appropriate Prompts Missing)

### ISSUE THREAD

**Issue by markaedmondson** [hoobs-org/HOOBS#1599]
**Description**
Following 4.0 upgrade unable to configure new plug-ins.  Ring doesn't have prompts to login into account, Nest doesn't have Token/Auth fields, etc.  

**Version**
4.0.104

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
Ring, Nest, Sonos, Dyson

**Post your log**
10/15/2021, 6:28:21 AMNest Bridge starting
10/15/2021, 6:28:43 AMNest BridgeWARNINGNo plugins installed.
10/15/2021, 6:28:44 AMNest BridgeBridge is running on port 51826.
10/15/2021, 6:29:22 AMNest BridgeConfiguration change
10/15/2021, 6:29:22 AMnestbridge stopping
10/15/2021, 6:29:27 AMNest Bridge starting
10/15/2021, 6:29:51 AMRing Bridge starting
10/15/2021, 6:29:51 AMNest BridgeERRORError loading plugin "homebridge-nest"
10/15/2021, 6:29:51 AMNest BridgeWARNINGNo plugins installed.
10/15/2021, 6:29:51 AMNest BridgeLoading 1 platforms...
10/15/2021, 6:29:51 AMNest BridgeBridge is running on port 51826.
10/15/2021, 6:30:13 AMRing BridgeWARNINGNo plugins installed.
10/15/2021, 6:30:13 AMRing BridgeBridge is running on port 51836.
10/15/2021, 6:30:55 AMRing BridgeConfiguration change
10/15/2021, 6:30:55 AMringbridge stopping
10/15/2021, 6:31:00 AMRing Bridge starting
10/15/2021, 6:31:29 AMRing BridgeLoaded plugin 'homebridge-ring'
10/15/2021, 6:31:29 AMRing BridgeLoading 1 platforms...
10/15/2021, 6:31:29 AMRing BridgeRingWARNINGPlugin is not configured. Visit https://github.com/dgreif/ring/tree/master/homebridge#homebridge-configuration for more information.
10/15/2021, 6:31:29 AMRing BridgeBridge is running on port 51836.

**Comment by markaedmondson** [comment]
Thanks askovi,  I got the bridge up and running, and got the login prompt (went through the process successfully), however the thermostat is not showing in my list of accessories (within HOOBS desktop or Homekit).   I'm getting the following log error: 

10/16/2021, 11:30:27 AMnestbridge stopping
10/16/2021, 11:30:32 AMNest Bridge starting
10/16/2021, 11:30:40 AMNest BridgeERRORError loading plugin "homebridge-nest"
10/16/2021, 11:30:40 AMNest BridgeWARNINGNo plugins installed.
10/16/2021, 11:30:40 AMNest BridgeLoading 1 platforms...
10/16/2021, 11:30:40 AMNest BridgeBridge is running on port 51826.

**Comment by markaedmondson** [comment]
Done several times, no change.

**Comment by mkellsy** [comment]
looks like the migration failed. You most likely need to backup and re-flash.

Please send an email to info@hoobs.com we can troubleshoot it further and replace components if needed. Please allow 24 - 48 hours for a response.

**Comment by sahotanick** [comment]
Very similar issue here, the link account buttons appear for both plugins however after pressing them nothing happens for me, there is no prompt to login etc. I raised a new issue yesterday about this and posted a screenshot from the console in dev view.

**Comment by matruel** [comment]
I'm getting the same error. There is no prompts after clicking the Login button for the Nest Plugin.
