### ISSUE TITLE
Edit System Entries for HOOBS in a Box and Pro version

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#160]
<img width="812" alt="Screenshot 2019-09-24 at 08 49 39" src="https://user-images.githubusercontent.com/50763727/65489117-c99fa400-deaa-11e9-8576-1f6b843ab7bb.png">

**Comment by BobbySlope** [comment]
Manufacturer: HOOBS.org
Model: HSLF-1
Version: Display Software version
Serial: delete this
SKU: 7 45114 12418 0

**Comment by BobbySlope** [comment]
Manufacturer: Rocket Smart Home
Model: RFLM-1
Version: Display Software version
Serial: delete this
SKU: 7 45114 12419 7

**Comment by mkellsy** [comment]
I can try to hide them, but the Raspberry Pi foundation will not let you change it. The only way to change this is to build your own board using rep-rap data.

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.56
