### ISSUE TITLE
Not Seeing Update

### ISSUE THREAD

**Issue by cneb1** [hoobs-org/HOOBS#1602]
After updating to 4.1.9 yesterday, no plugins will install. Get a notification Unable to Install Plugin. Please Try Again. The attempted install will still show in Bridges and if you Restart the Bridge, the plugin shows in the Plugins list but states no plugin installed. Other behavior seen is that the dashboard will state that the plugins are not running, which makes sense but why would they be present if unable to install? If you attempt to install again the plugin will then get a number designation at the end. Example Weather Plus and Weather Plus 2. Also noticed if that the Check for Updates function seems to be non-responsive. The window will overlay and the Homebridge icon just continues to scroll and no response is provided whether that's new updates or the All up to date message.

Is there an issue with the 4.1.9 release? If so, how to fix/resolve without having to start over? Logs are attached.

Thank you,
-Chris

[log.txt](https://github.com/hoobs-org/HOOBS/files/7380930/log.txt)

**Comment by cneb1** [comment]
<img width="1191" alt="Screen Shot 2021-10-20 at 9 06 05 AM" src="https://user-images.githubusercontent.com/16739307/138098574-e946b707-3d5c-4015-a36c-4e3e62ea47a0.png">

Here's a screenshot from the HOOBS Dashboard, not able to reboot right now due to work.

**Comment by mkellsy** [comment]
Your are on version 4.0.104
Click Check for Updates and update the Raspberry Pi.
Your desktop app is updated but not the system.

**Comment by mkellsy** [comment]
Your desktop app needs to be downgraded until after your pi is upgraded.
Download and run this https://github.com/hoobs-org/desktop/releases/download/v4.0.68/hoobs-desktop-v4.0.68.dmg

Then check for updates and update the system first, then the app.

Note: I realized that the order doesn't make sense, in new versions I have combined this to 1 update button.

**Comment by cneb1** [comment]
Thanks! Do you think I'll have to re-establish a connection eventually or that the progress bar will eventually update?

**Comment by cneb1** [comment]
<img width="572" alt="Screen Shot 2021-10-20 at 9 20 32 PM" src="https://user-images.githubusercontent.com/16739307/138194699-73bef893-6868-48a6-a593-202f0a10fef8.png">

Get this now when trying to ssh

**Comment by cneb1** [comment]
Fixed! ssh'd in, deleted the known host file so it would rebuild, ran the second terminal string, noticed the desktop app wasn't showing correctly compared to accessing via web interface so removed the app plus corresponding folders and plist. Reinstalled, shows correct now with native desktop app and then restored from backup.
