### ISSUE TITLE
Meross Plugin stopsworking / Update to homebridge 1.3.5

### ISSUE THREAD

**Issue by MasterofKungfu9999** [hoobs-org/HOOBS#1604]
**Description**
Meross Plugin stops working after the newest update 

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Meross

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
4.0.104 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
[31mThe plugin "homebridge-meross" requires a Homebridge version of ^1.3.5 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m

**Additional context**
Please update to homebridge 1.3.5

**Comment by bwp91** [comment]
Hi @MasterofKungfu9999 you will need to update your version of hoobs to 4.1 for this message to go away.

**Comment by MasterofKungfu9999** [comment]
Hi @bwp91 it could be so easy if there is an update. If i'm searching for updates. hoobs says that there are no updates and Version 4.0.104 is the latest version

**Comment by bwp91** [comment]
Have you tried clearing the cache from the "Hub Settings" section? then checking for updates again...

**Comment by MasterofKungfu9999** [comment]
@bwp91 Yes

**Comment by bwp91** [comment]
Okay, now this command

```
sudo apt full-upgrade
```

and when prompted type `y` and enter. This may take a little time, but let it finish. You may find your hoobs version has been updated once the process has finished.

**Comment by MasterofKungfu9999** [comment]
Nope, plugin doesn't work. It's the same error message:

31mThe plugin "homebridge-meross" requires a Homebridge version of ^1.3.5 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

**Comment by MasterofKungfu9999** [comment]
An then it stops. What should i do now? Reboot?

**Comment by mkellsy** [comment]
It will reboot on its own

**Comment by MasterofKungfu9999** [comment]
after rbooting i am now on 4.1.9 but meross plugin/bridge is starting and stopping again

**Comment by askovi** [comment]
check the logs from that plugin and post them here
