### ISSUE TITLE
Installing plugin, bridge issues

### ISSUE THREAD

**Issue by recoi1er** [hoobs-org/HOOBS#1605]
**Description**
I had PiHole installed in a bridge called "Hoobs Bridge" along with RPi plugin, pihole dev said through some troubleshooting that I should move them away from each other to separate bridges so I uninstall PiHole and go to install it again and create a bridge called "PiHole Bridge" but it says it already exists (it does not appear in the list of bridges) and then it has the moving HOOBS logo that infinitely spins. Using the Mac HOOBS app I tried to refresh (CMD+R) the page and it responded but only left me with an all black/gray background in the window, had to force quit and reopen.

**Version**
v4.1.10

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No, clean v4.1 install with restore from backup

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
your linux image running on v4.1+

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.
thesis 
```
{
    "accessories": [
        {
            "name": "Pihole",
            "auth": "324613754543ew634e76563475",
            "host": "localhost",
            "port": 80,
            "baseDirectory": "/admin/",
            "time": 0,
            "accessory": "Pihole"
        }
    ],
    "platforms": [
        {
            "platform": "RPi",
            "name": "RPi",
            "hosts": [
                {
                    "host": "localhost",
                    "name": "Hoobs",
                    "hidden": false,
                    "devices": [
                        {
                            "device": "switch",
                            "name": "Hoobs"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
10/21/2021, 8:40:28 AMpiholebridge stopping
10/21/2021, 8:40:31 AMRPi BridgeRPigoodbye
10/21/2021, 8:40:34 AMRPi Bridge starting
10/21/2021, 8:40:37 AMRPi BridgeLoaded plugin 'homebridge-pihole'
10/21/2021, 8:40:37 AMRPi BridgeLoaded plugin 'homebridge-rpi'
10/21/2021, 8:40:37 AMRPi BridgeLoading 1 platforms...
10/21/2021, 8:40:37 AMRPi BridgeRPihomebridge-rpi v1.3.11, node v14.18.1, homebridge v1.3.5, homebridge-lib v5.1.15
10/21/2021, 8:40:37 AMRPi BridgeRPiWARNINGwarning: config.json: hosts[0]: devices[0]: gpio: key missing
10/21/2021, 8:40:37 AMRPi BridgeBridge is running on port 51826.
10/21/2021, 8:40:38 AMRPi BridgeRPiWARNINGwarning: localhost: not a Raspberry Pi```

**Additional context**
Add any other context about the problem here.

Additionally just now I took the "Hoobs Bridge" I had created and renamed it to "RPi Bridge" and it seems that this bridge was once called "piholebridge" and I renamed it but it only changed the "display" name. Also to get the logs requested, I reinstalled PiHole to the original bridge (now named RPi Bridge) but if I am seeing it correctly the bridge is labeled "piholebridge" behind the scenes when I uninstall it again - have attached a photo. 
<img width="916" alt="image" src="https://user-images.githubusercontent.com/19810634/138312530-bb6ea7cc-7ef0-4c92-bbc1-58165c633c1c.png">

**Comment by recoi1er** [comment]
As an expansion on th additional info, I went ahead and uninstalled PiHole and then RPi and even with RPi uninstalled it did say the bridge name was "piholebridge", so seems like there is a difference between the display name of the bridge and the true name

**Comment by BobbySlope** [comment]
Please let us know if this issue is still persistent. If so reopen the issue and provide us more detailed info to reproduce the issue
