### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by Kompass02** [hoobs-org/HOOBS#1607]
Hello there.

I have a problem to update my hops station. Since The Version 4.010 the update process failed with this comment:

hoobs@hoobs:~ $ sudo apt install hoobsd hoobs-cli hoobs-gui
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libbrotli1
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  helm
The following NEW packages will be installed:
  helm hoobs-cli hoobs-gui hoobsd
0 upgraded, 4 newly installed, 0 to remove and 145 not upgraded.
Need to get 13.4 MB/13.7 MB of archives.
After this operation, 238 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 https://dl.hoobs.org/deb/stable buster/main armhf hoobs-cli all 4.0.46
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2606:50c0:8003::153 443]
Err:2 https://dl.hoobs.org/deb/stable buster/main armhf hoobsd all 4.0.104
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2606:50c0:8003::153 443]
Err:3 https://dl.hoobs.org/deb/stable buster/main armhf hoobs-gui all 4.0.91
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2606:50c0:8003::153 443]
E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobs-cli/hoobs-cli_4.0.46_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2606:50c0:8003::153 443]
E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobsd/hoobsd_4.0.104_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2606:50c0:8003::153 443]
E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobs-gui/hoobs-gui_4.0.91_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2606:50c0:8003::153 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

And if I try "apt-get update":
hoobs@hoobs:~ $ sudo apt-get update
Ign:1 https://dl.hoobs.org/deb/stable buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                   
Hit:3 https://deb.nodesource.com/node_14.x buster InRelease                    
Err:4 https://dl.hoobs.org/deb/stable buster Release                           
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2606:50c0:8003::153 443]
Hit:5 https://dl.yarnpkg.com/debian stable InRelease                           
Hit:6 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease
Reading package lists... Done
E: The repository 'https://dl.hoobs.org/deb/stable buster Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Do you have an idea to find the issue?

Thank you a lot.

Best regards
Marcus

**Comment by nicoryan** [comment]
@Kompass02 I also am having this issue
<img width="1502" alt="Screen Shot 2021-10-21 at 8 22 04 PM" src="https://user-images.githubusercontent.com/18583977/138374303-16d660dc-6954-4c36-b9bc-98fc6972102b.png">
.
