### ISSUE TITLE
Unable to install Hoobs-certified Plugin - RoombaSTV

### ISSUE THREAD

**Issue by gnbanta** [hoobs-org/HOOBS#1609]
Can't obtain Roomba password after 10 tries. Get the BLID but always fails to get the password and cannot continue with configuration. See attached [screensho
![Screen Shot 2021-10-22 at 5 52 47 PM](https://user-images.githubusercontent.com/93014404/138527615-2e85fdfc-2445-4541-9df9-c6c8d17b4541.png)
t.

**Comment by BobbySlope** [comment]
If this issue still persistant? If so reopen the issue and provide more information to reproduce the issue
