### ISSUE TITLE
Weather Forecast still donut work in Switzerland

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#161]
<img width="613" alt="Screenshot 2019-09-24 at 09 28 34" src="https://user-images.githubusercontent.com/50763727/65491190-dde5a000-deae-11e9-92f6-1a56018c1913.png">

@mkellsy I can give you access to my box if you want

**Comment by mkellsy** [comment]
There is not an issue here. I tested, I changed my location to CH,5080 (Switzerland) and the weather shows without issue. This may me due to a cookie that persisted in an earlier version of the beta.

I am closing because there is nothing to do here in the code.
