### ISSUE TITLE
HOOBS not updating to 4.1.9

### ISSUE THREAD

**Issue by ymohiuddin** [hoobs-org/HOOBS#1610]
Hi I am on 4.0.98 and I am attempting to update but it is giving me an error message
![Screen Shot 2021-10-23 at 11 44 44 AM](https://user-images.githubusercontent.com/88597993/138563013-af2b9485-16ae-4a88-88a1-1e29c340f5d2.png)

**Comment by Olegaus** [comment]
Hi. I am on. v 4.0.104 won't update at all.. No errors.. Its says you're up to date. Is it latest version?

**Comment by geox19** [comment]
> Hi. I am on. v 4.0.104 won't update at all.. No errors.. Its says you're up to date. Is it latest version?

I was stuck on v4.0.104 and the hoobs desktop app would just hang when checking for updates. Hoobs web gui would say I'm up to date so I ran the script above from a terminal and now I'm on version 4.1.11 node version 14.18.1 and home bridge version 1.3.5 the desktop app now checks for updates without hanging. curl -sk https://dl.hoobs.org/fix | sudo bash -

**Comment by Olegaus** [comment]
ran the above script in Mac terminal. it says no such file in directory. trying to log in in terminal using hoob.local asking for user and password when entered correctly not letting me in.. Resetting to factory settings and establishing new user didn't get me anywhere. Mac Hoobs app just hangs when trying to update, website UI Hoobs.local say it up to date. Current versing listed still 4.0.104
