### ISSUE TITLE
Authentication button not appearing in hoobs for certified plugin (simplisafe3)

### ISSUE THREAD

**Issue by vineetpotdar** [hoobs-org/HOOBS#1614]
**Description**
In order to configure the plugin authentication, there should be appearing a button to follow the guided steps. However the plugin's configuration page doesn't show any button. Additionally when trying to follow the command line method, hoobs terminal says "command not found"

**Expected behavoir**
SimpliSafe Authentication

As of December 2021 and v1.8.x of this plugin, SimpliSafe has transitioned to only supporting a protocol called OAuth for authentication. This requires the user to authenticate in a browser and it is not possible to circumvent this and authenticate directly against the API. This plugin provides two main ways to obtain credentials:

Users of Config UI X (which is included in many Homebridge installations) can initiate this process from the plugin settings. A button will launch the authentication process and you will have to copy and paste the final URL (begins with com.SimpliSafe.mobile://) back into the plugin settings. While Safari will redirect to the URL (and show an error) allowing you to easily copy and paste the URL, in some browsers (e.g. Chrome) the browser will not redirect you and will show an error in the Console (e.g. View > Developer Tools > Javascript Console) and you will have to copy and paste the URL from the error message. Also please note that this task cannot be performed on an iOS device that has the SimpliSafe app installed (authenticating will launch the app).
Alternatively the plugin provides a command-line method for authenticating. The process works the same as above and can be run using homebridge-simplisafe3 login. If you are using a non-standard storage location for Homebridge pass the -d argument e.g. homebridge-simplisafe3 login -d /path/to/storage/

**Plugin name**
SimpliSafe3

**Please report the issue to the plugin developer**
This issue has been reported already and has been redirected as an issue with hoobs.
https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/247
https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/discussions/248

**Version**
Please include the version of HOOBS you are using.
4.0.104

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No
- [N/A] => I directly purchased HOOBS 3
 
**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

    "accessories": [],
    "platforms": [
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "name": "Security System (SS)",
            "sensorRefresh": 15,
            "cameras": true,
            "resetSimpliSafeId": false,
            "persistAccessories": true
        }
    ]
}

**Post your log**

```
POST LOG HERE
```
10/24/2021, 9:54:10 AMSimplisafe BridgeSecurity System (SS)ERRORSimpliSafe login failed with error: Error: No authentication credentials detected.
    at SimpliSafe3AuthenticationManager.refreshCredentials (/var/lib/hoobs/simplisafebridge/node_modules/homebridge-simplisafe3/common/authManager.js:191:15)
    at new SS3Platform (/var/lib/hoobs/simplisafebridge/node_modules/homebridge-simplisafe3/index.js:84:41)
    at /usr/src/bridge/server.ts:455:46
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/src/bridge/server.ts:438:31)
    at Server.start (/usr/src/bridge/server.ts:239:69)
10/24/2021, 9:54:10 AMSimplisafe BridgeSecurity System (SS)ERRORSee the plugin README for more information on authenticating with SimpliSafe.
10/24/2021, 9:54:10 AMSimplisafe BridgeSecurity System (SS)ERRORInitial accessories refresh failed with error: Error: Not authenticated with SimpliSafe.
    at /var/lib/hoobs/simplisafebridge/node_modules/homebridge-simplisafe3/index.js:103:56

**Additional context**

**Comment by mkellsy** [comment]
The issue is the plugin won't start.
Remove this from your config.
```
"auth": {
    "username: "***",
    "password": "***"
}
```

Then the plugin should start.

**Comment by wsr554** [comment]
@mkellsy I am new at this and might be in the wrong spot but this is all that is showing. I went into the Simplisafe3 plugin, then configuration, and last advance. Thank you for your help
<img width="883" alt="Screen Shot 2021-10-30 at 8 47 59 PM" src="https://user-images.githubusercontent.com/93354391/139564806-925c502b-2b93-435d-b609-8562f2c7a8fe.png">
!

**Comment by vineetpotdar** [comment]
Took a bit of attempts, but finally was able to get it to work. Thank you!

**Comment by wsr554** [comment]
😩 Sorry for being annoying, but I have tried uninstalling and reinstalling the Mac app and plugin about 30 times. Every time the bridge wont launch. I have no idea what I am doing wrong. Any help would be awesome. Thanks!
