### ISSUE TITLE
This accessory is not responding.

### ISSUE THREAD

**Issue by ggianop** [hoobs-org/HOOBS#1616]
I have a hoobs box device configured with my apple home kit. All devices have been bridged to homekit for my smartthings, hue & ring. It ran for about 2-weeks with some success. While away on vacation the device has gone offline. Homekit reports for each of the 3 bridges it establishes (Smartthings, Philips, Ring):

> This accessory is not responding

I've used the Hoobs desktop to scan and it reports:
>      No devices. 
>      Make sure your device is plugged in and connected to the network".

I've restarted the hoobs box, and it lights RED. But the device does not seem to obtain an IP address, according to my dhcp server. I've always used the hoobs with ethernet. I've also tried wifi, but I never see a wifi access-point present.

It seems this device just died though it lights red.

My invoice is #27296.

**Version**
hoobs box (no way to know software version)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
It's offline.

**Post your config**
It's offline.

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
It's offline.

```
POST LOG HERE
```

**Additional context**
It seems this device fried itself, or failed to burn-in. It was powered via a ups, nothing else on the same circuit or network switch has experienced any damage.

**Comment by BobbySlope** [comment]
Please contact support@hoobs.com for further investigation and or replacement
