### ISSUE TITLE
GPIO Device plugin configuration

### ISSUE THREAD

**Issue by lesgongons** [hoobs-org/HOOBS#1617]
**Description**
I have an issue when using the configuration tab of the GPIO device plugin. If i used the configuration tab, it generate automatically update the accessory name to "GPIO Device" which seams not working. See the code generated after i save (the initial name was GPIODevice!!)
{
    "accessories": [
        {
            "accessory": "Gpio Device",
            "name": "Porte Garage",
            "type": "GarageDoorOpener",
            "openingDuration": 2,
            "waitingDuration": 2,
            "pulseDuration": 1000,
            "pin": 6,
            "plugin_map": {
                "plugin_name": "homebridge-gpio-device"
            }
        }
    ]
}

If i use the advanced tab and write my code directly in it, it works perfectly!, see the code:
{
    "accessories": [
        {
            "accessory": "GPIODevice",
            "name": "Porte Garage",
            "type": "GarageDoorOpener",
            "openingDuration": 2,
            "waitingDuration": 2,
            "pulseDuration": 1000,
            "pin": 6
        }
    ],
    "platforms": []
}

**Plugin name**
GPIO device

**Please report the issue to the plugin developer**
I think that this is not an issue from the plugin but from the configuration tab

**Version**
HOOBS 4.0.110

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

it works for me but could be useful for other people

**Comment by Peevb** [comment]
Thanks for the info! just what I was looking for.
