### ISSUE TITLE
Unable to Authenticate/Pair with Vivint

### ISSUE THREAD

**Issue by willop75** [hoobs-org/HOOBS#1620]
Unable to connect with Vivint.

Two factor authentication is required to pair with my Vivint account... but HOBBS app does not have an option to enter the authentication code...

Please help.

**Comment by mkellsy** [comment]
Had to update the the UI plugin.

This is done. You can get it by re-installing the plugin.

1. Go to the plugin page
2. Click on the Versions tab
3. Click on the Latest tag
4. Select the current bridge it's installed on

You will see the Link Account button as soon as the bridge restarts.
