### ISSUE TITLE
Update to Server 4.1.11 fails 

### ISSUE THREAD

**Issue by MasterofKungfu9999** [hoobs-org/HOOBS#1621]
**Description**
the newest update Server Version: 4.1.11 and GUI 4.1.11 fails and the gui/server restarts

**Version**
4.1.9

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
26.10.2021, 08:19:04E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
26.10.2021, 08:19:04WARNUNGservice restart command received
26.10.2021, 08:19:02restarting
26.10.2021, 08:19:02
```

**Additional context**

**Comment by Githubnewbynewb** [comment]
[https://github.com/hoobs-org/HOOBS/issues/1621#issuecomment-952410288](url). Worked for me too!

> The problem is you are using HelM to update HelM.
> 
> Use SSH either the mac terminal or windows power shell
> 
> ```
> ssh hoobs@hoobs.local
> ```
> 
> Then run
> 
> ```
> sudo dpkg --configure -a
> ```
> 
>  > This is actually caused by the post install script on HelM. HelM is the terminal you are using to update. I have this addressed in this issue [hoobs-org/helm#7](https://github.com/hoobs-org/helm/issues/7)

Worked for me too, Thank you !
