### ISSUE TITLE
error when attempting to install any plugin

### ISSUE THREAD

**Issue by MatthewDyer-SLS** [hoobs-org/HOOBS#1623]
**Description**
I just received my Hoobs, plugged it in to power, got the initial WiFi set up and everything appears to be ready to rock. 
however, when I attempt to install any plug in, Ring for example, I get an error message advising "Unable to install plugin. Please try again later"

**Expected behavoir**
I expect the plugin to install without errors.... 

**Plugin name**
Ring

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
V4.0.98 (also when I click Update Available, I get the house icon but it doesn't appear to do anything)
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
N/A

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
```
{
    "accessories": [],
    "platforms": []
}
```

**Post your log**

```

10/18/2021, 10:05:28 AMhub is running on port 80
10/25/2021, 8:27:57 PMRing Bridge starting
10/25/2021, 8:28:04 PMRing Bridge 2 starting
10/25/2021, 8:28:05 PMringbridge stopping
10/25/2021, 8:28:10 PMRing Bridge starting
10/25/2021, 8:28:17 PMRing Bridge 3 starting
10/25/2021, 8:29:42 PMringbridge3 stopping
10/25/2021, 8:29:42 PMRing Bridge 4 starting
10/25/2021, 8:29:47 PMRing Bridge 3 starting
10/25/2021, 8:30:01 PMmyQ Bridge starting
10/25/2021, 8:41:22 PMmyqbridge stopping
10/25/2021, 8:41:27 PMmyQ Bridge starting
10/25/2021, 8:41:47 PMringbridge stopping
10/25/2021, 8:41:52 PMRing Bridge starting
10/25/2021, 8:42:06 PMringbridge2 stopping
10/25/2021, 8:42:12 PMringbridge3 stopping
10/25/2021, 8:42:19 PMringbridge4 stopping
10/25/2021, 8:42:31 PMringbridge stopping
10/25/2021, 8:42:39 PMmyqbridge stopping
10/25/2021, 8:43:11 PMRing Bridge starting
10/25/2021, 8:43:18 PMRing Bridge 2 starting
10/25/2021, 8:43:18 PMringbridge stopping
10/25/2021, 8:43:23 PMRing Bridge starting
10/26/2021, 9:21:03 AMringbridge stopping
10/26/2021, 9:21:08 AMRing Bridge starting
10/26/2021, 9:21:48 AMRing Bridge 3 starting
10/26/2021, 9:21:49 AMringbridge2 stopping
10/26/2021, 9:21:54 AMRing Bridge 2 starting
10/26/2021, 9:29:08 AMRing Bridge 4 starting
10/26/2021, 9:29:09 AMringbridge3 stopping
10/26/2021, 9:29:14 AMRing Bridge 3 starting
10/26/2021, 9:40:59 AMRing Bridge 5 starting
10/26/2021, 9:48:44 AMringbridge5 stopping
10/26/2021, 9:48:44 AMringbridge2 stopping
10/26/2021, 9:48:49 AMRing Bridge 5 starting
10/26/2021, 9:48:50 AMringbridge3 stopping
10/26/2021, 9:49:03 AMringbridge4 stopping
10/26/2021, 9:49:11 AMringbridge5 stopping
```

**Additional context**

**Comment by Olegaus** [comment]
I have exactly same issue.  Bought HOOBS to run MyQ two door garage. That is it. Worked for about a month.  Tried to restore from back up. Restored to factory setting several times already. Nothing works. Unable to install plugin, please try again later... Frustrating, over $200 for this tot to work..

**Comment by Olegaus** [comment]
Update: Running sudo yarn cache clean fixed it. Now another problem. MyQ only opens one of the two garage doors. Again no errors, just not working. Any Ideas?

**Comment by mkellsy** [comment]
Try clearing the bridge cache. Bridges screen -> Select Bridge -> Cache button.
