### ISSUE TITLE
Harmony - Error loading plugin "homebridge-harmony"

### ISSUE THREAD

**Issue by EddieDSuza** [hoobs-org/HOOBS#1624]
**Description**
HOOBS 4 not loading the certified Harmony plugin. 

**Expected behavoir**
Load plugin and import devices from the Harmony Hub

**Plugin name**
https://plugins.hoobs.org/plugin/homebridge-harmony

**Please report the issue to the plugin developer**
The plugin is not loading 

**Version**
4.1.11

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
4.1.9

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Post your config**
-----

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
10/26/2021, 6:34:59 PMWARNINGservice restart command received
10/26/2021, 6:35:07 PMHarmony Bridge stopping
10/26/2021, 6:35:17 PMhub is running on port 80
10/26/2021, 6:35:18 PMHarmony Bridge starting
10/26/2021, 6:35:23 PMHarmony BridgeERRORError loading plugin "homebridge-harmony"
10/26/2021, 6:35:23 PMHarmony BridgeWARNINGNo plugins installed.
10/26/2021, 6:35:23 PMHarmony BridgeLoading 1 platforms...
10/26/2021, 6:35:23 PMHarmony BridgeBridge is running on port 51826.
```
<img width="669" alt="Screen Shot 2021-10-26 at 19 37 18" src="https://user-images.githubusercontent.com/52710883/138971362-3a5927e4-1b84-4944-a8f7-b986f48ec5ac.png">

**Comment by mkellsy** [comment]
Unable to reproduce. I use Harmony in my main setup and it installs and connects to my Harmony Hub without issue.

I will continue to try to reproduce.
