### ISSUE TITLE
Treatlife Ceiling Fan & Light Dimmer Switch Model DS-03

### ISSUE THREAD

**Issue by jstewart1988** [hoobs-org/HOOBS#1625]
I have been trying to get this fan control and light dimmer switch to work under HOOBS so I can use it in Homekit. Treatlife is the same as Tuya so I tried the Tuya HOOBS verified plug-in first. 
https://plugins.hoobs.org/plugin/@milo526/homebridge-tuya-web

The plug-in recognizes the switch but only provides fan control - on/off and 4 speeds. It doesn't provide control for the light on/off and dimmer.

I also tried several of the other Tuya plug-ins but none worked correctly for me.

After reading about others successfully getting this switch to work under Homebridge I installed Homebridge on my Mac and tried the tuya-homebridge plug-in. It requires a Tuya developer account and had me link my IOS Tuya Smart app to the developer account. The plug-in then communicates with that account and has access to devices registered through that account. 

This is the Homebridge Plug-in worked for me:
https://github.com/tuya/tuya-homebridge

My request is that someone make the tuya-homebridge 1.4.2 plug-in work in HOOBS.

Thanks in advance!

**Comment by BobbySlope** [comment]
We will certify it.

**Comment by jstewart1988** [comment]
Hello Bobby,I have used the Tuya Platform bridge successfully without issues for about a year. It has been solid. This week something changed and caused it to stop working. Other users experienced the same problem as well according to GitHub. Someone figured out a way to make it work but it requires modifying a file.workaround 'skill id invalid' false positive error · ***@***.*** this same modification be made to the HOOBS plugin?Thanks,Joel StewartSent from my iPadOn Dec 30, 2021, at 7:37 AM, BobbySlope ***@***.***> wrote:﻿
Closed #1625.
