### ISSUE TITLE
Support for RPi Zero 2, Arm 8

### ISSUE THREAD

**Issue by xraynano** [hoobs-org/HOOBS#1628]
The Raspberry Pi Zero 2 was just released, and it utilizes a 64-bit Arm Cortex-A53 CPU, which is an Arm 8 implementation. Does anyone know if this is supported under v4 HOOBS?

**Comment by mkellsy** [comment]
We do support arm64 (aka arm8)
https://support.hoobs.org/downloads/image?platform=arm64
