### ISSUE TITLE
Error "temporary failure resolving 'mirrors.ocf.berkeley.edu'" Received when Manually Reinstalling Node and Yarn to Fix Failed Migration to Version 4

### ISSUE THREAD

**Issue by toejeep** [hoobs-org/HOOBS#1630]
**Description**
My migration to version 4 failed, so I attempting a manual effort as documented here:  https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a.  When I attempted the step to reinstall Node and Yarn, I am getting the error "temporary failure resolving 'mirrors.ocf.berkeley.edu'" and unable to get any farther in the process

**Version**
4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
3.3.12

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
This fix script replaces the Berkley mirror.
```
curl -sk https://dl.hoobs.org/fix | sudo bash -
```
