### ISSUE TITLE
HSP Plugin Syntax Error

### ISSUE THREAD

**Issue by sebastianertl** [hoobs-org/HOOBS#1631]
**Description**
After Installing HSP i see Syntax error in the Log file and the Plugin is not shown under my bridge, also all other plugins do not show anymore, compare also:

**Expected behavoir**
Plugin works and is showed under my bridge

**Plugin name**
HSP

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
4.1.11 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
29.10.2021, 15:16:15HSP starting
29.10.2021, 15:16:48FEHLERSyntaxError: Unexpected token } in JSON at position 1239
    at JSON.parse (<anonymous>)
    at Function.loadSchema (/usr/src/services/plugins.ts:449:32)
    at Function.getPluginType (/usr/src/services/plugins.ts:341:32)
    at Timeout._onTimeout (/usr/src/services/plugins.ts:138:41)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
The plugin's confitg schema is broken.
We are overriding the schema from our plugins site, but it still will generate the error when installing.

I have opened a pull request for the developer
https://github.com/nidy86/homebridge-hsp/pull/5
