### ISSUE TITLE
Hoobs stopped working and I can't access it at all

### ISSUE THREAD

**Issue by Xelajuh** [hoobs-org/HOOBS#1637]
**Description**
I purchased  Hoobs device only 2 months ago.  It worked briefly for about a month, then stopped suddenly.  I can't access it at all, even though my router does see that it's there.  However, I can't access it via the desktop app (which says there are no devices found), via the IP address in the desktop app, via the IP address in a browser, nothing at all works.  I have spent a lot of time trying to find solutions online, but nothing works.  There is no way to reset the hoobs device to factory settings, although there are cryptic instructions posted by some users, but nothing works.  I'm fed up, and I don't have the time to spend hours and hours trying to get it to work.  I want this fixed, replaced or a refund.  This must be a defective unit.

**Version**
I have no idea what version it is, as I can't access it to find out.  I think it's 3.XX.

**Did you upgrade**
When it was actually running, I believe I tried to upgrade to version 4, but I don't think it actually did so.

- [ ] Yes
- [x] No

**Pervious version**
No idea, can't check, but it was in 3.XX.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
N/A.

**List your plugins**
The only plug in that actually worked was myQ for my garage doors.  It actually worked nicely and right away.  I could not get harmony or any other plugin to do anything.

**Post your config**
No idea what this is or how to get it.  I typed SSH '~/.hoobs/etc/config.json' as you instructed here in the "run" window, but it gives me nothing at all.

**Comment by mkellsy** [comment]
Please send an email to info@hoobs.com we can troubleshoot and replace components if needed.
