### ISSUE TITLE
Weather Forecast 

### ISSUE THREAD

**Issue by bgiuriceo** [hoobs-org/HOOBS#164]
not visible in Safari Version 13.0.1 (14608.2.11.1.11)
visible in Google Chrome Version 77.0.3865.90
HOOBS beta .57

(in Chrome the temperature reporting is 10 degrees lower than it should be for my zip code)

Just to keep this issue working.

**Comment by mkellsy** [comment]
You might need to clear your browser cache.

The weather is provided by OpenWeatherMap.org.

**Comment by mkellsy** [comment]
bgiuriceo is still having issues with this in Safari.

**Comment by mkellsy** [comment]
It is working on my end. I am unable to reproduce.
<img width="1680" alt="Screen Shot 2019-09-26 at 10 35 44 AM" src="https://user-images.githubusercontent.com/9777975/65707309-80398b00-e049-11e9-8b2d-d861629edd20.png">

**Comment by bgiuriceo** [comment]
I never got a response yesterday but I was asked to provide information from the browser, was that ever received? I’ve flushed the cache multiple times and shut down Ad Block. There are no other extensions running either.

**Comment by mkellsy** [comment]
No I didn't get the console log. What email did you use? Im at mkellsy@hoobs.org. What country and post code are you using.

I am trying to find out what is happening, but this is working for me on 5 different Macs and 3 different iPads. I have to be able to reproduce to fix. Without this I am shooting in the dark, and this could cause more problems.

Yesterday I found that Safari parses dates differently than every other browser. This is what was causing Safari to not show the forecast on my computers. I fixed this and ran through testing to make sure the other parts of the system that use dates weren't affected and working in Safari.

I am trying very hard to reproduce.

**Comment by mkellsy** [comment]
I'm moving the date calculations to epoch time UTC plus offset. This allows the code to use int dates. This should bypass all the wired stuff Safari does with dates. It is the most basic date calculation for the browser.

The reason why there is date calculation is important, is OpenWeatherMap.org doesn't supply a 5 day forecast. It only supplies a 15 minute forecast for a week. Therefore the forecast must be parsed by daytime temps and only show the temp at noon.

This is changed in 3.0.0-beta.58.

**Comment by bgiuriceo** [comment]
Nice work Michael Kellsy! Forecast is now working on Safari in beta 59.
