### ISSUE TITLE
Nest Bridge 4.6.2 (Certified)

### ISSUE THREAD

**Issue by gferguson1815** [hoobs-org/HOOBS#1640]
**Description**
After installing the plugin is unable to link to the Google account via the UI

**Expected behavoir**
Link to the nest/Google account

**Plugin name**
Nest Bridge 4.6.2

**Please report the issue to the plugin developer**
The developer has stated they do not use HOOBS and that this is a HOOBS issue rather than the plugin

**Version**
4.0.92

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] No

**Pervious version**

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Comment by gferguson1815** [comment]
Also upgraded using curl -sk https://dl.hoobs.org/fix | sudo bash - as per other similar reported issues which worked.

Any reason why the update would not show in the HOOBS UI?

**Comment by mkellsy** [comment]
The fix script fixes the OS. It clears the APT cache and updates the OS. That's why the update didn't show.
We developed the fix script because of this.
