### ISSUE TITLE
hue smart plugs shows as a light bulb

### ISSUE THREAD

**Issue by fedexx89** [hoobs-org/HOOBS#1642]
Hi there.
I'm having a question using the Philips smart plugs. I'm using Hoobs 4.
Actually there are already Osram plugs where I used an command to change them to a plug instead of a bulb.
Now I added some Philips smart plugs and they are displayed as bulbs again. 

I found this issue, which is closed already but shows my problem: 
[https://github.com/hoobs-org/HOOBS/issues/467](url)

As you can see I get the message "no such file or directory" when entering the command. What can I do?

**Comment by BobbySlope** [comment]
Nothing we can do here theres no option provided by the plugin developer
