### ISSUE TITLE
Hoobs not detected in macOS app

### ISSUE THREAD

**Issue by ChadWillC** [hoobs-org/HOOBS#1643]
I recently purchased the hoobs starter kit from someone on fb marketplace. 

Followed the instructions of downloading and installing the macOS desktop hoobs app, plugged in the unit to my network via ethernet and waited 2-3 minutes. 

I see the solid red light but when I scan for the device in the app no devices are found. 

I have a cable modem and an Eero pro plugged into it through ethernet and I see it showing up in to Eero app. 

I also tried clicking advanced and putting in the IP address listed in the Eero app for it, I went with the device port of 80. It states invalid IP address.

I tried connecting to the device using a web browser for the IP address and I typed in username: hoobs and password: hoobsadmin which I found online. It rejects the credentials.

I followed the following instructions I found on the hoobs fb community page but still getting invalid username and password when trying to log in with default hoobs and hoobsadmin credential at IP address of hoobs in browser. hoobs.local doesn't load, it only loads a login screen if I go directly to the IP address of the unit. 

----------------------------------------------------------------------------------------------------
"Your HOOBS account runs locally on your device. If you forgot your username or password here are instructions to reset your local account:

1. Go to http://hoobs.local:9090 in your browser
2. Login with SSH credentials: hoobs // hoobsadmin
3. Paste this command to delete the user account: sudo rm -f /var/lib/hoobs/access
4. Restart the HOOBS Service with this command: sudo hoobsd service restart You will then be prompted to create a new account when you go to http://hoobs.local or open the device in the Desktop app. This won't affect your plugins."
----------------------------------------------------------------------------------------------------

After running through these steps I am still unable to login via IP address of device which give me a hoobs local login UI.

When running the commands it does prompt after the restart command so I removed the d after hoobs and it accepts the command but issue persists:

hoobs@hoobs:~ $ sudo rm -f /var/lib/hoobs/access hoobs@hoobs:~ $ sudo hoobsd service restart sudo: hoobsd: command not found hoobs@hoobs:~ $ sudo hoobs service restart hoobs@hoobs:~ $

Even though it has an assigned IP that starts with 192 when the hoobs device is connected to power and router it only has a blinking orange light and a steady red light on the inside.

Not sure what I am doing wrong and could use feedback for what I am missing. Feedback is warmly received and appreciated.

**Comment by ChadWillC** [comment]
I also tried clicking advanced and putting in the IP address listed in the Eero app for it, I went with the device port of 80. It states invalid IP address.

**Comment by ChadWillC** [comment]
I tried connecting to the device using a web browser for the IP address and I typed in username: hoobs and password: hoobsadmin which I found online. It rejects the credentials.

**Comment by ChadWillC** [comment]
I followed the following instructions but till getting invalid username and password when trying to log in with default hoobs and hoobsadmin credential at IP address of hoobs in browser.

Your HOOBS account runs locally on your device. If you forgot your username or password here are instructions to reset your local account:
1. Go to http://hoobs.local:9090 in your browser
2. Login with SSH credentials: hoobs // hoobsadmin
3. Paste this command to delete the user account: sudo rm -f /var/lib/hoobs/access
4. Restart the HOOBS Service with this command: sudo hoobsd service restart
You will then be prompted to create a new account when you go to http://hoobs.local or open the device in the Desktop app.
This won't affect your plugins.

After running through these steps I am still unable to login via IP address of device which give me a hoobs local login UI.

**Comment by ChadWillC** [comment]
Even though it has an assigned IP that starts with 192 when the hoobs device is connected to power and router it only has a blinking orange light and a steady red light on the inside.

**Comment by fred-thorne** [comment]
Hello Chad, I'm having the same/similar issues here as well.  I've been struggling with HOOBS since I bought it earlier this year.  I too suspect I'm doing something wrong but for the life of me cannot figure out what it is.

**Comment by mkellsy** [comment]
Can you access the web interface? http://hoobs.local

**Comment by ChadWillC** [comment]
It doesn't load when I go to the site. It only loads when I type in the IP address the has been assigned to the unit.

**Comment by mkellsy** [comment]
The UI doesn’t have a default password. If you don’t get the initial setup screen when accessing the UI. Send an email to info@hoobs.com.

Did you buy this from Amazon?

**Comment by ChadWillC** [comment]
Thanks for your help with resolving my issue as we continued to troubleshoot via info@hoobs.com. I am loving having a working HOOBS!

**Comment by askovi** [comment]
Glad you got it working! If you need additional help, please open a new issue or contact us at info@hoobs.com.
