### ISSUE TITLE
HOOBS QR Code is missing on HOOBS Dashboard

### ISSUE THREAD

**Issue by RichardDSkene** [hoobs-org/HOOBS#1644]
**Description**
Downloaded latest version of HOOBS on Windows 10, Flashed SD card to installed on Raspberry Pi 4 (8GB).
HOOBS QR code is missing on HOOBS Dashboard.
Other plugsin can be installed and QR Codes are created.
Also downloaded Latest HomeBridge and installed on the same Raspberry Pi and QR code is available on that DashBoard

**Version**
Version 4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by RichardDSkene** [comment]
The QR code was missing on the Bridges page too!

**Comment by askovi** [comment]
You have to install a plugin. Each bridge has its own QR code in HOOBS 4. Separating plugins to 1 per bridge improves stability

**Comment by RichardDSkene** [comment]
I understand you need to install a plugin for each bridge and I was able to do that, and the QR codes would show up individually for those plugins but the initial QR code for HOOBS does show on the dashboard or Bridge screens.
In the mean time I've installed HomeBridge and the QR code appears on its dashboard and your are then able to capture it and establish the bridge on the Home app.
Is there no HOOB's QR code required as with HomeBridge and will just adding the individual plugin/bridges be sufficient.

**Comment by mkellsy** [comment]
There is no initial QR code. Each bridge is independent.
