### ISSUE TITLE
Issue at apt upgrade

### ISSUE THREAD

**Issue by jridder** [hoobs-org/HOOBS#1645]
During the latest apt upgrade, I got the following:

Setting up hoobsd (4.0.110) ...
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 26.61s.
Hit:1 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
error executing command
dpkg: error processing package hoobsd (--configure):
 installed hoobsd package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 hoobsd

I have tried a few things with dpkg and apt but can't get it resolved. My understanding is that fsevents isn't needed on the raspberry pi but I thought I had deleted the package.

**Comment by bwp91** [comment]
This may or may not be relevant, but, v4.1 of hoobs is out now, you can try running this command from the terminal (ideally via an ssh client rather than through the homebridge terminal),

```
curl -sk https://dl.hoobs.org/fix | sudo bash -
```

i believe running this fixes a few things to be able to update to 4.1.

Doing this may in turn fix your issue here!

**Comment by jridder** [comment]
Thanks, that fixed it.
