### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1648]
Hi, sorry but since 4.0 your release notes are still unavailable.
Or just saying updated. And now still cant find any information.

**Comment by Christian-CFP** [comment]
Do I have to lower my expectations here as well? As this cannot be common?

**Comment by mkellsy** [comment]
I understand your desire to review the changes made. I push a ton of code, and I work a lot. I just haven’t found time to write the code to generate release notes yet. It would be a lot easier if we had 1 repo and 1 binary, but with agile development this is not the case. You are welcome to review the commit messages from our projects in the meantime.

https://github.com/hoobs-org/hoobsd/commits/blackwing  
https://github.com/hoobs-org/image/commits/blackwing  
https://github.com/hoobs-org/repo/commits/main  
https://github.com/hoobs-org/portal/commits/blackwing  
https://github.com/hoobs-org/helm/commits/blackwing  
https://github.com/hoobs-org/cli/commits/blackwing  
https://github.com/hoobs-org/desktop/commits/blackwing  
https://github.com/hoobs-org/gui/commits/blackwing

**Comment by Christian-CFP** [comment]
Hope that there soon will be a place to really see all changes. Right?

**Comment by Christian-CFP** [comment]
Is it correct, that you have update HB and node? @mkellsy 
https://github.com/hoobs-org/hoobsd/commit/aa71f31937d3fbc6b20196547d18970ce7f13dc7

Because I am still on 4.1.15 HB 1.3.5 and node 14.18.1

**Comment by mkellsy** [comment]
That's in 4.1.17. I will release it this week. Needed to wait until others got updates to 4.1.15
