### ISSUE TITLE
Advanced Config Scroll Jumping in Edge

### ISSUE THREAD

**Issue by xdmate** [hoobs-org/HOOBS#165]
While copying or highlighting text in my config, the page moves up and down a line super quickly. Making it hard to copy anything accurately because its moving. 

To replicate just try to highlight something in your config.

I'm using the latest version of edge chromium, if you can't replicate I can upload a video showing exactly what its doing. 

Thanks!

**Comment by mkellsy** [comment]
What version of HOOBS are you using?

**Comment by xdmate** [comment]
3.0.0-beta.59

Since I updated to this version the updater no longer [shows](https://i.imgur.com/bAKBgwP.png) what version I'm on & if theres an update.

**Comment by mkellsy** [comment]
The version is on the home screen.

Also are you talking about the Advanced Configuration screen?

**Comment by xdmate** [comment]
Yeah I got the version off the home screen. & Yes I'm talking about the advanced config screen.

**Comment by mkellsy** [comment]
Next Step
I need to fire up my Windows computer to see if I can reproduce.

**Comment by xdmate** [comment]
I did some testing. I don't have the issue in Chrome or Safari. I tried edge chromium with all plugins and the issue still persists. 

Also, I haven't tested it on a Windows computer. I've only been on my laptop the last few days & I'm on the latest version of Edge Chromium

**Comment by mkellsy** [comment]
I understand, as a Windows Insider I have close experience with the new Edge browser. I have it installed on my Mac. I am referring to Windows as to most Edge users will be on this platform. As Safari users are on Mac (plus Apple shut down Safari on Windows). As for Linux users, we have to test on Links :) LOL.

**Comment by mkellsy** [comment]
In 3.0.0-beta.60 I added linting to the JSON fields. This highlights invalid JSON. After this change I am unable to reproduce in Edge. I did find a sizing issue with the Certified Plugin tiles.

Edge (Beta Mac)
- Certified Plugin Catalog - Tile Sizing Issue

Firefox
- No Style Issues

Safari
- No Style Issues

Chrome
- No Style Issues

**Comment by mkellsy** [comment]
I fixed all issues found with Edge in 3.0.0-beta.60
