### ISSUE TITLE
After upgrading to 4.1

### ISSUE THREAD

**Issue by Johan8012** [hoobs-org/HOOBS#1650]
Hello!
I upgraded manually to 4.1
After this Hoobs seems sluggish and when I check for updates there is big list of system updates. But they dont dissapear after updating.
What to do?

Base Files: 10.3+rpi1+deb10u11
Available
Libc6 Dbg: 2.28-10+rpt2+rpi1
Available
Libc6 Dev: 2.28-10+rpt2+rpi1
Available
Libc Dev Bin: 2.28-10+rpt2+rpi1
Available
Linux Libc Dev: 1:1.20211029-1~buster
Available
Libc6: 2.28-10+rpt2+rpi1
Available
Libc Bin: 2.28-10+rpt2+rpi1
Available
Python3 Debconf: 1.5.71+deb10u1
Available
Debconf Utils: 1.5.71+deb10u1
Available
Debconf I18n: 1.5.71+deb10u1
Available
Debconf: 1.5.71+deb10u1
Available
Libsystemd0: 241-7~deb10u8+rpi1
Available
Libpam Systemd: 241-7~deb10u8+rpi1
Available
Systemd: 241-7~deb10u8+rpi1
Available
Bluez: 5.50-1.2~deb10u2+rpt1
Available
Udev: 241-7~deb10u8+rpi1
Available
Libudev1: 241-7~deb10u8+rpi1
Available
Libasound2: 1.1.8-1+rpt2
Available
Libasound2 Data: 1.1.8-1+rpt2
Available
Systemd Sysv: 241-7~deb10u8+rpi1
Available
Liblz4 1: 1.8.3-1+deb10u1
Available
Libgcrypt20: 1.8.4-5+deb10u1
Available
Ntfs 3g: 1:2017.3.23AR.3-3+deb10u1
Available
Libntfs 3g883: 1:2017.3.23AR.3-3+deb10u1
Available
Libnettle6: 3.4.1-1+deb10u1
Available
Libhogweed4: 3.4.1-1+deb10u1
Available
Tzdata: 2021a-0+deb10u3
Available
Libssl1.1: 1.1.1d-0+deb10u7
Available
Libisc Export1100: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libdns Export1104: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Isc Dhcp Client: 4.4.1-2+deb10u1
Available
Isc Dhcp Common: 4.4.1-2+deb10u1
Available
Libxml2 Dev: 2.9.4+dfsg1-7+deb10u2
Available
Libxml2: 2.9.4+dfsg1-7+deb10u2
Available
Bind9 Host: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libbind9 161: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libisccfg163: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libisccc161: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libdns1104: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libisc1100: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libgssapi Krb5 2: 1.17-3+deb10u3
Available
Libkrb5 3: 1.17-3+deb10u3
Available
Libkrb5support0: 1.17-3+deb10u3
Available
Libk5crypto3: 1.17-3+deb10u3
Available
Liblwres161: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libc L10n: 2.28-10+rpt2+rpi1
Available
Locales: 2.28-10+rpt2+rpi1
Available
Distro Info Data: 0.41+deb10u4
Available
Firmware Atheros: 1:20190114-2+rpt4
Available
Firmware Brcm80211: 1:20190114-2+rpt4
Available
Firmware Libertas: 1:20190114-2+rpt4
Available
Firmware Misc Nonfree: 1:20190114-2+rpt4
Available
Firmware Realtek: 1:20190114-2+rpt4
Available
Klibc Utils: 2.0.6-1+rpi1+deb10u1
Available
Libklibc: 2.0.6-1+rpi1+deb10u1
Available
Libbluetooth3: 5.50-1.2~deb10u2+rpt1
Available
Libc Ares2: 1.14.0-1+deb10u1
Available
Libnftnl11: 1.1.7-1~bpo10+1~0
Available
Libraspberrypi Doc: 1:1.20211029-1~buster
Available
Libraspberrypi Dev: 1:1.20211029-1~buster
Available
Raspberrypi Kernel: 1:1.20211029-1~buster
Available
Libraspberrypi Bin: 1:1.20211029-1~buster
Available
Libraspberrypi0: 1:1.20211029-1~buster
Available
Raspberrypi Bootloader: 1:1.20211029-1~buster
Available
Libwebp Dev: 0.6.1-2+deb10u1
Available
Libwebpmux3: 0.6.1-2+deb10u1
Available
Libwebpdemux2: 0.6.1-2+deb10u1
Available
Libwebp6: 0.6.1-2+deb10u1
Available
Libtiff5: 4.1.0+git191117-2~deb10u3
Available
Libuv1: 1.24.1-1+deb10u1
Available
Libx11 Data: 2:1.6.7-1+deb10u2
Available
Libx11 6: 2:1.6.7-1+deb10u2
Available
Multiarch Support: 2.28-10+rpt2+rpi1
Available
Openssl: 1.1.1d-0+deb10u7
Available
Raspberrypi Sys Mods: 20211005
Available
Pi Bluetooth: 0.1.18
Available
Psmisc: 23.2-1+deb10u1
Available
Python Gpiozero: 1.6.2-1
Available
Python Spidev: 20200602~200721-1~buster
Available
Python3 Gpiozero: 1.6.2-1
Available
Python3 Spidev: 20200602~200721-1~buster
Available
Raspberrypi Net Mods: 1.3.2
Available
Rpi Eeprom: 12.14-1
Available
Rpi Update: 20210618
Available

**Comment by mkellsy** [comment]
Your OS is out of date.
We have a fix script that will get your OS in compliance 

curl -sk https://dl.hoobs.org/fix | sudo bash -

**Comment by Johan8012** [comment]
Hello! I ran from terminal from my mac the following commands
sudo apt-get install libgnutls30
sudo apt update
sudo apt full-upgrade
curl -sk https://dl.hoobs.org/fix | sudo bash - 

The last command I ran twice! Still the problem persists.
????

**Comment by BobbySlope** [comment]
Run the fix command again it should bring your device up to date and back up running
