### ISSUE TITLE
Configuration Save Issue

### ISSUE THREAD

**Issue by bwp91** [hoobs-org/HOOBS#1651]
**Description**
I’m basing this issue on the homebridge-wiz-lan plugin but it may apply to others.

When saving the plugin configuration, the property `platform` is saved as `Wiz Lan` when it should be `WizSmarthome`.

I have directed many users to edit the config via the “Settings” -> “Advanced” to change the `platform` to `WizSmartHome`, since when editing the plugin config from the “Plugins” panel, it saves incorrectly as `Wiz Lan`

Here is some more context and the solution I offered that worked.

https://www.reddit.com/r/HOOBS/comments/qr2oom/philips_wiz_wiz_lan_configuration/hk7o4rj/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

I don’t know whether this is due to the absence of a `config.schema.json` file, in fact I have made a pull request on the repo introducing this file.

**Version**
Please include the version of HOOBS you are using.

4.0/4.1

**Comment by BobbySlope** [comment]
Pr accepted, this should solve the issue

https://github.com/kpsuperplane/homebridge-wiz-lan/commit/d1d3b132a3d8ff4a7f47ddd6a5e0d8de7f90145b

**Comment by bwp91** [comment]
Yes, for wiz-lan I made the PR, but this issue was meant to be more general in that the same problems may occur with other plugins that don't have a config schema json file.

**Comment by BobbySlope** [comment]
Leave it closed for now, as we cant solve that in general. We will take care of it when they rise
