### ISSUE TITLE
How to install uPnP plugin

### ISSUE THREAD

**Issue by guussie** [hoobs-org/HOOBS#1655]
**Description**
Control of uPnP devices

**Expected behavoir**
On/Off/Volume/Source selection

**Plugin name**
https://www.npmjs.com/package/homebridge-upnp

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.
4.0.110

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3
This plugin was installable in version 3

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
RPi

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
Plugin cannot be installed, so no config.

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
The general question is: how can I install plugins that I can't find in the Library (I was somehow able to do that in version 3).

**Comment by askovi** [comment]
The plugin is available here: https://plugins.hoobs.org/plugin/homebridge-upnp
You can access it directly locally as well, just replace domain with hoobs.local
Plugin seems to not have been updated since 2019 so it might now work.

**Comment by mkellsy** [comment]
This plugin is blocked in the plugin site. I am not sure why. I will review the case. If it proves to be safe we can unblock it and then you will be able to install it.

Are you trying to control a Samsung TV?
Have you considered using this plugin?
https://plugins.hoobs.org/plugin/homebridge-samsungtv-control

It is newer and maintained.

**Comment by guussie** [comment]
The Samsung plugin does not allow me to control uPnP devices, so it is not appropriate for me.

I have used the uPnP plugin with an earlier version of Hoobs and this seemed to work fine.

Thanks for looking into this.

**Comment by guussie** [comment]
I am not trying to control a Samsung TV

**Comment by BobbySlope** [comment]
Upnp plugin is now unbanned and installable. Please check and teport back if everything works fine and if we need to abjust the plugin readme
