### ISSUE TITLE
HB ver. 1.3.6

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1656]
Hi is there again some update issues? 
Homebridge version 1.3.6 is out since a couple of days and no hint in the update section.

**Comment by bwp91** [comment]
There’s no update issues. Not sure what you’re expecting? 
There will be a new version of hoobs available which has homebridge 1.3.6 available in due course.

**Comment by askovi** [comment]
This is coming in 4.1.17 which is in testing for the next couple of weeks.

**Comment by Christian-CFP** [comment]
My expectation was / is the following. I thought HOOBS 4 would now perform the updates without any link to the HOOBS OS. So that we don't have to wait for a HOOBS update to get other updates.

Ok, I have to lower my expectations.

**Comment by bwp91** [comment]
I’m guessing releases of homebridge need to be tested with versions of hoobs.
i don’t see the rush in updating homebridge version?

**Comment by Christian-CFP** [comment]
Ok, so there are software parts that are connected to the HOOBS OS and are only updated with HOOBS.
Thats what I needed to know, so I don't need to be surprised if there is no update (despite the new version).

**Comment by bwp91** [comment]
> Ok, so there are software parts that are connected to the HOOBS OS and are only updated with HOOBS.
> Thats what I needed to know, so I don't need to be surprised if there is no update (despite the new version).

For the homebridge version, yes. A new version of HOOBS will be coming with Homebridge updated to 1.3.6 and node updated to v16.

**Comment by Christian-CFP** [comment]
Hey. Did you update HOOBS?
I do not get any updates!

Still in 4.1.15
HB 1.3.5
Node 14.18.1

**Comment by bwp91** [comment]
> Hey. Did you update HOOBS? @bwp91 I do not get any updates!
> 
> Still on 4.1.15 HB 1.3.5 Node 14.18.1

4.1.15 is still the latest version. When the update which includes updated versions of homebridge and node is released, it will appear as an update in the hoobs ui. i don't know a timeframe of when an update will be available.
