### ISSUE TITLE
New User - Unable to Operate

### ISSUE THREAD

**Issue by fred-thorne** [hoobs-org/HOOBS#1657]
May I have assistance please getting HOOBS in a box to work?  Earlier assistance revealed the presence of a corrupt HOOBS card and a new one was sent to me, which I have installed into my HOOBS in a box and connected via my iMac desktop computer.

I was subsequently able to upgrade this HOOBS in a box to Version 4.1.11; it is presently updating (taking forever, it seems) to upgrade to 4.1.15.  The unit indicates "all bridges are running" but the instructions for adding plug-ins include choices my HOOBS interface does not offer.

May I have assistance please in setting up my HOOBS in a box to that plug-ins can be added?

Fred Thorne
Washington State, USA
fred.thorne@me.com

<img width="1600" alt="Screen Shot 2021-11-19 at 9 18 35 AM" src="https://user-images.githubusercontent.com/75804395/142664434-3f54434e-7f0b-422c-bc75-9490898d22f9.png">

**Comment by austinrdennis** [comment]
Ok, I had this issue too. It's a little technical to fix, but I'll try to give easy instructions:

1. Login to your dashboard on hoobs.local.

2. Click the 3 vertical dots on the top right and select "Terminal" from the drop down menu.

3. It's going to take you to a screen that asks you for a username and password. The username is "hoobs" and the password is "hoobs admin". Hit enter after entering each requested piece of info.

4. Type "sudo apt-get update". It may prompt you to type yes or no, type "yes" and hit enter.

5. After that finishes, type "sudo apt-get upgrade". You should be working after a reboot now.

**Comment by BobbySlope** [comment]
You can run this command to force update hoobs and system all in one:

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3
