### ISSUE TITLE
Ring refresh token in Hoobs 4.1.11

### ISSUE THREAD

**Issue by mountain2042** [hoobs-org/HOOBS#1658]
**Description**
Can't find "terminal" and can't find a refresh token for Ring Plugin

**Expected behavoir**
Provide a refresh token

**Plugin name**
Ring

**Version**
4.1.11

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
n/a

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
n/a

**Post your config**
{
    "platform": "Ring",
    "refreshToken": "???"
}

**Additional context**
I'm new to Hoobs and have a Ring and MyQ plugin.  I got the MyQ plugin to work since it asked for my login information and was pretty simple.  The Ring plugin doesn't have a place for login information and the installation videos I've seen seems to be a little outdated as far as the Hoobs version; they recommend using a refresh token and say to click on the 3 dots on the Hoobs Dashboard to get to the terminal, but my Hoobs Dashboard no longer has terminal as an option...  So, how do I get the Ring refresh token on Hoobs 4.1.11?  Thanks!

**Comment by askovi** [comment]
You don't need to use the terminal for that anymore. That was in HOOBS 3. Ring now has a visual authentication screen. Just click on Link Account at the top of the plugin configuration page. You must use the HOOBS desktop app for Mac or Windows that you can download at https://hoobs.com/hoobs-installation-guides/
Also please make sure to update to HOOBS 4.1.15.

**Comment by mountain2042** [comment]
So I tried that and I just keep getting a message that says “Please wait for the bridge to start.”  Any ideas?  Thanks!

**Comment by mountain2042** [comment]
> You don't need to use the terminal for that anymore. That was in HOOBS 3. Ring now has a visual authentication screen. Just click on Link Account at the top of the plugin configuration page. You must use the HOOBS desktop app for Mac or Windows that you can download at https://hoobs.com/hoobs-installation-guides/
> Also please make sure to update to HOOBS 4.1.15.

@mountain2042
  
Author
 mountain2042 commented 1 minute ago • 
edited 

 So I tried that and I just keep getting a message that says “Please wait for the bridge to start.”  Any ideas?  Thanks!
