### ISSUE TITLE
Smartthings

### ISSUE THREAD

**Issue by whsbb99** [hoobs-org/HOOBS#1659]
I recently upgraded to HOOBS 4 and my setup did not transfer , so I a have to start over. I'm trying to reinstall the Smartthings plugin.  I deleted the SmartApp from the IDE, deleted the smart app from the Smartthings app, removed the hub from Homekit and started fresh.  I am able to easily reinstall all of these pieces, however none of the devices I select in the smart app within Smartthings are showing up in HOOBS and consequently are not available in Homekit.  Has anybody else experienced this issue?  This is incredibly frustrating.  I should note i am a novice, and only know enough (or thought I did) to use my devices in Homekit.  Any help is greatly appreciated.

**Comment by mkellsy** [comment]
Is your device on the same network as your SmartThings hub?

Also did you copy over the values from the smart app to HOOBS?

can you post your config?

**Comment by whsbb99** [comment]
I solved this by manually installing HOOBS (Connect) in lieu of the ST community installer Homebridge v2.  Lots of outdated information scattered across the internet.  Thanks for replying!
