### ISSUE TITLE
Postal Code input field does not allow letters

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#166]
Canadian Postal Codes are made up of 6 chars: 3 letters and 3 numbers with a space after the first 3. eg. H2B 3S4
There might be other countries using letters in their postal codes as well. Please change the input type from "number" to "text".

**Comment by askovi** [comment]
Fix also needs to be applied in the regular expression. current enforcing numbers only:
 -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?

**Comment by mkellsy** [comment]
I will open this field.

**Comment by mkellsy** [comment]
In the US postal codes are integers. I changed this to a text field.

Fixed in 3.0.0-beta.60
