### ISSUE TITLE
HOOBS "Check for Updates" hangs on Raspberry Pi

### ISSUE THREAD

**Issue by telicker** [hoobs-org/HOOBS#1660]
When attempting to check for updates in HOOBS (using the MacOS .app as well as the URL from the Pi), the search hangs and never returns any results.  The HOOBS symbol just keeps cycling.  The Pi is fully up to date.  I am currently running HOOBS 4.0.104 (see screenshot). 
<img width="1552" alt="Screen Shot 2021-11-20 at 8 21 33 AM" src="https://user-images.githubusercontent.com/26924098/142728039-03ef91c1-0909-49b1-ac43-5507b17265ae.png">

**Comment by bwp91** [comment]
Can you SSH into the raspberry pi and run the following command?

```
curl -sk https://dl.hoobs.org/fix | sudo bash - 
```

Let me know if you need help with the SSH access. I would use a dedicated terminal, not the terminal within the HOOBS UI.

**Comment by telicker** [comment]
@bwp91 

Thanks Ben... that fixed the issue.  Much appreciated.
