### ISSUE TITLE
New user - Hoobs not working 

### ISSUE THREAD

**Issue by BrianCoyle71** [hoobs-org/HOOBS#1661]
Hi, I have just installed hoobs for the first time on an rpi4. I have followed the instructions and cannot see any errors. The app allowed logon and showing dashboard, but does not appear to be running. e.g. CPU - 0% etc.. also unable to install plugins & unable to update. I must be doing something wrong on set up. I am using a MAC with latest OS installed. Any help would be grateful.

**Comment by mkellsy** [comment]
Try the 64bit version for your pi4
https://support.hoobs.org/downloads/image?platform=arm64

**Comment by BrianCoyle71** [comment]
You Sir are a legend, I cannot thank you enough. All working and enjoying using nest & ring apps.
