### ISSUE TITLE
Cannot download latest hoobs image

### ISSUE THREAD

**Issue by dabimaster** [hoobs-org/HOOBS#1662]
Hi Hoobs Team just like to confirm that once i have bought/donate hoobs image, there is no expiration on this right?
Im trying to download the latest image zip of 4.1 however it is directing me againto but the image file. Can you kindly check my account pls? 

Thanks in advamce

**Comment by mkellsy** [comment]
You can always download images here
https://support.hoobs.org/downloads

Thanks for the donation. However our software is free and open source. You will always have access to it regardless of your donation. Again thank you.
