### ISSUE TITLE
HOOBS "Check for Updates" not working. HOOBS macOS app.

### ISSUE THREAD

**Issue by wilky761** [hoobs-org/HOOBS#1665]
Hi there,

I am using macOS 12.01, HOOBS app V4.1.11.

When I click on "check for updates", nothing happens. It just hangs and then my iMac's CPU ramps up and the fan kicks in. I get no results. When I log into HOOBS via the internet, the check for updates works with no issues. So there appears to be an issue with the HOOBS macOS app.

I am running HOOBS on a HOOBS box. Please see screen grab attached.

When attempting to check for updates in HOOBS (using the MacOS .app as well as the URL from the Pi), the search hangs and never returns any results. The HOOBS symbol just keeps cycling. The Pi is fully up to date. I am currently running HOOBS 4.0.104 (see screenshot).

<img width="1414" alt="Screenshot 2021-11-22 at 10 15 15" src="https://user-images.githubusercontent.com/74021414/142844502-c92fea5e-a9e9-414d-b42a-9b465065c4b2.png">

**Comment by bwp91** [comment]
If you can SSH into your hoobs box you can try running this command:

```
curl -sk https://dl.hoobs.org/fix | sudo bash - 
```

**Comment by wilky761** [comment]
Many thanks for that. However, my HOOBS box can no longer be discovered. Have tried rebooting my HOOBS and also my broadband, and no devices are being found and when I fill in the IP address for my HOOBS, it says it is not valid. When I try using the web interface, I get a black screen.

<img width="579" alt="Screenshot 2021-11-22 at 11 09 45" src="https://user-images.githubusercontent.com/74021414/142852123-8b5c7000-8f22-4a55-9d59-fa97967ea173.png">
<img width="696" alt="Screenshot 2021-11-22 at 11 09 35" src="https://user-images.githubusercontent.com/74021414/142852134-0467d8b3-714b-4d13-b65d-ec02359664c9.png">
<img width="1467" alt="Screenshot 2021-11-22 at 11 16 31" src="https://user-images.githubusercontent.com/74021414/142852232-5d6d3051-ae41-4a26-8b90-909ea36d026b.png">

**Comment by bwp91** [comment]
Can you use the mac terminal app to ssh into the hoobs box?

**Comment by wilky761** [comment]
Yes, I can. When I try any of the three addresses listed, I get a blank screen.

<img width="842" alt="Screenshot 2021-11-22 at 11 40 57" src="https://user-images.githubusercontent.com/74021414/142855645-4876501c-618f-4225-b39a-ae67878f1bf9.png">

**Comment by bwp91** [comment]
If you type `sudo hbs log` I believe this is the command to display the latest hoobs log in the terminal. Are there any error messages here?

**Comment by wilky761** [comment]
It comes up "sudo: hbs: command not found

<img width="605" alt="Screenshot 2021-11-22 at 11 46 48" src="https://user-images.githubusercontent.com/74021414/142856347-d1fe8e19-ddd8-4c4c-ba99-70d5c492f801.png">
d"

**Comment by bwp91** [comment]
And if you run this?

```
sudo apt install -y helm hoobs-cli hoobsd hoobs-gui
```

**Comment by wilky761** [comment]
I get "unable to locate package......"

<img width="774" alt="Screenshot 2021-11-22 at 11 51 34" src="https://user-images.githubusercontent.com/74021414/142856998-7a83165c-1f8c-4953-bff9-5ed34d940a45.png">

**Comment by bwp91** [comment]
> If you can SSH into your hoobs box you can try running this command:
> 
> ```
> curl -sk https://dl.hoobs.org/fix | sudo bash - 
> ```

and what output do you get running this original command?

**Comment by wilky761** [comment]
Thanks. I re-ran the original command and seemed to install a new package....I have screenshot the last few lines....


<img width="729" alt="Screenshot 2021-11-22 at 11 57 19" src="https://user-images.githubusercontent.com/74021414/142857802-086cafb6-c3fd-4f85-be3e-895334396cba.png">
..

**Comment by bwp91** [comment]
Can you access the web ui now?

**Comment by wilky761** [comment]
That seems to have worked. My HOOBS box can now be discovered.

Also the original issue of the updating hanging is also now fixed.

Many thanks for your help. Appreciated :)
