### ISSUE TITLE
Reset Hoobs.local password

### ISSUE THREAD

**Issue by hoobsnewb** [hoobs-org/HOOBS#1670]
I am a new Hoobs user and while trying to set it up (Hoobs box starter kit) I relied on an iOS strong password and it didn’t save. Now I am unable to login and I screwed up before I even got started. please help! Thanks!

**Comment by databoy01** [comment]
Go on to your phone settings, in there is an area called passwords, look for “hoobs.local” or the IP address. It will have your login information there (hit the “i” to see the information)

**Comment by hoobsnewb** [comment]
Yeah, that’s how I screwed up I erased it from there. I emailed Hoobs Support and they said to go to http://hoobs.local:9090 but nothing loads for that address. Maybe I have to get a laptop, I’m trying to do everything on my iPad/iPhone

**Comment by databoy01** [comment]
Here are the instructions to reset your password:
1. Login to the HOOBS Box via SSH on your computer.
On MacOS use the Terminal app and type: ssh hoobs@hoobs.local
Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin
On Windows, use Putty with the same credentials as above.
2. After successfully logging in, type this to reset the users file: sudo rm -rf /home/hoobs/.hoobs/etc/access.json
Press enter. There will be no output.
3. Type this to reboot the HOOBS Box: sudo reboot
4. Allow 2-3 minutes for the HOOBS Box to reboot then go to http://hoobs.local and create a new account.
This won't affect your plugins and accessories, only your user.

**Comment by databoy01** [comment]
Remember the login information for SSH

username: hoobs
password: hoobsadmin

**Comment by hoobsnewb** [comment]
Thanks! I have to get my MacBook fixed first.
