### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by kaydee1982** [hoobs-org/HOOBS#1671]
Hi there!
I just moved to Hoobs 4.0.71 as a clean install - so no upgrade from a previous version.
The first problem i ran into was, that the Terminal won't work. It just says Connection refused.

**Comment by kaydee1982** [comment]
Yes, access from the UI is not working.
Connections via ssh work properly. But for me access via the UI is more comfortable :)

**Comment by bwp91** [comment]
I think it would make sense to update to the latest version of hoobs to see if this has been fixed before trying to debug more.

If you use your computer terminal to SSH into your hoobs instance and run this command:

```
curl -sk https://dl.hoobs.org/fix | sudo bash -
```

It should update your system to HOOBS 4.1

**Comment by danielkit83** [comment]
> curl -sk https://dl.hoobs.org/fix | sudo bash -

After running this command , i can't access to the web console. 

hoobs@hoobs:~ $ sudo systemctl status
● hoobs
    State: degraded
     Jobs: 0 queued
   Failed: 1 units
    Since: Thu 1970-01-01 08:00:02 CST; 51 years 11 months ago
   CGroup: /
           ├─user.slice
           │ └─user-1000.slice
           │   ├─user@1000.service
           │   │ └─init.scope
           │   │   ├─950 /lib/systemd/systemd --user
           │   │   └─951 (sd-pam)
           │   └─session-1.scope
           │     ├─ 943 sshd: hoobs [priv]

**Comment by bwp91** [comment]
> > curl -sk https://dl.hoobs.org/fix | sudo bash -
> 
> After running this command , i can't access to the web console.
> 
> hoobs@hoobs:~ $ sudo systemctl status ● hoobs State: degraded Jobs: 0 queued Failed: 1 units Since: Thu 1970-01-01 08:00:02 CST; 51 years 11 months ago CGroup: / ├─user.slice │ └─user-1000.slice │ ├─[user@1000.service](mailto:user@1000.service) │ │ └─init.scope │ │ ├─950 /lib/systemd/systemd --user │ │ └─951 (sd-pam) │ └─session-1.scope │ ├─ 943 sshd: hoobs [priv]

what output do you get from running this?

```
sudo hbs log
```

**Comment by kaydee1982** [comment]
> I think it would make sense to update to the latest version of hoobs to see if this has been fixed before trying to debug more.
> 
> If you use your computer terminal to SSH into your hoobs instance and run this command:
> 
> ```
> curl -sk https://dl.hoobs.org/fix | sudo bash -
> ```
> 
> It should update your system to HOOBS 4.1

That worked! Thank you for your help! :)

**Comment by danielkit83** [comment]
The output is showing command not found....FYI
hoobs@hoobs:~ $ sudo hbs log
sudo: hbs: command not found

Here is the log output during the installation 
Install HOOBS
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:3 http://45.64.22.23/archive.raspberrypi.org/debian buster/main armhf Packages [393 kB]
Err:3 http://45.64.22.23/archive.raspberrypi.org/debian buster/main armhf Packages
  File has unexpected size (392994 != 393009). Mirror sync in progress? [IP: 45.64.22.23 80]
  Hashes of expected file:
   - Filesize:393009 [weak]
   - SHA256:1eb02bfb0cc643ac47a065071aa90ebc78cfa041782bfde6c182cad5f7d2b73c
   - SHA1:e483c301d2a881ee625a69138bd331453067c343 [weak]
   - MD5Sum:2c0b7268bcab68ec5547cc455ce457e7 [weak]
  Release file created at: Wed, 01 Dec 2021 10:18:25 +0000
Fetched 32.6 kB in 2s (20.2 kB/s)
Reading package lists...
E: Failed to fetch http://45.64.22.23/archive.raspberrypi.org/debian/dists/buster/main/binary-armhf/Packages.gz  File has unexpected size (392994 != 393009). Mirror sync in progress? [IP: 45.64.22.23 80]
   Hashes of expected file:
    - Filesize:393009 [weak]
    - SHA256:1eb02bfb0cc643ac47a065071aa90ebc78cfa041782bfde6c182cad5f7d2b73c
    - SHA1:e483c301d2a881ee625a69138bd331453067c343 [weak]
    - MD5Sum:2c0b7268bcab68ec5547cc455ce457e7 [weak]
   Release file created at: Wed, 01 Dec 2021 10:18:25 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
error executing command
Reading package lists...
Building dependency tree...
Reading state information...
nodejs is already the newest version (14.17.2-1nodesource1).
yarn is already the newest version (1.22.5-1).
The following package was automatically installed and is no longer required:
  libbrotli1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package hoobsd
E: Unable to locate package hoobs-cli
E: Unable to locate package hoobs-gui
E: Unable to locate package hbs-vendor

**Comment by bwp91** [comment]
> The output is showing command not found....FYI hoobs@hoobs:~ $ sudo hbs log sudo: hbs: command not found
> 
> Here is the log output during the installation Install HOOBS Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB] Get:3 http://45.64.22.23/archive.raspberrypi.org/debian buster/main armhf Packages [393 kB] Err:3 http://45.64.22.23/archive.raspberrypi.org/debian buster/main armhf Packages File has unexpected size (392994 != 393009). Mirror sync in progress? [IP: 45.64.22.23 80] Hashes of expected file:
> 
> * Filesize:393009 [weak]
> * SHA256:1eb02bfb0cc643ac47a065071aa90ebc78cfa041782bfde6c182cad5f7d2b73c
> * SHA1:e483c301d2a881ee625a69138bd331453067c343 [weak]
> * MD5Sum:2c0b7268bcab68ec5547cc455ce457e7 [weak]
>   Release file created at: Wed, 01 Dec 2021 10:18:25 +0000
>   Fetched 32.6 kB in 2s (20.2 kB/s)
>   Reading package lists...
>   E: Failed to fetch http://45.64.22.23/archive.raspberrypi.org/debian/dists/buster/main/binary-armhf/Packages.gz  File has unexpected size (392994 != 393009). Mirror sync in progress? [IP: 45.64.22.23 80]
>   Hashes of expected file:
>   - Filesize:393009 [weak]
>   - SHA256:1eb02bfb0cc643ac47a065071aa90ebc78cfa041782bfde6c182cad5f7d2b73c
>   - SHA1:e483c301d2a881ee625a69138bd331453067c343 [weak]
>   - MD5Sum:2c0b7268bcab68ec5547cc455ce457e7 [weak]
>   Release file created at: Wed, 01 Dec 2021 10:18:25 +0000
>   E: Some index files failed to download. They have been ignored, or old ones used instead.
>   error executing command
>   Reading package lists...
>   Building dependency tree...
>   Reading state information...
>   nodejs is already the newest version (14.17.2-1nodesource1).
>   yarn is already the newest version (1.22.5-1).
>   The following package was automatically installed and is no longer required:
>   libbrotli1
>   Use 'sudo apt autoremove' to remove it.
>   0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
>   Reading package lists...
>   Building dependency tree...
>   Reading state information...
>   E: Unable to locate package hoobsd
>   E: Unable to locate package hoobs-cli
>   E: Unable to locate package hoobs-gui
>   E: Unable to locate package hbs-vendor

Could you try a full update of the system?

```
sudo apt update
```

```
sudo apt full-upgrade
```

and enter `y` when prompted.

Then try and install the hoobs packages again

```
sudo apt install -y hoobs-cli hoobsd hoobs-gui
```

If at any point you hit an error then don’t try to continue, just share the output here

**Comment by danielkit83** [comment]
hoobs@hoobs:~ $ sudo apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:3 http://45.64.22.23/archive.raspberrypi.org/debian buster/main armhf Packages [393 kB]
Err:3 http://45.64.22.23/archive.raspberrypi.org/debian buster/main armhf Packages
  File has unexpected size (392994 != 393009). Mirror sync in progress? [IP: 45.64.22.23 80]
  Hashes of expected file:
   - Filesize:393009 [weak]
   - SHA256:1eb02bfb0cc643ac47a065071aa90ebc78cfa041782bfde6c182cad5f7d2b73c
   - SHA1:e483c301d2a881ee625a69138bd331453067c343 [weak]
   - MD5Sum:2c0b7268bcab68ec5547cc455ce457e7 [weak]
  Release file created at: Wed, 01 Dec 2021 10:18:25 +0000
Fetched 32.6 kB in 2s (18.7 kB/s)
Reading package lists... Done
N: Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
E: Failed to fetch http://45.64.22.23/archive.raspberrypi.org/debian/dists/buster/main/binary-armhf/Packages.gz  File has unexpected size (392994 != 393009). Mirror sync in progress? [IP: 45.64.22.23 80]
   Hashes of expected file:
    - Filesize:393009 [weak]
    - SHA256:1eb02bfb0cc643ac47a065071aa90ebc78cfa041782bfde6c182cad5f7d2b73c
    - SHA1:e483c301d2a881ee625a69138bd331453067c343 [weak]
    - MD5Sum:2c0b7268bcab68ec5547cc455ce457e7 [weak]
   Release file created at: Wed, 01 Dec 2021 10:18:25 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
hoobs@hoobs:~ $ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libbrotli1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hoobs@hoobs:~ $ sudo apt install -y hoobs-cli hoobsd hoobs-gui
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hoobs-cli
E: Unable to locate package hoobsd
E: Unable to locate package hoobs-gui

**Comment by danielkit83** [comment]
Unfortunately, it still can't install the hoobs

**Comment by danielkit83** [comment]
I am using the image that downloaded from hoobs site. The version is 4.0.31. Then try to update the hoobs with you suggested script..

**Comment by bwp91** [comment]
> I am using the image that downloaded from hoobs site. The version is 4.0.31. Then try to update the hoobs with you suggested script..

If you’re willing to, i think a quick solution would be to download the latest hoobs image and re flash your system…

**Comment by danielkit83** [comment]
> > I am using the image that downloaded from hoobs site. The version is 4.0.31. Then try to update the hoobs with you suggested script..
> 
> If you’re willing to, i think a quick solution would be to download the latest hoobs image and re flash your system…

In the site, the latest image is 4.0.31. It is not 4.1 version.....i don't how to download the latest image from the hoobs site

**Comment by bwp91** [comment]
Are you running the commands from the hoobs ui terminal or a terminal app on your computer?

**Comment by danielkit83** [comment]
> Are you running the commands from the hoobs ui terminal or a terminal app on your computer?

I am using the terminal app on my computer.

**Comment by bwp91** [comment]
> > Are you running the commands from the hoobs ui terminal or a terminal app on your computer?
> 
> I am using the terminal app on my computer.

And are you accessing via direct IP or “hoobs.local” as host name?

**Comment by danielkit83** [comment]
> > > Are you running the commands from the hoobs ui terminal or a terminal app on your computer?
> > 
> > 
> > I am using the terminal app on my computer.
> 
> And are you accessing via direct IP or “hoobs.local” as host name?

direct ip

**Comment by bwp91** [comment]
> > > > Are you running the commands from the hoobs ui terminal or a terminal app on your computer?
> > > 
> > > 
> > > I am using the terminal app on my computer.
> > 
> > 
> > And are you accessing via direct IP or “hoobs.local” as host name?
> 
> direct ip

What happens if you run this?

```
wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
```

**Comment by danielkit83** [comment]
> wget -qO- https://dl.hoobs.org/stable | sudo -E bash -

hoobs@hoobs:~ $ wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
[sudo] password for hoobs: 
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:3 http://45.64.22.23/archive.raspberrypi.org/debian buster/main armhf Packages [393 kB]
Err:3 http://45.64.22.23/archive.raspberrypi.org/debian buster/main armhf Packages
  File has unexpected size (392994 != 393009). Mirror sync in progress? [IP: 45.64.22.23 80]
  Hashes of expected file:
   - Filesize:393009 [weak]
   - SHA256:1eb02bfb0cc643ac47a065071aa90ebc78cfa041782bfde6c182cad5f7d2b73c
   - SHA1:e483c301d2a881ee625a69138bd331453067c343 [weak]
   - MD5Sum:2c0b7268bcab68ec5547cc455ce457e7 [weak]
  Release file created at: Wed, 01 Dec 2021 10:18:25 +0000
Fetched 32.6 kB in 1s (22.3 kB/s)
Reading package lists... Done
N: Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
E: Failed to fetch http://45.64.22.23/archive.raspberrypi.org/debian/dists/buster/main/binary-armhf/Packages.gz  File has unexpected size (392994 != 393009). Mirror sync in progress? [IP: 45.64.22.23 80]
   Hashes of expected file:
    - Filesize:393009 [weak]
    - SHA256:1eb02bfb0cc643ac47a065071aa90ebc78cfa041782bfde6c182cad5f7d2b73c
    - SHA1:e483c301d2a881ee625a69138bd331453067c343 [weak]
    - MD5Sum:2c0b7268bcab68ec5547cc455ce457e7 [weak]
   Release file created at: Wed, 01 Dec 2021 10:18:25 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
error executing command

**Comment by bwp91** [comment]
In this case will need one of the hoobs support to help you. i’ve tried what i can :)

**Comment by danielkit83** [comment]
> In this case will need one of the hoobs support to help you. i’ve tried what i can :)

Thanks for your support. How can I contact the hoobs support?

**Comment by mkellsy** [comment]
The OP’s (kaydee1982) issue has been resolved.

@danielkit83 your issue is different. Are you using a HOOBS Box? I am closing this issue, please send an email to info@hoobs.com.
