### ISSUE TITLE
Hoobs.local never works

### ISSUE THREAD

**Issue by databoy01** [hoobs-org/HOOBS#1672]
Hello, since upgrading to Hoobs 4, I can never get to my hoobs device by typing in hoobs.local.  I can access it sometimes via the IP address and via terminal on my PC.  Seems to be a bug that affects that, as the browser times out. 

I’ve also restarted fresh to see if that would fix my issue (meaning I flashed the card and started over brand new). 

All updates are performed and it doesn’t show anything needed

version: 4.1.17 
Node version: 16.13.0
Homebridge version : 1.3.6

**Comment by mkellsy** [comment]
The .local address is Bonjour or mDNS. Some routers and computers don’t reliably support this. Have you tried just http://hoobs

You can also try the desktop app. The app scans your network and connects directly.
https://support.hoobs.org/downloads/desktop

**Comment by databoy01** [comment]
Thanks. Yeah that doesn't work either.  It is a new issue for me. As that always worked before I upgraded to the newest software on the Hoobs. No changes to my network so I don’t think its my router.

**Comment by mkellsy** [comment]
HOOBS is an app. We don’t actually have anything to do with Bonjour. We install Avachi on our image.

you can see if Avahi is running with this command.

systemctl status avahi-daemon

**Comment by MacFlagg** [comment]
I am having the same issue. When I try to login to HOOBS via HOOBS.local all I get is a blank webpage.

I’ve tried on my iPhone 12 Pro Max running iOS 15.2, my iPad Pro running iPadOS 15.2, and on my MacBook Pro. I’ve tried using Safari, Chrome, and Firefox.

**Comment by databoy01** [comment]
Unfortunately, I’ve come to realize these GitHub issue forum for HOOBS are useless.  This is the second issue Ive asked for guidance on.  No one that actually works for HOOBS provides support.  They create it and abandon any one that has issues.  To say I am disappointed, would be an understatement.  Not even sure why they created this GitHub to be truthful.  As numerous questions are listed and nothing ever is helped. Ive assisted people where I can.  But if the software is not behaving correctly. I can’t do anything about it and you would think those that made it would…

**Comment by MacFlagg** [comment]
Databoy01,

I emailed HOOBS directly about this issue and they emailed back with these instructions:

Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, execute the following commands:

sudo apt update

sudo apt install hoobsd

sudo npm install -g @hoobs/migration

cd ~/ && sudo hbs-migrate

Follow the onscreen instructions, Select HOOBS and DO NOT setup as separate bridges or else you will need to redo your setup

Terminal will disconnect from the box and after 3 mins - SSH back into the Box and paste below command to see the progress of the migration

sudo journalctl -o cat -n 500 -f -u migrate.service

It will take 5 to 10 mins. Wait for the process to complete. 

Let me know if it worked for you

**Comment by MacFlagg** [comment]
Those instructions failed for me, so they gave me these instructions:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
Download the App BalenaEtcher - https://www.balena.io/etcher/
Download the HOOBS Image - https://support.hoobs.org/downloads/image?platform=armhf
From the download folder - Load the .zip file in the BalenaEtcher. If you are using a Mac - the file is automatically decompressed and moved to the thrash bin. Restore the file to your download folder
Click on flash

Once the process is over - insert the card back into the board. Close the box with the screws. Plug the ethernet cable and then power the device.
