### ISSUE TITLE
Hoobs won't install any plugins

### ISSUE THREAD

**Issue by kk6891** [hoobs-org/HOOBS#1674]
**Description**
Attempt to install any plugin immediately results in "Unable to install plugin. Please try again later". It does create an associated bridge, though.
It happens to every single plugin I've tried and has been going on for days. I did a factory reset 4 times, but the issue persists.
**Version**
Please include the version of HOOBS you are using.
4.0.109
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
None. This issue happens even after factory reset, with 0 plugins or bridges installed.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
I don't see the config anywhere.

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
02/12/2021, 13:41:46Hue Bridge starting

**Additional context**
Above is my whole log, after another fresh factory reset.

**Comment by bwp91** [comment]
I think it would make sense to update to the latest version of hoobs to see if this has been fixed before trying to debug more.

Use your computer terminal to SSH into your hoobs instance with the host name as the IP of the box and the username/password combination hoobs/hoobsadmin. Then run this command:

```
curl -sk https://dl.hoobs.org/fix | sudo bash -
```

It should update your system to HOOBS 4.1

**Comment by bwp91** [comment]
Have you changed the ssh access password? This is different to the username and password used for accessing the hoobs ui

**Comment by kk6891** [comment]
You're right - I made two mistakes in one go - wrong username/password and not using user@IP address in ssh. It's updating now. I'll post here if it resolves the issue.

Thanks for the help so far!

**Comment by kk6891** [comment]
Update solved the issue, thanks a lot!
