### ISSUE TITLE
Persist and Accessories folder location?

### ISSUE THREAD

**Issue by kbardai** [hoobs-org/HOOBS#1676]
Hey,

I have hoobs 4 installed on ubuntu...where can I find the persist/accessories files folder locations for the relevant bridge that it is running under?

Thanks

**Comment by mkellsy** [comment]
You can view and clear the cache from the Bridges screen in the UI. Each bridge has its own cache. In /var/lib/hoobs

**Comment by kbardai** [comment]
Perfect, thanks, I was looking for the actual files so I can edit them to remove one cached accessory from the plugin b/c I removed that item and still shows up in HomeKit....from my understanding, doing a clear cache from the Bridges screen will require me to re-setup the accessories under that bridge/platform.

**Comment by kbardai** [comment]
oh my, I did not realize that HOOBS 4 UI had the ability to remove just one accessory from the cache list!

Going to the bridge -> cache button -> delete the specific accessory

Worked like a charm!

Thanks
