### ISSUE TITLE
Hoobs Service wont start, all files missing

### ISSUE THREAD

**Issue by currylee** [hoobs-org/HOOBS#1677]
**Description**
Hoobs Service wont start
You must first enable the HOOBS service
/home/hoobs/etc/systemd/system/hoobs.service: No such file or directory
Can't access any directory beyond home

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
cat: /home/hoobs/.hoobs/etc/config.json: No such file or directory

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
What version are you on?
And in Linux the services are not in /home/…
They are in /etc/systemd/system

**Comment by currylee** [comment]
I'm on 4.1.17.
Thanks for letting me know the pathing. I'm able to restart the service now and everything is working.
I feel dumb lol
