### ISSUE TITLE
Hoobs /RPi crashed on start

### ISSUE THREAD

**Issue by neji82** [hoobs-org/HOOBS#1678]
**Description**
Hi, I wanted to use hoops after some time again, so I plugged the RPi in and started the web portal. After adding a plugin the pi wasn't responding anymore so I turned it off and on again. From there on I cannot reach it anymore. Not via hoobs.local (or http://hoobs etc) nor via ssh. It also doesn't appear in my router as a device.
So I redownloaded hoobs4 (before it was version 3) and tried it again, with the same issues.

Then I plugged an cdmi cable in to see if I can see any errors, since ssh isn't working. On the screen there is a short message, then the screen goes black and after some seconds the message comes again.

The error message is : 

hub 1-1:1.0: hub_ext_port_status failed (err = -71)
usb 1-1: Failed to suspend device, error -71

I do not have any usb devices connected...just the pi (3b+) with an sd card, power cord and network cable.

Any suggestions?

**Version**
Please include the version of HOOBS you are using.
-4.0.31

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
fresh install

**Comment by BobbySlope** [comment]
The error message indicates an USB Port error. https://www.reddit.com/r/linuxquestions/comments/ox4zxk/usbdevices_randomly_fail_to_connect_after_some/

Do you have any usb pereferals attached?
