### ISSUE TITLE
Find a Way to Transition from Plugin Install to Configuration

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#168]
After installing a new plugin, it's not obvious to the user what they need to do. It should pop-up the add accessory window or at least give them a notification asking them to configure the plugin.

**Comment by mkellsy** [comment]
Adding a popup, or changing where the config file is saved would require an almost entire rewrite. It would also require me to scan the plugin js files to look for the words registerPlatform or registerAccessory to find out what type of plugin it is.

Both HOOBS 3.0 and UI-X depends on the config.schema files to do this. In UI-X if there is a schema file is present it will show a configure link, which creates a popup. The configure link is there in 3.0 too, it takes you to the config screen anchored to the plugin config.

I could redirect the user to the config screen automatically after a plugin is installed, but I can't do it if there is no schema file. If there is an accessory config, I could redirect to the config screen and show the add accessory dialog.

Adding a platform placeholder works great for platform plugins, not good for accessory plugins. Without the schema files, I would have to scan the files to determine this.

I have been thinking of a way to make this more obvious for users. For now I am just goint to redirect to the config screen after a plugin install.

**Comment by mkellsy** [comment]
I redirect to the config after a plugin install for now.

In 3.0.0-beta.60

**Comment by mkellsy** [comment]
I got the transition working. I load the plugin in the API and pass a fake homebridge instance to it. When the plugin calls registerPlatform() I mark it as a platform and registerAccessory() mark it as an accessory. If the plugin calls both, I mark it both and then load it as a platform.

After this I unload the plugin. This process is fault tolerant so it can't bing down the API.

I add platform JSON with the plugin mapping so it will show up in the config screen. and redirect to the JSON or form if there is a schema.

For accessories, I redirect to the config screen and I show the add accessory dialog. If the accessory doesn't have a schema, they can simply add a custom accessory, which will give them the capability to add the JSON.

Done in 3.0.0-beta.60
