### ISSUE TITLE
Unable to configure NEST cam and thermostat plugins

### ISSUE THREAD

**Issue by jeremyphelps** [hoobs-org/HOOBS#1680]
Hi all,  newbie to HOOBS here - thanks for a great product, at last, I can extend my Homekit devices!

I have successfully installed the TUYA plugin but am having issues configuring the NEST certified plugins.  I install the plugin, click 'link account', it then says "Login to Nest - First you will need to login to Google and get a one time access code. This will open a new dialog."

Once I click login, I have a white page/box, the NEST & HOOBS logos at the top and nothing happens.  

I'm pretty sure at this point I am meant to login to Google to obtain my one time access code.  I've tried reinstalling the plugin, deactivating popup blockers and different browsers and it's all the same.

**Version**
Please include the version of HOOBS you are using - Version 4.0.71

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- Custom Install

**If this is a custom install, what's your operating system?**
- macOS Monterey.

**List your plugins**
- Tuya web bridge
- Nest Cam Bridge (not able to configure)
- Nest Thermostat Bridge (not able to configure)

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

- tried looking - where can I find this? sorry

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

Is this what you need?

02/12/2021, 17:38:16Nest Cam Bridge starting
02/12/2021, 17:38:25Nest Cam BridgeLoaded plugin 'homebridge-nest-cam'
02/12/2021, 17:38:25Nest Cam BridgeLoading 1 platforms...
02/12/2021, 17:38:25Nest Cam BridgeNest-camERRORYou must provide a refreshToken or googleAuth object in config.json. Please see README.md for instructions
02/12/2021, 17:38:25Nest Cam BridgeNest-camERRORUnable to retrieve access token.
02/12/2021, 17:38:25Nest Cam BridgeBridge is running on port 51826.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Google uses popups in their auth. Disable your popup blocker or add an exception.
