### ISSUE TITLE
Cannot locate homekit QR code after installing

### ISSUE THREAD

**Issue by Teens444** [hoobs-org/HOOBS#1682]
**Description**
I installed hoobs and got it on the network both wifi and then wired.  The videos show a QR code to scan to add it to homekit when first logging in.  My interface does not have that anywhere.  How can I add hoobs to homekit?

**Version**
4.1.17

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes

**Pervious version**
unknown

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?** No
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.

- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
none yet

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by dsgomez1** [comment]
I'm also having the same issue

**Comment by dsgomez1** [comment]
Looks like you do not need to do that anymore. I was able to download plugins and then scan them in Home kit

**Comment by Teens444** [comment]
Wouldnt work for me.  Now I've reset it and can't get back into it at all.  Support is trying to help me with it.

**Comment by mkellsy** [comment]
HOOBS uses multiple bridges.  Go to the bridges screen to see your bridge(s) QR codes.
There also is a QR Icon on the desktop. Click It.
