### ISSUE TITLE
Hoobs Box - NIC Link randomly failing

### ISSUE THREAD

**Issue by DGAZ40** [hoobs-org/HOOBS#1684]
**Description**
Hoobs box purchased new a couple months ago.
Worked great for the first month but now it is continuing to loose its NIC link.  Generally what happens is I notice the device is offline, go check on it and see that the red light inside is on but the link lights are off.  After power cycling result is same, red light under vent is on but no link lights.  If I wait about 30 seconds after power cycle link will come up momentarily, then goes back off.  If I leave the device unplugged for a while eventually it usually comes back online for some period of time, sometimes 1 hour, a day, or the last time it was about a week.  Today after leaving disconnected from power for several hours it still is not coming back online.  Same result, no link light.   So overall it is randomly working and failing.  I have tried connecting to three different switches as well as directly to a pc, no change in result in any of those cases.
Please advise.

**Version**
I believe I am on v4 but I'm not 100% on the version as I cannot get logged into the unit currently.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No
Not recently.

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Ring and MyQ

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
Device is completely offline, so I'm unable to download the config.

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Is it connected via ethernet or wifi? Have you tried another network cable?

**Comment by DGAZ40** [comment]
Ethernet, and yes I have tried several different cables.   I’m confident it
is not a layer 1 or layer 2 issue external to the box.  Appears to be a
hardware or software issue with the box.

**Comment by askovi** [comment]
The microSD card could be corrupted. Here's how you can reflash it:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:

		Download the App BalenaEtcher - https://www.balena.io/etcher/
		Download the HOOBS Image - https://support.hoobs.org/downloads/image?platform=armhf
		From the download folder - Load the .zip file in the BalenaEtcher. If you are using a Mac - the file is automatically decompressed and moved to the thrash bin. Restore the file to your download folder
		Click on flash

Once the process is over - insert the card back into the board. Close the box with the screws. Plug the ethernet cable and then power the device.

**Comment by DGAZ40** [comment]
I’ve done this but behavior is the same.  I connected a monitor to the HDMI
port, when the unit is locked up there is no video output on the HDMI at
the same time that link lights and connectivity fail.  Then if I reboot it,
usually I can get it back online without too much fuss, but this is
happening several times per week now.  I believe the raspberry pie is
failing.  What is next step, can I get a warranty replacement?

**Comment by askovi** [comment]
Please send an email to support@hoobs.com with your order number to begin the RMA process.
