### ISSUE TITLE
Cannot Connect to HOOBS

### ISSUE THREAD

**Issue by sim006** [hoobs-org/HOOBS#1688]
I used my HOOBS Box for some time but I disconnected it when I had some network issues. I am trying to reconnect and set things back up and I cannot connect back to HOOBS no matter what I do. Some details and things I have tried:

- connecting using http://hoobs.local. Results: ERR_CONNECTION_REFUSED
- I looked up the ip address using my routes and tried to connect using this (port unknown, tried 9090). Using the app, invalid ip address. Browser, ERR_CONNECTION_REFUSED
- This is the weird one: I tried connecting using ssh through terminal, it asks for a password, 'hoobsadmin' entered, then it says "Connection closed by 192.168.1.233 port 22". No idea what to do from here.
- I tried connecting with the ip address and port 22, I get ERR_UNSAFE_PORT

Any suggestions? I am happy to reset the box, if needed, I would just like to get it working again, the box was not cheap.

**Comment by askovi** [comment]
Try reflashing your microSD card.

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:

Download the App BalenaEtcher - https://www.balena.io/etcher/
Download the HOOBS Image - https://support.hoobs.org/downloads/image?platform=armhf
From the download folder - Load the .zip file in the BalenaEtcher. If you are using a Mac - the file is automatically decompressed and moved to the thrash bin. Restore the file to your download folder
Click on flash

Once the process is over - insert the card back into the board. Close the box with the screws. Plug the ethernet cable and then power the device.

**Comment by sim006** [comment]
Thanks. I will give it a try tomorrow.
