### ISSUE TITLE
How to connect a Könighaus Thermostat in HOOBS

### ISSUE THREAD

**Issue by Pruefer001** [hoobs-org/HOOBS#1689]
I am new in this forum , an not sure if I use the correct platform to ask a question.

My question would be how I can integrate a Thermostat from Königshaus . ere the link for the device.

I could add the device through the Tuya plugin, but not sure what I need to use to adjust the correct parameters and lines int he program to see the correct way in the Home kit system.

https://www.koenighaus-infrarot.de/smart-home-steckdosenthermostat-steuerbar-mit-app-fuer-ios-und-android/

**Comment by BobbySlope** [comment]
You need to get in touch with the tuya plugin developer, we dont maintain the plugins. 

You can open an issue there:

https://github.com/tuya/tuya-homebridge/issues
