### ISSUE TITLE
Please certify Homebridge Tplink Smarthome

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#169]
[https://www.npmjs.com/package/homebridge-tplink-smarthome]( https://www.npmjs.com/package/homebridge-tplink-smarthome)

Plugin respects all requirements for certification.
It has auto device discovery and only config needed is this:
`"platforms": [{
  "platform": "TplinkSmarthome",
  "name": "TplinkSmarthome"
}]`
Please make it add that automatically to config file when installing.

**Comment by mkellsy** [comment]
Merging with the plugin roadmap
