### ISSUE TITLE
New user can't install any plug-ins

### ISSUE THREAD

**Issue by Danielmoore65** [hoobs-org/HOOBS#1691]
Installed Hoobs today on RPi4. Unable to install any plug-ins with the error message 'Unable to install plugin. Please try again'. tried numerous different plug-ins, and have tried to access the terminal from different pc's.

**Version**
4.0.71

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
No idea. I am using a RPi 4 8GB. Micro SD flashed using 'BalenaEtcher'.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Have tried; Meross, VERA, Mitsubishi A/C... all with the same result.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
I cannot find this, have the names changed with the update?

```
POST CONFIG HERE
```

**Post your log**
My log is empty.

```
POST LOG HERE
```

**Additional context**

I have re-booted the Pi, I have uninstalled and re-installed HOOBS on my PC, tried installing HOOBS on a different PC. Keep getting the same issue. I'm not very computer tech savvy, so any assistance in plain speak would be greatly appreciated.
[pug-ins.docx](https://github.com/hoobs-org/HOOBS/files/7666348/pug-ins.docx)

**Comment by BobbySlope** [comment]
Run this command to fix the issues

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3
