### ISSUE TITLE
'command not found' response

### ISSUE THREAD

**Issue by craney-tom** [hoobs-org/HOOBS#1692]
**Description**
After connecting to HOOBS device, all commands return with command not found

**Version**
Error began mid way through upgrade process, so not sure what version is currently loaded 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No
-[x] Trying

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

POST CONFIG HERE
hoobs@hoobs:~ $ cat ~/.hoobs/etc/config.json
-bash: cat: command not found

**Additional context**
Purchased nearly a year ago, then decided to move. Didn't seem to be any point setting up HOOBS until settled into new home. Now I'm here and ready to go. Plugged in device, went to the web interface and saw there was an update. Initiated update and got caught up in the migration to 4.0 failure. I was able to ssh into the device and I began the process as described on the HOOBS.org site. Got to this command: 
> sudo apt install -y hoobsd hoobs-cli hoobs-gui helm 

And that's when things started going sideways. It looked like everything was going as expected until I started getting: 
> dpkg: error while cleaning up:
 unable to remove newly-extracted version of '/usr/lib/hoobsd/node_modules/homebridge/node_modules/fs-extra/lib/copy-sync/copy-sync.js': Read-only file system

The next step would have been:

> E: Sub-process /usr/bin/dpkg returned an error code (2)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - pkgDPkgPM::Go (30: Read-only file system)
E: Problem executing scripts DPkg::Post-Invoke '/usr/bin/test -e /usr/share/dbus-1/system-services/org.freedesktop.PackageKit.service && /usr/bin/test -S /var/run/dbus/system_bus_socket && /usr/bin/gdbus call --system --dest org.freedesktop.PackageKit --object-path /org/freedesktop/PackageKit --timeout 4 --method org.freedesktop.PackageKit.StateHasChanged cache-update > /dev/null; /bin/echo > /dev/null'
E: Sub-process returned an error code
hoobs@hoobs:~ $ sudo npm install -g @hoobs/migration
Bus error

**Comment by BobbySlope** [comment]
Try to rin the fix command to update you to the latest system/hoobs/plugins

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3
