### ISSUE TITLE
API Error Message for Homebridge-Hue 

### ISSUE THREAD

**Issue by Toslink6124** [hoobs-org/HOOBS#1693]
I'm running HOOBS v4.0 running on a HOOBS Raspberry Pi kit, running Homebridge version 1.3.6. When I load the most current version of Homebridge Hue (v 0.13.3), the terminal replies state that it's not compatible with Homebridge v 1.3.6 and that it needs Homebridge 1.3.8, which I cannot load, as the Homebridge version is embedded within HOOBS, and I'm running the most current version.   

So, to resolve, I downgraded to Homebridge Hue version 0.12.26 (the last issue under version 12), and that seems to have resolved the conflicts I'd originally received. However,  as you can see from the terminal responses below, there's a mismatch between the Homebridge and the Hue Bridge in an API level, preventing communication. 

The Hue plug-in is the first I've loaded onto the HOOBS box.

Log is as follows....

12/7/2021, 3:02:32 PMHue Bridge starting
12/7/2021, 3:02:41 PMHue BridgeLoaded plugin 'homebridge-hue'
12/7/2021, 3:02:41 PMHue BridgeLoading 1 platforms...
12/7/2021, 3:02:41 PMHue BridgeHue Testhomebridge-hue v0.12.26, node v16.13.1, homebridge v1.3.6
12/7/2021, 3:02:41 PMHue BridgeHue Testsearching bridges and gateways
12/7/2021, 3:02:46 PMHue BridgeHue TestPhilips hue: Signify Netherlands B.V. BSB002 bridge v1948086000, api v1.48.0
12/7/2021, 3:02:46 PMHue BridgeHue TestWARNINGPhilips hue: warning: not using recommended Hue bridge api version 1.42.0
12/7/2021, 3:02:46 PMHue BridgeHue TestPhilips hue: 1 accessories
12/7/2021, 3:02:46 PMHue BridgeHue Testmasked debug info dumped to /var/lib/hoobs/huebridge/homebridge-hue.json.gz
12/7/2021, 3:02:46 PMHue BridgeHue TestPhilips hue: 2 services
12/7/2021, 3:02:46 PMHue BridgeBridge is running on port 51826.
12/7/2021, 3:02:46 PMHue BridgeHue TestWARNINGwarning: latest version: homebridge-hue v0.13.30

Can anyone offer guidance on where I may be going wrong with the API call out here? It because the Philips Hue Bridge runs a different API than the one used by the Homebridge Hue plug-in? I ask because I do not see the scenes I created in the Hue app exposed within the HomeKit UI, even though I have checked the "Scenes" box with the Configuration section.

**Comment by BobbySlope** [comment]
Run this command

This will bring you the latest version of hoobs and the plugin

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3
