### ISSUE TITLE
CLI Upgrade not working

### ISSUE THREAD

**Issue by afulki** [hoobs-org/HOOBS#1694]
application | distribution | package_manager | version | latest  | upgraded | init_system | running
---------------------------------------------------------------------------------------------------
cli         | raspbian     | apt-get         | 4.0.34  | 4.0.34  | true     |             |
gui         | raspbian     | apt-get         | 4.0.67  | 4.0.67  | true     |             |
hoobsd      | raspbian     | apt-get         | 4.0.71  | 4.0.71  | true     | systemd     | true
node        | raspbian     | apt-get         | 14.17.2 | 14.18.2 | false    |             |

hoobs@hoobs:~ $ sudo hbs system upgrade
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x buster main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x buster main
deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main
deb [signed-by=/usr/share/keyrings/hoobs.gpg] https://dl.hoobs.org/debian/ stable main
Get:1 https://dl.hoobs.org/debian stable InRelease [3,032 B]
Get:2 https://deb.nodesource.com/node_16.x buster InRelease [4,584 B]
Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Hit:4 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:5 http://archive.raspberrypi.org/debian buster InRelease
Get:6 https://dl.hoobs.org/debian stable/main armhf Packages [1,929 B]
Get:7 https://dl.yarnpkg.com/debian stable/main armhf Packages [10.4 kB]
Get:8 https://deb.nodesource.com/node_16.x buster/main armhf Packages [778 B]
Get:9 https://dl.yarnpkg.com/debian stable/main all Packages [10.4 kB]
Fetched 48.2 kB in 1s (33.6 kB/s)
Reading package lists... Done
 ERROR  TypeError: dest.on is not a function
    at WriteStream.Readable.pipe (internal/streams/readable.js:652:8)
    at Socket.<anonymous> (/usr/src/system/index.ts:167:32)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by BobbySlope** [comment]
Run this command

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3
