### ISSUE TITLE
System update files

### ISSUE THREAD

**Issue by Johan8012** [hoobs-org/HOOBS#1695]
Hello!
I updated manually to 4.1.17.
The update IO says there are updates available.
I have run the fix twice, nothing happens.
What to do?

ase Files: 10.3+rpi1+deb10u11
Available
Libc6 Dbg: 2.28-10+rpt2+rpi1
Available
Libc6 Dev: 2.28-10+rpt2+rpi1
Available
Libc Dev Bin: 2.28-10+rpt2+rpi1
Available
Linux Libc Dev: 1:1.20211201~buster-1
Available
Libc6: 2.28-10+rpt2+rpi1
Available
Libc Bin: 2.28-10+rpt2+rpi1
Available
Debconf I18n: 1.5.71+deb10u1
Available
Python3 Debconf: 1.5.71+deb10u1
Available
Debconf Utils: 1.5.71+deb10u1
Available
Debconf: 1.5.71+deb10u1
Available
Systemd Sysv: 241-7~deb10u8+rpi1
Available
Libpam Systemd: 241-7~deb10u8+rpi1
Available
Libsystemd0: 241-7~deb10u8+rpi1
Available
Systemd: 241-7~deb10u8+rpi1
Available
Bluez: 5.50-1.2~deb10u2+rpt1
Available
Udev: 241-7~deb10u8+rpi1
Available
Libudev1: 241-7~deb10u8+rpi1
Available
Libasound2: 1.1.8-1+rpt2
Available
Libasound2 Data: 1.1.8-1+rpt2
Available
Ntfs 3g: 1:2017.3.23AR.3-3+deb10u1
Available
Libntfs 3g883: 1:2017.3.23AR.3-3+deb10u1
Available
Tzdata: 2021a-0+deb10u3
Available
Bind9 Host: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libbind9 161: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libisccfg163: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libisccc161: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libssl1.1: 1.1.1d-0+deb10u7
Available
Libdns1104: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libisc1100: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libgssapi Krb5 2: 1.17-3+deb10u3
Available
Libkrb5 3: 1.17-3+deb10u3
Available
Libkrb5support0: 1.17-3+deb10u3
Available
Libk5crypto3: 1.17-3+deb10u3
Available
Liblwres161: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libc L10n: 2.28-10+rpt2+rpi1
Available
Locales: 2.28-10+rpt2+rpi1
Available
Distro Info Data: 0.41+deb10u4
Available
Firmware Atheros: 1:20190114-2+rpt4
Available
Firmware Brcm80211: 1:20190114-2+rpt4
Available
Firmware Libertas: 1:20190114-2+rpt4
Available
Firmware Misc Nonfree: 1:20190114-2+rpt4
Available
Firmware Realtek: 1:20190114-2+rpt4
Available
Libicu Dev: 63.1-6+deb10u2
Available
Icu Devtools: 63.1-6+deb10u2
Available
Libicu63: 63.1-6+deb10u2
Available
Libbluetooth3: 5.50-1.2~deb10u2+rpt1
Available
Libc Ares2: 1.14.0-1+deb10u1
Available
Libisc Export1100: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libdns Export1104: 1:9.11.5.P4+dfsg-5.1+deb10u6
Available
Libnftnl11: 1.1.7-1~bpo10+1~0
Available
Libraspberrypi Doc: 1:1.20211201~buster-1
Available
Libraspberrypi Dev: 1:1.20211201~buster-1
Available
Raspberrypi Kernel: 1:1.20211201~buster-1
Available
Libraspberrypi Bin: 1:1.20211201~buster-1
Available
Libraspberrypi0: 1:1.20211201~buster-1
Available
Raspberrypi Bootloader: 1:1.20211201~buster-1
Available
Multiarch Support: 2.28-10+rpt2+rpi1
Available
Openssl: 1.1.1d-0+deb10u7
Available
Raspberrypi Sys Mods: 20211005
Available
Pi Bluetooth: 0.1.18
Available
Psmisc: 23.2-1+deb10u1
Available
Raspberrypi Net Mods: 1.3.2
Available
Rpi Eeprom: 13.1-1~buster
Available

**Comment by BobbySlope** [comment]
Run the fix command:

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3

This brings your device to the latest version hoobs and system
