### ISSUE TITLE
Extremley detailed logs - spam, can't see important things

### ISSUE THREAD

**Issue by breather74** [hoobs-org/HOOBS#1696]
**Description**
I am seeing an extremely detailed log which is not what I would see before and this is causing my logs to be flooded with irrelevant things and I am not able to see older more important events.
**Version**
Please include the version of HOOBS you are using.
4.1.17 
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ Y] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
Not Sure
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ Y] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [Y ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
<img width="233" alt="Screen Shot 2021-12-08 at 11 58 15 PM" src="https://user-images.githubusercontent.com/89380644/145196949-25d67e2f-a0e5-4e17-9966-d85c61c14392.png">

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```
<img width="1464" alt="Screen Shot 2021-12-08 at 11 54 18 PM" src="https://user-images.githubusercontent.com/89380644/145197016-93f10c58-fca1-4623-8315-46756f6a1009.png">

**Additional context**

Have recently installed soma plugin and the problem has occurred since then. I am inclined to think it is the plugin that is causing the issue but my broadlink plugin is also displaying an irrelevant keep-alive signal message in the logs which worked fine before hand.

One thing I did before noticing this issue was that I tried to install the soma plugin manually using ssh. In case I did something wrong I took a copy of the logs of that which can be found below. TO BE CLEAR this logs I have provided didn't result in the plugin installing and displaying so I installed through the hoobs gui (maybe something I did here caused the issue) :

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs
* http://hoobs.local
* http://192.168.1.116

HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
hoobs@hoobs:~ $ sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
[sudo] password for hoobs: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bluez is already the newest version (5.50-1.2~deb10u2+rpt1).
bluez set to manually installed.
The following package was automatically installed and is no longer required:
  libbrotli1
Use 'sudo apt autoremove' to remove it.
Suggested packages:
  bluez-cups bluez-obexd
The following NEW packages will be installed:
  bluetooth libbluetooth-dev libudev-dev
0 upgraded, 3 newly installed, 0 to remove and 8 not upgraded.
Need to get 344 kB of archives.
After this operation, 797 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf bluetooth all 5.50-1.2~deb10u2+rpt1 [43.5 kB]
Get:2 http://wlglam.fsmg.org.nz/raspbian/raspbian buster/main armhf libudev-dev armhf 241-7~deb10u8+rpi1 [110 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf libbluetooth-dev armhf 5.50-1.2~deb10u2+rpt1 [190 kB]
Fetched 344 kB in 2s (174 kB/s)            
Selecting previously unselected package bluetooth.
(Reading database ... 72248 files and directories currently installed.)
Preparing to unpack .../bluetooth_5.50-1.2~deb10u2+rpt1_all.deb ...
Unpacking bluetooth (5.50-1.2~deb10u2+rpt1) ...
Selecting previously unselected package libbluetooth-dev:armhf.
Preparing to unpack .../libbluetooth-dev_5.50-1.2~deb10u2+rpt1_armhf.deb ...
Unpacking libbluetooth-dev:armhf (5.50-1.2~deb10u2+rpt1) ...
Selecting previously unselected package libudev-dev:armhf.
Preparing to unpack .../libudev-dev_241-7~deb10u8+rpi1_armhf.deb ...
Unpacking libudev-dev:armhf (241-7~deb10u8+rpi1) ...
Setting up libbluetooth-dev:armhf (5.50-1.2~deb10u2+rpt1) ...
Setting up libudev-dev:armhf (241-7~deb10u8+rpi1) ...
Setting up bluetooth (5.50-1.2~deb10u2+rpt1) ...
Processing triggers for man-db (2.8.5-2) ...
hoobs@hoobs:~ $ sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
hoobs@hoobs:~ $ npm install -g homebridge-soma
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge-soma@1.0.9',
npm WARN EBADENGINE   required: { homebridge: '^1.3.8', node: '^16.13.1', soma: '2.2.10' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge-lib@5.1.21',
npm WARN EBADENGINE   required: { homebridge: '^1.3.8', node: '^16.13.1' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
npm notice 
npm notice New minor version of npm available! 8.1.0 -> 8.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.2.0
npm notice Run npm install -g npm@8.2.0 to update!
npm notice 
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/lib/node_modules/homebridge-soma
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/homebridge-soma'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/homebridge-soma'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/lib/node_modules/homebridge-soma'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-12-07T07_05_00_104Z-debug.log
hoobs@hoobs:~ $ npm install -g npm@8.2.0
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/npm
npm ERR! dest /usr/lib/node_modules/.npm-qUIFSsiV
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/npm' -> '/usr/lib/node_modules/.npm-qUIFSsiV'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/lib/node_modules/npm' -> '/usr/lib/node_modules/.npm-qUIFSsiV'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/lib/node_modules/npm',
npm ERR!   dest: '/usr/lib/node_modules/.npm-qUIFSsiV'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-12-07T07_05_45_611Z-debug.log
hoobs@hoobs:~ $

**Comment by BobbySlope** [comment]
You can filter the logs via the filter option in the top bar
