### ISSUE TITLE
Hoobs unable top install plugins 

### ISSUE THREAD

**Issue by seantadez** [hoobs-org/HOOBS#1697]
**Description**
I'm not able to install new plugins every time I try I get this "unable to install plugin, try again later..." and this is happening for the last couple weeks, I really need install other plugins 

**Version**
4.0.109

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

bond, Nest , Nest cam , Wiz Lan 

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

Dashboard
Accessories
Log
Profiles
Bridges
Plugins
12/8/2021, 4:48:15 PMWARNINGperforming restore
12/8/2021, 4:48:16 PMrestore type "full"
12/8/2021, 4:48:31 PMrestore complete
12/8/2021, 4:48:31 PMWARNINGservice restart command received
12/8/2021, 4:48:47 PMhub is running on port 80
12/8/2021, 4:48:48 PMNest Bridge starting
12/8/2021, 4:48:56 PMNest BridgeWARNINGNo plugins installed.
12/8/2021, 4:48:56 PMNest BridgeBridge is running on port 51826.
12/8/2021, 4:51:26 PMWARNINGperforming restore
12/8/2021, 4:51:26 PMrestore type "full"
12/8/2021, 4:51:28 PMNest BridgeBridge change
12/8/2021, 4:51:28 PMnestbridge stopping
12/8/2021, 4:51:33 PMNest Bridge starting
12/8/2021, 4:51:41 PMNest BridgeWARNINGNo plugins installed.
12/8/2021, 4:51:41 PMNest BridgeBridge is running on port 51826.
12/8/2021, 4:51:45 PMrestore complete
12/8/2021, 4:51:45 PMWARNINGservice restart command received
12/8/2021, 4:51:54 PMNest Bridge stopping
12/8/2021, 4:52:06 PMhub is running on port 80
12/8/2021, 4:52:07 PMNest Bridge starting
12/8/2021, 4:52:16 PMNest BridgeWARNINGNo plugins installed.
12/8/2021, 4:52:16 PMNest BridgeBridge is running on port 51826.
12/8/2021, 4:53:38 PMWARNINGperforming restore
12/8/2021, 4:53:39 PMrestore type "full"
12/8/2021, 4:55:15 PMrestore complete
12/8/2021, 4:55:15 PMWARNINGservice restart command received
12/8/2021, 4:55:25 PMNest Bridge stopping
12/8/2021, 4:55:37 PMhub is running on port 80
12/8/2021, 4:55:38 PMBond Bridge starting
12/8/2021, 4:55:39 PMNest Bridge starting
12/8/2021, 4:55:39 PMWiz Lan Bridge starting
12/8/2021, 4:55:40 PMNest Cam Bridge starting
12/8/2021, 4:55:51 PMBond BridgeLoaded plugin 'homebridge-bond'
12/8/2021, 4:55:51 PMBond BridgeLoading 1 platforms...
12/8/2021, 4:55:52 PMBond BridgeBridge is running on port 51826.
12/8/2021, 4:55:53 PMBond BridgeBondERRORUnable to find Bond for IP Address: 10.0.0.46. Skipping this Bond.
12/8/2021, 4:55:53 PMBond BridgeBondWARNINGNo valid Bonds available.
12/8/2021, 4:55:53 PMWiz Lan BridgeLoaded plugin 'homebridge-wiz-lan'
12/8/2021, 4:55:53 PMWiz Lan BridgeLoading 3 platforms...
12/8/2021, 4:55:53 PMWiz Lan BridgeWizSmarthomeLoading accessory from cache: a8bb5009b701
12/8/2021, 4:55:53 PMWiz Lan BridgeWizSmarthomeLoading accessory from cache: a8bb5008da15
12/8/2021, 4:55:53 PMWiz Lan BridgeWizSmarthomeLoading accessory from cache: a8bb50093165
12/8/2021, 4:55:53 PMWiz Lan BridgeWizSmarthomeLoading accessory from cache: a8bb5008d72a
12/8/2021, 4:55:53 PMNest BridgeLoaded plugin 'homebridge-nest'
12/8/2021, 4:55:53 PMNest BridgeLoading 1 platforms...
12/8/2021, 4:55:53 PMNest BridgeNestFetching Nest devices.
12/8/2021, 4:55:53 PMWiz Lan BridgeWizSmarthome[Socket] Setting up socket on 192.168.1.186:38900
12/8/2021, 4:55:54 PMWiz Lan BridgeWizSmarthome[Discovery] Sending discovery UDP broadcast to 255.255.255.255:38899
12/8/2021, 4:55:54 PMWiz Lan BridgeBridge is running on port 51846.
12/8/2021, 4:55:54 PMNest BridgeBridge is running on port 51836.
12/8/2021, 4:55:54 PMWiz Lan BridgeWizSmarthomeUpdating accessory: Wiz RGB Bulb a8bb5008da15 [formerly a8bb5008da15]
12/8/2021, 4:55:54 PMWiz Lan BridgeWizSmarthomeUpdating accessory: Wiz RGB Bulb a8bb5008d72a [formerly a8bb5008d72a]
12/8/2021, 4:55:54 PMWiz Lan BridgeWizSmarthomeUpdating accessory: Wiz RGB Bulb a8bb5009b701 [formerly a8bb5009b701]
12/8/2021, 4:55:54 PMWiz Lan BridgeWizSmarthomeUpdating accessory: Wiz RGB Bulb a8bb50093165 [formerly a8bb50093165]
12/8/2021, 4:55:55 PMNest Cam BridgeLoaded plugin 'homebridge-nest-cam'
12/8/2021, 4:55:55 PMNest Cam BridgeLoading 1 platforms...
12/8/2021, 4:55:55 PMNest Cam BridgeNest-camConfiguring accessory Backyard
12/8/2021, 4:55:55 PMNest Cam BridgeNest-camConfiguring accessory Front Door
12/8/2021, 4:55:55 PMNest Cam BridgeNest-camConfiguring accessory Sala Sala
12/8/2021, 4:55:55 PMNest Cam BridgeNest-camConfiguring accessory Entryway
12/8/2021, 4:55:55 PMNest Cam BridgeNest-camConfiguring accessory Sanctuary 
12/8/2021, 4:55:56 PMNest Cam BridgeBridge is running on port 51856.
12/8/2021, 4:56:07 PMNest Cam BridgeWARNINGunhandled rejection: Error: Cannot add more than 100 services to a single accessory!
12/8/2021, 4:56:08 PMNest BridgeNestiniting thermostat (P) "Kitchen Thermostat": deviceId: 18B430000073285A structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 4:56:08 PMNest BridgeNestiniting thermostat (P) "Lobby Thermostat": deviceId: 18B4300000769CD9 structureId: cf852820-f10c-11e5-890d-22000b82a169
12/8/2021, 4:56:08 PMNest BridgeNestiniting thermostat (P) "Sanctuary-L Thermostat": deviceId: 18B430000078E68F structureId: cf852820-f10c-11e5-890d-22000b82a169
12/8/2021, 4:56:08 PMNest BridgeNestiniting thermostat (P) "Sanctuary-R Thermostat": deviceId: 18B4300000768885 structureId: cf852820-f10c-11e5-890d-22000b82a169
12/8/2021, 4:56:08 PMNest BridgeNestiniting home_away_sensor "Home Occupied - TABARES": deviceId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 4:56:08 PMNest BridgeNestiniting home_away_sensor "Home Occupied - Church": deviceId: cf852820-f10c-11e5-890d-22000b82a169 structureId: cf852820-f10c-11e5-890d-22000b82a169
12/8/2021, 4:56:08 PMNest BridgeNestiniting protect "Lavandera ": deviceId: 18B4300000ADEBDB structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 4:56:08 PMNest BridgeNestiniting protect "Benjamin Room": deviceId: 18B4300000ADCB33 structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 4:56:08 PMNest BridgeNestiniting protect "Oficina": deviceId: 18B43000003398BA structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 4:56:08 PMNest BridgeNestiniting protect "Cocina": deviceId: 18B4300000331F24 structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 4:56:08 PMNest BridgeNestiniting protect "Master Bedroom": deviceId: 18B4300000B1F5BA structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 4:56:08 PMNest BridgeNestiniting protect "Guest Room": deviceId: 18B4300000ADEBD3 structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 4:56:08 PMNest BridgeNestiniting protect "Downstairs": deviceId: 18B4300000B4D9D1 structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 4:56:08 PMNest BridgeNestiniting protect "Hallway": deviceId: 18B4300000B4DDE9 structureId: 110ea200-6919-11e7-ad8b-0a0e19cd60aa
12/8/2021, 5:08:15 PMRoomba Stv Bridge starting
12/8/2021, 5:08:54 PMNest Cam BridgeNest-camSetting Front Door Announcements to on
12/8/2021, 5:14:22 PMroombastvbridge stopping
12/8/2021, 5:17:14 PMNest BridgeNestERRORAPI observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at new NodeError (internal/errors.js:322:7)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2271:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at Http2Stream.onStreamClose (internal/http2/core.js:525:12) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
12/8/2021, 5:17:14 PMNest BridgeNestERRORRetrying in 10 seconds.

**Additional context**

**Comment by BobbySlope** [comment]
Try to run the fix command:

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3

And try to install new plugins afterwards
