### ISSUE TITLE
4.1.11 cannot be updated to 4.1.17 - 

### ISSUE THREAD

**Issue by stan73** [hoobs-org/HOOBS#1699]
Since I updated to 4.1.11 I cannot connect hoops to Homekit. I run hoops on a USB from you in a Raspberry PI4. Which was running until the update to 4.1.1!!!

The I realised that there is a new update 4.1.17 and I am trying several times to install - but not successfully. It stops with the following message:
#####
20:29:49Some packages could not be installed. This may mean that you have
20:29:49requested an impossible situation or if you are using the unstable
20:29:49distribution that some required packages have not yet been created
20:29:49or been moved out of Incoming.
20:29:49The following information may help to resolve the situation:
20:29:49The following packages have unmet dependencies:
20:29:49hoobs-cli : Depends: nodejs (>= 16.13.0) but 14.18.2-deb-1nodesource1 is to be installed
20:29:49hoobsd : Depends: nodejs (>= 16.13.0) but 14.18.2-deb-1nodesource1 is to be installed
20:29:49E: Unable to correct problems, you have held broken packages.
20:29:49WARNUNGservice restart command received
20:29:48restarting
20:29:48

So, I can't update to this new version and I am stuck with the 4.1.11 which seems to be broken somehow, as it doesn't let me connect to Homekit anymore.

This is the update showing

Server Version: 4.1.17
Verfügbar
GUI Version: 4.1.17
Verfügbar
CLI Version: 4.1.17
Verfügbar
Node Version: 14.18.2
Verfügbar
System
Bind9 Host: 1:9.11.5.P4+dfsg-5.1+deb10u6
Verfügbar
Libbind9 161: 1:9.11.5.P4+dfsg-5.1+deb10u6
Verfügbar
Libisccfg163: 1:9.11.5.P4+dfsg-5.1+deb10u6
Verfügbar
Libisccc161: 1:9.11.5.P4+dfsg-5.1+deb10u6
Verfügbar
Libdns1104: 1:9.11.5.P4+dfsg-5.1+deb10u6
Verfügbar
Libisc1100: 1:9.11.5.P4+dfsg-5.1+deb10u6
Verfügbar
Liblwres161: 1:9.11.5.P4+dfsg-5.1+deb10u6
Verfügbar
Firmware Atheros: 1:20190114-2+rpt4
Verfügbar
Firmware Brcm80211: 1:20190114-2+rpt4
Verfügbar
Firmware Libertas: 1:20190114-2+rpt4
Verfügbar
Firmware Misc Nonfree: 1:20190114-2+rpt4
Verfügbar
Firmware Realtek: 1:20190114-2+rpt4
Verfügbar
Libicu Dev: 63.1-6+deb10u2
Verfügbar
Icu Devtools: 63.1-6+deb10u2
Verfügbar
Libicu63: 63.1-6+deb10u2
Verfügbar
Libasound2: 1.1.8-1+rpt2
Verfügbar
Libasound2 Data: 1.1.8-1+rpt2
Verfügbar
Libisc Export1100: 1:9.11.5.P4+dfsg-5.1+deb10u6
Verfügbar
Libdns Export1104: 1:9.11.5.P4+dfsg-5.1+deb10u6
Verfügbar
Libraspberrypi Doc: 1:1.20211201~buster-1
Verfügbar
Libraspberrypi Dev: 1:1.20211201~buster-1
Verfügbar
Raspberrypi Kernel: 1:1.20211201~buster-1
Verfügbar
Libraspberrypi Bin: 1:1.20211201~buster-1
Verfügbar
Libraspberrypi0: 1:1.20211201~buster-1
Verfügbar
Raspberrypi Bootloader: 1:1.20211201~buster-1
Verfügbar
Linux Libc Dev: 1:1.20211201~buster-1
Verfügbar
Raspberrypi Net Mods: 1.3.2
Verfügbar
Rpi Eeprom: 13.1-1~buster
Verfügbar

**Comment by bwp91** [comment]
You may need to run the upgrade script from a ssh terminal into the hoobs instance

```
curl -sk https://dl.hoobs.org/fix | sudo bash -
```

**Comment by stan73** [comment]
Cool, Thanks. I will try it right now.

Can I copy and paste this command or do I need to maintain anything else here?

> Am 09.12.2021 um 20:36 schrieb Ben ***@***.***>:
> 
> url -sk https://dl.hoobs.org/fix <https://dl.hoobs.org/fix> | sudo bash -

**Comment by stan73** [comment]
Hey Ben,

After doing this, now the box isn’t accessible through browser.
I Trend several commands from the CLI-Reference but it won’t recognise any Hobbs commands?!


Any Idea?

**Comment by bwp91** [comment]
If you still have the output from running the fix script i posted can you show it here?

**Comment by stan73** [comment]
It closes my SSH windows after I can read something like

„This system is already initialized ….“

Then it tries to start an update, and that’s exactly where my ssh gets closed.

So I have no chance to post you anything

**Comment by stan73** [comment]
OK, It seems that the hoops is running again in web .
And I have now the 4.1.17
Thanks so far for that one...


Unfortunately, I am still unable to rejoin Homekit,
Scanning the QR with my Homekit app just wastes about 3 minutes and then it says unable to connect to accessory"

**Comment by batracy** [comment]
When installing the plugin, install in it's own bridge and switch from bonjour to ciao for the listening device. This is what I had to do to get things to pair with Homekit.

**Comment by stan73** [comment]
Thanks for the hint - but this was not working for me.

The plug-in was working earlier but then stopped.

So I tried to remove the bridge and put it then back to HomeKit. It was on Bonjour earlier

Now it is not able to bring it back to connect with HomeKit.

I am in the same subnet with HomeKit, iPhone wifi and hoobs

**Comment by icecoldcube007** [comment]
Hi guys, 

I had the same issue updating from 4.1.11 to 4.1.17 on a newly purchased Hoobs box, I've ran the command via Terminal as above. But I'm not able to access via the HTTP interface, only SSH.

Could I ask for someone to point me to the fix script mentioned earlier please?

Thank you.

**Comment by stan73** [comment]
That's the one I got.

And after the second try it worked good for me.

curl -sk https://dl.hoobs.org/fix | sudo bash -

**Comment by batracy** [comment]
Makes me wonder why so many of us have had to run the "fix" just to upgrade to the current version. I had to run it twice as well. Doesn't seem like there has been sufficient testing on the upgrade process.

Back to your issue stan73, do you have the hoobs app installed on your computer? Are you able to connect with hoobs via a web browers? It seems that one of these methoods is working for you. I use the hoobs app. Did you uninstall the bridge from Homekit before trying to connect your bridge in Hoobs to Homekit? Have you tried both bonjour and ciao as bridge advertisers? When I used bonjour, the bridge would not add to homekit it would say that it could not find the device. When I changed to ciao homekit recognized it almost immediately and added it without any issues.

I know that what works for one person may not work for another. If you have tried both bonjour and ciao without success, then I don't know what to tell you. It looks like you might want to reach out to hoobs support or the plugin developer or both.

**Comment by stan73** [comment]
Well, I am using webbrowser to my Hoobs. I earlier was able to use hoops Bridge on my Homekit for almost 6 months (Logitech Harmony and Camera FFMPEG). But then it started having issues with the 4.1..17 update and I wasn't able to use the accessory in my home app. So I tried several things to fix. And finally deleted the hoops accessory in my home app to let it connect again.

But then I never was again able to do so.
Here is my environment:
1. All devices (Hoobs Bridge, my HKKNX-Bridge, my Harmony etc. my iPhone, iPad, Apple TV, HomePod and so on, are in one Subnet (/24). So there is no need to pass any firewall between those devices. My Subnet is also able to connect to internet. My HKKNX Bridge is still running. I won't remove it because I am afraid that it also won't get reconnected to Homekit.
2. My hoops is well configured. Harmony Plugin has its own Bridge. CameraFFMPEG has its own Bridge. Both Plug-Ins work. I can test this by seeing the 5 Cameras and by powering on/off my TV and switch the apps on my Apple TV. But I can't connect hoobs to my Homekit ap. I deleted the cache of each Plugin, restarted the bridge, restarted the hoops. It does not help - all what happens is, that my HomeKitt tries for at least 2-3 minutes to connect to hoops and then interrupts with a single message, no accessory  could be connected.
3. I switched from Bonjour to Ciao and back. Its all the same.
4. Maybe I am missing s.th. Does anybody exactly know how the add bridge accessory prices works and what prerequisites you need to have? I am asking maybe if there is something special in my internet connection to be allowed or whatever....

**Comment by stan73** [comment]
Btw - This is not closed I accidentally hit that button.....

**Comment by batracy** [comment]
The only thing I can suggest is to reboot your router. I know that sounds strange. I had an issue where one of my ring camera's was not updating the view in Hoobs, but it worked find in Homekit. Someone on the FB Hoobs community suggested rebooting the router which I thought at the time was a dumb suggestion. I did it anyway and then everything worked.

So try the reboot. If that doesn't work, then it's possible that the upgrade to 4.1.17 didn't complete everything it should have and you might try that again by opening your terminal app on your computer and ssh'ing into Hoobs. If you need the commands let me know. I got them from Hoobs support. fyi, I had to run the update twice.

**Comment by BobbySlope** [comment]
You can run this command to fix the issue:

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3
