### ISSUE TITLE
Add UI Responsiveness for mobile browsing 

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#17]
![1E8EA95F-C0BC-403F-9A69-18A89885EC7A](https://user-images.githubusercontent.com/3981552/62421870-2a62eb00-b677-11e9-9b8f-6a925838a7f2.png)
![7E121A41-705F-49C3-8D05-EEE785AE4197](https://user-images.githubusercontent.com/3981552/62421871-2a62eb00-b677-11e9-9316-e861b2a924fd.png)
![7F529750-1EC6-45EC-8084-5263249F1522](https://user-images.githubusercontent.com/3981552/62421872-2a62eb00-b677-11e9-9e72-c85039fd3635.png)
![59B652E5-51F6-424B-911A-08595DAD4C04](https://user-images.githubusercontent.com/3981552/62421873-2a62eb00-b677-11e9-8144-f6519011c229.png)

**Comment by mkellsy** [comment]
This is done
