### ISSUE TITLE
Invalid JSON check in advanced config

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#170]
User requested: in the advanced config when invalid json is entered, do not allow saving, pop-up error message (already done) but also indicate the line that is invalid like in current v2.1.1 This helps users pinpoint the problem easier.

**Comment by mkellsy** [comment]
I will see if codemirror has this capibility. If not I may have to use a full Monaco build (Visual Studio Code uses Monaco). I was avoiding this because the editor would be 5 times larger than HOOBS.

**Comment by mkellsy** [comment]
I added JSON linting to both the advanced config and inline JSON fields. If the JSON is invalid, a red squiggly line will highlight the invalid JSON.

Done in 3.0.0-beta.30
