### ISSUE TITLE
hoobs.local

### ISSUE THREAD

**Issue by MargaridaPardal** [hoobs-org/HOOBS#1700]
**Description**
i cant run hoobs.local and its the first time i tried to run hoobs, i have a raspberry pi 4 
i follow *everything* in this video https://www.youtube.com/watch?v=10r4IY8VHJs&t=454s&ab_channel=CrazyWillTechShow and i cant even open hoobs local, i have the mac app and it says "no devices"

**Version**
hoobs- v4.0.31

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
MacOs Monterey

**Comment by BobbySlope** [comment]
https://support.hoobs.org/topics/61c9d900dcf29f5e39f026a4/61c9de86dcf29f5e39f02dd2
