### ISSUE TITLE
Ring refresh token

### ISSUE THREAD

**Issue by beachboy88** [hoobs-org/HOOBS#1702]
**Description**
Ring works for a day or two after I login and enter the 2FA code from text message, but then camera goes back to saying no response. The HOOBS console says there is a problem with the refresh token. I have already tried the very confusing and difficult-to-follow advice at https://github.com/dgreif/ring/wiki/Refresh-Tokens without success. I thought this was supposed to just work and I paid too much money to be having this much trouble with it.

**Expected behavoir**
Normal function of Ring doorbell/camera

**Plugin name**
Ring

**Please report the issue to the plugin developer**
Unsure how to do this.

**Version**
Don’t know. Can’t tell.

**Did you upgrade**
No

**Pervious version**
NA

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Don’t think so.

**What device are you using?**
HOOBS box

**If this is a custom install, what's your operating system?**
NA

**Post your config**
Can’t figure out how to do this either. For a $200 device that is supposed to just work right out of the box, this thing requires way too much tinkering and still won’t stay connected to Ring! Very disappointed.

**Post your log**
Can’t find log

**Additional context**
NA

**Comment by BobbySlope** [comment]
Please contact us via support@hoobs.com and we can help you troubleshoot via remote session
