### ISSUE TITLE
Bridge with Apple Home doesn't work

### ISSUE THREAD

**Issue by sebzibi** [hoobs-org/HOOBS#1703]
I regularly lose the connection between my devices and Homekit.

I still see all my devices in HOOBS but they are disconnected in Apple Home.

How can I resolve this problem?

I use HOOBS 4.0.110

All updates are OK

![99E299A8-64C3-41CD-800C-B43DB0F147F7](https://user-images.githubusercontent.com/85185968/145667943-2c20901a-869d-4296-b157-887a070a7647.png)

![C8E695EA-23C7-4A2D-9BDE-399C334EBB6C](https://user-images.githubusercontent.com/85185968/145667950-109335bc-b5d0-4116-9ab9-edf82b071c9b.png)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
TYDOM
DAIKIN

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Do you lose connection to Homekit when you're outside your network? In that case do you have a home hub? (Apple TV HD/4K, HomePod?)
You need one in order to control devices from outside your network.

Also the latest HOOBS version right now is 4.1.17. If you don't see an update available you can run this command from the HOOBS terminal:

    curl -sk https://dl.hoobs.org/fix | sudo bash -

**Comment by sebzibi** [comment]
> Do you lose connection to Homekit when you're outside your network? In that case do you have a home hub? (Apple TV HD/4K, HomePod?) You need one in order to control devices from outside your network.
> 
> Also the latest HOOBS version right now is 4.1.17. If you don't see an update available you can run this command from the HOOBS terminal:
> 
> ```
> curl -sk https://dl.hoobs.org/fix | sudo bash -
> ```

Hello,

Thank you for you answer. Problem is inside network and outside network. How to access to Hoobs terminal ?

**Comment by askovi** [comment]
You need to use a computer.
You can access it from the top right menu. It's recommended you download the app for mac or windows. 

Default terminal login is:

Username: hoobs 
Password: hoobsadmin
