### ISSUE TITLE
Cannot configure plug ins 

### ISSUE THREAD

**Issue by Fitzdrew516** [hoobs-org/HOOBS#1704]
**Description**
Cannot configure plug ins. It never prompts me for my myQ credentials (or any other plug ins). If anyone could help out I would be very thankful! I just set up today and cannot get anything to connect to homekit without the plug ins. 
![Hoobs Plugins](https://user-images.githubusercontent.com/95979378/145687946-315cdcd2-9c2d-4bf5-b52c-29f52efd6b05.PNG)

**Version**
Latest

**Did you upgrade**
No

**What device are you using?**
HOOBS SD Card

![Hoobs Config](https://user-images.githubusercontent.com/95979378/145687810-473e1542-18e7-43e5-9b31-70272ea21474.PNG)

**Comment by BobbySlope** [comment]
Go to the plus icon and configure it
