### ISSUE TITLE
Help with Samsung SmartThings Plug in

### ISSUE THREAD

**Issue by mdhEddie34** [hoobs-org/HOOBS#1705]
Just purchased Hoobs and cannot get accessories to show up from Samsung SmartThings.  followed all instructions provided.  items show up on Samsung side and let me choose, but after that nothing.  no accessories on hoops or HomeKit.  What am I doing wrong?  Do I need to return Hoobs if it doesn't work with Samsung like advertised?

**Comment by Melvo8** [comment]
I can’t get this to work either.  The app doesn’t seem to match up to the instructions?

**Comment by BobbySlope** [comment]
Please provide more information. 
Did you scanned the qr code from the bridges page to connect the bridge with homekit?

**Comment by Melvo8** [comment]
I think it is an issue with the Samsung app.  The instructions don't match the app, like Samsung did an update

**Comment by BobbySlope** [comment]
We fixed the README, and the instructions are cleaner.

TO FIX
Go to Main Menu -> Hub Settings - Clear Cache
Then to Config and SmartThings Bridge, the nice form will be there.
If you click the Advanced button you can paste the config from the SmartApp directly and it will work.

**Comment by Melvo8** [comment]
Going through the instructions on step 4 it says to click on My Hubs and verify your hub shows up.  I don't have anything that shows up, do i need to purchase a Samsung hub?
