### ISSUE TITLE
Cant connect HomeKit to hoobs 

### ISSUE THREAD

**Issue by MargaridaPardal** [hoobs-org/HOOBS#1706]
[](url
<img width="1078" alt="Captura de ecrã 2021-12-12, às 15 59 22" src="https://user-images.githubusercontent.com/95932844/145719563-978a57ad-535e-4f51-9fc0-d31bc2944486.png">
)

**Comment by MargaridaPardal** [comment]
#1488

**Comment by BobbySlope** [comment]
Without more information we cant support you.
