### ISSUE TITLE
Unable to Upgrade HOOBS version

### ISSUE THREAD

**Issue by Peltier36** [hoobs-org/HOOBS#1707]
**Description**
I'm unable to update to the newest version of hoobs
**Version**
Please include the version of HOOBS you are using.
4.0.71
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
Version 3
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Please run this command from the HOOBS terminal (default terminal credentials are hoobs // hoobsadmin)

    curl -sk https://dl.hoobs.org/fix | sudo bash -

**Comment by Peltier36** [comment]
I attempted to upgrade it and how it will not work at all. Please advise. Do I need to remote in? If so, how do I do so?

**Comment by BobbySlope** [comment]
How did you tried to run the command?
Go to hoobs.local:9090 login with hoobs / hoobsadmin and run the command again

**Comment by jwvanderbeck** [comment]
> Please run this command from the HOOBS terminal (default terminal credentials are hoobs // hoobsadmin)
> 
> ```
> curl -sk https://dl.hoobs.org/fix | sudo bash -
> ```

This "answer" is given all over but can someone please explain HOW to do it? I think this assumes we know what we are doing but I bought the HOOBS in a box thing and have no idea.

**Comment by jwvanderbeck** [comment]
Ok I finally figured out how to do this, but it apparently bricked my HOOBS box :(  I can still SSH in (Apparently that is what was meant by HOOBS terminal) but the web interface is gone.

**Comment by BobbySlope** [comment]
Ssh in again and run the command again. It takes some time but the hoobs box will come up again

**Comment by jwvanderbeck** [comment]
Thanks running it a second time did fix it!  Looking at the logs it looks like for some reason the first time it failed to reinstall the hoobs packages but the second time it did.
