### ISSUE TITLE
Unable to link account on Nest Thermostat plugin

### ISSUE THREAD

**Issue by pkondapani** [hoobs-org/HOOBS#1708]
Installed Nest Thermostat app using hoobs local on my Mac, however, it shows a blank screen when I click login (Please refer third and fourth screenshots below).

I tried with various browsers such as Safari and Chrome yet it still shows the same blank screen (4th screenshot).
Any help would be greatly appreciated!

![image](https://user-images.githubusercontent.com/71685845/145762900-af48dc7d-5a1d-4bcf-8094-b6ed0a947085.png)
![image](https://user-images.githubusercontent.com/71685845/145762954-54d4f63d-72ab-4dc5-a488-cd24ab60d2a6.png)
![image](https://user-images.githubusercontent.com/71685845/145763244-ec2048ef-aa02-4d28-a8b2-0996cc7f43c6.png)
![image](https://user-images.githubusercontent.com/71685845/145763270-323e0cc2-1215-4b34-8703-5eaebaac3ff9.png)

**Comment by askovi** [comment]
Please make sure you're running the latest HOOBS version 4.1.17 and using the latest HOOBS Desktop app for Mac or Windows. When you click the login button it's supposed to open a browser window with the google login. Make sure it opens in Chrome and that your pop-up blocker is disabled.

**Comment by pkondapani** [comment]
Thanks for your detailed response. My current HOOBS sw version is 4.0.87 and when I click update it says your software is up to date. I tried using the browser as well as my Mac desktop app. 

May I know how can I update to 4.1.17?

**Comment by askovi** [comment]
Run this fix command from the HOOBS terminal (default credentials are hoobs // hoobsadmin)

    curl -sk https://dl.hoobs.org/fix | sudo bash -

**Comment by pkondapani** [comment]
Thanks. I did execute the command and noticed the hoobs desktop version is now 4.1.17.
However, I can't access hoobs local now. Could you advise further suggestions?
![image](https://user-images.githubusercontent.com/71685845/146311228-a61175cc-6761-4333-a4e2-ae062c6b9f3f.png)

**Comment by askovi** [comment]
Can you access the recovery terminal at http://hoobs.local:9090?

If you can, please get the logs with:

    sudo hbs log

**Comment by pkondapani** [comment]
I can't access the recovery terminal using above lin; :(

**Comment by pkondapani** [comment]
I tried the below command suggested by you in other thread and it fixed the issue!
Now my Hoobs version is updated to 4.1.18. Thanks a lot for your help!

Please run this command from the HOOBS terminal (default terminal credentials are hoobs // hoobsadmin)

curl -sk https://dl.hoobs.org/fix | sudo bash -

**Comment by askovi** [comment]
Glad you got it working!
