### ISSUE TITLE
This plugin is no longer available

### ISSUE THREAD

**Issue by MasterofKungfu9999** [hoobs-org/HOOBS#1709]
**Description**
If i search for plugins i get this: "This plugin is no longer available."

**Version**
4.1.17

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
raspberry

**List your plugins**
homebridge-hue and others

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by Raczka1989** [comment]
I have the same Problem, Hue Homebridge Plugin is no longer available.

**Comment by askovi** [comment]
There was a temporary sync issue on the server side. This is now fixed.
