### ISSUE TITLE
Add Plugin Map to Plugins Without a Config Schema

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#171]
Currently there is only Add Accessory for Custom config. For plugins not yet certified, there is no way to add a platform through the Guided Configuration, only by editing it directly in the Advanced Configuration.

**Comment by mkellsy** [comment]
It isn't certified that triggers this it is the existence of a config schema file.

I could map an item in the platforms array, but in the past this was causing Homebridge not to start. However now we have our own spin, so I can add logic that ignores entries without a proper name.

**Comment by mkellsy** [comment]
Merging with #168
