### ISSUE TITLE
Homebridge 1.3.8 Support

### ISSUE THREAD

**Issue by scaryfast8750** [hoobs-org/HOOBS#1711]
**Description**
Hoobs is currently using Homebridge 1.3.6, current version is 1.3.8 and Plugins are warning about compatability.

How do we get Hoobs updated to 1.3.8.  Note the Wemo Plugin warning:  12/14/2021, 3:59:47 PMWemo BridgeERROR[31mThe plugin "homebridge-wemo" requires a Homebridge version of ^1.3.8 which does not satisfy the current Homebridge version of 1.3.6. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

**Version**
Hoobs 4.1.17 with all patches complete including OS patching from within the Hoobs UI.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X ] HOOBS Box

**Comment by bwp91** [comment]
My fault for releasing wemo plugin version early.
A new version of hoobs will be available soon with newest homebridge version.
But for the moment this will have no impact on the plugin working.

**Comment by mkellsy** [comment]
4.1.18 is published now. If you don't see it, you may have to wait for the CDN.
4.1.18 has HB 1.3.8 in it.

**Comment by scaryfast8750** [comment]
It upgraded smoothly to 4.1.18/1.3.8, all log errors are gone and everything still works. 

Great job.  Thank you.

**Comment by tonipepperoni77** [comment]
i dont see an upgrade available for my hoobs, currently running 4.0.100 @mkellsy

**Comment by mkellsy** [comment]
@tonipepperoni77
Your system missed a critical update. Run this to get it back
```
curl -sk https://dl.hoobs.org/fix | sudo bash -
```
