### ISSUE TITLE
Unable to update Hoobs & Unable to connect to Homekit. I just got this microsd today.

### ISSUE THREAD

**Issue by mnsrit** [hoobs-org/HOOBS#1712]
**Description**

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No
I got the microSD today and then I installed it as instructed. I noticed "update available" I clicked on it. Tried three times to no avail. I was able to grab the last statement - saying "You have broken packages." - what does that mean?

Secondly, there's no QR code in the dashboard. How can I connect this to my homekit environment?

Thirdly, I am able to log into Hoobs but I cannot log into Terminal OR find any config files in advanced area.

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

** No Plugins have been installed yet **

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
None provided - unable to access via Terminal or via Configuration -> Advanced.

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE

11/24/2021, 4:34:29 PMhub is running on port 80
12/14/2021, 5:23:01 PMWARNINGservice restart command received
12/14/2021, 5:23:13 PMhub is running on port 80
12/14/2021, 5:24:24 PMWARNINGservice restart command received
12/14/2021, 5:24:36 PMhub is running on port 80
12/14/2021, 5:25:25 PMWARNINGservice restart command received
12/14/2021, 5:25:37 PMhub is running on port 80
12/14/2021, 5:27:41 PMWARNINGdevice reboot command received
12/14/2021, 5:28:36 PMhub is running on port 80
12/14/2021, 5:48:18 PMWARNINGservice restart command received
12/14/2021, 5:48:30 PMhub is running on port 80
12/14/2021, 5:58:06 PMWARNINGservice restart command received
12/14/2021, 5:58:18 PMhub is running on port 80

**Additional context**

4.1.11 Update Available
14.18.1
1.3.5
2%
18 MB (18 MB)
HOOBS.org
HSLF-1
11
7-45114-12419-7
hoobs

![IMG_0401](https://user-images.githubusercontent.com/15224780/146099230-0368c4e8-bb51-4e28-8ea5-a3992e2fee57.jpeg)

![IMG_0402](https://user-images.githubusercontent.com/15224780/146099380-5b18566b-f628-4b36-ab93-1e851c802c64.jpeg)

**Comment by mnsrit** [comment]
Here's the update, I was able to get into the terminal and update. However, now I cannot find the hoobs after the update. What should I do now? Thanks.

**Comment by mnsrit** [comment]
Back to square one - i now cannot access the terminal as it's NOT THERE.

**Comment by mkellsy** [comment]
Send an email to info@hoobs.com. We can get you a new SD card. Remember to state if you are using a Pi 3 or a Pi 4.

**Comment by askovi** [comment]
Can you access the recovery terminal at http://hoobs.local:9090 ?
Login with:
user: hoobs
pass: hoobsadmin

Then run this fix command:
    curl -sk https://dl.hoobs.org/fix | sudo bash -

You can also access the terminal via ssh if needed:
On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.
