### ISSUE TITLE
Tesla "This accessory is not responding"

### ISSUE THREAD

**Issue by bngoofy** [hoobs-org/HOOBS#1714]
Installed Tesla Plugin 3.4.0. Got my refresh key via Auth for Tesla iOS ap.

HomeKit added the Bridge with no issues but is always says "This accessory is not responding" and is unuseable

Hoobs Version: 4.0.100

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
no

POST CONFIG HERE
{
    "accessories": [
        {
            "name": "Tardis",
            "vin": "truncated for security",
            "username": "truncated for security",
            "password": "truncated for security",
            "waitMinutes": 5,
            "latitude": "27.845791",
            "longitude": "-82.259825",
            "enableHomeLink": true,
            "accessory": "Tesla",
            "refreshToken": "truncated for security"
        }
    ],
    "platforms": []
}

POST LOG HERE

12/15/2021, 11:44:53 AMTesla BridgeTardisHomeLink does not support garage door status.
12/15/2021, 11:44:53 AMTesla BridgeTardisAlways setting garage door state to closed.
12/15/2021, 11:44:54 AMTesla BridgeTardisConnection on? false
12/15/2021, 11:44:54 AMTesla BridgeERROR[Tesla Bridge E7E1@Tardis@Tardis Charge Level@Battery Level] The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback!
12/15/2021, 11:44:56 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:44:56 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:44:57 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:44:57 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:44:57 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:44:57 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:44:57 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:44:57 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:44:57 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:44:57 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:02 AMTesla BridgeTardisHomeLink does not support garage door status.
12/15/2021, 11:45:02 AMTesla BridgeTardisAlways setting garage door state to closed.
12/15/2021, 11:45:03 AMTesla BridgeTardisVehicle was asleep; ignored 29 requests for current state
12/15/2021, 11:45:05 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:05 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:05 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:05 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:05 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:05 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:05 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:09 AMTesla BridgeTardisHomeLink does not support garage door status.
12/15/2021, 11:45:09 AMTesla BridgeTardisAlways setting garage door state to closed.
12/15/2021, 11:45:12 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:12 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:12 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:12 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:12 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:12 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:12 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:15 AMTesla BridgeTardisHomeLink does not support garage door status.
12/15/2021, 11:45:15 AMTesla BridgeTardisAlways setting garage door state to closed.
12/15/2021, 11:45:15 AMTesla BridgeTardisConnection on? false
12/15/2021, 11:45:18 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:18 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:18 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:18 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:18 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:18 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:18 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:23 AMTesla BridgeTardisVehicle was asleep; ignored 42 requests for current state
12/15/2021, 11:45:26 AMUnifi BridgeUniFi ProtectWCL-CloudKey [UCK-G2-PLUS] 1 - Front [UVC G3 Dome]: Streaming request from 192.168.1.17: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1920x1080@15fps (High), 3000 kbps.
12/15/2021, 11:45:35 AMTesla BridgeTardisHomeLink does not support garage door status.
12/15/2021, 11:45:35 AMTesla BridgeTardisAlways setting garage door state to closed.
12/15/2021, 11:45:37 AMUnifi BridgeUniFi ProtectWCL-CloudKey [UCK-G2-PLUS] 1 - Front [UVC G3 Dome]: Stopped video streaming session.
12/15/2021, 11:45:37 AMHOOBSRingPreparing Live Stream for Front Door
12/15/2021, 11:45:38 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:38 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:38 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:38 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:38 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:38 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:38 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:39 AMHOOBSRingWaiting for stream data from Front Door (1.627s)
12/15/2021, 11:45:39 AMHOOBSRingReceived stream data from Front Door (1.671s)
12/15/2021, 11:45:39 AMHOOBSRingStreaming active for Front Door
12/15/2021, 11:45:43 AMTesla BridgeTardisVehicle was asleep; ignored 14 requests for current state
12/15/2021, 11:45:50 AMTesla BridgeTardisHomeLink does not support garage door status.
12/15/2021, 11:45:50 AMTesla BridgeTardisAlways setting garage door state to closed.
12/15/2021, 11:45:51 AMHOOBSRingStopped Live Stream for Front Door
12/15/2021, 11:45:52 AMHOOBSSense Energy MeterReceived data. Watts: 1931.93603515625, Current: 10, Voltage: 122.19225692749023
12/15/2021, 11:45:53 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:53 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:53 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:53 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:53 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:53 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:53 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:45:58 AMTesla BridgeTardisVehicle was asleep; ignored 14 requests for current state
12/15/2021, 11:46:09 AMTesla BridgeTardisHomeLink does not support garage door status.
12/15/2021, 11:46:09 AMTesla BridgeTardisAlways setting garage door state to closed.
12/15/2021, 11:46:12 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:12 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:12 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:12 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:12 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:12 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:12 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:17 AMTesla BridgeTardisVehicle was asleep; ignored 14 requests for current state
12/15/2021, 11:46:20 AMTesla BridgeTardisHomeLink does not support garage door status.
12/15/2021, 11:46:20 AMTesla BridgeTardisAlways setting garage door state to closed.
12/15/2021, 11:46:23 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:23 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:23 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Target State] The read handler for the characteristic 'Lock Target State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:23 AMTesla BridgeERROR[Tesla Bridge E7E1@Lock Current State] The read handler for the characteristic 'Lock Current State' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:23 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:23 AMTesla BridgeERROR[Tesla Bridge E7E1@On] The read handler for the characteristic 'On' on the accessory 'Tardis' was slow to respond!
12/15/2021, 11:46:28 AMTesla BridgeTardisVehicle was asleep; ignored 14 requests for current state

**Comment by askovi** [comment]
Logs are reporting that your tesla is asleep. That's why you see the accessories as not responding. First try waking it up from the tesla app and restart the home app to see if they start responding.

**Comment by bngoofy** [comment]
I ve been in the tesla with it running and get the same response. Some things work intermittently

**Comment by BobbySlope** [comment]
Please check the open issues with the developer of the plugin:

https://github.com/nfarina/homebridge-tesla/issues

Or create a new issue there
Not much we can do here
