### ISSUE TITLE
HOOBS Client Upgrade failure

### ISSUE THREAD

**Issue by hapinstance** [hoobs-org/HOOBS#1715]
While upgrading to version 4.1.18 from version 4.1.11 i received the following error.  Three packages generate this error: helm, hoobs-cli hoobsd.  Please advise on how to fix.

hoobs@hoobs:~ $ sudo apt-get install hoobs-cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hoobs-cli : Depends: nodejs (>= 16.13.0) but 14.18.2-deb-1nodesource1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by jzuhone** [comment]
I'm getting this error too.

**Comment by askovi** [comment]
Try running this fix command:

`curl -sk https://dl.hoobs.org/fix | sudo bash -
`

**Comment by hapinstance** [comment]
That seems to have worked.  Thanks!
