### ISSUE TITLE
V 4.0.109 refuses to update

### ISSUE THREAD

**Issue by Wish2021** [hoobs-org/HOOBS#1717]
does anyone have a solution for Hoobs not updating system software?  I've been stuck at V. 4.0.109 for a month.  I've rebooted Hoobs and my Mac with no success.

The update window just spins.

**Comment by askovi** [comment]
Please run this fix command from the HOOBS terminal: 

`curl -sk https://dl.hoobs.org/fix | sudo bash -`

**Comment by Calorion** [comment]
I did that and now the HOOBS interface is not loading.

**Comment by BobbySlope** [comment]
Try the following 

hoobs.local
hoobs/
Or the ip adress given by your router

**Comment by jwvanderbeck** [comment]
Having I think the same issue trying to update from 4.1.11.  I purchased the prebuilt Homebridge in a box thing.  I click update and it fails with the following information:

```12:40:17 PMSome packages could not be installed. This may mean that you have
12:40:17 PMrequested an impossible situation or if you are using the unstable
12:40:17 PMdistribution that some required packages have not yet been created
12:40:17 PMor been moved out of Incoming.
12:40:17 PMThe following information may help to resolve the situation:
12:40:17 PMThe following packages have unmet dependencies:
12:40:18 PMhoobs-cli : Depends: nodejs (>= 16.13.0) but 14.18.2-deb-1nodesource1 is to be installed
12:40:18 PMhoobsd : Depends: nodejs (>= 16.13.0) but 14.18.2-deb-1nodesource1 is to be installed
12:40:18 PME: Unable to correct problems, you have held broken packages.
12:40:18 PMWARNINGservice restart command received
12:40:13 PMrestarting```

I tried SSHing into the device to run the above command but the username/pw I use to login to the webapp doesn't appear to work for SSH.

**Comment by Calorion** [comment]
> Try the following
> 
> hoobs.local hoobs/ Or the ip adress given by your router

I did all of that, but nothing worked. I eventually used the CLI to restore to factory settings, reinstall, and reload a backup, which worked—and, indeed, solved other problems.
