### ISSUE TITLE
Hoobs box is dead

### ISSUE THREAD

**Issue by hassanshahin1** [hoobs-org/HOOBS#1718]
Got the box two days ago. Connected it to WiFi and did the updates and plugins/bridges for SmartThings, ring and MyQ. Less than 24 hours later, it disappeared from my network. Tried the IP address and win Terminal with no luck. Tried to connect directly to router, didn’t work. I read about opening the box and flashing the SD card but don’t won’t to lose the right to return it since the screws are covered with plastic which will need to be removed first.

**Comment by BobbySlope** [comment]
Please send an email to ***@***.*** with your order number and 
reference this issue.

Cheers,
Ovi @ hoobs.org

**Comment by askovi** [comment]
Please send an email to support@hoobs.com with your order number and reference this issue.
