### ISSUE TITLE
installation on macOS

### ISSUE THREAD

**Issue by ravedoglv** [hoobs-org/HOOBS#1720]
Honestly. I don’t have the time or the patience or mostly the intellect to fix a problem. Someone fucked my install of HOOBS 3.x by installing Scrypted on my Mac. HOOBS is broken. Don’t know how to fix. I will pay someone from HOOBS to help me sort this out.

I have saved config and system setting from 3.x 

I have 22 devices offline and just would rather pay someone to help. I am not in a position to solve this on my own.

please help

**Comment by ravedoglv** [comment]
Tried reinstalling HOOBS for. The Mac cli using

`npm install -g --unsafe-perm @hoobs/hoobs`

and got this:
env: node: No such file or directory

What does this mean?

**Comment by ravedoglv** [comment]
So I did some googling. Apparently mode was too far ahead. And after digging thru old closed issues, I found this command 

wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts

Then I ran

sudo npm install -g --unsafe-perm @hoobs/hoobs

**Comment by databoy01** [comment]
BINGO!

**Comment by BobbySlope** [comment]
Heres the link to an macOS installation package:

https://github.com/hoobs-org/image/releases/download/v4.1.17/hoobs-v4.1.17-darwin.pkg

Try to install this one.

**Comment by GoWithitRoger** [comment]
@ravedoglv — Did you ever find a better solution to this? I'm trying to install on a Mac, as well.

The MacOS package @bobbyslope posted installs just fine, but I don't see that it's installing the server/service, just the HOOBS Desktop application, which reports "No devices". 

That wget command sequence you posted eventually worked for me. And simply running the command 'hoobs' works:
`HOOBS listening on port 80.
No plugins installed.
Bridge is running on port 51826.`

I can raise the admin interface in a browser on the machine's IP and port 80. 
But it's v3.xsomething, not the v4 I've seen is the current version.
