### ISSUE TITLE
Mac app issue

### ISSUE THREAD

**Issue by Ooblek33** [hoobs-org/HOOBS#1723]
**Description**
The hoobs app on MAC doesn’t seem to work. I have used multiple Mac computers and OS operating systems. After the download, the app shows that it is on an old version and will not allow me to update. I am also unable to download plugins. 

**Version**
The current version of the app is 4.1.17. 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
I can’t remember the previous version. 

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No, not that I recall. 

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Bond, ring, Vivint, Wemo, myQ. 

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by frios** [comment]
I have the same problem. Stuck on version 4.0.104

**Comment by BobbySlope** [comment]
Try to run the fix command:

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3
