### ISSUE TITLE
Hoobs not responding 

### ISSUE THREAD

**Issue by Kmh7777** [hoobs-org/HOOBS#1726]
Hoobs not connecting to the router, not showing in Hoobs.local. How can I do factory hard reset please?

**Comment by Kmh7777** [comment]
I bought it less than a month and now is dead. Please help

**Comment by mkellsy** [comment]
Please send an email to info@hoobs.com. We can further troubleshoot and replace if needed.

**Comment by Kmh7777** [comment]
I did already sir. Still no answer.

**Comment by Kmh7777** [comment]
Hello there, I sent email to info@hoobs.com, still no reply. Can you help or return the product for refund?

Thanks
