### ISSUE TITLE
Upgrade Failure

### ISSUE THREAD

**Issue by Peltier36** [hoobs-org/HOOBS#1727]
**Description**
attempted to upgrade to the new version and now the device will not stay on nor will it allow me to remote into it. 
**Version**
Please include the version of HOOBS you are using.
4.0.1
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by wsr554** [comment]
I am having the same problem.

**Comment by askovi** [comment]
Are you able to access the recovery terminal at http://hoobs.local:9090 ?

If you can then run this fix command:

    curl -sk https://dl.hoobs.org/fix | sudo bash -

**Comment by Peltier36** [comment]
It ask for a login and password

**Comment by askovi** [comment]
Login: hoobs 
Password: hoobsadmin

You will be prompted to change the default password upon first login.

**Comment by wsr554** [comment]
@askovi I can't get in, the page only times out.

**Comment by wsr554** [comment]
Got this help for Trey- 

Please follow the below guide to reflash
You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
Download the App BalenaEtcher - https://www.balena.io/etcher/
Download the HOOBS Image - https://support.hoobs.org/downloads/image?platform=armhf
From the download folder - Load the .zip file in the BalenaEtcher. If you are using a Mac - the file is automatically decompressed and moved to the trash bin. Restore the file to your download folder
Click on flash
Once the process is over - insert the card back into the board. Close the box with the screws. Plug the ethernet cable and then power the device.

**Comment by Peltier36** [comment]
I’ve now tried this along with reflashing the SD card 100 times to no avail. I’m about to get back in but once I’m back in nothing works… the plugins that are downloaded do not work and the bridges often stop themselves along with the system completely shutting itself down. What can be done for me to get a replacement unit? I’ve barely had it for a year and I’ve had a lot of issues with this unit. Please advise on what the next steps to proceed are.

**Comment by mkellsy** [comment]
Please send an email to info@hoobs.com.

Sounds like we need to do RMA this device.
