### ISSUE TITLE
New SD card will not boot in to HOOBS

### ISSUE THREAD

**Issue by kammieb** [hoobs-org/HOOBS#1728]
When I insert my brand new SD card with Hoobs preloaded on it, it hangs at the following line “random: crng init done. My keyboard does not work either when I try to select enter maybe input a command or anything. Can anyone assist me with this?

**Comment by grangej** [comment]
I am also seeing the exact same issue, what am I doing wrong?

**Comment by grangej** [comment]
FYI I downloaded the image / re-flashed the SD card and everything worked after that. It seems the image on the pre-flashed card is not working.

**Comment by kammieb** [comment]
Thank you for that tip and I will definitely try that out.

**Comment by mkellsy** [comment]
What device are you using pi3 or pi4?

Also send an email to info@hoobs.com, we can send you a new SD card. Be sure to note if you plan on using this on a pi3 or pi4.

**Comment by hephalump** [comment]
Same issue here. Received my new SD card yesterday and it won't boot.
