### ISSUE TITLE
Cant open Terminal 

### ISSUE THREAD

**Issue by nfstange** [hoobs-org/HOOBS#1729]
**Description**
When I want to open terminal it asks for username and password and I have tried my hoobs login and computer login 
**Version**
4.0.104
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [/ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [/ ] HOOBS SD Card
- [ ] Custom Install

**Comment by mkellsy** [comment]
The default password is **hoobsadmin**

**Comment by nfstange** [comment]
> The default password is **hoobsadmin**

if my login is my username and that’s the password it still doesn’t work keeps bringing back login screen for terminal

**Comment by mkellsy** [comment]
The terminal is not the same as the UI credentials. These are system credentials.

Username: hoobs
Password: hoobsadmin

On first login it will ask you to change the password.
