### ISSUE TITLE
Terminal not login

### ISSUE THREAD

**Issue by svharishtech** [hoobs-org/HOOBS#1731]
Terminal not working with default credentials

**Version**
 4.0.92

**Did you upgrade**
Yes. upgraded to V4 when it was launched initially

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box

I am using the default password to log into terminal
User: hoobs
pwd: hoobsadmin

It is not working and keeps on asking for username and password.

**Comment by mkellsy** [comment]
The terminal asks you to change the password on first login.
If you forgot this password, you can reset the terminal from the config screen.

Config Screen (Gear on the bottom left) -> Hub section -> Click Reset Terminal

Then you can use
username: hoobs
password: hoobsadmin

It will again ask you to change this password.
