### ISSUE TITLE
HOOBs Temp

### ISSUE THREAD

**Issue by Ehreckk** [hoobs-org/HOOBS#1732]
My HOOBs seems to be running quite hot. What can I do to cool it down?

**Comment by BobbySlope** [comment]
Whats Temperatures ste you getting?
The temperature shown in the dashboard widget is measured inside the cpu and not on the outside.

**Comment by Ehreckk** [comment]
The dashboard is showing anywhere between 62°C - 66°C in idle

**Comment by BobbySlope** [comment]
Thats normal operating Temperature. 
60-80 Degree Celsius are absolutely ok

**Comment by Ehreckk** [comment]
Oh fantastic! I was told otherwise on the Facebook group community!
