### ISSUE TITLE
I cant log into hoobs app either on my mac or on my pc. User name and password i just created doesnt work

### ISSUE THREAD

**Issue by richardruthven** [hoobs-org/HOOBS#1733]

**Comment by BobbySlope** [comment]
We need more information to help you

**Comment by richardruthven** [comment]
I cant log into the app, either on mac or on pc. it recognices my device but then user name and password arent accepted. Why would you need more info than this?

**Comment by BobbySlope** [comment]
https://support.hoobs.org/topics/61c8d87e4d578544831c25f6/61c8d8b04d578544831c2650
