### ISSUE TITLE
Order / Shipping / Taxes / Return or Replacement requests

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#1735]
If you have any Questions about your Order / Shipping / Taxes / Return or Replacement please contact us via Email to support@hoobs.com

**Comment by GordTessier** [comment]
Hi, I would lkke to return my unit. It does not do what I need it to. I sent an email a few days ago but no one responded. What do I need to do to send it back? It was purchased Dec 18, 2021.
Thanks,
Gord
