### ISSUE TITLE
Cleanup Fibaro plugins

### ISSUE THREAD

**Issue by ilcato** [hoobs-org/HOOBS#1738]
**Is your feature request related to a problem? Please describe.**
In the plugin repository there's a confusion regarding the Fibaro plugins I developed

**Describe the solution you'd like**
The only plugin the should be listed is "Fibaro Home Center" that works with all Fibaro Home Center devices.
"Fibaro HC3" is the old name of "Fibaro Home Center" and points to the same github repository.
"Fibaro HC2" is no longer supported. Fibaro Home Center 2 works with "Fibaro Home Center" plugin.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by BobbySlope** [comment]
Hello, iv banned the old one and certified the new plugin. Please check out our plugins page and give me a feedback if its ok.

**Comment by ilcato** [comment]
Perfect
