### ISSUE TITLE
Re-Image Hoobs in a box to solve login issues

### ISSUE THREAD

**Issue by CoryC12** [hoobs-org/HOOBS#1739]
I have been trying all suggestions online to reset the password on my new hoobs box. Used Putty, used Terminal ssh hoobs@hoobs.local password: hoobsadmin. Access has been denied everytime. I want to re-image the box now. How do I do so? Please help. thank you

**Comment by BobbySlope** [comment]
https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9e060dcf29f5e39f03278
