### ISSUE TITLE
Make password input fields of type "password" 

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#174]
This seems to be done in certified plugins. However in plugins with config.schema support not yet certified, passwords are displayed in clear text inside the input fields of type text. (eg. Ring plugin)

**Comment by mkellsy** [comment]
This needs to be updated in their config.schema. They need to add this to the field;

```
"options": {
    "hidden": true
}
```

It is part of the JSON schema standard. Please bring this up with the plugin developer.

BTW homebridge-ring does not have a config.schema.json file.

**Comment by askovi** [comment]
homebridge-ring does have a config.schema [https://github.com/dgreif/ring/blob/master/homebridge/config.schema.json](https://github.com/dgreif/ring/blob/master/homebridge/config.schema.json)

It shows up properly in the UI with the entire form however I noticed that the password field is of type string
`"password": {
        "title": "Password",
        "type": "string",
        "placeholder": "Password"
      }`

**Comment by askovi** [comment]
I made the required changes and made a pull request on the main repo. You might want to fork for certification.

**Comment by mkellsy** [comment]
Thanks
