### ISSUE TITLE
Hoobs not connecting properly

### ISSUE THREAD

**Issue by Javierg722** [hoobs-org/HOOBS#1740]
I'm having an issue with my HOOBS Box.  When I login in with the ip address from the router on my mobile it opens some windows, but not everything.  The ones it doesn't open just keep going with the loading house icon non-stop.  I'm trying to reset to factory settings (unable to reach through mobile).  When I try to login through desktop, it makes it seem like it isn't connected.  I tried the desktop app, but states invalid ip (I've checked multiple times, it is correct).  I've gone through a few other issues people were having but to no avail.  I CAN login through HeIM.  If I run the "sudo systemctl status hoobsd" command, I am getting the following:

![Hoobs1](https://user-images.githubusercontent.com/89281954/147729291-e45bff1a-8d35-4449-a83d-03711faffe60.PNG)

I've also tried the following commands already:
1.  Command "Sudo Hoobs Service Log" - "sudo:  hoobs: command not found"
2.  Command "rm -fR ~/.hoobs" - Nothing (I assume that deleted the folder?)
3.  Command "wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset" - "Resetting device" which should be to factory settings?  I cannot get it to startup though from scratch.

I'm trying to reset to factory settings because my HomeKit started acting up, but my Hubitat is working perfectly and seems like the bridge to HomeKit is the issue.  Please help...

**Comment by BobbySlope** [comment]
Login via HELM and ru. The Fix command:

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3
