### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Raczka1989** [hoobs-org/HOOBS#1742]
Hallo, wen i go to the Terminal and Login i become this messages 
hoobs@hoobs:~ $  /etc/profile
bash: /etc/profile: Permission denied
hoobs@hoobs:~ $  /home/hoobs/.profile
bash: /home/hoobs/.profile: Permission denied
hoobs@hoobs:~ $  /home/hoobs/.bashrc
bash: /home/hoobs/.bashrc: Permission denied

wen i will write the command "sudo apt update" i become this messages

sudo apt update
[sudo] password for hoobs: 
Hit:1 http://phoscon.de/apt/deconz buster InRelease                                                                                             
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                                                                                   
Hit:3 https://dl.hoobs.org/debian stable InRelease                                                                                                                                          
Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]                                                                                                      
Err:4 https://dl.yarnpkg.com/debian stable InRelease                                                                                                       
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
Hit:5 https://deb.nodesource.com/node_16.x buster InRelease                      
Hit:6 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
[log (1).txt](https://github.com/hoobs-org/HOOBS/files/7795108/log.1.txt)

**Comment by bwp91** [comment]
I looked at some solutions from this site:
https://askubuntu.com/questions/1306111/why-yarn-key-update-failes-all-the-time-gpg-error-https-dl-yarnpkg-com-debia

And there are a couple of terminal commands you could try:

```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
```

or

```
sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
```

If you run these and then a `sudo apt update` afterwards do you have any luck?

**Comment by BobbySlope** [comment]
Basically you dint need to update manually the system the hoobs updates will take care of it. 

If you want to force update your system use this command:

https://support.hoobs.org/topics/61c9e100dcf29f5e39f034fb/61c9e133dcf29f5e39f03535
