### ISSUE TITLE
Probleme mit Hoobs 4.0.. Apple HomeKit, Shellys, ConBee II

### ISSUE THREAD

**Issue by prentnwo** [hoobs-org/HOOBS#1744]
Hello, I hope that I'm in the right place.
And sorry, my english is bad.

My system: Raspberry PI 4 with Micro SD and Hoobs.

Everything went well under Hoobs 3.3.12
Apple HomeKit, Shelly's and ConBee II (Zegbee Gateway)

Then came Hoobs 4.0 ... and the failure was there after the update.
No terminal, Shelly's mess and no ConBee II gateway.

So Hoobs 4.0 ... reloaded, but:
* How do I set the language in German?
* And most importantly: Where is the QR code for the bridge to Apple HomeKit?
* Terminal is now available.

I ask for your support.

Kind regards
Wolfgang P.

**Comment by BobbySlope** [comment]
If your browser/system is set to german it should automatically switch. 

Terminal is now accessible via hoobs.local:9090

**Comment by BobbySlope** [comment]
You can find the qr code in the qr code tab in the user interface. 
Now plugins are splitted into separate bridges each bridge needs to be connected to homekit. This brings more stability into the system as if one plugin fails the other will remain online due to the separation into different bridges.

**Comment by BobbySlope** [comment]
https://support.hoobs.org/topics/61c9e169dcf29f5e39f035bb/61c9e18cdcf29f5e39f035ee

**Comment by BobbySlope** [comment]
And here is the command to install deconz and phoscon via terminal:

`wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/main/scripts/deconz-phoscon-hoobs.sh | sudo bash -`

**Comment by prentnwo** [comment]
Thank you for the quick information.

I will test everything and then get back to you.

Thank you very much WolfgangP.

**Comment by BobbySlope** [comment]
I will close this issue now. You can reopen if needed

**Comment by prentnwo** [comment]
Hello Booby Slope, hello forum help.
I cannot access the terminal in Hoobs 4.0.71, it stays black.
Device MAC OS Catalina: With no browser (Safari, Crome, Firefox)
Crome writes, hoobs.local: 9090 refused the connection.

Unfortunately I can't get any further
MFG prendy

**Comment by prentnwo** [comment]
I opened a new ticket.
Thank you prentnwo
