### ISSUE TITLE
Music app listed as "Certified" but requires Homebridge ver 1.3.9

### ISSUE THREAD

**Issue by mmaxton** [hoobs-org/HOOBS#1745]
This plugin fails to install.  When I tried installing via Terminal command ( sudo npm -g i homebridge-music ), it shows:

:npm WARN notsup Unsupported engine for homebridge-music@0.4.16: wanted: {"homebridge":"^1.3.9","node":"^16.13.1"} (current: {"node":"14.17.6","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-music@0.4.16
npm WARN notsup Unsupported engine for homebridge-lib@5.1.23: wanted: {"homebridge":"^1.3.9","node":"^16.13.1"} (current: {"node":"14.17.6","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@5.1.23

 ------

**Plugin name**
The plugin name listed within HOOBS app is just "Music" 
Looks like from the terminal command line instructions that the npm title is "Homebridge-music"

**Please report the issue to the plugin developer**
I suspect this is not a developer issue, but rather, just that HOOBS is running 1.3.8, one version behind Homebridge

**Version**
I have a brand new, Santa-delivered HOOBS box running 4.1.20. :)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
N/A

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
Sorry, I don't understand your instructions.
* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
I am guessing that this will be fixed when HOOBS upgrades to 1.3.9 ??  I just wondered what the general policy was for showing a plugin as certified, when it isn't really supported by current HOOBS use of slightly older Homebridge version.   

I am new to HOOBS, and am loving it - just wanted to offer some feedback on this.

**Comment by BobbySlope** [comment]
This is just a warning it will work as expected. We will provide an Update to HOOBS that contains homebridge 1.3.9 updates.

**Comment by BobbySlope** [comment]
Try to install the plugin via user interface. It will work as expected ignore the warning. 

We will release the update to homebridge 1.3.9 on tuesday

**Comment by mmaxton** [comment]
Thanks for the prompt reply.  Sorry, should have stated, I did try installing first via the user interface, and got the reply "Unable to install plugin.  Please try again."

But since Homebridge 1.3.9 is imminent, this will soon be a moot point.  As a noob to HOOBS, I didn't know how frequently it was updated, or what the lag time would be for updates to latest version of Homebridge.  

Thanks again.

<img width="1399" alt="Screen Shot 2022-01-02 at 7 08 57 AM" src="https://user-images.githubusercontent.com/95693064/147878437-f93c1ec3-18f0-4e2e-be68-1483c481bc16.png">
