### ISSUE TITLE
Can't update from 4.1.18 to 4.1.20

### ISSUE THREAD

**Issue by MarcoMetzger** [hoobs-org/HOOBS#1746]
I'm currently running 4.1.18 and the dashboard shows an available update to 4.1.20.
When I click update, Hoobs shuts down and shows 4.1.18 with an available update to 4.1.20 after the restart. Therefore the update didn't went through. 

I tried it multiple times via the browser and via the Mac app.

**Comment by mkellsy** [comment]
The fix for this is on our support site.
https://support.hoobs.org/topics/61c9e100dcf29f5e39f034fb/61c9e133dcf29f5e39f03535
