### ISSUE TITLE
Cannot open HOOBS in a BOX web page and HOOBS App cannot find device

### ISSUE THREAD

**Issue by JFG3rd** [hoobs-org/HOOBS#1747]
**Description**
I cannot reach my HOOBS in a BOX device via web browser using name or IP address. The macOS HOOBS application Version 4.1.17 (4.1.17) cannot find the device also.  **The device can be pinged**.
I had updated the device about two weeks ago with no issues.  I was about to add a plugin when this issue started! :(

**Version**
macOS Version 4.1.17 (4.1.17) application.  HOOBS in a BOX version is currently unknown, but I updated the device about two weeks ago??
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

A couple of days ago I had tried to "google" the issue and had found a similar post where the fix was to reimage the SD card in the BOX.  I have not found the post and therefore do not have a link to the HOOBS image. 

Please help.

**Comment by BobbySlope** [comment]
Try to run the fix command:

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3

**Comment by JFG3rd** [comment]
> Try to run the fix command:
> 
> https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3

Hi BobbySlope, thanks for your help, but I cannot SSH into the device either.  I get "kex_exchange_identification: read: Connection reset by peer".

**Comment by mkellsy** [comment]
Can you log into your router to get the IP address

**Comment by mkellsy** [comment]
Can you log into your router to get the IP address?

Also check your phone for the HOOBS (ABC...) access point. If the device can't detect a network it will start the AP.

**Comment by JFG3rd** [comment]
The device is pingable and registers it’s name to DNS. But the web service of the box seems dead. 😢

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BobbySlope** [comment]
try to run the fix command by ssh into the box using the IP Adress instead.

`ssh hoobs@IPADRESS`

**Comment by JFG3rd** [comment]
Hi,
sorry I have been quite busy and could not spend time to repair my Hoobs Box.  Thanks so far for your advices, but none of them work.

**The Heim interface works by the way:**
HOOBS - User Friendly Home Automation for Everyone

Login: 

but I cannot login the login screen just reappears.

**I tried SSH but cannot get a connection. I get the message:**
kex_exchange_identification: read: Connection reset by peer
every time I try.  So all the suggestions will not work.

What I'd like to do is just factory reset the Hoobs Box somehow or reimage the SD card.

Please help!

Best regards, Jesse
