### ISSUE TITLE
No access to the terminal in Hoobs

### ISSUE THREAD

**Issue by prentnwo** [hoobs-org/HOOBS#1750]
Hello forum help.
I cannot access the terminal in Hoobs 4.0.71, it stays black.
Device MAC OS Catalina: With no browser (Safari, Crome, Firefox)
Crome writes, hoobs.local:9090 refused the connection.

Unfortunately I can't get any further
MFG prentwo

**Comment by bwp91** [comment]
Take a look at this to update to HOOBS 4.1.

https://support.hoobs.org/topics/61c9e100dcf29f5e39f034fb/61c9e133dcf29f5e39f03535

**Comment by prentnwo** [comment]
Thank you for the info. I will do an update, I hope it works.
Kind regards
prentnwo
