### ISSUE TITLE
Hue plugin no QR code and other errors

### ISSUE THREAD

**Issue by prentnwo** [hoobs-org/HOOBS#1752]
Hello forum, please for your support.
Sorry, my english is bad.

My system Apple Mac Catalina, Raspberry PI 4 SD card, Hoobs 4.0 .. Update to 4.1.20
Plugin Shelly installed, everything ok. QR code available and the bridge to Apple HomeKit ok.
Then ConBee2 Deconz installed via the terminal, entry via Phoscon possible (ok).

My current problem:
1. When I install the Hue plug-in to connect to Phoscon, no QR code is generated for a new bridge !?
2. Connection errors are written in the Hoobs log and there should be an update from Hue or the plugin.
3. If I create a user code in Phoscon, which is then displayed in the Hoobs log, where and how do you have to enter this in the Hue plugin? The description in the Hue plugin is still stored for Hoobs version 3 ..., ALL SO OLD!?

Ask your support
Kind regards
prentnwo

**Comment by mkellsy** [comment]
Logs?

**Comment by prentnwo** [comment]
I'm currently installing and testing the new one.
I will contact you again.
I will also open a new ticket because there are other problems with Hoobs 4.1 ...

Thank you prentnwo
