### ISSUE TITLE
Cannot access hoobs.local anymore

### ISSUE THREAD

**Issue by psimoons** [hoobs-org/HOOBS#1756]
Installed Hoobs last week and it worked fine for a few days. Yesterday it started to halt unexpectedly and repeatedly. TRied everything including the "curl -sk https://dl.hoobs.org/fix | sudo bash -" command. I can ssh into the box, but no configuration on hoobs.local or IP address available. What to do?

**Comment by mkellsy** [comment]
Send an email to info@hoobs.com so we can troubleshoot and replace if needed.
