### ISSUE TITLE
Hoobs 4, Terminal problems. QR Code problems, and Hue Plugin problems (Ticket #1752)

### ISSUE THREAD

**Issue by prentnwo** [hoobs-org/HOOBS#1757]
Hello forum, please for your support.

Apple Mac Catalina, Raspberry PI 4 SD card, Hoobs 3 ... then 4.0 .. then Update to 4.1.20.

I tested two options.

* Update from HOOBS 3.3.12 to Hoobs 4.1.20:
1. After the update to 4 ... no more terminal available at the three points in the menu at the top right.
2. The QR code with the HOOBS bridge is retained.
3. I need the Hoobs bridge because the Philips HUE plugin does not generate a QR code (bridge) itself.

* Hoobs 4.1.20 installed immediately on the micro SD:
1. The terminal is available.
2. But there is no longer a QR code called HOOBS that creates a bridge to HomeKit.

How do I get the Hoobs QR code and the terminal into the Hoobs platform.

Thank you for your support.
prentnwo

Auf Deutsch:

Ich habe zwei Möglichkeiten getestet.

* Update von HOOBS 3.3.12 auf Hoobs 4.1.20:
1. Nach dem Update auf 4... kein Terminal mehr vorhanden bei den drei Punkten im Menü rechts oben.
2. Der QR-Code mit der HOOBS Brücke bleibt erhalten.
3. Die Hoobs Brücke brauche ich, da das Philips HUE Plugin keinen QR-Code (Brücke) selber erzeugt.

* Hoobs 4.1.20 sofort auf die Micro-SD installiert:
1. Das Terminal steht zur Verfühgung.
2. Es gibt aber keinen QR-Code mehr, der HOOBS heißt und eine Brücke zu HomeKit erzeugt.

Wie bekomme ich den QR-Code Hoobs und das Terminal in die Plattform Hoobs.

Danke für eure Unterstützung.
prentnwo

**Comment by BobbySlope** [comment]
Hallo prentnwo

Du musst zuerst HUE mit der Konfiguration Pairen und dann die Bridge starten. Dann erscheint auch der QR-Code
Der QR wird erst angezeigt wenn die konfiguration abgeschlossen ist und die Bridge ohne probleme Starten kann.

Wenn der QR Code nicht angezeigt wird heisst das das ein fehler in der Config vorliegt, schaue dir dazu die Logs an um zu sehen was genau nicht funktioniert

**Comment by BobbySlope** [comment]
Als erklärung die sich der HOOBS Hub die Bridges und die Plugins zueinander verhalten habe ich die dokumentation angepasst ich hoffe dies hilft weiter:

https://support.hoobs.org/docs/61d58700f049c61239124fe6

**Comment by prentnwo** [comment]
Vielen, vielen Dank!
Ich werde es testen.

prentnwo

**Comment by prentnwo** [comment]
Vielen Dank BobbySlope.
Es funktioniert jetzt soweit wieder alles, Dank deiner Unterstützung.
Es gibt aber noch kleinere Probleme.

Zum Produkt Hoobs: Von selber geht da gar nichts und schon gar nicht selbst erklärend ist Hoobs ;-)

GLG prentnwo
