### ISSUE TITLE
When will Hoobs 4 upgrade to Homebridge 1.39

### ISSUE THREAD

**Issue by Elch08** [hoobs-org/HOOBS#1758]
**Description**
Many Plug-ins like Philips Hue or Wemo now require Homebridge Version 1.39 whereas Hoobs 4 has still version 1.38. When will you upgrade to 1.39 ?

**Version**
Please include the version of HOOBS you are using.
HOOBS 4.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
On a Raspberry Pi 3B

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
For example homebridge-hue or homebridge-wemo

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
we will release the update on tueday

**Comment by jwise-cesmii** [comment]
Checked for updates regularly yesterday, checked again today. Still on 4.0.71, still getting the error that Hoobs is not using 1.39 of Homebridge.

**Comment by BobbySlope** [comment]
Running the fix command will force update to latest version:

https://support.hoobs.org/topics/61c9e100dcf29f5e39f034fb/61c9e133dcf29f5e39f03535
