### ISSUE TITLE
Homebridge version update

### ISSUE THREAD

**Issue by 49jpg** [hoobs-org/HOOBS#1760]
How can I update the homebridge version from 1.3.4 to 1.3.9?
I have updated some of my plugins and received this error: "[31mThe plugin "homebridge-ewelink" requires a Homebridge version of ^1.3.9 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m"

Thanks!

**Comment by bwp91** [comment]
You should update HOOBS to the latest 4.1 version

**Comment by 49jpg** [comment]
I have 4.0.110 but when I check for updates I received this "You're up to date."

**Comment by BobbySlope** [comment]
Try to run the fix command:

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3

**Comment by mkellsy** [comment]
1.3.9 is in version 4.1.21.
However it looks like your Node version is stuck on the old 14x LTS version.
You have to get Node updated to the new 16x LTS version.

The fix command can take care of this for you. This support article will help you.
https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3
