### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by whittenk** [hoobs-org/HOOBS#1762]
Is there a plugin planned for Feet Electric devices?

**Comment by whittenk** [comment]
FEIT, not FEET

**Comment by askovi** [comment]
Feit are just rebranded Tuya devices. Add them to the Tuya app or the Smart Life app then install a tuya plugin in HOOBS to control them.

**Comment by whittenk** [comment]
Awesome! And Thank You for the quick reply!
