### ISSUE TITLE
Terminal login for configuration

### ISSUE THREAD

**Issue by whittenk** [hoobs-org/HOOBS#1764]
I cannot login to the terminal. Have used suggested login and password in configuration, have used hub login and password. What am I missing?

**Comment by mkellsy** [comment]
The terminal is different than the UI. The default username is **hoobs** and the default password is **hoobsadmin**.
https://support.hoobs.org/topics/61c8d87e4d578544831c25f6/61c8d8cb4d578544831c269f

**Comment by whittenk** [comment]
That worked. Thanks Michael
