### ISSUE TITLE
roomba2bridge config

### ISSUE THREAD

**Issue by whittenk** [hoobs-org/HOOBS#1765]
when I copy and paste cd /var/lib/hoobs/_BRIDGE ID_/node_modules/dorita980
I get bash: cd: too many arguments
after first command, I see ID is roomba2bridge
where do I put this in the command?
replace _BRIDGE ID_  or dorita980?
Thanks

**Comment by mkellsy** [comment]
```
cd /var/lib/hoobs/roomba2bridge/node_modules/dorita980
```

**Comment by whittenk** [comment]
Thanks Michael
