### ISSUE TITLE
Migration HOOBS V.3.3.12 vs 4.1

### ISSUE THREAD

**Issue by Stewart06** [hoobs-org/HOOBS#1766]
Bonjour, je suis actuellement sur la version 3.3.12 et j'aurais souhaité passer a la version 4.1 mais elle ne m'est pas proposé dans l'interface de HOOBS.

Que faire ?

Hello, I am currently on version 3.3.12 and I would have liked to upgrade to version 4.1 but it is not offered to me in the HOOBS interface.

What to do ?

**Comment by BobbySlope** [comment]
On which hardware are you running HOOBS

**Comment by Stewart06** [comment]
Raspberry Pi 4

Cordialement.

**Comment by Stewart06** [comment]
[cid:FE980F05-EFFB-4807-BDD0-38112F5633EA]

Cordialement.

Le 8 janv. 2022 à 20:08, BobbySlope ***@***.******@***.***>> a écrit :



On which hardware are you running HOOBS

**Comment by Stewart06** [comment]
![Capture d’écran 2022-01-08 à 20 55 49](https://user-images.githubusercontent.com/63004191/148662952-9d808ea5-14b8-4b6b-a242-ae986e74e219.png)

**Comment by BobbySlope** [comment]
check this:
https://support.hoobs.org/docs/60e62a926c19a6a5ca8f4f42

**Comment by Stewart06** [comment]
Bonjour,

La migration vers HOOBS 4.0 n’a absolument pas fonctionné et m’a complètement cassé ma config.
Obligé de repartir de zéro avec une configuration vierge, deux jours de travail pour tout refaire.

J’ai malheureusement quelque plugin que je n’arrive pas à configurer.

Le premier plugin qui est des plus important pour moi est : Samsung Tizen.

Pourrais-je avoir de l’aide pour tout le configurer ?

Existe-t-il une app capable de convertir l’ancienne configuration vers la nouvelle ?

Cordialement.

Hello,

 Migration to HOOBS 4.0 absolutely didn't work and completely broke my setup.
 Forced to start from scratch with a blank configuration, two days of work to redo everything.

 Unfortunately I have some plugin that I cannot configure.

 The first plugin that is most important to me is: Samsung Tizen.

 Could I have some help setting it all up?

 Is there an app capable of converting the old configuration to the new one?

 Cordially.

Le 9 janv. 2022 à 16:58, BobbySlope ***@***.***> a écrit :

﻿

check this:
https://support.hoobs.org/docs/60e62a926c19a6a5ca8f4f42

**Comment by Stewart06** [comment]
[
    {
        "name": "Samsung Parentale »,
        "keys": {
            "INFORMATION": "KEY_HOME"
        },
        "ip": "192.168.******",
        "switches": [
            {
                "mute": true,
                "name": "Mute"
            },
            {
                "command": "KEY_VOLUP",
                "name": "Vol +"
            },
            {
                "command": "KEY_VOLDOWN",
                "name": "Vol -"
            },
            {
                "sleep": 90,
                "name": "Veille"
            }
        ],
        "inputs": [
            {
                "type": "app",
                "value": "3201611011210",
                "name": "1 - Molotov"
            },
            {
                "type": "app",
                "value": "11101200001",
                "name": "2 - Netflix"
            },
            {
                "type": "app",
                "value": "3201512006785",
                "name": "3 - Prime Video"
            },
            {
                "type": "app",
                "value": "3201901017640",
                "name": "4 - Disney+"
            },
            {
                "type": "app",
                "value": "111299001912",
                "name": "5 - YouTube"
            },
            {
                "type": "command",
                "value": [
                    "KEY_SOURCE",
                    "KEY_LEFT*6",
                    "KEY_RIGHT*3",
                    "KEY_ENTER"
                ],
                "name": "5 - FreeBox Tv"
            },
            {
                "type": "command",
                "value": [
                    "KEY_SOURCE",
                    "KEY_LEFT*6",
                    "KEY_RIGHT*1",
                    "KEY_ENTER"
                ],
                "name": "7 - Fire Stick Tv HD"
            }
        ],
        "refresh": 2000,
        "mac": "*************"
    },
    {
        "name": "Samsung Salon",
        "keys": {
            "INFORMATION": "KEY_HOME"
        },
        "ip": "192.168.*****",
        "method": "frame",
        "switches": [
            {
                "mute": true,
                "name": "Mute"
            },
            {
                "command": "KEY_VOLUP*2",
                "name": "Vol +"
            },
            {
                "command": "KEY_VOLDOWN*2",
                "name": "Vol -"
            }
        ],
        "inputs": [
            {
                "value": [
                    "KEY_HOME",
                    "KEY_LEFT*17",
                    "KEY_RIGHT*2",
                    "KEY_ENTER",
                    "KEY_LEFT*4",
                    "KEY_ENTER*1"
                ],
                "name": "1 - Direct TV",
                "type": "command"
            },
            {
                "value": "111299001912",
                "name": "2 - YouTube",
                "type": "app"
            },
            {
                "value": "11101200001",
                "name": "3 - Netflix",
                "type": "app"
            },
            {
                "value": "3201512006785",
                "name": "4 - Prime Video",
                "type": "app"
            },
            {
                "value": "3201901017640",
                "name": "5 - Disney+",
                "type": "app"
            },
            {
                "value": [
                    "KEY_HOME",
                    "KEY_LEFT*17",
                    "KEY_RIGHT*2",
                    "KEY_ENTER",
                    "KEY_LEFT*4",
                    "KEY_RIGHT*3",
                    "KEY_ENTER*1"
                ],
                "name": "6 - Xiaomi Mi Box",
                "type": "command"
            },
            {
                "value": [
                    "KEY_HOME",
                    "KEY_LEFT*17",
                    "KEY_RIGHT*2",
                    "KEY_ENTER",
                    "KEY_LEFT*4",
                    "KEY_RIGHT*4",
                    "KEY_ENTER*1"
                ],
                "name": "7 - Nintendo Switch",
                "type": "command"
            },
            {
                "value": [
                    "KEY_HOME",
                    "KEY_LEFT*17",
                    "KEY_RIGHT*2",
                    "KEY_ENTER",
                    "KEY_LEFT*4",
                    "KEY_RIGHT*1",
                    "KEY_ENTER*1"
                ],
                "name": "8 - PlayStation 4",
                "type": "command"
            }
        ],
        "refresh": 2000,
        "mac": "***************"
    }
]

**Comment by Stewart06** [comment]
C'est bon j'ai réussi !
