### ISSUE TITLE
Hoobs Update from 3 to 4.0

### ISSUE THREAD

**Issue by prentnwo** [hoobs-org/HOOBS#1768]
Hello forum, please for your support.

Apple Mac Catalina, Raspberry PI 4 SD card

Is there a possibility,

from Hoobs 3.3.12 to 4.0 .. and not to update to 4.1.20?
Update 4.1.20 is always suggested.

4.0 .. I have it as a download date.
But I want to update to 4.0 .. in the Hoobs program and not re-record the SD card with 4.0 ...

Thank you for your support
prentnwo

**Comment by BobbySlope** [comment]
Why you should not update to 4.1.20?

**Comment by prentnwo** [comment]
Warum nicht gleich auf 4.0.21:

Hallo BoobySlope.

Wenn ich von 3.3.12 auf 4.1.21 update habe ich zwar kein Terminal Eintrag bei den drei Punkten rechts oben in der Hoobs Ansicht, aber es bleibt die Hoobs Brücke bestehen.

Wenn ich aber zuerst von 3.3.12 auf 4.0.31 update, bleibt die Hoobs Brücke und ich kann dann diese Reparatur auf 4.1.21 durchführen (https://support.hoobs.org/topics/61c9e100dcf29f5e39f034fb/61c9e133dcf29f5e39f03535) und es erscheint dann möglicherweise das Terminal in der Benutzeroberfläche von Hoobs + Terminal.

Das ist auch nicht so wenn ich die SD-Karte gleich neu installiere mit 4.1.21, da gibt es dann keine Hoobs Brücke mehr.
Es köönte ja sein das ich die alte Hoobs Brücke einmal brauchen könnte? Oder nicht mehr?

Vielen Dank an dich.

prentnwo

**Comment by BobbySlope** [comment]
Das Temrinal ist bei allen künftigen releases über HELM auf hoobs.local:9090 erreichbar und nicht mehr direkt aus dem userinterface.

Die HOOBS Brücke wir zukünftig so nicht mehr benötigt
