### ISSUE TITLE
Hoobs 4 crashes several times per day

### ISSUE THREAD

**Issue by Elch08** [hoobs-org/HOOBS#1769]
**Description**

My Homebridge needs to restart several times per day. I have 15 Bridges with alltogether 17 Plugins installed. After a restart Hoobs4 respectivly Homebridge runs for sometimes 3, sometimes only 1 hour and suddenly something causes it crashing.
I had opened a similar issue, but it was transferred to somewhere, and I could not find it. Down below you find as a detailed Error log. What I did was stopping 14 out of 15 Bridges and than restarting additional bridges which I suspected to be the culprid one by one. Last night the crash reoccurred and I think it has to do with Homebridge-people-x Plugin. But I am not sure. Can you please look into it and give me advise ?

**Version**
Please include the version of HOOBS you are using.

Version 4.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Raspberry Pi 3B

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Homebridge-nest
Homebridge-people-x
Homebridge-shelly
Homebridge-Lifx-lan
Homebridge-nuki
Homebridge-delay-switch
homebridge-dummy
homebridge-fritz
homebridge-alexa
homebridge-dyson-pure-cool
homebridge-hue
homebridge-wemo
homebridge-doorbird
Homebridge-fritz-platform
Homebridge-samsung-tizen
Homebridge-harmony
Homebridge-roomba2

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```

8.1.2022, 23:02:30 People X Bridge starting
8.1.2022, 23:02:36 People X Bridge Loaded plugin 'homebridge-people-x'
8.1.2022, 23:02:42 People X Bridge Loading 1 platforms...
8.1.2022, 23:02:42 People X Bridge PeopleX WebHook: Started server on port '51828'
8.1.2022, 23:02:42 People X Bridge Bridge is running on port 51936,
8.1.2022, 23:02:42 People X Bridge PeopleX Changed occupancy state for 192.168.1.62 to true. Last successful ping 2022-01-08T23:02:42+01:00, last webhook none .
8.1.2022, 23:02:42 People X Bridge PeopleX Changed occupancy state for 192.168.1.79 to true. Last successful ping 2022-01-08T23:02:42+01:00, last webhook none .
9.1.2022, 05:55:37 FEHLER Error: Channel closed
at new NodeError (node: internal/errors: 371:5)
at ChildProcess.target.send (node:internal/child_process:721:16)
at/usr/src/hub/services/socket.ts:66:33
at new Promise (<anonymous>)
at Socket.fetch(/usr/src/hub/services/socket.ts:50:16)
at/usr/src/hub/services/ipc.ts:39:41
at new Promise (<anonymous>)
at HubIPC.fetch(/usr/src/hub/services/ipc.ts:35:16)
at/usr/src/hub/services/monitor.ts:35:28
at new Promise (<anonymous>)
at Monitor (/usr/src/hub/services/monitor.ts:34:24)
at Timeout._a [as _onTimeout] (/usr/src/hub/services/monitor.ts:88:44)
at
listOnTimeout (node: internal/timers:557:17)
at processTimers (node: internal/timers:500:71
9.1.2022, 05:55:37 People X Bridge stopping
9.1.2022, 05:55:37 Shell Bridge stopping
9.1.2022. 05:55:37 Doorbird Bridge stopping
```

**Additional context**

**Comment by BobbySlope** [comment]
this is the same issue, closing this one
https://github.com/hoobs-org/hoobsd/issues/105
