### ISSUE TITLE
Add a 'Remember Me' option on the login form

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#177]
If checked, keep logged in indefinitely, otherwise expire session after time set in settings.
Additionally, in settings, Log Out After, should have an indication that 60 minutes is max in the description text, before saving.

**Comment by mkellsy** [comment]
I added a remember me option. This actually extends the ttl to 1 year. Also if HOOBS reboots you will be required to login. This is done for security reasons.

Dine in 3.0.0-beta.60
