### ISSUE TITLE
Hoobs offers plugin update although it is already updated

### ISSUE THREAD

**Issue by svobod3** [hoobs-org/HOOBS#1771]
**Description**
I am facing problem with Harmony plugin (https://plugins.hoobs.org/plugin/homebridge-harmony).
In Check for update section Hoobs still offers me update to version 1.5.4 although I already installed it and plugin has this version.
When I click on Update button, log below follows, but nothing happends. When I connect to Hoobs again, situation remains the same.

_10:57:44Hit:1 http://deb.debian.org/debian bullseye InRelease
10:57:44Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
10:57:44Hit:3 https://deb.nodesource.com/node_16.x bullseye InRelease
10:57:44Hit:4 https://dl.hoobs.org/debian stable InRelease
10:57:44Hit:5 https://dl.yarnpkg.com/debian stable InRelease
10:57:44Reading package lists..._

In the past I just ignored it but when hoobs version 4.1.21 was release and offered I was not able to update it. When I clicked on Update button (one button for both plugin and hoobs update) it tried to update plugin first and got stuck. So I had to uninstall the plugin, update hoobs and install plugin again.
Can you help me with this? Or is it plugin related problem?

**Version**
4.1.21

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
See if this helps you: https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3

**Comment by svobod3** [comment]
Thanks for the answer.
But I am facing 2 issues.
1) when I wanted to use mac terminal and used ssh hoobs@192.168.1.34 command, I got following answer:

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:KimSyfOBRVmdfV5ZeAUEGfkctpzUuu4FZgR3YJjG9fc.
Please contact your system administrator.
Add correct host key in /Users/jirisvoboda/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/jirisvoboda/.ssh/known_hosts:2
Host key for 192.168.1.34 has changed and you have requested strict checking.
Host key verification failed.

2) when I wanted to use GUI terminal, I was asked for login and password ( I used hoobs and hoobsadmin), but after adding password and using Enter, it took a few seconds and login request appeared again

Could you help me with this?

**Comment by mkellsy** [comment]
Edit this file
nano /Users/jirisvoboda/.ssh/known_hosts

Remove the line for 192.168.1.34.
If you are having a tough time finding it, clear the entire file.

**Comment by svobod3** [comment]
Great, thanks, ssh access via terminal works again. But I am not able to log in (by hoobsadmin password) - Permission denied, please try again.
Is there any way how to discover/change this password?

**Comment by mkellsy** [comment]
If you lost the password for the terminal. You can reset it from the UI.
If you lost the UI password, you can reset it via the terminal.
If you lost both the UI and terminal passwords, you will need to re-flash.

Resetting the terminal password.  
https://support.hoobs.org/topics/61c8d87e4d578544831c25f6/how-do-i-reset-the-terminal-password  
The default username is **hoobs** and the default password is **hoobsadmin**.

Resetting the UI password.  
https://support.hoobs.org/topics/61c8d87e4d578544831c25f6/how-do-i-reset-my-hoobs-password.

If you can't remember any of the passwords, you are locked out. The only way is to re-flash and all data will be lost.

**Comment by svobod3** [comment]
Thanks a lot for the description how to reset terminal password from UI.
But I do not see Reset terminal button.
On main UI screen I click on 3 dots (right upper part, next to the ring symbol), go to Hub settings and there is no mentioned button (see picture below).
Am I doing something wrong?
<img width="769" alt="Hub" src="https://user-images.githubusercontent.com/79516491/150746545-ba6a9754-92ec-4916-8490-f9dd42397909.png">

**Comment by mkellsy** [comment]
Click on the Configuration screen (Gear on the bottom left).
Then click Hub in the bridge list.
Then click Reset Terminal.

**Comment by svobod3** [comment]
thanks a lot, it helped
