### ISSUE TITLE
Tuya configuration

### ISSUE THREAD

**Issue by NebuNC2** [hoobs-org/HOOBS#1772]
Hello, 
I try to configure the Tuya plugin but I dont know how.
What du I need to write here?
![grafik](https://user-images.githubusercontent.com/75451781/148927561-5f709ba2-1d71-4cfa-b287-a89461cddf8f.png)

Thanks for your help

**Comment by mkellsy** [comment]
Need to refresh schemas.
Click the main menu (top right, 2 dots)
Then go to Hub Settings.
Then click the Clear Cache button.

refresh your screen and the guided config will be there.

**Comment by NebuNC2** [comment]
Thanks for help. Now I'm connected. But the devices I can see in the SmartLife App are not shown in Hoobs or in the Tuya IoT Platform. 
Could you help again?
