### ISSUE TITLE
Hoobs 4 Docker

### ISSUE THREAD

**Issue by mbaiti** [hoobs-org/HOOBS#1774]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Docker Image should be updated to Version 4.
Today the latest version is 3.3.5 which is updated 10 months ago

**Describe alternatives you've considered**
No alternatives or maybe install Homebridge? ;)

**Additional context**
Are there any plans or schedule for releasing Hoobs 4 docker image?

**Comment by bigdant** [comment]
Hi,

Hoobs is in the Unraid app store (Which is amazing), however its still the old verion.

Could you please, please set-up a nightly or weekly update to the most recent Hoobs 4 and all us Unraiders will be eternally gratefull !

Thanks

D.

**Comment by JulianKropp** [comment]
I think i got a solution with docker compose and a dockerfile:

0. You need to have docker and docker compose installed. Have a look here if you dont:
https://dev.to/elalemanyo/how-to-install-docker-and-docker-compose-on-raspberry-pi-1mo

1. Create a file named `docker-compose.yml`:
```yml
version: "3"

services:
  hoobs:
    container_name: hoobs
    build: .
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./data:/var/lib/hoobs
```

2. Create a file named `dockerfile` in the same folder:
```
FROM debian

RUN apt update && apt install wget curl lsb-release sudo -y
RUN wget -qO- https://dl.hoobs.org/stable | bash -
RUN apt install hoobsd hoobs-cli hoobs-gui -y
RUN sudo hbs install -p 80

CMD ["/usr/bin/hoobsd", "hub"]
```

3. Create a folder named `data`:
`mkdir data`

4. In this data folder (`cd data`) create a file named `bridges.conf`:
```
[{"id":"hub","type":"hub","display":"Hub","port":80,"pin":"031-45-154","username":"20:D9:EE:46:32:35","autostart":0}]
```
Note: Here you can change the default port from 80 to something else if you want (`port":80`).

5. Go back to the docker-compose.yml file (`cd ..`)

6. Start docker with `docker-compose up -d`

DONE

**Comment by dehness** [comment]
@JulianKropp thanks bro! Worked perfect on the latest Unraid.

**Comment by Jens-Wymeersch** [comment]
@JulianKropp Thank you so much. Just wondering if you made a similar script for hoobs 5 ?

**Comment by JulianKropp** [comment]
@Jens-Wymeersch It seams like Hoobs 5 is closed source. Last release 2 years ago. https://github.com/hoobs-org/HOOBS  If you find the code I could build a docker img.

**Comment by Jens-Wymeersch** [comment]
@JulianKropp If I buy an image from Hoobs. You would be able to make a docker image ?

**Comment by JulianKropp** [comment]
@Jens-Wymeersch Maybe. But this could end in data piracy, if the code would be public without buying an image. And I don't want to support this.
I would only do it if the developers of hoobs 5 are releasing the source code.
