### ISSUE TITLE
Fresh installation, SmartThings BridgeFailed to find plugin to handle accessory [one of multiple accessories]

### ISSUE THREAD

**Issue by rdllarena** [hoobs-org/HOOBS#1775]
Hoobs team,

Context:
Hoobs 4.1.21
Node Version | 16.13.2
Homebridge Version | 1.3.9

SmartThings 1.6.76-584

I had this working mid-2021, but then my Hoobs failed. I shelved the project until recently, and after a day of tinkering and putting in my own flashed micro-SD card with the latest Hoobs 4.x release I'm up and running again.

Problem is, SmartThings not populating in HomeKit? Here's what I'm seeing in the log:

1/12/2022, 7:55:55 AMSmartThings Bridge starting
1/12/2022, 7:56:05 AMSmartThings BridgeLoaded plugin 'homebridge-smartthings'
1/12/2022, 7:56:05 AMSmartThings BridgeLoading 1 platforms...
1/12/2022, 7:56:07 AMSmartThings BridgeBridge is running on port 51836.
1/12/2022, 7:56:25 AMSmartThings BridgeConfiguration change
1/12/2022, 7:56:25 AMsmartthingsbridge stopping
1/12/2022, 7:56:31 AMSmartThings Bridge starting
1/12/2022, 7:56:41 AMSmartThings BridgeLoaded plugin 'homebridge-smartthings'
1/12/2022, 7:56:41 AMSmartThings BridgeFailed to find plugin to handle accessory Back Driveway Light
1/12/2022, 7:56:41 AMSmartThings BridgeFailed to find plugin to handle accessory Front Driveway Lights
1/12/2022, 7:56:41 AMSmartThings BridgeFailed to find plugin to handle accessory Garage Lights Interior
1/12/2022, 7:56:41 AMSmartThings BridgeFailed to find plugin to handle accessory Garage Door
1/12/2022, 7:56:41 AMSmartThings BridgeFailed to find plugin to handle accessory Low Voltage Lights
1/12/2022, 7:56:41 AMSmartThings BridgeFailed to find plugin to handle accessory Yard String Lights
1/12/2022, 7:56:41 AMSmartThings BridgeBridge is running on port 51836.
1/12/2022, 7:57:02 AMSmartThings BridgeConfiguration change
1/12/2022, 7:57:02 AMsmartthingsbridge stopping
1/12/2022, 7:57:08 AMSmartThings Bridge starting
1/12/2022, 7:57:18 AMSmartThings BridgeLoaded plugin 'homebridge-smartthings'
1/12/2022, 7:57:18 AMSmartThings BridgeBridge is running on port 51836.
1/12/2022, 7:57:21 AMsmartthingsbridge stopping
1/12/2022, 7:57:27 AMSmartThings Bridge starting
1/12/2022, 7:57:37 AMSmartThings BridgeLoaded plugin 'homebridge-smartthings'
1/12/2022, 7:57:37 AMSmartThings BridgeBridge is running on port 51836.
1/12/2022, 8:13:07 AMWARNINGdevice reboot command received
1/12/2022, 8:13:09 AMApple HomeKit stopping
1/12/2022, 8:13:09 AMBond Bridge stopping
1/12/2022, 8:13:09 AMSmartThings Bridge stopping
1/12/2022, 8:13:59 AMhub is running on port 80
1/12/2022, 8:14:01 AMApple HomeKit starting
1/12/2022, 8:14:02 AMBond Bridge starting
1/12/2022, 8:14:02 AMSmartThings Bridge starting
1/12/2022, 8:14:12 AMApple HomeKitWARNINGNo plugins installed.
1/12/2022, 8:14:12 AMApple HomeKitBridge is running on port 51846.

Please advise.

Thank you.

**Comment by mkellsy** [comment]
The SmartThings plugin logs wired, can you attach a downloaded log file to a new ticket.
Here's how to get the log file.
https://support.hoobs.org/topics/support-files/How-to-download-the-Log

And here's where to open a support ticket. Click Contact Us.
https://support.hoobs.org
