### ISSUE TITLE
npm install throwing error in reactjs

### ISSUE THREAD

**Issue by 41t1hy4** [hoobs-org/HOOBS#1776]
I am kind of new at this. Please help me. Thanks in advance.

PS C:\Project Code\ssp-ui-app> npm install

npm ERR! code EPROTO
npm ERR! syscall write
npm ERR! errno EPROTO
npm ERR! request to https://codeload.github.com/eligrey/FileSaver.js/tar.gz/e865e37af9f9947ddcced76b549e27dc45c1cb2e failed, reason: write EPROTO 045D0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:908:
npm ERR!

log file:
[2022-01-12T17_12_57_562Z-debug.log](https://github.com/hoobs-org/HOOBS/files/7856480/2022-01-12T17_12_57_562Z-debug.log)

**Comment by mkellsy** [comment]
HOOBS is not the right place for this.
For development questions try https://stackoverflow.com/
