### ISSUE TITLE
Missing Field Descriptions/Missing 'Visual' setup for HomeSeer Plugin

### ISSUE THREAD

**Issue by scoutbeer** [hoobs-org/HOOBS#1777]
**Description**
In version 4.0.x the UI is not showing the field descriptors properly. (See screenshots).
I'm wondering how I can get the field descriptions to properly show up in the UI. I've tried doing Hub Settings -> Cache -> Clear Cache and uninstalling and reinstalling the plugin but neither has resolved the issue.

I then tried a separate install on version 4.1.21 and the entire 'Visual' config is missing all together. (See screenshots).

I then tried testing on a Hombridge install and everything shows as it should (See screenshots).

**Expected behavoir**
Visual Config with proper descriptions and labels for the fields should show in the UI.

**Plugin name**
https://github.com/jvmahon/Homebridge-HomeSeer4

**Please report the issue to the plugin developer**
https://github.com/jvmahon/Homebridge-HomeSeer4/issues/166

**Version**
Tested with 4.0.x and 4.1.21 as well as Homebridge native

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

Operating System: Raspbian GNU/Linux 10 (buster)
 Kernel: Linux 5.10.63-v7l+

**Post your config**
hoobs@hoobs:~ $ cat ~/.hoobs/etc/config.json
cat: /home/hoobs/.hoobs/etc/config.json: No such file or directory

**Hoobs 4.0.x**
![HomeseerPluginUI-01](https://user-images.githubusercontent.com/87205579/149402088-09887f3b-a10b-4ba1-b055-adda72dd60b1.jpg)
![HomeseerPluginUI-02](https://user-images.githubusercontent.com/87205579/149402102-5794254e-a4eb-4296-a1b6-5551348c43c3.jpg)

**Hoobs 4.1.21**
![4 1 21 HomeseerPluginUI](https://user-images.githubusercontent.com/87205579/149402167-69d5843d-a320-48a3-9eaf-b2b6204f173f.png)

**Homebridge**

![Homebridge HomeseerPluginUI](https://user-images.githubusercontent.com/87205579/149402203-4cfde027-3fb0-448b-ae46-40200e018551.png)

**Comment by scoutbeer** [comment]
@mkellsy any thoughts on this?  Curious why it works in Homebridge but no UI/Visual in Hoobs.

**Comment by mkellsy** [comment]
The config for UI-X is a bit lazy, and the dev didn't add the "title" and "description" fields as stated in the JSON schema standard. I will be overriding this schema soon; it is on my to-do list.

**Comment by scoutbeer** [comment]
Thanks @mkellsy, i'll keep my eye out for an update!

**Comment by mkellsy** [comment]
I have the schema updated. If you don't see the changes right away, clear the Hub cache.
Main Menu (3 dots on the upper right) -> Hub Settings -> Click Clear Cache.
