### ISSUE TITLE
Link to Mac installation documentation is broken

### ISSUE THREAD

**Issue by GoWithitRoger** [hoobs-org/HOOBS#1782]
**Description**
I've seen this link referenced as giving the HOOBS service installation instructions for Mac:
https://github.com/hoobs-org/HOOBS/wiki/2.5.0-macOS-Installation) 

That link doesn't seem to work anymore and just redirects to the HOOBS readme on Github.

**What device are you using?**
Macbook/MacOS Big Sur

**Post your config**
The HOOBS desktop app is installed, but it finds "No devices".

**Comment by GoWithitRoger** [comment]
I found this post in an earlier issue that links to what looks to be a mac package that might work.

https://github.com/hoobs-org/HOOBS/issues/1720#issuecomment-1003036627

**Comment by mkellsy** [comment]
The wiki is old everything has moved to https://support.hoobs.org.
You can find the macOS installation here https://support.hoobs.org/downloads

**Comment by shivanathd** [comment]
Can you post the latest version there? I have trouble updating after install
