### ISSUE TITLE
Can't install Hoobs on Debian 11 /Bullseye Unmet Dependencies

### ISSUE THREAD

**Issue by clarionite** [hoobs-org/HOOBS#1785]
I'm attempting to install Hoobs 4 on a debian 11 server. But I get

Some packages could not be installed. this may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.31-13+deb11u2) but 2.33-5 is to be installed
                   Depends: libc-dev-bin (= 2.31-13+deb11u2) but it is not going to be installed
                   
  E: unable to correct problems, you have held broken packages.
  
  
  
  I thought at first that it was because I had installed Gnome 41 on this system from unstable. But I've taken that out. And I'm still getting this.
  
  Can anyone point me in the right direction to either updating the packages on my system that Hoobs 4 needs, or an how to install an older version of Hoobs that would match up to what my system has on it?

**Comment by mkellsy** [comment]
We test on bullseye. It's the main environment.
Can you run this command `ls -la /etc/apt/sources.list.d/` and post the output?
I wonder if there is conflicting sources.

**Comment by jbennetts23** [comment]
@mkellsy hi mate,

I am having the same issue
