### ISSUE TITLE
CLI Upgrade broken

### ISSUE THREAD

**Issue by afulki** [hoobs-org/HOOBS#1786]
**Description**

hoobs@hoobs:~ $ sudo hbs system upgrade
[sudo] password for hoobs:
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Fetched 15.0 kB in 1s (15.4 kB/s)
Reading package lists... Done
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x buster main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x buster main
deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main
deb [signed-by=/usr/share/keyrings/hoobs.gpg] https://dl.hoobs.org/debian/ stable main
Get:1 https://deb.nodesource.com/node_16.x buster InRelease [4,584 B]
Get:2 https://dl.hoobs.org/debian stable InRelease [3,032 B]
Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Hit:4 http://archive.raspberrypi.org/debian buster InRelease
Hit:5 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:6 https://dl.hoobs.org/debian stable/main armhf Packages [1,929 B]
Get:7 https://deb.nodesource.com/node_16.x buster/main armhf Packages [778 B]
Get:8 https://dl.yarnpkg.com/debian stable/main all Packages [10.5 kB]
Get:9 https://dl.yarnpkg.com/debian stable/main armhf Packages [10.5 kB]
Fetched 48.5 kB in 2s (31.6 kB/s)
Reading package lists... Done
 ERROR  TypeError: dest.on is not a function
    at WriteStream.Readable.pipe (internal/streams/readable.js:652:8)
    at Socket.<anonymous> (/usr/src/system/index.ts:167:32)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

**Version**
4.0.7.1

**Did you upgrade**
that's what I'm trying to do

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
hoobs@hoobs:~ $ sudo hbs plugin list

bridge                | name                          | version | path
-------------------------------------------------------------------------------------------------------------------------------------------------
braviabridge          | homebridge-bravia             | 2.4.9   | /var/lib/hoobs/braviabridge/node_modules/homebridge-bravia
denonheosbridge       | homebridge-denon-heos         | 2.9.7   | /var/lib/hoobs/denonheosbridge/node_modules/homebridge-denon-heos
goveebridge           | homebridge-govee              | 4.22.0  | /var/lib/hoobs/goveebridge/node_modules/homebridge-govee
myqbridge             | homebridge-myq                | 2.7.1   | /var/lib/hoobs/myqbridge/node_modules/homebridge-myq
nodealarmdotcombridge | homebridge-node-alarm-dot-com | 1.8.0   | /var/lib/hoobs/nodealarmdotcombridge/node_modules/homebridge-node-alarm-dot-com

**Post your config**
cat ~/.hoobs/etc/config.json
cat: /home/hoobs/.hoobs/etc/config.json: No such file or directory

**Post your log**
2/1/2022, 6:11:04 AM Bravia Bridge [ WARNING ] device reboot command received
2/1/2022, 6:11:04 AM Bravia Bridge [ DEBUG ] Shutting down
2/1/2022, 6:11:04 AM Bravia Bridge Govee Bridge stopping
2/1/2022, 6:11:04 AM Bravia Bridge Node Alarm Dot Com Bridge stopping
2/1/2022, 6:11:04 AM Bravia Bridge Bravia Bridge stopping
2/1/2022, 6:11:04 AM Bravia Bridge myQ Bridge stopping
2/1/2022, 6:11:04 AM Bravia Bridge Denon Heos Bridge stopping
2/1/2022, 6:11:08 AM Bravia Bridge [ DEBUG ] Stopped
2/1/2022, 6:11:33 AM Hub hub is running on port 80
2/1/2022, 6:11:33 AM Hub [ WARNING ] unhandled rejection: Cancel
2/1/2022, 6:11:35 AM Hub [ WARNING ] unhandled rejection: Cancel
2/1/2022, 6:11:35 AM Hub Govee Bridge starting
2/1/2022, 6:11:35 AM Hub Node Alarm Dot Com Bridge starting
2/1/2022, 6:11:35 AM Hub myQ Bridge starting
2/1/2022, 6:11:36 AM Hub Bravia Bridge starting
2/1/2022, 6:11:36 AM Hub Denon Heos Bridge starting
2/1/2022, 6:11:37 AM Govee Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
2/1/2022, 6:11:38 AM Node Alarm Dot Com Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
2/1/2022, 6:11:38 AM myQ Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
2/1/2022, 6:11:38 AM Govee Bridge [ ERROR ] [31mThe plugin "homebridge-govee" requires a Homebridge version of ^1.3.9 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
2/1/2022, 6:11:38 AM Govee Bridge Loaded plugin 'homebridge-govee'
2/1/2022, 6:11:38 AM Govee Bridge [ DEBUG ] Registering platform 'homebridge-govee.Govee'
2/1/2022, 6:11:38 AM Govee Bridge Loading 1 platforms...
2/1/2022, 6:11:38 AM Govee Bridge Govee [ WARNING ] ***** Disabling plugin. *****
2/1/2022, 6:11:38 AM Govee Bridge [ DEBUG ] Preparing Advertiser for 'Govee Bridge A2CD' using bonjour-hap backend!
2/1/2022, 6:11:38 AM Govee Bridge [ DEBUG ] Starting to advertise 'Govee Bridge A2CD' using bonjour-hap backend!
2/1/2022, 6:11:38 AM Govee Bridge Bridge is running on port 51836.
2/1/2022, 6:11:39 AM Bravia Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
2/1/2022, 6:11:39 AM Denon Heos Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Loaded plugin 'homebridge-node-alarm-dot-com'
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge [ DEBUG ] Registering platform 'homebridge-node-alarm-dot-com.Alarmdotcom'
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Loading 1 platforms...
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Security System Loaded from cache: Panel (100457560-127)
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Security System Loaded from cache: Front Door (100457560-1)
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Security System Loaded from cache: Hallway Motion Detector (100457560-4)
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Security System Loaded from cache: Interior Garage Door (100457560-3)
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Security System Loaded from cache: Panel Camera (100457560-229)
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Security System Loaded from cache: Side Door (100457560-2)
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Security System Logging into Alarm.com as thom4483
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge [ DEBUG ] Preparing Advertiser for 'Node Alarm Dot Com Bridge AAB6' using bonjour-hap backend!
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge [ DEBUG ] Starting to advertise 'Node Alarm Dot Com Bridge AAB6' using bonjour-hap backend!
2/1/2022, 6:11:39 AM Node Alarm Dot Com Bridge Bridge is running on port 51846.
2/1/2022, 6:11:40 AM Node Alarm Dot Com Bridge Security System Logged into Alarm.com as ****************
2/1/2022, 6:11:40 AM myQ Bridge Loaded plugin 'homebridge-myq'
2/1/2022, 6:11:40 AM myQ Bridge [ DEBUG ] Registering platform 'homebridge-myq.myQ'
2/1/2022, 6:11:40 AM myQ Bridge Loading 1 platforms...
2/1/2022, 6:11:40 AM Node Alarm Dot Com Bridge Security System Received 1 partitions from Alarm.com
2/1/2022, 6:11:40 AM Node Alarm Dot Com Bridge Security System Restoring accessory with ID 100457560-127
2/1/2022, 6:11:40 AM Node Alarm Dot Com Bridge Security System Received 5 sensors from Alarm.com
2/1/2022, 6:11:40 AM Node Alarm Dot Com Bridge Security System Restoring accessory with ID 100457560-1
2/1/2022, 6:11:40 AM Node Alarm Dot Com Bridge Security System Restoring accessory with ID 100457560-4
2/1/2022, 6:11:40 AM Node Alarm Dot Com Bridge Security System Restoring accessory with ID 100457560-3
2/1/2022, 6:11:40 AM Node Alarm Dot Com Bridge Security System Restoring accessory with ID 100457560-229
2/1/2022, 6:11:40 AM Node Alarm Dot Com Bridge Security System Restoring accessory with ID 100457560-2
2/1/2022, 6:11:40 AM Bravia Bridge Loaded plugin 'homebridge-bravia'
2/1/2022, 6:11:40 AM Bravia Bridge [ DEBUG ] Registering platform 'homebridge-bravia.BraviaPlatform'
2/1/2022, 6:11:40 AM Bravia Bridge Loading 1 platforms...
2/1/2022, 6:11:40 AM Bravia Bridge BraviaPlatform Creating new accessory for Sony TV
2/1/2022, 6:11:40 AM Bravia Bridge BraviaPlatform New TV Sony TV, will be queried for channels/apps and added to HomeKit
2/1/2022, 6:11:40 AM myQ Bridge [ DEBUG ] Preparing Advertiser for 'myQ Bridge 27E7' using bonjour-hap backend!
2/1/2022, 6:11:40 AM Bravia Bridge [ DEBUG ] Preparing Advertiser for 'Bravia Bridge 4552' using bonjour-hap backend!
2/1/2022, 6:11:40 AM myQ Bridge [ DEBUG ] Starting to advertise 'myQ Bridge 27E7' using bonjour-hap backend!
2/1/2022, 6:11:40 AM myQ Bridge Bridge is running on port 51826.
2/1/2022, 6:11:40 AM Bravia Bridge [ DEBUG ] Starting to advertise 'Bravia Bridge 4552' using bonjour-hap backend!
2/1/2022, 6:11:40 AM Bravia Bridge Bridge is running on port 51856.
2/1/2022, 6:11:40 AM Bravia Bridge BraviaPlatform Need to authenticate with TV!
2/1/2022, 6:11:40 AM Bravia Bridge BraviaPlatform Please enter the PIN that appears on your TV at http://hoobs:8999
2/1/2022, 6:11:40 AM Bravia Bridge BraviaPlatform PIN entry web server listening
2/1/2022, 6:11:41 AM myQ Bridge myQ myQ API: Successfully connected to the myQ API.
2/1/2022, 6:11:41 AM Denon Heos Bridge Loaded plugin 'homebridge-denon-heos'
2/1/2022, 6:11:41 AM Denon Heos Bridge [ DEBUG ] Registering platform 'homebridge-denon-heos.DenonAVR'
2/1/2022, 6:11:41 AM Denon Heos Bridge Loading 1 platforms...
2/1/2022, 6:11:42 AM Denon Heos Bridge [ DEBUG ] Preparing Advertiser for 'Denon Heos Bridge 3AEE' using bonjour-hap backend!
2/1/2022, 6:11:42 AM Denon Heos Bridge [ DEBUG ] Starting to advertise 'Denon Heos Bridge 3AEE' using bonjour-hap backend!
2/1/2022, 6:11:42 AM Denon Heos Bridge Bridge is running on port 51866.
2/1/2022, 6:11:42 AM myQ Bridge myQ myQ API: Discovered device family garagedoor: Garage Door (serial number: CG085043BBB5, gateway: GW0B00362B70).
2/1/2022, 6:11:42 AM myQ Bridge myQ myQ API: Discovered device family gateway: Garage Door [Liftmaster WiFi GDO AC] (serial number: GW0B00362B70).
2/1/2022, 6:11:58 AM Denon Heos Bridge [ DEBUG ] Preparing Advertiser for 'Denon Receiver 48A7' using bonjour-hap backend!
2/1/2022, 6:11:58 AM Denon Heos Bridge [ DEBUG ] Starting to advertise 'Denon Receiver 48A7' using bonjour-hap backend!
2/1/2022, 6:11:58 AM Denon Heos Bridge Denon Receiver 48A7 is running on port 34443.
2/1/2022, 6:11:58 AM Denon Heos Bridge DenonAVR [ ERROR ] Error: getaddrinfo ENOTFOUND  192.168.50.184
2/1/2022, 6:11:58 AM Denon Heos Bridge [ WARNING ] unhandled rejection: Error: getaddrinfo ENOTFOUND  192.168.50.184
2/1/2022, 6:12:00 AM Denon Heos Bridge [ WARNING ] unhandled rejection: TypeError: Cannot read property 'attempts' of undefined

**Additional context**
upgrade using UI fails with spinning logo

**Comment by mkellsy** [comment]
I tried to reproduce. I think there is a system upgrade that's stuck.
You can run the fix command to re-configure aptly. Here's the support doc we have on this.
https://support.hoobs.org/topics/resetting-re-flashing/what-is-the-fix-command
