### ISSUE TITLE
homebridge-shelly-ng

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#1788]
homebridge-shelly-ng plugin not available in Plugin library

It can be displayed on Pluginsite. 

https://plugins.hoobs.org/plugin/homebridge-shelly-ng

But it doesnt appear in search. So customer cant install it via HOOBS ui. 

See ticket:
https://support.hoobs.org/manage/tickets/61f9b3a281961ccaaa77b8a1

**Comment by jbnb54** [comment]
hey, the link to the ticket doesn't work. did you find a solution to install the plugin via hoobs ui?

**Comment by BobbySlope** [comment]
not yet its still open.

**Comment by BobbySlope** [comment]
next plugin not synced in library:

https://support.hoobs.org/manage/tickets/6212300d5b1147ec9dc54567

**Comment by BobbySlope** [comment]
next plugin not able to get the most recent version:
https://support.hoobs.org/manage/tickets/621303d8a741694b8050fc59

**Comment by BobbySlope** [comment]
next cutomer reporting:
https://support.hoobs.org/manage/tickets/621488c569580bb2f4b1706c

**Comment by apartmedia** [comment]
Is this something to be fixed any time soon or is it a bigger problem taking much more time?
Is there a workaround to install a non listed plugin in an alternative way while it’s not showing up in the library but being available on the plugin site?

**Comment by mkellsy** [comment]
This was an issue with the text search algorithm.

This is fixed. It shows up now.
https://plugins.hoobs.org/search/c2hlbGx5IG5n
