### ISSUE TITLE
NGINX Not Loading After Update to Beta 61

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#179]
After Update to Beta 61 the Webinterface doesnt start but Homebridge runs and the Devices are reachable.
![E5AD9AC2-4E05-4A66-9B4C-7C552337A61F](https://user-images.githubusercontent.com/55372949/66019070-00e10700-e4e2-11e9-93b0-4676bf6cc181.png)

**Comment by mkellsy** [comment]
How did you upgrade?
Can you post this file? /etc/nginx/conf.d/hoobs.conf
Can you post your config? ~/.hoobs/etc/config.json

**Comment by mkellsy** [comment]
Try running this command
sudo hoobs-init

**Comment by Bladestar2105** [comment]
sudo hoobs-init doesn't solve the problem.
I upgraded through the webinterface.

this works: http://192.168.178.54:51827
this doesn't work: http://192.168.178.54:8080

![grafik](https://user-images.githubusercontent.com/55372949/66022522-8c609500-e4ee-11e9-8aee-b0ba09da8c0e.png)

`{
    "client": {
        "port": 8080,
        "default_route": "status",
        "inactive_logoff": 50,
        "theme": "hoobs-dark",
        "locale": "de",
        "config": "http://192.168.178.54",
        "socket": "http://192.168.178.54",
        "api": [
            "http://192.168.178.54"
        ],
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": 68xxx
    },
    "bridge": {
        "username": "CD:22:3D:XX:XX:XX",
        "name": "Homebridge",
        "pin": "123-456-789",
        "port": 51826
    },
    "description": "This file is used for plugin configuration.",
    "ports": {
        "start": 52100,
        "end": 52150,
        "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "1-Cam",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://root:password@192.168.178.56/live",
                        "stillImageSource": "-i http://root:password@192.168.178.56/photo",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "debug": false,
                        "additionalCommandline": "-loglevel verbose",
                        "vcodec": "h264_omx"
                    }
                },
                {
                    "name": "2-Cam",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://192.168.178.97:8080",
                        "stillImageSource": "-i http://192.168.178.97:8080",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "hflip": true,
                        "debug": false,
                        "additionalCommandline": "-loglevel verbose",
                        "vcodec": "h264_omx"
                    }
                }
            ]
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Fernseher",
            "hubIP": "192.168.178.66",
            "TVPlatformMode": true,
            "mainActivity": "Fernseher",
            "showTurnOffActivity": false
        },
        {
            "broadcast": "255.255.255.255",
            "devices": [
                {
                    "host": "192.168.178.51"
                }
            ],
            "name": "TplinkSmarthome",
            "platform": "TplinkSmarthome"
        },
        {
            "platform": "NelloPlatform",
            "name": "nello.io",
            "username": "user",
            "password": "password",
            "clientId": "ID",
            "lockTimeout": 5000,
            "locationUpdateInterval": 3600000,
            "exposeReachability": true,
            "motionSensor": true,
            "motionTimeout": 5000,
            "alwaysOpenSwitch": false,
            "homekitUser": "Home Kit"
        },
        {
            "ccu_ip": "192.168.178.89",
            "outlets": [],
            "doors": [],
            "enable_hmip": true,
            "platform": "HomeMatic",
            "windows": [],
            "subsection": "Homekit",
            "name": "HomeMatic",
            "programs": [],
            "services": [
                {
                    "type": "KEY_TRANSCEIVER",
                    "service": "HomeMaticHomeKitKeyService"
                }
            ]
        },
        {
            "platform": "CallMonitor",
            "plugin_map": {
                "plugin_name": "homebridge-callmonitor"
            },
            "devices": [
                {
                    "port": "1012",
                    "outgoingName": "Ausgehender Anruf",
                    "incomingName": "Eingehender Anruf",
                    "name": "AVM Fritz!Box",
                    "address": "192.168.178.1"
                }
            ],
            "name": "Fritzbox"
        },
        {
            "name": "Hue",
            "hosts": [
                "127.0.0.1:81"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue",
            "users": {
                "user for hue"
            },
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "undefined": null
        }
    ]
}`

**Comment by mkellsy** [comment]
It looks like the configuration upgrade processes failed for you.

To fix this you will need to edit the config using the **Terminal**. Since you have access to the interface you can find this in the menu on the top right.

Once the terminal loads, it will already be in the folder where your config.json is.

1. Run `nano config.json`
2. Edit the config

```
{
    "server": {
        "port": 51827, <- Change this to 8080
        "socket": 51828, <- Delete this line
        "autostart": true,
        "home_setup_id": "X-HM://",
        "polling_seconds": 2
    },
    "client": {
        "port": 8080,  <- Delete this line
        "default_route": "status",
        "inactive_logoff": 50,
        "theme": "hoobs-dark",
        "locale": "de",
        "config": "http://192.168.178.54", <- Delete this line
        "socket": "http://192.168.178.54", <- Delete this line
        "api": [ <- Delete this line
            "http://192.168.178.54" <- Delete this line
        ], <- Delete this line
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": 68
    },
   ...
```

Results
```
{
    "server": {
        "port": 8080,
        "autostart": true,
        "home_setup_id": "X-HM://",
        "polling_seconds": 2
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 50,
        "theme": "hoobs-dark",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": 68
    },
   ...
```

3. Press **ctrl+x** to exit nano
4. Press **y** to save changes
5. Press **enter** to confirm
6. Run `sudo shutdown -r now`

Your device will reboot and should be back on: http://192.168.178.54.

> Note: You can not use the Advanced Configuration screen. It isn't advanced enough. You need to use nano in the terminal. We hide the server section to prevent users from bricking their device.

**Comment by Bladestar2105** [comment]
Thank you!
Now it works again :-)

**Comment by adavison007** [comment]
Ok Totally confused! I can't get to the web ui, so how can I get to terminal?

**Comment by askovi** [comment]
@adavison007 You can get to the UI using http://hoobs.local:51827
Make the above changes then reboot

**Comment by adavison007** [comment]
So I followed these instructions and now I can't access Homebridge at all! using .local or http://hoobs.local:51827 , but everything works in homekit?

**Comment by adavison007** [comment]
> So I followed these instructions and now I can't access Homebridge at all! using .local or http://hoobs.local:51827 , but everything works in homekit?

I can SSH into the box, so what should I do and where should I go to resolve this?

**Comment by adavison007** [comment]
> > So I followed these instructions and now I can't access Homebridge at all! using .local or http://hoobs.local:51827 , but everything works in homekit?
> 
> I can SSH into the box, so what should I do and where should I go to resolve this?

I can get in if I do this http://hoobs.local:8080

**Comment by askovi** [comment]
Ssh into the box then run sudo hoobs-init
Box will check installation and reboot then it will work normally

**Comment by adavison007** [comment]
> sudo hoobs-init

That worked thanks

**Comment by mkellsy** [comment]
I found the issue. In the past our upgrade process required the --ignore-scripts flag on the npm install. This flag is preventing the post upgrade scripts from running.

I have published 3.0.0-beta.62 to address this, with a failsafe in case the upgrade script is not ran.

If you already upgraded to beta 60 or 61. You can try to access the interface at http://hoobs.local:51827. Then click Check for Updates and update to beta 62. After the upgrade you should be able to access the interface at http://hoobs.local.

If you are unable to access the interface or unable to log in (the bug beta.60 was trying to fix). You need to access the terminal via SSH.

1. Open a terminal from Mac, or Putty on Windows.
2a. On mac type `ssh hoobs@hoobs.local` the password is **hoobsadmin**
2b. On Putty on Windows, set the Host **hoobs.local**, and the port to **22**. Click **Open**.
2b. Then enter **hoobs** for the username and **hoobsadmin** for the password.
3. Now run this command `sudo npm install -g --unsafe-perm @hoobs/hoobs` and wait for it to finish.
4. Then run `sudo reboot`

After the device reboots, the interface should appear.

**Comment by bgiuriceo** [comment]
Still stuck at splash screen after following the procedure below to get to .62. (.61 was the start of my issues)  Is it possible to revert to .59 until this is sorted out?

thanks

**Comment by mkellsy** [comment]
Yes open the terminal and run this.
sudo npm install -g --unsafe-perm @hoobs/hoobs@3.0.0-beta.59

Then run
sudo hoobs-init

Then
sudo reboot

**Comment by bgiuriceo** [comment]
Many thanks. Reversion was unsuccessful (never got passed the splash screen) and I’ve rebuilt my instance.
