### ISSUE TITLE
cannot access hoobs.local but can access true terminal..

### ISSUE THREAD

**Issue by Paddenhoek** [hoobs-org/HOOBS#1793]
Hoobs out of the box, configured, tried to upgrade(upgrade available 4.1.22?)

V4.1.21 tried to upgrade but lost local connection

Tried to install Hoobs out of the box in Portugal, after trying to upgrade lost connection to Hoobs.local.
Can reach hoobs true terminal.
**Pervious version**
4.1.21
HOOBS Box
 macOS Monterey.

**List your plugins**
no pluggins

**Post your config**
see attached screen shot

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```
![Screenshot 2022-02-13 at 13 17 26](https://user-images.githubusercontent.com/91569557/153754108-f89e3a62-7704-48a2-bdc2-76029dac547d.png)

**Comment by 1yoda** [comment]
Same issue here, installed Hoobs on my raspi and added mqtt + zigbee

all services are running, full acess by ssh - and no signal at UI...

 I am ripping my hair out at the moment.
![fail](https://user-images.githubusercontent.com/98899481/154836234-950db66c-bdf6-4405-be27-aa2dc211820f.JPG)

**Comment by Paddenhoek** [comment]
well that makes 2 of us...
still no access on lokal but on terminal all good

**Comment by 1yoda** [comment]
> well that makes 2 of us... still no access on lokal but on terminal all good

well I tried a lot and found a solution:
after this command:
wget -q -O - http://bit.ly/get-hoobs | sudo bash -

I got back on latest v. 3.x.x

and then I've updatet Hoobs following these instructions:

https://support.hoobs.org/docs/60e62a926c19a6a5ca8f4f42

and after all - restartet my Wi-Fi router

**Comment by Paddenhoek** [comment]
I'll load a new image.... and try all fresh again because 
![Screenshot 2022-02-22 at 08 38 25](https://user-images.githubusercontent.com/91569557/155085165-7b089dbe-df68-486b-93c6-889dac31b797.png)
:

**Comment by mkellsy** [comment]
Click the Advanced button and enter your IP address **192.168.178.54**.

If this doesn't work, open a support ticket, so we can troubleshoot further.
https://support.hoobs.org/ticket
