### ISSUE TITLE
Uninstalling a bridge cause uninstall window to hang up

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#1796]
While uninstalling a plugin incl. removing bridge the uninstall window does not disapear automatically.
You need to refresh the browser to get back to the UI

**Comment by mkellsy** [comment]
Plugin name?
Logs?
How do I reproduce?

**Comment by mkellsy** [comment]
Info from slack. Bobby tested with Ring, Nest and Shelly.
Interesting enough these plugins all have sidecars. Maybe?

NEXT STEP
Reproduce in lab

**Comment by mkellsy** [comment]
I got this fixed in 4.2.0
