### ISSUE TITLE
hbs log tailing is not working on terminal (web UI works fine)

### ISSUE THREAD

**Issue by shamasis** [hoobs-org/HOOBS#1797]
**Description**
Hello team. Just keeping a note here whenever someone gets the time to help debug this. The issue is straightforward... when using the `hbs` command via terminal, `sudo hbs log --tail 10` is not working. The command simply lists and exits without tailing the log.

**Version**
Using `v4.1.20`

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No
- [x] NA

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi (`Linux hoobs 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux`)

**List your plugins**
NA

**Post your config**
NA

**Comment by mkellsy** [comment]
Logs contain sensitive information and are encrypted at rest. The hbs log function reads in the current log and displays it. There is no tail function.
