### ISSUE TITLE
Dose scripts/deconz-phoscon-hoobs.sh work with Hoobs 4?

### ISSUE THREAD

**Issue by Tiiiziii** [hoobs-org/HOOBS#1799]
I'm trying to install the deConz and Phoscon on my raspberry Pi with Hoobs 4 software. I tryed using the provided script [[scripts/deconz-phoscon-hoobs.sh]]. Dose this script work with hoobs 4?

The Phoscon app workes fine exapt I can't get a conection to my Conbee 2 stick.

**Comment by mkellsy** [comment]
Can you post the terminal output from the deconz script. This will help me debug this.
