### ISSUE TITLE
Hoobs offers plugin update although it is already updated

### ISSUE THREAD

**Issue by svobod3** [hoobs-org/HOOBS#1800]
**Description**
I am facing problem with a plugin (currently LG
In Check for update section Hoobs still offers me update to new version although I already installed it and plugin has this version.
When I click on Update button, log below follows, but nothing happends. When I connect to Hoobs again, situation remains the same.
I followed previous advice (https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3), but it did not help.

**Version**
4.1.22

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Can I get the exact name of the plugin?
Is it LG?
When I search for LG I get these plugins.
https://plugins.hoobs.org/search/TEc

Which one are you using?

**Comment by svobod3** [comment]
Sure, it is LG Thinq plugin ( https://plugins.hoobs.org/plugin/homebridge-lg-thinq ). But the same happened to me also with Harmony plugin (https://plugins.hoobs.org/plugin/homebridge-harmony).

**Comment by mkellsy** [comment]
Awesome. Thanks for the information.

NEST STEP
Reproduce in lab

**Comment by svobod3** [comment]
Great, thanks.
If you need any further info please let me know.

**Comment by svobod3** [comment]
Maybe other info that can help you:
- when new plugin version is released, it is shown in GUI twice (in 2 rows)
- when I proceed update, plugin update is shown once (although plugin is already updated to the newest version)
- when other updates are available the only way how to proceed their update is to uninstall plugin, update the rest and install plugin again (or to execute curl -sk https://dl.hoobs.org/fix | sudo bash -)

**Comment by orianlevy** [comment]
i have the same issue with Connexoon plugin:
https://plugins.hoobs.org/plugin/homebridge-connexoon

**Comment by svobod3** [comment]
Update from my side - as new version of Roomba2 plugin was released, it happened also to this plugin. So for me this problem is not plugin related as it happends for all 3 plugins I have.

**Comment by vvdheuvel** [comment]
same issue with hue plugin: https://plugins.hoobs.org/plugin/homebridge-hue

**Comment by svobod3** [comment]
Hello, any news regarding solving this issue?

**Comment by vvdheuvel** [comment]
Almost 2 months guys, what’s going on? I’ll give it to the end of this month, then I’ll switch for sure to Homebridge.

**Comment by vvdheuvel** [comment]
Still radio silence! Almost end of April is going to be fixed or is it going to be bye bye Hoobs?

**Comment by mkellsy** [comment]
4.2.2 is being released today.
For faster response times please open a ticket here
https://support.hoobs.org/

**Comment by svobod3** [comment]
I just updated to 4.2.2 and unfortunately problem with plugin update is still there:(

**Comment by vvdheuvel** [comment]
Yeah, I can confirm the bug is still there. I’ve switched to homebridge. I’ve noticed a couple of things because of it: CPU temperatures are lower on Pi (+/- 6 degrees), responsiveness dashboard and load time are way better. Hope the HOOBS guys will fix these issues.

**Comment by mkellsy** [comment]
Can you post your logs?
The update is failing. The logs can be downloaded from the Logs screen.

**Comment by orianlevy** [comment]
Was able to finally solve this. 
i installed a fresh new hoobs, BUT the trick is, not to restore from previous backup file. Just install all the plugins from scratch, and copy the config file. (Seems like the old backup file was corrupted)

**Comment by svobod3** [comment]
great, thanks for the tip, I will try it also

**Comment by mkellsy** [comment]
Something in yarn is causing the plugin to not update. Here's a workaround.
The files are stored in /var/lib/hoobs/.
You will see folders here for each bridge.
cd into the bridge that has the plugin in it that won't update.

For example
```
cd /var/lib/hoobs/mypluginbridge/
```

Then remove the node_modules folder
```
sudo rm -fR node_modules
```

Then clear the yarn cache
```
sudo yarn cache clean
```

Then run yarn install to reinstall the plugins
```
sudo yarn install
```

If this doesn't update the plugin, try to update the through the UI.

**Comment by tron-zero** [comment]
Thanks; I think this worked but I had to reboot Hoobs before it did.

**Comment by tron-zero** [comment]
Nevermind; it did not work

**Comment by tron-zero** [comment]
Please reopen the ticket/thread - this was not resolved

**Comment by orianlevy** [comment]
This issue still relevant, was not solved
