### ISSUE TITLE
Hoobs 4.0 Docker !?

### ISSUE THREAD

**Issue by bigdant** [hoobs-org/HOOBS#1802]
Hi,

Hoobs is in the Unraid app store (Which is amazing), however its still the old version.

Could you please, please set-up a nightly or weekly update to the most recent Hoobs 4 and all us Unraiders will be eternally gratefull !

Thanks

D.

**Comment by bigdant** [comment]
@BobbySlope - any update would be ace ??

cheers

**Comment by BobbySlope** [comment]
Theres already a community made container:

https://hub.docker.com/r/mikeknowles/hoobs4

**Comment by bigdant** [comment]
@BobbySlope that version isn’t available in the unraid AppStore.

Does someone from your team maintain this one:- https://hub.docker.com/r/hoobs/hoobs as this is said to be the official container for Hoobs.

I’m curious if this is the case why it’s not on version 4.0 ???

**Comment by annabarnes1138** [comment]
The unraid template appears to be maintained by @malverez00 [here](https://github.com/malvarez00/unRAID-Docker-Templates). So maybe the template is what should be updated to point to the community maintained one rather than the "official" (aka old) one.

**Comment by annabarnes1138** [comment]
I think I'm going to switch to plain old HomeBridge anyway. According to [this reddit thread](https://www.reddit.com/r/homebridge/comments/o52q45/comment/h2l7ush/?utm_source=share&utm_medium=web2x&context=3) it is the way to go these days. 

> HOOBs may have been the better option before the official HomeBridge UI was implemented, but now I don't see any real reason to use it...
