### ISSUE TITLE
SimpliSafe3 Plugin not working in HOOBS

### ISSUE THREAD

**Issue by bigchrisatx** [hoobs-org/HOOBS#1803]
I recently updated to the latest version of the SimpliSafe3 plugin as well as the latest version of HOOBS.  I linked my account in the plugin, but the logs showed authentication failed and my SimpliSafe products no longer respond in HomeKit.  I tried to use the terminal and the command line to force a log in, but I do not know the directory for the plugin.  Please help!

**Comment by bigchrisatx** [comment]
Also, I tried uninstalling the bridge and plugin for SimpliSafe3, but I still received the same result in the log.

![image](https://user-images.githubusercontent.com/47667537/157712095-2fd3845e-538e-47e1-a387-e4c3006372f2.png)

**Comment by hondacm450e** [comment]
Same error after linking account

**Comment by mkellsy** [comment]
This has been fixed.
