### ISSUE TITLE
Need to install a fork of the DS plugin

### ISSUE THREAD

**Issue by guusvanw** [hoobs-org/HOOBS#1806]
**Description**
The original DS plugin is outdated and doesn't work in the new HOOBS version: https://github.com/cgHome/homebridge-digitalSTROM
There is a perfect fork with fixes though: https://github.com/ayalon/homebridge-digitalSTROM

However, it seems impossible to install this manually (I read the stance of the team that it shouldn't be possible).

**Expected behavoir**
I would like to replace the current DS plugin in the HOOBS UI with the fork, so I can install that one instead of the old one.
Or, get instructions how to find change config.json and plugin_map.json on the latest HOOBS box.

**Plugin name**
Old: https://github.com/cgHome/homebridge-digitalSTROM
New: https://github.com/ayalon/homebridge-digitalSTROM

**Please report the issue to the plugin developer**
Support seems to be discontinued.

**Version**
4.2.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No, coming from a clean sheet (just received the box 2 days ago)

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
 --- this is funny, I cannot find this .hoobs and etc don't exist in my box...?

**Comment by guusvanw** [comment]
Hi @mkellsy, would be great to get an answer to this query. Thanks!

**Comment by mkellsy** [comment]
You can always use the CLI.
https://support.hoobs.org/docs/60e0d1a2646faaa152f10ddb

Also the instructions here https://github.com/ayalon/homebridge-digitalSTROM are wrong. It's not published.
You can use the GIT url like this.

```
sudo hbs plugin add https://github.com/ayalon/homebridge-digitalSTROM
```

However, I think someone already beat you to this. Will this plugin work?
https://plugins.hoobs.org/plugin/homebridge-ds

**Comment by guusvanw** [comment]
Hi @mkellsy, 

Thanks for your reply!

I'm getting the following error, any idea?
Happy easter!

hoobs@hoobs:~$ sudo hbs plugin add https://github.com/ayalon/homebridge-digitalSTROM
[sudo] password for hoobs: 
yarn add v1.22.17
[1/4] Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ayalon/homebridge-digitalSTROM@latest
Directory: /var/lib/hoobs/ds
Output:
fatal: unable to access 'https://github.com/ayalon/homebridge-digitalSTROM@latest/': The requested URL returned error: 400
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by mkellsy** [comment]
I will need to look into this further.

**Comment by guusvanw** [comment]
Thanks Michael, much appreciated. :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guusvanw** [comment]
Hi @mkellsy, following up on this I have published my forked plugin version to NPM. How do I get it in the plugin list of HOOBS?

Here's the link to the NPM package: https://www.npmjs.com/package/homebridge-dss

**Comment by guusvanw** [comment]
Hi @mkellsy, would be great to get an answer on my last comment in this thread. Thanks!

**Comment by mkellsy** [comment]
It’s already there
https://plugins.hoobs.org/plugin/homebridge-dss

we automatically mirror NPM.
