### ISSUE TITLE
After Update Hoobs Crashed

### ISSUE THREAD

**Issue by Raczka1989** [hoobs-org/HOOBS#1807]
**Description**
Hallo, Hoobs has show me an Update an i make it, after that hoobs dosn´t start,
when i go to putty it show me this Massage when i will start the service

/usr/lib/hoobsd/node_modules/toidentifier/index.js:26
    .split(' ')
     ^
TypeError: Cannot read properties of undefined (reading 'split')
    at toIdentifier (/usr/lib/hoobsd/node_modules/toidentifier/index.js:26:6)
    at forEachCode (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:245:16)
    at Array.forEach (<anonymous>)
    at populateConstructorExports (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:243:9)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/index.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
(Reading database ... 95%ading database ... 85%
(Reading database ... (Reading database ... 100%
5/1/2022, 12:52:35 AM 86868 files and directories currently installed.)
5/1/2022, 12:52:35 AM Preparing to unpack .../libperl5.28_5.28.1-6+deb10u1_armhf.deb ...
5/1/2022, 12:52:35 AM Unpacking libperl5.28:armhf (5.28.1-6+deb10u1) over (5.28.1-6) ...
5/1/2022, 12:52:40 AM Preparing to unpack .../perl_5.28.1-6+deb10u1_armhf.deb ...
5/1/2022, 12:52:41 AM Unpacking perl (5.28.1-6+deb10u1) over (5.28.1-6) ...
5/1/2022, 12:52:41 AM Preparing to unpack .../perl-base_5.28.1-6+deb10u1_armhf.deb ...
5/1/2022, 12:52:41 AM Unpacking perl-base (5.28.1-6+deb10u1) over (5.28.1-6) ...
5/1/2022, 12:52:46 AM Setting up perl-base (5.28.1-6+deb10u1) ...
5/1/2022, 12:52:46 AM (Reading database ...
(Reading database ... 10%ading database ... 5%
5/1/2022, 12:52:46 AM (Reading database ... 15%
(Reading database ... 25%ading database ... 20%
5/1/2022, 12:52:46 AM (Reading database ... 30%
(Reading database ... 55%ading database ... 35%
5/1/2022, 12:52:46 AM (Reading database ... 60%
5/1/2022, 12:52:46 AM (Reading database ... 65%
5/1/2022, 12:52:46 AM (Reading database ... 70%
5/1/2022, 12:52:46 AM (Reading database ... 75%
5/1/2022, 12:52:46 AM (Reading database ... 80%
5/1/2022, 12:52:46 AM (Reading database ... 85%
5/1/2022, 12:52:46 AM (Reading database ... 90%
5/1/2022, 12:52:46 AM (Reading database ... 95%
(Reading database ... (Reading database ... 100%
5/1/2022, 12:52:47 AM 86868 files and directories currently installed.)
5/1/2022, 12:52:47 AM Preparing to unpack .../perl-modules-5.28_5.28.1-6+deb10u1_all.deb ...
5/1/2022, 12:52:47 AM Unpacking perl-modules-5.28 (5.28.1-6+deb10u1) over (5.28.1-6) ...
5/1/2022, 12:52:54 AM Preparing to unpack .../hoobsd_4.2.3_armhf.deb ...
5/1/2022, 12:52:54 AM Unpacking hoobsd (4.2.3) over (4.2.2) ...
5/1/2022, 12:53:12 AM Preparing to unpack .../libopenexr23_2.2.1-4.1+deb10u1_armhf.deb ...
5/1/2022, 12:53:12 AM Unpacking libopenexr23:armhf (2.2.1-4.1+deb10u1) over (2.2.1-4.1) ...
5/1/2022, 12:53:12 AM Setting up perl-modules-5.28 (5.28.1-6+deb10u1) ...
5/1/2022, 12:53:12 AM Setting up hoobsd (4.2.3) ...
5/1/2022, 12:53:12 AM Setting up libopenexr23:armhf (2.2.1-4.1+deb10u1) ...
5/1/2022, 12:53:13 AM Setting up libperl5.28:armhf (5.28.1-6+deb10u1) ...
5/1/2022, 12:53:13 AM Setting up perl (5.28.1-6+deb10u1) ...
5/1/2022, 12:53:13 AM Processing triggers for man-db (2.8.5-2) ...
5/1/2022, 12:53:14 AM Processing triggers for libc-bin (2.28-10+rpt2+rpi1) ...
5/1/2022, 12:53:15 AM  WARNING  service restart command received
5/1/2022, 1:17:23 AM  WARNING  unhandled rejection: TypeError: Invalid Version:
5/1/2022, 1:17:39 AM  WARNING  device reboot command received
5/1/2022, 1:17:40 AM Shutting down
5/1/2022, 1:17:40 AM Hue Bridge stopping
5/1/2022, 1:17:40 AM Shelly Bridge stopping
5/1/2022, 1:17:40 AM Tplink Smarthome Bridge stopping
5/1/2022, 1:17:40 AM Fritz Platform Bridge stopping
5/1/2022, 1:17:41 AM Hue Bridge Hue  WARNING  Conbee 2: websocket connection to ws://192.168.178.27:443 closed - retrying in 15s
5/1/2022, 1:17:42 AM Hue Bridge Hue goodbye
5/1/2022, 1:17:46 AM Stopped


**Additional context**
Add any other context about the problem here.

**Comment by Raczka1989** [comment]
when i will make this fix  curl -sk https://dl.hoobs.org/fix | sudo bash -
it make this

 curl -sk https://dl.hoobs.org/fix | sudo bash -
[ .... ] removing mal-configured sources [ hoobs, nodesource, yarn ]
[ .... ] purging stuck installs
(Reading database ... 86844 files and directories currently installed.)
Removing hoobs-cli (4.2.2) ...
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/socket.io-parser' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/socket.io-client/build' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/signal-exit' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/lazystream' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/is-weakset/.github' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/is-number-object/test' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/is-negative-zero/.github' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/is-date-object' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/is-callable/.github' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/is-bigint/test' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/is-arguments/.github' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/glob' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/es-abstract' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/engine.io-parser' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/engine.io-client' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/core-util-is' not empty so not removed
dpkg: warning: while removing hoobs-cli, directory '/usr/lib/hbs/node_modules/@hoobs/sdk/lib' not empty so not removed
Removing hoobs-gui (4.2.2) ...
Removing hoobsd (4.2.3) ...
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/type-fest' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/systeminformation' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/string_decoder' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/send/node_modules' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/roarr/dist/test/roarr' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/roarr/dist/src/factories' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/qs/test' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/lazystream' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/is-weakset/.github' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/is-number-object/test' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/is-negative-zero/.github' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/is-date-object' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/is-callable/.github' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/is-bigint/test' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/is-arguments/.github' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/http-errors' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/glob' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/formidable' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/es-abstract' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/engine.io-parser' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/engine.io' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/core-util-is' not empty so not removed
dpkg: warning: while removing hoobsd, directory '/usr/lib/hoobsd/node_modules/@types/node' not empty so not removed
[ .... ] removing queued pre and post install scripts
[ .... ] cleaning package manager
Reading package lists...
Building dependency tree...
Reading state information...
[ o.k. ] sources cleaned
[ .... ] removing installed node binaries [ node, npm, npx ]
[ .... ] removing node support files
[ o.k. ] node cleaned
[ .... ] removing services [ hoobs, homebridge, ui-x ]
[ .... ] disabling services
[ .... ] removing conflicting packages [ nginx ]
Failed to stop nginx.service: Unit nginx.service not loaded.
Failed to disable unit: Unit file nginx.service does not exist.
Reading package lists...
Building dependency tree...
Reading state information...
Package 'nginx' is not installed, so not removed
Package 'nginx-full' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[ .... ] repairing wifi captive portal [ wifi-connect ]
[Unit]
Description=WiFi Captive Portal
After=NetworkManager.service
Before=hoobsd.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/wifi-connect-startup

[Install]
WantedBy=multi-user.target
[ .... ] reloading systemd
[ o.k. ] services cleaned
/root/hoobs-fix.sh: line 127: messafe: command not found
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package systemd-timesyncd
[ .... ] upgrading system
Hit:1 http://phoscon.de/apt/deconz buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists...
Hit:1 http://phoscon.de/apt/deconz buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.64.0-4+deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[ .... ] repairing packages [ nodejs, yarn, hoobs ]
Hit:1 http://phoscon.de/apt/deconz buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists...
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x buster main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x buster main
deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main
deb [signed-by=/usr/share/keyrings/hoobs.gpg] https://dl.hoobs.org/debian/ stable main
Hit:1 http://phoscon.de/apt/deconz buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
Get:4 https://dl.hoobs.org/debian stable InRelease [3,032 B]
Get:5 https://deb.nodesource.com/node_16.x buster InRelease [4,584 B]
Get:6 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Get:7 https://dl.hoobs.org/debian stable/main armhf Packages [1,930 B]
Get:8 https://deb.nodesource.com/node_16.x buster/main armhf Packages [783 B]
Get:9 https://dl.yarnpkg.com/debian stable/main all Packages [10.6 kB]
Get:10 https://dl.yarnpkg.com/debian stable/main armhf Packages [10.6 kB]
Fetched 48.7 kB in 2s (28.4 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
nodejs is already the newest version (16.15.0-deb-1nodesource1).
yarn is already the newest version (1.22.18-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Package 'hoobs-cli' is not installed, so not removed
Package 'hoobs-gui' is not installed, so not removed
Package 'hoobsd' is not installed, so not removed
The following packages will be REMOVED:
  hbs-vendor
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 66.6 kB disk space will be freed.
(Reading database ... 68799 files and directories currently installed.)
Removing hbs-vendor (4.1.9) ...
Reading package lists...
Building dependency tree...
Reading state information...
nodejs is already the newest version (16.15.0-deb-1nodesource1).
yarn is already the newest version (1.22.18-1).
The following NEW packages will be installed:
  hbs-vendor hoobs-cli hoobs-gui hoobsd
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 22.8 MB of archives.
After this operation, 238 kB of additional disk space will be used.
Get:1 https://dl.hoobs.org/debian stable/main armhf hbs-vendor all 4.1.9 [2,536 B]
Get:2 https://dl.hoobs.org/debian stable/main armhf hoobs-cli armhf 4.2.2 [3,667 kB]
Get:3 https://dl.hoobs.org/debian stable/main armhf hoobsd armhf 4.2.3 [5,127 kB]
Get:4 https://dl.hoobs.org/debian stable/main armhf hoobs-gui all 4.2.2 [14.0 MB]
Fetched 22.8 MB in 2s (11.1 MB/s)
Selecting previously unselected package hbs-vendor.
(Reading database ... 68795 files and directories currently installed.)
Preparing to unpack .../hbs-vendor_4.1.9_all.deb ...
Unpacking hbs-vendor (4.1.9) ...
Selecting previously unselected package hoobs-cli.
Preparing to unpack .../hoobs-cli_4.2.2_armhf.deb ...
Unpacking hoobs-cli (4.2.2) ...
Selecting previously unselected package hoobsd.
Preparing to unpack .../hoobsd_4.2.3_armhf.deb ...
Unpacking hoobsd (4.2.3) ...
Selecting previously unselected package hoobs-gui.
Preparing to unpack .../hoobs-gui_4.2.2_all.deb ...
Unpacking hoobs-gui (4.2.2) ...
Setting up hoobsd (4.2.3) ...
Setting up hbs-vendor (4.1.9) ...
Setting up hoobs-cli (4.2.2) ...
Setting up hoobs-gui (4.2.2) ...

/usr/lib/hoobsd/node_modules/toidentifier/index.js:26
    .split(' ')
     ^
TypeError: Cannot read properties of undefined (reading 'split')
    at toIdentifier (/usr/lib/hoobsd/node_modules/toidentifier/index.js:26:6)
    at forEachCode (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:245:16)
    at Array.forEach (<anonymous>)
    at populateConstructorExports (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:243:9)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/index.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
 ERROR  /usr/lib/hbs/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
            ^
 ERROR  TypeError: Invalid Version:
    at new SemVer (/usr/lib/hbs/node_modules/semver/classes/semver.js:38:13)
    at compare (/usr/lib/hbs/node_modules/semver/functions/compare.js:3:32)
    at Object.gt (/usr/lib/hbs/node_modules/semver/functions/gt.js:2:29)
    at Object.info (/usr/src/system/index.ts:427:46)
    at Command.<anonymous> (/usr/src/main.ts:52:70)
    at Command.listener [as _actionHandler] (/usr/lib/hbs/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/usr/lib/hbs/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/usr/lib/hbs/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/usr/lib/hbs/node_modules/commander/index.js:1460:12)
    at Command.parse (/usr/lib/hbs/node_modules/commander/index.js:1292:10)
    at Main (/usr/src/main.ts:1050:13)
    at Object.<anonymous> (/usr/bin/hbs:23:27)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[ .... ] repairing packages [ helm ]
Reading package lists...
Building dependency tree...
Reading state information...
helm is already the newest version (2.1.7).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[ o.k. ] packages repaired
[ .... ] installing packages [ watchdog ]
Reading package lists...
Building dependency tree...
Reading state information...
watchdog is already the newest version (5.15-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[ .... ] configuring watchdog to prevent and recover from crashes
[ o.k. ] watchdog configured
[ warn ] rebooting

Hoobs is not starting

**Comment by effxiikc** [comment]
I'm having the same issue. I tried running `curl -sk https://dl.hoobs.org/fix | sudo bash -` 2 times but no luck

**Comment by eXCepT74** [comment]
Have same issue -no luck to fix in any way so finally got fresh image 4.2.1 and reinstalled in RPI. Then restored my full backup i did in SSH console before , because Hoobs web page was dead. At morning i tried again to do update and after i saw that CPU usage was between 50 and 95% - showed by htop on SSH. Web interface sometimes was inaccessible. Now i performed full restart RPI and is better but not perfect. Maybe i will install again 4.2.1 and hold with update.

**Comment by patyi40** [comment]
I have same issue.

**Comment by Dowser** [comment]
Same issue here too.

**Comment by BiGassKanga** [comment]
I'm having the same issues. Going to reinstall and use a backup.

**Comment by DeepGoes** [comment]
Same problem here.. how can I fix it?

**Comment by DeepGoes** [comment]
Found a fix that worked for me here:
https://www.reddit.com/r/HOOBS/comments/ufui0d/hoobs_not_reachable_after_latest_updates/

**Comment by effxiikc** [comment]
Thanks @DeepGoes. I was able to fix my issue.

This is the post and instructions on fixing the problem.

> i had the same problem but with mkellsy's help its fixed.
> 
> what helped me ? got to http://hoobs.local:9090/ and login with hoobs and hoobsadmin.
> 
> then run
> cd /usr/lib/hoobsd/
> sudo yarn add express@latest
> curl -sk https://dl.hoobs.org/fix | sudo bash -
> my system is now running on the latest version and is stable ! :)

**Comment by mkellsy** [comment]
The fix script has changes to handle this error. It's a yarn caching issue.
```
curl -sk https://dl.hoobs.org/fix | sudo bash -
```

If this doesn't work please open a support ticket here.
https://support.hoobs.org/ticket

**Comment by shamasis** [comment]
Apologies for posting on a closed thread. Same issue upon upgrade to latest 4.2.5.

I got UI up and running temporarily by changing two lines. Don't recommend this for long term.

sudo nano /usr/lib/hoobsd/node_modules/toidentifier/index.js line 26
<img width="322" alt="image" src="https://user-images.githubusercontent.com/232373/173276959-766ae467-7adb-4e79-bf7e-add643f214bd.png">
Changed `reutrn str` to `return (str || '')`

sudo nano /usr/lib/hoobsd/node_modules/depd/index.js line 415
<img width="526" alt="image" src="https://user-images.githubusercontent.com/232373/173277080-e702a123-d802-4722-b3ed-938f48d6f4fd.png">
> commented out the `throw` ... really bad thing to do
> added `fn = function () {}` to suppress error

**Comment by joecomo67** [comment]
> Apologies for posting on a closed thread. Same issue upon upgrade to latest 4.2.5.
> 
> I got UI up and running temporarily by changing two lines. Don't recommend this for long term.
> 
> sudo nano /usr/lib/hoobsd/node_modules/toidentifier/index.js line 26 <img alt="image" width="322" src="https://user-images.githubusercontent.com/232373/173276959-766ae467-7adb-4e79-bf7e-add643f214bd.png"> Changed `reutrn str` to `return (str || '')`
> 
> sudo nano /usr/lib/hoobsd/node_modules/depd/index.js line 415 <img alt="image" width="526" src="https://user-images.githubusercontent.com/232373/173277080-e702a123-d802-4722-b3ed-938f48d6f4fd.png">
> 
> > commented out the `throw` ... really bad thing to do
> > added `fn = function () {}` to suppress error

That worked for me - thanks a lot

**Comment by ilyesbenaicha** [comment]
i have the same problem but in windows

**Comment by patyi40** [comment]
Hi,

My advice that use Homebridge.

Az iPhone-omról küldve
