### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: undefined

### ISSUE THREAD

**Issue by motogon** [hoobs-org/HOOBS#1808]
**Description**
There is a problem with starting Hoobs 

UnhandledPromiseRejectionWarning: Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: undefined

**Version**
3.3.12

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Ubuntu 21.10

**List your plugins**
https://plugins.hoobs.org/plugin/@milo526/homebridge-tuya-web
https://plugins.hoobs.org/plugin/homebridge-ewelink
https://plugins.hoobs.org/plugin/homebridge-http-webhooks
https://plugins.hoobs.org/plugin/homebridge-mi-aqara
https://plugins.hoobs.org/plugin/homebridge-mqtt
https://plugins.hoobs.org/plugin/homebridge-plex-v2
https://plugins.hoobs.org/plugin/homebridge-unifi-occupancy-sensor

**Post your config**

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
{
    "server": {
        "port": 8888,
        "origin": "*",
        "autostart": 1,
        "home_setup_id": "X-HM://0023ISYWYL0CH",
        "polling_seconds": 5,
        "docker": false
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "ru",
        "temp_units": "celsius",
        "country_code": "RU",
        "postal_code": "111555",
        "latitude": "55.761062",
        "longitude": "37.828802"
    },
    "bridge": {
        "name": "Lupanovo",
        "port": 51826,
        "pin": "031-45-154",
        "username": "CC:22:3D:E3:CE:40"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "UniFi Occupancy Sensor",
            "plugin_map": {
                "plugin_name": "homebridge-unifi-occupancy-sensor",
                "index": 0
            },
            "name": "Я в Лупаново",
            "mode": "all",
            "interval": 1800,
            "unifi": {
                "site": "default",
                "controller": "https://192.168.3.20:8443",
                "username": "xxxxx",
                "password": "xxxxxxxx"
            },
            "monitor": [
                {
                    "device": "92:83:47:b0:10:42"
                },
                {
                    "device": "be:38:17:0b:5e:39"
                }
            ]
        },
        {
            "accessory": "Plex",
            "name": "Plex Гостинная",
            "plex_token": "xxxxxxxxx",
            "host": "192.168.1.153",
            "filter": [
                {
                    "user": "dend",
                    "player": "LG 65UK6450PLC"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-plex-v2",
                "index": 0
            }
        },
        {
            "accessory": "Plex",
            "name": "Plex Гостинная-1",
            "plex_token": "xxxxxxxx",
            "host": "192.168.1.101",
            "filter": [
                {
                    "user": "dend",
                    "player": "LG 65UK6450PLC"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-plex-v2",
                "index": 0
            }
        },
        {
            "accessory": "Plex",
            "name": "Plex кабинет",
            "plex_token": "xxxxxxxxx",
            "host": "192.168.1.101",
            "filter": [
                {
                    "user": "dend",
                    "player": "Chrome"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-plex-v2",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "name": "mqtt",
            "url": "mqtt://192.168.3.20",
            "port": "1883",
            "platform": "mqtt",
            "plugin_map": {
                "plugin_name": "homebridge-mqtt"
            },
            "qos": 0,
            "topic_type": "multiple",
            "topic_prefix": "homebridge"
        },
        {
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web",
                "debug": true
            },
            "name": "TuyaWebPlatform",
            "scenes": false,
            "options": {
                "platform": "tuya",
                "username": "xxxxxx",
                "password": "xxxxxxx",
                "countryCode": "+7",
                "pollingInterval": 5
            }
        },
        {
            "platform": "HttpWebHooks",
            "plugin_map": {
                "plugin_name": "homebridge-http-webhooks"
            },
            "webhook_port": "12346",
            "webhook_listen_host": "0.0.0.0",
            "sensors": [
                {
                    "id": "sensor2",
                    "name": "Sensor name 2",
                    "type": "motion",
                    "autoRelease": false,
                    "autoReleaseTime": 7500,
                    "debug": false
                }
            ]
        },
        {
            "platform": "MiAqaraPlatform",
            "gateways": {
                "xxxxxxx": "xxxxxxxxx"
            },
            "plugin_map": {
                "plugin_name": "homebridge-mi-aqara"
            }
        },
        {
            "platform": "eWeLink",
            "plugin_map": {
                "plugin_name": "homebridge-ewelink"
            },
            "name": "eWeLink",
            "debug": true,
            "debugReqRes": false,
            "sensorTimeLength": "2",
            "sensorTimeDifference": "120",
            "valveTimeLength": "20",
            "hideTHSwitch": false,
            "hideZBLDPress": false,
            "countryCode": "7",
            "username": "xxxxxxxx",
            "password": "xxxxxxxxx",
            "disableHTTPRefresh": false,
            "disablePlugin": false,
            "inUsePowerThreshold": 0,
            "lowBattThreshold": 25,
            "resetRFBridge": false,
            "mode": "auto",
            "disableNoResponse": true,
            "disableDeviceLogging": true,
            "language": "en",
            "lightDevices": [
                {
                    "deviceId": "1000d7fe5c",
                    "deviceModel": "king",
                    "adaptiveLightingShift": -1,
                    "brightnessStep": 10
                }
            ]
        }
    ]
}```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE

04.05.2022, 19:00:15 (node:69584) UnhandledPromiseRejectionWarning: Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: undefined
04.05.2022, 19:00:15 at Service.addCharacteristic (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Service.ts:344:15)
04.05.2022, 19:00:15 at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:128:15
04.05.2022, 19:00:15 at Array.forEach (<anonymous>)
04.05.2022, 19:00:15 at parseServiceJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:126:19)
04.05.2022, 19:00:15 at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:69:21
04.05.2022, 19:00:15 at Array.forEach (<anonymous>)
04.05.2022, 19:00:15 at Object.parseAccessoryJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:68:17)
04.05.2022, 19:00:15 at Server.createHAPAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:406:36)
04.05.2022, 19:00:15 at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:376:44
04.05.2022, 19:00:15 at Array.forEach (<anonymous>)
04.05.2022, 19:00:15 at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:370:29
04.05.2022, 19:00:15 at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/util/once.ts:9:1804.05.2022, 19:00:15 at HttpWebHooksPlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-http-webhooks/index.js:108:5)
04.05.2022, 19:00:15 at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:369:3004.05.2022, 19:00:15 at new Promise (<anonymous>)
04.05.2022, 19:00:15 at Server.loadPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:368:16)
04.05.2022, 19:00:15 at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:360:36
04.05.2022, 19:00:15 at Array.forEach (<anonymous>)
04.05.2022, 19:00:15 at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:329:31)
04.05.2022, 19:00:15 at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:148:35)04.05.2022, 19:00:15 at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:1604.05.2022, 19:00:15 at processTicksAndRejections (internal/process/task_queues.js:95:5)
04.05.2022, 19:00:15 (Use `node --trace-warnings ...` to show where the warning was created)
04.05.2022, 19:00:15 (node:69584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
04.05.2022, 19:00:15 (node:69584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.04.05.2022, 19:00:15 Got SIGTERM, shutting down Bridge...
```

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
3.3.12 is out of support. Please upgrade to 4.2.5.
https://support.hoobs.org/docs/setup-hoobs-manually
