### ISSUE TITLE
Plugins Are Not Installed After Upgrade

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#181]
Hello,

with the newest Update I had to reinstall all Plugins because no one was recognized.

**Comment by mkellsy** [comment]
I have corrected this issue in 3.0.0-beta-63

**Comment by Bladestar2105** [comment]
Not really...
I updated now and same issue. Have to reinstall all the Plugins...

**Comment by mkellsy** [comment]
How are you installing your plugins? Are you using the interface. Or are you running the commands in the terminal?

**Comment by Bladestar2105** [comment]
I use the Webinterface.

**Comment by mkellsy** [comment]
What plugin's are you using?

**Comment by Bladestar2105** [comment]
Homebridge Hue and these 
![CB7EED6E-401F-435C-98D4-6821CF4F88DE](https://user-images.githubusercontent.com/55372949/66160758-1d3c8b00-e62b-11e9-854c-bd09a7b2c669.png)

**Comment by mkellsy** [comment]
Thanks I am going to try to reproduce and fix.

**Comment by Bladestar2105** [comment]
Beta 64 was installed without problems!

**Comment by mkellsy** [comment]
I did fix this in 3.0.0-beta-63, but 63 had another issue that caused the upgrade process not to complete. I am marking this fixed in 3.0.0-beta.64.

The issue was a
delete current.server.socket;

It should have been
delete config.server.socket;
