### ISSUE TITLE
Hoobs Update needed

### ISSUE THREAD

**Issue by bryangauvin** [hoobs-org/HOOBS#1817]
Just updated Hoobs and it broke Ring plugin completely. All accessories are gone. Please update CORE module to newest version of homebridge

The plugin "homebridge-ring" requires a Homebridge version of >=1.4.0 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

**Comment by mkellsy** [comment]
HOOBS 4.2.7 is on Homebridge 1.4.1.
https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a
