### ISSUE TITLE
Display CPU Temp on Dashboard

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#182]
Display on graph or separate. 
Use the same units for display from settings.

**Comment by mkellsy** [comment]
I need to figure how how @hoobs/systeminfo fetches the temp.

I think it tries to use an obscure method. I need to modify it to use what's built into Raspbian.

**Comment by mkellsy** [comment]
Temp is now in system info. It will only be there if the OS supports reading temps. Raspbian works by default.

Done in 3.0.0-beta.68

**Comment by heardv** [comment]
I see the temp but would like to see a historical graph option.
