### ISSUE TITLE
Hue Config UI without usable fields

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#183]
The Hue Config UI shows the fields but no description so they are not usable.
![2019-10-05 at 12 17](https://user-images.githubusercontent.com/55372949/66253534-38fa7b00-e76a-11e9-8a16-74894bb2b246.png)

**Comment by mkellsy** [comment]
The homebridge-hue doesn't include titles in their config schema.

I added a fallback on the field key, and then humanize it.

Fixed in 3.0.0-beta.65
