### ISSUE TITLE
Issue with init

### ISSUE THREAD

**Issue by Mark1102** [hoobs-org/HOOBS#184]
On both Fedora and Debian I can get HOOBS installed but when I run hoops-init it keeps getting stuck on Installing HOOBS Service

Error is below -

Installing HOOBS Service(node:1708) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'
(node:1708) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at Promise (/usr/lib/node_modules/@hoobs/hoobs/scripts/systemd.js:38:96)
(node:1708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any ideas? Can't work out how to get passed it

Mark

**Comment by mkellsy** [comment]
Missing the root path.

Fixed in 3.0.0-beta.65

**Comment by Mark1102** [comment]
Has that been released?

**Comment by mkellsy** [comment]
Just now.

**Comment by Mark1102** [comment]
When trying to update in the GUI I get

[Homebridge] [05/10/2019, 22:11:08] Got SIGINT, shutting down service...
sudo: /usr/local/lib/node_modules/npm/bin/npm-cli.js: command not found

The host reboots and nothing updates

**Comment by mkellsy** [comment]
In the terminal run this
sudo npm install -g --unsafe-perm @hoobs/hoobs

I will address Fedora's different node location.

**Comment by mkellsy** [comment]
Also on Fedora. You can't use n. N puts Node in /use/local/lib where dnf puts it in /use/lib.

NVM also is not good to use on Fedora.

To fix this you need to uninstall n
sudo uninstall -g n

Delete /use/local/lib/node_modules

Reinstall node
sudo dnf reinstall nodejs

If that fails
sudo dnf install nodejs

Fedora uses the LTS version of Node.

**Comment by Mark1102** [comment]
Im using Debian at the moment is that still needed?

**Comment by mkellsy** [comment]
No. Debian puts Node in /usr/local/lib.

On Debian, N is the best way to get Node up to date.
Run this;

sudo npm install -g n
sudo n stable

This will install Node 10.16.3
It will fix NPM too.

From the error above. HOOBS can't find /usr/local/lib/node_modules/npm/bin/npm-cli.js
This is the main NPM command. It is installed with Node.
This is why I directing you to fix Node.
