### ISSUE TITLE
Can't install really needed Tibber energy price plugin.

### ISSUE THREAD

**Issue by acidkill** [hoobs-org/HOOBS#1841]
**Is your feature request related to a problem? Please describe.**
Yes. There is one widely used plugin for Tibber showing energy price through a day as a graph and actual energy price. I was using it for a long time before I switched from my Homebridge to Hoobs, but this homebridge plugin is not possible to install through plugins and if I install it from console - it doesn't appear in plugins section.
https://github.com/robinjhector/homebridge-tibber-price

**Describe the solution you'd like**
To be able to install this plugin. It can be even configured from homebridge gui so quick win.

**Describe alternatives you've considered**
I installed this plugin instead https://github.com/thomas-alrek/homebridge-tibber-energy-price but spent 4h to make it work and after that gave up.

**Additional context**
Possibility to automate and optimise heating and electrical car charging considering the energy price would be a great feature with energy prices going sky high.

**Comment by askovi** [comment]
It has been added to the database. You should be able to find it now in the plugin search. https://plugins.hoobs.org/plugin/homebridge-tibber-price

**Comment by acidkill** [comment]
Thank you!
