### ISSUE TITLE
Missing official Glue Lock plugin in Hoobs plugins database

### ISSUE THREAD

**Issue by acidkill** [hoobs-org/HOOBS#1842]
**Is your feature request related to a problem? Please describe.**
Glue released their official plugin that is available here https://github.com/GlueHome/homebridge-plugin
Official communication from Glue about the release https://www.gluehome.com/posts/get-homekit-compatible-with-glues-homebridge-plugin

**Describe the solution you'd like**
Adding this plugin that we could be able to install official one

**Describe alternatives you've considered**
I tried installing other plugin that is in the repository, but even when the bridge is running without errors I am not able to add it to my Apple Home in Home app and in Eve

**Comment by askovi** [comment]
The plugin isn't missing. it's right here: https://plugins.hoobs.org/plugin/@gluehome/homebridge-gluehome

**Comment by acidkill** [comment]
OK. My bad. Search in hoobs is not working with that one entering Glue in a search:
![Screenshot 2022-09-28 at 17 52 44](https://user-images.githubusercontent.com/58035493/192826767-b48d47d7-091f-46ea-a846-74cebd4fc14b.png)
![Screenshot 2022-09-28 at 17 53 06](https://user-images.githubusercontent.com/58035493/192826839-1003cf99-e63f-478a-874f-289f5bb5ed64.png)
But searching for a gluehome gives the results. It is a little confusing.
