### ISSUE TITLE
homebridge-ewelink requires a Homebridge version of ^1.6.0 and Higher

### ISSUE THREAD

**Issue by WiehanVanNiekerk** [hoobs-org/HOOBS#1849]
**Description**
The plugin "homebridge-ewelink" requires a Homebridge version of ^1.6.0 || 2.0.0-beta.0 which does not satisfy the current Homebridge version of 1.5.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

**Expected behavoir**
The plugin runs and works as expected.

**Plugin name**
homebridge-ewelink

**Version**
Hoobs Version: 4.2.8
Node Version: 16.19.0
Homebridge Version: 1.5.0

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
Can't remember.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi OS

**Post your log**
```
HouseERROR[31mThe plugin "homebridge-ewelink" requires a Homebridge version of ^1.6.0 || 2.0.0-beta.0 which does not satisfy the current Homebridge version of 1.5.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
1/11/2023, 12:09:13 PMHouseERRORError loading plugin "homebridge-ewelink"
1/11/2023, 12:09:13 PMHouseERRORCannot find module '/var/lib/hoobs/house/node_modules/axios/lib/env/classes/FormData.js' imported from /var/lib/hoobs/house/node_modules/axios/lib/helpers/toFormData.js
1/11/2023, 12:09:13 PMHouseERRORError: Cannot find module '/var/lib/hoobs/house/node_modules/axios/lib/env/classes/FormData.js' imported from /var/lib/hoobs/house/node_modules/axios/lib/helpers/toFormData.js
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:330:11)
    at moduleResolve (node:internal/modules/esm/resolve:907:10)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by bwp91** [comment]
Hi @WiehanVanNiekerk 

replying here as the plugin developer.

The issue is not the warning about homebridge version - the plugin will work with hoobs even if this warning is showing.

The issue is something separate.
And i believe if you simply reinstall the plugin it will fix this

**Comment by WiehanVanNiekerk** [comment]
Hi @bwp91 

After playing with the installation, I got it to work.

The reinstallation of the plugin fixed the problem.
