### ISSUE TITLE
weather forecast ZIP-Code 

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#185]
Zipcodes with 0 in front dont work
01844 skips back to 1844

Original message from FB Chat
Guten Tag Test gerade die neues Version bei der Postleitzahl geht keine 01844 einzugeben springt immer auf 1844 zurück fürs Wetter

**Comment by mkellsy** [comment]
In the guided config the field was text but the value was marked as a number. This is fixed in 3.0.0-beta.66.

In the meantime, you can set the "postal_code" to "01844", use the double quotes, in the Advanced Configuration screen.
