### ISSUE TITLE
Yarn key error

### ISSUE THREAD

**Issue by cleanev** [hoobs-org/HOOBS#1857]
**Description**
Trying to update Raspberry Pi Bullseye throws below error:

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Some index files failed to download. They have been ignored, or old ones used instead

**Version**
4.2.8

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
Raspberry Pi Bullseye
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi Bullseye

**List your plugins**
Bond 
Ring

**Comment by themick4u** [comment]
I’m experiencing same issue:
hoobs:/home/hoobs# apt update && apt -y upgrade && apt -y full-upgrade
Hit:1 https://dl.hoobs.org/debian stable InRelease
Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]                                     
Hit:3 https://deb.nodesource.com/node_16.x buster InRelease                                        
Hit:4 http://archive.raspberrypi.org/debian buster InRelease                           
Hit:5 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease
Err:2 https://dl.yarnpkg.com/debian stable InRelease        
  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
Fetched 17.1 kB in 2s (8,939 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by askovi** [comment]
We just updated all the keys. Please try again.
