### ISSUE TITLE
Setup HOOBS™ Manually ERROR

### ISSUE THREAD

**Issue by JamesJian-tech** [hoobs-org/HOOBS#1862]
**Description**

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x bullseye main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x bullseye main
deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main
deb [signed-by=/usr/share/keyrings/hoobs.gpg] https://dl.hoobs.org/debian/ stable main
Get:1 https://dl.hoobs.org/debian stable InRelease [3,032 B]
Get:2 https://deb.nodesource.com/node_16.x bullseye InRelease [4,586 B]        
Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]                 
Err:1 https://dl.hoobs.org/debian stable InRelease                             
  The following signatures were invalid: EXPKEYSIG 37295289E372DB3E hoobs <info@hoobs.org>
Hit:4 http://raspbian.raspberrypi.org/raspbian bullseye InRelease              
Hit:5 http://archive.raspberrypi.org/debian bullseye InRelease
Get:6 https://deb.nodesource.com/node_16.x bullseye/main armhf Packages [783 B]
Get:7 https://dl.yarnpkg.com/debian stable/main all Packages [10.9 kB]
Get:8 https://dl.yarnpkg.com/debian stable/main armhf Packages [10.9 kB]
Reading package lists... Done   
W: GPG error: https://dl.hoobs.org/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 37295289E372DB3E hoobs <info@hoobs.org>
E: The repository 'https://dl.hoobs.org/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
error executing command

**Comment by askovi** [comment]
We just updated all the keys. Please try installing again

**Comment by JamesJian-tech** [comment]
Thanks. All good.
