### ISSUE TITLE
Log View Needs to Attach to the Main Process

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#187]
Start Service does not work (due to intentionally misconfigured plugin) but logs do no appear at all

**Comment by mkellsy** [comment]
Currently the log only shows activity if the user is logged into the UI. This is a live socket, and needs to be redesigned. This needs to show the console of the main process regardless if the user is logged in or not.

**Comment by mkellsy** [comment]
I actually came up with a simple solution, that doesn't need to attach to a process. I created a log cache that gets sent to the client every time it connects.

This also sends a clear command when the socket connects to prevent duplicate log entries.

Done in 3.0.0-beta.68
