### ISSUE TITLE
Plugins require Node 18

### ISSUE THREAD

**Issue by mrrust310** [hoobs-org/HOOBS#1874]
**Description**
I have a couple of plugins that are not working correctly since they require the Node version to be 18 and above.

I can't figure out how to update the node in Hoobs, the latest seems to be version 16.20.2.

I tried to do the update manually on the terminal but it didn't work.

**Version**
4.3.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Mac OS Ventura 13.5.6

**List your plugins**
SmartThings TV Bridge
Tplink smarthomebridge

**Comment by askovi** [comment]
Please upgrade to HOOBS 5 and use the new HOOBS 5 client apps: https://support.hoobs.org/docs/hoobs-client-apps
