### ISSUE TITLE
Hoobs Homebridge version is too far behind, plugins are not working

### ISSUE THREAD

**Issue by recoi1er** [hoobs-org/HOOBS#1876]
**Description**
Hoobs 4 has fallen behind the times and needs an update, not only the OS but for Homebridge which is at least a 0.x.0 version behind and Node is 5-6 versions behind. Is this software just let to rot now and we should migrate to something else that has a better/current/managed development cycle?

**Version**
4.3.1 the most up to date

**Did you upgrade**
Please let us know if you upgraded from a previous version.
NO

**Pervious version**
n/a

**What device are you using?**
Hoobs SD Card

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
n/a
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
[31mThe plugin "homebridge-eufy-security" requires a Homebridge version of ^1.8.0 || ^2.0.0-beta.0 which does not satisfy the current Homebridge version of 1.7.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m```

**Additional context**
Just need this to be updated to current so plugins can function as they are supposed to

**Comment by askovi** [comment]
Please upgrade to HOOBS 5 and use the new HOOBS 5 client apps: https://support.hoobs.org/docs/hoobs-client-apps
