### ISSUE TITLE
Merge Platforms and Accessory Type Plugins

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#188]
![image (6)](https://user-images.githubusercontent.com/3981552/66324581-b7ceef80-e8f3-11e9-9096-569c0f8c2073.png)

**Comment by mkellsy** [comment]
The visuals is intended, they are not platforms they are accessories.

**Comment by mkellsy** [comment]
Every plugin has a section. If the plugin is a platform, simply show the settings
If the plugin is an accessory type, show an Add Accessory button
If the plugin is both, show the settings and an Add Accessory button

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.68
