### ISSUE TITLE
Weather API not Working with any Canadian ZIP Codes

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#189]
![image](https://user-images.githubusercontent.com/3981552/66324834-3461ce00-e8f4-11e9-82a3-e73c16226228.png)

https://api.openweathermap.org/data/2.5/weather?zip=K0A1K0,CA&units=metric&appid=fec67b55f7f74deaa28df89ba6a60821&callback=__jp0

**Comment by mkellsy** [comment]
https://openweathermap.desk.com/customer/portal/questions/17229700-zip-code-formats-especially-for-canada-

**Comment by mkellsy** [comment]
It looks like OpenWeather only accepts the first 3 characters for Canadian zip codes. I will add some logic in the code.

**Comment by mkellsy** [comment]
I added logic for Canadian zip codes. OpenWeather will only take the first 3 characters.

Done in 3.0.0-beta.68
