### ISSUE TITLE
Possible Initialization Failure on NPM Install

### ISSUE THREAD

**Issue by jeroen1973** [hoobs-org/HOOBS#193]
Yesterday a performed a update to the latest beta version from 2 versions older and now homebridge won’t start all anymore. Reboot, poweroff nothing helps.

**Comment by mkellsy** [comment]
Can you SSH into the device and post your config file
~/.hoobs/etc/config.json

Also can you post the package file
~/.hoobs/package.json

**Comment by mkellsy** [comment]
We are looking into slip streaming this process.

I am guessing here, but I think the upgrade process failed. The process below will reset the user mode, and it will force NPM to re-download your plugins. I am looking into a way to slipstream this.

You can first delete the ~/.npm directory

```bash
sudo rm -fR ~/.npm
```

Then edit this file ~/.hoobs/package.json

```bash
nano ~/.hoobs/package.json
```

Find this line

```
"version: "3.0.0-beta.67",
```

Change it to this

```
"version: "3.0.0-beta.6",
```

The reboot.

**Comment by jeroen1973** [comment]
Thanks Michael for your help! I decided to wait for the final release and flashed back tot V2.1.1 or else the family goes nuts 🥴

Jeroen van der Wal

> Op 9 okt. 2019 om 08:55 heeft Michael Kellsy <notifications@github.com> het volgende geschreven:
> 

﻿
We are looking into slip streaming this process.

I am guessing here, but I think the upgrade process failed. The process below will reset the user mode, and it will force NPM to re-download your plugins. I am looking into a way to slipstream this.

You can first delete the ~/.npm directory

sudo rm -fR ~/.npm
Then edit this file ~/.hoobs/package.json

nano ~/.hoobs/package.json
Find this line

"version: "3.0.0-beta.67",
Change it to this

"version: "3.0.0-beta.6",
The reboot.

**Comment by mkellsy** [comment]
I made the init scripts more fault tolerant. If NPM fails, it will attempt again.

Done in 3.0.0-beta.68
