### ISSUE TITLE
Web Socket Disconnecting and Cached

### ISSUE THREAD

**Issue by originalmagneto** [hoobs-org/HOOBS#194]
I installed HOOBS on top of my existing homebridge setup, I removed .homebridge from the home folder etc., however, for some reason, the hoobs service stops by itself after just a couple of seconds.

See the video here https://www.dropbox.com/s/q9ccefgsxk109pc/screen%20recording%202019-10-09%20at%2017.54.43.mov?dl=0

**Comment by mkellsy** [comment]
Can you post your config.

It is found in
~/.hoobs/etc/config.json

Also what system are you running this on.
- Raspberry Pi
- Mac
- Other Linux

Can you also do a video of the console in your browser. Or just post it.
In Chrome - Right Click and Inspect. Go to the console tab.

I need to determine if Homebridge is crashing or is your browser disconnecting from the web socket used for monitoring.

Also what's confusing is there is no weather information. Does this device have access to the internet?

**Comment by originalmagneto** [comment]
Attaching the config.json

I'm running it on a RPi

PS: I reinstalled it and the weather info is there. Will post my console output later.

https://www.dropbox.com/s/6yd18v46ecymmou/config.json?dl=0

**Comment by mkellsy** [comment]
Chrome is having issues with web sockets.

I think you need to clear the stored images and files from chrome. Don't forget to select from the beginning of time.

You don't need to clear the history or cookies.

I am looking for a way to prevent client side caching of these web sockets.

**Comment by mkellsy** [comment]
I confirmed that the issue is with Chrome. There is actually an open bug on this. To workaround this, I added a ?t=timestamp to the ws:// urls.

This is done in 3.0.0-beta.68

**Comment by originalmagneto** [comment]
@mkellsy I cant get the interface to load on Chrome :/ Is there a way to provide you with the logs that you need?

**Comment by mkellsy** [comment]
Just right click then click on inspect element. The developer tools will show. Go to the console tab and take a screenshot.

That will confirm that the socket is not connecting.
