### ISSUE TITLE
Registration Form Changes

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#195]
![image](https://user-images.githubusercontent.com/3981552/66709861-75197700-ed3a-11e9-985e-1b671fc5c54c.png)
Move 'to HOOBS' in the title so it becomes Welcome to HOOBS in bold yellow.
And the 'To start you need to setup the administrator account' then becomes one line and looks cleaner.

**Comment by mkellsy** [comment]
This will require community translation. Remove both keys, rename them and push them back to Loco.

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.68
