### ISSUE TITLE
Decrease the Required Length of the Username

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#196]
![image](https://user-images.githubusercontent.com/3981552/66709878-c45fa780-ed3a-11e9-8b50-dc49051cd7c7.png)

Username is entered but it still generates a username required error. I assume it has to do with restrictive regex function. 

Regarding the password regex, how much should a secure password be enforced here considering this UI is not likely to be exposed to the internet?

**Comment by askovi** [comment]
The username is still an issue with a 3 letter username. It just says 'Username is required'

**Comment by mkellsy** [comment]
The min length was 5. I lowered this to 3. I was thinking of removing the restriction all together, but I was to prevent the "su" username and the "." username.

This is fixed in the next beta 68 push.
