### ISSUE TITLE
Different System Info for HOOBS Boxes

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#197]
![image](https://user-images.githubusercontent.com/3981552/66709914-d1c96180-ed3b-11e9-9d25-b87b25b4d43b.png)

Model and SKU should differ between boxes we sell, sd cards and downloaded img file. what's the best way to do this? separate img files? 

Also what's the Serial number for?

**Comment by mkellsy** [comment]
The serial number comes from the motherboard.

**Comment by mkellsy** [comment]
We need to be able to tell the difference first

**Comment by mkellsy** [comment]
Set the system to "hoobs-box" for the devices we ship.

Done in 3.0.0-beta.68
