### ISSUE TITLE
Relocate Add User, Edit Accessories and Add Room Buttons

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#198]
![image](https://user-images.githubusercontent.com/3981552/66709950-7fd50b80-ed3c-11e9-94b3-d5db095a5852.png)

Can we move this up right under the last user in the left column. So it lists the users in the system then next option is to add user. Seems more intuitive that way.

**Comment by mkellsy** [comment]
If I move this I will have to move Edit Accessories and Add Room buttons. They all are in the same place.

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.68
