### ISSUE TITLE
Rename User Type to Terminal Access

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#199]
![image](https://user-images.githubusercontent.com/3981552/66709958-b14dd700-ed3c-11e9-8755-c1e51d2924a6.png)

Should display under the User Type when User is selected what it would be able to do.

**Comment by mkellsy** [comment]
Admin users have access to the terminal and can install and configure non certified plugins. Think of users as Rocket users.

**Comment by mkellsy** [comment]
I am going to rename this to Terminal Access with a true and false value.

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.68
