### ISSUE TITLE
Is there anyway to allow access to folders?

### ISSUE THREAD

**Issue by lacedup** [hoobs-org/HOOBS#2]
Is there anyway to allow access to folders. Like some apps need us to. Like I need to do this but I can’t “If you remove a camera from HomeKit for some reason (such as live stream troubleshooting), sometimes it will not show up again in the "Add Device" flow in the Home app. If this happens, follow these steps:
Verify that your homebridge server, HomeKit hub, and the device that you are trying to add the camera on are all on the same network without a firewall/router blocking access between them. Stop homebridge Go into your ~/.homebridge/persist directory and finding any AccessoryInfo.${uniqueId}.json files that relate to your camera. You can open them up and they have the device name right at the start of the file. Keep track of the ${uniqueId} values for your cameras. Delete each camera's AccessoryInfo.${uniqueId}.json and associated IdentifierCache.${uniqueId}.json file Remove the cameras from HomeKit via the Home app Start homebridge Re-add the cameras like you did the first time around”

**Comment by BobbySlope** [comment]
already #planned to delete cache and persist folder for that case
@mkellsy can we show a list and delete only single cached accessories from persist?

**Comment by mkellsy** [comment]
The original plan was to just clear the cache. I will look into listing the accessories.

**Comment by lacedup** [comment]
Also you should leave the terminal commands in a guide, so we can clear cache

**Comment by BobbySlope** [comment]
https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories

we will add that as a button inn v3.0.0

**Comment by mkellsy** [comment]
The reset connection  button in help will remove persist, accessories and update the username.

It does everything from here
https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories
automatically.
