### ISSUE TITLE
Opening Terminal changes menu to dark theme

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#201]
![image](https://user-images.githubusercontent.com/3981552/66710031-3a194280-ed3e-11e9-97c2-790bae709d21.png)

My theme is set to light. Clicking on another menu item brings it back to light theme. I assume it's because we only got css for dark terminal. If that's the case then it's fine like this.

**Comment by mkellsy** [comment]
It is too tough to make a theme based terminal. It requires code modifications. So I copied the log and made it dark.
