### ISSUE TITLE
Plugin Status Monitoring

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#203]
Add a status line under each plugin in the Installed Plugins section. 'Running' in green or 'Stopped' in red with the first line of the error spit by the plugin's log with a link to the logs to find out more.

**Comment by mkellsy** [comment]
I attempted to do this, but to do this properly every plugin would have to add an event to state that it has started properly. Then we can listen for the running/stopped event. I don't think we can get plugin developers to do this.
