### ISSUE TITLE
Empty Search Screen

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#204]
The search tab is empty until you search for something. Maybe add a list of Popular Plugins pulled from here: https://www.npmjs.com/search?q=homebridge&ranking=popularity

Must be marked as Popular Plugins and should disappear when something is searched for.

**Comment by mkellsy** [comment]
I thought about this. It used to be what's installed. Both Config UI and UI X are like this. HOOBS separates it.

All categories have the search. Maybe we should just remove it.

**Comment by mkellsy** [comment]
I tried this and it it clumsy. I don't know if there is a list or it is what I searched. I think it is better to start blank. Plus we have all of the certified plugins before you get to this screen.
