### ISSUE TITLE
homebridge-mi-hygrothermograph installs but not recognised as a plugin

### ISSUE THREAD

**Issue by magnificent3** [hoobs-org/HOOBS#207]
Hi there,
Since installing the v3 beta a few minutes ago, the homebridge-mi-hygrothermograph plugin stopped being recognised.
It even shows up on search, installs, but stops recognising and doesn't show up as a plugin.
On v2 it worked fine.
Can you please take a look at this issue?
Thanks!
Best regards!

**Comment by mkellsy** [comment]
Can you post your config?

Head to the terminal and type
cat ~/.hoobs/etc/config.json

**Comment by mkellsy** [comment]
It won't install for me either. I get this.

```
mkellsy@Mikes-Laptop .hoobs % npm install homebridge-mi-hygrothermograph --unsafe-perm

> @abandonware/noble@1.9.2-2 install /Users/mkellsy/.hoobs/node_modules/@abandonware/noble
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mkellsy/.hoobs/node_modules/@abandonware/noble
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @abandonware/bluetooth-hci-socket@0.5.3-3 (node_modules/@abandonware/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @abandonware/bluetooth-hci-socket@0.5.3-3: wanted {"os":"linux,android,freebsd,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @abandonware/noble@1.9.2-2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @abandonware/noble@1.9.2-2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mkellsy/.npm/_logs/2019-10-16T22_21_49_581Z-debug.log
```

**Comment by magnificent3** [comment]
but on v2 it worked fine...

**Comment by magnificent3** [comment]
Do you know what's causing it?

**Comment by mkellsy** [comment]
I'm looking into it

**Comment by mkellsy** [comment]
I was able to install it. However I am using Beta 68.

In Beta 67 (current) the plugin is there, you have to configure it manually. In Beta 68 we made some changes to the config screen, and it shows. Since this plugin is an accessory type, you need to configure it before it loads.

We are looking to release Beta 68 early next week.

For now you have 2 options.

1. Configure using the Advanced Configuration screen and add the entries to the "accessories" section.
2. Wait for the release of Beta 68.

**Comment by mkellsy** [comment]
If you have a spare SD card you can try Beta 68
[https://github.com/hoobs-org/hoobs-gen/releases/tag/v3.0.0-beta.68](https://github.com/hoobs-org/hoobs-gen/releases/tag/v3.0.0-beta.68)

**Comment by mkellsy** [comment]
If i just could add homebridge-mi-hygrothermograph since it requires Noble. These libraries and their dependencies are required by the Noble library and provide access to the kernel Bluetooth subsystem.
