### ISSUE TITLE
Create a Config Test Tool

### ISSUE THREAD

**Issue by mkellsy** [hoobs-org/HOOBS#208]
In the UI, you can make changes. Once finished you can click Save Changes. I think there should be another button called Test.

This should fire up a test version of Homebridge with the modified configuration, and show the user the output. The test version of Homebridge should be configured on a different port so it wont conflict with the currently running service.

This would be a great way to prevent problems with configuration changes.

**Comment by albertovm** [comment]
Maybe a easy way to solve Hoobs crash after configuration error in plugins should be have a not only a single config.json. Maybe a config.json for each plugin. AND if the personal config for that plugin is wrong, it will read another config_default_empty created by the developer. I believe that OpenHab does close to this.
Or a way to each plugin shutdown, without shutdown Hoobs.
This will keep Hoobs working, even if plugin developer does something wrong.
Regards.

**Comment by mkellsy** [comment]
This is a fair idea, worth exploring.

A little background. HOOBS 3 is a software stack, it is an API server that spawns Homebridge. The UI is simply a static compiled Vue app that runs along with the API. The API and Homebridge are isolated from each other. This is how we keep HOOBS alive when Homebridge crashes. So if a bad plugin is installed, the API and UI are still alive allowing users to fix the issue through the UI.

Then on top of this we have a custom version of Homebridge, which allows us to modify things. We already control the storage path, and the execution of Homebridge, so I am able to simply send the proposed config to the API and fire another instance of Homebridge with the proposed config, completely isolated from the current running version.

The reason why this is proposed for a future version is, we have plans on removing the config.json all together in favor of a database. This way we can sync with the cloud.

**Comment by mkellsy** [comment]
This is done with linting.
