### ISSUE TITLE
EWSLink Max Plugin Performance Degraded

### ISSUE THREAD

**Issue by magnificent3** [hoobs-org/HOOBS#210]
Hi there!
ewelink max is a plugin that reads the status from sonoff switches through the ewelink cloud.
On beta 67 performance was amazing and the status from the different switches updated almost instantly. On beta 68 that is not the case. Now it shows on the home app as No Response.

**Comment by magnificent3** [comment]
It seems that now is always in loop...

`[Homebridge] [10/18/2019, 1:38:42 AM] [eWeLink] API reported that [Social Bathroom] CH 1 is Off
[Homebridge] [10/18/2019, 1:38:42 AM] [eWeLink] API reported that [Social Bathroom] CH 2 is Off
[Homebridge] [10/18/2019, 1:38:47 AM] [eWeLink] Requesting power state for [Living Room Light Switch]
[Homebridge] [10/18/2019, 1:38:47 AM] [eWeLink] Requesting power state for [Kitchen Counter Light]
[Homebridge] [10/18/2019, 1:38:47 AM] [eWeLink] Requesting power state for [Social Bathroom CH 1]
[Homebridge] [10/18/2019, 1:38:47 AM] [eWeLink] Requesting power state for [Social Bathroom CH 2]
[Homebridge] [10/18/2019, 1:38:47 AM] [eWeLink] Requesting power state for [Rooms Hallway Light]
[Homebridge] [10/18/2019, 1:38:47 AM] [eWeLink] API reported that [Rooms Hallway Light] is Off
[Homebridge] [10/18/2019, 1:38:52 AM] [eWeLink] API reported that [Living Room Light Switch] is Off
[Homebridge] [10/18/2019, 1:38:52 AM] [eWeLink] API reported that [Kitchen Counter Light] is Off
[Homebridge] [10/18/2019, 1:38:54 AM] [eWeLink] Requesting power state for [Social Bathroom CH 1]
[Homebridge] [10/18/2019, 1:38:54 AM] [eWeLink] Requesting power state for [Kitchen Counter Light]
[Homebridge] [10/18/2019, 1:38:54 AM] [eWeLink] Requesting power state for [Living Room Light Switch]
[Homebridge] [10/18/2019, 1:38:54 AM] [eWeLink] Requesting power state for [Rooms Hallway Light]
[Homebridge] [10/18/2019, 1:38:54 AM] [eWeLink] Requesting power state for [Social Bathroom CH 2]
[Homebridge] [10/18/2019, 1:38:57 AM] [eWeLink] API reported that [Social Bathroom] CH 1 is Off
[Homebridge] [10/18/2019, 1:38:57 AM] [eWeLink] API reported that [Social Bathroom] CH 2 is Off
[Homebridge] [10/18/2019, 1:39:02 AM] [eWeLink] API reported that [Rooms Hallway Light] is Off
[Homebridge] [10/18/2019, 1:39:02 AM] [eWeLink] API reported that [Social Bathroom] CH 1 is Off
[Homebridge] [10/18/2019, 1:39:07 AM] [eWeLink] API reported that [Kitchen Counter Light] is Off
[Homebridge] [10/18/2019, 1:39:07 AM] [eWeLink] API reported that [Living Room Light Switch] is Off
[Homebridge] [10/18/2019, 1:39:12 AM] [eWeLink] Requesting power state for [Living Room Light Switch]
[Homebridge] [10/18/2019, 1:39:12 AM] [eWeLink] Requesting power state for [Kitchen Counter Light]
[Homebridge] [10/18/2019, 1:39:12 AM] [eWeLink] Requesting power state for [Social Bathroom CH 1]
[Homebridge] [10/18/2019, 1:39:12 AM] [eWeLink] Requesting power state for [Social Bathroom CH 2]
[Homebridge] [10/18/2019, 1:39:12 AM] [eWeLink] Requesting power state for [Rooms Hallway Light]
[Homebridge] [10/18/2019, 1:39:12 AM] [eWeLink] API reported that [Rooms Hallway Light] is Off
[Homebridge] [10/18/2019, 1:39:13 AM] [eWeLink] API reported that [Social Bathroom] CH 2 is Off
[Homebridge] [10/18/2019, 1:39:17 AM] [eWeLink] API reported that [Living Room Light Switch] is Off
[Homebridge] [10/18/2019, 1:39:17 AM] [eWeLink] API reported that [Kitchen Counter Light] is Off
[Homebridge] [10/18/2019, 1:39:22 AM] [eWeLink] Requesting power state for [Living Room Light Switch]
[Homebridge] [10/18/2019, 1:39:22 AM] [eWeLink] Requesting power state for [Kitchen Counter Light]
[Homebridge] [10/18/2019, 1:39:22 AM] [eWeLink] Requesting power state for [Social Bathroom CH 1]
[Homebridge] [10/18/2019, 1:39:22 AM] [eWeLink] Requesting power state for [Social Bathroom CH 2]
[Homebridge] [10/18/2019, 1:39:22 AM] [eWeLink] Requesting power state for [Rooms Hallway Light]
[Homebridge] [10/18/2019, 1:39:22 AM] [eWeLink] API reported that [Social Bathroom] CH 1 is Off
[Homebridge] [10/18/2019, 1:39:23 AM] [eWeLink] API reported that [Social Bathroom] CH 2 is Off
[Homebridge] [10/18/2019, 1:39:28 AM] [eWeLink] API reported that [Rooms Hallway Light] is Off
[Homebridge] [10/18/2019, 1:39:28 AM] [eWeLink] API reported that [Living Room Light Switch] is Off
[Homebridge] [10/18/2019, 1:39:33 AM] [eWeLink] API reported that [Kitchen Counter Light] is Off
[Homebridge] [10/18/2019, 1:39:33 AM] [eWeLink] API reported that [Social Bathroom] CH 1 is Off
[Homebridge] [10/18/2019, 1:39:38 AM] [eWeLink] Requesting power state for [Living Room Light Switch]
[Homebridge] [10/18/2019, 1:39:38 AM] [eWeLink] Requesting power state for [Kitchen Counter Light]
[Homebridge] [10/18/2019, 1:39:38 AM] [eWeLink] Requesting power state for [Social Bathroom CH 1]
[Homebridge] [10/18/2019, 1:39:38 AM] [eWeLink] Requesting power state for [Social Bathroom CH 2]
[Homebridge] [10/18/2019, 1:39:38 AM] [eWeLink] Requesting power state for [Rooms Hallway Light]
[Homebridge] [10/18/2019, 1:39:38 AM] [eWeLink] API reported that [Social Bathroom] CH 2 is Off
[Homebridge] [10/18/2019, 1:39:38 AM] [eWeLink] API reported that [Rooms Hallway Light] is Off`

**Comment by mkellsy** [comment]
There was no real changes with Homebridge between 67 and 68. None the less, I am going to trace the code and see if there were any changes that could have caused this.

**Comment by mkellsy** [comment]
I dug into this. There is not changes in Homebridge or HAP between 67 and 68. Most of 68's changes are to the user interface.

I also researched eWlink. According to [Twitter](https://twitter.com/hashtag/ewelink?lang=en), they have been having some issues in the past week. I would try again, because according to the logs, it looks like it is requesting the power state of your devices and it is re-trying. I don't know why it is retrying but my best guess is it is having issues communicating to eWlink.
