### ISSUE TITLE
Can't Install homebridge-fritz-platform

### ISSUE THREAD

**Issue by florian-muc** [hoobs-org/HOOBS#213]
Coming from multiple earlier versions of HOOBS, I'd love to continue using the homebridge-fritz-platform plugin. It provides many very useful features for Fritz!Box owners, which is the predominant DSL and cable modern/router in Germany.
See https://github.com/SeydX/homebridge-fritz-platform for more info.

Trying to install it on HOOBS 3.0b67 does show progress, but at the end the plugin just isn't there.

**Comment by BobbySlope** [comment]
So you cant find it in plugin search?
We dont have it certified, but you can search for it in the search bar

**Comment by florian-muc** [comment]
Sure, I find it and click the Install button, which makes the progress bar appear and everything looks fine. But when I check "Installed Plugins" afterwards, it is not listed there.

**Comment by florian-muc** [comment]
Let me know if there's anything else I can check.
For the installation of HOOBS 3, I migrated from an existing installation, I believe 2.1.1 that contained the plugins mentioned in #213 and #214.
After migration I found the service to be not running. Checking revealed that homebridge didn't find plugins for the corresponding entries in config.json (these are both platform plugins).

**Comment by mkellsy** [comment]
I can verify that the Fritz Platform (homebridge-fritz-platform) can be installed in Beta 68.

**Comment by florian-muc** [comment]
Not quite for me. It doesn't install. Seems I can't install anything any more on beta 68. Will investigate other possibilities.

**Comment by mkellsy** [comment]
Can you post your config and log.

Menu -> Help -> In the backup click the Config and Log button. Edit your config file after it downloads and remove any passwords.
