### ISSUE TITLE
Support for homebridge-yamaha-avr

### ISSUE THREAD

**Issue by florian-muc** [hoobs-org/HOOBS#214]
Coming from earlier versions of HOOBS, I'd love to continue using the homebridge-yamaha-avr plugin together with my Yamaha receiver. There are multiple variants of that plugin, maybe it makes sense to support all of them. I'm not perfectly happy with any of them, but they still provide useful HomeKit integration of Yamaha receivers.

**Comment by mkellsy** [comment]
Im confused here. Are you saying this plugin can't be installed or you want it certified?

**Comment by mkellsy** [comment]
I can verify that homebridge-yamaha-avr installs in Beta 68. Moving this to the plugin roadmap.

**Comment by defmech** [comment]
When I install this plugin it ruins my whole setup. I have configured my Tradfri bulbs, which work fine, but after install this plugin (v1.0.3) I can't see any accessories in HOOBS at all. I have to uninstall `homebridge-yamaha-avr` and restore from a backup before I get the accessories section back. Any ideas?

```
HOOBS Version | 3.1.22
Homebridge Version | 0.4.50
Node Version | 12.14.1
```

**Comment by mkellsy** [comment]
@defmech this is a closed issue. Your issue may be different. Can you open a new issue.
