### ISSUE TITLE
myQ Garage Door Opener Not Working

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#217]
![image](https://user-images.githubusercontent.com/3981552/67154539-0acd7d00-f2cc-11e9-8a11-4f43d9745a42.png)

No controllable devices found. Works fine from the app.

**Comment by askovi** [comment]
Seems like it's a plugin issue: https://github.com/caseywebdev/homebridge-chamberlain/issues/54

Can you merge this PR into the certified HOOBS myq: https://github.com/caseywebdev/homebridge-chamberlain/pull/55

**Comment by askovi** [comment]
I confirm this fix works:
src/api.js @ line 19 replace:

'User-Agent': 'Chamberlain/3.61.1 (iPhone; iOS 11.4.0; Scale/2.00)',
with
'User-Agent': 'N/A'

**Comment by mkellsy** [comment]
Fixed in @hoobs/chamberlain version 1.0.7

**Comment by mkellsy** [comment]
After the change, my garage door is not opening or closing. I think myQ changed something.

**Comment by mkellsy** [comment]
It's working now.
