### ISSUE TITLE
Multiple Homebridge instances

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#218]
Please make it possible to install and configure multiple homebridge instances.

**Comment by rpolenthon** [comment]
Take a look at this part of the documentation, it also mentions the use of instances, which can be created manually:

https://github.com/hoobs-org/HOOBS/wiki/6.1-Command-Line-Interface

**Comment by mkellsy** [comment]
HOOBS is not Homebridge. It uses Homebridge as a dependency, but it handles instances very differently.

The instructions on how to run instances on HOOBS 3.0 can be found here
[https://github.com/hoobs-org/HOOBS/wiki/6.1-Command-Line-Interface](https://github.com/hoobs-org/HOOBS/wiki/6.1-Command-Line-Interface)

**Comment by Bladestar2105** [comment]
Thank you for the link!
It would be much easier if you implement it directly into HOOBS.
"Create new Homebridge instance"-Button with some GUI fields for the needed information and all the work is done in the background.
As your website describe HOOBS as "USER FRIENDLY HOME AUTOMATION – FOR EVERYONE" this would be very user friendly, probably for version 3.1? :-)

**Comment by mkellsy** [comment]
Already in planning.

**Comment by nicoh88** [comment]
News about this?

**Comment by mkellsy** [comment]
Instructions on this can be found here

https://github.com/hoobs-org/HOOBS/wiki/6.1-Command-Line-Interface

**Comment by nicoh88** [comment]
Hmm. :flushed:

https://github.com/hoobs-org/HOOBS/wiki/6.2-Command-Line-Interface

No HOOBS instances, homebridge instances.

**Comment by mkellsy** [comment]
HOOBS can do that too. It also supports instances across devices too. It's best to start with a clean install. You can install without initializing the default instance with this command.
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --instance
```

1. Create a cluster client once.  `sudo hoobs cluster client`
2. Create an instance `hoobs server -i 'SmartThings'`
3 Repeat step 2 for each instance (does not need to be on the same device)

And fill out the information on the command line.
