### ISSUE TITLE
Delay Homebridge start

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#219]
Hello,

is it possible to delay the homebridge start?
The problem is, that my Zigbee Conbee2-USB-Stick is to slow when initializing after reboot so that not all accessories are loaded.

**Comment by mkellsy** [comment]
Currently there is no delayed start but there is a couple of workarounds.

1. If you edit the ~/.hoobs/etc/config.json file manually using nano. There is an autostart option in the server section. Set this to false. You will have to login to the UI and click Start Service from the menu on the top right.

2. If your USB stick uses a service, you can add it to the wait list in the /etc/systemd/system/hoobs.service or Homebridge.service.

**Comment by Bladestar2105** [comment]
Thank you the first solution works fine. Can you please implement the delay function? My stick has a service and it starts fast but the Initializing after service start is about 10 seconds before the lights are loaded.

**Comment by askovi** [comment]
@mkellsy this delay seems to also be needed for the Ikea Trafri. See trello plugin test results

**Comment by mkellsy** [comment]
I could expose some of the server section settings in the config screen.

Then I can change the autostart setting to an integer value in seconds.

**Comment by mkellsy** [comment]
Done in Beta 69

**Comment by Bladestar2105** [comment]
Is it public? It doesnt show.

**Comment by mkellsy** [comment]
Not released yet. Many changes go into a release. If we released after every change, the version would be something like Beta 2,345,321. :)

**Comment by mkellsy** [comment]
It is released now.

**Comment by Bladestar2105** [comment]
Thank you it works :-)

**Comment by PoppyS33d** [comment]
Would someone mind explaining how you set the delay for Homebridge? I just got a new Mac mini M2 Pro, and it loads Homebridge on startup too quickly, so quick in fact that I'm not even fully online, so it pretty much all fails. I have to restart Homebridge after boot, and then all is well. How do you set the delay? I'm using the GUI...

Thank you!
