### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Mark1102** [hoobs-org/HOOBS#220]
I'm currently on beta.67, when trying to update to beta 68 the bar just keeps going and the update never happens, not sure where to start

Cheers!

**Comment by mkellsy** [comment]
Go to the log and see if there are any errors. Please post these.

**Comment by Mark1102** [comment]
It doesn’t move past this -

[Homebridge] [10/23/2019, 6:17:30 PM] Got SIGINT, shutting down service...
[Homebridge] [10/23/2019, 6:17:30 PM] [HarmonyHub] INFO - shutdown

**Comment by mkellsy** [comment]
Can you open the terminal and run this.

```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

Then post the results. If it succeeds, simply reboot your device and it should be OK.

**Comment by mkellsy** [comment]
Node released a new LTS. One of our core dependencies didn't work on Node 12.13.0. Microsoft released a fixed version on the same day.

So I am working on a Beta 69, with all new updated dependencies that work with Node 12.13.0 and is backward compatible to Node 10.17.0.

**Comment by Mark1102** [comment]
I got it updated by running sudo npm install -g --unsafe-perm @hoobs/hoobs
