### ISSUE TITLE
Migrate All Unrecognized Files from the Storage Path to the New Location

### ISSUE THREAD

**Issue by johannrichard** [hoobs-org/HOOBS#222]
Upon migration of a legacy homebridge installaton via the `lib/migrate.js` script, it would be useful if the ZigBee database was also migrated. Otherwise, the ZigBee config & network is lost, although the plugin is migrated. 

Unless otherwise defined in the config, the ZigBee database is stored as  `homebridge_storage_path/zigbee.db`. Migration could therefore:

1. Check whether the `homebridge-zigbee` plugin is installed
1. If no `database` config parameter is set, `lib/migrate.js` would copy the `zigbee.db` over to HOOB's `etc` folder

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.71
