### ISSUE TITLE
Problems after Hoobs stuck on initialization 

### ISSUE THREAD

**Issue by grabson79** [hoobs-org/HOOBS#223]
I had the same problem as #221  tried
sudo npm install -g --unsafe-perm @hoobs/hoobs
but it did not resolved it.

I now tried
rm -fR ~/.hoobs
hoobs

and hoobs is back, I created new user and password and can login but all my accessories disappeared and the config.json is empty. Also homebridge seems to be very unstable, once I start the service it crashes after a short while

Is there any way to recover the previous config.json file or do I need to start from scratch?

**Comment by mkellsy** [comment]
Beta 69 is released now with support for the new Node version
