### ISSUE TITLE
Issue with Hoobs Certified Ring Pugin

### ISSUE THREAD

**Issue by adavison007** [hoobs-org/HOOBS#224]
I removed my ring plugin and then added the “HOOBS Certified” ring plugin…. I now can't add any ring cameras when hitting add accessories… I deleted each ring camera from homekit and also from the persist file as per the instructions from the homebridge-ring npm instructions…. I never had this issue when adding or removing ring before with the normal homebridge-ring plugin… I also can no longer add this plugin as your web ui only offers me the hoobs certified version (which is many versions behind the actual release) help please?

When looking a the CLI, it does show that the plugin found the devices... but when hitting add accessory in HomeKit, no camera appears...

<img width="853" alt="Test Screen Shot" src="https://user-images.githubusercontent.com/47482260/67845551-94b0ed80-faf7-11e9-9300-b52ed6c76221.png">

**Comment by mkellsy** [comment]
I have released the new version of the ring plugin.

**Comment by adavison007** [comment]
> I have released the new version of the ring plugin.

Thanks, working, but not seeing motion sensors... think it maybe the ring beta I am running
