### ISSUE TITLE
No plugins install on 3.0.0-beta.68 

### ISSUE THREAD

**Issue by adavison007** [hoobs-org/HOOBS#225]
I've rebuilt my PI 5 times tonight to the latest build of hoobs 3.0.0-beta.68 and it will not allow any plugins to be installed unless done i terminal using Sudo...

When I plug in is installed via terminal and you add the info to the json.. homekit fails with this message

<img width="1272" alt="Screenshot 2019-10-31 at 23 54 26" src="https://user-images.githubusercontent.com/47482260/67993677-d47fee00-fc39-11e9-9404-aab7b49a50b5.png">

**Comment by askovi** [comment]
Try flashing beta-69 from here

https://github.com/hoobs-org/hoobs-gen/releases

**Comment by mkellsy** [comment]
Beta 69 is released on NPM now.

**Comment by adavison007** [comment]
> Try flashing beta-69 from here https://github.com/hoobs-org/hoobs-gen/releases
> […](#)

All now working for plugin installs, other than a few plugins with accessories added themselves into the json as platforms.. edited json manually and all was ok
