### ISSUE TITLE
Fresh install fails upgrading to v3 homebridge to hoobs

### ISSUE THREAD

**Issue by sparks3875392** [hoobs-org/HOOBS#226]
I was happily using v2 and decided to move to the v3 beta.
I used the home bridge to hoobs plugin but this fails. I though perhaps it was due to the non standard changes I'd made to my v2 install. So I started with a fresh image using " (Buster) v2.1.1- Release Date: 2019-07-23" 
This has the same issues for me when doing the homebridge to hoobs update 
[2019-11-01T12_48_54_358Z-debug.log](https://github.com/hoobs-org/HOOBS/files/3797953/2019-11-01T12_48_54_358Z-debug.log)

**Comment by mkellsy** [comment]
I release3d beta 69 that addresses this.
