### ISSUE TITLE
Cant install on Mac OS Catalina

### ISSUE THREAD

**Issue by m11rphy** [hoobs-org/HOOBS#227]
HI All,

I have just done a clean install of macOS Catalina, Installed NodeJS and Xcode 11.2 hoover when I try to install HOOBs via terminal I get this error: 

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.8.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chris/.npm/_logs/2019-11-01T16_32_51_878Z-debug.log

**Comment by sparks3875392** [comment]
I think I am getting the same error on rPi - https://github.com/hoobs-org/HOOBS/issues/226#issue-516097820

**Comment by mkellsy** [comment]
I updated to bewta 69. This has the new node-pty code for the new node version.
