### ISSUE TITLE
Hoobs not loading - Bad Gateway - Error 502

### ISSUE THREAD

**Issue by nyxs** [hoobs-org/HOOBS#228]
Hi,
I just installed Hoobs on Ubuntu, followed by the guide here:
[https://github.com/hoobs-org/HOOBS/wiki/2.5.2-Debian-Installation](url)
After finishing everything, I'm entering the IP address of the Ubuntu in the URL and there is only the marquee that loads the system, but nothing happens.
Opening the developer tools shows me an error of bad gateway (502).

What can I do?

**Comment by mkellsy** [comment]
I released beta 69. Try installing hoobs again.
sudo npm install -g --unsafe-perm @hoobs/hoobs

**Comment by nyxs** [comment]
@mkellsy 
Thank you, now it half works. I still had to start Hoobs by myself, and because it's an interactive, I had to start it inside a screen, and not as a service.

**Comment by mkellsy** [comment]
I would run this again
sudo hoobs-init
