### ISSUE TITLE
Error trying to Running HOOBS on Startup

### ISSUE THREAD

**Issue by m11rphy** [hoobs-org/HOOBS#229]
HI All,

Trying to set up Hoobs  Running HOOBS on Startup on MacOS Catalan but getting when I enter ~ % sudo nano /Library/LaunchDaemons/com.hoobs.core.plist

I get this error:
>>> /etc/sudoers: syntax error near line 71 <<<
sudo: parse error in /etc/sudoers near line 71
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
chris@hoobs ~ %

**Comment by mkellsy** [comment]
Can you post your /etc/sudoers file. There's something wrong in there.

**Comment by mkellsy** [comment]
Stale
