### ISSUE TITLE
Cannot add a bridge accessory with the same UUID

### ISSUE THREAD

**Issue by nyxs** [hoobs-org/HOOBS#230]
Hi,
I just got this error:

> [Homebridge] [11/3/2019, 6:33:45 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7896a993-5b3c-467b-aa4a-82253298dc96
[Homebridge] at Bridge.Accessory.addBridgedAccessory (/root/.hoobs/node_modules/hap-nodejs/lib/Accessory.js:268:13)
[Homebridge] at Server.<anonymous> (/root/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:427:26)
[Homebridge] at /root/.hoobs/node_modules/hap-nodejs/lib/util/once.js:16:19
[Homebridge] at BroadlinkRMPlatform.accessories (/root/.hoobs/node_modules/homebridge-platform-helper/platform.js:42:14)
[Homebridge] at Server._loadPlatformAccessories (/root/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:416:22)
[Homebridge] at Server._loadPlatforms (/root/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:343:18)
[Homebridge] at Server.run (/root/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/root/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:78:12)
[Homebridge] at Object.<anonymous> (/root/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:971:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:822:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:730:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12)
[Homebridge] at internal/main/run_main_module.js:16:11
[Homebridge] [11/3/2019, 6:33:45 PM] Got SIGTERM, shutting down service...

The service stops after that.
What can be the problem? I have only one hoobs instance.

**Comment by mkellsy** [comment]
We have seen this before with the BroadlinkRMPlatform. Going to Help and clicking Reset Connection seems to help. This will clear the persisted accessories and rebuild them with different UUIDs.

Menu (Top Right) -> Help -> Reset Connection

You will need to repair with HomeKit after.

**Comment by nyxs** [comment]
It takes too long (after 30 minutes I just stopped it manually, it would still keep running).
Also, tried to perform hoobs-init again, but no luck.
