### ISSUE TITLE
Add an MQTT Broker

### ISSUE THREAD

**Issue by ceraz68** [hoobs-org/HOOBS#231]
**Is your feature request related to a problem? Please describe.**
Lots of IOT devices linked to homebridge support mqtt (eg tasmota, shelly), so a mqtt broker is essential.

**Describe the solution you'd like**
It would be good if Hoobs integrated a basic mqtt server so that Hoobs can centralise everything on a raspberry PI

**Describe alternatives you've considered**
Use an external mqtt server

**Additional context**
In a home environment most people won't deploy fault tolerant systems and forget what they did. Single points of failures pop-up everywhere: APs, Mqtt servers, homebridge, home hubs etc. Centralising services on a PI (homebridge + plugins + mqtt) makes things easy and cost effective, spare microSD and even a spare Pi board.

**Comment by mkellsy** [comment]
We already spawn Homebridge from the API, so spawning a MQTT broker wouldn't be difficult.

**Comment by aliwszyc** [comment]
ANy progress on this?

**Comment by tooluser** [comment]
+1 - it'd be great to see, seems like a good idea.
