### ISSUE TITLE
Confusing password requirements

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#232]
Remove password complexity check but keep 8 chars min req
Display requirement above password field

Also currently the dash char '-' is not recognized as a special char.

**Comment by ravedoglv** [comment]
Installed hoobs on Mac Mojave a few days ago. when I ran hoobs and opened the web page, it required me to set up an admin account. Gave it a username and had 1Password generate a 25 character password based on upper, lower, symbols and numbers. No matter what password I gave it, it would say that the password was too weak. Could not proceed to create an account.

**Comment by mkellsy** [comment]
We are removing this requirement, only length.

**Comment by mkellsy** [comment]
Fixed in beta 70
