### ISSUE TITLE
Support Installing Different Plugin Versions

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#233]
**Description**

PUT http://hoobs.local/api/plugins/homebridge-homematic@0.0.110

returns

{
  "error": "plugin can not be installed"
}

but the plugin is installed on the requested version, defined with @0.0.110.

**Version**
3.0 Beta 69

**Comment by mkellsy** [comment]
Not a bug. This is a feature request.

**Comment by mkellsy** [comment]
The business case for this is this.

Plugins like homebridge-homematic are "slow rollers" their current latest version is 2 years old. Versions 0.0.110 - 1.1.2 are in beta and have been for the last 2 years. Users are installing the plugin using versions to bypass this.

The details screen needs to have support for versions. and the installer needs to support multiple @ symbols.

**Comment by 9SL9** [comment]
I'm trying to install the latest rc version of this without luck. The currently published version 1.4 is broken

**Comment by mkellsy** [comment]
You will have to manually Install it. Here's the instructions. https://github.com/hoobs-org/HOOBS/wiki/4.0-Plugins

The important keys are
1. Your current working directory needs to be ~/.hoobs
2.Install without the -g flag
3. You need to whitelist the plugin and n the config.json

**Comment by mkellsy** [comment]
Done in HOOBS Desktop and HOOBS Server
