### ISSUE TITLE
Error upgrading thru web interface - yellow HOOBS loading screen

### ISSUE THREAD

**Issue by LSWON** [hoobs-org/HOOBS#234]
Hello, recently I saw there was an update to HOOBS. Did the update and waited for it to restart. However, I am now stuck on the yellow loading sceeen, which never proceeds to login. 

Any suggestions? Tried rebooting manually after waiting about 30 min for it to come back with no change.

**Comment by mkellsy** [comment]
**Description**
A clear and concise description of what the bug is.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Add any other context about the problem here.

**Comment by LSWON** [comment]
**Description**
Upgraded thru web interface; now hoobs won't get past yellow loading screen

**Version**
Not sure how to check. It was 3+

**Did you upgrade**
Yes, from 3+

**Pervious version**
Unknown

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
No

**What device are you using?**
Please let us know the device you are running HOOBS on.
 HOOBS SD Card

**If this is a custom install, what's your operating system?**
Raspbian v10

**List your plugins**
Nest (not set up)
Envisalink

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH cat 
````
{
    "server": {
        "port": 51827,
        "socket": 51828,
        "autostart": true,
        "home_setup_id": "X-HM://0023ISYWYCE38",
        "polling_seconds": 2
    },
    "client": {
        "port": 8080,
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "country_code": "US",
        "postal_code": REMOVED
    },
    "bridge": {
        "name": "HOOBS",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "plugins": [
        "nest",
        "chamberlain",
        "homebridge-envisalink"
    ],
    "interfaces": [],
    "accessories": [
        {
            "accessory": "Chamberlain",
            "plugin_map": {
                "plugin_name": "chamberlain",
                "index": 0
            },
            "name": "Garage Door",
            "username": "removed@gmail.com",
            "password": "REMOVED",
            "deviceId": "REMOVED"
        }
    ],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "nest"
            }
        },
        {
            "platform": "Envisalink",
            "host": "192.168.1.174",
            "deviceType": "DSC",
            "password": "REMOVED",
            "pin": "REMOVED",
            "suppressZoneAccessories": false,
            "suppressClockReset": true,
            "partitions": [
                {
                    "name": "Alarm"
                }
            ],
            "zones": [
                {
                    "name": "Front Door",
                    "type": "door",
                    "partition": 1
                },
                {
                    "name": "Living Room Window 1",
                    "type": "window",
                    "partition": 1
                },
                {
                    "name": "Living Room Window 2",
                    "type": "window",
                    "partition": 1
                },
                {
                    "name": "Dining Room Window 1",
                    "type": "window",
                    "partition": 1
                },
                {
                    "name": "Garage Interior Door",
                    "type": "door",
                    "partition": 1
                }
            ]
        }
    ],
    "system": "hoobs"
}          
```

Post your log
You can get the log from the intercafe. This is in the Log section.

POST LOG HERE
```
Error: Cannot find module '../build/Debug/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.loadNative (/home/hoobs/.hoobs/node_modules/node-pty/lib/utils.js:22:16)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js:24:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
homebridge.service: Main process exited, code=exited, status=1/FAILURE
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service RestartSec=3s expired, scheduling restart.
homebridge.service: Scheduled restart job, restart counter is at 604.
Stopped Homebridge.
Started Homebridge.
internal/modules/cjs/loader.js:638
    throw err;
```

Looking at the logs, I keep getting that same error over and over, which forces hoobs to continuously reboot. Any help would be appreciated.

**Comment by LSWON** [comment]
I ended up just hosing and starting over from scratch on the beta 3-70. Easier than trying to figure out what went wrong.

**Comment by mkellsy** [comment]
It looks like node-pty is failing to build on upgrade

**Comment by mkellsy** [comment]
Duplicate of #235
