### ISSUE TITLE
OpenWeather not handling postal codes properly

### ISSUE THREAD

**Issue by albertovm** [hoobs-org/HOOBS#239]
Forecast plugin is not working with Postal Code, and there is not a way to find another way.
Could not use city name, city ID or coordinates? We can find it in openweather.org website.

https://openweathermap.org/city

My old Weather configuration was:

```
   "accessories": [
        {
            "accessory": "Weather",
            "name": "Clima",
            "apikey": "f0e331de678048314650554c6ce3037b",
            "locationByCoordinates": "lat=-20.3201&lon=-40.3377"
        }
    ]

```
Thanks.

**Comment by mkellsy** [comment]
OpenWeatherMap is built into HOOBS 3. The weather can be viewed on the dashboard.

**Comment by albertovm** [comment]
> 
> 
> OpenWeatherMap is built into HOOBS 3. The weather can be viewed on the dashboard.

It is not working, because only accepts ZIP code. However, it is not finding the city based in ZIP code. And OpenWeatherMap do not show ZIP for cities, so we can not detect correct information for closer city.

**Comment by mkellsy** [comment]
HOOBS 3 is using this
https://openweathermap.org/current#zip

And we have both the zip code and country code in the configuration.

![Screen Shot 2019-11-12 at 3 04 23 PM](https://user-images.githubusercontent.com/9777975/68714800-d4e38780-055d-11ea-995a-ac7f3ef6df74.png)

Also which plugin are you referring to? Is it this plugin?
[https://github.com/werthdavid/homebridge-weather](https://github.com/werthdavid/homebridge-weather)?

You may need to open an issue with the plugin developer.

**Comment by albertovm** [comment]
It works for homebridge-weather perfectly.
Hoobs 3 weather DOES NOT work for ZIP. I tried many many ZIP codes from Brazil, Germany and none was found. So... ZIP code is not a valid option (maybe works US only).

**Comment by mkellsy** [comment]
One of our team leads is in Germany and we have done extensive testing on this. Did you set the Country Code?

Can you list the postal codes and country codes you have tried?

**Comment by albertovm** [comment]
Just a sample of each country...

Germany: 68535
Brazil: 29056255

**Comment by mkellsy** [comment]
Added latitude and longitude to the interface config for the weather forecasts.

Here are the new options, respective overrides
1. Latitude and longitude are defined. City ID is looked up on OpenWeather via location
2. Country code and postal code are defined. City ID is looked up on OpenWeather via data
3. No postal code, latitude and longitude. The IP address is used

Done in 3.0.0-beta-71

**Comment by albertovm** [comment]
Thanks a lot.
