### ISSUE TITLE
Update and Migration Assistant - Setup Process

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#24]
We should implement a separate service like the wifi portal that comes after wifi portal to setup HOOBS on first boot. Where the user will be able to migrate data from an old Homebridge he used. 
Activate integrations to Homekit / Alexa / Google so that the user can choose which integrations he want to use and deactivate others. Im thinking of the multistep setupprocess like ring have on their app. Maybe also with activate with hoobs login/ register from website. That we can implement a support platform via webpage integrated in hoobs-core. 

1. Setup Network
2. Update and or Migrate Data
3. Register or Login with HOOBS Account
4. Intitial Setup for Integrations 
5. start Homebridge service
6. kick out from portal and redirect to hoobs.local

**Comment by mkellsy** [comment]
- Setup your HOOBS on Rpi directly from Setupassistant
- Easy Update from any HOOBS Version (without reflashing SD and no HomeKit reset) v1.0/v1.0/v2.0.0/v2.1.0/v2.1.1
- Easy Migration from your existing Homebridge Setup (without reflashing SD and no HomeKit reset)

**Comment by mkellsy** [comment]
The migration is automatic and will move plugins, config, cache and persist on initial run.

NEXT STEP
Find a way to make services on Debian based systems (Debian, Raspian, Ubuntu, ...)

**Comment by mkellsy** [comment]
The setup is for new installs only. I want to;
- Detect if there is a service
- Remove homebridge-config-ui-x service
- Create the homebridge service (may name it hoobs.service)

**Comment by mkellsy** [comment]
NEXT STEP

Create a Homebridge plugin that installs the core and directs the user to reboot.
