### ISSUE TITLE
JSON Schema: "oneOf" not handled correctly

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#241]
I found out that the "oneOf" array for a schema property is not handled correctly. Take a look at the homebridge-zigbee plugin as an example. If you use the hoobs web interface, the selection box is just empty and not usable. The correct behavior would be a textfield, checking the input for the requirements defined with "oneOf".

Take a look at 9.2.1.3 https://json-schema.org/draft/2019-09/json-schema-core.html

The correct implementation can be simulated here: https://hamidihamza.com/Angular6-json-schema-form/?framework=bootstrap-4

**Comment by mkellsy** [comment]
Fixed in 3.0.0-beta.71
