### ISSUE TITLE
Plugin Search not working properly

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#242]
**Description**
When searching for plugins, it keeps searching after every key press and it keeps removing and re-adding results with HOOBS certified plugins forcing themselves on top even if not relevant. Pressing enter on the search makes relevant results disappear. Also characters like dashes seem to be ignored and do not show the results at all. Test case: homebridge-hue
If you search exactly that name it won't show. If you search homebridge hue (With a space) it shows only when completing the name after last key press but if you press enter it disappears.

**Comment by mkellsy** [comment]
this is a thing with NPM, it doesn't like "-". The real issue is Hue is only 3 characters, and the search doesn't start until 4 characters. I lowered this to 3 characters. Now you can search for just "hue".

Fixed in 3.0.1
