### ISSUE TITLE
Change 'Bridge Settings' to 'HOOBS Bridge Settings'

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#243]
Some users seem to think it's related to other bridges such as a Hue bridge. Needs to be clear the settings are for the HOOBS bridge. Same for other settings related to HOOBS

**Comment by mkellsy** [comment]
I tried HOOBS Bridge Settings and it looked out of place. I realized that this more like a plugin so I renamed it to Apple Home and put it on top of the plugins list.

For example my setup looks like this.
* Apple Home
* Chamberlain
* Google Home
* SmartThings

This makes way more sense.

Done in 3.0.1
