### ISSUE TITLE
problem after update to beta 3

### ISSUE THREAD

**Issue by sorriso93** [hoobs-org/HOOBS#245]
**Description**
I can't access web interface no more after upgrading to 3 beta

**Version**
beta 3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
last v2

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Hoobs distribution

**List your plugins**
none

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 2
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {},
    "description": "",
    "ports": {},
    "plugins": [],
    "interfaces": [],
    "accessories": [],
    "platforms": [],
    "package_manager": "npm"
}

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
You closed this issue. What did you do to fix it? Please elaborate for the community.
