### ISSUE TITLE
System backup time out error

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#246]
**Description**
Tested the system backup. It error-ed out in console after about a minute:
![image](https://user-images.githubusercontent.com/3981552/69032044-9872ba00-09a9-11ea-81e2-741994dbc4ab.png)

**Version**
HOOBS 3 beta-74 on Buster Lite

**Post your log**
No relevant logs in console

**Comment by mkellsy** [comment]
This is an issue with NGINX I already fixed this one.

Fixed in 3.0.1
