### ISSUE TITLE
Manual plugin install

### ISSUE THREAD

**Issue by galzil** [hoobs-org/HOOBS#248]
Can you please edit 4.0 Plugins in the Wiki for manual installtion of plugins from folders?
There's a plugin in development, that's not in NPM: 
https://github.com/royby12/homebridge-switcherV2
I tried a few things, but nothing worked, I can't install from git, and there's no:
/usr/local/lib/node_modules/homebridge/
folder in my hoobs installation (there's @hoobs)

**Comment by mkellsy** [comment]
If you are developing a plugin you need to use the developer docs. 4.0 Plugins is for released plugins.

https://github.com/hoobs-org/HOOBS/wiki/6.4-Developing-Plugins
