### ISSUE TITLE
Some plugins cause HOOBS to crash

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#249]
**Description**
Some plugins that need to be registered as accessory only, get added to the config as platform and cause HOOBS to continually crash with the error:

`[Homebridge] [11/18/2019, 8:36:43 PM] Error: The requested platform 'DummySwitch' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:78:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[Homebridge] at startup (internal/bootstrap/node.js:283:19)
[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

**Version**
HOOBS 3 beta-74

List of plugins causing this so far:
Homebridge-Dummy (https://www.npmjs.com/package/homebridge-dummy)
Homebridge-webos-tv (https://www.npmjs.com/package/homebridge-webos-tv?activeTab=readme)

If you remove this part from Advanced config it works fine:

{
            "platform": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy"
            }
 }

**Comment by mkellsy** [comment]
I see what's going on. The config schema is mis-reading the plugin type.

**Comment by mkellsy** [comment]
Fixed in 3.0.1
