### ISSUE TITLE
Hoobs crash after reboot

### ISSUE THREAD

**Issue by oly13** [hoobs-org/HOOBS#251]
**Description**
Every time I reboot my Rpi homebridge crashes

**Version**
3.0.0 beta76

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian Buster

**List your plugins**
Homebridge-Hue

**Post your config**
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY9GF0",
        "polling_seconds": 2
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "E7:7F:7A:6F:2B:31"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "nativeHomeKitLights": "false",
            "nativeHomeKitSensors": "false",
            "nupnp": true,
            "resource": "false",
            "heartrate": null,
            "lights": "true",
            "sensors": "true"
        }
    ]
}

**Post your log**
You can get the log from the intercafe. This is in the Log section.
[Homebridge] [11/21/2019, 7:08:53 PM] [Hue] Rpi: 2 services
[Homebridge] [11/21/2019, 7:08:53 PM] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 545161b7-ee81-41a5-aba1-a0d06be48f74
[Homebridge] at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
[Homebridge] at Server.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:427:26)
[Homebridge] at /home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/util/once.js:16:19
[Homebridge] at request.then.catch.then.then.then.catch.then (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HuePlatform.js:282:5)
[Homebridge] at Function.then (/home/hoobs/.hoobs/node_modules/deferred/_ext.js:65:13)
[Homebridge] at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
[Homebridge] at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)
[Homebridge] at Function.<anonymous> (/home/hoobs/.hoobs/node_modules/deferred/ext/promise/catch.js:29:4)
[Homebridge] at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
[Homebridge] at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)

**Comment by mkellsy** [comment]
Here's the cause

 [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 545161b7-ee81-41a5-aba1-a0d06be48f74

This is coming from your hue plugin. To fix you will have to reset the connection.

Menu -> Help -> Reset Connection.

This will clear the Accessory cache and reset the bridge username. You will have to repair with HomeKit.

**Comment by oly13** [comment]
But its happenning on every reboot. I have to reset it always?

**Comment by mkellsy** [comment]
It's a cache on disk, so it doesn't matter if you reboot. You would have had the same issue with vanilla Homebridge.
