### ISSUE TITLE
Separate Shelly Plugin Binaries to Separate Project

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#253]
command failure because plugin installs no longer in global scope, please fix

hoobs@hoobs:~/.hoobs/etc $ shellies listen
bash: shellies: command not found

hoobs@hoobs:~/.hoobs/etc $ homebridge-shelly describe 192.168.1.4
bash: homebridge-shelly: command not found

**Comment by mkellsy** [comment]
For now you can run this.

```
~/.hoobs/node_modules/@hoobs/shelly/bin/homebridge-shelly describe 192.168.1.4
```

As for **shellies**. The plugin doesn't have this command.

**Comment by BobbySlope** [comment]
`sudo npm install -g shellies` 
then 
`sudo shellies listen`

**Comment by mkellsy** [comment]
This is already done

```
sudo npm install -g shellies
```

Then you can access the same commands from the shellies command
