### ISSUE TITLE
Unifi-Protect-Camera-Motion

### ISSUE THREAD

**Issue by kwalkington** [hoobs-org/HOOBS#256]
**Description**
Doesn't appear to install when installing from UI.

**Expected behavoir**
Installation completing with plugin showing up as a plugin.  Maybe having to add the config text after.

**Plugin name**
Unifi-Protect-Camera-Motion

**Please report the issue to the plugin developer**
https://www.npmjs.com/package/homebridge-unifi-protect-camera-motion

**Version**
3.0 beta 77

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes - 2.1, upgraded, then to BETA 3.0 76, then upgrade to 77
- [ ] No

**Pervious version**
beta 3.0 76

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ x] Yes x yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
-

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Fixed in 3.0.0-beta.78
