### ISSUE TITLE
Unable to Pair with Apple Home

### ISSUE THREAD

**Issue by tedbrittchevy** [hoobs-org/HOOBS#257]
I am trying to install on macOS.   
running macOS Catalina
using fios router where port for homebridge port is open
wired network is 192.168. etc
wireless network is orbi system with 127.0. network
mac is ethernet connected on static ip and on wireless with dhcp

I scan hoobs qr code but it will not add

Hoobs seems to be running fine in terminal dialogue box from hoobs ui

sure it is a network issue but I am stumped.

**Comment by mkellsy** [comment]
Is your router blocking Bonjour (mDNS)

**Comment by tedbrittchevy** [comment]
How would I check?

**Comment by tedbrittchevy** [comment]
Also seeing connect ECONNREFUSED 127.0.0.1:51826

**Comment by mkellsy** [comment]
127.0.0.1 is localhost (loopback) your wireless is probably not on 127.0.x.x that is reserved for loopback. It most likely is 192.168.x.x

**Comment by tedbrittchevy** [comment]
My apologies my wireless is on 10.0. 
The Mac is at 10.0.0.25 and I made static and forwarded 51826 in or I to it.

**Comment by mkellsy** [comment]
Then if your WiFi is on a separate network you need to use NAT and an advanced firewall to control communication between different zones. Is would be much easier to connect your Mac to the WiFi.

**Comment by tedbrittchevy** [comment]
The Mac shows connected on both
