### ISSUE TITLE
Better loading status of Plugin search

### ISSUE THREAD

**Issue by ukypayne** [hoobs-org/HOOBS#258]
**Is your feature request related to a problem? Please describe.**
When searching for a plugin, there is little feedback to notify the user if the search has failed, is partially completed, or fully complete. 

**Describe the solution you'd like**
A loading bar, or at least a spinning wheel would be useful. Possibly even a status of "5 plugins found with search "Google""

**Describe alternatives you've considered**
Waiting patiently after typing anything to search for.

**Comment by BobbySlope** [comment]
I agree with this. Maybe just add a search button and listen for enter key rather than searching after every key press. It’s not intuitive and doesn’t work properly.

**Comment by mkellsy** [comment]
What version are you seeing this in?
2.1.1 or 3.0.0-beta

**Comment by mkellsy** [comment]
I added a loading marquee that will show when the search is taking longer then half a second.

Added in 3.0.1

**Comment by ukypayne** [comment]
Was 3.0.0-beta.77
Thanks!

**Comment by mkellsy** [comment]
You won't see it until we release.
