### ISSUE TITLE
GPIO Status

### ISSUE THREAD

**Issue by ukypayne** [hoobs-org/HOOBS#259]
**Is your feature request related to a problem? Please describe.**
Ability to see live status of GPIO values - similar to using wiringpi and running the command "GPIO readall"

**Describe the solution you'd like**
Something very similar to wiring pi. Or a mix between a graphic that shows all of the pins and a color indicator to show if a pin is high/low and in/out.

**Describe alternatives you've considered**

**Additional context**

**Comment by mkellsy** [comment]
There is already a plug-in for that

https://www.npmjs.com/package/homebridge-gpio-device

**Comment by mkellsy** [comment]
Moved to issue #97

**Comment by ukypayne** [comment]
I don't have the need to change the GPIO settings, I would just like to see the status as a diagnostic option on the dashboard. Does that still fall with #97 ?

**Comment by mkellsy** [comment]
Yep it would be a plug-in. Need to add it to the plug-in roadmap.

**Comment by SRamsdell1** [comment]
> There is already a plug-in for that
> 
> https://www.npmjs.com/package/homebridge-gpio-device

Several attempts to install using search in UI all fail.  I'm current with Hoobs version.  I've a Keysudio 4-ch relay shield I'm trying to use as 4 momentary switches. I've not found a gpio plugin that works correctly with Hoobs and this shield.  Any suggestions ?

**Comment by Johcan** [comment]
I have installed 3.1 HOOBS. I have tried to install the "homebridge-gpio-device" plugin myself but I simply cannot get it to work! I believe it may have to do with the version of Node.js. This HOOBS uses version 12.x.x of Node.js. I believe that "homebridge-gpio-device" only works with Node.js version 8.x.x. or earlier! correct me if wrong.
