### ISSUE TITLE
HOOBS (Running) Chart not showing values.

### ISSUE THREAD

**Issue by ukypayne** [hoobs-org/HOOBS#260]
**Description**
The "HOOBS (Running)" data point on the main chart when logged in doesn't show a datapoint on the chart.

**Version**
3.0.0 Beta 78

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Raspbian

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by ukypayne** [comment]
If the intent isn't to have a value on the chart, I think that the status should be moved out of the chart legend area (along with the Uptime counter).

**Comment by mkellsy** [comment]
This was a design decision by the team. It is either 1 or 0 doesn't make sense to graph that.

**Comment by mkellsy** [comment]
We don't graph the uptime counter either.
