### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#261]
**Description**
UI was loading very slow all of a sudden, now it doesn't load at all and gives a 504 Gateway Time-out error. All homebridge accessories are not responding in Homekit and HOOBS seem to be stopped with no errors visible. Only recent change was updating to beta 77. 

**Version**
HOOBS 3 beta 77

**Comment by askovi** [comment]
SSH also loading very slowly so the whole box is affected. CPU usage was up to 50-60%. Rebooting the box seems to have solved it. No cause identified as of now. This didn't happen before.

**Comment by mkellsy** [comment]
I ran some profiling on it. And it seems that 2 second polling is too short. I increased it to 5 seconds and it is much smoother now.

The polling setting controls how often the system and accessories status is pushed to the client.

**Comment by mkellsy** [comment]
You will need to change this setting and reboot. I changed the default.
