### ISSUE TITLE
Updated Chamberlain plugin breaks under 3.0.0 beta 79

### ISSUE THREAD

**Issue by bgiuriceo** [hoobs-org/HOOBS#262]
**Description**
Chamberlain Plug-In broken 

**Version**
1.08 (HOOBS 3.0.0 Beta 79)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ XXXX] Yes
- [ ] No

**Pervious version**
beta 77

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [XXXX ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ XXXXX] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
This error is published:

[Homebridge] [11/27/2019, 08:00:26] [Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
[Homebridge] at /home/hoobs/.hoobs/node_modules/@hoobs/chamberlain/src/api.js:30:19
[Homebridge] at runMicrotasks (<anonymous>)
[Homebridge] at processTicksAndRejections (internal/process/task_queues.js:93:5)

{Continuous}. 

```
POST LOG HERE
```

**Additional context**
Updated beta 77 to 79, Garage worked perfectly. Update Garage Plug-in and it broke.

**Comment by mkellsy** [comment]
This is due to a change in the Chamberlain myQ API. They moved from version 4 to 5. And they changed the device IDs. To fix, remove your device IDs. Then look at the log to find the new ID.

**Comment by bgiuriceo** [comment]
Thanks for the fast response!….that did it. I was presented with 2 IDs (I only have 1 opener) and selected the first. 

Happy Thanksgiving!

**Comment by mkellsy** [comment]
Same thing with me. I chose the first one and it works.
