### ISSUE TITLE
Fish Shell Failing on Installing NGINX

### ISSUE THREAD

**Issue by Brandonshire** [hoobs-org/HOOBS#264]
**Description**
After running the installer script, Hoobs doesn't start at boot, and has to be run manually. If I log out of my SSH session after starting Hoobs, it will stop.

**Version**
Hoobs V. 3.0.0.0 beta.79

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
I did not upgrade from a previous version though I did have hombridge installed previously (and removed it), and had tried installing Hoobs a few times before finding I needed to kill Pi-Hole first, so that port 80 would be available for nginx to start and finish the installation process. Once that was done, I could change the port nginx used, and theoretically run both at the same time.

I have noticed that if I run Hoobs without typing "sudo" before it I get one config, that doesn't seem to be able to start hombridge, and if I type sudo first I get a different config (with different accessories) that DOES seem to be able to start the homebridge service.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian Buster

**List your plugins**
"Dummy Switches" Plugin

**Post your config**

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYFO6M",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "0A:AE:FA:09:A8:5B"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "name": "Sample"
        }
    ],
    "platforms": []
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[11/28/2019, 02:27:40] HOOBS listning on port 8080.
[Homebridge] [11/28/2019, 02:27:41] Loaded config.json with 1 accessories and 0 platforms.
[Homebridge] [11/28/2019, 02:27:41] ---
[Homebridge] [11/28/2019, 02:27:41] Loaded plugin: homebridge-dummy
[Homebridge] [11/28/2019, 02:27:41] Registering accessory 'homebridge-dummy.DummySwitch'
[Homebridge] [11/28/2019, 02:27:41] ---
[Homebridge] [11/28/2019, 02:27:41] Loading 0 platforms...
[Homebridge] [11/28/2019, 02:27:41] Loading 1 accessories...
[Homebridge] [11/28/2019, 02:27:41] [Sample] Initializing DummySwitch accessory...
[Homebridge] X-HM://0023ISYWYFO6M
[Homebridge] [11/28/2019, 02:27:41] Service is running on port 51826.
```

**Additional context**
It took a number of tries to get the installer script to work as it kept getting stuck on starting nginx. I'm also using Fish as my shell environment, rather than the default Bash. I don't know if that might be an issue or not.

**Comment by mkellsy** [comment]
The install script uses bash. You can run hoobs-init after you install hoobs to try again. The command we use to install nginx is apt-get install nginx. So If it is failing there, there might be something wrong with apt.

Can you run hoobs-init and post the output?

**Comment by Brandonshire** [comment]
So it appears I didn't provide as much information as I thought I did. I _did_ get nginx to finish installing, I just had to kill Pi-Hole first so that port 80 was free, and the nginx service could start once as part of that process, and the installer script seemed to complete. Once that was done I was able to go in and change the port HOOBS was using to 90. Prior to the whole installer script would halt on trying to start up nginx, give me an error (I'm sorry I didn't record it at the time) and stop. Once I got the port situation worked out, nginx installed and started up fine, and the HOOBS installer script seemed to finish up without any complaint. If I manually start HOOBS, it will work, but only so long as I'm logged into that SSH session and it wont' start on it's own when I reboot. I'm pretty sure nginx is working.

When I said "It took a number of tries to get the installer script to work as it kept getting stuck on starting nginx." I was simply saying that I ran the script several times before it successfully ran (after I figured out I needed to kill Pi-hole first), in case running it multiple times might have led to some sort of issue.

I have run hoobs-init a few times, with no apparent change in this behavior, but here's what I get when run hoobs-init without sudo:

> Installing PrerequisitesE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
> E: Unable to lock directory /var/lib/apt/lists/
> (node:25112) UnhandledPromiseRejectionWarning: Error: Command failed: apt-get update
> E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
> E: Unable to lock directory /var/lib/apt/lists/
> 
>     at checkExecSyncError (child_process.js:621:11)
>     at Object.execSync (child_process.js:657:15)
>     at /usr/local/lib/node_modules/@hoobs/hoobs/scripts/prerequisites.js:31:25
>     at new Promise (<anonymous>)
>     at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/prerequisites.js:6:12)
>     at /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs-init:9:104
>     at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs-init:13:3)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
> (node:25112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:25112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ⠙Installing Prerequisites

 It then sits there saying "Installing Prerequisites" indefinitely.

And if I use sudo first...

> Installing Prerequisites
>   Configuring NGINX
> ---------------------------------------------------------
> HOOBS is Installed
> Please redirect your browser to http://hoobs.local
> ---------------------------------------------------------
> The HOOBS interface should apear in 5 - 10 minutes
> depending on how many plugins you have installed.
> ---------------------------------------------------------
>   Rebooting

The Pi then reboots, and everything is the same. HOOBS doesn't run on its own but will run if I manually start it.

**Comment by mkellsy** [comment]
Sorry, You need to run it with sudo
```
sudo hoobs-init
```

Check to see if this file exists
```
cat /etc/systemd/system/hoobs.service
```

It should look like this. It is ok to change it to another user. I do not recommend root.

```
[Unit]
Description=HOOBS
After=network-online.target

[Service]
Type=simple
User=hoobs
ExecStart=/usr/local/bin/hoobs
Restart=on-failure
RestartSec=3
KillMode=process

[Install]
WantedBy=multi-user.target
```

If the file doesn't exist, create it.
If it is already there

```
sudo systemctl enable hoobs
```

Then start it

```
sudo systemctl start hoobs
```

**Comment by Brandonshire** [comment]
Thanks for the replies! The file was  not there. But once I created it that seems to have done it, and it's working now!
I know just enough about this stuff to be dangerous (but this has been a fun project that has taught me a lot). Thanks again for your help and for this great project!
