### ISSUE TITLE
JSON Formatting Help Request. 

### ISSUE THREAD

**Issue by WillShawx** [hoobs-org/HOOBS#265]
Hi, 

I'm Trying To Setup HOOBS With No Previous Experience Of Coding / JSON And Am Running Into An Issue At The JSON Config File Stages. I Was Wondering If Anyone Would Be Able To Help Get My Config Formatted Properly. I Did Try Myself Using jsonlint But To No Joy :(.

Best Wishes, 
Will. 

`{
    "bridge": {
        "name": "HOOBS",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "amber",
            "sudo": true,
            "standalone": true,
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
           "platforms": [{
		"platform": "Ikea Trådfri Gateway",
		"name": "Ikea Trådfri Gateway",
		"securityCode": "WILL EDIT LATER",
		"expose": ["lightbulbs", "outlets", "blinds"]
	}, {
		"platform": "TplinkSmarthome",
		"name": "TplinkSmarthome",
		"broadcast": "255.255.255.0",
		"devices": [],
		"deviceTypes": [],
		"macAddresses": [],
		"excludeMacAddresses": [],
		"pollingInterval": 10,
		"addCustomCharacteristics": true,
		"inUseThreshold": 0,
		"switchModels": ["HS200", "HS210"],
		"timeout": 15
	}, {
		"platform": "WILL EDIT LATER",
		"email": "WILL EDIT LATER",
		"password": "abc123!#"
	}]
}`

EDIT: The Config file isn't displayed properly so I uploaded it as a .json file here (you can.edit directly in Google Drive) - https://drive.google.com/file/d/1FRovxzml2i8iVhh9hBp42NXnVgvIjnwe/view?usp=sharing

**Comment by mkellsy** [comment]
Here you go

```json
{
    "bridge": {
        "name": "HOOBS",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "amber",
            "sudo": true,
            "standalone": true,
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            }
        },
        {
            "platform": "Ikea Trådfri Gateway",
            "name": "Ikea Trådfri Gateway",
            "securityCode": "WILL EDIT LATER",
            "expose": [
                "lightbulbs",
                "outlets",
                "blinds"
            ]
        },
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome",
            "broadcast": "255.255.255.0",
            "devices": [],
            "deviceTypes": [],
            "macAddresses": [],
            "excludeMacAddresses": [],
            "pollingInterval": 10,
            "addCustomCharacteristics": true,
            "inUseThreshold": 0,
            "switchModels": [
                "HS200",
                "HS210"
            ],
            "timeout": 15
        },
        {
            "platform": "WILL EDIT LATER",
            "email": "WILL EDIT LATER",
            "password": "abc123!#"
        }
    ]
}
```

IN the future you can use this site
[https://jsonformatter.curiousconcept.com/](https://jsonformatter.curiousconcept.com/)
