### ISSUE TITLE
Pi Hole Compatability

### ISSUE THREAD

**Issue by stephenmd** [hoobs-org/HOOBS#268]
**Description**
in previous versions of hoobs, installing pihole was possible. i had to flash from the latest beta and it is no longer compatible. unable to install it. run into errors which dont allow the installation to complete

**Version**
latest 3.0 beta

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Can you post the errors?

**Comment by mkellsy** [comment]
HOOBS uses NGINX which clashes with Pi hole. You need to disable it.

```
sudo systemctl stop nginx.service
```

```
sudo systemctl disable nginx.service
```

Then you can install Pi Hole. You can only access HOOBS from port 8080 after NGINX is disabled.
