### ISSUE TITLE
Homebridge service not running

### ISSUE THREAD

**Issue by 9SL9** [hoobs-org/HOOBS#269]
**Description**
I've just installed hoobs following the instructions on your site. When I log into the hoobs.local I see this error "Homebridge service not running". 

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.

- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Raspian buster lite

**List your plugins**
Tuya-lan and Broadlink rm

**Post your config**
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYNI58",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "7C:66:0F:C9:92:36"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-broadlink-rm",
        "homebridge-tuya-lan"
    ],
    "accessories": [],
    "platforms": [
        {},
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "amber",
            "sudo": true,
            "standalone": true,
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "accessories": [
                {
                    "name": "Amp Source",
                    "type": "switch",
                    "enableAutoOff": false,
                    "onDuration": 1,
                    "data": {
                        "on": "260090000001188b12341211123412111211123412111234121112341211123412331311123313111211121112341234123312121233121212331234121112111311123313111233130003490001178c1233131112331212121112341211123412111234121112331333121113331211131112111211121113111211123412331234123412331333123412341211121112000d050000000000000000",
                        "off": "260090000001158e10360f1410360f141013103610131036101310360f1410360f3610131036101310141013101310361013101310141035103610361035101410351036103610131000034b0001158e103510141035101410131036101310360f1410360f1410360f361013103610131014101310131036101310131014103510361036103510140f3610361036101310000d050000000000000000)"
                    }
                },
                {
                    "name": "Amplifier",
                    "type": "switch",
                    "enableAutoOff": false,
                    "onDuration": 1,
                    "data": {
                        "on": "2600dc000b00039e0001188b12341211123412111212123312111333121113331211133312341211123412111211131112331234123412111211121113331234121112111311123313331234120003490001188b12341211123412111211123412111234121112341211123412341211123412111211121113331234123313111211121112341234121112111211133312341234120003490001188b1234121112341211121112341211123412111234121112341233121212331212121112111234123412331211131112111234123313111211121112341234123312000d05000000000000000000000000",
                        "off": "2600dc000b00039e0001188b12341211123412111212123312111333121113331211133312341211123412111211131112331234123412111211121113331234121112111311123313331234120003490001188b12341211123412111211123412111234121112341211123412341211123412111211121113331234123313111211121112341234121112111211133312341234120003490001188b1234121112341211121112341211123412111234121112341233121212331212121112111234123412331211131112111234123313111211121112341234123312000d05000000000000000000000000"
                    }
                },
                {
                    "name": "Amp Volume Down",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 3,
                    "data": [
                        {
                            "data": "2600d8000001188b133312111333121113101234121113331211123412111234113413111134121112341234121112341211101310141112101310131036101310361036103510361000034c0001158e103510141035101410131036101310360f14103512121035103612111036101312341234121110361013101310131014101310131036101310361036103510361000034b0001168d103610131036101310131036101310361013103610131036103510141035101410351036101310361013101310141013101310140f361013103610361036103510000d05",
                            "sendCount": 10,
                            "interval": 0.2,
                            "enableAutoOff": true,
                            "onDuration": 2
                        }
                    ]
                },
                {
                    "name": "Amp Volume Up",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 3,
                    "data": [
                        {
                            "data": "260090000001188b12341211123412111211123412111234121112341211123412341211123412111211123412111234121112111212121112331212123312121233123412341233120003490001188b1234121112341211121211341212113412121134121112341234121112341211121112341211123412111211121212111234121112341211123411341234123412000d050000000000000000",
                            "sendCount": 10,
                            "interval": 0.2,
                            "enableAutoOff": true,
                            "onDuration": 2
                        }
                    ]
                }
            ]
        },
        {
            "platform": "BroadlinkRM",
            "plugin_map": {
                "plugin_name": "homebridge-broadlink-rm"
            }
        },
        {
            "platform": "TuyaLan",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-lan"
            }
        }
    ],
    "interfaces": [],
    "package_manager": "npm",
    "system": "hoobs"

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
[12/2/2019, 8:31:35 PM] HOOBS listning on port 8080.
[Homebridge] [12/2/2019, 8:31:39 PM] Loaded config.json with 0 accessories and 5 platforms.
[Homebridge] [12/2/2019, 8:31:39 PM] ---
[Homebridge] [12/2/2019, 8:31:46 PM] Loaded plugin: homebridge-broadlink-rm
[Homebridge] [12/2/2019, 8:31:46 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[Homebridge] [12/2/2019, 8:31:46 PM] ---
[Homebridge] [12/2/2019, 8:31:47 PM] Loaded plugin: homebridge-tuya-lan
[Homebridge] [12/2/2019, 8:31:47 PM] Registering platform 'homebridge-tuya-lan.TuyaLan'
[Homebridge] [12/2/2019, 8:31:47 PM] ---
[Homebridge] [12/2/2019, 8:31:47 PM] Loading 5 platforms...
[Homebridge] [12/2/2019, 8:31:47 PM] TypeError: Cannot read property 'indexOf' of undefined
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:101:14)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[Homebridge] at startup (internal/bootstrap/node.js:283:19)
[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
Your config has an extra `{},` in the platforms section and it still has the old homebridge-config-ui-x configuration in it. And you had had broadlink defined twice.

Here is your config fixed.

```json
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYNI58",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "7C:66:0F:C9:92:36"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-broadlink-rm",
        "homebridge-tuya-lan"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "accessories": [
                {
                    "name": "Amp Source",
                    "type": "switch",
                    "enableAutoOff": false,
                    "onDuration": 1,
                    "data": {
                        "on": "260090000001188b12341211123412111211123412111234121112341211123412331311123313111211121112341234123312121233121212331234121112111311123313111233130003490001178c1233131112331212121112341211123412111234121112331333121113331211131112111211121113111211123412331234123412331333123412341211121112000d050000000000000000",
                        "off": "260090000001158e10360f1410360f141013103610131036101310360f1410360f3610131036101310141013101310361013101310141035103610361035101410351036103610131000034b0001158e103510141035101410131036101310360f1410360f1410360f361013103610131014101310131036101310131014103510361036103510140f3610361036101310000d050000000000000000)"
                    }
                },
                {
                    "name": "Amplifier",
                    "type": "switch",
                    "enableAutoOff": false,
                    "onDuration": 1,
                    "data": {
                        "on": "2600dc000b00039e0001188b12341211123412111212123312111333121113331211133312341211123412111211131112331234123412111211121113331234121112111311123313331234120003490001188b12341211123412111211123412111234121112341211123412341211123412111211121113331234123313111211121112341234121112111211133312341234120003490001188b1234121112341211121112341211123412111234121112341233121212331212121112111234123412331211131112111234123313111211121112341234123312000d05000000000000000000000000",
                        "off": "2600dc000b00039e0001188b12341211123412111212123312111333121113331211133312341211123412111211131112331234123412111211121113331234121112111311123313331234120003490001188b12341211123412111211123412111234121112341211123412341211123412111211121113331234123313111211121112341234121112111211133312341234120003490001188b1234121112341211121112341211123412111234121112341233121212331212121112111234123412331211131112111234123313111211121112341234123312000d05000000000000000000000000"
                    }
                },
                {
                    "name": "Amp Volume Down",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 3,
                    "data": [
                        {
                            "data": "2600d8000001188b133312111333121113101234121113331211123412111234113413111134121112341234121112341211101310141112101310131036101310361036103510361000034c0001158e103510141035101410131036101310360f14103512121035103612111036101312341234121110361013101310131014101310131036101310361036103510361000034b0001168d103610131036101310131036101310361013103610131036103510141035101410351036101310361013101310141013101310140f361013103610361036103510000d05",
                            "sendCount": 10,
                            "interval": 0.2,
                            "enableAutoOff": true,
                            "onDuration": 2
                        }
                    ]
                },
                {
                    "name": "Amp Volume Up",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 3,
                    "data": [
                        {
                            "data": "260090000001188b12341211123412111211123412111234121112341211123412341211123412111211123412111234121112111212121112331212123312121233123412341233120003490001188b1234121112341211121211341212113412121134121112341234121112341211121112341211123412111211121212111234121112341211123411341234123412000d050000000000000000",
                            "sendCount": 10,
                            "interval": 0.2,
                            "enableAutoOff": true,
                            "onDuration": 2
                        }
                    ]
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-broadlink-rm"
            }
        },
        {
            "platform": "TuyaLan",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-lan"
            }
        }
    ],
    "interfaces": [],
    "package_manager": "npm",
    "system": "hoobs"
}
```
