### ISSUE TITLE
Can the Console be Streamed Over a Socket

### ISSUE THREAD

**Issue by mkellsy** [hoobs-org/HOOBS#27]
Currently the console is transmitted via web sockets, line by line. Colors and special characters are stripped out.

Can the special characters and colors be streamed over the socket? Also, can the command buffer be transmitted? For example, when the interface is compiling, the percents are shown line by line, instead of just updating the current line.

Maybe there's a Node package is available, even if I need to tear the library apart to separate the transmit and receive.

**Comment by rpolenthon** [comment]
@mkellsy

Maybe we found a solution wich allows an easy integration of the colors also on HM client. Currently no colors are supported and no refreshing lines as mentioned.

**Comment by mkellsy** [comment]
@rpolenthon does it work with socket.io?

**Comment by rpolenthon** [comment]
@mkellsy 

I will write you on Slack

**Comment by mkellsy** [comment]
this is done
