### ISSUE TITLE
Convert Homebridge to TypeScript

### ISSUE THREAD

**Issue by mkellsy** [hoobs-org/HOOBS#272]
Homebridge's ECMA version is quite low. Upgrade @hoobs/homebridge  to version 3.1.0. Homebridge would benefit from an upgrade to TypeScript.

**Comment by dgreif** [comment]
There is already a PR to convert it, but it's been sitting for a while: https://github.com/nfarina/homebridge/pull/2266

**Comment by mkellsy** [comment]
Yes I saw that. Still need to test it all. I also want to merge Homebridge and HAP
