### ISSUE TITLE
Some Plugins are Not Migrating During Upgrade

### ISSUE THREAD

**Issue by Fookes74** [hoobs-org/HOOBS#273]
**Description**
Updated to 3.0 via Homebridge to Hoobs plugin. Seemed to stick on rebooting screen. I logged in to HOOBS using IP address of Pi. No accessories showing under Accessories tab but all plugins seem to show. I can also control my devices through Alexa but all devices show 'No Response' in Apple Home App.

**Version**
HOOBS 3.1.1

**Did you upgrade**
Yes

**Pervious version**
Can't recall - Pretty sure it was latest version prior to 3.0

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
As above

**What device are you using?**
Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
```json
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": "*** ***"
    },
    "bridge": {
        "name": "**************",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "170-31-974"
    },
    "description": "HOOBS.",
    "ports": {},
    "accessories": [
        {
            "accessory": "mqtt-switch-tasmota",
            "switchType": "lightbulb",
            "name": "Kitchen Table",
            "url": "mqtt://192.168.1.29",
            "username": "",
            "password": "",
            "topics": {
                "statusGet": "stat/kitchen_lights/RESULT1",
                "statusSet": "cmnd/kitchen_lights/POWER1",
                "stateGet": "tele/kitchen_lights/STATE1"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/kitchen_lights/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/kitchen_lights/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "Relay1"
        },
        {
            "accessory": "mqtt-switch-tasmota",
            "switchType": "lightbulb",
            "name": "Kitchen Oven",
            "url": "mqtt://192.168.1.29",
            "username": "",
            "password": "",
            "topics": {
                "statusGet": "stat/kitchen_lights/RESULT2",
                "statusSet": "cmnd/kitchen_lights/POWER2",
                "stateGet": "tele/kitchen_lights/STATE2"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/kitchen_lights/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/kitchen_lights/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "Relay2"
        },
        {
            "accessory": "mqtt-switch-tasmota",
            "switchType": "lightbulb",
            "name": "Kitchen Cupboards",
            "url": "mqtt://192.168.1.29",
            "username": "",
            "password": "",
            "topics": {
                "statusGet": "stat/kitchen_lights/RESULT3",
                "statusSet": "cmnd/kitchen_lights/POWER3",
                "stateGet": "tele/kitchen_lights/STATE3"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/kitchen_lights/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/kitchen_lights/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "Relay3"
        },
        {
            "name": "TV Lamp",
            "hostname": "192.168.1.37",
            "accessory": "SonoffTasmotaHTTP"
        },
        {
            "name": "Table Lamp",
            "hostname": "192.168.1.70",
            "accessory": "SonoffTasmotaHTTP"
        },
        {
            "name": "French Doors",
            "hostname": "192.168.1.72",
            "accessory": "SonoffTasmotaHTTP"
        },
        {
            "name": "Hall Lamp",
            "hostname": "192.168.1.46",
            "accessory": "SonoffTasmotaHTTP"
        },
        {
            "name": "Coffee",
            "hostname": "192.168.1.74",
            "accessory": "SonoffTasmotaHTTP"
        },
        {
            "name": "Bedroom Bulbs",
            "hostname": "192.168.1.51",
            "accessory": "SonoffTasmotaHTTP"
        },
        {
            "name": "Star Lamp",
            "hostname": "192.168.1.71",
            "accessory": "SonoffTasmotaHTTP"
        },
        {
            "name": "Flower Lamp",
            "hostname": "192.168.1.53",
            "accessory": "SonoffTasmotaHTTP"
        },
        {
            "name": "Fairy Lights",
            "hostname": "192.168.1.68",
            "accessory": "SonoffTasmotaHTTP"
        },
        {
            "accessory": "RaspberryPiTemperature",
            "name": "RaspberryPi CPU Temperature"
        },
        {
            "accessory": "Smartglass",
            "name": "Xbox One",
            "liveid": "F**************D5",
            "consoleip": "192.168.1.66"
        },
        {
            "accessory": "DummySwitch",
            "name": "Home Security",
            "stateful": true,
            "reverse": false
        }
    ],
    "platforms": [
        {
            "platform": "yeelight",
            "name": "Yeelight"
        },
        {
            "platform": "MiAqaraPlatform",
            "gateways": {
                "***********": "*********************"
            }
        },
        {
            "platform": "WeatherPlus",
            "name": "WeatherPlus",
            "service": "darksky",
            "units": "uk",
            "forecast": [
                1,
                2
            ],
            "key": "ee77470cad44c2f7175ed51211184898",
            "locationGeo": [
                53.09538989,
                -1.58314705
            ]
        },
        {
            "platform": "People",
            "anyoneSensor": true,
            "nooneSensor": true,
            "people": [
                {
                    "name": "Chris",
                    "target": "192.168.1.64"
                },
                {
                    "name": "Helen",
                    "target": "192.168.1.47"
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg-omx",
            "cameras": [
                {
                    "name": "Utility Room Cam",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.52/ch0_1.h264",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 30,
                        "maxBitrate": 200,
                        "vcodec": "h264_omx",
                        "audio": false,
                        "motion": true,
                        "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
                        "debug": false
                    }
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg-omx",
            "cameras": [
                {
                    "name": "Garage Cam",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.36/ch0_1.h264",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 30,
                        "maxBitrate": 200,
                        "vcodec": "h264_omx",
                        "audio": false,
                        "motion": true,
                        "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
                        "debug": false
                    }
                }
            ]
        },
        {
            "name": "Alexa",
            "username": "Rolo",
            "password": "Tamasi01",
            "pin": "***-**-***",
            "routines": true,
            "debug": true,
            "platform": "Alexa"
        }
    ]
}
```

**Post your log**
```
[12/4/2019, 14:45:58] HOOBS listning on port 8080.
[Homebridge] [12/4/2019, 14:45:59] Loaded config.json with 15 accessories and 7 platforms.
[Homebridge] [12/4/2019, 14:45:59] ---
[Homebridge] [12/4/2019, 14:45:59] Loaded plugin: homebridge-camera-ffmpeg-omx
[Homebridge] [12/4/2019, 14:45:59] Registering platform 'homebridge-camera-ffmpeg-omx.Camera-ffmpeg-omx'
[Homebridge] [12/4/2019, 14:45:59] ---
[Homebridge] [12/4/2019, 14:45:59] Loaded plugin: homebridge-dummy
[Homebridge] [12/4/2019, 14:45:59] Registering accessory 'homebridge-dummy.DummySwitch'
[Homebridge] [12/4/2019, 14:45:59] ---
[Homebridge] [12/4/2019, 14:46:00] Loaded plugin: homebridge-mi-aqara
[Homebridge] [12/4/2019, 14:46:00] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[Homebridge] [12/4/2019, 14:46:00] ---
[Homebridge] [12/4/2019, 14:46:00] Loaded plugin: homebridge-mqtt-switch-tasmota
[Homebridge] [12/4/2019, 14:46:00] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[Homebridge] [12/4/2019, 14:46:00] ---
[Homebridge] [12/4/2019, 14:46:01] Loaded plugin: homebridge-people-guest-mode
[Homebridge] [12/4/2019, 14:46:01] Registering platform 'homebridge-people-guest-mode.People'
[Homebridge] [12/4/2019, 14:46:01] Registering accessory 'homebridge-people-guest-mode.PeopleAccessory'
[Homebridge] [12/4/2019, 14:46:01] Registering accessory 'homebridge-people-guest-mode.PeopleAllAccessory'
[Homebridge] [12/4/2019, 14:46:01] Registering accessory 'homebridge-people-guest-mode.GuestModeSwitch'
[Homebridge] [12/4/2019, 14:46:01] ---
[Homebridge] [12/4/2019, 14:46:01] Loaded plugin: homebridge-raspberrypi-temperature
[Homebridge] [12/4/2019, 14:46:01] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[Homebridge] [12/4/2019, 14:46:01] ---
[Homebridge] [12/4/2019, 14:46:01] Loaded plugin: homebridge-smartglass
[Homebridge] [12/4/2019, 14:46:01] Registering accessory 'homebridge-smartglass.Smartglass'
[Homebridge] [12/4/2019, 14:46:01] ---
[Homebridge] [12/4/2019, 14:46:01] Loaded plugin: homebridge-sonoff-tasmota-http
[Homebridge] [12/4/2019, 14:46:01] Registering accessory 'homebridge-sonoff-tasmota-http.SonoffTasmotaHTTP'
[Homebridge] [12/4/2019, 14:46:01] ---
[Homebridge] [12/4/2019, 14:46:01] Loaded plugin: homebridge-yeelight-wifi
[Homebridge] [12/4/2019, 14:46:01] Registering platform 'homebridge-yeelight.yeelight'
[Homebridge] [12/4/2019, 14:46:01] ---
[Homebridge] [12/4/2019, 14:46:01] Loading 7 platforms...
[Homebridge] [12/4/2019, 14:46:01] [Yeelight] Initializing yeelight platform...
[Homebridge] [12/4/2019, 14:46:01] [Yeelight] starting YeePlatform using homebridge API v2.4
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] [INFO]**************************************************************
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.8.0 By YinHang
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] [INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] [INFO]                                         QQ Group: 107927710
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] [INFO]**************************************************************
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] [INFO]start success...
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] [INFO]config gateways: 7811dc64e359
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] [INFO]binding to the default interface
[Homebridge] [12/4/2019, 14:46:01] Error: The requested platform 'WeatherPlus' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[Homebridge] [12/4/2019, 14:46:01] [MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: 9898
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
```

**Additional context**

**Comment by mkellsy** [comment]
It looks like the weather plus plugin is crashing Homebridge.

**Comment by askovi** [comment]
As a temporary fix, remove this from the advanced config then save:

 {
"platform": "WeatherPlus",
"name": "WeatherPlus",
"service": "darksky",
"units": "uk",
"forecast": [
1,
2
],
"key": "ee77470cad44c2f7175ed51211184898",
"locationGeo": [
53.09538989,
-1.58314705
]
},

**Comment by Fookes74** [comment]
Just noticed that I can't see the Weather Plus plugin - it seems to have been removed in the update. Would that be right?

**Comment by Fookes74** [comment]
Restart, Start and Stop Service tabs are all greyed out too. Hard restart after removing the config you advise?

**Comment by mkellsy** [comment]
Yes you can try to install the weather plus plugin. I will look at it when I get off work today.

**Comment by Fookes74** [comment]
Removed Weather Plus from config. Rebooted Pi via SSH.

Still no accessories showing in Accessories tab.

Logs now show this:

[12/4/2019, 16:05:24] HOOBS listning on port 8080.
[Homebridge] [12/4/2019, 16:05:25] Loaded config.json with 15 accessories and 6 platforms.
[Homebridge] [12/4/2019, 16:05:25] ---
[Homebridge] [12/4/2019, 16:05:25] Loaded plugin: homebridge-camera-ffmpeg-omx
[Homebridge] [12/4/2019, 16:05:25] Registering platform 'homebridge-camera-ffmpeg-omx.Camera-ffmpeg-omx'
[Homebridge] [12/4/2019, 16:05:25] ---
[Homebridge] [12/4/2019, 16:05:25] Loaded plugin: homebridge-dummy
[Homebridge] [12/4/2019, 16:05:25] Registering accessory 'homebridge-dummy.DummySwitch'
[Homebridge] [12/4/2019, 16:05:25] ---
[Homebridge] [12/4/2019, 16:05:26] Loaded plugin: homebridge-mi-aqara
[Homebridge] [12/4/2019, 16:05:26] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[Homebridge] [12/4/2019, 16:05:26] ---
[Homebridge] [12/4/2019, 16:05:26] Loaded plugin: homebridge-mqtt-switch-tasmota
[Homebridge] [12/4/2019, 16:05:26] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[Homebridge] [12/4/2019, 16:05:26] ---
[Homebridge] [12/4/2019, 16:05:27] Loaded plugin: homebridge-people-guest-mode
[Homebridge] [12/4/2019, 16:05:27] Registering platform 'homebridge-people-guest-mode.People'
[Homebridge] [12/4/2019, 16:05:27] Registering accessory 'homebridge-people-guest-mode.PeopleAccessory'
[Homebridge] [12/4/2019, 16:05:27] Registering accessory 'homebridge-people-guest-mode.PeopleAllAccessory'
[Homebridge] [12/4/2019, 16:05:27] Registering accessory 'homebridge-people-guest-mode.GuestModeSwitch'
[Homebridge] [12/4/2019, 16:05:27] ---
[Homebridge] [12/4/2019, 16:05:27] Loaded plugin: homebridge-raspberrypi-temperature
[Homebridge] [12/4/2019, 16:05:27] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[Homebridge] [12/4/2019, 16:05:27] ---
[Homebridge] [12/4/2019, 16:05:27] Loaded plugin: homebridge-smartglass
[Homebridge] [12/4/2019, 16:05:27] Registering accessory 'homebridge-smartglass.Smartglass'
[Homebridge] [12/4/2019, 16:05:27] ---
[Homebridge] [12/4/2019, 16:05:27] Loaded plugin: homebridge-sonoff-tasmota-http
[Homebridge] [12/4/2019, 16:05:27] Registering accessory 'homebridge-sonoff-tasmota-http.SonoffTasmotaHTTP'
[Homebridge] [12/4/2019, 16:05:27] ---
[Homebridge] [12/4/2019, 16:05:27] Loaded plugin: homebridge-yeelight-wifi
[Homebridge] [12/4/2019, 16:05:27] Registering platform 'homebridge-yeelight.yeelight'
[Homebridge] [12/4/2019, 16:05:27] ---
[Homebridge] [12/4/2019, 16:05:27] Loading 6 platforms...
[Homebridge] [12/4/2019, 16:05:27] [Yeelight] Initializing yeelight platform...
[Homebridge] [12/4/2019, 16:05:27] [Yeelight] starting YeePlatform using homebridge API v2.4
[Homebridge] [12/4/2019, 16:05:27] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[Homebridge] [12/4/2019, 16:05:27] [MiAqaraPlatform] [INFO]**************************************************************
[Homebridge] [12/4/2019, 16:05:27] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.8.0 By YinHang
[Homebridge] [12/4/2019, 16:05:27] [MiAqaraPlatform] [INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara
[Homebridge] [12/4/2019, 16:05:27] [MiAqaraPlatform] [INFO]                                         QQ Group: 107927710
[Homebridge] [12/4/2019, 16:05:27] [MiAqaraPlatform] [INFO]**************************************************************
[Homebridge] [12/4/2019, 16:05:27] [MiAqaraPlatform] [INFO]start success...
[Homebridge] [12/4/2019, 16:05:27] [MiAqaraPlatform] [INFO]config gateways: 7811dc64e359
[Homebridge] [12/4/2019, 16:05:27] [MiAqaraPlatform] [INFO]binding to the default interface
[Homebridge] [12/4/2019, 16:05:27] [People] Initializing People platform...
[Homebridge] [12/4/2019, 16:05:27] [People] Initializing platform accessory 'Chris'...
[Homebridge] [12/4/2019, 16:05:27] [People] Initializing platform accessory 'Helen'...
[Homebridge] [12/4/2019, 16:05:27] [People] Initializing platform accessory 'Guest Mode'...
[Homebridge] [12/4/2019, 16:05:27] [People] Initializing platform accessory 'Anyone'...
[Homebridge] [12/4/2019, 16:05:27] [People] WebHook: Started server on port '51828'.
[Homebridge] [12/4/2019, 16:05:27] [Camera-ffmpeg-omx] Initializing Camera-ffmpeg-omx platform...
[Homebridge] [12/4/2019, 16:05:27] [Camera-ffmpeg-omx] Initializing Camera-ffmpeg-omx platform...
[Homebridge] [12/4/2019, 16:05:27] Error: The requested platform 'Alexa' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[Homebridge] [12/4/2019, 16:05:28] [MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: 9898
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826

**Comment by Fookes74** [comment]
Anything on this? 

I've removed Weather Plus config (plugin was removed during upgrade to 3.1.1) but it's still failing - logs as per above. I've noticed that my homebridge-people-guest-mode plugin is shown as installed but under advanced there seems to be a tab for guest mode which as some config shown which I've not input. Help!!!

![Screenshot 2019-12-04 at 17 06 14](https://user-images.githubusercontent.com/37369430/70164367-f21cf900-16b8-11ea-9e71-9f5bac0ab696.png)
![Screenshot 2019-12-04 at 17 06 42](https://user-images.githubusercontent.com/37369430/70164369-f21cf900-16b8-11ea-86dd-abba0716f30c.png)

**Comment by mkellsy** [comment]
Let me take a look.

Can you go to Menu -> Help and then click on Remote Support. Post the code that it gives you.

**Comment by Fookes74** [comment]
SB7-J0V

**Comment by Fookes74** [comment]
@mkellsy - Am I leaving it connected? Not sure what is meant to be happening after I clicked on it?

**Comment by mkellsy** [comment]
If it starts, make sure you create a System backup. Configuration -> Backup -> System.

I got into it and fixed the config.json for you. It looks like the Alexa plugin was missing too. You will need to install the homebridge-alexa plugin and reconfigure it.

You can try to install weather-plus too.

**Comment by Fookes74** [comment]
Ok, many thanks.

It's gone in and accessories are showing up. Apple Home app also shows tiles now 'live'. So no Alexa either? Is it still configured in my config and, if so, do I need to remove that first? Why were both Alexa and Weather Plus both removed when updating?

**Comment by Fookes74** [comment]
@mkellsy - Doesn't seem to want to take a System backup - the yellow 'in progress' bar going left to right and back hasn't changed.

**Comment by mkellsy** [comment]
The plugins didn't install on the migration when you upgraded. I will look into why.

Create a system backup now. Configuration -> Backup -> System
It will download a .hbf file. Keep that safe.

Now you can try to install the missing plugins from the plugin screen. It it breaks, you can use the backup (.hbs) file. and restore to a working state.

**Comment by Fookes74** [comment]
Tell a lie - it's now done it.

**Comment by mkellsy** [comment]
The backup takes a while, it backup all your plugins too.

**Comment by Fookes74** [comment]
Sorry, but my personal feeling is that this update is not ready for general release). 

I've added Alexa plugin (although it just sits processing it and doesn't do anything unless you switch to another page and it then shows as installed - now it's showing that I only have two installed plugins!!! What on earth is going on? All devices in Home app now back to 'No Response'

**Comment by Fookes74** [comment]
@mkellsy 

New log:
+ homebridge-alexa@0.4.43
added 40 packages from 33 contributors, removed 35 packages, moved 2 packages and audited 1457 packages in 24.563s

2 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities

┌─────────────────────────────────────────────────────────┐
│                 npm update check failed                 │
│           Try running with sudo or get access           │
│          to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/hoobs/.config │
└─────────────────────────────────────────────────────────┘
[12/4/2019, 18:01:08] Installed "homebridge-alexa" package.
[Homebridge] [12/4/2019, 18:01:11] Loaded config.json with 15 accessories and 5 platforms.
[Homebridge] [12/4/2019, 18:01:11] ---
[Homebridge] [12/4/2019, 18:01:13] Loaded plugin: homebridge-alexa
[Homebridge] [12/4/2019, 18:01:13] Registering platform 'homebridge-alexa.Alexa'
[Homebridge] [12/4/2019, 18:01:13] ---
[Homebridge] [12/4/2019, 18:01:13] Loaded plugin: homebridge-mi-aqara
[Homebridge] [12/4/2019, 18:01:13] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[Homebridge] [12/4/2019, 18:01:13] ---
[Homebridge] [12/4/2019, 18:01:13] Loading 5 platforms...
[Homebridge] [12/4/2019, 18:01:13] Error: The requested platform 'yeelight' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[Homebridge] [12/4/2019, 18:08:13] Got SIGINT, shutting down service...
[Homebridge] [12/4/2019, 18:08:15] Loaded config.json with 15 accessories and 5 platforms.
[Homebridge] [12/4/2019, 18:08:15] ---
[Homebridge] [12/4/2019, 18:08:17] Loaded plugin: homebridge-alexa
[Homebridge] [12/4/2019, 18:08:17] Registering platform 'homebridge-alexa.Alexa'
[Homebridge] [12/4/2019, 18:08:17] ---
[Homebridge] [12/4/2019, 18:08:18] Loaded plugin: homebridge-mi-aqara
[Homebridge] [12/4/2019, 18:08:18] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[Homebridge] [12/4/2019, 18:08:18] ---
[Homebridge] [12/4/2019, 18:08:18] Loading 5 platforms...
[Homebridge] [12/4/2019, 18:08:18] Error: The requested platform 'yeelight' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826

**Comment by mkellsy** [comment]
It looks like your upgrade process didn't complete. I will look at that code tonight when I'm off work. Can't get fired.

I can help install the missing plugins. The were missing in the package.json, and I missed it. If you click on Remote Support again and post the code. I will fix it.

**Comment by mkellsy** [comment]
It will generate a new code the old one is dead.

**Comment by Fookes74** [comment]
@mkellsy  - Code is SNG-8GR

Are you talking about the HOOBs upgrade. The other plugins were shown before your original fix. When I added Alexa plugin they were gone. Really not sure what is going on. Any changes/saves I've tried to make just hang and nothing happens.

**Comment by mkellsy** [comment]
It should be OK now. I made sure all of your plugins are installed and in the package.json.

Not every upgrade is going to be smooth, but we are here to help. Sorry for the inconvenience.

**Comment by Fookes74** [comment]
@mkellsy - Ok - appreciate you filling in the blanks. Not sure I understand what you’re telling me about the npm install. Should this now be stable for me going forward or am I likely to see more plugins vanishing from time to time?

**Comment by mkellsy** [comment]
Should be stable now. Migrating from UI-X is tough to do, sometimes things go wrong. But now that you are upgraded, things are much smoother now.

**Comment by mkellsy** [comment]
I'm leaving this issue open so I can determine what went wrong with the upgrade. Thanks for reporting the issue.

**Comment by Fookes74** [comment]
Ok, thank again. Let's see how we go. Would you suggest I don't attempt to add Weather Plus back in - at least for now?

**Comment by mkellsy** [comment]
I have made the same environment as the people who had the issues, and I was able to migrate without issues. Except the "homebridge-xiaomi-mi-robot-vacuum" plugin which has a broken dependency.

Trying other things.

**Comment by Nmonji** [comment]
The LIFX plug ins are not working with the HOOBS 3. It was working perfectly on 2.1
Any suggestions

**Comment by mkellsy** [comment]
Which plugin are you running? There are 3.
https://www.npmjs.com/search?q=homebridge%20LIFX

**Comment by Nmonji** [comment]
I used this:  https://github.com/devbobo/homebridge-lifx-lan#readme

seems like it is crashing home bridge too

Thanks
Gregory Job

**Comment by mkellsy** [comment]
@Nmonji can you post the logs. There's probably an exception in there. It can help me track down what's really happening.

**Comment by Nmonji** [comment]
Hi Michael 

I uninstalled and then reinstalled the plug in and now it’s working . 

Thanks for following up
Gregory Job

**Comment by mkellsy** [comment]
We are moving the Node base to 10.17.0. The plugins are not ready for 12.13.1.

**Comment by mkellsy** [comment]
Done in 3.1.2
