### ISSUE TITLE
Install Script Prerequisites Error

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#275]
**Description**
Output while installing Prerequisites

**Version**
2.1.0 upgrade

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes tried to
- [ ] No

**Terminal Output**

<img width="1016" alt="Screenshot 2019-12-04 at 22 24 28" src="https://user-images.githubusercontent.com/50763727/70183136-7f764280-16e5-11ea-8da3-ce3652586d55.png">

**Comment by d0n4v4nb3ck3r** [comment]
I am having the same issue on one of my RaspberryPIs

**Comment by mkellsy** [comment]
This is failing on `apt-get update`.

**Comment by mkellsy** [comment]
This is due to not running apt-get update since they officially released Buster. Here's a link the the issue on Raspberry Pis forum. https://www.raspberrypi.org/forums/viewtopic.php?t=245022

To fix this you need to run this command
```
sudo apt update -y
```
