### ISSUE TITLE
Accessories Screen Blank

### ISSUE THREAD

**Issue by JazzerAlto** [hoobs-org/HOOBS#277]
Nothing displayed on the accessories screen when I click on the left pane.

<img width="1340" alt="Screen Shot 2019-12-04 at 9 41 36 PM" src="https://user-images.githubusercontent.com/58541086/70202543-a467b700-16df-11ea-99b7-37b9609da5ce.png">

**Comment by askovi** [comment]
Is HOOBS running? Check your Dashboard 
![image](https://user-images.githubusercontent.com/3981552/70202627-3a074480-16e8-11ea-8306-fd06cf37d66a.png)
Also please post your logs and config

**Comment by JazzerAlto** [comment]
Yes, running and working.  Upgraded from 2.1.1 to release version.

**Comment by JazzerAlto** [comment]
[logs.txt](https://github.com/hoobs-org/HOOBS/files/3925294/logs.txt)

logs and config
