### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by hubert1529** [hoobs-org/HOOBS#278]
Getting stuck at this screen.. wont go any further

USER: hoobs
DIR: /usr/local/lib
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-to-hoobs@latest

homebridge-to-hoobs@1.0.31 postinstall /usr/local/lib/node_modules/homebridge-to-hoobs
./install.sh

Thank You for choosing HOOBS
---------------------------------------------------------
⠸ Node Version 12.13.1
⠼ Updating Repositories
⠋ Cleaning NPM
⠸ Installing HOOBS
⠹ Configuring
---------------------------------------------------------

Initializing HOOBS
---------------------------------------------------------
⠋ Installing PrerequisitesE: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'
(node:6572) UnhandledPromiseRejectionWarning: Error: Command failed: apt-get update
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/scripts/prerequisites.js:31:25
    at new Promise (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/prerequisites.js:6:12)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs-init:9:104
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs-init:13:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
(node:6572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠋ Installing Prerequisites

**Comment by mkellsy** [comment]
We recommend using this command
`sudo npm install -g --unsafe-perm @hoobs/hoobs`

HOOBS needs the -g flag.

**Comment by mkellsy** [comment]
It looks like the install is failing on apt-get.

Try going through this document.
https://github.com/hoobs-org/HOOBS/wiki/2.5.3-Installing-Manually

What part is it failing. on?

**Comment by mkellsy** [comment]
This is due to not running apt-get update since they officially released Buster. Here's a link the the issue on Raspberry Pis forum. https://www.raspberrypi.org/forums/viewtopic.php?t=245022

To fix this you need to run this command
```
sudo apt update -y
```
