### ISSUE TITLE
Stuck on launch screen

### ISSUE THREAD

**Issue by rupil10** [hoobs-org/HOOBS#280]
I recently upgraded to the latest version it was working fine until I had to change the port as it was conflicting with another device I have on my network. I changed it from 8080 to 80.

Now the service won't start when I visit hoobs.local it just hangs on the loading screen.

I have restarted the RPi a few times and that has not helped.

**Comment by rupil10** [comment]
So a bit of an update. I just completely reset the system up again. Before I configured any of my devices I just tried to change the port and it killed hoobs again. 

I need to change it from 8080 to something else as it conflicts with my media server and I am unable to forward the port in my router for remote login. 

How can I change the port without breaking it now that I have it running again?

**Comment by mkellsy** [comment]
You can edit the config.json file. it is here
`~/.hoobs/etc/config.json`

**Comment by rupil10** [comment]
mkellsy I have done that on two different occasions now and it has ended up me with me being in this situation of being stuck on the boot screen.

**Comment by mkellsy** [comment]
What port did you change it to?

**Comment by mkellsy** [comment]
HOOBS already runs on port 80 and 8080. We have a NGINX server in between.

Run this.
```
sudo systemctl disable nginx.service
```

Then run this
```
sudo systemctl start hoobs.service
```

**Comment by mkellsy** [comment]
If you want to know what the install script does, we have it documented here
https://github.com/hoobs-org/HOOBS/wiki/2.5.3-Installing-Manually

**Comment by rupil10** [comment]
Ok thanks I’ll look into it. I have tried 80 on one try then 88 on another. I don’t need to change the port really. The reason for it was I would like to be able to log in remotely if I need to start the server and to do that I have to forward the port on my router. When I tried to do that I couldn’t because my qnap server runs on the same port.
