### ISSUE TITLE
Scrolling in Settings sub-selection

### ISSUE THREAD

**Issue by martinnock** [hoobs-org/HOOBS#281]
**Description**
In the Settings screen, the sub-menu between the bar on the left hand side and the details page, where all the plugin settings are listed, I cannot scroll.
My list it too long, so that I cannot reach further down, e.g. to the Save button

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
3.07 beta

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [] Custom Install

**Comment by mkellsy** [comment]
This is fixed in 3.1.2
