### ISSUE TITLE
Terminal not installing plugins

### ISSUE THREAD

**Issue by ludgats** [hoobs-org/HOOBS#283]
**Description**
Installing plugins through terminal on HOOBS 3 does not work. It says everything went fine but the plugin does not show up. I’m trying to install an older version of a plugin so I don’t want to install it through the regular method. 

**Version**
HOOBS 3.0

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x] HOOBS SD Card
- [ ] Custom Install

No plugins install but specifically the plugin I want is node dot alarm dot com. Version 1.2

**Comment by rpolenthon** [comment]
Take a look in the wiki, there the manual plugin installation is explained:

https://github.com/hoobs-org/HOOBS/wiki/4.0-Plugins
