### ISSUE TITLE
Help page typo

### ISSUE THREAD

**Issue by ukypayne** [hoobs-org/HOOBS#286]
**Description**
On the Hoobs "help" page there is a typo.

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Additional context**
"Common Issues
Apple Home Can't Find Homebridge. The Homebridge service is not running. Try starting the service. Check the Status screen and if the Homebridge service is not running, click the service menu on the **rupper** right and click Start Service.

Status
Restart Service
"

**Comment by mkellsy** [comment]
Needs to be fixed in Loco.

**Comment by mkellsy** [comment]
Fixed in 3.1.2
