### ISSUE TITLE
Issues with HOOBS certified Ring and Wink

### ISSUE THREAD

**Issue by chrissortman** [hoobs-org/HOOBS#287]
I installed 3.0 and I'm having a few issues, first with ring it'll only allow me to add one camera. second with wink, it won't allow me to see any accessories. It appears that it is trying to use a different client ID and client Secret than what is on my current wink dev account. I tried to fix this in the advanced Config on HOOBS but it continued to give me an error since the only config option is for username and password. Do you have any suggestions on how to fix these errors or should I just downgrade to HOOBS 2

**Comment by mkellsy** [comment]
We will fix the Wink plugin soon. Wink was supposed to allow our client ID, but it's been 6 months since they said they were going to approve it.

I will revert the certified plugin to the one that uses the client is from the config. Sorry for the incoveience.

**Comment by d0n4v4nb3ck3r** [comment]
is ring plugin going to be updated also?

**Comment by mkellsy** [comment]
Wink is updated to use any client id.

**Comment by mkellsy** [comment]
Ring updated to version 5.10.0
