### ISSUE TITLE
Integrate @HOOBS/* search for certified plugins

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#29]

**Comment by mkellsy** [comment]
The @hoobs scope is up on NPM. This is where certified plugins will live. We also added support for scoped plugins.

This allows us to have plugins named anything. It doesn't need to start with homebridge-.

**Comment by mkellsy** [comment]
I have this done. We can control and approve plugins and release them under the @hoobs/ scope.
The UI pulls categories from https://github.com/hoobs-org/HOOBS/blob/master/certified/categories.json. So it doesn't have to scan NPM just for these, which will be tough as the certified plugin list grows.

The UI is now a click and browse, without searching for ceed plugins. You still can search to find the non-certified plugins.
