### ISSUE TITLE
weather forecast in Homekit

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#290]
it would be nice if the can expose actual temp and weahter condition from dashboard directly into homekit

Also user request

**Comment by mkellsy** [comment]
This can be handled by the weather-plug plugin.

**Comment by BobbySlope** [comment]
In my opinion it would be nice to have in a future version, because its already there

**Comment by mkellsy** [comment]
The weather in the dashboard (not the same thing) and then having it be pushed to homekit requires a plugin. The UI is not part of homebridge, the plugin is required.
