### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by SAMMY2785** [hoobs-org/HOOBS#298]
Hi, I’m new to this and I’m having some trouble with the configuration of the homebridge-nest plugin for google accounts. I tried to follow the tutorial on the NPM page but I keep getting an error. Thank you in advance to anyone that can help. Here is my config:

{
    "platform": "Nest"
    "googleAuth": {
        "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJDLj6LQu-SMCQLMJfOUep6S7tCewNtG6g8I8fdQNxj1nE5J4K9JZPONrWqTCdMJuvpuulOQI2_26lPfY1t87HyHPPrIRsH_hQ&client_id=733249279899-44tchle2kaa9afr5v9ov7jbuojfr9lrq.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2F...",
        "cookies": "OCAK=xe2jl0jn_vaA3vU5vsd64uSuQ0LcDlRMEE_hFH5XhkM; SID=rQcCbZx5iWdbxXy3ZmlFSQx...",
        "apiKey": "AIzaSy..."
      },
}

**Comment by BobbySlope** [comment]
you can install our certified plugin
<img width="1223" alt="Screenshot 2019-12-10 at 08 33 31" src="https://user-images.githubusercontent.com/50763727/70505255-d20d8f80-1b27-11ea-9126-77c671742a80.png">

configuration is easy as this:
<img width="1171" alt="Screenshot 2019-12-10 at 08 34 20" src="https://user-images.githubusercontent.com/50763727/70505280-e3569c00-1b27-11ea-89ce-52ec3c88995d.png">

No Config JSON editing needed

**Comment by SAMMY2785** [comment]
Thank you!! I have one more question. I’m trying to access HOOBS.local on my PC and it doesn’t work. I tried installing Bonjour printer services but it still doesn’t work. Can you help me with this? Thanks!!
