### ISSUE TITLE
Can this be made to run on a Linux vm?

### ISSUE THREAD

**Issue by lacedup** [hoobs-org/HOOBS#3]
I set up home assistant on a always on pc, Linux vm. If this could support a vm too, I could repurpose my pi

**Comment by lacedup** [comment]
Also because a lot of cameras use cpu, and a pc is much more suited

**Comment by lacedup** [comment]
Can anyone answer if this is planned or not

**Comment by mkellsy** [comment]
Yes hoobs-core should be able to run on linux. You will have to do a manual install. libavahi-compat-libdnssd-dev is required to run on linux.

**Comment by mkellsy** [comment]
I am running this in a Debian and Fedora VM on Parallels. So this will run on x86_64. The setup process will be much like homebridge with some automated routines.

**Comment by mkellsy** [comment]
Next Step
1. Test on a Fedora 30 VM
2. Test on a Debian Buster VM

**Comment by mkellsy** [comment]
This is tested using Fedora 30 and Debian 10. This can run in a VM.
