### ISSUE TITLE
server part of config Json resets after reboot

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#302]
this part resets after an reboot

I tried to fix my HOOBS Box at home after crashing while testing something
need to edit the home_setup_id to connect it back to my home app, without loosing all accessories in HomeKit.

but if I edit home_setup_id it changes back every time I reboot

    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ORAYQ8PGD",
        "polling_seconds": 5

**Comment by mkellsy** [comment]
The home_setup_id is not set by the config. The config is used to store this. It will reset always. Not a bug.
