### ISSUE TITLE
homebridge-ikea-tradfri-gateway

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#303]
- [X] forked to Hoobs-org
- [X] Standard Config (below)
- [X] Autodiscovery Devices 
- [X] Config Schema - needs to be added
- [ ] Updated readme on npm
- [X] Plugin Picture for UI (below)

**Comment by BobbySlope** [comment]
Standard config:

{
"platform": "Ikea Trådfri Gateway",
"name": "Ikea Trådfri Gateway",
"securityCode" : "this-is-found-on-the-back-of-the-gateway",
"host": "ip-address-of-ikea-gateway",
"expose": ["lightbulbs", "outlets", "blinds"]
}

**Comment by BobbySlope** [comment]
![product-ikea](https://user-images.githubusercontent.com/50763727/70397330-9f717300-1a11-11ea-8e9d-c08c738b6f8c.png)

**Comment by BobbySlope** [comment]
[platform.schema.txt](https://github.com/hoobs-org/HOOBS/files/3940576/platform.schema.txt)

**Comment by BobbySlope** [comment]
@askovi please pack everything into the repo and send me information about testing
after successful testing by @BobbySlope release on npm by @askovi

**Comment by mkellsy** [comment]
1. We don't update the readme. Doing this can break the link between the non certified version.
2. I renamed the repository in HOOBS
3. I changed the package ID to @hoobs/ikea-tradfri.

NEXT STEP
- We need a branding/product.png file. It needs to be in the "branding" folder. 
- Remove the config.json file. (confusing having it there)
- Remove homebridge-plugin from the keywords in the package.json
- Add  hoobs-certified and hoobs-plugin to the keywords in the package.json
- Add the categories to the keywords

Available keywords
[
    "category-voice-assistant",
    "category-climate",
    "category-lighting",
    "category-video",
    "category-hubs",
    "category-security",
    "category-outdoor",
    "category-media"
]

**Comment by BobbySlope** [comment]
> 1. We don't update the readme. Doing this can break the link between the non certified version.
> 2. I renamed the repository in HOOBS
> 3. I changed the package ID to @hoobs/ikea-tradfri.
> 
> NEXT STEP
> 
> * We need a branding/product.png file. It needs to be in the "branding" folder. DONE by @BobbySlope 
> * Remove the config.json file. (confusing having it there)
> * Remove homebridge-plugin from the keywords in the package.json
> * Add  hoobs-certified and hoobs-plugin to the keywords in the package.json
> * Add the categories to the keywords
> 
> Available keywords
> [
> "category-voice-assistant",
> "category-climate",
> "category-lighting",
> "category-video",
> "category-hubs",
> "category-security",
> "category-outdoor",
> "category-media"
> ]

**Comment by BobbySlope** [comment]
@mkellsy please provide step by step guide to install this directly from git to my testdevice
