### ISSUE TITLE
how to generate hbf file from ssh and load locally?

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#304]
Please write a short step by step tutorial for that

**Comment by mkellsy** [comment]
Not possible, requires the code to do this.

1. Needs authentication token.
2. Requires encryption at rest logic.
3. Requires zip logic.

The .hbf file simply zips up ~/.hoobs/ and removed dist and lib folders. So to take a backup manually, just create a tar ball of the ~/.hoobs fiolder. You won't be able to use the recovery tool, you will have to untar it manually.
