### ISSUE TITLE
Upgrade to Hoobs 3

### ISSUE THREAD

**Issue by khowell20454** [hoobs-org/HOOBS#306]
Upgraded to Hoobs 3 and now it states “Homebridge service is not running.”  Tried starting service, resetting connection, logging out and logging in. HomeKit is stating all devices “no response”.

**Comment by BobbySlope** [comment]
Please provide logs and config

**Comment by khowell20454** [comment]
I fixed issue by formatting and doing a clean install.

**Comment by mkellsy** [comment]
Logs not provided, no way to determine what happened. Closing issue.
