### ISSUE TITLE
Terminal windows removes content after some seconds/minutes

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#309]
I was able to reproduce the following issue multiple times:

- Go in the terminal section, type something and press enter.
- Do nothing or whatever you want in the meanwhile
- After about 1 or 2 minutes the terminal clears itself and adds another "hoobs@hoobs:~/.hoobs/etc $" in the first line

**Comment by mkellsy** [comment]
This is a known issue with Node-PTY.
Chrome and Safari, will try to disconnect long running sockets.

Not much we can do about this at the moment.

**Comment by mkellsy** [comment]
I think there is a way to tie PTY to an actual terminal, so it doesn't create one every time.

**Comment by mkellsy** [comment]
I added the process.env to the terminal, should keep it in place.
