### ISSUE TITLE
Homebridge-Alexa

### ISSUE THREAD

**Issue by dcstroud** [hoobs-org/HOOBS#310]
**Description**
When installing the homebridge-Alexa plugin, it requires homebridge to be running insecure.  This requires -I to be added at some point to the Autostart.  Is there an option in interface to run insecure, if not, what autostart command would need to be altered?

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Homebridge-Alexa

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
HOOBS doesn't need to run in insecure mode to run Alexa plugin

After installing Alexa plugin you can enter all needed settings here and save changes 
Alexa plugin is then set and up and running

<img width="1144" alt="Screenshot 2019-12-10 at 20 09 06" src="https://user-images.githubusercontent.com/50763727/70560590-2d239e80-1b89-11ea-8eb7-e6e2a4d87aea.png">

**Comment by fighterzg6** [comment]
I need it too

**Comment by mkellsy** [comment]
HOOBS runs in insecure mode.
