### ISSUE TITLE
homebridge-people-x plugin cannot be configured

### ISSUE THREAD

**Issue by MikeDeltaHH** [hoobs-org/HOOBS#311]
**Description**
This is a plugin for homebridge. It monitors who is at home, based on their smartphone being seen on the network recently. If you use the EVE.app you can also see the presence history of every person-sensor (powered by fakegato)

**Expected behavoir**

**Plugin name**
homebridge-people-x

**Please report the issue to the plugin developer**
This isn´t a problem by the plugin himself, in my other homebridge installation the plugin works fine but in hoobs i cannot configure it - in the add device dialog it shows ""accessory": "PeopleAllAccessory"" but the plugin must be configured as a platform ("platform": "People") - i try to edit the config.json manually and insert the configuration from my working homebridge installation but after save this hoobs stops working or didn´t save the configuration and i have some "[List Rooms] connect ECONNREFUSED 127.0.0.1:51826" messages in the log - i have to restore hoobs from a backup made before the plugin configuration.

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Ubuntu 18.04.3 LTS

**Post your config**

```
"platform": "People",
            "threshold": 15,
            "anyoneSensor": true,
            "nooneSensor": true,
            "webhookPort": 51828,
            "cacheDirectory": "./.node-persist/storage",
            "pingInterval": 10000,
            "ignoreReEnterExitSeconds": 0,
            "people": [
                {
                    "name": "Michael",
                    "target": "192.168.2.82",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Franzi",
                    "target": "192.168.2.32",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                }
            ]
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```

```

**Additional context**
I try another plugin, homebridge-people with the same effect! Sorry for my bad english, i´m from Germany!

**Comment by BobbySlope** [comment]
Yes you are right its not detected correct it should be platform but is detected as accessory

You can add the config part in advanced config there:
<img width="1242" alt="Screenshot 2019-12-10 at 21 14 31" src="https://user-images.githubusercontent.com/50763727/70565389-4d0b9000-1b92-11ea-85b2-054b19c15333.png">

**Comment by MikeDeltaHH** [comment]
Thanks a lot - this works!

**Comment by BobbySlope** [comment]
Add to the to certify list

**Comment by MikeDeltaHH** [comment]
Just for info - the version 3.1.9 didn´t solved the problem!
