### ISSUE TITLE
Hoobs is very slow after configuration of homebridge-homematic

### ISSUE THREAD

**Issue by MikeDeltaHH** [hoobs-org/HOOBS#312]
**Description**
Supports the Homematic System on HomeBridge Platform

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
homebridge-homematic

**Please report the issue to the plugin developer**
Plugin works perfect with my Homebridge installation, so i think it isn´t a plugin related problem.

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Ubuntu 18.04.3 LTS

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
            "platform": "HomeMatic",
            "name": "HomeMatic CCU3",
            "ccu_ip": "192.168.2.76",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "programs": [],
            "accessories": [],
            "enable_hmip": "true",
            "subsection": "Homebridge"
        }
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
At the moment i switch from my homebrigde installation to a fresh hoobs installation and the homebridge-homematic is the last plugin that i have to move from homebridge to hoobs - i have around 15 homematic devices.
After installation and configuration of this plugin the hoobs webinterface is often not responding or it takes minutes to switch to another menu - i have to restart the service but when i switch to accessories it shows me a blank page for minutes - in homekit the most hoobs devices are not responding so at the moment the plugin isn´t usefull.

**Comment by MikeDeltaHH** [comment]
Ich wurde im smart apfel forum gefragt ob ich bereit wäre wegen dem Homematic Plugin zu helfen da ihr selbst keine Homematic Komponenten habt... kann ich gerne machen, da ich hoobs auf einem ESXi am laufen hab kann ich auch problemlos per Snapshots Tests machen...

**Comment by BobbySlope** [comment]
thanks for translating in english :)

**Comment by mkellsy** [comment]
I need logs to troubleshoot.

**Comment by MikeDeltaHH** [comment]
Do a short test.. made a snapshot and install the homematic plugin without any configuration... nothin happens, all devices are online - but after do the plugin configuration and save them hoobs takes minutes to responding when i´m select any menu point... the accessories menu point is blank, in homekit all devices are not responding... and i have nothing special in the logs:

--------------------------------------------------------------------------------------------------
[Homebridge] [2020-1-5 11:03:13] [Alexa] alexaDiscovery - returned 74 devices[Homebridge] [2020-1-5 11:03:30] [Robot unten] INF getCleaning | rockrobo.vacuum.v1 | Cleaning is false[Homebridge] [2020-1-5 11:03:30] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:30] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO "Balanced" > HomeKit speed 60%[Homebridge] [2020-1-5 11:03:30] [Robot unten] INF getBattery | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:30] [Robot unten] INF getCharging | rockrobo.vacuum.v1 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:30] [Robot unten] INF getBatteryLow | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:30] [Robot unten] INF getDocked | rockrobo.vacuum.v1 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:30] [Robot oben] INF getCleaning | roborock.vacuum.s5 | Cleaning is false[Homebridge] [2020-1-5 11:03:30] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:30] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%[Homebridge] [2020-1-5 11:03:30] [Robot oben] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:30] [Robot oben] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:30] [Robot oben] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:30] [Robot oben] INF getDocked | roborock.vacuum.s5 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:30] [Kamera Küche] connecting to camera at 192.168.2.26...[Homebridge] [2020-1-5 11:03:30] [FritzBox 7590] Getting guest WLAN state[Homebridge] [2020-1-5 11:03:30] [ZP] Sonos Wohnzimmer Sonos: get Remaining Duration return 0s[Homebridge] [2020-1-5 11:03:30] [HomeMatic CCU3] Saving 21.8 for VirtualDevices.INT0000001:1[Homebridge] [2020-1-5 11:03:30] [Kamera Küche] current power state: off[Homebridge] [2020-1-5 11:03:31] [Diskstation] current system temp: 38 °C[Homebridge] [2020-1-5 11:03:33] [Robot unten] INF getCleaning | rockrobo.vacuum.v1 | Cleaning is false[Homebridge] [2020-1-5 11:03:33] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:33] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO "Balanced" > HomeKit speed 60%[Homebridge] [2020-1-5 11:03:33] [Robot unten] INF getBattery | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:33] [Robot unten] INF getCharging | rockrobo.vacuum.v1 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:33] [Robot unten] INF getBatteryLow | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:33] [Robot unten] INF getDocked | rockrobo.vacuum.v1 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:33] [Robot oben] INF getCleaning | roborock.vacuum.s5 | Cleaning is false[Homebridge] [2020-1-5 11:03:33] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:33] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%[Homebridge] [2020-1-5 11:03:33] [Robot oben] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:33] [Robot oben] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:33] [Robot oben] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:33] [Robot oben] INF getDocked | roborock.vacuum.s5 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:33] [Kamera Küche] connecting to camera at 192.168.2.26...[Homebridge] [2020-1-5 11:03:33] [FritzBox 7590] Getting guest WLAN state[Homebridge] [2020-1-5 11:03:33] [ZP] Sonos Wohnzimmer Sonos: get Remaining Duration return 0s[Homebridge] [2020-1-5 11:03:33] [Kamera Küche] current power state: off[Homebridge] [2020-1-5 11:03:33] [HomeMatic CCU3] Saving 21.8 for VirtualDevices.INT0000001:1[Homebridge] [2020-1-5 11:03:34] [Diskstation] current system temp: 38 °C[Homebridge] [2020-1-5 11:03:40] [Robot unten] INF getCleaning | rockrobo.vacuum.v1 | Cleaning is false[Homebridge] [2020-1-5 11:03:40] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:40] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO "Balanced" > HomeKit speed 60%[Homebridge] [2020-1-5 11:03:40] [Robot unten] INF getBattery | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:40] [Robot unten] INF getCharging | rockrobo.vacuum.v1 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:40] [Robot unten] INF getBatteryLow | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:40] [Robot unten] INF getDocked | rockrobo.vacuum.v1 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:40] [Robot oben] INF getCleaning | roborock.vacuum.s5 | Cleaning is false[Homebridge] [2020-1-5 11:03:40] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:40] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%[Homebridge] [2020-1-5 11:03:40] [Robot oben] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:40] [Robot oben] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:40] [Robot oben] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:40] [Robot oben] INF getDocked | roborock.vacuum.s5 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:40] [Kamera Küche] connecting to camera at 192.168.2.26...[Homebridge] [2020-1-5 11:03:40] [FritzBox 7590] Getting guest WLAN state[Homebridge] [2020-1-5 11:03:40] [ZP] Sonos Wohnzimmer Sonos: get Remaining Duration return 0s[Homebridge] [2020-1-5 11:03:40] [Kamera Küche] current power state: off[Homebridge] [2020-1-5 11:03:40] [HomeMatic CCU3] Saving 21.8 for VirtualDevices.INT0000001:1[Homebridge] [2020-1-5 11:03:41] [Diskstation] current system temp: 38 °C[Homebridge] [2020-1-5 11:03:45] [Robot unten] INF getCleaning | rockrobo.vacuum.v1 | Cleaning is false[Homebridge] [2020-1-5 11:03:45] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:45] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO "Balanced" > HomeKit speed 60%[Homebridge] [2020-1-5 11:03:45] [Robot unten] INF getBattery | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:45] [Robot unten] INF getCharging | rockrobo.vacuum.v1 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:45] [Robot unten] INF getBatteryLow | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:45] [Robot unten] INF getDocked | rockrobo.vacuum.v1 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:45] [Robot oben] INF getCleaning | roborock.vacuum.s5 | Cleaning is false[Homebridge] [2020-1-5 11:03:45] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:45] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%[Homebridge] [2020-1-5 11:03:45] [Robot oben] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:45] [Robot oben] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:45] [Robot oben] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:45] [Robot oben] INF getDocked | roborock.vacuum.s5 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:45] [Kamera Küche] connecting to camera at 192.168.2.26...[Homebridge] [2020-1-5 11:03:45] [FritzBox 7590] Getting guest WLAN state[Homebridge] [2020-1-5 11:03:45] [ZP] Sonos Wohnzimmer Sonos: get Remaining Duration return 0s[Homebridge] [2020-1-5 11:03:45] [Kamera Küche] current power state: off[Homebridge] [2020-1-5 11:03:45] [HomeMatic CCU3] Saving 21.8 for VirtualDevices.INT0000001:1[Homebridge] [2020-1-5 11:03:46] [Diskstation] current system temp: 38 °C[Homebridge] [2020-1-5 11:03:53] [Diskstation] do poll...[Homebridge] [2020-1-5 11:03:53] [Diskstation] current power state is: true[Homebridge] [2020-1-5 11:03:53] [FritzBox 7590] Updating guest WLAN[Homebridge] [2020-1-5 11:03:53] [FritzBox 7590] Getting guest WLAN state[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 087610431609 Strom Kino Wohnzimmer:  undefined W undefined kWh 22 °C 0 kWh[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 087610431537 Strom Entertain Schlafzimmer:  undefined W undefined kWh 14.5 °C 0 kWh[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 087610463000 Strom Eismaschine:  undefined W undefined kWh 22.5 °C 0 kWh[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 087610463001 Strom PC Michael:  undefined W undefined kWh 19 °C 0 kWh[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 116300025251 Strom TV Schlafzimmer:  undefined W undefined kWh 14 °C 0 kWh[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 116300002962 Strom PC Franzi:  undefined W undefined kWh 19.5 °C 0 kWh[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 116300008210 Strom Big Box:  undefined W undefined kWh 19.5 °C 0 kWh[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 116300008206 Strom Entertain Küche:  undefined W undefined kWh 22 °C 0 kWh[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 116300044472 Strom TV Küche:  undefined W undefined kWh 22 °C 0 kWh[Homebridge] [2020-1-5 11:03:57] [FritzBox 7590] Updated outlet 116300040182 Strom Netzwerk:  undefined W undefined kWh 21.5 °C 0 kWh[Homebridge] [2020-1-5 11:03:59] [Robot unten] INF getCleaning | rockrobo.vacuum.v1 | Cleaning is false[Homebridge] [2020-1-5 11:03:59] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:59] [Robot unten] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 60 over miIO "Balanced" > HomeKit speed 60%[Homebridge] [2020-1-5 11:03:59] [Robot unten] INF getBattery | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:59] [Robot unten] INF getCharging | rockrobo.vacuum.v1 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:59] [Robot unten] INF getBatteryLow | rockrobo.vacuum.v1 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:59] [Robot unten] INF getDocked | rockrobo.vacuum.v1 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:59] [Robot oben] INF getCleaning | roborock.vacuum.s5 | Cleaning is false[Homebridge] [2020-1-5 11:03:59] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit[Homebridge] [2020-1-5 11:03:59] [Robot oben] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%[Homebridge] [2020-1-5 11:03:59] [Robot oben] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:59] [Robot oben] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)[Homebridge] [2020-1-5 11:03:59] [Robot oben] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%[Homebridge] [2020-1-5 11:03:59] [Robot oben] INF getDocked | roborock.vacuum.s5 | Robot Docked is true (Status is charging)[Homebridge] [2020-1-5 11:03:59] [Kamera Küche] connecting to camera at 192.168.2.26...[Homebridge] [2020-1-5 11:03:59] [FritzBox 7590] Getting guest WLAN state[Homebridge] [2020-1-5 11:03:59] [ZP] Sonos Wohnzimmer Sonos: get Remaining Duration return 0s[Homebridge] [2020-1-5 11:03:59] [Kamera Küche] current power state: off[Homebridge] [2020-1-5 11:03:59] [HomeMatic CCU3] Saving 21.8 for VirtualDevices.INT0000001:1[Homebridge] [2020-1-5 11:04:00] [Diskstation] current system temp: 38 °C

----------------------------------------------------------------------------------------------------

No error entry or any other hint for the source of the problem...
