### ISSUE TITLE
Using HOOBS/nest with a google account 

### ISSUE THREAD

**Issue by SAMMY2785** [hoobs-org/HOOBS#313]
I’m trying to use HOOBS/nest plugin with a google account. I don’t have a nest UN and PW because I use google to log in to my nest account. Is there a way to get this plugin to work?

**Comment by mkellsy** [comment]
Fixed in version 3.5.2.

**Comment by SAMMY2785** [comment]
Thank you for your reply. I looked on the npm page and it shows the latest version is 3.5.1. Can you tell me where to get the 3.5.2 version or send me a link? Thank you!!
