### ISSUE TITLE
Flashed img 3.1.1 requires reboot to access the UI

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#315]
**Description**
Freshly flashed 3.1.1 img file doesn't boot when first powered on Raspbian Buster Lite. Rebooting via ssh or even simply replugging the power cable fixes it. 

**Version**
3.1.1

**Comment by mkellsy** [comment]
I am un able to reproduce. I will try again, and rebuild the image.

**Comment by askovi** [comment]
Seems to have been an issue on my network. Recently all the flashed cards boot right away.
