### ISSUE TITLE
Discuss a plugin blacklist

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#319]
The amount of available plugins is huge (about 1900 so far). Some of them are old and don't work anymore or got replaced by better community plugins.

In my opinion, we should discuss a "blacklist" which includes plugin names who don't work correctly with HOOBS. These plugins would than not appear in the plugin search or they appear with a flag called "unsupported".

This would decrease the number of support requests about old plugins.

**Comment by askovi** [comment]
I agree. But how do you propose we go about identifying all the ones not working? Maybe a whitelist would be easier and we can just put an 'untested' label on those we haven't tested.

**Comment by rpolenthon** [comment]
The problem with the "untested" label is that the user could interpret plugins without this flag as a kind of hoobs certified plugin. 

We are not able to test every plugin on functionality, but if we see that the plugin even cant be installed, we will set it on the blacklist (if the issues also report problems in the plugin repo).

The first time we could just use user feedback about not working plugins to test the installation by ourselves. Later if we have more time we could just go the hard way and try every 1900 plugins to install.

**Comment by mkellsy** [comment]
Already done. 
[https://github.com/hoobs-org/hoobs-core/blob/master/lib/plugins.js](https://github.com/hoobs-org/hoobs-core/blob/master/lib/plugins.js) line 584.

**Comment by rpolenthon** [comment]
I thought we could outsource it in a JSON file on github, so we can edit it flexible just in time.

Maybe integrate this in a future version.
