### ISSUE TITLE
Installing as service on Catalina sets up an entirely new HOOBS installation

### ISSUE THREAD

**Issue by seannymurrs** [hoobs-org/HOOBS#323]
**Description**
I installed HOOBS 3 on my iMac earlier this week. Today I decided to follow the instructions to install it as a service to avoid having to manually start HOOBS any time my Mac restarts. I was a little confused to see that it appears to have installed an entirely new instance of HOOBS. I had previously set the service to run on port 2728, but I couldn’t access the webui after restarting my Mac. When I tried localhost:8080, however, the webui initial start page loaded asking me to set up an administrator account.

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
macOS Catalina.

**Comment by mkellsy** [comment]
HOOBS run is user mode. ON macOS this user is root. When you run hoobs from the terminal it is ran under the current user.

**Comment by seannymurrs** [comment]
I feel like this is something that should be mentioned in the installation instructions. Especially since I was specifically asked to come open this bug report when I made a post on Reddit and was told that was NOT the expected behavior.
