### ISSUE TITLE
Nest plugin with Google account config. Issues 

### ISSUE THREAD

**Issue by SAMMY2785** [hoobs-org/HOOBS#324]
Hi, I’m new to this and I’m having some trouble with the configuration of the homebridge-nest plugin for google accounts. I tried to follow the tutorial on the NPM page but I keep getting an error that says: Invalid JSON in an platform. Thank you in advance to anyone that can help. Here is my config:

{
"platform": "Nest"
"googleAuth": {
"issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJDLj6LQu-SMCQLMJfOUep6S7tCewNtG6g8I8fdQNxj1nE5J4K9JZPONrWqTCdMJuvpuulOQI2_26lPfY1t87HyHPPrIRsH_hQ&client_id=733249279899-44tchle2kaa9afr5v9ov7jbuojfr9lrq.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2F...",
"cookies": "OCAK=xe2jl0jn_vaA3vU5vsd64uSuQ0LcDlRMEE_hFH5XhkM; SID=rQcCbZx5iWdbxXy3ZmlFSQx...",
"apiKey": "AIzaSy..."
},
}

**Comment by mkellsy** [comment]
Please refer to the plugin docs.
https://github.com/chrisjshull/homebridge-nest

Here is your config fixed.

```json
{
    "platform":"Nest",
    "googleAuth":{ 
        "issueToken":"https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJDLj6LQu-SMCQLMJfOUep6S7tCewNtG6g8I8fdQNxj1nE5J4K9JZPONrWqTCdMJuvpuulOQI2_26lPfY1t87HyHPPrIRsH_hQ&client_id=733249279899-44tchle2kaa9afr5v9ov7jbuojfr9lrq.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2F...",
        "cookies":"OCAK=xe2jl0jn_vaA3vU5vsd64uSuQ0LcDlRMEE_hFH5XhkM; SID=rQcCbZx5iWdbxXy3ZmlFSQx...",
        "apiKey":"AIzaSy..."
    }
}
```

I use this site to validate JSON
https://jsonformatter.curiousconcept.com/
