### ISSUE TITLE
Problem with Xiaomi Flower Care Plug-In and HOOBS 3.1.1

### ISSUE THREAD

**Issue by 2lazy2chill** [hoobs-org/HOOBS#327]
I have a Xiaomi Flower Care and would like to integrate it into my HomeKit. Since I have a HOOBS (v3.1.1) / Homebridge and there is a plug-in (https://www.npmjs.com/package/homebridge-mi-flora-filtered), I thought it would be easy... But whenever I insert the following via Plug-Ins -> "Installed Packages" -> "Configuration" (of the Plug-In "Mi Flora Filtered") ...

> {
    "accessory": "mi-flower-care",
    "name": "Plantsensor",
    "deviceId": "..:..:..:..:..:..",        <- Of course I have the right MAC in here;-)
    "interval": 300,
    "humidityAlertLevel": 30,
    "lowLightAlertLevel": 500
}

and save the change, the "Homebridge service" does not start anymore:

> [Homebridge] [12/13/2019, 18:14:25] Got SIGINT, shutting down service…
[Homebridge] [12/13/2019, 18:14:25] [Harmony Hub] INFO - shutdown
[Homebridge] [12/13/2019, 18:14:27] Loaded config.json with 1 accessories and 1 platforms.
[Homebridge] [12/13/2019, 18:14:27] ---
[Homebridge] [12/13/2019, 18:14:28] Loaded plugin: homebridge-harmony
[Homebridge] [12/13/2019, 18:14:28] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
[Homebridge] [12/13/2019, 18:14:28] ---
[Homebridge] [12/13/2019, 18:14:28] Plugin /home/hoobs/.hoobs/node_modules/homebridge-mi-flora-filtered requires Node version of >=0.12.0 <10.0.0 which does not satisfy the current Node version of v12.13.1. You may need to upgrade your installation of Node.
[Homebridge] [12/13/2019, 18:14:28] ====================
[Homebridge] [12/13/2019, 18:14:28] ERROR LOADING PLUGIN homebridge-mi-flora-filtered:
[Homebridge] [12/13/2019, 18:14:28] Error: Cannot find module 'bluetooth-hci-socket'
[Homebridge] Require stack:
[Homebridge] - /home/hoobs/.hoobs/node_modules/noble/lib/hci-socket/hci.js
[Homebridge] - /home/hoobs/.hoobs/node_modules/noble/lib/hci-socket/bindings.js
[Homebridge] - /home/hoobs/.hoobs/node_modules/noble/lib/resolve-bindings.js
[Homebridge] - /home/hoobs/.hoobs/node_modules/noble/index.js
[Homebridge] - /home/hoobs/.hoobs/node_modules/node-mi-flora/index.js
[Homebridge] - /home/hoobs/.hoobs/node_modules/homebridge-mi-flora-filtered/index.js
[Homebridge] - /home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/plugin.js
[Homebridge] - /home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js
[Homebridge] - /home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js
[Homebridge] - /home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge
[Homebridge] at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:690:27)
[Homebridge] at Module.require (internal/modules/cjs/loader.js:852:19)
[Homebridge] at require (internal/modules/cjs/helpers.js:74:18)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/noble/lib/hci-socket/hci.js:6:26)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Module.require (internal/modules/cjs/loader.js:852:19)
[Homebridge] at require (internal/modules/cjs/helpers.js:74:18)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/noble/lib/hci-socket/bindings.js:9:11)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Module.require (internal/modules/cjs/loader.js:852:19)
[Homebridge] at require (internal/modules/cjs/helpers.js:74:18)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/noble/lib/resolve-bindings.js:13:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/noble/index.js:2:49)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] [12/13/2019, 18:14:28] ====================
[Homebridge] [12/13/2019, 18:14:28] Error: The requested accessory 'mi-flower-care' was not registered by any plugin.
[Homebridge] at API.accessory (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:45:19)
[Homebridge] at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:305:48)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:81:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[Homebridge] at internal/main/run_main_module.js:17:11
[Homebridge] [12/13/2019, 18:14:28] Loading 1 platforms...
[Homebridge] [12/13/2019, 18:14:28] [Harmony Hub] Initializing HarmonyHubWebSocket platform...
[Homebridge] [12/13/2019, 18:14:28] [Harmony Hub] HarmonyPlatform Init
[Homebridge] [12/13/2019, 18:14:28] Loading 1 accessories…

Hoppefully somebondy can help me with this:-).

**Comment by BobbySlope** [comment]
HOObS v3.1.1 runs latest Node 12.13.1 LTS but this plugin cant be run on this new version. I will open an issue at the developer repo to update the plugin.

**Comment by BobbySlope** [comment]
Heres the issue on the developer repo
https://github.com/honkmaster/homebridge-mi-flower-care/issues/30

**Comment by Bladestar2105** [comment]
Check out this for newer Node Version.

https://github.com/Martvvliet/homebridge-mi-flora-filtered
