### ISSUE TITLE
Homebridge /Hoobs/ Homekit reset???

### ISSUE THREAD

**Issue by arttext** [hoobs-org/HOOBS#342]
-Installed Hoobs, (latest)works: IP is visible, I 'local' works, terminal works
-installed Nest plugin (latest) through Hoobs, did all the correct config steps including the google stuff (this only an abbreviation)
googleAuth": {
        "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken...",
        "cookies": "OCAK=TOMPYI3cCPAt...",
        "apiKey": "AIzaS..."
      },
Then I tried to get it into home on my iPhone 11 latest iOS with this result:
'to add this accessory to your home, you'll need to reset it first'
I don't know what that means; reset homebridge? Reset the Nest thermostat? Reset homekit app?
Anyway I did all that, to be sure, with no different outcome

**Comment by BobbySlope** [comment]
https://hoobs.org/knowledge-base/homekit-accessory-already-added-error/

**Comment by ZinkDifferent** [comment]
Not helpful, BobbySlope, since that comment and solution no longer exists:

"Nothing Found
Sorry, the post you are looking for is not available. Maybe you want to perform a search?"

**Comment by askovi** [comment]
The documentation moved here: https://support.hoobs.org/docs/5e960c1b0ab68b0344e872e0
