### ISSUE TITLE
Vacuum cleaner config (dock sensor) contains string instead of boolean

### ISSUE THREAD

**Issue by brailawle** [hoobs-org/HOOBS#344]
**Description**
I can't turn off dock sensor accessory for my Xiaomi Vacuum Cleaner through the HOOBS plugin settings. When I'm trying to turn off showing of dock sensor as an accessory in HOOBS Web App / Homekit App my dock config parameter is changing to 
```
"dock": "false"
```
at any types of update (directly from config file or via HOOBS Web App). I can assume that the this problem is due to the fact that the config is saved with the value of the string, instead of boolean `false`.

**Expected behavoir**
1. Plugin should provide me with ability to turn off 'dock sensor' at all
2. Plugin should set config parameter `"dock": false` as boolean
 

**Plugin**
https://www.npmjs.com/package/@hoobs/roborock

**Version**
HOOBS 3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**Comment by brailawle** [comment]
The issue looks similar to https://github.com/hoobs-org/HOOBS/issues/296#issuecomment-565471798 or https://github.com/dgreif/ring/issues/161#issuecomment-565343085 also. I can add `config.json` and logs if needed.

**Comment by mkellsy** [comment]
I had to add select field type casting.

Done in 3.1.4

**Comment by brailawle** [comment]
I've updated to the v3.1.4 through the HOOBS Web App and now everything looks fine. I can confirm that issue is fixed. Thanks
