### ISSUE TITLE
HOOBS Certified Nest auto config issue with googleAuth

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#346]
**Description**
hoobs certified nest plugin adds google auth empty object to advanced config automatically when saving the username and password from config.sceham and doesnt ignore it for regular nest accounts. This causes the plugin to not load your accessories and just spit into logs: 

"[Nest] When using googleAuth, you must provide issueToken, cookies and apiKey in config.json. Please see README.md for instructions"

Removing the googleAuth empty object from advanced config fixes the issue but it always gets added back whenever any change is done to the plugin configuration via config.schema. 

**Expected behavoir**
It should only add the googleAuth object if added from config.schema. Or ignore it if not necessary. 

**Plugin name**
HOOBS Nest

**Version**
3.5.2

**Comment by mkellsy** [comment]
I filter empty objects now. I also remove empty arrays, null properties and empty strings.

Done in 3.1.4
