### ISSUE TITLE
Add changelog in the UI after an update

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#347]
**Is your feature request related to a problem? Please describe.**
Currently users don't know what changed after an update unless they come to Github, which most of them do not do. 

**Describe the solution you'd like**
Add a nice list of the things that have changed in the new version, either before the update (when clicking the check for update button) or after the update is done inside the system/software page.

**Comment by mkellsy** [comment]
The type is not defaulting to string.

**Comment by mkellsy** [comment]
Fixed in 3.1.5

**Comment by mkellsy** [comment]
There is now a What's New button next to the Upgrade button. It shows what is changing.

Done in 3.1.6
