### ISSUE TITLE
Config Arrays Being Set to False, Preventing Empty Arrays from Being Removed

### ISSUE THREAD

**Issue by alessiobulfaro** [hoobs-org/HOOBS#349]
I've update HOOBS (installed on a Raspberry Pi 4) to 3.1.6 and now the homebridge server seems to not start. The web UI work well. The problem is in the photo, I think.
<img width="1680" alt="Schermata 2019-12-20 alle 19 00 51" src="https://user-images.githubusercontent.com/58361310/71280394-539cc300-235b-11ea-93ec-7bcca004f611.png">

**Comment by mkellsy** [comment]
If the interface is there, hoobs is already running, so running it again will cause an error.

Can you post the logs.

**Comment by BobbySlope** [comment]
Start the server via top right menu start service and provide the log

**Comment by alessiobulfaro** [comment]
This is the LOG after I try to start service.
<img width="1680" alt="Schermata 2019-12-20 alle 19 07 05" src="https://user-images.githubusercontent.com/58361310/71280615-fa815f00-235b-11ea-937a-af42b6700380.png">

**Comment by alessiobulfaro** [comment]
> This is the LOG after I try to start service.
> <img alt="Schermata 2019-12-20 alle 19 07 05" width="1680" src="https://user-images.githubusercontent.com/58361310/71280615-fa815f00-235b-11ea-937a-af42b6700380.png">

I've removed all plugins I have...problem persist

**Comment by mkellsy** [comment]
Can you post the log after you removed the plugins?
Can you post your config?

From the current logs it looks like homebridge-webos-tv is the issue.

Can you open the terminal and run `node -v`, what does it say?

**Comment by mkellsy** [comment]
I found out what was going on. I was able to reproduce this error and I have a fix for it coming in 3.1.7
