### ISSUE TITLE
Unable to update from 3.1.1 to 3.1.8

### ISSUE THREAD

**Issue by MikeDeltaHH** [hoobs-org/HOOBS#353]
**Description**
Hoobs show me that version 3.1.8 is available, after clicking on update the service is stopped and after some seconds it starts again and doesn´t change the version. Try this sometimes, do a reboot of the whole machine without success. Cannot see any error in the log...

**Version**
3.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Ubuntu 18.04.3 LTS

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Can you post the log.

**Comment by MikeDeltaHH** [comment]
Node is v12.13.1

See that version 3.1.9 is out - start the update:

[Homebridge] [2019-12-21 20:28:35] [FritzBox 7590] Getting guest WLAN state[Homebridge] [2019-12-21 20:28:35] [ZP] Sonos Wohnzimmer Sonos: get Remaining Duration return 0s[Homebridge] [2019-12-21 20:28:36] [Diskstation] current system temp: 41 °C[Homebridge] [2019-12-21 20:28:43] Got SIGINT, shutting down service...[Homebridge] [2019-12-21 20:28:43] [HarmonyHub Wohnzimmer] INFO - shutdown[Homebridge] [2019-12-21 20:28:43] [ZP] closed http://192.168.2.252:38647/notify[HOOBS] Stopping server.

[2019-12-21 20:39:05] HOOBS listning on port 8080.[Homebridge] [2019-12-21 20:39:06] Loaded config.json with 5 accessories and 8 platforms.[Homebridge] [2019-12-21 20:39:06] ---[Homebridge] [2019-12-21 20:39:06] Loaded plugin: homebridge-alexa[Homebridge] [2019-12-21 20:39:06] Registering platform 'homebridge-alexa.Alexa'[Homebridge] [2019-12-21 20:39:06] ---[Homebridge] [2019-12-21 20:39:06] Loaded plugin: homebridge-eveatmo[Homebridge] [2019-12-21 20:39:06] Registering platform 'homebridge-eveatmo.eveatmo'[Homebridge] [2019-12-21 20:39:06] ---[Homebridge] [2019-12-21 20:39:06] Loaded plugin: homebridge-fritz-eve[Homebridge] [2019-12-21 20:39:06] Registering platform 'homebridge-fritz.Fritz!Box'[Homebridge] [2019-12-21 20:39:06] ---[Homebridge] [2019-12-21 20:39:07] Loaded plugin: homebridge-harmony[Homebridge] [2019-12-21 20:39:07] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'[Homebridge] [2019-12-21 20:39:07] ---[Homebridge] [2019-12-21 20:39:07] Loaded plugin: homebridge-nuki[Homebridge] [2019-12-21 20:39:07] Registering platform 'homebridge-nuki.NukiPlatform'[Homebridge] [2019-12-21 20:39:07] ---[Homebridge] [2019-12-21 20:39:07] Loaded plugin: homebridge-people-x...

i´ve made a instalaltion via ssh - sudo npm install -g --unsafe-perm @hoobs/hoobs and reboot

After reboot:
 sudo npm list -g --depth=0
/usr/local/lib
├── @hoobs/hoobs@3.1.9
└── npm@6.12.1

But the Webinterface shows:  Current Version: 3.1.1 and find the update to 3.1.9 and i can repeat this often and often without success...

**Comment by MikeDeltaHH** [comment]
I revert to a snapshot before i test the installation via ssh and check the installed version again:

hoobs@hoobs:~$ sudo npm list -g --depth=0
/usr/local/lib
├── @hoobs/hoobs@3.1.9
└── npm@6.12.1

So i think this is a problem with the webinterface, shows the wrong version...

**Comment by mkellsy** [comment]
If you go to the base address **http://hoobs.local:8080** does the correct version show?

There is a fix for this in 3.1.9, but you still might need to clear your browser cache. You can keep the history and cookies, just make sure **Cached images and files** is checked. And make sure the **Time range** is set to **All time**.

<img width="529" alt="Screen Shot 2019-12-21 at 1 04 19 PM" src="https://user-images.githubusercontent.com/9777975/71313203-9f4e7b80-23f2-11ea-8e08-e6b82183986f.png">

**Comment by MikeDeltaHH** [comment]
Clearing the cache was my first idea after the doing the update but no luck! I do this from another pc i never visit the hoobs website before but the result is the same...

HOOBS Core
Current Version: 3.1.1
3.1.9 Update Available

**Comment by mkellsy** [comment]
HOOBS run under the current user. And It looks like this got stuck. It's rare but it can happen.

Are you running as a service?
What's the user you are running the service under?

What you are looking for is in this file `/etc/systemd/system/` and it should look like this.
```
[Unit]
Description=HOOBS
After=network-online.target

[Service]
Type=simple
User=hoobs
ExecStart=/usr/local/bin/hoobs
Restart=on-failure
RestartSec=3
KillMode=process

[Install]
WantedBy=multi-user.target
```

What is the **User** directive set to?
```
User=hoobs
```

SU into that user
```
su hoobs
```

If you are using the `hoobs` user the password is `hoobsadmin`.

> Note: If you are already logged in as `hoobs` you don't need to run su.

Then you can delete the `dist` and `lib` directories.
```
rm -fR ~/.hoobs/dist && rm -fR ~/.hoobs/lib
```

The reboot or restart the hoobs service
```
sudo systemctl restart hoobs
```

**Comment by mkellsy** [comment]
Another thing ti look at is the NGINX config.

This file lives here `/etc/nginx/conf.d/hoobs.conf` and should look like this.
```
server {
    listen 80;
    listen [::]:80;
    server_name hoobs;
    client_max_body_size 2048M;

    error_page 502 /loader.html;

    location / {
        proxy_pass            "http://127.0.0.1:8080";

        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      Upgrade $http_upgrade;
        proxy_set_header      Connection "upgrade";

        add_header            Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";

        if_modified_since     off;
        expires               off;
        etag                  off;
    }

    location = /loader.html {
        root /usr/share/hoobs;
        internal;
    }
}
```

The important parts are the `add_header Cache-Control`, `f_modified_since`, `expires` and ` etag` directives.

**Comment by mkellsy** [comment]
If all else fails you can run this script from the terminal.

```
wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/clean.sh | sudo bash -
```

The reboot the device.

This script will downgrade Node to 10.17.0, and reinstall HOOBS. It will keep your config and plugins, but you may need to remove and re-install some of your plugins.

**Comment by MikeDeltaHH** [comment]
I´ve forgot to write that i came from homebrdige... here is what i do:

1. install Ubuntu 18.04.3 LTS in a VMware vm with the user hoobs
2. install homebridge (runs as a service), homebridge-config-ui-x and then the hoobs plugin to migrate to hoobs
3. install all needed plugins and join my HomeKit setup - in the last weeks after migrating to hoobs i have no problem with the installation, all works perfect - this problem now is the first...

So i don´t have a hoobs.service, but a homebridge.service:

------------------------------------------------------------------------------------------
[Unit]
Description=Node.js HomeKit Server
After=syslog.target network-online.target

[Service]
Type=simple
User=hoobs
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
-----------------------------------------------------------------------------------------

try "rm -fR ~/.hoobs/dist && rm -fR ~/.hoobs/lib" and restart the service homebridge (because i´m come from a homebridge installation i have none hoobs.service but a homebridge.service --> no success, version is 3.1.1

In my hoobs.conf i have the important entries:

if_modified_since     off;
        expires               off;
        etag                  off;

Don´t understand what the problem is... by the way... all plugins are working - i hope the result isn´t to reinstall hoobs in a fresh vm... 

And by the way... thanks a lot for your help!

**Comment by mkellsy** [comment]
If you do, we have an install script so you don't need to start with Homebridge.

```
wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/install.sh | sudo bash -
```

It will even setup Node for you.

**Comment by MikeDeltaHH** [comment]
Test the script... after that i have to start hoobs manually and some of the plugins and configs are not working... revert to a snapshot bevore them... think the only solution is to do a fresh installation in a new virtual machine?! I use Ubuntu Linux and it seems that the hoobs script do not install hoobs as a service... what must i do to fix it?

**Comment by mkellsy** [comment]
I will have to test on Ubuntu, we test on Debian/Raspbian and Fedora

**Comment by MikeDeltaHH** [comment]
Ok, i will follow your installing manually howto for the service installation - i make a fresh installation without homebridge first and migrate all plugins step by step!

**Comment by MikeDeltaHH** [comment]
Strange... do a second test with the hoobs install script and now it works... all plugins are functional, hoobs running as a service, the homebrdige.service is gone and the version is 3.1.9!

Thanks for help and this masterpiece of software!

**Comment by mkellsy** [comment]
That's good to hear. Do you have a snapshot of the bad install? I would like to figure out what went wrong.

What's the hypervisor you use? Maybe you can email me the snapshot. If you have time.

**Comment by MikeDeltaHH** [comment]
I´m using VMware vSphere 6.7 on a nuc in my home network and i have a snapshot i made bevore i run the script, grab it here:

https://nextcloud.wandsbek-hamburg.de:52000/s/BsF4TnALMcAF4WY

**Comment by mkellsy** [comment]
Thanks
