### ISSUE TITLE
unable to find or intall homebridge-nuki

### ISSUE THREAD

**Issue by testpaul999** [hoobs-org/HOOBS#359]
**Description**
A clear and concise description of what the plugin is doing.
manage dooropener NUKI

**Expected behavoir**
Please let us know what the plugin is supposed to do.
use SIRI  to open door

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.
https://www.npmjs.com/package/homebridge-nuki

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.
no plugin problem, runns fine at "normal" homebridge installation
**Version**
Please include the version of HOOBS you are using.

3.1.10

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
xubuntu 19.10

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
hoobs@hoobs:~/.hoobs/etc$ cat config.json 
{
  "server": {
    "port": 8080,
    "origin": "*",
    "autostart": 0,
    "home_setup_id": "X-HM://0023ISYWYHN4B",
    "polling_seconds": 5
  },
  "client": {
    "default_route": "status",
    "inactive_logoff": 30,
    "theme": "hoobs-light",
    "locale": "de",
    "temp_units": "celsius",
    "country_code": "DE",
    "postal_code": "13059"
  },
  "bridge": {
    "name": "HOOBS",
    "port": 51826,
    "pin": "031-45-154",
    "username": "8F:EA:CC:16:94:CA"
  },
  "plugins": [
    "homebridge-fritz-platform"
  ],
  "platforms": [
    {
      "platform": "FritzPlatform",
      "devices": {
        "FRITZ!Box 7590": {
          "active": true,
          "host": "192.168.2.1",
          "port": 49000,
          "username": "",
          "password": "",
          "type": "dsl",
          "master": true,
          "mesh": true,
          "readOnly": true,
          "options": {
            "reconnect": false,
            "wifi2": [
              false,
              false
            ],
            "wifi5": [
              false,
              false
            ],
            "wifiGuest": [
              false,
              false
            ],
            "wps": [
              false,
              false
            ],
            "aw": [
              false,
              false
            ],
            "deflection": [
              false,
              false
            ],
            "led": [
              false,
              false
            ],
            "lock": [
              false,
              false
            ]
          }
        },
        "Repeater-Arbeitszimmer": {
          "active": true,
          "host": "192.168.2.2",
          "port": 49000,
          "username": "",
          "password": "",
          "type": "repeater",
          "readOnly": true,
          "options": {
            "wifi2": [
              false,
              false
            ],
            "wifi5": [
              false,
              false
            ],
            "wifiGuest": [
              false,
              false
            ],
            "wps": [
              false,
              false
            ],
            "led": [
              false,
              false
            ]
          }
        }
      },
      "presence": {
        "user": [
          {
            "active": true,
            "name": "JUF iPhone",
            "address": "38:53:9C:C6:E7:B7"
          },
          {
            "active": true,
            "name": "Anette iPhone",
            "address": "64:70:33:2E:DF:AF"
          },
          {
            "active": true,
            "name": "Dite iPhone",
            "address": "70:3C:69:7A:AE:74"
          },
          {
            "active": true,
            "name": "Omel iPhone",
            "address": "80:BE:05:82:15:3B"
          },
          {
            "active": true,
            "name": "Drucker",
            "address": "2C:6F:C9:49:FF:80"
          }
        ],
        "anyone": false,
        "offDelay": 2,
        "onDelay": 2,
        "ping": true
      },
      "smarthome": {
        "Repeater Flur oben": {
          "active": true,
          "ain": "087610859944",
          "tempSensor": true,
          "devType": "switch"
        },
        "Fernseher": {
          "active": true,
          "ain": "087610226897",
          "tempSensor": true,
          "devType": "switch"
        },
        "Stehlampe": {
          "active": true,
          "ain": "087610229590",
          "tempSensor": true,
          "devType": "switch"
        },
        "Licht Gartenhaus": {
          "active": true,
          "ain": "087610087090",
          "tempSensor": true,
          "devType": "switch"
        },
        "Licht Apfelbaum": {
          "active": true,
          "ain": "087610079122",
          "tempSensor": true,
          "devType": "switch"
        },
        "Pumpe": {
          "active": true,
          "ain": "116570018303",
          "tempSensor": true,
          "devType": "switch"
        },
        "WSterne Kueche": {
          "active": true,
          "ain": "087610340529",
          "tempSensor": true,
          "devType": "switch"
        },
        "WSterne HWR": {
          "active": true,
          "ain": "087610208071",
          "tempSensor": true,
          "devType": "switch"
        },
        "WSterne KiZi": {
          "active": true,
          "ain": "116300110260",
          "tempSensor": true,
          "devType": "switch"
        },
        "WBaum": {
          "active": true,
          "ain": "087610454568",
          "tempSensor": true,
          "devType": "switch"
        },
        "WSchlaZi": {
          "active": true,
          "ain": "116300094284",
          "tempSensor": true,
          "devType": "switch"
        },
        "DECT Lampe": {
          "active": true,
          "ain": "127010068434",
          "tempSensor": false,
          "devType": "switch"
        },
        "Briefkasten": {
          "active": true,
          "ain": "119340107283",
          "devType": "contact"
        },
        "Haustür": {
          "active": true,
          "ain": "119340245663",
          "devType": "contact"
        }
      },
      "polling": 5,
      "timeout": 5,
      "clearCache": false,
      "debug": false,
      "alarm": {
        "active": false,
        "telNr": "",
        "duration": 30
      },
      "wakeup": {
        "active": false,
        "internNr": "",
        "duration": 30
      },
      "broadband": {
        "active": false,
        "measureTime": 5
      },
      "extReboot": {
        "active": false,
        "cmdOn": "",
        "cmdOff": ""
      },
      "telegram": {
        "active": false,
        "token": "",
        "chatID": "",
        "presence": {
          "in": "",
          "out": "",
          "anyoneIn": "",
          "anyoneOut": ""
        },
        "callmonitor": {
          "incoming": "",
          "disconnected": ""
        },
        "alarm": {
          "activated": "",
          "deactivated": ""
        },
        "extReboot": {
          "start": "",
          "finish": ""
        }
      },
      "callmonitor": {
        "active": false,
        "ip": "0.0.0.0",
        "port": 1012,
        "country": "",
        "incomingTo": [],
        "outgoingFrom": []
      },
      "wol": [
        {
          "active": false,
          "name": "Test Device",
          "address": "00:00:00:00:00:00"
        }
      ],
      "ringlock": {
        "active": false,
        "DECTphones": 1,
        "start": "11:00",
        "end": "22:00"
      },
      "disableAutoSearch": false,
      "disableAutoConfig": false,
      "phoneBook": {
        "active": false,
        "blacklists": []
      },
      "plugin_map": {
        "plugin_name": "homebridge-fritz-platform"
      }
    }
  ],
  "package_manager": "npm",
  "system": "hoobs",
  "id": "config",
  "accessories": []
}hoobs@hoobs:~/.hoobs/etc$ 

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by MikeDeltaHH** [comment]
Just for info... think this isn´t a generally problem - i have the homebrdige-nuki plugin installed and running without any problems!

**Comment by testpaul999** [comment]
@MikeDeltaHH 
End how do you install this? At the module search I don‘t find it.
And if I install manually Hiobs don’t see it.

Thanks

**Comment by MikeDeltaHH** [comment]
Try to search nuki without homebrdige-! Then hoobs will find the plugin!

**Comment by testpaul999** [comment]
Ok, thx.

**Comment by MikeDeltaHH** [comment]
Does it solve the issue?

**Comment by testpaul999** [comment]
No this are the first problem for me, donˋt find Nuki or homebridge-Nuki. But equal this are only a test for decide HB or Hobbs.

**Comment by MikeDeltaHH** [comment]
Strange... i have some trouble with my Homematic setup, doesn´t work with hoobs this time but nuki works perfect!

**Comment by mkellsy** [comment]
I am unable to reproduce. When I type in nuki, it shows in the list. I am able to install it.
<img width="1171" alt="Screen Shot 2019-12-24 at 7 14 22 PM" src="https://user-images.githubusercontent.com/9777975/71429022-a808b100-2681-11ea-8971-1b349771ed35.png">

**Comment by testpaul999** [comment]
Thx and happy holly day
