### ISSUE TITLE
Ring Plugin with Two-Factor does not work

### ISSUE THREAD

**Issue by Matthias1987** [hoobs-org/HOOBS#361]
You can not use your Ring devices if Two-Factor in your Ring-account ist activated. The Plugin does not have this option to paste the Two-Factor-Key in its config.

**Comment by mkellsy** [comment]
You need to ask the developer of this plugin. His repo is here
https://github.com/dgreif/ring/issues

**Comment by Matthias1987** [comment]
Das Eintragen des zweiten Faktors funktioniert mit dem Plugin des Entwicklers bereits - wenn man es per Hand in der Config einträgt.
Das Ring-Plugin habt ihr für hoobs ja zertifiziert und daher mit einer Maske zum Konfigurieren versehen.
Ihr müsst eure Maske zum Eintragen aber noch anpassen. Hier fehlt schlicht noch ein Feld um den zweiten Faktor eintragen zu können.
Wenn das geschehen ist, lässt sich das Plugin auch in Hoobs komplett einstellen.

Mit freundlichen Grüßen
Matthias Petrat
(studierter Redakteur/Journalist | Buchautor )

Blog: matthias-petrat.com <https://www.matthias-petrat.com/>
Podcast: Kolumnen-Podcast <https://itunes.apple.com/de/podcast/matthias-petrat-com-kolumnen-podcast/id1030896274?mt=2>
Twitter: @matthiaspetrat <https://twitter.com/matthiaspetrat>
Facebook: @matthiaspetrat@me.com.blog <https://www.facebook.com/matthiaspetrat.blog/>
Apple Bücher: Apple HomeKit - die Schnittstelle zum Zuhause <https://apple.co/2QOkUEf>
