### ISSUE TITLE
Error while using the hue-plugin with Hoobs

### ISSUE THREAD

**Issue by MasterofKungfu9999** [hoobs-org/HOOBS#364]
Hi

I'm using the plugin with the newest Hoobs-Version of homebridge:

I'm getting following issue when i hit the hue-button:

```
[Homebridge] [12/23/2019, 21:26:32] [Hue] Philips hue: created user - please edit config.json and restart homebridge
[Homebridge] "platforms": [
[Homebridge] {
[Homebridge] "platform": "Hue",
[Homebridge] "users": {
[Homebridge] "xxxxxx": "xxxxx"
[Homebridge] }
[Homebridge] }
[Homebridge] ]
[Homebridge] [12/23/2019, 21:26:32] [Hue] Philips hue: 1 accessories
[Homebridge] [12/23/2019, 21:26:32] [Hue] cannot create /home/hoobs/.hoobs/etc/@hoobs/hue.json.gz: error ENOENT
[Homebridge] [12/23/2019, 21:26:32] [Hue] Initializing platform accessory 'Philips hue'...
[Homebridge] [12/23/2019, 21:26:32] [Hue] Philips hue: 2 services
```

Thanks

**Comment by mkellsy** [comment]
I bought a Hue bridge so I can start testing this.

**Comment by mkellsy** [comment]
I found the issue, we scope certified plugins and homebridge-hue uses the package name for files. This is a wired thing to do.

I modified the code to use "homebridge-hue" for the file names this plugin creates.

**Comment by MasterofKungfu9999** [comment]
I get now this error:

[Homebridge] [1/5/2020, 15:09:24] [Hue] npm registry: status 404 Not Found[Homebridge] [1/5/2020, 15:09:24] [Hue] TypeError: host.split is not a function
    at HuePlatform.maskHost (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:374:20)
    at HuePlatform.maskConfigJson (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:393:29)
    at /home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:265:42
    at Function.then (/home/hoobs/.hoobs/node_modules/deferred/_ext.js:65:13)
    at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)
    at Function.<anonymous> (/home/hoobs/.hoobs/node_modules/deferred/ext/promise/catch.js:29:4)
    at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)
    at Function.then (/home/hoobs/.hoobs/node_modules/deferred/_ext.js:70:4)

**Comment by mkellsy** [comment]
Can you post your config? This looks like an issue with the host variable.

**Comment by MasterofKungfu9999** [comment]
i have the same issue with other plugins. Homebridge isn't running after installation of the weather plus plugin.
Here is my config:

{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "",
        "latitude": "5",
        "longitude": "1"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 5,
        "pin": "031-",
        "username": "5F:"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "BlinkSecurityPlatform",
            "name": "Blink System",
            "username": "",
            "password": "",
            "discovery": false,
            "plugin_map": {
                "plugin_name": "homebridge-blinkcameras"
            }
        },
        {
            "platform": "FritzPlatform",
            "devices": {
                "FRITZ!WLAN Repeater 1750E": {
                    "active": true,
                    "host": "192.168.13.23",
                    "port": 49000,
                    "username": "",
                    "password": "",
                    "type": "repeater",
                    "readOnly": false,
                    "options": {
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ]
                    }
                },
                "FRITZ!Box 7590": {
                    "active": true,
                    "host": "192.168.13.1",
                    "port": 49000,
                    "username": "",
                    "password": "",
                    "type": "dsl",
                    "master": true,
                    "mesh": true,
                    "readOnly": false,
                    "options": {
                        "reconnect": false,
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "aw": [
                            true,
                            false
                        ],
                        "deflection": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ],
                        "lock": [
                            true,
                            false
                        ]
                    }
                }
            },
            "smarthome": {
                "Test Contact Sensor": {
                    "active": false,
                    "ain": "01234567890",
                    "devType": "contact"
                },
                "Test Thermostat Device": {
                    "active": false,
                    "ain": "01234567890",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false,
                    "devType": "thermostat"
                },
                "Test Outlet Device": {
                    "active": false,
                    "ain": "01234567890",
                    "tempSensor": false,
                    "devType": "switch"
                }
            },
            "callmonitor": {
                "active": false,
                "ip": "0.0.0.0",
                "port": 1012
            },
            "presence": {
                "user": [
                    {
                        "active": false,
                        "name": "Test User",
                        "address": "0.0.0.0"
                    }
                ],
                "anyone": false,
                "offDelay": 90,
                "onDelay": 15,
                "ping": false
            },
            "wol": [
                {
                    "active": false,
                    "name": "Test Device",
                    "address": "00:00:00:00:00:00"
                }
            ],
            "phoneBook": {
                "active": false
            },
            "alarm": {
                "active": false,
                "duration": 30
            },
            "wakeup": {
                "active": false,
                "duration": 30
            },
            "ringlock": {
                "active": false,
                "DECTphones": 1,
                "start": "11:00",
                "end": "22:00"
            },
            "broadband": {
                "active": true,
                "measureTime": 5
            },
            "extReboot": {
                "active": false
            },
            "telegram": {
                "active": false
            },
            "polling": 10,
            "timeout": 10,
            "clearCache": false,
            "debug": false,
            "disableAutoSearch": false,
            "disableAutoConfig": false,
            "plugin_map": {
                "plugin_name": "homebridge-fritz-platform"
            }
        },
        {
            "platform": "WeatherPlus",
            "plugin_map": {
                "plugin_name": "homebridge-weather-plus"
            }
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            }
        }
    ]
}

**Comment by mkellsy** [comment]
Hue and WeatherPlus are not configured.
```
{
    "platform": "WeatherPlus",
    "plugin_map": {
        "plugin_name": "homebridge-weather-plus"
    }
},
{
    "platform": "Hue",
    "plugin_map": {
        "plugin_name": "hue"
    }
}
```

HOOBS is fault tollerent, but Homebridge and the plugins are not. If you finish the configuration, Homebridge should start.

**Comment by MasterofKungfu9999** [comment]
Nope, it's the same when i configured the plugins

**Comment by mkellsy** [comment]
Can I get the config.json configured. I need to know how you are running it so I can do the same on a test rig. I need to do this so I can look for problems.

**Comment by MasterofKungfu9999** [comment]
i gót back default default settings and restored my config.json with the working plugins Fritz and Blink

**Comment by MasterofKungfu9999** [comment]
I have installed the weather-plus plugin (the modul is configured).  Hue-Plugin wasn't installed. I get this error:

<[Homebridge] [1/5/2020, 16:40:37] [WeatherPlus] Initializing WeatherPlus platform...[Homebridge] [1/5/2020, 16:40:37] [WeatherPlus] Adding station with weather service Dark Sky named 'Enger'[Homebridge] [1/5/2020, 16:40:37] ReferenceError: CustomService is not defined
    at new ForecastWeatherAccessory (/home/hoobs/.hoobs/node_modules/homebridge-weather-plus/accessories/forecast.js:54:30)
    at /home/hoobs/.hoobs/node_modules/homebridge-weather-plus/index.js:97:31
    at Array.forEach (<anonymous>)
    at /home/hoobs/.hoobs/node_modules/homebridge-weather-plus/index.js:91:19
    at Array.forEach (<anonymous>)
    at new WeatherPlusPlatform (/home/hoobs/.hoobs/node_modules/homebridge-weather-plus/index.js:62:22)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:293:34)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11[Homebridge] [1/5/2020, 16:40:37] Got SIGTERM, shutting down service...>

Do you want to have my config.json?

**Comment by mkellsy** [comment]
I will test the Hue and WeatherPlus plugins In dev, but I can't guarantee that it will address the issues you are seeing because I might configure my Hue bridge differently.

I will give it a shot though.

**Comment by MasterofKungfu9999** [comment]
I could install the plugins and the work. The issue can be closed.
