### ISSUE TITLE
upgrade von Homebridge auf hoobs / benutzernamen

### ISSUE THREAD

**Issue by fighterzg6** [hoobs-org/HOOBS#365]
Hi there,

i had two instances of homebridge running homebridge and homebridge-gerolf,
then upgrade done via the tool!
one instance is running again but I cannot log in to the second instance because the user name was pi. but he doesn't accept that! can I delete this instance and create a new one? or change username any way ??

hoobs current version 3.1.10 on Raspberry Pi 4 with buster
Sincerely yours

**Comment by BobbySlope** [comment]
Bitte innsies in english verfassen die wntwickler sprechen kein deutsch

**Comment by mkellsy** [comment]
Please translate to English.

**Comment by mkellsy** [comment]
HOOBS and Homebridge handle instances very differently. We do not have an upgrade path for systems that run multiple instances. This will require manually installing and configuring HOOBS.

Please visit our Wiki.
https://github.com/hoobs-org/HOOBS/wiki/6.1-Command-Line-Interface
