### ISSUE TITLE
Hoobs und Phiole

### ISSUE THREAD

**Issue by fighterzg6** [hoobs-org/HOOBS#366]
hallo, 

habe festgestellt das ich Phiole mit ip/admin/ nicht mehr aufrufen kann!!
kommt immer 

403 Forbidden

nginx/1.14.2

?????irgend eine Lösung????

**Comment by BobbySlope** [comment]
In terminal:
sudo systemctl disable nginx.service
sudo reboot

Hoobs ui is then reachable by hoobs.local:8080
Pihole ui is reachable by hoobs.local:80
