### ISSUE TITLE
Phiole nginx and hoobs

### ISSUE THREAD

**Issue by fighterzg6** [hoobs-org/HOOBS#367]
hello, i can no longer access the pihole web interface since i installed hoobs! it always comes
403 Forbidden

nginx/1.14.2

the address /ip/admin/

**Comment by BobbySlope** [comment]
In terminal:
sudo systemctl disable nginx.service
sudo reboot

Hoobs ui is then reachable by hoobs.local:8080
Pihole ui is reachable by hoobs.local:80
