### ISSUE TITLE
Ikea Tradfri - errors on install 1.2.30 published 12/21/2019

### ISSUE THREAD

**Issue by BlueiPhone** [hoobs-org/HOOBS#370]
> node-aead-crypto@2.1.4 install /home/hoobs/.hoobs/node_modules/node-aead-crypto 
> node lib/install.jsnode-aead-crypto is no longer needed on NodeJS 10+npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.1.4 (node_modules/node-aead-crypto): npmWARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.1.4 install: `node lib/install.js` npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1+ @hoobs/ikea-tradfri@1.2.30 added 22 packages from 16 contributors and audited 15331 packages in 78.6sfound 1 low severity vulnerability run `npm audit fix` to fix them, or `npm audit` for details ┌─────────────────────────────────────────────────────────┐ │ npm update check failed │ │ Try running with sudo or get access │ │ to the local update config store via │ │ sudo chown -R $USER:$(id -gn $USER) /home/hoobs/.config │ └─────────────────────────────────────────────────────────┘[12/25/2019, 9:54:58 AM] Installed "@hoobs/ikea-tradfri" package.

**Comment by mkellsy** [comment]
Please use issue temptates.
Did you upgrade from 2.1.1 specifically.

NPM is telling you what's wrong. It is root locked. This happens from running npm with sudo.

You need to run this.
```
sudo rm -fR ~/.npm
```

Then this.
```
sudo rm -fR ~/.config
```

**Comment by BlueiPhone** [comment]
Mike,

 

Yes, I did upgrade from 2.x to 3.x.

I did not understand: “Please use issue temptates.”

Are you asking me to use the install plugins?



I did the commands you suggested and then again tried installing ikea-tradfri.

 

I now see this:

 


> node-aead-crypto@2.1.4 install /home/hoobs/.hoobs/node_modules/node-aead-crypto 

> node lib/install.jsnode-aead-crypto is no longer needed on NodeJS 10+npm 

WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.1.4 (node_modules/node-aead-crypto):

npm WARN optional SKIPPING 

OPTIONAL 

DEPENDENCY: node-aead-crypto@2.1.4 install: `node lib/install.js` npm WARNoptional SKIPPING OPTIONAL DEPENDENCY: Exit status 1+ 

@hoobs/ikea-tradfri@1.2.30 added 22 packages from 16 contributors and audited 15331 packages in 76.508sfound 1 low severity vulnerability run `npm audit fix` to fix them, or `npm audit` for details[12/26/2019, 4:02:31 AM] Installed "@hoobs/ikea-tradfri" package.

 

Thank you,

 

Clay

**Comment by BlueiPhone** [comment]
Mike,

 

Yes, I did upgrade from 2.x to 3.x.

I did not understand: “Please use issue temptates.”

Are you asking me to use the install plugins?

I did the commands you suggested and then again tried installing ikea-tradfri.

 

All is running now.

 

Thank you,

 

Clay
