### ISSUE TITLE
3.1.10 Won't start after reboot

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/HOOBS#371]
**Description**
3.1.10 Won't start after reboot
**Version**
Please include the version of HOOBS you are using.
3.1.10
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Nest

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
can't access it through the UI

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```
can't access it through the UI

**Additional context**

**Comment by mkellsy** [comment]
I need some sort of log to invisgate this.

Can you SSH into the device and run this command
```
sudo systemctl status hoobs
```

Then post the output.

**Comment by OfficialKaos** [comment]
hoobs@hoobs:~ $ sudo systemctl status hoobs
● hoobs.service - HOOBS
   Loaded: loaded (/etc/systemd/system/hoobs.service; enabled; vendor preset: en
   Active: active (running) since Thu 2019-12-26 11:19:36 GMT; 7h ago
 Main PID: 292 (hoobs-core)
    Tasks: 13 (limit: 2200)
   Memory: 79.5M
   CGroup: /system.slice/hoobs.service
           ├─292 hoobs-core
           └─573 /bin/bash

Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] at Object.<anonymous> (/home/hoob
Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] at Module._compile (internal/modu
Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] at Object.Module._extensions..js 
Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] at Module.load (internal/modules/
Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] at tryModuleLoad (internal/module
Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] at Function.Module._load (interna
Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] at Function.Module.runMain (inter
Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] at startup (internal/bootstrap/no
Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] at bootstrapNodeJSCore (internal/
Dec 26 11:19:55 hoobs hoobs[292]: [Homebridge] [12/26/2019, 11:19:55 AM] Got SIG
lines 1-20/20 (END)

**Comment by mkellsy** [comment]
It looks like that is truncated. Can you do this.
```
sudo systemctl stop hoobs
```

Then run this
```
hoobs
```

And then post the output.

**Comment by OfficialKaos** [comment]
hoobs@hoobs:~ $ hoobs
[12/26/2019, 7:15:44 PM] HOOBS listning on port 8080.
[Homebridge] [12/26/2019, 7:15:45 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [12/26/2019, 7:15:45 PM] ---
[Homebridge] [12/26/2019, 7:15:46 PM] ====================
[Homebridge] [12/26/2019, 7:15:46 PM] ERROR LOADING PLUGIN homebridge-nest:
[Homebridge] [12/26/2019, 7:15:46 PM] /home/hoobs/.hoobs/node_modules/promise-prompt/index.js:1
[Homebridge] 
[Homebridge] ^
[Homebridge] SyntaxError: Invalid or unexpected token
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:723:23)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Module.require (internal/modules/cjs/loader.js:692:17)
[Homebridge] at require (internal/modules/cjs/helpers.js:25:18)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-nest/lib/nest-connection.js:8:16)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Module.require (internal/modules/cjs/loader.js:692:17)
[Homebridge] at require (internal/modules/cjs/helpers.js:25:18)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-nest/index.js:1:24)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Module.require (internal/modules/cjs/loader.js:692:17)
[Homebridge] at require (internal/modules/cjs/helpers.js:25:18)
[Homebridge] at Plugin.load (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/plugin.js:54:27)
[Homebridge] at Server.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:162:20)
[Homebridge] at Array.forEach (<anonymous>)
[Homebridge] at Server._loadPlugins (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:156:24)
[Homebridge] at new Server (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:49:26)
[Homebridge] [12/26/2019, 7:15:46 PM] ====================
[Homebridge] [12/26/2019, 7:15:46 PM] No plugins found. See the README for information on installing plugins.
[Homebridge] [12/26/2019, 7:15:46 PM] Error: The requested platform 'Nest' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[Homebridge] at startup (internal/bootstrap/node.js:283:19)
[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[Homebridge] [12/26/2019, 7:15:46 PM] Loading 1 platforms...
[Homebridge] [12/26/2019, 7:15:46 PM] Got SIGTERM, shutting down service...

**Comment by OfficialKaos** [comment]
I've uninstalled the nest plugin using the instructions here 
https://github.com/hoobs-org/HOOBS/wiki/4.0-Plugins 

Then re-installed it the same way through the API 

The devices are showing up and usable in homekit but no HOOBS UI just the HOOBS Tab at the top with no funtionality

[12/27/2019, 2:02:55 AM] HOOBS listning on port 8080.
[Homebridge] [12/27/2019, 2:02:55 AM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [12/27/2019, 2:02:55 AM] ---
[Homebridge] [12/27/2019, 2:02:56 AM] Loaded plugin: homebridge-nest
[Homebridge] [12/27/2019, 2:02:56 AM] Registering platform 'homebridge-nest.Nest'
[Homebridge] [12/27/2019, 2:02:56 AM] ---
[Homebridge] [12/27/2019, 2:02:56 AM] Loading 1 platforms...
[Homebridge] [12/27/2019, 2:02:56 AM] [Nest] Initializing Nest platform...
[Homebridge] [12/27/2019, 2:02:56 AM] [Nest] Fetching Nest devices.
[Homebridge] [12/27/2019, 2:02:57 AM] Loading 0 accessories...
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] initing thermostat "Reece": deviceId: xxxxxxxxxxxxxxxx structureId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] initing thermostat "Upstairs": deviceId: xxxxxxxxxxxxxxxx structureId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] initing thermostat "Downstairs": deviceId: xxxxxxxxxxxxxxxx structureId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] initing home_away_sensor "Home/Away": deviceId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx structureId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] initing protect "Reece": deviceId: xxxxxxxxxxxxxxxx  structureId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] initing protect "Family Room": deviceId: xxxxxxxxxxxxxxxx structureId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] initing protect "Living Room": deviceId: xxxxxxxxxxxxxxxx  structureId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] Initializing platform accessory 'Reece'...
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] Initializing platform accessory 'Upstairs'...
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] Initializing platform accessory 'Downstairs'...
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] Initializing platform accessory 'Home/Away'...
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] Initializing platform accessory 'Reece'...
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] Initializing platform accessory 'Family Room'...
[Homebridge] [12/27/2019, 2:02:59 AM] [Nest] Initializing platform accessory 'Living Room'...
[Homebridge] X-HM://0035ASDC6F1M8
[Homebridge] [12/27/2019, 2:02:59 AM] Service is running on port 51826.

**Comment by OfficialKaos** [comment]
Maybe I'm getting this part wrong because it won't execute?


Note. If you installed the plugin via the user interface, the interface can restart just the internal Homebridge service. If using the API you can restart the internal service via POST /api/service/restart. Since the terminal doesn't have access to the internal service, you must restart the entire HOOBS service.

this is twhat I'm doing
POST /api/service/restart

**Comment by mkellsy** [comment]
Can you screenshot the Accessories screen?

**Comment by OfficialKaos** [comment]
Sorry Mike I formatted the card and started again, 
Was going to use a new card, so you can look into the old one but I didnt have one! 

I'm just configuring the new install in HomeKit now everything seems ok so far. 

One thing I noticed was in the log when I update the accessories room, and edit there order in the HOOBS UI, I get this 
[Update Accessory] Request failed with status code 401

However doesn't seem to be effecting anything

Also I've installed the HOOBS Nest pluggin but I've still had to edit the config.json file manually is that right?

**Comment by OfficialKaos** [comment]
Fresh install HOOBS 3.1.1 udated to 3.1.12 
npm i @hoobs/nest
All working perfectly
