### ISSUE TITLE
Ring plugin prevents Hoobs from starting

### ISSUE THREAD

**Issue by erichter2018** [hoobs-org/HOOBS#372]
**Description**
Adding Ring plugin to Hoobs 3.1.10 prevents the Hoobs service from starting.

**Version**
3.1.10

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
RPi 4

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
chamberlain
tuya

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYK9GG",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "???"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "A8:FC:D2:C7:B7:15"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Chamberlain",
            "plugin_map": {
                "plugin_name": "chamberlain",
                "index": 0
            },
            "name": "Garage Door",
            "username": "???",
            "password": "???",
            "deviceId": "???"
        }
    ],
    "platforms": [
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "???",
                "password": "???",
                "countryCode": "1",
                "platform": "tuya",
                "pollingInterval": 10
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            }
        }
    ]
}```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[12/25/2019, 23:48:43] Installed "@hoobs/ring" package.
[Homebridge] [12/25/2019, 23:48:44] Loaded config.json with 1 accessories and 2 platforms.
[Homebridge] [12/25/2019, 23:48:44] ---
[Homebridge] [12/25/2019, 23:48:45] Loaded plugin: ring
[Homebridge] [12/25/2019, 23:48:45] Registering platform 'homebridge-ring.Ring'
[Homebridge] [12/25/2019, 23:48:45] ---
[Homebridge] [12/25/2019, 23:48:45] Loading 2 platforms...
[Homebridge] [12/25/2019, 23:48:45] Error: The requested platform 'TuyaWebPlatform' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[Homebridge] [12/25/2019, 23:48:45] Got SIGTERM, shutting down service...```

**Additional context**
Log after removing Ring plugin:

[12/25/2019, 23:49:39] "@hoobs/ring" package removed.
[Homebridge] [12/25/2019, 23:49:50] Loaded config.json with 1 accessories and 1 platforms.
[Homebridge] [12/25/2019, 23:49:50] ---
[Homebridge] [12/25/2019, 23:49:50] Loaded plugin: homebridge-tuya-web
[Homebridge] [12/25/2019, 23:49:50] Registering platform 'homebridge-tuya-web.TuyaWebPlatform'
[Homebridge] [12/25/2019, 23:49:50] ---
[Homebridge] [12/25/2019, 23:49:50] Loaded plugin: chamberlain
[Homebridge] [12/25/2019, 23:49:50] Registering accessory 'chamberlain.Chamberlain'
[Homebridge] [12/25/2019, 23:49:50] ---
[Homebridge] [12/25/2019, 23:49:50] Loading 1 platforms...
[Homebridge] [12/25/2019, 23:49:50] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[Homebridge] [12/25/2019, 23:49:50] Loading 1 accessories...
[Homebridge] [12/25/2019, 23:49:50] [Garage Door] Initializing Chamberlain accessory...
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Couch Disco Light] 16602287600194c29c5a fe21179f-239e-4701-9e15-170b2cabf28d
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Left Snowflakes] 68102802dc4f22e8974c c6468c22-fb71-4d11-a55b-833b0217d924
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Lower Foyer Tree] 82261020600194c5d515 72eb383c-79f3-4cd4-bd9f-49f1a17cc50e
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Right Snowflakes] 20156003600194b3c693 8a626bdc-9444-421c-b354-fc53d9cf87f5
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Dining Room Jesus Tree] 75111640dc4f22912e00 1367baa3-6086-4c1c-954a-386223c4644a
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Dining Room Snowflakes] 05528600dc4f22e27c67 e1a40a77-8c2c-4428-af66-7eefba4fef33
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Office Santa] 07830085c44f3385a95d 4152fc6a-93b6-4773-9d33-9ef8148b436e
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Kitchen Right Tree] 20156003840d8e4a1d14 891875c1-7855-4233-8b2f-e52a90ce9044
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Left Fireplace Tree] 63657747600194b5c2e7 7c4479f8-6f4e-4abd-a924-69e1b2034cce
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Dining Room Jesus Display] 63657747600194bab166 55982c04-56f1-4871-8a30-521853052f03
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Foyer Right Soldier] 63657747600194bcc070 54f63b33-6e52-4d16-915c-9e72f271ab54
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Butler's Pantry Jew Snowflake] 68102802dc4f22ebbc4d 6e6d90f7-784c-4670-8cc7-2efe3072d8c6
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Garage Power Switch] 02200370ecfabc916668 938d827a-909a-4b85-b1e2-9d68c640eeec
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Foyer Left Toy Soldier] 34340346600194c57b1a 53b4155f-d59d-4669-91fe-6c23a1ebefa6
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Boys Room Snowflakes] 20156003600194b4f419 e5e5447d-03c5-4d1a-990c-337cde703a70
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Garage Snowflakes] 68102802dc4f22ebb393 0f2cf7b5-db85-4925-81f7-3a89338372d9
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Buffet Tree] 75111640dc4f22915869 686f7b0a-2579-40b6-abfa-be64c7cd600b
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Dining Room Left Birch Trees] 05528600dc4f22e0627d b0fc1773-59e9-4ee9-a2c6-322c1788242f
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Christmas Tree] 20156003840d8e49c976 dafdf81d-388d-4ada-9e2d-93bd3eea43ac
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Dining Room Right Birch Trees] 63657747600194ba27ce 93ed4eb2-4525-4824-89f1-4b8a528ab85b
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Dining Room Window Trees] 17182400807d3a4fd6be 4a41b8f0-ff29-4a4e-a900-cb1ec2b4c5a8
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Light Cube] 05528600dc4f22e9a199 93d76c92-a4e1-4cd0-b814-887b117c2f9b
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Kitchen Sink Snowflake] 02200370ecfabc915dd4 d4fa2d6b-0a8d-4506-8145-c67b7e276284
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Foyer Snowflakes] 68102802dc4f22e879a8 ec8825cf-3902-4a49-bf55-3a188d8fb897
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Kitchen Right Snowflake] 75111640dc4f22914465 17d87f50-f132-41de-91fd-8e75c4a36d94
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Master Bedroom Snowflakes] 63657747600194b9ce41 39773cf9-b7d7-4053-9c6c-af8a9e0616f3
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Birch Trees] 68102802dc4f22e88aa9 ec097414-4b69-4329-9c55-c8a2b27fe05c
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Powder Room Wax Melt] 63657747600194baa5ba e848cce0-f5b3-4d24-aeda-2f933a48eae2
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Kitchen Left Snowflake] 63657747600194bca7e2 3c2d4252-cd70-4fdb-ab81-b5ffc016c824
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Corner Tree] 05528600dc4f22ea1b6e 4184bd32-2b11-4e95-8651-85845105063e
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Powder Room Tree] 38486716dc4f22e017b6 e970ad8a-957b-41db-aa28-03cdc65b8e42
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Family Room Right Fireplace Tree] 38486716dc4f22e283cb 7e5fb5c2-ab8a-4d0e-b365-cd453cdd77b7
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Configuring cached accessory [Office Window Holiday] 68102802dc4f22f073ae 4f5d2c47-fdba-41b6-8226-88ca2ef3d677
[Homebridge] X-HM://0023ISYWYK9GG
[Homebridge] [12/25/2019, 23:49:51] [TuyaWebPlatform] Initializing TuyaWebPlatform...
[Homebridge] [12/25/2019, 23:49:51] Service is running on port 51826.
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Couch Disco Light (switch / 16602287600194c29c5a)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Couch Disco Light] [16602287600194c29c5a] [fe21179f-239e-4701-9e15-170b2cabf28d]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Left Snowflakes (switch / 68102802dc4f22e8974c)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Left Snowflakes] [68102802dc4f22e8974c] [c6468c22-fb71-4d11-a55b-833b0217d924]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Lower Foyer Tree (switch / 82261020600194c5d515)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Lower Foyer Tree] [82261020600194c5d515] [72eb383c-79f3-4cd4-bd9f-49f1a17cc50e]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Right Snowflakes (switch / 20156003600194b3c693)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Right Snowflakes] [20156003600194b3c693] [8a626bdc-9444-421c-b354-fc53d9cf87f5]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Dining Room Jesus Tree (switch / 75111640dc4f22912e00)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Dining Room Jesus Tree] [75111640dc4f22912e00] [1367baa3-6086-4c1c-954a-386223c4644a]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Dining Room Snowflakes (switch / 05528600dc4f22e27c67)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Dining Room Snowflakes] [05528600dc4f22e27c67] [e1a40a77-8c2c-4428-af66-7eefba4fef33]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Office Santa (switch / 07830085c44f3385a95d)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Office Santa] [07830085c44f3385a95d] [4152fc6a-93b6-4773-9d33-9ef8148b436e]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Kitchen Right Tree (switch / 20156003840d8e4a1d14)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Kitchen Right Tree] [20156003840d8e4a1d14] [891875c1-7855-4233-8b2f-e52a90ce9044]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Left Fireplace Tree (switch / 63657747600194b5c2e7)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Left Fireplace Tree] [63657747600194b5c2e7] [7c4479f8-6f4e-4abd-a924-69e1b2034cce]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Dining Room Jesus Display (switch / 63657747600194bab166)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Dining Room Jesus Display] [63657747600194bab166] [55982c04-56f1-4871-8a30-521853052f03]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Foyer Right Soldier (switch / 63657747600194bcc070)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Foyer Right Soldier] [63657747600194bcc070] [54f63b33-6e52-4d16-915c-9e72f271ab54]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Butler's Pantry Jew Snowflake (switch / 68102802dc4f22ebbc4d)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Butler's Pantry Jew Snowflake] [68102802dc4f22ebbc4d] [6e6d90f7-784c-4670-8cc7-2efe3072d8c6]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Garage Power Switch (switch / 02200370ecfabc916668)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Garage Power Switch] [02200370ecfabc916668] [938d827a-909a-4b85-b1e2-9d68c640eeec]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Foyer Left Toy Soldier (switch / 34340346600194c57b1a)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Foyer Left Toy Soldier] [34340346600194c57b1a] [53b4155f-d59d-4669-91fe-6c23a1ebefa6]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Boys Room Snowflakes (switch / 20156003600194b4f419)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Boys Room Snowflakes] [20156003600194b4f419] [e5e5447d-03c5-4d1a-990c-337cde703a70]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Garage Snowflakes (switch / 68102802dc4f22ebb393)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Garage Snowflakes] [68102802dc4f22ebb393] [0f2cf7b5-db85-4925-81f7-3a89338372d9]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Buffet Tree (switch / 75111640dc4f22915869)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Buffet Tree] [75111640dc4f22915869] [686f7b0a-2579-40b6-abfa-be64c7cd600b]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Dining Room Left Birch Trees (switch / 05528600dc4f22e0627d)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Dining Room Left Birch Trees] [05528600dc4f22e0627d] [b0fc1773-59e9-4ee9-a2c6-322c1788242f]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Christmas Tree (switch / 20156003840d8e49c976)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Christmas Tree] [20156003840d8e49c976] [dafdf81d-388d-4ada-9e2d-93bd3eea43ac]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Dining Room Right Birch Trees (switch / 63657747600194ba27ce)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Dining Room Right Birch Trees] [63657747600194ba27ce] [93ed4eb2-4525-4824-89f1-4b8a528ab85b]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Dining Room Window Trees (switch / 17182400807d3a4fd6be)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Dining Room Window Trees] [17182400807d3a4fd6be] [4a41b8f0-ff29-4a4e-a900-cb1ec2b4c5a8]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Light Cube (switch / 05528600dc4f22e9a199)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Light Cube] [05528600dc4f22e9a199] [93d76c92-a4e1-4cd0-b814-887b117c2f9b]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Kitchen Sink Snowflake (switch / 02200370ecfabc915dd4)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Kitchen Sink Snowflake] [02200370ecfabc915dd4] [d4fa2d6b-0a8d-4506-8145-c67b7e276284]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Foyer Snowflakes (switch / 68102802dc4f22e879a8)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Foyer Snowflakes] [68102802dc4f22e879a8] [ec8825cf-3902-4a49-bf55-3a188d8fb897]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Kitchen Right Snowflake (switch / 75111640dc4f22914465)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Kitchen Right Snowflake] [75111640dc4f22914465] [17d87f50-f132-41de-91fd-8e75c4a36d94]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Master Bedroom Snowflakes (switch / 63657747600194b9ce41)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Master Bedroom Snowflakes] [63657747600194b9ce41] [39773cf9-b7d7-4053-9c6c-af8a9e0616f3]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Birch Trees (switch / 68102802dc4f22e88aa9)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Birch Trees] [68102802dc4f22e88aa9] [ec097414-4b69-4329-9c55-c8a2b27fe05c]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Powder Room Wax Melt (switch / 63657747600194baa5ba)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Powder Room Wax Melt] [63657747600194baa5ba] [e848cce0-f5b3-4d24-aeda-2f933a48eae2]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Kitchen Left Snowflake (switch / 63657747600194bca7e2)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Kitchen Left Snowflake] [63657747600194bca7e2] [3c2d4252-cd70-4fdb-ab81-b5ffc016c824]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Corner Tree (switch / 05528600dc4f22ea1b6e)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Corner Tree] [05528600dc4f22ea1b6e] [4184bd32-2b11-4e95-8651-85845105063e]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Powder Room Tree (switch / 38486716dc4f22e017b6)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Powder Room Tree] [38486716dc4f22e017b6] [e970ad8a-957b-41db-aa28-03cdc65b8e42]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Family Room Right Fireplace Tree (switch / 38486716dc4f22e283cb)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Family Room Right Fireplace Tree] [38486716dc4f22e283cb] [7e5fb5c2-ab8a-4d0e-b365-cd453cdd77b7]
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Adding: Office Window Holiday (switch / 68102802dc4f22f073ae)
[Homebridge] [12/25/2019, 23:49:53] [TuyaWebPlatform] Existing Accessory found [Office Window Holiday] [68102802dc4f22f073ae] [4f5d2c47-fdba-41b6-8226-88ca2ef3d677]

**Comment by mkellsy** [comment]
It looks like the TuyaWebPlatform that is causing the issue. I need to try to reproduce.
1. inatall TuyaWebPlatform
2. then install ring

**Comment by erichter2018** [comment]
Uninstalling Tuya and installing Ring worked fine.  So indeed it's Tuya...  BTW, installing any plugin after Tuya made Hoobs fail, just FYI.

**Comment by mkellsy** [comment]
I figured as much.

**Comment by mkellsy** [comment]
I updated this plugin. It should work now.
