### ISSUE TITLE
Permission issues causing hoobs to crash on boot

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#373]
**Description**
It seems like in some cases, with a fresh install of 3.1.10 (both flashed from img or installed via the the command line), we run into the following error:

`hoobs@hoobs:~/.hoobs/etc $ hoobs -D
[12/26/2019, 12:15:48 AM] Unhandled Rejection "TypeError: Cannot read property 'port' of undefined".
TypeError: Cannot read property 'port' of undefined
    at new AccessoriesController (/home/hoobs/.hoobs/lib/controllers/accessories.js:12:72)
    at new API (/home/hoobs/.hoobs/lib/api.js:119:26)
    at module.exports (/home/hoobs/.hoobs/lib/cli.js:147:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:1023) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)`

It can also display as a SyntaxError if the config and layout.json files exist but are empty
![port error](https://user-images.githubusercontent.com/3981552/71459657-85a48f80-2776-11ea-9ec5-920a3fe0753c.PNG)

However the error seems to go away if HOOBS is ran as root:

`root@hoobs:~/.hoobs# hoobs -D
Migrating users '/root/.homebridge/accessories/layout.json'.
Migrating config '/root/.homebridge/config.json'.
[12/26/2019, 12:18:00 AM] HOOBS listning on port 8080.
[Homebridge] [12/26/2019, 12:18:01 AM] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [12/26/2019, 12:18:01 AM] ---
[Homebridge] [12/26/2019, 12:18:01 AM] No plugins found. See the README for information on installing plugins.
[Homebridge] [12/26/2019, 12:18:01 AM] Loading 0 platforms...
[Homebridge] [12/26/2019, 12:18:01 AM] Loading 0 accessories...
[Homebridge] X-HM://0023ISYWY3IMD
[Homebridge] [12/26/2019, 12:18:01 AM] Service is running on port 51826.`

**Version**
HOOBS 3.1.10
Node v10.17.0
NPM 6.11.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Additional context**
This seems to be a permission issue to read the layout and config files. I tried changing the permissions on these 2 files however it hasn't fixed the issue as a regular user.

**Comment by askovi** [comment]
Nevermind. Not a permission issue. It seems like when installed without root, it didn't add this part to the config.json file:

`"bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "A3:CC:53:A0:A3:3D"
    },
   "system": "hoobs"`

Adding that part to the config got it working

**Comment by mkellsy** [comment]
This is happening because there is config clean logic that is removing the bridge section. I restricted this to only accessories and platforms.

**Comment by askovi** [comment]
So the same JSON syntax error was happening to another customer. Here's how I fixed it:

1. Added the bridge section and the system:hoobs to config.json
2. deleted layout.json
3. Added an empty array [ ] in access.json (file was empty) 

Errors went away and it booted fine after that. Please check what could cause any of the above to fail.

**Comment by mkellsy** [comment]
I added file try catches for the access and layout files.

**Comment by mkellsy** [comment]
Zero length file issues. Run the testing reset script before shipping.
