### ISSUE TITLE
Cannot delete any plugin

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#375]
**Description**
User reported bug. No plugin can be deleted. It doesn't seem to be plugin specific. I tested twinkly and it worked fine to install, use and remove.  
As per user: 

>  I am unable to update or uninstall any of the plugins. I installed a plugin for twinkly lights a while back and all was working fine for a while. I noticed there is an update available for this plugin, but I am unable to update it. I also tried deleted the plugin completely but it will not delete. Hoobs will not let me delete any plugin at the currently.

See errors below:
![A1DDA270-2892-49C5-B839-1572FD40AAD6](https://user-images.githubusercontent.com/3981552/71504679-60805180-2848-11ea-85d3-7379f8e6bdea.png)

**Version**
3.1.x

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Comment by mkellsy** [comment]
He needs to run this
```
rm -fR ~/.hoobs/node_modules/homebridge-twinkly

**Comment by mkellsy** [comment]
This was caused by improper migration logic. This could have also been caused by root locked npm directories.

I have fixed this in 3.1.15
