### ISSUE TITLE
Update the SSL Certificate at cockpit.hoobs.org

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#376]
**Description**
Clicking the Remote support button crashes HOOBS and brings it back to login page. In browser console we get:
![image](https://user-images.githubusercontent.com/3981552/71505031-ae498980-2849-11ea-8bf5-b1f9b2ddbae0.png)

**Version**
3.1.12

**Comment by mkellsy** [comment]
This is due to a certificate issue at https://cockpit.hoobs.org

**Comment by mkellsy** [comment]
It took a bit but I was able to get certbot to renew the certificate. It has to shutdown the cockpit.service before. It's not clear.

Anyway I added the certbot renew script to crontab so it does it automatically.
