### ISSUE TITLE
Philips Hue Plugin Hoobs Certifiet version 0.11.45 problem

### ISSUE THREAD

**Issue by BPC83** [hoobs-org/HOOBS#377]
**Description**
Earlier I was using the same hue plugin (before it was certified) and it worked great, then I installed another plugin, and maked a miskate, and *language* op til system, so I formatted the SD card, downloaded a fresh image from hoobs.org flashed it to my sd card, booted up, updated hoobs to 3.1.10 installed HUE from the certified plugins, linked my bridge, copied the username from the log, and pasted it in the settings, exactly as I have done last time, when it worked, and the the log tells something about wrong versions (log will be pasted down below) today 27-12-2019 I see that there was a new version of hoobs, upgraded to 3.1.12 from gui, but still don't work
 
**Expected behavoir**
Connection to philips hue bridge, and dischover lights and publish them to HomeKit 

**Plugin name**
"Hue" from "lighting" section under certified plugins version 0.11.45

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.1.12

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes from the version that the image file to download on hoobs.org
- [ ] No

**Pervious version**
The online image version I think is was 3.1 then to 3.1.10 and to 3.1.12

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X ] Custom Install

**If this is a custom install, what's your operating system?**
Downloaded image, on SD card on Raspberry PI 3 B+

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY1EJD",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "DK",
        "postal_code": "7400"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "REMOVED",
        "username": "REMOVED"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "users": {
                "REMOVED": "REMOVED"
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[12/27/2019, 11:22:17] HOOBS listning on port 8080.
[Homebridge] [12/27/2019, 11:22:20] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [12/27/2019, 11:22:20] ---
[Homebridge] [12/27/2019, 11:22:25] Loaded plugin: hue
[Homebridge] [12/27/2019, 11:22:25] Registering platform 'homebridge-hue.Hue'
[Homebridge] [12/27/2019, 11:22:25] ---
[Homebridge] [12/27/2019, 11:22:25] Loading 1 platforms...
[Homebridge] [12/27/2019, 11:22:25] [Hue] Initializing Hue platform...
[Homebridge] [12/27/2019, 11:22:25] [Hue] config.json: warning: plugin_map: ignoring unknown key
[Homebridge] [12/27/2019, 11:22:25] [Hue] @hoobs/hue v0.11.45, node v12.13.1, homebridge v0.4.50
[Homebridge] [12/27/2019, 11:22:25] [Hue] warning: not using recommended node version v7.0.0 LTS
[Homebridge] [12/27/2019, 11:22:25] [Hue] warning: not using recommended homebridge version v0.4.22
[Homebridge] [12/27/2019, 11:22:25] Loading 0 accessories...
[Homebridge] [12/27/2019, 11:22:32] [Hue] Philips hue: Philips BSB002 bridge v1935144020, api v1.35.0
[Homebridge] [12/27/2019, 11:22:32] [Hue] Philips hue: warning: not using recommended Hue bridge api version undefined
[Homebridge] [12/27/2019, 11:22:33] [Hue] Philips hue: 1 accessories
[Homebridge] [12/27/2019, 11:22:33] [Hue] cannot create /home/hoobs/.hoobs/etc/@hoobs/hue.json.gz: error ENOENT
[Homebridge] [12/27/2019, 11:22:33] [Hue] Initializing platform accessory 'Philips hue'...
[Homebridge] [12/27/2019, 11:22:33] [Hue] Philips hue: 2 services
[Homebridge] X-HM://0023ISYWY1EJD
[Homebridge] [12/27/2019, 11:22:33] Service is running on port 51826.
```

**Additional context**

**Comment by mkellsy** [comment]
Need to modify the code to handle the hue.json.gz file.

**Comment by mkellsy** [comment]
I bought a Hue bridge so I can start testing this.

**Comment by mkellsy** [comment]
Here's the issue.
```
cannot create /home/hoobs/.hoobs/etc/@hoobs/hue.json.gz: error ENOENT
```
I need modify the code to use something different then the name of the package for a file name. HOOBS supports scoped plugins, where homebridge-hue is not scoped.

**Comment by mkellsy** [comment]
I found the issue. it took a bit, but I release a new version of this plugin.
