### ISSUE TITLE
Boot error on 3.1.1

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#380]
**Description**
Box customer on 3.1.1 first boot received this error:
![error paul 1](https://user-images.githubusercontent.com/3981552/71531389-7d566c80-28bc-11ea-8d5a-f3fac6fe684d.PNG)

I ran the install.sh script then after it was done on 3.1.14 it prompted this error:
![error paul 2 after install script ran](https://user-images.githubusercontent.com/3981552/71531420-952df080-28bc-11ea-9a31-f9503343d026.PNG)

After a restart, it went into the JSON syntax error, and I got it fixed by adding the missing parts in config.json (bridge and system)

**Version**
3.1.1 & 3.1.14

**Comment by mkellsy** [comment]
This is a Node error because it isn't loading the main cli.js.

In 3.1.15 I re-worked the loader. I will look at the img generator to see why Node is corrupt.

**Comment by mkellsy** [comment]
This is happening because you unplug the pi before it has a chance to commit it's write buffer. This is causing the user mode files to be zero length.

In 3.1.17, there is a reset test script.
```
 wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset
```
