### ISSUE TITLE
How do you update the Node

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/HOOBS#381]
**Description**
I have 6 pi's running HOOBS on 3.1.14 and each has a different Node version?
**Version**
Please include the version of HOOBS you are using.
3.1.14
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.
2.1.1 and new custom install
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [x] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
MacOS High Sierra
**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Nest
Sonos ZP
Ring
Harmony
Wemo
Sonos

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
This will install Node 10.17.0
```
wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/clean.sh | sudo bash -
```

**Comment by OfficialKaos** [comment]
excellent thanks
what if we need a specific version? will you update the Node with HOOBS releases?

**Comment by OfficialKaos** [comment]
Thanks worked perfectly

**Comment by mkellsy** [comment]
This installs Node 10.17.0
```
wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/clean.sh | sudo bash -
```

This installs 12.14.0
```
wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/upgrade-node.sh | sudo bash -
```

If you want to install different versions, have a look at n.
https://www.npmjs.com/package/n

**Comment by OfficialKaos** [comment]
Excellent thank you
