### ISSUE TITLE
Honeywell-Home Plugin

### ISSUE THREAD

**Issue by donavanbecker** [hoobs-org/HOOBS#382]
**Description**
Issue with config on Homebridge-Honeywell-Home

**Expected behavoir**
Connect to Honeywell Home Thermostats

**Plugin name**
Homebridge-honeywell-home

**Please report the issue to the plugin developer**
I am the developer

**Version**
3.1.14

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{ "platform"         : "homebridge-honeywell-home.HoneywellHome"
    , "name"             : "HoneywellHome"
    , "credentials"      :
      { "consumerKey"    : "..."
      , "consumerSecret" : "..."
      , "accessToken"    : "..."
      , "refreshToken"   : "..."
      }
    , "options"          : { "ttl": 600, "verboseP" : false }
    }
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
Cannot find module './build/Release/pcap_binding'
Require stack:
- /private/var/root/.hoobs/node_modules/pcap/pcap.js
- /private/var/root/.hoobs/node_modules/homespun-discovery/observers/observer-arp.js
- /private/var/root/.hoobs/node_modules/homespun-discovery/index.js
- /private/var/root/.hoobs/node_modules/homebridge-honeywell-home/index.js
- /private/var/root/.hoobs/lib/plugins.js
- /private/var/root/.hoobs/lib/controllers/system.js
- /private/var/root/.hoobs/lib/api.js
- /private/var/root/.hoobs/lib/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
Unable to determine plugin type for "homebridge-honeywell-home"
```

**Additional context**

**Comment by d0n4v4nb3ck3r** [comment]
Why is this doing this on hoobs?

**Comment by d0n4v4nb3ck3r** [comment]
[](https://github.com/d0n4v4nb3ck3r/homebridge-honeywell-home)

**Comment by mkellsy** [comment]
I am working on better plugin detection logic. It should use your config.schema.json to determine the type, but it is still running the partial load logic to determine the type and alias.

**Comment by mkellsy** [comment]
Done in 3.1.15

**Comment by donavanbecker** [comment]
Awesome!

**Comment by YungFras85** [comment]
I have installed the Honeywell Home plugin but it does not trigger the account link page like Homebridge does and I get this error when restarting HOOBS:     9/27/2020, 12:28:58 PM The requested platform "HoneywellHomeThermostat" was not registered by any plugin.
9/27/2020, 12:28:58 PM Your config.json is requesting the platform "HoneywellHomeThermostat" which has not been published by any installed plugins.

Any idea why it is doing this. It worked fine with homebridge but does not work with HOOBS.
