### ISSUE TITLE
ERROR: FFmpeg exited with code -2 -need to add a line on terminal

### ISSUE THREAD

**Issue by uazad** [hoobs-org/HOOBS#383]
I'm getting an  FFmpeg exited with code -2
I fixed that on my other homebridge install by adding :
apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev 
on terminal.. but on hoops that command does not work on terminal.. any help? 

**Version**
Please include the version of HOOBS you are using.
3.1.14

```
[
    {
        "name": "XXX",
        "videoConfig": {
            "source": "-re -i rtsp://XXXX:XXXX@192.168.1.33:554/Sms=1.unicast",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 10,
            "maxBitrate": 300,
            "vcodec": "h.264",
            "packetSize": 1316,
            "audio": true,
            "debug": false
        }
    }
]```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
Need to use sudo with apk
```
sudo apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev
```

I think using apt-get is better
```
sudo apt-get install -y ffmpeg ffmpeg-libs libpcap-dev
```

**Comment by uazad** [comment]
I'm getting this:

hoobs@hoobs:~ $ sudo apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev
sudo: apk: command not found


and:


hoobs@hoobs:~ $ sudo apt-get install -y ffmpeg ffmpeg-libs libpcap-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ffmpeg-libs

**Comment by mkellsy** [comment]
That's because Debian calls it something different, doesn't matter because ffmpeg depends on it's libs. So this should work.
```
sudo apt-get install -y ffmpeg libpcap-dev
```

> Note. This is not HOOBS software this is the package manager that comes with Debian or Raspbian. I just did a quick Google search and found out that all you really need to install is ffmpeg.

**Comment by uazad** [comment]
Thank you so much!
