### ISSUE TITLE
Blocked at loading screen

### ISSUE THREAD

**Issue by Yatoo2** [hoobs-org/HOOBS#384]
Hello !

I've downloaded last version (3.1.1) on Hoobs website after donating.
I've flashed my Micro SD with belenaEtcher.
I've installed this micro SD on a Raspberry PI Zero W and run it.

I've seen him in my wifi's:
![image](https://user-images.githubusercontent.com/9976799/71554417-04235a80-2a1f-11ea-8f63-81f587fb3ecd.png)

I've connected him on my wifi and visited http://hoobs.local
I'm now blocked on loading screen (even after one night loading):
![image](https://user-images.githubusercontent.com/9976799/71554463-bf4bf380-2a1f-11ea-90f0-80a1f6e1b08c.png)

I see him in my network:
![image](https://user-images.githubusercontent.com/9976799/71554493-223d8a80-2a20-11ea-91ce-2bbe37b5afec.png)

Have you got a solution for me ?

Have a nice day

**Comment by BobbySlope** [comment]
HOOBS 3 doesn’t work on Pi Zero. It requires at least a Pi3. Download HOOBS 2.1.1 from your account to run on the zero.

**Comment by Yatoo2** [comment]
Thank you for your quick answer ! It works :)

**Comment by mkellsy** [comment]
@Yatoo2 My Pi Zero is on it's way. We released version 3.1.15 and we made a ARM V6 build for the Pi Zero.

If you have a chance, can you download the img and test it for us.
https://github.com/hoobs-org/HOOBS/releases/tag/v3.1.15

> It's under the Raspberry Pi 1B, 2B and Zero W section

**Comment by Yatoo2** [comment]
Yes I’ll try it this evening :)

**Comment by Yatoo2** [comment]
> @Yatoo2 My Pi Zero is on it's way. We released version 3.1.15 and we made a ARM V6 build for the Pi Zero.
> 
> If you have a chance, can you download the img and test it for us.
> https://github.com/hoobs-org/HOOBS/releases/tag/v3.1.15
> 
> > It's under the Raspberry Pi 1B, 2B and Zero W section

I can confirm it works :)
