### ISSUE TITLE
HOOBS 2.1.1 Image appears to already have a username and password

### ISSUE THREAD

**Issue by mrjcohen** [hoobs-org/HOOBS#388]
**Description**
After flashing the HOOBS 2.1.1 Image from Github to an SD card and connecting via hoobs.local I am prompted to enter an existing username and password. I am not getting a prompt to create a user. 

**Version**
HOOBS 2.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

This is a new install on a raspberry Pi 3B+

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**Comment by askovi** [comment]
V2.1.1 comes with default user: admin password: admin

**Comment by mrjcohen** [comment]
oh I see, I'm sorry for wasting your time. I was unable to find it in the documentation. Thank you :)
