### ISSUE TITLE
Ring live video not working 

### ISSUE THREAD

**Issue by burnusgas** [hoobs-org/HOOBS#390]
**Description**
Having an issue with Ring cameras - will show the snapshot, but not the live video.  Log shows that it cannot find ffmpeg. Used terminal to install using "sudo npm install ffmpeg" and it appeared to install - restarted service, restarted appletv hub, restarted iPhone, added ring camera to Home app again. Didn't work - log still showing that it cannot find ffmpeg. The error in the Home app is "No Response. This camera is not responding."  All the doorbell cams, spotlight cams, & inside cams work find on Ring app. Using Eero Pro mesh system w/ ethernet backhaul. Raspberry Pi 3.

**Expected behavoir**
When you click on the camera snapshot in the Home app, it is supposed to show live video from the ring camera. 

**Plugin name**
homebridge-ring 5.10 from Hoobs

**Please report the issue to the plugin developer**
https://github.com/dgreif/ring/issues/211

**Version**
3.1.15

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Downloaded the HOOBS image and flashed onto blank microSD card on 12/30/2019. 

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "deleted for security",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "deleted for security"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "deleted for security",
        "username": "deleted for security"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "nest"
            },
            "googleAuth": {
                "issueToken": "deleted for security",
                "cookies": "deleted for security",
                "apiKey": "deleted for security"
            },
            "email": "deleted for security"
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "refreshToken": "deleted for security"
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[Homebridge] [12/30/2019, 15:23:43] Service is running on port 51826.
[Homebridge] [12/30/2019, 15:24:55] [Ring] Snapshot for Garage Requested
[Homebridge] [12/30/2019, 15:24:58] [Ring] Snapshot for Garage Received (2.364s)
[Homebridge] [12/30/2019, 15:25:01] [Ring] Preparing Live Stream for Garage
[Homebridge] [12/30/2019, 15:25:01] [Ring] Streaming video only - ffmpeg was not found
[Homebridge] [12/30/2019, 15:25:04] [Ring] Waiting for stream data from Garage (2.922s)
[Homebridge] [12/30/2019, 15:25:11] [Ring] Stopped Live Stream for Garage
```

**Additional context**

**Comment by askovi** [comment]
It's not sudo npm install ffmpeg
It's sudo apt-get install ffmpeg

**Comment by burnusgas** [comment]
[Homebridge] [12/30/2019, 17:51:09] [Ring] Snapshot for Pond Received (3.754s)
[Homebridge] [12/30/2019, 17:51:17] [Ring] Preparing Live Stream for Pond
[Homebridge] [12/30/2019, 17:51:17] [Ring] Streaming video only - found ffmpeg, but libfdk_aac is not installed.
[Homebridge] [12/30/2019, 17:51:20] [Ring] Waiting for stream data from Pond (2.983s)
[Homebridge] [12/30/2019, 17:51:27] [Ring] Stopped Live Stream for Pond

**Comment by burnusgas** [comment]
Opened most of the ports for a ring camera based on this - https://support.ring.com/hc/en-us/articles/205385394-What-Ports-Do-I-Need-to-Open-in-My-Firewall-for-Ring-Doorbells-and-Chimes-

Ports | Traffic type | Protocol

15063/15064 | SIP | TCP/UDP
9998/9999/6970 | RSS | TCP
16500-65000 | RTP | UDP (could not do this whole range since Eero app allows only 100 range)
7076/7077 | App | UDP
9078/9079 | App | UDP

Restarted iPhone, appletv, Pi, deleted & added that ring camera - no live view.

**Comment by d0n4v4nb3ck3r** [comment]
Looks like @dgreif updated the ring plugin to 5.12.1 that fixes live-stream. Anyway we can get the update on the certified plugin so that live view works with hoobs?

https://www.npmjs.com/package/homebridge-ring

**Comment by adavison007** [comment]
ALL - For ring live stream, you need to do more than just sudo apt-get install ffmpeg See full instructions from @dgreif below... this has worked on all version for me..

https://github.com/dgreif/ring/wiki/FFmpeg#homebridge-audio-support

**Comment by mkellsy** [comment]
I updated the Ring plugin.

**Comment by donavanbecker** [comment]
Thanks @mkellsy!!
