### ISSUE TITLE
innerError Error: Cannot find module '../build/Debug/pty.node' Require stack:

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/HOOBS#393]
**Description**
tried to upgrade the Node but got this 
**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
macOS Catalina
**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Sonos ZP
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
please see status report

hoobs@hoobs:~ $ hoobs status
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js
- /home/hoobs/.hoobs/node_modules/node-pty/lib/index.js
- /home/hoobs/.hoobs/lib/api.js
- /home/hoobs/.hoobs/lib/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js',
    '/home/hoobs/.hoobs/node_modules/node-pty/lib/index.js',
    '/home/hoobs/.hoobs/lib/api.js',
    '/home/hoobs/.hoobs/lib/cli.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
  ]
}
(node:2488) UnhandledPromiseRejectionWarning: Error: The module '/home/hoobs/.hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
(node:2488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
hoobs@hoobs:~ $

**Comment by OfficialKaos** [comment]
I Used this to upgrade

wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/upgrade-node.sh | sudo bash -

**Comment by OfficialKaos** [comment]
Should of been more specific tried to upgrade the Node to 12.14.0 (recommended by Sonos ZP plugin) But Homebridge woudn't start as reported above.
used 
get -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/clean.sh | sudo bash -

to get 10.17.0 and now all working 
but still need to upgrade the Node at some point

**Comment by mkellsy** [comment]
It looks like you had node 12 on this device before. I need to find out a way to remove old builds.

**Comment by OfficialKaos** [comment]
What if I do a fresh install?

**Comment by mkellsy** [comment]
that would always work. Next time make a backup before you change Node versions. So you can restore the plugins in one step.

**Comment by OfficialKaos** [comment]
I only have 1 plugin on each HOOBS so I'm just backing up the config.
fresh install had Node 12.3.1 the upgrade to 12.4.0 went well this time

**Comment by d0n4v4nb3ck3r** [comment]
Same thing happened to me when I tried updating node

**Comment by d0n4v4nb3ck3r** [comment]
> I only have 1 plugin on each HOOBS so I'm just backing up the config.
> fresh install had Node 12.3.1 the upgrade to 12.4.0 went well this time
> 

Which .img file did you use to get 12.3.1?

**Comment by mkellsy** [comment]
When you upgrade node you need to uninstall hoobs and reinstall.

```
sudo npm uninstall -g @hoobs/hoobs
```
Then
```
sudo npm Install -g --unsafe-perm @hoobs/hoobs
```
This will trigger a node-pty rebuild.

**Comment by OfficialKaos** [comment]
Sorry for late reply I only just see this
> > I only have 1 plugin on each HOOBS so I'm just backing up the config.
> > fresh install had Node 12.3.1 the upgrade to 12.4.0 went well this time
> 
> Which .img file did you use to get 12.3.1?

HOOBS to Download (Buster) v3.1.1 – Release Date 2019-12-03

**Comment by OfficialKaos** [comment]
Sorry for late reply I only just see this
> > I only have 1 plugin on each HOOBS so I'm just backing up the config.
> > fresh install had Node 12.3.1 the upgrade to 12.4.0 went well this time
> 
> Which .img file did you use to get 12.3.1?

HOOBS to Download (Buster) v3.1.1 – Release Date 2019-12-03

**Comment by OfficialKaos** [comment]
> When you upgrade node you need to uninstall hoobs and reinstall.
> 
> ```
> sudo npm uninstall -g @hoobs/hoobs
> ```
> 
> Then
> 
> ```
> sudo npm Install -g --unsafe-perm @hoobs/hoobs
> ```
> 
> This will trigger a node-pty rebuild.

What Node will be installed? What if a specific Node is required?

**Comment by mkellsy** [comment]
No. It's just the npm install commands. It re-triggers a build.
and it is
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```
with a lower case i, it was a typo.
