### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by shayfunk** [hoobs-org/HOOBS#395]
I bought the download for raspberry pi and can’t seem to get it going. I have an orbi mesh and have it plugged into the main router via Ethernet cable. When I access the dashboard through hoobs.local/ the homebridge service is not running. Says hoobs is stopped. When I try to start service nothing happened. I noticed the following in the log...
ECONNREFUSED 127.0.0.1:51826
[Homebridge] error: unknown option ‘-S’

The first ‘ above isn’t actually ‘
It looks like an accent grave from French which I don’t currently have on my keyboard. Sorry if this doesn’t make any sense.

I logged into my router and it has Hoobs assigned as a connected device. I can see hoobs in the HomeKit app in hubs. I’m not sure what’s wrong. Can you please point me in the right direction?

I’ve gone through the “help” steps from the menu and things are getting worse. I can’t even scan the QR code anymore to add back to HomeKit. The log still shows the same issue above. Thanks.

**Comment by mkellsy** [comment]
This is an issue with the prep for 3.1.17. I am currently testing it. It should be released soon tonight.

**Comment by shayfunk** [comment]
No worries. Thank you for following up. I was able to use the older version with no issues. It’s so fast!
