### ISSUE TITLE
HOOBS service won't run, Error, Econnrefused

### ISSUE THREAD

**Issue by agentjam** [hoobs-org/HOOBS#396]
Hello - I had my Nest thermostat on Hoobs working fine until the last day or so, now the service will not stay running for longer than a few seconds.  When I look at the Log this is what I see:

[1/2/2020, 21:03:53] HOOBS listning on port 8080.
[Homebridge] error: unknown option `-S'
[Homebridge] error: unknown option `-S'
[Homebridge] error: unknown option `-S'
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826

I tried updating the HOOBS to Version 3.1.15, and also the Homebridge-Nest Plugin to version 3.5.2 published 12/16/2019.  Still the same thing.

I also tried factory reset of the HOOBS...same thing.

Any ideas of what this means and how I can resolve it?  I paid $150 for HOOBS since I am a beginner in this space, now I feel like I work for the company trying to resolve the issue...

Thank you to anyone who can help me resolve this.

**Comment by BobbySlope** [comment]
Please update to latest version 3.1.17. 
issue was fixed within this release
