### ISSUE TITLE
After updating to 3.1.15, Homebridge will not start and gives two errors

### ISSUE THREAD

**Issue by Spyromaniac31** [hoobs-org/HOOBS#397]
**Description**
After updating to version 3.1.15 of HOOBS, HOOBS is stopped. Rebooting or clicking Start Service gives the error
> [Homebridge] error: unknown option `-S'

If I go to the dashboard, I get the error

> [List Accessories] connect ECONNREFUSED 127.0.0.1:51826

And occasionally the same error with [List Rooms]

**Version**
3.1.15

**Did you upgrade**
Yes

**Previous version**
3.1.12

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Not sure what version I was on when I upgraded to HOOBS 3, but I have been using HOOBS 3 successfully before now.

**What device are you using?**
A Raspberry Pi Zero W with the HOOBS bootable image on its SD card

**If this is a custom install, what's your operating system?**
N/A

**List your plugins**
myQ2
Tplink Smarthome
Tuya Web
Smartglass

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYE0L5",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "87106"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [
        {
            "accessory": "Smartglass",
            "name": "Xbox One",
            "liveid": "****************",
            "consoleip": "192.168.0.36"
        }
    ],
    "platforms": [
        {
            "platform": "MyQ2",
            "email": "jimmy@jpontzer.net",
            "password": "**************"
        },
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome"
        },
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "henry@jpontzer.net",
                "password": "********",
                "countryCode": "1",
                "platform": "tuya"
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[1/3/2020, 9:30:48 AM] HOOBS listning on port 8080.
[Homebridge] error: unknown option `-S'
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[Homebridge] error: unknown option `-S'
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
```

**Additional context**

**Comment by mkellsy** [comment]
Please update to 3.1.17.

**Comment by Spyromaniac31** [comment]
Is there a way to do this in the terminal? I can't update through the interface because HOOBS isn't running

**Comment by mkellsy** [comment]
Here you go
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash -
```

**Comment by Spyromaniac31** [comment]
Thank you, this fixed it!
