### ISSUE TITLE
New Plugin request: Amazon Smart Plug

### ISSUE THREAD

**Issue by gleeglee217** [hoobs-org/HOOBS#399]
I have some Amazon smart plugs that I would like to use with Homebridge/HOOBS but there is not a plugin yet, it seems. I would also like to help as well, but I have no knowledge of programming/developing of Homebridge stuff only had a course in C++.

> Edited for clarity

**Comment by mkellsy** [comment]
We will look into this, thanks for asking us.

**Comment by mdelag** [comment]
That would be great. +1

**Comment by BobbySlope** [comment]
not in current task list, we aren't focused on developing plugins

**Comment by pyaethar** [comment]
anyone know how to add broadlink smart plug to homebridge?
