### ISSUE TITLE
HomeConnect Plugin Cannot Be Updated via HOOBS

### ISSUE THREAD

**Issue by JerGitHub** [hoobs-org/HOOBS#403]
**Description**
HomeConnect plugin cannot be updated via HOOBS UI. HOOBS shows update is available (which is correct) but does not show the correct new version of the plugin and cannot be updated via HOOBS. This has been happening for the past few versions of HOOBS and the past few updates of the HomeConnect plugin. Clicking update looks like it is updating but the plugin never updates.

Example in screenshot - the current version of the plugin is 0.10.0. An update is available but is showing the version I currently have installed instead 0.9.1. 

In order to update via HOOBS UI, I need to uninstall the current HomeConnect plugin and then install the new HomeConnect plugin. 

**Expected behavior**
Expected to be able to see correct updated plugin version in the HOOBS UI and then update the plugin via HOOBS UI. 

**Plugin name**
homebridge-homeconnect
https://github.com/thoukydides/homebridge-homeconnect

**Please report the issue to the plugin developer**
Plugin works fine - this looks to be a HOOBS plugin update issue. 

**Version**
Has been happening for the past few version of HOOBS. I'm on v3.1.17 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X ] No - Installed on v3.1.x code train. Have only updated minor versions ie. v3.1.15 to v3.1.17

**Pervious version**
See above

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
macOS Catalina 10.15.2

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

config.json is not applicable for this issue

**Post your log**
You can get the log from the intercafe. This is in the Log section.

> npm
>  notice created a lockfile as package-lock.json. You should commit this file.
> homebridge-homeconnect@0.9.1
> updated 1 package and audited 1094 packages in 4.207s
> 15 packages are looking for funding
>   run `npm fund` for details
> found 0 vulnerabilities
> [1/4/2020, 3:11:19 PM] "homebridge-homeconnect" package updated.

<img width="463" alt="Screen Shot 2020-01-04 at 2 57 15 PM" src="https://user-images.githubusercontent.com/16343534/71771154-d64d8280-2f04-11ea-8005-7f955a79161a.png">

**Comment by mkellsy** [comment]
NPM is not picking up the new version on install. I am looking into this.

**Comment by mkellsy** [comment]
This is fixed in 3.1.19

**Workaround**
Run this in the Terminal
```
cd ~/.hoobs && npm install homebridge-homeconnect@0.10.1
```

Then Restart the Service

**Comment by JerGitHub** [comment]
great! thanks! I'll try updating from 0.10.0 (which I installed just before he released 0.10.1 about 20 minutes ago - ha!) to 0.10.1 or a higher version of the plugin if available once 3.1.19 comes out.

Thanks!

**Comment by JerGitHub** [comment]
Just updated HOOBS to 3.1.19 and then updated to latest HomeConnect plugin 0.12.0 and it worked! Thanks for the quick fix.

Also - I like the new push notifications - nice touch!

<img width="1362" alt="Screen Shot 2020-01-05 at 9 16 46 PM" src="https://user-images.githubusercontent.com/16343534/71790981-43464280-3001-11ea-8fc5-2872df41d89e.png">
