### ISSUE TITLE
3.1.17 unknown option '-U'

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/HOOBS#405]
**Description**

HOOBS only runs with ssh terminal open after 3.1.17 update

after the update i only see the starting sequence 

I ssh and type > hoobs status
this then gets it running, but then back to starting sequence when terminal closed

happening on 3 out of 6 bridges

**Comment by mkellsy** [comment]
Run this command
```
sudo hoobs service start
```

**Comment by OfficialKaos** [comment]
It hasn't worked

**Comment by OfficialKaos** [comment]
typing > hoobs status 
gets it running and accessible through the UI and it stays running unless I close the terminal

**Comment by OfficialKaos** [comment]
Now 5 out of 6 bridges have this issue on 3.1.17
please help

**Comment by OfficialKaos** [comment]
This might be my network !
I changed the dns servers 3 days ago , so if no one else is having this issue it’s probably that . I’ll investigate later this evening and report back.

**Comment by mkellsy** [comment]
Typing this
```
hoobs status
```
Is the same as typing this
```
hoobs
```
That is the command to run HOOBS in the terminal.

What happens when you reboot the device
```
sudo reboot
```
Does the UI show? Then it is OK to close the terminal
If not run this command
```
sudo hoobs service start
```

**Comment by mkellsy** [comment]
Another thing you can try is this.
```
sudo hoobs switch hoobs
```

You may have a stuck service.

**Comment by OfficialKaos** [comment]
The only thing that works is typing hoobs through ssh and keeping the terminal open

**Comment by mkellsy** [comment]
can you run this command and post the results
```
ls -la /etc/systemd/system
```
And the run this and post the results
```
ls -la /etc/systemd/system/multi-user.target.wants
```

**Comment by OfficialKaos** [comment]
hoobs@hoobs:~/.hoobs/etc $ ls -la /etc/systemd/system
total 88
drwxr-xr-x 16 root root 4096 Dec 22 22:00 .
drwxr-xr-x  5 root root 4096 Jul 23 02:36 ..
-rw-r--r--  1 root root 1551 Jun 25  2019 autologin@.service
drwxr-xr-x  2 root root 4096 Jul 23 02:56 bluetooth.target.wants
lrwxrwxrwx  1 root root   42 Jul 23 02:58 dbus-fi.w1.wpa_supplicant1.service -> /lib/systemd/system/wpa_supplicant.service
lrwxrwxrwx  1 root root   37 Jul 23 02:56 dbus-org.bluez.service -> /lib/systemd/system/bluetooth.service
lrwxrwxrwx  1 root root   40 Jul 23 02:57 dbus-org.freedesktop.Avahi.service -> /lib/systemd/system/avahi-daemon.service
lrwxrwxrwx  1 root root   40 Jul 23 03:01 dbus-org.freedesktop.ModemManager1.service -> /lib/systemd/system/ModemManager.service
lrwxrwxrwx  1 root root   53 Jul 23 03:01 dbus-org.freedesktop.nm-dispatcher.service -> /lib/systemd/system/NetworkManager-dispatcher.service
lrwxrwxrwx  1 root root   45 Jul 23 02:36 dbus-org.freedesktop.timesync1.service -> /lib/systemd/system/systemd-timesyncd.service
drwxr-xr-x  2 root root 4096 Jul 23 02:58 dhcpcd.service.d
drwxr-xr-x  2 root root 4096 Jul 23 02:36 getty.target.wants
drwxr-xr-x  2 root root 4096 Jul 23 02:51 getty@tty1.service.d
drwxr-xr-x  2 root root 4096 Jul 23 02:55 halt.target.wants
-rw-r--r--  1 root root  207 Jul 23 03:00 hoobs-arch-check.service
-rwxr-xr-x  1 root root  234 Dec 22 22:00 hoobs.service
drwxr-xr-x  2 root root 4096 Dec 22 22:00 multi-user.target.wants
drwxr-xr-x  2 root root 4096 Jul 23 03:01 network-online.target.wants
drwxr-xr-x  2 root root 4096 Jul 23 02:55 poweroff.target.wants
drwxr-xr-x  2 root root 4096 Jul 23 02:58 rc-local.service.d
drwxr-xr-x  2 root root 4096 Jul 23 02:55 reboot.target.wants
drwxr-xr-x  2 root root 4096 Jul 23 02:56 remote-fs.target.wants
drwxr-xr-x  2 root root 4096 Jul 23 02:58 sockets.target.wants
-rw-r--r--  1 root root  264 Jul 23 03:02 ssdpd.service
lrwxrwxrwx  1 root root   31 Jul 23 02:57 sshd.service -> /lib/systemd/system/ssh.service
drwxr-xr-x  2 root root 4096 Jul 23 02:57 sysinit.target.wants
lrwxrwxrwx  1 root root   35 Jul 23 02:40 syslog.service -> /lib/systemd/system/rsyslog.service
drwxr-xr-x  2 root root 4096 Jul 23 02:40 timers.target.wants
-rw-r--r--  1 root root  159 Jul 23 03:01 tzupdate.service
-rw-r--r--  1 root root  273 Jul 23 03:01 wifi-connect.service
hoobs@hoobs:~/.hoobs/etc $ ls -la /etc/systemd/system/multi-user.target.wants
total 8
drwxr-xr-x  2 root root 4096 Dec 22 22:00 .
drwxr-xr-x 16 root root 4096 Dec 22 22:00 ..
lrwxrwxrwx  1 root root   40 Jul 23 02:57 avahi-daemon.service -> /lib/systemd/system/avahi-daemon.service
lrwxrwxrwx  1 root root   41 Jul 23 02:57 console-setup.service -> /lib/systemd/system/console-setup.service
lrwxrwxrwx  1 root root   32 Jul 23 02:40 cron.service -> /lib/systemd/system/cron.service
lrwxrwxrwx  1 root root   42 Jul 23 02:57 dphys-swapfile.service -> /lib/systemd/system/dphys-swapfile.service
lrwxrwxrwx  1 root root   35 Jul 23 02:57 hciuart.service -> /lib/systemd/system/hciuart.service
lrwxrwxrwx  1 root root   44 Jul 23 03:00 hoobs-arch-check.service -> /etc/systemd/system/hoobs-arch-check.service
lrwxrwxrwx  1 root root   33 Dec 22 22:00 hoobs.service -> /etc/systemd/system/hoobs.service
lrwxrwxrwx  1 root root   40 Jul 23 03:01 ModemManager.service -> /lib/systemd/system/ModemManager.service
lrwxrwxrwx  1 root root   38 Jul 23 02:40 networking.service -> /lib/systemd/system/networking.service
lrwxrwxrwx  1 root root   42 Jul 23 03:01 NetworkManager.service -> /lib/systemd/system/NetworkManager.service
lrwxrwxrwx  1 root root   37 Jul 23 02:56 nfs-client.target -> /lib/systemd/system/nfs-client.target
lrwxrwxrwx  1 root root   33 Jul 23 03:01 nginx.service -> /lib/systemd/system/nginx.service
lrwxrwxrwx  1 root root   36 Jul 23 03:01 pppd-dns.service -> /lib/systemd/system/pppd-dns.service
lrwxrwxrwx  1 root root   48 Jul 23 02:58 raspberrypi-net-mods.service -> /lib/systemd/system/raspberrypi-net-mods.service
lrwxrwxrwx  1 root root   36 Jul 23 02:36 remote-fs.target -> /lib/systemd/system/remote-fs.target
lrwxrwxrwx  1 root root   33 Jul 23 02:56 rsync.service -> /lib/systemd/system/rsync.service
lrwxrwxrwx  1 root root   35 Jul 23 02:40 rsyslog.service -> /lib/systemd/system/rsyslog.service
lrwxrwxrwx  1 root root   33 Jul 23 03:02 ssdpd.service -> /etc/systemd/system/ssdpd.service
lrwxrwxrwx  1 root root   31 Jul 23 02:57 ssh.service -> /lib/systemd/system/ssh.service
lrwxrwxrwx  1 root root   37 Jul 23 02:55 sshswitch.service -> /lib/systemd/system/sshswitch.service
lrwxrwxrwx  1 root root   40 Jul 23 02:51 triggerhappy.service -> /lib/systemd/system/triggerhappy.service
lrwxrwxrwx  1 root root   36 Jul 23 03:02 tzupdate.service -> /etc/systemd/system/tzupdate.service
lrwxrwxrwx  1 root root   47 Jul 23 03:00 unattended-upgrades.service -> /lib/systemd/system/unattended-upgrades.service
lrwxrwxrwx  1 root root   40 Jul 23 03:01 wifi-connect.service -> /etc/systemd/system/wifi-connect.service
lrwxrwxrwx  1 root root   42 Jul 23 02:58 wpa_supplicant.service -> /lib/systemd/system/wpa_supplicant.service
hoobs@hoobs:~/.hoobs/etc $

**Comment by mkellsy** [comment]
The hoobs service is set to start. Can you run this command and post the results.
```
sudo hoobs service log
```
> You will need to ctrl+c to exit.

**Comment by OfficialKaos** [comment]
hoobs@hoobs:~ $ sudo hoobs service log
hoobs.service: Scheduled restart job, restart counter is at 2724.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2725.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2726.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2727.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2728.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2729.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2730.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2731.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2732.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2733.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2734.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2735.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2736.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2737.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2738.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2739.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2740.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2741.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2742.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2743.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2744.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2745.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2746.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2747.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2748.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2749.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2750.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2751.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2752.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2753.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2754.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2755.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2756.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2757.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2758.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2759.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2760.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2761.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2762.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2763.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2764.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2765.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2766.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2767.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2768.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2769.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2770.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2771.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2772.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2773.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2774.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2775.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2776.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2777.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2778.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2779.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2780.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2781.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2782.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2783.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2784.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2785.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2786.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2787.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2788.
Stopped HOOBS.
Started HOOBS.
- Enviornment
error: unknown option '-U'
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
h

**Comment by mkellsy** [comment]
3.1.19 fixes this issue. Run this.
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash -
```

**Comment by OfficialKaos** [comment]
It worked thank you so much
