### ISSUE TITLE
updated from 3.1.1 to 3.1.19

### ISSUE THREAD

**Issue by stephenmd** [hoobs-org/HOOBS#406]
i updated from 3.1.1 where my hoobs setup was functioning with no problem to 3.1.19 and now i cant even open the log in page.

**Comment by mkellsy** [comment]
@stephenmd  Can you use issue templates. There is not enough information for me to troubleshoot.

**Comment by mkellsy** [comment]
Can you run this from a SSH terminal
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash -
```
and post the output.

**Comment by stephenmd** [comment]
I can go ahead and try when j get back home in a while... but how will I connect to the hoobs setup if I can’t even open hoobs anymore? I try to access it via it’s ip and nothing happened just says it’s unavailable & this occurred by me pressing check for update and then updating to 3.1.19

**Comment by mkellsy** [comment]
SSH

**Comment by stephenmd** [comment]
can cancel this as i reflashed with latest and used my backup to restore
