### ISSUE TITLE
Cant update Hoobs from 3.1.15 to 3.1.19

### ISSUE THREAD

**Issue by monza258** [hoobs-org/HOOBS#407]
Hello Guys, I will update from 3.1.15 to 3.1.19 but it dosn't work. 

**Version**
3.1.15

**List your plugins**
camera-ui
http-webhooks
eveatmo (also can't update)
Raspberrypi Info

Is there anyway to update Hoobs manuell by Terminal?

**Comment by mkellsy** [comment]
What happens? Is it still on the old version? Or does it not start?

Upgrading from the terminal is the same as install.
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash -
```

Can you post the output?

**Comment by monza258** [comment]
After click on update button it doesn't update itself.

**Comment by BobbySlope** [comment]
Can you right click in your browser, click on Inspect and then go to the Console tab. Then click on the update button and see if any error appears in the browser console and paste it here. 

Cheers,
Ovi @ hoobs.org

**Comment by monza258** [comment]
Hey Bobby, it’s done. I have use the Upgrading in Terminal which Michael have told me. Now I am on Version 3.1.19.
