### ISSUE TITLE
Local issuer certificate

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#408]
**Description**
SD card customer has a separate network for IoT and allowed internet connection via macadress but get the following error:

Jan  7 20:22:18 hoobs hoobs[574]: [1/7/2020, 8:22:18 PM] Unhandled Rejection "Error: unable to get local issuer certificate".
Jan  7 20:22:18 hoobs hoobs[574]: (node:574) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 12)
Jan  7 20:22:18 hoobs hoobs[574]: [1/7/2020, 8:22:18 PM] Cannot read property 'objects' of undefined
Jan  7 20:22:18 hoobs hoobs[574]: TypeError: Cannot read property 'objects' of undefined
Jan  7 20:22:18 hoobs hoobs[574]:     at Request [as _callback] (/home/hoobs/.hoobs/lib/plugins.js:363:41)
Jan  7 20:22:18 hoobs hoobs[574]:     at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
Jan  7 20:22:18 hoobs hoobs[574]:     at Request.emit (events.js:189:13)
Jan  7 20:22:18 hoobs hoobs[574]:     at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:881:8)
Jan  7 20:22:18 hoobs hoobs[574]:     at ClientRequest.emit (events.js:189:13)
Jan  7 20:22:18 hoobs hoobs[574]:     at TLSSocket.socketErrorListener (_http_client.js:392:9)
Jan  7 20:22:18 hoobs hoobs[574]:     at TLSSocket.emit (events.js:189:13)
Jan  7 20:22:18 hoobs hoobs[574]:     at emitErrorNT (internal/streams/destroy.js:82:8)
Jan  7 20:22:18 hoobs hoobs[574]:     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
Jan  7 20:22:18 hoobs hoobs[574]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jan  7 20:22:18 hoobs hoobs[574]: [Homebridge] [1/7/2020, 8:22:18 PM] Got SIGINT, shutting down service…

**Did you upgrade**
- [X] Yes because of stuck on yellow screen following this:

https://hoobs.org/knowledge-base/stuck-on-yellow-hoobs-screen/

- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card

**Comment by mkellsy** [comment]
This is because it can't reach "https://registry.npmjs.org". HOOBS needs an internet connection.

**Comment by BobbySlope** [comment]
User solved by reflashing newest version from github.

**Comment by mkellsy** [comment]
If that's the case, the testing reset script was not ran.
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset
```

I let the team know.
