### ISSUE TITLE
Hoobs Homematic-Plugin

### ISSUE THREAD

**Issue by Ron0815** [hoobs-org/HOOBS#413]
Hello, I have been using Hoobs 3.1.20 on a RaspPi 3 B + for about 2 weeks. I installed the Homematic plugin for my Homematic devices. Unfortunately, the switching status of the roller shutter actuators is not displayed correctly. The shutters are shown as open, although they are already closed or only open to X%. What can I do to make it work correctly?
Best regards
Ron0815

**Comment by MikeDeltaHH** [comment]
Interesting... when i try to configure the homematic plugin my hoobs installation has very slow responding  the moment i saved it - after that all my devices are offline in homekit and the hoobs webgui takes minutes for a respond when i´m select any menu options so i have an extra homebridge installation for this plugin! You don´t have such problems?!

**Comment by Ron0815** [comment]
No, my devices remain online, but the status is not actual.

**Comment by Ron0815** [comment]
I think I‘ll install a completly new setup, including raspbian and homebridge, without using Hoobs.

**Comment by rpolenthon** [comment]
The issue with homematic is known. Take a look at the issues on the homematic plugin page. I also opened an issue about wrong device statuses some months ago. In my case, they reset sometimes or should I even say the reset very often...

I wasn't able to fix it, the dev also wasn't able to provide updates.

The issue has nothing to do with HOOBS. I have the issue way longer than HOOBS exists.

You could open or reply to issues directly on the homematic github page, so the developer gets reminded that the issue still exists.

**Comment by MikeDeltaHH** [comment]
I have also an issue with the homematic windows/doors sensors about a year and no reaction or a new version from the developer...

**Comment by MathiasDiessner** [comment]
Im a bit new to this: how do I start the service HomematicIP in hoobs after I installed it. I've put the ID of the accespoint in, but nothing happens. Is there a thing I need to do to start it manually? m8383@mail(dot)de

**Comment by EddieDSuza** [comment]
> Im a bit new to this: how do I start the service HomematicIP in hoobs after I installed it. I've put the ID of the accespoint in, but nothing happens. Is there a thing I need to do to start it manually? m8383@mail(dot)de

Responded [here](https://github.com/hoobs-org/HOOBS/issues/1043#issuecomment-765734142)
