### ISSUE TITLE
tp-link plugin is crashing

### ISSUE THREAD

**Issue by wtdeane** [hoobs-org/HOOBS#417]
**Description**
I installed the latest tp-link plugin update.  After it ran, Hobbs starts, but immediately stops running. 

**Version**

Current Version: 3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**

Nest
3.5.2 published 12/16/2019

Tplink Smarthome
5.0.0 published 1/9/2020 • 5 hours ago

Twinkly
0.2.1 published 12/22/2019

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYIHGP",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "CA",
        "postal_code": "xxxxx",
        "latitude": "xxxxxxxx0",
        "longitude": "-79.247020"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "A1:3C:19:13:1A:6C"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Twinkly",
            "name": "Left Window Lights",
            "ip": "192.168.0.16",
            "allowBrightnessControl": true,
            "plugin_map": {
                "plugin_name": "homebridge-twinkly",
                "index": 0
            }
        },
        {
            "accessory": "Twinkly",
            "name": "Right Window Lights",
            "ip": "192.168.0.14",
            "allowBrightnessControl": true,
            "plugin_map": {
                "plugin_name": "homebridge-twinkly",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "nest"
            },
            "email": "xxxxxxx",
            "password": "xxxxxxx",
            "googleAuth": {}
        },
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome",
            "broadcast": "192.168.0.255",
            "addCustomCharacteristics": true,
            "inUseThreshold": 0,
            "switchModels": [
                "HS300",
                "HS110"
            ],
            "timeout": 15,
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        }
    ]
}

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE (I don’t know where that is. 
```

**Additional context**
Removing to link plugin will see jobs start and continue running. Reinstalling causes failure.

**Comment by mkellsy** [comment]
Can you post your log.

**Comment by wtdeane** [comment]
I don’t know how to access the logs.

**Comment by mkellsy** [comment]
So you can't see the interface? What do you see?

**Comment by wtdeane** [comment]
I have the hoobs interface.  Can’t see where to get logs from.

**Comment by wtdeane** [comment]
[logs.txt](https://github.com/hoobs-org/HOOBS/files/4043752/logs.txt)

**Comment by wtdeane** [comment]
This was under backup.  I hope those are the logs you were looking for.

**Comment by mkellsy** [comment]
They will work.

**Comment by mkellsy** [comment]
There is a log screen too. In the nav on the left.  
https://github.com/hoobs-org/HOOBS/wiki/3.5-Log

**Comment by wtdeane** [comment]
<facepalm> My goodness, I’m showing off how new I am.  Thanks for the guidance.

**Comment by mkellsy** [comment]
This is an issue with the new version of that plugin. Someone already opened an issue for the plugin developer.  
https://github.com/plasticrake/homebridge-tplink-smarthome/issues/108

**Comment by askovi** [comment]
In addition to your tplink issue, I also notice you're having login issues with Nest. Google recently added recaptcha to the login request, we haven't been able to fix that yet. For now you will have to start using access_token value instead of username and password. See details here: https://github.com/chrisjshull/homebridge-nest/issues/195

**Comment by wtdeane** [comment]
> This is an issue with the new version of that plugin. Someone already opened an issue for the plugin developer.
> [plasticrake/homebridge-tplink-smarthome#108](https://github.com/plasticrake/homebridge-tplink-smarthome/issues/108)

Thank you. Is there a way to downgrade the plug-in via the hoobs interface (as I’m not a terminal guy), or should I just wait?

Thanks for your help!

**Comment by wtdeane** [comment]
> In addition to your tplink issue, I also notice you're having login issues with Nest. Google recently added recaptcha to the login request, we haven't been able to fix that yet. For now you will have to start using access_token value instead of username and password. See details here: [chrisjshull/homebridge-nest#195](https://github.com/chrisjshull/homebridge-nest/issues/195)

Thank you!  I noticed that too when looking through the logs.  I’ll look at the link you provided and see if I can do what’s needed without moving my nest account to a google account. 

Thanks again!

**Comment by mkellsy** [comment]
To downgrade a plugin requires terminal access. If you are not comfortable with that, I would wait.

But you can with these commands.
In HOOBS click Menu (upper right) -> Terminal -  https://github.com/hoobs-org/HOOBS/wiki/3.6-System

Then run these commands in order (exactly as typed).
```
cd ../
```
then
```
npm install homebridge-tplink-smarthome@4.0.1
```

After those finish click Menu -> Restart Service.

**Comment by askovi** [comment]
> > This is an issue with the new version of that plugin. Someone already opened an issue for the plugin developer.
> > [plasticrake/homebridge-tplink-smarthome#108](https://github.com/plasticrake/homebridge-tplink-smarthome/issues/108)
> 
> Thank you. Is there a way to downgrade the plug-in via the hoobs interface (as I’m not a terminal guy), or should I just wait?
> 
> Thanks for your help!

You can add this to your config file: 
"switchModels": [
                "HS200",
                "HS100",
                "HS105"
            ],

inside your  Tplink platform like this: {
      "platform" : "TplinkSmarthome",
      "name" : "TplinkSmarthome",
     "switchModels": [
                "HS200",
                "HS100",
                "HS105"
            ],
    }

**Comment by wtdeane** [comment]
But I don’t have model of switches.

**Comment by askovi** [comment]
> > In addition to your tplink issue, I also notice you're having login issues with Nest. Google recently added recaptcha to the login request, we haven't been able to fix that yet. For now you will have to start using access_token value instead of username and password. See details here: [chrisjshull/homebridge-nest#195](https://github.com/chrisjshull/homebridge-nest/issues/195)
> 
> Thank you! I noticed that too when looking through the logs. I’ll look at the link you provided and see if I can do what’s needed without moving my nest account to a google account.
> 
> Thanks again!

You can do it without migrating, you have to grab the access_token from your browser after logging in on nest.com. 
In chrome, just right click, click inspect then go to the Network tab, click on XHR then refresh the page and look for a file called 'session...' click on it and look on the right for the "access_token" value.

**Comment by mkellsy** [comment]
For you it would be this. I think it changes something in the plugin code.
```
"switchModels": [
    "HS200",
    "HS100",
    "HS105",
    "HS300",
    "HS110"
],
```
I would ask the plugin developer, here.  
https://github.com/plasticrake/homebridge-tplink-smarthome/issues/108

**Comment by askovi** [comment]
> But I don’t have model of switches.

You have to add the models you're actually using. You can look them up in the Kasa app, by clicking on the device then device settings and then Device info. It will show you the model. List all your models in that array.

**Comment by wtdeane** [comment]
I’ve always had my models listed in the config file though.

**Comment by askovi** [comment]
I see that in your config you got: 
"HS300",
"HS110",

But do you have any others installed that are not listed?

**Comment by askovi** [comment]
The TP-Link plugin has always worked great out of the box but it seems like the developer released an update about 6 hours ago that broke some things.

**Comment by wtdeane** [comment]
> I see that in your config you got:
> "HS300",
> "HS110",
> 
> But do you have any others installed that are not listed?

No.  Just those two models.

**Comment by askovi** [comment]
try listing them all, might fix the issue:
"switchModels": [
    "HS200",
    "HS100",
    "HS105",
    "HS300",
    "HS110"
],

**Comment by wtdeane** [comment]
> try listing them all, might fix the issue:
> "switchModels": [
> "HS200",
> "HS100",
> "HS105",
> "HS300",
> "HS110"
> ],

That didn’t work.   :(

**Comment by mkellsy** [comment]
Please comment in this issue

https://github.com/plasticrake/homebridge-tplink-smarthome/issues/108

So you get updates when this gets fixed. The TPLink plugin developer needs to fix this issue. You are not the only one.

**Comment by mkellsy** [comment]
The new version of this plugin has been pulled. If you backup your config. You can uninstall the TPLink SmartHome plugin. Then reinstall it and put your config back.
