### ISSUE TITLE
Start/Stop/Restart buttons on the dashboard

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#420]
**Is your feature request related to a problem? Please describe.**
Sometimes the HOOBS Service is stopped and does not restart on its own for various reasons. This can get confusing for some users to manually start the service from the top right menu. 

**Describe the solution you'd like**
Having an additional 'Control' tile to control the service status on the dashboard will make it more obvious.

**Comment by mkellsy** [comment]
In HOOBS Desktop this is part of the Manage Devices screen.
