### ISSUE TITLE
Hoobs versions out of sync

### ISSUE THREAD

**Issue by shayfunk** [hoobs-org/HOOBS#423]
**Description**
A clear and concise description of what the plugin is doing.
Ver 3.1.20 in Hoobs dashboard and 3.1.18 from Home app

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version. 3.1.18

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina. Linux on raspberry pi

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": ""
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        },
        {
            "platform": "tcc",
            "name": "Thermostat",
            "username": "",
            "password": "",
            "devices": [
                {
                    "deviceID": "",
                    "name": "THERMOSTATDOWN",
                    "usePermanentHolds": true
                },
                {
                    "deviceID": "",
                    "name": "THERMOSTATUP",
                    "usePermanentHolds": true
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-tcc"
            }
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Wyze",
                    "videoConfig": {
                        "source": "",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 15
                    }
                }
            ]
        }
    ]
}

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Where are you seeing the HOOBS version in the Home app? We don't push the version to that.

**Comment by shayfunk** [comment]
I really think I messed up the upgrade though. I don’t know how I missed your documentation. It’s very well written. Definitely screwed up the “be patient” bit. Ever since I tried to upgrade the non native HomeKit devices are constantly disconnecting & reconnecting. Should I just start over and if so delete Home data too? Ugh...sorry :-(

**Comment by mkellsy** [comment]
The easiest thing to do is download the Raspberry Pi image from here https://github.com/hoobs-org/HOOBS/releases/tag/v3.1.20 and flash with the balinaEtcher.

It's a ready to go image for your Raspberry Pi.

**Comment by shayfunk** [comment]
Gotcha...thank you!!!

**Comment by rpolenthon** [comment]
![594E29DA-7777-430C-A2EA-609F2108FBEC](https://user-images.githubusercontent.com/46066477/72234989-044f5880-35d0-11ea-80aa-d46589139417.png)

Double checked it. The version displayed for the bridge in HomeKit is wrong.

HomeKit: 3.1.18
Real Version: 3.1.20

**Comment by mkellsy** [comment]
That's the version of the bridge software (custom Homebridge) we use under the hood it is at version 3.1.18. This will not be in sync they are on different release cycles.

https://www.npmjs.com/package/@hoobs/homebridge

@hoobs/hoobs = 3.1.20
@hoobs/homebridge = 3.1.18

**Comment by shayfunk** [comment]
A-ha...thank you sm!!!

**Comment by shayfunk** [comment]
Great...thanks!!! Do they let you guys sleep ever? Hopefully coffee is provided 😂

**Comment by mkellsy** [comment]
There is no they. HOOBS is just 4 guys who do this in their spare time.

**Comment by shayfunk** [comment]
Wow...well thanks for doing it.
