### ISSUE TITLE
Hoobs doesn´t show the new hue plugin version

### ISSUE THREAD

**Issue by MikeDeltaHH** [hoobs-org/HOOBS#424]
**Description**
I have installed version 0.11.46 and version 0.11.47 is out since yesterday but hoobs doesn´t regocnized this version

**Version**
3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Ubuntu 18.04.3 LTS

**List your plugins**
https://github.com/ebaauw/homebridge-hue#readme

**Comment by mkellsy** [comment]
We test plugins before pushing the the certified version.

**Comment by MikeDeltaHH** [comment]
Ah ok, doesn´t realize that! :)
