### ISSUE TITLE
Hoobs in-a-box : Initialization screen is stuck 

### ISSUE THREAD

**Issue by takeitothegrill** [hoobs-org/HOOBS#426]
**Description**
I bought a Hoobs in-a-box. Followed all instructions.
Have not been able to progress to the admin-login from http://hoobs.local page as the initialization page is stuck / frozen: The white line underneath the Hoobs logo is moving back-and-forth... 
Waited for 24-hours now.

**Version**
V3
(assuming the Hoobs in-a-box I order in late December had the V3 installed....)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Additional context**
I am in Australia.
My WiFi network name contains special characters, and I understand that some devices don't like this. FYI the network name is "WiFi-3xxx-5G".

Have tried both Ethernet and WiFi set-ups.
Have tried Ethernet to main router and mesh router; likewise for WiFi.
I turned off power to Hoobs box each time the network connection method was changed. For example, inserted Ethernet cable first, then powered on box.

Thank you for looking at this...

**Comment by mkellsy** [comment]
This is a known issue with version 3.1.15. this is fixed in 3.1.17+

Here's how to fix. You will need to use SSH.
1. From a Mac
   ```
   ssh hoobs@hoobs.local
   ```
   Password: hoobsadmin

   On Windows you need to use [Putty](https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.73-installer.msi)

   Username: hoobs  
   Password: hoobsadmin

2. Then run this
   ```
   cd ~/
   ```

3. Then
   ```
   rm -fR ~/.hoobs
   ```

**Comment by askovi** [comment]
If you're not able to fix it yourself, please contact us at info@hoobs.org and we will help you via remote support.

**Comment by takeitothegrill** [comment]
Yes that fixed it.

Thank you!
