### ISSUE TITLE
Cannot update, stuck at 3.1.9. Plugins will not update.

### ISSUE THREAD

**Issue by greggsymington** [hoobs-org/HOOBS#427]
**Description**
Stuck at 3.1.9. Service crashes and restarts when attempting to update.

**Version**
3.1.9

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes (Attempted)
- [ ] No

**Pervious version**
N/A

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
No, Hoobs image.

**List your plugins**
homebridge-camera-ffmpeg
homebridge-ring
homebridge-tcc

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYM155",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "xxxxx",
        "latitude": "xxxxx",
        "longitude": "xxxxx"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This file is used for plugin configuration.",
    "plugins": [
        "homebridge-tcc",
        "homebridge-ring",
        "homebridge-camera-ffmpeg"
    ],
    "platforms": [
        {
            "platform": "tcc",
            "name": "Thermometer",
            "username": "email@gmail.com",
            "password": "pass",
            "devices": [
                {
                    "deviceID": "73020",
                    "name": "Dining Room",
                    "usePermanentHolds": true
                }
            ]
        },
        {
            "email": "email@gmail.com",
            "hideDoorbellSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "platform": "Ring",
            "refreshToken": "token"
        },
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Garage Exterior",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:pass@192.168.7.35:554/h264Preview_01_main",
                        "stillImageSource": "-i http://192.168.7.35:80/cgi-bin/api.cgi?cmd=Snap&channel=0&user=user&password=pass",
                        "maxStreams": 2,
                        "maxBitrate": 900,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "audio": false
                    }
                },
                {
                    "name": "Garage 2",
                    "videoConfig": {
                        "source": "-re -i http://192.168.7.123:8081",
                        "stillImageSource": "-f mjpeg -i http://user:pass@192.168.7.123:8765/picture/1/current/",
                        "maxStreams": 2,
                        "maxBitrate": 1000,
                        "maxWidth": 800,
                        "maxHeight": 480,
                        "maxFPS": 10,
                        "audio": false
                    }
                },
                {
                    "name": "Ender 3",
                    "videoConfig": {
                        "source": "-re -i http://192.168.7.99/webcam/?action=stream",
                        "maxStreams": 2,
                        "maxBitrate": 500,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 20,
                        "audio": false
                    }
                }
            ],
            "name": "Camera ffmpeg"
        }
    ],
    "package_manager": "npm",
    "system": "hoobs",
    "accessories": []
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
Not sure which log you are looking for here.
```

**Additional context**
Tried running through the commands in issue 394 (https://github.com/hoobs-org/HOOBS/issues/394) and found a orphaned plugin (homebridge-tplink-smarthome). I removed the reference to the plugin from the json but nothing has changed. I've attempted to remove the plugin via command line (npm uninstall -g homebridge-tplink-smarthome) but get the folllowing error 

"internal/modules/cjs/loader.js:250
    throw e;
    ^

SyntaxError: Error parsing /usr/local/lib/node_modules/npm/node_modules/number-is-nan/package.json: Unexpected token � in JSON at position 1
    at JSON.parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:239:25)
    at readPackageMain (internal/modules/cjs/loader.js:273:15)
    at tryPackage (internal/modules/cjs/loader.js:283:15)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/is-fullwidth-code-point/index.js:2:19) {
  path: '/usr/local/lib/node_modules/npm/node_modules/number-is-nan/package.json'
}"

**Comment by mkellsy** [comment]
Can you post your log.

**Comment by greggsymington** [comment]
Which log? Please reply which command you would like to run.

**Comment by mkellsy** [comment]
The log from the UI. The error you posted isn't complete. It is coming from a plug-in because HOOBS doesn't use the "number-is-nan" package.

If you can't access the UI you can get the log from SSH using this command.
```
sudo journalctl -o cat -n 500 -f -u hoobs
```
or this if the above doesn't work
```
sudo journalctl -o cat -n 500 -f -u homebridge
```

**Comment by greggsymington** [comment]
sudo journalctl -o cat -n 500 -f -u hoobs  has no result.


hoobs@hoobs:~ $ sudo journalctl -o cat -n 500 -f -u homebridge
Started Homebridge.
[1/15/2020, 20:55:46] HOOBS listning on port 8080.
[Homebridge] [1/15/2020, 20:55:47] Loaded config.json with 0 accessories and 3 platforms.
[Homebridge] [1/15/2020, 20:55:47] ---
[Homebridge] [1/15/2020, 20:55:51] Loaded plugin: homebridge-camera-ffmpeg
[Homebridge] [1/15/2020, 20:55:51] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[Homebridge] [1/15/2020, 20:55:51] ---
[Homebridge] [1/15/2020, 20:55:53] Loaded plugin: homebridge-ring
[Homebridge] [1/15/2020, 20:55:53] Registering platform 'homebridge-ring.Ring'
[Homebridge] [1/15/2020, 20:55:53] ---
[Homebridge] [1/15/2020, 20:55:53] Loaded plugin: homebridge-tcc
[Homebridge] [1/15/2020, 20:55:54] Registering platform 'homebridge-tcc.tcc'
[Homebridge] [1/15/2020, 20:55:54] ---
[Homebridge] [1/15/2020, 20:55:54] Loading 3 platforms...
[Homebridge] [1/15/2020, 20:55:54] [Thermometer] Initializing tcc platform...
[Homebridge] [1/15/2020, 20:55:54] [Thermometer] Logging into tcc...
[Homebridge] [1/15/2020, 20:55:54] [Ring] Initializing Ring platform...
[Homebridge] [1/15/2020, 20:55:54] [Camera ffmpeg] Initializing Camera-ffmpeg platform...
[Homebridge] [1/15/2020, 20:55:54] Loading 0 accessories...
[Homebridge] [1/15/2020, 20:55:54] Garage Exterior is running on port 43589.
[Homebridge] [1/15/2020, 20:55:54] Please add [Garage Exterior] manually in Home app. Setup Code: 031-45-154
[Homebridge] [1/15/2020, 20:55:54] Garage 2 is running on port 32941.
[Homebridge] [1/15/2020, 20:55:54] Please add [Garage 2] manually in Home app. Setup Code: 031-45-154
[Homebridge] [1/15/2020, 20:55:54] Ender 3 is running on port 40821.
[Homebridge] [1/15/2020, 20:55:54] Please add [Ender 3] manually in Home app. Setup Code: 031-45-154
[Homebridge] [1/15/2020, 20:55:56] [Ring] Configuring 1 cameras and 1 devices for location "Windsor Locks" - locationId: 49f3cda5-123b-45eb-a2d7-f91f18fd3a33
[Homebridge] [1/15/2020, 20:55:56] [Ring] Adding new accessory doorbell_v3 Front Door
[Homebridge] [1/15/2020, 20:55:56] Front Door is running on port 46621.
[Homebridge] [1/15/2020, 20:55:56] Please add [Front Door] manually in Home app. Setup Code: 031-45-154
[Homebridge] [1/15/2020, 20:55:56] [Thermometer] Logged into tcc! [ { deviceID: '73020', name: 'Dining Room', usePermanentHolds: true } ]
[Homebridge] [1/15/2020, 20:55:58] [Thermometer] Adding TCC Device Dining Room 73020
[Homebridge] [1/15/2020, 20:55:58] [Thermometer] Initializing platform accessory 'Dining Room'...
[Homebridge] [1/15/2020, 20:55:58] [Thermometer] getServices Dining Room
[Homebridge] X-HM://0023ISYWYM155
[Homebridge] [1/15/2020, 20:55:58] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 20:55:58] Service is running on port 51826.
[Homebridge] [1/15/2020, 20:56:09] [Thermometer] Change Dining Room { deviceLive: true }
[Homebridge] [1/15/2020, 20:57:08] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 20:57:09] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 20:57:30] Got SIGINT, shutting down service...
internal/modules/cjs/loader.js:250
    throw e;
    ^
SyntaxError: Error parsing /usr/local/lib/node_modules/npm/node_modules/number-is-nan/package.json: Unexpected token � in JSON at position 1
    at JSON.parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:239:25)
    at readPackageMain (internal/modules/cjs/loader.js:273:15)
    at tryPackage (internal/modules/cjs/loader.js:283:15)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/is-fullwidth-code-point/index.js:2:19) {
  path: '/usr/local/lib/node_modules/npm/node_modules/number-is-nan/package.json'
}
[1/15/2020, 20:57:32] "homebridge-ring" package updated.
[Homebridge] [1/15/2020, 20:57:33] Loaded config.json with 0 accessories and 3 platforms.
[Homebridge] [1/15/2020, 20:57:33] ---
[Homebridge] [1/15/2020, 20:57:35] Loaded plugin: homebridge-camera-ffmpeg
[Homebridge] [1/15/2020, 20:57:35] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[Homebridge] [1/15/2020, 20:57:35] ---
[Homebridge] [1/15/2020, 20:57:36] Loaded plugin: homebridge-ring
[Homebridge] [1/15/2020, 20:57:36] Registering platform 'homebridge-ring.Ring'
[Homebridge] [1/15/2020, 20:57:36] ---
[Homebridge] [1/15/2020, 20:57:36] Loaded plugin: homebridge-tcc
[Homebridge] [1/15/2020, 20:57:37] Registering platform 'homebridge-tcc.tcc'
[Homebridge] [1/15/2020, 20:57:37] ---
[Homebridge] [1/15/2020, 20:57:37] Loading 3 platforms...
[Homebridge] [1/15/2020, 20:57:37] [Thermometer] Initializing tcc platform...
[Homebridge] [1/15/2020, 20:57:37] [Thermometer] Logging into tcc...
[Homebridge] [1/15/2020, 20:57:37] [Ring] Initializing Ring platform...
[Homebridge] [1/15/2020, 20:57:37] [Camera ffmpeg] Initializing Camera-ffmpeg platform...
[Homebridge] [1/15/2020, 20:57:37] Loading 0 accessories...
[Homebridge] [1/15/2020, 20:57:37] Garage Exterior is running on port 41851.
[Homebridge] [1/15/2020, 20:57:37] Please add [Garage Exterior] manually in Home app. Setup Code: 031-45-154
[Homebridge] [1/15/2020, 20:57:37] Garage 2 is running on port 39563.
[Homebridge] [1/15/2020, 20:57:37] Please add [Garage 2] manually in Home app. Setup Code: 031-45-154
[Homebridge] [1/15/2020, 20:57:37] Ender 3 is running on port 33105.
[Homebridge] [1/15/2020, 20:57:37] Please add [Ender 3] manually in Home app. Setup Code: 031-45-154
[Homebridge] [1/15/2020, 20:57:39] [Ring] Configuring 1 cameras and 1 devices for location "Windsor Locks" - locationId: 49f3cda5-123b-45eb-a2d7-f91f18fd3a33
[Homebridge] [1/15/2020, 20:57:39] [Ring] Adding new accessory doorbell_v3 Front Door
[Homebridge] [1/15/2020, 20:57:39] Front Door is running on port 37881.
[Homebridge] [1/15/2020, 20:57:39] Please add [Front Door] manually in Home app. Setup Code: 031-45-154
[Homebridge] [1/15/2020, 20:57:39] [Thermometer] Logged into tcc! [ { deviceID: '73020', name: 'Dining Room', usePermanentHolds: true } ]
[Homebridge] [1/15/2020, 20:57:41] [Thermometer] Adding TCC Device Dining Room 73020
[Homebridge] [1/15/2020, 20:57:41] [Thermometer] Initializing platform accessory 'Dining Room'...
[Homebridge] [1/15/2020, 20:57:41] [Thermometer] getServices Dining Room
[Homebridge] X-HM://0023ISYWYM155
[Homebridge] [1/15/2020, 20:57:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 20:57:41] Service is running on port 51826.
[Homebridge] [1/15/2020, 20:57:42] [Thermometer] Change Dining Room { deviceLive: true }
[Homebridge] [1/15/2020, 20:58:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 20:58:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 20:59:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 20:59:42] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:00:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:00:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:01:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:01:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:02:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:02:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:03:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:03:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:04:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:04:42] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:05:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:05:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:06:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:06:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:07:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:07:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:08:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:08:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:09:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:09:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:10:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:10:41] [Thermometer] Change Dining Room { latestData: { uiData: { EquipmentOutputStatus: 1 } } }
[Homebridge] [1/15/2020, 21:11:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:11:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:12:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:12:41] [Thermometer] Change Dining Room { latestData: { fanData: { fanIsRunning: true } } }
[Homebridge] [1/15/2020, 21:13:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:13:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:14:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:14:41] [Thermometer] Change Dining Room { latestData: { uiData: { EquipmentOutputStatus: 0 } } }
[Homebridge] [1/15/2020, 21:15:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:15:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:16:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:16:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:17:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:17:42] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:18:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:18:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:19:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:19:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:20:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:20:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:21:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:21:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:22:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:22:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:23:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:23:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:24:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:24:42] [Thermometer] Change Dining Room { latestData: { fanData: { fanIsRunning: false } } }
[Homebridge] [1/15/2020, 21:25:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:25:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:26:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:26:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:27:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:27:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:28:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:28:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:29:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:29:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:30:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:30:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:31:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:31:42] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:32:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:32:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:33:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:33:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:34:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:34:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:35:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:35:41] [Thermometer] Change Dining Room {}
   hoobs : TTY=pts/1 ; PWD=/home/hoobs/.hoobs/etc ; USER=root ; COMMAND=/usr/local/bin/hoobs service log
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
[Homebridge] [1/15/2020, 21:36:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:36:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:37:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:37:42] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:38:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:38:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:39:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:39:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:40:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:40:41] [Thermometer] Change Dining Room {}
[Homebridge] [1/15/2020, 21:41:41] [Thermometer] updateValues 1
[Homebridge] [1/15/2020, 21:41:41] [Thermometer] Change Dining Room {}
