### ISSUE TITLE
Homebridge-Ring Released 6.0.0 - When will you update the certified hoobs version

### ISSUE THREAD

**Issue by adavison007** [hoobs-org/HOOBS#431]
**Description**
Please can you certify the new ring homebridge-ring certified plugin in  to the latest 6.0.0?

**Expected behavoir**

**Plugin name**
homebridge-ring

**Please report the issue to the plugin developer**

**Version**
Latest

**Comment by mkellsy** [comment]
We test new plugin releases first.
