### ISSUE TITLE
Strange problem with the homebridge-harmony plugin

### ISSUE THREAD

**Issue by MikeDeltaHH** [hoobs-org/HOOBS#432]
**Description**
I have a strange problem with the plugin... sometimes when i installed or update a plugin and hoobs do a service reboot all my harmony switches are moved from the configured room to unassigned and i have to move all switches back - the problem is that this kill all my homekit automation routines with the harmony switches and i have to recreate them. In alexa my created groups with the switches doesn´t work then, i have to do a new search to bring them back to work... i haven´t any problem with the plugin itself or an error in the log and don´t know why this happens... this never happens bevore i switch to hoobs from my homebridge so i think this isn´t a plugin related problem.

**Version**
3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Ubuntu 18.04.3 LTS

**List your plugins**
homebridge-harmony

**Post your config**

{
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "HarmonyHub Wohnzimmer",
            "hubIP": "192.168.2.34",
            "cleanCache": "false",
            "publishAllTVAsExternalAccessory": "true",
            "TVAccessory": "true",
            "mainActivity": "Fernsehen",
            "playPauseBehavior": "true",
            "numberOfCommandsSentForVolumeControl": 1,
            "switchAccessories": "true",
            "showTurnOffActivity": "true",
            "publishGeneralMuteSwitch": "false",
            "addAllActivitiesToSkippedIfSameStateActivitiesList": "true",
            "publishSwitchActivitiesAsIndividualAccessories": "false",
            "publishDevicesAsIndividualAccessories": "true",
            "publishSequencesAsIndividualAccessories": "true",
            "showCommandsAtStartup": "false",
            "publishHomeControlsAsIndividualAccessories": "true",
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "activitiesToPublishAsAccessoriesSwitch": [],
            "skippedIfSameStateActivities": [],
            "devicesToPublishAsAccessoriesSwitch": [],
            "sequencesToPublishAsAccessoriesSwitch": [],
            "homeControlsToPublishAsAccessoriesSwitch": [],
            "otherPlatforms": []
        }

**Comment by mkellsy** [comment]
This is happening because the homebridge-harmony plugin is not using the accessory cache and Homebridge is assigning new IDs.

**Comment by MikeDeltaHH** [comment]
Ok, is the reason for this the design of hoobs or comes it from the plugin itself? I haven´t this in the past bevore i switch to hoobs but i don´t know what the source of the problem is...

**Comment by mkellsy** [comment]
I don't have an answer. It's going to take some time to figure it out.

**Comment by MikeDeltaHH** [comment]
Switched the plugin back to my homebridge installation i have for these plugins doesn´t work with hoobs, three at the moment - so i hope that these problems can be solved in future versions.

**Comment by nicoduj** [comment]
Hi, I am the developper of harmony plugin and I use cached accessories. Only TV accessories are exposed as external accessories beacuse of apple limitation and the use of bonjour protocol for this.

Other users are also reporting problems with latest update and websocket I can't reproduce without hoobs. 

https://github.com/nicoduj/homebridge-harmony/issues/217

If you have any clue ...

**Comment by MikeDeltaHH** [comment]
@mkellsy Think this is more important for the hoobs team...

**Comment by mkellsy** [comment]
I am looking into this.

**Comment by mkellsy** [comment]
I am continuing this in issue #428. It has logs posted.

**Comment by MikeDeltaHH** [comment]
@nicoduj has the problem that the plugin doesn´t use the cached assessories in hoobs the same source than the other problem?

**Comment by nicoduj** [comment]
Hi, I don't understand what you mean. The plugin is using cached accessories, and it is working fine as far as I know on a "regular" homebridge. The problem that seems to happen for some users is a websocket problem, maybe since latest update of my plugin in hoobs.

**Comment by MikeDeltaHH** [comment]
Asking this because mkellsy wrote that he continuing investigate this in the other issue 428 , i think this is another problem...

**Comment by nicoduj** [comment]
Indeed, I think so also. I am using some files at the root directory of homebridge, for names serialization, like some other plugins (hue / netamto for exemple). Maybe hoobs delete them at restart ?

**Comment by MikeDeltaHH** [comment]
The hue plugin runs without any problems on hoobs, but this plugin is certified for hoobs - don´t know the hoobs or hue developer made some changes for certification...but ok, think only the hoobs developer can help for this...

**Comment by nicoduj** [comment]
@mkellsy : I think you can close this issue, in the config @MikeDeltaHH put an option (cleancache) to "false" and not false, which is interpreted true and so remove allaccessories from cache at restart.

**Comment by MikeDeltaHH** [comment]
Yes, this was ist... shame on me but thanks a lot for help! :)

**Comment by nicoduj** [comment]
No shame at all, I have pushed a nex version that is more tolerant to this kind of error :)
