### ISSUE TITLE
Show accessories from first room on the list on the accessories page

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#434]
**Is your feature request related to a problem? Please describe.**
Accessories page does not show any accessories when opened, if they are assigned to rooms unless you click on a room. 

**Describe the solution you'd like**
It should load the first room on the list by default.

**Comment by mkellsy** [comment]
It does. Is this a bug? I am unable to reproduce.

**Comment by askovi** [comment]
When I click on the Accessories page i get nothing unless I click on a room:
![image](https://user-images.githubusercontent.com/3981552/72671245-6a474000-3a15-11ea-95fc-784eee6538d7.png)

**Comment by mkellsy** [comment]
Unable to reproduce. No stack trace.
