### ISSUE TITLE
Terminal input cutoff and overwrite the same line

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#435]
**Description**
In the UI Terminal, if you type a command over 50 chars long, the text restarts on the same line and overwrites it. Also using backspace once that happens makes the whole line disappear instantly but doesn't actually delete the text.

![image](https://user-images.githubusercontent.com/3981552/72671169-37e91300-3a14-11ea-9351-11d997049f7c.png)

**Version**
3.1.20

**Comment by mkellsy** [comment]
This is a known issue with node-pty. Microsoft is working on it.

**Comment by mkellsy** [comment]
I figured this out thanks to the issue https://github.com/Microsoft/node-pty/issues/37.

The problem is the rows and cols are not set. And this is because the dimensions of the window need to be tracked.

This is done in HOOBS Server 3.2 and HOOBS Desktop
