### ISSUE TITLE
Crash when plugins need update

### ISSUE THREAD

**Issue by weekendplaya** [hoobs-org/HOOBS#438]
** Description **

Whenever one of my plugins needs an update (or HOOBS itself), HOOBS stops working with HomeKit until I log into the interface and run the update and reboot HOOBS. 

**Version** 

3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**

Probably 3.1.19 but might have been 3.1.18

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**

Yes

Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ X] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?** 

Raspberry Pi

Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Ring
HarmonyHub
Dummy
Ifttt
myQ2
Tplink Smarthome
Tuya Web

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

  "{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY7B3H",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "XX",
        "postal_code": “XXXXXX"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "Xxxxxxxxxxxx",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "name": "Open Sesame"
        }
    ],
    "platforms": [
        {
            "email": "XXX",
            "password": "XXX",
            "hideCameraSirenSwitch": "true",
            "hideAlarmSirenSwitch": "false",
            "platform": "Ring",
            "hideDoorbellSwitch": "true",
            "hideUnsupportedServices": "true", hideUnsupportedServices": "true",
            "showPanicButtons": "false",
            "hideCameraMotionSensor": "true"
        },
        {
            "platform": "MyQ2",
            "email": "XXX",
            "password": "XXX"
        },
        {
            "platform": "HarmonyHub",
            "name": "homebridge-harmonyhub-plugin"
        },
        {
            "platform": "IFTTT",
            "plugin_map": {
                "plugin_name": "homebridge-ifttt"
            }
        },
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "XXX",
                "password": "XXX",
                "countryCode": "1",
                "platform": "smart_life",
                "pollingInterval": 10
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            }
        },
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        }
    ]

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
How are you updating?
Can you post your logs?

I need logs to troubleshoot.

https://github.com/hoobs-org/HOOBS/wiki/3.5-Log

**Comment by weekendplaya** [comment]
[1/18/2020, 18:08:28] HOOBS listning on port 8080.
[Homebridge] [1/18/2020, 18:08:29] Loaded config.json with 1 accessories and 6 platforms.
[Homebridge] [1/18/2020, 18:08:30] Loaded plugin: "homebridge-dummy"
[Homebridge] [1/18/2020, 18:08:30] Registering accessory "homebridge-dummy.DummySwitch"
[Homebridge] [1/18/2020, 18:08:31] Loaded plugin: "homebridge-harmonyhub-plugin"
[Homebridge] [1/18/2020, 18:08:31] Registering platform "homebridge-harmonyhub-plugin.HarmonyHub"
[Homebridge] [1/18/2020, 18:08:31] Loaded plugin: "homebridge-ifttt"
[Homebridge] [1/18/2020, 18:08:31] Registering platform "homebridge-ifttt.IFTTT"
[Homebridge] [1/18/2020, 18:08:31] Loaded plugin: "homebridge-myq2"
[Homebridge] [1/18/2020, 18:08:31] Registering platform "homebridge-myq2.MyQ2"
[Homebridge] [1/18/2020, 18:08:34] Loaded plugin: "homebridge-ring"
[Homebridge] [1/18/2020, 18:08:34] Registering platform "homebridge-ring.Ring"
[Homebridge] [1/18/2020, 18:08:34] Loaded plugin: "homebridge-tplink-smarthome"
[Homebridge] [1/18/2020, 18:08:34] Registering platform "homebridge-tplink-smarthome.TplinkSmarthome"
[Homebridge] [1/18/2020, 18:08:34] Loaded plugin: "homebridge-tuya-web"
[Homebridge] [1/18/2020, 18:08:34] Registering platform "homebridge-tuya-web.TuyaWebPlatform"
[Homebridge] [1/18/2020, 18:08:34] Loading 6 platforms...
[Homebridge] [1/18/2020, 18:08:34] [Ring] Initializing Ring platform...
[Homebridge] [1/18/2020, 18:08:34] [MyQ2] Initializing MyQ2 platform...
[Homebridge] [1/18/2020, 18:08:34] [homebridge-harmonyhub-plugin] Initializing HarmonyHub platform...
[Homebridge] [1/18/2020, 18:08:34] [IFTTT] Initializing IFTTT platform...
[Homebridge] [1/18/2020, 18:08:34] [IFTTT] Loading accessories...
[Homebridge] [1/18/2020, 18:08:34] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[Homebridge] [1/18/2020, 18:08:34] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[Homebridge] [1/18/2020, 18:08:34] [TplinkSmarthome] homebridge-tplink-smarthome v4.0.1, node v12.13.1, homebridge v0.4.50
[Homebridge] [1/18/2020, 18:08:34] Loading 1 accessories...
[Homebridge] [1/18/2020, 18:08:34] [Open Sesame] Initializing DummySwitch accessory...
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory da1d6b3c-872d-4ad3-a0ab-d86e9e2b7ac8 Ring Alarm
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory 34adf826-4d4f-4ada-9e76-7a33fd555a5c Front Door
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory 33aaa6dd-6ff3-4a73-9de4-61e97ab09e5e Living Room
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory c9a59c86-6595-46d4-98ff-10928206ffba Kitchen Window
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory a338ae50-bb6f-40b2-81c2-1ba7ae427ecf Garage Door
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory a7b23a3a-be1f-4439-9805-e27e3c1a6741 Back Door
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory 8cb5ead1-4a84-46d3-8323-a879748f01c4 Smoke/CO Listener
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory 3ed26488-4d4c-4024-8cbb-af25e8797d14 Panic Buttons
[Homebridge] [1/18/2020, 18:08:34] [TuyaWebPlatform] Configuring cached accessory [Christmas tree ] eb37aebe34edab2a60cdqg 72fc3385-0b6b-4301-8301-5041ad951377
[Homebridge] [1/18/2020, 18:08:34] [TuyaWebPlatform] Configuring cached accessory [Socket 2] eb20c97506cd8e9f77or6x 57691b5d-e1b5-4ca8-a760-2a8dcdaf9c40
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory 7bf5e516-b32d-4905-aae1-5853b85d8799 Kitchen
[Homebridge] [1/18/2020, 18:08:34] [Ring] Configuring cached accessory 415dc0a2-8acf-45d0-b199-8790e2b2917a Laundry Sensor
[Homebridge] [1/18/2020, 18:08:34] [TplinkSmarthome] Configuring cached accessory: [Upstairs Hallway] 8006BE900ED7C5ADA78AEF92BE337DAA1A1CA70A e7afe0a5-0e8e-4764-8f00-db90e1c844da
[Homebridge] [1/18/2020, 18:08:34] [TplinkSmarthome] Configuring cached accessory: [Downstairs Hallway] 8006B1991E6EC2A90BB98373C49459E51A1BE571 e1dc3930-702b-4a03-9440-0ee7d04fd790
[Homebridge] [1/18/2020, 18:08:34] [TplinkSmarthome] Configuring cached accessory: [Entrance Hallway] 800699BB1C8F06971D61CDB1ABC1BF6C1A1C1CC9 5c46ad5e-793e-4e5a-a80c-f129a4734687
[Homebridge] [1/18/2020, 18:08:34] [TplinkSmarthome] Configuring cached accessory: [Kitchen Lights] 8006C7958B310CB4FE9E5CEA50E7FB951A189065 bf9bd8d5-7e08-4128-848b-af0124d3f455
[Homebridge] [1/18/2020, 18:08:34] [TplinkSmarthome] Configuring cached accessory: [Island Light] 8006378AAEBC7E4CBECB4045D09F000C1A75ECC7 6569b6e5-0123-42bf-9a1e-ee523c3b6b3e
[Homebridge] [1/18/2020, 18:08:34] [TplinkSmarthome] Configuring cached accessory: [Dining Room Light] 80062C13CCA72F4AE50CBF61FEB8A1441A89846D 34d6c12e-bd0d-430c-ac4d-caf88340a39d
[Homebridge] [1/18/2020, 18:08:34] [TplinkSmarthome] Configuring cached accessory: [Outdoor Light] 8006B566DE90BF90777FFC2DC40B00921A758993 f79e7a01-3e1f-41b2-8ed7-566365b6ea20
[Homebridge] [1/18/2020, 18:08:34] [TuyaWebPlatform] Initializing TuyaWebPlatform...
[Homebridge] [1/18/2020, 18:08:34] API launched
[Homebridge] [1/18/2020, 18:08:34] Service is running on port 51826.
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] New Device Online: [Entrance Hallway] plug [800699BB1C8F06971D61CDB1ABC1BF6C1A1C1CC9] 192.168.0.104 9999
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] Adding: [Entrance Hallway] plug [800699BB1C8F06971D61CDB1ABC1BF6C1A1C1CC9]
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] New Device Online: [Outdoor Light] plug [8006B566DE90BF90777FFC2DC40B00921A758993] 192.168.0.246 9999
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] Adding: [Outdoor Light] plug [8006B566DE90BF90777FFC2DC40B00921A758993]
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] New Device Online: [Kitchen Lights] plug [8006C7958B310CB4FE9E5CEA50E7FB951A189065] 192.168.0.187 9999
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] Adding: [Kitchen Lights] plug [8006C7958B310CB4FE9E5CEA50E7FB951A189065]
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] New Device Online: [Downstairs Hallway] plug [8006B1991E6EC2A90BB98373C49459E51A1BE571] 192.168.0.118 9999
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] Adding: [Downstairs Hallway] plug [8006B1991E6EC2A90BB98373C49459E51A1BE571]
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] New Device Online: [Island Light] plug [8006378AAEBC7E4CBECB4045D09F000C1A75ECC7] 192.168.0.105 9999
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] Adding: [Island Light] plug [8006378AAEBC7E4CBECB4045D09F000C1A75ECC7]
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] New Device Online: [Upstairs Hallway] plug [8006BE900ED7C5ADA78AEF92BE337DAA1A1CA70A] 192.168.0.244 9999
[Homebridge] [1/18/2020, 18:08:35] [TplinkSmarthome] Adding: [Upstairs Hallway] plug [8006BE900ED7C5ADA78AEF92BE337DAA1A1CA70A]
[Homebridge] [1/18/2020, 18:08:35] [MyQ2] Initializing platform accessory 'JayMarv’s Garage  (ID: 1806651861)'...
[Homebridge] [1/18/2020, 18:08:37] [TuyaWebPlatform] Adding: Christmas tree  (switch / eb37aebe34edab2a60cdqg)
[Homebridge] [1/18/2020, 18:08:37] [TuyaWebPlatform] Existing Accessory found [Christmas tree ] [eb37aebe34edab2a60cdqg] [72fc3385-0b6b-4301-8301-5041ad951377]
[Homebridge] [1/18/2020, 18:08:37] [TuyaWebPlatform] Adding: Socket 2 (switch / eb20c97506cd8e9f77or6x)
[Homebridge] [1/18/2020, 18:08:37] [TuyaWebPlatform] Existing Accessory found [Socket 2] [eb20c97506cd8e9f77or6x] [57691b5d-e1b5-4ca8-a760-2a8dcdaf9c40]
[Homebridge] [1/18/2020, 18:08:37] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <2> hubs
[Homebridge] [1/18/2020, 18:08:37] [homebridge-harmonyhub-plugin] {HarmonyHub} <08302d2f-c71d-4fee-85e1-743e4cd9aea1> <Bedroom Hub>
[Homebridge] [1/18/2020, 18:08:37] [homebridge-harmonyhub-plugin] {HarmonyHub} <a8863463-f8ad-4355-b2c4-ad0c4fdef967> <Living Room Hub>
[Homebridge] [1/18/2020, 18:08:37] [Ring] Creating location socket.io connection
[Homebridge] [1/18/2020, 18:08:37] [homebridge-harmonyhub-plugin] {HarmonyHub} create new client for <Bedroom Hub>
[Homebridge] [1/18/2020, 18:08:37] [homebridge-harmonyhub-plugin] {HarmonyHub} create new client for <Living Room Hub>
[Homebridge] [1/18/2020, 18:08:38] [Ring] Ring connected to socket.io server
[Homebridge] [1/18/2020, 18:08:38] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <3> activities: <Watch Bedroom TV, Watch Bedroom Apple TV, Watch Bedroom Blu Ray>
[Homebridge] [1/18/2020, 18:08:38] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <3> activities: <Watch Living Room Blu Ray, Watch Living Room TV, Watch Living Room Netflix>
[Homebridge] [1/18/2020, 18:08:38] [Ring] Configuring 1 cameras and 18 devices for location "Ottawa" - locationId: beee7ce2-edaa-424f-b6b9-69f53a4d25ba
[Homebridge] [1/18/2020, 18:08:38] [Ring] Hidden accessory adapter.zigbee ZigBee onboard adapter
[Homebridge] [1/18/2020, 18:08:38] [Ring] Hidden accessory access-code.vault Code Vault
[Homebridge] [1/18/2020, 18:08:38] [Ring] Hidden accessory access-code Security Access Code
[Homebridge] [1/18/2020, 18:08:38] [Ring] Hidden accessory hub.redsky Base Station
[Homebridge] [1/18/2020, 18:08:38] [Ring] Hidden accessory adapter.zwave Z-Wave Adapter
[Homebridge] [1/18/2020, 18:08:38] [Ring] Hidden accessory range-extender.zwave Entrance Range Extender
[Homebridge] [1/18/2020, 18:08:38] [Ring] Hidden accessory security-keypad Entryway Keypad
[Homebridge] [1/18/2020, 18:08:38] [Ring] Adding new accessory doorbell_v4 Front Door
[Homebridge] [1/18/2020, 18:08:38] [Front Door] is running on port 36041.
[Homebridge] [1/18/2020, 18:08:44] [TplinkSmarthome] New Device Online: [Dining Room Light] plug [80062C13CCA72F4AE50CBF61FEB8A1441A89846D] 192.168.0.190 9999
[Homebridge] [1/18/2020, 18:08:44] [TplinkSmarthome] Adding: [Dining Room Light] plug [80062C13CCA72F4AE50CBF61FEB8A1441A89846D]
[Homebridge] [1/18/2020, 18:08:48] [MyQ2] JayMarv’s Garage  is closed.
[Homebridge] [1/18/2020, 18:09:39] [MyQ2] JayMarv’s Garage  is closed.

**Comment by weekendplaya** [comment]
Hope this is what you are looking for.

**Comment by mkellsy** [comment]
There is no error in the logs. What HOOBS version are you on? The current version is 3.1.20

**Comment by weekendplaya** [comment]
I am on the current version. I’ve rebooted since the last crash. So maybe the log doesn’t show anything?

**Comment by mkellsy** [comment]
I will need the log from when it crashes. There is information in there that tells me what plugin it is or if it is from HOOBS core.
