### ISSUE TITLE
Hoobs Auto stop his service 

### ISSUE THREAD

**Issue by F3000** [hoobs-org/HOOBS#439]
**Description**
Hoobs automaticly disable his service . When I want to start it (right three dot menu -> start service ) I see the notification : service is stopped 

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

custom install with your iso

**Comment by mkellsy** [comment]
Can you post your logs? Need those to troubleshoot.

https://github.com/hoobs-org/HOOBS/wiki/3.5-Log

**Comment by F3000** [comment]
@mkellsy  This are the logs after pressing "start service" 

![Bildschirmfoto 2020-01-28 um 23 47 29](https://user-images.githubusercontent.com/8161283/73312427-f41eb680-4228-11ea-81a9-067cc5eda043.png)

Do you need something else ?

**Comment by askovi** [comment]
Says it right there. Your FritzBox username is invalid
