### ISSUE TITLE
Ring Video Glitching

### ISSUE THREAD

**Issue by JazzerAlto** [hoobs-org/HOOBS#440]
**Description**
I am on 3.1.20 using the HOOBS certified Ring plugin 5.12.1. I have 3 flood light cams and 1 Ring Pro. Video quality is great but as I am viewing a live feed, the video will freeze briefly every couple of seconds and then resume. The RPI CPU never gets above 20%. I have the RPI connected to my network view ethernet and I see this behavior on either iOS or OS X. On the OS X machines, some are wifi connected and others are ethernet connected and it doesn't appear to make any change to the issue. Has anyone encountered this? When I pull the cameras up within the Ring app, I don't see any issue.
I also have 5 Circle 2s running HSV and I don't see this kind of issue at all with them. I'm thinking this might rule out a network issue but I'm at a loss. If the RPI was running high CPU load, I might suspect the 3B is the problem but it never goes above about 20%

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Hoobs certified Ring plug in.

**Please report the issue to the plugin developer**
Plugin developer says its likely a network problem but it works fine using the ring app and native HomeKit cameras work fine as well.

**Version**
3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY0C54",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "66224"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "",
        "username": "6C:43:68:04:6C:13"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Roomba",
            "name": "Roomba",
            "model": "e5",
            "blid": "",
            "robotpwd": ":",
            "ipaddress": "",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "cacheTTL": 30,
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "email": ",
            "password": "",
            "hideLightGroups": false,
            "hideDoorbellSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideCameraMotionSensor": true,
            "debug": false,
            "locationIds": []
        }
    ]
}
**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
The Ring plugin is unique. It doesn't process the video at all. It's a feed directly from the camera.

**Comment by JazzerAlto** [comment]
That’s how I understood it as well which makes this all the more puzzling to me.  HOOBS is wired straight into a gigabit ethernet switch as well. I am on a RPI 3B and it’s mpt even close to being overloaded.  It almost feels like a buffer or MTU issue but those are just guesses.  The fact it looks fine using the Ring app and that I also have 5 Circle 2 cameras working fine on mu network has me at a lost.

**Comment by mkellsy** [comment]
The Ring plugin sends the RSTP stream directly to Apple Home, it doesn't go through HOOBS, only the setup part does.

**Comment by JazzerAlto** [comment]
Ah, gotcha. If you have any ideas of things to look at, I’d welcome advice. Sounds like HOOBS is ruled out. 

Other things I’ve tried include:

Using a Ethernet connected Mac to look at the stream. Brand new iMac and an older Mac Pro. 

Power cycled my whole network and hubs

Tried iPhone 11 max, iPad mini 5, iPad 10.2

I though about WiFi signal quality causing the glitches but I don’t see it via the Ring app unless Ring is compensating and allows a buffer causing a slight delay in the start of the feed so you never see the pauses. 

I may just have to accept it but I’ll try any suggestions. 

Thanks Michael
