### ISSUE TITLE
Unable to install broadlink plugin on windows

### ISSUE THREAD

**Issue by rafayez** [hoobs-org/HOOBS#441]
Hi all,

I've been using homebridge with the broad link plugin for 2 or 3 years now with no issues that weren't fixable. Until recently i bumped into an issue where homebridge will just refuse to run hitting me with a bunch of errors. So i decided to reinstall the plugin to resolve the issue, for doing so, i removed broadlink plugin using the command " npm remove -g homebridge-broadlink-rm " and then tried to re-install by using the command " npm install -g homebridge-broadlink-rm " , but sadly it kept on failing and logged the following errors one the log file :

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-broadlink-rm'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.3.1
4 verbose npm-session b94767d920bfce97
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-broadlink-rm 1443ms (from cache)
8 silly pacote tag manifest for homebridge-broadlink-rm@latest fetched in 1578ms
9 timing stage:loadCurrentTree Completed in 1679ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 14ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-broadlink-rm@3.6.22 checking installable status
17 silly fetchPackageMetaData error for homebridge-platform-helper@github:lprhodes/homebridge-platform-helper#feature/typescript Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 304 https://registry.npmjs.org/github-version-checker 1387ms (from cache)
19 silly pacote range manifest for github-version-checker@^1.2.0 fetched in 1404ms
20 silly resolveWithNewModule github-version-checker@1.2.0 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/broadlinkjs-rm 2759ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/uuid 2563ms (from cache)
23 http fetch GET 304 https://registry.npmjs.org/find-key 2769ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/chai 2774ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/ping 2582ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/net-ping 2675ms (from cache)
27 silly pacote range manifest for uuid@^3.3.3 fetched in 2677ms
28 silly resolveWithNewModule uuid@3.4.0 checking installable status
29 silly pacote range manifest for find-key@^2.0.1 fetched in 2887ms
30 silly resolveWithNewModule find-key@2.1.3 checking installable status
31 silly pacote range manifest for chai@^4.2.0 fetched in 2897ms
32 silly resolveWithNewModule chai@4.2.0 checking installable status
33 silly pacote range manifest for broadlinkjs-rm@^0.7.6 fetched in 2910ms
34 silly resolveWithNewModule broadlinkjs-rm@0.7.6 checking installable status
35 silly pacote range manifest for ping@^0.2.2 fetched in 2706ms
36 silly resolveWithNewModule ping@0.2.2 checking installable status
37 silly pacote range manifest for net-ping@^1.2.3 fetched in 2741ms
38 silly resolveWithNewModule net-ping@1.2.3 checking installable status
39 timing stage:rollbackFailedOptional Completed in 3ms
40 timing stage:runTopLevelLifecycles Completed in 4703ms
41 verbose stack Error: spawn git ENOENT
41 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
41 verbose stack     at onErrorNT (internal/child_process.js:456:16)
41 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
42 verbose cwd C:\Users\Server\Desktop
43 verbose Windows_NT 10.0.18362
44 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge-broadlink-rm"
45 verbose node v12.3.1
46 verbose npm  v6.9.0
47 error path git
48 error code ENOENT
49 error errno ENOENT
50 error syscall spawn git
51 error enoent Error while executing:
51 error enoent undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
51 error enoent
51 error enoent
51 error enoent spawn git ENOENT
52 error enoent This is related to npm not being able to find a file.
53 verbose exit [ 1, true ]

Can someone please help me with my issue, as i've tried almost everything that i could think of but none of the worked. Removed Homebridge, Node.js and reinstalled them but still nothing seemed to resolve the issue.

Thank you in advance for your help, much appreciated.
Rafay

**Comment by mkellsy** [comment]
HOOBS doesn't use plugins like Homebridge. npm install doesn't work. You need to install plugins with the I terrace.

Run `sudo npm uninstall -g homebridge-broadlink-rm` then go to the Plugins screen and search for "broadlink" and install by clicking the Install button.

**Comment by rafayez** [comment]
Thank you mkellsy for your support and comments. I forgot to mention that I'm using Homebridge on a windows based computer, hence I'm using the old npm method. Should I delete my config.json file and start from scratch by creating a new blank config.json file so that I can gain access to the Homebridge UI and install the plugins through the user interface.

**Comment by mkellsy** [comment]
HOOBS is not Homebridge.

**Comment by rafayez** [comment]
Sorry for my ignorance, i've posted my issue here while not realizing that it's related to HOOBS over here.


Than you mkellsy for your help
