### ISSUE TITLE
custom parameters starting homebridge with hoobs

### ISSUE THREAD

**Issue by SRamsdell1** [hoobs-org/HOOBS#443]
The homebridge-samsung-tizen works great when installed thru Hoobs. But, to obtain a list of IDs it calls for starting the homebridge server with homebridge tizen-apps as documented here 

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications

How is this accomplished (only needs to be done temporarily) within hoobs?

**Comment by mkellsy** [comment]
I looked at the link you posted and it doesn't talk about custom parameters.

It isn't the -I parameter is it?

**Comment by mkellsy** [comment]
I read through their wiki. And the only command they are asking you to run is debug mode. It's the same with HOOBS it's just a lower case -d.

So.
1. Stop the service `sudo hoobs service stop`
2. Run HOOBS in debug mode `hoobs -d`
3. When done start the service `sudo hoobs service start`

**Comment by SRamsdell1** [comment]
This paragraph is what I was referring to on the link I provided ... 

“If you don't find what you are looking for you can start the homebridge server with tizen-apps as parameter (homebridge tizen-apps) and it will show a table with all the apps that are installed on the TV.”

Can I simply run [sudo hoobs tizen-apps] instead of [sudo Homebridge tizen-apps]? 

Thanks!

**Comment by mkellsy** [comment]
No. HOOBS is a different binary.

**Comment by WibiNorg** [comment]
Having the same struggle: How can I get the "tizen-apps" running as a parameter in Hoobs?
