### ISSUE TITLE
HOOBS error after fresh install on Raspbian Lite

### ISSUE THREAD

**Issue by alessiobulfaro** [hoobs-org/HOOBS#444]
**Description**
I've installed Raspbian Buster Lite on a Raspberry Pi 4. Installed HOOBS trough the guide for Debian/Raspbian devices. Trying to start HOOBS and received some error.

**Version**
3.1.20

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian Buster Lite.

<img width="697" alt="Schermata 2020-01-21 alle 14 43 02" src="https://user-images.githubusercontent.com/58361310/72809888-d9fb3c00-3c5c-11ea-9c22-365cdf374300.png">

**Comment by mkellsy** [comment]
That's because the install process starts a service. It's already running.

**Comment by alessiobulfaro** [comment]
But if I try to navigate to hoobs.local nothing happened.

**Comment by mkellsy** [comment]
Try the IP address. the .local part might not be available on your network. And there is a missing mDNS responder that we install on the pre-built images that makes .local addresses more persistant.

**Comment by alessiobulfaro** [comment]
Ok, now work, thanks. Maybe update the guide could be useful for other.
