### ISSUE TITLE
After update everything gone

### ISSUE THREAD

**Issue by Ace-li-k** [hoobs-org/HOOBS#446]
Hello,

I updated to 3.1.20 yesterday.

The page has not changed after 1 1/2 hours, when I restarted the Raspberry, I was able to log in without any problems and the update to 3.1.20 was successful, unfortunately all plugins and settings are gone.

Of course, I made a backup of the system and the config beforehand.
I then tried to import the COnfig backup, it also shows that it was backed up, but unfortunately there is still nothing.

**Comment by mkellsy** [comment]
Can you fill out the issue template. There is missing information that I need to troubleshoot.

https://github.com/hoobs-org/HOOBS/issues/new/choose
