### ISSUE TITLE
Plugin update / uninstall not possible

### ISSUE THREAD

**Issue by Spy-1** [hoobs-org/HOOBS#447]
I cannot update the Shelly Plugin (certified).

The display is not updated.

When I uninstall the plugin I get a message "Plugin uninstall failed".

![qvyh8h8ckbc41](https://user-images.githubusercontent.com/44490104/72965910-cf0bed00-3dbd-11ea-8eb3-0bb6ffe8f1cc.jpg)

**Comment by mkellsy** [comment]
Logs? Need the logs just after you try to upgrade.

**Comment by Spy-1** [comment]
Problem is solved! 

I did a new install!

 

Von: Michael Kellsy <notifications@github.com> 
Gesendet: Donnerstag, 23. Januar 2020 15:04
An: hoobs-org/HOOBS <HOOBS@noreply.github.com>
Cc: Spy-1 <info@brittnacher.com>; Author <author@noreply.github.com>
Betreff: Re: [hoobs-org/HOOBS] Plugin update / uninstall not possible (#447)

 

Logs? Need the logs just after you try to upgrade.
