### ISSUE TITLE
Docker network issue

### ISSUE THREAD

**Issue by NicoOosterwijk** [hoobs-org/HOOBS#448]
When creating a docker container with hoobs/hoobs, I forward loadbalancer ports 80, 8080 and 51826 to the hoobs container but my iPhone Home app does not connect to hoobs.

The loadbalancer is on my local network IP address and the docker container is using an internal IP network (host). 
- Can this be the issue? 
- How does the Home app connect to hoobs?
- What info is in the QCode?

thanks in advance!

Nico

**Comment by mkellsy** [comment]
Both Homebridge and HOOBS needs to be on the same subnet as the phone or iPad while pairing with Apple Home. Once it's pairs it no longer needs to be on the same subnet. This includes mesh networks.

**Comment by mkellsy** [comment]
The info in the QR Code is the Setup ID. It looks like a URL and it is in the System Info on your dashboard.

As for pairing from a load balanced Docker container. The host needs to be on the same subnet as the iOS device you are using to pair. Your load balancer might be impeding this. HOOBS/Homebridge should run just fine on a single node, it's designed for a Raspberry Pi, so it's small.

However, you should setup, initially, as a non load balanced container, where the IP and ports of the host correspond to the container, like if you were running the container on Docker Desktop. This way the physical IP address of the container is the same as the host and the ports don't need to be forwarded.

Then pair with Apple Home, making sure the Docker host and the iPhone or iPad are on the same subnet.  Ex. if you Docker host is on IP 192.168.1.5 with a subnet mask of 255.255.255.0, the iOS device should be on an IP in this range, 192.168.1.2 - 192.168.1.254 (192.168.1.0/24). You might have to add a temp AP to the network that you have your Docker host on.

Once it is paired, you then can move and load balance the container. You can even tear down and rebuild the container, as long as you have a persistant volume that stores the hoobs folder. This contains your plugins, config and most important the persist and accessories folders that keep the data from Apple Home. The subnet restriction is only for pairing.

I know this is a bit complicated, but Homebridge is not designed for advanced networking. Both HOOBS and Homebridge have this limitation. Both projects are trying to solve this restriction.

I hope this information helps.
