### ISSUE TITLE
Roborock Cleaning Status

### ISSUE THREAD

**Issue by JazzerAlto** [hoobs-org/HOOBS#450]
**Description**
If I start cleaning with the Mi app, the HOOBs plugin will recognize fan speed, no longer docked or charging but it doesn't show it's cleaning so when you look in the Home app, Homekit thinks the RoboRock is off

**Expected behavoir**
Expected to see the fan speed match the mode of operation of the vac

**Plugin name**
HOOBS certified RoboRock Plugin
**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.1.20
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
Hoobs 3 release build

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
No

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY0C54",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "",
        "username": "
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Roomba",
            "name": "Roomba",
            "model": "e5",
            "blid": "",
            "robotpwd": "",
            "ipaddress": "192.168.100.205",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "cacheTTL": 30,
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            }
        },
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "roborock",
                "index": 0
            },
            "name": "Roborock Vacuum",
            "pause": false,
            "dock": true,
            "ip": "192.168.100.207",
            "token": ""
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "email": "",
            "password": "",
            "hideLightGroups": false,
            "hideDoorbellSwitch": true,
            "hideInHomeDoorbellSwitch": true
        }
    ]
}
**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[Homebridge] [1/26/2020, 09:53:26] [Roborock Vacuum] INF getCleaning | roborock.vacuum.s6 | Cleaning is false
[Homebridge] [1/26/2020, 09:53:26] [Roborock Vacuum] INF getSpeed | roborock.vacuum.s6 | Fanspeed is 103 over miIO. Converting to HomeKit
[Homebridge] [1/26/2020, 09:53:26] [Roborock Vacuum] INF getSpeed | roborock.vacuum.s6 | Fanspeed is 103 over miIO "Turbo" > HomeKit speed 77%
[Homebridge] [1/26/2020, 09:53:26] [Roborock Vacuum] INF getBattery | roborock.vacuum.s6 | Batterylevel is 95%
[Homebridge] [1/26/2020, 09:53:26] [Roborock Vacuum] INF getCharging | roborock.vacuum.s6 | Charging is false (Status is unknown-18)
[Homebridge] [1/26/2020, 09:53:26] [Roborock Vacuum] INF getBatteryLow | roborock.vacuum.s6 | Batterylevel is 95%
[Homebridge] [1/26/2020, 09:53:26] [Roborock Vacuum] INF getDocked | roborock.vacuum.s6 | Robot Docked is false (Status is unknown-18)
```

**Additional context**

**Comment by brailawle** [comment]
Just a plus sign, I have the same issue

**Comment by JazzerAlto** [comment]
If I initiate a cleaning cycle from the Home app, it will give me a status that its cleaning but if I turn it off via the home app, it just stops and doesn't return to the dock like the Plug In documentation would indicate

**Comment by BobbySlope** [comment]
@JazzerAlto @brailawle please open an issue on the plugindeveloper repo
https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues

nothing we can do on HOOBS side, plugindev needs to do that

**Comment by JazzerAlto** [comment]
Hi Hoobs team,

I had a question on certified plugins like this one.  The package that you forked from looks like it has had bug fixes and features added.  The Hoobs version is 0.6.5 and the plugindev is on 0.7.2.  When will the certified plugin catch up with the plugin dev?

Thanks
