### ISSUE TITLE
Simplisafe (original) Quit working

### ISSUE THREAD

**Issue by rickdeg** [hoobs-org/HOOBS#451]
My Simplisafe (original version) quit working.  My Accessory is setup as: 
{
    "accessory": "Homebridge-SimpliSafe",
    "name": "Alarm System",
    "auth": {
        "username": "my@email.com",
        "password": "password"
    }
}
My log file is attached with no errors.

[logs (3).txt](https://github.com/hoobs-org/HOOBS/files/4120130/logs.3.txt)
![Plugins](https://user-images.githubusercontent.com/58718563/73227062-13351f80-4127-11ea-86b9-b1920c5e8e94.PNG)

**Comment by mkellsy** [comment]
Could you elaborate? What is not working? Are you not getting updates?

**Comment by rickdeg** [comment]
Thanks for the reply.
My Simplisafe version 1 stopped working.  I was able to get the new Nest Google login fixed but of course the thing I care about most, Simplisafe isn't.
My logs are clean and my passwords are correct, it's just not returning anything from the SS API, no response from the server on the status of the system.  
I think it has to do with an API retiring but you would think that there would have been a notice on github or something?

Dear SimpliSafe Customer,


We are officially sunsetting SimpliSafe’s legacy APIs. When these APIs are shut down, integrations relying on them will also stop functioning; we believe you may be using one of these integrations.


SimpliSafe has not actively supported these legacy APIs since 2016. In order to prevent unsupported APIs from compromising the security of our customers, we have determined that it is time to discontinue them.


We are always looking to improve our smart home integrations in a way that is safe and helpful. If you would like to share your ideas with us, please send us a message.


We apologize for any inconvenience.


    On Monday, January 27, 2020, 08:17:14 PM PST, Michael Kellsy <notifications@github.com> wrote:  
 
 
Could you elaborate? What is not working? Are you not getting updates?

**Comment by mkellsy** [comment]
It looks like you are not the only one. Here is an issue from the plugin's GitHub.

https://github.com/fholgado/homebridge-simplisafe-security-system/issues/7
