### ISSUE TITLE
Hoobs and Razberry-Board

### ISSUE THREAD

**Issue by koehlhirsch** [hoobs-org/HOOBS#452]
Hi,
I´m using a raspberry pi 4 with homebridge-software an one RaZberry-Modul with no problems. At the last weekend I tried to install hoobs with the same Razberry-Board, but ist doesn´t work really. There is a error by initilization of the board. 
![pasted-from-clipboard](https://user-images.githubusercontent.com/60389682/73263256-74fd9400-41d0-11ea-991e-5bd880a9073f.png)

Has anyone similar problems with that combination??

koehlhirsch

**Comment by koehlhirsch** [comment]
No, it seems to use port 8083. That is the entry at config.json.

**Comment by mkellsy** [comment]
You might have to disable NGINX.

```
sudo systemctl stop nginx
sudo systemctl disable nginx
```

You will only be able to access HOOBS at http://hoobs.local:8080.

Are you getting anything in the HOOBS log?

**Comment by koehlhirsch** [comment]
All right, I will try this in the evening when I´m back from work. 
Hoobs is running well and I can access hoobs at hoobs.local:8080. I also can access the z-way-Server at IP:8083 without any problem, but the server seems to have a problem reaching RaZberry.

**Comment by koehlhirsch** [comment]
Good evening Mike,
the problem stays the same. When I try to change settings in the RaZberry server, it doesn't let me save the changes.
![Unbenannt](https://user-images.githubusercontent.com/60389682/73395966-bc734580-42e0-11ea-85bd-c33f970f09fd.JPG)
This is also an error I don´t have with homebridge installation (not HOOBS). Can the problem be related to access rights under HOOBS?

**Comment by mkellsy** [comment]
This is something with the RaZberry server, it is unrelated to HOOBS. We will have to research this because we use a different z-wave board.

In the meantime, here are some resources that might help you  
https://forum.z-wave.me/viewtopic.php?t=19799  
https://z-wave.me/frequently-asked-questions/

**Comment by koehlhirsch** [comment]
Thank you for the links. But I think, it is a problem between HOOBS an Z-Way, because with Hombridge stand alone it works fine. 
I will check the threads from your links. Perhaps I will find a solution.

**Comment by BobbySlope** [comment]
@koehlhirsch please let us know if you found a solution, and share it for other users
I will close the issue for the moment, you can reopen it if we need to solve anything on our side

**Comment by 3ne** [comment]
Not sure if this matters now but Ive just installed my Razberry with HOOBS. I installed HOOBS first then installed the Zway server via wget -q -O - https://storage.z-wave.me/RaspbianInstall | sudo bash. Im using a PI3 B however.
