### ISSUE TITLE
Expose homebridge --remove-orphans option in HOOBS UI

### ISSUE THREAD

**Issue by jqnatividad** [hoobs-org/HOOBS#453]
**Is your feature request related to a problem? Please describe.**
As you setup your Homebridge system, oftentimes, you'd end up with orphaned accessories.  Traditionally, this is resolved by flushing some directories from the CLI.  As HOOBS is meant to enable non-tech users to use Homebridge, it'd be great if the --remove-orphans option is exposed in the HOOBS UI that was introduced in Homebridge 04.48.

https://github.com/nfarina/homebridge/commit/955536a6b891d3406f8dde7f8bb43854e5fa023a

**Describe the solution you'd like**
Add a "Remove Orphans" option in the System menu, in the Start/Stop/Restart Service section.

**Comment by mkellsy** [comment]
We already add the `-R` flag by default to Homebridge.

**Comment by jqnatividad** [comment]
Great! Keeping the UX simple and doing it by default is better.

**Comment by mkellsy** [comment]
We already add the `-R` flag by default to Homebridge.
