### ISSUE TITLE
squeezebox-plugin

### ISSUE THREAD

**Issue by ddbkva** [hoobs-org/HOOBS#456]
Hey 
can someone help me i like to install this plug in but i dont know what i can do with the config
homebridge-squeezebox

Example config.json

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [
		{
			"platform": "Squeezebox",
			"name": "Squeezebox",
			"host": "127.0.0.1",
			"port": 9000,
			"username": "username",
			"password": "password"
		}
	}
}
hoobs says that there is a syntax error

**Comment by mkellsy** [comment]
Go to Squeezebox in the Config screen and enter this into the field
```
{
    "platform": "Squeezebox",
    "name": "Squeezebox",
    "host": "127.0.0.1",
    "port": 9000,
    "username": "username",
    "password": "password"
}
```

**Comment by ddbkva** [comment]
thx

**Comment by Thebeatman** [comment]
hi new to all this. annd can't get this plug in to work at all. Any advice?
Not entirely sure what to even offer here to show why it isn't working
