### ISSUE TITLE
Linn DSM/ Majik plug-in support

### ISSUE THREAD

**Issue by guussie** [hoobs-org/HOOBS#457]
I can’t find the linn-Majik or Linn-DSM plug-ins 

Is it possible to add this?

**Comment by mkellsy** [comment]
There's a plugin out there, but it is not published properly.  
https://www.npmjs.com/package/linn-majik-dsm-control

You might have a bit more luck asking around in the Homebridge community  
https://www.reddit.com/r/homebridge/
