### ISSUE TITLE
When will you update the ring certified plugin?

### ISSUE THREAD

**Issue by adavison007** [hoobs-org/HOOBS#458]
homebridge-ring

**Comment by mkellsy** [comment]
We are working on a system that doesn't require us to do this. However I plan on pulling the new version this weekend.

**Comment by adavison007** [comment]
Awesome, thanks 

Adam Davison
adavison@me.com
07748 761448

Sent from my iPhone

> On 30 Jan 2020, at 19:38, Michael Kellsy <notifications@github.com> wrote:
> 

﻿
We are working on a system that doesn't require us to do this. However I plan on pulling the new version this weekend.

**Comment by adavison007** [comment]
@mkellsy any news on if Ring will be updated this weekend? Thanks in advance

**Comment by mkellsy** [comment]
This is updated to version 6.1.1

**Comment by adavison007** [comment]
@mkellsy Many thanks
