### ISSUE TITLE
100+ accessories 

### ISSUE THREAD

**Issue by goedh452** [hoobs-org/HOOBS#460]
I have 100+ accessoires I want exposed to the home app. I read that the home app is limited to 100 accessories per bridge. Does HOOBS address this by e.g. running multiple instances or does the problem doesn’t occur at all?

**Comment by askovi** [comment]
Apple increased this limit in ios13 to 1000 devices. 
HOOBS runs a custom build of Homebridge and HAP which supports this new limit.

**Comment by goedh452** [comment]
Great! Thanks for your quick response.
