### ISSUE TITLE
Can't update Mac HOOBS from .15 to .20

### ISSUE THREAD

**Issue by ravedoglv** [hoobs-org/HOOBS#465]
**Description**
Attempting to update from .15 to .20 from within the Web interface (on Mac High Sierra) and it has a progress bar that goes back and forth but never does anything.

**Version**
3.1.15

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Mac Mini Running High Sierra (latest)

**List your plugins**
MCUIOT
Hue
Dummy

```
POST CONFIG HERE
**Post your config**
{
    "server": {
        "origin": "*",
        "home_setup_id": "X-HM://0023ISYWYEKCA",
        "polling_seconds": 5,
        "autostart": 0,
        "port": 8080
    },
    "client": {
        "theme": "hoobs-dark",
        "country_code": "US",
        "inactive_logoff": 30,
        "postal_code": "89117",
        "default_route": "status",
        "temp_units": "fahrenheit",
        "locale": "en"
    },
    "bridge": {
        "name": "HOOBS Mini HTPC",
        "username": "xxx",
        "pin": "xxx",
        "port": 51826
    },
    "description": "HOOBS HomeBridge on Mac Mini HTPC",
    "ports": {},
    "plugins": [
        "homebridge-dummy",
        "hue",
        "homebridge-mcuiot"
    ],
    "accessories": [
        {
            "reverse": false,
            "name": "Asleep",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "accessory": "DummySwitch",
            "stateful": true,
            "time": 1000
        },
        {
            "reverse": false,
            "name": "Movie Mode",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "accessory": "DummySwitch",
            "stateful": true,
            "time": 1000
        },
        {
            "reverse": false,
            "name": "Cleaning Time",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "accessory": "DummySwitch",
            "stateful": true,
            "time": 1000
        },
        {
            "reverse": false,
            "name": "Sitting in Garage",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "accessory": "DummySwitch",
            "stateful": true,
            "time": 1000
        }
    ],
    "platforms": [
        {
            "lights": true,
            "nativeHomeKitLights": true,
            "nupnp": true,
            "name": "Hue",
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "nativeHomeKitSensors": true,
            "users": {
                "xxx": "xxx"
            },
            "hosts": [
                "192.168.1.154"
            ],
            "forceCt": true,
            "resource": false
        },
        {
            "debug": false,
            "aliases": {
                "NODE-B0DC7": "Bedroom Temp"
            },
            "platform": "mcuiot",
            "name": "MCUIOT",
            "port": 8081,
            "plugin_map": {
                "plugin_name": "homebridge-mcuiot"
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
* Remove any passwords from the config file. This is public.

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[Homebridge] X-HM://0023ISYWYEKCA
[Homebridge] [2/3/2020, 3:11:34 PM] Service is running on port 51826.
[Homebridge] [2/3/2020, 3:11:44 PM] [MCUIOT] HTTP get failed: NODE-B0DC7 ESOCKETTIMEDOUT
[Homebridge] [2/3/2020, 3:12:34 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:13:34 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:14:34 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:15:35 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:16:35 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:17:35 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:17:52 PM] Got SIGINT, shutting down service...
[Homebridge] [2/3/2020, 3:17:53 PM] Loaded config.json with 4 accessories and 2 platforms.
[Homebridge] [2/3/2020, 3:17:53 PM] ---
[Homebridge] [2/3/2020, 3:17:53 PM] Loaded plugin: homebridge-dummy
[Homebridge] [2/3/2020, 3:17:53 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[Homebridge] [2/3/2020, 3:17:53 PM] ---
[Homebridge] [2/3/2020, 3:17:54 PM] Loaded plugin: homebridge-mcuiot
[Homebridge] [2/3/2020, 3:17:54 PM] Registering platform 'homebridge-mcuiot.mcuiot'
[Homebridge] [2/3/2020, 3:17:54 PM] ---
[Homebridge] [2/3/2020, 3:17:54 PM] Loaded plugin: hue
[Homebridge] [2/3/2020, 3:17:54 PM] Registering platform 'homebridge-hue.Hue'
[Homebridge] [2/3/2020, 3:17:54 PM] ---
[Homebridge] [2/3/2020, 3:17:54 PM] Loading 2 platforms...
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] Initializing Hue platform...
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] config.json: warning: plugin_map: ignoring unknown key
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] homebrige-hue v0.11.46, node v12.14.0, homebridge v0.4.50
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] warning: not using recommended node version v7.0.0 LTS
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] warning: not using recommended homebridge version v0.4.22
[Homebridge] [2/3/2020, 3:17:54 PM] [MCUIOT] Initializing mcuiot platform...
[Homebridge] [2/3/2020, 3:17:54 PM] Loading 4 accessories...
[Homebridge] [2/3/2020, 3:17:54 PM] [Asleep] Initializing DummySwitch accessory...
[Homebridge] [2/3/2020, 3:17:54 PM] [Asleep] Setting switch to false
[Homebridge] [2/3/2020, 3:17:54 PM] [Movie Mode] Initializing DummySwitch accessory...
[Homebridge] [2/3/2020, 3:17:54 PM] [Movie Mode] Setting switch to false
[Homebridge] [2/3/2020, 3:17:54 PM] [Cleaning Time] Initializing DummySwitch accessory...
[Homebridge] [2/3/2020, 3:17:54 PM] [Cleaning Time] Setting switch to false
[Homebridge] [2/3/2020, 3:17:54 PM] [Sitting in Garage] Initializing DummySwitch accessory...
[Homebridge] [2/3/2020, 3:17:54 PM] [Sitting in Garage] Setting switch to false
[Homebridge] [2/3/2020, 3:17:54 PM] [MCUIOT] configureAccessory MCUIOT Reset Switch
[Homebridge] [2/3/2020, 3:17:54 PM] [MCUIOT] configureAccessory NODE-B0DC7
[Homebridge] [2/3/2020, 3:17:54 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:17:54 PM] [MCUIOT] Starting Bonjour listener
[Homebridge] [2/3/2020, 3:17:54 PM] [MCUIOT] Web Server listening on: http://localhost:8081
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] npm registry: status 404 Not Found
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] Philips hue: Philips BSB002 bridge v1935144040, api v1.35.0
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] Philips hue: warning: not using recommended Hue bridge api version undefined
[Homebridge] [2/3/2020, 3:17:54 PM] [MCUIOT] Skipping NODE-B0DC7
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] Philips hue: 3 accessories
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] masked debug info dumped to /private/var/root/.hoobs/etc/homebrige-hue.json.gz
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] Initializing platform accessory 'Philips hue'...
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] Philips hue: 2 services
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] Initializing platform accessory 'Pedestal Light'...
[Homebridge] [2/3/2020, 3:17:54 PM] [Hue] Initializing platform accessory 'Extended color light 1'...
[Homebridge] X-HM://0023ISYWYEKCA
[Homebridge] [2/3/2020, 3:17:54 PM] Service is running on port 51826.
[Homebridge] [2/3/2020, 3:18:04 PM] [MCUIOT] HTTP get failed: NODE-B0DC7 ESOCKETTIMEDOUT
[Homebridge] [2/3/2020, 3:18:54 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:19:54 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:20:54 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:21:54 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:22:54 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:23:54 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:24:54 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:25:55 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:26:55 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:27:55 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:28:55 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:29:55 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:30:55 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:31:55 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:32:55 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:33:55 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:34:56 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:35:56 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:36:56 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:37:56 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:38:56 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:39:56 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:40:56 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:41:56 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:42:57 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:43:57 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:44:57 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:45:57 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:46:57 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:47:57 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:48:57 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:49:57 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:50:57 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:51:58 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7
[Homebridge] [2/3/2020, 3:52:58 PM] [MCUIOT] Reading MCUIOT: NODE-B0DC7```
[Homebridge] [2/3/2020, 3:55:43 PM] Got SIGINT, shutting down service...
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826

**Additional context**

**Comment by ravedoglv** [comment]
I realize this is a duplicate of another submission but I thought you'd want to see my logs and configs as well..

**Comment by mkellsy** [comment]
Open the terminal and type this command
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

Please post the output.

**Comment by ravedoglv** [comment]
It's still stuck in that progress animation state.... shall i reboot the Mac then run the command?  I hate to disrupt it if its doing something...

**Comment by mkellsy** [comment]
It will take a minute depending on your plugins.

You can always stop the process with ctrl+c

**Comment by ravedoglv** [comment]
trying now (ctrl c wouldn't work as it runs a service)


output:

/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> @hoobs/hoobs@3.1.20 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

+ @hoobs/hoobs@3.1.20
updated 1 package in 8.99s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.13.4 → 6.13.7       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.7   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯


Should i?

**Comment by mkellsy** [comment]
Yes

**Comment by ravedoglv** [comment]
That worked! running

`sudo npm install -g --unsafe-perm @hoobs/hoobs
`

its up and running. Any ideas what went wrong?

**Comment by mkellsy** [comment]
NPM has been acting up for the past few days. Maybe the connection timedout. It's near impossible to find out after the fact.

I'm glad to hear you were able to upgrade.
