### ISSUE TITLE
Hoobs Not Working After New Homemanager App Installed

### ISSUE THREAD

**Issue by benji6388** [hoobs-org/HOOBS#466]
My Hoobs suddenly will not start up.  Things working fine until today - I upgraded and synced with the new Homemanager App and install a plugin from that app, and then everything stopped working correctly.  Plugin I installed was homebridge-wifi-presence.  Thanks for the help.

**Comment by mkellsy** [comment]
Please use the issue templates. We will need your logs to troubleshoot.

**Comment by benji6388** [comment]
Description 
My Hoobs suddenly will not start up. Things working fine until today - I upgraded and synced with the new Homemanager App and install a plugin from that app, and then everything stopped working correctly. Plugin I installed was homebridge-wifi-presence.

Version Please include the version of HOOBS you are using.
3.1.20

Did you upgrade Please let us know if you upgraded from a previous version.
 No

What device are you using? Please let us know the device you are running HOOBS on.

 HOOBS SD Card and Raspberry Pi Zero W

List your plugins Please include a list of the plugins you are using. 
-Nest (Hoobs version) (with google authentication)
- iControl
- PeopleX
- Wifipresence

Post your log You can get the log from the intercafe. This is in the Log section.
[2/3/2020, 8:28:48 PM] HOOBS listning on port 8080.
[Homebridge] [2/3/2020, 8:28:55 PM] Loaded config.json with 0 accessories and 2 platforms.
[Homebridge] [2/3/2020, 8:29:00 PM] Loaded plugin: "homebridge-icontrol-platform"
[Homebridge] [2/3/2020, 8:29:00 PM] Registering platform "homebridge-icontrol-platform.iControl"
[Homebridge] [2/3/2020, 8:29:00 PM] Loaded plugin: "homebridge-people-x"
[Homebridge] [2/3/2020, 8:29:12 PM] Registering platform "homebridge-people.PeopleX"
[Homebridge] [2/3/2020, 8:29:12 PM] Registering accessory "homebridge-people.PeopleAccessory"
[Homebridge] [2/3/2020, 8:29:12 PM] Registering accessory "homebridge-people.PeopleAllAccessory"
[Homebridge] [2/3/2020, 8:29:13 PM] Loaded plugin: "homebridge-wifipresence"
[Homebridge] [2/3/2020, 8:29:13 PM] Registering accessory "homebridge-wifi-presence.WifiPresence"
[Homebridge] [2/3/2020, 8:29:16 PM] Loaded plugin: "nest"
[Homebridge] [2/3/2020, 8:29:16 PM] Registering platform "nest.Nest"
[Homebridge] [2/3/2020, 8:29:17 PM] Loading 2 platforms...
[Homebridge] [2/3/2020, 8:29:17 PM] [Nest] Initializing Nest platform...
[Homebridge] [2/3/2020, 8:29:17 PM] [Nest] Fetching Nest devices.
[Homebridge] [2/3/2020, 8:29:17 PM] [iControl Platform] Initializing iControl platform...
[Homebridge] [2/3/2020, 8:29:17 PM] Loading 0 accessories...
[Homebridge] [2/3/2020, 8:29:19 PM] API launched
[Homebridge] [2/3/2020, 8:29:20 PM] Unhandled Rejection "StatusCodeError: 401 - {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}".
[Homebridge] [2/3/2020, 8:29:20 PM] StatusCodeError: 401 - {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}
    at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Homebridge] [2/3/2020, 8:29:22 PM] [iControl Platform] Finished loading.
[Homebridge] [2/3/2020, 8:30:34 PM] Loaded config.json with 0 accessories and 2 platforms.
[Homebridge] [2/3/2020, 8:30:38 PM] Loaded plugin: "homebridge-icontrol-platform"
[Homebridge] [2/3/2020, 8:30:38 PM] Registering platform "homebridge-icontrol-platform.iControl"
[Homebridge] [2/3/2020, 8:30:39 PM] Loaded plugin: "homebridge-people-x"
[Homebridge] [2/3/2020, 8:30:49 PM] Registering platform "homebridge-people.PeopleX"
[Homebridge] [2/3/2020, 8:30:49 PM] Registering accessory "homebridge-people.PeopleAccessory"
[Homebridge] [2/3/2020, 8:30:49 PM] Registering accessory "homebridge-people.PeopleAllAccessory"
[Homebridge] [2/3/2020, 8:30:49 PM] Loaded plugin: "homebridge-wifipresence"
[Homebridge] [2/3/2020, 8:30:49 PM] Registering accessory "homebridge-wifi-presence.WifiPresence"
[Homebridge] [2/3/2020, 8:30:52 PM] Loaded plugin: "nest"
[Homebridge] [2/3/2020, 8:30:52 PM] Registering platform "nest.Nest"
[Homebridge] [2/3/2020, 8:30:53 PM] Loading 2 platforms...
[Homebridge] [2/3/2020, 8:30:53 PM] [Nest] Initializing Nest platform...
[Homebridge] [2/3/2020, 8:30:53 PM] [Nest] Fetching Nest devices.
[Homebridge] [2/3/2020, 8:30:53 PM] [iControl Platform] Initializing iControl platform...
[Homebridge] [2/3/2020, 8:30:53 PM] Loading 0 accessories...
[Homebridge] [2/3/2020, 8:30:55 PM] API launched
[Homebridge] [2/3/2020, 8:30:57 PM] Unhandled Rejection "StatusCodeError: 401 - {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}".
[Homebridge] [2/3/2020, 8:30:57 PM] StatusCodeError: 401 - {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}
    at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Homebridge] [2/3/2020, 8:30:58 PM] [iControl Platform] Finished loading.

**Comment by mkellsy** [comment]
It looks like the iControl Platform lost it's auth token. This could be causing the Homemanager app not to connect. I will need to research this plugin to give you instructions on how to authenticate it.

**Comment by benji6388** [comment]
Thank you very much!  Here's my config as it relates to the iControl Platform:

 {
            "platform": "iControl",
            "name": "iControl Platform",
            "system": "XFINITY_HOME",
            "email": "E-MAIL",
            "password": "PASSWORD",
            "pin": "PIN CODE",
            "plugin_map": {
                "plugin_name": "homebridge-icontrol-platform"
            }

**Comment by benji6388** [comment]
Pretty sure it was nest that was the issue.... thanks for the help.  all set.
