### ISSUE TITLE
homebridge-hue ph outlet

### ISSUE THREAD

**Issue by dixiklo9** [hoobs-org/HOOBS#467]
Hi,
I want to use the command ph outlet to display my Osram plugs as a power outlet. But I get an error message bash: ph: command not found.
I have installed hoobs, Homebridge-hue and Homebridge-lib.
Unfortunately the developer of Homebridge-hue can't help me either and referred me to the developers of hoobs.

At GitHub, you might be able to track the problem.
https://github.com/ebaauw/homebridge-hue/issues/615

**Comment by mkellsy** [comment]
Its here in HOOBS
```
~/.hoobs/node_mofules/.bin/ph
```

**Comment by dixiklo9** [comment]
Okay, I found it. Why can't I execute the command `ph outlet`?

`hoobs@hoobs:~/.hoobs/node_modules/.bin $ cd ~/.hoobs/node_modules/.bin
hoobs@hoobs:~/.hoobs/node_modules/.bin $ ls
dc_eventlog  he       multicast-dns            ph          sshpk-verify
errno        json     ncp                      rimraf      upnp
folder-hash  mime     node-gyp-build           semver      uuid
gp12-pem     mkdirp   node-gyp-build-optional  sshpk-conv  zp
hap          msgpack  node-gyp-build-test      sshpk-sign
hoobs@hoobs:~/.hoobs/node_modules/.bin $ ph outlet -v
bash: ph: command not found`

**Comment by mkellsy** [comment]
In HOOBS we isolate plugins to HOOBS for security. We don't give random plugin developers full access to the system.

**Comment by dixiklo9** [comment]
Thank you!

**Comment by DominicHochberg** [comment]
I tried the same. what's the full command line to run the script incl. username etc.?

**Comment by mkellsy** [comment]
Whatever the homebridge-hue docs say.
just replace `ph` with `~/.hoobs/node_modules/.bin/ph`

> HOOBS isolates plugins for security reasons.

**Comment by gmum4d** [comment]
also trying to do this. I'm running HOOBS on a Pi with Conbee 2 USB stick.  Deconz is running ok. When I enter `~/.hoobs/node_modules/.bin/ph outlet -v` I get the following... `ph: error: localhost: not a Hue bridge nor deCONZ gateway`

**Comment by Hase-HH** [comment]
> In HOOBS we isolate plugins to HOOBS for security. We don't give random plugin developers full access to the system.
> 
> Instead of running `ph` run it like this
> 
> ```
> ~/.hoobs/node_modules/.bin/ph
> ```
> 
> No $ between /.bin and ph.

also have an issue when trying to do this. Instead of using 

ph -H IP.HueBridge -u xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx outlet -v 

i used 

~/.hoobs/node_modules/.bin/ph -H IP.HueBridge -u xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx outlet -v

and i get a "No such file or directory"

Any ideas?

**Comment by fedexx89** [comment]
> > In HOOBS we isolate plugins to HOOBS for security. We don't give random plugin developers full access to the system.
> > Instead of running `ph` run it like this
> > ```
> > ~/.hoobs/node_modules/.bin/ph
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No $ between /.bin and ph.
> 
> also have an issue when trying to do this. Instead of using
> 
> ph -H IP.HueBridge -u xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx outlet -v
> 
> i used
> 
> ~/.hoobs/node_modules/.bin/ph -H IP.HueBridge -u xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx outlet -v
> 
> and i get a "No such file or directory"
> 
> Any ideas?


I have exact the same problem: "no such file or directory".
what can I do now?

**Comment by Raczka1989** [comment]
Hallo, ich have the same problem, with it, no such file or directory, how i can set in Hoobs Hue Plugin the light as a Plug?
