### ISSUE TITLE
Philips Hue Plugin installieren

### ISSUE THREAD

**Issue by sTsJoch** [hoobs-org/HOOBS#470]
**Description**
Ich habe das philips hue Plugin installiert aber es funktioniert nichts

**Plugin name**
hue

**Version**

HOOBS 3 Version | 3.1.20
-- | --

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY38ML",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "63768"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-XX-XXX",
        "username": "8D:XX:XX:XX:XX:E0"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "lights": true,
            "rooms": true,
            "rules": true,
            "scenes": true,
            "schedules": true,
            "sensors": true
        }
    ]
}
```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[Homebridge] [2/7/2020, 2:29:10 PM] [Hue] 192.***.***.31: bridge request 257: get /config
[Homebridge] [2/7/2020, 2:29:10 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:29:14 PM] [Hue] 192.***.***.31: bridge request 255: get /config
[Homebridge] [2/7/2020, 2:29:14 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:29:16 PM] [Hue] 192.***.***.57: bridge request 196: get /config
[Homebridge] [2/7/2020, 2:29:16 PM] [Hue] 192.***.***.57: bridge communication error EHOSTUNREACH on 192.***.***.57
[Homebridge] [2/7/2020, 2:29:16 PM] [Hue] 192.***.***.57: bridge request 211: get /config
[Homebridge] [2/7/2020, 2:29:16 PM] [Hue] 192.***.***.57: bridge communication error EHOSTUNREACH on 192.***.***.57
[Homebridge] [2/7/2020, 2:29:16 PM] [Hue] 192.***.***.57: bridge request 132: get /config
[Homebridge] [2/7/2020, 2:29:16 PM] [Hue] 192.***.***.57: bridge communication error EHOSTUNREACH on 192.***.***.57
[Homebridge] [2/7/2020, 2:29:16 PM] [Hue] 192.***.***.57: bridge request 213: get /config
[Homebridge] [2/7/2020, 2:29:16 PM] [Hue] 192.***.***.57: bridge communication error EHOSTUNREACH on 192.***.***.57
[Homebridge] [2/7/2020, 2:29:18 PM] [Hue] 192.***.***.31: bridge request 237: get /config
[Homebridge] [2/7/2020, 2:29:18 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:29:21 PM] [Hue] 192.***.***.31: bridge request 160: get /config
[Homebridge] [2/7/2020, 2:29:21 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:29:23 PM] [Hue] Philips hue: bridge request 161: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [2/7/2020, 2:29:23 PM] [Hue] Philips hue: bridge error 101: link button not pressed
[Homebridge] [2/7/2020, 2:29:23 PM] [Hue] Philips hue: press link button on the bridge to create a user
[Homebridge] [2/7/2020, 2:29:25 PM] [Hue] 192.***.***.31: bridge request 258: get /config
[Homebridge] [2/7/2020, 2:29:25 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:29:29 PM] [Hue] 192.***.***.31: bridge request 256: get /config
[Homebridge] [2/7/2020, 2:29:29 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:29:33 PM] [Hue] 192.***.***.31: bridge request 238: get /config
[Homebridge] [2/7/2020, 2:29:33 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:29:34 PM] [Hue] 192.***.***.57: bridge request 212: get /config
[Homebridge] [2/7/2020, 2:29:34 PM] [Hue] 192.***.***.57: bridge communication error EHOSTUNREACH on 192.***.***.57
[Homebridge] [2/7/2020, 2:29:34 PM] [Hue] 192.***.***.57: bridge request 133: get /config
[Homebridge] [2/7/2020, 2:29:34 PM] [Hue] 192.***.***.57: bridge communication error EHOSTUNREACH on 192.***.***.57
[Homebridge] [2/7/2020, 2:29:34 PM] [Hue] 192.***.***.57: bridge request 214: get /config
[Homebridge] [2/7/2020, 2:29:34 PM] [Hue] 192.***.***.57: bridge communication error EHOSTUNREACH on 192.***.***.57
[Homebridge] [2/7/2020, 2:29:34 PM] [Hue] 192.***.***.57: bridge request 197: get /config
[Homebridge] [2/7/2020, 2:29:34 PM] [Hue] 192.***.***.57: bridge communication error EHOSTUNREACH on 192.***.***.57
[Homebridge] [2/7/2020, 2:29:36 PM] [Hue] 192.***.***.31: bridge request 161: get /config
[Homebridge] [2/7/2020, 2:29:36 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:29:38 PM] [Hue] Philips hue: bridge request 162: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [2/7/2020, 2:29:38 PM] [Hue] Philips hue: bridge error 101: link button not pressed
[Homebridge] [2/7/2020, 2:29:38 PM] [Hue] Philips hue: press link button on the bridge to create a user
[Homebridge] [2/7/2020, 2:29:40 PM] [Hue] 192.***.***.31: bridge request 259: get /config
[Homebridge] [2/7/2020, 2:29:40 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:29:44 PM] [Hue] 192.***.***.31: bridge request 257: get /config

```

**Additional context**
ich kann mich wohl nicht mit der hue bridge verbinden - so interpretiere ich das als Laie. Aber die IP Adressen 192.***.***.57 und 192.***.***.31 haben nichts mit der hue bridge zu tun. Die bridge ist auf IP 192.***.***.64

wenn ich die taste auf der hue bridge drücke passiert folgendes:

[Homebridge] [2/7/2020, 2:32:23 PM] [Hue] Philips hue: created user - please edit config.json and restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "00XXXXXXXX4C9A02": "1tZO5qeQl4XXXXXXXX-oNacVjXXXXXXXXOsh7jr7"
      }
    }
  ]
[Homebridge] [2/7/2020, 2:32:24 PM] [Hue] Philips hue: 10 accessories
[Homebridge] [2/7/2020, 2:32:25 PM] [Hue] 192.***.***.31: bridge request 270: get /config
[Homebridge] [2/7/2020, 2:32:25 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31
[Homebridge] [2/7/2020, 2:32:29 PM] [Hue] 192.***.***.31: bridge request 268: get /config
[Homebridge] [2/7/2020, 2:32:29 PM] [Hue] 192.***.***.31: bridge communication error ECONNREFUSED on 192.***.***.31

Ich bin absoluter Laie - wie könnt ihr mir helfen?

**Comment by mkellsy** [comment]
I don't think your config is complete. Please refer to the homebridge-hue docs
https://github.com/ebaauw/homebridge-hue

**Comment by whitecole83** [comment]
I have exactly the same issue
