### ISSUE TITLE
Build a Node 12 Docker Image

### ISSUE THREAD

**Issue by RienduPre** [hoobs-org/HOOBS#471]
**Description**
Plugin for HomeSeer does not start because it needs Node version 12 or higher

**Plugin name**
Homeseer4

**Version**
HOOBS 3.1.20 in a docker

**Did you upgrade**
Please let us know if you upgraded from a previous version.
-  No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- No

**What device are you using?**
Please let us know the device you are running HOOBS on.
-  Docker from https://hub.docker.com/r/hoobs/hoobs/tags

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[Homebridge] [2/7/2020, 5:14:56 PM] Got SIGINT, shutting down service...
[Homebridge] [2/7/2020, 5:14:58 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [2/7/2020, 5:14:58 PM] Plugin /hoobs/node_modules/homebridge-homeseer4 requires Node version of >=12.0.0 which does not satisfy the current Node version of v10.18.0. You may need to upgrade your installation of Node.
[Homebridge] [2/7/2020, 5:14:59 PM] Error Loading Plugin "homebridge-homeseer4"
[Homebridge] [2/7/2020, 5:14:59 PM] No plugins found.
[Homebridge] [2/7/2020, 5:14:59 PM] Loading 1 platforms...
[Homebridge] [2/7/2020, 5:14:59 PM] Error: The requested platform 'HomeSeer' was not registered by any plugin.
    at API.platform (/hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
    at Server._loadPlatforms (/hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
    at Server.run (/hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] [2/7/2020, 5:14:59 PM] Got SIGTERM, shutting down service...
Unexpected token =
Unable to determine plugin type for "homebridge-homeseer4"
Unexpected token =
Unable to determine plugin type for "homebridge-homeseer4"
Unexpected token =
Unable to determine plugin type for "homebridge-homeseer4"
[Homebridge] [2/8/2020, 8:59:53 AM] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [2/8/2020, 9:00:09 AM] Plugin /hoobs/node_modules/homebridge-homeseer4 requires Node version of >=12.0.0 which does not satisfy the current Node version of v10.18.0. You may need to upgrade your installation of Node.
[Homebridge] [2/8/2020, 9:00:16 AM] Error Loading Plugin "homebridge-homeseer4"
[Homebridge] [2/8/2020, 9:00:16 AM] No plugins found.
[Homebridge] [2/8/2020, 9:00:16 AM] Loading 0 platforms...
[Homebridge] [2/8/2020, 9:00:16 AM] Loading 0 accessories...
[Homebridge] [2/8/2020, 9:00:16 AM] API launched
[Homebridge] [2/8/2020, 9:00:16 AM] Service is running on port 51826.
Unexpected token =
Unable to determine plugin type for "homebridge-homeseer4"
```

Please explain how I can upgrade the NODE version in the HOOBS docker implementation?

Thanks,
Rien

**Comment by mkellsy** [comment]
Docker containers are immutable, which means we need to build a new image with an upgraded version of node.

**Comment by rmohsenn** [comment]
+1 , same issue here , running HOOBS on unraid

**Comment by delucs** [comment]
Just wondering how to update, even if you build a new container. Will i need to reinstall all plugins and restore the config?

**Comment by mkellsy** [comment]
No. If you setup a Docker volume your config and plugins will remain static.

**Comment by mkellsy** [comment]
Done in 3.1.21

**Comment by rmohsenn** [comment]
> Done in 3.1.21

Thank you , any idea when will it be updated ?

**Comment by delucs** [comment]
How is the update done? Within hoobs? Automatically?  If not a short tutorial on your website would be useful to the docker users 

Sent from my iphone,  sorry for typos
-----------------------------------------
Luc SCHENGEN

**Comment by mkellsy** [comment]
The new image is not released yet. It still needs to go through testing.

When it is ready, you will need to upgrade the container.
1. Make sure that you have the hoobs volume setup https://docs.docker.com/storage/volumes/ if not you will loose your config and plugins.

2. Update the container https://docs.docker.com/engine/reference/commandline/container_update/

**Comment by delucs** [comment]
I don’t know if I have all setup correctly. From my QNAP NAS I just installed the Docker and all worked perfectly. Is it those shared folder I need?
Will you post some release notes what will be in the new container (I suppose ffmpeg and latest node)

**Comment by delucs** [comment]
I suppose this are the hoobs volumes needed (data)

**Comment by delucs** [comment]
MAybe you can help: I see the latest Docker update is released.
Inside Hoobs, I also see an update possiblility, which does not work.
I then in the docker in its Terminal send the command “docker container update hoobs-1” but I get this error..
 
Or am I doing something wrong?
 
Luc

**Comment by mkellsy** [comment]
What's the error?

**Comment by rmohsenn** [comment]
I updated my Unraid docker and now it doesn't run anymore , throwing this error , I even completely remove it and reinstalled 

`internal/modules/cjs/loader.js:985
throw err;
^

Error: Cannot find module '/usr/src/hoobs/bin/hoobs -c'

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
at Function.Module._load (internal/modules/cjs/loader.js:864:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
at internal/main/run_main_module.js:18:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}`

**Comment by mkellsy** [comment]
Fixed in 3.1.22. It is building now. Should be done soon.

**Comment by rmohsenn** [comment]
Perfect , thank you for your prompt response , will test it once it's up

**Comment by mkellsy** [comment]
The image is updated. If it was successful the Node version should be on 12.16.1. Also in the terminal you should be able to type this command `ffmpeg -protocols`.

**Comment by delucs** [comment]
how I proceed: In the ContainerSTation of QNAP
![2020-03-02_18h18_39](https://user-images.githubusercontent.com/7610744/75700569-901d6100-5cb2-11ea-8179-fb686b0ca90b.png)
a new browser window opens with this message
![image](https://user-images.githubusercontent.com/7610744/75700683-c1962c80-5cb2-11ea-9f24-b736ba1221bf.png)
but I think the new container is somehow there, but not installed.
![image](https://user-images.githubusercontent.com/7610744/75700822-face9c80-5cb2-11ea-9d3f-bee97da1ad40.png)

Is this a bug that within Doocker hoobs you see that you can update, but it does not work?

![image](https://user-images.githubusercontent.com/7610744/75700918-205ba600-5cb3-11ea-9edd-94f287b80b95.png)

**Comment by rmohsenn** [comment]
updated mine and it's now working perfectly with Homeseer 

@delucs I think it's better if you start over , copy your configuration file , delete hoobs and redownload the image and plugins again

**Comment by delucs** [comment]
@rmohsenn :-) this might be an idea, but it would be good to know how to do it for a next update...  QNAP NAS is not that exotic that I am the only one using it.
Also I would love to avoid configuring the all on the iphone again, because i think that I will lose. Also pairing deCONZ etc will be needed, no?

**Comment by mkellsy** [comment]
@delucs We need to create documentation for this. What I can tell you is you need to create a volume.

Docker command
```
docker volume create hoobs
```

Synology must have a way to do this.

Next. You need to create a container
```
docker container run --publish 8080:8080 --detach --mount source=hoobs,target=/hoobs --name hoobs docker.io/hoobs/hoobs:latest
```

Synology will have a way to do this. The important parts are the --mount source=hoobs,target=/hoobs` This is the static volume so you don't loose your data.

Then you need to start the container
```
docker container start hoobs
```

Again Synology will have a way to do this.

If Synology uses Compose Here is an example compose file (I think it does this automatically)
```
version: '2'
services:
  hoobs:
    image: hoobs/hoobs:latest
    container_name: hoobs
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ./hoobs:/hoobs
```

**Comment by delucs** [comment]
I would appreciate a short documentation. I am on QNAP but i think its very close to SYNOLOGY. I am pretty sure its not that difficult,  i don’t really what to do where? 😊😊

**Comment by mkellsy** [comment]
I have neither. I have to buy one to properly write the docs.

**Comment by delucs** [comment]
I think it easier than we both think... I am close but not there: The commands are not send via the terminal of the container, but on the NAS level through SSH. I opened a Putty session and could send the command, but what flag are missing??
![image](https://user-images.githubusercontent.com/7610744/75709603-4ab55f80-5cc3-11ea-8574-0fa542bbfefb.png)

**Comment by mkellsy** [comment]
Your QNAP is going to handle the volumes differently then my server.

1. Create a volume (check the QNAP docs on how to run this command)
```
docker volume create hoobs
```

2. Remove any containers called `hoobs`
```
docker container rm --force hoobs
```

3. Next pull the current image and attach the `hoobs` volume to `/hoobs` via the `--mount source=hoobs,target=/hoobs` flag.
```
docker container run --publish 8080:8080 --detach --mount source=hoobs,target=/hoobs --name hoobs hoobs/hoobs:latest
```

4. Start the container
```
docker container start hoobs
```

Since you are creating a volume, you can destroy the `hoobs` container and rebuild all you want as long as you mount the `hoobs` volume, you will not loose the data. This is how you upgrade a Docker container.

**Comment by rmohsenn** [comment]
everything is working fine with me , all plugins installed, my only issue now is i my iPhone doesn't find hoobs , cannot discover it , i tried the QR code and the manual code with no luck, i even changed the mac address couple of times, how can i troubleshoot this ?

**Comment by delucs** [comment]
@rmohsenn this is exactly my fear, rearranging all on iphone is not want i want to do again...
@mkellsy  all in QNAP (probably also in SYNOLOGY) for contaimners are done through the GUI. I suppose creating the new one, is the same as I did for the old one, but I still have some trouble understanding how I will not lose all, (I Have backup, but..) when I delete the running hoobs and then create a new container (this source and target thing :-))

![image](https://user-images.githubusercontent.com/7610744/75714689-7557e600-5ccc-11ea-9d58-a8261d8e290e.png)

**Comment by mkellsy** [comment]
@rmohsenn The Docker host and the iPhone needs to be on the same subnet. Once paired you can move them around. Also mesh networks like Google WiFi interfere with the pairing process. This is an issue with both HOOBS and Homebridge.

**Comment by rmohsenn** [comment]
@mkellsy They are on the same network , actually both homebridge docker and hoobs docker are running on the same unraid server , homebridge is added but hoobs is not

**Comment by mkellsy** [comment]
@delucs In the menu on the left under the Resource section, there is a Volume option. This is where you create the volume. Then when you create the container, you attach the volume to `/hoobs`.

**Comment by mkellsy** [comment]
@rmohsenn Check the home pin and username in the config. These need to be different from your Homebridge instance. We use the same default values as Homebridge.

**Comment by delucs** [comment]
There is no option top create anything in the VOLUME section
![image](https://user-images.githubusercontent.com/7610744/75715298-7a696500-5ccd-11ea-9df1-2507a167970b.png)

**Comment by delucs** [comment]
..and when i want to create a new container, it takes the old one... local. I could pull the latest but I cannot find a a valid name

![image](https://user-images.githubusercontent.com/7610744/75715501-c916ff00-5ccd-11ea-9939-3e28ed9ed578.png)
****

**Comment by rmohsenn** [comment]
@mkellsy tired that , no luck

**Comment by mkellsy** [comment]
@delucs I did a Google search on how to setup a shared volume for a container
1. Create a shared folder
![](https://blog.linuxserver.io/content/images/2017/06/chrome_2017-06-05_21-33-57.png)

2. In this image they called their folder appdata
![](https://blog.linuxserver.io/content/images/2017/06/chrome_2017-06-05_21-36-37.png)

3. Once the shared folder is created add a sub folder called "hoobs"
![](https://blog.linuxserver.io/content/images/2017/06/chrome_2017-06-05_21-37-41.png)
Note their screenshot they called the folder "tvheadend" use "hoobs" instead.

4. Create your container and pull hoobs/hoobs:latest
![](https://blog.linuxserver.io/content/images/2017/04/chrome_2017-04-08_00-58-06.png)
Set the name and then click Advanced Settings

5. Under the Shared Folders section add the volume
![](https://blog.linuxserver.io/content/images/2017/04/chrome_2017-04-08_01-11-47.png)
Set the Volume from Host to `/appdata/hoobs` and set the Mount Point to `/hoobs`

This is from this site
https://blog.linuxserver.io/2017/09/17/how-to-setup-containers-on-qnap/

**Comment by mkellsy** [comment]
@rmohsenn Do you have port 51826 mapped to the container? In my examples I show mapping port 8080, but not 51826.

**Comment by delucs** [comment]
@mkellsy  great! but I have a running container with data, plugins etc. where are my data (i did not create this shared folder) n? when I installed it i just pulled the container (latest) and installed it. when I now try to install a new one from the docker hub , it seems to me Container Station wants to use the one that is already downloaded (old node) . is docker hub not updated yet?
![image](https://user-images.githubusercontent.com/7610744/75717299-282a4300-5cd1-11ea-9d79-b4418029a120.png)

**Comment by rmohsenn** [comment]
@mkellsy this is my settings for both hoobs and the docker container in unraid, port is mapped correctly 
<img width="591" alt="Screen Shot 2020-03-02 at 11 05 25 PM" src="https://user-images.githubusercontent.com/34405822/75717741-6841f380-5cda-11ea-927a-41b5fda7756d.png">
<img width="673" alt="Screen Shot 2020-03-02 at 11 05 07 PM" src="https://user-images.githubusercontent.com/34405822/75717753-6d06a780-5cda-11ea-8a19-9d8e543c573f.png">

**Comment by mkellsy** [comment]
@delucs unfortunately that is in a disposable volume. You will have to backup your config. Then reinstall the plugins after you create a new container.

Good news is, if you setup the shared folder, you won't have to do it again.

**Comment by mkellsy** [comment]
@rmohsenn You said you also had a Homebridge container? It is using port 51826? You could try to change the Apple Home bridge port to 5**2**826 and then map that port. Then see if it can pair to HomeKit.

**Comment by delucs** [comment]
@mkellsy ok, I see. not a big deal to reinstall all. I have backup of the config, but also a system backup, does this help? Will I lose anything on my iphone? or will all this be transparent for the iphone?
How can I pull the latest container from github, it seems my system thinks it already has the latest

**Comment by mkellsy** [comment]
System backups are not Docker compatible. You will need to reinstall the plugins.

**Comment by rmohsenn** [comment]
@mkellsy I got it working , gave the hoobs container a seperate ip than my unraid server and it worked , thanks a lot for all the help

**Comment by mkellsy** [comment]
@rmohsenn Thanks no problem

**Comment by delucs** [comment]
@mkellsy  I finaly found the time to try to setup a new docker. Unfortunately it cannot work, as this Dockerversion does not have a backup import (config). I even tried to copy the contents and replace the one that'sn created by default, but then there is an error and will not save, maybe because i do not have the plugins installed....
