### ISSUE TITLE
ffmpeg built into 3.1.20

### ISSUE THREAD

**Issue by JazzerAlto** [hoobs-org/HOOBS#472]
**Description**
We now have ffmpeg built directly into the 3.1.20 ARM 7 image.
If you don't want to reflash you can install the pre-compiled ffmpeg with this command.

wget -q -O - http://bit.ly/get-hoobs | sudo bash -
Note. This will only work on Raspbian on a newer pi with the armv7l architecture.

I tried this on my 3b and it did not work meaning no sound on my Ring cameras and ffmpeg showing in the log
**Version**
3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

Not sure, whatever the latest 3.x version image I had downloaded a while back but it was a 3.x version I started with

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Ring - Hoobs Certified
Roborock - Hoobs Certified
Roomba STV

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYD2LO",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "",
        "username": ""
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Roomba",
            "name": "Roomba",
            "model": "e5",
            "blid": "",
            "robotpwd": ":",
            "ipaddress": "192.168.100.205",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "cacheTTL": 30,
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            }
        },
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "roborock",
                "index": 0
            },
            "name": "1st Floor Roborock Vacuum",
            "pause": true,
            "dock": true,
            "ip": "192.168.100.207",
            "token": ""
        },
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "roborock",
                "index": 0
            },
            "name": "2nd Floor Roborock Vacuum",
            "pause": true,
            "dock": true,
            "ip": "192.168.100.208",
            "token": ""
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "email": "",
            "password": "",
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": true,
            "hideInHomeDoorbellSwitch": true,
            "hideUnsupportedServices": true
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[Homebridge] [2/8/2020, 09:23:15] [Ring] Preparing Live Stream for Right Side Backyard
[Homebridge] [2/8/2020, 09:23:15] [Ring] Streaming video only - ffmpeg was not found
[Homebridge] [2/8/2020, 09:23:16] [Ring] Waiting for stream data from Right Side Backyard (0.86s)
[Homebridge] [2/8/2020, 09:23:16] [Ring] Received stream data from Right Side Backyard (1.085s)
[Homebridge] [2/8/2020, 09:23:16] [Ring] Streaming active for Right Side Backyard
```

**Additional context**
I saw no errors when I ran wget -q -O - http://bit.ly/get-hoobs | sudo bash - and I also do a full reboot just to be sure.  No change in result.  No audio from Ring cameras

I ended up going the long way around and doing a full ffmpeg compile per this link 

https://github.com/dgreif/ring/wiki/FFmpeg#homebridge-audio-support

This did allow audio to work on my Ring

**Comment by mkellsy** [comment]
The command is
```
wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
```

The script you are running is to install HOOBS.

**Comment by JazzerAlto** [comment]
I was following the command that was published from the high temp thread that was just closed:

From #400 

mkellsy commented on Jan 9

We now have ffmpeg built directly into the 3.1.20 ARM 7 image.If you don't want to reflash you can install the pre-compiled ffmpeg with this command.wget -q -O - http://bit.ly/get-hoobs \| sudo bash - Note. This will only work on Raspbian on a newer pi with the armv7l architecture.
--

**Comment by mkellsy** [comment]
Yes. That was an older issue. Part of the reason why I closed it because ffmpeg has nothing to do with that issue.

**Comment by JazzerAlto** [comment]
Right but that’s why I opened a new issue per your direction. I’m just saying running the command to load the pre compiled ffmpeg on a HOOBS upgraded to 3.1.20 didn’t work.

**Comment by mkellsy** [comment]
The command is
```
wget -q -O - http://bit.ly/**get-ffmpeg** | sudo bash -
```

Not **get-hoobs**

**Comment by JazzerAlto** [comment]
Understood.  I was just following the command I saw in the other posting.

**Comment by JazzerAlto** [comment]
No errors with the command but I had already changed course and manually compiled.  I ran the command you gave above to confirm if it popped up any issues.  Sound was working fine from my Ring cameras after I executed the wget.

hoobs@hoobs:~/.hoobs/etc $ wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
Hit:1 https://dl.yarnpkg.com/debian stable InRelease
Get:2 http://archive.raspberrypi.org/debian buster InRelease [25.1 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:4 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
Get:5 http://archive.raspberrypi.org/debian buster/main armhf Packages [277 kB]
Fetched 13.3 MB in 11s (1,160 kB/s)                                            
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtool is already the newest version (2.4.6-9).
libtool-bin is already the newest version (2.4.6-9).
libx264-dev is already the newest version (2:0.155.2917+git0a84d98-2+rpi1).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Installing FFMPEG
Configuring
FFMPEG is installed
hoobs@hoobs:~/.hoobs/etc $
