### ISSUE TITLE
No option to restore .hbf files - Hoobs Docker

### ISSUE THREAD

**Issue by diegocjorge** [hoobs-org/HOOBS#475]
**Description**
I have the option to download a backup, but there is no option to restore an existing backup
![hoobs1](https://user-images.githubusercontent.com/58111081/74114105-e94c1600-4b86-11ea-892f-4706fb626ff2.jpg)
![hoobs2](https://user-images.githubusercontent.com/58111081/74114107-eb15d980-4b86-11ea-9d0d-c9a1499ea70a.jpg)

**Version**
Version 3.1.20 (Docker)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian Buster - RPi 4

**Comment by mkellsy** [comment]
This is not a bug, it is by design. Docker uses volumes so the backup should be handled by your Docker host.

HOOBS for Docker uses a different file structure and this doesn't have this feature. We are looking to add this in a future version.
