### ISSUE TITLE
Issue on cameras Onvif

### ISSUE THREAD

**Issue by adrianopery** [hoobs-org/HOOBS#476]
Hi guys, first of all thanks for your job and share the knowledge about homebridge.
I installed HOOBs a few days ago and added my LG TVs and my Yamaha receiver.
I tried to install my ONVIF cameras using  camera-ffmpeg plugin.
In the firs moment I had problem but after many tries I could add 2 of 4 cameras I have.
So I tried to remove the plugin and install other version available on the plugin list, but after that, I could NEVER add my cameras.
After install the plugin, I can't find the device on my iPhone when I add new accessory.

Do you have any idea?

Thanks in advance.

**Comment by mkellsy** [comment]
1. You need to install the homebridge-ffmpeg plugin.
2. Then you need to run this command in the terminal
```
wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
```
3. Configure the homebridge-ffmpeg plugin.

**Comment by adrianopery** [comment]
Thanks for you support mkellsy.
I did exactly what you suggested and I received some errors on Terminal, as you can see below.

hoobs@hoobs:~/.hoobs/etc $ wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
Obter:1 https://dl.yarnpkg.com/debian stable InRelease [17,1 kB]
Err:1 https://dl.yarnpkg.com/debian stable InRelease                           
  As seguintes assinaturas eram inválidas: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
Atingido:2 http://archive.raspberrypi.org/debian buster InRelease              
Atingido:3 http://raspbian.raspberrypi.org/raspbian buster InRelease           
Baixados 17,1 kB em 22s (776 B/s)                                       
Lendo listas de pacotes... Pronto
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: As seguintes assinaturas eram inválidas: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Falhou ao buscar https://dl.yarnpkg.com/debian/dists/stable/InRelease  As seguintes assinaturas eram inválidas: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Falhou o download de alguns ficheiros de índice. Foram ignorados ou os antigos foram usados em seu lugar.
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
libtool is already the newest version (2.4.6-9).
libtool-bin is already the newest version (2.4.6-9).
libx264-dev is already the newest version (2:0.155.2917+git0a84d98-2+rpi1).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 25 não atualizados.
Installing FFMPEG
Configuring
FFMPEG is installed
hoobs@hoobs:~/.hoobs/etc $

**Comment by adrianopery** [comment]
> 1. You need to install the homebridge-ffmpeg plugin.
> 2. Then you need to run this command in the terminal
> 
> ```
> wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
> ```
> 
> 1. Configure the homebridge-ffmpeg plugin.

Thanks for you support mkellsy.
I did exactly what you suggested and I received some errors on Terminal, as you can see below.

hoobs@hoobs:~/.hoobs/etc $ wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
Obter:1 https://dl.yarnpkg.com/debian stable InRelease [17,1 kB]
Err:1 https://dl.yarnpkg.com/debian stable InRelease                           
  As seguintes assinaturas eram inválidas: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
Atingido:2 http://archive.raspberrypi.org/debian buster InRelease              
Atingido:3 http://raspbian.raspberrypi.org/raspbian buster InRelease           
Baixados 17,1 kB em 22s (776 B/s)                                       
Lendo listas de pacotes... Pronto
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: As seguintes assinaturas eram inválidas: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Falhou ao buscar https://dl.yarnpkg.com/debian/dists/stable/InRelease  As seguintes assinaturas eram inválidas: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Falhou o download de alguns ficheiros de índice. Foram ignorados ou os antigos foram usados em seu lugar.
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
libtool is already the newest version (2.4.6-9).
libtool-bin is already the newest version (2.4.6-9).
libx264-dev is already the newest version (2:0.155.2917+git0a84d98-2+rpi1).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 25 não atualizados.
Installing FFMPEG
Configuring
FFMPEG is installed
hoobs@hoobs:~/.hoobs/etc $

**Comment by askovi** [comment]
Try deleting your cached accessories and persist. Go the Terminal in the HOOBS UI and type these 2 commands and press enter after each:
**sudo rm -rf accessories**
**sudo rm -rf persist**

Then restart service from top right menu and try adding your cameras again. Also make sure you don't have any config error and that HOOBS is running. Post your logs if it isn't.

**Comment by adrianopery** [comment]
> Try deleting your cached accessories and persist. Go the Terminal in the HOOBS UI and type these 2 commands and press enter after each:
> **sudo rm -rf accessories**
> **sudo rm -rf persist**
> 
> Then restart service from top right menu and try adding your cameras again. Also make sure you don't have any config error and that HOOBS is running. Post your logs if it isn't.

Hi Askovi thanks. 
It works and I could add my 4 cameras on App Home.

Just a question....
When I remove my cash I misse my TVs and receiver on App Home, now they are as "No Service". 
Should I need to add these devices again?

**Comment by askovi** [comment]
Yes, when you delete the cached accessories and persist, it removes all your saved accessories. Everything needs to be added again.

**Comment by adrianopery** [comment]
> Yes, when you delete the cached accessories and persist, it removes all your saved accessories. Everything needs to be added again.

Sorry for many questions....
I'm new on HOOBS.

On HOOBS.local page I still can control my devices, only on iPhone I can't.
There is any way to re-send the devices to iPhone or only uninstall on HOOBS dashboard and re-install?

**Comment by askovi** [comment]
Easiest way would be to just go to Top right menu, click Help then click Reset Connection. Then refresh the Dashboard page and rescan the QR code.

**Comment by adrianopery** [comment]
> Easiest way would be to just go to Top right menu, click Help then click Reset Connection. Then refresh the Dashboard page and rescan the QR code.

Thanks for your support. I did the process you suggested and now everything is working fine.
