### ISSUE TITLE
Hoobs.local not resolving on PC

### ISSUE THREAD

**Issue by journeyofthought** [hoobs-org/HOOBS#477]
Hoobs.local is not resolving on my PC - I get the error:

This site can’t be reachedhoobs.local’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

However, it works just fine if I go to Windows Explorer --> Network --> right click Hoobs --> View Device Webpage. It does load by IP.

**Comment by mkellsy** [comment]
Your PC is not using Apple Bonjour. try http://hoobs.net or http://hoobs

**Comment by askovi** [comment]
You can also download the Apple Bonjour service for Windows, install and restart your PC after: https://support.apple.com/kb/DL999?locale=en_US

**Comment by journeyofthought** [comment]
I do have bonjour installed - from the link you indicated. I installed that before installing hoobs. It shows up in the windows add/remove programs as Bonjour 2.0.2.0 and Bonjour Print Services 2.0.2.0.

I just tried and neither http://hoobs.lan or http://hoobs works.

**Comment by mkellsy** [comment]
Do you know the IP address of the Pi?

You can always use http://1922.168.x.x where 192.168.x.x is the ip address of the Pi.

**Comment by journeyofthought** [comment]
Is the pi's address static then? I guess as long as it is, then thats fine - if not though its just easier to use hoobs.local (otherwise I have to lookup the IP every time).

**Comment by askovi** [comment]
You can assign it as static from your router's admin page. You can reserve it based on the MAC address of the Pi.
