### ISSUE TITLE
Unable to install Pi-Hole

### ISSUE THREAD

**Issue by stephenmd** [hoobs-org/HOOBS#478]
**Description**
Unable to install pihole as there is an issue with the certificates being used for curl. if curl doesnt work, there is no way to finish the installation as you get an certificates error of curl: (60) SSL certificate problem: unable to get local issuer certificate and if you try an alternate method to get the installer to show you get 
"[i] Checking for existing FTL binary...
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[i] Checksums do not match, downloading from ftl.pi-hole.net.
[✗] Downloading and Installing FTL
Error: Unable to get latest release location from GitHub
[✗] FTL Engine not installed"  

therefore the FTL Engine isnt installed. Pi hole worked in previous versions of hoobs but now im unable to get it to work. I was told this by pi hole devs themselves and a hoobs member directed me to open this issue. none of the alternate methods work as you cant get passed installing the FTL Engine.

**Version**
3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Previous version**
3.1.19

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi 3 Model B+ release 10 codename buster kernel 4.19.97-v7+

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023NJRZ19JC2",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "111-14-333",
        "username": "78:A3:1E:D3:E1:9E"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Smartglass",
            "name": "STEPHENSONEX",
            "ipAddress": "<>",
            "liveId": "<FD0057FEE931999B>"
        },
        {
            "name": "Pi Temp",
            "updateInterval": 1000,
            "accessory": "RaspberryPiTemperature"
        },
        {
            "accessory": "Broadband",
            "maxTime": 120,
            "interval": 120,
            "name": "Broadband"
        }
    ],
    "platforms": [
        {
            "name": "Sonos",
            "service": "fan",
            "speakers": true,
            "platform": "ZP"
        },
        {
            "hubIP": "",
            "refreshTimer": 240,
            "skipedIfSameStateActivities": false,
            "name": "Steph's Harmony Hub",
            "showTurnOffActivity": true,
            "platform": "HarmonyHubWebSocket"
        },
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "ip": "192.168.86.36",
                    "refresh": true,
                    "name": "Stephen's TV",
                    "mac": "84:C0:EF:03:63:4A",
                    "token": "13588084"
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Desk",
                    "manufacturer": "WYZE",
                    "model": "Wyze Cam Pan",
                    "serialNumber": "2CAA8E2D4675",
                    "firmwareRevision": "4.29.4.41",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://stephenmd:marcel23@/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://stephenmd:marcel23@1/live -vframes 1 -r 1",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "vcodec": "h264_omx",
                        "audio": false,
                        "debug": true
                    }
                },
                {
                    "name": "OFFICE DOOR",
                    "manufacturer": "WYZE",
                    "model": "Wyze Cam Pan",
                    "serialNumber": "2CAA8E2D43A8",
                    "firmwareRevision": "4.29.4.41",
                    "videoconfig": {
                        "source": "-rtsp_transport tcp -i rtsp://Stephenmd:Typeaphoto@/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://Stephenmd:Typeaphoto@/live -vframes 1 -r 1",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "vcodec": "h264_omx",
                        "audio": false,
                        "debug": true
                    }
                }
            ]
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
After some research, this is due to some renaming with cURL. It is best to update cURL.

These steps will get the updated ca root certificate from Firefox.
```
curl --remote-name --time-cond cacert.pem https://curl.haxx.se/ca/cacert.pem
```

Then run the Pi Hole command with the new --cacert
```
curl -sSL --cacert cacert.pem https://install.pi-hole.net | sudo bash
```

**Comment by mkellsy** [comment]
Try this command
```
sudo update-ca-certificates
```

It should work on Raspbian.
Then try to install.

```
curl -sSL https://install.pi-hole.net | sudo bash
```

**Comment by mkellsy** [comment]
This looks like an issue with the ca root for Let's Encrypt, it's a server configuration issue with Pi Hole. I am looking for a way around this. For the meantime try this command.

```
curl -k https://install.pi-hole.net | sudo bash
```

**Comment by stephenmd** [comment]
Wow Thank you so much for this Michael!! I actually ended up getting another raspberry pi but this is very good for other HOOBS owners who would like to run it along with pihole 

Stephen M. Diplan

**Comment by pelted** [comment]
Sorry for reviving a closed issue, but this didn't actually resolve the problem. I'm having the same issue on a fresh Hoobs image, then apt update/upgrade trying to get Pihole to install, but getting stuck on the same spot. I found some other possible solutions that disabled nginx and moved hoobs to 8080, but still this same issue FTL

**Comment by mkellsy** [comment]
Please open a new issue. This issue was mis-titled. It was actually SSL issues, not Pi-Hole itself.
