### ISSUE TITLE
Remove the Reboot option from Docker Version

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#483]
If you click on reboot in the web interface of HOOBS, which runs as a docker, the docker will shut down instead of being restarted.

-Reported by customer-

**Comment by delucs** [comment]
Docker Hoobs v 3.10.3 is running Hoobs 3.1.20 on a 4.14.24 QNAP Kernel

**Comment by mkellsy** [comment]
The reboot should be removed from the Docker version. You don't reboot a container, you rebuild it.

**Comment by mkellsy** [comment]
I found that in some circumstances, a user could break out of docker mode. I changed this in 3.1.21 that will prevent this from happening.
