### ISSUE TITLE
Ring Plugin Error connecting to API

### ISSUE THREAD

**Issue by lirand84** [hoobs-org/HOOBS#487]
I get the following error in the log:

[Homebridge] [2/21/2020, 2:26:31 PM] Got SIGINT, shutting down service...
[Homebridge] [2/21/2020, 2:26:32 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [2/21/2020, 2:26:34 PM] Loaded plugin: "ring"
[Homebridge] [2/21/2020, 2:26:34 PM] Registering platform "homebridge-ring.Ring"
[Homebridge] [2/21/2020, 2:26:34 PM] Loading 1 platforms...
[Homebridge] [2/21/2020, 2:26:34 PM] [Ring] Initializing Ring platform...
[Homebridge] [2/21/2020, 2:26:34 PM] Loading 0 accessories...
[Homebridge] [2/21/2020, 2:26:34 PM] API launched
[Homebridge] [2/21/2020, 2:26:34 PM] Service is running on port 51826.
[Homebridge] [2/21/2020, 2:26:37 PM] [Ring] Error connecting to API
[Homebridge] [2/21/2020, 2:26:37 PM] [Ring] TypeError: Cannot read property 'filter' of undefined
    at RingApi.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/api.js:104:18)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hoobs/.hoobs/node_modules/@hoobs/ring/lib/api/api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

I successfully retrieved the token via ring-auth-cli and saved it in the configuration.
Ring Plugin Version 6.1.1
Hoobs Version 3.1.20

**Comment by donavanbecker** [comment]
I bet it’s because of the new changes to requiring refresh token.

**Comment by mkellsy** [comment]
Plugin updated to 7.0.0

**Comment by lirand84** [comment]
> Plugin updated to 7.0.0

I installed the update to 7.0.0. Still the same mistake.

**Comment by askovi** [comment]
Please post your advanced config. Remove any passwords and remove some characters from the access tokens.

**Comment by lirand84** [comment]
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": „X-HM://?????????“,
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "21035"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": „??:??:??:??:??:??“
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "refreshToken": „??????????????????????????????????????????????????“,
            "locationIds": []
        }
    ]
}

**Comment by lirand84** [comment]
> Please post your advanced config. Remove any passwords and remove some characters from the access tokens.

{
"server": {
"port": 8080,
"origin": "*",
"autostart": 0,
"home_setup_id": „X-HM://?????????“,
"polling_seconds": 5
},
"client": {
"default_route": "status",
"inactive_logoff": 30,
"theme": "hoobs-dark",
"locale": "de",
"temp_units": "celsius",
"country_code": "DE",
"postal_code": "21035"
},
"bridge": {
"name": "HOOBS",
"port": 51826,
"pin": "031-45-154",
"username": „??:??:??:??:??:??“
},
"description": "",
"ports": {},
"accessories": [],
"platforms": [
{
"platform": "Ring",
"refreshToken": „??????????????????????????????????????????????????“,
"locationIds": []
}
]
}

**Comment by donavanbecker** [comment]
Try removing the ring config and then readding it

**Comment by lirand84** [comment]
> Try removing the ring config and then readding it

I've tried that several times. I also switched the 2fa on and off in the Ring app. Always the same mistake.

**Comment by donavanbecker** [comment]
Are you re adding the same code?

**Comment by lirand84** [comment]
> Are you re adding the same code?

I get a new code every time via email. With that I get the new token.

**Comment by lirand84** [comment]
Today I restarted hoobs and it worked.  I was able to integrate my doorbell into homekit.  Unfortunately I cannot see a live video in Homekit.  Do I have to set anything else for the live video?
