### ISSUE TITLE
Plugin Not Found in HOOBS Search?

### ISSUE THREAD

**Issue by a-rodriguez** [hoobs-org/HOOBS#489]
**Description**

I am trying to install a plugin https://github.com/MikeManzo/homebridge-weather-plus, when I search for this plugin in HOOBS it returns another plugin by the same name https://github.com/naofireblade/homebridge-weather-plus. The one I want to install was forked from the one that is returned by HOOBS. Without getting into why two plugins have the same name, how do I install the one I want into HOOBS?

**Expected behavior**

I should be able to find https://github.com/MikeManzo/homebridge-weather-plus when I search for homebridge-weather-plus.

**Plugin name**
homebridge-weather-plus

**Please report the issue to the plugin developer**
OK

**Version**
3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
N/A

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
N/A

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install - Installed off the image download.

**Comment by mkellsy** [comment]
We are working on a different plugin search repository.npm.com is not reliable. It does work in our new system.
https://plugins.hoobs.org/search/aG9tZWJyaWRnZS13ZWF0aGVyLXBsdXM

**Comment by a-rodriguez** [comment]
> We are working on a different plugin search repository.npm.com is not reliable. It does work in our new system.
> https://plugins.hoobs.org/search/aG9tZWJyaWRnZS13ZWF0aGVyLXBsdXM

That is not the one I am looking for.

**Comment by mkellsy** [comment]
2 plugins can not have the same name. homebridge-weather-plus belongs to naofireblade. MikeManzo will need to rename his plugin.

This is not an issue with our search tool.
