### ISSUE TITLE
Chamberlin Secure Video

### ISSUE THREAD

**Issue by inforatio** [hoobs-org/HOOBS#490]
The newest Chamberlin openers provide for support "Secure Video" in addition to remote opening/closing using MyQ.  Can you update your plug-in to support this new feature so that users don't have to go back and forth between apps? And all functionality can be accesses through Apple Home?

https://www.chamberlain.com/garage-door-openers/secure-view-camera-opener

**Comment by mkellsy** [comment]
You will need to make this feature request with the plugin developer
https://github.com/caseywebdev/homebridge-chamberlain
