### ISSUE TITLE
Livestream is not working

### ISSUE THREAD

**Issue by lirand84** [hoobs-org/HOOBS#491]
I set up my Ring Doorbel Pro using the homebridge-ring plugin. Hoobs version 3.1.20. Plugin version 7.0.0. I generated refresh tokens via npx -p ring-client-api ring-auth-cli and saved them in the plugin settings. Snapshot works very well in the iPhone HomeKit app. Unfortunately, the live feed does not work. UPnP is switched on in my modem. I have carried out all the points from the "[Camera Troubleshooting](https://github.com/dgreif/ring/wiki/Camera-Troubleshooting)" instructions. Unfortunately, the live feed still doesn't work.

[Homebridge] [2/24/2020, 5:05:38 AM] [Ring] Preparing Live Stream for Haustür
[Homebridge] [2/24/2020, 5:05:38 AM] [Ring] Waiting for stream data from Haustür (0.863s)
[Homebridge] [2/24/2020, 5:05:48 AM] [Ring] Stopped Live Stream for Haustür

**Comment by mkellsy** [comment]
I upgraded our ffmpeg build to include more libs. This should fix your issue.
```
wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
```

Note this will only work on a Raspberry Pi 3B and 4B.
