### ISSUE TITLE
Can't Download HOOBS, where's the link?

### ISSUE THREAD

**Issue by bgiuriceo** [hoobs-org/HOOBS#495]
After A GREAT run, I awoke this morning to this:
: EIO: i/o error, stat '/home/hoobs/.hoobs/dist/index.html'

(looks like the SD failed?)

Totally unresponsive and not working after a power cycle also. i went to download HOOBS to potentially start again and can't find a download link? I've donated in the past...do I need to donate again? My 'account' doesn't provide a way to retrieve the code either.

**Comment by BobbySlope** [comment]
https://github.com/hoobs-org/HOOBS/releases
