### ISSUE TITLE
apt-get update - error - signature - EXPKEYSIG 23E7166788B63E1E Yarn Packaging

### ISSUE THREAD

**Issue by handy80** [hoobs-org/HOOBS#499]
**Description**
login ssh with user hoobs: 
"sudo apt-get update" 
shows errors on signatures for 

**Version**
3.1.20 ARM7

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card (to download)
- [] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
no plugins yet, fresh installation

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
hoobs@hoobs:~ $ sudo apt-get update
OK:1 http://archive.raspberrypi.org/debian buster InRelease
Holen:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB]
Holen:3 https://dl.yarnpkg.com/debian stable InRelease [17,1 kB]                   
**Fehl:3** https://dl.yarnpkg.com/debian stable InRelease
  Die folgenden Signaturen waren ungültig: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
Es wurden 15,0 kB in 1 s geholt (9.984 B/s).
Paketlisten werden gelesen... Fertig
W: Während der Überprüfung der Signatur trat ein Fehler auf. Das Depot wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: https://dl.yarnpkg.com/debian stable InRelease: Die folgenden Signaturen waren ungültig: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Fehlschlag beim Holen von https://dl.yarnpkg.com/debian/dists/stable/InRelease Die folgenden Signaturen waren ungültig: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
```

**Additional context**

**Comment by handy80** [comment]
ok, the following three commands worked to solve the issue but I don't close the bug as the original image from your website contains still this outdated definition.

`wget -O yarnpkg.gpg.pub https://dl.yarnpkg.com/debian/pubkey.gpg
gpg yarnpkg.gpg.pub #just check the expired date of the key
sudo apt-key add yarnpkg.gpg.pub`
source: [https://github.com/yarnpkg/yarn/issues/4453](url)

**Comment by mkellsy** [comment]
Debian changed Yarn's GPG key. Run this command to update the key.
```
curl -ksS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
```

This will auto fix itself on the next build.
