### ISSUE TITLE
Ring Plugin Not Responding for Flood Light Camera

### ISSUE THREAD

**Issue by KinshukON** [hoobs-org/HOOBS#500]
**Description**
I updated my RING plugin. And Flood Light Camera stopped responding

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
HOOBS plugin for Ring doorbells, cameras, security alarm system and smart lighting.

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Please post your log

**Comment by mkellsy** [comment]
I updated the plugin version to 7.2.0. if you have further issues please open an issue with the plugin developer.
https://github.com/dgreif/ring

**Comment by KinshukON** [comment]
Thanks for the suggestion. I was missing the authentication key. Instead, I was providing the authentication message. My bad.
