### ISSUE TITLE
Unhandled Rejection "Error: Cannot find module './controllers/accessories'

### ISSUE THREAD

**Issue by calebcaudill** [hoobs-org/HOOBS#504]
I restarted my MacBook Air and now HOOBS will not start. This is the full error I get:

[3/2/2020, 4:01:26 AM] Unhandled Rejection "Error: Cannot find module './controllers/accessories'
Require stack:
- /Users/cc/.hoobs/lib/api.js
- /Users/cc/.hoobs/lib/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs".
(node:597) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

**Comment by mkellsy** [comment]
Delete the `/Users/cc/.hoobs/lib` folder and restart HOOBS.

You can do this in Finder or by running this command in the terminal
```
rm -fR /Users/cc/.hoobs/lib
```

**Comment by calebcaudill** [comment]
Ran the command and restarted HOOBS, it ran and looked to be fixing some modules and then I get the same error back.

**Comment by mkellsy** [comment]
OK.

Maybe the install got botched. Try this

First
```
rm -fR /Users/cc/.hoobs/lib
```
Again.

Then
```
sudo npm install -g --unsafe-perms @hoobs/hoobs
```

Then restart HOOBS.

**Comment by calebcaudill** [comment]
Thank you, back up and running. Weird that it was running find for weeks until I restarted this. I am guessing I can just repeat these steps if it happens again.

**Comment by mkellsy** [comment]
HOOBS is developed on a Mac, so those commands will work every time, until I change something :)
But we will let you know.
