### ISSUE TITLE
Updated to 3.1.22 and now I cannot login

### ISSUE THREAD

**Issue by schpeen** [hoobs-org/HOOBS#505]
**Description**
Updated to latest firmware and now my Hoobs service is running on my Pi and working but I cannot login anymore. I tried restarting service, rebooting and even using Admin login but nothing working and I know I am using the right credentials. Is there a way for me to reset password or user login??

**Version**
3.1.22
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Login via SSH with user: **hoobs** and password: **hoobsadmin**
then run this command: **sudo rm -rf /home/hoobs/.hoobs/etc/access.json**
Then run this to reboot: **sudo reboot**
You will be prompted to create a new admin user when it comes back up. You won't lose any plugins or config.

**Comment by schpeen** [comment]
Might be a silly question but how do I SSH? Do i just go directly to IP address like I always do? my Hoobs is running on a Pi.

**Comment by askovi** [comment]
On a mac use the Terminal app and type:
ssh hoobs@hoobs.local
Type yes to confirm the key then type the password hoobsadmin (you won’t see it being typed as a security measure)

On Windows use Putty

**Comment by schpeen** [comment]
Yeah just not working....when I try that I get nothing the hoobs.local never works for me why I have go directly to IP address. Even in terminal if I ssh @192.168.x.xxx I get a prompt for a password but nothing works tried the hoobsadmin, tried my old password, tried raspberry pi basic password all say invalid. Guess I will just have to re do it all over again which is such a bummer all my stuff was working great too.

**Comment by askovi** [comment]
It’s ssh hoobs@192.168.x.x
Then password: hoobsadmin

**Comment by schpeen** [comment]
YES!! You're awesome....that worked. You guys are so great with helping I really appreciate it and learned a lot in here.

**Comment by askovi** [comment]
You’re welcome 😊
