### ISSUE TITLE
No snapshot image for Yi Camera under camera-ffmpeg plugin

### ISSUE THREAD

**Issue by Fookes74** [hoobs-org/HOOBS#506]
**Description**
Have recently changed from using camera-ffmpeg-omx to camera-ffmpeg for my two Yi Cameras - both flashed with Yi Hack V4. Running latest HOOBS version 3.1.22. On the old omx plugin I had video (albeit 'choppy') and regular snapshots automatically refreshing every 10-15 seconds.  On installing the new camera-ffmpeg plugin I have managed to get both cameras working in terms of video (and much better quality thanks to changing to 'vcodec: copy' but the snapshots have stopped working. They generally only refresh now when I open up the live video and close it again. Sometimes they don't even refresh then. The curious thing is that one of the cameras, when first re-added in the new plugin, worked as it should do and refreshed every 10-15 seconds. This was evidenced in the logs which repeatedly came up with this on every refresh:

[Camera ffmpeg] Snapshot from Garage Cam at 480x270
[Homebridge] ffmpeg -rtsp_transport tcp -re -i rtsp://192.168.1.XX/ch0_1.h264 -t 1 -s 480x270 -f image2 -

After rebooting the Pi to try and force the other camera to refresh it actually then stopped the one working camera from refreshing! It hasn't taken any snapshots since. 

**Expected behavoir**
A snapshot to be taken every 10-15 seconds without opening the video stream.

**Plugin name**
camera-ffmpeg

**Please report the issue to the plugin developer**
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/437

**Version**
3.1.22

**Did you upgrade**
From previous version of 3.1.20

**Pervious version**
3.1.20

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Yes

**What device are you using?**
Custom Install

**If this is a custom install, what's your operating system?**
RPi 3

**Post your config**
[
    {
        "name": "Utility Room Cam",
        "manufacturer": "Yi Camera Home",
        "videoConfig": {
            "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.XX/ch0_1.h264",
            "maxStreams": 2,
            "maxWidth": 640,
            "maxHeight": 360,
            "maxFPS": 30,
            "maxBitrate": 200,
            "packetSize": 1128,
            "vcodec": "copy",
            "audio": false,
            "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
            "debug": true
        }
    },
    {
        "name": "Garage Cam",
        "manufacturer": "Yi Camera Dome",
        "videoConfig": {
            "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.XX/ch0_1.h264",
            "maxStreams": 2,
            "maxWidth": 640,
            "maxHeight": 360,
            "maxFPS": 30,
            "maxBitrate": 200,
            "packetSize": 1128,
            "vcodec": "copy",
            "audio": false,
            "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
            "debug": true
        }
    }
]
```

**Post your log**
[Homebridge] 2020-03-06T12:56:38.303Z hapNodeJSClient HAP Device discovered Utility Room Cam [ '192.168.1.XX', 'fe80::751b:37da:4066:xxxx' ]
[Homebridge] 2020-03-06T12:56:38.305Z hapNodeJSClient HAP instance address: Utility Room Cam -> 85_3F_0A_B4_XX_XX.local -> 192.168.1.XX:XXXXX
[Homebridge] 2020-03-06T12:56:38.309Z hapNodeJSClient HAP Device discovered Garage Cam [ '192.168.1.XX', 'fe80::751b:37da:4066:xxxx' ]
[Homebridge] 2020-03-06T12:56:38.310Z hapNodeJSClient HAP instance address: Garage Cam -> 9D_E3_7D_42_XX_XX.local -> 192.168.1.XX:XXXXX

**Additional context**
None

**Comment by BobbySlope** [comment]
need to be solved by plugindev, we can't do anything on HOOBS side for that
KhaosT/homebridge-camera-ffmpeg#437
