### ISSUE TITLE
HOOB's certified Roborock plugin update

### ISSUE THREAD

**Issue by ursusHU** [hoobs-org/HOOBS#508]
Update request of certified Roborock plugin.

The newer version also supports new Roborock vacuums like the S5 Max.

https://www.npmjs.com/package/homebridge-xiaomi-roborock-vacuum/v/0.7.2

**Comment by MikeDeltaHH** [comment]
Miss some updates of certified plugins like homebridge-hue, but think the developer are primerly working on the next hoobs major version and will be release no new versions of the certified plugins at this thime...

**Comment by BobbySlope** [comment]
@MikeDeltaHH and @ursusHU we are on that. After releasing the next major update, we will be able to update and certify plugins much faster.
