### ISSUE TITLE
Broadlink RM 3.6.22

### ISSUE THREAD

**Issue by Maciolus** [hoobs-org/HOOBS#509]
I've made a fresh HOOBS install due to Broadlink plugin dysfunction.

I've tried to install hap-nodejs with no luck.
I've tried to manually install previous versions of Broadlink plugin with no luck (it's invisible in HOOBS plugins.  
Same problem after apt-get upgrade and apt-get update commands.

Please help, I am not a pro Linux user.

Raspberry 3B
HOOBS: 3.1.20 (same issue with 3.1.22)
Homebridge 0.4.50
Node: 12.14.1

Config:
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY7D7G",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "59:46:E7:F7:77:7D"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}

Fresh HOOBS install Log:
[3/8/2020, 7:09:02 AM] HOOBS listning on port 8080.
[Homebridge] [3/8/2020, 7:09:04 AM] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [3/8/2020, 7:09:04 AM] No plugins found.
[Homebridge] [3/8/2020, 7:09:05 AM] Loading 0 platforms...
[Homebridge] [3/8/2020, 7:09:05 AM] Loading 0 accessories...
[Homebridge] [3/8/2020, 7:09:05 AM] API launched
[Homebridge] [3/8/2020, 7:09:05 AM] Service is running on port 51826.
[Homebridge] [3/8/2020, 7:10:45 AM] Got SIGINT, shutting down service...

> raw-socket@1.7.0 install /home/hoobs/.hoobs/node_modules/raw-socket
> node-gyp rebuild
make: Entering directory '/home/hoobs/.hoobs/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
In file included from ../src/raw.h:23,
                 from ../src/raw.cc:6:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../src/raw.h:21,
                 from ../src/raw.cc:6:
../src/raw.cc: At global scope:
/home/hoobs/.cache/node-gyp/12.14.1/include/node/node.h:560:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/hoobs/.cache/node-gyp/12.14.1/include/node/node.h:594:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/raw.cc:55:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(raw, InitAll)
 ^~~~~~~~~~~
In file included from /home/hoobs/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/hoobs/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/hoobs/.cache/node-gyp/12.14.1/include/node/node_object_wrap.h:84:78:   required from here
/home/hoobs/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hoobs/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/hoobs/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/raw.node
  COPY Release/raw.node
make: Leaving directory '/home/hoobs/.hoobs/node_modules/raw-socket/build'
npm
 notice created a lockfile as package-lock.json. You should commit this file.
+ homebridge-broadlink-rm@3.6.22
added 126 packages from 105 contributors and audited 1115 packages in 46.275s

15 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
Cannot find module 'hap-nodejs'
Require stack:
- /home/hoobs/.hoobs/node_modules/homebridge-platform-helper/dist/accessory.js
- /home/hoobs/.hoobs/node_modules/homebridge-platform-helper/dist/index.js
- /home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm/platform.js
- /home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm/index.js
- /home/hoobs/.hoobs/lib/plugins.js
- /home/hoobs/.hoobs/lib/controllers/system.js
- /home/hoobs/.hoobs/lib/api.js
- /home/hoobs/.hoobs/lib/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
Unable to determine plugin type for "homebridge-broadlink-rm"
[3/8/2020, 7:11:37 AM] Installed "homebridge-broadlink-rm" package.
Cannot find module 'hap-nodejs'
Require stack:
- /home/hoobs/.hoobs/node_modules/homebridge-platform-helper/dist/accessory.js
- /home/hoobs/.hoobs/node_modules/homebridge-platform-helper/dist/index.js
- /home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm/platform.js
- /home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm/index.js
- /home/hoobs/.hoobs/lib/plugins.js
- /home/hoobs/.hoobs/lib/controllers/system.js
- /home/hoobs/.hoobs/lib/api.js
- /home/hoobs/.hoobs/lib/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
Unable to determine plugin type for "homebridge-broadlink-rm"
[Homebridge] [3/8/2020, 7:11:38 AM] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [3/8/2020, 7:11:39 AM] Error Loading Plugin "homebridge-broadlink-rm"
[Homebridge] [3/8/2020, 7:11:39 AM] No plugins found.
[Homebridge] [3/8/2020, 7:11:39 AM] Loading 0 platforms...
[Homebridge] [3/8/2020, 7:11:39 AM] Loading 0 accessories...
[Homebridge] [3/8/2020, 7:11:39 AM] API launched
[Homebridge] [3/8/2020, 7:11:39 AM] Service is running on port 51826.

**Comment by BobbySlope** [comment]
Thus issue should be solved with version 3.1.23 released later this day

**Comment by IT-Lueg** [comment]
Hello,
the new version has not been released yet, or ?
I still have v3.1.22.

And unfortunately I have exactly the same problem :/

**Comment by Maciolus** [comment]
Try version 3.5.5

I went back to Homebridge with UI X

Maciej
