### ISSUE TITLE
Cant update Hoobs from 3.1.20 to 3.1.22

### ISSUE THREAD

**Issue by monza258** [hoobs-org/HOOBS#514]
Hello Guys, I will update from 3.1.20 to 3.1.22 but it dosn't work.

Version
3.1.20

Also cant update direct via terminal 
wget -q -O - http://bit.ly/get-hoobs | sudo bash -

 ```
pi@raspberrypi:~ $ wget -q -O - http://bit.ly/get-hoobs | sudo bash -

Thank You for choosing HOOBS
---------------------------------------------------------
Node Version 12.13.1
Updating Repositories
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Fetched 15.0 kB in 1s (19.8 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u1).
git is already the newest version (1:2.20.1-2+deb10u1).
tar is already the newest version (1.30+dfsg-6).
The following package was automatically installed and is no longer required:
  point-rpi
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 147 not upgraded.

Restarting HOOBS
```

Hoobs shows i have a new update

**Comment by mkellsy** [comment]
The `wget -q -O - http://bit.ly/get-hoobs | sudo bash -` command is for installing Node and HOOBS. It doesn't upgrade HOOBS.

Please run this command
```
sudo npm install -g --unsage-perms @hoobs/hoobs
```

If you get an error please post it to this issue.

**Comment by mkellsy** [comment]
I am trying to reproduce. I need to know some information.
1. What device are you using?
2. What is your operating system?
3. What plugins are you using?

I was able to upgrade without issue from 3.1.20 to 3.1.22.

**Comment by monza258** [comment]
> The `wget -q -O - http://bit.ly/get-hoobs | sudo bash -` command is for installing Node and HOOBS. It doesn't upgrade HOOBS.
> 
> 
> 
> Please run this command
> 
> ```
> 
> sudo npm install -g --unsafe-perms @hoobs/hoobs
> 
> ```
> 
> 
> 
> If you get an error please post it to this issue.

I get some errors 


`pi@raspberrypi:~ $ sudo npm install -g —unsage-perms @hoobs/hoobs
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> bufferutil@4.0.1 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil
> node-gyp-build

gyp WARN EACCES current user („nobody“) does not have permission to access the dev dir „/root/.cache/node-gyp/12.13.1“
gyp WARN EACCES attempting to reinstall using temporary dev dir „/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil/.node-gyp“
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir ‚/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil/.node-gyp‘
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command „/usr/local/bin/node“ „/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js“ „rebuild“
gyp ERR! cwd /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutilgyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

> node-pty@0.9.0 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
> node scripts/install.js

gyp WARN EACCES current user („nobody“) does not have permission to access the dev dir „/root/.cache/node-gyp/12.13.1“
gyp WARN EACCES attempting to reinstall using temporary dev dir „/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/.node-gyp“
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir ‚/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/.node-gyp‘
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command „/usr/local/bin/node“ „/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js“ „rebuild“
gyp ERR! cwd /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@4.0.1 (node_modules/@hoobs/hoobs/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@4.0.1 install: `node-gyp-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.9.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-14T21_33_38_276Z-debug.log
pi@raspberrypi:~ $ 
`

**Comment by mkellsy** [comment]
OK it looks like NPM is to blame. Run these commands and then try again.

First clear the NPM cache
```
sudo rm -fR /root/.npm
sudo rm -fR /root/.cache
```

Then uninstall and reinstall HOOBS (Triggers a GYP rebuild)
```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perms @hoobs/hoobs
```

> Note: If you get an error uninstalling, just move on to the install.

**Comment by monza258** [comment]
```
pi@raspberrypi:~ $ sudo rm -fR /root/.npm
pi@raspberrypi:~ $ sudo rm -fR /root/.cache
pi@raspberrypi:~ $ sudo npm uninstall -g @hoobs/hoobs
up to date in 0.063s
pi@raspberrypi:~ $ sudo npm install -g --unsafe-perms @hoobs/hoobs
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> bufferutil@4.0.1 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil
> node-gyp-build

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.13.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil/.node-gyp'
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

> node-pty@0.9.0 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
> node scripts/install.js

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.13.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/.node-gyp'
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@4.0.1 (node_modules/@hoobs/hoobs/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@4.0.1 install: `node-gyp-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.9.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-15T07_07_32_573Z-debug.log
pi@raspberrypi:~ $
```

**Comment by monza258** [comment]
sudo npm i @hoobs/hoobs -g --unsafe-perm 

DONE

**Comment by mkellsy** [comment]
@monza258 did you get HOOBS updated?

After reading the issue on node-gyp's repo. It looks like this fixes the issue.
```
sudo npm_config_user=root npm install -g --unsafe-perms @hoobs/hoobs
```

> Note you should only have to run `npm_config_user=root` this seems to fix the NPM Nobody issue.
