### ISSUE TITLE
Hoobs on SSD

### ISSUE THREAD

**Issue by stfiston** [hoobs-org/HOOBS#515]
Hello, is it possible to install Hoobs on a SSD and boot on it with a raspberry pi 3B?

**Comment by mkellsy** [comment]
HOOBS is an SD Card image. You can download from here.
https://github.com/hoobs-org/HOOBS/releases/tag/v3.1.22

Flash it to an SD Card using something like the balinaEtcher.

Here are the docs
https://github.com/hoobs-org/HOOBS/wiki/2.2-HOOBS-SD-Card

**Comment by stfiston** [comment]
I allready do that but I prefer the Solid State Drive. If I clone my sd card it is possible to run Hoobs on the Drive
