### ISSUE TITLE
hoobs and plex server together 

### ISSUE THREAD

**Issue by rrrfedeli** [hoobs-org/HOOBS#516]
**Description**
need assistance to install plex server on a raspberry working with hoobs (installed by hoobs image file)

I tried doing by following this tutorial working with ssh terminal but i found many error during the installation
https://thepi.io/how-to-set-up-a-raspberry-pi-plex-server/

**Comment by mkellsy** [comment]
Those instructions are old. Raspbian is now on Buster not Jessie.

HOOBS and Plex do not have conflicting ports, so it is fine to install together.

1. Start with the latest HOOBS image 3.1.22+ (SSL is fixed)
https://github.com/hoobs-org/HOOBS/releases/tag/v3.1.22

2. Follow updated instructions
https://linuxize.com/post/how-to-install-plex-media-server-on-raspberry-pi/
