### ISSUE TITLE
Ability to delete Ghost Devices in UI (selective cached accessories removing)

### ISSUE THREAD

**Issue by delucs** [hoobs-org/HOOBS#518]
**Description**
A lot of users including me, have what I call ghost devices in the HOME window (favourite window).
Those are often gateways like Phoscon, but in my case also some SonoffRF Buttons. There is no way to delete them from that screen (disable "show in favourite" has no effect). They are persistent.
I found a solution , but it opens an other problem/bug... when opening the problematic devices you see that the BRIDGE says a different room than set? changing it to the correct room, has no effect, but now disable "show in favourite has an effect?... 

**Version**
Please include the version of HOOBS you are using.
3.1.22
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Docker on QNAP
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Duplicate. Using #539 it has more than nfo
