### ISSUE TITLE
After server port change and reboot: Bad Gateway - Error 502 

### ISSUE THREAD

**Issue by nbaosullivan** [hoobs-org/HOOBS#519]
**Description**
After changing the server port from `8080` to `8081` in the HOOBS interface and rebooting, when I visit http://hoobs.local/ it's stuck on the loading screen, and in the network tab I see that it's receiving a 502 error.

**Version**
HOOBS 3.1.22 - Raspberry Pi 1B, 2B and Zero W

**Did you upgrade**
- [ ] Yes
- [x] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
- [ ] Yes
- [x] No

**What device are you using?**
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
- `homebridge-tuya-lan`

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8081,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY4L3I",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "AB:36:33:B8:9C:B3"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-tuya-lan"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "TuyaLan",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-lan"
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
```
**Additional context**
I want to be able to run tuya-lan-find which uses port 8080 and can't configure any parameters when running this command.

**Comment by BobbySlope** [comment]
hoobs.local points via nginx to port 8080
To access hoobs with a changed port you need to define the port to reach like hoobs.local:8081 in your case
