### ISSUE TITLE
Nest Plugin not Showing Accessories

### ISSUE THREAD

**Issue by maswind** [hoobs-org/HOOBS#520]
**Description**
A clear and concise description of what the plugin is doing.

The plugin is installed and running on My Raspberry Pi 4, but the accessories are not showing up. The only info in the config is the token info from logging into the web interface for my Nest account. I am still operating using my Nest account and have not shifted to Google. 

**Expected behavoir**
Please let us know what the plugin is supposed to do.

My thermostat, doorbell, and smoke detector should show up as accessories. 

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.

The plug in is Nest, the ferried plugin, version 4.4.0

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using. 3.0

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [n] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
  "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "nest"
            },
            "googleAuth": {
                "issueToken": "XXXX"
            }
        }
    ]
}```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Add any other context about the problem here.

**Comment by maswind** [comment]
Log:

[3/15/2020, 1:14:56 PM] HOOBS listening on port 8080.
[Homebridge] [3/15/2020, 1:14:57 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [3/15/2020, 1:14:57 PM] Loaded plugin: "nest"
[Homebridge] [3/15/2020, 1:14:57 PM] Registering platform "nest.Nest"
[Homebridge] [3/15/2020, 1:14:57 PM] Loading 1 platforms...
[Homebridge] [3/15/2020, 1:14:57 PM] [Nest] Initializing Nest platform...
[Homebridge] [3/15/2020, 1:14:57 PM] [Nest] Fetching Nest devices.
[Homebridge] [3/15/2020, 1:14:57 PM] Loading 0 accessories...
[Homebridge] [3/15/2020, 1:14:57 PM] API launched
[Homebridge] [3/15/2020, 1:14:57 PM] [Nest] When using googleAuth, you must provide issueToken, cookies and apiKey in config.json. Please see README.md for instructions
[Homebridge] [3/15/2020, 1:14:57 PM] Service is running on port 51826.

**Comment by askovi** [comment]
Error is clear in the logs: [Nest] When using googleAuth, you must provide **issueToken**, **cookies** and **apiKey** in config.json. Please see README.md for instructions
You only have issueToken. You must also put the apiKey and the cookies. Watch this video for more instructions: https://www.youtube.com/watch?v=nX5ztcGnRUQ

**Comment by maswind** [comment]
Thank You Ovidu

After a couple of tries, I got the config right and the thermostat and smoke alarm are showing in HomeKit. 


Thank you for the assistance!!!


Tim

**Comment by askovi** [comment]
Glad you got it working!

**Comment by maswind** [comment]
Thanks Again!
