### ISSUE TITLE
Plug-in failure 

### ISSUE THREAD

**Issue by jpjandrucko** [hoobs-org/HOOBS#521]
**Description**

When searching for plug in I get kick out and requested to log in

![D2EFC56B-EA27-4FD6-A1CB-7D9888C7C236](https://user-images.githubusercontent.com/62253007/76772020-361aa200-676e-11ea-8f9e-fb518d6b0505.jpeg)

**Version**
Please include the version of HOOBS you are using.

3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

![image](https://user-images.githubusercontent.com/62253007/76772226-88f45980-676e-11ea-8577-13fb5b33988a.jpg)

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
What plugin were you serching for? Also can you copy and paste your log to this task. The Chrome console screenshot only shows that the websocket is not there. The log is more helpful.

**Comment by jpjandrucko** [comment]
A few different plugs, none showed up before I was logged out and taken back to the login page.  

What do need me to run to get the needed logs?

**Comment by jpjandrucko** [comment]
So funny think. Reset my router and that fixed it. Sorry for the goose chase
