### ISSUE TITLE
FFMPEG Binary Moved Need to Update Script

### ISSUE THREAD

**Issue by IT-Lueg** [hoobs-org/HOOBS#522]
Description
Cant get the "Ring Plugin" working with ffmpeg

already tried:
wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
Note. This will only work on Raspbian on a newer pi with the armv7l architecture.

I tried this on my 4B and it did not work meaning no sound on my Ring cameras and ffmpeg showing in the log,

Did you upgrade
Please let us know if you upgraded from a previous version.

[X ] Yes
 No

List your plugins
Ring - Hoobs Certified
Wol
Hue
Tplink Smarthome
Loxone Ws Adv

Post your config
This can be found in the interface, Configuration -> Advanced or you can get it via SSH cat ~/.hoobs/etc/config.json

Remove any passwords from the config file. This is public.

{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY1L75",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "AT",
        "postal_code": "4020"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "03:C9:73"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "NetworkDevice",
            "name": "PC Sonja",
            "ip": "192.168.1.6",
            "mac": "60:a4:4c",
            "plugin_map": {
                "plugin_name": "homebridge-wol",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "LoxoneWs",
            "name": "Loxone",
            "host": "192.168.1.9",
            "port": "80",
            "username": "Username",
            "password": "",
            "plugin_map": {
                "plugin_name": "homebridge-loxone-ws"
            }
        },
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        },
        {
            "platform": "Hue",
            "users": {
                "001788FFF": "QN-ZXhnHlijRPNbgX"
            },
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "lights": "true",
            "anyOn": true,
            "forceCt": true
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "email": "<mail>",
            "password": "<pw>",
            "refreshToken": "<token>"
        }
    ]
}

Post your log
You can get the log from the intercafe. This is in the Log section.

> [Homebridge] [3/17/2020, 07:49:32] [Ring] Snapshot for Haupteingang Requested
> [Homebridge] [3/17/2020, 07:49:33] [Ring] Snapshot for Haupteingang Received (1.885s)
> [Homebridge] [3/17/2020, 07:49:34] [Ring] Preparing Live Stream for Haupteingang
> [Homebridge] [3/17/2020, 07:49:34] [Ring] Streaming video only - ffmpeg was not found
> [Homebridge] [3/17/2020, 07:49:34] [Ring] Waiting for stream data from Haupteingang (0.798s)
> [Homebridge] [3/17/2020, 07:49:35] [Ring] Received stream data from Haupteingang (1.774s)
> [Homebridge] [3/17/2020, 07:49:36] [Ring] Streaming active for Haupteingang
> [Homebridge] [3/17/2020, 07:49:39] [Ring] Stopped Live Stream for Haupteingang

Additional context
Output of "_wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -_":

> Hit:1 http://archive.raspberrypi.org/debian buster InRelease
> Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
> Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
> Err:2 https://dl.yarnpkg.com/debian stable InRelease
>   The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
> Reading package lists... Done
> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
> W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Note, selecting 'libfontconfig1-dev' instead of 'libfontconfig-dev'
> frei0r-plugins-dev is already the newest version (1.6.1-2).
> libass-dev is already the newest version (1:0.14.0-2).
> libfontconfig1-dev is already the newest version (2.13.1-2).
> libfreetype6-dev is already the newest version (2.9.1-3+deb10u1).
> libfribidi-dev is already the newest version (1.0.5-3.1+deb10u1).
> libmp3lame-dev is already the newest version (3.100-2+b1).
> libopus-dev is already the newest version (1.3-1).
> librubberband-dev is already the newest version (1.8.1-7).
> libsoxr-dev is already the newest version (0.1.2-3).
> libspeex-dev is already the newest version (1.2~rc1.2-1+b2).
> libtheora-dev is already the newest version (1.1.1+dfsg.1-15).
> libtool is already the newest version (2.4.6-9).
> libtool-bin is already the newest version (2.4.6-9).
> libvidstab-dev is already the newest version (1.1.0-2).
> libvorbis-dev is already the newest version (1.3.6-2).
> libvpx-dev is already the newest version (1.7.0-3+deb10u1).
> libwebp-dev is already the newest version (0.6.1-2).
> libx264-dev is already the newest version (2:0.155.2917+git0a84d98-2+rpi1).
> libxml2-dev is already the newest version (2.9.4+dfsg1-7+b3).
> libxvidcore-dev is already the newest version (2:1.3.5-1).
> openssl is already the newest version (1.1.1d-0+deb10u2+rpt1).
> 0 upgraded, 0 newly installed, 0 to remove and 50 not upgraded.
> Installing FFMPEG
> --2020-03-17 07:52:59--  https://github.com/hoobs-org/hoobs-gen/raw/master/stage5/00-install-ffmpeg/files/ffmpeg.tar.gz
> Resolving github.com (github.com)... 140.82.118.4
> Connecting to github.com (github.com)|140.82.118.4|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2020-03-17 07:52:59 ERROR 404: Not Found.
> 
> Configuring
> FFMPEG is installed

**Comment by mkellsy** [comment]
Our FFMPEG binary moved due to some changes in our build process.

You can tun this again and it should work
```
wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
```
