### ISSUE TITLE
Can't Login With Keyboard Input

### ISSUE THREAD

**Issue by Palmermatic** [hoobs-org/HOOBS#523]
**Description**
Using tab and enter on the login page is unsuccessful.  Neither the login button nor Remember Me checkbox have a tabindex.

**Version**
3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.1?

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian

**Comment by mkellsy** [comment]
We removed the "Remember Me"  checkbox from the tab flow by design, for security reasons. The Login button doesn't need a tab index because the Enter key submits the form if you are focused on any of the fields in the login form.
