### ISSUE TITLE
Can not connect to hoobs.local

### ISSUE THREAD

**Issue by Cattango** [hoobs-org/HOOBS#525]
**Description**
Unable to connect to hoobs.local after initial installation.

**Version**
Hoobs 3.1.20 (Stable) - Raspberry Pi 3B+

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
N/A

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X] Custom Install

**If this is a custom install, what's your operating system?**
Mac OS Mojave 10

```
POST LOG HERE
```

**Additional context**
Please help with this fix. Thanks in advance!

**Comment by BobbySlope** [comment]
some network routers don't allow .local adresses:

try the following:
//hoobs
hoobs.lan

or just enter the IP Adress of your Pi in the browser
