### ISSUE TITLE
Eero Pro and Hoobs

### ISSUE THREAD

**Issue by douggainous** [hoobs-org/HOOBS#531]
Eero updated to support Homekit Secure Routers and I can no longer access hoobs.local and all of the hoobs plugins like ring cameras no longer are working.  Any suggestions?

**Comment by askovi** [comment]
Open the Network Security of the HOOBS bridge and set it to Automatic or No Restriction instead of Restrict to Home
![image](https://user-images.githubusercontent.com/3981552/77677680-68927f00-6f66-11ea-88b3-15c068e0a91a.png)

**Comment by douggainous** [comment]
It was already set to automatic.  I had deleted out the devices that were not working and I wanted to add them back in, but I can’t access the Hoobs interface any longer.  Any thoughts on this?

**Comment by askovi** [comment]
Set it to No Restriction for the HOOBS bridge in the Hubs & Bridges section then try to access it again

**Comment by douggainous** [comment]
I discovered the my HOOBS device does not have the Homebridge service running and I have not been able to get it to work.  I have disabled Homekit in my router, rebooted the network, clicked on Start Service, and tried power cycling the hoobs device.  I am not able to get the service to run.

**Comment by askovi** [comment]
Check your logs. Probably something misconfigured.

**Comment by mkellsy** [comment]
I just released 3.1.27
This issue has been fixed.
I recommend updating.
