### ISSUE TITLE
Daikin Local not working with HOOBS 3.1.23

### ISSUE THREAD

**Issue by phastier** [hoobs-org/HOOBS#532]
**Description**
Migration from 3.1.20 to 3.1.23, plugin crashes HOOBS and prevents startup.

**Expected behavoir**
Working :)

**Plugin name**
Daikin Local

**Please report the issue to the plugin developer**
[Homebridge] [3/27/2020, 6:10:09 PM] Error: The requested accessory 'Daikin-Local' was not registered by any plugin.
    at API.accessory (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:45:19)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:258:48)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[Homebridge] [3/27/2020, 6:10:10 PM] Got SIGTERM, shutting down service...

**Version**
3.1.23

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
3.1.20

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian 9 on Raspberry Pi 3B+

Config file

   "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY9FO9",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "fr",
        "temp_units": "celsius",
    },
    "bridge": {
        "name": "Homebridge",
        "username": "5E:55:FC:BB:EE:A0",
        "port": 51826,
        "pin": "***-**-***"
    },
    "description": "Home Smart Home",
    "ports": {},
    "accessories": [
        {
            "name": "Chambre Pierre",
            "apiroute": "http://192.168.0.59",
            "accessory": "Daikin-Local"
        },
        {
            "name": "Bureau",
            "apiroute": "http://192.168.0.61",
            "accessory": "Daikin-Local"
        },
        {
            "name": "Cuisine",
            "apiroute": "http://192.168.0.56",
            "accessory": "Daikin-Local"
        },
        {
            "name": "Salon",
            "apiroute": "http://192.168.0.55",
            "accessory": "Daikin-Local"
        },
        {
            "name": "Chambre Parents",
            "apiroute": "http://192.168.0.57",
            "accessory": "Daikin-Local"
        }
    ],
    "platforms": [
        {
            "platform": "Nest",
            "email": "*******",
            "password": "*******",
            "access_token": "*******",
            "name": "Nest",
            "googleAuth": {},
            "options": []
        }
    ]
}

**Comment by phastier** [comment]
Still no idea ?

It looks like something is preventing the plugin from loading. Location issue ? Rights issue ?

**Comment by mkellsy** [comment]
We are working on an updated version that can handle plugins designed for the new version of HB.

**Comment by phastier** [comment]
Great news ! :) Thanks.

**Comment by mkellsy** [comment]
I just released 3.1.27
This issue has been fixed.
I recommend updating.

**Comment by phastier** [comment]
Update fails for me, because of 3 invalid password attempts. Is that a known issue ? How can I fix it ?

**Comment by mkellsy** [comment]
You have a few options
1. Run hooks with the -p 'your password' you will need to edit your /etc/systemd/system/hoobs.service file
2. Add NOPASSWD to the admin group in your /etc/sudoers file.

**Comment by phastier** [comment]
IT WORKED. :) Thank you so much.
