### ISSUE TITLE
problem with installing Hoobs in a raspi-all-in-one system (in lcx container)

### ISSUE THREAD

**Issue by gitigit6** [hoobs-org/HOOBS#533]
hi, have a raspi-all-in-one-image in use (it is CCU3-Homematic, iO-Broker and Homebridge .. in two lxc containers)  
there are three ports in use :8081, :8082 and the last :8083 for Homebridge!!!
When I install HOOBS via manual installation: support.hoobs.org/docs/5e763edfe87d1e02b6c19d38
it seems to be installed parallel to the existing homebridge, and when I boot, unfortunately the "old" (existing) homebridge again starts on port :8083  .... ports 8080,8081,8082 do not work .... HOOBS also doesn't start.
(by the way, the last step of installation "sudo hoobs-init" is not executed (get error messag "command not found")

PS: existing homebridge is  located in: "home/pi/.homebridge" (with "dot")

**Comment by gitigit6** [comment]
hi, another way to request my 'existing homebridge' to 'hoobs' installation problems:
-the existing homebridge runs on port 8083  (HOOBS usually on port 8080) ... how do i get hoobs to install under the same port 8083 ?
the existing homebridge is located in: "home/pi/.homebridge", I think HOOBS installs in  usr/bin and /usr/lib/node_modules/@hoobs/hoobs  .... how do I get HOOBS to install on the existing path, or is this not necessary ?
.... any opinion or infos regarding this?

**Comment by gitigit6** [comment]
hi there, I*m glad that now hoobs is installed and works, but it does not work by restart (even it shows on HDMI-plugged display "hoobs startet" , but it is not reachable by IP-Adress .... to get it reachable I have every time to type in; "hoobs init" --- any ideas to solve that?

**Comment by mkellsy** [comment]
hoobs init creates a service in /etc/systemd/system. It also installs NGINX, and uses a proxy. You can start hoobs by just running hoobs. You can change the port in the config file ~/.hoobs/etc/config.json.

HOOBS needs to run from a user account.

**Comment by mkellsy** [comment]
You may need to use our Docker container
https://hub.docker.com/repository/docker/hoobs/hoobs
