### ISSUE TITLE
Delete Single Accessories from Persist Directory

### ISSUE THREAD

**Issue by Nate872711** [hoobs-org/HOOBS#539]
**Description**
When uninstalling a plugin, the accessory json files remain afterwards in the Persist Directory.  This usually only happens with the camera after removing it from the Home App.

The only solution is to manually remove them in the Hoobs terminal.

**Version**
3.1.23

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspian GNU/Linux 10

**List your plugins**
Nest
Ring
Tplink Smarthome

**Comment by BobbySlope** [comment]
we added this as an task for an future update

**Comment by kbardai** [comment]
@Nate872711 @BobbySlope 

> The only solution is to manually remove them in the Hoobs terminal.

Can you guys share the steps to remove a stale/stuck accessory from the terminal? I had to change out a switch and the older one is still showing in Home app.

Thanks

**Comment by mkellsy** [comment]
There's a Reset Connection button in the Help screen.
This will clear out the accessory cache. This will require re-pairing to HomeKit.

**Comment by kbardai** [comment]
@mkellsy thanks, I was aware of that option but that would require me to re-setup like 45+ accessories in homekit (mostly tp-link switches)...any way to edit/update the json file or is that too risky?

**Comment by mkellsy** [comment]
I am going to have to make this a feature request.

The accessory cache is located in /home/hoobs/.hoobs/etc/accessories. You can open the cache files and remove the accessories manually. These are simply .json files.

**Comment by BobbySlope** [comment]
@mkellsy would it be possible to bind those to bind those to the plugin? So if you uninstall the plugin they will be deleted?

Or binding them to accessories in the ui and be able to delete the accessory from ui?

**Comment by amery78** [comment]
Up ;)
Would be very useful to be able to delete specific accessories.
Reseting is not an option as we would need to re setup lots of accessories.
My cache becoming more and more dirty over time :(

**Comment by cuatexoft** [comment]
Please add this feature, Homebridge.io have it in the Homebridge settings section

**Comment by snorbik** [comment]
Yeah. Please reopen this issue and add this feature. :)

**Comment by mike4president** [comment]
Yes. That would be great...

**Comment by dmote75** [comment]
Would anyone have instructions on how to do this manually? I have no trouble messing around in Terminal, just don't know the commands.
Thanks

**Comment by WIMWG** [comment]
I have the same problem

**Comment by TeslaOwnerTips** [comment]
This is a BUG. If a plugin is removed the accessories also should get removed. Reset? Are you kidding? So we have to reprogram/configure 20 to 30 accessories ?
