### ISSUE TITLE
Camera Stream using SimpliSafe Plugin not Working

### ISSUE THREAD

**Issue by calebcaudill** [hoobs-org/HOOBS#541]
**Description**
Plugin will not stream video feed from camera.

**Expected behavior**
Plugin is suppose to stream video from camera.

**Plugin name**
Simplisafe3

**Please report the issue to the plugin developer**
https://github.com/nzapponi/homebridge-simplisafe3/issues/89

**Version**
3.1.23

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Previous version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": XXX,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "XXXXXXXXXXXX",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "XXXXX"
    },
    "bridge": {
        "name": "HOOBS",
        "port": XXXXX,
        "pin": "XXX-XX-XXX",
        "username": "XXXXXXXXXX"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "plugin_map": {
                "plugin_name": "homebridge-simplisafe3"
            },
            "name": "Home Alarm",
            "cameras": true,
            "sensorRefresh": 15,
            "persistAccessories": false,
            "resetSimpliSafeId": false,
            "auth": {
                "password": "XXXXX",
                "username": "XXXXX"
            },
            "debug": true,
            "cameraOptions": {
                "ffmpegPath": "/usr/local/bin/ffmpeg"
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[Homebridge] [4/6/2020, 7:24:53 PM] [Home Alarm] Start streaming video from Doorbell
[Homebridge] [4/6/2020, 7:24:53 PM] [Home Alarm] ffmpeg version N-96428-ga8ceb2a72f Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
[Homebridge] [4/6/2020, 7:24:53 PM] [Home Alarm]   libavutil      56. 38.100 / 56. 38.100
  libavcodec     58. 66.100 / 58. 66.100
  libavformat    58. 35.103 / 58. 35.103
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 71.100 /  7. 71.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[Homebridge] [4/6/2020, 7:24:54 PM] [Home Alarm] https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=1280: Protocol not found
Did you mean file:https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=1280?
[Homebridge] [4/6/2020, 7:24:54 PM] [Home Alarm] Error: FFmpeg exited with code 1
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] Handling snapshot for Doorbell at 480x270
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] Handling snapshot for Upstairs at 480x270
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] /usr/local/bin/ffmpeg-re,-headers,Authorization: Bearer y10iF8OU3JMR40ps3q1i/auYi3cIXa4HT3Hd0THJ4SI=,-i,https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=480,-t,1,-s,480x270,-f,image2,-vframes,1,-
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] Close Doorbell stream with image of length: 0
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] /usr/local/bin/ffmpeg-re,-headers,Authorization: Bearer y10iF8OU3JMR40ps3q1i/auYi3cIXa4HT3Hd0THJ4SI=,-i,https://52.87.36.43/v1/8591ad234de0a302fcbacd03700c05e1/flv?x=480,-t,1,-s,480x270,-f,image2,-vframes,1,-
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] Close Upstairs stream with image of length: 0
[Homebridge] [4/6/2020, 7:25:42 PM] [Home Alarm] Handling snapshot for Doorbell at 480x270
[Homebridge] [4/6/2020, 7:25:42 PM] [Home Alarm] /usr/local/bin/ffmpeg-re,-headers,Authorization: Bearer y10iF8OU3JMR40ps3q1i/auYi3cIXa4HT3Hd0THJ4SI=,-i,https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=480,-t,1,-s,480x270,-f,image2,-vframes,1,-
[Homebridge] [4/6/2020, 7:25:42 PM] [Home Alarm] Close Doorbell stream with image of length: 0
```

**Additional context**
Plugin worked fine on my previous HOOBS running on my MacBook Air. I purchased a Raspberry PI 4 4gb and installed HOOBS on the SD card. Same configuration. Now streaming won't work.

**Comment by calebcaudill** [comment]
So it seems the issue is that the included ffmpeg does not support HTTPS. How do I add HTTPS support?

**Comment by askovi** [comment]
Run this command in terminal: wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -

**Comment by calebcaudill** [comment]
**Output of above command:**

`hoobs@hoobs:/home/hoobs/.hoobs/etc $ wget -q -O - http://bit.ly/get-ffmpeg | sudo
o bash -
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]        
Hit:3 http://archive.raspberrypi.org/debian buster InRelease          
Err:2 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libfontconfig1-dev' instead of 'libfontconfig-dev'
frei0r-plugins-dev is already the newest version (1.6.1-2).
libass-dev is already the newest version (1:0.14.0-2).
libfontconfig1-dev is already the newest version (2.13.1-2).
libfreetype6-dev is already the newest version (2.9.1-3+deb10u1).
libfribidi-dev is already the newest version (1.0.5-3.1+deb10u1).
libmp3lame-dev is already the newest version (3.100-2+b1).
libopus-dev is already the newest version (1.3-1).
librubberband-dev is already the newest version (1.8.1-7).
libsoxr-dev is already the newest version (0.1.2-3).
libspeex-dev is already the newest version (1.2~rc1.2-1+b2).
libtheora-dev is already the newest version (1.1.1+dfsg.1-15).
libtool is already the newest version (2.4.6-9).
libtool-bin is already the newest version (2.4.6-9).
libvidstab-dev is already the newest version (1.1.0-2).
libvorbis-dev is already the newest version (1.3.6-2).
libvpx-dev is already the newest version (1.7.0-3+deb10u1).
libwebp-dev is already the newest version (0.6.1-2).
libx264-dev is already the newest version (2:0.155.2917+git0a84d98-2+rpi1).
libxml2-dev is already the newest version (2.9.4+dfsg1-7+b3).
libxvidcore-dev is already the newest version (2:1.3.5-1).
openssl is already the newest version (1.1.1d-0+deb10u2+rpt1).
openssl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
Installing FFMPEG
--2020-04-13 18:47:51--  https://github.com/hoobs-org/hoobs-gen/raw/master/stage7/00-install-ffmpeg/files/ffmpeg.tar.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-13 18:47:51 ERROR 404: Not Found.

Configuring
FFMPEG is installed`

**Restarted Raspberry Pi, then tried to open stream again:**

`[Homebridge] [4/13/2020, 6:46:51 PM] [Home Alarm] Start streaming video from Doorbell
[Homebridge] [4/13/2020, 6:46:51 PM] [Home Alarm] ffmpeg version N-96428-ga8ceb2a72f Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
[Homebridge] [4/13/2020, 6:46:51 PM] [Home Alarm]   libavutil      56. 38.100 / 56. 38.100
  libavcodec     58. 66.100 / 58. 66.100
  libavformat    58. 35.103 / 58. 35.103
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 71.100 /  7. 71.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
[Homebridge] [4/13/2020, 6:46:51 PM] [Home Alarm]   libpostproc    55.  6.100 / 55.  6.100
[Homebridge] [4/13/2020, 6:46:51 PM] [Home Alarm] https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
[Homebridge] [4/13/2020, 6:46:51 PM] [Home Alarm] https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=1280: Protocol not found
[Homebridge] [4/13/2020, 6:46:51 PM] [Home Alarm] Did you mean file:https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=1280?
[Homebridge] [4/13/2020, 6:46:51 PM] [Home Alarm] Error: FFmpeg exited with code 1`

**Comment by mkellsy** [comment]
Had to fix something on the server. Try the command again
```
wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
```

**Comment by calebcaudill** [comment]
Working great now, thanks!
