### ISSUE TITLE
Cant deinstall Shelly Plugin

### ISSUE THREAD

**Issue by Ace-li-k** [hoobs-org/HOOBS#542]
Hi, I cant deinstall my Shelly Plugin.
Click on deinstall in Hoobs and nothing will change. It shows also the is an update. 

If I run "sudo npm uninstall homebridge-shelly -g" in Terminal: Log says "up to date" ??

 Version: 
Hoobs: 3.1.23
Node: 12.13.1

**Comment by mkellsy** [comment]
HOOBS does not install plugins globally. Use the interface to uninstall or these commands.
```
cd ~/.hoobs
npm uninstall homebridge-shelly
```
