### ISSUE TITLE
Hoobs restarts from MacOS browser

### ISSUE THREAD

**Issue by coderandgentleman** [hoobs-org/HOOBS#543]
**Description**
Hello, I have an issue, where even with fresh install, if I'd try to access hoobs.local on my computer, no matter what browser, I could open page, but as soon as I'd start to type username hoobs would restart and I can't login. It seems to work on my iPhone browser and iPhone Home Assistant 2 app, but computer would always restart it.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] Custom Install

**If this is a custom install, what's your operating system?**
macOS Catalina

**List your plugins**
No plugins

**Post your config**
Can;t get to that yet

**Comment by mkellsy** [comment]
Are you using the same computer to access it as HOOBS is running on. If so, try http://localhost
