### ISSUE TITLE
Install npm serialport by default

### ISSUE THREAD

**Issue by odeckmyn** [hoobs-org/HOOBS#545]
You `should` provied serialport package by default (and modify boot.txt accordingly) as it is very difficult to install for a beginner

Today it's not included and it make usual plugins (rfxcom for instance) much more difficult to install.

**Comment by markwrightderby** [comment]
Hi :) can you offer any advice on how to do this manually ? im guessing this is why when I try to install the RFXcom plugin it fails. Iv tried to follow this https://support.hoobs.org/docs/5e763b63e87d1e02b6c19d2b
to install the serialport but I get loads of access permission denied

**Comment by BobbySlope** [comment]
We added this as an task for an future update
