### ISSUE TITLE
CPU Temp Historical Graph

### ISSUE THREAD

**Issue by heardv** [hoobs-org/HOOBS#546]
I would like to see the temperature sensor history in a graph much like CPU and Memory.

**Comment by BobbySlope** [comment]
we added that as an task for a future update

**Comment by heardv** [comment]
stale :(

**Comment by BobbySlope** [comment]
planned in a future update but not an issue, its an enhancement, so we can let stalebot close this

**Comment by heardv** [comment]
Thanks Bobby. Have a nice weekend :)
