### ISSUE TITLE
Problems with the hiveforever plug-in

### ISSUE THREAD

**Issue by treforparr** [hoobs-org/HOOBS#556]
It's not compatible or not working properly hoobs coding  really wanna plug-in for the Hive products that works with the thermostat

**Comment by mkellsy** [comment]
Can you post your logs. There's clues there that tell me what's going on.

**Comment by treforparr** [comment]
Just ordered a hob form HOOBS as I was using Linx and homeBridge what I would like to know is how do you enter the code for the Hive product or right your own plug in 


https://plugins.hoobs.org/plugin/homebridge-hive-forever <https://plugins.hoobs.org/plugin/homebridge-hive-forever>

I have try contact the developer is this code crashes the system on devices I've tried on several and the other one doesn't really work to I've asked on numerous forums no one is being helpful at all I have a hive thermostat in the UK really need a plug-in that works for it hive view CCTV cameras and other accessories I want to integrate them into (hoobs that's my mission) daughter to hoobo device it will be here in a few days as I have Samsung and Google stuff to I want to more integrated into Apple and this is the best feature,

Reply trefor.parr@me.com or trefor.parr@icloud.com
 all information is confidentiality,  Who the recipient all information is treated with high strict confidentiality rights and copyright

**Comment by mkellsy** [comment]
Can you post your logs. There's clues there that tell me what's going on.

**Comment by askovi** [comment]
Hi Trefor,
The Hive Forever plugin works with HOOBS. You just have to install it from the UI, then on the Config page, click Add Accessory (needs one accessory per device you want to add) then configure it like this:
![image](https://user-images.githubusercontent.com/3981552/79703064-47783200-8277-11ea-8ad5-2888a763dee2.png)

Replace the product with the device you want to add. Eg:

Dimmable Light: **HiveLight**
Active / Tunable Light: **HiveTunableLight**
SmartPlug: **HiveSmartPlug**
Thermostat: **HiveThermostat**
Thermostat Boost: **HiveThermostatBoost**

Replace display name with the name you want to show in the Home app, and add your username and password. 
**Note**: Please ensure that the name matches the name you have given to the device. For example if you have renamed your Light to John's Smart Plug, then you will need to replace "Plug 1" with "John's Smart Plug", the name is case-sensitive so please make sure you enter it correctly.

**Comment by treforparr** [comment]
I’ve been trying it on Lennox upstairs as well and I get the problem on hoobs this was done on home bridge and I got the problem on there as well but what he does it keeps rebooting the log, I have ordered a hoobs device Hoobs so I will try this code when it comes

**Comment by treforparr** [comment]
Tried a few plug-ins now for the hive noticed there is a problem with quite a few of them some of them crash the system some work okay but not very well I would love to develop my own maybe if some form I know it's quite hard to do but I think it might be worth it in the end, unless there's any developers out there who are up for the challenge I would like to see the hive  live view cameras as well as their lifestream,

**Comment by BobbySlope** [comment]
@treforparr We setup everything via screenshare and did a system backup
Please restore this and don’t touch hoobs
Until i reach you in Facebook Chat to solve the Google Home issue
