### ISSUE TITLE
Update from 3.1.23 to 3.1.27 fails with Sudo 3 incorrect password attempts

### ISSUE THREAD

**Issue by Andybishop** [hoobs-org/HOOBS#557]
**Description**
When attempting to update in the UI from 3.1.23 to 3.1.27 it fails, checking the log shows sudo: 3 incorrect password attempts.  This is on a ubuntu VM. 

**Version**
3.1.23

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ Y] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [N ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [C ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

Ubuntu 19.10

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Nest
Ring
Camera FFMPEG Rest Motion
Harmonyhub
Lightwaverf
Sonos

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYH5O1",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": "postcode"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-***",
        "username": "56:61:B5:15:35:54"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Sonos",
            "plugin_map": {
                "plugin_name": "homebridge-sonos",
                "index": 0
            },
            "name": "Son's Sonos",
            "room": "Son's Room"
        },
        {
            "accessory": "Sonos",
            "plugin_map": {
                "plugin_name": "homebridge-sonos",
                "index": 0
            },
            "name": "Bedroom Sonos",
            "room": "Bedroom"
        },
        {
            "accessory": "Sonos",
            "plugin_map": {
                "plugin_name": "homebridge-sonos",
                "index": 0
            },
            "name": "Kitchen Sonos",
            "room": "Kitchen"
        },
        {
            "accessory": "Sonos",
            "plugin_map": {
                "plugin_name": "homebridge-sonos",
                "index": 0
            },
            "name": "Living Room Sonos",
            "room": "Living Room"
        }
    ],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "nest"
            },
            "googleAuth": {
                "issueToken": "***issuetoken removed***",
                "cookies": "***Cookie removed***",
                "apiKey": "***API KEY***"
            }
        },
        {
            "platform": "Camera-ffmpeg",
            "name": "Camera ffmpeg",
            "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp",
            "videoProcessor": "ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg-rest-motion"
            },
            "cameras": [
                {
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://username:password@192.168.***.***/streaming/Channels/102/",
                        "audio": false,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "maxFPS": 10,
                        "debug": false,
                        "maxWidth": 1280,
                        "packetSize": 1316,
                        "maxHeight": 720,
                        "stillImageSource": "-i http://username:password@192.168.***.***/ISAPI/Streaming/channels/101/picture",
                        "maxStreams": 2
                    },
                    "manufacturer": "Hikvision",
                    "name": "Front Drive",
                    "model": "DS-2CD2055FWD-I"
                },
                {
                    "videoConfig": {
                        "debug": false,
                        "maxBitrate": 300,
                        "stillImageSource": "-i http://username:password@192.168.***.***/ISAPI/Streaming/channels/201/picture",
                        "packetSize": 1316,
                        "audio": false,
                        "maxFPS": 10,
                        "maxHeight": 720,
                        "maxWidth": 1280,
                        "source": "-rtsp_transport tcp -re -i rtsp://username:password@192.168.***.***/streaming/Channels/202/",
                        "vcodec": "libx264",
                        "maxStreams": 2
                    },
                    "manufacturer": "Hikvision",
                    "name": "Back Garden",
                    "model": "DS-2CD2055FWD-I"
                }
            ]
        },
        {
            "name": "LightWaveRF",
            "platform": "LightWaveRF",
            "devices": [
                {
                    "deviceType": "S",
                    "deviceName": "Scentsy",
                    "deviceId": 1,
                    "roomName": "Living Room",
                    "roomId": 2
                },
                {
                    "deviceType": "S",
                    "deviceName": "Lamp",
                    "deviceId": 2,
                    "roomName": "Living Room",
                    "roomId": 2
                },
                {
                    "deviceType": "S",
                    "deviceName": "Dehumidifier",
                    "deviceId": 1,
                    "roomName": "Bedroom",
                    "roomId": 1
                },
                {
                    "deviceType": "D",
                    "deviceName": "Light",
                    "deviceId": 1,
                    "roomName": "Hall",
                    "roomId": 5
                },
                {
                    "deviceType": "D",
                    "deviceName": "Light",
                    "deviceId": 2,
                    "roomName": "Landing",
                    "roomId": 5
                },
                {
                    "deviceType": "D",
                    "deviceName": "Light",
                    "deviceId": 5,
                    "roomName": "Son's Room",
                    "roomId": 3
                },
                {
                    "deviceType": "S",
                    "deviceName": "Bed Spare",
                    "deviceId": 4,
                    "roomName": "Son's Room",
                    "roomId": 3
                },
                {
                    "deviceType": "S",
                    "deviceName": "Star Lamp",
                    "deviceId": 3,
                    "roomName": "Son's Room",
                    "roomId": 3
                },
                {
                    "deviceType": "S",
                    "deviceName": "Spare1",
                    "deviceId": 1,
                    "roomName": "Son's Room",
                    "roomId": 3
                },
                {
                    "deviceType": "S",
                    "deviceName": "Extention",
                    "deviceId": 2,
                    "roomName": "Son's Room",
                    "roomId": 3
                },
                {
                    "deviceType": "D",
                    "deviceName": "Side Lights",
                    "deviceId": 1,
                    "roomName": "Outside",
                    "roomId": 4
                }
            ],
            "ip_address": "192.168.***.***",
            "plugin_map": {
                "plugin_name": "homebridge-lightwaverf"
            }
        },
        {
            "platform": "HarmonyHub",
            "name": "Harmony Hub",
            "plugin_map": {
                "plugin_name": "homebridge-harmonyhub"
            }
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "refreshToken": "***refreshtoken removed***",
            "email": "email address",
            "password": "password"
        }
    ]
}

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
You have 3 options.
1. Restart manually
2. Run HOOBS with the -p 'your password' you may need to edit the /etc/systems/system/hoobs.service file
3. Edit your /etc/sudoers file and add NOPASSWD to the admin group.

**Comment by Andybishop** [comment]
Thanks for getting back to me, What is the command for upgrading manually?

**Comment by mkellsy** [comment]
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```
