### ISSUE TITLE
Not showing updated on macOS (launchd)

### ISSUE THREAD

**Issue by jamezpowell** [hoobs-org/HOOBS#558]
I'm currently on version 3.1.23. When I try to upgrade to.27 it gives an error that my mkdirp needs to be updated. I've tried to update mkdirp manually but that didn't seem to work.

Hoobs will not start. The log shows services starting and devices being added, but then it just freezes and never starts the service.

"WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142 npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.) /usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

@hoobs/hoobs@3.1.27 postinstall /usr/local/lib/node_modules/@hoobs/hoobs bin/hoobs upgrade

@hoobs/hoobs@3.1.27 updated 1 package in 5.986s"

**Comment by jamezpowell** [comment]
Latest attempt:

"npm
WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> @hoobs/hoobs@3.1.27 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade
+ @hoobs/hoobs@3.1.27
updated 3 packages in 9.329s"

**Comment by mkellsy** [comment]
That's a warning, the bottom line states success
```
@hoobs/hoobs@3.1.27 updated 1 package in 5.986s"
```

**Comment by jamezpowell** [comment]
> That's a warning, the bottom line states success
> 
> ```
> @hoobs/hoobs@3.1.27 updated 1 package in 5.986s"
> ```

It still shows that I need to update though. And Hoobs won't start.
<img width="591" alt="Screen Shot 2020-04-20 at 10 30 15 PM" src="https://user-images.githubusercontent.com/26349971/79822469-d314c000-8356-11ea-9d54-02f7f38a1558.png">

**Comment by mkellsy** [comment]
Can you post more of the log? There's something else happening. The npm warning is common. Homebridge still uses that package and it doesn't stop the install.

**Comment by jamezpowell** [comment]
> Can you post more of the log? There's something else happening. The npm warning is common. Homebridge still uses that package and it doesn't stop the install.
> 
> You may just need to reboot.
It appears to load everything and then it cycles through this over and over. It still shows Hoobs as not running though, and I can't access the devices from homekit.

**[Homebridge] GOOD: Refreshing All Device Data
[Homebridge] NOTICE: Temperature Unit is Now: (F)
[Homebridge] NOTICE: Updating Global Values | HubIP: 192.168.1.xx | UseLocal: true
[Homebridge] WARN: Devices to Remove: (0) []
[Homebridge] INFO: Devices to Update: (22)
[Homebridge] GOOD: Devices to Create: (0) []
[Homebridge] ALERT: Total Initialization Time: (1 seconds)
[Homebridge] NOTICE: Unknown Capabilities: []
[Homebridge] INFO: SmartThings DeviceCache Size: (22)
[Homebridge] INFO: Checking Package Version for Updates...
[Homebridge] INFO: INFO: Your plugin version is up-to-date
[Homebridge] NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.2
[Homebridge] [4/20/2020, 10:43:06 PM] [Security System] Logging into Alarm.com as xxxxx
[Homebridge] [4/20/2020, 10:43:07 PM] [Security System] Logged into Alarm.com as xxxxx
[Homebridge] GOOD: Refreshing All Device Data
[Homebridge] NOTICE: Temperature Unit is Now: (F)
[Homebridge] NOTICE: Updating Global Values | HubIP: 192.168.1.xx | UseLocal: true
[Homebridge] WARN: Devices to Remove: (0) []
[Homebridge] INFO: Devices to Update: (22)
[Homebridge] GOOD: Devices to Create: (0) []
[Homebridge] ALERT: Total Initialization Time: (1 seconds)
[Homebridge] NOTICE: Unknown Capabilities: []
[Homebridge] INFO: SmartThings DeviceCache Size: (22)
[Homebridge] INFO: Checking Package Version for Updates...
[Homebridge] INFO: INFO: Your plugin version is up-to-date
[Homebridge] NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.2
[Homebridge] [4/20/2020, 10:44:02 PM] [Security System] Logging into Alarm.com as xxxxx
[Homebridge] [4/20/2020, 10:44:03 PM] [Security System] Logged into Alarm.com as xxxxx**

**Comment by mkellsy** [comment]
Can you run this command and post the results (do this just after it starts)
```
sudo hoobs service log
```

This has a bit more information in it.

**Comment by jamezpowell** [comment]
> Can you run this command and post the results (do this just after it starts)
> 
> ```
> sudo hoobs service log
> ```
> 
> This has a bit more information in it.

When I try to run that command it says that I must run hoobs service first. (I had already started the service from the dashboard) when I try to start hoobs from terminal I get the following:

james@homebridge ~ % hoobs
Writing package file
[4/22/2020, 8:54:00 PM] listen EADDRINUSE: address already in use :::8080
Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1306:16)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/lib/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/lib/cli.js:175:21)
[HOOBS] Stopping server.

**Comment by mkellsy** [comment]
The HOOBS service and the bridge service in the UI are different things. What I am talking about is lower level.

Can you run this command and post the results.
```
ls -la /etc/systemd/system
```

**Comment by jamezpowell** [comment]
> The HOOBS service and the bridge service in the UI are different things. What I am talking about is lower level.
> 
> 
> 
> Can you run this command and post the results.
> 
> ```
> 
> ls -la /etc/systemd/system
> 
> ```


ls: /etc/systemd/system: No such file or directory

**Comment by mkellsy** [comment]
What are you running this on? What OS?

**Comment by jamezpowell** [comment]
Mac OS Mojave

**Comment by mkellsy** [comment]
Did you set this up as a service? If so can you post the .plist file you created?

**Comment by jamezpowell** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.hoobs.core</string>
        <key>EnvironmentVariables</key>
        <dict>
            <key>PATH</key>
            <string><![CDATA[/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin]]></string>
            <key>HOME</key>
            <string>/var/root</string>
        </dict>
        <key>Program</key>
        <string>/usr/local/bin/hoobs</string>
        <key>ProgramArguments</key>
        <array>
            <string>/usr/local/bin/hoobs</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>SessionCreate</key>
        <true/>
    </dict>
</plist>

**Comment by jamezpowell** [comment]
> Did you set this up as a service? If so can you post the .plist file you created?

"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.hoobs.core</string>
        <key>EnvironmentVariables</key>
        <dict>
            <key>PATH</key>
            <string><![CDATA[/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin]]></string>
            <key>HOME</key>
            <string>/var/root</string>
        </dict>
        <key>Program</key>
        <string>/usr/local/bin/hoobs</string>
        <key>ProgramArguments</key>
        <array>
            <string>/usr/local/bin/hoobs</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>SessionCreate</key>
        <true/>
    </dict>
</plist>"

**Comment by mkellsy** [comment]
Can you add this to your post.
```
`````` xml
<xml here>
``````
```

**Comment by jamezpowell** [comment]
Changed it to a .txt file but this is the "com.hoobs.core.plist" file from my machine. I don't have a "com.hoobs.plist" file.
[com.hoobs.core.txt](https://github.com/hoobs-org/HOOBS/files/4533615/com.hoobs.core.txt)

**Comment by jamezpowell** [comment]
> Can you add this to your post.
> 
> ```
> ``` xml
> <xml here>
> ```
> ```

Sorry, I wasn't sure how to do that. Here you go.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.hoobs.core</string>
        <key>EnvironmentVariables</key>
        <dict>
            <key>PATH</key>
            <string><![CDATA[/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin]]></string>
            <key>HOME</key>
            <string>/var/root</string>
        </dict>
        <key>Program</key>
        <string>/usr/local/bin/hoobs</string>
        <key>ProgramArguments</key>
        <array>
            <string>/usr/local/bin/hoobs</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>SessionCreate</key>
        <true/>
    </dict>
</plist>
```

**Comment by mkellsy** [comment]
That looks good. To restart the service you need to use these commands
```
sudo launchctl unload /Library/LaunchDaemons/com.hoobs.core.plist
sudo launchctl load -w /Library/LaunchDaemons/com.hoobs.core.plist
```

**Comment by jamezpowell** [comment]
> That looks good. To restart the service you need to use these commands
> 
> ```
> sudo launchctl unload /Library/LaunchDaemons/com.hoobs.core.plist
> sudo launchctl load -w /Library/LaunchDaemons/com.hoobs.core.plist
> ```

So you can see that I restarted using the commands and that I still get the service not running error when trying to pull the service logs.
![Recents](https://user-images.githubusercontent.com/26349971/80287538-f6918f00-86f7-11ea-8eae-6a324cb509d4.png)

**Comment by jamezpowell** [comment]
Also, I get this when checking to see if hoobs is running:

james@homebridge ~ % sudo launchctl list | grep com.hoobs.core
50720	0	com.hoobs.core
james@homebridge ~ %

**Comment by mkellsy** [comment]
`sudo hoobs service` does not work with macOS it's a Linux command.

What's in the HomebridgeRestart.command?
Have you rebooted the entire computer?

Basically what I think is happening is, the serverce never restarted. If you run `hoobs -v` and it shows 3.1.27, then the proper binary is installed, and the service just needs to be restarted.

**Comment by jamezpowell** [comment]
It does show 3.1.27. 
The homebridgerestart comand is a script I created on the desktop to quickly run those two commands that kill and restart the service. I had it prior to switching to Phobos, biut

**Comment by jamezpowell** [comment]
After reboot the dashboard says that it is up to date, but the service still shows not running.
![14 15 16 17 18](https://user-images.githubusercontent.com/26349971/80288549-44a99100-86fe-11ea-9cd6-9d3a0eca9cb6.png)

It does show as a service running in Activity Monitor though.
![312 root](https://user-images.githubusercontent.com/26349971/80288562-555a0700-86fe-11ea-872c-b3e1f94c02bb.png)

**Comment by mkellsy** [comment]
What's the log say?
HOOBS is a service and Homebridge is a component to that.
We just call it a service in the UI, it's just a spawned process, and it is failing somehow.

Do you have vanilla Homebridge installed?

**Comment by jamezpowell** [comment]
> What's the log say?
> 
> HOOBS is a service and Homebridge is a component to that.
> 
> We just call it a service in the UI, it's just a spawned process, and it is failing somehow.
> 
> 
> 
> Do you have vanilla Homebridge installed?

I used to use vanilla, but switched to hoobs a fee months ago. I assume there's still some vanilla left on the machine, but I don't know how to fix that. It's been working fine up until now though. 

What log are you referring to? The hoobs dashboard log shows the plug-ins loading and starting, and the devices loading. If I change the status of a device via its native app or manually turn it on/off, the log shows those actions taking place. I'm just unable to control anything from Homekit an all devices show "No response" in the home app.

**Comment by jamezpowell** [comment]
![image](https://user-images.githubusercontent.com/26349971/80316828-b39ded00-87c5-11ea-8d39-63094088babe.png)

This is what I'm referring to. All hoobs managed devices are unavailable in Home app. Lifx, Hue, etc. that are natively homekit compatible are working fine.

**Comment by mkellsy** [comment]
You may simply have an old Homebridge service defined.
Can you run this command and post the results?
```
sudo ls -la /Library/LaunchDaemons
```

**Comment by jamezpowell** [comment]
> You may simply have an old Homebridge service defined.
> 
> Can you run this command and post the results?
> 
> ```
> 
> sudo ls -la /Library/LaunchDaemons
> 
> ```


Last login: Sat Apr 25 14:02:31 on console
james@homebridge ~ % sudo ls -la /Library/LaunchDaemons 
total 128
drwxr-xr-x  18 root  wheel   576 Jan 30 21:47 .
drwxr-xr-x  67 root  wheel  2144 Jan  2 18:26 ..
-rw-r--r--   1 root  wheel   861 Jan 27 00:28 com.hoobs.core.plist
-rw-r--r--   1 root  wheel   564 Feb  7  2019 com.ipvanish.osx.vpnhelper.plist
-rw-r--r--   1 root  wheel   392 Nov 15 03:40 com.splashtop.streamer-daemon.plist
-rw-r--r--   1 root  wheel   585 Nov 15 03:40 com.splashtop.streamer-srioframebuffer.plist
-rw-r--r--   1 root  wheel   532 Dec 18 14:29 com.symantec.SymLUHelper.MES.plist
-rw-r--r--   1 root  wheel   520 Dec 18 14:29 com.symantec.UninstallerToolHelper.MES.plist
-rw-r--r--   1 root  wheel   624 Dec 18 14:29 com.symantec.deepsightdownload.MES.plist
-rw-r--r--   1 root  wheel   640 Dec 18 14:28 com.symantec.dsp.nortonaggregatord.MES.plist
-rw-r--r--   1 root  wheel   580 Dec 18 14:29 com.symantec.kexthelper.MES.plist
-rw-r--r--   1 root  wheel   576 Dec 18 14:29 com.symantec.liveupdate.daemon.MES.plist
-rw-r--r--   1 root  wheel   592 Dec 18 14:28 com.symantec.sharedsettings.MES.plist
-rw-r--r--   1 root  wheel  1230 Dec 18 14:28 com.symantec.symdaemon.MES.plist
-rw-r--r--   1 root  wheel  1044 Dec 18 14:28 com.symantec.symqual.detail.MES.plist
-rw-r--r--   1 root  wheel  1357 Dec 18 14:28 com.symantec.symqual.panicreporter.MES.plist
-rw-r--r--   1 root  wheel  1513 Dec 18 14:28 com.symantec.symqual.submit.MES.plist

**Comment by jamezpowell** [comment]
Any update?

**Comment by mkellsy** [comment]
What's concerning me is there are Homebridge processes running in your activity monitor. Where are those coming from. I thought there might me an old .plist that is starting those.

Hoobs shows up as "hoobs" in the activity monitor. So there's definitely some process taking over port 51826. You can try to change the bridge port, this is in the Apple Home section of the config screen.

**Comment by jamezpowell** [comment]
So, I searched for any homebridge files not nested under the hoobs directory and deleted them. I did find an old com.homebridge.plist file and I deleted it as well. After a reboot, jobs is the only process showing up in the activity monitor now. However, when I log into the hoobs UI and select start service, I immediately get a "Hoobs service stopped" toast notification. Here at the logs from that:

[Homebridge] [4/30/2020, 2:07:52 PM] Loaded config.json with 0 accessories and 4 platforms.
[Homebridge] [4/30/2020, 2:07:53 PM] Loaded plugin "homebridge-neato".
[Homebridge] [4/30/2020, 2:07:53 PM] Registering platform "homebridge-neato.NeatoVacuumRobot"
[Homebridge] [4/30/2020, 2:07:53 PM] Loaded plugin "homebridge-node-alarm-dot-com".
[Homebridge] [4/30/2020, 2:07:53 PM] Registering platform "homebridge-node-alarm-dot-com.Alarmdotcom"
[Homebridge] [4/30/2020, 2:07:53 PM] Error loading plugin "homebridge-smartthings-v2".
[Homebridge] [4/30/2020, 2:07:53 PM] Error: Cannot find module 'winston'
Require stack:
- /private/var/root/.hoobs/node_modules/winston-daily-rotate-file/index.js
- /private/var/root/.hoobs/node_modules/homebridge-smartthings-v2/src/libs/Logger.js
- /private/var/root/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js
- /private/var/root/.hoobs/node_modules/homebridge-smartthings-v2/src/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/plugin.js
- /usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js
- /usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/private/var/root/.hoobs/node_modules/winston-daily-rotate-file/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
[Homebridge] [4/30/2020, 2:07:53 PM] Loaded plugin "nest".
[Homebridge] [4/30/2020, 2:07:53 PM] Registering platform "nest.Nest"
[Homebridge] [4/30/2020, 2:07:53 PM] Loading 4 platforms...
[Homebridge] [4/30/2020, 2:07:53 PM] Error: The requested platform "SmartThings-v2" was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/api.js:132:19)
    at Server._loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:289:47)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:93:14)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/cli.js:74:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/bin/homebridge:27:59)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[Homebridge] [4/30/2020, 2:07:53 PM] Got SIGTERM, shutting down Homebridge...

I also tried changing the port to another port that I know is open on my network (the one I use for plex server) and I get the same results.

**Comment by mkellsy** [comment]
Just deleting files won't fix this. What is trying to start the services?

Where did you find the com.homebridge.plist file? That's what's doing it.

Should have called
```
sudo launchctl unload [path to com.homebridge.plist]
```

**Comment by jamezpowell** [comment]
> Just deleting files won't fix this. What is trying to start the services?
> 
> 
> 
> Where did you find the com.homebridge.plist file? That's what's doing it.
> 
It was in the LaunchAgents folder. I put everything I deleted back and tried the command, but it says "could not find specified service"

**Comment by mkellsy** [comment]
Well from the error above you may need to reinstall hoobs
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by jamezpowell** [comment]
> Well from the error above you may need to reinstall hoobs
> 
> ```
> 
> sudo npm install -g --unsafe-perm @hoobs/hoobs
> 
> ```

Will that delete or overwrite my setup and plug-ins or just reinstall the service?

**Comment by jamezpowell** [comment]
Tried reinstalling:

Last login: Thu Apr 30 22:57:25 on console
james@homebridge ~ % sudo npm install -g--unsafe-perm @hoobs/hoobs
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

> @hoobs/hoobs@3.1.27 postinstall /Users/james/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

npm WARN saveError ENOENT: no such file or directory, open '/Users/james/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/james/package.json'
npm WARN james No description
npm WARN james No repository field.
npm WARN james No README data
npm WARN james No license field.

+ @hoobs/hoobs@3.1.27
removed 3 packages, updated 1 package and audited 3372 packages in 8.712s

3 packages are looking for funding
  run `npm fund` for details

found 41 vulnerabilities (3 low, 12 moderate, 26 high)
  run `npm audit fix` to fix them, or `npm audit` for details

james@homebridge ~ % npm audit fix
npm ERR! code EAUDITNOPJSON
npm ERR! audit No package.json found: Cannot audit a project without a package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/james/.npm/_logs/2020-05-01T04_10_51_622Z-debug.log
james@homebridge ~ %

**Comment by jamezpowell** [comment]
Any advice on where to go from here?

**Comment by BobbySlope** [comment]
@mkellsy please take a look at it when u have time

**Comment by mkellsy** [comment]
The install succeeded. You can't run npm audit fix on packages that you don't own.
