### ISSUE TITLE
Hoobs docker container not accessible: port 8080 already in use.

### ISSUE THREAD

**Issue by andredewaard** [hoobs-org/HOOBS#560]
**Description**
Hoobs docker container not accessible when port 8080 is already in use.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Synology docker with the latest image of https://hub.docker.com/r/hoobs/hoobs

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
None at the moment

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
Default config still

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[4/21/2020, 7:39:31 AM] listen EADDRINUSE: address already in use :::8080
```

**Additional context**
Port 8080 is in use by the Unifi Controller also running in Docker on my Synology Nas. 
Is there a enviroment variable i can add to change the default port 8080 to something else?

**Comment by mkellsy** [comment]
Do you have another container running on port 8080? Is there something on the host that is running on port 8080?

**Comment by andredewaard** [comment]
As mentioned in the additional context section my Unifi controller in running on port 8080. I hoped there was a way to change the default port of Hoobs from 8080 to something else via the environment variables of the Docker Container.

**Comment by mkellsy** [comment]
Did you create a volume for hoobs. Does Synology allow you to view and edit files in that volume?

You can edit the config.json file that it created. and change the server.port to something else.

Here's the default config
``` json
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": []
}
```

Then you can fire up the container.

The other option you have it to temporally disable the unifi controller and start HOOBS then change the port and then fire up the unifi controller.

**Comment by andredewaard** [comment]
That was a great idea, couldn't find the config file in the docker container, but did manage to change the port in the Hoobs web UI. Restarting the Hoobs server and starting the Unifi controller again fixed the issue!
