### ISSUE TITLE
Filter live log in webview

### ISSUE THREAD

**Issue by toellbe** [hoobs-org/HOOBS#566]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Filtering the Homebridge log in web interface to get filtered results live. E.q. Only from one accessory...

**Comment by mkellsy** [comment]
He have this coming in our desktop app.

**Comment by mkellsy** [comment]
since this is already done in our upcoming desktop and mobile apps. I am closing this here.
