### ISSUE TITLE
Hue plugin not working.

### ISSUE THREAD

**Issue by ItsMisterEric** [hoobs-org/HOOBS#567]
**Description**
I'll admit that I should have backed up everything first, but here we are. I updated from 3.1.22 to 3.1.27 the other day, and thereafter Homebridge couldn't complete startup. Noticed there was an update for Hue, installed that, and still no love. Hitting the Hue button does nothing, and logs similar to this keep racking up. HOOBS can no longer complete the startup process because Hue wants the Hub button pressed to create a user, and pressing it does not work. 

**Version**
Please include the version of HOOBS you are using.
3.1.27
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
3.1.22

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Downloaded HOOBS image on a RasPi 3

**List your plugins**
Wink
Thingspeak
Chamberlain
Plex2

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYGHOA",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "throwback-blue",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "07005"
    },
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "REDACTED"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [
        {
            "accessory": "Plex",
            "name": "Plex",
            "plex_token": "REDACTED",
            "host": "10.0.1.2",
            "filter": [
                {
                    "user": "REDACTED",
                    "player": "Attic"
                }
            ]
        },
        {
            "accessory": "Httpthingspeak",
            "name": "Basement Temperature",
            "type": "CurrentTemperature",
            "manufacturer": "Manufacturer",
            "model": "DHT11",
            "serial": "1",
            "url": "https://api.thingspeak.com/channels/REDACTED/field/1/last.json",
            "http_method": "GET",
            "debug": true
        },
        {
            "accessory": "Httpthingspeak",
            "name": "Basement Humidity",
            "type": "CurrentRelativeHumidity",
            "manufacturer": "Manufacturer",
            "model": "DHT11",
            "serial": "1",
            "url": "https://api.thingspeak.com/channels/REDACTED/field/2/last.json",
            "http_method": "GET",
            "debug": true
        },
        {
            "accessory": "Chamberlain",
            "plugin_map": {
                "plugin_name": "chamberlain",
                "index": 0
            },
            "name": "Garage Door",
            "username": "REDACTED",
            "password": "REDACTED"
        },
        {
            "accessory": "Httpthingspeak",
            "name": "Sun Porch Humidity",
            "type": "CurrentRelativeHumidity",
            "manufacturer": "Manufacturer",
            "model": "DHT11",
            "serial": "1",
            "url": "https://api.thingspeak.com/channels/REDACTED/field/4/last.json",
            "http_method": "GET",
            "debug": true,
            "plugin_map": {
                "plugin_name": "homebridge-thingspeak",
                "index": 0
            }
        },
        {
            "accessory": "Httpthingspeak",
            "name": "Kitchen Humidity",
            "type": "CurrentRelativeHumidity",
            "manufacturer": "Manufacturer",
            "model": "DHT11",
            "serial": "1",
            "url": "https://api.thingspeak.com/channels/REDACTED/field/6/last.json",
            "http_method": "GET",
            "debug": true,
            "plugin_map": {
                "plugin_name": "homebridge-thingspeak",
                "index": 0
            }
        },
        {
            "accessory": "Httpthingspeak",
            "name": "Sun Porch Temperature",
            "type": "CurrentTemperature",
            "manufacturer": "Manufacturer",
            "model": "DHT11",
            "serial": "1",
            "url": "https://api.thingspeak.com/channels/REDACTED/field/2/last.json",
            "http_method": "GET",
            "debug": true,
            "plugin_map": {
                "plugin_name": "homebridge-thingspeak",
                "index": 0
            }
        },
        {
            "accessory": "Httpthingspeak",
            "name": "Kitchen Temperature",
            "type": "CurrentTemperature",
            "manufacturer": "Manufacturer",
            "model": "DHT11",
            "serial": "1",
            "url": "https://api.thingspeak.com/channels/REDACTED/field/3/last.json",
            "http_method": "GET",
            "debug": true,
            "plugin_map": {
                "plugin_name": "homebridge-thingspeak",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "Wink",
            "name": "Wink",
            "client_id": "REDACTED",
            "client_secret": "REDACTED",
            "access_token": "REDACTED",
            "refresh_token": "REDACTED",
            "username": "REDACTED",
            "password": "REDACTED"
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "anyOn": true,
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "lights": true,
            "hueMotionTemperatureHistory": true,
            "hueDimmerRepeat": true
        }
    ]
}

**Post your log**
[Homebridge] [4/24/2020, 08:25:28] [Hue] Philips hue: bridge communication error: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
at checkListener (events.js:64:11)
at ClientRequest.once (events.js:313:3)
at new ClientRequest (_http_client.js:177:10)
at Object.request (https.js:309:10)
at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/agent-base/patch-core.js:25:22)
at Object.request (/home/hoobs/.hoobs/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20)
at HttpClient.request (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
at HueClient._request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueClient.js:348:41)
at HueBridge.request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:1119:43)
at HueBridge.createUser (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:286:28)
[Homebridge] [4/24/2020, 08:25:28] [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
[Homebridge] [4/24/2020, 08:25:43] [Hue] Philips hue: bridge request 36: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [4/24/2020, 08:25:43] [Hue] Philips hue: bridge communication error: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
at checkListener (events.js:64:11)
at ClientRequest.once (events.js:313:3)
at new ClientRequest (_http_client.js:177:10)
at Object.request (https.js:309:10)
at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/agent-base/patch-core.js:25:22)
at Object.request (/home/hoobs/.hoobs/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20)
at HttpClient.request (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
at HueClient._request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueClient.js:348:41)
at HueBridge.request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:1119:43)
at HueBridge.createUser (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:286:28)
[Homebridge] [4/24/2020, 08:25:43] [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s

**Additional context**

**Comment by mkellsy** [comment]
What's you node version? You can check this by typing this command in the terminal.
```
node -v
```

**Comment by ItsMisterEric** [comment]
Node is 12.13.1.

**Comment by mkellsy** [comment]
Your node version is too low. The Hue plugin requires a newer version. You can run this command to upgrade Node
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 12.16.2
```

**Comment by ItsMisterEric** [comment]
Ran the command, rebooted the Pi, verified 12.16.2 installed.  Issue persists.

**Comment by mkellsy** [comment]
I will have to dig into this this weekend

**Comment by mkellsy** [comment]
@askovi I tested this plugin and it sees my bridge, however it doesn't recognize the outdoor lightstrip that I have.

Can you test this with your bulbs?

**Comment by BobbySlope** [comment]
# Update to HOOBS 3.2.0 Available

### What's New in 3.2.0
* Bug Fixes
* Removed NGINX
* Faster Load Times
* Updated HAP Core
* Cleaned Bridge Code
* Support For Short Form UUIDS
* Support Plugins for Latest HB Version
* Support Identifier less Plugin Registration
* Allow Non HOOBS Scoped Certified Plugins

**Comment by ItsMisterEric** [comment]
Updated, re-added Hue plugin, issue persists.

**Comment by resgroupmsr** [comment]
Updated to 3.2.0, nothing working now.  Only had SmartThings and FFMPEG running.  Tried removing SmartThings as log suggested it was crashing on start up but even with it gone, HOOBS crashes.  Don't want to remove FFMPEG at this point.  Ideas?

**Comment by mkellsy** [comment]
Can you post logs?

**Comment by ItsMisterEric** [comment]
5/1/2020, 1:15:00 PM HOOBS listening on port 8080.
5/1/2020, 1:15:05 PM Loaded plugin "homebridge-plex-v2".
5/1/2020, 1:15:05 PM Loaded plugin "homebridge-thingspeak".
5/1/2020, 1:15:05 PM Loaded plugin "chamberlain".
5/1/2020, 1:15:08 PM Loaded plugin "hue".
5/1/2020, 1:15:10 PM Loaded plugin "wink".
5/1/2020, 1:15:10 PM [Wink] Initializing Wink platform...
5/1/2020, 1:15:10 PM [Hue] Initializing Hue platform...
5/1/2020, 1:15:10 PM [Hue] homebridge-hue v0.11.63, node v12.16.2, homebridge v3.2.0
5/1/2020, 1:15:10 PM [Hue] searching bridges and gateways
5/1/2020, 1:15:10 PM [Plex] Initializing Plex accessory...
5/1/2020, 1:15:10 PM [Basement Temperature] Initializing Httpthingspeak accessory...
5/1/2020, 1:15:10 PM [Basement Temperature] Httpthingspeak: reading config
5/1/2020, 1:15:10 PM [Basement Temperature] getServiecs
5/1/2020, 1:15:10 PM [Basement Humidity] Initializing Httpthingspeak accessory...
5/1/2020, 1:15:10 PM [Basement Humidity] Httpthingspeak: reading config
5/1/2020, 1:15:10 PM [Basement Humidity] getServiecs
5/1/2020, 1:15:10 PM [Garage Door] Initializing Chamberlain accessory...
5/1/2020, 1:15:10 PM [Sun Porch Humidity] Initializing Httpthingspeak accessory...
5/1/2020, 1:15:10 PM [Sun Porch Humidity] Httpthingspeak: reading config
5/1/2020, 1:15:10 PM [Sun Porch Humidity] getServiecs
5/1/2020, 1:15:10 PM [Kitchen Humidity] Initializing Httpthingspeak accessory...
5/1/2020, 1:15:10 PM [Kitchen Humidity] Httpthingspeak: reading config
5/1/2020, 1:15:10 PM [Kitchen Humidity] getServiecs
5/1/2020, 1:15:10 PM [Sun Porch Temperature] Initializing Httpthingspeak accessory...
5/1/2020, 1:15:10 PM [Sun Porch Temperature] Httpthingspeak: reading config
5/1/2020, 1:15:10 PM [Sun Porch Temperature] getServiecs
5/1/2020, 1:15:10 PM [Kitchen Temperature] Initializing Httpthingspeak accessory...
5/1/2020, 1:15:10 PM [Kitchen Temperature] Httpthingspeak: reading config
5/1/2020, 1:15:10 PM [Kitchen Temperature] getServiecs
5/1/2020, 1:15:10 PM [Wink] Loaded from cache: Dining Room (binary_switch/405728)
5/1/2020, 1:15:10 PM [Wink] Loaded from cache: Wink Relay Sensor (sensor_pod/323882)
5/1/2020, 1:15:10 PM [Wink] Refreshing devices...
5/1/2020, 1:15:11 PM [Wink] Not supported by HomeKit: Basement (powerstrip/15863)
5/1/2020, 1:15:11 PM [Wink] Not supported by HomeKit: Master Bedroom (powerstrip/21578)
5/1/2020, 1:15:11 PM [Wink] Devices refreshed
5/1/2020, 1:15:15 PM [Hue] Philips hue: Philips BSB002 bridge v1938052050, api v1.37.0
5/1/2020, 1:15:15 PM [Hue] Philips hue: bridge request 1: post / {"devicetype":"homebridge-hue#hoobs"}
5/1/2020, 1:15:15 PM [Hue] Philips hue: bridge communication error: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:108:11)
    at ClientRequest.once (events.js:430:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/agent-base/patch-core.js:25:22)
    at Object.request (/home/hoobs/.hoobs/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20)
    at HttpClient.request (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HueClient._request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueClient.js:348:41)
    at HueBridge.request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:1119:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
5/1/2020, 1:15:15 PM [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
5/1/2020, 1:15:40 PM [Hue] Philips hue: bridge request 2: post / {"devicetype":"homebridge-hue#hoobs"}
5/1/2020, 1:15:40 PM [Hue] Philips hue: bridge communication error: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:108:11)
    at ClientRequest.once (events.js:430:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/agent-base/patch-core.js:25:22)
    at Object.request (/home/hoobs/.hoobs/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20)
    at HttpClient.request (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HueClient._request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueClient.js:348:41)
    at HueBridge.request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:1119:43)
    at HueBridge.createUser (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:286:28)
5/1/2020, 1:15:40 PM [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s

**Comment by Christian-CFP** [comment]
Add this line to your config:
` "forceHttp": true`

**Comment by BobbySlope** [comment]
solved? 
closing for now.
if not reopen and provide more info

**Comment by ItsMisterEric** [comment]
That did not fix the issue, however, I gave up on the installation and started over.

**Comment by Christian-CFP** [comment]
`{
            **"forceHttp": true,**
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "nupnp": false,
            "hosts": [
                "XXX.XXX.XXX.XXX"
            ],
            "users": {
                "XXXXX": "YYYYY"
            },
            "sensors": false,
            "nativeHomeKitSensors": false,
            "nativeHomeKitLights": true,
            "lights": true,
            "forceCt": true,
            "resource": true
        }`

like this? and it does not work?

**Comment by ItsMisterEric** [comment]
Correct.   That did not work.  Added that, and rebooted, and then I was unable to load the config screen and see the JSON.   Out of frustration, I gave up and paved it.  So far, I am slowly re-adding  plugins.
