### ISSUE TITLE
Homebridge Service Autorestart 

### ISSUE THREAD

**Issue by toellbe** [hoobs-org/HOOBS#569]
It would be very valuable if the homebridge service restarts automatically after a "crash".

For example, if the wifi is not available and devices stop responding, Homebridge runs on an error and the service stops. After the connection is restored, the service must be started manually.

It would be great to have a configuration that asks how often and at what interval to try to restart the service

**Comment by Jarvichi** [comment]
I agree, I have everything set up and working perfectly... sporadically a plug-in fails (maybe once every few weeks) and causes the Homebridge service to stop, it would be really useful for a watchdog to restart the service after a minute, if the service repeatedly fails to start wait an hour and retry, and give up if a retry threshold is hit (I.e. 5 times)

**Comment by BobbySlope** [comment]
we added that as an task for an future update

**Comment by Nisse57** [comment]
Plus one for this feature. I use the Telldus plugin which depends on a piece of hardware called Tellstick. After a power outage Tellstick is much slower to boot than the RasPi and hence Tellstick is not ready when the bridge service start, and the bridge crash. A configurable number of restarts with a configurable delay would solve this issue.

**Comment by warleysa** [comment]
I also agree this feature would be great. It would solve a ton of problems I have been having with "hoobs FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory" since the last update

**Comment by GLoBE7823** [comment]
+1

**Comment by ValoV83** [comment]
+1 for this feature as well. I have everything setup and working fine as well. I use a plugin for my Panasonic TV that occasionally causes Homebridge to crash (I've sent a bug report to the dev). It would be great to have the ability to have the Homebridge service restart automatically rather than having to login to hoobs.local and do it manually.

**Comment by docgilno** [comment]
Very needed.

**Comment by KiwiV** [comment]
+1 This would be a great addition to an already very good product!

**Comment by chrisjshull** [comment]
Bounty added: https://www.bountysource.com/issues/91309722-homebridge-service-autorestart

**Comment by koweye** [comment]
+1 also... i left home not knowing my HOOBS service wasn’t running, not sure if it crashed or what. So none of my security stuff activated or doors locked. Sorely needed! Or at least a way for a service to notify when its down or auto restart... thanks!

**Comment by sponte** [comment]
Probably needs more work but added auto-restart when Bridge process unexpectedly crashes:

https://github.com/hoobs-org/hoobs-core/pull/117

**Comment by metalnodeug** [comment]
+1 I have the same issue and it’s boring 😓

**Comment by fschwanzara** [comment]
+1 I allways notice that the service is down when the expected automations do not run ....

**Comment by chrisjshull** [comment]
keepalive

**Comment by metalnodeug** [comment]
Keep alive

**Comment by r0ballis0n** [comment]
It's about time to add this feature. I have been running into this with a newly added plugin. A simple start services command fixes the issue for a while but it sure would be nice if the thing did that itself once and awhile. Seems pretty important feature as the product grows more important to the way one excepts their home to function.

**Comment by chrisjshull** [comment]
bump

**Comment by efurban** [comment]
This is definitely much-needed feature.  Vote !

**Comment by Nisse57** [comment]
keep alive

**Comment by red-gee** [comment]
Need this feature too!

**Comment by elpaso666** [comment]
+1. Come on ;)

**Comment by askovi** [comment]
This is already implemented in HOOBS 4.

**Comment by metalnodeug** [comment]
Have you a date or
A link to download hoobs 4 ?

**Comment by arakis** [comment]
> This is already implemented in HOOBS 4.

If so, somebody should close https://www.bountysource.com/issues/91309722-homebridge-service-autorestart

**Comment by novacite** [comment]
So, is this truly resolved in a forthcoming version?

**Comment by efthymakis** [comment]
Timetable for HOOBS 4?

**Comment by luisfrocha** [comment]
I'm running HOOBS 4.0.104 on HOOBS box and I'm having to restart it every night because neither web interface nor Homemenager app work. I ssh into it and reboot. That's the only thing that will get it working again. Interestingly, though, all commands work fine (it can still control my devices), so it seems it's only the web interface that stops working.
