### ISSUE TITLE
I'm having problems with the hive, plugin and Google they're not configuring properly and they crash the systemthey're not configuring properly and they crash the system

### ISSUE THREAD

**Issue by treforparr** [hoobs-org/HOOBS#570]
**Description**
I'm having problems with the  Samsung smartthings, hive plugin , Google is a real big problem at the moment it's not configuring properly, it won't let you login in google AccountAccount 
**Expected behavoir**

Sometimes hoobs shuts down your problem at the beginning where I had to reinstall the os due to a memory card corruption, 

**Plugin name**
Pro plug-ins are not working properly, some work for a few hours and then stopped working ring is okay, 

**Please report the issue to the plugin developer**
Constant problems with Google, unable to login due to come for a config folder that homebridge has but this one doesn't

**Version**
lates 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
Installation it out of the box

**Pervious version**
2 days

*

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box

**Post your config**
Several plug-ins have stopped working
```

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
#556 see here

**Comment by BobbySlope** [comment]
# Update to HOOBS 3.2.0 Available

### What's New in 3.2.0
* Bug Fixes
* Removed NGINX
* Faster Load Times
* Updated HAP Core
* Cleaned Bridge Code
* Support For Short Form UUIDS
* Support Plugins for Latest HB Version
* Support Identifier less Plugin Registration
* Allow Non HOOBS Scoped Certified Plugins
