### ISSUE TITLE
[Hue] undefined: TypeError: bridgeid: missing string value

### ISSUE THREAD

**Issue by h0mesmart** [hoobs-org/HOOBS#571]
**Description**
Fresh install Hoobs 3.1.27
Install hoobs-deconz-phoscon
install hue plugin

**Expected behavoir**
expose accessories : sensors, light to home app

**Plugin name**
HOOBS plugin for Philips Hue and deCONZ

**Version**
3.1.27

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
Fresh install

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry pi 3b+

**Post your config**
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYG83M",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "CH",
        "postal_code": "1400"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "81:D8:E9:DB:9C:98"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-dummy",
        "homebridge-camera-ffmpeg",
        "ring",
        "homebridge-harmony",
        "hue"
    ],
    "accessories": [
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "name": "Armed"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "name": "Disarmed"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "name": "Unlock"
        }
    ],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Camera",
                    "manufacturer": "AXIS",
                    "model": "M1031-W",
                    "serialNumber": "*******",
                    "firmwareRevision": "5.20.5",
                    "motion": true,
                    "uploader": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://**************:554/axis-media/media.amp",
                        "maxStreams": 3,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 15,
                        "vcodec": "h264_omx",
                        "audio": true
                    }
                }
            ]
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "refreshToken": "<removed>",
            "hideDoorbellSwitch": true
        },
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "Salon TV",
            "hubIP": "10.0.0.119",
            "TVPlatformMode": true,
            "mainActivity": "Regarder la TV",
            "devicesToPublishAsAccessoriesSwitch": [
                "Sony Mini System"
            ],
            "activitiesToPublishAsInputForTVMode": [
                "Regarder Apple TV",
                "Regarder la TV",
                "M6",
                "TF1",
                "TFX",
                "6TER",
                "FR4",
                "FR3"
            ],
            "activitiesToPublishAsAccessoriesSwitch": [
                "Credence Sunset"
            ]
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "forceCt": false,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": false,
            "resource": false,
            "lights": true,
            "users": {
                "ECB5FAFFFE15F4B5": "<removed>",
                "00212EFFFF051A15": "<removed>"
            },
            "hosts": [
                "10.0.0.114",
                "10.0.0.115"
            ],
            "sensors": false,
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence"
            ],
            "lowBattery": 25,
            "anyOn": true
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}

**Post your log**
+ @hoobs/hue@0.11.63
added 50 packages from 77 contributors in 16.367s

37 packages are looking for funding
  run `npm fund` for details
[4/27/2020, 4:42:58 PM] Installed "@hoobs/hue" package.
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] undefined: TypeError: bridgeid: missing string value
    at newTypeError (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:42:52)
    at Function.toString (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:298:13)
    at Object._callbacks.<computed> [as bridgeid] (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:781:40)
    at OptionParser.parse (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:808:29)
    at new HueClient (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueClient.js:41:18)
    at HueBridge.request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:1105:22)
    at HueBridge.getFullState (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:314:28)
    at HueBridge.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:93:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
    at async HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:288:29)
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] undefined: 1 accessories
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Philips hue: Philips BSB002 bridge v1938052050, api v1.37.0
[Homebridge] [4/27/2020, 4:55:38 PM] Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:310:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
[Homebridge] [4/27/2020, 4:55:38 PM] Got SIGTERM, shutting down Homebridge...
[Homebridge] [4/27/2020, 4:55:38 PM] [Salon TV] INFO - shutdown
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Philips hue: 9 accessories
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "Philips hue"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Philips hue: 2 services
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "Près de la télé"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "Près du canapé"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "La Bande LED TV"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "Plafonnier"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "le ruban LED"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "Spot 2"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "Spot 1"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "Spot 3"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] Initializing platform accessory "undefined"...
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] undefined: 2 services
[Homebridge] [4/27/2020, 4:55:38 PM] [Hue] homebridge: error: Accessories must be created with a non-empty displayName.
[Homebridge] [4/27/2020, 4:58:19 PM] Loaded config.json with 3 accessories and 4 platforms.
[Homebridge] [4/27/2020, 4:58:21 PM] Loaded plugin "homebridge-camera-ffmpeg".
[Homebridge] [4/27/2020, 4:58:21 PM] Registering platform "homebridge-camera-ffmpeg.Camera-ffmpeg"
[Homebridge] [4/27/2020, 4:58:21 PM] Loaded plugin "homebridge-dummy".
[Homebridge] [4/27/2020, 4:58:21 PM] Registering accessory "homebridge-dummy.DummySwitch"
[Homebridge] [4/27/2020, 4:58:22 PM] Loaded plugin "homebridge-harmony".
[Homebridge] [4/27/2020, 4:58:22 PM] Registering platform "homebridge-harmony.HarmonyHubWebSocket"
[Homebridge] [4/27/2020, 4:58:23 PM] Loaded plugin "hue".
[Homebridge] [4/27/2020, 4:58:23 PM] Registering platform "homebridge-hue.Hue"
[Homebridge] [4/27/2020, 4:58:24 PM] Loaded plugin "ring".
[Homebridge] [4/27/2020, 4:58:24 PM] Registering platform "homebridge-ring.Ring"
[Homebridge] [4/27/2020, 4:58:24 PM] Loading 4 platforms...
[Homebridge] [4/27/2020, 4:58:24 PM] [Camera ffmpeg] Initializing Camera-ffmpeg platform...
[Homebridge] [4/27/2020, 4:58:24 PM] [Ring] Initializing Ring platform...
[Homebridge] [4/27/2020, 4:58:24 PM] [Salon TV] Initializing HarmonyHubWebSocket platform...
[Homebridge] [4/27/2020, 4:58:24 PM] [Salon TV] HarmonyPlatform Init
[Homebridge] [4/27/2020, 4:58:24 PM] [Hue] Initializing Hue platform...
[Homebridge] [4/27/2020, 4:58:24 PM] [Hue] homebridge-hue v0.11.63, node v12.16.2, homebridge v0.4.53
[Homebridge] [4/27/2020, 4:58:24 PM] Loading 3 accessories...
[Homebridge] [4/27/2020, 4:58:24 PM] [Armed] Initializing DummySwitch accessory...
[Homebridge] [4/27/2020, 4:58:24 PM] [Disarmed] Initializing DummySwitch accessory...
[Homebridge] [4/27/2020, 4:58:24 PM] [Unlock] Initializing DummySwitch accessory...
[Homebridge] [4/27/2020, 4:58:24 PM] [Salon TV] WARNING - configureAccessory - TV accessory added in your bridge from cache, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
[Homebridge] [4/27/2020, 4:58:24 PM] [Salon TV] DidFinishLaunching
[Homebridge] [4/27/2020, 4:58:24 PM] [Salon TV] (Salon TV)INFO - Loading activities...
[Homebridge] [4/27/2020, 4:58:24 PM] Taupo is running on port 33485.
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] undefined: TypeError: bridgeid: missing string value
    at newTypeError (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:42:52)
    at Function.toString (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:298:13)
    at Object._callbacks.<computed> [as bridgeid] (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:781:40)
    at OptionParser.parse (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:808:29)
    at new HueClient (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueClient.js:41:18)
    at HueBridge.request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:1105:22)
    at HueBridge.getFullState (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:314:28)
    at HueBridge.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:93:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
    at async HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:288:29)
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] undefined: 1 accessories
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Philips hue: Philips BSB002 bridge v1938052050, api v1.37.0
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Philips hue: 9 accessories
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "Philips hue"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Philips hue: 2 services
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "Près de la télé"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "Près du canapé"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "La Bande LED TV"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "Plafonnier"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "le ruban LED"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "Spot 2"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "Spot 1"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "Spot 3"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] Initializing platform accessory "undefined"...
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] undefined: 2 services
[Homebridge] [4/27/2020, 4:58:25 PM] [Hue] homebridge: error: Accessories must be created with a non-empty displayName.

**Additional context**
Now impossible to start homebridge service

**Comment by h0mesmart** [comment]
Did some testing and find out if modified the Hue plugin config like so 
{
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "anyOn": true,
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": false,
            "resource": true,
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence"
            ],
            "hosts": [
                "10.0.0.114"
            ],
            "scenes": false,
            "sensors": true,
            "users": {
                "ECB5FAFFFE15F4B5": "*******************4Z"
            },
            "lights": true
        }

I did not include the phoscon GW it works 

[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Philips hue: Philips BSB002 bridge v1938052050, api v1.37.0
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Philips hue: 9 accessories
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Initializing platform accessory "Philips hue"...
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Philips hue: 2 services
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Initializing platform accessory "Près de la télé"...
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Initializing platform accessory "Près du canapé"...
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Initializing platform accessory "La Bande LED TV"...
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Initializing platform accessory "Plafonnier"...
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Initializing platform accessory "le ruban LED"...
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Initializing platform accessory "Spot 2"...
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Initializing platform accessory "Spot 1"...
[Homebridge] [4/27/2020, 10:11:08 PM] [Hue] Initializing platform accessory "Spot 3"...
[Homebridge] [4/27/2020, 10:11:08 PM] Homebridge is running on port 51826.

BTW the phoscon GW is installed on the same pi as hoobs and it's up and running 

As soon as I added the phoscon GW i get the 
[Hue] undefined: TypeError: bridgeid: missing string value
    at newTypeError (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:42:52)
    at Function.toString (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:298:13)
    at Object._callbacks.<computed> [as bridgeid] (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:781:40)
    at OptionParser.parse (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:808:29)
    at new HueClient (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueClient.js:41:18)
    at HueBridge.request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:1105:22)
    at HueBridge.getFullState (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:314:28)
    at HueBridge.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:93:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
    at async HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:288:29)
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] undefined: 1 accessories
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Philips hue: Philips BSB002 bridge v1938052050, api v1.37.0
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Philips hue: 9 accessories
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Philips hue"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Philips hue: 2 services
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Près de la télé"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Près du canapé"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "La Bande LED TV"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Plafonnier"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "le ruban LED"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Spot 2"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Spot 1"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Spot 3"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "undefined"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] undefined: 2 services
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] homebridge: error: Accessories must be created with a non-empty displayName.

**Comment by mkellsy** [comment]
Thanks we will look into this.

**Comment by h0mesmart** [comment]
some update :

So I've changed the config like so 

{
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "anyOn": true,
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": false,
            "resource": true,
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence"
            ],
            "hosts": [
                "10.0.0.114",
                "10.0.0.115:1881"
            ],
            "scenes": false,
            "sensors": true,
            "users": {
                "ECB5FAFFFE15F4B5": "********4Z",
                "00212EFFFF051A15": "*******90"
            },
            "lights": true
        }


As you can see I did mentioned the port for the phoscon GW.  now I can see accessories through the conbee but I still have some error in the log 

[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.75, api v1.16.0
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Philips hue: Philips BSB002 bridge v1938052050, api v1.37.0
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Phoscon-GW: 3 accessories
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Philips hue: 9 accessories
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Philips hue"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Philips hue: 2 services
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Près de la télé"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Près du canapé"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "La Bande LED TV"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Plafonnier"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "le ruban LED"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Spot 2"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Spot 1"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Spot 3"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Phoscon-GW"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Phoscon-GW: 2 services
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Detecteur Bureau"...
[Homebridge] [4/28/2020, 3:38:22 PM] [Hue] Initializing platform accessory "Detecteur Cuisine"...
[Homebridge] [4/28/2020, 3:38:22 PM] Homebridge is running on port 51826.
[Homebridge] [4/28/2020, 3:38:35 PM] [Hue] 10.***.***.115: 10.1.0.115:1881: cannot connect: ETIMEDOUT - retrying in 15s
[Homebridge] [4/28/2020, 3:39:22 PM] [Hue] 10.***.***.115: 10.1.0.115:1881: cannot connect: ETIMEDOUT - retrying in 15s
[Homebridge] [4/28/2020, 3:40:09 PM] [Hue] 10.***.***.115: 10.1.0.115:1881: cannot connect: ETIMEDOUT - retrying in 15s
[Homebridge] [4/28/2020, 3:40:57 PM] [Hue] 10.***.***.115: 10.1.0.115:1881: cannot connect: ETIMEDOUT - retrying in 15s

**Comment by h0mesmart** [comment]
Last update, I got it. I’ve mistakenly added the pi’s IP address. I corrected it but somehow it’s still trying to connect to that wrong address. A reboot and everything is going well

**Comment by mkellsy** [comment]
Thanks for the update
