### ISSUE TITLE
Trigger for Lutron 'SmartAway' scene

### ISSUE THREAD

**Issue by resgroupmsr** [hoobs-org/HOOBS#572]
When Nest pulled support for Lutron, it also pulled the automatic geofence triggering of the Lutron 'SmartAway' scene that runs random on/off lights when the house is empty.  Has anyone worked out a way to use geofencing via Homebridge to trigger this Lutron SmartAway?

**Comment by resgroupmsr** [comment]
Not sure where else to post this but my FFMPEG, NEST and SmartThings issues are all now (apparently) resolved this morning.  I also sent along a PayPal donation because you guys are working overtime these last two days.  Thanks from all of us.

On my Lutron 'SmartAway' trigger, would really love to get this working again.  Hopefully something will come along eventually.

**Comment by mkellsy** [comment]
I hse Lutron Caseta. I have been looking for a good plugin for this so I don't have to use SmartThings.

I am an old Wink user.
