### ISSUE TITLE
Any plans for upgrading to Homebridge 1.0?

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#573]
Hello guys,

I would like to ask if you plan to integrate Homebridge 1.0 in Hoobs because some newer  Plugin versions do not work with the Old Homebridge.

**Comment by mkellsy** [comment]
HOOBS is different then HB. So no we will not upgrade to HB 1.0 (technically).
However we are testing version 3.2.0. This version supports plugins wrote for HB 1.0.

**Comment by Bladestar2105** [comment]
Thanks for your statement 🙂

**Comment by BobbySlope** [comment]
# Update to HOOBS 3.2.0 Available

### What's New in 3.2.0
* Bug Fixes
* Removed NGINX
* Faster Load Times
* Updated HAP Core
* Cleaned Bridge Code
* Support For Short Form UUIDS
* Support Plugins for Latest HB Version
* Support Identifier less Plugin Registration
* Allow Non HOOBS Scoped Certified Plugins
