### ISSUE TITLE
Support of Homebridge 1.0

### ISSUE THREAD

**Issue by F3000** [hoobs-org/HOOBS#574]
I hope this is in your roadmap 😁

**Comment by rpolenthon** [comment]
Duplicate of #573

**Comment by BobbySlope** [comment]
# Update to HOOBS 3.2.0 Available

### What's New in 3.2.0
* Bug Fixes
* Removed NGINX
* Faster Load Times
* Updated HAP Core
* Cleaned Bridge Code
* Support For Short Form UUIDS
* Support Plugins for Latest HB Version
* Support Identifier less Plugin Registration
* Allow Non HOOBS Scoped Certified Plugins
