### ISSUE TITLE
Unable to add to Home app --need to reset first

### ISSUE THREAD

**Issue by douggainous** [hoobs-org/HOOBS#575]
I had an issue with Hoobs previously that your recent update resolved, however, all my devices are missing in the home app, so when I try to add it back, it tells me that I need to reset it first.  How do I resolve this?

**Comment by mkellsy** [comment]
Menu -> Help -> Reset Connection
This should allow you to re-pair with Homekit.

**Comment by douggainous** [comment]
Thanks, unfortunately I am now getting “Couldn’t add HOOBS-4EC9” The setup code is incorrect.  I am using the camera to scan the barcode in the HOOBS interface from the home app.

**Comment by mkellsy** [comment]
What version of iOS are you using?

**Comment by douggainous** [comment]
13.4.1

**Comment by BobbySlope** [comment]
Closing this issue, if there's still an issue please reopen and provide more info
