### ISSUE TITLE
HOOBS 3.2.0 not in Node Repository

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#577]
Hello,

I try to find the new update but in shows me this message on https://www.npmjs.com/package/@hoobs/hoobs/v/3.2.0

> {"error":"Service Unavailable"}

**Comment by mkellsy** [comment]
3.2.9 is not released.

**Comment by BobbySlope** [comment]
### What's New in 3.2.0
* Bug Fixes
* Removed NGINX
* Faster Load Times
* Updated HAP Core
* Cleaned Bridge Code
* Support For Short Form UUIDS
* Support Plugins for Latest HB Version
* Support Identifier less Plugin Registration
* Allow Non HOOBS Scoped Certified Plugins

**Comment by Bladestar2105** [comment]
Thank you, updated without any issues. Great work 🙂👍
