### ISSUE TITLE
New version 3.2.0 is not shown

### ISSUE THREAD

**Issue by MikeDeltaHH** [hoobs-org/HOOBS#578]
**Description**
The new version 3.2.0 is not visible in my installation

**Version**
3.1.27

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Ubuntu 18.04.4 LTS

**Additional context**
The Software option shows:

HOOBS Core
Current Version: 3.1.27
Latest

**Comment by BobbySlope** [comment]
its not released yet to npm. will be done today

**Comment by BobbySlope** [comment]
# Update to HOOBS 3.2.0 Available

### What's New in 3.2.0
* Bug Fixes
* Removed NGINX
* Faster Load Times
* Updated HAP Core
* Cleaned Bridge Code
* Support For Short Form UUIDS
* Support Plugins for Latest HB Version
* Support Identifier less Plugin Registration
* Allow Non HOOBS Scoped Certified Plugins
