### ISSUE TITLE
Homebridge Service not working 

### ISSUE THREAD

**Issue by xalex88** [hoobs-org/HOOBS#580]
**Description**

**Version**
Please include the version of HOOBS you are using.

3.1.27 = Fine
Update to 3.2.0 = no service 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

3.2

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
 MacOS 

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Homebrige shelly

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "xxx",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "80803"
    },
    "bridge": {
        "name": "Bridge",
        "username": "xxx",
        "port": 51826,
        "pin": "xxx"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Shelly",
            "name": "Shelly",
            "admin": {
                "enabled": true,
                "port": 8081
            },
            "plugin_map": {
                "plugin_name": "homebridge-shelly"
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```

1.5.2020, 19:31:48 HOOBS listening on port 8080.
1.5.2020, 19:31:50 /usr/local/lib/node_modules/@hoobs/hoobs/bridge/plugin.js:56
1.5.2020, 19:31:50 static loadPackageJSON = function (pluginPath) {
1.5.2020, 19:31:50 ^
1.5.2020, 19:31:50 SyntaxError: Unexpected token =
1.5.2020, 19:31:50 at Module._compile (internal/modules/cjs/loader.js:721:23)
1.5.2020, 19:31:50 at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
1.5.2020, 19:31:50 at Module.load (internal/modules/cjs/loader.js:653:32)
1.5.2020, 19:31:50 at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
1.5.2020, 19:31:50 at Function.Module._load (internal/modules/cjs/loader.js:585:3)
1.5.2020, 19:31:50 at Module.require (internal/modules/cjs/loader.js:690:17)
1.5.2020, 19:31:50 at require (internal/modules/cjs/helpers.js:25:18)
1.5.2020, 19:31:50 at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:23:16)
1.5.2020, 19:31:50 at Module._compile (internal/modules/cjs/loader.js:776:30)
1.5.2020, 19:31:50 at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

```

**Additional context**

**Comment by fasm** [comment]
I have the exact same issue. Good to know it wasn't just me. I tried factory reset, but that didn't change anything. I backed up my config.json and will unfortunately have to do a full wipe.

**Comment by sanjeevshah** [comment]
I have the same problem. Can you please provide instructions on reverting back to 3.1.27?

**Comment by mkellsy** [comment]
What version of Node are you on?
Run this command and post the results
```
node -v
```

**Comment by fasm** [comment]
I re-imaged my SD card with fresh 3.2.0. 
STILL doesn't work, so it's not a problem with the upgrade. Something is wrong with 3.2.0 is general.

**Comment by BenBike** [comment]
Same issue after update. 
Node v10.16.0

**Comment by mkellsy** [comment]
@fasm can you post the logs from the fresh image?

**Comment by fasm** [comment]
@mkellsy Prior to the reimage, I had the same error shown in the original post.

Now, this is all I have:
`5/1/2020, 1:26:24 PM - HOOBS listening on port 80.
5/1/2020, 1:26:25 PM - No plugins found.
5/1/2020, 1:26:26 PM - Bridge is running on port 51826.`

Not very informative, I know. It doesn't even show any attempts to start the service. Much like before reimaging, I am not able to access Plugins, System, or Configuration.

**Comment by mkellsy** [comment]
I am building 3.2.1 now.

**Comment by sanjeevshah** [comment]
node is v10.16.0 and nom is v6.9.0

**Comment by mkellsy** [comment]
You can upgrade to 3.2.1 it should fix the issue.
If you don't see the update, reboot.

**Comment by JazzerAlto** [comment]
I updated to 3.2.1 and show node v12.13.1

**Comment by JBuchanan63** [comment]
Bridge Service will not start on v3.2.1 for me either.

**Comment by xalex88** [comment]
Good Morning, 

What a Reaktion! Wow! 
Update 3.2.1 Is done and works.
Thanks 👍👍👍

Node is 10.16.0

**Comment by BenBike** [comment]
Update also works for me, thanks 👍🏻

**Comment by JBuchanan63** [comment]
Has anyone who upgraded to 3.2.1 that was having issue with Bridge Service NOT running figure out a solution to get it to run?

**Comment by mkellsy** [comment]
3.2.2 is published to NPM. It may take a few hours to show up.

**Comment by vypergts** [comment]
Updated to 3.2.2 and still can’t start bridge service.

**Comment by mkellsy** [comment]
Logs please or open a new issue.
