### ISSUE TITLE
Only Chrome is working, Firefox, Edge won't go into some categories

### ISSUE THREAD

**Issue by Seexelas** [hoobs-org/HOOBS#581]
**Description**
Since I did a clean install in Docker of Hoobs 3.2.1, when i'm using Firefox, i can go into Configuration, or Plugins, it's like nothin is happening when i click on those categories. I can only manage to get it working by Chrome or Safari on my iPhone

**Version**
3.2.1
Node 12.16.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No, fresh image

**Pervious version**
3.1.7 and it was working great

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X ] Custom Install

**If this is a custom install, what's your operating system?**
Synology DSM6 with Docker 18.09.0.0-0506

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY2F4C",
        "polling_seconds": 5,
        "docker": true
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "1E:8A:31:EF:C9:4C"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}
```
5/2/2020, 2:26:48 AM HOOBS listening on port 80.
5/2/2020, 2:26:49 AM No plugins found
5/2/2020, 2:26:49 AM Bridge is running on port 51826.

```
POST LOG HERE
```

**Additional context**
The problems appeared after downloading a the new image 3.2.1. 

Thanks a lot for the help,

**Comment by MikeDeltaHH** [comment]
Same problem here... plugins, software, interface, etc are not reachable with Firefox!

**Comment by Seexelas** [comment]
If you use Chrome, you will have no issues :) it works for me

**Comment by mkellsy** [comment]
This is due to a package that we use called decamelize. I replaced this with a function that works in all browsers.

Fix coming in 3.2.2

**Comment by Seexelas** [comment]
Great thanks

**Comment by mkellsy** [comment]
3.2.2 is published to NPM. It may take a few hours to show up.

**Comment by Seexelas** [comment]
Yes, i'll confirm, it's working again, thanks a lot
