### ISSUE TITLE
3.2.1 Version Issues

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/HOOBS#582]
Description

On the HOOBS UI under the accessories tab I can’t open accessories, System or config. One plugin (tuya-web) is throwing errors

Version
Please include the version of HOOBS you are using.
3.2.1

Did you upgrade
Please let us know if you upgraded from a previous version.
No

Previous version
If you upgraded, please let us know your previous version.
3.2.0

Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1? 
No

Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
No

What device are you using?
Rpi-4

Please let us know the device you are running HOOBS on.
   Yes- HOOBS SD Card
   

If this is a custom install, what's your operating system?
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

List your plugins
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
homebridge-camera-ffmpeg
homebridge-tuya-web
homebridge-wink3
homebridge-magichome-platform

Post your config
This can be found in the interface, Configuration -> Advanced or you can get it via SSH cat ~/.hoobs/etc/config.json

    Remove any passwords from the config file. This is public.

Config below

Post your log
You can get the log from the intercafe. This is in the Log section.

[Wink] Loaded from cache: Sensor (sensor_pod/644868)5/2/2020, 9:42:32 AM [Wink] Loaded from cache: Motion Sensor (sensor_pod/644867)5/2/2020, 9:42:32 AM [TuyaWebPlatform] Initializing TuyaWebPlatform...5/2/2020, 9:42:32 AM Bridge is running on port 51826.5/2/2020, 9:42:32 AM Logitech Web-cam is running on port 43997.5/2/2020, 9:42:32 AM Wyze-Cam-LR is running on port 43771.5/2/2020, 9:42:32 AM [Wink] Refreshing devices...5/2/2020, 9:42:33 AM [Wink] Devices refreshed5/2/2020, 9:42:33 AM [Wink] Checking if hub is reachable (Wink Hub V2, 10.0.0.2)...5/2/2020, 9:42:33 AM [Wink] Hub is reachable locally (Wink Hub V2, 10.0.0.2)5/2/2020, 9:42:34 AM [Wink] Authenticated with local hub (Wink Hub V2, 10.0.0.2)5/2/2020, 9:42:34 AM [TuyaWebPlatform] Adding:  Outdoor Smart Outlet (switch / 32206507c44f3385178e)5/2/2020, 9:42:34 AM [TuyaWebPlatform] Existing Accessory found [ Outdoor Smart Outlet] [32206507c44f3385178e] [4301c29e-9ec0-44dd-b1fa-3df2627c8ca5]5/2/2020, 9:42:35 AM [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot set property 'displayName' of undefined
    at OutletAccessory.updateAccessory (/home/hoobs/.hoobs/node_modules/homebridge-tuya-web/lib/base_accessory.js:88:68)
    at /home/hoobs/.hoobs/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:97:5)5/2/2020, 9:43:34 AM [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot set property 'displayName' of undefined
    at OutletAccessory.updateAccessory (/home/hoobs/.hoobs/node_modules/homebridge-tuya-web/lib/base_accessory.js:88:68)
    at /home/hoobs/.hoobs/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Additional context

Tuya plugin is throwing these errors.... Could be related? Not sure. 

Having some strange issues after upgrading to 3.2.1
Cannot access config, system or plugins pages and one of my plugins in log is spitting out errors

![image](https://user-images.githubusercontent.com/23066923/80851527-530d1680-8bf0-11ea-868a-bfc96ef60aae.png)

**Comment by themick4u** [comment]
NPM -v = 6.14.4
Node -v = 12.16.1

 cat ~/.hoobs/etc/config.json
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISJGL46LI",
        "polling_seconds": 2,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "34994"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "xx",
        "port": 51826,
        "pin": "xx"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "plugins": [
        "homebridge-tuya-web",
        "homebridge-camera-ffmpeg",
        "wink",
        "homebridge-magichome-platform"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Wink",
            "name": "Wink",
            "client_id": "xxx",
            "client_secret": "xxx",
            "access_token": "xxx",
            "refresh_token": "xxx",
            "direct_access": true,
            "temperature_unit": "F",
            "switch_ids": [
                657654
            ],
            "username": "xxx@xxx.com",
            "password": "xxxxx",
            "plugin_map": {
                "plugin_name": "wink"
            }
        },
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxx@xxx.com",
                "password": "xxxxx",
                "countryCode": "01",
                "platform": "tuya",
                "pollingInterval": 60
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            }
        },
        {
            "platform": "Camera-ffmpeg",
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Logitech Web-cam",
                    "motion": true,
                    "manufacturer": "Logitech",
                    "model": "USB Webcam",
                    "serialNumber": "1234567890",
                    "videoConfig": {
                        "source": "-f v4l2 -i /dev/video0",
                        "stillImageSource": "-f video4linux2 -input_format mjpeg -video_size 640x360 -ss 0.9 -i /dev/video0 -frames:v 1",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 30,
                        "maxBitrate": 300,
                        "vcodec": "h264_omx",
                        "packetSize": 188,
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Wyze-Cam-LR",
                    "motion": true,
                    "manufacturer": "Wyze-Cam",
                    "model": "V2",
                    "serialNumber": "A4DA223286C3",
                    "firmwareRevision": "4.28.4.40",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://xxxxx:Homebridge@10.0.0.7/live",
                        "stillImageSource": "-rtsp_flags prefer_tcp -i rtsp://xxxxx:Homebridge@10.0.0.7/live",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 30,
                        "maxBitrate": 299,
                        "vcodec": "h264_omx",
                        "audio": true,
                        "packetSize": 752,
                        "hflip": false,
                        "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
                        "debug": false
                    }
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            }
        },
        {
            "platform": "MagicHome-Platform",
            "lights": [
                {
                    "name": "Living Room LED Strip",
                    "ip": "10.0.0.10",
                    "setup": "RGBW",
                    "purewhite": false
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-magichome-platform"
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"

**Comment by mkellsy** [comment]
HB change the _associatedHAPAccessory to associatedHAPAccessory
In HOOBS we will rename this back to _associatedHAPAccessory with the _

**Comment by themick4u** [comment]
Thanks Michael, keep me posted when you have an update ready to go

**Comment by fabiovit** [comment]
so only just wait for a new update?

**Comment by mkellsy** [comment]
Yes. I am working as fast as I can.

**Comment by mkellsy** [comment]
3.2.2 is published to NPM. It may take a few hours to show up.

**Comment by fabiovit** [comment]
Thanks

**Comment by fabiovit** [comment]
I have updated to 3.2.2. Camera FFMPEG says it is updated but I always get the update request. also I only view the installed packages and not the suggested packages.

**Comment by mkellsy** [comment]
We removed the categories. Too hard to maintain. There should only be Installed and Search.
We are working on a plugin screen redesign.

**Comment by fabiovit** [comment]
Can`t remove or update Camera FFMPEG...

**Comment by fabiovit** [comment]
3/5/2020, 09:56:59 npm
3/5/2020, 09:56:59  ERR! code EEXIST
npm ERR!
3/5/2020, 09:56:59 path /home/hoobs/.hoobs/node_modules/tar/node_modules/.bin/mkdirp
3/5/2020, 09:56:59 npm
3/5/2020, 09:56:59  ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/tar/node_modules/.bin/mkdirp: is outside /home/hoobs/.hoobs/node_modules/tar/node_modules/mkdirp and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/tar/node_modules/.bin/mkdirp
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

**Comment by fabiovit** [comment]
I removed manually from terminal and reinstalled the pluging. All works.
