### ISSUE TITLE
I have no accessories showing!

### ISSUE THREAD

**Issue by barns102** [hoobs-org/HOOBS#584]
**Description**
On the HOOBS UI under the accessories tab I can’t see any accessories.  

**Version**
Please include the version of HOOBS you are using.
3.2.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [Y ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.2.0
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [Y ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Raspberry Pi 
**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Ring
Broadlink RM
TPLink Smarthome 
PanasonicTV
Camera FFMPEG
Mijia Camera 

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
The only error that has come up in the logs is the following:
02/05/2020, 10:37:52 am [Broadlink RM] Broadlink RM won't detect device failures due to a permissions issues with "net-ping".

To fix:

Run "which node" to determine your node path.
Run "sudo setcap cap_net_raw+ep /path/to/node".
Note: Replacing /path/to/node with the path you found in the first step.
02/05/2020, 10:37:52 am [Broadlink RM] Sky Toggle getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] TV Toggle getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] Soundbar Toggle getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] Sky Power getSwitchState: true
02/05/2020, 10:37:52 am [Broadlink RM] TV Power getSwitchState: true
02/05/2020, 10:37:52 am [Broadlink RM] Vol. Up getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] Sky and ChromeCast getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] Apple Tv getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] Netflix getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] Vol. Down getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] Sky Select getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] Chrome Cast Select getSwitchState: false
02/05/2020, 10:37:52 am [Broadlink RM] TV Mute getSwitchState: false

**Comment by mkellsy** [comment]
We recently moved away from NGINX. Our images do set the permissions on the node binary.
To fix this, set the server port to 3000 +.

We are going to make the default a higher port and only changer this for our pre-built images.

**Comment by resgroupmsr** [comment]
Went to bed, all was working.  Woke up, got prompted to update ffmpeg and nest plug ins.  FFMPEG was updated, Nest now gone and won't reinstall.

**Comment by mkellsy** [comment]
@resgroupmsr not the same issue this guy is having.

Please open a new issue. Anyway we are working on a fix for this in version 3.2.2. Will be out soon.

**Comment by mkellsy** [comment]
3.2.2 is published to NPM. It may take a few hours to show up.

**Comment by barns102** [comment]
I have been able to update to 3.2.2, but I still don’t see any accessories under the accessories tab, @mkellsy what am I doing wrong?

**Comment by barns102** [comment]
This is their only error (is it an error) showing up in the logs:
03/05/2020, 8:34:49 am [Broadlink RM] Broadlink RM won't detect device failures due to a permissions issues with "net-ping".

To fix:

 1. Run "which node" to determine your node path.
2. Run "sudo setcap cap_net_raw+ep /path/to/node".

**Comment by mkellsy** [comment]
Broadcom may be having issues
```
sudo setcap cap_net_raw+ep /use/local/bin/node
```

**Comment by barns102** [comment]
@mkellsy 
This is what I got 
![49C85D65-951E-4646-8363-6A6B3DF02D2C](https://user-images.githubusercontent.com/40626743/80892729-746d2000-8d20-11ea-8387-ba7c63f45bde.jpeg)

**Comment by mkellsy** [comment]
Typos, sorry I am very busy, typing too fast.

/use -> /usr

Broadcom may be having issues
```
sudo setcap cap_net_raw+ep /usr/local/bin/node
```

You may also need to add the hoobs binary too
```
sudo setcap cap_net_raw+ep /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
```

**Comment by barns102** [comment]
@mkellsy 
So I have run those commands, and restarted, and the Broadlink error is no longer showing, but I still can’t see my accessories in the accessory tab.

**Comment by barns102** [comment]
@mkellsy 
Does this have something to do with the port ranges?

**Comment by mkellsy** [comment]
no

**Comment by mkellsy** [comment]
It's hard to say. Do the accessories show up in HomeKit?

**Comment by barns102** [comment]
@mkellsy 
Yeah they do show up in HomeKit,  just not HOOBS UI.

Is this something I should get over, I just struggle when things don’t work as they should!!

FYI, I absolutely love HOOBS, it has transformed home automation for me.

Thanks for your help.

**Comment by mkellsy** [comment]
I think we might not have those accessories defined in HOOBS. It it is a TV type, we don't have that yet.

**Comment by barns102** [comment]
I have several accessories, TPLink sockets, Ring Doorbell, Panasonic TV, Mijia Cameras, Nest Protect, as well as the broadlink RM.

None of them show up.

**Comment by mkellsy** [comment]
I will need to investigate that. Make a system backup and a download your logs. Then email them to me mkellsy@hoobs.org

Config Screen -> Backup - System

**Comment by BobbySlope** [comment]
@barns102 is the issue solved? if not reopen and provide more info

**Comment by barns102** [comment]
Hi, @BobbySlope  no this issue is not resolved. I have already updated to 3.2.3 and yet I still don’t have any accessories showing in the HOOBS UI. My log is not reporting any errors.

**Comment by BobbySlope** [comment]
did u set the backup to @mkellsy ?

**Comment by barns102** [comment]
@BobbySlope. I tried to, but my email said the size of the file exceeds to limit. I will investigate this further.
