### ISSUE TITLE
Possible to install a "branch" of a plugin?

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#586]
Want to test a "branch" of the plugin "Dyson Pure Cool" (#ph01).
How can I install this to hoobs?
I installed it manually via terminal, but hoobs ignores this and still uses the "master" version.
`npm install -g `https://github.com/lukasroegner/homebridge-dyson-pure-cool.git#ph01``

**Comment by mkellsy** [comment]
HOOBS doesn't allow plugins installed globally to run. This is for security. Plugins are made by the community, and anyone with poor intentions could gain access to your device.

To install plugins from source, You need to install the plugin into the user space. You need to be logged in as the user that is running HOOBS.
```
cd ~/.hoobs
npm install https://github.com/lukasroegner/homebridge-dyson-pure-cool.git#ph01
```

Then edit the config.json file (has to be done from the terminal.
```
nano ~/.hoobs/etc/config.json
```

Edit the "plugins" directive and add `homebridge-dyson-pure-cool`
While you have the config file open, add the necessary config for the plugin. And add this code to the config.
```
plugin_map: {
    plugin_name: "homebridge-dyson-pure-cool"
}
```

Then restart the HOOBS service
```
sudo hoobs service restart
```

**Comment by Christian-CFP** [comment]
@mkellsy `cd ~/.hoobs` this was the key. Thank you.
