### ISSUE TITLE
Plug in are not installing 

### ISSUE THREAD

**Issue by treforparr** [hoobs-org/HOOBS#590]
No plugging are installing at all 

02/05/2020, 14:04:45 HOOBS listening on port 80.
02/05/2020, 14:04:46 No plugins found.
02/05/2020, 14:04:46 Bridge is running on port 51826.
02/05/2020, 14:06:04 npm
02/05/2020, 14:06:04 
02/05/2020, 14:06:04 ERR!
02/05/2020, 14:06:04  Unexpected end of JSON input while parsing near '...ttps://registry.npmjs'
02/05/2020, 14:06:04 
02/05/2020, 14:06:04 npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-02T13_06_04_910Z-debug.log
02/05/2020, 14:07:29 npm
02/05/2020, 14:07:29  WARN
02/05/2020, 14:07:29  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
02/05/2020, 14:08:29 npm
02/05/2020, 14:08:29 ERR! Response timeout while trying to fetch https://registry.npmjs.org/aws4 (over 30000ms)
02/05/2020, 14:08:29 
02/05/2020, 14:08:29 npm
02/05/2020, 14:08:29  ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-02T13_08_29_819Z-debug.log big log of error help

**Comment by mkellsy** [comment]
What plugin were you trying to install?

**Comment by treforparr** [comment]
All of then and none are working

**Comment by mkellsy** [comment]
What plugins are you trying to install.

I am able to install plugins. So to find out what is going on, we need to test the plugins you are trying to install.

I also need to know what device you are running HOOBS on. We support many platforms. What Node version?

When I search NPM for "All of them" I get 109 packages
https://www.npmjs.com/search?q=All%20of%20them

**Comment by treforparr** [comment]
Managed to get it working but about to reinstall hoobs

**Comment by BobbySlope** [comment]
we solved that on remote support
