### ISSUE TITLE
Can't update or newly install Shelly plugin after 3.2.1 update

### ISSUE THREAD

**Issue by bcarli2910** [hoobs-org/HOOBS#593]
**Description**
Upgrade to HOOBS 3.2.1 went without problems. After the upgrade HOOBS showed that my (certified) Shelly plugin can be updated. So I clicked on "Update"...  But the update never succeeded, so after a restart of Homebridge service, I received an error and (because it couldn't find the Shelly plugin). 

I tried to freshly install the Shelly plugin, but the HOOBS screen for plugins just hangs (btw. the whole plugin screen is broken in this release, since I only have a Search function, all other previously shown plugins are gone). 

**Version**
Please include the version of HOOBS you are using.
3.2.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
Upgraded from last previous HOOBS version to 3.2.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
HOOBS image for RAPSI 4

**List your plugins**
The relevant plugin here is only **homebridge-shelly**

**Post your config**
{
    "server": {
        "port": 8080,
        "autostart": 1,
        "home_setup_id": "X-HM://0023ISYWZFPND",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "85570"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-155",
        "username": "B2:6A:AE:5E:B0:4D"
    },
    "description": "Bernhards Homebridge ",
    "ports": {},
    "accessories": [
        {
            "accessory": "marantz-volume",
            "name": "Denon",
            "host": "192.168.1.73:8080",
            "plugin_map": {
                "plugin_name": "homebridge-marantz-volume",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "Shelly",
            "plugin_map": {
                "plugin_name": "homebridge-shelly"
            },
            "name": "Shelly",
            "admin": {
                "enabled": false,
                "port": 8181
            }
        },
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        },
        {
            "platform": "eWeLink",
            "name": "eWeLink",
            "countryCode": "49",
            "email": "dummy@dummy.com",
            "password": "some password",
            "imei": "Some IMEI",
            "plugin_map": {
                "plugin_name": "homebridge-ewelink-max"
            }
        }
    ]
}

**Post your log**
02/05/2020, 16:42:22 HOOBS listening on port 8080.
02/05/2020, 16:42:25 Loaded plugin "homebridge-ewelink-max".
02/05/2020, 16:42:25 homebridge API version: 2.5
02/05/2020, 16:42:25 Loaded plugin "homebridge-marantz-volume".
02/05/2020, 16:42:25 Loaded plugin "homebridge-tplink-smarthome".
02/05/2020, 16:42:26 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
02/05/2020, 16:42:26 Error: The requested platform "Shelly" was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/api.js:128:23)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:271:35)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:87:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
02/05/2020, 16:42:26 Got SIGTERM, shutting down Bridge...
02/05/2020, 16:43:13 + homebridge-shelly@0.12.0
updated 1 package in 5.388s
02/05/2020, 16:43:13 
16 packages are looking for funding
  run `npm fund` for details
02/05/2020, 16:44:31 + homebridge-shelly@0.12.0
updated 1 package in 4.848s
02/05/2020, 16:44:32 
16 packages are looking for funding
  run `npm fund` for details
02/05/2020, 16:46:34 + homebridge-shelly@0.12.0
updated 1 package in 4.925s
02/05/2020, 16:46:35 
16 packages are looking for funding
  run `npm fund` for details

**Additional context**

**Comment by mkellsy** [comment]
This is due to an error in the plugin install.

I have a fix coming soon in 3.2.2

**Comment by MrWGT** [comment]
The same occurs with hue plugin.

**Comment by mkellsy** [comment]
This is due to an error in the plugin install.

I have a fix coming soon in 3.2.2

**Comment by mkellsy** [comment]
3.2.2 is published to NPM. It may take a few hours to show up.

**Comment by bcarli2910** [comment]
Ok, manually removing the Shelly plugin from the config, updating to 3.2.2 and adding the Shelly plugin again, things started to work again. 

But there still something wrong with the plugin screen (I tried on three different browsers, Safari, Chrome & Firefox - same problem with all of them): I can see only my installed plugins and have an additional Search option to search for plugins.

**Comment by mkellsy** [comment]
Yes we removed the categories. Making changes here. There should only be Installed and Search.
