### ISSUE TITLE
How to update Hoobs on Synology Docker

### ISSUE THREAD

**Issue by Seexelas** [hoobs-org/HOOBS#595]
**Description**
How can i update Hoobs inside my docker image on Synology ? I don't see the button to update in the Configuration page (when i was in 3.1.17), and if i duplicate the container, i go to the default settings and have to restore my system and configuration. 

**Version**
3.2.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Synology DSM6 with docker

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY2F4C",
        "polling_seconds": 5,
        "docker": true
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "1E:8A:31:EF:C9:4C"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
I tried to search on the Google, but didn't find anything helpfull. 

Thanks a lot for the help,

**Comment by mkellsy** [comment]
You don't upgrade Docker containers, you rebuild them. You need to rebuild the container with the latest image from Docker Hub.

**Comment by Seexelas** [comment]
Ok great thanks, i will try this
