### ISSUE TITLE
Error Update HOOBS v3.2.2

### ISSUE THREAD

**Issue by Stewart06** [hoobs-org/HOOBS#596]
Description
Bonjour, je vous contact car depuis la mise à jour de HOOBS en version 3.2.1 plus aucun service ne démarre. J'ai également fait la mise à jour de RING et le plugin a disparu. Auriez-vous une solution ?

*J'ai effectué la mise à jour en version 3.2.2 et le serveur ne démarre toujours pas.

Version
Please include the version of HOOBS you are using.
3.2.1
Did you upgrade
Please let us know if you upgraded from a previous version.

[*] Yes
  No
Pervious version
If you upgraded, please let us know your previous version.
Version precedente 3.2.0

Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.

  Yes
[*] No
What device are you using?
Please let us know the device you are running HOOBS on.

  HOOBS Box
  HOOBS SD Card
[*] Custom Install
If this is a custom install, what's your operating system?
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
HOOBS image GitHub
List your plugins
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Apple TV Remote
Camera FFMPEG
Delay Switch
Dummy
Dummy Thermostat
Ewelink Max
Rpitemp
Samsung Tizen
Wol

Post your config
This can be found in the interface, Configuration -> Advanced or you can get it via SSH cat ~/.hoobs/etc/config.json

Remove any passwords from the config file. This is public.
{
    "server": {
        "port": 8090,
        "origin": "*",
        "autostart": 1,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 15,
        "theme": "hoobs-light",
        "locale": "fr",
        "temp_units": "celsius",
        "country_code": "FR",
        "postal_code": "06340"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "",
        "username": ""
    },
    "description": "",
    "ports": {
        "comment": "HOOBS",
        "start": 40000,
        "end": 42000
    },
    "plugins": [
        "homebridge-samsung-tizen",
        "homebridge-dummy",
        "homebridge-dummy-thermostat",
        "homebridge-apple-tv-remote",
        "homebridge-wol",
        "homebridge-ewelink-max",
        "homebridge-delay-switch",
        "homebridge-rpitemp",
        "homebridge-camera-ffmpeg"
    ],
    "accessories": [
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": true,
            "time": 1000,
            "name": "Mode Eco ON - OFF"
        },
        {
            "accessory": "Thermostat",
            "plugin_map": {
                "plugin_name": "homebridge-dummy-thermostat",
                "index": 0
            },
            "name": "Thermostat",
            "temperatureDisplayUnits": "°C",
            "model": "Nest",
            "manufacturer": "Apple"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": true,
            "time": 1000,
            "name": "Protection ON - OFF"
        },
        {
            "accessory": "NetworkDevice",
            "name": "Imprimante HP",
            "ip": "",
            "mac": "",
            "plugin_map": {
                "plugin_name": "homebridge-wol",
                "index": 0
            }
        },
        {
            "accessory": "NetworkDevice",
            "name": "PC Serveur",
            "ip": "",
            "mac": "",
            "plugin_map": {
                "plugin_name": "homebridge-wol",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "Minuterie Cuisine",
            "disableSensor": true,
            "delay": 600000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "Minuterie Couloir Haut",
            "disableSensor": true,
            "delay": 120000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "Minuterie Escalier",
            "disableSensor": true,
            "delay": 60000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "Minuterie Couloir Bas",
            "disableSensor": true,
            "delay": 120000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "Minuterie Ch Timéo",
            "disableSensor": true,
            "delay": 600000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "Minuterie Ch Garçons",
            "disableSensor": true,
            "delay": 720000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "Minuterie Toilette",
            "disableSensor": true,
            "delay": 600000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            }
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": true,
            "reverse": true,
            "time": 1000,
            "name": "iMac 27"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": true,
            "time": 5000,
            "name": "HOOBS Pi - On - Off"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": true,
            "time": 15000,
            "name": "Appel - Ch de Timéo"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": true,
            "time": 15000,
            "name": "Appel - Ch des Garçons"
        },
        {
            "accessory": "RpiTemp",
            "name": "HOOBS",
            "tempid": "cpu",
            "plugin_map": {
                "plugin_name": "homebridge-rpitemp",
                "index": 0
            }
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": true,
            "time": 60000,
            "name": "HK Cam 2 - On - Off"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": true,
            "time": 60000,
            "name": "MotionEye - On - Off"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": true,
            "time": 60000,
            "name": "HK Cam 1 - On - Off"
        }
    ],
    "platforms": [
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Samsung Salon",
                    "ip": "",
                    "mac": "",
                    "switches": [
                        {
                            "name": "Mute",
                            "mute": true
                        },
                        {
                            "name": "Vol +",
                            "command": "KEY_VOLUP"
                        },
                        {
                            "name": "Vol -",
                            "command": "KEY_VOLDOWN"
                        }
                    ],
                    "inputs": [
                        {
                            "name": "1 - Direct TV",
                            "type": "command",
                            "value": [
                                "KEY_SOURCE",
                                "KEY_LEFT*3",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "2 - YouTube",
                            "type": "app",
                            "value": "111299001912"
                        },
                        {
                            "name": "3 - Netflix",
                            "type": "app",
                            "value": "11101200001"
                        },
                        {
                            "name": "4 - Prime Video",
                            "type": "app",
                            "value": "3201512006785"
                        },
                        {
                            "name": "5 - Disney+",
                            "type": "app",
                            "value": "3201901017640"
                        },
                        {
                            "name": "6 - Xiaomi Mi Box",
                            "type": "command",
                            "value": [
                                "KEY_SOURCE",
                                "KEY_LEFT*6",
                                "KEY_RIGHT*3",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "7 - PlayStation 4",
                            "type": "command",
                            "value": [
                                "KEY_SOURCE",
                                "KEY_LEFT*6",
                                "KEY_RIGHT*1",
                                "KEY_ENTER"
                            ]
                        }
                    ]
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "name": "SamsungTizen",
            "app_list": false,
            "keys": {
                "REWIND": [
                    {
                        "name": "Vol +",
                        "command": "KEY_VOLUP"
                    }
                ]
            }
        },
        {
            "platform": "AppleTvPlatform",
            "devices": [
                {
                    "name": "Apple Tv 4k On - Off",
                    "credentials": "",
                    "isOnOffSwitchEnabled": true,
                    "onOffSwitchName": "Apple Tv 4k On - Off"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-apple-tv-remote"
            },
            "name": "Apple TV Platform"
        },
        {
            "platform": "eWeLink",
            "name": "eWeLink",
            "countryCode": "",
            "email": "@",
            "password": "",
            "imei": "",
            "plugin_map": {
                "plugin_name": "homebridge-ewelink-max"
            }
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "debug": false,
            "refreshToken": ""
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "cameras": [
                {
                    "name": "Caméra Couloir",
                    "manufacturer": "D-Link",
                    "model": "DCS-932b1",
                    "serialNumber": "62576306",
                    "firmwareRevision": "2.18",
                    "motion": false,
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://mjpeg.cgi",
                        "stillImageSource": "-f mjpeg -i http://mjpeg.cgi",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 1080,
                        "maxFPS": 30
                    }
                },
                {
                    "name": "Caméra Exterieur",
                    "manufacturer": "D-link",
                    "model": "DCS-932b1",
                    "serialNumber": "62576328",
                    "firmwareRevision": "2.18",
                    "motion": false,
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://mjpeg.cgi",
                        "stillImageSource": "-f mjpeg -i http://mjpeg.cgi",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 1080,
                        "maxFPS": 30
                    }
                },
                {
                    "name": "Caméra de Timéo",
                    "manufacturer": "Mydlink",
                    "model": "MotionEye",
                    "serialNumber": "62576328",
                    "firmwareRevision": "2.18",
                    "motion": false,
                    "videoConfig": {
                        "source": "-re -i http://?action=stream",
                        "stillImageSource": "-i http://?action=stream/",
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "maxHeight": 1080,
                        "maxFPS": 20
                    }
                },
                {
                    "name": "Caméra des Garçons",
                    "manufacturer": "Mydlink",
                    "model": "MotionEye",
                    "serialNumber": "62576328",
                    "firmwareRevision": "2.18",
                    "motion": false,
                    "videoConfig": {
                        "source": "-re -i http://?action=stream",
                        "stillImageSource": "-i http://?action=stream/",
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "maxHeight": 1080,
                        "maxFPS": 20
                    }
                }
            ]
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
Post your log
You can get the log from the intercafe. This is in the Log section.

02/05/2020 à 16:04:46 HOOBS listening on port 8090.
02/05/2020 à 16:04:49 Loaded plugin "homebridge-apple-tv-remote".
02/05/2020 à 16:04:51 Loaded plugin "homebridge-camera-ffmpeg".
02/05/2020 à 16:04:51 Loaded plugin "homebridge-delay-switch".
02/05/2020 à 16:04:51 Loaded plugin "homebridge-dummy".
02/05/2020 à 16:04:51 Loaded plugin "homebridge-dummy-thermostat".
02/05/2020 à 16:04:52 Loaded plugin "homebridge-ewelink-max".
02/05/2020 à 16:04:52 homebridge API version: 2.5
02/05/2020 à 16:04:52 Loaded plugin "homebridge-rpitemp".
02/05/2020 à 16:04:52 Loaded plugin "homebridge-samsung-tizen".
02/05/2020 à 16:04:52 Loaded plugin "homebridge-wol".
02/05/2020 à 16:04:52 [SamsungTizen] Initializing SamsungTizen platform...
02/05/2020 à 16:04:52 [Apple TV Platform] Initializing AppleTvPlatform platform...
02/05/2020 à 16:04:52 [eWeLink] Initializing eWeLink platform...
02/05/2020 à 16:04:52 [eWeLink] Intialising eWeLink
02/05/2020 à 16:04:52 [eWeLink] Found 0 group(s)
02/05/2020 à 16:04:52 Error: The requested platform "Ring" was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/api.js:128:23)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:271:35)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:87:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
02/05/2020 à 16:04:52 Got SIGTERM, shutting down Bridge...
02/05/2020 à 16:04:52 [Apple TV Platform] Shutting down Apple TV clients...

hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo hoobs service log
Started HOOBS.
HOOBS listening on port 8090.
Loaded plugin "homebridge-apple-tv-remote".
Loaded plugin "homebridge-camera-ffmpeg".
Loaded plugin "homebridge-delay-switch".
Loaded plugin "homebridge-dummy".
Loaded plugin "homebridge-dummy-thermostat".
Loaded plugin "homebridge-ewelink-max".
homebridge API version: 2.5
Loaded plugin "homebridge-rpitemp".
Loaded plugin "homebridge-samsung-tizen".
Loaded plugin "homebridge-wol".
[SamsungTizen] Initializing SamsungTizen platform...
[Apple TV Platform] Initializing AppleTvPlatform platform...
[eWeLink] Initializing eWeLink platform...
[eWeLink] Intialising eWeLink
[eWeLink] Found 0 group(s)
Error: The requested platform "Ring" was not registered by any plugin.
at API.platform (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/api.js:128:23)
at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:271:35)
at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:87:18)
at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
at Object. (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
Got SIGTERM, shutting down Bridge...
[Apple TV Platform] Shutting down Apple TV clients...
homebridge API version: 2.5
hoobs : TTY=pts/0 ; PWD=/home/hoobs/.hoobs/etc ; USER=root ; COMMAND=/usr/local/bin/hoobs service log
pam_unix(sudo:session): session opened for user root by (uid=0)

**Comment by Stewart06** [comment]
J'espère sincèrement que vous allez pouvoir arriver à trouver une solution, sans être obligée de tout effacer la configuration !

I sincerely hope you can come to a solution, without having to erase the configuration!

**Comment by mkellsy** [comment]
Uninstall and reinstall the ring plugin.

**Comment by Stewart06** [comment]
Comment Uninstall le plugin RING car il n’apparait plus dans la liste des plugins ?


How does Uninstall the plugin RING because it no longer appear in the plugin list?


Le 2 mai 2020 à 22:54, Michael Kellsy <notifications@github.com<mailto:notifications@github.com>> a écrit :



Uninstall and reinstall the ring plugin.

**Comment by themick4u** [comment]
Me too, cannot install update to 3.2.2.... What is the cmd line to do so?

**Comment by mkellsy** [comment]
If the plugin doesn't show in the list of installed plugins. Search for it and click install.

**Comment by Stewart06** [comment]
C’est bon j’ai réussi à installer le plugin RING, mais le serveur HOOBS ne démarre toujours pas.

Auriez vous une solution ? Ma maison ne fonctionne plus...


I did manage to install the plugin RING, but the HOOBS server still doesn't start.

Do you have a solution? My house is not working anymore…


PS : Quelle est la commande pour obtenir les logs, sudo ….

PS: What's the order to get the logs, sudo ...

Le 2 mai 2020 à 23:05, Michael Kellsy <notifications@github.com<mailto:notifications@github.com>> a écrit :



If the plugin doesn't show in the list of installed plugins. Search for it and click install.

**Comment by Stewart06** [comment]
Voici les LOGS

hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo hoobs service log
Started HOOBS.
HOOBS listening on port 8080.
Loaded plugin "homebridge-apple-tv-remote".
Loaded plugin "homebridge-camera-ffmpeg".
Loaded plugin "homebridge-delay-switch".
Loaded plugin "homebridge-dummy".
Loaded plugin "homebridge-dummy-thermostat".
Loaded plugin "homebridge-ewelink-max".
homebridge API version: 2.5
Loaded plugin "homebridge-ring".
Loaded plugin "homebridge-rpitemp".
Loaded plugin "homebridge-samsung-tizen".
Loaded plugin "homebridge-wol".
[SamsungTizen] Initializing SamsungTizen platform...
[Apple TV Platform] Initializing AppleTvPlatform platform...
[eWeLink] Initializing eWeLink platform...
[eWeLink] Intialising eWeLink
[eWeLink] Found 0 group(s)
[Ring] Initializing Ring platform...
[Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[Mode Eco ON - OFF] Initializing DummySwitch accessory...
[Mode Eco ON - OFF] Setting switch to true
[Thermostat] Initializing Thermostat accessory...
[Thermostat] Thermostat
[Protection ON - OFF] Initializing DummySwitch accessory...
[Protection ON - OFF] Setting switch to true
[Imprimante HP] Initializing NetworkDevice accessory...
[PC Serveur] Initializing NetworkDevice accessory...
[Minuterie Cuisine] Initializing DelaySwitch accessory...
TypeError: Cannot read property 'hap' of undefined
    at new delaySwitch (/home/hoobs/.hoobs/node_modules/homebridge-delay-switch/index.js:13:23)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:263:39)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:91:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
Got SIGTERM, shutting down Bridge...
[Apple TV Platform] Shutting down Apple TV clients...
homebridge API version: 2.5
   hoobs : TTY=pts/0 ; PWD=/home/hoobs/.hoobs/etc ; USER=root ; COMMAND=/usr/local/bin/hoobs service log
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
Loaded plugin "homebridge-apple-tv-remote".
Loaded plugin "homebridge-camera-ffmpeg".
Loaded plugin "homebridge-delay-switch".
Loaded plugin "homebridge-dummy".
Loaded plugin "homebridge-dummy-thermostat".
Loaded plugin "homebridge-ewelink-max".
homebridge API version: 2.5
Loaded plugin "homebridge-ring".
Loaded plugin "homebridge-rpitemp".
Loaded plugin "homebridge-samsung-tizen".
Loaded plugin "homebridge-wol".
[SamsungTizen] Initializing SamsungTizen platform...
[Apple TV Platform] Initializing AppleTvPlatform platform...
[eWeLink] Initializing eWeLink platform...
[eWeLink] Intialising eWeLink
[eWeLink] Found 0 group(s)
[Ring] Initializing Ring platform...
[Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[Mode Eco ON - OFF] Initializing DummySwitch accessory...
[Mode Eco ON - OFF] Setting switch to true
[Thermostat] Initializing Thermostat accessory...
[Thermostat] Thermostat
[Protection ON - OFF] Initializing DummySwitch accessory...
[Protection ON - OFF] Setting switch to true
[Imprimante HP] Initializing NetworkDevice accessory...
[PC Serveur] Initializing NetworkDevice accessory...
[Minuterie Cuisine] Initializing DelaySwitch accessory...
TypeError: Cannot read property 'hap' of undefined
    at new delaySwitch (/home/hoobs/.hoobs/node_modules/homebridge-delay-switch/index.js:13:23)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:263:39)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:91:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
Got SIGTERM, shutting down Bridge...
[Apple TV Platform] Shutting down Apple TV clients...
   hoobs : TTY=pts/0 ; PWD=/home/hoobs/.hoobs/etc ; USER=root ; COMMAND=/usr/local/bin/hoobs service log
pam_unix(sudo:session): session opened for user root by (uid=0)

Le 2 mai 2020 à 23:05, Michael Kellsy <notifications@github.com<mailto:notifications@github.com>> a écrit :



If the plugin doesn't show in the list of installed plugins. Search for it and click install.

**Comment by Stewart06** [comment]
Avez-vous une solution s'il vous plait ?
Il y a pas un moyen de retourner à la version de HOOBS 3.2.0 ?

Do you have a solution, please?
Is there any way to get back to the version of HOOBS 3.2.0?

**Comment by mkellsy** [comment]
I am working on it.

**Comment by Stewart06** [comment]
Thank You

Cordialement.

Le 3 mai 2020 à 00:52, Michael Kellsy <notifications@github.com> a écrit :

﻿

I am working on it.

**Comment by mkellsy** [comment]
You should be able to upgrade to 3.2.3

**Comment by Stewart06** [comment]
Affirmatif j'ai mettre à jour HOOBS vers la version 3.2.3 et ça y est le serveur redemande, je vous remercie énormément pour le travail que vous avez accompli !

Affirmative I updated HOOBS to version 3.2.3 and this is the server asks again, thank you very much for the work you have done!
