### ISSUE TITLE
unable to install any plugins

### ISSUE THREAD

**Issue by stephenmd** [hoobs-org/HOOBS#597]
**Description**
these last three or 4 updates broke setup. everytime i try to install a plugin whether its zp, hue, smartglass, broadband, ffmpeg. i get this error after trying to install zp. i have done a fresh installation of hoobs. also whenever i press any tab to see plugins or dashboard theres a very long pause or it signs off.
5/2/2020, 4:35:08 PM HOOBS listening on port 80.
5/2/2020, 4:35:09 PM No plugins found.
5/2/2020, 4:35:09 PM Bridge is running on port 51826.
5/2/2020, 4:40:36 PM npm
5/2/2020, 4:40:36 PM  WARN notsup Unsupported engine for homebridge-lib@4.6.1: wanted: {"homebridge":"~1.0.4","node":"^12.16.3"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.6.1
5/2/2020, 4:40:36 PM 
5/2/2020, 4:40:36 PM npm
5/2/2020, 4:40:36 PM  ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/moment/-/moment-2.24.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
5/2/2020, 4:40:36 PM 
5/2/2020, 4:40:36 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-02T20_40_36_673Z-debug.log

**Version**
3.2.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x ] Yes
- [ ] No

**Pervious version**
3.2.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
pi 4
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
havent installed anything yet fresh install
Zoneplayer 

Smart glass

Pi temp

Broadband

Ffmpeg

Harmony

Samsung Tizen

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
have a config but havent added it. this is a fresh install
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
5/2/2020, 4:35:08 PM HOOBS listening on port 80.
5/2/2020, 4:35:09 PM No plugins found.
5/2/2020, 4:35:09 PM Bridge is running on port 51826.
5/2/2020, 4:40:36 PM npm
5/2/2020, 4:40:36 PM  WARN notsup Unsupported engine for homebridge-lib@4.6.1: wanted: {"homebridge":"~1.0.4","node":"^12.16.3"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.6.1
5/2/2020, 4:40:36 PM 
5/2/2020, 4:40:36 PM npm
5/2/2020, 4:40:36 PM  ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/moment/-/moment-2.24.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
5/2/2020, 4:40:36 PM 
5/2/2020, 4:40:36 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-02T20_40_36_673Z-debug.log
```

**Additional context**

**Comment by mkellsy** [comment]
OK. Create a System Backup and email it to me mkellsy@hoobs.org.
I will try to fix your setup.

**Comment by stephenmd** [comment]
ok

**Comment by stephenmd** [comment]
sent

**Comment by mkellsy** [comment]
I am building a new backup for you

**Comment by mkellsy** [comment]
OK there is something going on with homebridge-hue and homebridge-zp. Everything is OK once you are setup, but getting to that point is an issue.

**Comment by stephenmd** [comment]
yea even with homebridge-harmony. that gives an error as well. once setup correect i havent had any issues

but the issues all started after some updates a couple days ago

**Comment by mkellsy** [comment]
It's zp. with hue you can force http, zp you can't and it cycles over and over.

**Comment by stephenmd** [comment]
Okay, so what am I supposed to do going forward?

**Comment by mkellsy** [comment]
I am looking into this. I think another plugin is breaking hue and zp. Those plugins are finicky

**Comment by mkellsy** [comment]
OK. The broadband plugin is breaking hue and zp. You may have to do without this plugin.

To fix this. you need to reset.
```
rm -fR ~/.hoobs
```

Then
```
sudo hoobs service restart
```

And until I figure out what is going on with broadband, you will need to do without or running multiple instances.

**Comment by stephenmd** [comment]
i went ahead and did that & im still receiving errors upon trying to install plugins. 

5/3/2020, 1:05:01 AM HOOBS listening on port 80.
5/3/2020, 1:05:02 AM No plugins found.
5/3/2020, 1:05:02 AM Bridge is running on port 51826.
5/3/2020, 1:09:42 AM npm
5/3/2020, 1:09:42 AM 
5/3/2020, 1:09:42 AM ERR! code EINTEGRITY
5/3/2020, 1:09:42 AM npm
5/3/2020, 1:09:42 AM  ERR! sha512-LIj1tPCJ6IDoERZ1ZhqcQR3RtyHVY0j+7WBwHV1D1UxvrOK3w7PdLIeDlKF6yNsVWZzoqAMW+bcOJ5XDdfAy1Q== integrity checksum failed when using sha512: wanted sha512-LIj1tPCJ6IDoERZ1ZhqcQR3RtyHVY0j+7WBwHV1D1UxvrOK3w7PdLIeDlKF6yNsVWZzoqAMW+bcOJ5XDdfAy1Q== but got sha512-+zmWkf9/DXqIKatSA9VlSbm6vl+St2Fym9Wfj6T7LCcH7M2N696FdTr/8Og5AcUw5W2k/v/U5KoeE8nMwQeeug==. (232740 bytes)
5/3/2020, 1:09:42 AM 
5/3/2020, 1:09:42 AM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-03T05_09_42_551Z-debug.log



this is from fresh install which i then reset like you asked

**Comment by stephenmd** [comment]
upgraded to 3.2.3 and im getting this error upon trying to install homebridge-hue. no plugins are installed.

5/3/2020, 1:21:27 AM HOOBS listening on port 80.
5/3/2020, 1:21:27 AM No plugins found.
5/3/2020, 1:21:27 AM Bridge is running on port 51826.
5/3/2020, 1:29:14 AM npm
5/3/2020, 1:29:14 AM  WARN notsup Unsupported engine for homebridge-lib@4.6.1: wanted: {"homebridge":"~1.0.4","node":"^12.16.3"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.6.1
5/3/2020, 1:29:14 AM 
5/3/2020, 1:29:14 AM npm
5/3/2020, 1:29:14 AM  ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR!
5/3/2020, 1:29:14 AM  request to https://registry.npmjs.org/fakegato-history/-/fakegato-history-0.5.6.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
5/3/2020, 1:29:14 AM 
5/3/2020, 1:29:14 AM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-03T05_29_14_078Z-debug.log

**Comment by mkellsy** [comment]
What's your internet like? Usually the getaddrinfo EAI_AGAIN errors happen when your internet droppes mid install.

**Comment by stephenmd** [comment]
I have good internet & ib have my pi connected directly to access point. I have another pi running pi hole I thought maybe it was blocking it but it isn’t.

**Comment by stephenmd** [comment]
i think the issue comes from this. im trying to get my system back up as i am unable to setup anything at the moment. just have a blank hoobs running ive flashed multiple times and still receiving the same error mentioning this. i believe its part of homebridge hue and zp

WARN notsup Unsupported engine for homebridge-lib@4.6.1: wanted: {"homebridge":"~1.0.4","node":"^12.16.3"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.6.1

**Comment by stephenmd** [comment]
@mkellsy Did you ever remake the backup for me? Also what am I supposed to do going forward as I now have days with a non functioning system

**Comment by BobbySlope** [comment]
@mkellsy please send him the remake backup soon, if you have time

**Comment by stephenmd** [comment]
ive somehow managed to get hoobs working again.. i flashed 3.2.1 then upgraded to 3.2.3 and was having issues installing plugins so i used a backup from february i had which was set up properly and deleted broadband, and havent had any issues besides this

5/6/2020, 11:34:52 AM Loaded plugin "homebridge-camera-ffmpeg".
5/6/2020, 11:34:52 AM Loaded plugin "homebridge-harmony".
5/6/2020, 11:34:52 AM Loaded plugin "homebridge-hue".
5/6/2020, 11:34:52 AM Loaded plugin "homebridge-raspberrypi-temperature".
5/6/2020, 11:34:53 AM Loaded plugin "homebridge-samsung-tizen".
5/6/2020, 11:34:53 AM Loaded plugin "homebridge-zp".
5/6/2020, 11:34:53 AM [Steph's Harmony Hub] HarmonyPlatform Init
5/6/2020, 11:34:53 AM [Sonos] homebridge-zp v1.0.21, node 12.16.2, homebridge v3.2.3, homebridge-lib v4.4.14
5/6/2020, 11:34:53 AM [Sonos] warning: 12.16.2: not using recommended node v12.15.0 LTS
5/6/2020, 11:34:53 AM [Sonos] warning: not using recommended homebridge v0.4.50
5/6/2020, 11:34:53 AM [Hue] config.json: warning: nativeHomeKit: ignoring unknown key
5/6/2020, 11:34:53 AM [Hue] homebridge-hue v0.11.64, node v12.16.2, homebridge v3.2.3
5/6/2020, 11:34:53 AM [Steph's Harmony Hub] WARNING - configureAccessory - TV accessory added in your bridge from cache, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
5/6/2020, 11:34:53 AM [Steph's Harmony Hub] DidFinishLaunching
5/6/2020, 11:34:53 AM [Steph's Harmony Hub] INFO - Loading activities...
5/6/2020, 11:34:53 AM [Sonos] restored 2 accessories from cache
5/6/2020, 11:34:53 AM Office Door is running on port 45769.
5/6/2020, 11:34:53 AM Stephen's TV is running on port 38443.
5/6/2020, 11:34:53 AM Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:310:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
5/6/2020, 11:34:53 AM Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:310:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
5/6/2020, 11:34:53 AM Got SIGTERM, shutting down Bridge...
5/6/2020, 11:34:53 AM [Steph's Harmony Hub] INFO - shutdown

**Comment by stephenmd** [comment]
im actually unable to install homebridge ring and xbox tv

**Comment by Geronyy** [comment]
Hi, i have some nearly same problem... 

Cant install some plugins. Others can be installed.

**Comment by askovi** [comment]
Please open a new issue and follow the bug report template if you're still experiencing problems installing plugins on 3.2.6
