### ISSUE TITLE
Hoobs 3.2.2 Issues (Cannot access config or Plugins)

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/HOOBS#598]
**Description**
Tried Chrome/Firefox and cannot access the plugins (only shows text "Installed Plugins" and not clickable and the config page (blank)

**Version**
3.2.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.2.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Wink3
camera-ffmpeg
tuya-web
magichome-platform

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
 cat ~/.hoobs/etc/config.json
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISJGL46LI",
        "polling_seconds": 2,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "34994"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "xx",
        "port": 51826,
        "pin": "xxx"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "plugins": [
        "homebridge-tuya-web",
        "homebridge-camera-ffmpeg",
        "wink",
        "homebridge-magichome-platform"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Wink",
            "name": "Wink",
            "client_id": "xx",
            "client_secret": "xx",
            "access_token": "xx",
            "refresh_token": "xx",
            "direct_access": true,
            "temperature_unit": "F",
            "switch_ids": [
                657654
            ],
            "username": "xx",
            "password": "xx",
            "plugin_map": {
                "plugin_name": "wink"
            }
        },
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xx",
                "password": "xx",
                "countryCode": "01",
                "platform": "tuya",
                "pollingInterval": 60
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            }
        },
        {
            "platform": "Camera-ffmpeg",
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Logitech Web-cam",
                    "motion": true,
                    "manufacturer": "Logitech",
                    "model": "USB Webcam",
                    "serialNumber": "1234567890",
                    "videoConfig": {
                        "source": "-f v4l2 -i /dev/video0",
                        "stillImageSource": "-f video4linux2 -input_format mjpeg -video_size 640x360 -ss 0.9 -i /dev/video0 -frames:v 1",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 30,
                        "maxBitrate": 300,
                        "vcodec": "h264_omx",
                        "packetSize": 188,
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Wyze-Cam-LR",
                    "motion": true,
                    "manufacturer": "Wyze-Cam",
                    "model": "V2",
                    "serialNumber": "A4DA223286C3",
                    "firmwareRevision": "4.28.4.40",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://xx:Homebridge@10.0.0.7/live",
                        "stillImageSource": "-rtsp_flags prefer_tcp -i rtsp://xx:Homebridge@10.0.0.7/live",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 30,
                        "maxBitrate": 299,
                        "vcodec": "h264_omx",
                        "audio": true,
                        "packetSize": 752,
                        "hflip": false,
                        "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
                        "debug": false
                    }
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            }
        },
        {
            "platform": "MagicHome-Platform",
            "lights": [
                {
                    "name": "Living Room LED Strip",
                    "ip": "10.0.0.10",
                    "setup": "RGBW",
                    "purewhite": false
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-magichome-platform"
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
You may need to clear the cache. I did a full test in Firefox and it works.

**Comment by themick4u** [comment]
> You may need to clear the cache. I did a full test in Firefox and it works.

Can you get me the cmd line for that so I get it right?

**Comment by themick4u** [comment]
I cleared both browser's cache and still no go.... cannot access the config of hoobs or see any of the plugins

**Comment by mkellsy** [comment]
The plugin screen does not have categories anymore, only installed and search. We are redesigning this in a future version.

The categories were too hard to manage.

**Comment by jacobgraf** [comment]
Same issue here. Black screens. If I uninstall the Wink3 plugin, everything works as expected. Anybody get this working? Tried clearing cache and even multiple browsers. Same issue.

**Comment by themick4u** [comment]
No, 3.2.3 is still an issue for me as well accessing the config page. I also had to blow away my magichome-platform Plugin as that was crashing my system after 3.2.1 onward 

**Sent from my iPhone XS Max

**Comment by themick4u** [comment]
@mkellsy 
It appears to be the wink3 plugin. Once I removed it, i was able to see the config page... Reinstalled it, and lost it immediately.... This is on a fresh new reimage of 3.2.2 on sdcard (arm8) on RPI-4

**Comment by themick4u** [comment]
npm5/3/2020, 7:41:56 PM  WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.5/3/2020, 7:41:56 PM npm5/3/2020, 7:41:56 PM  WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.5/3/2020, 7:41:56 PM npm5/3/2020, 7:41:56 PM  WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.5/3/2020, 7:41:59 PM + homebridge-wink3@2.1.0
added 13 packages from 12 contributors in 4.775s5/3/2020, 7:41:59 PM 
3 packages are looking for funding
  run `npm fund` for details5/3/2020, 7:42:00 PM ENOENT: no such file or directory, open '/home/hoobs/.hoobs/node_modules/sshpk/node_modules/tweetnacl/nacl-fast.js'5/3/2020, 7:42:00 PM Unable to determine plugin type for "homebridge-wink3"5/3/2020, 7:42:00 PM Plugin "homebridge-wink3" installed.5/3/2020, 7:42:01 PM ENOENT: no such file or directory, open '/home/hoobs/.hoobs/node_modules/sshpk/node_modules/tweetnacl/nacl-fast.js'5/3/2020, 7:42:01 PM Unable to determine plugin type for "homebridge-wink3"

**Comment by MikeDeltaHH** [comment]
Same here... cannot update to 3.2.3, no access to the system page, cannot update any plugin ... i give up this time and migrate all installed plugins to my other homebrige installation...

**Comment by themick4u** [comment]
I too gave up and went back to flawless working 3.1.22 and restored backup from that version



 

    On Monday, May 4, 2020, 1:56:08 AM EDT, MikeDeltaHH <notifications@github.com> wrote:  
 
 


Same here... cannot update to 3.2.3, no access to the system page, cannot update any plugin ... i give up this time and migrate all installed plugins to my other homebrige installation...

**Comment by jacobgraf** [comment]
Wait a minute. What am I missing here? Why was this closed? Has it been resolved? I don't see any available updates for HOOBS or the Wink plugin and no comments on the closure. 🤔

**Comment by BobbySlope** [comment]
Sorry to Fast

**Comment by themick4u** [comment]
When I removed the wink3 plugin (dumped Wink and went with Hubitat) I was able to rerun the 3.2.3 update successfully. All is well now without Wink

**Comment by jacobgraf** [comment]
I ended up dumping Wink for Hubitat as well and the Hubitat MakerAPI plugin is excellent! :-)

**Comment by themick4u** [comment]
Exactly what I did and I agree 100% with you! Happy happy!

**Sent from my iPhone XS Max
