### ISSUE TITLE
3.2.2 System page is blank

### ISSUE THREAD

**Issue by andy-dinger** [hoobs-org/HOOBS#599]
**Description**
I just upgraded from 3.2.1 and now the system page is blank. All other pages seem visible as usual

**Version**
3.2.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x ] Yes
- [ ] No

**Pervious version**
3.2.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Nest & Landroid 

**Post your config**
There isn’t a Configuration -> Advanced on my phone browser

**Post your log**
02/05/2020, 22:39:58 HOOBS listening on port 8080.
02/05/2020, 22:39:59 Loaded plugin "homebridge-landroid".
02/05/2020, 22:39:59 Loaded plugin "homebridge-nest".
02/05/2020, 22:39:59 [Nest] Initializing Nest platform...
02/05/2020, 22:39:59 [Nest] Fetching Nest devices.
02/05/2020, 22:39:59 [Landroid] Initializing Landroid platform...
02/05/2020, 22:39:59 [Landroid] Restoring Landroid Landroid Bertrand from HomeKit
02/05/2020, 22:39:59 [Landroid] DidFinishLaunching
02/05/2020, 22:40:00 [Landroid] Connected to WORX cloud.
02/05/2020, 22:40:00 [Landroid] Found Landroid in Worx Cloud with name: Bertrand
02/05/2020, 22:40:02 [Landroid] Landroid Bertrand battery level changed to 100
02/05/2020, 22:40:02 [Landroid] Landroid Bertrand status changed to 1 (Home)
02/05/2020, 22:40:03 [Nest] initing thermostat "Hallway Thermostat": deviceId: 09AA01AC15170HX6 structureId: 9d3631a0-115f-11e8-89df-12b753469b0a
02/05/2020, 22:40:03 [Nest] initing home_away_sensor "Home Occupied": deviceId: 9d3631a0-115f-11e8-89df-12b753469b0a structureId: 9d3631a0-115f-11e8-89df-12b753469b0a
02/05/2020, 22:40:03 [Nest] Initializing platform accessory "Hallway Thermostat"...
02/05/2020, 22:40:03 [Nest] Initializing platform accessory "Home Occupied"...
02/05/2020, 22:40:03 Bridge is running on port 51826.

**Additional context**
None

**Comment by themick4u** [comment]
Yep, me too on this as well....

**Comment by mkellsy** [comment]
I fixed this in 3.2.3. You can update now.

**Comment by themick4u** [comment]
That worked for the System, The configuration is still coming up blank page

**Comment by mkellsy** [comment]
See if it eventually comes up.
Also if you could, right click and inspect element. then post the console if there is any error.

**Comment by themick4u** [comment]
Sure, here ya go: Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
vue.runtime.esm.js:1888 Error: Request failed with status code 504
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.l.onreadystatechange (xhr.js:61)
ie @ vue.runtime.esm.js:8
re @ vue.runtime.esm.js:8
ee @ vue.runtime.esm.js:8
(anonymous) @ vue.runtime.esm.js:8

**Comment by themick4u** [comment]
And here it is in Firefox: Loading failed for the <script> with source “blob:http://10.0.0.3/40d18827-b383-46a5-9476-a5bac486dcd4”. interface:1:1
Loading failed for the <script> with source “http://10.0.0.3/lib/chart.js”. interface:1:1
Error: "Request failed with status code 504"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
vue.runtime.esm.js:1888:12
    VueJS 4
        ie
        re
        ee
        ne

**Comment by andy-dinger** [comment]
> I fixed this in 3.2.3. You can update now.

How do I update if the system page is blank?

**Comment by mkellsy** [comment]
From the terminal run this
```
sudo npm install -g --unsafe-perm @hoobs/hoobs@latest
```

**Comment by themick4u** [comment]
Same issue, System is blank.... I’ve tried from iPhone safari, laptop Chrome and Firefox

**Sent from my iPhone XS Max

**Comment by andy-dinger** [comment]
> From the terminal run this
> 
> ```
> sudo npm install -g --unsafe-perm @hoobs/hoobs@latest
> ```

Yup that worked. And now so does the system page again
