### ISSUE TITLE
HOOBS stops working every restart

### ISSUE THREAD

**Issue by angelflames1337** [hoobs-org/HOOBS#6]
As subject, Hoobs stops working everytime it restart. The logs shows below: 

> [8/7/2019, 7:07:36 PM] [homebridge-config-ui-x] Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
> [8/7/2019, 7:07:36 PM] [homebridge-config-ui-x] Another process or service on this host is using port 8080. Please stop the other service or change the port you have assigned to homebridge-config-ui-x.

Its only resolved when I issue command "sudo killall homebridge-config-ui-x". Any idea how to solve this permanently would be great.

**Comment by BobbySlope** [comment]
Have you installed any other Software on the Rpi using an Websinterface on port 8080?

**Comment by BobbySlope** [comment]
https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#error---eaddrinuse

**Comment by angelflames1337** [comment]
> Have you installed any other Software on the Rpi using an Websinterface on port 8080?

Nothing, only transmission on 9091.

> https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#error---eaddrinuse

Not exactly sure what does this means, I just use HOOBs image from the site, and assume the config is already set in there to start the homebridge.

Since this only works when I kill the homebridge-ui x, I assume there are two instance of homebridge UI is starting and they are overlapping with each other?

Let me know if you need specific log to look at.

**Comment by BobbySlope** [comment]
Please send us the Log. 
HOOBS running only one instance.
