### ISSUE TITLE
3.2.3 - LG WebOS plugin shows no configuration

### ISSUE THREAD

**Issue by kbardai** [hoobs-org/HOOBS#600]
Getting the following error in chrome console.  Let me know if you need anything else more specific.

```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'devices' of undefined
    at a.fieldType (schema-form.vue:208)
    at schema-form.vue?66d2:1
    at a.Le [as _l] (vue.runtime.esm.js:2630)
    at a.F (schema-form.vue?66d2:1)
    at a.t._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at new nr (vue.runtime.esm.js:4468)
    at Nn (vue.runtime.esm.js:4073)
    at a.$r.$mount (vue.runtime.esm.js:8415)
```

**Comment by askovi** [comment]
Which LG WebOS plugin are you using and what's the version?

**Comment by askovi** [comment]
Nevermind. I see the issue. @mkellsy this issue appeared in 3.1.23 only. LG webOS Tv
1.7.1 published 4/23/2020

**Comment by BobbySlope** [comment]
Update to 3.2.3, just checked everything works fine
otherwise just reopen the issue, and provide more info

**Comment by kbardai** [comment]
I'm on version 3.2.3 and here is what I see when I try to configure the LG WebOS Plugin (https://plugins.hoobs.org/plugin/homebridge-webos-tv): https://imgur.com/lI7PRRE

There's no errors in the hoobs console/logs.

I don't know how to re-open the issue once it's closed, let me know what more information you need.
