### ISSUE TITLE
3.2.3 Bridge service will not start

### ISSUE THREAD

**Issue by johnrkingsley** [hoobs-org/HOOBS#601]
Everything worked fine as of early afternoon and then it broke and the service will not start.
[logs (1).txt](https://github.com/hoobs-org/HOOBS/files/4569471/logs.1.txt) there is my latest log from a reboot and attempt to start the service. I made no changes other than wafter it broke I updated to 3.2.3 before that I was on 3.2.2. Thanks.

**Comment by askovi** [comment]
Your Ring access token is invalid. Please get a new one and replace it in the configuration. 
You can use this command in terminal:  `npx -p ring-client-api ring-auth-cli`

**Comment by johnrkingsley** [comment]
I have not cofigured Ring. I don't use it, should I remove the plugin?

**Comment by askovi** [comment]
Yes, only keep plugins that you're using. They must all be configured.

**Comment by johnrkingsley** [comment]
Ok, thank you. It was never a problem previously.

**Comment by askovi** [comment]
There is another issue I see in the logs at the bottom with MyQ not being able to connect. Which plugin are you using for it?

**Comment by johnrkingsley** [comment]
I am using the plugin from within HOOBS. Here is the latest log. The service is running now I have not test to see if everything is working.
[logs (2).txt](https://github.com/hoobs-org/HOOBS/files/4569500/logs.2.txt)

**Comment by johnrkingsley** [comment]
Everything is working the only other issue is Nest but I will likely just remove that. I have never used homekit to control my nests. Thank you, your support has been fantastic.
