### ISSUE TITLE
Hue faulty low battery message

### ISSUE THREAD

**Issue by delucs** [hoobs-org/HOOBS#604]
**Description**
A faulty low battery message is displayed for the heiman smoke detector even with full battery

**Expected behavoir**
Show 100% battery

**Plugin name**
Hue

**Please report the issue to the plugin developer**

**Version**
3.1.22

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Docker

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
This is a Plugin issue, not an HOOBS issue, Please post it in the Github Issues of Hue Plugin

**Comment by delucs** [comment]
according to the author's mail it is a HOOBS problem[https://github.com/ebaauw/homebridge-hue/issues/694](url)

**Comment by mkellsy** [comment]
Please post logs.
