### ISSUE TITLE
Add a menu to shut down the device

### ISSUE THREAD

**Issue by sdecaux** [hoobs-org/HOOBS#605]
**Is your feature request related to a problem? Please describe.**
It is now a pain to safely turn off my raspberry hosting HOOBS (ssh then sudo poweroff)

**Describe the solution you'd like**
Add a menu item in the configuration page or in the "..." menu at top right, with a "switch off" option (that would ask "are you sure?")

**Describe alternatives you've considered**
using ssh, and then typing "sudo poweroff"

**Additional context**
Sometimes one need to safely switch off the device (before cutting off the power for house work, or just need to plug it elsewhere). And it is not safe to just pull the plug, last time I did the SD CARD was corrupted.

**Comment by BobbySlope** [comment]
Its already there update to 3.2.3
![62398F77-6E8B-47CB-8572-949810B87A3F](https://user-images.githubusercontent.com/50763727/80921468-dd7f8280-8d76-11ea-8426-82b8758fda7a.jpeg)

**Comment by sdecaux** [comment]
great news! I wish I had seen the release note...
