### ISSUE TITLE
Adding Releasenotes (Changelog) to Updates shown in UI

### ISSUE THREAD

**Issue by sdecaux** [hoobs-org/HOOBS#606]
**Is your feature request related to a problem? Please describe.**
System software menu in the user interface of HOOBS tells that an update is available (now it is 3.2.3). But now way to know what is new, and if the update worth it.

**Describe the solution you'd like**
I would like that in the System > Software screen, when an update is proposed, a link to the release note. 

**Describe alternatives you've considered**
Alternative would be to search in the Git repository, but it is not convenient, and I was not even able to find it! (where is it???)

**Additional context**

**Comment by BobbySlope** [comment]
They are on github releases:
https://github.com/hoobs-org/HOOBS/releases

**Comment by BobbySlope** [comment]
We added this enhancement as a task for a future update

**Comment by mkellsy** [comment]
This is done, we just need to add the release notes to the CHANGELOG
