### ISSUE TITLE
Homebridge-Hue error

### ISSUE THREAD

**Issue by AKWillows** [hoobs-org/HOOBS#607]
**Description**
I have set up Homebridge-Hue to connect some Zigbee devices via Deconz/Phoscon. I Installed Deconz/Phoscon using the script on the HOOBS support site and it has installed correctly and I have one door sensor active in it. I have authorised Homebridge-Hue in the Phoscon app and updated the user ID in homebridge config. The plug in is throwing an error in the log file and is not exposing devices to Homebridge.

**Expected behavoir**
The plug in should connect and expose the sensor device in Homebridge and HomeKit

**Plugin name**
Homebridge-Hue

**Please report the issue to the plugin developer**
https://discordapp.com/channels/432663330281226270/432698909509287947/706535857405952001  I was advised there to contact HOOBS support.

**Version**
3.2.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X ] Yes
- [ ] No

**Pervious version**
Whichever was the latest prior to 3.2

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ X ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
It was a HOOBS disk image - Raspbian Release 10
Node Version | 10.16.0
-- | --
**Post your config**
This is the part relevant to the Hue plug in

```
{
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "sensors": true,
            "excludeSensorTypes": [
                "CLIPPresence",
                "Geofence"
            ],
            "host": "192.168.1.70",
            "users": {
                "xxxxxxxxxxx": "xxxxxxxxxxxx"
            },
            "lights": true,
            "heartrate": 2
        }
```

**Post your log**
I have just posted the parts relevant to Hue plugin

```
03/05/2020, 16:53:33 [Hue] config.json: warning: plugin_map: ignoring unknown key
03/05/2020, 16:53:33 [Hue] homebridge-hue v0.11.64, node v10.16.0, homebridge v3.2.3
03/05/2020, 16:53:33 [Hue] warning: not using recommended node version v12.16.2 LTS

03/05/2020, 16:53:35 [Hue] undefined: TypeError: bridgeid: missing string value
    at newTypeError (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:42:52)
    at Function.toString (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:298:13)
    at Object._callbacks.(anonymous function) [as bridgeid] (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:781:40)
    at OptionParser.parse (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:808:29)
    at new HueClient (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueClient.js:41:18)
    at HueBridge.request (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueBridge.js:1105:22)
    at HueBridge.getFullState (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueBridge.js:314:28)
    at HueBridge.accessories (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueBridge.js:93:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
03/05/2020, 16:53:35 [Hue] undefined: 1 accessories
03/05/2020, 16:53:36 [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
03/05/2020, 16:53:36 [Hue] Initializing platform accessory "undefined"...
03/05/2020, 16:53:36 [Hue] undefined: 2 services
03/05/2020, 16:53:36 [Hue] homebridge: error: Accessories must be created with a non-empty displayName.
```

**Additional context**
I have been using HOOBS for some time, but this is the first time I have used Deconz/Phoscon and the Homebridge-Hue app. In the log above I can see some debug info has been dumped, but I am unsure how to access it

**Comment by askovi** [comment]
See if this helps you https://github.com/ebaauw/homebridge-hue/issues/680

**Comment by AKWillows** [comment]
Yes, great that did help - and the sensor is now showing in Homebridge and HomeKit. Is there still an issue with the version of Node? I'm seeing that it is recommending 12.16.2, but I seem to be on 10.16.0

**Comment by BobbySlope** [comment]
You don't need to upgrade node, its just a "warning" because its not the latest node version you have installed. if everything works properly you dont need to upgrade
