### ISSUE TITLE
HOOBS and Panasonic TV Plugin

### ISSUE THREAD

**Issue by ValoV83** [hoobs-org/HOOBS#610]
**Description**
The plugin is used to control Panasonic TV's within the Home app. However it's causing the HomeBridge Service to stop running and you have to restart the service manually.

**Expected behavoir**
Switch On/Off and Switch Inputs of Panasonic TV's through the Home App

**Plugin name**
https://www.npmjs.com/package/homebridge-panasonic-viera-tv

**Please report the issue to the plugin developer**
https://github.com/g30r93g/homebridge-panasonic/issues/37

**Version**
3.2.1
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [* ] Yes
- [ ] No

**Pervious version**
3.1.27

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [* ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ *] Custom Install

**If this is a custom install, what's your operating system?**
Hoobs.org image

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYMJP0",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": "***",
        "latitude": "***",
        "longitude": "-***"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "DE:9F:78:57:64:2E"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Panasonic-TV",
            "name": "TX-42AS650B",
            "ipaddress": "192.168.0.15",
            "inputs": [
                {
                    "id": "TV",
                    "name": "TV",
                    "type": "TV"
                },
                {
                    "id": "HDMI 1",
                    "name": "Apple TV",
                    "type": "HDMI"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-panasonic-viera-tv",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "nest"
            },
            "googleAuth": {
                "apiKey": "***",
                "cookies": "***",
                "issueToken": "***"
            }
        }
    ]
}
**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
04/05/2020, 15:57:26 [TX-42AS650B] X_ScreenState: off
04/05/2020, 15:57:27 [TX-42AS650B] Switching to TV
04/05/2020, 15:57:27 [TX-42AS650B] Powering TV on...
04/05/2020, 15:57:27 TypeError: properties.filter is not a function
    at Subscription.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-panasonic-viera-tv/index.js:255:45)
    at Subscription.emit (events.js:310:20)
    at /home/hoobs/.hoobs/node_modules/node-upnp-subscription/index.js:37:37
    at Parser.<anonymous> (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:310:20)
    at SAXParser.onclosetag (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:1436:13)
04/05/2020, 15:57:27 Got SIGTERM, shutting down Bridge...

**Additional context**

**Comment by BobbySlope** [comment]
did you updated the plugin or did u fresh installed it? which plugin version?

**Comment by ValoV83** [comment]
It was a fresh install off Hoobs and the plugin Version 6.3.0.

**Comment by BobbySlope** [comment]
check there's version 7.0.0 out now

Panasonic Viera Tv
7.0.0 published 5/1/2020 • 3 days ago

**Comment by ValoV83** [comment]
Would you recommend to update my Hoobs version to 3.2.3 prior to updating the plugin?

**Comment by BobbySlope** [comment]
Yes

**Comment by ValoV83** [comment]
Upgraded HOOBS to 3.2.3 and the Panasonic TV plugin to 7.0.0 and still get the error causing Homebridge to crash. 

Log:

05/05/2020, 22:43:26 [TX-42AS650B] Powering TV on...
05/05/2020, 22:43:26 TypeError: properties.filter is not a function
    at Subscription.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-panasonic-viera-tv/index.js:255:45)
    at Subscription.emit (events.js:310:20)
    at /home/hoobs/.hoobs/node_modules/node-upnp-subscription/index.js:37:37
    at Parser.<anonymous> (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:310:20)
    at SAXParser.onclosetag (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:1436:13)
05/05/2020, 22:43:26 Got SIGTERM, shutting down Bridge...

**Comment by g30r93g** [comment]
So the issue was that viera.js tries to log a message about being unable to connect and it crashes since it cannot reference back. I'll be releasing a new version to quickly fix this, but I will make a proper fix for it.

**Comment by ValoV83** [comment]
Thats great! Thanks for finding the fault. I've been avoiding using HOOBS to control my TV as it was crashing homebridge every time.

Look forward to the update and testing the quick fix.

**Comment by ValoV83** [comment]
Issue fixed by the developer - ****

https://github.com/g30r93g/homebridge-panasonic/issues/37
