### ISSUE TITLE
Access Impossible after Install HOOBS Debian 10 

### ISSUE THREAD

**Issue by clem66100** [hoobs-org/HOOBS#612]
**Description**
Impossible to access to hoobs.local (http://192.168.X.X or other methods) after installation on Debian 10.

**Version**
3.2.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

I use a Dell XPS 1530.

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

Debian 10. 
Only HOOBS is on this computer.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "30:8D:39:7D:9B:39"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": [],
    "package_manager": "npm"
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 74.
Stopped HOOBS.
Started HOOBS.
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1284:19)
    at listenInCluster (net.js:1349:12)
    at Server.listen (net.js:1437:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
```

**Additional context**

**Comment by BobbySlope** [comment]
Did u followed this guide?
https://support.hoobs.org/docs/5e763e76e87d1e02b6c19d35

**Comment by clem66100** [comment]
Yes exactly.
More information :
![Capture d’écran 2020-05-03 à 21 14 00](https://user-images.githubusercontent.com/64861727/81099966-02592e80-8f0c-11ea-8aa5-d152e5f7712e.png)
![Capture d’écran 2020-05-03 à 21 32 26](https://user-images.githubusercontent.com/64861727/81099970-0422f200-8f0c-11ea-9310-2f0fa0001198.png)
![Capture d’écran 2020-05-03 à 21 33 13](https://user-images.githubusercontent.com/64861727/81099974-04bb8880-8f0c-11ea-8b2a-f4599889a179.png)
![Capture d’écran 2020-05-04 à 18 08 11](https://user-images.githubusercontent.com/64861727/81099975-04bb8880-8f0c-11ea-8fc3-97f15267ca70.png)

**Comment by askovi** [comment]
Run these in order
`sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs`
`sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`
`sudo reboot`

**Comment by clem66100** [comment]
Amazing !
I try for 2 weeks and you find immediately.
http://hoobs.local doesn't works but http://192.168.X.X:80 YES.

Thank you so much
