### ISSUE TITLE
WiFi connection not possible

### ISSUE THREAD

**Issue by stuermera** [hoobs-org/HOOBS#619]
Hello

I've bought and installed the HOOBS image.
Running fine so far, instead WiFi - I did a setup via Raspi-Config, also manual by editing wpa_supplicant... It won't connect to my WiFi after a reboot.

Any help?
All my other Raspberrys did fine so far.
Thanks.

**Comment by BobbySlope** [comment]
follow these instruction after flashing the image to the sd card:
https://support.hoobs.org/docs/5e95bf740ab68b0344e872d9
