### ISSUE TITLE
Dyson Pure Cool Plugin versions on npm and Hoobs don't match

### ISSUE THREAD

**Issue by Padtline** [hoobs-org/HOOBS#620]
**Description**
Support for Dyson Fan

**Expected behavoir**
Nee Model Supportet

**Plugin name**
Homebridge-dyson-pure-cool

**Version**
3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x ] Custom Install

**Additional context*

hello, i just tried to install the plugin "homebridge-dyson-pure-cool".  Unfortunately Hoobs does not find the latest version of it which I need for my device.  The latest version is 1.7.4 and was released 5 days ago.

**Comment by BobbySlope** [comment]
<img width="466" alt="Screenshot 2020-05-08 at 21 45 43" src="https://user-images.githubusercontent.com/50763727/81443240-5e72bb80-9175-11ea-9c03-e9f66452a9d9.png">
<img width="548" alt="Screenshot 2020-05-08 at 21 46 14" src="https://user-images.githubusercontent.com/50763727/81443244-5fa3e880-9175-11ea-93c9-e5e55191368a.png">

**Comment by Christian-CFP** [comment]
1.7.5 online and still 1.6.5 on hoobs?

**Comment by mkellsy** [comment]
The plugins site is on 1.7.7.

There is a 3 hour cache to reduce network traffic.
