### ISSUE TITLE
ZLLSwitch not appearing in HomeKit 

### ISSUE THREAD

**Issue by lherlitz** [hoobs-org/HOOBS#621]
**Description**
I’ve used the HOOBS-forked plugin of homebridge-hue but a ZLLSwitch I have paired with the Hue bridge is not appearing in HomeKit. 

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
My switch should be appearing as an accessory. 

**Please report the issue to the plugin developer**
The developer has stated that you have forked their plugin and made changes to it, so they cannot help me. 

**Version**
3.2.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ x] Yes
- [ ] No

I never used this plugin on the previous version. 

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

[![PNG-image.png](https://i.postimg.cc/dtmT6ZWW/PNG-image.png)](https://postimg.cc/KRjzvjhL)

**Post your log**
You can get the log from the intercafe. This is in the Log section.

[![PNG-image-2.png](https://i.postimg.cc/x1fN4jh9/PNG-image-2.png)](https://postimg.cc/LnWsqSmW)

**Additional context**

**Comment by askovi** [comment]
The plugin is a fork but it supports the same things. Check the plugin description if your switch is supported
