### ISSUE TITLE
Files are locked / Hoobs - is there a password to unlock file changes

### ISSUE THREAD

**Issue by hexardavies** [hoobs-org/HOOBS#624]
Trying to change a few extra files i placed in the system before Hoobs was installed. how do i unlock this so i can change a few things

nano   /usr/local/bin/cgate/config/C-GateConfig.txt
--

![hoobs_locked to change files](https://user-images.githubusercontent.com/36327886/81634455-68850a80-9452-11ea-93a2-a3669ee1f494.JPG)

**Comment by askovi** [comment]
Have you tried with sudo in front?
`sudo nano /usr/local/bin/cgate/config/C-GateConfig.txt`

**Comment by hexardavies** [comment]
I just figured it out. change the perssions on the file 
sudo chmod 777 /usr/local/bin/cgate/config/C-GateConfig.txt
