### ISSUE TITLE
Manage homebridge instances in hoobs

### ISSUE THREAD

**Issue by raffoul** [hoobs-org/HOOBS#625]
Hi,
Hoobs purpose to create a cluster of hoobs instances. Is it possible to manage a homebridge instance from a hoobs instance ?

Indeed, I have an instance on my raspbeerry pi but another instance is running on jeedom. So I'd like have the ability to manage 2 instances in only one interface (hoobs).

Thank you

Regards,

**Comment by BobbySlope** [comment]
Check these out: 

https://support.hoobs.org/docs/5e764e72e87d1e02b6c19d4c


https://support.hoobs.org/docs/5ea6858d0ab68b0344e872e3

**Comment by raffoul** [comment]
Thanks for your reply.
I've already read the manual. My goal is not to make a cluster. I want to manage an instance that is not a hoobs instance. So I don't know how to do that because the "client" property reference the URI of the hoobs interface.

**Comment by mkellsy** [comment]
HOOBS are Homebridge are not the same. HOOBS has an API that is used to manage these Homebridge doesn;t have this API.
