### ISSUE TITLE
HOOBS won't start after update

### ISSUE THREAD

**Issue by j-ktz** [hoobs-org/HOOBS#628]
**Description**
I updated to the latest version and not HOOBs won't start. Every time I try to restart it it starts and then fails, in the log it says this "Error: Service name is already in use on the network at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27) at Prober.done" and it says Bridge not running. I've also tried restarting my router and unplugging my RPi and plugging back in.
**Version**
Please include the version of HOOBS you are using.
Current Version: 3.2.4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version., not sure?

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Raspberry Pi

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Nest and Ring

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYH25G",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51829,
        "pin": "031-45-154",
        "username": "redacted"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "refreshToken": "token",
            "alarmOnEntryDelay": false,
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "showPanicButtons": false
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "googleAuth": {
                "issueToken": token",
                "cookies": "cookies",
                "apiKey": "APIKEY"
            },
            "email": "*****@gmail.com",
            "password": "",
            "name": "Nest"
        }
    ]
}

```
* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
5/15/2020, 10:37:40 PM [Ring] Adding new accessory lpd_v1 Front Door
5/15/2020, 10:37:40 PM [Ring] Adding new accessory hp_cam_v1 Backyard
5/15/2020, 10:37:40 PM [Ring] Adding new accessory stickup_cam_lunar Entryway
5/15/2020, 10:37:40 PM Front Door is running on port 34995.
5/15/2020, 10:37:40 PM Backyard is running on port 44669.
5/15/2020, 10:37:40 PM Entryway is running on port 43255.
5/15/2020, 10:37:40 PM Error: Service name is already in use on the network at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27) at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10) at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102) at EventEmitter.emit (events.js:223:5) at Socket. (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43) at Socket.emit (events.js:223:5) at UDP.onMessage [as onmessage] (dgram.js:874:8)
5/15/2020, 10:37:40 PM Got SIGTERM, shutting down Bridge...
```

**Additional context**

**Comment by sollymay** [comment]
Having exactly the same issue with my Raspberry pi after updating. My configuration is really similar to what @j-ktz mentions (also have Nest and Ring and thats it)

`5/15/2020, 11:57:52 PM [Ring] Adding new accessory jbox_v1 Front Door
5/15/2020, 11:57:52 PM [Ring] Adding new accessory stickup_cam_v4 Front
5/15/2020, 11:57:52 PM [Ring] Adding new accessory stickup_cam_v4 Backyard
5/15/2020, 11:57:52 PM [Ring] Adding new accessory stickup_cam_mini Garage
5/15/2020, 11:57:52 PM Front Door is running on port 45549.
5/15/2020, 11:57:52 PM Front is running on port 42213.
5/15/2020, 11:57:52 PM Backyard is running on port 33239.
5/15/2020, 11:57:52 PM Garage is running on port 34933.
5/15/2020, 11:57:52 PM Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:223:5)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:223:5)
    at UDP.onMessage [as onmessage] (dgram.js:874:8)
5/15/2020, 11:57:52 PM Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:223:5)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:223:5)
    at UDP.onMessage [as onmessage] (dgram.js:874:8)
5/15/2020, 11:57:52 PM Got SIGTERM, shutting down Bridge... `

**Comment by mkellsy** [comment]
Try rebooting.

**Comment by j-ktz** [comment]
I’ve tried rebooting, unplugging my pi, pluging back in, restarting service, nothing works?

**Comment by mkellsy** [comment]
No prob just asking. Trying to reproduce.

**Comment by mkellsy** [comment]
Another thing you can try is this. In the Help screen, there is a Reset Connection button. This will clear the cache and generate a new username for the bridge.

You will need to re-pair with HomeKit.

**Comment by j-ktz** [comment]
Thanks Michael, I think I got it fixed!!! I did have to reset up Nest but it’s working now.

**Comment by mkellsy** [comment]
Good news! I would like to figure out what is causing this.

**Comment by VasylKhmil** [comment]
Same issue after update, but resetting connection have not helped me

**Comment by askovi** [comment]
If you're still experiencing this issue in 3.2.6 please open a new issue and follow the bug report template.
