### ISSUE TITLE
Can't update Homebridge-Ring

### ISSUE THREAD

**Issue by IT-Lueg** [hoobs-org/HOOBS#629]
**Description**
Can't update Homebridge-RIng Plugin

**Plugin name**
Homebridge-Ring

**Version**
3.2.4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
3.2.3

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry-Image

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
18.5.2020, 03:14:00 - npm
18.5.2020, 03:14:00 -  ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/.bin/ring-auth-cli
18.5.2020, 03:14:00 - npm
18.5.2020, 03:14:00 -  ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/.bin/ring-auth-cli: is outside /home/hoobs/.hoobs/node_modules/@hoobs/ring and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/.bin/ring-auth-cli
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
18.5.2020, 03:14:00 - 
18.5.2020, 03:14:00 - npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-18T01_14_00_975Z-debug.log
18.5.2020, 03:14:01 - Plugin "@hoobs/ring" updated.
```

**Comment by mkellsy** [comment]
Run this in the terminal
```
rm -f /home/hoobs/.hoobs/node_modules/.bin/ring-auth-cli
```

Then try to update.

If that doesn't work, run this
```
cd ~/.hoobs
rm -fR node_modules
npm install
```

**Comment by IT-Lueg** [comment]
Thank you @mkellsy !

Worked right away.
Great support - TOP!
