### ISSUE TITLE
wifi issue with hoobs and soma connect / ifplugd

### ISSUE THREAD

**Issue by toellbe** [hoobs-org/HOOBS#633]
**Description**
I use the Raspberry and Hoobs over wifi. After installing ifplugd as a dependency for a plugin / bridge, the wifi will only work if eth0 plugged. ifplugd was only installed without making any changes to the configuration.

**Version**
3.2.4

**Comment by askovi** [comment]
Can you run this command and post the results 
`ifconfig`

**Comment by toellbe** [comment]
hoobs@hoobs:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.196  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::13d8:5451:cea6:8abd  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:62:1f:6c  txqueuelen 1000  (Ethernet)
        RX packets 35716  bytes 5894467 (5.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34690  bytes 22625067 (21.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 83477  bytes 45185444 (43.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 83477  bytes 45185444 (43.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.197  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::a009:e9a4:b840:fb09  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:62:1f:6d  txqueuelen 1000  (Ethernet)
        RX packets 10551  bytes 2803226 (2.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1499  bytes 1016612 (992.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by toellbe** [comment]
Ok it's the soma connect service  https://github.com/hoobs-org/soma-connect

If I stop the service, the connection is possible without any problems. When I deactivate eth0 and start the somaconnect service, the connection via wifi is immediately interrupted.

**Comment by toellbe** [comment]
How can I remove the wifi that was set up under Hoobs?
/etc/wpa_supplicant/wpa_supplicant.conf is empty ...
