### ISSUE TITLE
Can‘t update homebridge-hue

### ISSUE THREAD

**Issue by ScharV** [hoobs-org/HOOBS#634]
**Description**
Hoobs shows an Update for homebridge-Hue to 0.11.68. Clicking update everything goes his normal way til the notifier says updated successfully. After that Hoobs still shows the update

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
homebridge-hue 

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Hoobs 3.2.4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
Hoobs 3.2.3
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi with Hoobs Buster Image

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Config is same as before and everything is okay, server is Running. Logs don‘t show any hints for this issue. They’re normal.

**Comment by urba1n** [comment]
On a fresh Hoobs install (v3.2.4, node 12.16.2) it is not possible to install the homebridge-hue@0.11.68, because node 12.16.3 is required; might it be related ?

**Comment by mkellsy** [comment]
Node 12.16.3 is recommended, it will install fine on any Node 12.x.

**Comment by ScharV** [comment]
I‘m on node 12.13.1

**Comment by urba1n** [comment]
> Node 12.16.3 is recommended, it will install fine on any Node 12.x.

Would the docker image be based on 12.16.3 ?

**Comment by ScharV** [comment]
@mkellsy any advises?
