### ISSUE TITLE
Mac Install Help

### ISSUE THREAD

**Issue by GregBDA** [hoobs-org/HOOBS#635]
Description: New user coming from Homebridge. Fresh install following the macOS guide. All goes well till starting HOOBS for the first time. I receive the error "listen EACCES: permission denied 0.0.0.0:80"

Version: 3.2.4

Did you upgrade Please let us know if you upgraded from a previous version
No

Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1? Did you perform an upgrade from HOOBS 2.1.1? Some things are different

 No

What device are you using? Please let us know the device you are running HOOBS on.

Custom Install
macOS High Sierra 10.13.6

List your plugins: NONE

Post your config This can be found in the interface, Configuration -> Advanced or you can get it via SSH cat ~/.hoobs/etc/config.json

Remove any passwords from the config file. This is public.

  "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "***-**-***"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": []

POST CONFIG HERE
Post your log You can get the log from the intercafe. This is in the Log section.

hoobs:~ Greg$ hoobs -p ********
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80

**Comment by mkellsy** [comment]
You need to run as root.
```
sudo hoobs
```

**Comment by GregBDA** [comment]
THANK YOU!
