### ISSUE TITLE
Harmony Update 1.3.8 doesnt work

### ISSUE THREAD

**Issue by clipse2004** [hoobs-org/HOOBS#636]
**Description**
After updating the Harmony Plugin to newest Version 1.3.8 it didn’t work. 
I think it’s same Probleme like Ring. 

**Expected behavoir**
Error in Hoobs:

21.5.2020, 19:18:15 [TV Wohnzimmer] (TV Schlafzimmer)INFO - configuring Main TV Service
21.5.2020, 19:18:15 [TV Wohnzimmer] (TV Schlafzimmer)INFO - Configuring Main Activity Cable TV
21.5.2020, 19:18:15 (node:2972) UnhandledPromiseRejectionWarning: TypeError: AccessControlManagement is not a constructor
21.5.2020, 19:18:15 at HarmonySubPlatform.readTVAccessories (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonySubPlatform.js:291:23)
21.5.2020, 19:18:15 at HarmonySubPlatform.readAccessories (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonySubPlatform.js:158:58)
21.5.2020, 19:18:15 at /home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyBase.js:93:27
21.5.2020, 19:18:15 (node:2972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
21.5.2020, 19:18:15 (node:2972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Newest

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
1.3.7

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?** 
No
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Buster

**Additional context**
I hope Hoobs will update soon to Homebridge Version 1.1 :/

**Comment by nicoduj** [comment]
Hi, I have bump homebridge dependency to 1.0.4, so indeed HOOBs needs to update.

**Comment by BobbySlope** [comment]
@nicoduj we are just checking what causes the issue, and fix that and then certify it for hoobs also. can u please remove this one? https://github.com/nicoduj/homebridge-harmony#note

**Comment by b-** [comment]
https://github.com/homebridge/HAP-NodeJS/blob/8ce43281b637fd1fb636436c3d60352dec54ba14/src/lib/tv/AccessControlManagement.ts

It’s failing on AccessControlManagement.

**Comment by nicoduj** [comment]
@BobbySlope Hi, I don't use Hoobs so I can't guarantee that my plugin is working well on it, that is why I made the note. It seems from lots of reports I have that the behavior with hoobs is not really the same (especially with some websockets errors and the fact that you don't respect bump dependencies as far as I can see), so I can't maintain the plugin and especially the support in this case. 

If you are willing to certify my plugin, fine, I can alter the note saying that hoobs user might first check there it is not a hoobs issue if you want, but once again, I won't be able to provide support on this environment so at least I need to say it on my README :)

**Comment by mkellsy** [comment]
Fixed in 3.2.5
Needed to update the HAP core

@nicoduj we would be glad to certify your plugin.
