### ISSUE TITLE
homebridge-hue

### ISSUE THREAD

**Issue by fabiovit** [hoobs-org/HOOBS#638]
I have this problem:
21/5/2020, 19:56:55 [Hue] Phoscon-GW: 1 accessories
21/5/2020, 19:56:55 [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
21/5/2020, 19:56:55 [Hue] Initializing platform accessory "Phoscon-GW"...
21/5/2020, 19:56:55 [Hue] Phoscon-GW: 2 services
21/5/2020, 19:56:55 [Hue] Initializing platform accessory "Phoscon-GW"...
21/5/2020, 19:56:55 [Hue] Phoscon-GW: 2 services
21/5/2020, 19:56:55 [Hue] homebridge: error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 9b0d72f1-8a63-4330-9c5a-79cd3ede0646

**Comment by toellbe** [comment]
I had the same issue when two interfaces were active and so Phoscon started twice / with two IPs.

**Comment by BobbySlope** [comment]
solved?

**Comment by fabiovit** [comment]
Yes, solved.
