### ISSUE TITLE
Cannot access UI via browser

### ISSUE THREAD

**Issue by galexandr** [hoobs-org/HOOBS#646]
**Description**
I am unable to access Hoobs UI via browser. I have only been able to SSH into hoob@hoobs via terminal.

**Version**
3.2.6 

**Did you upgrade**
Yes, upgraded from previous version, i believe i lost when upgrading from 3.2.1

**Pervious version**
I believe i lost access to UI when i came from 3.2.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Cannot access 

**Post your config**
Cannot access

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Try accessing it by the local IP address or add port 8080 at the end like this:

http://hoobs.local:8080

**Comment by mkellsy** [comment]
If you can say I to it. Can you post your config.json file. It is located in ~/.hoobs/etc/config.json.

> Remember to remove passwords.

**Comment by originalmagneto** [comment]
I have the same problem as the OP, can access only when adding the port to the url as suggested by @askovi 

Here is my config file 
[config.json.zip](https://github.com/hoobs-org/HOOBS/files/4676407/config.json.zip)
