### ISSUE TITLE
Error: Listen EADDRINUSE: Address Already In use

### ISSUE THREAD

**Issue by theque9** [hoobs-org/HOOBS#647]
Via Raspberry Pi CLI, receiving the subject error. Unable to access web interface, assuming as a result of this.

**Comment by mkellsy** [comment]
Can you post your log? That error is generic, need the full stack trace.

**Comment by theque9** [comment]
I was able to follow these instructions to get it working:

This fuser 8080/tcp will print you PID of process bound on that port.

And this fuser -k 8080/tcp will kill that process.

Quentin
