### ISSUE TITLE
Busch Jäger API npm ERR! code EACCES

### ISSUE THREAD

**Issue by eustefan** [hoobs-org/HOOBS#648]
**Description**
API for the Busch Jäger Plugin

**Expected behavoir**
npm install freeathome-api --save

**Plugin name**
freeathome-api
1.1.0 • Public • Published 5 months ago

<img width="980" alt="Bildschirmfoto 2020-05-23 um 14 09 25" src="https://user-images.githubusercontent.com/65815253/82730811-cf33df00-9d02-11ea-9e7d-a7b89449081d.png">

Please tell me what the problem is. Thank you

**Comment by askovi** [comment]
If you want to install it in a directory, you need to create one first outside of .hoobs. Here are the commands to follow:
1. `cd /home/hoobs`
2. `mkdir freeathomeapi`
3. `cd freeathomeapi`
4. `sudo npm install freeathome-api --save`
5. Start the API with `node bin/freeathome-api`
You have to also create / edit a config.json file in this folder, using this example: https://github.com/henry-spanka/freeathome-api/blob/HEAD/config.example.json
**Set the port for the websocket server to 8001. The HTTP API can be disabled.**

To automatically start the API at boot, see these instructions: https://www.npmjs.com/package/freeathome-api#automatically-start-on-boot
