### ISSUE TITLE
Can not access UI on new MacOS Install

### ISSUE THREAD

**Issue by pnigrini** [hoobs-org/HOOBS#652]
1.  Please forgive me I am both new and a novice.
2.  I just installed HOOBS on macOS following the instruction page and believe I have successfully completed all of the instructions on the page "2.5.0 macOS Installation" up to "Accessing the Interface"  At this point Safari is unable to open the page.  The Safari tab sill shows a blue loading progress bar, but the page says "Safari Can't Open the page". 
I am trying to load "http://hoobs.local:8080"

In the step prior "Starting HOOBS" I receive the following message in terminal

home@home ~ % hoobs -p 'XXXX'
HOOBS listening on port 80.
No plugins found.
Bridge is running on port 51826.

Thanks for your help.

**Comment by askovi** [comment]
Can you access it on port 80? Just simply: http://hoobs.local

**Comment by pnigrini** [comment]
That fixed it.


Thanks
________________________________
Peter Nigrini
Theatre Designer

**Comment by pnigrini** [comment]
Hello, I am having the same problem outlined above in a new installation.  I don't know if it is the same problem, or a completely different problem, but the result is the same.  I am unable to load the web interface.  I tried the solution presented here to no avail.  At a minimum, I believe hoops is running.  After launching it via terminal I receive the following response.

`Last login: Sat Jun 19 17:09:56 on ttys000
home@SERVER-STUDIO ~ % hoobs -p '5552'
HOOBS listening on port 80.
Initializing HAP-NodeJS v0.9.3...
No plugins installed.
Preparing Advertiser for 'HOOBS 869A' using bonjour-hap backend!
Starting to advertise 'HOOBS 869A' using bonjour-hap backend!
Bridge is running on port 51826.
















`
