### ISSUE TITLE
Plugin not working (homebridge-roku-tv)

### ISSUE THREAD

**Issue by andrewtzn** [hoobs-org/HOOBS#654]
**Description**
The plugin doesn't seem to be running.
(The requested platform "RokuTV" was not registered by any plugin.)

**Expected behavoir**
Plugin should find Roku TV on the network and create a TV accessory in the Home app.

**Plugin name**
homebridge-roku-tv
([https://github.com/JarekToro/homebridge-roku-tv](https://github.com/JarekToro/homebridge-roku-tv))

**Please report the issue to the plugin developer**
Reported.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
N/A

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Platform: 	linux
Distro:	Raspbian GNU/Linux
Release:	10
Codename:	buster
Kernel:	4.19.97-v7l+

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
"platforms": [

        {
            "pollingInterval": 30000,
            "platform": "RokuTV",
            "plugin_map": {
                "plugin_name": "homebridge-roku-tv-plugin"
            },
            "excludedApps": []
        }
]
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
5/25/2020, 3:33:30 PM The requested platform "RokuTV" was not registered by any plugin.
5/25/2020, 3:33:30 PM Your config.json is requesting the platform "RokuTV" which has not been published by any installed plugins.
```

**Additional context**
Please let me know if any additional info is needed.
Thank you!

**Comment by andrewtzn** [comment]
FYI, Here's the ongoing communication with the creator of the plugin:
[https://github.com/JarekToro/homebridge-roku-tv/issues/3](https://github.com/JarekToro/homebridge-roku-tv/issues/3)

**Comment by JarekToro** [comment]
From what I can tell everything is registering fine when using Home-bridge itself. I'm unsure if there would be any compatibility issues when being used via HOOBS

**Comment by askovi** [comment]
I submitted a PR with the fix. Waiting for @JarekToro to approve it.

**Comment by andrewtzn** [comment]
Thank you @askovi for the fix!
The plugin is working well with HOOBS now.

Thank you @JarekToro again for creating the Roku plugin!

Stay well!
