### ISSUE TITLE
Cluster Set UP

### ISSUE THREAD

**Issue by Daryllvang** [hoobs-org/HOOBS#655]
**Description**
Trying to setup a client cluster produces "UnhandledPromiseRejectionWarning"

**Version**
3.2.4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [*] No

**Pervious version**
N/A

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [*] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [*] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry PI 4 (ARM7)

**List your plugins**
No Plugins Virgin Install

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYBBLF",
        "polling_seconds": 5
    },
    "client": {},
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "57:F5:DF:23:F3:F9"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}
```

**Post your log**
Not sure on how to do this

```
POST LOG HERE
```

**Additional context**
THIS IS THE ERROR after running the following commands....
sudo hoobs service stop
sudo hoobs service disable
rm -fR ~/.hoobs
sudo rm -f /etc/systemd/system/hoobs.service
sudo hoobs cluster client
✔ Choose your HOOBS cluster account name … TBA
✔ Choose your HOOBS cluster username … Daryll
✔ Choose your HOOBS cluster password … ******
✔ Confirm your password … ******
(node:2198) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at /usr/local/lib/node_modules/@hoobs/hoobs/scripts/client.js:88:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

THANK YOU FOR YOUR TIME!!

**Comment by BobbySlope** [comment]
we need to investigate here further

**Comment by Daryllvang** [comment]
Thanks

Appreciate your efforts greatly

Kind Regards


Daryll van Geelen
