### ISSUE TITLE
dashboard weather misforecasting 

### ISSUE THREAD

**Issue by wallacepost** [hoobs-org/HOOBS#658]
**Description**
dashboard weather misforecasting , it doesn't match the information from openweathermap.org

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
just received the hub a day ago, updated the firmware. there was same issue from 3.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box

* Remove any passwords from the config file. This is public.

```
 "client": {
        "longitude": "145.03",
        "default_route": "status",
        "latitude": "-37.58",
        "temp_units": "celsius",
        "postal_code": "",
        "country_code": "AU",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en"
```
![Screen Shot 2020-05-27 at 1 32 59 am](https://user-images.githubusercontent.com/65918663/82922849-7c398080-9fbd-11ea-9014-99393f78825d.png)
![Screen Shot 2020-05-27 at 1 37 43 am](https://user-images.githubusercontent.com/65918663/82922872-82c7f800-9fbd-11ea-9379-a6dee889c207.png)
![Screen Shot 2020-05-27 at 1 30 30 am](https://user-images.githubusercontent.com/65918663/82922875-83f92500-9fbd-11ea-8c8b-25f3b69ea218.png)

**Comment by BobbySlope** [comment]
we need to discover more, why there's a difference in forecast

**Comment by pkreipke** [comment]
Is there a way to help diagnose this? I see the same for zipcode "08542"

**Comment by wallacepost** [comment]
any update? thanks

![Screen Shot 2020-06-16 at 1 46 40 am](https://user-images.githubusercontent.com/65918663/84678614-94287280-af73-11ea-90f2-c59cd4c035dd.png)
![Screen Shot 2020-06-16 at 1 47 06 am](https://user-images.githubusercontent.com/65918663/84678624-97bbf980-af73-11ea-98b2-9e90b70ff292.png)
![Screen Shot 2020-06-16 at 1 47 13 am](https://user-images.githubusercontent.com/65918663/84678630-98549000-af73-11ea-9db3-6aaf74e82ee7.png)
