### ISSUE TITLE
no button to uninstall nest-cam2 plugin

### ISSUE THREAD

**Issue by wjkie** [hoobs-org/HOOBS#660]
**Description**
I cannot remove the Nest-Cam2 plugin as it has no uninstall button on the installed plugins page. I tried to uninstall Nest-Cam 2 in the terminal session using this command "sudo npm -g uninstall homebridge-nest-cam2" with no luck on the result.  How can I remove the plugin and eliminate the duplicate plugin situation. Everything was working fine with the Nest-cam2 but i feared that no future updates would be available for the plugin so I wanted to get it working with the replacement.
Appreciate any help i can get.
**Version**
Please include the version of HOOBS you are using.
3.2.6
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x
 ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Nest, 
Nest-Cam
Nest-Cam2 (https://www.npmjs.com/package/homebridge-nest-cam2) 
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYX0KPP1",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": “My Zipcode”
    },
    "bridge": {
        "name": "HOOBS",
        "username": "CC:xx:3D:xx:CE:xx”,
        "port": 51826,
        "pin": "03x-4x-1xx”
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "email": “My Nest Account Email”,
            "password": “M”y Nest Password”,
            "googleAuth": {  “My google  Issue Token”,                
	    "cookies": "My google Cookies”,
                "apiKey": "My google API key
            },
            "name": "Nest",
            "fanDurationMinutes": 15
        },
        {
            "platform": "Nest-cam",
            "ffmpegCodec": "h264_omx",
            "email": “My Nest Account Email”,
            "password": “M”y Nest Password”,
            "googleAuth": {  “My google  Issue Token”,                
	    "cookies": "My google Cookies”,
                "apiKey": "My google API key
            },
            "plugin_map": {
                "plugin_name": "homebridge-nest-cam"
            },
            "options": {
                "motionDetection": true,
                "streamingSwitch": true
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```

5/26/2020, 3:40:39 PM - Loaded plugin "homebridge-nest".
5/26/2020, 3:40:39 PM - Loaded plugin "homebridge-nest-cam".
5/26/2020, 3:40:39 PM - Loaded plugin "homebridge-nest-cam2".
5/26/2020, 3:40:39 PM - [Nest] Fetching Nest devices.
5/26/2020, 3:40:39 PM - The requested platform "Nest-cam" has been registered multiple times.
5/26/2020, 3:40:39 PM - Your config.json is requesting the platform "Nest-cam" which has not been published by any installed plugins.
5/26/2020, 3:40:39 PM - Load homebridge-nest-cam2.Nest-cam
5/26/2020, 3:40:43 PM - [Nest] initing thermostat "Nest Thermostat": deviceId: 02AA01AC231300TG structureId: 1d752990-4809-11e3-xxxa-12313b0cf507
5/26/2020, 3:40:43 PM - [Nest] initing home_away_sensor "Home Occupied": deviceId: 1d752990-4809-11e3-999a-12313b0cf507 structureId: 1d752990-4809-11e3-xxxa-12313b0cf507
5/26/2020, 3:40:43 PM - [Nest] initing protect "Family Room": deviceId: 18B430000023E7B3 structureId: 1d752990-4809-11e3-xxxa-12313b0cf507
5/26/2020, 3:40:43 PM - [Nest] initing protect "Hallway": deviceId: 18B430000024414C structureId: 1d752990-4809-11e3-xxxa-12313b0cf507
5/26/2020, 3:40:43 PM - [Nest] Initializing platform accessory "Nest Thermostat"...
5/26/2020, 3:40:43 PM - [Nest] Initializing platform accessory "Home Occupied"...
5/26/2020, 3:40:43 PM - [Nest] Initializing platform accessory "Family Room"...
5/26/2020, 3:40:43 PM - [Nest] Initializing platform accessory "Hallway"...
5/26/2020, 3:40:43 PM - Bridge is running on port 51826.E
```

**Additional context**
<img width="908" alt="Screen Shot 2020-05-26 at 2 34 29 PM" src="https://user-images.githubusercontent.com/43555886/82946359-31dbe380-9f6c-11ea-8c3a-ded55d59c40b.png">

**Comment by stoplis** [comment]
I am also seeing the exact same issue. I am unable to manually uninstall Nest Cam2 using NPM.

**Comment by wjkie** [comment]
I tried the terminal route to uninstall via NPM with no change in results, still shows up in the installed plugins even after a reboot.  I also tried deleting the Accessories and Persist directory as they may have been keeping the reference and that did not help either. Now the Nest thermostat and Nest protects will not show up in Home app.

**Comment by KiwiV** [comment]
I have exactly the same issue with the Wemo plugin! (no button to uninstall)

**Comment by wjkie** [comment]
I didn't hear back from HOOBS and my being the impatient type.  I just reset my HOOBS to factory settings and reinstalled all my plugins.  Now all is well for me.  But, this did not answer the question on why we couldn't delete the Nest-Cam2 from the HOOBS plugins so I will leave this open for someone to address and correct.

**Comment by KiwiV** [comment]
Thanks for the follow-up on your fix. I came across the Homemanager app yesterday and used this to successfully remove the Wemo plugin from Hoobs :)

**Comment by BobbySlope** [comment]
you can delete the plugin manually in terminal:

sudo rm -Rf /home/hoobs/.hoobs/node_modules/homebridge-nest-cam-2

I thinks thats caused because the plugin dev removed it from nam

**Comment by wjkie** [comment]
I tried that. but it didn't work, probably due to the fact that the Json file, persist directory and accessories directory had remnants/references.  When you remove using the button provided by HOOBS it should clear all these remnants and references.  I fixed it by resetting HOOBS to factory settings, removed HOOBS bridge from Homekit then setup and installed everything from the beginning. All is well now for me.  HOOBS needs to have their product recognize when a plugin has been merged into another to allow you to transition over more cleanly.

**Comment by BobbySlope** [comment]
enhancement: HOOBS needs to have their product recognize when a plugin has been merged into another to allow you to transition over more cleanly.

**Comment by ethempekin** [comment]
i am experiencing this with another plugin.

**Comment by askovi** [comment]
If for whatever reason you cannot uninstall a plugin, put this command in the Terminal and replace the last part with the plugin you want to uninstall: 

`rm -fR ~/.hoobs/node_modules/homebridge-nest-cam2`
