### ISSUE TITLE
Samsung Tizen Plugin

### ISSUE THREAD

**Issue by EddieDSuza** [hoobs-org/HOOBS#662]
**Description**
Installed and configured but the accessories do not appear in hoobs but in apple home it does.

**Expected behavoir**
Works fine in homebridge

**Plugin name**
https://www.npmjs.com/package/homebridge-samsung-tizen

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [N] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] Custom Install - DOCKER

**If this is a custom install, what's your operating system?**
Synology - Linux 

**Post your config**
[
    {
        "name": "TV",
        "ip": "192.168.86.6",
        "mac": "7C:64:56:98:9f:5b",
        "inputs": [
            {
                "name": "Netflix",
                "type": "app",
                "value": "11101200001"
            },
            {
                "name": "Prime",
                "type": "app",
                "value": "3201512006785"
            },
            {
                "name": "YouTube",
                "type": "app",
                "value": "111299001912"
            },
            {
                "name": "YouTube Kids",
                "type": "app",
                "value": "3201611010983"
            },
            {
                "name": "Spotify",
                "type": "app",
                "value": "3201606009684"
            }
        ],
        "switches": [
            {
                "name": "Mute",
                "mute": true
            },
            {
                "name": "Vol Up"
            },
            {
                "name": "Vol Down"
            },
            {
                "name": "HDMI"
            }
        ],
        "refresh": {
            "main": 5000
        }
    }
]

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.
Not available

**Comment by BobbySlope** [comment]
the accessories are not coded yet in the user interface. adding to task list as enhancement
