### ISSUE TITLE
Plugin Labels

### ISSUE THREAD

**Issue by EddieDSuza** [hoobs-org/HOOBS#663]
**Description**
Plugins Like Weather Plus & Soundtouch - their label values are not appearing correctly. The default value is Bose or Weather for all accessories

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [N] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [Y] Custom Install

**If this is a custom install, what's your operating system?**
Linux (Synology / Docker)

**List your plugins**
https://www.npmjs.com/package/homebridge-weather-plus
https://www.npmjs.com/package/homebridge-soundtouch-platform

**Post your config**
{
            "platform": "SoundTouchPlatform",
            "name": "SoundTouch",
            "accessories": [
                {
                    "name": "Bose",
                    "ip": "192.XXX.XX.11",
                    "volume": {
                        "unmuteValue": 25,
                        "maxValue": 100,
                        "mode": "lightbulb"
                    },
                    "presets": [
                        {
                            "name": "Ant 1",
                            "index": 1,
                            "enabled": true
                        },
                        {
                            "name": "Radio 2",
                            "index": 2,
                            "enabled": false
                        },
                        {
                            "name": "Radio 3",
                            "index": 3,
                            "enabled": false
                        },
                        {
                            "name": "Ipanema",
                            "index": 4,
                            "enabled": true
                        },
                        {
                            "name": "Radio 5",
                            "index": 5,
                            "enabled": false
                        },
                        {
                            "name": "Radio 6",
                            "index": 6,
                            "enabled": false
                        }
                    ]
                }
            ],
            "global": {
                "sources": [
                    {
                        "source": "QPLAY",
                        "enabled": false
                    }
                ]
            },
            "plugin_map": {
                "plugin_name": "homebridge-soundtouch-platform"
            }
        },
{
            "platform": "WeatherPlus",
            "plugin_map": {
                "plugin_name": "homebridge-weather-plus"
            },
            "units": "metric",
            "interval": 60,
            "stations": [
                {
                    "nameNow": "Weather",
                    "service": "openweathermap",
                    "key": "XXXXXX",
                    "locationCity": "XXXX, BR",
                    "language": "en",
                    "compatibility": "both",
                    "now": true,
                    "extraHumidity": false,
                    "conditionCategory": "detailed",
                    "hidden": [
                        "ConditionCategory",
                        "TemperatureApparent",
                        "DewPoint",
                        "ForecastDay",
                        "ObservationStation",
                        "ObservationTime",
                        "RainChance",
                        "SnowBool",
                        "TemperatureMin",
                        "WindSpeedMax"
                    ],
                    "units": "metric"
                }
            ]
        },

* Remove any passwords from the config file. This is public.
<img width="1037" alt="Screen Shot 2020-05-28 at 18 17 43" src="https://user-images.githubusercontent.com/52710883/83194907-c5014e80-a10f-11ea-9517-a41622eb2568.png">
<img width="1060" alt="Screen Shot 2020-05-28 at 18 18 46" src="https://user-images.githubusercontent.com/52710883/83194912-c92d6c00-a10f-11ea-85dd-41f1b41de9a9.png">

**Comment by BobbySlope** [comment]
this needs to be done manually in the ui, you can rename them see here:

![](https://raw.githubusercontent.com/hoobs-org/HOOBS/master/docs/accessories/accessories.png)

click on edit accessories and then u can rename them
