### ISSUE TITLE
Shelly Plugin. Can‘t delete or update

### ISSUE THREAD

**Issue by xalex88** [hoobs-org/HOOBS#664]
**Description**
I cant install a Update oder Remove the Shelly Plugin.

**Expected behavoir**

**Plugin name**
https://www.npmjs.com/package/homebridge-shelly

**Please report the issue to the plugin developer**
https://github.com/alexryd/homebridge-shelly/issues/119

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
MacOS

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```

    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": " ",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": " "
    },
    "bridge": {
        "name": "Bridge",
        "username": " ",
        "port": 51826,
        "pin": " "
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "plugins": [
        "homebridge-shelly"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Shelly",
            "name": "Shelly",
            "admin": {
                "enabled": true,
                "port": 8081
            },
            "plugin_map": {
                "plugin_name": "homebridge-shelly"
            }
        }
    ],
    "interfaces": [],
    "package_manager": "npm",
    "system": "hoobs"
}

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```

29.5.2020, 08:27:49 npm
29.5.2020, 08:27:49  ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/.bin/homebridge-shelly
29.5.2020, 08:27:49 npm
29.5.2020, 08:27:49 ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/.bin/homebridge-shelly: is outside /home/hoobs/.hoobs/node_modules/homebridge-shelly and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/.bin/homebridge-shelly
npm ERR!
29.5.2020, 08:27:49  Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
29.5.2020, 08:27:49 
29.5.2020, 08:27:49 npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-29T06_27_49_666Z-debug.log
29.5.2020, 08:28:39 npm
29.5.2020, 08:28:39  ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/.bin/homebridge-shelly
29.5.2020, 08:28:39 npm
29.5.2020, 08:28:39 
29.5.2020, 08:28:39 ERR!
29.5.2020, 08:28:39  Refusing to delete /home/hoobs/.hoobs/node_modules/.bin/homebridge-shelly: is outside /home/hoobs/.hoobs/node_modules/homebridge-shelly and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/.bin/homebridge-shelly
npm ERR! Remove the existing file and try again, or run npm
npm
29.5.2020, 08:28:39 ERR! with --force to overwrite files recklessly.
29.5.2020, 08:28:39 
29.5.2020, 08:28:39 npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-29T06_28_39_722Z-debug.log
29.5.2020, 08:28:39 Plugin "homebridge-shelly" updated.
29.5.2020, 08:28:39 Got SIGINT, shutting down Bridge...
29.5.2020, 08:28:43 Loaded plugin "homebridge-shelly".
29.5.2020, 08:28:44 [Shelly] 10 accessories loaded from cache
29.5.2020, 08:28:44 Bridge is running on port 51826.
29.5.2020, 08:28:44 [Shelly] Admin server is running on port 8081

```

**Additional context**

**Comment by askovi** [comment]
Try running this command in Terminal to remove the file it's complaining about:

`sudo rm -rf /home/hoobs/.hoobs/node_modules/.bin/homebridge-shelly`

**Comment by xalex88** [comment]
Hi,

Doesnt work :-(

**Comment by askovi** [comment]
What do you get when you type the command from above? Please post a screenshot

**Comment by xalex88** [comment]
Hallo,

Screenshot atached. Unfortunately nothing happens
![DA523941-01E2-4E41-962C-08736FB00C5F](https://user-images.githubusercontent.com/19264417/83438292-77535180-a441-11ea-8a3d-893a66569d01.png)

**Comment by askovi** [comment]
That’s normal, there’s no output for that command. Can you uninstall the plugin now from the UI?

**Comment by xalex88** [comment]
No can still not be uninstalled

**Comment by BobbySlope** [comment]
@xalex88 can u reach out to me on fb chat? I probably can solve that via remote support

**Comment by xalex88** [comment]
I made a new installation with 3.2.6 and now it works. 
I think in the future I will wait with updates :-D

**Comment by BobbySlope** [comment]
@xalex88 can u olease close the issue in the shelly repo?
