### ISSUE TITLE
Blinkcameras plugin

### ISSUE THREAD

**Issue by omolko** [hoobs-org/HOOBS#665]
Hi, I am new with hoobs but many things works great. I have for the moment installed hoobs on my Mac just to try.
I don't get any image from my blink cameras
Here is my config. I have probably missed something. HOOBs find the cameras . I can armed them but no more .

{
            "platform": "BlinkCameras",
            "plugin_map": {
                "plugin_name": "homebridge-blinkcameras"
            },
            "name": "Blink System",
            "username": "blabla@bebe.com",
            "password": "Jbibbbb",
            "deviceId": "EXT1",
            "deviceName": "*|DEVICENAME|*"
        },

my log 
Blink System] [Maison System] is armed
30/05/2020 à 15:19:29 [Blink System] [Entree nord Camera] is disarmed
30/05/2020 à 15:19:29 [Blink System] [ouest Camera] is disarmed

Thanks for your help

**Comment by askovi** [comment]
Cameras need to be added manually in Homekit. Tap on Add Accessory -> Don’t have a code or cannot scan

Select the camera there then scan the QR code on the HOOBS dashboard to pair it.

**Comment by omolko** [comment]
Hi thanks for your help
 I don't have a QR code for the blink camera. The only QR code I have is the Hoobs one.

<img width="1311" alt="Capture d’écran 2020-06-02 à 13 37 57" src="https://user-images.githubusercontent.com/20817709/83515856-51c45780-a4d6-11ea-8bc9-21a2500e6028.png">

**Comment by askovi** [comment]
yes that's the code you need to scan after selecting your camera from the Add Accessory -> Don’t have a code or cannot scan screen in Homekit

**Comment by omolko** [comment]
I try again and again but when I ask add accessory as you explained above , HomeKit doesn't find nothing.
I can see my blink camera in my log, and as plug in the home app.(so I can just armed and disarmed them)
In the config I have chosen the device ID and let the device name like it was in the blink email confirmation.

![IMG_0CB327758CBB-1](https://user-images.githubusercontent.com/20817709/83689127-cdb1c300-a5ee-11ea-842d-ae2a879c0584.jpeg)

**Comment by askovi** [comment]
I just read the description of the plugin. That's all it actually does: let you arm and disarm the blink security cameras. It doesn't provide streaming. 
Check if your cameras support RTSP streaming. If they do, you can use the camera-ffmpeg plugin to stream live in Homekit.
