### ISSUE TITLE
EWeLink Max New Version 0.1.21

### ISSUE THREAD

**Issue by Stewart06** [hoobs-org/HOOBS#667]
Bonjour, je voudrais savoir si vous comptiez mettre à jour le plugin EWeLink Max qui est passé à la version 0.1.2.1 ?

Hello, I would like to know if you were planning to bring the plugin EWelink Max to the day passed by the version 0.1.2.1?

**Comment by BobbySlope** [comment]
@mkellsy 
https://plugins.hoobs.org/plugin/homebridge-ewelink-max
and
https://www.npmjs.com/package/homebridge-ewelink-max

is out of sync

**Comment by Stewart06** [comment]
Bonjour,

Vous pensez que la mise à jour 0.1.21 sera disponible bientôt ?

Cordialement.

Le 31 mai 2020 à 10:05, Bobby Slope <notifications@github.com> a écrit :

﻿

@mkellsy<https://github.com/mkellsy>
https://plugins.hoobs.org/plugin/homebridge-ewelink-max
and
https://www.npmjs.com/package/homebridge-ewelink-max

is out of sync

**Comment by BobbySlope** [comment]
solved is in sync now, developer probably dint made the version bump correctly
