### ISSUE TITLE
HOOBS Pi-Hole Installer: Missing rights for user www-data

### ISSUE THREAD

**Issue by herz08** [hoobs-org/HOOBS#668]
**Description**
After install Pi-Hole using the provided script
`wget -q -O - https://raw.githubusercontent.com/hoobs-org/hoobs-pihole/master/pihole-hoobs.sh | sudo bash -`
It is not possible to change any settings in the pi-hole admin interface 
> localhost:1882/admin/

After many unsuccessful attempts, I added the user www-data to the sudo group.
I'm not sure if this is the right approach, but that seems to solve the problems.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] HOOBS to Download
- [ ] Custom Install

**Comment by askovi** [comment]
Thank you. I will add it to the install script.
