### ISSUE TITLE
not succeed to enter to debug mode via docker

### ISSUE THREAD

**Issue by alon112** [hoobs-org/HOOBS#669]
**Description**
i don't succeed to enter debug mode via docker (using unraid system).
tried terminal from Hoobs, and terminal from Unraid. 

from unraid iam getting this:   https://imgur.com/FBaHiDv

**Version**
Version 3.2.6

**Did you upgrade**
no

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
 [ ] Custom Install (docker)

**If this is a custom install, what's your operating system?**
Unraid system

**List your plugins**
Harmony
Weater plus
webos tv
camera ffmpeg
dummy
nature remo sensor
mi philps light fork
ring
sensibo sky 7modes
smarthtings v2
tplink smarthome

**Post your config**
{
    "server": {
        "port": 8080,
        "origin": "*",
        "docker": true,
        "home_setup_id": "X-HM://0023ISYWYF9LF",
        "autostart": 0,
        "polling_seconds": 5
    },
    "client": {
        "theme": "hoobs-dark",
        "temp_units": "celsius",
        "postal_code": "94040",
        "country_code": "IL",
        "default_route": "status",
        "inactive_logoff": 60,
        "locale": "en"
    },
    "bridge": {
        "name": "HOOBS",
        "pin": "031-45-154",
        "username": "2E:99:69:55:A7:BF",
        "port": 51826
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "mini": false,
            "sensors": {
                "light": false,
                "temperature": true,
                "humidity": true
            },
            "deviceName": "AC",
            "accessory": "remo-sensor",
            "schedule": "*/5 * * * *",
            "name": "Bed Room",
            "plugin_map": {
                "plugin_name": "homebridge-nature-remo-sensor",
                "index": 0
            },
            "accessToken": "xxxxxx"
        }
    ],
    "platforms": [
        {
            "timeLapse": 5,
            "hideHumidity": false,
            "plugin_map": {
                "plugin_name": "homebridge-sensibo-sky-7modes"
            },
            "apiKey": "xxx",
            "name": "alon",
            "hideFan": false,
            "ai": true,
            "platform": "SensiboSky",
            "fixedState": "auto"
        },
        {
            "refreshToken": "xxxxx",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "platform": "Ring"
        },
        {
            "cameras": [
                {
                    "videoConfig": {
                        "source": "-rtsp_transport http -re -i rtsp://admin:pass@ip:port/617163cf9e616c3a",
                        "maxFPS": 30,
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "audio": true,
                        "mapvideo": "0:1",
                        "maxHeight": 720,
                        "mapaudio": "0:0",
                        "dbug": true,
                        "vcodec": "h264_omx"
                    },
                    "name": "Camera"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "platform": "Camera-ffmpeg",
            "name": "camera"
        },
        {
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            },
            "platform": "TplinkSmarthome"
        },
        {
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "platform": "HarmonyHubWebSocket"
        },
        {
            "devices": [
                {
                    "volumeLimit": 100,
                    "name": "My LG TV",
                    "pollingInterval": 5,
                    "ip": "x.x.x.x",
                    "inputs": [
                        {
                            "appId": "YouTubeLG",
                            "name": "youtube.leanback.v4"
                        }
                    ],
                    "channelControl": true,
                    "showInputButtons": true,
                    "infoButtonAction": "INFO",
                    "prefsDir": "~/.webosTv",
                    "legacyTvService": true,
                    "mac": "38:8C:50:AF:88:EF",
                    "volumeControl": false,
                    "mediaControl": false
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv"
            },
            "platform": "webostv"
        },
        {
            "plugin_map": {
                "plugin_name": "homebridge-weather-plus"
            },
            "units": "si",
            "platform": "WeatherPlus",
            "stations": [
                {
                    "forecast": [
                        0
                    ],
                    "key": "b907906d462f3fb3a10f0f5d17b092a3",
                    "locationGeo": [
                        32.0838614,
                        34.8220969
                    ],
                    "conditionCategory": "simple",
                    "extraHumidity": false,
                    "now": true,
                    "compatibility": "home",
                    "service": "openweathermap",
                    "language": "en"
                }
            ],
            "interval": 5
        },
        {
            "plugin_map": {
                "plugin_name": "homebridge-smartthings-v2"
            },
            "platform": "SmartThings-v2"
        }
    ]
}

```
```

```
POST LOG HERE
```

**Additional context**
also every few hours the bridge not working  "Bridge service not running"-
sometimes i see it that the accessories in the home app are "not responded" and sometimes i get this error but the accessories are working (i get the same message on the homemanager app.

thank you

**Comment by BobbySlope** [comment]
unfortunately we can't reproduce that, because we are not running an unraid system
