### ISSUE TITLE
Cannot connect to HomeKit after reset 

### ISSUE THREAD

**Issue by JBMJBM** [hoobs-org/HOOBS#673]
Cannot connect to HomeKit after reset.  Continue to get can’t add.
![82CEF43B-0B98-41B9-9070-14F83413B95E](https://user-images.githubusercontent.com/52239/83472156-36146f00-a44c-11ea-8742-735fd67c5a98.png)
![456B8D6B-16D1-496E-886F-257AFB12180C](https://user-images.githubusercontent.com/52239/83472159-36ad0580-a44c-11ea-9686-068c0568bad9.png)

**Comment by askovi** [comment]
Reboot your router, and the HOOBS Box. Make sure both your iphone and the HOOBS box are on the same subnet.

**Comment by JBMJBM** [comment]
That did not work.

**Comment by BobbySlope** [comment]
Please reset Apple Home connection and try again
try these steps: https://support.hoobs.org/docs/5e960c1b0ab68b0344e872e0

if that doesn't work try to reflash the sd card with the latest HOOBS version:
https://github.com/hoobs-org/HOOBS/releases

and create a system backup to restore after:
https://support.hoobs.org/docs/5e875e550ab68b0344e872d7

**Comment by JBMJBM** [comment]
Do even show a “HELP” menu in the drop down?

Also it says my Node.js Version is out of date but all my plugins are up to date.



Brice Milliorn, CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | jbmjbm22@me.com

**Comment by JBMJBM** [comment]
Up To Date
Version 1.1.0 




Plugins


Timezone	GMT-0500
OS	Raspbian GNU/Linux Buster (10) 
Hostname	hoobs
IPv4 (eth0) 	192.168.1.50
IPv6 (eth0) 	fe80::e3ef:33cb:c498:d54
Node.js Version	v10.16.0 
Npm Version	v6.9.0 
User	hoobs
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json




Brice Milliorn, CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | jbmjbm22@me.com

**Comment by askovi** [comment]
Looks like you're still on the old version. Install the homebridge-to-hoobs plugin to upgrade to HOOBS 3 then you can update from the dashboard.

**Comment by JBMJBM** [comment]
Ok installed the homebridege-to-hoobs but now still shows homebridge version 1.1.0?




Brice Milliorn | CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | 
jbmjbm22@me.com

**Comment by askovi** [comment]
Can you post a screenshot with that you see?

**Comment by JBMJBM** [comment]
Brice Milliorn, CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | jbmjbm22@me.com

**Comment by askovi** [comment]
I don't see anything posted above. Try pasting an image directly in the box it will upload it automatically to github

**Comment by JBMJBM** [comment]
<img width="1614" alt="Screen Shot 2020-06-12 at 9 16 46 AM" src="https://user-images.githubusercontent.com/52239/84515678-66e97500-ac92-11ea-90ac-7d31f024682f.png">
<img width="1614" alt="Screen Shot 2020-06-12 at 9 16 52 AM" src="https://user-images.githubusercontent.com/52239/84515688-69e46580-ac92-11ea-9e96-546ba54924c9.png">
<img width="285" alt="Screen Shot 2020-06-12 at 9 17 01 AM" src="https://user-images.githubusercontent.com/52239/84515692-6b159280-ac92-11ea-92d0-9f3cb4953cd5.png">

**Comment by askovi** [comment]
so that's the old version prior to HOOBS 3. When you install homebridge-to-hoobs plugin it will take like 10 minutes to complete. Then reboot the HOOBS box and you will be prompted to create a new account when you go to hoobs.local and you'll have access to the new dashboard.

**Comment by JBMJBM** [comment]
So again per images you can see I have that plugin installed????



Brice Milliorn, CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | jbmjbm22@me.com

**Comment by askovi** [comment]
have you tried rebooting?

**Comment by JBMJBM** [comment]
Yes



Brice Milliorn, CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | jbmjbm22@me.com

**Comment by askovi** [comment]
Did you install the plugin from the UI? 
Try uninstalling it then reinstall it but do not close the install window until it says to point your browser to hoobs.local (takes around 10 minutes)

**Comment by JBMJBM** [comment]
I did.  Now I am getting this screen and it never goes off of it...
<img width="1404" alt="Screen Shot 2020-06-13 at 4 07 49 PM" src="https://user-images.githubusercontent.com/52239/84579025-18ba9b80-ad90-11ea-8b03-f478efd8701e.png">

**Comment by askovi** [comment]
ok that's a step forward! that's the HOOBS 3 loading screen. Now we just need to figure out why it's not letting you in. Login via ssh with user: hoobs and password: hoobsadmin 
Then run this command to get the logs:
`sudo hoobs service log`

**Comment by JBMJBM** [comment]
I just login from the browser.  How else is there to login?




Brice Milliorn, CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | jbmjbm22@me.com

**Comment by askovi** [comment]
On MacOS use the Terminal app and type: `ssh hoobs@hoobs.local`

Type yes to accept the certificate key then press enter. When prompted for password, type **hoobsadmin**
You won't see the password being typed, that's normal. 

On Windows, use Putty with the same credentials as above.

After successfully logging in, type this to get the logs: `sudo hoobs service log`

**Comment by JBMJBM** [comment]
Ok here are the logs...
[Untitled.pdf](https://github.com/hoobs-org/HOOBS/files/4777006/Untitled.pdf)

**Comment by askovi** [comment]
Seems like something went wrong during the upgrade. Here's how to easily fix it:

While still logged in via ssh, run these 2 commands in order in the Terminal:

`sudo npm uninstall -g @hoobs/hoobs`

`sudo npm install -g --unsafe-perm @hoobs/hoobs`

**Comment by JBMJBM** [comment]
Ok that worked, it lets me log in now but when I go to add to HomeKit is says still cannot add device, does it if I scan the QR code or add the number mannually.



Brice Milliorn, CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | jbmjbm22@me.com

**Comment by askovi** [comment]
ok now you have to make sure both HOOBS and your iphone that you use to scan the code with are on the same network and most importantly same subnet. Check the 2 local ip addresses from your router's admin page and confirm that only the last part is different. 

If you're running a mesh network, make sure to connect HOOBS to the main node.

**Comment by JBMJBM** [comment]
It seems they are on different IP addresses but from the same router.  One is hardwired in and my phone is WiFi?




Brice Milliorn | CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | 
jbmjbm22@me.com

**Comment by askovi** [comment]
Please post both IPs. Also are you using an Eero router by any chance with Eero secure?

**Comment by JBMJBM** [comment]
IP of WiFi is 192.168.1.7

Where do I find hoobs WiFi ?



Brice Milliorn | CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | 
jbmjbm22@me.com

**Comment by askovi** [comment]
Look for HOOBS on your network and post the IP

**Comment by JBMJBM** [comment]
192.168.1.14




Brice Milliorn | CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | 
jbmjbm22@me.com

**Comment by askovi** [comment]
Ok that’s perfect. They’re on the same subnet. You should be able to add HOOBS by scanning the code.

If you’re still not able to, I need to know if your router is an Eero?

**Comment by JBMJBM** [comment]
Can’t add, same error.  This is getting old.

Using Orbi WiFi 6 router which is a mesh router 




Brice Milliorn | CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | 
jbmjbm22@me.com

**Comment by askovi** [comment]
For mesh routers, you have to plug HOOBS into the main node. Disconnect the power cable from HOOBS then plug the ethernet cable into your main node and the other end into the HOOBS Box then replug the power cable. Allow HOOBS to boot then try scanning the QR code again.

**Comment by JBMJBM** [comment]
Ok plugged in directly to the main node and nothing changed.  I am really getting frustrated here.  Why can’t you get this fixed?




Brice Milliorn | CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | 
jbmjbm22@me.com

**Comment by BobbySlope** [comment]
@JBMJBM i will send you an email to schedule a remote support session

**Comment by JBMJBM** [comment]
Still doesn’t work




Brice Milliorn | CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | 
jbmjbm22@me.com

**Comment by JBMJBM** [comment]
It is stale because you never responded with a fix.  Can I get a refund for my Hoobs since you can’t get it to work what so ever.



Brice Milliorn, CFP®, CLU®, ChFC®, AAMS® 
(979) 324-5500 | jbmjbm22@me.com

**Comment by BobbySlope** [comment]
i will write u a direct email
