### ISSUE TITLE
Add Samba-Common APK

### ISSUE THREAD

**Issue by Seexelas** [hoobs-org/HOOBS#676]
**Description**
I can't add anymore Samba-common via the terminal. When i do apk add samba, i'm stuck at this step : 

/hoobs/etc # apk add samba
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz

And nothing happens, it was working with precedent version. When i click on the link, i can download the file without any issue.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Fresh install, no plugins

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Thanks a lot,

**Comment by askovi** [comment]
What's your operating system?

**Comment by Seexelas** [comment]
Synology DSM 6.2.3 with docker 18.09.0-0513

**Comment by Seexelas** [comment]
Is there a way to install manually the apk I have in a folder from the terminal ?

**Comment by Seexelas** [comment]
it seems that my whole docker package was broken, i had to delete and reinstall everything.
