### ISSUE TITLE
Nest Cam 2.3.4 plugin when on wifi stops HOOBS services and disconnects all devices

### ISSUE THREAD

**Issue by wmlorenzo** [hoobs-org/HOOBS#677]
When I switched from Wired to Wifi connection on my HOOBS account, everything worked fine. Then once I added the Nest Cam 2.3.4 plugin (maybe it overloaded things since I have 5 cameras streaming? Though I’ve never had a problem in the nest app and only have a few other plugins on my HOOBS - ring doorbell, Broadlink for universal remote, Nest thermostat) I would intermittently get “No Response” on all my HOOBS connected devices since the the Service won’t stay up. It seems to go down intermittently. I can reboot HOOBS and it will come up but eventually goes down. I noticed the CPU usage and temperature go way up.

Seems strange since I have a great wifi network setup (google wifi 5 ghz and 2.4 ghz; HOOBS in same room as the primary google wifi base.

Once I switch back to wired, the services never go down and CPU % usage and temperature are fine. I’ll probably do this moving forward since it seems to improve performance all around on my HOOBS / homebridge experience but it’s worth noting that using wifi especially in combination with the Nestcam seems to be an issue.

**Comment by askovi** [comment]
Camera streaming is very intensive. A wired connection is always recommended. 
I also noticed you're using the wrong codec in the other issue. Change it to copy and it should improve things.

**Comment by wmlorenzo** [comment]
Thanks I did indeed change the codec to “copy” and that improved things a lot. Ill use a wired connection moving forward for the HOOBS bridge as you recommended. Thank you
