### ISSUE TITLE
No Bond device found

### ISSUE THREAD

**Issue by thadeusa** [hoobs-org/HOOBS#679]
**Description**
When using the Bond Plugin I am receiving an Error getaddrinfo ENOTFOUND when I know my Bond device is online, the IP address and Token information is entered correctly and I've followed all other steps including restarting.  As a result I can't add the accessories (fans/lights) since the system can't see the Bond bridge.  I've been trying to trouble shoot via Hoobs help on FB Messenger and they advised I report here.

**Version**
Please include the version of HOOBS you are using.  Using Hoobs Version 3.2.6  Node version 12.16.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install  Using a Raspberry PI 3B+ with Hoobs software

**If this is a custom install, what's your operating system?**
Using MacOS Catalina 10.15.5

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.  I'm using Bond
2.6.0 published 5/23/2020
Bond plug-in for HOOBS using the Bond V2 API

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYLE63",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "accessories",
        "inactive_logoff": 30,
        "theme": "hazed-infused",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "xxxxx",
        "latitude": "xx.xxxxxx",
        "longitude": "xx.xxxxxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "8F:2B:61:25:D3:0A"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Bond",
            "plugin_map": {
                "plugin_name": "homebridge-bond"
            },
            "debug": true,
            "include_dimmer": false,
            "fan_speed_values": true,
            "bonds": [
                {
                    "platform": "BondHome",
                    "bond_ip_address": "192.168.1.122",
                    "bond_token": "97cb0f2ecf4eb600"
                }
            ]
        }
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
6/4/2020, 7:39:41 AM - Got SIGINT, shutting down Bridge...
6/4/2020, 7:39:46 AM - Loaded plugin "homebridge-bond".
6/4/2020, 7:39:46 AM - [Bond] DEBUG: Request [GET http://undefined/v2/devices] - body: {}
6/4/2020, 7:39:46 AM - Bridge is running on port 51826.
6/4/2020, 7:39:47 AM - [Bond] DEBUG: Error [GET http://undefined/v2/devices] - {"name":"RequestError","message":"Error: getaddrinfo ENOTFOUND undefined","cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"undefined"},"error":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"undefined"},"options":{"method":"GET","uri":"http://undefined/v2/devices","headers":{},"body":{},"json":true,"simple":false,"timeout":10000,"resolveWithFullResponse":false,"transform2xxOnly":false}}
6/4/2020, 7:39:47 AM - [Bond] A request error occurred: Error: getaddrinfo ENOTFOUND undefined
6/4/2020, 7:39:47 AM - [Bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
6/4/2020, 7:39:47 AM - [Bond] 0 cached accessories were loaded
6/4/2020, 7:39:47 AM - [Bond] Getting devices...
6/4/2020, 7:39:47 AM - [Bond] 0 devices were found on this Bond.
6/4/2020, 7:39:47 AM - [Bond] Attempting to add 0 devices that were not previously added.
6/4/2020, 7:45:46 AM - Got SIGINT, shutting down Bridge...
6/4/2020, 7:45:51 AM - Loaded plugin "homebridge-bond".
6/4/2020, 7:45:51 AM - [Bond] DEBUG: Request [GET http://undefined/v2/devices] - body: {}
6/4/2020, 7:45:51 AM - Bridge is running on port 51826.
6/4/2020, 7:45:51 AM - [Bond] DEBUG: Error [GET http://undefined/v2/devices] - {"name":"RequestError","message":"Error: getaddrinfo ENOTFOUND undefined","cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"undefined"},"error":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"undefined"},"options":{"method":"GET","uri":"http://undefined/v2/devices","headers":{},"body":{},"json":true,"simple":false,"timeout":10000,"resolveWithFullResponse":false,"transform2xxOnly":false}}
6/4/2020, 7:45:51 AM - [Bond] A request error occurred: Error: getaddrinfo ENOTFOUND undefined
6/4/2020, 7:45:51 AM - [Bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
6/4/2020, 7:45:51 AM - [Bond] 0 cached accessories were loaded
6/4/2020, 7:45:51 AM - [Bond] Getting devices...
6/4/2020, 7:45:51 AM - [Bond] 0 devices were found on this Bond.
6/4/2020, 7:45:51 AM - [Bond] Attempting to add 0 devices that were not previously added.
6/4/2020, 7:48:14 AM - Got SIGINT, shutting down Bridge...
6/4/2020, 7:48:19 AM - Loaded plugin "homebridge-bond".
6/4/2020, 7:48:19 AM - [Bond] DEBUG: Request [GET http://undefined/v2/devices] - body: {}
6/4/2020, 7:48:19 AM - Bridge is running on port 51826.
6/4/2020, 7:48:19 AM - [Bond] DEBUG: Error [GET http://undefined/v2/devices] - {"name":"RequestError","message":"Error: getaddrinfo ENOTFOUND undefined","cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"undefined"},"error":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"undefined"},"options":{"method":"GET","uri":"http://undefined/v2/devices","headers":{},"body":{},"json":true,"simple":false,"timeout":10000,"resolveWithFullResponse":false,"transform2xxOnly":false}}
6/4/2020, 7:48:19 AM - [Bond] A request error occurred: Error: getaddrinfo ENOTFOUND undefined
6/4/2020, 7:48:19 AM - [Bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
6/4/2020, 7:48:19 AM - [Bond] 0 cached accessories were loaded
6/4/2020, 7:48:19 AM - [Bond] Getting devices...
6/4/2020, 7:48:19 AM - [Bond] 0 devices were found on this Bond.
6/4/2020, 7:48:19 AM - [Bond] Attempting to add 0 devices that were not previously added.
6/4/2020, 7:48:55 AM - Got SIGINT, shutting down Bridge...
6/4/2020, 7:49:00 AM - Loaded plugin "homebridge-bond".
6/4/2020, 7:49:00 AM - [Bond] DEBUG: Request [GET http://undefined/v2/devices] - body: {}
6/4/2020, 7:49:00 AM - Bridge is running on port 51826.
6/4/2020, 7:49:00 AM - [Bond] DEBUG: Error [GET http://undefined/v2/devices] - {"name":"RequestError","message":"Error: getaddrinfo ENOTFOUND undefined","cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"undefined"},"error":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"undefined"},"options":{"method":"GET","uri":"http://undefined/v2/devices","headers":{},"body":{},"json":true,"simple":false,"timeout":10000,"resolveWithFullResponse":false,"transform2xxOnly":false}}
6/4/2020, 7:49:00 AM - [Bond] A request error occurred: Error: getaddrinfo ENOTFOUND undefined
6/4/2020, 7:49:00 AM - [Bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
6/4/2020, 7:49:00 AM - [Bond] 0 cached accessories were loaded
6/4/2020, 7:49:00 AM - [Bond] Getting devices...
6/4/2020, 7:49:00 AM - [Bond] 0 devices were found on this Bond.
6/4/2020, 7:49:00 AM - [Bond] Attempting to add 0 devices that were not previously added.
```

**Additional context**

I'm not sure why it can't find my device but I'm assuming it is a small tweak I need to make?

**Comment by askovi** [comment]
Your configuration is incorrect. This is how it should look like:

`{
        "platform": "Bond",
        "bonds": [
            {
                "ip_address": "<BOND_IP_ADDRESS>",
                "token": "<BOND_TOKEN>"
            }
        ],
    }`

**Comment by thadeusa** [comment]
@askovi 
Thank you!  I'm not home atm but will try this when I stop by the house at lunch and let you know if it works.  I understand I should replace current configuration above with the code you gave me.  But I'm unsure of where exactly to place it in the configuration.

Should I delete the items in _Italics_ below? and add your code **in bold** below?  Or do I leave the items in _Italics_ alone?

"platforms": [
        {
            "platform": "Bond",
            _"plugin_map": {
                "plugin_name": "homebridge-bond"
            },
            "debug": true,
            "include_dimmer": false,
            "fan_speed_values": true,_
            "bonds": [
                {
                    
                    "ip_address": "192.168.1.122",
                    "token": "97cb0f2ecf4eb600"
                }
            ]
        }

**Comment by askovi** [comment]
You can edit it in the advanced config. Keep everything as you have it and only change the bonds array from this:

` “bonds”: [
                {
                    “platform”: “BondHome”,
                    “bond_ip_address”: “192.168.1.122”,
                    “bond_token”: “97cb0f2ecf4eb600”
                }
            ]`

To this:


`”bonds”: [ 
{ 
“ip_address”: “<BOND_IP_ADDRESS>”,
“token”: “<BOND_TOKEN>” 
} 
]`

Replace the angled brackets with caps text with the real values of the IP address and token.

**Comment by askovi** [comment]
Also for some reason my phone added the “” quotation marks. You always want to use these: "" straight ones, otherwise it will give a json error.

**Comment by thadeusa** [comment]
@askovi 
I will try that when I stop by the house later today/this evening and let you know how it goes.  I can't thank you enough and appreciate the support!

**Comment by thadeusa** [comment]
@askovi
It worked!!  Thank you so much and I can't tell you after 2 weeks of trying to make this work how happy I am.   I also wanted to figure out how to get 2 switches to show up in HomeKit (one for fan and one for light).  I've since figured how to make them show as separate tiles so I think I'm all set.  Really appreciate it.

**Comment by askovi** [comment]
Awesome!
