### ISSUE TITLE
homebridge-hue Service name is already in use on the network

### ISSUE THREAD

**Issue by renmlp** [hoobs-org/HOOBS#682]
**Description**

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian 10

**List your plugins**
- homebridge-nest
- homebridge-fritz
- homebridge-weather-plus
- homebridge-samsung-tizen
- homebridge-hue

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "users": {
                "bla": "bla"
            }
        }
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:310:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
```

**Comment by askovi** [comment]
Go to settings -> Apple Home and change service name from HOOBS to HOOBS2

**Comment by renmlp** [comment]
@askovi sorry this does not work

**Comment by askovi** [comment]
what do you see in the logs after changing the service name?

**Comment by renmlp** [comment]
@askovi same error

**Comment by renmlp** [comment]
I now know why the error occurred.  Apparently I am not allowed to leave the deConz Gateway on the default name.

**Comment by urba1n** [comment]
> I now know why the error occurred. Apparently I am not allowed to leave the deConz Gateway on the default name.

How did you solve you problem ? I have the same error, but I am not sure where to change deConz default name.

**Comment by marvelousmo** [comment]
I would be highly interested in a solution as well!

**Comment by dimer47** [comment]
Me too, I am interested to know the solution
