### ISSUE TITLE
homebridge-securitysystem has to be certified by HOOBS

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#683]
Hey you guys,
take a look at this awesome plugin from @MiguelRipoll23 and certified it for HOOBS.
It deserves it! Thank you!

**Comment by BobbySlope** [comment]
@Christian-CFP its already on the list to be certified

**Comment by BobbySlope** [comment]
Certified: https://plugins.hoobs.org/plugin/homebridge-securitysystem
