### ISSUE TITLE
Unable to update from 3.1.20 to 3.2.6

### ISSUE THREAD

**Issue by joewalch** [hoobs-org/HOOBS#687]
**Description**
Update from 3.1.20 to 3.2.6 - update procecss starts but no update occurrs

**Version**
Please include the version of HOOBS you are using.

3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Raspbian
**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Evohome
0.6.3 published 5/3/2020
Honeywell Evohome support for Homebridge:

Samsung Tizen
4.3.2 published 4/28/2020
Samsung TV plugin for Homebridge

SmartThings V2
2.3.4 published 5/15/2020
SmartThings plugin for HomeBridge

Sonoff
1.0.6 published 5/17/2020
Control Sonoff devices with Siri and HomeKit

Tplink Smarthome
5.1.0 published 5/13/2020
TPLink Smarthome plugin for Homebridge

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

{
    "server": {
        "port": 18000,
        "origin": "*",
        "autostart": 3,
        "home_setup_id": "X-HM://0023ISYWYB839",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "accessories",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": "XXXXXX"
latitude": "xxxxxxxxxxxxx",
        "longitude": "xxxxxxxxxxxx"        
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "XXX-XX-XX",
        "username": "XXXXXXXXXXXXX"
    },
    "description": "Homekit Bridge",
    "ports": {},
    "plugins": [
        "homebridge-evohome",
        "homebridge-sonoff",
        "homebridge-samsung-tizen",
        "homebridge-tplink-smarthome",
        "homebridge-smartthings-v2"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Evohome",
            "name": "Evohome",
            "username": "XXXXXXXXXXXXXXXXXXXXXXX",
            "password": "XXXXXXXXXXXXX",
            "temperatureUnit": "Celsius",
            "locationIndex": "0",
            "plugin_map": {
                "plugin_name": "homebridge-evohome"
            }
        },
        {
            "platform": "Sonoff",
            "name": "Sonoff",
            "devices": [
                {
                    "name": "Lamp",
                    "hostname": "XXXXXXXXXXX"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-sonoff"
            }
        },
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "TV",
                    "ip": "XXXXXXXXXXXXXX",
                    "mac": "XXXXXXXXXXXXXXXX"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "name": "SamsungTizen",
            "app_list": true
        },
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        },
        {
            "platform": "SmartThings-v2",
            "name": "SmartThings-v2",
            "app_url": "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/",
            "app_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "access_token": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
            "temperature_unit": "C",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": false,
                "hideNamePrefix": false,
                "file": {
                    "enabled": true,
                    "level": "Good"
                }
            },
            "direct_port": 8000
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```
[too much personal information in the log] no errors regarding update or homebridge shown.

**Additional context**

**Comment by askovi** [comment]
Just run this via ssh:

`sudo npm install -g --unsafe-perm @hoobs/hoobs`

**Comment by awoolford** [comment]
I have exactly this same problem following a migration from a Homebridge to Hoobs on a RPi 3 running Raspbian Buster.  I also ran  `npm install -g --unsafe-perm @hoobs/hoobs` as suggested by askovi above.  This ran without errors, but the version number of Hoobs remains 3.1.20 with 3.2.6 Update Available.  Just like the original OP, there are no errors in the log file.  Any help appreciated.
