### ISSUE TITLE
Error loading plugin "homebridge-weather-plus"

### ISSUE THREAD

**Issue by freddair** [hoobs-org/HOOBS#689]
**Description**
Hoobs Plugin Weather Plus installs but does not work
**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
homebridge-weather-plus
**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS SD Card Image on Raspberry Pi 3B+

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-dark",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "13189"
    },
    "bridge": {
        "name": "HOOBS",
        "port":,
        "pin": "",
        "username": ""
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "homebridge-xiaomi-roborock-vacuum",
                "index": 0
            },
            "name": "",
            "waterBox": false,
            "pause": true,
            "dock": true,
            "delay": false,
            "cleanword": "clean",
            "autoroom": true,
            "ip": "",
            "token": ""
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 5000,
            "name": "Timer 5s"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "name": "Dummy"
        }
    ],
    "platforms": [
        {
            "platform": "netatmo",
            "name": "netatmo platform",
            "auth": {
                "client_id": "",
                "client_secret": "",
                "username": "",
                "password": ""
            }
        },
        {
            "platform": "webostv",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv"
            },
            "devices": [
                {
                    "name": "Fernseher",
                    "ip": "",
                    "mac": "",
                    "keyFile": "~/.webosTv/lgtvKey",
                    "prefsDir": "~/.webosTv",
                    "pollingInterval": 10,
                    "legacyTvService": false,
                    "showInputButtons": false,
                    "volumeControl": "none",
                    "volumeLimit": 20,
                    "channelControl": false,
                    "mediaControl": false,
                    "inputs": [
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "Live TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "Fidelio"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "HDMI 3"
                        },
                        {
                            "appId": "com.webos.app.hdmi4",
                            "name": "Computer"
                        },
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "YouTube"
                        }
                    ],
                    "remoteSequenceButtons": [
                        {
                            "interval": 500
                        }
                    ],
                    "infoButtonAction": "INFO",
                    "accessory": "webostv"
                }
            ]
        },
        {
            "platform": "FritzPlatform",
            "devices": {
                "FRITZ!Box 6490 Cable": {
                    "active": true,
                    "host": "",
                    "port": 49000,
                    "username": "",
                    "password": "",
                    "type": "cable",
                    "master": true,
                    "mesh": true,
                    "readOnly": false,
                    "options": {
                        "reconnect": true,
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "aw": [
                            true,
                            false
                        ],
                        "deflection": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ],
                        "lock": [
                            true,
                            false
                        ]
                    }
                },
                "FRITZ!Box 7590": {
                    "active": true,
                    "host": "",
                    "port": 49000,
                    "username": "",
                    "password": "",
                    "type": "dsl",
                    "readOnly": false,
                    "options": {
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ],
                        "reconnect": false
                    }
                }
            },
            "callmonitor": {
                "active": true,
                "ip": "",
                "port": 1012,
                "country": "DE",
                "incomingTo": [
                    "",
                    ""
                ],
                "outgoingFrom": [
                    "",
                    ""
                ]
            },
            "presence": {
                "user": [
                    {
                        "active": true,
                        "name": "xxx",
                        "address": "xxx"
                    }
                ],
                "anyone": false,
                "offDelay": 15,
                "onDelay": 15,
                "ping": false
            },
            "wol": [
                {
                    "active": false,
                    "name": "Rechner",
                    "address": "xxx"
                }
            ],
            "alarm": {
                "active": false,
                "telNr": "012514587",
                "duration": 30
            },
            "wakeup": {
                "active": false,
                "internNr": "**620",
                "duration": 30
            },
            "ringlock": {
                "active": false,
                "DECTphones": 1,
                "start": "11:00",
                "end": "22:00"
            },
            "broadband": {
                "active": false,
                "measureTime": 5
            },
            "extReboot": {
                "active": true,
                "cmdOn": "sh /PATH/TO/SCRIPT/on.sh",
                "cmdOff": "sh /PATH/TO/SCRIPT/off.sh"
            },
            "phoneBook": {
                "active": false,
                "blacklists": [
                    "Blacklist"
                ]
            },
            "polling": 10,
            "timeout": 10,
            "clearCache": false,
            "debug": false,
            "disableAutoSearch": true,
            "disableAutoConfig": false,
            "plugin_map": {
                "plugin_name": "homebridge-fritz-platform"
            },
            "smarthome": {
                "Test Contact Sensor": {
                    "active": false,
                    "ain": "01234567890",
                    "devType": "contact"
                },
                "Test Thermostat Device": {
                    "active": false,
                    "ain": "01234567890",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false,
                    "devType": "thermostat"
                },
                "Test Outlet Device": {
                    "active": false,
                    "ain": "01234567890",
                    "tempSensor": false,
                    "devType": "switch"
                }
            },
            "telegram": {
                "active": false,
                "presence": {},
                "callmonitor": {},
                "alarm": {},
                "extReboot": {}
            }
        },
        {
            "platform": "RPi",
            "plugin_map": {
                "plugin_name": "homebridge-rpi"
            },
            "name": "RPi",
            "hosts": [
                {
                    "host": "localhost"
                }
            ]
        },
        {
            "platform": "WeatherPlus",
            "plugin_map": {
                "plugin_name": "homebridge-weather-plus"
            },
            "units": "ca",
            "interval": 5,
            "stations": [
                {
                    "displayName": "xxx",
                    "service": "openweathermap",
                    "key": "xxx",
                    "forecast": [
                        0
                    ],
                    "locationGeo": [
                        xxx,
                        xxx
                    ]
                }
            ]
        }
    ]
}```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
11.6.2020, 18:01:34 HOOBS listening on port 80.
11.6.2020, 18:01:38 Loaded plugin "homebridge-dummy".
11.6.2020, 18:01:38 Loaded plugin "homebridge-fritz-platform".
11.6.2020, 18:01:41 Loaded plugin "homebridge-rpi".
11.6.2020, 18:01:41 Error loading plugin "homebridge-weather-plus".
11.6.2020, 18:01:41 Error: Cannot find module 'request'
Require stack:
- /home/hoobs/.hoobs/node_modules/dark-sky/dark-sky-api.js
- /home/hoobs/.hoobs/node_modules/homebridge-weather-plus/apis/darksky.js
- /home/hoobs/.hoobs/node_modules/homebridge-weather-plus/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/plugin.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/dark-sky/dark-sky-api.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
11.6.2020, 18:01:41 Loaded plugin "homebridge-webos-tv".
11.6.2020, 18:01:42 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
11.6.2020, 18:01:43 The requested platform "netatmo" was not registered by any plugin.
11.6.2020, 18:01:43 Your config.json is requesting the platform "netatmo" which has not been published by any installed plugins.
11.6.2020, 18:01:43 [FritzPlatform] [INFO] **************************************************************
11.6.2020, 18:01:43 [FritzPlatform] [INFO] FritzPlatform v4.1.0 by SeydX
11.6.2020, 18:01:43 [FritzPlatform] [INFO] GitHub: https://github.com/SeydX/homebridge-fritz-platform
11.6.2020, 18:01:43 [FritzPlatform] [INFO] Email: seyd55@outlook.de
11.6.2020, 18:01:43 [FritzPlatform] [INFO] **************************************************************
11.6.2020, 18:01:43 [FritzPlatform] [INFO] start success...
11.6.2020, 18:01:43 [RPi] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
11.6.2020, 18:01:43 [RPi] warning: 12.16.2: not using recommended node v12.17.0 LTS
11.6.2020, 18:01:43 [RPi] warning: config.json: plugin_map: invalid key
11.6.2020, 18:01:43 The requested platform "WeatherPlus" was not registered by any plugin.
11.6.2020, 18:01:43 Your config.json is requesting the platform "WeatherPlus" which has not been published by any installed plugins.
11.6.2020, 18:01:43 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
11.6.2020, 18:01:43 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
11.6.2020, 18:01:43 [Dummy] Setting switch to false
11.6.2020, 18:01:43 [webostv] Init - initializing devices
11.6.2020, 18:01:43 [webostv] Init - initializing device with name: Fernseher
11.6.2020, 18:01:43 [FritzPlatform] [INFO] Auto Device Search is disabled, looking for devices in config.json..
11.6.2020, 18:01:43 [FritzPlatform] [INFO] Initializing config...
11.6.2020, 18:01:43 [RPi] restored 1 accessories from cache
11.6.2020, 18:01:43 Bridge is running on port 51826.
11.6.2020, 18:01:43 Fernseher is running on port 45133.
11.6.2020, 18:01:43 [FritzPlatform] [INFO] Callmonitor connection established with 10.0.0.1:1012
11.6.2020, 18:01:43 [FritzPlatform] [INFO] Callmonitor: Connection were ended!
11.6.2020, 18:01:43 [FritzPlatform] [INFO] Callmonitor: Connection were closed!
11.6.2020, 18:01:43 [FritzPlatform] [INFO] Found 6 active devices...
11.6.2020, 18:01:44 [RPi] warning: npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:108:11)
    at ClientRequest.once (events.js:430:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.request (/home/hoobs/.hoobs/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at HttpClient.request (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HttpClient.get (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:136:17)
    at RpiPlatform._checkLatest (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/Platform.js:384:42)
    at RpiPlatform._heartbeat (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/Platform.js:294:12)
    at RpiPlatform._beat (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/Platform.js:288:42)
11.6.2020, 18:01:44 [RPi] localhost: Raspberry Pi 3B+ v1.3 (BCM2837, 1GB) - 000000003683C2C3
11.6.2020, 18:01:45 [RPi] warning: heartbeat 1, drift 257
11.6.2020, 18:01:47 [RPi] warning: heartbeat 2, drift 344```

**Additional context**

**Comment by freddair** [comment]
now Hoobs "forgot" all its config incl. all plugins and settings... restoring to latest backup prior last plugin install.

**Comment by freddair** [comment]
No support here?

**Comment by BobbySlope** [comment]
How did u installed the plugin via ui or terminal? It seam like it didn’t load all the parts needed on installation

**Comment by freddair** [comment]
At first I installed it via UI. Didn’t work so I tried again via terminal, which didn’t work either. I will try again and send the outcome.

**Comment by BobbySlope** [comment]
use this command in terminal to update your node version to the latest LTS

```wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node 12.16.2``` 

please give us a feedback if this solved the issues

**Comment by freddair** [comment]
done. installed plugin again via UI. Log extract after reboot:

22.6.2020, 23:52:14 - HOOBS listening on port 80.
22.6.2020, 23:52:18 - Loaded plugin "homebridge-dummy".
22.6.2020, 23:52:18 - Loaded plugin "homebridge-fritz-platform".
22.6.2020, 23:52:21 - Loaded plugin "homebridge-rpi".
22.6.2020, 23:52:21 - Error loading plugin "homebridge-weather-plus".
22.6.2020, 23:52:21 - Error: Cannot find module 'request'
Require stack:
- /home/hoobs/.hoobs/node_modules/dark-sky/dark-sky-api.js
- /home/hoobs/.hoobs/node_modules/homebridge-weather-plus/apis/darksky.js
- /home/hoobs/.hoobs/node_modules/homebridge-weather-plus/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/plugin.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/dark-sky/dark-sky-api.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
22.6.2020, 23:52:21 - Loaded plugin "homebridge-webos-tv".
22.6.2020, 23:52:25 - Loaded plugin "homebridge-xiaomi-fan".
22.6.2020, 23:52:25 - Loaded plugin "homebridge-xiaomi-roborock-vacuum".
22.6.2020, 23:52:25 - [FritzPlatform] [INFO] **************************************************************
22.6.2020, 23:52:25 - [FritzPlatform] [INFO] FritzPlatform v4.1.0 by SeydX
22.6.2020, 23:52:25 - [FritzPlatform] [INFO] GitHub: https://github.com/SeydX/homebridge-fritz-platform
22.6.2020, 23:52:25 - [FritzPlatform] [INFO] Email: seyd55@outlook.de
22.6.2020, 23:52:25 - [FritzPlatform] [INFO] **************************************************************
22.6.2020, 23:52:25 - [FritzPlatform] [INFO] start success...
22.6.2020, 23:52:25 - [RPi] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
22.6.2020, 23:52:25 - [RPi] warning: 12.16.2: not using recommended node v12.17.0 LTS
22.6.2020, 23:52:25 - [RPi] warning: config.json: plugin_map: invalid key
22.6.2020, 23:52:25 - The requested platform "WeatherPlus" was not registered by any plugin.
22.6.2020, 23:52:25 - Your config.json is requesting the platform "WeatherPlus" which has not been published by any installed plugins.
22.6.2020, 23:52:25 - HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
22.6.2020, 23:52:25 - HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.

**Comment by freddair** [comment]
@BobbySlope I still have this issue but only on my Pi 3B+. It is running well on two other Pi zeros with HOOBS. What can I do to make it run on the 3B+ HOOBS also?
