### ISSUE TITLE
Got SIGTERM, shutting down Bridge

### ISSUE THREAD

**Issue by wallacepost** [hoobs-org/HOOBS#691]
Hi Log attached,Got SIGTERM, shutting down Bridge.
Can you please assist, thanks
Hoobs Hub

Bridge Name	HOOBS
HOOBS Version	3.2.6
Node Version	12.16.2

[logs.txt](https://github.com/hoobs-org/HOOBS/files/4781318/logs.txt)

**Comment by BobbySlope** [comment]
Try powercycle the device. Use top right menu shutdown, wait a minute unplug power an replug it.
