### ISSUE TITLE
Updates to Plugins not working

### ISSUE THREAD

**Issue by SRamsdell1** [hoobs-org/HOOBS#693]
**Description**
Both Gsh (listed as HOOBs Certified) and Hubitat Hubconnect plugins show Update Available in the UI.  Updating them thru the UI returns a "successfully updated" message.  However the installed version numbers, and the Update Available do not change in the UI.  

Logs indicated the old version of Hubitat Hubconnect [0.3.9] is still loading and specificities an update [0.3.11] is available.   

An error attempting to remove a file is also listed in the logs after each update attempt: 

6/18/2020, 2:32:20 PM npm ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/winston-logrotate/node_modules/.bin/rimraf
npm ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/winston-logrotate/node_modules/.bin/rimraf: is outside /home/hoobs/.hoobs/node_modules/winston-logrotate/node_modules/rimraf and not a link
npm ERR!
6/18/2020, 2:32:20 PM  File exists: /home/hoobs/.hoobs/node_modules/winston-logrotate/node_modules/.bin/rimraf
6/18/2020, 2:32:20 PM npm
6/18/2020, 2:32:20 PM 
6/18/2020, 2:32:20 PM ERR!
6/18/2020, 2:32:20 PM  Remove the existing file and try again, or run npm
6/18/2020, 2:32:20 PM npm ERR! with --force to overwrite files recklessly.
6/18/2020, 2:32:20 PM 
6/18/2020, 2:32:20 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-06-18T18_32_20_794Z-debug.log
6/18/2020, 2:32:20 PM Plugin "homebridge-hubitat-hubconnect" updated.

6/18/2020, 2:38:33 PM [6/18/2020, 12:38:33 PM] [Hubitat HubConnect hhh:0.3.9] HE got pong
6/18/2020, 2:38:54 PM npm
6/18/2020, 2:38:54 PM  ERR! code EEXIST
6/18/2020, 2:38:54 PM npm ERR! path
6/18/2020, 2:38:54 PM  /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/.bin/multicast-dns
6/18/2020, 2:38:54 PM npm
6/18/2020, 2:38:54 PM  ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/.bin/multicast-dns: is outside /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/multicast-dns and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/.bin/multicast-dns
6/18/2020, 2:38:54 PM npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
6/18/2020, 2:38:55 PM 
6/18/2020, 2:38:55 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-06-18T18_38_54_335Z-debug.log
**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Gsh & Hubitat Hubconnect

**Please report the issue to the plugin developer**

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**

PI3B+ from Hoobs SD Image download 

**Post your config**
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "[removed]",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "[removed]",
        "latitude": "[removed]",
        "longitude": "[removed]"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "[removed]",
        "username": "[removed]"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Relay-custom",
            "name": "Close Curtain",
            "pin": 37,
            "invert": false,
            "default_state": false,
            "duration_ms": 10,
            "plugin_map": {
                "plugin_name": "homebridge-relays-lapo",
                "index": 0
            }
        },
        {
            "accessory": "Relay-custom",
            "name": "Open Curtain",
            "pin": 31,
            "invert": false,
            "default_state": false,
            "duration_ms": 10,
            "plugin_map": {
                "plugin_name": "homebridge-relays-lapo",
                "index": 0
            }
        },
        {
            "accessory": "Relay-custom",
            "name": "Screen Up",
            "pin": 15,
            "invert": false,
            "default_state": false,
            "duration_ms": 10,
            "plugin_map": {
                "plugin_name": "homebridge-relays-lapo",
                "index": 0
            }
        },
        {
            "accessory": "Relay-custom",
            "name": "Screen Down",
            "pin": 7,
            "invert": false,
            "default_state": false,
            "duration_ms": 10,
            "plugin_map": {
                "plugin_name": "homebridge-relays-lapo",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "yamaha-avr",
            "name": "Yamaha RX-V677",
            "ip": "192.168.55.175",
            "inputs": [
                {
                    "id": "HDMI3",
                    "name": "Apple TV"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-yamaha-avr"
            }
        },
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Family TV",
                    "ip": "192.168.55.240",
                    "mac": "[removed]",
                    "keys": {
                        "INFORMATION": "KEY_SOURCE"
                    },
                    "inputs": [
                        {
                            "name": "AppleTV",
                            "type": "app",
                            "value": "3201807016597"
                        },
                        {
                            "name": "Netflix",
                            "type": "app",
                            "value": "11101200001"
                        },
                        {
                            "name": "Amazon",
                            "type": "app",
                            "value": "3201512006785"
                        },
                        {
                            "name": "HBO Go",
                            "type": "app",
                            "value": "111199000417"
                        },
                        {
                            "name": "YouTube",
                            "type": "app",
                            "value": "111299001912"
                        },
                        {
                            "name": "CuriostyStream",
                            "type": "app",
                            "value": "3201705012304"
                        },
                        {
                            "name": "Hulu",
                            "type": "app",
                            "value": "3201601007625"
                        },
                        {
                            "name": "Disney+",
                            "type": "app",
                            "value": "3201901017640"
                        }
                    ]
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "name": "SamsungTizen",
            "app_list": true
        },
        {
            "platform": "Hubitat-HubConnect",
            "name": "Hubitat HubConnect",
            "hubconnect_key": "[removed]",
            "local_ip": "192.168.55.54",
            "local_port": 20009,
            "mode_switches": true,
            "hsm": false,
            "debug": false,
            "programmable_buttons": [
                "71"
            ],
            "logFile": {
                "enabled": true,
                "compress": true,
                "keep": 5,
                "size": "10m"
            },
            "plugin_map": {
                "plugin_name": "homebridge-hubitat-hubconnect"
            }
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest",
            "googleAuth": {
                "apiKey": "[removed]",
                "cookies": "[removed]"
            }
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "accessories": [
                {
                    "name": "MB Samsung",
                    "type": "switch",
                    "data": {
                        "on": "26005e018f9412381238123812131213121312131213113912371238121312131114111412131114123812131114111312131114111412381213123812381237123811391238120006089495113812381238111411141114111411141238113812381213121311141213111411141238121311141113121311141114123812131238123812371238123812381200060a929412381238123811141114121311141114143611381139111411141114111411141113113911141213111411141114111411381213113911391238113912371238110006099494123812381238121311141114111411131238123812381213111411141114111312131139131211141114121312131114113911131238123811391139123712381100060d90951237123812381114111411141114111412381138113a11131114121311141213111412381113121312131213111412131238121312381138123811391139123811000d0500000000000000000000)",
                        "off": "26005e018f9412381238123812131213121312131213113912371238121312131114111412131114123812131114111312131114111412381213123812381237123811391238120006089495113812381238111411141114111411141238113812381213121311141213111411141238121311141113121311141114123812131238123812371238123812381200060a929412381238123811141114121311141114143611381139111411141114111411141113113911141213111411141114111411381213113911391238113912371238110006099494123812381238121311141114111411131238123812381213111411141114111312131139131211141114121312131114113911131238123811391139123712381100060d90951237123812381114111411141114111412381138113a11131114121311141213111412381113121312131213111412131238121312381138123811391139123811000d0500000000000000000000)"
                    }
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-broadlink-rm"
            }
        },
        {
            "platform": "google-smarthome",
            "plugin_map": {
                "plugin_name": "homebridge-gsh"
            },
            "name": "Google Smart Home",
            "notice": "Keep your token a secret!",
            "token": [removed]
        }
    ]
}
**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
6/18/2020, 2:32:20 PM npm ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/winston-logrotate/node_modules/.bin/rimraf
npm ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/winston-logrotate/node_modules/.bin/rimraf: is outside /home/hoobs/.hoobs/node_modules/winston-logrotate/node_modules/rimraf and not a link
npm ERR!
6/18/2020, 2:32:20 PM  File exists: /home/hoobs/.hoobs/node_modules/winston-logrotate/node_modules/.bin/rimraf
6/18/2020, 2:32:20 PM npm
6/18/2020, 2:32:20 PM 
6/18/2020, 2:32:20 PM ERR!
6/18/2020, 2:32:20 PM  Remove the existing file and try again, or run npm
6/18/2020, 2:32:20 PM npm ERR! with --force to overwrite files recklessly.
6/18/2020, 2:32:20 PM 
6/18/2020, 2:32:20 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-06-18T18_32_20_794Z-debug.log
6/18/2020, 2:32:20 PM Plugin "homebridge-hubitat-hubconnect" updated.

6/18/2020, 2:38:33 PM [6/18/2020, 12:38:33 PM] [Hubitat HubConnect hhh:0.3.9] HE got pong
6/18/2020, 2:38:54 PM npm
6/18/2020, 2:38:54 PM  ERR! code EEXIST
6/18/2020, 2:38:54 PM npm ERR! path
6/18/2020, 2:38:54 PM  /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/.bin/multicast-dns
6/18/2020, 2:38:54 PM npm
6/18/2020, 2:38:54 PM  ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/.bin/multicast-dns: is outside /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/multicast-dns and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/.bin/multicast-dns
6/18/2020, 2:38:54 PM npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
6/18/2020, 2:38:55 PM 
6/18/2020, 2:38:55 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-06-18T18_38_54_335Z-debug.log
```

**Additional context**

**Comment by BobbySlope** [comment]
@SRamsdell1 there a synchronisation error for the homebridge-hubitat-hubconnect, we try to resolve that asap

**Comment by BobbySlope** [comment]
@SRamsdell1 for the gsh plugin I just updated that to the lastest version to be certified, please try to update again and tell us if it worked. Thx
