### ISSUE TITLE
Hoobs Noob

### ISSUE THREAD

**Issue by fleshparade** [hoobs-org/HOOBS#694]
Trying to get Hoobs back to factory settings. I have the Hoobs Box and it is connected to the network. It just won't take my saved username and password nor the default. I would like to start over as my initial attempt appears to have been done wrong.

**Comment by askovi** [comment]
Here are the instructions to reset your password:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this to reset the users file:  sudo rm -rf /home/hoobs/.hoobs/etc/access.json

Press enter. There will be no output.

3. Type this to reboot the HOOBS Box: sudo reboot

4. Allow 2-3 minutes for the HOOBS Box to reboot then go to http://hoobs.local and create a new account.

This won't affect your plugins and accessories, only your user.
