### ISSUE TITLE
Expose Dashboard Weather data to Homekit

### ISSUE THREAD

**Issue by jqnatividad** [hoobs-org/HOOBS#695]
**Is your feature request related to a problem? Please describe.**
Already, we configure weather in HOOBS, but its only exposed on the dashboard.  Why not to Homekit as well?

**Describe the solution you'd like**
Be able to access the HOOBS weather info from Homekit.

**Describe alternatives you've considered**
Alternatively, just bundle in a certified weather plugin that uses the same configuration info as the weather dashboard.

**Comment by BobbySlope** [comment]
this is planned
