### ISSUE TITLE
Local client error - HOOBS 3.2.6 after configuring a plugin

### ISSUE THREAD

**Issue by Jack-eit** [hoobs-org/HOOBS#697]
**Description**
Hi. I've been using HOOBS out of the box, since monday. I added one plugin with a success. Today, I decided to add one more - "xiaomi hygrothermograph" (https://github.com/hannseman/homebridge-mi-hygrothermograph) - and it was nearly a success, because I have configured 2 devices - but the in the Home-App they seemed to be not-responding all the time. 

So I thought maybe I have to write this line in terminal "_sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)_" as the instructions from plugin GitHub site suggests... I've done it and suddenly all the HOOBS device seems to be bricked/frozen. I see on the router app, it connects with my local network through Wi-Fi but client "hoobs.local" does not respond at all. Even with IP_ADRESS:8080. 

I even used Terminal in macOS Catalina to connect to hoobs and it connects with success... I tried to factory reset by deleting the config like typing in "_rm -fR ~/.hoobs"and "sudo rm -rf /home/hoobs/.hoobs/etc/access.json_" and then "_sudo hoobs service restart_" / "_sudo reboot_" and nothing really helped. Even I type in "_sudo hoobs cluster client_" but after typing the user ID, passwords and so on,  I'm receiving this:

 _"(node:6680) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at /usr/local/lib/node_modules/@hoobs/hoobs/scripts/client.js:88:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."_

**Now this device is only a white piece of plastic :/. What I'm supposed to do ? I heard someone had to open the box and reflash the SD-card?**

**Version**
The latest HOOBS 3.2.6. 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
I think it was 3.2.2 or something.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**Post your config**
Got it via SSH `cat ~/.hoobs/etc/config.json`

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "3A:B1:1C:3E:76:75"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": [],
    "package_manager": "npm"
}
```

**Seems like everything got reseted, because client settings changed to default - I set different parameters at the beginning of using hoobs.**

**Comment by askovi** [comment]
Please get the logs with:

`sudo hoobs service log`

**Comment by Jack-eit** [comment]
> Please get the logs with:
> 
> `sudo hoobs service log`

There it is... It repeats constantly and never stops... 

```
hoobs@hoobs:~ $ sudo hoobs service log
Started HOOBS.
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 1.
Stopped HOOBS.
hoobs.service: Found left-over process 587 (hoobs) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started HOOBS.
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
```

**Comment by askovi** [comment]
Disable nginx then reboot with the following commands 


`sudo systemctl disable nginx
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
sudo reboot`

**Comment by Jack-eit** [comment]
> Disable nginx then reboot with the following commands
> 
> sudo systemctl disable nginx
> 
> sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
> 
> sudo reboot

There is a problem, as can you see below (it says the nginx does not exist):

```
Last login: Thu Jun 25 02:30:37 2020 from fe80::14cd:f5e1:c888:c1bf%wlan0
hoobs@hoobs:~ $ sudo systemctl disable nginx
Failed to disable unit: Unit file nginx.service does not exist.
hoobs@hoobs:~ $ sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
hoobs@hoobs:~ $ sudo reboot
Connection to hoobs.local closed by remote host.
Connection to hoobs.local closed.
```

**Comment by Jack-eit** [comment]
And I have additional question, because in Home-App I can't delete old added devices, and I want to reconfigure from the beginning all my devices... how to absolutely delete the old accessories added to HOOBS? I see the config in HOOBs is default, but when I install my old plugin, the old accessory appears on my list and in the Home-App, but it seems to using the old "json" configuration file, but I can't edit it or delete it from the local website.

**Comment by askovi** [comment]
Start by removing the old HOOBS bridge from Homekit from the top left house icon then scroll down to hubs & bridges. 

Then click Reset Connection from the top right menu under Help in HOOBS. Then re-scan the new QR code on the dashboard.

**Comment by Jack-eit** [comment]
> Start by removing the old HOOBS bridge from Homekit from the top left house icon then scroll down to hubs & bridges.
> 
> Then click Reset Connection from the top right menu under Help in HOOBS. Then re-scan the new QR code on the dashboard.

Yeap I tried exactly this what you are writing about. It doesn't work for me. The accessory disappeared but when I install the same "plugin", though plugin starts with "zero configuration", the device configured in the past, suddenly appears in home-app (iPad).

**Comment by askovi** [comment]
If you Reset Connection from the Help menu it deletes all cached accessories. If it re-appears that means the plugin creates it. Check with the plugin developer on their GitHub for the appropriate behavior for the plugin.

**Comment by Coffeeei** [comment]
> Disable nginx then reboot with the following commands
> 
> sudo systemctl disable nginx
> 
> sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
> 
> sudo reboot

Hello, I have the same problem as the Author of this post. And even the solution that the commentator provided also helps me. But the problem is this.

I use Hoobs and install the Hygrothermograph as well. In the terminal, I enter all the required commands.
 After entering the command:

**sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)**

the plugin starts working and receives data from the sensor, but after I restart the device, the device does not want to boot. In general, everything is the same as that of the author.
 But the problem is that without this command (**sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)**), the plugin does not work, and Bluetooth scanning stops immediately after starting. It turns out that I need to enter this command, but after I reboot, the device will not turn on; or enter your commands, and the device reboots normally, but now the device does not take readings from the sensor.
 As I understand it, the solution that you provided helps to cancel this command and now the device reboots normally, but the plugin does not work :(
 please help to solve the problem, I'm new to this business and I'm very confused.

Thank you!!!
