### ISSUE TITLE
MQTTThing empty config page but working

### ISSUE THREAD

**Issue by delucs** [hoobs-org/HOOBS#698]
**Description**
when clicking on the configuration button of the MQTTThing plugin, the webpage freezes or shows an empty page.
but in CONFIGURATION->ADVANCED i can access the config, which is working fine and change it.
all plugins are latest. uninstalling and re-installing plugin doesn't help.
No change in config since upgrade from 3.1 docker to 3.2 docker

**Expected behavoir**
I should be able to access the config page of the plugin and add accessories or edit

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.6.2 Docker

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
3.1.x??

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Docker on QNAP

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Add any other context about the problem here.

**Comment by askovi** [comment]
I just tested this on both docker and rpi image and the config works fine on both for HOOBS version 3.2.6 and mqttthing version 1.1.16. I see the Add Accessory option:
![image](https://user-images.githubusercontent.com/3981552/85612578-04e02680-b627-11ea-985c-ca191cae3569.png)
![image](https://user-images.githubusercontent.com/3981552/85612617-0b6e9e00-b627-11ea-8dab-ae0088c54110.png)
