### ISSUE TITLE
Help and Service Tabs in ui

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#7]
- Advanced Homebridge controlls: Start, Stop and Restart, Help link, Resetting, Clearing Cache.
- System Health (CPU/RAM/MEMORY) with Detection of Hardware and OS that HOOBS is running on)

**Comment by mkellsy** [comment]
I have a help screen with a reset connection (delete persist) and a username regenerate. I need to add.

- clear cache
- view and remove single cached accessory
- add hardware information

**Comment by mkellsy** [comment]
This is done.
