### ISSUE TITLE
Upgrading my Raspberry Pi

### ISSUE THREAD

**Issue by koweye** [hoobs-org/HOOBS#700]
hello, i installed hoobs 3.2.6 for raspberry pi 1B, 2B and zero W. it was an old pi that i had. its a slow so i want to buy a newer pi 4. 

if i do that, can i download 3.2.6. for raspberry pi 4B, 3B, and 3B+ img and flash it to a sd card? boot it up and copy my config.json file from my original installl and restore it? will all my plugins and config be there? and also use the same QR code and home setup pin? or will i need to readd the hoobs hub back to homekit? main thing is all my plug ins and configs are there

thanks

**Comment by askovi** [comment]
Go to settings -> Backup and download a backup of the System and the Config. Then you can restore both on the new system and it will all be back to how it is now.

**Comment by koweye** [comment]
Thanks for the quick reply. I can backup and download the config but when I click on system nothing happens. Am I supposed to be able to download something?

________________________________

**Comment by BobbySlope** [comment]
depending on how many plugins you are running this can take up to 15-20 minuten, because it make a copy of everything and loadloads it after. just press the system backup button and let it run, once its finished it downloads the backupfile

**Comment by koweye** [comment]
Oh that long. Ok I will let it run. What is the download file called?

________________________________

**Comment by BobbySlope** [comment]
it has a date and timestamp and ending with .hbfx

**Comment by koweye** [comment]
Thank you so much! I just had to be more patient. So when i restore i restore the system first then config?

________________________________

**Comment by BobbySlope** [comment]
you can just resotre the system backup, it contains the current config

**Comment by koweye** [comment]
hello, sorry if i am opening this ticket up again but something just
occured to me.

i currently have hoobs for pi 3 image installed on a pi 3, i have a pi 4
coming in a couple days.  to get everything
over, if i back up the hoobs system config for pi 3, and then install hoobs
image for pi 4 on the new pi, and i do a restore of that
pi 3 system would it work? or am i basically overriding my pi 4 hoobs image
with the pi 3 image?

**Comment by askovi** [comment]
You can either just take the microSD card from your pi 3 and put it into the pi 4 or if you want to set it up again then you can backup the system and config on your pi 3 in HOOBS then after installing or flashing HOOBS on your pi 4, just restore both files from settings -> restore.

**Comment by koweye** [comment]
will the pi 3 image run on the new pi 4?

or i'll just flash the new pi 4 image to a new sd card and then do a
settings > restore the
system file (not config file) and that should work? i think i prefer this
option so i will try
this instead of running the pi 3 image.

**Comment by koweye** [comment]
Thank you for being so helpful!!! I was able to install my new pi and restored the system backup and everything was back!!!

________________________________
