### ISSUE TITLE
None of the z-wave plugins will install

### ISSUE THREAD

**Issue by therobfoster** [hoobs-org/HOOBS#702]
**Description**
None of the Z-wave plugins will install. This is a fresh install of Hoobs on a brand new raspberry pi 3.
This describes it: 
https://www.reddit.com/r/HOOBS/comments/ggky0q/homebridgeopenzwave_plugin_install_failed/

**Expected behavoir**
Installation complete

**Plugin name**
Platform Zwave
Openzwave
Zwave

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.2.6

**Did you upgrade**
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "throwback-blue",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "",
        "username": ""
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
6/27/2020, 9:15:02 AM 
> openzwave-shared@1.7.1 preinstall /home/hoobs/.hoobs/node_modules/openzwave-shared
> node lib/install-ozw.js
6/27/2020, 9:15:02 AM 
> openzwave-shared@1.7.1 install /home/hoobs/.hoobs/node_modules/openzwave-shared
> node-gyp rebuild
6/27/2020, 9:15:09 AM grep: /usr/*/include/value_classes: No such file or directory
gyp: Call to 'grep -r GetTypeNameFromEnum /usr/*/include/value_classes | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
6/27/2020, 9:15:09 AM gyp
6/27/2020, 9:15:09 AM 
6/27/2020, 9:15:09 AM ERR! configure error
6/27/2020, 9:15:09 AM gyp
6/27/2020, 9:15:09 AM  ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack
6/27/2020, 9:15:09 AM      at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
6/27/2020, 9:15:09 AM gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hoobs/.hoobs/node_modules/openzwave-shared
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
6/27/2020, 9:15:09 AM npm
6/27/2020, 9:15:09 AM  ERR! code ELIFECYCLE
npm ERR! errno
6/27/2020, 9:15:09 AM  1
6/27/2020, 9:15:09 AM npm
6/27/2020, 9:15:09 AM ERR! openzwave-shared@1.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.7.1 install script.
npm ERR!
6/27/2020, 9:15:09 AM  This is probably not a problem with npm. There is likely additional logging output above.
6/27/2020, 9:15:09 AM 
6/27/2020, 9:15:09 AM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-06-27T15_15_09_494Z-debug.log

**Additional context**
Add any other context about the problem here.

**Comment by LunchboxNYC** [comment]
Still having the same issue...  Lack of support for ZWave on hoobs is a big deal!
