### ISSUE TITLE
Error using Mi flower plugin

### ISSUE THREAD

**Issue by GitGabKat** [hoobs-org/HOOBS#704]
If I install and configure any mi flower sensor plugin, the sensor parameter appear in the home app, but not any measurement. The system bar shows any battery issue, but this is not the real issue.
It seems that there is any rights vulnerability due to not having roots rights with hoobs. This might be a general issue with Bluetooth devices and plugins used without root rights. 
Is there any fix or workaround to use the BLE without root rights, especially the mi flower sensor, which is quite popular?

**Comment by GitGabKat** [comment]
Below is a threat describing the same issue in other words, if it might help. 
https://forum.smartapfel.de/forum/thread/5327-config-json-f%C3%BCr-mi-flora-filtered/

**Comment by BobbySlope** [comment]
please provide logs and config

**Comment by GitGabKat** [comment]
`{
    "accessory": "mi-flower-care",
    "name": "Flower Sensor West",
    "deviceId": "80:EA:CA:89:50:F8",
    "interval": 100
} `

**Comment by GitGabKat** [comment]
`3 packages are looking for funding
  run `npm fund` for details
14.7.2020, 21:25:52 found 0 vulnerabilities
14.7.2020, 21:25:52 Plugin "homebridge-calendar" removed.
14.7.2020, 21:25:52 Got SIGINT, shutting down Bridge...
14.7.2020, 21:25:53 Loaded plugin "homebridge-mi-flora-filtered".
14.7.2020, 21:25:55 Loaded plugin "homebridge-shelly".
14.7.2020, 21:25:56 Loaded plugin "homebridge-weather-plus".
14.7.2020, 21:25:56 [Weather Plus] Adding station with weather service Dark Sky named 'Now'
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "Now"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "Today"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "In 1 Day"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "In 2 Days"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "In 3 Days"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "In 4 Days"...
14.7.2020, 21:25:56 [Flower Sensor West] aa46c6dc-2788-4e33-b2f4-03fba6969329
14.7.2020, 21:25:56 [Flower Sensor West] 6a4cbbb1-7967-4b62-aa1d-c8a13001efc6
14.7.2020, 21:25:56 [Flower Sensor West] c1c4efd2-9589-48bd-8bdc-d551a020c802
14.7.2020, 21:25:56 [Shelly] 9 accessories loaded from cache
14.7.2020, 21:25:56 Bridge is running on port 51826.
14.7.2020, 21:25:56 [Shelly] Admin server is running on port 8181 `

**Comment by GitGabKat** [comment]
3 packages are looking for funding
  run `npm fund` for details
14.7.2020, 21:25:52 found 0 vulnerabilities
14.7.2020, 21:25:52 Plugin "homebridge-calendar" removed.
14.7.2020, 21:25:52 Got SIGINT, shutting down Bridge...
14.7.2020, 21:25:53 Loaded plugin "homebridge-mi-flora-filtered".
14.7.2020, 21:25:55 Loaded plugin "homebridge-shelly".
14.7.2020, 21:25:56 Loaded plugin "homebridge-weather-plus".
14.7.2020, 21:25:56 [Weather Plus] Adding station with weather service Dark Sky named 'Now'
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "Now"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "Today"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "In 1 Day"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "In 2 Days"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "In 3 Days"...
14.7.2020, 21:25:56 [Weather Plus] Initializing platform accessory "In 4 Days"...
14.7.2020, 21:25:56 [Flower Sensor West] aa46c6dc-2788-4e33-b2f4-03fba6969329
14.7.2020, 21:25:56 [Flower Sensor West] 6a4cbbb1-7967-4b62-aa1d-c8a13001efc6
14.7.2020, 21:25:56 [Flower Sensor West] c1c4efd2-9589-48bd-8bdc-d551a020c802
14.7.2020, 21:25:56 [Shelly] 9 accessories loaded from cache
14.7.2020, 21:25:56 Bridge is running on port 51826.
14.7.2020, 21:25:56 [Shelly] Admin server is running on port 8181

**Comment by askovi** [comment]
For security purposes, by default, HOOBS does not run as root and keeps all plugins contained. Try this to test if it works:

You have to login via ssh with user hoobs and password hoobsadmin. Then stop the HOOBS Service with this command:

`sudo hoobs service stop`

then start HOOBS as root manually with this command:

`sudo hoobs`

This will create a separate instance of HOOBS. Do not close the Terminal or HOOBS will stop running. 
Go back to hoobs.local and install your mi-flower plugin and test it. See if it fixes the issue.

**Comment by GitGabKat** [comment]
This effects the following error:
hoobs@hoobs:~ $ sudo hoobs service stop
hoobs@hoobs:~ $ sudo hoobs
Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1306:16)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 80
}
[HOOBS] Stopping server.

**Comment by askovi** [comment]
First make sure the HOOBS Port in your advanced config is set to 80 (not 8080) run the following commands in order:

`sudo systemctl disable nginx`

`sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`

`sudo reboot`

Wait 2 minutes to reboot then log back into ssh and type:

`sudo systemctl stop hoobs`

`sudo hoobs`

Now you have hoobs running as root in your terminal. Do not close the terminal. Go to hoobs.local and test your plugin (please note this is a separate hoobs instance so you won't have any plugins installed - this is normal). 

To go back to your regular instance, press ctrl + c in the terminal to stop the HOOBS process. Then type:

`sudo systemctl start hoobs`

**Comment by GitGabKat** [comment]
After logging in to the new instance, installing the mi flora filtered plugin, the measurements of the sensor still doesn't appear. Instead I'm not able to reach any instance due to error 

Last login: Sat Jul 25 14:02:36 2020 from 192.168.178.27
-bash: /etc/profile: line 46: unexpected EOF while looking for matching `"'
-bash: /etc/profile: line 65: syntax error: unexpected end of file

**Comment by GitGabKat** [comment]
make: Leaving directory '/usr/local/lib/node_modules/bluetooth-hci-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bluetooth-hci-socket
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bluetooth-hci-socket@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-25T22_30_44_531Z-debug.log

**Comment by askovi** [comment]
Try this plugin instead, some users mentioned it works well: https://plugins.hoobs.org/plugin/homebridge-mi-flora-filtered
(search for 'filtered' in the plugin search box)

**Comment by GitGabKat** [comment]
I use that one the whole time.

**Comment by GitGabKat** [comment]
Is there any solution possible from the developer of the plug in, or isn't it for seen that hoobs makes it possible to access the BTLE?

**Comment by GitGabKat** [comment]
Sorry that I still insist on this: is there a workaround at least which give the plugin access to the BTLE with hoobs user? - I wouldn't like to built up my hole config running hoobs as root user.

**Comment by SvenPe** [comment]
> Sorry that I still insist on this: is there a workaround at least which give the plugin access to the BTLE with hoobs user? - I wouldn't like to built up my hole config running hoobs as root user.

I got it working using this command from the original noble Page on GitHub https://github.com/noble/noble

sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
