### ISSUE TITLE
HOOBS adding code to the homebridge config that should not be in there, resulting in Homebridge not starting

### ISSUE THREAD

**Issue by jcvangent** [hoobs-org/HOOBS#706]
**Description**
I installed the "Camera Uni Fi Protect" plugin, and I could not get it to work. Had a chat about it on Github with the developers:
https://github.com/hjdhjd/homebridge-unifi-protect2/issues/18 to try to get it to work.

But then I noticed that HOOBS is adding stuff into the Homebridge config that is a duplicate and as a result Homebridge won't start:

In the controllers section, I only want to add this
![image](https://user-images.githubusercontent.com/223772/86280811-cfb27600-bbdc-11ea-8c69-ac17fb260690.png)

But as soon as I hit save, it will turn it into this
![image](https://user-images.githubusercontent.com/223772/86280880-eb1d8100-bbdc-11ea-9be5-bbf8afb85c26.png)

If I then look in the config file I see a nested section with a duplicate of the controller part:
![image](https://user-images.githubusercontent.com/223772/86280912-fa9cca00-bbdc-11ea-9ef3-9fd69533c0e3.png)

If I remove the wrong nested part and hit save (by hand on the terminal straight in the config file):
![image](https://user-images.githubusercontent.com/223772/86280945-08524f80-bbdd-11ea-9a40-6b078c97b041.png)

I can then start Homebridge from the HOOBS config panel, however at that moment HOOBS overwrites the config file again with the wrong (nested) code, so the next time I want to restart HOOBS it won't work unless I stop the Homebridge service, manually edit the config file on the server and then start Homebridge.

**Version**
Version 3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you performed an upgrade, please let us know your previous version.

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X ] No, fresh install

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
 Raspberry Pi 3 model B+, running Linux unifipi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Just this one plugin: https://www.npmjs.com/package/homebridge-unifi-protect2

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
The Controllers input box is expecting an array according to the config.schema provided by the plugin developer. An array is defined in between square brackets [ ] which is why you see them appear by default in the box when installing the plugin. 
If you remove them and only paste the values for url, username and password, HOOBS tries to rebuild the array from those which in this case doesn't match the config schema. 

This is what you need to paste in the Controllers box to make it work correctly (replace with actual data):

`[
    {
        "url": "https://my-cloud-key:7443",
        "username": "some-unifi-protect-user (or create a new one just for homebridge)",
        "password": "some-password"
    }
]`

**Comment by jcvangent** [comment]
Check that did the trick! Maybe add a little explanation on that input field to make it easier for other people to don't make a mistake like that?
