### ISSUE TITLE
Hoobs 3.2.6 not working

### ISSUE THREAD

**Issue by mikelito80** [hoobs-org/HOOBS#708]
**Description**
Hoobs doesn't work anymore since I upgraded to 3.2.6

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes

**Pervious version**
I don´t remember

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
I don´t remember

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
Shelly
Samsung Tizen

I followed the steps in this post.  
https://github.com/hoobs-org/HOOBS/issues/649
This is what I did:

sudo npm install -g n
and than
sudo n stable

Now it hangs in the boot loop

![82746239-e2d85780-9d8d-11ea-945a-142a0853b1ed](https://user-images.githubusercontent.com/59291241/86406466-710bfb80-bcb3-11ea-8d97-e93967ad8332.png)

I need help.
Thank you in advance

**Comment by askovi** [comment]
You upgraded node so you need to reinstall HOOBS with these commands via ssh:


sudo npm uninstall -g @hoobs/hoobs

sudo npm install -g --unsafe-perm @hoobs/hoobs

Then reboot with:

sudo reboot

**Comment by mikelito80** [comment]
Please explain me how can i do use vis ssh. I don’t know what is that. Thank you very much.

**Comment by askovi** [comment]
1.	Login to the HOOBS Box via SSH on your computer.
On MacOS use the Terminal app and type: ssh hoobs@hoobs.local
Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin
On Windows, use Putty with the same credentials as above.
2.	After successfully logging in, paste the commands from my previous comment in order.

**Comment by mikelito80** [comment]
Thank you very much. Problem solved!!
