### ISSUE TITLE
homebridge-securitysystem

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#710]
3.0.2 was actually pulled 1 h after release because of sec issues.
3.1.0 is online but still not visible on hoobs updates...

**Comment by BobbySlope** [comment]
Updates were pulled once in 24h, should be visible tomorrow

**Comment by Christian-CFP** [comment]
No. Its more than 24h now. Greetings 😉

**Comment by BobbySlope** [comment]
@askovi please check the npm sync

**Comment by askovi** [comment]
Updated.

**Comment by Christian-CFP** [comment]
@askovi I think you got problems with npm service... Security System has again an update since yesturday... 3.2.0.
No update showing.. ;(

**Comment by askovi** [comment]
The updater service just ran. It's updated now

**Comment by Christian-CFP** [comment]
Awesome thx!
