### ISSUE TITLE
homebridge-xiaomi-fan update

### ISSUE THREAD

**Issue by h0mesmart** [hoobs-org/HOOBS#711]
**Description**
A new update of the homebridge-xiaomi-fan has been published but not visible on hoobs UI

**Expected behavoir**
Hoobs UI should propose the button Update

**Plugin name**
Homebridge-xiaomi-fan

**Version**
Hoobs 3.2.6 
Node 12.16.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x] HOOBS SD Card
- [ ] Custom Install

**Comment by BobbySlope** [comment]
@askovi please check the npm sync

**Comment by askovi** [comment]
Updated.
