### ISSUE TITLE
Help needed with HOOBS for beginner

### ISSUE THREAD

**Issue by selzen** [hoobs-org/HOOBS#713]
Good morning, I have ordered HOOBS on a SD card and inserted the card in a Raspberry Pi Model B with 8GB. When I try to connect via WifI (SSID : HOOBS) or ethernet it just does not work. It does not connect to the network at all. There are status lights blinking on the Raspberry:

The right is continuously RED

The left light is green, blinking 4 times normal and 4 time fast. Any idea ? Any help is appreciated, this is the first time I am using a Raspberry. Kind regards, Stef den Elzen

**Comment by b-** [comment]
Hi,

Could you share a little more details about which Raspberry Pi model you’re using? There are a number of different ones that are all called “B”, so it would just be a lot more helpful. If you’re not sure, look for small print on the board itself reading something like, “Raspberry Pi Model B+ V1.2”

Also, have you tried attaching a display and an HDMI cable? If not, please do so and let me know if you see anything on the screen, and what. It sounds like it might be hanging too early to show anything on screen, but confirming it would also be very helpful.

Thanks!

**Comment by selzen** [comment]
The text just mentions "Rasperry Pi 4 model B", but I might have found the cause. Looking at the error lights 4 times normal and 4 time fast. it is explained here: https://www.raspberrypi.org/documentation/configuration/led_blink_warnings.md

These lights mean: Unsupported board type

![Screenshot 2020-07-07 at 17 38 59 ](https://user-images.githubusercontent.com/67955226/86806152-e04d6b00-c078-11ea-9f09-5cb5879c3a68.jpg)

So I guess the version I received from HOOBS on SD does not support this version of the board in combination with the 8GB

**Comment by askovi** [comment]
HOOBS was fully tested with the Raspberry Pi 4 with 1GB, 2GB and 4 GB of RAM. The 8GB just came out but it shouldn't make a difference, the board doesn't have any other changes. 
When you connect the ethernet cable to your router and to the pi then connect the power cable, wait a few seconds, do you see the ethernet port lights blinking? If you do then it is connecting to the network. Look for it on your router's admin page and try reaching it via the assigned IP address. 
If you don't see any ethernet port light activity then it's not booting. You can try reflashing your microSD card using the step by step guide here: https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

**Comment by selzen** [comment]
Thanks a lot for the advice/hints & tips. This is my very first experience with Raspberry. So, yes I did connect it directly to the router. The lights of the ethernet adapter were blinking, so far so good. However even after several restarts, the green light was blinking like explained meaning "Unsupported board type". The link you emailed brings me to the HOOBS site, where I have to donate $7,00. I just paid HOOBS $19,90 for the SD card including working software, so I have also emailed support@hoobs.org to ask for support and expect that they can without additional costs.

**Comment by askovi** [comment]
You can download the img file from here without the donation: https://github.com/hoobs-org/HOOBS/releases/tag/v3.2.6

**Comment by selzen** [comment]
OK, tomorrow I will try to recreate it the Micro SD card and see if it works now, Thanks for the help

**Comment by selzen** [comment]
Good morning, I have re-imaged the SD card with v3.2.6 and it works now. Guess the SD card ordered via HOOBS (which I could read on my Macbook Air) did not have the correct version which supports the new board. Thanks to everyone for the support, Kind regards, Stef

**Comment by b-** [comment]
Thank you, I’ll close the issue
