### ISSUE TITLE
Front Gate reported error ECONNREFUSED

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/HOOBS#716]
Platform Wemo
I've just upgraded my router and sometimes my wemo maker shows as no response in homekit
I'm getting this in the log

Front Gate reported error ECONNREFUSED
what does this mean?

I've also posted the question in issues homebridge-platform-wemo 

thanks for any help

**Comment by BobbySlope** [comment]
This lead to a networking issue the information from your front gate cannot be fentched, connection refused.
try check if your wifi is enough strengh at your front gate

**Comment by OfficialKaos** [comment]
Thanks Bobby I also changed the AP radio channel and this must be causing the issue
