### ISSUE TITLE
Hoobs stuck on "starting Now'

### ISSUE THREAD

**Issue by VK10110101** [hoobs-org/HOOBS#718]
hoobs has been working fine : i restarted and now stuck on 'Starting Now'
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Please login via ssh with user hoobs and password hoobsadmin then run this command to get the logs:

`sudo hoobs service log`

**Comment by VK10110101** [comment]
Hi thanks for the quick response : I am a novice ... therefore i don't know the IP address of hoobs.local

**Comment by VK10110101** [comment]
how do i find this thanks 

sorry for the lame questions

**Comment by askovi** [comment]
You can use hoobs.local as the ip. If you’re on a mac open the Terminal app and type:

`ssh hoobs@hoobs.local`

Then type yes when prompted to accept the ssh key. Then when prompted for password, type: hoobsadmin

**Comment by VK10110101** [comment]
i get the following 
ul 11 20:55:36 hoobs homebridge[12721]: SyntaxError: Unexpected end of JSON input
Jul 11 20:55:36 hoobs homebridge[12721]:     at JSON.parse (<anonymous>)
Jul 11 20:55:36 hoobs homebridge[12721]:     at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:212:19)
Jul 11 20:55:36 hoobs homebridge[12721]:     at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
Jul 11 20:55:36 hoobs homebridge[12721]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
Jul 11 20:55:36 hoobs homebridge[12721]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jul 11 20:55:36 hoobs homebridge[12721]:     at Module._compile (internal/modules/cjs/loader.js:776:30)
Jul 11 20:55:36 hoobs homebridge[12721]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
Jul 11 20:55:36 hoobs homebridge[12721]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Jul 11 20:55:36 hoobs homebridge[12721]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Jul 11 20:55:36 hoobs homebridge[12721]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Jul 11 20:55:36 hoobs systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Jul 11 20:55:36 hoobs systemd[1]: homebridge.service: Failed with result 'exit-code'.
Jul 11 20:55:40 hoobs systemd[1]: homebridge.service: Service RestartSec=3s expired, scheduling restart.
Jul 11 20:55:40 hoobs systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 2189.
Jul 11 20:55:40 hoobs systemd[1]: Stopped Homebridge.
Jul 11 20:55:40 hoobs systemd[1]: Started Homebridge.
Jul 11 20:55:43 hoobs homebridge[12741]: [7/11/2020, 8:55:43 PM] There was a problem reading your config.json file.
Jul 11 20:55:43 hoobs homebridge[12741]: [7/11/2020, 8:55:43 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
Jul 11 20:55:43 hoobs homebridge[12741]: [7/11/2020, 8:55:43 PM]
Jul 11 20:55:43 hoobs homebridge[12741]: /usr/local/lib/node_modules/homebridge/lib/server.js:218
Jul 11 20:55:43 hoobs homebridge[12741]:     throw err;

**Comment by askovi** [comment]
Your config file is invalid. This could have happened if you manually edited the config from the Advanced option and did not write valid JSON. You can either try to fix it manually by editing the file with 

`sudo nano /home/hoobs/.hoobs/etc/config.json`

Or you can just reset it with this command:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset`

**Comment by VK10110101** [comment]
hi ive done that and get this :

hoobs@hoobs:~ $ wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset

Reseting device

Connection to hoobs.local closed by remote host.
Connection to hoobs.local closed.

however im still getting the 'yellow screen'....

**Comment by VK10110101** [comment]
can i have a response pls

**Comment by askovi** [comment]
`sudo rm -rf /home/hoobs/.hoobs`

`sudo reboot`

Wait 1 minute then open hoobs.local

**Comment by VK10110101** [comment]
hi

im still getting the yellow start up screen 

can you please assist 

thx

**Comment by BobbySlope** [comment]
Heres the Trackinglink from DHL.de <http://dhl.de/>

https://www.dhl.de/en/privatkunden/pakete-empfangen/verfolgen.html?piececode=RM429379529DE <https://www.dhl.de/en/privatkunden/pakete-empfangen/verfolgen.html?piececode=RM429379529DE>

It was handed over to Emirate Post successfully


Regards 

Bobby Slope
bobby@hoobs.org


HOOBS Inc. - Europe
c/o two4you business solution gmbh
Rhypark 8
CH-5080 Laufenburg
Switzerland

info@hoobs.org
www.hoobs.org

**Comment by askovi** [comment]
Please get the logs again

**Comment by VK10110101** [comment]
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Jul 15 15:50:37 2020 from fe80::4c0:8fd:4e2:bee8%eth0
hoobs@hoobs:~ $ sudo journalctl -f -u hoobs
-- Logs begin at Thu 2019-02-14 10:11:59 GMT. --



i get the above -- its just stays stuck

**Comment by VK10110101** [comment]
sudo hoobs service log

it does recognise this comment

**Comment by askovi** [comment]
did you reboot?

sudo reboot

**Comment by VK10110101** [comment]
Connection to hoobs.local closed by remote host.
Connection to hoobs.local closed.

i get the following when i put in the 'sudo reboot'

**Comment by askovi** [comment]
yes that's normal, the connection is closing because it's rebooting. Reconnect to it via ssh again after it boots back up and get the logs again.

**Comment by VK10110101** [comment]
it is just hanging as above and not showing the logs

**Comment by askovi** [comment]
type this via ssh now to reinstall HOOBS:

`sudo npm install -g --unsafe-perm @hoobs/hoobs`

**Comment by VK10110101** [comment]
o configure Homebridge browse to the one of the following addresses from 
another device on your network:

* http://hoobs.local
* http://192.168.0.14

All Homebridge configuration can be completed via the Homebridge Web UI.

homebridge was created by nfarina and licensed under the Apache License 2.0.
homebridge-config-ui-x was created by oznu and licensed under the MIT License.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Jul 15 16:58:14 2020 from fe80::4c0:8fd:4e2:bee8%eth0
hoobs@hoobs:~ $ sudo npm install -g --unsafe-perm @hoobs/hoobs
npm WARN deprecated bonjour-hap@3.5.11: bonjour-hap is no longer maintained. Refer to the Notice section of the README.md. The library should not be used anymore
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> bufferutil@4.0.1 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil
> node-gyp-build

make: Entering directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil/build'

> node-pty@0.9.0 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
> node scripts/install.js

make: Entering directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/unix/pty.cc: In function ‘void pty_after_waitpid(uv_async_t*)’:
../src/unix/pty.cc:486:43: warning: ‘void* memset(void*, int, size_t)’ writing to an object of type ‘class Nan::Persistent<v8::Function>’ with no trivial copy-assignment [-Wclass-memaccess]
   memset(&baton->cb, -1, sizeof(baton->cb));
                                           ^
In file included from ../../nan/nan.h:405,
                 from ../src/unix/pty.cc:20:
../../nan/nan_persistent_12_inl.h:12:40: note: ‘class Nan::Persistent<v8::Function>’ declared here
template<typename T, typename M> class Persistent :
                                        ^~~~~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
../src/unix/pty.cc: At global scope:
/root/.node-gyp/10.16.0/include/node/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.node-gyp/10.16.0/include/node/node.h:607:3: note: in expansion of macro NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/unix/pty.cc:708:1: note: in expansion of macro ‘NODE_MODULE’
NODE_MODULE(pty, init)
^~~~~~~~~~~
In file included from /root/.node-gyp/10.16.0/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.16.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.node-gyp/10.16.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.node-gyp/10.16.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.node-gyp/10.16.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.node-gyp/10.16.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'

> utf-8-validate@5.0.2 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/utf-8-validate
> node-gyp-build

make: Entering directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/utf-8-validate/build'
  CC(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/utf-8-validate/build'

> node-pty@0.9.0 postinstall /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
> node scripts/post-install.js


> @hoobs/hoobs@3.2.6 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

+ @hoobs/hoobs@3.2.6
added 200 packages from 152 contributors in 116.792s
hoobs@hoobs:~ $ sudo journalctl -f -u hoobs
-- Logs begin at Wed 2020-07-15 16:24:00 BST. --

**Comment by VK10110101** [comment]
did that : then tried to get log in -- still yellow screen then tried to get logs and still hanging

**Comment by askovi** [comment]
ohh...you were not running on HOOBS 3... those logs are from 2.1.1

Try this:
`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reboot`

**Comment by VK10110101** [comment]
ok did that : it re booted : still yellow screen and still hangs on requesting logs

**Comment by askovi** [comment]
ok at this point you should just reflash the sd card since i was giving you instructions to run on HOOBS 3 above. 
Follow this guide: https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

**Comment by VK10110101** [comment]
hold on that make no sense

Sorry but i have the Hoobs Box i don't use the SD card?

I plugged in stared to use it ... i did nothing with a SD card

**Comment by VK10110101** [comment]
ok done thanks
