### ISSUE TITLE
HOOBS service will not start

### ISSUE THREAD

**Issue by koweye** [hoobs-org/HOOBS#719]

**Comment by koweye** [comment]
for some reason now, the HOOBS service stopped and i can't get it to start. this is my log when i try to restart. whats going on and please help!!!

7/11/2020, 8:08:16 AM Loaded plugin "homebridge-blinkcameras".
7/11/2020, 8:08:16 AM Loaded plugin "homebridge-camera-ffmpeg".
7/11/2020, 8:08:16 AM Loaded plugin "homebridge-nest".
7/11/2020, 8:08:16 AM Loaded plugin "homebridge-nest-cam".
7/11/2020, 8:08:17 AM Loaded plugin "homebridge-ring".
7/11/2020, 8:08:17 AM Loaded plugin "homebridge-smartthings-v2".
7/11/2020, 8:08:17 AM Loaded plugin "homebridge-wyze-connected-home".
7/11/2020, 8:08:17 AM Loaded plugin "homebridge-zp".
7/11/2020, 8:08:17 AM [Nest Protect] Fetching Nest devices.
7/11/2020, 8:08:17 AM [Don't Blink] Init
7/11/2020, 8:08:17 AM INFO: Homebridge Version: 2.5
7/11/2020, 8:08:17 AM INFO: SmartThings-v2 Plugin Version: 2.3.4
7/11/2020, 8:08:18 AM INFO: Checking Package Version for Updates...
7/11/2020, 8:08:18 AM [Sonos] homebridge-zp v1.0.36, node 12.16.3, homebridge v3.2.6, homebridge-lib v4.7.11
7/11/2020, 8:08:18 AM [Sonos] warning: 12.16.3: not using recommended node v12.18.1 LTS
7/11/2020, 8:08:18 AM [Sonos] warning: config.json: plugin_map: invalid key
7/11/2020, 8:08:18 AM Load homebridge-zp.ZPS1
7/11/2020, 8:08:18 AM [homebridge-zp.ZPS1] homebridge-zp v1.0.36, node 12.16.3, homebridge v3.2.6, homebridge-lib v4.7.11
7/11/2020, 8:08:18 AM [homebridge-zp.ZPS1] warning: 12.16.3: not using recommended node v12.18.1 LTS
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory e18423f1-8a95-460f-8b13-4f5313c7286e Ring Alarm
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory 2c369f3b-ae30-468b-b9b3-2d2d8be3a282 Base Station
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory e56752ae-c7a2-4165-9fb8-6672eb00ec57 Bedroom (Middle) Sensor 35929
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory c1c117cf-aec5-4bb4-89eb-26b20b5bee2a Front Door Sensor 60377
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory 10a97f3e-4a07-45cb-82b5-db0b4ca00618 Bedroom (Front) Sensor 39675
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory c38e1228-eae1-488d-94e8-0a5d584554c3 Garage Entry Door Sensor 18306
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory 47a28881-0329-46d2-b4f6-ea9b170c4cae Living Room Motion Sensor 34637
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory 8a082460-aefa-4b43-b947-1b7d5bdeed98 Family Room Sliding Door 07623
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory 332f5d76-75cb-4ab7-933b-b1b7b6a819b2 Bedroom (Master) Sensor 08891
7/11/2020, 8:08:18 AM [Ring] Configuring cached accessory 922d397d-e0ef-4e59-bd93-81b4f946910e Ring Keypad
7/11/2020, 8:08:18 AM [Camera ffmpeg] Configuring accessory Front Door
7/11/2020, 8:08:18 AM [Nest-cam] Configuring accessory Front Door
7/11/2020, 8:08:18 AM [Camera ffmpeg] Configuring accessory Hoku Cam
7/11/2020, 8:08:18 AM [Don't Blink] [Server Room System] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [Server Room System] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [Server Room System] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] [Don't Blink System] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [Don't Blink System] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [Don't Blink System] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] [3 External - Right Camera] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [3 External - Right Camera] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [3 External - Right Camera] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] [4 External - Left and Patio Camera] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [4 External - Left and Patio Camera] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [4 External - Left and Patio Camera] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] [5 Dining Room / Kitchen Camera] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [5 Dining Room / Kitchen Camera] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [5 Dining Room / Kitchen Camera] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] [6 TV Room / Dining Room Camera] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [6 TV Room / Dining Room Camera] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [6 TV Room / Dining Room Camera] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] [7 Garage Camera] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [7 Garage Camera] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [7 Garage Camera] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] [8 Hoku Cam Camera] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [8 Hoku Cam Camera] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [8 Hoku Cam Camera] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] [1 External - Front Door Camera] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [1 External - Front Door Camera] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [1 External - Front Door Camera] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] [2 External - Side Gate Camera] Registering
7/11/2020, 8:08:18 AM [Don't Blink] [2 External - Side Gate Camera] Initialized
7/11/2020, 8:08:18 AM [Don't Blink] [2 External - Side Gate Camera] Loaded cached accessory
7/11/2020, 8:08:18 AM [Don't Blink] Finished Launching
7/11/2020, 8:08:18 AM [Don't Blink] Discovering Cameras
7/11/2020, 8:08:18 AM [Don't Blink] Authenticating with Blink API as islandsnow@gmail.com
7/11/2020, 8:08:18 AM Making new blink client
7/11/2020, 8:08:18 AM INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
7/11/2020, 8:08:18 AM GOOD: Refreshing All Device Data | Source: (First Launch)
7/11/2020, 8:08:18 AM [Sonos] restored 1 accessories from cache
7/11/2020, 8:08:18 AM [Sonos] listening on http://192.168.1.4:46349/notify
7/11/2020, 8:08:18 AM [Sonos] RINCON_949F3E0890DA01400 [Family Room]: associated S1 zone player
7/11/2020, 8:08:18 AM [Sonos] found 1 S1 zone players in 1 zones
7/11/2020, 8:08:18 AM [Sonos] └─ Family Room
7/11/2020, 8:08:18 AM [Sonos]    └─ RINCON_949F3E0890DA01400 [Family Room]: Sonos Play:1 (S12) (master)
7/11/2020, 8:08:18 AM TypeError: Cannot read property 'message' of undefined
    at Request._callback (/home/hoobs/.hoobs/node_modules/node-blink-security/lib/blink.js:399:90)
    at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
7/11/2020, 8:08:18 AM ERROR: uncaughtException: Cannot read property 'message' of undefined
7/11/2020, 8:08:18 AM TypeError: Cannot read property 'message' of undefined
7/11/2020, 8:08:18 AM at Request._callback (/home/hoobs/.hoobs/node_modules/node-blink-security/lib/blink.js:399:90)
7/11/2020, 8:08:18 AM at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
7/11/2020, 8:08:18 AM at Request.emit (events.js:310:20)
7/11/2020, 8:08:18 AM at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:877:8)
7/11/2020, 8:08:18 AM at ClientRequest.emit (events.js:310:20)
7/11/2020, 8:08:18 AM at TLSSocket.socketErrorListener (_http_client.js:426:9)
7/11/2020, 8:08:18 AM at TLSSocket.emit (events.js:310:20)
7/11/2020, 8:08:18 AM at emitErrorNT (internal/streams/destroy.js:92:8)
7/11/2020, 8:08:18 AM at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
7/11/2020, 8:08:18 AM at processTicksAndRejections (internal/process/task_queues.js:84:21)
7/11/2020, 8:08:18 AM Got SIGTERM, shutting down Bridge...
7/11/2020, 8:08:18 AM [Sonos] closed http://192.168.1.4:46349/notify
7/11/2020, 8:08:19 AM NOTICE: Temperature Unit is Now: (F)
7/11/2020, 8:08:19 AM NOTICE: Updating Global Values | HubIP: 192.168.1.199 | UseLocal: false
7/11/2020, 8:08:19 AM WARN: Devices to Remove: (0) []
7/11/2020, 8:08:19 AM INFO: Devices to Update: (3)
7/11/2020, 8:08:19 AM GOOD: Devices to Create: (0) []
7/11/2020, 8:08:19 AM ALERT: Total Initialization Time: (1 seconds)
7/11/2020, 8:08:19 AM NOTICE: Unknown Capabilities: ["Momentary","Relay Switch"]
7/11/2020, 8:08:19 AM INFO: SmartThings DeviceCache Size: (3)
7/11/2020, 8:08:19 AM INFO: WebServer Initiated...
7/11/2020, 8:08:19 AM INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
7/11/2020, 8:08:19 AM INFO: Direct Connect Active | Listening at 192.168.1.4:8000
7/11/2020, 8:08:19 AM INFO: INFO: Your plugin version is up-to-date
7/11/2020, 8:08:19 AM NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.4
7/11/2020, 8:08:19 AM INFO: SmartThings-v2 Hub Communication Established
7/11/2020, 8:08:21 AM [Sonos] goodbye

**Comment by askovi** [comment]
The error is coming from the blink security plugin. Please open an issue with the plugin developer on their GitHub and provide the same logs. In the meantime you can uninstall the plugin then HOOBS will start again.

**Comment by koweye** [comment]
thanks for the quick response! yes you are right, after removing blink plugin the service started right up. now that i think about it i did update the plugin recently but didn't immediately stop the service. thanks!!!
