### ISSUE TITLE
Ring plugin in HOOBS shows wrong version

### ISSUE THREAD

**Issue by koweye** [hoobs-org/HOOBS#720]
**Description**
HOOBS reports that i have an update for Ring plugin. it says 
Ring
9.3.3 published 7/11/2020 • 11 hours ago

i hit update, it looks like its installing, restarts the service but every single time it keeps saying update as if it did not install. so i posted on github on developers page, he said that the current version is 9.5.0 and according to their page, they are right and they said that its a HOOBS issue

https://plugins.hoobs.org/plugin/homebridge-ring

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install

**If this is a custom install, what's your operating system?**
raspberry pi

**List your plugins**
Ring

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
https://plugins.hoobs.org/plugin/homebridge-ring

https://www.npmjs.com/package/homebridge-ring

Plugin were synced every 24h
