### ISSUE TITLE
Hoobs in a box stopped working. 

### ISSUE THREAD

**Issue by brwhitt** [hoobs-org/HOOBS#721]
I have a red light that flashes once every few minutes inside the Hoobs.  The network traffic lights are not illuminated on the hoobs or on the switch.  Help please!

**Comment by askovi** [comment]
If the ethernet port lights aren’t flashing that means it’s not booting. This can happen if it suddenly lost power while writing data to the microSD card which got corrupted. The fastest fix is to reflash the sd card using the tutorial here: https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

If you don’t feel comfortable flashing it, you can also request a replacement microSD by emailing info@hoobs.org with your order number and referencing this thread.

**Comment by brwhitt** [comment]
So I got a new SD card. And flashed it, following the directions. I plugged the new SD card into the hoobs box and still don’t get any Ethernet port lights. I left the top off the hoobs box and there is a red light and green random flashing light.  

--  
Ben Whittenburg

**Comment by askovi** [comment]
Do you see a new Wi-Fi network showing up called HOOBS when you check available Wi-Fi networks with your iPhone?

**Comment by brwhitt** [comment]
I do not

--  
Ben Whittenburg

**Comment by brwhitt** [comment]
I reformatted and loaded hoobs on my new sd card using my Mac and terminal. I still get nothing on the Ethernet port and no wifi appears for my phone to connect to. Does it matter how the sd card is formatted before I start the sudo process?

--  
Ben Whittenburg

**Comment by askovi** [comment]
You need to follow the guide here on how to reflash your sd card. You must use balenaEtcher: https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

**Comment by brwhitt** [comment]
That is what I did the first time. It did not work. Is there a particular format for the sad card (Fat32 exfat etc) that I should be using?

--  
Ben Whittenburg

**Comment by askovi** [comment]
It depends on the size of your sd card:

SDHC standard - over 2GB-32GB SDHC memory card using FAT32 file system

SDXC standard - over 32GB-2TB SDXC memory card using exFAT file system

**Comment by brwhitt** [comment]
Okay it is a 32gb. I formatted it Fat32. Flashed it exactly per the instruction on the website. I still do not get lights on the Ethernet connection and no WiFi network shows up. What now?

--  
Ben Whittenburg

**Comment by askovi** [comment]
Please send an email to info@hoobs.org with your order number and the best phone number to reach you at. Someone will assist you directly.
