### ISSUE TITLE
Plugin List for installation is empty

### ISSUE THREAD

**Issue by chrisjshull** [hoobs-org/HOOBS#724]
**Description**

**Version**
Bridge Name | HOOBS
HOOBS Version | 3.2.6
Node Version | 12.14.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
Don't recall

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Don't recall

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
macOS Mojave

There used to be a list of installable plugins, bt now it's just already installed and "search". Is that intended?

![image](https://user-images.githubusercontent.com/877679/87484504-39724d00-c5eb-11ea-8753-3e5bb31e9147.png)

**Comment by askovi** [comment]
This is intended. The categories have been removed as they were not very intuitive. A new UI will improve the user experience in a future update.
