### ISSUE TITLE
Auto update for installed plugins

### ISSUE THREAD

**Issue by wmlorenzo** [hoobs-org/HOOBS#726]
The plugins I have installed are constantly having updates released for them. Rather than me having to check manually when I think of it to see if there are updates, does Hoobs have an option for me to "auto update" the installed plugins as they become available e.g. where it can check daily and just install it automatically.

I'm happy to accept the risk if something breaks (since I just hit update anyway) so I'm taking that risk as is. And if an issue arises I can look at the logs or at the version history of the plugins to see what happened.

This way I'm always running the latest and greatest in terms of features, bug fixes, security fixes.

Thanks,
William

**Comment by askovi** [comment]
There is no such option at the moment. I added it as an enhancement suggestion to the project board. If it gets added you will be informed here. Thank you for your feedback!

**Comment by wmlorenzo** [comment]
Awesome, thank you!

**Comment by abbeycode** [comment]
@askovi where is the project board? I'd like to +1 this request and get notified if/when it's available.

**Comment by Calorion** [comment]
Could you set a `cron` job to do this?

**Comment by Calorion** [comment]
On this front, is there a way to update all plugins from the command line?

**Comment by BobbySlope** [comment]
https://support.hoobs.org/docs/60e0d1a2646faaa152f10ddb

This will upgrade a single plugin or all plugins from an bridge.

`sudo hbs plugin update`

**Comment by Calorion** [comment]
Right. Which is why I asked if there was a way to update _all_ plugins from the command line.

**Comment by BobbySlope** [comment]
`sudo hbs plugin update `
Will update all plugins

`sudo hbs plugin update my-plugin`
Will update a specific plugin

**Comment by Calorion** [comment]
All plugins in all bridges?

**Comment by BobbySlope** [comment]
You can also run the fix command from terminal to update all plugins and system dependencies. 

https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3

**Comment by Calorion** [comment]
> You can also run the fix command from terminal to update all plugins and system dependencies.
> 
> https://support.hoobs.org/topics/61c9df1fdcf29f5e39f02f34/61c9dfd0dcf29f5e39f030e3

Aha! Yes, that looks like what I was looking for. Attaching that to a cron job should eliminate the need to check HOOBS periodically for updates—which, frankly, I rarely do. I generally don’t look at HOOBS for months if everything is running smoothly.

**Comment by BobbySlope** [comment]
👍🏻 it also makes a reboot. So you dont need to cron a reboot separately
