### ISSUE TITLE
Issues with Ring in HOOBS, cannot update

### ISSUE THREAD

**Issue by koweye** [hoobs-org/HOOBS#728]
**Description**
in HOOBS, there is a notice that there is an update for ring. it lists it as 9.3.3 published 7/12/20. i hit update, it looks like it updates but nothing actually gets updated and HOOBS again reports that there is an update. i contacted the developer and they said the actual latest version is 9.6.0 not 9.3.3. and to check with you guys why HOOBS isn't seeing the latest version. 

**Expected behavoir**
i expect when i hit update HOOBS will update to latest version which it is not. its stuck on 9.3.3

**Plugin name**
RING, which is HOOBS certified

**Please report the issue to the plugin developer**
i did and they said its a HOOBS issue

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Try this command in terminal: 

`rm -fR ~/.hoobs/node_modules/homebridge-ring`

Then reinstall the plugin from the UI.

**Comment by koweye** [comment]
yup! that worked! thank you very much!

**Comment by askovi** [comment]
Awesome! Glad you got it working!
