### ISSUE TITLE
Run full log of HOOBS

### ISSUE THREAD

**Issue by alezanott** [hoobs-org/HOOBS#731]
I'm having some troubles with an installed plugin that doesn't work. I want to run a full log of HOOBS, trying to find where it gets stuck the plugin. There is a command that I can run? I've already tested `DEBUG=* hoobs -D` but I can't find anything helpful.

Basically when running this `Unifi Protect Camera Motion` plugin I get this output:
```
24/7/2020, 11:00:05 Loaded plugin "homebridge-unifi-protect-camera-motion".
24/7/2020, 11:00:05 The requested platform "UnifiProtectMotion" was not registered by any plugin.
24/7/2020, 11:00:05 Your config.json is requesting the platform "UnifiProtectMotion" which has not been published by any installed plugins.
24/7/2020, 11:00:05 Bridge is running on port 51826.
```

**Comment by askovi** [comment]
This is a plugin issue. I already submitted a fix which was accepted by the plugin developer but not yet pushed as an update. Please see here: https://github.com/beele/homebridge-unifi-protect-camera-motion/issues/57

**Comment by alezanott** [comment]
> This is a plugin issue. I already submitted a fix which was accepted by the plugin developer but not yet pushed as an update. Please see here: [beele/homebridge-unifi-protect-camera-motion#57](https://github.com/beele/homebridge-unifi-protect-camera-motion/issues/57)

Thank you @askovi !

**Comment by alezanott** [comment]
@askovi seems that even after the update of the plugin I get the same error for what concerns the registration.

**Comment by galzil** [comment]
This is a hoobs issue. 
Hoobs needs to support Homebridge API v1.0.0
Almost every plug-in that I try to install fail to work with:
The requested platform "XXXXXX" was not registered by any plugin.
Error
