### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Shady30** [hoobs-org/HOOBS#732]
When trying to login to HOOBS.local none of my credentials work. I am using RaspberryPi with HOOBS sdcard i purchased from HOOBS. Can I reset and start over? Please advise

**Comment by askovi** [comment]
If you forgot your username or password, you can reset the admin account. This won't affect your plugins and configuration.

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this to reset the users file:  sudo rm -rf /home/hoobs/.hoobs/etc/access.json

Press enter. There will be no output.

3. Type this to reboot the HOOBS Box: sudo reboot

4. Allow 2-3 minutes for the HOOBS Box to reboot then go to http://hoobs.local and create a new account.

**Comment by Shady30** [comment]
I don’t have a computer, that is why I purchased the sdcard

**Comment by askovi** [comment]
You can do it on your phone using the Termius app. Same process
