### ISSUE TITLE
Plugin update from non certified to certified, deletes configuration

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#733]
**Description**
If you perform an update from the non certified homebridge-securitysystem plugin to the HOOBS certified version, HOOBS will delete the entire configuration for this plugin.

**Version**
3.2.6

**Comment by rpolenthon** [comment]
I found out that HOOBS gave the plugin a new accessory identifier. It switched from `"Security system"` to `"security-system"`

**Comment by askovi** [comment]
This is normal. It uses the pluginAlias as defined in the config schema here: https://github.com/MiguelRipoll23/homebridge-securitysystem/blob/master/config.schema.json
Or here if defined as accessory: https://github.com/MiguelRipoll23/homebridge-securitysystem/blob/master/accessories.schema.json

**Comment by rpolenthon** [comment]
Ok, thanks for the answer. I will close the issue as it is more an issue on the plugin side.
