### ISSUE TITLE
homebridge-ws_ Uninstall the plugin is impossible

### ISSUE THREAD

**Issue by Enerv78180** [hoobs-org/HOOBS#734]
**Description**
I cannot uninstall the plugin "WS" on Hoobs

**Expected behavoir**
Uninstall the plugin

**Plugin name**
homebridge-ws

**HOOBS Version**
Version: 3.2.6

**Comment by askovi** [comment]
Run this command in the HOOBS Terminal:

`rm -fR ~/.hoobs/node_modules/homebridge-ws`
