### ISSUE TITLE
homebridge-tplink-smarthome version 5.1.0

### ISSUE THREAD

**Issue by kbardai** [hoobs-org/HOOBS#735]
Hey,

How can we upgrade the tp-link smarthome plugin to the latest version 5.1.0? https://www.npmjs.com/package/homebridge-tplink-smarthome

HOOBS only shows version 4.0.1

Thanks

**Comment by askovi** [comment]
It was version locked awaiting certification. I just certified it and enabled updates. You can now upgrade to the latest version.

**Comment by kbardai** [comment]
Thanks, worked as expected.
