### ISSUE TITLE
Unable to access Hoobs UI

### ISSUE THREAD

**Issue by listenclosely03** [hoobs-org/HOOBS#736]
I am unable to access my HOOBS UI to complete the set up. I have tried both wired and wireless set up types. Also have reset username and password via terminal. But am not able to get any further. Upon trying to access hoobs.local, web browser cannot reach the page. I have tried hoobs.local, 192.168.X.XXX, hoobs.lan.  None of which will allow me to view the UI to complete my set up. 

Any help would be greatly appreciated.

Last login: Tue Jul 28 06:19:05 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
alexanders-mbp:~ Lex$ ssh hoobs@hoobs.local
Warning: Permanently added the ECDSA host key for IP address 'fe80::7dde:66f0:fe47:a3cb%en0' to the list of known hosts.
hoobs@hoobs.local's password: 
Linux hoobs 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l
Raspberry Pi 3 Model B Plus Rev 1.3

*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://192.168.86.67

HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Jul 28 09:19:51 2020 from 192.168.86.49
Could not chdir to home directory /home/hoobs: No such file or directory
hoobs@hoobs:/$

**Comment by askovi** [comment]
Run this via ssh to get the logs:

`sudo hoobs service log`

**Comment by listenclosely03** [comment]
This is what came up. 

internal/fs/utils.js:230
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:841:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 753.
Stopped HOOBS.
Started HOOBS.

**Comment by askovi** [comment]
Run this command to reinstall HOOBS 

`sudo npm install -g --unsafe-perm @hoobs/hoobs`

**Comment by listenclosely03** [comment]
This is what is showing in Terminal

*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://192.168.86.67


HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Jul 28 15:48:07 2020 from fe80::c34:5246:56ff:131f%wlan0
Could not chdir to home directory /home/hoobs: No such file or directory
hoobs@hoobs:/$ sudo npm install -g --unsafe-perm @hoobs/hoobs
npm WARN deprecated bonjour-hap@3.5.11: bonjour-hap is no longer maintained. Refer to the Notice section of the README.md. The library should not be used anymore
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> @hoobs/hoobs@3.2.6 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

+ @hoobs/hoobs@3.2.6
removed 2 packages and updated 16 packages in 47.374s
hoobs@hoobs:/$

**Comment by askovi** [comment]
Ok so it looks like it got installed. So now do

`sudo hoobs service restart`

Then

`sudo hoobs service log`

If not working please get the node version with

`node -v`

**Comment by listenclosely03** [comment]
This is now what shows in terminal. Forgive me as I dont know what "node -v" means or where to locate it.  Thank you

Last login: Tue Jul 28 16:23:36 2020 from fe80::c34:5246:56ff:131f%wlan0
Could not chdir to home directory /home/hoobs: No such file or directory
hoobs@hoobs:/$ sudo hoobs service restart
hoobs@hoobs:/$ sudo hoobs service log
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 3585.
Stopped HOOBS.
Started HOOBS.

**Comment by listenclosely03** [comment]
I am still unable to access hoobs.local or via IP. What in "node -v"?

**Comment by askovi** [comment]
node -v is the command to get your nodejs version.
Is this a HOOBS Starter Kit or self installed setup?

**Comment by listenclosely03** [comment]
This is a Starter Kit
Alexander Bacani
*562-841-7746*
*alexander.bacani@gmail.com <alexander.bacani@gmail.com>*
*BRE #0203164*

**Comment by askovi** [comment]
Solved via remote support. Caused by user permissions issue.
