### ISSUE TITLE
Two Ring Plugins

### ISSUE THREAD

**Issue by SoullessElbows** [hoobs-org/HOOBS#737]
I have two Ring Plugins set up on my HOOBS. I have one 7.2.5 published 4/6/2020 that is old and another one HOOBS certified 9.6.0 published 7/12/2020. I tried to delete the old one but it keeps erroring out. Is there away to get around this to delete this?

**Comment by askovi** [comment]
Run this command in the HOOBS terminal:


`rm -fR ~/.hoobs/node_modules/homebridge-ring`

Then reinstall the plugin from the UI.

**Comment by SoullessElbows** [comment]
Yep that fixed it. Thanks! It was from the npx -p ring-client-api ring-auth-cli.
