### ISSUE TITLE
Hoobs reboot - Hue don´t start Apple Home all on default

### ISSUE THREAD

**Issue by disasterhome** [hoobs-org/HOOBS#738]
**Description**
Discover my lights from my deCONZ Gateway

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
hue

**Please report the issue to the plugin developer**
When I re-boot my Hoobs the Hue Plugin is not starting automatically or have heartbeat / drift and I need to go to Plugin and press "Save changes" to get it to run. In the log I can see that weather plus is working but hue has a heartbeat / drift.

I only have 2 plugins weather plus and hue - at least I removed weather plus and minimized the hue gui config to a minimum.

**Version**
latest

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
I used your customed image

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY6EB5",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 15,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "XXXX",
        "latitude": "XXXX",
        "longitude": "XXXX"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "XXXX",
        "username": "XXXX"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": false,
            "users": {
                "XXXX": "XXXX"
            },
            "heartrate": 5,
            "timeout": 30,
            "groups": true,
            "group0": false,
            "hueDimmerRepeat": true,
            "hueMotionTemperatureHistory": true,
            "lights": true,
            "linkButton": true,
            "lowBattery": 5,
            "rooms": true,
            "rules": true,
            "scenes": true,
            "scenesAsSwitch": true,
            "schedules": true,
            "sensors": true,
            "excludeSensorTypes": [
                "Daylight"
            ]
        },
        {
            "platform": "WeatherPlus",
            "plugin_map": {
                "plugin_name": "homebridge-weather-plus"
            },
            "units": "si",
            "interval": 5,
            "stations": [
                {
                    "displayName": "XXXX",
                    "service": "openweathermap",
                    "key": "XXXX",
                    "forecast": [
                        0,
                        1,
                        2
                    ],
                    "locationGeo": [
                        XXXX,
                        XXXX
                    ]
                }
            ]
        }
    ]
} 
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
7/29/2020, 8:18:40 AM HOOBS listening on port 80.
7/29/2020, 8:18:44 AM Loaded plugin "homebridge-hue".
7/29/2020, 8:18:44 AM Loaded plugin "homebridge-weather-plus".
7/29/2020, 8:18:44 AM [Hue] config.json: warning: plugin_map: ignoring unknown key
7/29/2020, 8:18:44 AM [Hue] homebridge-hue v0.11.73, node v12.16.3, homebridge v3.2.6
7/29/2020, 8:18:44 AM [Hue] warning: not using recommended node version v12.18.2 LTS
7/29/2020, 8:18:45 AM [WeatherPlus] Adding station with weather service OpenWeatherMap named 'XXXXX'
7/29/2020, 8:18:45 AM [WeatherPlus] Initializing platform accessory "XXXXX"...
7/29/2020, 8:18:45 AM [WeatherPlus] Initializing platform accessory "Today"...
7/29/2020, 8:18:45 AM [WeatherPlus] Initializing platform accessory "In 1 Day"...
7/29/2020, 8:18:45 AM [WeatherPlus] Initializing platform accessory "In 2 Days"...
7/29/2020, 8:18:45 AM [Hue] searching bridges and gateways
7/29/2020, 8:18:50 AM [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.78, api v1.16.0
7/29/2020, 8:18:50 AM [Hue] Phoscon-GW: 1 accessories
7/29/2020, 8:18:50 AM [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
7/29/2020, 8:18:50 AM [Hue] Initializing platform accessory "Phoscon-GW"...
7/29/2020, 8:18:50 AM [Hue] Phoscon-GW: 2 services
7/29/2020, 8:18:50 AM Bridge is running on port 51826.
7/29/2020, 8:19:06 AM [Hue] heartbeat 1, drift 14142
7/29/2020, 8:19:06 AM [Hue] heartbeat 2, drift 13144
7/29/2020, 8:19:06 AM [Hue] heartbeat 3, drift 12145
7/29/2020, 8:19:06 AM [Hue] heartbeat 4, drift 11147
7/29/2020, 8:19:06 AM [Hue] heartbeat 5, drift 10148
7/29/2020, 8:19:06 AM [Hue] heartbeat 6, drift 9151
7/29/2020, 8:19:06 AM [Hue] heartbeat 7, drift 8152
7/29/2020, 8:19:06 AM [Hue] heartbeat 8, drift 7154
7/29/2020, 8:19:06 AM [Hue] heartbeat 9, drift 6155
7/29/2020, 8:19:06 AM [Hue] heartbeat 10, drift 5157
7/29/2020, 8:19:06 AM [Hue] heartbeat 11, drift 4159
7/29/2020, 8:19:06 AM [Hue] heartbeat 12, drift 3160
7/29/2020, 8:19:06 AM [Hue] heartbeat 13, drift 2162
7/29/2020, 8:19:06 AM [Hue] heartbeat 14, drift 1163
```

**Additional context**
After a reboot also in my Apple Home App all settings from hue are on default room and the accessories gone in my automation section. The weather plus sensors are still correct added and also in the correct room.

The serial numbers are identical after a reboot.

![image](https://user-images.githubusercontent.com/68971774/88852407-87dc3a00-d1ee-11ea-92b2-1b58e180d253.png)

**Comment by askovi** [comment]
is your deconz service running on the same device? It might take longer to start the deconz service so the plugin doesn't find it initially?

**Comment by disasterhome** [comment]
> 
> 
> is your deconz service running on the same device? It might take longer to start the deconz service so the plugin doesn't find it initially?

Hi askovi,

yes, my deCONZ is running on the same PI like the HOOBS. How can I manipulate it that my deCONZ is started before HOOBS is starting / discovering?

**Comment by disasterhome** [comment]
Now, I did a test and run deCONZ on my Windows 10 machine and HOOBS standalone on the PI then everything is working also reboot / boot.
Is there a HOOBS fix to get a delay of HOOBS until deCONZ is finally running? Otherwise I need to buy a 2nd RPI just for deCONZ bridge.
