### ISSUE TITLE
Hoobs running on port 80 not 8080

### ISSUE THREAD

**Issue by qdoobp** [hoobs-org/HOOBS#739]
**Description**
The Hoobs port was changed from 8080 which is stated in the documentation to 80. The documentation was not changed to reflect this and it causes issues with existing webservers.
Maybe there should be an easy way to set the port after installation.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Ubuntu Server 20.04 on Raspberry 4

**List your plugins**
No plugins yet.

**Comment by askovi** [comment]
This option already exists. It's in settings -> Server Settings -> Server Port

**Comment by qdoobp** [comment]
But to use that I need to start the server. It would be great to define the port beforehand.

**Comment by askovi** [comment]
You can do that by editing the /home/hoobs/.hoobs/etc/config.json file and setting the port you want.

**Comment by qdoobp** [comment]
Ahh, perfect. That's what I was looking for. Thank you.
It looks like the systemd hoobs.service cannot start properly because it is not allowed to bind a port below 1024. Therefore I was unable to start it even after stopping my nginx.
