### ISSUE TITLE
Unable to Access Plugins

### ISSUE THREAD

**Issue by brentlacey** [hoobs-org/HOOBS#740]
I’m unable to access any plugins. I receive a “failed search NPM” message (screenshot below) when I attempt to search for any plugins from hoobs.local. Not sure if it’s connected, but I’m also “Failed to check for Node.js version updates” message in my logs (screenshot below). I’m running version 1.1.1. Other details below. Thanks.

![460BDD2A-6DF8-40F6-BA12-B277E91D59B9](https://user-images.githubusercontent.com/69093442/89111847-8d649a80-d40f-11ea-97ba-3dad53a4b860.jpeg)
![837B512C-3AB9-4970-BD57-4F533FDA73EC](https://user-images.githubusercontent.com/69093442/89111848-8fc6f480-d40f-11ea-8936-843c9c0ba190.jpeg)
![B2836BC8-1533-4E36-94A9-0211A1D12A8C](https://user-images.githubusercontent.com/69093442/89111849-90f82180-d40f-11ea-822e-07bcc06f78f0.jpeg)

**Comment by askovi** [comment]
That means HOOBS doesn't have connectivity. Make sure it's connected to the internet. If you're using an eero router you will have to reboot it. 
Also, once you get it working again, it's highly recommended you upgrade to HOOBS 3 by installing the homebridge-to-hoobs plugin. You're running on HOOBS 2.1.1 which is no longer supported.

**Comment by brentlacey** [comment]
Thank you!
