### ISSUE TITLE
Bigger Json box for plugins

### ISSUE THREAD

**Issue by TMaskell** [hoobs-org/HOOBS#743]
**Is your feature request related to a problem? Please describe.**
I have spent most of today adding Broadlink to Homebridge, This plugin is entirely in the Json editor as HOOBS has no customised entry. The Json box is so small it's nearly impossible to work any length of code with it. I had to copy it out to Jsonlint.com and then copy it back in. A shame when you have a Json editor built in

**Describe the solution you'd like**
Make the Box bigger

**Describe alternatives you've considered**
I would need to keep copying it out to Jsonlint. Not the end of the world but a bit annoying

**Additional context**
<img width="1111" alt="Screenshot 2020-08-03 at 20 43 10" src="https://user-images.githubusercontent.com/60987401/89220704-fabc2b00-d5c9-11ea-8eb4-4b9fd3761ad8.png">

**Comment by askovi** [comment]
This will be done in a future update. It has been added to the project board. I will close the issue for now. Thank you for your feedback.
