### ISSUE TITLE
Looking for an easy solution on my HOOBS server to get a static IP 

### ISSUE THREAD

**Issue by Tesla-P100FX** [hoobs-org/HOOBS#744]
I use XFINITY at home and they don't support Static IP.  They dynamically allocate IP addresses from their router.    I would love a HOOBS plugin that would allow you to set up static IP address for my server.   There are ways to set it up , but they are complex and require that you log on to your Hoobs server locally.

**Comment by dipen26** [comment]
I think you can reserve DHCP IP through your router too, because for Wyze Camera that what I did. Wyze was keep changing ip when router, and camera restarts, and I had to keep regenerating address.

**Comment by askovi** [comment]
This is done in the router's settings. All routers support this functionality. It might be called RESERVED IP instead. Here's a screenshot from xfinity: 
![image](https://user-images.githubusercontent.com/3981552/89449702-754e8d00-d727-11ea-9ccc-ca9f0d9c5adb.png)
Click Add device with reserved ip.
