### ISSUE TITLE
Ewelink Max

### ISSUE THREAD

**Issue by dipen26** [hoobs-org/HOOBS#746]
**Description**
failing to add SonOff Fan controller

**Expected behavoir**
After saving config file, it should show up under connected devices

**Plugin name**
Ewelink Max

**Please report the issue to the plugin developer**
I tried to add Ewelink Max to control SonOff Fan relay with light, but it is not showing after entering all configs.

**Version**
Latest

**Did you upgrade**
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] Custom Install
- Raspberry Pi 4 2GB with Hoobs on SD Card

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
      {
            "platform": "eWeLink",
            "plugin_map": {
                "plugin_name": "homebridge-ewelink-max"
            },
            "name": "eWeLink",
            "groups": {
                "platform": "eWeLink",
                "name": "eWeLink",
                "countryCode": "1",
                "email": "xxxxxxxxxx",
                "password": "xxxxxxxxxxx",
                "imei": "4B82A832-6948-498A-A99A-D706C3ED93D1"
            },
            "imei": "4B82A832-6948-498A-A99A-D706C3ED93D1",
            "password": "xxxxxxxxxxx",
            "phoneNumber": "xxxxxxxxxxx"
        }

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
When I use this plugin, and save it keep crashing Raspberry PI.

**Comment by askovi** [comment]
Please post your logs.

**Comment by dipen26** [comment]
Before I post, Have simple question.. Do log have any personal details, which I have to remove before posting?

**Comment by dipen26** [comment]
8/5/2020, 1:40:29 PM HOOBS listening on port 80.
8/5/2020, 1:40:30 PM Loaded plugin "homebridge-camera-ffmpeg".
8/5/2020, 1:40:30 PM Loaded plugin "homebridge-chamberlain".
8/5/2020, 1:40:31 PM Loaded plugin "homebridge-ewelink-max".
8/5/2020, 1:40:31 PM homebridge API version: 2.5
8/5/2020, 1:40:33 PM Loaded plugin "homebridge-hue".
8/5/2020, 1:40:33 PM Loaded plugin "homebridge-nest".
8/5/2020, 1:40:34 PM Loaded plugin "homebridge-ring".
8/5/2020, 1:40:35 PM Loaded plugin "homebridge-vesync-v2".
8/5/2020, 1:40:35 PM Loaded plugin "homebridge-wiz-lan".
8/5/2020, 1:40:35 PM [Hue] config.json: warning: plugin_map: ignoring unknown key
8/5/2020, 1:40:35 PM [Hue] homebridge-hue v0.11.74, node v12.16.3, homebridge v3.2.6
8/5/2020, 1:40:35 PM [Hue] warning: not using recommended node version v12.18.3 LTS
8/5/2020, 1:40:35 PM [WizSmarthome] homebridge-wiz-lan v2.0.5, node v12.16.3, homebridge v3.2.6
8/5/2020, 1:40:35 PM [Nest] Fetching Nest devices.
8/5/2020, 1:40:35 PM [Living Room Fan] Initialization skipped. Missing configuration data.
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory c43631d4-c381-479a-8c7c-1d6ee88505ae Ring Alarm
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 17e718db-14d3-4b36-a248-305ddcedd39c Base Station
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 8cdfeaaa-bf7b-414e-aa2d-ac528b96c0f6 Garage Ent Door
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 59f2959f-32f8-4c31-b3b8-dba519f939b9 Guest Bedroom
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 7a9fd3bc-1892-44b8-b37e-89cfcf852d84 Main Door
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory ae0d9a34-b031-4469-bc4c-14e62433ab9d Entry way Window
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 194bbf19-05ee-4f24-9dbc-3e1ed46fa5d6 Kitchen Window
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 703404fc-9967-4da8-9724-f3dd19504d44 Back Door
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 862e1656-a19a-4c8b-a703-41d05caf1acf Ring Keypad 41198
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 7df942b2-91d8-44cc-8e68-3a48cdca1519 Living room Motion sensor
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory adc2e1e1-b7d5-4ce3-9bb5-39e33b162dd9 Dining
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory aa069d4e-7c7a-4caa-9d61-54b90f2a59c0 Kids Room Window
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 24e5249c-294b-48e4-bb65-db0fb86fab45 Kids Room Window
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory c83da7e6-6d75-4807-8687-3bbf52e2ee50 Front Door Lock
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 945a4553-9e5e-4072-b181-bab73ee9c840 Front Door
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory e8b41b34-c0f9-4b8b-9cb6-1549eafd42bf Garage
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory 5f18cc88-bf34-434e-b19e-2a740acc2e91 Panic Buttons
8/5/2020, 1:40:35 PM [WizSmarthome] Configuring cached accessory: [a8bb5086bf09] a8bb5086bf09 248a3ba5-fecb-43b7-81bc-ce5eb3db4692
8/5/2020, 1:40:35 PM [WizSmarthome] Configuring cached accessory: [a8bb5083e1d4] a8bb5083e1d4 e015f24a-9c92-4afc-8a84-3e082204a58a
8/5/2020, 1:40:35 PM [WizSmarthome] Configuring cached accessory: [a8bb508d4522] a8bb508d4522 cdba84da-a051-4296-a063-aa337fb1387b
8/5/2020, 1:40:35 PM [WizSmarthome] Configuring cached accessory: [a8bb508c784e] a8bb508c784e b7e089cd-5a7a-4d85-a221-f398093fed02
8/5/2020, 1:40:35 PM [WizSmarthome] Configuring cached accessory: [a8bb5083fb30] a8bb5083fb30 ed90ae42-d5ee-47e4-9ef1-a2b908412483
8/5/2020, 1:40:35 PM [Ring] Configuring cached accessory cd40245d-a9e9-4384-8d8c-047d0b1d236b Backdoor Lock
8/5/2020, 1:40:35 PM [Kids Room] [Kids] Configuring accessory...
8/5/2020, 1:40:35 PM [WizSmarthome] New Device Online: [a8bb5086bf09] bulb [a8bb5086bf09] 192.168.1.23 49159
8/5/2020, 1:40:35 PM [WizSmarthome] Adding: [a8bb5086bf09] bulb [a8bb5086bf09]
8/5/2020, 1:40:35 PM [Hue] searching bridges and gateways
8/5/2020, 1:40:37 PM [Ring] Creating location socket.io connection
8/5/2020, 1:40:37 PM [Ring] Ring connected to socket.io server
8/5/2020, 1:40:37 PM [Ring] Configuring 2 cameras and 25 devices for location "XXXXXX" - locationId:
8/5/2020, 1:40:37 PM [Ring] Hidden accessory df2376b1-d95b-44ee-a530-a1bd43ed0a6a adapter.zigbee ZigBee onboard adapter
8/5/2020, 1:40:37 PM [Ring] Hidden accessory c0cd4fe9-9ef8-4314-9c61-45b7be853d9c access-code.vault Code Vault
8/5/2020, 1:40:37 PM [Ring] Hidden accessory 04cd01f5-f2d7-4087-8601-653d013d3ded access-code Security Access Code
8/5/2020, 1:40:37 PM [Ring] Hidden accessory f6692210-533c-43e4-9220-229d1576961f adapter.zwave Z-Wave Adapter
8/5/2020, 1:40:37 PM [Ring] Hidden accessory e8c86c49-af6f-4479-b160-80c8328b8584 range-extender.zwave Entryway Z-Wave Extender 34515
8/5/2020, 1:40:37 PM [Ring] Hidden accessory 207681c2-82b4-40eb-867b-52da01dc689a access-code Yale Access Code
8/5/2020, 1:40:37 PM [Ring] Hidden accessory 1d96d0bf-51bb-4dec-97d4-44402f2392b4 access-code Access Code
8/5/2020, 1:40:38 PM [Nest] initing thermostat "Living Room Thermostat": deviceId: 09AA01AC20170HDB structureId: 49a67890-e08c-11e8-9a1a-0e536acac670
8/5/2020, 1:40:38 PM [Nest] initing home_away_sensor "Home Occupied": deviceId: 49a67890-e08c-11e8-9a1a-0e536acac670 structureId: 49a67890-e08c-11e8-9a1a-0e536acac670
8/5/2020, 1:40:38 PM [Nest] initing temp_sensor "Office": deviceId: 18B430CAC9B76BE1 structureId: 49a67890-e08c-11e8-9a1a-0e536acac670
8/5/2020, 1:40:38 PM [Nest] initing temp_sensor "Master Bedroom": deviceId: 18B430C110F78C89 structureId: 49a67890-e08c-11e8-9a1a-0e536acac670
8/5/2020, 1:40:38 PM [Nest] initing temp_sensor "Kids Room": deviceId: 18B430C3AF2CE0B7 structureId: 49a67890-e08c-11e8-9a1a-0e536acac670
8/5/2020, 1:40:38 PM [Nest] Initializing platform accessory "Living Room Thermostat"...
8/5/2020, 1:40:38 PM [Nest] Initializing platform accessory "Home Occupied"...
8/5/2020, 1:40:38 PM [Nest] Initializing platform accessory "Office"...
8/5/2020, 1:40:38 PM [Nest] Initializing platform accessory "Master Bedroom"...
8/5/2020, 1:40:38 PM [Nest] Initializing platform accessory "Kids Room"...
8/5/2020, 1:40:41 PM [Hue] Philips hue: Philips BSB002 bridge v1939070020, api v1.38.0
8/5/2020, 1:40:41 PM [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.39.0
8/5/2020, 1:40:41 PM [Hue] Philips hue: 13 accessories
8/5/2020, 1:40:41 PM [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Philips hue"...
8/5/2020, 1:40:41 PM [Hue] Philips hue: 2 services
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Front Garage 2"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Front Garage 1"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Front Porch Light"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Living Room 3"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Living Room 4"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Living Room 1"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Living Room 2"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Backyard"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Office Light 1"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Office light 2"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Master Bedroom Light 1"...
8/5/2020, 1:40:41 PM [Hue] Initializing platform accessory "Master Bedroom Light 2"...
8/5/2020, 1:40:41 PM Bridge is running on port 51826.
8/5/2020, 1:41:01 PM [Hue] heartbeat 8, drift 11450
8/5/2020, 1:41:01 PM [Hue] heartbeat 9, drift 10451
8/5/2020, 1:41:01 PM [Hue] heartbeat 10, drift 9452
8/5/2020, 1:41:01 PM [Hue] heartbeat 11, drift 8455
8/5/2020, 1:41:01 PM [Hue] heartbeat 12, drift 7457
8/5/2020, 1:41:01 PM [Hue] heartbeat 13, drift 6459
8/5/2020, 1:41:01 PM [Hue] heartbeat 14, drift 5460
8/5/2020, 1:41:01 PM [Hue] heartbeat 15, drift 4462
8/5/2020, 1:41:01 PM [Hue] heartbeat 16, drift 3466
8/5/2020, 1:41:01 PM [Hue] heartbeat 17, drift 2469
8/5/2020, 1:41:01 PM [Hue] heartbeat 18, drift 1471
8/5/2020, 1:41:01 PM [Hue] heartbeat 19, drift 472

**Comment by askovi** [comment]
There are no personal details in the logs, only in the config. 
Make sure you grab the logs when you see the error happening. Or go to settings -> backup -> log and download the log file and just attach it here.

**Comment by dipen26** [comment]
[logs-2.txt](https://github.com/hoobs-org/HOOBS/files/5030635/logs-2.txt)

**Comment by dipen26** [comment]
Any Fix?

**Comment by askovi** [comment]
Your config is incorrect. Please use the visual configuration to enter your account details. You don't need to add anything to the Groups box unless you're adding blinds. Like this:
![image](https://user-images.githubusercontent.com/3981552/89854142-20fd4000-db61-11ea-88f0-a25601159d58.png)
