### ISSUE TITLE
My server is Stopping

### ISSUE THREAD

**Issue by Tesla-P100FX** [hoobs-org/HOOBS#747]
TV
 Watch Apple TV 2
8/4/2020,
 5:03:03 PM errorhub Error: connect ETIMEDOUT 10.0.0.225:5222
8/4/2020,
 5:03:03 PM at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
8/4/2020,
 5:03:03 PM errno: 'ETIMEDOUT',
8/4/2020,
 5:03:03 PM code: 'ETIMEDOUT',
8/4/2020,
 5:03:03 PM syscall: 'connect',
8/4/2020,
 5:03:03 PM address: '10.0.0.225',
8/4/2020,
 5:03:03 PM port: 5222
8/4/2020,
 5:03:03 PM }
8/4/2020,
 5:04:48 PM errorhub Error: connect ETIMEDOUT 10.0.0.225:5222
8/4/2020,
 5:04:48 PM at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
8/4/2020,
 5:04:48 PM errno: 'ETIMEDOUT',
8/4/2020,
 5:04:48 PM code: 'ETIMEDOUT',
8/4/2020,
 5:04:48 PM syscall: 'connect',
8/4/2020,
 5:04:48 PM address: '10.0.0.225',
8/4/2020,
 5:04:48 PM port: 5222
8/4/2020,
 5:04:48 PM }
8/4/2020,
 5:13:28 PM errorhub Error: connect ETIMEDOUT 10.0.0.225:5222
8/4/2020,
 5:13:28 PM at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
8/4/2020,
 5:13:28 PM errno: 'ETIMEDOUT',
8/4/2020,
 5:13:28 PM code: 'ETIMEDOUT',
8/4/2020,
 5:13:28 PM syscall: 'connect',
8/4/2020,
 5:13:28 PM address: '10.0.0.225',
8/4/2020,
 5:13:28 PM port: 5222
8/4/2020,
 5:13:28 PM }
8/4/2020,
 5:16:38 PM errorhub Error: connect ETIMEDOUT 10.0.0.225:5222
8/4/2020,
 5:16:38 PM at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
8/4/2020,
 5:16:38 PM errno: 'ETIMEDOUT',
8/4/2020,
 5:16:38 PM code: 'ETIMEDOUT',
8/4/2020,
 5:16:38 PM syscall: 'connect',
8/4/2020,
 5:16:38 PM address: '10.0.0.225',
8/4/2020,
 5:16:38 PM port: 5222
8/4/2020,
 5:16:38 PM }
8/4/2020,
 5:24:33 PM errorhub Error: connect ETIMEDOUT 10.0.0.225:5222
8/4/2020,
 5:24:33 PM at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
8/4/2020,
 5:24:33 PM errno: 'ETIMEDOUT',
8/4/2020,
 5:24:33 PM code: 'ETIMEDOUT',
8/4/2020,
 5:24:33 PM syscall: 'connect',
8/4/2020,
 5:24:33 PM address: '10.0.0.225',
8/4/2020,
 5:24:33 PM port: 5222
8/4/2020,
 5:24:33 PM }
8/4/2020,
 5:25:55 PM Error: MAX_CLIENTS=6 at Connection.onStanza (/home/hoobs/.hoobs/node_modules/node-xmpp-core/lib/Connection.js:355:17) at StreamParser.<anonymous> (/home/hoobs/.hoobs/node_modules/node-xmpp-core/lib/Connection.js:226:10) at StreamParser.emit
 (events.js:310:20) at SaxLtx.<anonymous> (/home/hoobs/.hoobs/node_modules/node-xmpp-core/lib/StreamParser.js:58:14) at SaxLtx.emit (events.js:310:20) at SaxLtx._handleTagOpening (/home/hoobs/.hoobs/node_modules/ltx/lib/parsers/ltx.js:31:18) at SaxLtx.write
 (/home/hoobs/.hoobs/node_modules/ltx/lib/parsers/ltx.js:105:26) at StreamParser.write (/home/hoobs/.hoobs/node_modules/node-xmpp-core/lib/StreamParser.js:123:17) at Connection.onData (/home/hoobs/.hoobs/node_modules/node-xmpp-core/lib/Connection.js:305:17)
 at Socket.emit (events.js:322:22) at addChunk (_stream_readable.js:286:12) at readableAddChunk (_stream_readable.js:268:9) at Socket.Readable.push (_stream_readable.js:209:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
8/4/2020,
 5:25:55 PM Got SIGTERM, shutting down Bridge...

10.0.0.225 is a Harmony Hub.   

Running 3.2.6

**Comment by askovi** [comment]
Make sure you have a static IP address defined for your Harmony Hub in your router settings. Also make sure you use the ip in your configuration, not the name of your harmony hub. See here: https://github.com/hoobs-org/HOOBS/issues/645#issuecomment-669194364
