### ISSUE TITLE
Cannot load login page after upgrading to 3.0 Beta

### ISSUE THREAD

**Issue by angelflames1337** [hoobs-org/HOOBS#75]
Pi Model: 2B
Hoobs before: Yes
Version: 2.1.1

Use the upgrade plugin and stuck at this screen either yellow bar at the top or loading screen at below link.

https://raw.githubusercontent.com/hoobs-org/HOOBS/master/docs/hoobs-box/loader.png
Tried restarting services, and restarting the pi a few times with no luck. Backup created can't be restored for different reason. 

Running the  sudo systemctl status homebridge give below: 

? homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor prese
   Active: active (running) since Wed 2019-08-28 18:06:56 +08; 16min ago
 Main PID: 647 (hoobs-core)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/homebridge.service
           +-647 hoobs-core

Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Server._loadPlatforms (/h
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Server.run (/home/hoobs/.
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at module.exports (/home/hoo
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Object.<anonymous> (/home
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Module._compile (internal
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Object.Module._extensions
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Module.load (internal/mod
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at tryModuleLoad (internal/m
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Function.Module._load (in
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] [8/28/2019, 6:07:19 PM] Got
lines 1-18/18 (END)...skipping...
? homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-08-28 18:06:56 +08; 16min ago
 Main PID: 647 (hoobs-core)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/homebridge.service
           +-647 hoobs-core

Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:286:47)
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:76:14)
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:73:12)
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Aug 28 18:07:19 hoobs homebridge[647]: [Homebridge] [8/28/2019, 6:07:19 PM] Got SIGTERM, shutting down service...

**Comment by mkellsy** [comment]
This is now old. Early beta. no response.
