### ISSUE TITLE
Show weather location

### ISSUE THREAD

**Issue by WHNiii385** [hoobs-org/HOOBS#750]
**Description**

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Ring
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Weather shown in Dashboard is not correct.  How do I know where it is from?

**Comment by askovi** [comment]
Go To settings -> Interface Settings then enter your Postal Code in the Postal Code input box. If that's not accurate, you can enter your latitude and longitude in the appropriate input boxes under postal code.

**Comment by WHNiii385** [comment]
Both of those have been done before I asked for help.

**Comment by WHNiii385** [comment]
I expected more from this forum than RTFM!

**Comment by askovi** [comment]
The weather data is pulled from the openweathermap api. Can you please verify if it's reporting accurate data for your location? https://openweathermap.org/

**Comment by WHNiii385** [comment]
Sorry the hurricane has hijacked my attention.

I have opened openweathermap.org and the temperatures on the site are different than the ones on my running hoops.

I have tippled and quadruple checked the location info and it is correct.

**Comment by WHNiii385** [comment]
Openweathermap.org

[Open Weather Site.pdf](https://github.com/hoobs-org/HOOBS/files/5251707/Open.Weather.Site.pdf)

My Hoobs
[My Hoobs Dashboard.pdf](https://github.com/hoobs-org/HOOBS/files/5251708/My.Hoobs.Dashboard.pdf)

As you can see the 2 do not match.

Why?

**Comment by askovi** [comment]
It seems like their API is not returning the same data as published on their website. We will change the service provider in a future update to fix this issue.

**Comment by WHNiii385** [comment]
I am glad that I am not going crazy.  Thank you for your help.
