### ISSUE TITLE
(node:608) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Insteon]. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by fdiovine** [hoobs-org/HOOBS#752]
**Description**
I am getting a similar error for my Insteon stuff .

**Version**
 3.2.6.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Camera FFMPEG 2.4.4
Kunalight - 1.0.2
Nest - 4.4.6
Platform Insteonlocal - 0.4.13
Platform Orbit - 1.4.3
Ring - 9.7.3
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYDL3P",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "08753",
        "latitude": "39.9537° N",
        "longitude": "74.1979° W"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "38:BC:F1:43:20:92"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Kuna",
            "plugin_map": {
                "plugin_name": "homebridge-kunalight",
                "index": 0
            },
            "name": "Kuna Light",
            "polling": 15,
            "proxyThumbnail": true,
            "proxyPort": 2999,
            "email": "Remove ",
            "password": "remove",
            "serial": "OOKNBL014321701739"
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTcwODMyMzIsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6MTA5NzgwOSwicm5kIjoiZWZPd1lUUU9TUTlTd0EiLCJzZXNzaW9uX2lkIjoiNGRmZTU2YTItZGNlNy00ODcyLTk2NmMtMzY3MGZjMDMwN2NjIiwidHlwZSI6InJlZnJlc2gtdG9rZW4ifQ.soFNmdaqVblpyz3BsNnmyHLS4cpCCcGYV4rYJ-kfALbCnmWpfYkSXWlBvhKkD1I4IK10ra1M_p401Ck55NU4Aw"
        },
        {
            "platform": "orbit",
            "name": "orbit",
            "email": "remove",
            "password": "remove",
            "plugin_map": {
                "plugin_name": "homebridge-platform-orbit"
            }
        },
        {
            "platform": "InsteonLocal",
            "name": "Insteon Local Platform",
            "user": "remove",
            "pass": "remove",
            "host": "10.0.0.50",
            "port": "25105",
            "model": "2245",
            "refresh": "0",
            "server_port": "3000",
            "keepAlive": "3600",
            "devices": [
                {
                    "name": "Backyard Spot",
                    "deviceID": "28.B9.CD",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Family Room Light",
                    "deviceID": "24.E6.4F",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Foyer Light",
                    "deviceID": "25.77.18",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Kitchen Light",
                    "deviceID": "24.E7.38",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Up Stairs Hall",
                    "deviceID": "4B.87.35",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Garage Main Light",
                    "deviceID": "3E.31.A0",
                    "deviceType": "switch"
                },
                {
                    "name": "Basement Main",
                    "deviceID": "40.6C.66",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Basement",
                    "deviceID": "29.5B.B0",
                    "deviceType": "switch"
                },
                {
                    "name": "Media Room Plugin",
                    "deviceID": "22.C8.05",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Basement Media Room",
                    "deviceID": "40.AF.C8",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Media Room Rope Light",
                    "deviceID": "40.9F.F1",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Basement Pantry",
                    "deviceID": "40.A0.AD",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Basement Play Area",
                    "deviceID": "40.60.AE",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Curio Cabinet",
                    "deviceID": "36.46.60",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Front Door Light",
                    "deviceID": "28.8D.16",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Landscape Light",
                    "deviceID": "28.76.3E",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Garage Single",
                    "deviceID": "29.67.DE",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Master Bedroom",
                    "deviceID": "28.B7.8E",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Living Room Top Outlet",
                    "deviceID": "41.8D.89",
                    "dimmable": "no",
                    "deviceType": "outlet",
                    "position": "top"
                },
                {
                    "name": "Living Room Bottom Outlet",
                    "deviceID": "41.8D.89",
                    "dimmable": "no",
                    "deviceType": "outlet",
                    "position": "bottom"
                },
                {
                    "name": "Family Room Top Outlet",
                    "deviceID": "41.8D.E5",
                    "dimmable": "no",
                    "deviceType": "outlet",
                    "position": "top"
                },
                {
                    "name": "Family Room Bottom Outlet",
                    "deviceID": "41.8D.E5",
                    "dimmable": "no",
                    "deviceType": "outlet",
                    "position": "bottom"
                },
                {
                    "name": "Foyer Top Outlet",
                    "deviceID": "41.8D.6B",
                    "dimmable": "no",
                    "deviceType": "outlet",
                    "position": "top"
                },
                {
                    "name": "Foyer Bottom Outlet",
                    "deviceID": "41.8D.6B",
                    "dimmable": "no",
                    "deviceType": "outlet",
                    "position": "bottom"
                },
                {
                    "name": "Main Bathroom Leak Sensor",
                    "deviceID": "4C.AA.3E",
                    "dimmable": "no",
                    "deviceType": "leaksensor"
                },
                {
                    "name": "Basement Bathroom Leak Sensor",
                    "deviceID": "4C.AF.C1",
                    "dimmable": "no",
                    "deviceType": "leaksensor"
                },
                {
                    "name": "Girls Bathroom Leak Sensor",
                    "deviceID": "4C.AB.1F",
                    "dimmable": "no",
                    "deviceType": "leaksensor"
                },
                {
                    "name": "Theater Room Leak Sensor",
                    "deviceID": "28.4F.E3",
                    "dimmable": "no",
                    "deviceType": "leaksensor"
                },
                {
                    "name": "Water Filter Leak Sensor",
                    "deviceID": "37.7A.0E",
                    "dimmable": "no",
                    "deviceType": "leaksensor"
                },
                {
                    "name": "Water Heater Leak Sensor",
                    "deviceID": "37.D1.6B",
                    "dimmable": "no",
                    "deviceType": "leaksensor"
                },
                {
                    "name": "Master Bath Leak Sensor",
                    "deviceID": "4C.AB.C4",
                    "dimmable": "no",
                    "deviceType": "leaksensor"
                },
                {
                    "name": "Palm Tree Plugin",
                    "deviceID": "28.1D.81",
                    "dimmable": "no",
                    "deviceType": "switch"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-platform-insteonlocal"
            }
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest",
            "access_token": "b.248736.cUDb9NO8dM6rdB6CYsu21GZyrPSksfrhXx80oP5gQGQZ7t4QYVvC34ozbvdI6FUFAZSBbTQKhbxKrRrYOEKXEgCzgGXjkqn3EKmajSErsk23Tdxb0ltCcxAy3pUQeooHmL7RfrJ6BCwrKJbb_1589067807713"
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "cameras": [
                {
                    "name": "Back Door Camera",
                    "videoConfig": {
                        "source": "-i http://127.0.0.1:2999/OOKNBL014321701739",
                        "stillImageSource": "-i http://127.0.0.1:2999/OOKNBL014321701739",
                        "maxStreams": 1,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10
                    }
                }
            ],
            "name": "Back Door Camera"
        }
    ]
}* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
8/10/2020, 2:33:24 PM HOOBS listening on port 8080.
8/10/2020, 2:33:27 PM Loaded plugin "homebridge-camera-ffmpeg".
8/10/2020, 2:33:28 PM Loaded plugin "homebridge-kunalight".
8/10/2020, 2:33:29 PM Loaded plugin "homebridge-nest".
8/10/2020, 2:33:29 PM Loaded plugin "homebridge-platform-insteonlocal".
8/10/2020, 2:33:29 PM homebridge API version: 2.5
8/10/2020, 2:33:29 PM Loaded plugin "homebridge-platform-orbit".
8/10/2020, 2:33:31 PM Loaded plugin "homebridge-ring".
8/10/2020, 2:33:31 PM [orbit] Starting OrbitPlatform using homebridge API 2.5
8/10/2020, 2:33:31 PM Initializing Insteon UI
8/10/2020, 2:33:31 PM Reading config from /home/hoobs/.hoobs/etc/config.json
8/10/2020, 2:33:31 PM Found 5 platform(s) in config
8/10/2020, 2:33:31 PM Creating new insteon.json
8/10/2020, 2:33:31 PM No devices in config
8/10/2020, 2:33:31 PM [Insteon Local Platform] Started connection watcher...
8/10/2020, 2:33:31 PM [Insteon Local Platform] Found 32 devices in config
8/10/2020, 2:33:31 PM [Insteon Local Platform] Initializing platform accessory "Backyard Spot"...
8/10/2020, 2:33:31 PM [Insteon Local Platform] Initializing platform accessory "Family Room Light"...
8/10/2020, 2:33:31 PM [Insteon Local Platform] Initializing platform accessory "Foyer Light"...
8/10/2020, 2:33:31 PM [Insteon Local Platform] Initializing platform accessory "Kitchen Light"...
8/10/2020, 2:33:31 PM [Insteon Local Platform] Initializing platform accessory "Up Stairs Hall"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Garage Main Light"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Basement Main"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Basement"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Media Room Plugin"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Basement Media Room"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Media Room Rope Light"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Basement Pantry"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Basement Play Area"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Curio Cabinet"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Front Door Light"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Landscape Light"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Garage Single"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Master Bedroom"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Living Room Top Outlet"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Living Room Bottom Outlet"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Family Room Top Outlet"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Family Room Bottom Outlet"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Foyer Top Outlet"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Foyer Bottom Outlet"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Main Bathroom Leak Sensor"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Basement Bathroom Leak Sensor"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Girls Bathroom Leak Sensor"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Theater Room Leak Sensor"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Water Filter Leak Sensor"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Water Heater Leak Sensor"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Master Bath Leak Sensor"...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Initializing platform accessory "Palm Tree Plugin"...
8/10/2020, 2:33:32 PM [Nest] Fetching Nest devices.
8/10/2020, 2:33:32 PM [Kuna Light] Creating polling timer for every 15 minutes
8/10/2020, 2:33:32 PM [Kuna Light] Getting Authentication Token...
8/10/2020, 2:33:32 PM [orbit] Remembered accessory, configuring handlers Home Smart Outdoor Timer
8/10/2020, 2:33:32 PM [Ring] Configuring cached accessory 9ad146cd-507c-45bd-994f-96bf9fd5ed51 Front Door
8/10/2020, 2:33:32 PM [Ring] Configuring cached accessory bece78ff-6743-4479-af90-5396b43cd1a8 Backyard
8/10/2020, 2:33:32 PM [Ring] Configuring cached accessory 3e339975-9714-4b0c-b0dd-4c8742f74f2a Mom’s Front Door
8/10/2020, 2:33:32 PM [Ring] Configuring cached accessory ced9434d-b858-4ac6-b042-60b040c2ceb5 Upstairs
8/10/2020, 2:33:32 PM [Ring] Configuring cached accessory 7a1034f4-7189-4348-bfd6-b5b7db3e4ab5 Downstairs
8/10/2020, 2:33:32 PM [Back Door Camera] [Back Door Camera] Configuring cached bridged accessory...
8/10/2020, 2:33:32 PM (node:608) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Insteon]. Use emitter.setMaxListeners() to increase limit
8/10/2020, 2:33:32 PM [Insteon Local Platform] Connected to Insteon Model 2245 Hub...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Backyard Spot
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Family Room Light
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Foyer Light
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Kitchen Light
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Up Stairs Hall
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Garage Main Light
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Basement Main
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Basement
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Media Room Plugin
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Basement Media Room
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Media Room Rope Light
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Basement Pantry
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Basement Play Area
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Curio Cabinet
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Front Door Light
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Landscape Light
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Garage Single
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Master Bedroom
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting power state for Living Room Top Outlet
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting power state for Living Room Bottom Outlet
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting power state for Family Room Top Outlet
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting power state for Family Room Bottom Outlet
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting power state for Foyer Top Outlet
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting power state for Foyer Bottom Outlet
8/10/2020, 2:33:32 PM [Insteon Local Platform] Getting status for Palm Tree Plugin
8/10/2020, 2:33:32 PM [Insteon Local Platform] Insteon event listener started...
8/10/2020, 2:33:32 PM [Insteon Local Platform] Started Insteon Express server...
8/10/2020, 2:33:32 PM [Kuna Light] Proxying Thumbnail Enabled Use URL: http://127.0.0.1:2999/OOKNBL014321701739
8/10/2020, 2:33:32 PM [Kuna Light] Getting current state...
8/10/2020, 2:33:33 PM [Kuna Light] Light is currently OFF
8/10/2020, 2:33:33 PM [Ring] Configuring 2 cameras and 4 devices for location "Toms River" - locationId: dr5781-11g2h-0
8/10/2020, 2:33:33 PM [Ring] Configuring 1 cameras and 1 devices for location "Medford" - locationId: 6fd9992b-5be5-4e36-8d36-0e6b65530205
8/10/2020, 2:33:35 PM [Nest] initing thermostat "Hall Thermostat": deviceId: 02AA01AB43120P0P structureId: 6d7abeb0-6d9d-11e2-ad36-12313928ac9f
8/10/2020, 2:33:35 PM [Nest] initing home_away_sensor "Home Occupied": deviceId: 6d7abeb0-6d9d-11e2-ad36-12313928ac9f structureId: 6d7abeb0-6d9d-11e2-ad36-12313928ac9f
8/10/2020, 2:33:35 PM [Nest] Initializing platform accessory "Hall Thermostat"...
8/10/2020, 2:33:35 PM [Nest] Initializing platform accessory "Home Occupied"...
8/10/2020, 2:33:35 PM Bridge is running on port 51826.
8/10/2020, 2:33:39 PM [Insteon Local Platform] Got updated status for Kitchen Light
8/10/2020, 2:33:48 PM [Ring] Front Door Detected Motion. Loading snapshot before sending event to HomeKit
8/10/2020, 2:34:54 PM [Ring] Front Door Detected Motion. Loading snapshot before sending event to HomeKit
8/10/2020, 2:38:02 PM [Kuna Light] Getting current state...
8/10/2020, 2:38:02 PM [Kuna Light] Light is currently OFF
8/10/2020, 2:38:13 PM [Kuna Light] Getting current state...
8/10/2020, 2:38:14 PM [Kuna Light] Light is currently OFF
8/10/2020, 2:43:50 PM [Kuna Light] Getting current state...
8/10/2020, 2:43:50 PM [Kuna Light] Light is currently OFF
8/10/2020, 2:44:27 PM [Kuna Light] Getting current state...
8/10/2020, 2:44:27 PM [Kuna Light] Light is currently OFF
8/10/2020, 2:44:30 PM [Kuna Light] Getting current state...
8/10/2020, 2:44:31 PM [Kuna Light] Light is currently OFF
8/10/2020, 2:44:43 PM [Kuna Light] Getting current state...
8/10/2020, 2:44:44 PM [Kuna Light] Light is currently OFF
8/10/2020, 2:45:02 PM [Kuna Light] Getting current state...
8/10/2020, 2:45:02 PM [Kuna Light] Light is currently OFF
8/10/2020, 2:47:10 PM [Insteon Local Platform] Got updated status for Family Room Top Outlet
8/10/2020, 2:47:10 PM [Insteon Local Platform] Getting power state for Family Room Top Outlet
8/10/2020, 2:47:10 PM [Insteon Local Platform] Got updated status for Family Room Bottom Outlet
8/10/2020, 2:47:10 PM [Insteon Local Platform] Getting power state for Family Room Bottom Outlet
8/10/2020, 2:47:12 PM [Insteon Local Platform] Got updated status for Foyer Top Outlet
8/10/2020, 2:47:12 PM [Insteon Local Platform] Getting power state for Foyer Top Outlet
8/10/2020, 2:47:12 PM [Insteon Local Platform] Got updated status for Foyer Bottom Outlet
8/10/2020, 2:47:12 PM [Insteon Local Platform] Getting power state for Foyer Bottom Outlet
8/10/2020, 2:47:18 PM [Insteon Local Platform] Got updated status for Kitchen Light
8/10/2020, 2:48:40 PM [Kuna Light] Getting current state...
8/10/2020, 2:48:41 PM [Kuna Light] Light is currently OFF
```
POST LOG HERE
```

**Additional context**
My Hoobs will just shut down for no reason....

**Comment by askovi** [comment]
What node version are you running? Run `node -v` in the terminal to get it.

**Comment by JohnBarger** [comment]
+1  I've been having the same problem since May.

**Comment by fdiovine** [comment]
OK this is going to sound weird, I went through some things last night and the error has stopped and Hoobs has been running for 12 hours straight.  only thing I am now getting is - HAP Warning: Characteristic 00000008-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.

**Comment by fdiovine** [comment]
> What node version are you running? Run `node -v` in the terminal to get it.
Node v - v12.16.2. everything was fine for over 12 hours and now shut down again and got that error again......

**Comment by JohnBarger** [comment]
Back in May, Michael Kellsy said this would be fixed in 3.2.7.  There have been no updates since then.

**Comment by JohnBarger** [comment]
Bump for update.

**Comment by BobbySlope** [comment]
dublicate of #751 

Will be solved in next version

**Comment by JohnBarger** [comment]
Do we know when that update is coming?  A fix was promised in the the next version 3.2.7 over 3 months ago.

**Comment by BobbySlope** [comment]
We are still working on it, no ETA atm

**Comment by JohnBarger** [comment]
Tapping to keep thread alive.

**Comment by JohnBarger** [comment]
Just updated to 3.2.7.  Same problem.  

(node:1456) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpaired listeners added to [Bridge]. Use emitter.setMaxListeners() to increase limit

This has been going on for a ludicrous amount of time.  When can we expect a fix?  Can we get safe instructions for increasing  emitter.setMaxListeners() manually?

**Comment by JohnBarger** [comment]
Same problem on 3.2.8

**Comment by mariusstrom** [comment]
Running into this similarly on HOOBS 3.2.8. Not using insteon plugin but am using deconz/hue, nest, xiaomi roborock, keylights, and purpleair.
