### ISSUE TITLE
HOOBS Core update issue

### ISSUE THREAD

**Issue by bikerboy-86** [hoobs-org/HOOBS#753]
HOOBS Core
Current Version: 3.1.20
3.2.6 Update Available

I click on update then something happens for a few minutes, but after that the new version is not installed
in the log fiele i can see nothing what was done

**Comment by askovi** [comment]
Please login via ssh with user: `hoobs` and password: `hoobsadmin`
Then run this command to update:

`sudo npm install -g --unsafe-perm @hoobs/hoobs`

**Comment by bikerboy-86** [comment]
Thank you it runs
