### ISSUE TITLE
Hoobs Stuck Yellow Screen

### ISSUE THREAD

**Issue by slimtedi23** [hoobs-org/HOOBS#756]
im stuck in this yellow page can someone help i just updated to latest version it was fine reboot and this happened

![Capture](https://user-images.githubusercontent.com/8677830/90215392-79367b00-ddc9-11ea-8009-0874cdd64bc8.PNG)

**Comment by slimtedi23** [comment]
just in case pi 3b sorry i didnt put this info

**Comment by BobbySlope** [comment]
See here:
https://support.hoobs.org/docs/5ea6a66f0ab68b0344e872e7

**Comment by slimtedi23** [comment]
still same thing thanks for the help 


Node Version 12.16.2
Updating Repositories
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u1).
git is already the newest version (1:2.20.1-2+deb10u3).
tar is already the newest version (1.30+dfsg-6).
0 upgraded, 0 newly installed, 0 to remove and 159 not upgraded.

Restarting HOOBS
================================================================================
Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 80
}
[HOOBS] Stopping server.

**Comment by BobbySlope** [comment]
please reboot

**Comment by slimtedi23** [comment]
I did and same thing. I’m at work now but any other help will be appreciated.

**Comment by askovi** [comment]
Are you running anything else on the Pi that uses port 80?
Try changing the server port in the config.json file using the ssh terminal from 80 to 8080. 
Then access it like this: http://hoobs.local:8080

**Comment by slimtedi23** [comment]
Thanks for the help I got it working I just started fresh
