### ISSUE TITLE
Homebridge Tuya Web not working

### ISSUE THREAD

**Issue by motogon** [hoobs-org/HOOBS#758]
**Description**

Homebridge plugin for Tuya devices using a cloud Tuya Web Api.

This Homebridge plugin is based on the Home Assistent Tuya integration that implements a special Tuya Home Assistant API.

**Expected behavoir**

This Homebridge Plugin implements the following features:

    Controlling Tuya WiFi enabled devices form within HomeKit enabled iOS Apps.
    Uses simple and lightweight Cloud Web API to control and get state update from Tuya devices. You will need a stable internet connection to control the devices.
    Device State Caching. State of devices is cached in memory, every time a HomeKit app request status updates from the devices this results in a very fast and responsive response. There can be a latency in updates when a device is controlled form an App/Hub/Controller other than HomeKit, e.g. from the Tuya Android/iOS App.

**Plugin name**
Homebridge Tuya Web 

https://plugins.hoobs.org/plugin/@milo526/homebridge-tuya-web

**Please report the issue to the plugin developer**

https://github.com/milo526/homebridge-tuya-web/issues/49#issuecomment-672942131

**Version**
0.4.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
0.3.3

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

dockers version HOOBS 3 | 3.2.6
-- | --

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**

Distro | Alpine Linux

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

{
    "server": {
        "port": 8888,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://xxxxx",
        "polling_seconds": 5,
        "docker": true
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "ru",
        "temp_units": "celsius",
        "country_code": "RU",
        "postal_code": "111555",
        "latitude": "55.761062",
        "longitude": "37.828802"
    },
    "bridge": {
        "name": "Lupanovo",
        "port": 51826,
        "pin": "xxxxx",
        "username": "xxxxx"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Plex",
            "name": "Plex",
            "plex_token": "xxxxxx",
            "host": "192.168.1.108",
            "filter": [
                {
                    "user": "xxxx",
                    "player": "DPC (base3d)"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-plex-v2",
                "index": 0
            }
        },
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "homebridge-xiaomi-roborock-vacuum",
                "index": 0
            },
            "name": "Xiaomi Mi Robot Vaccum 1st Generation",
            "waterBox": false,
            "pause": false,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": true,
            "delay": false,
            "cleanword": "cleaning",
            "autoroom": true,
            "ip": "192.168.1.144",
            "token": "xxxxxxxxxx"
        },
        {
            "accessory": "UniFi Occupancy Sensor",
            "plugin_map": {
                "plugin_name": "homebridge-unifi-occupancy-sensor",
                "index": 0
            },
            "name": "Я в Лупаново",
            "mode": "all",
            "interval": 1800,
            "unifi": {
                "site": "default",
                "controller": "https://172.17.0.3:8443",
                "username": "xxxxx",
                "password": "xxxxxx"
            },
            "monitor": [
                {
                    "device": "xxxxxx"
                },
                {
                    "device": "xxxxx"
                }
            ]
        },
        {
            "accessory": "Plex",
            "name": "Plex кабинет",
            "plex_token": "xxxxxxx",
            "host": "192.168.1.108",
            "filter": [
                {
                    "user": "xxxxxx",
                    "player": "Chrome"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-plex-v2",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "eWeLink",
            "plugin_map": {
                "plugin_name": "homebridge-ewelink-sonoff"
            },
            "name": "eWeLink",
            "mode": "ws",
            "debug": false,
            "debugReqRes": false,
            "sensorTimeLength": "2",
            "sensorTimeDifference": "120",
            "username": "xxxxxxx",
            "countryCode": 7,
            "password": "xxxxxx"
        },
        {
            "name": "mqtt",
            "url": "mqtt://192.168.1.74",
            "port": "1883",
            "platform": "mqtt",
            "plugin_map": {
                "plugin_name": "homebridge-mqtt"
            }
        },
        {
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "@milo526/homebridge-tuya-web"
            },
            "name": "TuyaWebPlatform",
            "scenes": false,
            "options": {
                "platform": "tuya",
                "username": "xxxxx",
                "password": "xxxxxx",
                "countryCode": "+7",
                "pollingInterval": 5
            },
            "defaults": [],
            "scenesWhitelist": []
        }
    ]
}

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```
14.08.2020, 15:14:01 Loaded plugin "homebridge-mqtt".14.08.2020, 15:14:01 homebridge API version: 2.514.08.2020, 15:14:01 Loaded plugin "homebridge-plex-v2".14.08.2020, 15:14:01 Loaded plugin "homebridge-unifi-occupancy-sensor".14.08.2020, 15:14:02 Loaded plugin "homebridge-xiaomi-roborock-vacuum".14.08.2020, 15:14:02 Loaded plugin "homebridge-tuya-web".14.08.2020, 15:14:02 [mqtt] homebridge-mqtt v0.6.214.08.2020, 15:14:02 The requested platform "TuyaWebPlatform" was not registered by any plugin.14.08.2020, 15:14:02 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.14.08.2020, 15:14:02 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.14.08.2020, 15:14:02 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.14.08.2020, 15:14:02 [eWeLink] Plugin has finished initialising. Starting synchronisation with eWeLink account.14.08.2020, 15:14:02 [mqtt] Number of cached Accessories: 314.08.2020, 15:14:02 [mqtt] clientId = homebridge-mqtt_29ec84f514.08.2020, 15:14:02 [mqtt] Connecting..14.08.2020, 15:14:02 Bridge is running on port 51826.14.08.2020, 15:14:03 [mqtt] connected (url = mqtt://192.168.1.74)14.08.2020, 15:14:03 [Я в Лупаново] UniFi Events: Connected (1) - wss://172.17.0.3:8443/wss/s/default/events14.08.2020, 15:14:03 [Я в Лупаново] 2 monitored device(s) found. Accessory is in mode "all" and all watched devices are connected so triggering occupancy.14.08.2020, 15:14:05 Catching error on address already in use: {"errno":"EADDRINUSE","code":"EADDRINUSE","syscall":"addMembership"}14.08.2020, 15:14:08 [eWeLink] [1] eWeLink devices were loaded from the Homebridge cache.14.08.2020, 15:14:08 [eWeLink] [1] primary devices were loaded from your eWeLink account.14.08.2020, 15:14:08 [eWeLink] [1] primary devices were discovered on your local network.14.08.2020, 15:14:08 [eWeLink] [Спальня с балконом] found in eWeLink but LAN mode unavailable as unsupported.14.08.2020, 15:14:08 [eWeLink] Synchronisation complete. Ready to go!14.08.2020, 15:14:13 [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | Connected to: 192.168.1.14414.08.2020, 15:14:13 [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | Model: rockrobo.vacuum.v114.08.2020, 15:14:13 [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | State: charging14.08.2020, 15:14:13 [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | FanSpeed: 10014.08.2020, 15:14:13 [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | BatteryLevel: 10014.08.2020, 15:14:13 [Xiaomi Mi Robot Vaccum 1st Generation] INF getRoomMap | rockrobo.vacuum.v1 | Map is unknown_method14.08.2020, 15:14:13

**Additional context**

TuyaWebPlatform" was not registered by any plugin.
Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.

**Comment by SpcFilho** [comment]
Same problem here. Thanks for reporting.

**Comment by BobbySlope** [comment]
"plugin_name": "@milo526/homebridge-tuya-web"

add this here:
...
],
"plugin_map": {
"plugin_name": "homebridge-plex-v2",
**"plugin_name": "@milo526/homebridge-tuya-web",**
"index": 0
}
...

and delete it here:
...
{
"platform": "TuyaWebPlatform",
**"plugin_map": {
"plugin_name": "@milo526/homebridge-tuya-web"
},**
"name": "TuyaWebPlatform",
"scenes": false,
....

The plugin writes the pluginmap in the wrong place

**Comment by motogon** [comment]
@BobbySlope Fixed config

But the problem remained


Log :
 
14.08.2020, 15:32:24 Got SIGINT, shutting down Bridge...14.08.2020, 15:32:29 Loaded plugin "homebridge-ewelink-sonoff".14.08.2020, 15:32:30 Loaded plugin "homebridge-mqtt".14.08.2020, 15:32:30 homebridge API version: 2.514.08.2020, 15:32:31 Loaded plugin "homebridge-plex-v2".14.08.2020, 15:32:31 Loaded plugin "homebridge-unifi-occupancy-sensor".14.08.2020, 15:32:32 Loaded plugin "homebridge-xiaomi-roborock-vacuum".14.08.2020, 15:32:32 Loaded plugin "homebridge-tuya-web".14.08.2020, 15:32:32 [mqtt] homebridge-mqtt v0.6.214.08.2020, 15:32:32 The requested platform "TuyaWebPlatform" was not registered by any plugin.14.08.2020, 15:32:32 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.14.08.2020, 15:32:32 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.14.08.2020, 15:32:32 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.14.08.2020, 15:32:33 [eWeLink] Plugin has finished initialising. Starting synchronisation with eWeLink account.14.08.2020, 15:32:33 [mqtt] Number of cached Accessories: 314.08.2020, 15:32:33 [mqtt] clientId = homebridge-mqtt_cb28158514.08.2020, 15:32:33 [mqtt] Connecting..14.08.2020, 15:32:33 Bridge is running on port 51826.14.08.2020, 15:32:33 [mqtt] connected (url = mqtt://192.168.1.74)14.08.2020, 15:32:33 [Я в Лупаново] UniFi Events: Connected (1) - wss://172.17.0.3:8443/wss/s/default/events14.08.2020, 15:32:34 [Я в Лупаново] 2 monitored device(s) found. Accessory is in mode "all" and all watched devices are connected so triggering occupancy.14.08.2020, 15:32:35 Catching error on address already in use: {"errno":"EADDRINUSE","code":"EADDRINUSE","syscall":"addMembership"}14.08.2020, 15:32:38 [eWeLink] [1] eWeLink devices were loaded from the Homebridge cache.14.08.2020, 15:32:38 [eWeLink] [1] primary devices were loaded from your eWeLink account.14.08.2020, 15:32:38 [eWeLink] [1] primary devices were discovered on your local network.

ps 

After saving the config

in section

],
'plugin_map': {
'plugin_name': 'homebridge-plex-v2',
'plugin_name': '
 milo526 / homebridge-tuya-web',
'index': 0
}

only one entry remains

or 'plugin_name': 'homebridge-plex-v2',
or 'plugin_name': 'milo526 / homebridge-tuya-web',

**Comment by BobbySlope** [comment]
],
'plugin_map': {
'plugin_name': 'homebridge-plex-v2',
'@milo526/homebridge-tuya-web',
'index': 0
}

**Comment by BobbySlope** [comment]
go to terminal and enter nano config.json

add this line here:
<<Last entry>>**,**
"@milo526/homebridge-tuya-web"

<img width="331" alt="Screenshot 2020-08-14 at 14 55 44" src="https://user-images.githubusercontent.com/50763727/90251605-50040200-de3e-11ea-82a4-4561730b257f.png">

**Comment by BobbySlope** [comment]
<img width="403" alt="Screenshot 2020-08-14 at 14 58 51" src="https://user-images.githubusercontent.com/50763727/90251810-aec97b80-de3e-11ea-80c0-69d6d2449fe0.png">

**Comment by motogon** [comment]
![изображение](https://user-images.githubusercontent.com/12997195/90256712-c3ae0b00-de4e-11ea-9bed-3859c5a936b6.png)

Problem still exists

14.08.2020, 16:49:23 The requested platform "TuyaWebPlatform" was not registered by any plugin.
14.08.2020, 16:49:23 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.

**Comment by motogon** [comment]
![изображение](https://user-images.githubusercontent.com/12997195/90257442-db39c380-de4f-11ea-9c4e-0fd206b573e5.png)

**Comment by motogon** [comment]
14.08.2020, 17:00:17 Got SIGINT, shutting down Bridge...
14.08.2020, 17:00:20 Loaded plugin "homebridge-ewelink-sonoff".
14.08.2020, 17:00:21 Loaded plugin "homebridge-mqtt".
14.08.2020, 17:00:21 homebridge API version: 2.5
14.08.2020, 17:00:21 Loaded plugin "homebridge-plex-v2".
14.08.2020, 17:00:21 Loaded plugin "homebridge-unifi-occupancy-sensor".
14.08.2020, 17:00:22 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
14.08.2020, 17:00:22 [mqtt] homebridge-mqtt v0.6.2
14.08.2020, 17:00:22 The requested platform "TuyaWebPlatform" was not registered by any plugin.
14.08.2020, 17:00:22 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.

**Comment by BobbySlope** [comment]
Try using tuya-lan plugin instead

https://plugins.hoobs.org/plugin/homebridge-tuya-lan

**Comment by BobbySlope** [comment]
https://youtu.be/oq0JL_wicKg

**Comment by SpcFilho** [comment]
> Try using tuya-lan plugin instead
> 
> https://plugins.hoobs.org/plugin/homebridge-tuya-lan

![image](https://user-images.githubusercontent.com/25888298/90275997-8db25c00-de39-11ea-8eda-762b06172320.png)

--------------------

_This package has been deprecated
Author message:

Futher development for this plugin is located at '@milo526/homebridge-tuya-we' please remove 'homebridge-tuya-web' and install '@milo526/homebridge-tuya-web' if you wish to keep using this plugin._

**Comment by milo526** [comment]
Nah they want you to use this plugin: https://www.npmjs.com/package/homebridge-tuya-lan

P.s. if you want to work with the plugin developer to solve these issues hit me up @BobbySlope 🙂

**Comment by BobbySlope** [comment]
ah nice: please send me an email to plugindev@hoobs.org with your email where i can send an invitation to our slack channel

**Comment by askovi** [comment]
This has been fixed by the developer on the new Tuya Web plugin and is awaiting certification. You can install it by accessing this URL: http://hoobs.local/plugin/%40milo526%2Fhomebridge-tuya-web
