### ISSUE TITLE
Add String for translation

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#76]
This file is used for plugin configuration.

**Comment by BobbySlope** [comment]
the preset text in the flied ok plugin settings

**Comment by mkellsy** [comment]
It looks like you didn't upload the file.

**Comment by BobbySlope** [comment]
omg no no only this line
<img width="1194" alt="Screenshot 2019-08-29 at 06 48 36" src="https://user-images.githubusercontent.com/50763727/63911006-25504c00-ca29-11e9-9de7-380b75bbef7f.png">

**Comment by mkellsy** [comment]
Those strings come from the config.json they are not translatable. It is an open text field. https://github.com/nfarina/homebridge/blob/master/config-sample.json

**Comment by mkellsy** [comment]
The way program translation works (i18n) is the code has a language too. It doesn't translate words it looks up pre-translated phrases via a key.

For example
https://github.com/hoobs-org/hoobs-core/blob/master/src/lang/de.json
This is the German file. It is not word by word, it is phrases.

So when a config file is involved the settings are important. I can't set it to a dynamically generated value.
The service description goes from the config file directly into the HAP server.

Language translation is done on the UI lever, where we can do something like this.

```
<span>{{ $t("pre_defined_lang_key") }}</span>
```

The $t() function dynamically translates **pre_defined_lang_key** when the page renders.
