### ISSUE TITLE
HOOBS shows old version of homebridge-myq2 plugin 

### ISSUE THREAD

**Issue by jlg89** [hoobs-org/HOOBS#761]
**Description**
The homebridge-myq2 plugin is currently at 2.1.10 published 4 days ago, but HOOBS plugin search still shows 2.1.9 and the "Update" button does not appear, even after multiple reboots. Both GitHub and NPM show the current version.

**Expected behavoir**
HOOBS should reflect the current release of plugins.

**Plugin name**
https://github.com/hjdhjd/homebridge-myq2

**Please report the issue to the plugin developer**
https://github.com/hjdhjd/homebridge-myq2/issues/103

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**Comment by askovi** [comment]
It has been updated now. Thank you for your feedback.
