### ISSUE TITLE
Pi VPN WITH HOOBS?

### ISSUE THREAD

**Issue by LS73** [hoobs-org/HOOBS#762]
Hi, 

I wanted to ask if I can run Pi VPN on my Hoobs raspberry Pi?
I am new to this ecosystem and am not sure if I can run a different program at the same time on the same machine. 
Pi-hole is running fine, but it came from the Hoobs website.

Regards,
LS73

**Comment by askovi** [comment]
Yes you can run any software you want on your Pi as long as it doesn't use the same ports as HOOBS (by default these are: 80, 8080, 51826)

**Comment by LS73** [comment]
Thank for such a quick reply!
Maybe having Hoobs Pi-VPN like the Pi-hole would be a great possible future addition 😉
