### ISSUE TITLE
Rpi Plugin Not working at all

### ISSUE THREAD

**Issue by piiong** [hoobs-org/HOOBS#763]
**Description**
I cant get the plugin to work. Not at all!

**Expected behavoir**

I just want to see the Temperatur of the pi in Homekit.

**Plugin name**

Rpi
HOOBS Certified
1.1.13 veröffentlicht 8/13/2020 • 4 days ago

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.2.6.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
macOS Catalina 

**Post your config**
I totally don’t know what s right to put in there. Tried a lot !!!

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```

[RPi] error: Cannot add a Service with the same UUID '000000D8-0000-1000-8000-0xxxxxxxx1' and subtype 'undefined TV' as another Service in this Accessory.

```

**Additional context**

**Comment by askovi** [comment]
Works just fine here. This is what you put in the Raspberry Pis config box on the plugin configuration screen:

`[
    {
        "host": "localhost"
    }
]`

Regarding the same UUID issue, try the Reset Connection option from the Help menu then rescan the new QR code from the HOOBS Dashboard using the Home app.

**Comment by piiong** [comment]
Thanks for the response. 👍
I had all this done before. With that configuration. No success. 

But then I start over again (no restart nor restart) the next day and it directly works... The same way.
Strange. Didn’t change anything.
But hey, thanks anyway :)

Chris
