### ISSUE TITLE
Need to update homebridge-chamberlain plugin

### ISSUE THREAD

**Issue by ToddWebDev** [hoobs-org/HOOBS#764]
**Description**
API issues have been resolved in the repo, but HOOBS is serving 1.4.0 published 11/24/2019, it needs to serve the latest 1.6.1

**Expected behavoir**
HOOBS to serve the latest version [1.6.1](https://github.com/iRayanKhan/homebridge-chamberlain/releases/tag/1.6.1) which includes a fix

**Plugin name**
[homebridge-chamberlain](https://github.com/iRayanKhan/homebridge-chamberlain)

**Please report the issue to the plugin developer**
They have already resolved this issue

**Version**
3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
2.1.x
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
```[Garage] Error: invalid response, got HTTP 400: {
    "SecurityToken": "",
    "ReturnCode": "0",
    "ErrorMessage": "please contact customer care, supportID: "16889929860518110581",
    "CorrelationId": ""
}
    at /home/hoobs/.hoobs/node_modules/@hoobs/chamberlain/src/api.js:30:19
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
8/18/2020, 3:35:19 PM
    at /home/hoobs/.hoobs/node_modules/@hoobs/chamberlain/src/api.js:30:19```


**Additional context**
Add any other context about the problem here.

**Comment by askovi** [comment]
You're on the old certified version. Uninstall the plugin first then reinstall from the UI, it will install the right version 1.6.1.
If you're having trouble uninstalling from the UI, run this command in Terminal to remove it:

`sudo rm -fR ~/.hoobs/node_modules/@hoobs/chamberlain`
