### ISSUE TITLE
Dutch translation for "Present" is wrong and translated as "Cadeau"

### ISSUE THREAD

**Issue by johnx1971** [hoobs-org/HOOBS#767]
**Description**
When using the Homebridge-People plugin in HOOBS than the Dutch translation for "Present" is wrong and translated as "Cadeau" which means gift. 

Proper translation for the status AWAY and Present should be.

AWAY - Afwezig
PRESENT - Aanwezig

**Version**
Version 3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] No, new install

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X ] HOOBS SD Card
- [ ] Custom Install

**Comment by whitecat** [comment]
I made a PR: https://github.com/hoobs-org/hoobs-languages/pull/1

**Comment by askovi** [comment]
Hi @whitecat , send us an email at info@hoobs.org, I will invite you to the translation platform. Dutch is only completed at 46% right now. You can look over the current translations and add the rest if you wish. Cheers!

**Comment by BobbySlope** [comment]
Solved in Translation system
