### ISSUE TITLE
Hoobs Desktop- unable to login

### ISSUE THREAD

**Issue by LS73** [hoobs-org/HOOBS#768]
**Description**
I have installed the Hoobs desktop on y Pi.
Every time I enter the default login and password, the screen goes black and returns to a blank login screen.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X] Custom Install

**If this is a custom install, what's your operating system?**
I downloaded the latest image of 3.2.6 from Hoobs.org.
I recently installed Pi-hole and updated/upgraded Raspian.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
Desktoplogin is

User: hoobs
Password: hoobsadmin

**Comment by Cojaeck** [comment]
Hi. I have the same problem. I enter the correct password as mentioned above. But the login screen returns after showing "cannot currently show desktop". I reinstalled the hole pi but get the same problem. I changed the screen-res via raspi-config. But that also did not help. 
(Installed it via the command line described in the knowledgebase article above).

**Comment by jnmmoore** [comment]
Seeing the same issue. Installed the Hoops image on my Pi and wanted to use the touchscreen to show the dashboard but I can't get past the debian login page. Has anyone resolved this?
<img width="804" alt="Screenshot 2022-01-19 at 13 19 05" src="https://user-images.githubusercontent.com/83212730/150138708-d86f6fa4-754c-4930-9895-eb3dd777c112.png">
