### ISSUE TITLE
homebridge-xiaomi-fan "no answer"

### ISSUE THREAD

**Issue by TheBassfly** [hoobs-org/HOOBS#770]
I just started to use the Plugin with my SmartMi Fan 2. For now, it looks like, the Plugin is working fine, but Hoods seems t interfere with the Plugin, because in HomeKit the Fan is visible with "No Answer"

**Plugin name**
homebridge-xiaomi-fan

**Please report the issue to the plugin developer**
The Developer is also informed, but says, that his plugin is working fine, based on the debug output.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X] HOOBS SD Card
- [ ] Custom Install

**Post your config**
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "-",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "orient-red",
        "locale": "-",
        "temp_units": "-",
        "country_code": "-",
        "postal_code": "-",
        "longitude": "-",
        "latitude": "-"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "-",
        "port": 51827,
        "pin": "-"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [
        {
            "accessory": "Weather",
            "apikey": "-",
            "location": "-",
            "name": "OpenWeatherMap Temperature",
            "plugin_map": {
                "plugin_name": "homebridge-weather",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "TVSwitch",
            "disableSensor": true,
            "delay": 25000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "AppleSwitch",
            "disableSensor": true,
            "delay": 25000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            }
        },
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "homebridge-xiaomi-roborock-vacuum",
                "index": 0
            },
            "name": "Roborock S50",
            "waterBox": false,
            "pause": false,
            "dock": true,
            "delay": false,
            "cleanword": "Reinigung",
            "autoroom": false,
            "rooms": [
                {
                    "id": 16,
                    "name": "Gäste-WC"
                },
                {
                    "id": 17,
                    "name": "Esszimmer"
                },
                {
                    "id": 18,
                    "name": "Flur"
                },
                {
                    "id": 19,
                    "name": "Wohnzimmer"
                },
                {
                    "id": 20,
                    "name": "Küche"
                },
                {
                    "id": 21,
                    "name": "Büro"
                },
                {
                    "id": 22,
                    "name": "Eingang"
                },
                {
                    "id": 23,
                    "name": "Hauswirtschaftsraum"
                }
            ],
            "ip": "192.168.2.21",
            "token": "-"
        }
    ],
    "platforms": [
        {
            "name": "Hue",
            "forceCt": true,
            "groups": false,
            "hosts": [
                "192.168.2.7"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "rooms": false,
            "platform": "Hue",
            "users": {
                -
            "wallSwitch": true,
            "anyOn": true,
            "plugin_map": {
                "plugin_name": "hue"
            },
            "hueDimmerRepeat": true,
            "scenes": true
        },
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "HarmonyHub",
            "hubIP": "192.168.2.15",
            "switchAccessories": true,
            "TVAccessory": false,
            "publishAllTVAsExternalAccessory": false,
            "cleanCache": false
        },
        {
            "platform": "FRITZ!Box",
            "name": "My FRITZ!Box",
            "username": "-",
            "password": "-",
            "url": "http://fritz.box",
            "interval": 600,
            "concurrent": true,
            "devices": {
                "wifi": {
                    "name": "Guest WLAN",
                    "display": true
                }
            },
            "plugin_map": {
                "plugin_name": "homebridge-fritz"
            }
        },
        {
            "platform": "xiaomifan",
            "devices": [
                {
                    "name": "Xiaomi Fan 2",
                    "ip": "192.168.2.17",
                    "token": "-",
                    "pollingInterval": 10,
                    "moveControl": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "naturalModeButton": true,
                    "shutdownTimer": false,
                    "angleButtons": [
                        30,
                        60,
                        90,
                        120
                    ]
                }
            ]
        }
    ]
}

**Comment by TheBassfly** [comment]
Small update:
I tried the workaround mentioned here:

https://github.com/hoobs-org/HOOBS/issues/704#issuecomment-661619584

So in root mode the fan worked in Homekit. But the switch back to my normal hoobs doesn't  work. Homekit is working but the Gui-Page is not reachable anymore.

**Comment by TheBassfly** [comment]
Maybe you can help me out with this, because the developer of the plug in only says, that's my personal problem because others have no issues with this plug-in an hoobs.

**Comment by TheBassfly** [comment]
Or do I have to use the root instance of hoobs permanently?

**Comment by TheBassfly** [comment]
No clue?

**Comment by hfanieng** [comment]
I still have the same problem with Hoobs:

`25.8.2020, 12:42:19 [xiaomifan] Init - initializing devices
25.8.2020, 12:42:19 [xiaomifan] Init - initializing device with name: Ventilator
25.8.2020, 12:42:19 Ventilator is running on port 59158.
25.8.2020, 12:28:05 [xiaomifan] [Ventilator] Connected to Fan zhimi.fan.za4
25.8.2020, 12:28:07 [xiaomifan] [Ventilator] Fan total use time: 1395 minutes.
`

I tried also a clean installation of Hoobs and starts it as root, but I can't get the plugin to work as expected

**Comment by TheBassfly** [comment]
With the workaround above the Fan Plugin worked for me, but I still don't know how I can use this information now in the standard hoobs instance. Or do I have to move everything to a Root instance? This would cost me a lot of work then.

**Comment by TheBassfly** [comment]
> Please post your logs

Nothing new here?
Or do you ignore this issue?

**Comment by askovi** [comment]
I don't have this accessory so I cannot test the plugin myself. Your logs are not showing any issue. I looked more into the plugin issues and i noticed you said here you got it working? https://github.com/merdok/homebridge-xiaomi-fan/issues/46
If you did please close this issue.

**Comment by TheBassfly** [comment]
Yes

In the meantime it is working.

Thanks.
