### ISSUE TITLE
Hoobs.local unreachable

### ISSUE THREAD

**Issue by TheBassfly** [hoobs-org/HOOBS#773]
After trying  this workaround for the Xiaomi fan plugin, I can't reach the Gui anymore.

https://github.com/hoobs-org/HOOBS/issues/704

Any help apreciated.

**Comment by askovi** [comment]
Try with http://hoobs.local:8080 or find the local ip address given to HOOBS by you router and access it like this: http://192.168.x.x

If none of the above work, connect via ssh with user `hoobs `and password `hoobsadmin`
`ssh hoobs@hoobs.local`
Then run this command to get the logs:
`sudo hoobs service log`

**Comment by TheBassfly** [comment]
okay, I got it. Thank you.
