### ISSUE TITLE
Can't find light in "HOOBS plugin for Philips Hue and deCONZ"

### ISSUE THREAD

**Issue by MyHoobs** [hoobs-org/HOOBS#774]
**Description**
I am a beginner with HOOBS and try it on my Apple Homekit.

I have install the plugin (HOOBS plugin for Philips Hue and deCONZ), follow te configuration and fill in the user code. In Homekit I find the Phillips Hue bridge but they don't show the light's and smart plugs.

With "Expose group 0 (all lights)" it works but the lamps do not work separately.

I hope anyone can help me. 

**Expected behavoir**
This plugin exposes ZigBee devices (lights, plugs, sensors, switches, etc.) to HOOBS. Accessories must be connected to one of the following bridges:

Philips Hue Dresden Elektronik deCONZ gateway

**Plugin name**
HOOBS plugin for Philips Hue and deCONZ

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
macOS Catalina

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYDGD5",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "nl",
        "temp_units": "celsius",
        "country_code": "NL",
        "postal_code": "5854"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
   "username": "EA:BF:60:E2:E3:9B"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": false,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": false,
            "users": {
                "ECB5FAFFFE06190B": "ZlVNYR4N5g6dCZxEd7B6qgeUcvOKLtMWwmef-DTs"
            },
            "lights": true,
            "group0": true,
            "groups": true,
            "hueDimmerRepeat": false,
            "hueMotionTemperatureHistory": false,
            "linkButton": false,
            "rooms": false,
            "sensors": false,
            "schedules": false,
            "scenesAsSwitch": false,
            "scenes": false,
            "rules": false,
            "wallSwitch": false,
            "forceEveWeather": false,
            "forceHttp": false
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
25-8-2020 19:17:14 Bridge is running on port 51826.
25-8-2020 19:17:18 [Hue] Group 0: homekit on changed from 0 to 1
25-8-2020 19:17:20 [Hue] Group 0: set homekit any on from 1 to 0
25-8-2020 19:17:23 [Hue] Group 0: homekit on changed from 0 to 1
25-8-2020 19:17:24 [Hue] Group 0: homekit on changed from 1 to 0
25-8-2020 19:17:26 [Hue] Group 0: homekit on changed from 0 to 1
25-8-2020 19:17:30 [Hue] Group 0: set homekit any on from 1 to 0
```

**Additional context**

**Comment by BobbySlope** [comment]
Please Login to Phoscon and see if the Lights are dectected as separate lights
