### ISSUE TITLE
Can't see Homekit devices after Pi-Hole install

### ISSUE THREAD

**Issue by spenceuiuc** [hoobs-org/HOOBS#775]
**Description**
I had Hoobs running fine on a Raspberry Pi 4 for some time but I did a clean install of Hoobs via the downloadable image written to the SD card To start fresh with some other projects removed. I got it connected to homekit/Home app and everything was working fine. 

Then I installed Pi-Hole per the Hoobs guide: https://support.hoobs.org/docs/5e875a0e0ab68b0344e872c3

After installing Pi-Hole, the none of my accessories would respond in homekit/Home. I tried removing the hub from the Home app, changing the username + pin of Hoobs and adding again, and it would not find the accessory. 

I also noted that I could access HOOBS via hoobs.local prior to installing pihole, but had to use IP addresses afterwards. And, my mg7550 router could only use PiHole via an IPv4 DNS- it couldn't set a custom DNS server for IPv6 for whatever reason- maybe related?

I tried the flash HOOBS + install pihole process 2x, and got the same results. 

Any ideas on how to resolve it? Thanks!

**Version**
Hoobs Version 3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi 4

**List your plugins**
Hubitat Tonesto7

**Post your config**
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYXP85MM",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "removed"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "removed",
        "username": "4C:EA:27:2A:DA:GF"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Hubitat",
            "name": "Hubitat",
            "app_url": "removed",
            "access_token": "removed",
            "plugin_map": {
                "plugin_name": "homebridge-hubitat-tonesto7"
            }
        }
    ]
}

**Comment by BobbySlope** [comment]
please provide more info; Log? Dies the HOOBS Service run?
