### ISSUE TITLE
hoobs installation on raspberry pi 3 failed

### ISSUE THREAD

**Issue by Paherb** [hoobs-org/HOOBS#776]
**Description**
when installing hoobs according to support.hoobs.org installation fails after 
`$ wget -q -O - http://bit.ly/get-hoobs | sudo bash -`
 with following error:

> Setting up curl (7.52.1-5+deb9u11) ...
>bash: line 490: npm: command not found
>Failed to set capabilities on file `/usr/bin/node' (Invalid argument)
>The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file

**Version**
No Version available, because Installation failed

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Raspberry pi - Raspian

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Real VNC

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
No Configuration available, because Installation failed
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Complet terminal error message:

root@raspberrypi:/home/pi# wget -q -O - http://bit.ly/get-hoobs | sudo bash -

Thank You for choosing HOOBS
================================================================================
Node Version 4.8.2
Updating Repositories
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease            
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u11).
git is already the newest version (1:2.11.0-3+deb9u6).
tar is already the newest version (1.29b-1.1).
0 upgraded, 0 newly installed, 0 to remove and 358 not upgraded.
**bash: line 490: npm: command not found
Failed to set capabilities on file `/usr/bin/node' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file**

**Comment by BobbySlope** [comment]
Please Try again, and send us the output

**Comment by Paherb** [comment]
In the meanwhile I got hoobs runnig by installing a complet new raspberry image.
THX for your response
