### ISSUE TITLE
Ring PlugIn Refresh Token

### ISSUE THREAD

**Issue by Jimmymck** [hoobs-org/HOOBS#778]
I'm trying to set up the ring plugin in Hoobs but I get the following in the terminal when running the command.

/hoobs/etc # npx -p ring-client-api ring-auth-cli
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/4254/lib/node_modules/ring-client-api/node_modules/ffmpeg-for-homebridge/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffmpeg-for-homebridge@0.0.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffmpeg-for-homebridge@0.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-27T19_20_27_933Z-debug.log
Install for [ 'ring-client-api@latest' ] failed with code 1

**Comment by askovi** [comment]
If you're running HOOBS inside a docker container, that command won't work. 
Simply run the command in your local terminal and follow the prompted instructions. It's completely independent from HOOBS. You can then copy the generated token and paste it into the Ring plugin config in HOOBS.

**Comment by Jimmymck** [comment]
Yes I am using Docker. I’ve tried terminal and I might be doing something stupid but terminal says npx is an unknown command

**Comment by BobbySlope** [comment]
please send us a snipped of the terminal when you are trying it and get an error
