### ISSUE TITLE
Hue Plugin Won't Update

### ISSUE THREAD

**Issue by ghost** [hoobs-org/HOOBS#779]
**Description**
HOOBS dashboard shows an update for homebridge-Hue to 0.11.74. Upon clicking "Update," the system seems to process the update as normal (I even get a "Plugin updated successfully" message), but afterwards, HOOBS still shows that an update is available. 

**Expected behavoir**
Plugin should successfully update.

**Plugin name**
homebridge-Hue

**Version**
HOOBS v. 3.2.6

**Did you upgrade**
I did not upgrade from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
@askovi npm sync issue again?
@ghost which plugin version are you on right now?
try to uninstall the plugin and reinstall it

**Comment by askovi** [comment]
Try to uninstall it then reinstall from the UI.
