### ISSUE TITLE
Unable to Uninstall homebridge-alexa

### ISSUE THREAD

**Issue by Gamejunkie85** [hoobs-org/HOOBS#780]
I'm trying to uninstall the homebridge-alexa plugin but continue to receive "Plugin Uninstall Failed" in hoobs. I have also gone into terminal and tried:

`sudo npm uninstall -g homebridge-alexa`

This does nothing and the plugin remains. I have also deleted the homebridge alexa plugin username and password but the Alexa devices are still being discovered in the log file.

Any help would be much appreciated.

**Comment by askovi** [comment]
Try with this command in Terminal:

sudo rm -fR ~/.hoobs/node_modules/homebridge-alexa

**Comment by Gamejunkie85** [comment]
> Try with this command in Terminal:
> 
> sudo rm -fR ~/.hoobs/node_modules/homebridge-alexa

Awesome thank you, that worked!
