### ISSUE TITLE
Raspberry II integration in Hoobs with Hue / Deconz" plugin

### ISSUE THREAD

**Issue by homer123456** [hoobs-org/HOOBS#784]
**Raspberry II integration in Hoobs with Hue / Deconz" plugin **

Hi all,
I have a problem integrating the Raspberry II module in hoobs.

I have plugged in the Phoscon Raspberry II module to my Raspberry which is running Hoobs.

Have installed the deconz package, which is running o.k.
In my case Hoobs I can reach via 192.168.0.31
and Deconz graphical plugin via 192.68.0.31:1881

I was able to link 2 zigbee devices (Xiaomi Sensor and an Osram plug) to Deconz.

Was then trying to install the "Hue / Deconz" plugin (homebridge-hue
0.11.75 • Published August 24th) in Hoobs and then link to the Raspberry II.
Via the log function in Hoobs I have received the user data:
"0021xxxxxxxx": "2Axxxxx"
and inserted this in the mask of the plugin in Hoobs.

When I press save config for the plugin the Hoobs bridge is not turning on again.
In the log-file I can see that the Hue plugin seem to use a different IP address
192........192 and others.

Have then tried to set Host: "192.168.0.31"
but this is also not working.

Config:

{
"platform": "Hue",
"plugin_map": {
"plugin_name": "homebridge-hue"
},
"name": "Hue",
"anyOn": true,
"nativeHomeKitLights": true,
"nativeHomeKitSensors": true,
"nupnp": true,
"resource": true,
"hosts": [
"192.168.0.31"
],
"users": {
"002xxxxxxxxxxxxx": "9Cxxxxxxxxx"
}

When I de-install the Hue Plugin Hoobs works again (with the rest).

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
homebridge-hue
0.11.75 • Published August 24th

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.
Latest version. Just installed it last week (end of August)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
See extract from config above.

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**

```
Extract from log:

9/1/2020, 9:41:32 PM [Hue] goodbye
9/1/2020, 9:41:42 PM [Hue] 192.***.***.192: 192.168.0.192:80: cannot connect: EHOSTUNREACH - retrying in 15s
9/1/2020, 9:42:00 PM [Hue] 192.***.***.192: 192.168.0.192:80: cannot connect: EHOSTUNREACH - retrying in 15s
9/1/2020, 9:42:05 PM [Hue] 192.***.***.20: 192.168.178.20:80: cannot connect: ETIMEDOUT - retrying in 15s
9/1/2020, 9:42:19 PM [Hue] 192.***.***.192: 192.168.0.192:80: cannot connect: EHOSTUNREACH - retrying in 15s
9/1/2020, 9:42:21 PM Loaded plugin "homebridge-ewelink-max".
9/1/2020, 9:42:21 PM homebridge API version: 2.5
9/1/2020, 9:42:22 PM Loaded plugin "homebridge-harmony".
9/1/2020, 9:42:24 PM Loaded plugin "homebridge-hue".
9/1/2020, 9:42:24 PM Loaded plugin "homebridge-nest".
9/1/2020, 9:42:25 PM Loaded plugin "homebridge-nest-cam".
9/1/2020, 9:42:25 PM Loaded plugin "homebridge-shelly".
9/1/2020, 9:42:25 PM Loaded plugin "homebridge-yeelight-platform".
9/1/2020, 9:42:25 PM [Nest] Fetching Nest devices.
9/1/2020, 9:42:25 PM [eWeLink] Initialising eWeLink


```

**Additional context**

**Comment by askovi** [comment]
Try changing your host ip to include the port: 192.68.0.31:1881

**Comment by askovi** [comment]
Try Reset Connection from the Help menu to get rid of cached accessories. Then rescan the QR code from the dashboard. It has to connect to the one with port 1881.

**Comment by homer123456** [comment]
Tanks askovi! Tried, but also not working. I now did it now with the "normal" homebridge, which seems to have now nearly as much functionality as hoobs. So the Hoobs is not so much an advantage any more. This also have an installer for deconz/Phoscon included, so it really ran nearly "out of the box". No issues in connecting and passing through to homekit.
