### ISSUE TITLE
HOOBS web interface not opening after power outage (already in use)

### ISSUE THREAD

**Issue by martinnock** [hoobs-org/HOOBS#785]
My HOOBS web interface is inaccessible after my Pi 3 has restarted after a power outage.
I had this issue a couple of times and my only solution so far was writing the backup to the SD, but there must be another solution to it, hence, I am logging this as an issue now.

HOOBS as such is running, all my plugins works, however, I cannot access the hoobs.local webinterface anylonger (also not via IP address).

I tried some killall, but it didn't solve it - also when trying to launch the server after reboot, HOOBS is already running.

Which terminal commands do you recommend to run?

Thanks!
Martin

**Comment by askovi** [comment]
Start by running this command to get the logs:

`sudo hoobs service log`

**Comment by martinnock** [comment]
Thanks - actually a very normal log I got.
However, it brought me to an idea, as it says "listening on port 8080".
I tried hoobs.local:8080 and the UI opens up, but not without the :8080 which I didn't have before.
Any thoughts?

**Comment by askovi** [comment]
You can change the server port back to 80 from your configuration. 
If you get this error in the logs after you change it:
`Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80`

Run the following commands to fix it:

```
sudo systemctl disable nginx

sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node

sudo reboot
```

**Comment by martinnock** [comment]
Great help, thanks. Just changing the port to 80 solved the issue with further complications.
Leaving the unresolved mystery why the port changed with the reboot due to power outage.
