### ISSUE TITLE
Unable to Edit Camera FFMPEG Configuration 

### ISSUE THREAD

**Issue by Nebcool** [hoobs-org/HOOBS#787]
I'm new to HOOBS/Homebridge, but thought the instructions pretty straight forward that once HOOBS was up and running, I would install the Camera FFMPEG and amend the Config box to fit my Amcrest camera and pull into Apple Home. Unfortunately, every time I go into the Configuration box and try to copy/paste/amend as needed from the code [here]([url](https://sunoo.github.io/homebridge-camera-ffmpeg/configs/Amcrest-IP3M-HX2W.html), it does not save. When I click "Save Changes," I get a message saying the Bridge Service is stopping, restarting, and then when it comes up again, the box is blank again. Can you please advise if I'm doing something wrong or how to get the configurations to take in the system?

**Comment by askovi** [comment]
This is probably because you're entering incorrect configuration. You need to paste only this part in the box:

`[{
		"name": "Camera Living Room Amcrest",
		"videoConfig": {
			"source": "-rtsp_transport tcp -re -i rtsp://user:pwd@192.168.1.221/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46bG9sYTk2OTg=",
			"stillImageSource": "-i http://user:pwd@192.168.1.221/cgi-bin/snapshot.cgi?1",
			"maxStreams": 2,
			"maxWidth": 1280,
			"maxHeight": 720,
			"maxFPS": 15,
			"maxBitrate": 300,
			"vcodec": "libx264 -preset ultrafast",
			"packetSize": 1316,
			"audio": false,
			"debug": true
		}
	}]`
