### ISSUE TITLE
Homebridge plugin to control Worx Landroid  problems

### ISSUE THREAD

**Issue by enggaard10** [hoobs-org/HOOBS#788]
6.9.2020 13.40.47 [FibaroHC2] Configured Accessory:  PIR port
6.9.2020 13.40.47 [FibaroHC2] Configured Accessory:  Temp
6.9.2020 13.40.47 [FibaroHC2] Configured Accessory:  Lux
6.9.2020 13.40.47 [FibaroHC2] didFinishLaunching. 
6.9.2020 13.40.47 [My Landroid] DidFinishLaunching
6.9.2020 13.40.47 TypeError: Cannot read property 'server' of undefined
    at new Worx (/home/hoobs/.hoobs/node_modules/iobroker.worx/lib/api.js:155:38)
    at API.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-landroid/index.js:36:26)
    at API.emit (events.js:215:7)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:104:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
6.9.2020 13.40.47 Bridge is running on port 51826.
6.9.2020 13.40.47 Got SIGTERM, shutting down Bridge...
6.9.2020 13.40.47 [FibaroHC2] Loading accessories 
6.9.2020 13.40.47 [FibaroHC2] Added/changed accessory:  Loft Lys
6.9.2020 13.40.47 [FibaroHC2] Added/changed accessory:  Lys over vask rele
6.9.2020 13.40.47 [FibaroHC2] Added/changed accessory:  Ude Lys
6.9.2020 13.40.47 [FibaroHC2] Added/changed accessory:  Sove Tv
6.9.2020 13.40.47 [FibaroHC2] Added/changed accessory:  Danfoss

 },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "FibaroHC2",
            "name": "FibaroHC2",
            "host": "192.169.0.100",
            "username": "admin",
            "password": "XXX",
            "grouping": "room",
            "pollerperiod": "2",
            "plugin_map": {
                "plugin_name": "homebridge-fibaro-hc2"
            }
        },
        {
            "platform": "Landroid",
            "plugin_map": {
                "plugin_name": "homebridge-landroid"
            },
            "name": "My Landroid",
            "dev_name": "LandroidM",
            "email": "XXX",
            "pwd": "XXX",
            "rainsensor": false,
            "reload": false,
            "debug": false,
            "mowdata": false
        }
    ]
}

**Comment by enggaard10** [comment]
a fresh installation

6.9.2020 14.41.04 HOOBS listening on port 8080.
6.9.2020 14.41.06 No plugins found.
6.9.2020 14.41.06 Bridge is running on port 51826.
6.9.2020 14.42.03 npm
6.9.2020 14.42.03  WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
6.9.2020 14.42.03 npm
6.9.2020 14.42.03  WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
6.9.2020 14.42.03 npm
6.9.2020 14.42.03  WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
6.9.2020 14.42.06 npm
6.9.2020 14.42.06  WARN deprecated har-validator@5.1.5: this library is no longer supported
6.9.2020 14.42.34 + homebridge-landroid@0.9.0
added 133 packages from 164 contributors in 31.925s
6.9.2020 14.42.35 
2 packages are looking for funding
  run `npm fund` for details
6.9.2020 14.42.35 Plugin "homebridge-landroid" installed.
6.9.2020 14.42.36 Got SIGINT, shutting down Bridge...
6.9.2020 14.42.41 Loaded plugin "homebridge-landroid".
6.9.2020 14.42.41 [Landroid] WARNING: No account configured, please set email and password of your Worx account in config.json!
6.9.2020 14.42.41 Bridge is running on port 51826.
6.9.2020 14.43.04 Got SIGINT, shutting down Bridge...
6.9.2020 14.43.13 Loaded plugin "homebridge-landroid".
6.9.2020 14.43.13 [Landroid] DidFinishLaunching
6.9.2020 14.43.13 [Landroid] **** WARNING: Landroid plugin is in reload mode, mowers will be recreated each boot ****
6.9.2020 14.43.13 TypeError: Cannot read property 'server' of undefined
    at new Worx (/home/hoobs/.hoobs/node_modules/iobroker.worx/lib/api.js:155:38)
    at API.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-landroid/index.js:36:26)
    at API.emit (events.js:210:5)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:104:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
6.9.2020 14.43.13 Bridge is running on port 51826.
6.9.2020 14.43.13 Got SIGTERM, shutting down Bridge...
6.9.2020 14.46.02 Loaded plugin "homebridge-landroid".
6.9.2020 14.46.02 [Landroid] DidFinishLaunching
6.9.2020 14.46.02 [Landroid] **** WARNING: Landroid plugin is in reload mode, mowers will be recreated each boot ****
6.9.2020 14.46.02 TypeError: Cannot read property 'server' of undefined
    at new Worx (/home/hoobs/.hoobs/node_modules/iobroker.worx/lib/api.js:155:38)
    at API.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-landroid/index.js:36:26)
    at API.emit (events.js:210:5)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:104:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
6.9.2020 14.46.02 Bridge is running on port 51826.
6.9.2020 14.46.02 Got SIGTERM, shutting down Bridge...

{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://xxx",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "xxx"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Landroid",
            "plugin_map": {
                "plugin_name": "homebridge-landroid"
            },
            "email": "xxx",
            "pwd": "xxx",
            "rainsensor": true,
            "reload": true,
            "debug": true,
            "mowdata": true
        }
    ]
}

**Comment by BobbySlope** [comment]
You need to Setup your Account info in the Plugins Configuration:
<img width="825" alt="Screenshot 2020-09-06 at 16 20 40" src="https://user-images.githubusercontent.com/50763727/92327879-0ed9c900-f05d-11ea-8592-a63099ea1060.png">

**Comment by enggaard10** [comment]
Hi yes I have done it too, but it works, shutting down Bridge ...

**Comment by enggaard10** [comment]
as soon as I remove Plugin "homebridge-landroid" removed.
runs my fibaro as normal
6.9.2020 16.32.06 Loaded plugin "homebridge-fibaro-hc2"

**Comment by BobbySlope** [comment]
please share your actual config, i use this plugin by myself and i never had issues with it

**Comment by BobbySlope** [comment]
which mover do you have? and which plugin version have you installed?

**Comment by enggaard10** [comment]
A Landroid M WR143E 
 HOOBS Certified Landroid
0.9.0 published 5/18/2020

{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://x",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "DK",
        "postal_code": "3310"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "x"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "FibaroHC2",
            "name": "FibaroHC2",
            "host": "192.168.0.100",
            "username": "x",
            "password": "x",
            "grouping": "room",
            "pollerperiod": "2",
            "plugin_map": {
                "plugin_name": "homebridge-fibaro-hc2"
            }
        },
        {
            "platform": "Landroid",
            "plugin_map": {
                "plugin_name": "homebridge-landroid"
            },
            "email": "x@x.dk",
            "pwd": "x",
            "rainsensor": true,
            "reload": true,
            "debug": true,
            "mowdata": true
        }
    ]
}

**Comment by enggaard10** [comment]
6.9.2020 16.48.10 Loaded plugin "homebridge-fibaro-hc2".
6.9.2020 16.48.11 Loaded plugin "homebridge-landroid".
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Loft Lys
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Lys over vask rele
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Ude Lys
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Sove Tv
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Danfoss
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Lys
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Retur solvarme
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Danfoss
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Danfoss
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Danfoss
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Danfoss
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Danfoss
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Danfoss mod indkørse
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Led auto 80 10
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Lys over vask
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Led on 80%
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Auto Lys On/Off
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Led Loft
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Køkken skabe
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Pir
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Pir
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Solvarme Top
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Solvarme Bund
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Danfoss sofa
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  LED Dør
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Pir
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Temp
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Lux
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Cirkulationspumpe
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Ventil Centralvarme
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Vagt
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Spa vand
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Fermløb veksler
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Dørlås
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Stue/køkken
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Stue/Køkken
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Røg
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Temp
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Pir
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Temp
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Lux 420
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Temperature
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Loft Lys
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Kontakt Lys sofa
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Led 80%
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Kontakt Tv
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Brykkers dør
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Křken Pir
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Stue Pir
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Gang Pir
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Satel control
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Loft lampe verlse
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  loft lampe gang
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Led
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Led
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Danfoss
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Led
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Røg
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Dør Sensor
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Temperatur sensor
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Dør Sensor
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Temp Dør
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Test lys
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Stå op klik
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  gå i seng klik
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  PIR port
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Temp
6.9.2020 16.48.11 [FibaroHC2] Configured Accessory:  Lux
6.9.2020 16.48.11 [FibaroHC2] didFinishLaunching. 
6.9.2020 16.48.11 [Landroid] DidFinishLaunching
6.9.2020 16.48.11 [Landroid] **** WARNING: Landroid plugin is in reload mode, mowers will be recreated each boot ****
6.9.2020 16.48.11 TypeError: Cannot read property 'server' of undefined
    at new Worx (/home/hoobs/.hoobs/node_modules/iobroker.worx/lib/api.js:155:38)
    at API.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-landroid/index.js:36:26)
    at API.emit (events.js:215:7)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:104:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
6.9.2020 16.48.11 Bridge is running on port 51826.
6.9.2020 16.48.11 Got SIGTERM, shutting down Bridge...
6.9.2020 16.48.12 [FibaroHC2] Loading accessories 
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Loft Lys
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Lys over vask rele
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Ude Lys
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Sove Tv
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Danfoss
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Lys
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Retur solvarme
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Danfoss
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Danfoss
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Danfoss
6.9.2020 16.48.12 [FibaroHC2] Added/changed accessory:  Danfoss
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Danfoss
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Danfoss mod indkørse
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Led auto 80 10
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Lys over vask
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Led on 80%
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Auto Lys On/Off
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Led Loft
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Køkken skabe
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Pir
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Pir
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Solvarme Top
6.9.2020 16.48.13 [FibaroHC2] Added/changed accessory:  Solvarme Bund
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Danfoss sofa
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  LED Dør
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Pir
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Temp
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Lux
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Cirkulationspumpe
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Ventil Centralvarme
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Vagt
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Spa vand
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Fermløb veksler
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Vagt
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Dørlås
6.9.2020 16.48.14 [FibaroHC2] Added/changed accessory:  Stue/køkken
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Stue/Køkken
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Røg
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Temp
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Pir
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Temp
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Lux 420
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Temperature
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Loft Lys
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Kontakt Lys sofa
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Led 80%
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Kontakt Tv
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Brykkers dør
6.9.2020 16.48.15 [FibaroHC2] Added/changed accessory:  Křken Pir
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Stue Pir
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Gang Pir
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Satel control
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Loft lampe verlse
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  loft lampe gang
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Led
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Led
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Danfoss
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Led
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Røg
6.9.2020 16.48.16 [FibaroHC2] Added/changed accessory:  Temp
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  Dør Sensor
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  Temperatur sensor
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  Dør Sensor
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  Temp Dør
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  Test lys
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  Stå op klik
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  gå i seng klik
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  PIR port
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  Temp
6.9.2020 16.48.17 [FibaroHC2] Added/changed accessory:  Lux

**Comment by enggaard10** [comment]
completely fresh system.

6.9.2020 18.08.52 HOOBS listening on port 8080.
6.9.2020 18.08.54 No plugins found.
6.9.2020 18.08.54 Bridge is running on port 51826.
6.9.2020 18.09.53 npm
6.9.2020 18.09.53  WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
6.9.2020 18.09.53 npm
6.9.2020 18.09.53  WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
6.9.2020 18.09.53 npm
6.9.2020 18.09.53  WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
6.9.2020 18.09.56 npm
6.9.2020 18.09.56  WARN deprecated har-validator@5.1.5: this library is no longer supported
6.9.2020 18.10.09 npm
6.9.2020 18.10.09  notice created a lockfile as package-lock.json. You should commit this file.
6.9.2020 18.10.09 + homebridge-landroid@0.9.0
added 133 packages from 164 contributors in 16.973s
6.9.2020 18.10.10 
2 packages are looking for funding
  run `npm fund` for details
6.9.2020 18.10.10 Plugin "homebridge-landroid" installed.
6.9.2020 18.10.11 Got SIGINT, shutting down Bridge...
6.9.2020 18.10.16 Loaded plugin "homebridge-landroid".
6.9.2020 18.10.16 [Landroid] WARNING: No account configured, please set email and password of your Worx account in config.json!
6.9.2020 18.10.16 Bridge is running on port 51826.
6.9.2020 18.11.03 Got SIGINT, shutting down Bridge...
6.9.2020 18.11.08 Loaded plugin "homebridge-landroid".
6.9.2020 18.11.08 [Landroid] DidFinishLaunching
6.9.2020 18.11.08 [Landroid] **** WARNING: Landroid plugin is in reload mode, mowers will be recreated each boot ****
6.9.2020 18.11.08 TypeError: Cannot read property 'server' of undefined
    at new Worx (/home/hoobs/.hoobs/node_modules/iobroker.worx/lib/api.js:155:38)
    at API.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-landroid/index.js:36:26)
    at API.emit (events.js:210:5)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:104:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
6.9.2020 18.11.08 Bridge is running on port 51826.
6.9.2020 18.11.08 Got SIGTERM, shutting down Bridge...

(Configuration Advanced)

{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://X",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "XXXXX"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Landroid",
            "plugin_map": {
                "plugin_name": "homebridge-landroid"
            },
            "email": "XXX@XXX.dk",
            "pwd": "XXXXXX",
            "rainsensor": true,
            "reload": true,
            "debug": true,
            "mowdata": true
        }
    ]
}

**Comment by enggaard10** [comment]
Have tried with HOOBS Version 3.1.1
there I can get Homebridge service to go on with fibaro although it does conflict with the homebridge-Landroid


[9/7/2020, 17:47:48] HOOBS listning on port 8080.
[Homebridge] [9/7/2020, 17:47:49] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [9/7/2020, 17:47:49] ---
[Homebridge] [9/7/2020, 17:47:49] Warning: skipping plugin found at '/home/hoobs/node_modules/homebridge-landroid' since we already loaded the same plugin from '/home/hoobs/.hoobs/node_modules/homebridge-landroid'.
[Homebridge] [9/7/2020, 17:47:50] Loaded plugin: homebridge-fibaro-hc2
[Homebridge] [9/7/2020, 17:47:50] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
[Homebridge] [9/7/2020, 17:47:50] ---
[Homebridge] [9/7/2020, 17:47:51] Loaded plugin: homebridge-landroid
[Homebridge] [9/7/2020, 17:47:51] Registering platform 'homebridge-landroid.Landroid'
[Homebridge] [9/7/2020, 17:47:51] ---
[Homebridge] [9/7/2020, 17:47:51] Loading 1 platforms...
[Homebridge] [9/7/2020, 17:47:51] [Landroid] Initializing Landroid platform...
[Homebridge] [9/7/2020, 17:47:51] Loading 0 accessories...
[Homebridge] Load homebridge-fibaro-hc2.FibaroHC2
[Homebridge] [9/7/2020, 17:47:51] [homebridge-fibaro-hc2.FibaroHC2] Configured Accessory:  Loft Lys
[Homebridge] [9/7/2020, 17:47:51] [homebridge-fibaro-hc2.FibaroHC2] Configured Accessory:  Lys over vask rele
[Homebridge] [9/7/2020, 17:47:51] [homebridge-fibaro-hc2.FibaroHC2] Configured Accessory:  Ude Lys
[Homebridge] [9/7/2020, 17:47:51] [homebridge-fibaro-hc2.FibaroHC2] Configured Accessory:  Sove Tv
[Homebridge] [9/7/2020, 17:47:51] [homebridge-fibaro-hc2.FibaroHC2] Configured Accessory:  Danfoss
[Homebridge] X-HM://0023ISYWYJEEH
[Homebridge] [9/7/2020, 17:47:52] [Landroid] DidFinishLaunching
[Homebridge] [9/7/2020, 17:47:52] [Landroid] **** WARNING: Landroid plugin is in reload mode, mowers will be recreated each boot ****
[Homebridge] [9/7/2020, 17:47:52] TypeError: Cannot read property 'server' of undefined
[Homebridge] at new Worx (/home/hoobs/.hoobs/node_modules/iobroker.worx/lib/api.js:155:38)
[Homebridge] at API.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-landroid/index.js:36:26)
[Homebridge] at API.emit (events.js:210:5)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:94:15)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[Homebridge] at internal/main/run_main_module.js:17:11
[Homebridge] [9/7/2020, 17:47:52] Service is running on port 51826.
[Homebridge] [9/7/2020, 17:47:55] [homebridge-fibaro-hc2.FibaroHC2] Getting value from device:  319  parameter: Current Ambient Light Level
[Homebridge] [9/7/2020, 17:47:55] [homebridge-fibaro-hc2.FibaroHC2] Getting value from device:  17  parameter: Target Temperature
[Homebridge] [9/7/2020, 17:47:55] [homebridge-fibaro-hc2.FibaroHC2] Getting value from device:  17  parameter: Current Heating Cooling State
[Homebridge] [9/7/2020, 17:47:55] [homebridge-fibaro-hc2.FibaroHC2] Getting value from device:  17  parameter: Target Heating Cooling State
[Homebridge] [9/7/2020, 17:47:55] [homebridge-fibaro-hc2.FibaroHC2] Getting value from device:  17  parameter: Current Temperature
[Homebridge] [9/7/2020, 17:47:55] [homebridge-fibaro-hc2.FibaroHC2] Getting value from device:  17  parameter: Temperature Display Units
[Homebridge] [9/7/2020, 17:47:55] [homebridge-fibaro-hc2.FibaroHC2] Getting value from device:  439  parameter: On

**Comment by enggaard10** [comment]
have tried it on google assistant it works fine but not the platform I run.

is there really no one who has a solution to my little problem, has written with several on several forums. they have no issues with Landroids on HOOBS :)

**Comment by Schosch83** [comment]
Hi I have the same issue.
look here:
https://github.com/normen/homebridge-landroid/issues/26

**Comment by Baxtar** [comment]
> have tried it on google assistant it works fine but not the platform I run.
> 
> is there really no one who has a solution to my little problem, has written with several on several forums. they have no issues with Landroids on HOOBS :)

Hi I have the same Problem. 
Same problem on 2 systems....raspberrypi 4 with Homebridge and raspberrypi 4 with HOOBS. As soon as I install the plug-in, the homebridge crasps and Hobbs can no longer be started. After uninstalling, everything goes back to normal.

**Comment by Schosch83** [comment]
Now he fixed the Problem.
Just Upgrade homebridge-landroid to 0.9.1 
Works fine.
