### ISSUE TITLE
NEST Plugin preventing communication from bridge to phone

### ISSUE THREAD

**Issue by vazrams** [hoobs-org/HOOBS#794]
**Description**
I had communication issues for the last couple days between my HOOBS bridge and HomeKit. I did a complete re-install and when I added all my plugins one by one they worked. When I add NEST plugin it interrupts the communication between HOOBS and my phone.. All other devices become inactive as well. When I uninstall NEST all others are back again.

**Expected behavoir**
NEST thermostat should show up on home and all other accessories should work. 

**Plugin name**
NEST

**Please report the issue to the plugin developer**

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
This is most likely related to a configuration issue. Please post your logs and config. Mask any passwords and access tokens
