### ISSUE TITLE
Ewelink Max

### ISSUE THREAD

**Issue by engelbho** [hoobs-org/HOOBS#796]
**Description**
Installed the plugin and added the ewelink account details as per the instructions.

Everytime i start the Hoobs services the accessories page goes blank.

In the log files it shows everything is active and working but accessories page stays blank.

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Ewelink Max version 0.1.24

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.2.6 Docker

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Please post your logs and config. Mask any passwords and access tokens.
