### ISSUE TITLE
Hoobs local forgot password 

### ISSUE THREAD

**Issue by abizzio** [hoobs-org/HOOBS#798]
So how to I retrieve or reset password so I can get into Hoobs local and manage my device ?

**Comment by askovi** [comment]
The account can be reset by deleting the access.json file via ssh. After you’re logged in via ssh paste the following command:

sudo rm -rf /home/hoobs/.hoobs/etc/access.json

Then reboot with:

sudo reboot

After a couple of minutes go to hoobs.local and you will be prompted to create a new admin account. You won’t lose any plugins or configuration.

**Comment by abizzio** [comment]
Im gonna sound like a noob.... what’s a Ssh? Sorry :-(

**Comment by elmehalawi** [comment]
I don't see a ~/.hoobs directory. I'm using 4.0.31, was it changed in 4?
