### ISSUE TITLE
ETIMEDOUT while connecting after update plugin

### ISSUE THREAD

**Issue by wavi-web** [hoobs-org/HOOBS#801]
Posted this issue to the autor of the plugin: Response: Others have said there was a homebridge error (rather than the plugin). Try updating nodejs, homebridge, and the plugin and try again. If I don't hear back by end of week, I'll close this issue.

Since I cannot update nodejs and homebridge on HOOBS I am looking for a solution. 

Using the Homebridge/Homeseer4 plugin version 1.06 on HOOBS on a Rpi4, version 3.6.2.

Just installed version 1.0.6 of the plugin, after configuration the service won't start. See config.json and logging:
Edit 19:22: No problems when connecting to HS3 (old installation).

config.json:
{
"server": {
"port": 80,
"origin": "*",
"autostart": 0,
"home_setup_id": "X-HM://0023ISYWYxxxx",
"polling_seconds": 5
},
"client": {
"default_route": "status",
"inactive_logoff": 30,
"theme": "hoobs-light",
"locale": "en",
"temp_units": "celsius",
"country_code": "NL",
"postal_code": "94040"
},
"bridge": {
"name": "HOOBS",
"port": 51826,
"pin": "031-45-xxx",
"username": "44:A8:BF:8F:xx:xx"
},
"description": "",
"ports": {},
"accessories": [],
"platforms": [
{
"platform": "HomeSeer",
"plugin_map": {
"plugin_name": "homebridge-homeseer4"
},
"name": "HomeSeer",
"host": "http://homeseer.local",
"ASCIIport": 11000,
"login": "xxxxx",
"password": "xxxxxx"
}
]
}
Log:
17-9-2020 09:52:31 (node:22916) UnhandledPromiseRejectionWarning: FetchError: request to http://hoobs:xxx@192.168.1.10/JSON?request=getstatus failed, reason: connect ETIMEDOUT 192.168.1.10:8017-9-2020 09:52:31 at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1461:11)17-9-2020 09:52:31 at ClientRequest.emit (events.js:310:20)17-9-2020 09:52:31 at Socket.socketErrorListener (_http_client.js:426:9)17-9-2020 09:52:31 at Socket.emit (events.js:310:20)17-9-2020 09:52:31 at emitErrorNT (internal/streams/destroy.js:92:8)17-9-2020 09:52:31 at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)17-9-2020 09:52:31 at processTicksAndRejections (internal/process/task_queues.js:84:21)17-9-2020 09:52:31 (node:22916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)17-9-2020 09:52:31 (node:22916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by askovi** [comment]
To update node on HOOBS, you can use the following command in the Terminal:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

**Comment by wavi-web** [comment]
Updated HOOBS using wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts.
It did not solve the problem. Still getting:
(node:4871) UnhandledPromiseRejectionWarning: FetchError: request to http://hoobs:homebridge@192.168.1.10/JSON?request=getstatus failed, reason: connect ETIMEDOUT 192.168.1.10:80

When I test the status link in a browser is works: http://hoobs:homebridge@192.168.1.10/JSON
Could there be something I'm missing here?

**Comment by askovi** [comment]
Can you run `node -v` in the HOOBS terminal and post the results please

**Comment by wavi-web** [comment]
v12.16.3

**Comment by wavi-web** [comment]
> 
> 
> v12.16.3

Hi askovi, any luck on solving my problem? Thx.

**Comment by wavi-web** [comment]
I would appreciate some help here, the HS4 plugin is my main reason for purchasing HOOBS. I cannot upgrade to HS4 but already bought the licenses.

Is it possible to solve this issue? Thanks in advance.
