### ISSUE TITLE
Problem With HOOBS and HomeKit TV Icon

### ISSUE THREAD

**Issue by ValoV83** [hoobs-org/HOOBS#802]
I have just upgraded my iPhone to iOS 14 and have noticed that TV icon for my Panasonic TV tile within the Home app has now been replaced with a default home icon. 

![IMG_5505](https://user-images.githubusercontent.com/53697662/93465492-c8992b00-f8e2-11ea-83df-9f2d0f981f73.jpg)

This only happens within the Home app on iOS 14. My iPad still on iOS 13.7 is displaying the correct icon on the tile. How can I get the correct tile icon back on iOS 14?

HOOBS Version: 3.2.6

**Comment by askovi** [comment]
This issue is not related to HOOBS, it comes directly from the plugin itself. Please open an issue with the plugin developer on their github. It needs to be properly implemented in the plugin code.
