### ISSUE TITLE
Can't get to http://hoobs.local ... Server not found...on iMac

### ISSUE THREAD

**Issue by STCummings57** [hoobs-org/HOOBS#805]
**Description**
Can't get to http://hoobs.local ... Server not found...on iMac
**Version**
HOOBS-in-a-Box Model # HSLF-1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Mac OS High Sierra

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Some routers don't support .local domains. Try accessing it with no domain like this: http://hoobs
You can also look for the local IP address assigned to HOOBS by your router and access it like this: http://192.168.x.x

**Comment by jwheadrick** [comment]
@askovi is right. my issue was that my AT&T router has defined it's own search domain that overrides my local hostnames. hoobs.local became hoobs.attlocal.net. I used an iOS app called WiFiman (Free) to discover all my network devices and noticed that the hoobs box had a different hostname shown.

**Comment by STCummings57** [comment]
Thanks!  I have an AT&T router providing internet access.  hoobs.attlocal.net works!

**Comment by askovi** [comment]
Thank you for confirming it works. Will close this for now.

**Comment by DominicHochberg** [comment]
same issue, I can't reach the server by using any of the urls. it worked before but lost connection after upgrading to new node... any ideas on how to access the hoobs?  THANKS!
