### ISSUE TITLE
Ring Not Prompting for Email

### ISSUE THREAD

**Issue by bngoofy** [hoobs-org/HOOBS#807]
Brand New Hoobs in a box 3.2.6 arrived today. Very Exciting!!

Installed Ring Plugin 9.9.0 and ran the terminal command. It jumps past the email prompt and cursor rests after password not allowing the emailing address to be entered. When I attempt to enter the password it fails to authenticate. If I enter the email then the password or the email by itself I get the same result.

I uninstalled and Re-installed the plugin with the same result.

Any help would be greatly appreciated

Thank You

**Comment by askovi** [comment]
Make sure when you paste the command you don't have any spaces at the end. Try pasting it in notepad first then copy just the command.

**Comment by bngoofy** [comment]
I assume this is for the Ring for HomeKit.

If so, BBEdit showed no spaces or inviable characters from the paste 
but deleting the last character, after pasting, and re-typing the "i" 
in terminal did the trick. Trying it a second time without the afore 
mentioned steps resulted in it skipping the email step again and 
landing on the password.

 It is working well now.

Thanks
Shawn

Shawn Rowland
Webconsort LLC
818.356.0661 O
818.364.1751 F
