### ISSUE TITLE
Trying to get hue plugin to work

### ISSUE THREAD

**Issue by FotoGen1** [hoobs-org/HOOBS#808]
**Description**
Plug in is terminating.

9/18/2020, 5:48:05 PM Got SIGTERM, shutting down Bridge...
9/18/2020, 5:48:08 PM [Hue] goodbye

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Hue
**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using. 3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.

- [ ] HOOBS SD Card

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYI0H6",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "48:01:E3:84:35:D3"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-hue"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}hoobs@hoobs:/home/hoobs/.hoobs/etc $ ```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
9/18/2020, 5:59:20 PM Loaded plugin "homebridge-hue".
9/18/2020, 5:59:20 PM [Hue] config.json: warning: plugin_map: ignoring unknown key
9/18/2020, 5:59:20 PM [Hue] homebridge-hue v0.11.75, node v12.16.3, homebridge v3.2.6
9/18/2020, 5:59:20 PM [Hue] warning: not using recommended node version v12.18.3 LTS
9/18/2020, 5:59:20 PM [Hue] searching bridges and gateways
9/18/2020, 5:59:25 PM [Hue] Philips hue: Philips BSB002 bridge v1940094000, api v1.40.0
9/18/2020, 5:59:25 PM [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.38.0
9/18/2020, 5:59:26 PM [Hue] Philips hue: bridge request 1: post / {"devicetype":"homebridge-hue#hoobs"}
9/18/2020, 5:59:26 PM [Hue] Philips hue: bridge request 1: error 101 link button not pressed
9/18/2020, 5:59:26 PM [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
9/18/2020, 5:59:41 PM [Hue] Philips hue: bridge request 2: post / {"devicetype":"homebridge-hue#hoobs"}
9/18/2020, 5:59:41 PM [Hue] Philips hue: bridge request 2: error 101 link button not pressed
9/18/2020, 5:59:41 PM [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
9/18/2020, 5:59:56 PM [Hue] Philips hue: created user - please edit config.json and restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "001788FFFE491C00": "16kdsvelayB977CQxpT0ktjbnF35BT2V43hT0jZw"
      }
    }
  ]
9/18/2020, 5:59:56 PM [Hue] Philips hue: 1 accessories
9/18/2020, 5:59:56 PM [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
9/18/2020, 5:59:56 PM [Hue] Initializing platform accessory "Philips hue"...
9/18/2020, 5:59:56 PM [Hue] Philips hue: 2 services
9/18/2020, 5:59:56 PM Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js:86:30)
    at HAPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:188:31)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:560:27)
    at Server.publish (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:134:21)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:369:22
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:15:25
    at HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HuePlatform.js:326:5)
9/18/2020, 5:59:56 PM Got SIGTERM, shutting down Bridge...
9/18/2020, 5:59:59 PM [Hue] goodbye```

**Additional context**

**Comment by askovi** [comment]
That looks like a port conflict. It should solve itself if you reboot HOOBS from the top right menu.
