### ISSUE TITLE
ffmpeg not working (HOOBS-Beta 3.0.0)

### ISSUE THREAD

**Issue by iLumen** [hoobs-org/HOOBS#81]
![Bildschirmfoto 2019-08-28 um 16 58 59](https://user-images.githubusercontent.com/4661044/63867756-b08ffa00-c9b5-11e9-84a6-98322a87a84c.png)

If I'm right, then FFMPEG should be pre-installed.

Then why doesn't it work?
I am using the Camera-ffmpeg-ufv plugin.
Is it because of the plugin or because of hoobs?

![Bildschirmfoto 2019-08-28 um 16 59 22](https://user-images.githubusercontent.com/4661044/63867583-6870d780-c9b5-11e9-9637-c3cc2efd2b6a.png)

**Comment by BobbySlope** [comment]
See Release notes:
HOOBS Core
Complete UI redesign, entirely recoded in vueJS and Node
UI Responsive (Mobile / Tablet / Desktop)
Advanced Homebridge controlls: Start, Stop and Restart, Help link, Resetting, Clearing Cache.
Welcome Dashboard incl. Actual Weather information, Weather forecast, Favorite Accessories,
System Health (CPU/RAM/MEMORY) with Detection of Hardware and OS that HOOBS is running on)

HOOBS Certified Plugins

Search of Certified Plugins / Non Certified Installation also Possible (for the Tinkerers)
Seamless integration of Plugin Installation / Config process without JSON Editing
NPM Namespace @HOOBS/[plugin] for certified Plugins (all Plugins Dev can use this as soon as their Plugin works with HOOBS Automated Config)

Certified Plugins comes with V3.0.0 Beta
@HOOBS/Wink https://github.com/hoobs-org/homebridge-wink/blob/master/README.md
@HOOBS/Nest https://github.com/hoobs-org/homebridge-nest
@HOOBS/Chamberlain https://github.com/hoobs-org/homebridge-chamberlain/blob/master/README.md
@HOOBS/Google Home https://github.com/hoobs-org/homebridge-google/blob/master/README.md

**Comment by iLumen** [comment]
okay, sry
then I'm waiting :)

**Comment by BobbySlope** [comment]
Merged with Issue #69
