### ISSUE TITLE
Accessory is out of Compliance

### ISSUE THREAD

**Issue by CaptBeard** [hoobs-org/HOOBS#810]
Unable to add HOOBS to Apple Home. Getting error:
"Unable to add accessory. Accessory is out of compliance."

Using iPhone 11 Pro Max running iOS 14.0

HOOBS Core 3.2.6
Running on Raspberry Pi 3 B

![IMG_0033](https://user-images.githubusercontent.com/25092259/93775793-d73c5680-fbf0-11ea-8c35-54026085c929.png)

**Comment by askovi** [comment]
Do a reset connection from the Help menu in the top right corner, then try scanning again

**Comment by CaptBeard** [comment]
> Do a reset connection from the Help menu in the top right corner, then try scanning again

Did a reset, it generated new Apple Home info, attempting to add to Home again, same results. Thanks.

**Comment by CaptBeard** [comment]
Did a factory reset and the bridge added successfully.
Restored my config file and it produced the same error.
Started removing plugins one by one, and it seems the culprit is the HOOBS certified Nest plugin
