### ISSUE TITLE
HOOBS tries to update homebridge-myq2 instead of homebridge-myq

### ISSUE THREAD

**Issue by jlg89** [hoobs-org/HOOBS#812]
**Description**
HOOBS plugin list shows that the homebridge-myq plugin has an available update, and has the correct number of days since the latest version was released; however, it does not show the current released version of the plugin, and clicking the "Update" button results in a not-updated plugin. Right now, HOOBS shows v2.2.2 as the current version, but it's actually 2.2.3.

**Expected behavoir**
HOOBS should update it to the latest version.

**Plugin name**
homebridge-myq

**Please report the issue to the plugin developer**
I've reported this type of issue to them before (see #761), but it always turns out to be a HOOBS problem, and I'm always given flak for using HOOBS in the first place. Fine, whatever. But if we can determine that this is truly a plugin issue, I'll be pleased to tell them.

I suspect that this issue hinges on the fact that the plugin name was recently changed from "homebridge-myq2" to "homebridge-myq" and HOOBS tries to update using the old plugin name rather than (actually in addition to) the new, which makes the plugin not appear correctly in the list (see #803). I've already removed homebridge-myq2 and installed homebridge-myq, so (according to the plugin author) this should not be happening.

To prevent HOOBS from writing to the old plugin name (so #803 doesn't happen), I created a file at /home/hoobs/.hoobs/node_modules/homebridge-myq2 with root ownership and 000 permissions. So of course this shows up in the log:

<pre>
9/22/2020, 4:27:34 PM npm
9/22/2020, 4:27:34 PM  WARN checkPermissions Missing write access to /home/hoobs/.hoobs/node_modules/homebridge-myq2
9/22/2020, 4:27:35 PM npm
9/22/2020, 4:27:35 PM  ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/hoobs/.hoobs/node_modules/homebridge-myq2
npm
9/22/2020, 4:27:35 PM  ERR! errno -13
9/22/2020, 4:27:35 PM npm
9/22/2020, 4:27:35 PM ERR! Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/homebridge-myq2'
npm ERR!  [Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/homebridge-myq2'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/hoobs/.hoobs/node_modules/homebridge-myq2'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm
9/22/2020, 4:27:35 PM ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
9/22/2020, 4:27:35 PM 
9/22/2020, 4:27:35 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-09-22T21_27_35_537Z-debug.log
9/22/2020, 4:27:35 PM Plugin "homebridge-myq" updated.
</pre>

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS SD Card

**Comment by jlg89** [comment]
The interesting bit from the log file:

<pre>
30 silly saveTree ├─┬ homebridge-myq@2.3.0
30 silly saveTree │ ├─┬ @types/node-fetch@2.5.7
30 silly saveTree │ │ ├── @types/node@14.6.4
30 silly saveTree │ │ └── form-data@3.0.0
30 silly saveTree │ ├── node-fetch@2.6.1
30 silly saveTree │ └─┬ util@0.12.3
30 silly saveTree │   ├── is-arguments@1.0.4
30 silly saveTree │   ├── is-generator-function@1.0.7
30 silly saveTree │   ├─┬ is-typed-array@1.1.3
30 silly saveTree │   │ └─┬ available-typed-arrays@1.0.2
30 silly saveTree │   │   └── array-filter@1.0.0
30 silly saveTree │   └── which-typed-array@1.1.2
30 silly saveTree ├─┬ homebridge-myq2@2.1.11
30 silly saveTree │ └── node-fetch@2.6.0
30 silly saveTree ├─┬ homebridge-neato@0.7.2
30 silly saveTree │ ├── colors@1.4.0
30 silly saveTree │ └─┬ node-botvac@0.4.0
30 silly saveTree │   └─┬ axios@0.18.1
30 silly saveTree │     ├─┬ follow-redirects@1.5.10
30 silly saveTree │     │ └─┬ debug@3.1.0
30 silly saveTree │     │   └── ms@2.0.0
30 silly saveTree │     └── is-buffer@2.0.4
30 silly saveTree ├─┬ homebridge-tplink-smarthome@5.1.0
30 silly saveTree │ ├── lodash.castarray@4.4.0
30 silly saveTree │ ├── semver@7.3.2
30 silly saveTree │ └─┬ tplink-smarthome-api@2.0.0
30 silly saveTree │   ├── commander@4.1.1
30 silly saveTree │   ├── lodash.defaultto@4.14.0
30 silly saveTree │   ├── lodash.groupby@4.6.0
30 silly saveTree │   ├── lodash.isequal@4.5.0
30 silly saveTree │   ├── loglevel@1.7.0
30 silly saveTree │   ├── promise-queue@2.2.5
30 silly saveTree │   └── tplink-smarthome-crypto@2.0.0
30 silly saveTree └── utf-8-validate@5.0.2
31 verbose stack Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/homebridge-myq2'
32 verbose cwd /home/hoobs/.hoobs
33 verbose Linux 5.4.51-v7+
34 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm" "--no-audit" "--progress=true" "homebridge-myq@2.3.0"
35 verbose node v12.16.3
36 verbose npm  v6.14.4
37 error code EACCES
38 error syscall access
39 error path /home/hoobs/.hoobs/node_modules/homebridge-myq2
40 error errno -13
41 error Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/homebridge-myq2'
41 error  [Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/homebridge-myq2'] {
41 error   errno: -13,
41 error   code: 'EACCES',
41 error   syscall: 'access',
41 error   path: '/home/hoobs/.hoobs/node_modules/homebridge-myq2'
41 error }
42 error The operation was rejected by your operating system.
42 error It is likely you do not have the permissions to access this file as the current user
42 error
42 error If you believe this might be a permissions issue, please double-check the
42 error permissions of the file and its containing directories, or try running
42 error the command again as root/Administrator.
43 verbose exit [ -13, true ]
</pre>

Why is it even trying to track homebridge-myq2@2.1.11? That's the one I removed awhile back, before installing homebridge-myq.

**Comment by jlg89** [comment]
I removed the /home/hoobs/.hoobs/node_modules/homebridge-myq2 placeholder file and clicked the Update button. Now the plugin list shows this.

![Screen Shot 2020-09-23 at 8 43 16 AM](https://user-images.githubusercontent.com/10470394/94020889-07aefc80-fd79-11ea-8ceb-dbc55cc6ce7d.png)

**Comment by jlg89** [comment]
Once I do any plugin actions, install/remove/update, the homebridge-myq2 directory comes back, and myQ2 appears in the plugins list as shown above. Fortunately, though, the myQ plugin appears in the list correctly, with the Details/Uninstall/Configuration controls appearing as they should.

**Comment by askovi** [comment]
This plugin changed its name from myQ2 to myQ. Remove any reference to myQ2 including editing the package.json file to remove the plugin from the dependencies list.

**Comment by jlg89** [comment]
That fixed it.
