### ISSUE TITLE
Can't install any plugins manually

### ISSUE THREAD

**Issue by uncdp** [hoobs-org/HOOBS#815]
Followed the following instructions https://support.hoobs.org/docs/5e763b63e87d1e02b6c19d2b however am getting 
npm WARN checkPermissions Missing write access to /home/hoobs/.hoobs/node_modules/hap-nodejs
later that leads to an error. 
Can't use plugin manager as that does not let me install particular version of the plugin.
Same issue whenever i try to install any plugin as hoobs user.
Already reflashed my hoobs card to have a clean approach to no avail.

Error:
npm WARN checkPermissions Missing write access to /home/hoobs/.hoobs/node_modules/hap-nodejs
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/hoobs/.hoobs/node_modules/hap-nodejs
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR!  [Error: EACCES: permission denied, access '/home/hoobs/.hoobs/node_modules/hap-nodejs'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-09-25T19_19_05_777Z-debug.log

**Comment by mkellsy** [comment]
You need to shutdown the HOOBS instance before installing manually.

**Comment by uncdp** [comment]
was able to install it, perfect. Thanks you.
also instructions here  https://support.hoobs.org/docs/5e763b63e87d1e02b6c19d2b say the following
"Once the plugin installs you will need to stop HOOBS.
~]$ sudo hoobs service stop"
then do more stuff.
