### ISSUE TITLE
Hoobs in a box has stopped

### ISSUE THREAD

**Issue by clkellogg** [hoobs-org/HOOBS#816]
I have been using my Hoobs in a box for a few weeks now.  Everything working great.  Today i tried to turn out lights in HomeKit everything says updating or No Response and in red.  Nothing works.  Tried to restart but cannot access.  What do I need to do to get this working again.

**Comment by askovi** [comment]
If you're able to get into the HOOBS UI, please get your log file from settings -> backup -> log and post it here. 
If you cannot access the UI, make sure the HOOBS Box is connected to your network via the Ethernet cable and that the lights on the HOOBS Box ethernet port are blinking. If they are try accessing the UI with: http://hoobs (no domain)
If that doesn't work, go to your router's admin page and find the local ip address assigned to HOOBS by your router and connect to it like this: http://192.168.x.x (replace with actual ip).
