### ISSUE TITLE
Stuck on Starting Now Screen

### ISSUE THREAD

**Issue by NuLevelness** [hoobs-org/HOOBS#817]
I tried to update to the latest version and now I am stuck on the "starting now" screen. I'm running the Hoobs Box. When I log into the terminal app and try to get the logs, I get, "You must first enable the HOOBS service".

**Comment by NuLevelness** [comment]
> I tried to update to the latest version and now I am stuck on the "starting now" screen. I'm running the Hoobs Box. When I log into the terminal app and try to get the logs, I get, "You must first enable the HOOBS service".

@askovi any advice on how to resolve the issue?

**Comment by askovi** [comment]
This was solved over email.
