### ISSUE TITLE
PurpleAirSensor was not registered by any plugin

### ISSUE THREAD

**Issue by maxmuller** [hoobs-org/HOOBS#821]
Hi,
   I recently installed a PurpleAir sensor at my house. In trying to get it setup in HOOBS I have run into an issue where HOOBS reports it can not find the plugin. Here is the portion of the config (just using the wizard):

    "accessories": [
        {
            "accessory": "PurpleAirSensor",
            "plugin_map": {
                "plugin_name": "homebridge-purpleair-sensor",
                "index": 0
            },
            "conversion": "LRAPA",
            "aqiInsteadOfDensity": true,
            "name": "Outdoor Purple Sensor",
            "sensor": 53459,
            "averages": "10m"
        }
    ],

Here are the logs:

9/30/2020, 9:53:36 AM Loaded plugin "homebridge-camera-ffmpeg".
9/30/2020, 9:53:37 AM Loaded plugin "homebridge-nuheat".
9/30/2020, 9:53:37 AM Loaded plugin "homebridge-purpleair-sensor".
9/30/2020, 9:53:37 AM Loaded plugin "homebridge-screenlogic".
9/30/2020, 9:53:38 AM Loaded plugin "homebridge-tesla".
9/30/2020, 9:53:38 AM [NuHeat] Logging into NuHeat...
9/30/2020, 9:53:38 AM The requested accessory "PurpleAirSensor" was not registered by any plugin.
9/30/2020, 9:53:38 AM Your config.json is requesting the accessory "PurpleAirSensor" which has not been published by any installed plugins.

Any ideas?

**Comment by askovi** [comment]
The plugin doesn’t register the platform properly. We will release an update soon that will address this issue for plugins that register using 2 parameters instead of 3.
