### ISSUE TITLE
Can't connect to hoobs.local on PC

### ISSUE THREAD

**Issue by dothans** [hoobs-org/HOOBS#823]
**Description**
Brand new Hoobs box went to set up hoops for the first time setup administrator account then turned it off for two days and now I can not connect via hoobs.local or direct Ip address and can not connect via iPad as setup was not done,  Hoobs box is hard wired to router.

**Version**
Just received from hoobs

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
None

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Dies HOOBS have an ip in your router’s admin page in the devices list?

**Comment by dothans** [comment]
Yes Hoobs does have an IP address 192.168.1.106 but still comes up with can't connect to server which I have tried
