### ISSUE TITLE
Hoobs Bridge "This device is not responding"

### ISSUE THREAD

**Issue by TheRock89** [hoobs-org/HOOBS#824]
Hi,

1.5 months ago I installed Hoobs on an RPI 4 via an SD card.
And I installed 2 plugins
* Hue
* Eveatmo

Everything worked perfectly until yesterday.
-->Hoobs service stopped.

I restarted the Hoobs service and everything looked fine.
I can control my Homekit devices on the Hoobs Dashboard.
The bridge is running and the log shows no errors ....

BUT in Homekit all devices do not respond.
In the home app under Control Centers & Bridges the "Hoobs Bridge" says "This device is not responding" ?

I tried :
- removed the bridge from home
- Reset connection
- Generate New Username
- load a backup
- RPI de-energized
- I changed the ports and restarted my router
- .............

But Nothing worked

So I decided to reset Hoobs to factory settings.

Homekit code scanned
HUE plugin installed
Restart Hoobs Service
Running! :)
I was able to control the devices in Homekit again and saw their status

But again after ~ 30 min: :(
In the home app under Control Centers & Bridges the Hoobs Bridge says "This device does not answer"
And of course all connected devices from Hoobs ( The other native home kit devices run without problems)

But everything is normal in the Hoobs dashboard and Log?!?!

LOG:
3.10.2020, 14:19:32 Loaded plugin "homebridge-eveatmo".
3.10.2020, 14:19:34 Loaded plugin "homebridge-hue".
3.10.2020, 14:19:34 [Conbee II] config.json: warning: plugin_map: ignoring unknown key
3.10.2020, 14:19:34 [Conbee II] homebridge-hue v0.11.76, node v12.18.4, homebridge v3.2.6
3.10.2020, 14:19:34 [eveatmo platform] Loading new data from API for: weatherstation
3.10.2020, 14:19:34 [Conbee II] searching bridges and gateways
3.10.2020, 14:19:34 HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
3.10.2020, 14:19:35 HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
3.10.2020, 14:19:35 [eveatmo platform] Initializing platform accessory "Home 2 Andre"...
3.10.2020, 14:19:35 [eveatmo platform] Initializing platform accessory "Home 2 Niederschlagsmesser"...
3.10.2020, 14:19:35 [eveatmo platform] Initializing platform accessory "Home 2 Garage"...
3.10.2020, 14:19:35 [eveatmo platform] Initializing platform accessory "Home Wohnzimmer"...
3.10.2020, 14:19:35 [eveatmo platform] Initializing platform accessory "Home Gartenhaus"...
3.10.2020, 14:19:39 [Conbee II] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.78, api v1.16.0
3.10.2020, 14:19:39 [Conbee II] Phoscon-GW: warning: not using recommended deCONZ gateway version 2.5.81
3.10.2020, 14:19:39 [Conbee II] Phoscon-GW: 20 accessories
3.10.2020, 14:19:39 [Conbee II] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Phoscon-GW"...
3.10.2020, 14:19:39 [Conbee II] Phoscon-GW: 2 services
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Stehlampe Büro"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Stehlampe Sarah"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Wandleuchte"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Steckdose"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Daylight"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Button Flur"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Eingangstür"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Schlafzimmer"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Sarah"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Badezimmer"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Schalter Sarah"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Haustür"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Garagentor"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Schalter Büro"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Schalter Schlafzimmer"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Relaiskontakt"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Vibrationssensor"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Keller"...
3.10.2020, 14:19:39 [Conbee II] Initializing platform accessory "Dachboden"...
3.10.2020, 14:19:39 Bridge is running on port 51826.

Can someone help me please?

**Comment by allenlicn** [comment]
How was it resolved? I removed the HOOBS bridge from Home but now unable to add it back.
