### ISSUE TITLE
HOOBS in a box not responding

### ISSUE THREAD

**Issue by jboggs326** [hoobs-org/HOOBS#825]
Hello all
I have a new HOOBS in a box.  Started setup, have a leave it for a few days, and when I returned it has a red light and is not accessible.  The IP address that I used to previously access the UI is no longer available.

I don’t know what to do at this stage.  Please advise.  Thank you

Jay

**Comment by BobbySlope** [comment]
Please check if the box got a new ip adress, check therefore the router ip table. 
The red light is a power on light, so theres everything ok

**Comment by jboggs326** [comment]
I did check via Network Analyzer to see if the box has a new IP address - that’s not it. :(

**Comment by askovi** [comment]
Please send an email to info@hoobs.org with your order number and reference this issue. Someone will assist you via remote support to solve the issue.

**Comment by jboggs326** [comment]
I sent an email and haven’t heard from anyone...
