### ISSUE TITLE
HOOBS.LOCAL won't even open

### ISSUE THREAD

**Issue by ShaLorDen** [hoobs-org/HOOBS#826]
Just purchased a HOOBS kit.  Plugged it into the ethernet and power.  Went to HOOBS.local  as instructed but absolutely noting happens.  Unplugged everything and tried again...and again....and again.  Eventually on the tenth attempt, it connected to HOOBS.LOCAL and I was able to set up my account. Then it froze.  I was not able to do  anything on that page. Tried refreshing the page and I am back to not being able to access HOOBS.LOCAL at all.  I only get a blank black page.

Do I have a defective unit?  I thought this was going to be easy, but so far, absolutely nothing works.  I just get this blank  screen.

<img width="1374" alt="Screen Shot 2020-10-03 at 5 54 26 PM" src="https://user-images.githubusercontent.com/72325503/95004683-61969a00-05a3-11eb-9df6-7df472f884e5.png">

**Comment by askovi** [comment]
Please get the local IP address assigned to hoobs by your router and connect to it like this: http://192.168.x.x

If you still cannot reach the UI, please send an email to info@hoobs.org with your order number and reference this issue. Someone will assist you via remote support.

**Comment by ShaLorDen** [comment]
Thank you for your help. If I could also ask, how do I find the up address assigned by my router?

**Comment by askovi** [comment]
Go to your router’s admin page or app. Address is on the back of your router. Look for devices list or DHCP list

**Comment by dizney2424** [comment]
Having same issue HOOBS is running fine but i can no longer get to the homepage or ssh in
