### ISSUE TITLE
HOOBS.LOCAL won't open

### ISSUE THREAD

**Issue by dizney2424** [hoobs-org/HOOBS#828]
**Description**
unable to access Hoobs.local or ip 
**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Hoobs runs fine just can't access the gui

**Comment by askovi** [comment]
Try just http://hoobs or find the local IP address assigned to HOOBS by your router and connect to it like this: http://192.168.x.x

**Comment by dizney2424** [comment]
I have I get hoobs’s server IP address could not be found. but I can ping the ip

**Comment by askovi** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

You can also try logging in via SSH and get the logs. 

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this to get the logs: `sudo hoobs service log`

**Comment by dizney2424** [comment]
hoobs@hoobs:~ $ sudo hoobs service log
Started HOOBS.
HOOBS listening on port 8080.
Loaded plugin "homebridge-dyson-pure-cool".
Loaded plugin "homebridge-govee".
Loaded plugin "homebridge-myq".
Loaded plugin "homebridge-nest".
Loaded plugin "homebridge-ring".
Loaded plugin "homebridge-samsung-tizen".
Loaded plugin "homebridge-unifi-protect".
[Ring] Configuring cached accessory c9103011-2122-4be2-b75f-79d1f6f3e878 Front Door
[Ring] Configuring cached accessory e0956cd4-d780-4f57-832b-cad7787cc563 Backyard
[Ring] Configuring cached accessory 9b5b0527-69a8-426d-a1b5-7db3f98d9926 Garage Door
[Ring] Configuring cached accessory 83ba24d0-16f9-4e1d-b6ec-61a5327ad763 Downstairs
[Ring] Configuring cached accessory e65d7533-672f-40cc-97c4-ddef47e4788c Upstairs
[Ring] Configuring cached accessory 261d1eb3-fd93-4566-ae9d-c6ec3fb92d5f Mom’s
[Ring] Configuring cached accessory 691c4eee-576f-4347-b3b3-43ae0fe95807 Mom's Backyard
[Nest] Fetching Nest devices.
[DysonPureCoolPlatform] Device credentials not stored, asking Dyson API. If you want to prevent communication with the Dyson API, copy the credentials for each device from the coming log entries to the config.json.
[DysonPureCoolPlatform] Signing in.
[Govee] Plugin has finished initialising. Synching with Govee.
Bridge is running on port 51826.
Living Room TV is running on port 34257.
[Govee] [1] devices loaded from your Govee account.
[Govee]  → [TV Lights] found in your Govee account.
[Govee] Govee setup complete. Don't forget to ⭐️  this plugin on GitHub!
[Door ] myQ API: Successfully connected to the myQ API.
[Door ] myQ API: Discovered device family garagedoor: Garage Door Opener (serial number: CG080060C871, gateway: GW0000078CE0).
[Door ] myQ API: Discovered device family gateway: Home [Chamberlain Ethernet Gateway] (serial number: GW0000078CE0).
[DysonPureCoolPlatform] Signed in.
[DysonPureCoolPlatform] Credentials for device with serial number RT7-US-HKA0377A are: eyJTZXJpYWwiOiJSVDctVVMtSEtBMDM3N0EiLCJOYW1lIjoiTWFzdGVyIGJlZHJvb20iLCJWZXJzaW9uIjoiMjEuMDQuMDMiLCJMb2NhbENyZWRlbnRpYWxzIjoiN09RY250ZWtTcStSczhnOE5oSmxMamsyVXFyd3JhSXFmVG1Xd054WGU0a0tvTkhhL202eUpmODA2YTNaOFd4Tk9Tdk00NnB3OVE4U2xEY0xpZjFWVW1zTmo4Z2NGRmRERzhYSFUyUFBhV0tEcE5Ld1Y2U2trT0toaVB1T2lBc1R3NFBhbEF3UCtoNVpySllTRTh0SllPY3FNMThSRVNsR0xxYit2ck91U1p4aTN4dVN2WTc1aFlnZUlPbzd6S1NzIiwiQXV0b1VwZGF0ZSI6dHJ1ZSwiTmV3VmVyc2lvbkF2YWlsYWJsZSI6ZmFsc2UsIlByb2R1Y3RUeXBlIjoiNDU1IiwiQ29ubmVjdGlvblR5cGUiOiJ3c3MiLCJwYXNzd29yZCI6IlRLSjBkajZFQnR5TG42VSsyRk1jdU83bUpWeE1NaTIzRW5rdTQ1NHI5L1JCMDl3aXVyMjJTLzNTUzhhMEgrL2ZHRnN0Yzh0VVM5MElmTGRHdTFvdy93PT0ifQ==
[DysonPureCoolPlatform] Got devices from the Dyson API.
[UniFi Protect] UDMPRO [UDM-PRO]: Connected to the Protect controller API (address: 192.168.88.1 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Connected to the UniFi realtime update events API.
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Side-Door [UVC G3] (address: 192.168.88.64 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Garage 4k [UVC G4 Pro] (address: 192.168.88.235 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Rear-Of-House [UVC G3] (address: 192.168.88.143 mac: F).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Living-Room-Flex [UVC G3 Flex] (address: 192.168.88.213 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Laundry-Room [UVC G3 Flex] (address: 192.168.88.139 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Family Room [UVC G3 Flex] (address: 192.168.88.185 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Front-Door [UVC G3 Pro] (address: 192.168.88.56 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Yard  [UVC G3 Pro] (address: 192.168.88.68 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Living-Room-Micro [UVC G3 Micro] (address: 192.168.88.95 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Alley [UVC G3] (address: 192.168.88.27 mac: F09FC214BF06).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Garage-Camera [UVC G3 Dome] (address: 192.168.88.76 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Office [UVC G3 Micro] (address: 192.168.88.31 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Patio Door [UVC G3] (address: 192.168.88.33 mac: ).
[UniFi Protect] UDMPRO [UDM-PRO]: Controller refresh interval set to 10 seconds.
[UniFi Protect] UDMPRO [UDM-PRO] Side-Door [UVC G3]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Garage 4k [UVC G4 Pro]: Stream quality configured: Medium.
[UniFi Protect] UDMPRO [UDM-PRO] Rear-Of-House [UVC G3]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Living-Room-Flex [UVC G3 Flex]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Laundry-Room [UVC G3 Flex]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Family Room [UVC G3 Flex]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Front-Door [UVC G3 Pro]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Yard  [UVC G3 Pro]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Living-Room-Micro [UVC G3 Micro]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Alley [UVC G3]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Garage-Camera [UVC G3 Dome]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Office [UVC G3 Micro]: Stream quality configured: High.
[UniFi Protect] UDMPRO [UDM-PRO] Patio Door [UVC G3]: Stream quality configured: High.
(node:658) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
[Ring] Configuring 2 cameras and 2 devices for location "Jersey City" - locationId: dr5rfb-11gdg-0
[Ring] Configuring 3 cameras and 5 devices for location "Linden" - locationId: dr5pnm-11gdg-0
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Nest] initing thermostat "Dining Room Thermostat": deviceId: 09AA01AC37160R4N structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing home_away_sensor "Home Occupied": deviceId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing temp_sensor "Master Bedroom": deviceId: 18B430C8CC74009A structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing temp_sensor "Garage": deviceId: 18B430C59999F456 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing temp_sensor "Office": deviceId: 18B430C3A25EE495 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing temp_sensor "Server Rack": deviceId: 18B430C4935AF69D structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing protect "James Room": deviceId: 6416660000CDB37C structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing protect "Living Room": deviceId: 18B4300000A06F63 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing protect "Kitchen": deviceId: 18B4300000A03317 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing protect "Lanndry Room": deviceId: 18B4300000B50F07 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing protect "Basement Hallway": deviceId: 18B4300000B51887 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing protect "Janiyas Room": deviceId: 6416660000D09D53 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing protect "Master Bedroom": deviceId: 6416660000CDAA84 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing protect "Hallway": deviceId: 18B4300000A01AB8 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Nest] initing protect "Justice Room ": deviceId: 6416660000D09C50 structureId: 5f6f6940-5067-11e7-9ff5-0a3b132d7252
[Ring] Mom’s Detected Motion
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[UniFi Protect] UDMPRO [UDM-PRO]: Controller API connection reset.
[UniFi Protect] UDMPRO [UDM-PRO] Front-Door [UVC G3 Pro]: Unable to retrieve snapshot.
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Door ] myQ API: Connection has been reset.
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom’s Detected Motion
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Front Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[DysonPureCoolPlatform] RT7-US-HKA0377A - set TargetAirPurifierState to 1 with delay
[DysonPureCoolPlatform] RT7-US-HKA0377A - set Active to 1: setting TargetAirPurifierState cancelled
[DysonPureCoolPlatform] RT7-US-HKA0377A - set Active to 1: {"fpwr":"ON","fmod":"FAN"}
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[DysonPureCoolPlatform] RT7-US-HKA0377A - set Active to 0: {"fpwr":"OFF","fmod":"OFF"}
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom’s Detected Motion
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom's Backyard Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Door ] myQ API: Connection has been reset.
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[UniFi Protect] UDMPRO [UDM-PRO]: Connected to the UniFi realtime update events API.
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Door ] myQ API: Connection has been reset.
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] myQ API: Connection has been reset.
[Door ] myQ API: Unable to authenticate. Will retry later.
[Door ] myQ API: Connection has been reset.
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] myQ API: Connection has been reset.
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] myQ API: Connection has been reset.
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom’s Detected Motion
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Front Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom’s Detected Motion
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Ring] Mom’s Detected Motion
[Ring] Garage Door Detected Motion. Loading snapshot before sending event to HomeKit
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5/Login failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to authenticate. Will retry later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[UniFi Protect] request to https://192.168.88.1/proxy/protect/api/bootstrap failed, reason: connect ENETUNREACH 192.168.88.1:443
[UniFi Protect] UDMPRO [UDM-PRO]: Unable to retrieve NVR configuration information from UniFi Protect. Will retry again later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Nest] Nest API call to subscribe to device settings updates returned an error: EAI_AGAIN
[Nest] Retrying in 10 seconds.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Nest] Nest API call to subscribe to device settings updates returned an error: EAI_AGAIN
[Nest] Retrying in 10 seconds.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Nest] Nest API call to subscribe to device settings updates returned an error: EAI_AGAIN
[Nest] Retrying in 10 seconds.
[UniFi Protect] 192.168.88.1: Throttling API calls due to errors with the 10 previous attempts. I'll retry again in 5 minutes.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:694:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:364:12)
    at afterDns (dgram.js:640:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:694:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:364:12)
    at afterDns (dgram.js:640:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Got SIGTERM, shutting down Bridge...
[Door ] request to https://api.myqdevice.com/api/v5.1/Accounts/eb793aed-c250-4c40-b3aa-3f2c48311a96/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
[Door ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.

**Comment by askovi** [comment]
Your service is running on port 8080, so the address is: http://hoobs.local:8080

**Comment by dizney2424** [comment]
Holy crap that was it I can’t believe I missed it thanks so much

**Comment by askovi** [comment]
You're welcome!
