### ISSUE TITLE
Can't update plugins

### ISSUE THREAD

**Issue by brunoDobe** [hoobs-org/HOOBS#829]
I have the issue with Hue and Ring plugins. It shows as update available, I click on it, it tells me the update was successful and nothing. It does not update it and I have the same update option. I tried uninstalling and I get an error saying that it can't be uninstalled. 
I am running Hoobs 3.2.6
Hue 0.11.46
Ring 7.0.0
I also tried from terminal "npm install -g homebridge-ring@7.2.2" and I received non permission errors.
Please advise

**Comment by askovi** [comment]
You are on the old certified versions of the plugins. Remove them like this then search and install the latest ones from the UI:


sudo rm -fR ~/.hoobs/node_modules/homebridge-ring

sudo rm -fR ~/.hoobs/node_modules/homebridge-hue

You might also want to remove them from the package.json file like this:

`sudo nano  ~/.hoobs/package.json`

Find the 2 plugins and remove them from dependencies then save changes with ctrl + s and exit with ctrl + x.

**Comment by czarnyolek** [comment]
Hello
I have the same situation with Bravia Tvos plugin. Cant update and remove. Can you help? What will be commnad for for manual removal?

Or maybe tutorial how can remove after this command: 
sudo nano ~/.hoobs/package.json

Thank you
