### ISSUE TITLE
Build documentation incomplete

### ISSUE THREAD

**Issue by n4zmz** [hoobs-org/HOOBS#830]
**Description**
Current build documentation does not match GitHub repositories.
Could not build docker image.

**Version**
Master branch

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x ] Custom Install
Docker Swarm on Arm64 with Ubuntu 20.04.1

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Ubuntu 20.04.1 aarch64

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Goal is to add Hoobs to swarm cluster using cluster data storage.

**Comment by askovi** [comment]
You can get the docker img from here: [https://hub.docker.com/r/hoobs/hoobs/](https://hub.docker.com/r/hoobs/hoobs/)

**Comment by n4zmz** [comment]
Image alone does not help with the broken build process or getting past the service requirements to deploy in swarm with shared volumes.
