### ISSUE TITLE
Hoobs PiHole /etc/profile borked out of the box

### ISSUE THREAD

**Issue by Webster83** [hoobs-org/HOOBS#832]
After flashing my SD Card with Hoobs and setting that up, the first things I wanted to do on my rPi4 with 8 GB (may as well go big, right?) were to run:

PiHole
Full Rasp. desktop (I'm ok with terminal, but why not get some familiarity with the GUI too? My day job is IT User Services, so I get a lot of "oddball" requests and Pi is definitely getting a foothold in Higher Ed and Scientific/Engineering applications)

PiHole installed properly, or so I thought.
The full Raspbian Desktop package installed well enough, or so I thought.

Had I been paying attention after installing PiHole and rebooting, when I next ssh'd into the box, I'd have seen 2 ominous errors about unexpected EOF in /etc/profile - it took me a hot minute and wondering WTF after my next issue

When I tried to log into the Desktop GUI - nada. Blacked out the screen for a second then returned to the login window. Trying with different (and known incorrect) credentials gave me an error. Ok, return to SSH. AHHH, errors. Errors are bad at this point. sudo nano /etc/profile and see what's afoot. 

Holy hell?!? What is this nonsense.

I saw an unterminated string (ended with $ but no "). I added that, saved and sourced it. More errors. Ok. 
scp'd it to my desktop and ran it through shellcheck... and there were a few errors, unexpected EOFs as I already knew. 
Then I saw the mess of 'if' statements. Turns out, there were a good number (~6) fi missing. I resorted to counting and adding the appropriate number in, tidied up some other things, that according to scriptcheck should be. 

I put the new file in place, sourced it and voila, worked. I could then log in to the GUI Desktop.

I've attached the version that works for me. However, I'd appreciate some eyes on it and some consideration for future inclusion so it's not broken out of the box. 

Edit: New profile.txt added 
[profile.txt](https://github.com/hoobs-org/HOOBS/files/5348660/profile.txt)

**Comment by ptlambert** [comment]
I can confirm this behavior.  Paid for and downloaded HOOBS-3.2.6-ARM7.zip two days ago, etched onto SD card, and followed the directions to "Add a Desktop to HOOBS" here: https://support.hoobs.org/docs/5eabd7dd09210b2a8e851c65

DE was added without errors but after several hours of struggling with a broken GUI logon I happened to notice the same two Bash errors being reported at logon over SSH.

I've attached a cat of my fixed version of the file that includes the erroneous entries commented out.

[cat etc-profile.log](https://github.com/hoobs-org/HOOBS/files/5360665/cat.etc-profile.log)

**Comment by ptlambert** [comment]
I've opened up HOOBS-3.2.6-ARM7.zip in Windows with 7-Zip and extracted the original /cat/profile (see attached).  This original version has PATH properly terminated with an ending double-quote and no $ character present (I almost got that one right, just missed at guessing the last directory in the path).  There are also no errors in the nested if-else-fi statement for PS1 assignment.  And Notepad++ shows only LF characters for line endings.

However this original version does *not* include the HOOBS-branded copyright notice and GPLv3 header.  So it seems that some "branding" process during installation is borking the file.  My concern is for other potentially borked files...

At this point I think I am going to re-attempt a fully-manual install of HOOBS into a stock Raspberry OS image.  I tried that before etching the image to SD but apparently got fouled up with what user names and HTTP ports to use.  Hopefully I've learned enough by stumbling around through this process that I can get it to work this time.

Cheers!

[original profile.txt](https://github.com/hoobs-org/HOOBS/files/5360687/original.profile.txt)

**Comment by ptlambert** [comment]
P.S. Besides this issue with /etc/profile, I noticed that the installed /boot/config.txt has multiple [pi4] and [all] sections (I discovered this during the process of trying to get the GUI logon to work, before noticing the bugs in /etc/profile).  This is apparently not as big a deal, and I don't have a sample of the file state prior to my cleaning it up.  But I've extracted the file from HOOBS-3.2.6-ARM7.zip (see attached) and confirmed that there are no duplicate sections there.

Something's up with the initial Out-Of-Box install process...

[original config.txt](https://github.com/hoobs-org/HOOBS/files/5360710/original.config.txt)

**Comment by Webster83** [comment]
I’m glad to see I’m not the only one. I’m hopeful that with these issues ID’d there can be a fix. I can’t say that the issues with the /boot/config.txt have caused any noticeable issue as I’ve got a working DE without modification to this. Honestly I can see why they’d get overlooked if the idea really was to have a single purpose appliance vs a multifunctional platform.

**Comment by mickelsn** [comment]
@Webster83 You're not the only one with this problem...and the posts you guys made here helped me fix this problem on my HOOBS + Pi-Hole deployment. Please take a look at the [issue I filed against the hoobs-pihole project](https://github.com/hoobs-org/hoobs-pihole/issues/3) -- the `profile` errors were preventing SSL certs from loading on the deployment which created a few problems...fixed thanks to the work you guys shared here~
