### ISSUE TITLE
Ring Plugin Config Issue

### ISSUE THREAD

**Issue by tscholle** [hoobs-org/HOOBS#838]
Hello, I am new to HOOBS and I am having an issue with the ring plugin. I was hoping someone could please give me some guidance. Everything seemed to setup OK and as you can see from the first screen I do see my doorbell called Front Door when I go to that room in Homekit, I think these are keyframes taken periodically. But when I click on that camera to go to a live stream I get a "No Response" message.  I did some searching and thought the issue was I was missing ffmpeg so I found directions and installed that. But, it did not help. What else should I be looking at in my config? I have tried removing the plugin and starting over. I have also tried a full reboot. Based on the log I think something is missing in the config, but I honestly do not know what is missing.

Thank you in advance for your help! 

![IMG_3049](https://user-images.githubusercontent.com/72678371/95685043-bd1fe380-0bb2-11eb-9e74-c46b9910d58a.png)
![IMG_3050](https://user-images.githubusercontent.com/72678371/95685046-c27d2e00-0bb2-11eb-9cdd-99b72220492e.png)
<img width="1057" alt="Screen Shot 2020-10-11 at 10 59 19 AM" src="https://user-images.githubusercontent.com/72678371/95685049-c4df8800-0bb2-11eb-9c01-3b8b2fa42c96.png">

**Comment by askovi** [comment]
This is a known plugin issue that affects inly certain Ring users. Please refer to this issue for more information: https://github.com/dgreif/ring/issues/447
