### ISSUE TITLE
Issue installling Yamaha AVR Plugin

### ISSUE THREAD

**Issue by adrianopery** [hoobs-org/HOOBS#842]
**Description**
After update to version 2.0, I did the update on my Hoobs but after that I'm receiving an error on LOG

13/10/2020 21:37:06 Loaded plugin "homebridge-yamaha-avr".
13/10/2020 21:37:06 The requested platform "yamaha-avr" was not registered by any plugin.
13/10/2020 21:37:06 Your config.json is requesting the platform "yamaha-avr" which has not been published by any installed plugins.

**Expected behavoir**
The plugin is used to control my Yamaha AVR Receiver.

**Plugin name**
Yamaha Avr.
https://github.com/ACDR/homebridge-yamaha-avr/issues/17

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.
I reported the issue to developer but I believe I'm facing any issue on my Hoobs OS.

**Version**
versão HOOBS 3 | 3.2.6
Node Version | 12.14.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
Version 1.04

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "origin": "*",
        "home_setup_id": "X-HM://0023ISYWY8IAB",
        "polling_seconds": 5
    },
    "client": {
        "latitude": "-23.49936054",
        "default_route": "status",
        "country_code": "BR",
        "temp_units": "celsius",
        "theme": "hoobs-light",
        "inactive_logoff": 30,
        "postal_code": "02925080",
        "longitude": "-46.69739199",
        "locale": "pt"
    },
    "bridge": {
        "port": 51826,
        "pin": "031-45-154",
        "username": "5B:6E:00:5F:AB:87",
        "name": "HOOBS"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "yamaha-avr",
            "name": "Yamaha TRS-5790",
            "ip": "192.168.0.140",
            "play_volume": -48,
            "Set input": "Vivo TV",
            "inputs": "Yamaha AVR",
            "plugin_map": {
                "plugin_name": "homebridge-yamaha-avr"
            }
        },
        {
            "platform": "webostv",
            "devices": [
                {
                    "legacyTvService": false,
                    "notificationButtons": [
                        "Movimento detectado na garagem",
                        "Portão social foi aberto",
                        "Portão da garagem foi aberto",
                        "Portão da garagem foi fechado",
                        "Adriana vai pra academia!"
                    ],
                    "mac": "e8-f2-e2-3a-22-52",
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "Home"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "HDMI 1"
                        },
                        {
                            "name": "HDMI 3",
                            "appId": "com.webos.app.hdmi3"
                        },
                        {
                            "name": " Netflix",
                            "appId": "netflix"
                        },
                        {
                            "name": " Amazon",
                            "appId": "amazon.global"
                        },
                        {
                            "name": "YouTube",
                            "appId": "youtube.leanback.v4"
                        }
                    ],
                    "accessory": "webostv",
                    "showInputButtons": false,
                    "pollingInterval": 5,
                    "prefsDir": "~/.webosTv",
                    "plugin_map": {
                        "plugin_name": "homebridge-webos-tv",
                        "index": 0
                    },
                    "infoButtonAction": "INFO",
                    "volumeLimit": 30,
                    "channelControl": false,
                    "name": "TV Sala",
                    "mediaControl": false,
                    "volumeControl": "slider",
                    "ip": "192.168.0.109"
                },
                {
                    "legacyTvService": false,
                    "notificationButtons": [
                        "Movimento detectado na garagem",
                        "Portão social foi aberto",
                        "Portão da garagem foi aberto",
                        "Portão da garagem foi fechado"
                    ],
                    "mac": "ec-f4-51-22-df-86",
                    "inputs": [
                        {
                            "name": " VIVO TV",
                            "appId": "com.webos.app.hdmi3"
                        },
                        {
                            "name": " Amazon",
                            "appId": "amazon"
                        },
                        {
                            "name": " Netflix",
                            "appId": "netflix"
                        },
                        {
                            "name": "HDMI 1",
                            "appId": "com.webos.app.hdmi1"
                        },
                        {
                            "name": "HDMI 2",
                            "appId": "com.webos.app.hdmi2"
                        }
                    ],
                    "accessory": "webostv",
                    "showInputButtons": false,
                    "pollingInterval": 5,
                    "prefsDir": "~/.webosTv",
                    "plugin_map": {
                        "plugin_name": "homebridge-webos-tv",
                        "index": 0
                    },
                    "infoButtonAction": "INFO",
                    "volumeLimit": 30,
                    "channelControl": false,
                    "name": "TV quarto master",
                    "mediaControl": false,
                    "volumeControl": "slider",
                    "ip": "192.168.0.110"
                },
                {
                    "legacyTvService": false,
                    "notificationButtons": [
                        "Movimento detectado na garagem",
                        "Portão social foi aberto",
                        "Portão da garagem foi aberto",
                        "Portão da garagem foi fechado"
                    ],
                    "mac": "ec-f4-51-26-6e-8a",
                    "inputs": [
                        {
                            "name": " VIVO TV",
                            "appId": "com.webos.app.hdmi3"
                        },
                        {
                            "name": " Amazon",
                            "appId": "amazon"
                        },
                        {
                            "name": " Netflix",
                            "appId": "netflix"
                        },
                        {
                            "name": "HDMI 1",
                            "appId": "com.webos.app.hdmi1"
                        },
                        {
                            "name": "HDMI 2",
                            "appId": "com.webos.app.hdmi2"
                        }
                    ],
                    "accessory": "webostv",
                    "showInputButtons": false,
                    "pollingInterval": 5,
                    "prefsDir": "~/.webosTv",
                    "plugin_map": {
                        "plugin_name": "homebridge-webos-tv",
                        "index": 0
                    },
                    "infoButtonAction": "INFO",
                    "volumeLimit": 30,
                    "channelControl": false,
                    "name": "TV quarto da frente",
                    "mediaControl": false,
                    "volumeControl": "slider",
                    "ip": "192.168.0.111"
                }
            ]
        },
        {
            "cameras": [
                {
                    "videoConfig": {
                        "packetSize": 188,
                        "maxStreams": 2,
                        "motion": true,
                        "source": "-re -i rtsp://192.168.0.xxx:554/11",
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxWidth": 1280
                    },
                    "name": "Entrada Social"
                },
                {
                    "videoConfig": {
                        "packetSize": 188,
                        "maxStreams": 2,
                        "source": "-re -i rtsp://192.168.0.xxx:554/11",
                        "maxHeight": 720,
                        "audio": true,
                        "maxFPS": 30,
                        "maxWidth": 1280
                    },
                    "name": "Entrada Externa"
                },
                {
                    "videoConfig": {
                        "maxStreams": 2,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "audio": true,
                        "maxWidth": 1280,
                        "source": "-re -i rtsp://192.168.0.xxx:554/11",
                        "packetSize": 188
                    },
                    "name": "Entrada Varanda"
                },
                {
                    "videoConfig": {
                        "maxStreams": 2,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "audio": true,
                        "maxWidth": 1280,
                        "source": "-re -i rtsp://192.168.0.xxx:554/11",
                        "packetSize": 188
                    },
                    "name": "Garagem Externa"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "platform": "Camera-ffmpeg",
            "name": "Camera ffmpeg"
        },
        {
            "presetSwitches": [
                {
                    "name": "Led Quarto Didi (Party)",
                    "ips": {
                        "2CF432DD777F": "255,255,255"
                    },
                    "preset": "seven_color_strobe_flash",
                    "speed": 60
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-magichome-platform"
            },
            "debug": true,
            "platform": "MagicHome-Platform",
            "lights": [
                {
                    "purewhite": false,
                    "timeout": 10000,
                    "setup": "RGBW",
                    "name": "Led Quarto Didi",
                    "ip": "192.168.0.155"
                }
            ]
        }
    ]
}

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
13/10/2020 21:43:39 Loaded plugin "homebridge-camera-ffmpeg".
13/10/2020 21:43:39 Loaded plugin "homebridge-magichome-platform".
13/10/2020 21:43:39 Loaded plugin "homebridge-webos-tv".
13/10/2020 21:43:40 Loaded plugin "homebridge-yamaha-avr".
13/10/2020 21:43:40 The requested platform "yamaha-avr" was not registered by any plugin.
13/10/2020 21:43:40 Your config.json is requesting the platform "yamaha-avr" which has not been published by any installed plugins.
```

**Additional context**
I cant find the Yamaha config on the Json but I really don't know if I should.
Anyway, the install process is not complete for my devices.

**Comment by eddiedsouza** [comment]
The plugin doesn’t register the platform properly. We will release an update soon that will address this issue for plugins that register using 2 parameters instead of 3.

**Comment by smithjp3** [comment]
Similar issue for me. Can load the plug-in but it does not discover any devices to add to HOOBS/homebridge.

**Comment by adrianopery** [comment]
Its woking now after Hoobs update.

**Comment by ash123-germany** [comment]
"play_volume": -48,
"Set input": "Vivo TV",

This part is not working in my config.jason  , allways the last input goes on 


HOOBS 3 Version | 3.3.2
-- | --
Node Version | 14.15.1
