### ISSUE TITLE
Hoobs isn’t reachable

### ISSUE THREAD

**Issue by ajcascio** [hoobs-org/HOOBS#843]
I had my hoobs up and running for about 2 months.. I swapped routers and reinstalled, now I can’t even get the router to give the hoobs an ip address. I have a starling hub and other devices hooked up. Everything else works great except the hoobs.

**Comment by askovi** [comment]
Make sure you have connectivity. Plug in the ethernet cable first then the power cable. Look for flashing lights next to the ethernet port. Then look for the ip address on your router. 
You can also try connecting it to wifi. The AP should pop up if you connect the power cable without plugging in the ethernet cable.

**Comment by ajcascio** [comment]
I have lights at the Ethernet port on the hoobs box both yellow and green. And have tried multiple times to unplug, then plug in Ethernet first then power and hoobs is still not getting a IP address.

**Comment by ajcascio** [comment]
If you see below, my switch recognizes the starling home hub. But doesn't recognize the hoobs.

![image](https://user-images.githubusercontent.com/53406433/96160265-b90e0180-0ee3-11eb-9cd4-4cebc6778fc6.jpeg)
![image](https://user-images.githubusercontent.com/53406433/96160289-bd3a1f00-0ee3-11eb-899b-e85f064bef13.jpeg)

**Comment by ajcascio** [comment]
Is this an official Hoobs support? I just see canned generic responses and none really tailored to the actual problem. Like this guys response to mine stating to look up my ip....when I mentioned in the OP that I'm not receiving an IP address from the hoobs. Does Hoobs have an actual support site?

**Comment by ajcascio** [comment]
> Make sure you have connectivity. Plug in the ethernet cable first then the power cable. Look for flashing lights next to the ethernet port. Then look for the ip address on your router. 
> 
> You can also try connecting it to wifi. The AP should pop up if you connect the power cable without plugging in the ethernet cable. 

Hoobs box won't generate WiFi either.

**Comment by askovi** [comment]
If you're not getting an IP address for HOOBS on your router's admin page, it might indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

You can download the img file free or charge from here: https://github.com/hoobs-org/hoobs-build/releases/download/v3.2.6/HOOBS-3.2.6-ARM7.zip
