### ISSUE TITLE
HOOBS restarts when accessing web interface

### ISSUE THREAD

**Issue by ahnyerkeester** [hoobs-org/HOOBS#844]
**Description**
When I try to log into HOOBS via the web interface, it restarts the service. As long as I'm connected to the web interface, the service just keeps restarting.

**Version**
I'm not positive because I can't access the interface to check, but last time I saw it it was 3.2.6.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
macOS Catalina 10.15.7 running on a late 2012 MacMini with 16GB memory.

**List your plugins**
Roomba
Ring
Chamberlain

**Post your config**
```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYNLOC",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "6E:DC:7A:A8:D7:44"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": [],
    "package_manager": "npm",
    "system": "hoobs"
}%    
```

**Post your log**
Can't access the log through the web interface because it restarts before it shows the log.

**Additional context**
The service runs fine as along as I don't try to access the web interface.

**Comment by askovi** [comment]
Please try getting the HOOBS logs using the terminal with: `sudo hoobs service log` while trying to access the web interface.

**Comment by ahnyerkeester** [comment]
'''
You must first enable the HOOBS service
'''
Rats.

**Comment by askovi** [comment]
Please see here: https://support.hoobs.org/docs/5e763f09e87d1e02b6c19d39
