### ISSUE TITLE
When adressing hoobs.local I get Phoscon instead

### ISSUE THREAD

**Issue by mastrigt** [hoobs-org/HOOBS#845]
**Description**
After installing Deconz and Phoscon on my starterbox I can't reach the Hoobs application anymore and I get Phoscon instead
**Version**
3.?

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Just the yeelight wifi plugin

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
You must setup a different port for phoscon or for HOOBS. By default they both run on port 80. In HOOBS you can change the server port in the UI, but if you cannot access it anymore, you will have to do it via ssh:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this command: `sudo nano /home/hoobs/.hoobs/etc/config.json`
Edit server port from 80 to 8080. 
Save with ctrl +s and exit file with ctrl + x.

3. Restart the HOOBS service with command: sudo hoobs service restart

4. Access HOOBS via http://hoobs.local:8080

**Comment by mastrigt** [comment]
Thank you so much for your clear answer. It worked and was easy. Would be nice to have this in the FAQ's!
