### ISSUE TITLE
Blank page in Mi Philips Light Plugin and Mi Philips Moonlight Plugin

### ISSUE THREAD

**Issue by Ka111n** [hoobs-org/HOOBS#847]
**Description**
I have Absolutely blank page in plugins settings: Philips Light Plugin and Mi Philips Moonlight Plugin. Another plugins works normal (Roborock and Yeelight). I tried a different browser and tried to open the settings from another device. No changes. Please help me!

**Version**
Current Version: 3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
macOS Catalina 10.15.7. Hoobs installed on Raspberry PI Zero W

**List your plugins**
Mi Philips Light 
Mi Philips Moonlight

**Post your config**
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY93PI",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "ru",
        "temp_units": "celsius",
        "country_code": "RU",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "E6:3F:B7:55:83:4F"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}

**Post your log**
17.10.2020, 01:30:38 HOOBS listening on port 80.
17.10.2020, 01:30:58 Loaded plugin "homebridge-mi-philips-light".
17.10.2020, 01:31:02 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
17.10.2020, 01:31:03 Bridge is running on port 51826.
17.10.2020, 01:35:51 + homebridge-mi-philips-moonlight@1.0.1
added 2 packages from 1 contributor in 34.428s
17.10.2020, 01:35:54 
32 packages are looking for funding
  run `npm fund` for details
17.10.2020, 01:35:54 Plugin "homebridge-mi-philips-moonlight" installed.
17.10.2020, 01:35:55 Got SIGINT, shutting down Bridge...
17.10.2020, 01:36:03 Loaded plugin "homebridge-mi-philips-light".
17.10.2020, 01:36:03 Loaded plugin "homebridge-mi-philips-moonlight".
17.10.2020, 01:36:03 /home/hoobs/.hoobs/etc/config.json
17.10.2020, 01:36:06 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
17.10.2020, 01:36:07 Bridge is running on port 51826.
17.10.2020, 01:37:33 Got SIGINT, shutting down Bridge...
17.10.2020, 01:37:41 Loaded plugin "homebridge-mi-philips-light".
17.10.2020, 01:37:41 Loaded plugin "homebridge-mi-philips-moonlight".
17.10.2020, 01:37:41 /home/hoobs/.hoobs/etc/config.json
17.10.2020, 01:37:44 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
17.10.2020, 01:37:45 Bridge is running on port 51826.

**Additional context**
<img width="2560" alt="Снимок экрана 2020-10-17 в 01 39 46" src="https://user-images.githubusercontent.com/73002423/96319951-ba414a80-1019-11eb-95e5-4e0a49601c82.png">
<img width="2560" alt="Снимок экрана 2020-10-17 в 01 39 51" src="https://user-images.githubusercontent.com/73002423/96319962-bf05fe80-1019-11eb-9625-85c89e90f134.png">
<img width="2560" alt="Снимок экрана 2020-10-17 в 01 39 59" src="https://user-images.githubusercontent.com/73002423/96319964-c0372b80-1019-11eb-98df-5f7c98f784af.png">

**Comment by askovi** [comment]
These plugins do not yet have a config schema and must be configured via the Advanced tab in HOOBS. You can request a config schema to be added by opening an issue with the plugin developer on their github:
https://github.com/YinHangCode/homebridge-mi-philips-light/issues
