### ISSUE TITLE
Upgraded plug-in not showing as available on HOOBS

### ISSUE THREAD

**Issue by rhuss2** [hoobs-org/HOOBS#848]
**Description**
The Bond plug-in has been update to version 3.x , but still is version 2.8 on HOOBS

**Expected behavoir**
Bond plug-in would be available shortly after release. 

**Plugin name**
Bond

**Please report the issue to the plugin developer**
Already did, developer doesn’t know how updates start to appear in HOOBS

**Version*
2.8 & 3.x

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
It has now been updated. You can update from the HOOBS UI.
