### ISSUE TITLE
homebridge-tplink-smarthome 6.0.0 error

### ISSUE THREAD

**Issue by jlg89** [hoobs-org/HOOBS#850]
**Description**
The installed version of homebridge-tplink-smarthome is 5.1.0 and is working properly. The plugins page shows that an update is available, and clicking the "Update" button installs the update successfully. But then the log file shows:

10/17/2020, 3:36:58 PM Loaded plugin "homebridge-tplink-smarthome".
10/17/2020, 3:36:58 PM The requested platform "TplinkSmarthome" was not registered by any plugin.
10/17/2020, 3:36:58 PM Your config.json is requesting the platform "TplinkSmarthome" which has not been published by any installed plugins.

...and then it removes all of the "orphaned" accessories, which also removes any scenes and other configurations in HomeKit that use those accessories.

Uninstalling the plugin, then reinstalling it, fixes the issue, though it doesn't restore the lost HomeKit configs. Apparently the installer is still pulling version 5.1.0 of the plugin, whereas the updater pulls the latest version, 6.0.0.

**Version**
HOOBS 3.2.6
Node Version 12.16.3
Hardware: BCM2835 - Pi 3 Model B+
Raspbian 10 "buster"

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**Comment by mcalderin** [comment]
Same issue.  Running custom install.

**Comment by askovi** [comment]
The plugin has been reverted temporarily to the working version. Simply uninstall and reinstall the plugin. A HOOBS update is coming up next week which will add compatibility for v6.0.0.
