### ISSUE TITLE
Docker version : can't access to the UI

### ISSUE THREAD

**Issue by Zazou89** [hoobs-org/HOOBS#853]
**Description**
Hello, I use HOOBS docker on UnRAID. I tried to access to teh UI but isn't reachable. 

![image](https://user-images.githubusercontent.com/206181/96514192-95401800-1263-11eb-96ce-4fabdd3a54ae.png)

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- Docker on UnRAID

**Post your config**
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='HOOBS' --net='bridge' -e TZ="Europe/Paris" -e HOST_OS="Unraid" -p '51826:51826/tcp' -p '4873:8080/tcp' -v '/mnt/user/appdata/hoobs/':'/hoobs':'rw' --restart=unless-stopped 'hoobs/hoobs' 
```

**Comment by mkellsy** [comment]
It looks like our Docker Hub repo got corrupt somehow. I was able to rebuild and re-push a new image. However, we are abandoning the latest tag, so you must pull with the version like this.

```
docker pull hoobs/hoobs:3.2.8
```

**Comment by mkellsy** [comment]
We were using HB 1.2.3 by mistake. It was pulled. The HB version should be 1.1.6.

Related issue https://github.com/homebridge/homebridge/issues/2681

3.2.9 should fix your issues.

**Comment by Galiwyx** [comment]
Hello, 
I updated the docker version but the problem persists.

**Comment by mkellsy** [comment]
Try changing this 4873:8080 to this 4873:80
