### ISSUE TITLE
homebridge-tplink-smarthome 6.1.0 error

### ISSUE THREAD

**Issue by recoi1er** [hoobs-org/HOOBS#856]
**Description**
Same issue as here: https://github.com/hoobs-org/HOOBS/issues/850
 I installed the plugin brand new with the 6.1.0 version for the first time, setup up the config and this is what happens in the log:

- The requested platform "TplinkSmarthome" was not registered by any plugin.
- Your config.json is requesting the platform "TplinkSmarthome" which has not been published by any installed plugins.

**Expected behavoir**
It's supposed to load the plugin into HomeKit

**Plugin name**
https://plugins.hoobs.org/plugin/homebridge-tplink-smarthome

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.
https://github.com/plasticrake/homebridge-tplink-smarthome/issues/149

**Version**
3.2.6
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
HOOBS 3.2.6

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": “REMOVED”,
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hazed-infused",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "REMOVED",
        "latitude": "REMOVED",
        "longitude": "REMOVED"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": “REMOVED”,
        "username": "REMOVED"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Pihole",
            "plugin_map": {
                "plugin_name": "homebridge-pihole",
                "index": 0
            },
            "name": "Pihole",
            "ssl": false,
            "host": "localhost",
            "port": 80,
            "baseDirectory": "/admin/",
            "time": 0,
            "reversed": false,
            "logLevel": 1,
            "auth": "REMOVED"
        },
        {
            "accessory": "Roomba",
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            },
            "name": "Roomba",
            "model": "i8+",
            "blid": "REMOVED",
            "robotpwd": "REMOVED",
            "ipaddress": "192.168.1.248",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": false,
            "cacheTTL": 30
        }
    ],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Shop Cam",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://REMOVED@192.168.1.53/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://REMOVED@192.168.1.53/live -vframes 1 -r 1",
                        "vcodec": "copy",
                        "maxStreams": 2,
                        "motion": true,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "audio": true,
                        "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
                    }
                },
                {
                    "name": "Front Door",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://REMOVED@192.168.1.52/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://REMOVED@192.168.1.52/live -vframes 1 -r 1",
                        "vcodec": "copy",
                        "maxStreams": 2,
                        "motion": true,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "audio": true,
                        "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
                    }
                },
                {
                    "name": "Garage Indoor Cam",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://REMOVED@192.168.1.51/live",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://REMOVED@192.168.1.51/live -vframes 1 -r 1",
                        "vcodec": "copy",
                        "maxStreams": 2,
                        "motion": true,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "audio": true,
                        "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
                    }
                }
            ]
        },
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            },
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": false,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "switchModels": [
                "HS100",
                "KP400"
            ],
            "broadcast": "255.255.255.0",
            "pollingInterval": 30,
            "transport": "tcp",
            "timeout": 15,
            "waitTimeUpdate": 100
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
10/21/2020, 3:26:30 PM Got SIGINT, shutting down Bridge...
10/21/2020, 3:26:34 PM Loaded plugin "homebridge-camera-ffmpeg".
10/21/2020, 3:26:34 PM Loaded plugin "homebridge-pihole".
10/21/2020, 3:26:34 PM Loaded plugin "homebridge-roomba-stv".
10/21/2020, 3:26:34 PM Loaded plugin "homebridge-tplink-smarthome".
10/21/2020, 3:26:34 PM Loaded plugin "homebridge-twinkly".
10/21/2020, 3:26:35 PM The requested platform "TplinkSmarthome" was not registered by any plugin.
10/21/2020, 3:26:35 PM Your config.json is requesting the platform "TplinkSmarthome" which has not been published by any installed plugins.
10/21/2020, 3:26:35 PM [Roomba] Enabling autoRefresh every 30 seconds
10/21/2020, 3:26:35 PM [Camera FFmpeg] [Shop Cam] Configuring cached bridged accessory...
10/21/2020, 3:26:35 PM [Camera FFmpeg] [Front Door] Configuring cached bridged accessory...
10/21/2020, 3:26:35 PM [Camera FFmpeg] [Garage Indoor Cam] Configuring cached bridged accessory...
10/21/2020, 3:26:35 PM Bridge is running on port 51826.
```

**Additional context**

**Comment by askovi** [comment]
Update HOOBS to 3.2.8 from the dashboard.

**Comment by recoi1er** [comment]
> Update HOOBS to 3.2.8 from the dashboard.

Do I need to update the Node version as well?

**Comment by askovi** [comment]
Not required but if you want to get to the latest LTS version use this command:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

**Comment by recoi1er** [comment]
> Not required but if you want to get to the latest LTS version use this command:
> 
> `wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

Ok did that too but after the HOOBS update, no change. After the Node update, no change still nothing showing up in Home app. The log is different now though:

10/21/2020, 3:42:38 PM Got SIGINT, shutting down Bridge...
10/21/2020, 3:42:43 PM Loaded plugin 'homebridge-tplink-smarthome'
10/21/2020, 3:42:43 PM [10/21/2020, 3:42:43 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
10/21/2020, 3:42:44 PM [TplinkSmarthome] Initializing TplinkSmarthome platform...
10/21/2020, 3:42:44 PM [TplinkSmarthome] homebridge-tplink-smarthome v6.1.0, node v12.16.3, homebridge v1.2.3
10/21/2020, 3:42:44 PM Loading 2 accessories...
10/21/2020, 3:42:44 PM Bridge is running on port 51826.

**Comment by askovi** [comment]
Logs look good. Try restarting the service and check your accessories tab.

**Comment by Merexor** [comment]
Hello I have this problem too. The old Version search without a config, but with the new Plugin i have this error: 

• The requested platform "TplinkSmarthome" was not registered by any plugin.
• Your config.json is requesting the platform "TplinkSmarthome" which has not been published by any installed plugins.

And i tried different things .. without success. 
I Hope somebody Can help me.

**Comment by recoi1er** [comment]
> Hello I have this problem too. The old Version search without a config, but with the new Plugin i have this error:
> 
> • The requested platform "TplinkSmarthome" was not registered by any plugin.
> • Your config.json is requesting the platform "TplinkSmarthome" which has not been published by any installed plugins.
> 
> And i tried different things .. without success.
> I Hope somebody Can help me.

I resolved this by updating HOOBS to 3.2.8 (I also updated the Node) and those log messages went completely away.

**Comment by mkellsy** [comment]
I am closing since the OP is up and running.

**Comment by d4e5v8** [comment]
> Update HOOBS to 3.2.8 from the dashboard.

And... how are we supposed to know that please?

**Comment by recoi1er** [comment]
> > Update HOOBS to 3.2.8 from the dashboard.
> 
> And... how are we supposed to know that please?

You open hoobs.local and hit update
