### ISSUE TITLE
Bridge service not started -> Accessories must be created with a non-empty displayName.

### ISSUE THREAD

**Issue by Raka74** [hoobs-org/HOOBS#857]
I’m running Hoobs on docker / Synololgy.
All was running fine - I had harmony and ring plugins installed.

Watchtower updated container to the latest version - now the service doesn’t start anymore.
This is in the log:

22-10-2020 01:53:16 AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
22-10-2020 01:53:16 at Bridge.Accessory [as constructor] (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1092:25)
22-10-2020 01:53:16 at new Bridge (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Bridge.js:26:28)
22-10-2020 01:53:16 at new Server (/usr/src/hoobs/bridge/server.js:86:23)
22-10-2020 01:53:16 at module.exports (/usr/src/hoobs/bridge/cli.js:47:20)
22-10-2020 01:53:16 at Object.<anonymous> (/usr/src/hoobs/bin/hoobs:63:81)
22-10-2020 01:53:16 at Module._compile (internal/modules/cjs/loader.js:1015:30)
22-10-2020 01:53:16 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
22-10-2020 01:53:16 at Module.load (internal/modules/cjs/loader.js:879:32)
22-10-2020 01:53:16 at Function.Module._load (internal/modules/cjs/loader.js:724:14)
22-10-2020 01:53:16 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
22-10-2020 01:53:16 at internal/main/run_main_module.js:17:47 {
22-10-2020 01:53:16 generatedMessage: false,
22-10-2020 01:53:16 code: 'ERR_ASSERTION',
22-10-2020 01:53:16 actual: undefined,
22-10-2020 01:53:16 expected: true,
22-10-2020 01:53:16 operator: '=='

Removing plugins didn’t help.
Removed complete container and config folders , reinstalled without any plugins - still no go.

Any suggestions?

**Comment by pmppk** [comment]
Same issue for me with the latest container

**Comment by rhuss2** [comment]
Same here

**Comment by izkorn** [comment]
same here

**Comment by mkellsy** [comment]
Can someone post their config.json.

I need to look at the bridge config.

**Comment by mkellsy** [comment]
It looks like our Docker Hub repo got corrupt somehow. I was able to rebuild and re-push a new image. However, we are abandoning the latest tag, so you must pull with the version like this.

```
docker pull hoobs/hoobs:3.2.8
```

**Comment by pmppk** [comment]
After pulling hoobs/hoobs:3.2.8 I am now hitting a different error:
`10/21/2020, 9:52:05 PM HOOBS listening on port 80.
10/21/2020, 9:52:06 PM No plugins installed.
10/21/2020, 9:52:06 PM TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:82:11)
    at Bridge.Accessory._this.publish (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:507:18)
    at Server.publishBridge (/usr/src/hoobs/bridge/server.js:193:21)
    at /usr/src/hoobs/bridge/server.js:162:53
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Server.start (/usr/src/hoobs/bridge/server.js:162:9)`

**Comment by askovi** [comment]
What's your node version?

**Comment by mkellsy** [comment]
We were using HB 1.2.3 by mistake. It was pulled. The HB version should be 1.1.6.

Related issue https://github.com/homebridge/homebridge/issues/2681

3.2.9 should fix your issues.

**Comment by izkorn** [comment]
My node version is 12.19.0

**Comment by Raka74** [comment]
I updated to 3.2.9 but now I get: 


AssertionError [ERR_ASSERTION]: The supplied username (undefined) is not valid (expected a format like 'XX:XX:XX:XX:XX:XX' with XX being a valid hexadecimal string). Note that, if you had this accessory already paired with the invalid username, you will need to repair the accessory and reconfigure your services in the Home app. Using an invalid username will lead to unexpected behaviour. | stdout
-- | --


(Clean install)

**Comment by pmppk** [comment]
Same for me with 3.2.9

**Comment by rhuss2** [comment]
Same for me with 3.2.9 on docker

**Comment by gbougiakas** [comment]
Same here with 3.2.9 on docker

**Comment by gbougiakas** [comment]
@mkellsy @askovi should be asleep by now maybe @BobbySlope can post a newer version that works or restore one before 3.2.8 that also worked

**Comment by enrogue** [comment]
As stated in another thread. Hoobs is down for me. (Synology Docker).
3.28 - Service wont start
3.29 - container wont start

Same error messages the rest of you are getting.

**Comment by mkellsy** [comment]
Re-pull 3.2.9. There was an error pushing it.

**Comment by pmppk** [comment]
No longer seeing this issue after re-pulling 3.2.9. Thanks for being so responsive and getting this resolved!

**Comment by rhuss2** [comment]
I can also confirm that after re-pulling 3.2.9, there is no issue and service is up and running correctly.
________________________________

**Comment by enrogue** [comment]
Everything is running in 3.2.9 EXCEPT Accessories not updating in Homekit. I removed the Hoobs Bridge but CANNOT re-add it.. 

Homekit error code : 2502 when I try an add the HOOBS bridge to Apple Home(kit).

Anyone else having issues?? (everything was working perfectly until 24 hours ago!)

**Comment by mkellsy** [comment]
In Help there is a Reset Connection button this will remove the persist files. It will rebuild after. Then you should be able to add it.

This is the same process as in HB 1.1.6.

**Comment by enrogue** [comment]
> In Help there is a Reset Connection button this will remove the persist files. It will rebuild after. Then you should be able to add it.
> 
> This is the same process as in HB 1.1.6.

Thank you.
1_ Tried the above
2_ Tried remaning the service name in Configuration, Apple Home
3_ Tried changing the Home PIN in configuration, apple home
PS NO ERRORS in the logs

Very strange. I assume you aren't having this issues with 3.2.9 then! agghh

**Comment by enrogue** [comment]
> > In Help there is a Reset Connection button this will remove the persist files. It will rebuild after. Then you should be able to add it.
> > This is the same process as in HB 1.1.6.
> 
> Thank you.
> 1_ Tried the above
> 2_ Tried remaning the service name in Configuration, Apple Home
> 3_ Tried changing the Home PIN in configuration, apple home
> PS NO ERRORS in the logs
> 
> Very strange. I assume you aren't having this issues with 3.2.9 then! agghh

Just wiped out my hoobs data folder, and did a nice, clean fresh install. Still unable to add HOOBS to Apple Home - "Accessory Not Found"... "aggghhhhhh

**Comment by enrogue** [comment]
> > > In Help there is a Reset Connection button this will remove the persist files. It will rebuild after. Then you should be able to add it.
> > > This is the same process as in HB 1.1.6.
> > 
> > 
> > Thank you.
> > 1_ Tried the above
> > 2_ Tried remaning the service name in Configuration, Apple Home
> > 3_ Tried changing the Home PIN in configuration, apple home
> > PS NO ERRORS in the logs
> > Very strange. I assume you aren't having this issues with 3.2.9 then! agghh
> 
> Just wiped out my hoobs data folder, and did a nice, clean fresh install. Still unable to add HOOBS to Apple Home - "Accessory Not Found"... "aggghhhhhh

All my fault.. big surprise.
I forgot to check "Use the same network as Docker Host" when I created the container.. dummy. sorry to all. 
Self-solved.

**Comment by mkellsy** [comment]
I am closing this issue due to everyone except the op have reported that 3.2.9 is working for them.

To recap, to fix this either upgrade to 3.2.9 or re-pull the 3.2.9 image.
