### ISSUE TITLE
Docker images should be tagged with version numbers in addition to 'latest'

### ISSUE THREAD

**Issue by pmppk** [hoobs-org/HOOBS#858]
In order to facilitate an easy rollback to a specific version of the docker image, images should be tagged with an immutable version number, in addition to always pointing 'latest' to the latest version.

This is especially important for cases when an update may break functionality, as the 3.2.8 update has.

**Comment by mkellsy** [comment]
We have been having problems with our Docker Hub repo. I just cleared it out and am rebuilding it from scratch.

**Comment by mkellsy** [comment]
I was able to rebuild this. I also removed the latest tag. This way there is nothing gets overwritten.

**Comment by pmppk** [comment]
Thanks!
