### ISSUE TITLE
When ever I install any new Plugin the Home Bridge service stopped working

### ISSUE THREAD

**Issue by kasar10** [hoobs-org/HOOBS#860]
When ever I install any new Plugin the Home Bridge service stopped working. When I uninstall the Plugin the service comes back up. I wanted to know whether it is a known issue or I'm missing something else. Please help me on resolving the issue.

**Comment by askovi** [comment]
Please follow the bug report template.

**Comment by mkellsy** [comment]
This depends on the plugins you are trying to install. There are 3,000+ plugins. Some plugins need configuration, so when the plugin is installed the bridge might not start back up until it is configured.
