### ISSUE TITLE
CPU temperature Error after Update

### ISSUE THREAD

**Issue by shroudy86** [hoobs-org/HOOBS#861]
**Description**
After updating Homebridge Core to 3.2.8 and/or 3.2.7 the CPU temperature of the Raspberry Pie is no longer displayed in the Homemanager App. Instead it says „Server Error“. This worked before the update. Resetting the app or restarting of the Pie did not solve the problem.

**Version**
3.2.8 / 3.2.7

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Previous version**
3.2.6

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

- Delay Switch
- Rademacher Homepilot

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

**Post your log**
You can get the log from the intercafe. This is in the Log section.

**Additional context**

**Comment by mkellsy** [comment]
We removed the temp from the API because it was highly inaccurate. It was causing many issues.

**Comment by shroudy86** [comment]
Ah ok, I see. I never had any problems with it. Do you know when it will be removed in the Homemanager App?

Maybe it would be good if such changes would be listed in the changelog.

Anyway, thanks for the quick answer, at least I know now that I didn't break anything :-).
