### ISSUE TITLE
Services wont start after upgrading from 3.2.6 to 3.2.8

### ISSUE THREAD

**Issue by zanderroth** [hoobs-org/HOOBS#862]
**Description**
Services wont start after upgrading from 3.2.6 to 3.2.8

**Version**
HOOBS Version 3.2.8
Node Version 12.14.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
3.2.6

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card 
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Pi 3 Model B+

**List your plugins**
Bond
Chamerlain
Dyson Link
Hubitat Makerapi
Mysmartblinds Bridge
Orbit Bhyve

**Post your config**
[config.txt](https://github.com/hoobs-org/HOOBS/files/5425164/config.txt)

**Post your logs**
[logs.txt](https://github.com/hoobs-org/HOOBS/files/5425556/logs.txt)

**Comment by askovi** [comment]
Please post your logs

**Comment by zanderroth** [comment]
> Please post your logs

Updated with logs

**Comment by JeriMind** [comment]
i have the same error, only with another plugin "Alexa":

22.10.2020, 22:19:35 Error: The requested platform 'Alexa' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:365:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:351:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:87:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
22.10.2020, 22:19:35 Got SIGTERM, shutting down Bridge...

**Comment by mkellsy** [comment]
Thanks for reporting this. I found the issue. Will be fixed in 3.2.9.

**Comment by JeriMind** [comment]
Thanks. So now Hoobs don't quit. But Alexa don't work. Any Ideas?

23.10.2020, 11:05:40 [Alexa] INFO: DeviceList empty feature not enabled or config error in deviceListHandling
23.10.2020, 11:05:40 [Alexa] alexaDiscovery - returned 21 devices
23.10.2020, 11:05:46 [Alexa] ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.
23.10.2020, 11:06:11 [Alexa] ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.



{
            "platform": "Alexa",
            "plugin_map": {
                "plugin_name": "homebridge-alexa"
            },
            "name": "Alexa",
            "routines": false,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "username": "username",
            "password": "password",
            "pin": "111-444-111",
            "deviceList": [],
            "combine": [],
            "speakers": []
 }

**Comment by zanderroth** [comment]
Upgrading to 3.2.9 resolved the issue.
