### ISSUE TITLE
Hoobs wont load after 3.2.8

### ISSUE THREAD

**Issue by twennywonn** [hoobs-org/HOOBS#864]
It appeared to me like the MyQ plugin was causing an issue but I cannot uninstall it.  

Plugins are
myQ
Harmony
Dyson Pure Cool
SmartThings V2
 All on the latest updates

[logs (1).txt](https://github.com/hoobs-org/HOOBS/files/5427358/logs.1.txt)

**Comment by askovi** [comment]
Remove Chamberlain from your config. 
Then install the new myq plugin homebridge-myq

**Comment by twennywonn** [comment]
I don’t know where to remove it from it’s not in my plugins list. Removed in months ago and swapped in for the MyQ plug-in.  

Donavan Lozo

**Comment by askovi** [comment]
Check your advanced config. You can post your config here if you want but remove any passwords and access tokens.

**Comment by twennywonn** [comment]
I see chamberlain in there but its not in my plugin list an I don't know
how to delete it from the json without breaking it

{

    "server": {

        "port": 8080,

        "autostart": 0,

        "home_setup_id": "X-HM://0023ISYWY374B",

        "polling_seconds": 2,

        "origin": "*"

    },

    "client": {

        "default_route": "status",

        "inactive_logoff": 30,

        "theme": "hoobs-light",

        "locale": "en",

        "temp_units": "fahrenheit",

        "country_code": "US",

        "postal_code": “xx”

    },

    "bridge": {

        "name": "HOOBS",

        "username": “xx:22:3D:E3:CE:30",

        "port": 51826,

        "pin": "031-45-154"

    },

    "description": "This file is used for plugin configuration.",

    "ports": {},

    "accessories": [

        {

            "name": "Garage Door",

            "username": “xxx”,

            "password": “xxx”,

            "accessory": "Chamberlain"

        },

        {

            "name": "Ring Alarm",

            "stateful": true,

            "reverse": false,

            "time": 1000,

            "accessory": "DummySwitch"

        },

        {

            "accessory": "DummySwitch",

            "plugin_map": {

                "plugin_name": "homebridge-dummy",

                "index": 0

            },

            "stateful": true,

            "reverse": false,

            "time": 1000,

            "name": "Door Auto Lock"

        }

    ],

    "platforms": [

        {

            "name": "Harmony Purifier",

            "hubIP": "192.168.1.58",

            "otherPlatforms": [

                {

                    "name": "Harmony Living Room",

                    "hubIP": "192.168.1.59"

                }

            ],

            "platform": "HarmonyHubWebSocket"

        },

        {

            "platform": "SmartThings-v2",

            "name": "SmartThings-v2",

            "app_url": "
https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/
",

            "app_id": “xxx”,

            "access_token": “xxx”,

            "temperature_unit": "F",

            "validateTokenId": false,

            "logConfig": {

                "debug": false,

                "showChanges": false,

                "hideTimestamp": false,

                "hideNamePrefix": false,

                "file": {

                    "enabled": true,

                    "level": "Good"

                }

            },

            "plugin_map": {

                "plugin_name": "homebridge-smartthings-v2"

            },

            "direct_port": 8000,

            "local_commands": true

        },

        {

            "platform": "DysonPureCoolPlatform",

            "plugin_map": {

                "plugin_name": "homebridge-dyson-pure-cool"

            },

            "username": “xxx”,

            "countryCode": "US",

            "password": “xxx”,

            "updateInterval": 120,

            "devices": [

                {

                    "ipAddress": "192.168.1.79",

                    "serialNumber": “xxx”,

                    "enableAutoModeWhenActivating": false,

                    "isNightModeEnabled": true,

                    "isJetFocusEnabled": false,

                    "isTemperatureSensorEnabled": false,

                    "isHumiditySensorEnabled": false,

                    "isAirQualitySensorEnabled": false,

                    "isSingleAccessoryModeEnabled": true

                }

            ]

        },

        {

            "platform": "myQ",

            "plugin_map": {

                "plugin_name": "homebridge-myq"

            },

            "password": “xxx”,

            "email": “xxx”

        }

    ]

}

**Comment by askovi** [comment]
Delete specifically these lines only:

`  {

            "name": "Garage Door",

            "username": “xxx”,

            "password": “xxx”,

            "accessory": "Chamberlain"

        },`

**Comment by twennywonn** [comment]
Thank you so much that resolved my issue.
