### ISSUE TITLE
Error Updating HOOBS Certified Nest Plugin (homebridge-nest)

### ISSUE THREAD

**Issue by ValoV83** [hoobs-org/HOOBS#865]
**Description**
I'm trying to upgrade the Nest plugin (homebridge-nest) to the latest version 4.4.12 without success. I'm currently using homebridge-nest is 4.4.6 and I've applied the latest HOOBS updates 3.2.7/3.2.8/3.2.9 and manually updated Node via terminal to 12.19.0 but keep getting an NPM error.

**Version**
3.2.9
Node 12.19.0

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [*] Yes
- [ ] No

**Pervious version**
3.2.8

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [*] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [*] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
homebridge-nest
homebridge-panasonic-viera-tv

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023OKMQLA1EL",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": "",
        "latitude": "",
        "longitude": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "128-33-821",
        "username": "C4:71:95:CF:42:AB"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Panasonic-TV",
            "name": "TX-42AS650B",
            "ipaddress": "192.168.0.15",
            "inputs": [
                {
                    "id": "TV",
                    "name": "TV",
                    "type": "TV"
                },
                {
                    "id": "HDMI 1",
                    "name": "Apple TV",
                    "type": "HDMI"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-panasonic-viera-tv",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "googleAuth": {
                "apiKey": "",
                "cookies": ".",
                "issueToken": ""
            },
            "name": "Nest"
        }
    ]
}
**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
![Screenshot 2020-10-23 at 12 08 51](https://user-images.githubusercontent.com/53697662/96998796-0a457300-152c-11eb-8d3f-4d8a7c37e2a5.png)

**Additional context**

**Comment by mkellsy** [comment]
Looks like NPM screwed some things up.

You can restore the state of the plugins folder likw this.
```
cd ~/.hoobs
rm -fR node_modules
npm install
```

This will remove the stuck files that npm will not remove. The npm install command will reinstall all plugins.

**Comment by ValoV83** [comment]
Thats fixed it! Thank you
