### ISSUE TITLE
Problem after install Hue Plugin

### ISSUE THREAD

**Issue by Hodenbeer** [hoobs-org/HOOBS#867]
I want to install the hue plugin on my Hoobs (Raspberry pi 4B). But after that, the server stops: 

WARN notsup Unsupported engine for homebridge-hue@0.11.77: wanted: {"BSB001":"1.16.0","BSB002":"1.41.0","deCONZ":"2.5.84","homebridge":"^1.1.0","node":"^12.19.0"} (current: {"node":"12.16.3","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-hue@0.11.77
npm WARN notsup Unsupported engine for homebridge-lib@4.7.16: wanted: {"homebridge":"^1.1.0","node":"^12.19.0"} (current: {"node":"12.16.3","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.7.16
25.10.2020, 21:26:18 + homebridge-hue@0.11.77
added 55 packages from 98 contributors in 9.004s
25.10.2020, 21:26:18 
36 packages are looking for funding
  run `npm fund` for details
25.10.2020, 21:26:18 Plugin "homebridge-hue" installed.
25.10.2020, 21:26:20 Got SIGINT, shutting down Bridge...
25.10.2020, 21:26:25 [10/25/2020, 2:26:25 PM] The plugin "homebridge-hue" requires Node version of ^12.19.0 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.
25.10.2020, 21:26:26 Loaded plugin 'homebridge-hue'
25.10.2020, 21:26:26 [10/25/2020, 2:26:26 PM] Registering platform 'homebridge-hue.Hue'
25.10.2020, 21:26:27 Loaded plugin 'homebridge-xiaomi-roborock-vacuum'
25.10.2020, 21:26:27 Loading 1 platforms...
25.10.2020, 21:26:27 [10/25/2020, 2:26:27 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
25.10.2020, 21:26:27 [Hue] Initializing Hue platform...
25.10.2020, 21:26:27 [Hue] config.json: warning: plugin_map: ignoring unknown key
25.10.2020, 21:26:27 [Hue] homebridge-hue v0.11.77, node v12.16.3, homebridge v1.1.6
25.10.2020, 21:26:27 [Hue] warning: not using recommended node version v12.19.0 LTS
25.10.2020, 21:26:27 Loading 1 accessories...
25.10.2020, 21:26:27 [R2D2] Initializing XiaomiRoborockVacuum accessory...
25.10.2020, 21:26:27 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
25.10.2020, 21:26:27 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.

25.10.2020, 21:31:12 [Hue] 192.***.***.32: 192.168.178.32:80: cannot connect: ECONNREFUSED - retrying in 15s
25.10.2020, 21:31:19 [Hue] Bitch Bridge: gateway request 20: post / {"devicetype":"homebridge-hue#hoobs"}
25.10.2020, 21:31:19 [Hue] Bitch Bridge: gateway request 20: error 101 link button not pressed
25.10.2020, 21:31:19 [Hue] Bitch Bridge: unlock gateway to create a user - retrying in 15s
25.10.2020, 21:31:34 [Hue] Bitch Bridge: gateway request 21: post / {"devicetype":"homebridge-hue#hoobs"}
25.10.2020, 21:31:34 [Hue] Bitch Bridge: gateway request 21: error 101 link button not pressed
25.10.2020, 21:31:34 [Hue] Bitch Bridge: unlock gateway to create a user - retrying in 15s

25.10.2020, 21:35:45 [Hue] Bitch Bridge: dresden elektronik deCONZ gateway v2.5.77, api v1.16.0
25.10.2020, 21:35:45 [Hue] Bitch Bridge: warning: not using recommended deCONZ gateway version 2.5.84
25.10.2020, 21:35:45 [Hue] Bitch Bridge: 1 accessories

I think it wants to connect to the last Bridge. 
But I deleted it, because it doesn't work all the time. After a few hours the Hoobs server stoped, and I could not see the live temperatur on my Aqara sensor. So I deleted the plugin. But now I can not install it again. 

And it doesn't end the progress of installing with the user information for my Phoscon Gateway (Raspian II), which usually works well all the time. 

I reboot the Raspberry: 

25.10.2020, 21:43:37 [Hue] searching bridges and gateways
25.10.2020, 21:43:43 [Hue] Bitch Bridge: dresden elektronik deCONZ gateway v2.5.77, api v1.16.0
25.10.2020, 21:43:43 [Hue] Bitch Bridge: warning: not using recommended deCONZ gateway version 2.5.84
25.10.2020, 21:43:43 [Hue] Bitch Bridge: 1 accessories
25.10.2020, 21:47:19 [Hue] 192.***.***.32: 192.168.178.32:80: cannot connect: EHOSTUNREACH - retrying in 15s
25.10.2020, 21:47:37 [Hue] 192.***.***.32: 192.168.178.32:80: cannot connect: ECONNREFUSED - retrying in 15s
25.10.2020, 21:47:52 [Hue] 192.***.***.32: 192.168.178.32:80: cannot connect: ECONNREFUSED - retrying in 15s

Thank you for help.

**Comment by mkellsy** [comment]
It looks like it can't connect to your Hub bridge. I am guessing that it is at 192.168.178.32. Can you verify that in your router?

You also state that you can't install the plugin again. Are you getting an error? Can you post the logs when you try to install the plugin?

**Comment by Hodenbeer** [comment]
This IP is my iPhone. My HomeKit Hub is an Apple TV ...72 . 

I can install it. But when I want to save the configuration this progress doesn't end. 

I use Homemanager on my iPhone, is this a problem?

**Comment by Hodenbeer** [comment]
WARN notsup Unsupported engine for homebridge-hue@0.11.77: wanted: {"BSB001":"1.16.0","BSB002":"1.41.0","deCONZ":"2.5.84","homebridge":"^1.1.0","node":"^12.19.0"} (current: {"node":"12.16.3","npm":"6.14.4"})
npm WARN
26.10.2020, 09:14:28 notsup Not compatible with your version of node/npm: homebridge-hue@0.11.77
26.10.2020, 09:14:28 npm WARN notsup Unsupported engine for homebridge-lib@4.7.16: wanted: {"homebridge":"^1.1.0","node":"^12.19.0"} (current: {"node":"12.16.3","npm":"6.14.4"})
26.10.2020, 09:14:28 npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.7.16
26.10.2020, 09:14:28 
26.10.2020, 09:14:28 + homebridge-hue@0.11.77
added 55 packages from 98 contributors in 9.789s
26.10.2020, 09:14:29 
36 packages are looking for funding
  run `npm fund` for details
26.10.2020, 09:14:29 Plugin "homebridge-hue" installed.
26.10.2020, 09:14:31 Got SIGINT, shutting down Bridge...
26.10.2020, 09:14:36 [10/26/2020, 2:14:36 AM] The plugin "homebridge-hue" requires Node version of ^12.19.0 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.
26.10.2020, 09:14:37 Loaded plugin 'homebridge-hue'
26.10.2020, 09:14:37 [10/26/2020, 2:14:37 AM] Registering platform 'homebridge-hue.Hue'
26.10.2020, 09:14:37 Loaded plugin 'homebridge-xiaomi-roborock-vacuum'
26.10.2020, 09:14:37 [10/26/2020, 2:14:37 AM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
26.10.2020, 09:14:37 Loading 1 platforms...
26.10.2020, 09:14:37 [Hue] Initializing Hue platform...
26.10.2020, 09:14:37 [Hue] config.json: warning: plugin_map: ignoring unknown key
26.10.2020, 09:14:37 [Hue] homebridge-hue v0.11.77, node v12.16.3, homebridge v1.1.6
26.10.2020, 09:14:37 [Hue] warning: not using recommended node version v12.19.0 LTS
26.10.2020, 09:14:37 Loading 1 accessories...
26.10.2020, 09:14:37 [R2D2] Initializing XiaomiRoborockVacuum accessory...
26.10.2020, 09:14:37 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
26.10.2020, 09:14:37 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
26.10.2020, 09:14:38 [R2D2] STA getDevice | Connected to: 192.168.178.22
26.10.2020, 09:14:38 [R2D2] STA getDevice | Model: roborock.vacuum.s5
26.10.2020, 09:14:38 [R2D2] STA getDevice | State: charging
26.10.2020, 09:14:38 [R2D2] STA getDevice | FanSpeed: 103
26.10.2020, 09:14:38 [R2D2] STA getDevice | BatteryLevel: 100
26.10.2020, 09:14:38 [R2D2] INF getSerialNumber | roborock.vacuum.s5 | Serial Number is R0018S92431855
26.10.2020, 09:14:38 [R2D2] STA getDevice | Serialnumber: R0018S92431855
26.10.2020, 09:14:38 [R2D2] INF getFirmware | roborock.vacuum.s5 | Firmwareversion is 3.5.7_002008
26.10.2020, 09:14:38 [R2D2] STA getDevice | Firmwareversion: 3.5.7_002008
26.10.2020, 09:14:38 [R2D2] INF changedCleaning | roborock.vacuum.s5 | Cleaning is OFF.
26.10.2020, 09:14:38 [R2D2] MON changedCharging | roborock.vacuum.s5 | ChargingState is now true
26.10.2020, 09:14:38 [R2D2] INF changedCharging | roborock.vacuum.s5 | Charging is active
26.10.2020, 09:14:38 [R2D2] INF changedCharging | roborock.vacuum.s5 | Robot was docked.
26.10.2020, 09:14:38 [R2D2] MON changedSpeed | roborock.vacuum.s5 | FanSpeed is now 103%
26.10.2020, 09:14:38 [R2D2] INF changedSpeed | roborock.vacuum.s5 | Speed was changed to 103% (Turbo), for HomeKit 80%
26.10.2020, 09:14:38 [R2D2] INF changedPause | roborock.vacuum.s5 | Paused not possible, no cleaning
26.10.2020, 09:14:38 [Hue] searching bridges and gateways
26.10.2020, 09:14:43 [Hue] 192.***.***.32: 192.168.178.32:80: cannot connect: ECONNREFUSED - retrying in 15s
26.10.2020, 09:14:43 [Hue] Bitch Bridge: dresden elektronik deCONZ gateway v2.5.77, api v1.16.0
26.10.2020, 09:14:43 [Hue] Bitch Bridge: warning: not using recommended deCONZ gateway version 2.5.84
26.10.2020, 09:14:43 [Hue] Bitch Bridge: gateway request 1: post / {"devicetype":"homebridge-hue#hoobs"}
26.10.2020, 09:14:43 [Hue] Bitch Bridge: gateway request 1: error 101 link button not pressed
26.10.2020, 09:14:43 [Hue] Bitch Bridge: unlock gateway to create a user - retrying in 15s

**Comment by Hodenbeer** [comment]
This are the logs after install, without write something in user

**Comment by mkellsy** [comment]
The logs are telling you that you need to press the button on the Hue bridge.

**Comment by Hodenbeer** [comment]
I use a Raspbee II and no Hue bridge. I press the Button on the Phoscon App to connect the Gateway, after that this are the logs:

 28.10.2020, 10:05:40 [Hue] 192.***.***.32: 192.168.178.32:80: cannot connect: EHOSTUNREACH - retrying in 15s
28.10.2020, 10:05:44 [Hue] Bitch Bridge: created user - please edit config.json and restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "00212EFFFF062033": "7AE9A636B0"
      }
    }
  ]
28.10.2020, 10:05:44 [Hue] Bitch Bridge: 1 accessories
28.10.2020, 10:05:47 [Hue] Bitch Bridge: created user - please edit config.json and restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "00212EFFFF062033": "7AE9A636B0"
      }
    }

**Comment by Hodenbeer** [comment]
![Screenshot (32)_LI](https://user-images.githubusercontent.com/73251194/97416739-1f911780-1907-11eb-8df7-0546a5456075.jpg)


When I install it, this loading bar runs continuously for minutes.

**Comment by mkellsy** [comment]
That's because the Hue plugin spawns a process and tries to connect every 15 seconds. The plugin can't find a Hue bridge or a Deconz server.

Check to see if the HOOBS box can actually see the Hue or Deconz bridge. A simple ping should work. If it can see it there might be something on your network preventing the communication protocol.
