### ISSUE TITLE
Can't get RPI plugin to work

### ISSUE THREAD

**Issue by jneuringer** [hoobs-org/HOOBS#869]
**Description**
have this:
[
    {
        "host": "hoobs.local"
    }
]
but get this:
10/26/2020, 9:03:08 AM [RPi] warning: hoobs.local: 192.168.2.136:8888: cannot connect: ECONNREFUSED
10/26/2020, 9:03:23 AM [RPi] warning: hoobs.local: 192.168.2.136:8888: cannot connect: ECONNREFUSED
10/26/2020, 9:03:38 AM [RPi] warning: hoobs.local: 192.168.2.136:8888: cannot connect: ECONNREFUSED
10/26/2020, 9:03:53 AM [RPi] warning: hoobs.local: 192.168.2.136:8888: cannot connect: ECONNREFUSED
10/26/2020, 9:04:08 AM [RPi] warning: hoobs.local: 192.168.2.136:8888: cannot connect: ECONNREFUSED

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
RPi

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
Try this:

"host": "localhost"

**Comment by jneuringer** [comment]
Thanks, that worked.

**Comment by mkellsy** [comment]
Try localhost or 127.0.0.1

**Comment by jneuringer** [comment]
Thanks, both seem to work..

Although I get some weird messages on the RPI side…

10/26/2020, 9:56:10 AM [RPi] localhost: set Load from 0.12 to 0.1
10/26/2020, 9:56:25 AM [RPi] localhost: set Current Temperature from 60.1°C to 60.7°C
10/26/2020, 9:56:25 AM [RPi] localhost: set Load from 0.1 to 0.07
10/26/2020, 9:56:40 AM [RPi] localhost: set Current Temperature from 60.7°C to 60.1°C
10/26/2020, 9:56:40 AM [RPi] localhost: set Throttled from false to true
10/26/2020, 9:56:40 AM [RPi] localhost: set Smoke Detected from 0 to 1
10/26/2020, 9:56:40 AM [RPi] localhost: set Under Voltage from false to true
10/26/2020, 9:56:40 AM [RPi] localhost: set Load from 0.07 to 0.06
10/26/2020, 9:56:55 AM [RPi] localhost: set Throttled from true to false
10/26/2020, 9:56:55 AM [RPi] localhost: set Under Voltage from true to false
10/26/2020, 9:56:55 AM [RPi] localhost: set Smoke Detected from 1 to 0
10/26/2020, 9:56:55 AM [RPi] localhost: set Load from 0.06 to 0.11


Smoke detected and Under volt..   any ideas about that?

j

**Comment by mkellsy** [comment]
That looks like normal operation of the plugin. The Pi does have an under volt sensor. It might have a smoke detector too although I didn't know about that.

**Comment by jneuringer** [comment]
Hello,

So just following up..  I’ve read a few articles that seem to imply there maybe something wrong with my new HOOBS hardware…  
There seems to be an oscillation between undervolt, throttled, and smoke detected (all at the same intervals).

I have tested / verified it is NOT the power adapter by trying an alternative.  It’s also not over-temperature because 58 degrees is actually cool for the CPU.  And there is in fact no smoke condition in my home. 

Thoughts?

Jeremy


10/26/2020, 1:53:13 PM [RPi] 127.0.0.1: set Current Temperature from 58.5°C to 58°C
10/26/2020, 1:53:13 PM [RPi] 127.0.0.1: set Throttled from false to true
10/26/2020, 1:53:13 PM [RPi] 127.0.0.1: set Smoke Detected from 0 to 1
10/26/2020, 1:53:13 PM [RPi] 127.0.0.1: set Under Voltage from false to true
10/26/2020, 1:53:13 PM [RPi] 127.0.0.1: set Load from 0.34 to 0.27
10/26/2020, 1:53:28 PM [RPi] 127.0.0.1: set Current Temperature from 58°C to 57.5°C
10/26/2020, 1:53:28 PM [RPi] 127.0.0.1: set Throttled from true to false
10/26/2020, 1:53:28 PM [RPi] 127.0.0.1: set Under Voltage from true to false
10/26/2020, 1:53:28 PM [RPi] 127.0.0.1: set Smoke Detected from 1 to 0
10/26/2020, 1:53:28 PM [RPi] 127.0.0.1: set Load from 0.27 to 0.21
10/26/2020, 1:53:43 PM [RPi] 127.0.0.1: set Current Temperature from 57.5°C to 56.9°C
10/26/2020, 1:53:43 PM [RPi] 127.0.0.1: set Load from 0.21 to 0.16
10/26/2020, 1:53:58 PM [RPi] 127.0.0.1: set Current Temperature from 56.9°C to 55.8°C
10/26/2020, 1:53:58 PM [RPi] 127.0.0.1: set Load from 0.16 to 0.12
10/26/2020, 1:54:13 PM [RPi] 127.0.0.1: set Load from 0.12 to 0.1
10/26/2020, 1:54:28 PM [RPi] 127.0.0.1: set Current Temperature from 55.8°C to 55.3°C
10/26/2020, 1:54:28 PM [RPi] 127.0.0.1: set Load from 0.1 to 0.07
10/26/2020, 1:54:43 PM [RPi] 127.0.0.1: set Current Temperature from 55.3°C to 54.8°C
10/26/2020, 1:54:43 PM [RPi] 127.0.0.1: set Load from 0.07 to 0.06
10/26/2020, 1:54:58 PM [RPi] 127.0.0.1: set Current Temperature from 54.8°C to 53.7°C
10/26/2020, 1:54:58 PM [RPi] 127.0.0.1: set Load from 0.06 to 0.04
10/26/2020, 1:55:13 PM [RPi] 127.0.0.1: set Throttled from false to true
10/26/2020, 1:55:13 PM [RPi] 127.0.0.1: set Smoke Detected from 0 to 1
10/26/2020, 1:55:13 PM [RPi] 127.0.0.1: set Under Voltage from false to true
10/26/2020, 1:55:13 PM [RPi] 127.0.0.1: set Load from 0.04 to 0.03
10/26/2020, 1:55:28 PM [RPi] 127.0.0.1: set Current Temperature from 53.7°C to 53.2°C
10/26/2020, 1:55:28 PM [RPi] 127.0.0.1: set Throttled from true to false
10/26/2020, 1:55:28 PM [RPi] 127.0.0.1: set Under Voltage from true to false
10/26/2020, 1:55:28 PM [RPi] 127.0.0.1: set Smoke Detected from 1 to 0
10/26/2020, 1:55:43 PM [RPi] 127.0.0.1: set Load from 0.03 to 0.02
10/26/2020, 1:55:58 PM [RPi] 127.0.0.1: set Current Temperature from 53.2°C to 52.1°C
10/26/2020, 1:55:58 PM [RPi] 127.0.0.1: set Load from 0.02 to 0.01
10/26/2020, 1:56:13 PM [RPi] 127.0.0.1: set Current Temperature from 52.1°C to 52.6°C
10/26/2020, 1:56:43 PM [RPi] 127.0.0.1: set Current Temperature from 52.6°C to 52.1°C
10/26/2020, 1:56:43 PM [RPi] 127.0.0.1: set Load from 0.01 to 0

**Comment by jneuringer** [comment]
interesting follow up to the RPI plugin/ hoobs hardware issue…

0/26/2020, 2:52:07 PM [RPi] Initializing RPi platform...
10/26/2020, 2:52:07 PM [RPi] homebridge-rpi v1.1.16, node 12.16.3, homebridge v1.1.6, homebridge-lib v4.7.16
10/26/2020, 2:52:07 PM [RPi] warning: 12.16.3: not using recommended node v12.19.0 LTS
10/26/2020, 2:52:07 PM [RPi] warning: config.json: plugin_map: invalid key

not sure why it’s complaining.

**Comment by freddair** [comment]
It's a feature of the Plugin that also annoyed me. You may disable the smoke sensor (which detects thermal throttling of the CPU) by adding the "noSmokeSensor" key.

https://github.com/ebaauw/homebridge-rpi/issues/44

**Comment by mkellsy** [comment]
Those Node and invalid key messages are just that, messages. It's safe to ignore and here's why.

Having an extra key in a config doesn't hurt the operation. We add that key to tie a config to a plugin without having to start Homebridge. It's handy when looking at a config and helps in diagnosis.

The differences between node 12.16 and 12.19 won't affect the operation of the plugin either. If your setup is working, I would skip the pain of upgrading Node. This can get frustrating because Node releases sometimes daily.

Here's the Node changeling, so you can decide if you actually need to upgrade.
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.19.0

This plugin dev likes forcing people to upgrade Node when Node releases a minor update. He also won't support anyone not running his "ideal" setup.
