### ISSUE TITLE
Wyze motion sensor lag

### ISSUE THREAD

**Issue by Rtmckinney** [hoobs-org/HOOBS#871]
Just got my HOOBS up and working and for the most part everything is working. However, there is significant lag time (about 2 seconds at times) between motion detection and light response automation. I am using WYZE motion sensors with a WYZE cam as the hub. The lights are lutron casseta and my automations are running through homekit. I have a friend that uses the WYZE motion sensors with the hub connected directly to his RP 3 with lutron casseta and there is zero lag at all. I have the refresh rate set at 100 microseconds for the wyze sensors. Does anyone have any suggestions? Is there a way to connect the wyze bridge directly into the HOOBS out of the box raspbery pi? This is very frustrating. Thanks

**Comment by askovi** [comment]
Try opening an issue with the plugin developer. This is probably a network issue, not HOOBS related.
