### ISSUE TITLE
dash board & menu css issue after updated 3.2.9

### ISSUE THREAD

**Issue by wallacepost** [hoobs-org/HOOBS#872]
![Screen Shot 2020-10-28 at 6 12 05 am](https://user-images.githubusercontent.com/65918663/97351033-55250900-18e5-11eb-83b4-5564bd851c94.png)
after updated 3.2.9 , the dash board & menu looks funny...

**Comment by mkellsy** [comment]
It looks like your browser isn't loading the fonts. Try clearing your browser cache.

**Comment by wallacepost** [comment]
Hi , tried clear cache, also install google chrome & different phone. no luck

**Comment by wallacepost** [comment]
Does anyone has similar issue?

**Comment by askovi** [comment]
Try reinstalling HOOBS via ssh using this command:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash -`

**Comment by mkellsy** [comment]
Your browser is not downloading the fonts from the pi property. Do you get the same behavior from another browser.

Did you select from "all time" and was "files" selected when you cleared your browser history?

**Comment by wallacepost** [comment]
I was updated the firmware 3.2.9 through Homemanager app through iOS . Recently  I have updated the firmware to 3.3.1 through OSX, it fixed the ccs issue.
