### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by Stetocasa** [hoobs-org/HOOBS#874]
Guys, due to a chronic issues with yesterday EWeLink plug-in, I did a disaster in my hoobs.
In particular, I tried to reset connection with hk, re add again but all olds icons of oldest plug-in keep inside.
Tried to recall a yesterday backup of the system but I don't know if this process goes well or no. 
Now I removed hoobs hub from hk, seems to be that I cannot remove the plug-in because from 5 hours seem to be another installation process running. 
So, I'm in the middle without possibility to reconfigure to zero.
I really need you support to understand how fix and really start from factory begin.

**Comment by askovi** [comment]
Without logs and more details on what actions got you to this point it’s impossible to determine the issue. Try reflashing your sd card.
