### ISSUE TITLE
Abode locks breaks hoobs with Bond 

### ISSUE THREAD

**Issue by azmurph** [hoobs-org/HOOBS#875]
I have everything working perfectly. I installed Abode Locks and get an error with hoobs shutting down and bond shows can’t find bond id within the log.  When I remove abode locks, bond works again.  I’ve installed the latest updates for hoobs, bond and abode and also have the latest firmware for all devices, including bond.  How can this be fixed?   I’ve tried deleting everything and setup again with no luck.  Never had this issue before until abode.  No way to email or get in touch with developer.  I’ve tried to reach out to him in Instagram via direct message but not responding. Thanks!

**Comment by askovi** [comment]
Please follow the bug report template

**Comment by azmurph** [comment]
Yeah, how do I find the template?

**Comment by askovi** [comment]
When you create the issue it prompts you to select it
