### ISSUE TITLE
Error: send ENETUNREACH 224.0.0.251:5353

### ISSUE THREAD

**Issue by eddiem5** [hoobs-org/HOOBS#881]
**Description**
I have had zero issue with HOOBS but today found my bridge had exited with an error.
The messages in the log file are as follows:

10/31/2020, 4:19:15 AM Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:697:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at afterDns (dgram.js:643:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
10/31/2020, 4:19:15 AM ERROR: uncaughtException: send ENETUNREACH 224.0.0.251:5353
10/31/2020, 4:19:15 AM Error: send ENETUNREACH 224.0.0.251:5353
10/31/2020, 4:19:15 AM at doSend (dgram.js:697:16)
10/31/2020, 4:19:15 AM at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
10/31/2020, 4:19:15 AM at afterDns (dgram.js:643:5)
10/31/2020, 4:19:15 AM at processTicksAndRejections (internal/process/task_queues.js:85:21)
10/31/2020, 4:19:15 AM Got SIGTERM, shutting down Bridge...

When I found the bridge down, I restarted the bridge from the web page (which was working) and everything came back with no issues.

**Version**
I am running 3.2.9 with the Ring, MyQ, Smartthings and Tesla plugins.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
3.2.7

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Raspian PI 4 - Linux hoobs 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

**List your plugins**
Ring, MyQ, Smartthings and Tesla plugins

**Post your config**

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://XXXXX",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040",
        "latitude": "XXXX",
        "longitude": "XXXX"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "XXXXX",
        "username": "XXXXX"
    },
    "description": "Hoobs Bridge PI4 Based Device",
    "ports": {},
    "accessories": [
        {
            "accessory": "Tesla",
            "plugin_map": {
                "plugin_name": "homebridge-tesla",
                "index": 0
            },
            "name": "Tesla",
            "vin": "XXXXXX",
            "authToken": "xxxxx",
            "waitMinutes": 1,
            "latitude": "XXXXX",
            "longitude": "-XXXXX",
            "enableHomeLink": false,
            "disableChargeLevel": false,
            "disableStarter": true,
            "disableCharger": false,
            "disableFrunk": false,
            "disableTrunk": false,
            "disableClimate": false,
            "disableDoors": false
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "XXXXXXX",
            "alarmOnEntryDelay": false,
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": false,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": false,
            "hideUnsupportedServices": true,
            "showPanicButtons": false
        },
        {
            "platform": "SmartThings-v2",
            "plugin_map": {
                "plugin_name": "homebridge-smartthings"
            },
            "name": "SmartThings-v2",
            "direct_port": 8000,
            "temperature_unit": "F",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "Good"
                }
            },
            "communityUserName": " Homebridge v2",
            "app_url": "https://xxxxxxxx.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxx",
            "access_token": "xxxxxxx-xxxx-xxxx-xxxx-xxxxx"
        },
        {
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq"
            },
            "email": "xxxxxxxx@yahoo.com",
            "password": "XXXXXXX",
            "name": "Mansfield Garage"
        }
    ]
}```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
10/31/2020, 4:19:15 AM Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:697:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at afterDns (dgram.js:643:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
10/31/2020, 4:19:15 AM ERROR: uncaughtException: send ENETUNREACH 224.0.0.251:5353
10/31/2020, 4:19:15 AM Error: send ENETUNREACH 224.0.0.251:5353
10/31/2020, 4:19:15 AM at doSend (dgram.js:697:16)
10/31/2020, 4:19:15 AM at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
10/31/2020, 4:19:15 AM at afterDns (dgram.js:643:5)
10/31/2020, 4:19:15 AM at processTicksAndRejections (internal/process/task_queues.js:85:21)
10/31/2020, 4:19:15 AM Got SIGTERM, shutting down Bridge...```

**Additional context**

**Comment by askovi** [comment]
Which device has this ip on your network? 224.0.0.251

The logs state that device couldn’t be reached which caused a crash. This should be handled at the plugin level. If you find the device you can identify the plugin in question .

**Comment by mc-hamster** [comment]
I've been getting the exact same error for the last month or so.

11/8/2020, 9:43:54 PM Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:694:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:364:12)
    at afterDns (dgram.js:640:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

I don't have any devices on my network with that IP address.

**Comment by MacFlagg** [comment]
I updated HOOBS yesterday and my Harmony activities disappeared out of the Home app. Upon investigating, I found that the plug-in was having the following error: 

Loading activities...
11/9/2020, 7:46:26 AM [******************] (******************)Error - Error retrieving info from hub : request to http://192.168.1.197:8088/ failed, reason: connect EHOSTUNREACH 192.168.1.197:8088

Is there a fix for this or will we have to wait for another HOOBS update?

**Comment by carloscheddar** [comment]
Decided to upgrade hoobs a few weeks ago after a year of not touching it and I’m having the same issue.
```

[Homebridge] [11/11/2020, 14:46:16] Error: send ENETUNREACH 224.0.0.251:5353
[Homebridge] at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
[Homebridge] [11/11/2020, 14:46:16] Got SIGTERM, shutting down service...
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826

```

**Comment by carloscheddar** [comment]
I managed to find the plugin causing the issue for me I ended up removing it for now. https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum
