### ISSUE TITLE
Removing an individual accessory from cache?

### ISSUE THREAD

**Issue by jahunt** [hoobs-org/HOOBS#883]
Is there a command I can type into the terminal to remove an accessory from the cache? I’ve removed the plug-in but the accessory still shows up in HomeKit. I don’t want to have to reset my entire HOOBS setup.

**Comment by askovi** [comment]
No there isn't a simple command to do that. You would have to browse the cached accessories and persist folders in `/home/hoobs/.hoobs/etc/`
Then you have to open the files inside and manually find it and remove it. It will take you a lot longer than simply using the Reset Connection button in the Help menu.

**Comment by chrisjshull** [comment]
doesn't "Reset Connection" force me to reconfigure my entire Home, and also rebuild any automations set up?
