### ISSUE TITLE
Hoobs Box stopped working after upgrade

### ISSUE THREAD

**Issue by joseanmendez** [hoobs-org/HOOBS#884]
After the last upgrade, my Hoobs-in-a-box stopped working.  I cannot connect via SSH, is hot showing up in my router.  Lights are on.

How do I get it back to the factory-mode and start over?

Latest version.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
Ring, Somfy, Sony, Marantz, Modern Forms, MyQ

**Post your config**
I cannot connect, cannot get any information.

How do I get it back to the factory-mode and start over?

This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
CANNOT Connect.

**Comment by askovi** [comment]
Try both Ethernet and Wi-Fi. If you don’t see it appear on your router with either one, then it could indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:
https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

You can download the img file free or charge from here: https://github.com/hoobs-org/hoobs-build/releases/download/v3.2.9/HOOBS-3.2.9-ARM7.zip

**Comment by joseanmendez** [comment]
Hi askovi,

I have opened my Hoobs and have my microSD card.  How do I recover my configuration before reflashing it?

I want to avoid the whole configuration process.

Thanks

**Comment by joseanmendez** [comment]
And one more thing.  The microSD appears  locked.  Balenaetcher won't let me select it.

**Comment by askovi** [comment]
If it’s already corrupted you can’t recover the configuration. There is a backup option in the HOOBS UI for both the system and the configuration under settings -> backup. It’s recommended you make a backup when you have the system running and fully configured.

Try formatting the microSD card first. If it’s still not working after that, please send an email to info@hoobs.org with your order number and mention this GitHub issue for a replacement.

**Comment by askovi** [comment]
This has been resolved over email.
