### ISSUE TITLE
Plugin "homebridge-hue" requires Node version of ^12.19.0

### ISSUE THREAD

**Issue by vvdheuvel** [hoobs-org/HOOBS#885]
**Description**
The plug-in "homebridge-hue" requires Node version of ^12.19.0 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.

**Question**
If I upgrade my Node tot the recommended version of the plug-in will this give me any problems with HOOBS?

**Comment by askovi** [comment]
That's just a message from the plugin. It doesn't actually require it and it doesn't even use anything from the newer version. However if you want to upgrade, you can do so with this command:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`
