### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by Stetocasa** [hoobs-org/HOOBS#886]
Yesterday I spent all day to hard reset and reconfigure all plugins and HomeKit

Today for a simple power off Idon’t  have any idea to do the same

The hoobs is connected to my network

This is the Wi-Fi IP I have also the IP for lan

Devices also founded by home manager but if select of both tell me client error![image](https://user-images.githubusercontent.com/70729310/97887124-c28fca00-1d29-11eb-96f3-8c4c4e6fc99f.jpeg)

**Comment by Stetocasa** [comment]
![image](https://user-images.githubusercontent.com/70729310/97887148-cb809b80-1d29-11eb-8cdc-4c8740bdc550.jpeg)

**Comment by Stetocasa** [comment]
![image](https://user-images.githubusercontent.com/70729310/97887159-d0454f80-1d29-11eb-9f72-aa53e9cf29c3.jpeg)

**Comment by Stetocasa** [comment]
![Uploading 97887171...]

**Comment by Stetocasa** [comment]
![image](https://user-images.githubusercontent.com/70729310/97887889-c5d78580-1d2a-11eb-8475-71fbee5b2122.jpeg)

**Comment by askovi** [comment]
Please use the HOOBS UI at http://hoobs.local
Follow the bug report template here and provide your logs and config, etc.
