### ISSUE TITLE
How to remove Harmony Hub

### ISSUE THREAD

**Issue by danevans60** [hoobs-org/HOOBS#889]
I have this stuck on my Apple HomeKit I use via Hoobs. It has been uninstalled but seems to stay present on the homepage on HomeKit how can I remove it.

![E8282F43-1DE9-465A-B1E9-20B9378D8DDC](https://user-images.githubusercontent.com/60575480/98365040-c1141980-2029-11eb-8da6-39048075edf0.png)

**Comment by askovi** [comment]
Top right menu -> Help -> Reset Connection
Then rescan the new QR code from the dashboard.
