### ISSUE TITLE
Since Update 3.2.9 stuck on Service start

### ISSUE THREAD

**Issue by Bladestar2105** [hoobs-org/HOOBS#891]
Hello,

since update 3.2.9 and also 3.2.10 when the update is done the service start always stuck.
I tried to uninstall the Plugin AVMFritz where the stuck starts but it doesn't help.
Here is my config:
>{
    "server": {
        "origin": "*",
        "autostart": 90,
        "port": 8080,
        "home_setup_id": "X-HM://XXXXXXXXX",
        "polling_seconds": 5
    },
    "client": {
        "country_code": "DE",
        "postal_code": 12345,
        "latitude": "XXXXXXX",
        "inactive_logoff": 50,
        "temp_units": "celsius",
        "theme": "hoobs-dark",
        "longitude": "XXXXXXX",
        "default_route": "status",
        "locale": "de"
    },
    "bridge": {
        "pin": "XXX-XX-XXX",
        "name": "Homebridge",
        "port": 51826,
        "username": "XXXXXXXXX"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {
        "start": 52100,
        "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to.",
        "end": 52150
    },
    "accessories": [
        {
            "dock": true,
            "name": "Roborock Vacuum",
            "ip": "192.168.178.72",
            "findMe": false,
            "findMeWord": "where are you",
            "rooms": [
                {
                    "name": "das Wohnzimmer",
                    "id": 22
                },
                {
                    "name": "die Küche",
                    "id": 16
                },
                {
                    "name": "den Flur",
                    "id": 17
                },
                {
                    "name": "das Bad",
                    "id": 18
                },
                {
                    "name": "XXXX Zimmer",
                    "id": 19
                },
                {
                    "name": "XXXXXX Zimmer",
                    "id": 20
                },
                {
                    "name": "das Schlafzimmer",
                    "id": 21
                }
            ],
            "delay": true,
            "cleanword": "reinige",
            "autoroom": false,
            "pauseWord": "pause",
            "token": "1234567890",
            "plugin_map": {
                "plugin_name": "homebridge-xiaomi-roborock-vacuum",
                "index": 0
            },
            "pause": false,
            "waterBox": false,
            "accessory": "XiaomiRoborockVacuum"
        }
    ],
    "platforms": [
        {
            "TVPlatformMode": true,
            "mainActivity": "Fernsehen",
            "linkVolumeControlToTV": true,
            "showTurnOffActivity": false,
            "name": "Fernseher",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "hubIP": "192.168.178.66",
            "platform": "HarmonyHubWebSocket"
        },
        {
            "name": "Fritzbox",
            "devices": [
                {
                    "incomingName": "Eingehender Anruf",
                    "name": "AVM Fritz!Box",
                    "address": "192.168.178.1",
                    "port": "1012",
                    "outgoingName": "Ausgehender Anruf"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-callmonitor"
            },
            "platform": "CallMonitor"
        },
        {
            "users": {
                "1234567890": "XXXXXXXX"
            },
            "name": "Hue",
            "sensors": true,
            "hosts": [
                "192.168.178.73"
            ],
            "lights": true,
            "forceCt": true,
            "nativeHomeKitLights": true,
            "excludeSensorTypes": [
                "Daylight"
            ],
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "anyOn": true,
            "resource": true,
            "nupnp": "false",
            "platform": "Hue",
            "nativeHomeKitSensors": true
        },
        {
            "hostCallbackApiPort": 40123,
            "bridgeIpAddress": "192.168.178.71",
            "bridgeRebootSwitch": false,
            "hostNameOrIpAddress": "192.168.178.79",
            "bridgeApiToken": "XXXXX",
            "plugin_map": {
                "plugin_name": "homebridge-nuki"
            },
            "devices": [
                {
                    "isContinuousModeEnabled": false,
                    "isRingToOpenEnabled": false,
                    "nukiId": 12345678
                }
            ],
            "bridgeApiPort": 8080,
            "platform": "NukiPlatform"
        },
        {
            "options": {
                "strictSSL": false
            },
            "interval": 900,
            "concurrent": true,
            "url": "http://192.168.178.1",
            "username": "Username",
            "name": "FritzBox",
            "devices": {
                "wifi": {
                    "name": "Guest WLAN",
                    "display": false
                },
                "Heizung XXXXX": {
                    "ContactSensor": true
                },
                "Heizung Badezimmer": {
                    "ContactSensor": false
                }
            },
            "plugin_map": {
                "plugin_name": "homebridge-fritz"
            },
            "password": "passwort123",
            "platform": "FRITZ!Box"
        },
        {
            "videoProcessor": "ffmpeg",
            "name": "Camera FFmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Wäscheraum-Cam",
                    "manufacturer": "Reolink",
                    "firmwareRevision": "20.05.06.04",
                    "videoConfig": {
                        "debug": false,
                        "maxStreams": 20,
                        "preserveRatio": true,
                        "source": "-i http://192.168.178.74:8080/ihhkhkjhkljhlfgzfzgk/hls/ypFprfsaHe/FjHA5VuQYK/s.m3u8",
                        "maxHeight": 0,
                        "audio": true,
                        "maxWidth": 0,
                        "forceMax": true,
                        "vcodec": "libx264",
                        "videoFilter": "none"
                    },
                    "unbridge": true,
                    "model": "E1 Pro"
                }
            ]
        },
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        }
    ]
}

At this point it stucks
![IMG_0004](https://user-images.githubusercontent.com/55372949/98459029-e4a8a280-2196-11eb-8e6c-861c9d2b1f9a.PNG)

**Comment by Bladestar2105** [comment]
Can somebody please help? 🙁

**Comment by askovi** [comment]
Please post your entire log file from settings -> backup -> log. 
There is not enough information in the above post to identify any issue

**Comment by Bladestar2105** [comment]
It stops always at the same point. I already tried restarting the Server but nothing helps.
I run HOOBS in a Debian VM installed on Proxmox Hypervisor. With version 3.2.8 there are no issues.

Here we go, this is the entire log:

> 14.11.2020, 09:25:26 - HOOBS listening on port 8080.
14.11.2020, 09:26:07 - Loaded plugin 'homebridge-callmonitor'
14.11.2020, 09:26:07 - [2020-11-14 9:26:07] Registering platform 'homebridge-callmonitor.CallMonitor'
14.11.2020, 09:26:07 - Loaded plugin 'homebridge-camera-ffmpeg'
14.11.2020, 09:26:07 - [2020-11-14 9:26:07] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
14.11.2020, 09:26:07 - Loaded plugin 'homebridge-fritz'
14.11.2020, 09:26:07 - [2020-11-14 9:26:07] Registering platform 'homebridge-fritz.FRITZ!Box'
14.11.2020, 09:26:07 - Loaded plugin 'homebridge-harmony'
14.11.2020, 09:26:07 - [2020-11-14 9:26:07] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
14.11.2020, 09:26:07 - [2020-11-14 9:26:07] The plugin "homebridge-hue" requires Node version of ^14.15.0 which does not satisfy the current Node version of v12.17.0. You may need to upgrade your installation of Node.
14.11.2020, 09:26:09 - Loaded plugin 'homebridge-hue'
14.11.2020, 09:26:09 - [2020-11-14 9:26:09] Registering platform 'homebridge-hue.Hue'
14.11.2020, 09:26:09 - Loaded plugin 'homebridge-nuki'
14.11.2020, 09:26:09 - [2020-11-14 9:26:09] Registering platform 'homebridge-nuki.NukiPlatform'
14.11.2020, 09:26:09 - Loaded plugin 'homebridge-tplink-smarthome'
14.11.2020, 09:26:09 - [2020-11-14 9:26:09] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
14.11.2020, 09:26:09 - Loaded plugin 'homebridge-xiaomi-roborock-vacuum'
14.11.2020, 09:26:09 - Loading 7 platforms...
14.11.2020, 09:26:09 - [2020-11-14 9:26:09] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
14.11.2020, 09:26:09 - [Fernseher] Initializing HarmonyHubWebSocket platform...
14.11.2020, 09:26:09 - [Fernseher] HarmonyPlatform Init
14.11.2020, 09:26:09 - [Fritzbox] Initializing CallMonitor platform...
14.11.2020, 09:26:09 - [Fritzbox] CallMonitor Platform Plugin Loaded
14.11.2020, 09:26:09 - [Fritzbox] Found device in config: "undefined"
14.11.2020, 09:26:09 - Initializing platform accessory 'AVM Fritz!Box'...
14.11.2020, 09:26:09 - [Hue] Initializing Hue platform...
14.11.2020, 09:26:09 - [Hue] config.json: warning: forceCt: ignoring unknown key
14.11.2020, 09:26:09 - [Hue] config.json: warning: plugin_map: ignoring unknown key
14.11.2020, 09:26:09 - [Hue] homebridge-hue v0.12.0, node v12.17.0, homebridge v1.1.6
14.11.2020, 09:26:09 - [Hue] warning: not using recommended node version v14.15.0 LTS
14.11.2020, 09:26:09 - [NukiPlatform] Initializing NukiPlatform platform...
14.11.2020, 09:26:09 - [NukiPlatform] Homebridge API available.
14.11.2020, 09:26:09 - [FritzBox] Initializing FRITZ!Box platform...
14.11.2020, 09:26:09 - [Camera FFmpeg] Initializing Camera-ffmpeg platform...
14.11.2020, 09:26:09 - [TplinkSmarthome] Initializing TplinkSmarthome platform...
14.11.2020, 09:26:09 - [TplinkSmarthome] homebridge-tplink-smarthome v6.1.0, node v12.17.0, homebridge v1.1.6
14.11.2020, 09:26:09 - Loading 1 accessories...
14.11.2020, 09:26:09 - [Roborock Vacuum] Initializing XiaomiRoborockVacuum accessory...
14.11.2020, 09:26:09 - [Roborock Vacuum] INF createRoom | undefined | Room das Wohnzimmer (22) undefined
14.11.2020, 09:26:09 - [Roborock Vacuum] INF createRoom | undefined | Room die Küche (16) undefined
14.11.2020, 09:26:09 - [Roborock Vacuum] INF createRoom | undefined | Room den Flur (17) undefined
14.11.2020, 09:26:09 - [Roborock Vacuum] INF createRoom | undefined | Room das Bad (18) undefined
14.11.2020, 09:26:09 - [Roborock Vacuum] INF createRoom | undefined | Room User1 Zimmer (19) undefined
14.11.2020, 09:26:09 - [Roborock Vacuum] INF createRoom | undefined | Room User2 Zimmer (20) undefined
14.11.2020, 09:26:09 - [Roborock Vacuum] INF createRoom | undefined | Room das Schlafzimmer (21) undefined
14.11.2020, 09:26:09 - HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
14.11.2020, 09:26:09 - HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
14.11.2020, 09:26:09 - [Fritzbox] Connected to AVM Fritz!Box
14.11.2020, 09:26:10 - [FritzBox] FRITZ!Box platform login successful
14.11.2020, 09:26:10 - [FritzBox] Discovering accessories
14.11.2020, 09:26:10 - [FritzBox] Alarm sensors found: none
14.11.2020, 09:26:10 - [FritzBox] Buttons found: none
14.11.2020, 09:26:10 - [FritzBox] Outlets found: none
14.11.2020, 09:26:10 - [FritzBox] Thermostats found: 133560956000,133570026840
14.11.2020, 09:26:10 - [FritzBox] Updating thermostat 133560956000
14.11.2020, 09:26:10 - [FritzBox] Updating thermostat 133570026840
14.11.2020, 09:26:10 - [FritzBox] Sensors found: none
14.11.2020, 09:26:10 - Initializing platform accessory 'Heizung Badezimmer'...
14.11.2020, 09:26:10 - Initializing platform accessory 'Heizung User2'...

**Comment by Bladestar2105** [comment]
Since the HOOBS support is not so good I changed my setup without problems to Homebridge with UI-X.
