### ISSUE TITLE
HOOBS won't update!!!!!

### ISSUE THREAD

**Issue by cbarnhart76** [hoobs-org/HOOBS#892]
For days I have been trying to update from 3.2.6 to 3.2.9 and now I see that 3.2.10 is the most recent version. I have tried to update to that and it fails. When I select that "Update" button I get a sliding goldish bar then HOOBS logs me out and my dashboard stills says 3.2.6 and that an update to 3.2.10 is available.

**Comment by askovi** [comment]
Please follow the bug report template

**Comment by cbarnhart76** [comment]
> Please follow the bug report template

Excuse my ignorance but I don't know where that is or much about this part of HOOBS. I'm rather novice and need help.

**Comment by jlg89** [comment]
Click the "New issue" button and select the "Bug report" option. The post will contain a template. Copy that, return to this issue, and either paste the template into a new comment or edit your original comment and replace it with the template. Fill out the details, and help will be on the way.
