### ISSUE TITLE
3.2.10 - Service won't start (3.2.9 working perfectly)

### ISSUE THREAD

**Issue by enrogue** [hoobs-org/HOOBS#894]
**Description**
Service won't start (3.2.9 working perfectly)

**Version**
3.2.10

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
NO

**What device are you using?**
Please let us know the device you are running HOOBS on.
- DOCKER

**If this is a custom install, what's your operating system?**
DOCKER SYNOLOGY

**List your plugins**
DUMMY

**Comment by enrogue** [comment]
3.2.9 is working perfectly. Only one plug in currently: "Dummy" - Hoobs Certified

Here is the log with the error with 3.2.10 that causes Hoobs to abort the start:

11/9/2020, 2:25:22 PM HOOBS listening on port 8081.
11/9/2020, 2:25:23 PM assert.js:386
11/9/2020, 2:25:23 PM throw err;
11/9/2020, 2:25:23 PM ^
11/9/2020, 2:25:23 PM AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
11/9/2020, 2:25:23 PM at Bridge.Accessory [as constructor] (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1092:25)
11/9/2020, 2:25:23 PM at new Bridge (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Bridge.js:26:28)
11/9/2020, 2:25:23 PM at new Server (/usr/src/hoobs/bridge/server.js:86:23)
11/9/2020, 2:25:23 PM at module.exports (/usr/src/hoobs/bridge/cli.js:47:20)
11/9/2020, 2:25:23 PM at Object.<anonymous> (/usr/src/hoobs/bin/hoobs:63:81)
11/9/2020, 2:25:23 PM at Module._compile (internal/modules/cjs/loader.js:1015:30)
11/9/2020, 2:25:23 PM at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
11/9/2020, 2:25:23 PM at Module.load (internal/modules/cjs/loader.js:879:32)
11/9/2020, 2:25:23 PM at Function.Module._load (internal/modules/cjs/loader.js:724:14)
11/9/2020, 2:25:23 PM at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
11/9/2020, 2:25:23 PM at internal/main/run_main_module.js:17:47 {
11/9/2020, 2:25:23 PM generatedMessage: false,
11/9/2020, 2:25:23 PM code: 'ERR_ASSERTION',
11/9/2020, 2:25:23 PM actual: undefined,
11/9/2020, 2:25:23 PM expected: true,
11/9/2020, 2:25:23 PM operator: '=='
11/9/2020, 2:25:23 PM }

**Comment by mkellsy** [comment]
The only difference between 3.2.9 and 3.2.10 is the color of the logo in the splash screen for the light theme and a link in the about dialog.

Check to see if your data directory (hoobs) is mounted to the container.

**Comment by enrogue** [comment]
Everything looks clean. And the container log is clean too..

Container Log:
