### ISSUE TITLE
Support for arrays in config.schema.json 

### ISSUE THREAD

**Issue by aarons22** [hoobs-org/HOOBS#895]
**Is your feature request related to a problem? Please describe.**
I've had a few users have issues related to config validation because arrays aren't well supported. 

**Describe the solution you'd like**
In the Hoobs UI when users are configuring a plugin, I'd like there to be form fields when an array is specified in the config.schema.json with the correct items and properties (example [here](https://github.com/aarons22/homebridge-bond/blob/main/config.schema.json#L8-L41)).

_Current:_
- Right now, the fields is just a json text field, which leads to unexpected errors.
![image](https://user-images.githubusercontent.com/1285320/98608800-fb93e580-22b9-11eb-85f3-1f46f1e6dac3.png)

_Desired:_
- Something similar to what you get when you drop that config into this [schema validation tool](https://hamidihamza.com/ajsf/?framework=bootstrap-4)
![image](https://user-images.githubusercontent.com/1285320/98608978-5594ab00-22ba-11eb-8d17-5a8e5e79f128.png)

**Describe alternatives you've considered**
I'll likely add additional validation in my plugin to prevent issues, but this seems like a no-brainer for all plugins.

**Comment by mkellsy** [comment]
Already planned in HOOBS 4.
