### ISSUE TITLE
Is there a way to adjust terminal history?

### ISSUE THREAD

**Issue by jlg89** [hoobs-org/HOOBS#896]
The terminal screen seems to have a limited scrolling capacity, and at some point it runs out of buffer space, or something, and all terminal output just sits at the bottom line of the screen and overwrites itself, until terminal is stopped and restarted. Is there a way to adjust this?

**Comment by mkellsy** [comment]
The log in the UI only has the info from the current run. And it is truncated at 500 lines.

You can get more of the log by running this in the terminal.
```
sudo hoobs service log
```

We are adding this capability as well as more log controls in HOOBS 4.

**Comment by jlg89** [comment]
I meant the Terminal UI, for command line access. It seems like that window is limited in its buffer capacity.
