### ISSUE TITLE
Cannot add TPlink HS100 with the Tplink Smarthome Plugin

### ISSUE THREAD

**Issue by franco-101** [hoobs-org/HOOBS#897]
Hello,

Before updating to the latest version of the Tplink Smarthome Plugin my plug was successfully discovered. My HS100 smartplug was working correctly. Now that I have updated to version 6.1.0 of the plugin, my plug is no longer functioning correctly.
It is strange as the plug still appears as a valid accessory but there is no functionality.
I have tried uninstalling the TPlink Plugin, when the plugin is uninstall he smart plug accessory disappears. But when re installing the plugin it reappears with no functionality.

Log when cached accessory keeps adding.
`11/11/2020, 14:27:45 [TplinkSmarthome] Configuring cached accessory: [Fan] 80068CB8B2C6910BE3B82407DF5BF2C11C9228E7 7d36575f-3b3d-4c61-9cee-7b4b074599fb`

Error message in log when trying to uninstall plugin
```
11/11/2020, 14:27:54 npm
11/11/2020, 14:27:54  ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/homebridge-tplink-smarthome/node_modules/.bin/semver
11/11/2020, 14:27:54 npm
11/11/2020, 14:27:54 ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/homebridge-tplink-smarthome/node_modules/.bin/semver: is outside 
```

Fix this error by running
`hoobs@hoobs:~ $ rm -fR /home/hoobs/.hoobs/node_modules/homebridge-tplink-smarthome/node_modules/.bin/semver`

Tried removing 
```
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo rm -rf persist/
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo rm -rf accessories/

```
Any help would be apricated!

I have also tried from fresh install with the TPLink Plugin installed only and still no control of my HS100 plug.

Thanks
Francis

**Comment by mkellsy** [comment]
This is an issue with the plugin. The plugin shouldn't be accessing the semver binary. A better way to use semver is to access the module in your code. https://www.npmjs.com/package/semver

There are many different ways this could go wrong.

Please contact the plugin dev.

**Comment by mkellsy** [comment]
I looked into this.
The uninstalling issue is known and we are working on it.

For the HS100 plug.

I think you may need to modify the config.

The default config looks like this.
```
"switchModels": ["HS200", "HS210"]
```

You may need to add HS100.
```
"switchModels": ["HS100", "HS200", "HS210"]
```

**Comment by franco-101** [comment]
> I looked into this.
> The uninstalling issue is known and we are working on it.
> 
> For the HS100 plug.
> 
> I think you may need to modify the config.
> 
> The default config looks like this.
> 
> ```
> "switchModels": ["HS200", "HS210"]
> ```
> 
> You may need to add HS100.
> 
> ```
> "switchModels": ["HS100", "HS200", "HS210"]
> ```

How can I contact the plugin developer?

**Comment by mkellsy** [comment]
On the GitHub
https://github.com/plasticrake/homebridge-tplink-smarthome

**Comment by mac-n-cheese-uk** [comment]
Could be unrelated but it looks like TPlink have been rolling out firmware updates which has broken things for HomeAssistant users:

[https://www.home-assistant.io/blog/2020/11/23/tplink-local-access/](https://www.home-assistant.io/blog/2020/11/23/tplink-local-access/)

Not sure if the Homebridge plugin is also a casualty of the updates...
