### ISSUE TITLE
Hoobs won't start after add zigbee router and reboot

### ISSUE THREAD

**Issue by pedroxns** [hoobs-org/HOOBS#899]
Hey, in need of some help here !
I`ve got a rPi4 with a fresh Buster and started (for the 50th time) the process:
- Updated everything
- Plugins - Ewelink, Alexa, Hue, Dummy Garage and Schedule
- Installed Hoobs [https://support.hoobs.org/docs/5e763e30e87d1e02b6c19d33](url)
  + Plugins - z2m, Dummy Contact, Apple TV Remote
- Installed Zigbee2mqtt + mosquitto [https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html](url)
- installed Node-red [https://nodered.org/docs/getting-started/raspberrypi](url)

This setup was running at excelente conditions, CPU usage and Memory usage were low and had no delays.
Decided to add a zigbee router to improve my zigbee network, just plugged the usb CC2531 and decided to reboot for a fresh relationship between the devices, that's when (as we say in Brazil "The cow went to the swamp".
After the pi rebooted I couldn't find my beloved Hoobs on the usual (since the installation ) 80 port.
Got the following logs (sudo hoobs service log)

```
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 1.
Stopped HOOBS.
hoobs.service: Found left-over process 685 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started HOOBS.
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.serverListen [as listen] (/usr/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.
```

Gone exploring the possibilities and found this:
- I have a lot of ways to start hoobs service (no news for the experts but it was for a lame cook trying to understand things)
    - sudo systemctl start hoobs.service returns an endless loop with the error above.
    - sudo hoobs service start returns the same error
    - sudo hoobs - Starts a hoobs instance on port 81 and the web ui asked me for a new name, user and password as a brand new Hoobs.

I don't care about the plugins and configured accessories, in fact I'm ok with the idea that I already lost it all, just want to clean this up, get hoobs running at boot and understand the reason it happened, so I don't get this issue again in the future .

**Comment by askovi** [comment]
Your very first step was wrong. You need to flash the HOOBS img on your microSD card from our website. 

You flashed hb which is full of security issues  from installing global plugins and the UI comes with useless stuff like nginx. 

Try this fix to get rid of nginx which should also fix your permission issue:

`sudo systemctl disable nginx`

`sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`

`sudo reboot`

**Comment by pedroxns** [comment]
> Your very first step was wrong. You need to flash the HOOBS img on your microSD card from our website.
> 
> You flashed hb which is full of security issues from installing global plugins and the UI comes with useless stuff like nginx.
> 
> Try this fix to get rid of nginx which should also fix your permission issue:
> 
> `sudo systemctl disable nginx`
> 
> `sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`
> 
> `sudo reboot`

Thanks for your reply !
I've already tried this, while searching for solutions found a reply here somewhere with this instructions, but my return is:
```sudo systemctl disable nginx
Failed to disable unit: Unit file nginx.service does not exist.```

**Comment by askovi** [comment]
Looks like your node is installed elsewhere. Run this command to find the location:

`which node`

Then use the returned path in the command:

`sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`

then
`sudo reboot`
