### ISSUE TITLE
Upgrade and Migration Process

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#9]
- Setup your HOOBS on Rpi directly from Setupassistant
- Easy Update from any HOOBS Version (without reflashing SD and no HomeKit reset) v1.0/v1.0/v2.0.0/v2.1.0/v2.1.1
- Easy Migration from your existing Homebridge Setup (without reflashing SD and no HomeKit reset)

**Comment by mkellsy** [comment]
Same as issue #24
