### ISSUE TITLE
Can't update or remove plugin, like #829

### ISSUE THREAD

**Issue by czarnyolek** [hoobs-org/HOOBS#901]
Hello

The same situation like issue #829 

Cant update and remove Bravia Tvos plugin  . Can you help? What will be commnad  for manual removal?

Or maybe tutorial how can remove after this command:
sudo nano ~/.hoobs/package.json

Thank you

**Comment by mkellsy** [comment]
The node modules are stuck. These commands should get you fixed up.
```
cd ~/.hoobs
sudo rm -fR ./node_modules
npm install
```

The reboot or restart the HOOBS service.

**Comment by czarnyolek** [comment]
Thank you, now working

:+1:
