### ISSUE TITLE
I want reset hoobs in a box

### ISSUE THREAD

**Issue by SonEunju** [hoobs-org/HOOBS#902]
I connected to hoobs
![제목 없음](https://user-images.githubusercontent.com/74124278/99082798-fad7b800-2607-11eb-8476-0e85827eace6.png)
 ui a few days ago and also connected to apple home. However, after removing the hoobs bridge from the home app, the hoobs cannot connect to the network.
I connected to 192.168.24, but now it is also unreachable.
As a result of checking my router, it turns out that the hoobs are assigned to the network at 192.168.0.24. How can I use hoobs? Is there any way to force reset?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by askovi** [comment]
Please make sure HOOBS is plugged into your main node if you're using a mesh network. Then go to the Help menu in the HOOBS UI and click on Reset Connection. Then rescan the new QR code on the dashboard
