### ISSUE TITLE
camera-ffmpeg plugin

### ISSUE THREAD

**Issue by panzer1234** [hoobs-org/HOOBS#908]
Hi,

I installed the camera-ffmpeg plugin into hoobs, got it all working on the Apple Ios Home APP

BUT

Is there any way to get the stream visible on the HOOBS accessory page (Camera icon), as i got the hoobs webpage loaded on a touchscreen in the livingroom

**Comment by panzer1234** [comment]
sorry it's not closed

**Comment by askovi** [comment]
This is already being worked on and is coming out in HOOBS 4.

**Comment by panzer1234** [comment]
When is hoobs 4 being released? :)

There is no temp solution for this until hoobs 4?



Op 17 nov. 2020 om 02:11 heeft Ovidiu Mija <notifications@github.com> het volgende geschreven:

﻿

This is already being worked on and is coming out in HOOBS 4.

**Comment by jlg89** [comment]
Just use an RTSP client like VLC, HomeCam, Webcam HQ, etc.
