### ISSUE TITLE
Factory Reset Hoobs in a Box and then actually get it working with Apple HomeKit

### ISSUE THREAD

**Issue by AR3A50TONE** [hoobs-org/HOOBS#912]
Hello,
First thing, how do I restore my HOOBS in a Box to factory so I can start all over? I don't remember my login information. Once I start over with new login credentials I will make one last attempt to add my HOOBS to HomeKit as a Bridge then start searching and installing the Plugins I need, at this point I will cross my fingers that they appear in my HomeKit screen on y iPad, this is the point I've never made it to before.

**Comment by askovi** [comment]
Here are the instructions to reset your password:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this to reset the users file:  sudo rm -rf /home/hoobs/.hoobs/etc/access.json

Press enter. There will be no output.

3. Type this to reboot the HOOBS Box: sudo reboot

4. Allow 2-3 minutes for the HOOBS Box to reboot then go to http://hoobs.local and create a new account.

This won't affect your plugins and accessories, only your user.

**Comment by AR3A50TONE** [comment]
Hello,
This isn’t working? Is there a space between “sudo rm and -rf”?

**Comment by askovi** [comment]
Yes. Please copy and paste the commands exactly as shown in my comment above.

**Comment by AR3A50TONE** [comment]
Awesome it worked, thank you so much!

Now I'm having road blocks, I've been successful at installing Plugins. I'll talk about Ring Doorbell specifically. For the life of me I can't figure out how to get it to appear in my Apple HomeKit app. I do the refresh token part,and other task mentioned in setup instructions and nothing works

**Comment by OfficialKaos** [comment]
you need to add each camera as an accessory seperately and use the same 8 digit pin from your HOOBS for each one

**Comment by mkattan1992** [comment]
> Here are the instructions to reset your password:
> 
>     1. Login to the HOOBS Box via SSH on your computer.
> 
> 
> On MacOS use the Terminal app and type: ssh [hoobs@hoobs.local](mailto:hoobs@hoobs.local)
> 
> Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin
> 
> On Windows, use Putty with the same credentials as above.
> 
>     1. After successfully logging in, type this to reset the users file:  sudo rm -rf /home/hoobs/.hoobs/etc/access.json
> 
> 
> Press enter. There will be no output.
> 
>     1. Type this to reboot the HOOBS Box: sudo reboot
> 
>     2. Allow 2-3 minutes for the HOOBS Box to reboot then go to http://hoobs.local and create a new account.
> 
> 
> This won't affect your plugins and accessories, only your user.

Hi askovi,
i would like to reset my box to factory default including all accessories ? what process/commands shall i follow ? thanks

**Comment by runningfool20** [comment]
sorry to piggyback off of this post. i tried the reset instructions here in MacOS terminal and everything seems to go right. But when I go to hoobs.local or 192.168.1.67 (my box's IP), i get the Chrome error page that reads, "This site can't be reached" Any thoughts to get to some sort of resolution?
