### ISSUE TITLE
Ring Cameras

### ISSUE THREAD

**Issue by Zwoliwhop** [hoobs-org/HOOBS#913]
Hello almighty forum geniuses,

I was having trouble with my ring cameras “not responding” in my Home App and I tried creating a new token and rebooting the device but I have had no luck.  I figured since the only plugin I use is the ring plugin that I will just factory reset this bad boy and start fresh, I don’t have to many ring devices, so it was an easy set up and once I got everything done I noticed my cameras were back up with a snapshot.  Unfortunately when I click the cameras to go to a live view I get the dreaded “camera not responding” error.  I can open them up just fine in my ring app and my connections are all good since I have a 1gb fiber line.  Secondly I can not seem to get the home app to show up on the Apple TV side bar where I would be able to see the cameras.  It says connected but again I have no clue as to why everything went a rye when it was working perfectly for weeks. 

sincerely, 

A noob at all of this

**Comment by askovi** [comment]
Please try to stream in Homekit while having the HOOBS logs page open. When you see the No response message, check the logs for errors and paste them here so we can troubleshoot.

**Comment by Zwoliwhop** [comment]
Hello,

Ok, this is what I got.

**Comment by Tesla-P100FX** [comment]
> Please try to stream in Homekit while having the HOOBS logs page open. When you see the No response message, check the logs for errors and paste them here so we can troubleshoot.

from Status.ring.com.  I can not get mine to work reliably right now either.  Others are updating node.js to a current version and says that solves the issue but Hoobs is not running the latest version 

Nov 19, 2020
Live Video Feed Failures
Resolved - This incident has been resolved.
Nov 19, 00:47 UTC
Investigating - We are investigating reports of failures when trying to connect to an on-demand live view events as well as doorbell button push events and motion events. You may receive delays or errors when trying to access live video feeds from your device. We are working to resolve this as soon as possible.
Nov 18, 22:08 UTC
Nov 18, 2020
Live Video Feed Failures
Resolved - We have identified and resolved our trouble with live video connections. All users should be able to connect to live view, push button, and motion events normally. Thank you for your patience.
Nov 18, 21:31 UTC
Update - We are continuing to investigate this issue.
Nov 18, 21:00 UTC
Update - We are continuing to investigate this issue.
Nov 18, 21:00 UTC
Investigating - We are investigating reports of failures when trying to connect to an on-demand live view events as well as doorbell button push events and motion events. You may receive delays or errors when trying to access live video feeds from your device. We are working to resolve this as soon as possible.
Nov 18, 20:55 UTC

**Comment by Zwoliwhop** [comment]
<img width="1680" alt="Screen Shot 2020-11-19 at 09 34 09" src="https://user-images.githubusercontent.com/74720341/99732094-de66d000-2a8c-11eb-8b17-821c7beb271f.png">

**Comment by Zwoliwhop** [comment]
That’s all I have in my logs. It just keeps repeating.

**Comment by Tesla-P100FX** [comment]
Look at this thread i posted , with the Ring Developer. https://github.com/dgreif/ring/issues/496

**Comment by schpeen** [comment]
any updates on this problem i am getting same just keeps trying over and over saying it cant reach ring refresh token. How do you roll back a version of a plugin on Hoobs? someone said to rollback to a previous verson.

**Comment by askovi** [comment]
This is a Ring plugin issue. Please continue the discussion with the developer here https://github.com/dgreif/ring/issues/496
The plugin will update on HOOBS as soon as it is released by the developer.
