### ISSUE TITLE
Plguin install failed

### ISSUE THREAD

**Issue by NuLevelness** [hoobs-org/HOOBS#915]
I'm upgraded to the latest version but can't install any plugins. Logs below. 

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
11/20/2020, 12:10:57 AM 
11/20/2020, 12:10:57 AM npm
11/20/2020, 12:10:57 AM 
11/20/2020, 12:10:57 AM ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-11-20T06_10_57_293Z-debug.log
11/20/2020, 12:12:32 AM Unhandled rejection Error: EACCES: permission denied, mkdir '/home/hoobs/.npm/_cacache/index-v5/12/b8'
11/20/2020, 12:12:47 AM npm
11/20/2020, 12:12:47 AM 
11/20/2020, 12:12:47 AM ERR! cb() never called!
11/20/2020, 12:12:47 AM 
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
11/20/2020, 12:12:48 AM 
11/20/2020, 12:12:48 AM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-11-20T06_12_48_032Z-debug.log

**Comment by mkellsy** [comment]
The NPM cache is root locked. Open the terminal and run this command.
```
sudo rm -fR /home/hoobs/.npm
```

This will clear the root locked cache and you should be able to install the plugin.
