### ISSUE TITLE
HOOBS.local not reachable

### ISSUE THREAD

**Issue by nippy1** [hoobs-org/HOOBS#917]
I have just installed Hoobs via an Ethernet Cable and successfully connected to the user interface through hoobs.local and added the bridge to Homekit OK. I then updated the software to the latest version but during the software update the Safari window closed and since then I have been unable to launch hoobs.local. I have tried reconnecting everything and tried the wifi connection but I still get the Safari  cannot connect message. I can see and IP address for the Hoobs bridge and I have tried that in the browser but still get the same Safari cannot connect message. What do I try next ?

**Comment by askovi** [comment]
Please post your logs. 

Here are the instructions to retrieve the logs:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this command: sudo hoobs service log

**Comment by mkellsy** [comment]
Your router might be picking .local addresses. Try http://hoobs.lan or try the ip address if you have it http://192.168.X.X

**Comment by nippy1** [comment]
I have followed the instructions you sent me however I cannot access the log from terminal – see below. I have now noticed that there is no flashing green light on the router box – I have swapped all the cables with ports that are working but no success. There appears to be power supply to the HOOBs box (dull red) so it appears there might be a problem with the box itself.
 
 
 
 
Last login: Fri Nov 20 20:07:17 on console
Restored session: Fri 20 Nov 2020 18:30:06 GMT
 
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Pauls-iMac:~ paulnippard$ ssh@hoobs.local
-bash: ssh@hoobs.local: command not found
Pauls-iMac:~ paulnippard$ 
Pauls-iMac:~ paulnippard$ ssh@hoobs.local

**Comment by mkellsy** [comment]
The command is
```
ssh hoobs@hoobs.local
```

**Comment by Chumnick** [comment]
Hey. I have the same problem... Can you help me? Thanks. My log is here:

sudo hoobs service log
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 94.
Stopped HOOBS.
hoobs.service: Found left-over process 4064 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 4071 (sh) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 4072 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started HOOBS.
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1300:21)
    at listenInCluster (net.js:1365:12)
    at Server.listen (net.js:1451:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}

**Comment by nippy1** [comment]
I did not find a solution and have emailed Info@hoobs.org because I think they might have to send me a replacement box as it is not booting properly. I will post any response from them.

**Comment by cdstickney77** [comment]
> I did not find a solution and have emailed Info@hoobs.org because I think they might have to send me a replacement box as it is not booting properly. I will post any response from them.
> […](#)
> On 24 Nov 2020, at 17:48, Chumnick ***@***.***> wrote: ﻿ Hey. I have the same problem... Can you help me? Thanks. My log is here: sudo hoobs service log errno: 'EACCES', syscall: 'listen', address: '0.0.0.0', port: 80 } [HOOBS] Stopping server. hoobs.service: Main process exited, code=exited, status=1/FAILURE hoobs.service: Failed with result 'exit-code'. hoobs.service: Service RestartSec=3s expired, scheduling restart. hoobs.service: Scheduled restart job, restart counter is at 94. Stopped HOOBS. hoobs.service: Found left-over process 4064 (node) in control group while starting unit. Ignoring. This usually indicates unclean termination of a previous run, or service implementation deficiencies. hoobs.service: Found left-over process 4071 (sh) in control group while starting unit. Ignoring. This usually indicates unclean termination of a previous run, or service implementation deficiencies. hoobs.service: Found left-over process 4072 (node) in control group while starting unit. Ignoring. This usually indicates unclean termination of a previous run, or service implementation deficiencies. Started HOOBS. Error: listen EACCES: permission denied 0.0.0.0:80 at Server.setupListenHandle [as _listen2] (net.js:1300:21) at listenInCluster (net.js:1365:12) at Server.listen (net.js:1451:7) at Function.serverListen [as listen] ***@***.***/hoobs/node_modules/express-ws/lib/index.js:42:40) at API.start ***@***.***/hoobs/server/api.js:191:17) at module.exports ***@***.***/hoobs/server/cli.js:172:21) { code: 'EACCES', errno: 'EACCES', syscall: 'listen', address: '0.0.0.0', port: 80 } — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Did you ever get a response?  If so, what did they say as I am having a similar issue myself.

**Comment by mkellsy** [comment]
You need to SSH into the box and run this command
```
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
```

**Comment by nippy1** [comment]
I received the following response from hoobs.org – everything is working now.

 

I apologize for the late reply.

If you cannot see HOOBS on your network at all, it might indicate a microSD card corruption. This can happen in some rare cases if the HOOBS Box lost power or was improperly shut down by removing the power cable without shutting it down from the top right menu first, while it was writing data to the microSD card. The only fix is to reflash the microSD card. Here are the steps to do that:

 

You will have to unscrew the 4 screws on the bottom of the HOOBS Box and take the board out then remove the microSD card and plug it into your computer, then follow this guide:

https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

 

You can download the img file free or charge from here: https://download.hoobs.org/HOOBS-armv7.zip
