### ISSUE TITLE
Hoobs.local Not reachable; box is Not working anymore

### ISSUE THREAD

**Issue by 1982GERAlex** [hoobs-org/HOOBS#918]
**Description**
I can’t reach the hoobs.local Site and the Box isn’t working. I only had one plugin for my Rademacher blinds. 
They worked for 8 month now in this setup. Suddenly so response. 
Hope you guys can help me. 

**Version**
Hoobs Box. Don’t know the version no. 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Rademacher blinds plug-in 
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

The authenticity of host 'hoobs.local (2003:d0:cf22:d00:f14:4476:16ac:beae)' can't be 
established.
ECDSA key fingerprint is SHA256:1GL49Aa+E4o9wjVFXrK5VlL3u8rdOIrMhYJR1x8t7B4.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'hoobs.local,2003:d0:cf22:d00:f14:4476:16ac:beae' (ECDSA) 
to the list of known hosts.
hoobs@hoobs.local's password: 
Linux hoobs 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l
Raspberry Pi 3 Model B Rev 1.2
*** HOOBS - Homebridge Out Of The Box ***
 _ _ ____ ____ ____ _____ 
 | | | |/ __ \ / __ \| _ \ / ____| 
 | |__| | | | | | | | |_) | (___ 
 | __ | | | | | | | _ < \___ \ 
 | | | | |__| | |__| | |_) |____) | 
 |_| |_|\____/ \____/|____/|_____/ 
 
To configure HOOBS browse to the one of the following addresses from another 
device on your network:
* http://hoobs.local
* http://192.168.178.25
* http://[2003:d0:cf22:d00:f14:4476:16ac:beae]
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
hoobs@hoobs:~ $ sudo hoobs service log
 at Object.<anonymous> 
(/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/archiver-utils/index.js:11:18)
 at Module._compile (internal/modules/cjs/loader.js:778:30)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
 at Module.load (internal/modules/cjs/loader.js:653:32)
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 25562.
Stopped HOOBS.
Started HOOBS.
internal/modules/cjs/loader.js:638
 throw err;
 ^
Error: Cannot find module 'readable-stream/passthrough'
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
 at Function.Module._load (internal/modules/cjs/loader.js:562:25)
 at Module.require (internal/modules/cjs/loader.js:692:17)
 at require (internal/modules/cjs/helpers.js:25:18)

This repeats on and on
**Additional context**

**Comment by Slartybart** [comment]
With thanks to Rodrigo Mendonça who posted this on the Facebook page:
When accessing Hoobs through a browser IP add port 80 or 8080 after hoops.local or the ip address
(hoobs.local:8080 or xxx.xxx.xxx.xxx:8080)

Worked for me I..... should have thought to try this myself.....

**Comment by 1982GERAlex** [comment]
Thanks for the comment. I already tried it. No chance to get in. I can see the hoobs logo but the white loading sign ist just going through. 

How is the warranty time for purchase the box? One year?
