### ISSUE TITLE
would like some pointers on modifying Hoobs

### ISSUE THREAD

**Issue by Final-Hawk** [hoobs-org/HOOBS#920]
Hi,
This is NOT a bug report, just simply looking for some help. I am currently using a homebridge managing app that only works with hoobs and config-ui-x, but I would like to monitor another different systemd service, more specifically HAP-NodeJS. I was wondering how or if I could get hoobs to monitor that service instead of the homebridge service. I do not care if it gives lots of errors,  all I want is running status and start stop reboot control. To note I am on raspberry os and have spent over 2 hours trying to figure it out myself. Thanks in advance and hope you can help.

**Comment by askovi** [comment]
Can you please give more details what you're trying to do and which app are you using?

**Comment by Final-Hawk** [comment]
Hi, so sorry for the late reply. What I am trying to do is to make the hoobs ui report the status of a hap-nodejs service instead of the hoobs service. The reason I would like to do this is so I can use the homemanager app to control and report the status of the hap-nodejs service.  Hope you can point the in the right direction! Thanks.

**Comment by mkellsy** [comment]
HAP is a module in Homebridge and HOOBS it is not a service. Monitoring HOOBS or Homebridge includes any logging from HAP too.
