### ISSUE TITLE
Sony Bravia "EADDRINUSE: address already in use"

### ISSUE THREAD

**Issue by ptamayon** [hoobs-org/HOOBS#921]
**Description**
After resetting Hoobs yesterday the Sony Bravia TV plug-in stopped to display the Sony Bravia tv.  When the PIN displayed is entered on http://hoobs:8999 the authentication can not be completed on time making the TV PIN to expired.
The TV was connected with Homekit with out any issue.

The Hoobs bridge on Homekit was deleted and then re-added to Homekit an error is displayed on the Hoobs log indicating that the address already exists however nothing had been changed on the plug-in configuration (Hoobs was started with a Configuration backup)

**Version** HOOBS  3.2.10
**Upgraded from Version** 3.2.6
**Node Version** 12.16.3
**What device are you using?**  Custom Install
**If this is a custom install, what's your operating system?** Raspbian
**List your plugins**
   - Tuya Web
   - Hombridge-Bravia
   - Nest
   - Unifi Protect

**Config**
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "xxxxxxxxx",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "xxxx",
        "latitude": "0000° N",
        "longitude": "0000° W"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xxx-xxx-xxx",
        "username": "xxxxxxxxxxxxxx"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest",
            "googleAuth": {
                "issueToken": "xxxxx",
                "cookies": "xxxxx",
                "apiKey": "xxxxxx"
            }
        },
        {
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            },
            "name": "TuyaWebPlatform",
            "scenes": false,
            "options": {
                "platform": "tuya",
                "username": "email address",
                "password": "xxxxxxx",
                "countryCode": "1"
            }
        },
        {
            "platform": "UniFi Protect",
            "plugin_map": {
                "plugin_name": "homebridge-unifi-protect"
            },
            "controllers": [
                {
                    "address": "xxx.xxx.xxx.xxx",
                    "username": "xxxxxx",
                    "password": "xxxxxxx"
                }
            ]
        },
        {
            "platform": "BraviaPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-bravia"
            },
            "tvs": [
                {
                    "name": "Family TV",
                    "ip": "192.168.99.167",
                    "tvsource": "tv:HDMI 1",
                    "soundoutput": "speaker",
                    "applications": [
                        {
                            "title": "AppleTV+"
                        }
                    ],
                    "sources": [
                        "extInput:HDMI"
                    ],
                    "listapplications": 0,
                    "cookiepath": "/root/.homebridge/sonycookie"
                },
                {
                    "name": "Master TV",
                    "ip": "192.168.99.161",
                    "tvsource": "tv:HDMI 1",
                    "soundoutput": "speaker",
                    "applications": [
                        {
                            "title": "AppleTV+"
                        },
                        {
                            "title": "YouTube TV"
                        }
                    ],
                    "sources": [
                        "extInput:HDMI"
                    ],
                    "listapplications": 1,
                    "cookiepath": "/root/.homebridge/second_sonycookie"
                },
                {
                    "name": "Media TV",
                    "ip": "192.168.99.169",
                    "tvsource": "tv:HDMI 1",
                    "soundoutput": "speaker",
                    "applications": [
                        {
                            "title": "AppleTV+"
                        }
                    ],
                    "sources": [
                        "extInput:HDMI"
                    ],
                    "listapplications": 2,
                    "cookiepath": "/root/.homebridge/third_sonycookie"
                }
            ]
        }
    ]
}

**Log**
[BraviaPlatform] Creating new accessory for Family TV
[BraviaPlatform] New TV Family TV, will be queried for channels/apps and added to HomeKit
[BraviaPlatform] Creating new accessory for Master TV
[BraviaPlatform] New TV Master TV, will be queried for channels/apps and added to HomeKit
[BraviaPlatform] Creating new accessory for Media TV
[BraviaPlatform] New TV Media TV, will be queried for channels/apps and added to HomeKit
Bridge is running on port 51826.
[BraviaPlatform] Need to authenticate with TV!
[BraviaPlatform] Please enter the PIN that appears on your TV at http://hoobs:8999
[BraviaPlatform] PIN entry web server listening
[BraviaPlatform] Need to authenticate with TV!
[BraviaPlatform] Please enter the PIN that appears on your TV at http://hoobs:8999
[BraviaPlatform] PIN entry web server error: Error: listen EADDRINUSE: address already in use :::8999
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at onSucces (/home/hoobs/.hoobs/node_modules/homebridge-bravia/index.js:274:19)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-bravia/index.js:924:9)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8999
}
[BraviaPlatform] Need to authenticate with TV!
[BraviaPlatform] Please enter the PIN that appears on your TV at http://hoobs:8999
[BraviaPlatform] PIN entry web server error: Error: listen EADDRINUSE: address already in use :::8999
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at onSucces (/home/hoobs/.hoobs/node_modules/homebridge-bravia/index.js:274:19)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-bravia/index.js:924:9)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8999
}

**Additional context**

**Comment by askovi** [comment]
That means port 8999 is already in use by another service. Try rebooting HOOBS from the top right menu and see if it fixes it.

**Comment by ptamayon** [comment]
I

> 
> 
> That means port 8999 is already in use by another service. Try rebooting HOOBS from the top right menu and see if it fixes it.

I did that and only 2 of the 3 TVs can be registered.  The 3rd one is getting the same error message.
