### ISSUE TITLE
Ring Plugin works only with bug in Hoobs

### ISSUE THREAD

**Issue by Otto-Wilhelm** [hoobs-org/HOOBS#922]
**Description**

The Ring plugin allows under Homebridge to select one of the alarm modes "home" and "away" as "night" alarm modes, which does not require that an open contact sensor is confirmed. This selection is not possible in Hoobs. The selection drop down box in the configuration menu doesn't work.

**Version**
3.2.10

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

Complete new installation on Raspberry 4 with the image downloaded from Hoobs. Now additional plugin installed so far besides the Ring plugin.

For the time being I will return to normal Homebridge.

**Comment by askovi** [comment]
Please open an issue with the plugin developer here: https://github.com/dgreif/ring/issues

**Comment by Otto-Wilhelm** [comment]
In Homebridge the plugin works fine, so that I thought that there is a problem in Hoobs. Nevertheless, I posted the bug report to the developer.
