### ISSUE TITLE
Ikea Tradfri Gateway Crashes hoops bridge

### ISSUE THREAD

**Issue by gmum4d** [hoobs-org/HOOBS#924]
The Ikea Tradfri Gateway (Certified) plugin is crashing my Hoobs bridge service. It's been working fine for months, then all of a sudden the bridge stopped. I've un-installed all my plugins and removed config files then reinstalled them one by one until I found the bridge stop again as soon as the tradfri gateaway plugin is installed.  Is this a known issue?

**Comment by askovi** [comment]
Please follow the bug report template

**Comment by askovi** [comment]
Duplicate of #926
