### ISSUE TITLE
OTGW plugin no longer works

### ISSUE THREAD

**Issue by theactiv** [hoobs-org/HOOBS#927]
**Description**
I have been using the OTGW pluging for a few months now and all was well. After the latest update it stopped working.

**Expected behavoir**
Normally I would see status messages in the log and I would be able to control my thermostat. 

**Plugin name**
homebridge-otgw

**Please report the issue to the plugin developer**
https://github.com/ebaauw/homebridge-otgw/issues/4

**Version**
3.2.10

**Did you upgrade**
Please let us know if you upgraded from a previous version.
Yes, but that is not when the problem started. It was after updating to the latest version of the plugin.

**Pervious version**
The plugin? it was 1.1.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
No. I started with 3 about a month ago.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYL7L2",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "NL",
        "postal_code": "",
        "latitude": "",
        "longitude": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "",
        "username": ""
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": ""
        },
        {
            "platform": "eveatmo",
            "plugin_map": {
                "plugin_name": "homebridge-eveatmo"
            },
            "name": "eveatmo platform",
            "ttl": 540,
            "extra_co2_sensor": false,
            "co2_alert_threshold": 1000,
            "auth": {
                "client_id": "",
                "client_secret": "",
                "username": "",
                "password": ""
            }
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "lights": true,
            "linkButton": false,
            "sensors": true,
            "wallSwitch": false,
            "schedules": false,
            "scenes": false,
            "rules": false,
            "rooms": false,
            "group0": false,
            "groups": false,
            "forceEveWeather": false,
            "forceHttp": false,
            "users": {
                "": ""
            }
        },
        {
            "platform": "FibaroHC2",
            "host": "192.168.1.4",
            "username": "homebridge",
            "password": "",
            "plugin_map": {
                "plugin_name": "homebridge-fibaro-hc2"
            }
        },
        {
            "platform": "OTGW",
            "plugin_map": {
                "plugin_name": "homebridge-otgw"
            },
            "name": "OTGW",
            "host": "192.168.1.45:8081",
            "otgw": "192.168.1.45:8081"
        }
    ]
}
```

**Post your log**
11/27/2020, 10:05:28 PM Loaded plugin 'homebridge-eveatmo'11/27/2020, 10:05:28 PM [11/27/2020, 2:05:28 PM] Registering platform 'homebridge-eveatmo.eveatmo'11/27/2020, 10:05:28 PM Loaded plugin 'homebridge-fibaro-hc2'11/27/2020, 10:05:28 PM [11/27/2020, 2:05:28 PM] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'11/27/2020, 10:05:28 PM [11/27/2020, 2:05:28 PM] The plugin "homebridge-hue" requires Node version of ^14.15.1 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.11/27/2020, 10:05:29 PM Loaded plugin 'homebridge-hue'11/27/2020, 10:05:29 PM [11/27/2020, 2:05:29 PM] Registering platform 'homebridge-hue.Hue'11/27/2020, 10:05:29 PM [11/27/2020, 2:05:29 PM] The plugin "homebridge-otgw" requires Node version of ^14.15.1 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.11/27/2020, 10:05:29 PM Loaded plugin 'homebridge-otgw'11/27/2020, 10:05:29 PM [11/27/2020, 2:05:29 PM] Registering platform 'homebridge-otgw.Lib'11/27/2020, 10:05:29 PM [11/27/2020, 2:05:29 PM] Registering platform 'homebridge-otgw.OTGW'11/27/2020, 10:05:30 PM Loaded plugin 'homebridge-ring'11/27/2020, 10:05:30 PM [11/27/2020, 2:05:30 PM] Registering platform 'homebridge-ring.Ring'11/27/2020, 10:05:30 PM Loading 5 platforms...11/27/2020, 10:05:30 PM [Ring] Initializing Ring platform...11/27/2020, 10:05:30 PM [eveatmo platform] Initializing eveatmo platform...11/27/2020, 10:05:30 PM [eveatmo platform] Loading new data from API for: weatherstation11/27/2020, 10:05:30 PM [Hue] Initializing Hue platform...11/27/2020, 10:05:30 PM [Hue] config.json: warning: plugin_map: ignoring unknown key11/27/2020, 10:05:30 PM [Hue] homebridge-hue v0.12.3, node v12.16.3, homebridge v1.1.611/27/2020, 10:05:30 PM [Hue] warning: not using recommended node version v14.15.1 LTS11/27/2020, 10:05:30 PM [FibaroHC2] Initializing FibaroHC2 platform...11/27/2020, 10:05:30 PM [OTGW] Initializing OTGW platform...11/27/2020, 10:05:30 PM [OTGW] homebridge-otgw v1.1.2, node 12.16.3, homebridge v1.1.6, homebridge-lib v5.0.011/27/2020, 10:05:30 PM [OTGW] warning: not using recommended node v14.15.1 LTS11/27/2020, 10:05:30 PM [OTGW] warning: config.json: plugin_map: invalid key11/27/2020, 10:05:30 PM [Ring] Configuring cached accessory 41533d95-85b4-431e-8225-2d983d9b6007 Front Door11/27/2020, 10:05:30 PM [Ring] Configuring cached accessory 72216ab8-6cce-48cb-b545-25afbd0195b9 Hallway11/27/2020, 10:05:30 PM [Ring] Configuring cached accessory 33964b19-29dc-43b6-bd5c-a0fb1a5888b9 'S-Gravenhage Mode11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Mouse lamp11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Laundry switch 111/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Laundry switch 211/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Living Switch 111/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Living Switch 211/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Hall Switch11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Outside Switch11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Kitchen Switch 111/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Kitchen Switch 211/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Toilet Switch11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Bathroom Switch 111/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Bathroom Switch 211/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Calla Dimmer11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Passage 2nd Dimmer11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Jar light left11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Study Switch 111/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Study Switch 211/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Jar light right11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Front door11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Kitchen door11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Kitchen window11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Study door11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Study Window11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Book cupboard11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Kitchen Window Front11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  WindowSensor11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  SeondFloorWindow11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Bathroom Temp11/27/2020, 10:05:30 PM [FibaroHC2] Configured Accessory:  Bathroom Humidity11/27/2020, 10:05:30 PM [FibaroHC2] didFinishLaunching. 11/27/2020, 10:05:30 PM [OTGW] restored 4 accessories from cache11/27/2020, 10:05:30 PM [FibaroHC2] Loading accessories 11/27/2020, 10:05:30 PM [FibaroHC2] Added/changed accessory:  Mouse lamp11/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Laundry switch 111/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Laundry switch 211/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Living Switch 111/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Living Switch 211/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Hall Switch11/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Outside Switch11/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Kitchen Switch 111/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Kitchen Switch 211/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Toilet Switch11/27/2020, 10:05:31 PM [FibaroHC2] Added/changed accessory:  Bathroom Switch 111/27/2020, 10:05:32 PM [FibaroHC2] Added/changed accessory:  Bathroom Switch 211/27/2020, 10:05:32 PM [FibaroHC2] Added/changed accessory:  Calla Dimmer11/27/2020, 10:05:32 PM [FibaroHC2] Added/changed accessory:  Passage 2nd Dimmer11/27/2020, 10:05:32 PM [FibaroHC2] Added/changed accessory:  Jar light left11/27/2020, 10:05:32 PM [FibaroHC2] Added/changed accessory:  Study Switch 111/27/2020, 10:05:32 PM [FibaroHC2] Added/changed accessory:  Study Switch 211/27/2020, 10:05:32 PM [FibaroHC2] Added/changed accessory:  Jar light right11/27/2020, 10:05:32 PM [FibaroHC2] Added/changed accessory:  Front door11/27/2020, 10:05:32 PM [FibaroHC2] Added/changed accessory:  Kitchen door11/27/2020, 10:05:33 PM [FibaroHC2] Added/changed accessory:  Kitchen window11/27/2020, 10:05:33 PM [FibaroHC2] Added/changed accessory:  Study door11/27/2020, 10:05:33 PM [FibaroHC2] Added/changed accessory:  Study Window11/27/2020, 10:05:33 PM [FibaroHC2] Added/changed accessory:  Book cupboard11/27/2020, 10:05:33 PM [FibaroHC2] Added/changed accessory:  Kitchen Window Front11/27/2020, 10:05:33 PM [FibaroHC2] Added/changed accessory:  WindowSensor11/27/2020, 10:05:33 PM [FibaroHC2] Added/changed accessory:  SeondFloorWindow11/27/2020, 10:05:33 PM [FibaroHC2] Added/changed accessory:  Bathroom Temp11/27/2020, 10:05:34 PM [FibaroHC2] Added/changed accessory:  Bathroom Humidity11/27/2020, 10:05:34 PM [OTGW] warning: heartbeat 0, drift 238611/27/2020, 10:05:34 PM [OTGW] connecting to OpenTherm Monitor...11/27/2020, 10:05:34 PM [Hue] searching bridges and gateways11/27/2020, 10:05:34 PM [OTGW] warning: heartbeat 1, drift 143911/27/2020, 10:05:34 PM [OTGW] warning: heartbeat 2, drift 44211/27/2020, 10:05:34 PM [OTGW] connected to OpenTherm Monitor at ws://192.168.1.45:8081/message.ws11/27/2020, 10:05:34 PM HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.11/27/2020, 10:05:34 PM Initializing platform accessory 'Goudvisplein (Kitchen) Kitchen'...11/27/2020, 10:05:34 PM Initializing platform accessory 'Goudvisplein (Kitchen) Garden'...11/27/2020, 10:05:34 PM [OTGW] warning: T80190000: out of sequence OpenTherm message - reset sequence11/27/2020, 10:05:35 PM [Ring] Configuring 1 cameras and 3 devices for location "'S-Gravenhage" - locationId: cef8fc00-d315-4cc1-b951-3fedd186693811/27/2020, 10:05:39 PM [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1941132070, api v1.41.011/27/2020, 10:05:39 PM [Hue] Philips hue: 12 accessories11/27/2020, 10:05:39 PM [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz11/27/2020, 10:05:39 PM Initializing platform accessory 'Philips hue'...11/27/2020, 10:05:39 PM [Hue] Philips hue: 2 services11/27/2020, 10:05:39 PM Initializing platform accessory 'Bedroom'...11/27/2020, 10:05:39 PM Initializing platform accessory 'Subwoofer 1'...11/27/2020, 10:05:39 PM Initializing platform accessory 'Subwoofer 2'...11/27/2020, 10:05:39 PM Initializing platform accessory 'Study ledstrip'...11/27/2020, 10:05:39 PM Initializing platform accessory 'Daylight'...11/27/2020, 10:05:39 PM Initializing platform accessory 'XFDani[1]sn:state'...11/27/2020, 10:05:39 PM Initializing platform accessory 'XFDani[1][1]sn:step'...11/27/2020, 10:05:39 PM Initializing platform accessory 'start - stop'...11/27/2020, 10:05:39 PM Initializing platform accessory 'state'...11/27/2020, 10:05:39 PM Initializing platform accessory 'Play and stop'...11/27/2020, 10:05:39 PM Initializing platform accessory 'daypart'...11/27/2020, 10:05:39 PM Bridge is running on port 51826.11/27/2020, 10:05:40 PM [Hue] Bedroom: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":13,"characteristic":2}]}11/27/2020, 10:05:40 PM [Hue] Bedroom: set homekit transition control to ""11/27/2020, 10:05:40 PM [Hue] Study ledstrip: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":21,"characteristic":2}]}11/27/2020, 10:05:40 PM [Hue] Study ledstrip: set homekit transition control to ""11/27/2020, 10:05:55 PM [Hue] Study ledstrip: set homekit transition control to ""11/27/2020, 10:05:55 PM [Hue] Bedroom: set homekit transition control to ""

**Additional context**

**Comment by mkellsy** [comment]
I think you need to upgrade to Node 14 to continue using this plugin.

This command will upgrade Node to LTS
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```

**Comment by theactiv** [comment]
> I think you need to upgrade to Node 14 to continue using this plugin.
> 
> This command will upgrade Node to LTS
> 
> ```
> wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
> ```
That installed some stuff, restarted hoobs in de ssh session and it worked in that session. Of course I wanted to start the service again afterwards, but the service won't start anymore.

**Comment by mkellsy** [comment]
It's in beta. We are testing the many plugins out there.

**Comment by theactiv** [comment]
Awesome, thanks for the help.
