### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by paulxw** [hoobs-org/HOOBS#930]
**could you pls help me? Maybe in German 🥺
Downwards you see my log messages**
A clear and concise description of what the plugin is doing.

**Expected behavoir**
Please let us know what the plugin is supposed to do.

**HOOBS plugin for Philips Hue and deCONZ**
Please let us know what the plugin name is. We need to be able to find it on NPM.

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**3.2.10**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**Raspberry Pi 3 B+**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "REMOVED",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "REMOVED"
    },
    "bridge": {
        "name": "HOOBS",
        "port": REMOVED,
        "pin": "REMOVED",
        "username": "REMOVED"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-hue"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": false,
            "groups": true,
            "lights": true,
            "linkButton": false,
            "lowBattery": 25,
            "rooms": false,
            "scenes": false,
            "scenesAsSwitch": false,
            "schedules": true,
            "sensors": true,
            "wallSwitch": true
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
27.11.2020, 21:48:39 Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js:100:30)
    at HAPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:201:31)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:575:27)
    at Server.publishBridge (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:193:21)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:162:53
    at async Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:162:9)
27.11.2020, 21:48:39 Got SIGTERM, shutting down Bridge...
```

**Additional context**

**Comment by askovi** [comment]
Just reboot from the top right menu

**Comment by paulxw** [comment]
> Just reboot from the top right menu

I can not. 
<img width="183" alt="Bildschirmfoto 2020-11-28 um 16 48 08" src="https://user-images.githubusercontent.com/75143207/100519634-840af500-3199-11eb-8ec6-0e07bb924ab7.png">
