### ISSUE TITLE
Help with hoobs (completely new at this)

### ISSUE THREAD

**Issue by MIKIS23** [hoobs-org/HOOBS#931]
My hoobs.local is unable to load on any device in my home,  I have the HOOBS box and setup went fine but in the middle of installing them BLINK security camera plugin i attempted to reload it and now i am unable to load the local page.  All of the lights on the HOOBs still seem to be functioning.

**Comment by askovi** [comment]
Check your router’s admin page and find the local ip assigned to HOOBS and connect to it like this: http://192.168.x.x
