### ISSUE TITLE
I just got hoobs today and i think i broke it. 

### ISSUE THREAD

**Issue by YoDaddy612** [hoobs-org/HOOBS#932]
I tired to download the ring plugin and now it will not work at all. I keep getting 

Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

I have no clue what im doing.

**Comment by aydinbolkar** [comment]
Same here, I never thought that HOOBS was going to be so buggy. Very disappointed...

**Comment by mkellsy** [comment]
There might be an issue with this install. You should be able to run this command to get it fixed
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```

**Comment by aydinbolkar** [comment]
Thanks for the quick reply. I appreciate.

I am a newbie to HOOBS, I bought the box, didn't install it myself. I was hoping to get my feet in the water without needing to do terminal window command inputs etc, as I've watched on Youtube. 

I believe that will not be possible,

**Comment by askovi** [comment]
Normally no terminal use is required however if a software issue happens, then Here are the instructions to login via ssh:

On MacOS use the Terminal app and type: ` ssh hoobs@hoobs.local`

Type yes to accept the certificate key then press enter. When prompted for password, type `hoobsadmin`

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, paste this command to reinstall HOOBS and upgrade node: `wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts && sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`

**Comment by mjudson64** [comment]
I followed the link and my terminal said the following when I opened it up:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.

When I typed in ssh hoobs@hoobs.local <mailto:hoobs@hoobs.local>

But I didn’t get anything that I could answer yes to.  It just said "kex_exchange_identification: read: Connection reset by peer”

Then I thought I need to update the account to zsh, so I typed in chi -s /bin/zsh; it asked for a password, but wouldn’t let me type in anything.

I’m at a loss.

**Comment by greekjgg** [comment]
I was getting the same error, followed the directions above and i'm getting this error now. 

hoobs@hoobs:~ $ wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts && sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node

Thank You for choosing HOOBS
============================================================================================================
Node Version 14.15.1
Updating Repositories
0% [Working]
Hit:1 http://archive.raspberrypi.org/debian buster InRelease                       
Hit:2 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster InRelease           
Reading package lists... Done                                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u1).
git is already the newest version (1:2.20.1-2+deb10u3).
tar is already the newest version (1.30+dfsg-6).
0 upgraded, 0 newly installed, 0 to remove and 53 not upgraded.
setsebool:  SELinux is disabled.
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> @hoobs/hoobs@3.3.2 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

(node:1206) UnhandledPromiseRejectionWarning: TypeError: File.realpathSync is not a function
    at /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:208:39
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:230:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1206) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1206) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ @hoobs/hoobs@3.3.2
updated 1 package in 185.017s
removed 214 packages in 9.709s
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> bufferutil@4.0.3 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil
> node-gyp-build


> node-pty@0.9.0 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
> node scripts/install.js

make: Entering directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: *** [pty.target.mk:109: Release/obj.target/pty/src/unix/pty.o] Bus error
make: Leaving directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.72-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN rollback Rolling back @hoobs/hoobs@3.3.2 failed (this is probably harmless): EROFS: read-only file system, rmdir '/usr/local/lib/node_modules/@hoobs/hoobs'
npm WARN rollback Rolling back nan@2.14.2 failed (this is probably harmless): EROFS: read-only file system, rmdir '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/nan'
npm WARN rollback Rolling back node-pty@0.9.0 failed (this is probably harmless): EROFS: read-only file system, rmdir '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.9.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
-bash: /usr/bin/sudo: Input/output error

**Comment by EddieDSuza** [comment]
SSH into your HOOBS device and run the below 2 commands

```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
sudo reboot
```

**Comment by mjudson64** [comment]
What does SSH into your HOOBS device mean?

**Comment by mkellsy** [comment]
This is a closed issue. Please open a new one.
