### ISSUE TITLE
No network connectivity - Hoobs in a box

### ISSUE THREAD

**Issue by cdstickney77** [hoobs-org/HOOBS#936]
Hoobs has been working fine for months until today.  I noticed my smart devices were not available and tried to log into Hoobs local and nothing.  I checked the Hoobs pi and it’s powered on just has no connectivity via Ethernet.  I unplugged the  Ethernet and tried to connect wirelessly and it’s not broadcasting either.  Any ideas?

**Comment by mkellsy** [comment]
Was there a power outage? Can you access the box via IP address?
If not you can open the case and plug a monitor into the HDMI port and see if there is a Linux kernel panic.

You may need to re-flash the SD Card and reconfigure. If you made a backup, this is the best option.

**Comment by unchainedlion** [comment]
@mkellsy I have the exact issue you described! I will try reflashingg once I figure out how

Thank you very much!

**Comment by mkellsy** [comment]
To re-flash
1. Download the BalinaEtcher https://www.balena.io/etcher/
2. Download HOOBS 3.3.1 https://github.com/hoobs-org/HOOBS/releases
3. You will also need a micro SD card reader
4. Backup HOOBS before re-flashing
5. Take the SD card out of the Pi and put it into the card reader
6. Use BalinaEtcher to flash HOOBS 3.3.1 to the SD card
7. Put back into the Pi and turn on
8. Restore the backup

**Comment by unchainedlion** [comment]
@mkellsy Thank you very much. HOOBS is running back normal after reflashing.
