### ISSUE TITLE
Firmware update interrupted

### ISSUE THREAD

**Issue by tai86hk** [hoobs-org/HOOBS#939]
I was updating hoobs out of box firmware to the latest one, and unfortunately my house power went out.. and now my hoobs is not working at all. please help!!!
<img width="718" alt="Screen Shot 2020-11-30 at 9 43 24 PM" src="https://user-images.githubusercontent.com/75288400/100690707-202d2b80-3355-11eb-9c76-5ee724a2465b.png">

**Comment by askovi** [comment]
Try reinstalling HOOBS via ssh with these commands:
`sudo npm uninstall -g @hoobs/hoobs`
`sudo npm install -g --unsafe-perm @hoobs/hoobs`

**Comment by tai86hk** [comment]
Thanks for the reply, and now i got the following error messages.



Really appreciate it

**Comment by tai86hk** [comment]
Thanks for the reply, and now i got the following error messages.

Really appreciate it

<img width="1089" alt="Screen Shot 2020-11-30 at 10 03 07 PM" src="https://user-images.githubusercontent.com/75288400/100692125-2bce2180-3358-11eb-9ba1-966ff80f15ca.png">

**Comment by mkellsy** [comment]
This got screwed up pretty bad, but it can be fixed.
First manually remove the wired files
```
sudo rm -fR /usr/local/lib/node_modules/@hoobs
```
Then run this
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```
This will reinstall HOOBS.

**Comment by tai86hk** [comment]
It works!!! many many thanks!!!!!!

**Comment by askovi** [comment]
Awesome!
