### ISSUE TITLE
Cant access the Hoobs login page from network outside hoobs subnet. 

### ISSUE THREAD

**Issue by angelflames1337** [hoobs-org/HOOBS#94]
my hoobs is on 192.168.1.80 and I can access it anywhere from 192.168.1.0/24. But when I VPN from my office, or port forward it, the login page doesnt seem to load.

**Comment by mkellsy** [comment]
We have a document about remote access. There is an API and a web socket the interface needs to access.

https://github.com/hoobs-org/HOOBS/wiki/2.7-Remote-Access
