### ISSUE TITLE
After upgrading there is no new node version

### ISSUE THREAD

**Issue by MasterofKungfu9999** [hoobs-org/HOOBS#940]
**Description**
After upragding to Version 3.3.1 the node version is 12.13.1 
Chancelog says Node LTS (14.15.1)

**Version**
3.3.1 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
The change log is for both the code and the SD Card image. The SD Card image has been upgraded to node 14.
To get an existing device upgraded to node 14, this command needs to be ran
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```

**Comment by MasterofKungfu9999** [comment]
Ok and if i run the comand i'm getting the error pur of issue #914?

**Comment by askovi** [comment]
Run it like this: `wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts && sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`

**Comment by MrWGT** [comment]
Tried "wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts && sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node" but my node stays on 12.16.1. What can i do?
