### ISSUE TITLE
issues with homekit supporting my leviton device

### ISSUE THREAD

**Issue by dougfields** [hoobs-org/HOOBS#941]
Hi, Hopefully you can help. 
I am having issues with homekit supporting my leviton device DW4SF (Fan controller) . The system boots, but homekit does not show additional devices to be added. Additionally, it looks like that there may may be issues with the plugin. Also, works fine with Alexa.
Here is my debug
Many thanks!
Doug Fields

 
Hoobs 3.2.10
Model:  (from myleviton)
Model
DW4SF
Serial Number
1000_0017_363E
IP Address
192.168.0.98
Firmware Version
1.5.46; CP 1.19
 
 

Config  from hoobs
{
            "platform": "LevitonDecoraSmart",
            "plugin_map": {
                "plugin_name": "homebridge-leviton"
            },
            "email": "dummy@gmail.com",
            "password": "Secret"
        }
 

Logging: Home bridge plugin for switch doesn’t seem to be starting

11/28/2020, 4:23:53 AM [TuyaAccessory] Color format for Doug2 (3.1) identified as HEXHSB (length: 14).

11/28/2020, 4:23:55 AM (node:23981) UnhandledPromiseRejectionWarning: TypeError: devices.forEach is not a function

11/28/2020, 4:23:55 AM at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-leviton/index.js:27:15)

11/28/2020, 4:23:55 AM at processTicksAndRejections (internal/process/task_queues.js:97:5)

11/28/2020, 4:23:55 AM (node:23981) UnhandledPromiseRejectionWarning

**Comment by mkellsy** [comment]
This looks like an issue with the TuyaAccessory plugin. You may be missing something in the config.
Also I would report this to the plugin dev, because a simple fix for this would be to change `devices.forEach` to `(devices ||[]).forEach` in the code.

**Comment by dougfields** [comment]
Thanks for the response,   I pulled the Tuya plugin and still have the same problem with Leviton plugin. It looks like there is an issue with the Leviton api

**Comment by dougfields** [comment]
Which log files should I look at to debug the Leviton plugin? It looks like its logging in to my.Leviton.com, but dies afterwards.  Since Leviton has a zillion Alexi components, it makes sense to get this plugin up and running.. and better documented

**Comment by askovi** [comment]
You can post your full log file from settings -> backup -> log
