### ISSUE TITLE
Plugins page empty, in Homemanager app plugins can be installed and are working

### ISSUE THREAD

**Issue by boesermichl** [hoobs-org/HOOBS#943]
**Description**
When opening Plugins page in webbrowser (cache already emptied..) there is only "Installed plugins" in Headline but screen is empty.
Can't do anything in this page.

By using Homemanager app on IPhone, i can install anything i need. But not on Web-Frontend...

**Version**
3.2.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Homepilot
Fritzbox

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by boesermichl** [comment]
![image](https://user-images.githubusercontent.com/75419073/100987367-bb3d2580-354e-11eb-8616-766275cac44a.png)

**Comment by askovi** [comment]
Please right click on the page and click Inspect then click on the Console tab at the top and take a screenshot of the errors and post it here.

**Comment by boesermichl** [comment]
A reset of the user did it...
Deleted the access.json and that's it...
Strange thing...
Thanks for help..

**Comment by mkellsy** [comment]
This is known. From time to time (rare) NPM will return an empty result. We keep a cache of your installed plugins that prevents over access of the NPM API. If that result is empty, an empty response is cached. When you removed the access.json file and rebooted, that cleared this cache, and then it fetched a fresh response.

In our next major version, we are moving to our own plugin API that is based on our NPM mirror. This gives us more control especially when things like this happen.
