### ISSUE TITLE
cannot setup hoobs via wifi or ethernet

### ISSUE THREAD

**Issue by dabimaster** [hoobs-org/HOOBS#944]
HI Im just a newbie here, imtrying to setup my hoobs via my own raspberry pi4b however upon connecting via ethernet or wifi, the opening of hoobs wont come out at all, can somebody help me with this already check my routers(tplink deco m5) unfortunately no success hope you can help me

![image](https://user-images.githubusercontent.com/75493111/101187744-b8961980-368f-11eb-9d07-cbf6e5d920fb.png)

![image](https://user-images.githubusercontent.com/75493111/101188092-335f3480-3690-11eb-88c8-68acc2c57d37.png)

**Comment by jlg89** [comment]
Have you tried:
https://github.com/hoobs-org/HOOBS/issues/914#issuecomment-731225356
