### ISSUE TITLE
Hue Plug-in V0.12.6 crashes 

### ISSUE THREAD

**Issue by dibimuc** [hoobs-org/HOOBS#945]
I am running the latest version of Hoobs and updated to the latest Hue plugin 12.6. Service does not start. Removing the plug-in help, so it might be a problem with the plug-in. Developer recommends to talk to Hoobs support

https://github.com/ebaauw/homebridge-hue/issues/694

**Comment by TheBassfly** [comment]
Same issue for me.
The Plugin crashes HOOBS with the following messages:
onSocketError:  Error: read ECONNRESET
5.12.2020, 12:00:05 at TLSWrap.onStreamRead (internal/stream_base_commons.js:208:20) {
5.12.2020, 12:00:05 errno: 'ECONNRESET',
5.12.2020, 12:00:05 code: 'ECONNRESET',
5.12.2020, 12:00:05 syscall: 'read'
5.12.2020, 12:00:05 }

**Comment by mkellsy** [comment]
What version of Node are you on? Hue requires node 14.15.1

**Comment by dibimuc** [comment]
Since they released an update (0.12.8), it works. But to be honest, not very reliable. I face the following issues sporadically.

[Hue] Philips hue: bridge communication error: http status 503 Service Temporarily Unavailable

[Hue] Philips hue: bridge request 13341: error 201 parameter, bri, is not modifiable. Device is set to off.

Also, the hue bridge appears in the Home App. This is not critical but it shows me that with the small and little update to 0.12.6 a lot of things happened and the update has not been tested at all. 

<img width="171" alt="Bildschirmfoto 2020-12-20 um 14 19 40" src="https://user-images.githubusercontent.com/61652682/102714381-70513b00-42ce-11eb-8824-942b6d7b32d5.png">

**Comment by mkellsy** [comment]
The 503 error is coming from your Hub bridge. This leads me to network issues or your Hub bridge is crashing.
Reboot your router. Reboot your Hue bridge. Also check for updates on your Hue bridge.

If this fails, you might need to involve the developer. He doesn't realize that HOOBS runs Homebridge 1.1.6, so you will need to tell him that you are having issues running his plugin on Homebridge 1.1.6, don't mention HOOBS. He might help you.

In the meantime, I will be testing this plugin further in the next couple of weeks.
