### ISSUE TITLE
Honeywell Home plugin w/ Hoobs

### ISSUE THREAD

**Issue by matthewcouto** [hoobs-org/HOOBS#951]
My Honeywell T5 is HomeKit native but absolutely horrible at keeping a connection with HomeKit. I was hoping to install the Homewell Home plugin but I get an error that states:

The plugin "homebridge-honeywell-home-thermostat" requires a Homebridge version of >=1.2.2 which does not satisfy the current Homebridge version of 1.1.6. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

Is there a technical reason why Hoobs is running an older version of Homebridge?

**Comment by askovi** [comment]
1.1.6 is the latest stable version of homebridge as you can see in the notes of this release here: https://github.com/homebridge/homebridge/releases/tag/v1.2.4
This will not be upgraded until the latest stable version changes. I recommend asking the plugin developer to remove that constraint.
