### ISSUE TITLE
Initial Set Up Log In

### ISSUE THREAD

**Issue by grantsplace** [hoobs-org/HOOBS#956]
**Description**
I just got the HOOBS device and did the ethernet set up.  I went to hoops.local and it asks for a username and password.  I used my hoobs.org log on info and it states invalid username and/or password.  On this page there is no password reset or link to correct an issue.  Looking for information on how to reset from start to start over or recover the username and password this admin start up page is looking for.

**Version**
New right out of the box

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by askovi** [comment]
The username and password is created during first time setup. This is a local account running only on your device and is not connected the your hoobs.org account. If you forgot your username and password, you can reset your account.

Here are the instructions to reset your password:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this to reset the users file:  sudo rm -rf /home/hoobs/.hoobs/etc/access.json

Press enter. There will be no output.

3. Type this to reboot the HOOBS Box: sudo reboot

4. Allow 2-3 minutes for the HOOBS Box to reboot then go to http://hoobs.local and create a new account.

This won't affect your plugins and accessories, only your user.

**Comment by grantsplace** [comment]
I believe I did what you asked for a Mac and it did not work.  Below is my screen shot:

Last login: Mon Dec 14 11:30:15 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Donalds-MacBook-Air:~ donaldgrant$ sshhoobs@hoobs.local
-bash: sshhoobs@hoobs.local: command not found
Donalds-MacBook-Air:~ donaldgrant$ hoobs@hoobs.local
-bash: hoobs@hoobs.local: command not found
Donalds-MacBook-Air:~ donaldgrant$ ssh hoobs@hoobs.local
Yes

Regards,  Don
