### ISSUE TITLE
Hoobs 3.3.1 - Bridge incompatible with iOS 14.1.

### ISSUE THREAD

**Issue by MexxReal** [hoobs-org/HOOBS#959]
After some troubleshooting why my devices (tado and roborock) were no longer displayed as reachable in the HomeApp, I removed the bridge from the HomeApp. I wanted to add it again, but this is not possible because the bridge is incompatible according to iOS (error message).

How do I get the bridge added to the HomeApp again so that my automations work as before?

**Comment by askovi** [comment]
Reset Connection from the Help menu in the top right corner then scan the new QR code on the dashboard.

**Comment by MexxReal** [comment]
How to reset the connection? I restarted the service. I have also changed the name under 'Configuration / Apple Home / Home Username'. After that I scanned the QR code. Unfortunately, this does not work. The error message remains the same.

I also restarted the whole pi. This showed also no effects.. 

![IMG_8369](https://user-images.githubusercontent.com/61295788/102022643-7902b800-3d88-11eb-8a72-b8270ee93fe3.PNG)
![IMG_8370](https://user-images.githubusercontent.com/61295788/102022646-7c963f00-3d88-11eb-9e2e-4b1c864b5f69.PNG)

**Comment by askovi** [comment]
top right menu -> Help -> Reset Connection

**Comment by MexxReal** [comment]
Unfortunately, that doesn't work either. The error message remains the same

**Comment by askovi** [comment]
Try factory reset from the bottom of the Help page. Backup your config first from settings -> backup
