### ISSUE TITLE
homebridge update to 3.0.3 causes reboot loop

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#96]
FB chat user:
Hi!  I can't seem to get the service started after the 3.0.3 upgrade.  The device keeps on re-starting every time I give it a command and it won't let me add any plugins.  Running on a Pi Zero W, hardware might be too slow for that software?  Going back to 2.1.1...

**Comment by mkellsy** [comment]
Is this user installing @hoobs/hoobs or @hoobs/Homebridge? The latter is a component.

**Comment by BobbySlope** [comment]
he tried updating homebridge to 3.0.3 in the v3 ui plugin section

**Comment by mkellsy** [comment]
This is fixed in 3.0.0-beta.29.

The Homebridge in that list is from before this was a component. He needs to run this

```sh
~]$ sudo npm install -g -unsafe-perm @hoobs-org/hoobs
```

This is a repeat of a closed issue.
