### ISSUE TITLE
Hoobs in Box - Does anyone know how to true factory reset?

### ISSUE THREAD

**Issue by MK474** [hoobs-org/HOOBS#960]
Hello Everyone!!

Does anyone know how to erase install the Hoobs-In-Box? Basically my device is in a very messed up state and I can't seem to get it working again. I am able to SSH into it so that's good, however I wanted to know if anyone has the exact commands to basically to do a fresh install as if it out of the box.

 I've tried using this command wget -q -O - http://bit.ly/get-hoobs | sudo bash - and it works however I wanted a way to revert back to original FW since I'm on 3.0+

Any help would be much appreciated!!

**Comment by askovi** [comment]
If you can access the UI, you can factory reset from the bottom of the Help page from the top right menu.
If you want to do it via SSH, you can use this command: wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset
It will keep the latest installed software version but will delete all plugins, configurations, etc. This command reboots the device after the reset so please wait a couple of minutes until it comes back online.
