### ISSUE TITLE
HOOBS-in-box unexpectedly disconnecting due to Error: read ECONNRESET

### ISSUE THREAD

**Issue by MK474** [hoobs-org/HOOBS#961]
**Description**
HOOBS-in-box unexpectedly disconnecting due to below error. 
Occurs within an hour or sometimes it takes a few hours. 

11/29/2020, 11:04:41 PM Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
11/29/2020, 11:04:41 PM Got SIGTERM, shutting down Bridge... 

**Version**
3.3.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
n/a

**List your plugins**
Mylink 1.2.1

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYNK7A",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "",
        "username": ""
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-mylink"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Somfy myLink",
            "ipAddress": "",
            "systemID": "Mk",
            "targets": [
                {
                    "targetID": "CC10E5F2.1",
                    "name": "Master Bedroom Office"
                },
                {
                    "targetID": "CC10E5F2.2",
                    "name": "Master Bedroom Corner"
                },
                {
                    "targetID": "CC10E5F2.4",
                    "name": "Living Room Right"
                },
                {
                    "targetID": "CC10E5F2.5",
                    "name": "Living Room Left"
                }
            ]
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
11/29/2020, 10:21:59 PM - HOOBS listening on port 80.
11/29/2020, 10:22:05 PM - Loaded plugin 'homebridge-mylink'
11/29/2020, 10:22:05 PM - [11/29/2020, 11:22:05 PM] Registering platform 'homebridge-mylink.Somfy myLink'
11/29/2020, 10:22:05 PM - Loading 1 platforms...
11/29/2020, 10:22:05 PM - [Somfy myLink] Initializing Somfy myLink platform...
11/29/2020, 10:22:05 PM - Initializing platform accessory 'Somfy Master Bedroom Office'...
11/29/2020, 10:22:05 PM - Initializing platform accessory 'Somfy Master Bedroom Corner'...
11/29/2020, 10:22:06 PM - Initializing platform accessory 'Somfy Living Room Right'...
11/29/2020, 10:22:06 PM - Initializing platform accessory 'Somfy Living Room Left'...
11/29/2020, 10:22:06 PM - Bridge is running on port 51826.
11/29/2020, 10:22:09 PM - Class extends value #<Object> is not a constructor or null
11/29/2020, 10:22:09 PM - Unable to determine plugin type for "homebridge-mylink"
11/29/2020, 10:22:35 PM - [Somfy myLink] Setting position of target CC10E5F2.1 (Master Bedroom Office) from 0% to 100%.
11/29/2020, 10:22:37 PM - [Somfy myLink] Setting position of target CC10E5F2.2 (Master Bedroom Corner) from 0% to 100%.
11/29/2020, 10:22:37 PM - [Somfy myLink] Setting position of target CC10E5F2.4 (Living Room Right) from 0% to 100%.
11/29/2020, 10:22:37 PM - [Somfy myLink] Setting position of target CC10E5F2.5 (Living Room Left) from 0% to 100%.
11/29/2020, 10:22:38 PM - [Somfy myLink] Setting position of target CC10E5F2.4 (Living Room Right) from 100% to 0%.
11/29/2020, 10:22:38 PM - [Somfy myLink] Setting position of target CC10E5F2.5 (Living Room Left) from 100% to 0%.
11/29/2020, 10:22:39 PM - [Somfy myLink] Setting position of target CC10E5F2.2 (Master Bedroom Corner) from 100% to 0%.
11/29/2020, 10:22:39 PM - [Somfy myLink] Setting position of target CC10E5F2.1 (Master Bedroom Office) from 100% to 0%.
11/29/2020, 10:26:09 PM - [Somfy myLink] Setting position of target CC10E5F2.1 (Master Bedroom Office) from 0% to 0%.
11/29/2020, 10:26:09 PM - [Somfy myLink] Setting position of target CC10E5F2.5 (Living Room Left) from 0% to 0%.
11/29/2020, 10:26:09 PM - [Somfy myLink] Setting position of target CC10E5F2.4 (Living Room Right) from 0% to 0%.
11/29/2020, 10:26:09 PM - [Somfy myLink] Setting position of target CC10E5F2.2 (Master Bedroom Corner) from 0% to 0%.
11/29/2020, 10:27:15 PM - [Somfy myLink] Setting position of target CC10E5F2.1 (Master Bedroom Office) from 0% to 0%.
11/29/2020, 10:27:15 PM - [Somfy myLink] Setting position of target CC10E5F2.5 (Living Room Left) from 0% to 0%.
11/29/2020, 10:27:15 PM - [Somfy myLink] Setting position of target CC10E5F2.4 (Living Room Right) from 0% to 0%.
11/29/2020, 10:27:15 PM - [Somfy myLink] Setting position of target CC10E5F2.2 (Master Bedroom Corner) from 0% to 0%.
11/29/2020, 10:30:00 PM - [Somfy myLink] Setting position of target CC10E5F2.5 (Living Room Left) from 0% to 0%.
11/29/2020, 10:30:00 PM - [Somfy myLink] Setting position of target CC10E5F2.2 (Master Bedroom Corner) from 0% to 0%.
11/29/2020, 10:30:00 PM - [Somfy myLink] Setting position of target CC10E5F2.1 (Master Bedroom Office) from 0% to 0%.
11/29/2020, 10:30:00 PM - [Somfy myLink] Setting position of target CC10E5F2.4 (Living Room Right) from 0% to 0%.
11/29/2020, 10:30:19 PM - [Somfy myLink] Setting position of target CC10E5F2.5 (Living Room Left) from 0% to 0%.
11/29/2020, 10:30:19 PM - [Somfy myLink] Setting position of target CC10E5F2.2 (Master Bedroom Corner) from 0% to 0%.
11/29/2020, 10:30:19 PM - [Somfy myLink] Setting position of target CC10E5F2.1 (Master Bedroom Office) from 0% to 0%.
11/29/2020, 10:30:19 PM - [Somfy myLink] Setting position of target CC10E5F2.4 (Living Room Right) from 0% to 0%.
11/29/2020, 10:30:20 PM - [Somfy myLink] Setting position of target CC10E5F2.5 (Living Room Left) from 0% to 0%.
11/29/2020, 10:30:20 PM - [Somfy myLink] Setting position of target CC10E5F2.2 (Master Bedroom Corner) from 0% to 0%.
11/29/2020, 10:30:20 PM - [Somfy myLink] Setting position of target CC10E5F2.1 (Master Bedroom Office) from 0% to 0%.
11/29/2020, 10:30:20 PM - [Somfy myLink] Setting position of target CC10E5F2.4 (Living Room Right) from 0% to 0%.
11/29/2020, 10:30:47 PM - [Somfy myLink] Setting position of target CC10E5F2.5 (Living Room Left) from 0% to 0%.
11/29/2020, 10:30:47 PM - [Somfy myLink] Setting position of target CC10E5F2.2 (Master Bedroom Corner) from 0% to 0%.
11/29/2020, 10:30:47 PM - [Somfy myLink] Setting position of target CC10E5F2.1 (Master Bedroom Office) from 0% to 0%.
11/29/2020, 10:30:47 PM - [Somfy myLink] Setting position of target CC10E5F2.4 (Living Room Right) from 0% to 0%.
11/29/2020, 10:36:20 PM - [Somfy myLink] Setting position of target CC10E5F2.1 (Master Bedroom Office) from 0% to 0%.
11/29/2020, 10:36:20 PM - [Somfy myLink] Setting position of target CC10E5F2.5 (Living Room Left) from 0% to 0%.
11/29/2020, 10:36:20 PM - [Somfy myLink] Setting position of target CC10E5F2.4 (Living Room Right) from 0% to 0%.
11/29/2020, 10:36:20 PM - [Somfy myLink] Setting position of target CC10E5F2.2 (Master Bedroom Corner) from 0% to 0%.
11/29/2020, 11:04:41 PM - Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
11/29/2020, 11:04:41 PM - Got SIGTERM, shutting down Bridge...

**Additional context**
This error appears to randomly occur anywhere between 1-3 hours.

**Comment by mkellsy** [comment]
It looks like Somfy myLink is crashing the system when it can't access the ipAddress in the config. Do you have something like a stateful packet filter on you router? Is your router rebooting?

**Comment by MK474** [comment]
Hi mkellsy,

Really appreciate the help. If it makes any difference my Hoobs-box is connected directly to ethernet.

Also I don't believe my router is rebooting, and I don't stateful packet filter is enabled on my wireless route. How do I confirm the latter?  

Thanks,
Mike

**Comment by mkellsy** [comment]
Tracking this down is tough. It looks like everything is running fine, then you get the ECONNRESET.

This error is the plugin crashing because it can't connect to the Somfy device. Either the Somfy device is resetting the connection, or the router is resetting the connection. This should be more fault tolerant. It might help reporting this to the plugin dev. The plugin should not crash the bridge if the connection is reset. ECONNRESET is a common thing, often used to clean up a network connection.

Also check the Somfy device. It it in range? Is the firmware updated? Does it need a reboot?
