### ISSUE TITLE
How can I remove a plugin and/or find my config if hoobs is on a restart loop

### ISSUE THREAD

**Issue by costispavlou** [hoobs-org/HOOBS#965]
**Description**
I installed soma plugin. While trying to config hoobs crashed and went on a restart loop that does nothing.

**Expected behavoir**
control curtains

**Plugin name**
https://www.npmjs.com/package/homebridge-soma-shades

**Version**
Latest one.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
cant access config as device is on restart loop.
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
any chance i can remove the plugin and get my config/plugins back? It'll be a nightmare to reconfig everthing.

**Comment by mkellsy** [comment]
Can you access the interface?

**Comment by costispavlou** [comment]
No. If I could, I’d be able to heh.

**Comment by mkellsy** [comment]
Something else is going on. You will need to ssh into the device.
The config file is in `~/.hoobs/etc`

**Comment by costispavlou** [comment]
I cannot ssh, it's on a restart loop.

**Comment by costispavlou** [comment]
i rebuilt hoobs and tried the plugin again (soma connect) it basically allows bluetooth connection  / service. 
that bricks the os completely.
