### ISSUE TITLE
Issues uninstalling the Hue Plugin after importing settings and config file 

### ISSUE THREAD

**Issue by dorminyk** [hoobs-org/HOOBS#966]
**Description**
Hue Plugin is not working after importing settings and configuration backup. Attempted to remove Hue Plugin and it is giving me an uninstall error.

**Plugin name**
HOOBS plugin for Philips Hue and deCONZ

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
HOOBS Core
Current Version: 3.3.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi on an Arm7

**Post your config**
* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYJPC8",
        "origin": "*",
        "port": 80,
        "polling_seconds": 5
    },
    "client": {
        "temp_units": "fahrenheit",
        "theme": "hoobs-dark",
        "country_code": "US",
        "postal_code": "55056",
        "default_route": "status",
        "inactive_logoff": 30,
        "locale": "en"
    },
    "bridge": {
        "name": "HOOBS",
        "pin": "031-45-154",
        "port": 51826,
        "username": "A5:B8:FD:9D:E4:AB"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "email": "boanes@gmail.com",
            "password": xxxxxxxxxxxxx,
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq"
            },
            "name": "myQ"
        },
        {
            "resetSimpliSafeId": false,
            "subscriptionId": "0006FCB7",
            "auth": {
                "username": "boanes@gmail.com",
                "password": "xxxxxxxxxxxxxxxxxxxx"
            },
            "sensorRefresh": 5,
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "cameraOptions": {
                "enableHwaccelRpi": true
            },
            "persistAccessories": true,
            "plugin_map": {
                "plugin_name": "homebridge-simplisafe3"
            },
            "cameras": true,
            "name": "Home Alarm"
        },
        {
            "sendCameraMotionNotificationsToTv": false,
            "hideUnsupportedServices": true,
            "hideInHomeDoorbellSwitch": true,
            "platform": "Ring",
            "hideLightGroups": true,
            "sendDoorbellMotionNotificationsToTv": false,
            "hideCameraSirenSwitch": true,
            "hideDoorbellSwitch": true,
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "x",
            "alarmOnEntryDelay": false,
            "showPanicButtons": false,
            "avoidSnapshotBatteryDrain": false,
            "hideAlarmSirenSwitch": true,
            "hideCameraMotionSensor": false
        },
        {
            "resource": true,
            "rooms": true,
            "platform": "Hue",
            "nativeHomeKitSensors": true,
            "linkButton": false,
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "lights": true,
            "effects": true,
            "nativeHomeKitLights": true,
            "anyOn": true,
            "nupnp": true,
            "users": {
                "001788FFFEA21310": "x"
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
12/15/2020, 10:36:45 AM HOOBS listening on port 80.
12/15/2020, 10:36:50 AM Loaded plugin 'homebridge-hue'
12/15/2020, 10:36:51 AM [12/15/2020, 10:36:50 AM] Registering platform 'homebridge-hue.Hue'
12/15/2020, 10:36:51 AM Loaded plugin 'homebridge-myq'
12/15/2020, 10:36:51 AM [12/15/2020, 10:36:51 AM] Registering platform 'homebridge-myq.myQ'
12/15/2020, 10:36:52 AM Loaded plugin 'homebridge-ring'
12/15/2020, 10:36:52 AM [12/15/2020, 10:36:52 AM] Registering platform 'homebridge-ring.Ring'
12/15/2020, 10:36:53 AM Loaded plugin 'homebridge-simplisafe3'
12/15/2020, 10:36:53 AM [12/15/2020, 10:36:53 AM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
12/15/2020, 10:36:53 AM Loading 4 platforms...
12/15/2020, 10:36:53 AM [myQ] Initializing myQ platform...
12/15/2020, 10:36:53 AM [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
12/15/2020, 10:36:53 AM [Ring] Initializing Ring platform...
12/15/2020, 10:36:53 AM [Hue] Initializing Hue platform...
12/15/2020, 10:36:53 AM [Hue] config.json: warning: plugin_map: ignoring unknown key
12/15/2020, 10:36:53 AM [Hue] homebridge-hue v0.12.11, node v14.15.1, homebridge v1.1.6
12/15/2020, 10:36:53 AM [Ring] Configuring cached accessory 705a216c-658f-41f4-bab2-09aae2dc20b1 Owyn’s Room
12/15/2020, 10:36:53 AM [Hue] searching bridges and gateways
12/15/2020, 10:36:54 AM [myQ] myQ API: Successfully connected to the myQ API.
12/15/2020, 10:36:54 AM [myQ] myQ API: Discovered device family gateway: 2-Door Garage Door [Chamberlain WiFi GDO AC] (serial number: GW0A00021564).
12/15/2020, 10:36:54 AM [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CG08500FB322, gateway: GW0A00021564).
12/15/2020, 10:36:55 AM [Ring] Configuring 1 cameras and 1 devices for location "North Branch" - locationId: b192be3e-e72e-433a-81aa-94fd81def190
12/15/2020, 10:36:58 AM [Hue] Home: Signify Netherlands B.V. BSB002 bridge v1941132080, api v1.41.0
12/15/2020, 10:36:59 AM [Hue] Home: 4 accessories
12/15/2020, 10:36:59 AM [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
12/15/2020, 10:36:59 AM Initializing platform accessory 'Home'...
12/15/2020, 10:36:59 AM [Hue] Home: 2 services
12/15/2020, 10:36:59 AM Initializing platform accessory 'Hallway Light'...
12/15/2020, 10:36:59 AM Initializing platform accessory 'Office Light 1'...
12/15/2020, 10:36:59 AM Initializing platform accessory 'Office Light 2'...
12/15/2020, 10:36:59 AM Bridge is running on port 51826.
12/15/2020, 10:37:19 AM [Hue] heartbeat 5, drift 13972
12/15/2020, 10:37:19 AM [Hue] heartbeat 6, drift 12973
12/15/2020, 10:37:19 AM [Hue] heartbeat 7, drift 11975
12/15/2020, 10:37:19 AM [Hue] heartbeat 8, drift 10976
12/15/2020, 10:37:19 AM [Hue] heartbeat 9, drift 9978
12/15/2020, 10:37:19 AM [Hue] heartbeat 10, drift 8979
12/15/2020, 10:37:19 AM [Hue] heartbeat 11, drift 7983
12/15/2020, 10:37:19 AM [Hue] heartbeat 12, drift 6984
12/15/2020, 10:37:19 AM [Hue] heartbeat 13, drift 5985
12/15/2020, 10:37:19 AM [Hue] heartbeat 14, drift 4986
12/15/2020, 10:37:19 AM [Hue] heartbeat 15, drift 3987
12/15/2020, 10:37:19 AM [Hue] heartbeat 16, drift 2990
12/15/2020, 10:37:19 AM [Hue] heartbeat 17, drift 1991
12/15/2020, 10:37:19 AM [Hue] heartbeat 18, drift 993
12/15/2020, 12:58:10 PM [Hue] Hallway Light: set homekit status fault from 0 to 1
12/15/2020, 12:59:10 PM [Hue] Office Light 2: set homekit status fault from 0 to 1
12/15/2020, 1:00:05 PM [Hue] Office Light 1: set homekit status fault from 0 to 1
12/15/2020, 1:00:20 PM [Hue] Hallway Light: set homekit status fault from 1 to 0
12/15/2020, 1:00:50 PM [Hue] Office Light 2: set homekit status fault from 1 to 0
12/15/2020, 1:01:01 PM [myQ] request to https://api.myqdevice.com/api/v5.1/Accounts/cb0525df-fd52-49fe-82c4-9da71ef59b48/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
12/15/2020, 1:01:01 PM [myQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
12/15/2020, 1:01:30 PM [Hue] Office Light 1: set homekit status fault from 1 to 0
12/15/2020, 1:02:45 PM [Hue] Hallway Light: set homekit status fault from 0 to 1
12/15/2020, 1:03:25 PM [Hue] Hallway Light: set homekit status fault from 1 to 0
12/15/2020, 1:28:05 PM [Hue] Office Light 1: set homekit on from 0 to 1
12/15/2020, 1:28:05 PM [Hue] Office Light 2: set homekit on from 0 to 1
12/15/2020, 1:28:10 PM [Hue] Office Light 1: set homekit brightness from 50% to 100%
12/15/2020, 1:28:10 PM [Hue] Office Light 2: set homekit brightness from 50% to 100%
12/15/2020, 1:29:15 PM [Hue] Office Light 1: set homekit on from 1 to 0
12/15/2020, 1:29:15 PM [Hue] Office Light 1: set homekit brightness from 100% to 50%
12/15/2020, 1:30:25 PM [Hue] Office Light 2: set homekit brightness from 100% to 50%
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:33:37 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 1:43:15 PM [Hue] Office Light 1: set homekit brightness from 50% to 100%
12/15/2020, 1:43:15 PM [Hue] Office Light 2: set homekit on from 1 to 0
12/15/2020, 1:43:15 PM [Hue] Office Light 2: set homekit brightness from 50% to 100%
12/15/2020, 1:59:06 PM [myQ] myQ API: Connection has been reset.
12/15/2020, 1:59:06 PM [myQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
12/15/2020, 2:07:59 PM [Hue] heartbeat 12659, drift 293
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:29:33 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:30:10 PM [Hue] Office Light 2: set homekit status fault from 0 to 1
12/15/2020, 2:31:05 PM [Hue] Office Light 2: set homekit status fault from 1 to 0
12/15/2020, 2:34:19 PM [Hue] heartbeat 14239, drift 322
12/15/2020, 2:39:35 PM npm
12/15/2020, 2:39:35 PM 
12/15/2020, 2:39:35 PM ERR!
12/15/2020, 2:39:35 PM 
12/15/2020, 2:39:35 PM code
12/15/2020, 2:39:35 PM  EEXIST
12/15/2020, 2:39:35 PM npm
12/15/2020, 2:39:35 PM  ERR! path /home/hoobs/.hoobs/node_modules/homebridge-lib/node_modules/.bin/semver
12/15/2020, 2:39:35 PM npm ERR!
12/15/2020, 2:39:35 PM  Refusing to delete /home/hoobs/.hoobs/node_modules/homebridge-lib/node_modules/.bin/semver: is outside /home/hoobs/.hoobs/node_modules/homebridge-lib/node_modules/semver and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/homebridge-lib/node_modules/.bin/semver
npm ERR! Remove the existing file and try again, or run npm
npm
12/15/2020, 2:39:35 PM ERR!
12/15/2020, 2:39:35 PM  with --force to overwrite files recklessly.
12/15/2020, 2:39:36 PM 
12/15/2020, 2:39:36 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-12-15T20_39_35_963Z-debug.log
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
12/15/2020, 2:58:38 PM [Home Alarm] Sensor refresh received un-expected SSAPI error.
```

**Additional context**

**Comment by mkellsy** [comment]
It looks like npm locked some files on a previous install.
These commands should get you fixed up.
```
cd ~/.hoobs
rm -fR node_modules
npm install
```

**Comment by dorminyk** [comment]
Looks like that fixed it, thanks!

**Comment by resgroupmsr** [comment]
> It looks like npm locked some files on a previous install.
> These commands should get you fixed up.
> 
> ```
> cd ~/.hoobs
> sudo rm -fR node_modules
> npm install
> ```

I've submitted a couple of bugs today but also had same problem when trying to fix FFMPEG - would not allow me to uninstall the plug in.  I don't want or need to uninstall FFMPEG I just need to get it working today.  Is it possible that the commands you show might work for me as well?

**Comment by mkellsy** [comment]
@resgroupmsr maybe. Are you installing FFMPEG from the interface?

**Comment by resgroupmsr** [comment]
> @resgroupmsr maybe. Are you installing FFMPEG from the interface?

If you mean in HOOBS and plugin section then yes.  I had not changed anything on FFMPEG it just stopped working today at around 11:30.  I have my working config backed up so thought I'd just remove the plugin and try again but wouldn't let me uninstall.  Nothing I do gets the cameras back to working state.  An error occurred while making snapshot request: Error: spawn /home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg EACCES errors on snapshot creation and streaming.

**Comment by mkellsy** [comment]
Did the ffmpeg-for-homebridge plugin update? You might need to upgrade node to version 14.15.2.

**Comment by resgroupmsr** [comment]
> Did the ffmpeg-for-homebridge plugin update? You might need to upgrade node to version 14.15.2.
> Please open a new issue, as this is not the same problem.

How would I update the Node?  No the plugin did not update as far as I know.

**Comment by resgroupmsr** [comment]
I tried this command from terminal in HOOBS.  Same kind of EACCES

Any ideas?

hoobs@hoobs:/home/hoobs/.hoobs/etc $ npm install -g npm
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/cliui/node_modules/ansi-regex
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/cliui/node_modules/strip-ansi
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/co
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/dot-prop
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/fast-deep-equal
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/get-caller-file
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/graceful-fs
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/configstore
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/invert-kv
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/json-schema-traverse
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/ajv
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/lcid
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/mem/node_modules/mimic-fn
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/mkdirp
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/gentle-fs
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/bin-links
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/nice-try
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/nopt
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/safe-buffer
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/os-locale/node_modules/cross-spawn
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/os-locale/node_modules/execa
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/p-defer
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/map-age-cleaner
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/p-is-promise
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/mem
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/os-locale
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/p-try
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/p-limit
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/p-locate
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/locate-path
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/find-up
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/rc/node_modules/minimist
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/require-main-filename
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/spdx-license-ids
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/har-validator
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/wrap-ansi/node_modules/string-width
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/wrap-ansi
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/cliui
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/yargs-parser
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/yargs/node_modules/y18n
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/yargs
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/libcipm
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/libnpx
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/meant
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/npm-audit-report
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/npm-user-validate
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/cliui/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/mem/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/os-locale/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/rc/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/wrap-ansi/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/yargs/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/npm/node_modules/cliui/node_modules/ansi-regex
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/cliui/node_modules/ansi-regex'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/cliui/node_modules/ansi-regex'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/cliui/node_modules/ansi-regex'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/npm/node_modules/cliui/node_modules/ansi-regex'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-12-16T20_20_40_060Z-debug.log
hoobs@hoobs:/home/hoobs/.hoobs/etc $

**Comment by mkellsy** [comment]
You can't install global Node modules from a non elevated terminal. That's why you are getting an EACCES error.

You install npm, the command should be this.
```
sudo npm install -g npm
```

HOOBS does not use global plugins. You should install plugins via the UI regardless of that the plugin dev tells you.

**Comment by resgroupmsr** [comment]
> You can't install global Node modules from a non elevated terminal. That's why you are getting an EACCES error.
> 
> To install the npm module globally, the command should be this.
> 
> ```
> sudo npm install -g npm
> ```
> 
> HOOBS does not use global plugins. You should install plugins via the UI regardless of that the plugin dev tells you.

I only have certified plugins installed and only installed via the HOOBS UI.  I'm running that command now from terminal.

**Comment by resgroupmsr** [comment]
> > You can't install global Node modules from a non elevated terminal. That's why you are getting an EACCES error.
> > To install the npm module globally, the command should be this.
> > ```
> > sudo npm install -g npm
> > ```
> > 
> > 
> > HOOBS does not use global plugins. You should install plugins via the UI regardless of that the plugin dev tells you.
> 
> I only have certified plugins installed and only installed via the HOOBS UI. I'm running that command now from terminal.

Same errors.  I have to stop working on this now and do my real job.  Will this work better from direct connection to the Pi?

**Comment by dorminyk** [comment]
I'm opening this up again because now after restoring configuration settings, it's not allowing me to update plugins.

Without removing all of the plugins, is there a way that I can resolve this?

Here's an error from the log file..

**_1/2/2021, 3:50:50 PM ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/homebridge-ring/node_modules/.bin/uuid: is outside /home/hoobs/.hoobs/node_modules/homebridge-ring/node_modules/uuid and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/homebridge-ring/node_modules/.bin/uuid
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
1/2/2021, 3:50:50 PM 
1/2/2021, 3:50:50 PM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-01-02T21_50_50_717Z-debug.log_**

**Comment by mkellsy** [comment]
NPM root locked this file
```
/home/hoobs/.hoobs/node_modules/homebridge-ring/node_modules/.bin/uuid
```
so run
```
sudo rm -f /home/hoobs/.hoobs/node_modules/homebridge-ring/node_modules/.bin/uuid
```

This is being taken care of in our next major release.
