### ISSUE TITLE
Cannot Login to plugin page

### ISSUE THREAD

**Issue by saiajin** [hoobs-org/HOOBS#967]
HI when I try to Login to the plugins page with my Hoobs account it says invalid.. I even tried changing my password..
Thanks!

**Comment by mkellsy** [comment]
Not sure what you mean here? Are you talking about https://plugins.hoobs.org, or the Plugin screen in the software?

**Comment by saiajin** [comment]
The Webpage... trying to review a plugin and can not log in the review.

Thanks!

**Comment by mkellsy** [comment]
When trying to login click Forgot Password. Then check your email for the reset link. Be sure to check your spam folder too.

You actually don't need to login to view or search plugins on the plugin site, it is a public site. If you need something changed on the plugin page, this is an admin task. You will need to ask us to change it. We will if you verify that you are the owner of the plugin. If you need to change the Readme, you will need to commit the changes to your repo, and publish a new version to NPM. Our plugin site is simply a mirror of NPM with some things added.

If it is the plugin page of the HOOBS device, you need to ssh into the device and run this command
```
rm -f ~/.hoobs/etc/access.json
```

Then reboot the device, and you will be asked to setup the admin account.

**Comment by saiajin** [comment]
I’m just trying to review a plugin but can’t login... I even changed my password...

miles@milesreetz.com
773-301-3041

**Comment by mkellsy** [comment]
Just queried our accounts database and there is no account for "miles@milesreetz.com".
You will need to click "Sign In" then click the "Sign Up" button.

The plugin site does not use the same login as the HOOBS device or the sales site. Sorry for the inconvenience but we are working towards merging the three.

**Comment by saiajin** [comment]
Ooooh... so it’s a a separate account than the one I bought my Hoobs on... plugin site is separate account ...got it... yes it’s confusing!

Thank you!

Miles

miles@milesreetz.com
773-301-3041
