### ISSUE TITLE
Document/Info for cross platform transfer of installation available?

### ISSUE THREAD

**Issue by MrWGT** [hoobs-org/HOOBS#971]
I want to move my hoobs installation on a raspi 4b to a more powerful PC based installation.

How to I transfer the pi setup to the new machine in that way that Apple Home doesn't see a change?

Steps I've done so far:

1) setup new machine with Linux with fixed new ip
2) install deconz and hoobs
3) install mosquitto
4) downloaded config/settings from pi to directory on new machine.

How to continue from there on new pc?

- install same Plugins on hoobs
- disconnect new machine from  network
- load config.json from old machine 
- restore deconz setup
- change ip of new machine to old one 
- change apple id of new machine to the id from old machine 
- shutdown Pi
- shutdown PC
- connect PC to network again 
- power up PC 

Are this the correct steps?

Thanks in advance 
Gerd

**Comment by mkellsy** [comment]
Just backup on the Pi "Menu -> System -> Backup" Click the "Backup System" button. Save the file it downloads somewhere safe.

Install HOOBS on a supported OS. https://support.hoobs.org/docs/5e763e30e87d1e02b6c19d33

We support
* .deb - Debian, Ubuntu, Mint, Raspbian
* .rpm - Fedora, RHEL, CentOS
* macOS

Once you can get to the interface, simply restore the backup file.

**Comment by MrWGT** [comment]
Thanks 🙂

Didn't know that backup works for changing ARM64 -> X64. Thought that some Plugins maybe use executables. Therefore Backup might not work. I'll try 😅

**Comment by mkellsy** [comment]
The restore runs a "npm install" on the plugin folder, so it re-downloads the modules anyway.
