### ISSUE TITLE
No boot after update 

### ISSUE THREAD

**Issue by thevoyager3** [hoobs-org/HOOBS#973]
Updated hoobs to its latest version. Now it is stuck either communicating with smartThings or eWelink. 
[logs.txt](https://github.com/hoobs-org/HOOBS/files/5710859/logs.txt)

**Comment by askovi** [comment]
Which ewelink plugin are you using? You should use this one: https://plugins.hoobs.org/plugin/homebridge-ewelink

**Comment by thevoyager3** [comment]
I had the ewelink Max. Deleted and installed the hoops certified one. Got stuck at:
`Note: Replacing /path/to/node with the path you found in the first step.
12/19/2020, 8:48:47 PM [netatmo platform] ERROR - Netatmo: Error: Authenticate error: invalid_grant
12/19/2020, 8:48:48 PM [Thermostat] Existing TCC accessory LivingRoom1
12/19/2020, 8:48:48 PM [Thermostat] Existing TCC accessory LivingRoom2
12/19/2020, 8:48:54 PM [eWeLink] [1] eWeLink devices loaded from the Homebridge cache.
12/19/2020, 8:48:54 PM [eWeLink] [2] primary devices loaded from your eWeLink account.
12/19/2020, 8:48:54 PM [eWeLink]  → [Elektra 2 (devicesa32d97)] was removed from Homebridge.
12/19/2020, 8:48:55 PM [eWeLink]  → [Elektra 1 (devicesa32d1c)] has been added to Homebridge.
12/19/2020, 8:48:55 PM [eWeLink]  → [Elektra 1 (devicesa32d1c)] initialised and found locally with IP [10.0.0.20].
12/19/2020, 8:48:55 PM [eWeLink]  → [Elektra 2 (devicesa32d97)] has been added to Homebridge.
12/19/2020, 8:48:55 PM [eWeLink]  → [Elektra 2 (devicesa32d97)] initialised and found locally with IP [10.0.0.25].
12/19/2020, 8:48:55 PM [eWeLink] eWeLink sync complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!`

Then deleted ewelink and smartthings entirely. Then got stuck here:

`Note: Replacing /path/to/node with the path you found in the first step.
12/19/2020, 8:55:33 PM [Thermostat] Existing TCC accessory LivingRoom1
12/19/2020, 8:55:33 PM [Thermostat] Existing TCC accessory LivingRoom2
12/19/2020, 8:55:33 PM [netatmo platform] ERROR - Netatmo: Error: Authenticate error: invalid_grant`

Maybe once I delete all plug ins it will work :)

**Comment by thevoyager3** [comment]
This was all working with the previous Hoobs version. Is there a way to go back to a prior version? I sure don't feel like re-programming all my HomeKit settings.

**Comment by thevoyager3** [comment]
Deleted all plugins and home bridge started. Re-installed all plugins and it is all back on. Still have to re-do all my automations and shortcuts but I am happy it is running back again.
