### ISSUE TITLE
Uninstalling Orbit Plugin

### ISSUE THREAD

**Issue by forever54321** [hoobs-org/HOOBS#975]
I downloaded Platform Orbit for my B-Hyve Sprinkler system, and I decided to uninstall it from my Hoobs hub, but still showing even after uninstalling it! is there a way clean the Hub from this plugin? Thank you

**Comment by askovi** [comment]
Is the plugin still showing or the accessories from it are still showing?
Please provide your logs after attempting to uninstall it.
