### ISSUE TITLE
Why global packages are installed with sudo?

### ISSUE THREAD

**Issue by Olepir** [hoobs-org/HOOBS#98]
Why global packages are installed with sudo?
Looks like permissions error

**Comment by mkellsy** [comment]
@hoobs/hoobs is a service, it needs to be installed with sudo. Vanilla Homebridge requires sudo npm install -g too, as well as the plugins.

HOOBS installs it's plugins locally so global is not required, just the HOOBS service needs to be global.

**Comment by mkellsy** [comment]
It also symlinks a binary in /usr/local/bin/ or /usr/bin/
