### ISSUE TITLE
New HOOBs, worked and then EI0 error

### ISSUE THREAD

**Issue by Nook25** [hoobs-org/HOOBS#981]
**Description**
I just started using my HOOBS box today, I installed the Ring plug-in and then I couldn't get into Hoobs.local , had an EI0 error. Still listed on my router as connect with an IP address. I tried to login via SSH and this was what showed: 

ssh hoobs@hoobs.local
kex_exchange_identification: read: Connection reset by peer

I checked the box and it's showed blinking lights at the ethernet port. 

**Version**
I'm honestly not sure, it arrived yesterday so I assume the most updated version. I can't log into the web portal to see. 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
macOS Big Sur

**List your plugins**
Nest
Simplisafe 3
Installed Ring (but problem started right after)

**Post your config**
Unable to get into local.hoobs to get the config file 
```

**Comment by Nook25** [comment]
An update. I did open the box up and re-flash, I tried both versions that are listed. For each when I go to hoobs.local it won’t even give me an error message just says unable to connect to server. Also my router is not finding it either. I don’t know if I got a bad box? Any help is appreciated, was excited to set this up.

**Comment by askovi** [comment]
Please email info@hoobs.org with your order number and a link to this post to get a replacement card.
