### ISSUE TITLE
Cannot access hoobs local via instructions, nor IP. (Xfinity, Ethernet, Mac)

### ISSUE THREAD

**Issue by discouragedadopter** [hoobs-org/HOOBS#985]
I need help with the initial setup. The local page "failed to open"

**Comment by askovi** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)
