### ISSUE TITLE
Error: EIO

### ISSUE THREAD

**Issue by Shep084** [hoobs-org/HOOBS#987]
**Description**
I recently purchased a Hoobs box and spend ages setting it up. Its been running well for a few weeks now. I recently tried login into the dashboard and got the follow error.
Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/index.html'

**Version**
I cant login to confirm?

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [X] Yes

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
I cant login to confirm the exact name but below is the list off the top of my head,
- Dummy Switch
- Sony Bravia
- Apple TV
- Sonos ZP

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
I cant login to pull the config files.

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
It appears others are having the same issues.
https://github.com/hoobs-org/HOOBS/issues/984
https://github.com/hoobs-org/HOOBS/issues/981
Its been suggested to flush the SD card, which i have no idea how to do that, however, i am also not interested in starting from scratch and losing all the plugins and automation I have already set up.
Hoobs is still functioning, all accessories are still visible and functioning in HomeKit.
How do you resolve this issue without starting from scratch?

**Comment by mkellsy** [comment]
HTML files are static files, so the IO error is an os thing. This looks like SD card corruption.

You should still be able to access the device from SSH.

You can try reinstall
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

Also you can backup the ~/.hoobs folder to save your setup.

**Comment by Shep084** [comment]
Thanks, I'm not really sure what SSH means. I'm a bit of a novice. I have just restarted the hub again and it appears I can now login to the dashboard.
I will now backup the Hub :)
Is this going to be an ongoing issue?

**Comment by mkellsy** [comment]
It shouldn't. It it happens again email info@hoons.org with your order number and we can replace the sd card.

**Comment by Shep084** [comment]
It’s still happening. I’m going to attempt to flash the SD card and see if that has any impact.
Question. 
- Do you think that will fix it or is the SD card corrupted and need replacing?
- If I restore from back up once I’ve flash the SD card or replace it, will that be ok or will I just restore corrupted files?
Thanks

**Comment by mkellsy** [comment]
Re-Flashing may fix this.
The backup is a different folder so it should be ok.

**Comment by Shep084** [comment]
Thanks, I’ve flashed a new SD card so we’ll see if that does the trick.
