### ISSUE TITLE
How to Reset HOOBS to factory settings 

### ISSUE THREAD

**Issue by dfowler18** [hoobs-org/HOOBS#989]
My HOOBS  crash on setu  . How to reset HOOBS to factory settings.

**Comment by mkellsy** [comment]
Click the Reset button in the Help screen

**Comment by dfowler18** [comment]
I can’t get to the help screen. I have my HOOBS connected and I can’t connect to it from my computer or iPad or iPhone. It just sits there with a orange light.

**Comment by mkellsy** [comment]
Is it connected to the network?
Check to see if it is broadcasting the HOOBS WiFi access point.
If it is connected to the network, you can get the IP address from your router, and access the UI from http://[ip address].
If the UI is not up you can ssh into the OS `ssh hoobs@[ip address]` the password is hoobsadmin.

if you have to ssh into it you can reset the HOOBS by deleting the ~/.hoobs folder

```
rm -fR ~/.hoobs
```

Then reboot.

**Comment by dfowler18** [comment]
First let me say "mkellsy" thanks for your assistance, but I must say I am a novice to this network stuff.  I can't see Hoobs on my list of networks.  When I first connected it to my router it did appear in my network list and I tried to enter the iD and Pswd, but I guess it did not take it, and the screen went a way.  Since then it won't show up in my network list.  I have tried different commands I have received but I get no response or Server not found messages.  That is why I wanted to try and set it back to factory settings.  Any ideas?

**Comment by mkellsy** [comment]
If you entered in your wifi wrong, it will still broadcast the HOOBS wifi. Otherwise it's connected.

You can open your browser and go to http://hoobs.local to continue the setup.

Without access to the device you can't reset it.
If it is not connecting, you will have to do something like changing your wifi password temporally to trigger a reconnect.

**Comment by Supermuls** [comment]
I have the same problem...

Posted on FB support page and still not solved..
[](https://www.facebook.com/groups/HOOBSorg/permalink/2848252958791028/)
