### ISSUE TITLE
Check User Mode Files Before JSON Parse

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#99]
<img width="1159" alt="Screenshot 2019-08-29 at 21 52 56" src="https://user-images.githubusercontent.com/50763727/63971711-74d55d00-caa7-11e9-9086-10327f0e14e9.png">
<img width="567" alt="Screenshot 2019-08-29 at 21 53 55" src="https://user-images.githubusercontent.com/50763727/63971743-86b70000-caa7-11e9-90bd-b8dfdd40cc8f.png">

**Comment by mkellsy** [comment]
Can you post the results of this
cat /var/lib/hombridge/config.json

**Comment by BobbySlope** [comment]
<img width="480" alt="Screenshot 2019-08-29 at 21 59 01" src="https://user-images.githubusercontent.com/50763727/63972073-3db37b80-caa8-11e9-9643-395366c34295.png">

**Comment by mkellsy** [comment]
I missed the e
cat /var/lib/homebridge/config.json

**Comment by BobbySlope** [comment]
hoobs@hoobs:~ $ cat /var/lib/homebridge/config.json
{
    "bridge": {
        "name": "HOOBS",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "amber",
	    "sudo": true,
	    "standalone": true,
	    "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
	    "temp": "/sys/class/thermal/thermal_zone0/temp",
	    "log": {
                "method": "custom",
		"command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"
        }
    ]
}
hoobs@hoo

**Comment by mkellsy** [comment]
Fixed in 3.0.0-beta.33
