### ISSUE TITLE
No Response from the HOOBS

### ISSUE THREAD

**Issue by dfowler18** [hoobs-org/HOOBS#990]
I plugged in my HOOBS and I did eventually get a log in screen, but I get nothing since.  I have had my box connected to my router and tried via wireless network and it does nothing. I tried connecting via my browser and get a message saying not found. Can someone tell me how to reset the box?  I am new to this and don't know where to turn.

**Comment by askovi** [comment]
Can you please check if the HOOBS Box has network connectivity? While connected via the ethernet cable to your router, look for amber and green light activity on the HOOBS Box ethernet port. If there is light activity, go to your router's admin page or app and look in the devices list for HOOBS. It will have a local ip address associated with it. Try to connect to it like this: http://192.168.x.x (replace with actual ip address).
