### ISSUE TITLE
shelly hoobs plugin with apple

### ISSUE THREAD

**Issue by tivo65** [hoobs-org/HOOBS#991]
**Description**
from the apple home app the light connected to a shelly 1pm can be turned on, but it won't turn off from the apple home app.  the light works as expected when controlling from the shelly app on iphone.  light also functions correctly using the light switch.  this is a light on a 120v 15amp circuit 

**Plugin name**
using shelly 0.16.0 on hoobs published 11/27/20

**Version**
hoobs 3.31
shelly plugin on hoobs 0.16.0 published 11/27/20
firmware on shelly 1 PM - 20201228-0930009/v1.9.3 

**Did you upgrade**
i upgraded to this firmware version on shelly 1PM yesterday, i did not notice this problem before the upgrade.

**What device are you using?**
Please let us know the device you are running HOOBS on.
i have hoobs running on raspberry pi raspian 5.4.79-v7l+

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

**Comment by askovi** [comment]
Please see here for a description of the problem and the troubleshooting and solutions depending on your networking equipment: https://github.com/alexryd/homebridge-shelly/wiki/Shelly,-CoAP-and-multicast#devices-can-be-turned-on-but-not-off

**Comment by tivo65** [comment]
Thank you for that link.  That helps me narrow in on the problem.  I have Unifi AP-Pro's in my network with a separate SSID for all automation devices (like the shelly 1pm) and hoobs is running hardwired ethernet (not wifi) on the same layer 2 network.  i have a pfsense router/FW but in this scenario all the traffic is inside the FW.  anyone with suggestions/experience on the setting changes in Unifi to address/solve this problem?

**Comment by apartmedia** [comment]
May be you get some useful hints from one of the last comments from this:
https://github.com/alexryd/homebridge-shelly/issues/199
