### ISSUE TITLE
Avahi-daemon Cannot Reload Because It Is Inactive

### ISSUE THREAD

**Issue by billfulton1026** [hoobs-org/HOOBS#992]
Hi all, I went to reinstall Hoobs and reflashed the SD card. I was able to join WiFi but the only way to access Hoobs was to use the IP address. The Hoobs.local worked before I reflashed.

I used SSH into the PI (had to use hoobs@192.168.1.xxx). I could see the Avahi daemon was not running using the ps -A | grep avah command. Rebooting did not help.

When I tried to check the status using sudo systemctl status avahi-daemon, I got this below.

hoobs@hoobs:~ $ sudo systemctl status avahi-daemon
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2020-12-29 14:14:27 MST; 4min 22s ago
  Process: 395 ExecStart=/usr/sbin/avahi-daemon -s (code=exited, status=0/SUCCESS)
 Main PID: 395 (code=exited, status=0/SUCCESS)
   Status: "avahi-daemon 0.7 starting up."

Dec 29 14:14:26 hoobs avahi-daemon[395]: New relevant interface wlan0.IPv4 for mDNS.
Dec 29 14:14:26 hoobs avahi-daemon[395]: Registering new address record for 192.168.1.246 on wlan0.IPv4.
Dec 29 14:14:27 hoobs avahi-daemon[395]: Got SIGTERM, quitting.
Dec 29 14:14:27 hoobs avahi-daemon[395]: Leaving mDNS multicast group on interface wlan0.IPv6 with address fe80::a51c:f86c:7cdf:116b.
Dec 29 14:14:27 hoobs avahi-daemon[395]: Leaving mDNS multicast group on interface wlan0.IPv4 with address 192.168.1.246.
Dec 29 14:14:27 hoobs avahi-daemon[395]: avahi-daemon 0.7 exiting.
Dec 29 14:14:27 hoobs systemd[1]: Stopping Avahi mDNS/DNS-SD Stack...
Dec 29 14:14:27 hoobs systemd[1]: avahi-daemon.service: Succeeded.
Dec 29 14:14:27 hoobs systemd[1]: Stopped Avahi mDNS/DNS-SD Stack.
Dec 29 14:17:15 hoobs systemd[1]: avahi-daemon.service: Unit cannot be reloaded because it is inactive.

The only thing I could do to get it to work was to uninstall the daemon (sudo apt remove avahi-daemon) then reinstall it (sudo apt-get install libnss-mdns) and everything works great until I reboot the machine. Then the same thing as above happens and I need to go through the uninstall/reinstall process.

Any idea what is causing the SIGTERM? Is it a name conflict from the machine before I reflashed it?

Thanks for the help.

**Comment by mkellsy** [comment]
The command is
```
sudo systemctl restart avahi-daemon.service
```

You may need to restart the socket too
```
sudo systemctl status avahi-daemon.socket
```

We don't modify this, you may need to troubleshoot any further issues here.
https://www.avahi.org/

**Comment by billfulton1026** [comment]
Thanks for the comments

**Comment by askovi** [comment]
Make sure to reserve the local ip address assigned to HOOBS by your router. If the ip changes, it could result in hoobs.local being inaccessible because the browser caches the DNS. You could test in another browser or in a private browsing session.
