### ISSUE TITLE
HOOBS in a box not booting

### ISSUE THREAD

**Issue by Queue212** [hoobs-org/HOOBS#995]
**Description**

I just got a new HOOBS in a box and it appears not to be booting. All I get when I plug it in is a red LED light. Nothing on the Ethernet (no communication lights) and no WiFi signal. Please help as I was looking forward to adding this device to my home automation.

**Version**
HOOBS in a box - unknown software version, won’t boot. 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Is it broadcasting the HOOBS wifi?
Use your phone and connect to the HOOBS wifi.
A screen will show on your phone and you can connect it to your wifi.

**Comment by Queue212** [comment]
Thank you for your response. No it not broadcasting the HOOBS WiFi either.

**Comment by mkellsy** [comment]
You have 2 options. Re-flasing the SD Carrd. The images are here https://github.com/hoobs-org/HOOBS/releases/tag/v3.3.1 (this will require you to open the case and pull the sd card out)

Or send an email to info@hoobs.org with your email and the issue. We will see about replacing it.

**Comment by Queue212** [comment]
Is there a way to know it is a SD card issue and not the board itself? I can go thru the process of flashing the SD card. I will try that first and report back. 

Than you again. 
Quentin

**Comment by mkellsy** [comment]
You can connect a monitor to the HDMI port and see if there's any errors in dmesg. If there is, it's probably sd card corruption.

**Comment by Queue212** [comment]
I tried to reinstall the software onto the Micro SD card that came with the box but it looks like the Micro SD card was bad. I got another Micro SD card installed the software and the system booted. It is now up and running. I got it connected to my Home. Now looking to install my first plug in. I will send a message to the email about the bad card. Thank you again for your help.
