### ISSUE TITLE
No longer able to access my Hoobs

### ISSUE THREAD

**Issue by sergiom38** [hoobs-org/HOOBS#996]
**Description**
I bought a Hoobs box and everything was ok until yesterday. I’m no longer able to access it through wifi or rj45 cable (both lights are on and the green one is blinking).I also tried to connect via the ip address without success. I’m lost and desesperated.

**Version**
It was the last one (automatic update done)

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Only Freebox Delta and Broadlink RM ones

**Post your config**
Can’t access it :-(((

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by sergiom38** [comment]
In addition, before facing this issue, I typed the following command as explain in the Broadlink plugin documentation:
sudo setcap cap_net_raw+ep /path/to/node

I assume my issue is linked to it but don't know how to rolleback to the previous configuration as I have no longer access to the Hoobs UI

**Comment by askovi** [comment]
Please retrieve and post your HOOBS Logs via ssh using the instruction below:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: `ssh hoobs@hoobs.local`

Type yes to accept the certificate key then press enter. When prompted for password, type `hoobsadmin`

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this command: `sudo hoobs service log`

**Comment by sergiom38** [comment]
Hello,

thanks for your answer.
I was able to connect to my Hoobs using ssh as suggested but after typing the "sudo hoobs service log" command I'm a error message repeating without ending:
![unnamed](https://user-images.githubusercontent.com/76838387/103537942-9dd4e180-4e95-11eb-9925-c23420f272b9.png)

**Comment by askovi** [comment]
ok log back into ssh and run this command to fix it:

`sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node`

**Comment by sergiom38** [comment]
A great thank for your efficient support. Everything is back to normal. I'm able to access my Hobbs UI.
Thanks again
Serge

**Comment by sergiom38** [comment]
A great thank for your efficient support. Everything is back to normal. I'm
able to access my Hobbs UI.

I was facing this issue trying to use my Broadlink RM4 Pro with my Hoobs.
It worked fine learning IR but not for RF. Do you know what the reason
could be and which plugin should I use with a Broadlink RM 4 Pro?

Thanks again for your support.
Have a good day
Serge

Le lun. 4 janv. 2021 à 20:32, Ovidiu Mija <notifications@github.com> a
écrit :
