### ISSUE TITLE
Hoobs Shutting Down

### ISSUE THREAD

**Issue by SrNaranja** [hoobs-org/HOOBS#998]
**Description**

The system suddently shut down. Eveything works nicely until some hours the system shuts down.

**Version**

HOOBS Core
Current Version: 3.3.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.

 No

**Pervious version**

No

**What device are you using?**
Please let us know the device you are running HOOBS on.

 Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using.

Win 10 and installed on a Raspberry 4 4gbRAM

**List your plugins**
Broadlink Platform Outlet
LG webOS Tv

**Post your config**

This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": xxxxxx
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "es",
        "temp_units": "celsius",
        "country_code": "ES",
        "postal_code": "xxxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": xxxx
        "pin": "xxxxx
        "username": "xxxx
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "broadlinkPlatformOutlet",
            "plugin_map": {
                "plugin_name": "homebridge-broadlink-platform-outlet"
            },
            "accessories": [
                {
                    "name": "Aux Cuarto",
                    "type": "SP",
                    "ip": "192.168.1.63"
                },
                {
                    "name": "Sonido",
                    "type": "SP",
                    "ip": "192.168.1.53"
                },
                {
                    "name": "Lámpara Pie",
                    "type": "SP",
                    "ip": "192.168.1.54"
                },
                {
                    "name": "Led Techo ",
                    "type": "SP",
                    "ip": "192.168.1.52"
                },
                {
                    "name": "Luz sofá",
                    "type": "SP",
                    "ip": "192.168.1.55"
                },
                {
                    "name": "Neon",
                    "type": "SP",
                    "ip": "192.168.1.56"
                }
            ]
        },
        {
            "platform": "webostv",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv"
            },
            "devices": [
                {
                    "name": "webOS TV",
                    "ip": "192.xxxx",
                    "mac": "30:axxxxb",
                    "pollingInterval": 10,
                    "volumeControl": "slider",
                    "channelControl": false,
                    "mediaControl": false,
                    "appButtons": [
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "Live TV"
                        },
                        {
                            "appId": "com.webos.app.netflix",
                            "name": "Netflix"
                        },
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "YouTube"
                        }
                    ],
                    "notificationButtons": [
                        {
                            "message": "^xxxxxxxxxxx",
                            "name": "Prueba de Mensaje"
                        }
                    ],
                    "soundOutputButtons": [
                        "tv_speaker",
                        "headphone"
                    ]
                }
            ]
        }
    ]
}
```

**Post your log**
1/2021 14:33:25 [webostv] [webOS TV] Channel changed. Current channel: 10, Cuatro HD, channelId: 1_25_10_0_16_191_8916
1/1/2021 14:33:25 [webostv] [webOS TV] Channel changed. Current channel: 9, Telecinco HD, channelId: 1_25_9_0_16_190_8916
1/1/2021 14:33:26 [webostv] [webOS TV] Channel changed. Current channel: 23, antena3 HD, channelId: 1_34_23_0_15_149_8916
1/1/2021 14:33:27 [webostv] [webOS TV] Channel changed. Current channel: 25, laSexta HD, channelId: 1_34_25_0_15_151_8916
1/1/2021 14:49:03 Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
    at Object.final (<anonymous>)
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/broadlinkjs-sm/index.js:234:27)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)
1/1/2021 14:49:03 Got SIGTERM, shutting down Bridge...
1/1/2021 14:49:03 Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
    at Object.final (<anonymous>)
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/broadlinkjs-sm/index.js:234:27)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)

**Additional context**

**Comment by askovi** [comment]
The issue seems to be from the broadlink plugin you're using. Try this one instead: https://plugins.hoobs.org/plugin/homebridge-broadlink-rm

**Comment by SrNaranja** [comment]
> The issue seems to be from the broadlink plugin you're using. Try this one instead: https://plugins.hoobs.org/plugin/homebridge-broadlink-rm

Hi thanks for the reply. I had tryed that plugim with the RM´s (the IR/RF senders) but I think it does not support the SP Family (the plugs).
Now i see it have a objet called "outlet". Have you manage to use it?

thanks in advance
