### ISSUE TITLE
release 3.3.1 is incompattible with iOS 14.3

### ISSUE THREAD

**Issue by saridori** [hoobs-org/HOOBS#999]
Connection is working, Apple home can show devices and their status, but I can't control devices, in HOOBS terminal get this error

![image](https://user-images.githubusercontent.com/62716625/103445817-9990a480-4c9a-11eb-8f7f-5351f23ed5de.png)

perhaps it was incompatibles API keys

**Comment by mkellsy** [comment]
This is an eWeLink issue. It looks like the plugin is having issues connecting to eWeLink. Check your config.

**Comment by saridori** [comment]
> This is an eWeLink issue. It looks like the plugin is having issues connecting to eWeLink. Check your config.

Thank's for answering, authorization was with email, in new wersion HOOBS is doing that with phone number, I had edited it in config files, it devices it get list of my devices, I think auth. was successed but it dosn't wotk (

**Comment by bwp91** [comment]
It looks like you are using the `homebridge-ewelink-max` plugin?

Try using `homebridge-ewelink`.

And the config is slightly different so do use the user interface to configure the plugin properly!

**Comment by saridori** [comment]
> It looks like you are using the `homebridge-ewelink-max` plugin?
> 
> Try using `homebridge-ewelink`.
> 
> And the config is slightly different so do use the user interface to configure the plugin properly!

Thanks, it was a  `homebridge-ewelink-max`, `homebridge-ewelink` is working as well )

**Comment by bwp91** [comment]
Ah good glad it’s working!
i’d like to suggest that you closed the issue if all is in order!
